### ISSUE TITLE
bug: ion-datetime is broken/fails when the current value is not defined, the min value is in the future  and time format is 12-hour

### ISSUE THREAD

**Issue by ryaa** [ionic-team/ionic-framework#25296] opened 2022-05-17 04:52 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

Datetime control show empty time popover and when it is dismissed an error occurs which makes ion-datetime unusable.
Note that the value provided to the control is null and the min property must be in the future. If the min property is in the past then everything works fine.

### Expected Behavior

Time part needs to be displayed correctly and no error when it is dismissed/closed

### Steps to Reproduce

1) open this link https://ionic6-angular13-qkrphu.stackblitz.io/
2) tap on the button
3) tap on the time control
Note that the popover opened is empty - see below
![Screen Shot 2022-05-17 at 07 41 21](https://user-images.githubusercontent.com/3608222/168731363-f4d74f0b-ca70-45a5-a07e-1aaadaa414ad.png)
4) tap outside of the popover to dismiss it
Note that an error is triggered/thrown - see below
![Screen Shot 2022-05-17 at 07 41 38](https://user-images.githubusercontent.com/3608222/168731410-fd53b5db-b304-4171-a0e7-8b59b33f6b92.png)

You can also see the problem here https://stackblitz.com/edit/ionic6-angular13-qkrphu?file=src%2Fapp%2Fapp.component.ts

### Code Reproduction URL

https://stackblitz.com/edit/ionic6-angular13-qkrphu?file=src%2Fapp%2Fapp.component.ts

### Ionic Info

See https://stackblitz.com/edit/ionic6-angular13-qkrphu?file=src%2Fapp%2Fapp.component.ts

### Additional Information

This seems to be related to https://github.com/ionic-team/ionic-framework/issues/22756 which has been reported to be fixed.

**Comment by liamdebeasi** [comment] 2022-05-17 12:48
Thanks for the issue. Things seem to be working as intended here, though the UX can be improved.

In your demo, the current selected date is May 17th (today's date). However, the minimum selectable date is May 20th. This means that there are no times on May 17th that you should be able to select. As a result, no values will appear in the time picker.

We are tracking UX improvements for this in https://github.com/ionic-team/ionic-framework/issues/24881. One idea is to have the initial date always be in bounds, even if that means the initial date is not today's date.

Does this align with what you are seeing on your end?

**Comment by ryaa** [comment] 2022-05-17 14:39
> Ensuring that the pre-selected date is in range (currently being tracked in https://github.com/ionic-team/ionic-> framework/issues/24881) should resolve the following issues:

> The time picker does not have any items to select.
> An error is thrown since there are no items to select in the picker.
> Does that clarify things?

Yes. This makes sense.

There is one minor thing though. The current and the min date are on the same date but the min time is greater than the current time. The datetime control will show the below (my current time is 5:34 PM and the min time is 7PM of the same date)
![Screen Shot 2022-05-17 at 17 34 15](https://user-images.githubusercontent.com/3608222/168837774-faa6dc75-ea64-4153-b229-156b7d87fa4c.png)
However, when the user makes any changes in the time part of the component it will update the displayed time and no error is thrown.

Thank you very much for all the detailed explanations.

**Comment by liamdebeasi** [comment] 2022-05-18 13:31
> The value should be unset/null unless the user explicitly set it.

I recommend opening a separate feature request for this. The current behavior was implemented to align with the native iOS and Android date pickers, so having a separate discussion on this would help us make a more informed decision about which path to take.

> There is one more minor thing as well. The current and the min date are on the same date but the min time is greater than the current time. The datetime control will show the below (my current time is 5:34 PM and the min time is 7PM of the same date)

This is the same problem as https://github.com/ionic-team/ionic-framework/issues/24881. Ensuring that the `value` is always in bounds (or adding a `console.warn` to inform the developer) should help here.

I am going to close this in favor of #24881. You can track any progress on that thread. Thanks for all the helpful context!

**Closed by liamdebeasi** 2022-05-18 13:31 UTC
Labels: triage
