### ISSUE TITLE
feat: Wheel style picker date-time scroll days

### ISSUE THREAD

**Issue by Webrow** [ionic-team/ionic-framework#28619] opened 2023-12-01 11:24 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

![afbeelding](https://github.com/ionic-team/ionic-framework/assets/3177853/1c79a35a-4b33-447a-b27a-5c63badb3c9e)

### Describe the Use Case

When I am scrolling forward i'd assume the day would go along. Especially when selecting "start times and end times" this results in start and end times sometimes getting jumbled up. 

### Describe Preferred Solution

I expect there to be a 00:00 after the 23, which when clicked adds one day. Same goes when you are at 0000, that there is a 23 above it, click it will subtract one day.

**Comment by liamdebeasi** [comment] 2023-12-01 14:26
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/26268.

**Closed by liamdebeasi** 2023-12-01 14:26 UTC
Labels: triage
