### ISSUE TITLE
bug: Autogrow property in IonTextArea doesnt look good

### ISSUE THREAD

**Issue by andirsun** [ionic-team/ionic-framework#21242] opened 2020-05-08 01:48 UTC
# Bug Report

**Ionic version:**

[x] **5.1**

**Current behavior:**
When I initialize the value of a text area the label doesnt look good 

**Expected behavior:**
Need to auto expand if I set property autogrod = true

**Steps to reproduce:**

Set a value to textArea component

**Related code:**

```
<IonItem>
            <IonLabel position="stacked">Beneficios</IonLabel>
            <IonTextarea 
              className="inputs"
              placeholder={benefits}
              autoGrow={true}
              maxlength={400}     
              value={benefits}
              rows={6} cols={20}
              onIonChange={e => setBenefits(e.detail.value!)}>
            </IonTextarea>
 </IonItem>
```

**Other information:**

![localhost_8100_home(iPhone X)](https://user-images.githubusercontent.com/22928302/81361426-facc8d80-90a3-11ea-9724-8a9c2ea1d995.png)

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.8.0 (/Users/timugo/.nvm/versions/node/v12.16.0/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.1.0

Capacitor:

   Capacitor CLI   : 2.1.0
   @capacitor/core : 2.1.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.16.0 (/Users/timugo/.nvm/versions/node/v12.16.0/bin/node)
   npm    : 6.14.4
   OS     : macOS Mojave
```

**Comment by andirsun** [comment] 2020-05-08 16:07
@liamdebeasi 
- Clone https://github.com/andirsun/bugTextArea
- npm install
- see the IonTextArea cant see correctly

**Comment by brandyscarney** [comment] 2020-05-14 15:18
I was able to reproduce it in a Codepen *randomly* - if you keep refreshing eventually you'll see it: https://codepen.io/brandyscarney/pen/JjYabVa

**Comment by andirsun** [comment] 2020-05-14 18:33
> I was able to reproduce it in a Codepen _randomly_ - if you keep refreshing eventually you'll see it: https://codepen.io/brandyscarney/pen/JjYabVa

Yes, in the web browser the autogrow propertie works fine, but in phone view the input doesnt recognize the size of the preloaded text.

**Comment by HansKrywaa** [comment] 2020-07-17 12:24
Still appears. Any Updates to this?

**Comment by andirsun** [comment] 2020-07-17 12:40
> Still appears. Any Updates to this?

No yet :(

**Comment by man1989** [comment] 2020-08-08 05:39
I am facing the same issue, I am using ionic 6.10.2 with react. To get around this issue i had to set ```autoGrow=true``` on focus of the element

**Comment by below43** [comment] 2020-09-25 00:42
I have this issue on 5.4.16 with angular

**Comment by EinfachHans** [comment] 2020-10-09 11:14
Does someone have a Workaround? This still appears in latest version....

**Comment by andirsun** [comment] 2020-10-12 22:59
> Does someone have a Workaround? This still appears in latest version....

No interests in solve this bug I think.

**Comment by EinfachHans** [comment] 2020-10-13 06:15
Setting **min-height** seems to be a workaround

**Comment by below43** [comment] 2020-10-13 22:03
> Does someone have a Workaround? This still appears in latest version....

It's ugly but this solution is working for me for the time being... (I've disabled autoGrow attribute for the time being)

`<ion-textarea [rows]="this.autoGrow?12:2" (click)="this.autoGrow=true" etc... >`

**Comment by EinfachHans** [comment] 2020-11-09 15:19
@liamdebeasi @brandyscarney i debugged a bit:

https://github.com/ionic-team/ionic-framework/blob/907cc7b159cb569b97df013327ea4d6a4586ec64/core/src/components/textarea/textarea.tsx#L224

`nativeInput.scrollHeight` is 0 if this bug happens. For me it happens in a Modal, seems to be the problem here in this Issue too if i look at the attached image. Maybe this is related to #22449 - there a property also could be zero (if the containing element is hidden). I think this cause problems in some more components if used in a modal or other can-be-hidden-elements 🤔

**Comment by barrcodes** [comment] 2020-11-12 17:36
In `ngOnInit` if I do the following, it will show properly. This is a horrible hack, but it may help some folks:

```
ngOnInit() {
  setTimeout(() => {
    this.applyValues();
  }, 300);
}

applyValues() {
  this.formGroup.patchValue({ content: this.textEntry.content });
}
```

**Comment by EinfachHans** [comment] 2020-11-24 08:56
Seems like something has changed here, as this now happens every time for me in our app. I was able to create a repo where it also happens every time, so it should be easier to reproduce it now. Please investigate into this as it now happens always. @liamdebeasi @brandyscarney 

Maybe my comment two above this one helps you.

Repo where it happens every time: https://github.com/EinfachHans/ionic-textarea-autogrow

Screen Recording:
![Bildschirmaufnahme-2020-11-24-um-09 51 25](https://user-images.githubusercontent.com/20899975/100071327-34e05f80-2e3b-11eb-91b8-49f55cf8abc6.gif)

**Comment by EinfachHans** [comment] 2020-11-25 11:28
# Working Workaround
Until this is fixed, you can use this as a good Workaround:

define in **global.scss**:
```
ion-textarea[ng-reflect-auto-grow=true] {
  // see: https://github.com/ionic-team/ionic-framework/issues/21242
  textarea {
    min-height: 66px;
  }
}
```

Of course you can adjust the value, 66px fits perfect for my case 😊

**Comment by ivanov84** [comment] 2020-12-04 15:51
@EinfachHans for my [issue](https://github.com/ionic-team/ionic-framework/issues/22584) this does not work...

**Comment by rdlabo** [comment] 2020-12-07 02:23
> # Working Workaround
> Until this is fixed, you can use this as a good Workaround:
> 
> define in **global.scss**:
> 
> ```
> .some-class {
>   // see: https://github.com/ionic-team/ionic-framework/issues/21242
>   textarea {
>     min-height: 66px;
>   }
> }
> ```
> 
> Of course you can adjust the value, 66px fits perfect for my case 😊 Then you need to add this class to every textarea 😕

This is good idea. may be able to simple:

```
ion-textarea[ng-reflect-auto-grow=true] {
  textarea {
    min-height: 66px;
  }
}
```

**Comment by EinfachHans** [comment] 2020-12-07 10:01
@rdlabo this will not work in production, as the ng reflect attributes aren't available then

**Comment by rdlabo** [comment] 2020-12-07 10:06
@EinfachHans Oh, thanks tell me. Today, I changed these:

```html
<ng-container *ngIf="isReady">
   <ion-textarea [(ngModel)]="..." [autoGrow]="true">
</ng-container>
```

```ts
ionViewDidEnter {
  this.ready = true;
}
```
 
This work well. thanks.

**Comment by ivanov84** [comment] 2020-12-07 21:08
@EinfachHans @rdlabo could you help to find work around for my case #22584:

```
<ion-item>
  <ion-label position="stacked" color="primary">kuku kuku ku ku kuku kuku</ion-label>
  <ion-textarea autoGrow="true" rows="3" [placeholder]="textPlaceholder"></ion-textarea>
</ion-item>
```

**Comment by ivanov84** [comment] 2020-12-13 09:29
@liamdebeasi Maybe I can help somehow to solve my issue #22584? Could you direct me where in ionic code there are an autogrow part with code?

**Comment by liamdebeasi** [comment] 2020-12-16 14:50
> @liamdebeasi Maybe I can help somehow to solve my issue #22584? Could you direct me where in ionic code there are an autogrow part with code?

The autogrow code is here: https://github.com/ionic-team/ionic-framework/blob/master/core/src/components/textarea/textarea.tsx#L224-L235. We might want to reference https://css-tricks.com/the-cleanest-trick-for-autogrowing-textareas/ to see if there is anything we can adapt. The examples in that article seem to work pretty well.

**Comment by ocarreterom** [comment] 2020-12-16 19:56
I made an example with `<IonModal>`. It only works the first time it is open.
https://codesandbox.io/s/focused-einstein-y2o4q?file=/src/App.js

**Comment by ivanov84** [comment] 2020-12-18 13:31
@liamdebeasi Thank you. I tried to understand the reason of this bug but I did't get it.

Btw I created a codepen example with this BUG demonstration - please enter any symbol in textarea and look that happens in emulator. And try to delete symbol - please look again. I would like to explane that this 'bouncing' thing started to show in all my apps in all pages where textarea is placed.

[https://codepen.io/ivanov-developer/pen/wvzedPm](https://codepen.io/ivanov-developer/pen/wvzedPm)

**Comment by svmszcck** [comment] 2020-12-27 16:06
I was having this problem with Ionic Vue, I have renamed autoGrow as auto-grow and problem solved...

**Comment by svmszcck** [comment] 2020-12-27 21:15
> @EinfachHans Oh, thanks tell me. Today, I changed these:
> 
> ```
> <ng-container *ngIf="isReady">
>    <ion-textarea [(ngModel)]="..." [autoGrow]="true">
> </ng-container>
> ```
> 
> ```ts
> ionViewDidEnter {
>   this.ready = true;
> }
> ```
> 
> This work well. thanks.

Worked for me with Ionic Vue

**Comment by svmszcck** [comment] 2020-12-30 13:25
I have tried this approach until this bug is solved and it seems to be working:

```
  <ion-item v-if="state.loaded">
            <ion-textarea
              placeholder="Write the question answer here..."
              class="input"
              :auto-grow="true"
              rows="5"
            ></ion-textarea>
          </ion-item>
```

**Comment by manchegoP** [comment] 2021-07-06 21:03
Has there been any progress on this? I noticed this is still an issue.

**Comment by Lxstr** [comment] 2021-07-22 02:43
I noticed that the behaviour differed when you use the slot vs input attribute (demo at [https://cranky-swartz-c7bdf8.netlify.app/](https://cranky-swartz-c7bdf8.netlify.app/) and source code [https://github.com/Lxstr/ionic-issue-input](https://github.com/Lxstr/ionic-issue-input). 

So I was I was looking through the source code and noticed the difference in how the value is coded in ion-textarea vs ion-input.

ion-textarea:
<img width="365" alt="Screen Shot 2021-07-22 at 10 53 08 am" src="https://user-images.githubusercontent.com/15979196/126583176-3ad674b2-5f77-46df-b978-d481433d4f45.png">

ion-input:
<img width="490" alt="Screen Shot 2021-07-22 at 12 36 57 pm" src="https://user-images.githubusercontent.com/15979196/126583187-25b23b63-009c-428c-888f-01f162b2b680.png">

Would changing ion-textarea code to match the way ion-input does this possibly help?

**Comment by Lxstr** [comment] 2021-07-22 03:36
My current workaround in a stenciljs app is not setting autogrow or value in the component declaration but rather in the onload lifecycle method.

`  componentDidLoad() {
    if (this.editingFragment) {
      console.log(this.el.querySelector('ion-textarea'))
      this.el.querySelectorAll('ion-textarea').forEach(value => (value.autoGrow = true))
      this.el.querySelectorAll('ion-textarea')[0].value = this.myfirstvalue
      this.el.querySelectorAll('ion-textarea')[1].value = this.mysecondvalue
    }
  }`

`<ion-item>
              <ion-textarea
                // autoGrow={true}
                // value={this.myfirstvalue}
              ></ion-textarea>
</ion-item>`

**Comment by Sitronik** [comment] 2021-07-29 14:42
Hello everyone!
I have a problem and it is related to autoGrow.
In my case, I set these styles for the classes:

```css
.sc-ion-textarea-md-h {
  font-family: unset;
  margin-top: 0px;
  --padding-top: 0px;
  --padding-bottom: 0px;
  --padding-start: 0px;
}

.sc-ion-textarea-ios-h {
  font-family: unset;
  --padding-top: 0px;
  --padding-bottom: 0px;
  --padding-end: 0px;
}
```

To override the default styles as they break the my application design.
Download the example code with the bug:
https://github.com/Sitronik/ionic-vue-bug-textarea
and run the serve script after clicking on the test value you will see that the textarea will disappear as autoGrow will not set the height of the element. In my case I am using the vue v-show directive it sets the display style based on the value. I use this implementation since the editable textarea are in an element that also has a click handler, so that there is no conflict, if v-show is true, I show the textarea, otherwise just text.

@liamdebeasi I fixed this problem by two lines of code:
```js
var observer = new MutationObserver(function() {this.el.style.display != 'none' ? this.runAutoGrow() : ''}.bind(this));
observer.observe(this.el, {attributes: true, childList: true});
```
If you place this code in 
https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/textarea/textarea.tsx

At the end of the connectedCallback function, the height will be set depending on whether the element is displayed on the page or not and everything will work correctly.
Perhaps the ionic team will have another way of solving the problem, since you know your architecture better, but the essence of the problem with autoGrow in my case, I hope I could explained.

**Comment by Lxstr** [comment] 2021-08-04 03:58
@Sitronik That looks great thank you! 
@liamdebeasi would this likely be added to ionic?

**Comment by liamdebeasi** [comment] 2021-08-04 14:12
If you would like to see this code added to Ionic Framework, I recommend [creating a pull request](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-a-pull-request).

**Comment by Sitronik** [comment] 2021-08-04 16:54
> If you would like to see this code added to Ionic Framework, I recommend [creating a pull request](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-a-pull-request).

Ok, little later I will create PR

**Comment by Lxstr** [comment] 2021-08-06 05:17
New to contributing and finding an error in use case testing.

I am trying the changes out according to https://ionicframework.com/docs/contributing/how-to-contribute#preview-changes and I want to install the newly built /core into my project in place of @ionic/core.

I have tried
npm i https://github.com/Lxstr/ionic-framework/tree/main/core
npm i https://github.com/Lxstr/ionic-framework/ 
npm i github:lxstr/ionic-framework/cor 

but this gives the error Cannot read property 'spec' of undefined

Anything I'm missing here test out this new build? thanks

**Comment by liamdebeasi** [comment] 2021-08-06 13:39
Just so I am understanding properly, you want to take the built version of `@ionic/core` with your fix and test it in your project? If so, you can try the following:

1. Build core: `npm run build`
2. Link the core project: `npm link`
3. In your test project, create a symlink between the @ionic/core in your project and the @ionic/core from step 2: `npm link @ionic/core`

That _should_ do the trick, but `npm link` can be a little tricky. Let me know if it does not work and I can create a development build of Ionic that you can install using `npm install`.

**Comment by Sitronik** [comment] 2021-08-10 09:10
> If you would like to see this code added to Ionic Framework, I recommend [creating a pull request](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-a-pull-request).

Hello @liamdebeasi I created [PR](https://github.com/ionic-team/ionic-framework/pull/23734) 4 days ago. When you will have time to check. Please merge this functionality. Thank you so much 😉

**Comment by liamdebeasi** [comment] 2021-08-10 13:18
Hi there,

Thanks for making PR. No need to ping us - we are aware of the PR. We will review it when we have time in the coming days and provide feedback.

**Comment by Sitronik** [comment] 2021-08-29 08:50
> Hi there,
> 
> Thanks for making PR. No need to ping us - we are aware of the PR. We will review it when we have time in the coming days and provide feedback.

In the coming days - [PR](https://github.com/ionic-team/ionic-framework/pull/23734) created 23 days ago

Please take 5 minutes to check, there is not much code and merge this functionality, it is already needed not only for me, thanks

**Comment by liamdebeasi** [comment] 2021-08-30 13:14
Hi @Sitronik,

We are not intentionally ignoring you, but comments like this are not helpful. We are a small team in the middle of trying to finish a major release of Ionic Framework, so we are a bit behind on reviewing PRs. We will provide any feedback we have on the linked PR, thanks.

**Comment by liamdebeasi** [comment] 2022-07-27 16:02
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/24205 and a fix will be available in an upcoming release of Ionic.

**Closed by liamdebeasi** 2022-07-27 16:02 UTC
Labels: help wanted, package: core, type: bug
