### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by samueligno** [ionic-team/ionic-framework#21749] opened 2020-07-14 10:25 UTC
# Bug Report

**Ionic version:**
**5.1.2**

**Current behavior:**
The color of some icons does not change

**Expected behavior:**
The color should change

**Steps to reproduce:**
Using ionicons like this:
`<script src = "https://unpkg.com/ionicons@5.1.2/dist/ionicons.js"> </script>`

By selecting the icon
```
<ion-icon name = "chevron-back-sharp"> </ion-icon>
<ion-icon name = "chevron-forward-sharp"> </ion-icon>
```
or the icon
`<ion-icon name = "close-sharp"> </ion-icon>`  _and in my opinion many others that appear as lines._

The color, even if set correctly in css (example color: red;) does not really change the color of the icon

I tried with other icons like:
`<ion-icon name="play-sharp"></ion-icon>`
and it works perfectly, so I think it's a bug with some icons

**Other information:**

![screen](https://user-images.githubusercontent.com/18459127/87415048-e4bfd980-c5cc-11ea-85f1-83a6485d5aed.jpg)

**Comment by liamdebeasi** [comment] 2020-07-14 13:29
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. Styling the icons works fine for me: https://codepen.io/liamdebeasi/pen/pogOyNp. Due to how certain icons are constructed, you may need to style icons using SVG-specific properties such as `fill` or `stroke`.

**Closed by liamdebeasi** 2020-07-14 13:29 UTC
Labels: triage
