### ISSUE TITLE
bug: (Angular) navigation doesn't work correct in combination with double tap on tab and redirectTo in Route.

### ISSUE THREAD

**Issue by evgeniyefimov** [ionic-team/ionic-framework#23143] opened 2021-04-05 13:05 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

If you make double tap on tab which has redirectTo in his route, then navigation doesn't work in context of this tab and no router tracing. Router starts working again only if you click on another tab.

**Expected behavior:**

Router should work as usual.

**Steps to reproduce:**

There are 3 tabs in a sample application. All 3 uses shared module with shared pages.
tab 1 uses absolute navigation.
tab 2 uses relative navigation.
tab 1 and tab 2 are work fine.
tab 3 makes a redirect to child page and also works fine until you make a double tap on tab 3. Then router doesn't response until you click on 1 or 2 tab.

**Related code:**
[https://github.com/evgeniyefimov/ionic-double-tap-issue](https://github.com/evgeniyefimov/ionic-double-tap-issue)

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.12.2 (C:\Users\efimov.e\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.6.3
   @angular-devkit/build-angular : 0.1102.7
   @angular-devkit/schematics    : 11.2.7
   @angular/cli                  : 11.2.7
   @ionic/angular-toolkit        : 3.1.1

Utility:

   cordova-res                          : not installed
   native-run (update available: 1.2.2) : 1.2.1

System:

   NodeJS : v12.19.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.11
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment] 2021-04-05 13:50
Thanks for the issue. Can you provide some steps to reproduce the issue? I am not seeing the issue on my end.

**Comment by evgeniyefimov** [comment] 2021-04-05 14:27
Hi @liamdebeasi 

Make a double click on tab 3:
![Screenshot_1](https://user-images.githubusercontent.com/11611433/113584622-cc4c8f00-9633-11eb-8c69-9f67639c47a2.png)

Then click on this button:
![Screenshot_2](https://user-images.githubusercontent.com/11611433/113584714-e38b7c80-9633-11eb-9caa-7659b8efc240.png)

Without double click on tab 3 you will be redirected to "Child 2" page, with double click on tab 3 router doesn't respond.

**Comment by liamdebeasi** [comment] 2021-04-05 14:31
Thanks for the follow up. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/18845#issuecomment-737472915 (same underlying issue with relative routing).

As a temporary workaround, you can use an absolute URL (I.e. `/tabs/tab3/child-2`)

**Closed by liamdebeasi** 2021-04-05 14:31 UTC
Labels: triage
