### ISSUE TITLE
bug: Ionic doesn't work with Vite (anything except webpack)

### ISSUE THREAD

**Issue by haikyuu** [ionic-team/ionic-framework#22924] opened 2021-02-15 11:21 UTC
I'm trying to use Ionic in my app along with Vite.

But I'm getting a 404 `http://localhost:3000/node_modules/.vite/ion-app_8.entry.js?import`

You can try it out immediately here https://repl.it/@abdellah/vite-ionic-1 and here is its github repo https://github.com/haikyuu/vite-ionic

How can I use Vite with Ionic?

**Comment by remorses** [comment] 2021-02-15 11:43
This is a problem with `@stencil/core` 

It is importing dynamically some modules and vite cannot statically analyze these imports

The problem is probably here
https://github.com/ionic-team/stencil/blob/cfd5d39bad4ce2cab431595ae8c8f11d1fabb192/src/client/client-load-module.ts#L23

**Comment by remorses** [comment] 2021-02-15 14:45
Created an issue at https://github.com/ionic-team/stencil/issues/2827

**Comment by haikyuu** [comment] 2021-02-16 10:03
[It seems like Ionic is coupled to Webpack
](https://github.com/vitejs/vite/discussions/2033#discussioncomment-370871)
It doesn't seem possible to use Ionic with [Rollup](https://forum.ionicframework.com/t/bundling-ionic-4-with-rollup-js/181623), Vite or snowpack to name a few.

It's worth noting that Vite is becoming the defacto bundler for Vue projects and A lot of react projects are using it.

Workarounds exist for Snowpack but they suggest using a CDN. But this is not reasonable for building mobile apps!

**Comment by liamdebeasi** [comment] 2021-02-17 14:55
Thanks for the issue. The problem here is the fact that we rely on Stencil's lazy loading solution as noted in https://github.com/ionic-team/ionic-framework/issues/22924#issuecomment-779167963.

We have a "Custom elements" build of Ionic Framework coming soon that does not use this lazy loading which will make the framework much easier to use with Rollup, Vite, etc. Keep an eye out for an announcement regarding this!

I am going to close this issue in favor of https://github.com/ionic-team/stencil/issues/2827.

**Closed by liamdebeasi** 2021-02-17 14:55 UTC
Labels: triage

**Comment by haikyuu** [comment] 2021-02-18 15:31
That's great news. Thanks @liamdebeasi

**Comment by vvni** [comment] 2021-03-19 06:43
This issue was not resolved.

**Comment by haikyuu** [comment] 2021-03-22 19:09
Definitely! I guess this means it will be a won't fix ?!

Too bad for Ionic. Rollup and vite have a big portion of projects especially new ones. Webpack is a tool of the past.

**Comment by liamdebeasi** [comment] 2021-03-22 19:42
Hi there, as per my comment in https://github.com/ionic-team/ionic-framework/issues/22924#issuecomment-780611713 I noted that I was closing this issue in favor of https://github.com/ionic-team/stencil/issues/2827. (Our automated bot closed this out, but I reopened it because it should not have done that).

Work is already underway to support this and we will have more to share soon. Thanks!

**Comment by reslear** [comment] 2021-04-06 08:50
@liamdebeasi Hi, thank you 🙏 but is planned before 2022?

**Comment by liamdebeasi** [comment] 2021-04-06 13:55
I don't have a specific date to share, but yes we do plan on doing this before 2022.

**Comment by stewones** [comment] 2021-04-15 04:02
+1 I'm going to drop ionic support for a vue project due to this.

**Comment by stewones** [comment] 2021-04-28 18:46
seems like everyone is switching to vite, I think you guys could make this a priority and ship sooner.
