### ISSUE TITLE
bug: Ionic React's Global definitions not being registered by ESLint

### ISSUE THREAD

**Issue by haydencrain** [ionic-team/ionic-framework#26597] opened 2023-01-12 03:40 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

Re-opening https://github.com/ionic-team/ionic-framework/issues/25914

Attempting to implement an `<IonModal/>` component as described by the docs: https://ionicframework.com/docs/api/modal, and attempting to set a ref for it:
```tsx
const modal = useRef<HTMLIonModalElement>(null);
```
Using the `HTMLIonModalElement` will trigger an ESLint error
```
'HTMLIonModalElement' is not defined. eslint(no-undef)
```

### Expected Behavior

Any `HTMLFooElement` definitions created by Ionic would behave similarly to React definitions like `HTMLButtonElement`.

I've turned off the `'no-undef'` rule for now, but would be great to know if there was any way to keep it on + compatible with Ionic React :) 

### Steps to Reproduce

See attached starter app repo

1. install dependencies (so eslint and prettier will work)
```
npm install
```
2. Go to `src/pages/Tab1.tsx`, note the use of `HTMLIonModalElement` (as seen within the docs: https://ionicframework.com/docs/api/modal)

3. Run ionic app
```
ionic serve
```

4. Error is encountered
```
Compiled with problems:X

ERROR

[eslint] 
src/pages/Tab1.tsx
  Line 15:30:  'HTMLIonModalElement' is not defined  no-undef
```

### Code Reproduction URL

https://github.com/haydencrain/ionic-starter-app

### Ionic Info

```
Ionic:

   Ionic CLI       : 6.20.6 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 6.4.1

Capacitor:

   Capacitor CLI      : 4.6.1
   @capacitor/android : 4.6.1
   @capacitor/core    : 4.6.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.1

System:

   NodeJS : v18.13.0 (/Users/haydencrain/.nvm/versions/node/v18.13.0/bin/node)
   npm    : 9.2.0
   OS     : macOS
```

### Additional Information

I understand that within `.eslintrc` config you can have an option `globals` where you can register them e.g.
```tsx
globals: {
  React: 'readonly',
  ServiceWorkerGlobalScope: 'readonly',
},
```

Is there some namespace for Ionic that I could place here? e.g.
```
globals: {
  React: 'readonly',
  ServiceWorkerGlobalScope: 'readonly',
  Ionic: 'readonly',
},

**Comment by amandaejohnston** [comment] 2023-01-12 15:36
Thanks for the issue. I'm unable to access the provided repo; maybe it's set to private?

**Comment by haydencrain** [comment] 2023-01-12 23:07
Hey @amandaejohnston, apologies it was set to private >.< it should be ok now! :)

**Comment by amandaejohnston** [comment] 2023-01-19 15:54
Thank you, and apologies for the delay. I'm able to replicate the error using the provided repo, but I still need to dig into why it's happening here and not with a fresh test app. I'll let you know when I have more to share.

**Comment by thetaPC** [comment] 2023-04-21 18:39
@haydencrain I was also able to reproduce it on your repo and a fresh starter app. The issue comes from the setup of `.eslintrc.js`. 

The `not defined` error does not display when commenting out the [eslint:recommended](https://github.com/haydencrain/ionic-starter-app/blob/master/.eslintrc.js#L17).

The `not defined` error also does not display when using the exact [example](https://typescript-eslint.io/getting-started#step-2-configuration) that `@typescript-eslint/parser` provides. Notice that this example does include `eslint:recommended`.

Therefore, the issue lies in the order of the `extends`. The error is no longer displaying when moving `eslint:recommended` before `plugin:@typescript-eslint`.

```js
extends: [
  'eslint:recommended',
  'plugin:@typescript-eslint/eslint-recommended',
  'plugin:@typescript-eslint/recommended',
  'plugin:prettier/recommended',
  'plugin:react/recommended',
  'plugin:import/typescript',
  'prettier',
],
```

Please update the `.eslintrc.js`.

I'm closing this issue since it's related to eslint.

Please open a new issue when encountering issues.

**Closed by thetaPC** 2023-04-21 18:39 UTC
Labels: triage
