### ISSUE TITLE
bug: cannot print all content

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionic-framework#24173] opened 2021-11-05 16:46 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

Is is not possible to print all the content of an`ion-content` that contains more content than what's displayed on screen.

Don't know exactly which Ionic tags block the print behavior, but only a single page will be recognize as content to be printed.

### Expected Behavior

Print multiple pages for all the content.

### Steps to Reproduce

```
git clone https://github.com/peterpeterparker/print-ionic
cd print-ionic
npm ci
npm run start
open http://localhost:3333/
print
```

### Code Reproduction URL

https://github.com/peterpeterparker/print-ionic

### Ionic Info

Ionic:

   Ionic CLI : 6.17.1

Utility:

   cordova-res (update available: 0.15.3) : 0.15.1
   native-run (update available: 1.5.0)   : 1.0.0

System:

   NodeJS : v16.5.0
   npm    : 7.19.1
   OS     : macOS Big Sur

### Additional Information

Screenshot:

<img width="1229" alt="Capture d’écran 2021-11-05 à 17 44 14" src="https://user-images.githubusercontent.com/16886711/140547322-24b1bdc1-8ea2-4a65-b708-055abda367b5.png">

**Comment by liamdebeasi** [comment] 2021-11-05 17:39
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/19886.

**Closed by liamdebeasi** 2021-11-05 17:39 UTC
Labels: triage

**Comment by peterpeterparker** [comment] 2021-11-05 17:40
Thanks, upvoted the other issue.

Here's also the related stackoverflow issue: https://stackoverflow.com/questions/63178845/ionic-5-with-angular-9-how-to-print-from-desktop-not-mobile-device

**Comment by liamdebeasi** [comment] 2021-11-05 18:01
Thank you! This helps with prioritizing our tasks.
