### ISSUE TITLE
ionic6打包的realase版本无法在android12上安装，提示与操作系统不兼容 

### ISSUE THREAD

**Issue by HuangFuQuang** [ionic-team/ionic-framework#26118] opened 2022-10-13 11:34 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

我打包了一个ionic6的项目，当他在安卓9上成功运行，但是在安卓12上无法安装，会显示安装失败，Cordova-Android版本为11

### Expected Behavior

应该是能够安装吧

### Steps to Reproduce

1.打包一个ionic6 realease版本包
2.运行到安卓12操作系统上

### Ionic Info

Ionic:

   Ionic CLI                     : 6.20.3 (C:\Users\user\AppData\Roaming\nvm\v14.20.0\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.2.8
   @angular-devkit/build-angular : 14.2.3
   @angular-devkit/schematics    : 14.2.3
   @angular/cli                  : 14.2.3
   @ionic/angular-toolkit        : 6.1.0

Cordova:

   Cordova CLI       : 11.0.0
   Cordova Platforms : android 10.1.2
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 3 other plugins)

Utility:

   cordova-res                          : 0.15.4
   native-run (update available: 1.7.1) : 1.7.0

System:

   Android SDK Tools : 26.1.1 (D:\AndroidTool\AndroidSDK)
   NodeJS            : v14.20.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.14.17
   OS                : Windows 10

**Comment by liamdebeasi** [comment] 2022-10-13 13:05
Hey there,

Thanks for the report. As I understand it, you are trying to install an Ionic app on your device running Android 12 but it is showing that the installation failed. I recommend posting on the [Ionic Forum](https://forum.ionicframework.com/) as it sounds like the issue is related to your native dependencies, not Ionic Framework. I am going to close this, but let me know if you have any questions.

**Comment by HuangFuQuang** [comment] 2022-10-13 13:05
谢谢亲呐 (*＾-＾*)么么哒我已经收到啦

**Closed by liamdebeasi** 2022-10-13 13:05 UTC
Labels: triage
