### ISSUE TITLE
bug: platform is pwa returns false when pwa is in fullscreen

### ISSUE THREAD

**Issue by muuvmuuv** [ionic-team/ionic-framework#24220] opened 2021-11-15 08:48 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

Running `isPlatform("pwa")` returns `false` when a PWA is in fullscreen mode.

### Expected Behavior

Return `true`.

### Steps to Reproduce

1. Open repro
2. `pnpm i`
3. `pnpm build`
4. Add certs to keychain or similar
5. `pnpm serve`
6. Open browser and install PWA
7. Open fullscreen
8. Reload

### Code Reproduction URL

https://github.com/muuvmuuv/ionic-pwa-issue

### Ionic Info

Ionic:

   Ionic CLI : 6.18.0

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v16.13.0
   npm    : 8.1.0
   OS     : macOS Big Sur

**Comment by liamdebeasi** [comment] 2022-05-18 18:45
Thanks for the issue. I am no longer able to reproduce this behavior, so it seems to have been resolved. The isPWA check in Ionic looks for the `display-mode: standalone` media query, so it is likely that this was a bug in a browser that has since been resolved.

I am going to close this. If you are still running into problems, please open a new issue. Thanks!

**Closed by liamdebeasi** 2022-05-18 18:45 UTC
Labels: triage
