### ISSUE TITLE
bug: ion-datetime time picker doesn't work when shown via popover in Android

### ISSUE THREAD

**Issue by tetsuwanadam** [ionic-team/ionic-framework#27499] opened 2023-05-17 16:20 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

If you show ion-datetime with presentation="time" via a popover in Android, the picker often ignores the set value and shows 12:00 AM instead. In these instances it also doesn't update the value to the picked time consistently.

```
<ion-item detail="true">
	<ion-label id="time_label">Show time picker</ion-label>
</ion-item>

<ion-popover trigger="time_label">
	<!-- Picker should default to 1:15 PM when shown but it usually shows 12:00 AM instead -->
	<ion-datetime value="13:15" presentation="time" show-default-buttons></ion-datetime>
</ion-popover>
```

### Expected Behavior

The time picker should show the preset time value when it appears via the popover.

### Steps to Reproduce

1. Show ion-datetime with presentation="time" and a preset time value via a popover.

### Ionic Info

Ionic:

   Ionic CLI       : 7.1.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 7.0.6

Capacitor:

   Capacitor CLI      : 5.0.3
   @capacitor/android : 5.0.3
   @capacitor/core    : 5.0.3
   @capacitor/ios     : 5.0.3

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.2

System:

   NodeJS : v16.1.0 (/usr/local/bin/node)
   npm    : 8.19.2
   OS     : macOS Unknown

**Comment by tetsuwanadam** [comment] 2023-05-18 13:50
Here's a link to a sample app.
https://github.com/tetsuwanadam/ionic-test/blob/main/src/views/HomePage.vue

Note that it only happens on Android and randomly at that - you may have to try it a few times before the bug occurs. (It happens regularly on my Pixel 4a device as well as on a Pixel 5 emulator.)

**Comment by liamdebeasi** [comment] 2023-05-22 14:17
Thanks! This looks like a duplicate of https://github.com/ionic-team/ionic-framework/issues/26234, so I am going to merge the two threads. Note that you can work around this issue by setting `:keep-contents-mounted="true"` on the `popover.

**Closed by liamdebeasi** 2023-05-22 14:17 UTC
Labels: triage
