### ISSUE TITLE
bug: Ionic Vue - classList error when navigate backwards

### ISSUE THREAD

**Issue by dlodeprojuicer** [ionic-team/ionic-framework#22967] opened 2021-02-24 15:01 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

I get the error `Cannot read property 'classList' of undefined` when I navigate back using the browser’s back button and when I use `this.$router.go(-1);`

**Expected behavior:**

Must be able to navigate backward.

**Steps to reproduce:**

Click the arrow at the bottom, then the big purple card, when you get to Create Virtual Card screen click the back button or use the browser's back button. Dev console will show the error.

**Related code:**

[Demo](https://ionic-vue-mobile-template-08.netlify.app/)

[Github repo](https://github.com/dlodeprojuicer/ionic-vue-mobile-template-08)

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.11.8-testing.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 5.5.4

Capacitor:

   Capacitor CLI   : 2.4.2
   @capacitor/core : 2.4.2

Utility:

   cordova-res (update available: 0.15.2) : 0.15.1
   native-run                             : not installed

System:

   NodeJS : v12.18.0 (/usr/local/bin/node)
   npm    : 6.14.4
   OS     : macOS Catalina


  ───────────────────────────────────────────────────────────

     Ionic CLI update available: 6.11.8-testing.0 → 6.12.2
               Run npm i -g @ionic/cli to update

  ───────────────────────────────────────────────────────────
```

**Comment by liamdebeasi** [comment] 2021-02-24 15:47
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. You are missing an `ion-page` in `Tabs.vue` which is why you are encountering this error:

```html
<template>
  <ion-page>
    <ion-tabs>
      ...
    </ion-tabs>
  </ion-page>
</template>
```

**Closed by liamdebeasi** 2021-02-24 15:47 UTC
Labels: triage
