### ISSUE TITLE
[Ionic 4] Block whitespace appear when call keyboard.hide in ionScroll event.

### ISSUE THREAD

**Issue by leopangchan** [ionic-team/ionic-framework#17324] opened 2019-01-31 01:12 UTC
# Bug Report

**Ionic version:**
```
Ionic:

   ionic (Ionic CLI)             : 4.6.0
   Ionic Framework               : @ionic/angular 4.0.0
   @angular-devkit/build-angular : 0.12.2
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.2

Cordova:

   cordova (Cordova CLI) : not installed
   Cordova Platforms     : not available
   Cordova Plugins       : not available

System:

   Android SDK Tools : 26.1.1 (/Users/it02/Library/Android/sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 7.0.0
   NodeJS            : v10.6.0 (/usr/local/bin/node)
   npm               : 6.4.1
   OS                : macOS Mojave
   Xcode             : Xcode 10.1 Build version 10B61
```

**Current behavior:**
I'm working on a page that has a contenteditable div.  I want the keyboard to be hidden, when the user scrolls down while editing the div. To do that, I called this.keyboard.hide() in onScroll event of ion-content. The keyboard is hidden successfully, but it leaves a blank space behind for 0.5s or until the scrolling is completely finished.

**Expected behavior:**
The transition for hiding the keyboard should be smooth and no whitespace left behind.

**Steps to reproduce:**
The following images of a ionic page shows the behavior. The pink area is the contenteditable div.

***Normal state:***
<img src="https://user-images.githubusercontent.com/16515271/52023166-e5d07a00-24b0-11e9-81ee-6650394cdff9.PNG" width="230" height="400">

***When the contenteditable div is focus:***
<img src="https://user-images.githubusercontent.com/16515271/52023207-11ebfb00-24b1-11e9-85f0-7e7ff49b9b6e.PNG" width="230" height="400">

***When I scroll down while the div is still in focus:***
<img src="https://user-images.githubusercontent.com/16515271/52023216-1d3f2680-24b1-11e9-996a-a0f15f5ae593.PNG" width="230" height="400">

This image shows that there's a white blank space at the bottom of the app that takes up 30%-40% of the height.

**A sample application via GitHub:**
The HTML and TS are in home.page.html and home.page.ts on https://github.com/leopangchan/ionic-scroll-bug

**Other Info**:
I've found some related issues in ionic 1 on Google, but they involve changing ion-content to ion-scroll, which is not available in ionic 4 anymore.

**Comment by orcicareapp** [comment] 2019-10-11 14:24
I am also facing this issue in ionic 3.. Any solution???

**Comment by mattcwebster** [comment] 2019-12-25 18:45
any resolution on this, facing same issue

**Comment by pradeepsonisoni** [comment] 2020-04-02 08:09
**

Choosing IONIC is a big problem in my case.

**

**Comment by liamdebeasi** [comment] 2020-11-16 22:29
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The issue here is that the webview is getting resized when you open and close the keyboard. If you are using something like Capacitor, you can prevent this by changing the resize mode on the Keyboard plugin: https://capacitorjs.com/docs/apis/keyboard#keyboard-configuration-ios-only. For example, you could set the resize value to `none` which would turn off all webview resizing. Or you could set it to `ionic` which would cause only `ion-app` to be resized, not the entire webview. Thanks!

**Closed by liamdebeasi** 2020-11-16 22:29 UTC
Labels: needs: investigation, package: angular, package: core
