### ISSUE TITLE
bug: Number inputs throw an exception

### ISSUE THREAD

**Issue by hardmaster92** [ionic-team/ionic-framework#24786] opened 2022-02-15 07:41 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Changing the value (by user input) of an input of type `number` throws this exception:

```
DOMException: Failed to execute 'setSelectionRange' on 'HTMLInputElement': The input element's type ('number') does not support selection.
    at h.valueChanged (https://cdn.jsdelivr.net/npm/@ionic/core/dist/ionic/p-db2cac9b.entry.js:4:1924)
    at https://cdn.jsdelivr.net/npm/@ionic/core/dist/ionic/p-70d27bbc.js:4:11115
    at Array.map (<anonymous>)
    at https://cdn.jsdelivr.net/npm/@ionic/core/dist/ionic/p-70d27bbc.js:4:11098
    at h.set [as value] (https://cdn.jsdelivr.net/npm/@ionic/core/dist/ionic/p-70d27bbc.js:4:11166)
    at HTMLInputElement.onInput (https://cdn.jsdelivr.net/npm/@ionic/core/dist/ionic/p-db2cac9b.entry.js:4:841) 
```
Because of that, I can't handle form values anymore and they can't be submitted. I use Angular but I think the issue is not related to UI framework since I see it on the UI components page demo.

### Expected Behavior

An exception should not be thrown and the value change should be handled.

### Steps to Reproduce

1. Open an ionic app that uses an input of type `number` ([the official input demo has one)](https://ionicframework.com/docs/api/input)
2. Change the value of a number input by either typing in a value or using the spin buttons

### Code Reproduction URL

https://ionicframework.com/docs/api/input

### Ionic Info

Ionic:

   Ionic CLI                     : 6.18.1 (/usr/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.7
   @angular-devkit/build-angular : 13.2.3
   @angular-devkit/schematics    : 13.2.3
   @angular/cli                  : 13.2.3
   @ionic/angular-toolkit        : 6.0.0

Capacitor:

   Capacitor CLI      : 3.4.1
   @capacitor/android : not installed
   @capacitor/core    : 3.4.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v16.14.0 (/usr/bin/node)
   npm    : 6.14.16
   OS     : Linux 5.13

**Comment by indraraj26** [comment] 2022-02-15 11:54
duplicate https://github.com/ionic-team/ionic-framework/issues/24753

6.0.8 will be released on tomorrow. You can try with dev build for now which is in above link.

**Comment by liamdebeasi** [comment] 2022-02-15 13:48
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/24753.

**Closed by liamdebeasi** 2022-02-15 13:48 UTC
Labels: triage
