### ISSUE TITLE
bug: header adds cloned elements outside of root context, causing appload to get fired multiple times

### ISSUE THREAD

**Issue by EinfachHans** [ionic-team/ionic-framework#24091] opened 2021-10-18 09:13 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

We currently get many Errors (over thousand in two days) like this one in Production:

https://sentry.io/share/issue/f73db0f955c84087ae68e7ae94567495/

We don't use the `IonSlides` anymore, we already migrated to use `swiperjs` directly.

### Expected Behavior

1. understand why this is happening
2. Fix it 😃 

### Steps to Reproduce

I can not really reproduce this locally, so i guess this makes it a bit harder^^

But maybe you have an idea or something we can start with to understand this bug?

**Comment by EinfachHans** [comment] 2021-10-19 14:17
@amandaesmith3 As i said i can't reproduce this local, but this error is reported thousand of times and i bet we should be able to solve that without reproduction.

First step would be for me to understand why this is fired if i don't use slides and use swiper directly?

**Comment by amandaesmith3** [comment] 2021-10-19 15:04
It's tricky for us to identify the issue without being able to see your codebase. Could you send an example of how you're configuring your slides? I understand this is tricky to reproduce, but we can't fix an issue we are unable to reproduce on our end.

**Comment by EinfachHans** [comment] 2021-10-19 17:57
I can reproduce the multiple firing of the event already (not yet in combination with swiper) - is this enough?

**Comment by liamdebeasi** [comment] 2021-11-10 16:54
This was resolved via https://github.com/ionic-team/ionic-framework/commit/d0b61307c6b7ff1589646c43f989260b59db1473. The old Swiper 6 module has been deprecated in favor of the Swiper 7 module which does not have this issue. A fix should be available in an upcoming release of both Ionic 5 and Ionic 6. Thanks!

**Closed by liamdebeasi** 2021-11-10 16:54 UTC
Labels: package: core, type: bug
