### ISSUE TITLE
bug: click event fires twice on item-label margin when button=true

### ISSUE THREAD

**Issue by pkunszt** [ionic-team/ionic-framework#28437] opened 2023-10-31 12:41 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

I have an `ion-item` with a label and a toggle inside. It has `button=true` and the click event is set to switch the toggle's state.

But the behavior when using it is really strange
- If you click  anywhere on the item, you should be able to switch the toggle. 
- But this only works if you click in the middle (vertically) of the label, then it fires and the toggle is switched.
- If you click close to the top line or the bottom line (so on the label text margin), the click event fires TWICE as seen in the logs and the flag is not changed because it is changed back immediately

note: this works with a checkbox without a problem.

The following new-style code works correctly - but the styling is different from the previous, we get a 12px padding:
```
<ion-item [button]="true" (click)="setFlag()">
   <ion-toggle [checked]="flag" labelPlacement="start">Set Flag</ion-toggle>
</ion-item>
```

Of course i can work around the added padding to get the same styling by adding a `style="padding: 0"` but it is not nice that the behavior is different in styling.

### Expected Behavior

The expected behavior is as the new-style code behavior. wherever you click in the ion-item, you should get the event fired only once, not twice. Also, the paddings should match between old and new style.

The old style labeling is still very useful for ion-inputs where i want to have the label left of the input in a list, styled separately.

### Steps to Reproduce

Let's look at the following code

```        
<ion-item [button]="true" (click)="setFlag()">
      <ion-label>The Label</ion-label>
      <ion-toggle [checked]="flag" labelPlacement="start" aria-label="Label" slot="end"></ion-toggle>
</ion-item>
```
in the `.ts` file the method is

```
setFlag() {
  this.flag = !this.flag;
  console.log('fire', this.flag);
}
```

If you then render this in a component and click in the center of the label, all good.
But click close to the line (vertically), and you get the double fire issue. Check the console.

### Ionic Info

```
Ionic:

   Ionic CLI                     : 7.1.1 (/opt/homebrew/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.5.2
   @angular-devkit/build-angular : 16.2.8
   @angular-devkit/schematics    : 16.2.8
   @angular/cli                  : 16.2.8
   @ionic/angular-toolkit        : 9.0.0

Utility:

   cordova-res : 0.15.4
   native-run  : not installed globally

System:

   NodeJS : v18.13.0 (/opt/homebrew/Cellar/node@18/18.13.0_1/bin/node)
   npm    : 8.19.3
   OS     : macOS Unknown
```

**Comment by liamdebeasi** [comment] 2023-10-31 13:28
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. Form controls are designed to take up the entire container, so you should not need to manually add a click event to update the toggle. We added logic to `ion-item` so that clicking the padding in an item results in a click event on the toggle. Otherwise, there would be "Dead space" on one side of the item (you can actually see this in old versions of Ionic 7 since we recently shipped this improvement).

Additionally, this pattern is not something we support because it breaks accessibility tools such as screen readers. The code provided here creates a [nested interactive](https://dequeuniversity.com/rules/axe/4.4/nested-interactive) because the `ion-item` has a button, but a form control is rendered inside of the button. This anti-pattern is mentioned on the [Item documentation](https://ionicframework.com/docs/api/item#guidelines).

Here is an example of a toggle in an item where you can click anywhere on the item to update the toggle: https://codepen.io/liamdebeasi/pen/yLZJybe

**Closed by liamdebeasi** 2023-10-31 13:28 UTC
Labels: triage
