### ISSUE TITLE
bug: ion-radio styling issues on SSR

### ISSUE THREAD

**Issue by agustinhaller** [ionic-team/ionic-framework#22118] opened 2020-09-19 22:32 UTC
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
When testing SSR with javascript disabled, `<ion-radio>` rendered styles have different precedence than browser rendered styles.

For this reason SSR rendered `<ion-radio>` looks different than the browser rendered version.
In particular [these styles](https://github.com/ionic-team/ionic-framework/blob/master/core/src/components/radio/radio.md.scss#L112) take precedence over [these styles](https://github.com/ionic-team/ionic-framework/blob/94159291b27ddf1a859c8f3f87a0d6e54a8b5f13/core/src/components/item/item.md.scss#L103) causing the `margin-end` property to be 36px instead of 32px like the browser rendered version of the `<ion-radio>`

**Expected behavior:**
`<ion-radio>` gets rendered in SSR (with javascript disabled) with the same CSS properties precedence it has when rendered in the browser.

**Steps to reproduce:**

1. Enable (SSR with Angular Universal And Ionic)[https://ionicframework.com/blog/ssr-with-angular-universal-and-ionic/]
2. Create a view with `<ion-radio>` inside `<ion-item>`
3. Run `npm run dev:ssr`
4. Open Chrome dev tools and disable javascript (in order to properly test SSR)
5. Observe the `<ion-radio>` visual diff between SSR and browser rendering

**Other information:**

### SSR Ionic Form (Pixel 2)
![SSR Ionic Form (Pixel 2)](https://user-images.githubusercontent.com/597833/93690441-cedc0280-faae-11ea-9490-49ca29df04e5.png)

### Browser rendered Ionic Form (Pixel 2)
![Browser rendered Ionic Form (Pixel 2)](https://user-images.githubusercontent.com/597833/93690447-de5b4b80-faae-11ea-80d2-028283dae5e0.png)

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.11.8 (/Users/agustin/.npm-global/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.3.3
   @angular-devkit/build-angular : 0.1001.2
   @angular-devkit/schematics    : 10.1.2
   @angular/cli                  : 10.1.2
   @ionic/angular-toolkit        : 2.3.3

Capacitor:

   Capacitor CLI   : 2.4.1
   @capacitor/core : 2.4.1

Utility:

   cordova-res (update available: 0.15.1) : 0.11.0
   native-run                             : not installed

System:

   NodeJS : v12.14.1 (/usr/local/bin/node)
   npm    : 6.14.8
   OS     : macOS Catalina
```

**Comment by liamdebeasi** [comment] 2022-06-02 13:28
Thanks for the issue and apologies for the delay. In the time since this issue was opened, there have been many enhancements and fixes made to Ionic Framework that may have resolved this issue.

It is difficult for us to verify whether or not this is still an issue as no GitHub repo was provided in the original post (Code snippets are typically not enough to reproduce more complex issues). I am going to close this issue for now. If this issue is still occurring, please reply with a minimal GitHub repo that we can use to verify this behavior. At that point, we will be more than happy to reopen this issue. Thank you!

-----

For more info on how to create a good code reproduction, please see https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-a-good-code-reproduction.

**Closed by liamdebeasi** 2022-06-02 13:28 UTC
Labels: triage
