### ISSUE TITLE
bug: build breaks Ionic components

### ISSUE THREAD

**Issue by sander-spruit** [ionic-team/ionic-framework#28756] opened 2023-12-21 20:15 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Developed an angular/ionic application which serves properly and works. However, once build no errors are reported and the build succeed. However, in practice the build does not work and Ionic components are lacking functionality. No console errors are showing.

Example of incorrect output;
<img width="478" alt="Schermafbeelding 2023-12-21 204846" src="https://github.com/ionic-team/ionic-framework/assets/54065344/6c915dca-bb3d-42ae-b994-f0d5ed6414d7">

### Expected Behavior

Ionic should load properly. Example of what page should look like.

<img width="465" alt="Schermafbeelding 2023-12-21 204939" src="https://github.com/ionic-team/ionic-framework/assets/54065344/c85cd524-3a58-48ba-9c3c-6057c98d7471">

### Steps to Reproduce

1. Create a new angular project, could be i.e. the tabs demo
2. Add an Ionic element to that page i.e. a ion-input.
3. Build the project with ion build --prod
4. Upload the project to a random web server

### Code Reproduction URL

http://bit.ly/3NDCCqD (Edit from Sean: https://admin.spruit.events/#/tabs/tab1, never trust a bit.ly link)

Link is based on reproduction steps, not screenshot

### Ionic Info

Ionic:

   Ionic CLI                     : 7.1.5 (C:\Users\SanderAkkermans\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 7.6.2
   @angular-devkit/build-angular : 17.0.7
   @angular-devkit/schematics    : 17.0.7
   @angular/cli                  : 17.0.7
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.5.1
   @capacitor/android : not installed
   @capacitor/core    : 5.5.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.4

System:

   NodeJS : v20.10.0 (C:\Program Files\nodejs\node.exe)
   npm    : 10.2.3
   OS     : Windows 10

### Additional Information

Dependencies used;
```
    "@angular/animations": "^17.0.2",
    "@angular/common": "^17.0.2",
    "@angular/compiler": "^17.0.2",
    "@angular/core": "^17.0.2",
    "@angular/forms": "^17.0.2",
    "@angular/platform-browser": "^17.0.2",
    "@angular/platform-browser-dynamic": "^17.0.2",
    "@angular/router": "^17.0.2",
    "@capacitor/app": "5.0.6",
    "@capacitor/core": "5.5.1",
    "@capacitor/haptics": "5.0.6",
    "@capacitor/keyboard": "5.0.6",
    "@capacitor/status-bar": "5.0.6",
    "@ionic/angular": "^7.6.2",
    "@ngx-translate/core": "^15.0.0",
    "@ngx-translate/http-loader": "^8.0.0",
    "ionicons": "^7.2.1",
    "moment": "^2.29.4",
    "ngx-quill": "^24.0.4",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.14.2"
```

**Comment by liamdebeasi** [comment] 2023-12-21 21:27
How are you importing your components? It looks like the `ion-input` component is not being registered in the sample you provided. This makes me think that your application is importing  from `@ionic/angular/standalone` and `@ionic/angular` which developers should not do (since it causes issues like this).

**Comment by sander-spruit** [comment] 2023-12-21 22:01
That did it (although I looked into it endlessly.

Switching
`import { IonicModule } from '@ionic/angular';

@Component({
  imports: [ExploreContainerComponent, IonicModule],
})`

to
`import { IonInput, IonHeader, IonToolbar, IonTitle, IonContent } from '@ionic/angular/standalone';

@Component({
  imports: [ExploreContainerComponent, IonInput, IonHeader, IonToolbar, IonTitle, IonContent],
})`

fixes it.

Why does this not show any error reporting? And why does it work with serving?

**Comment by liamdebeasi** [comment] 2023-12-21 22:31
There is no treeshaking/dead code elimination when serving, so IonInput was likely being defined as a result of a side effect. Once you build for production, Webpack will do treeshaking and see that you aren't actually importing `IonInput` anywhere in your application and remove that code from your build.

There isn't a great way to automatically detect this when mixing imports between `@ionic/angular` and `@ionic/angular/standalone` because they are two different build systems of Ionic. As a result, we recommend developers only import from one or the other. If you are using VSCode you can add the following setting to prevent it from suggesting `@ionic/angular` imports: https://github.com/ionic-team/starters/blob/main/angular-standalone/base/.vscode/settings.json. I believe you can do something similar for JetBrains products too.

I am going to close this since the issue is resolved, but let me know if you have other questions.

**Closed by liamdebeasi** 2023-12-21 22:31 UTC
Labels: triage

**Comment by bennyvenassi** [comment] 2023-12-23 15:06
Hey there,
is this really the only solution to Import every component by its own instead of the IonicModule?
While using a lot components this isn't really pretty.
e.g. my imports for a simple Page: 
import { IonInput, IonHeader, IonToolbar, IonTitle, IonContent, IonLabel, IonGrid, IonCard, IonSpinner, IonRow, IonCol, IonCardTitle, IonCardContent, IonText, IonItem, IonButton } from '@ionic/angular/standalone';

imports: [CommonModule, FormsModule, ReactiveFormsModule, IonInput, IonHeader, IonToolbar, IonTitle, IonContent, IonLabel, IonGrid, IonCard, IonSpinner, IonRow, IonCol, IonCardTitle, IonCardContent, IonText, IonItem, IonButton]

**Comment by liamdebeasi** [comment] 2024-01-02 17:41
Yes, this is the recommended solution. You can optionally define import groups to import related components to help cut down on the number of separate imports:

**import-group.ts**
``` js
import { IonCard, IonCardContent, IonCardTitle } from '@ionic/angular/standalone';
export const CARD_COMPONENTS = [IonCard, IonCardContent, IonCardTitle];
```

**home.component.ts**
```js
import { CARD_COMPONENTS } from '../import-group.ts';

...

imports: [...CARD_COMPONENTS]
```
