### ISSUE TITLE
bug: Title cut off different font

### ISSUE THREAD

**Issue by danielehrhardt** [ionic-team/ionic-framework#22478] opened 2020-11-11 17:20 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
I am using a custom font in my App. (Google Sans) 
![image](https://user-images.githubusercontent.com/19570043/98842686-3a58a580-244a-11eb-853f-971105e8b403.png)
The Title gets cut off. 
![image](https://user-images.githubusercontent.com/19570043/98842776-578d7400-244a-11eb-8cbb-9e4f731b8870.png)

**Expected behavior:**
The Title should not cut off

**Steps to reproduce:**
Add google Sans to the Ionic App and create a iOS Header

**Related code:**
```
<ion-header [translucent]="true">
  <ion-toolbar>
    <ion-title>Profil</ion-title>
  </ion-toolbar>
</ion-header>

<ion-content [fullscreen]="true">
  <ion-header collapse="condense">
    <ion-toolbar>
      <ion-title size="large">Profil</ion-title>
    </ion-toolbar>
  </ion-header>
```

**Comment by liamdebeasi** [comment] 2020-11-11 20:29
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The reason that this is happening is the custom font you are using has a line height that is larger than the height of the toolbar. Since `ion-title` inherits the height of the toolbar (44px), your font is getting cut off.

Our components focus on working with the system fonts, but developers can either a) change the height of the toolbar (not recommended) or b) change the line height of `ion-title` to account for the taller letters.

**Closed by liamdebeasi** 2020-11-11 20:29 UTC
Labels: triage

**Comment by danielehrhardt** [comment] 2020-11-11 22:24
> Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The reason that this is happening is the custom font you are using has a line height that is larger than the height of the toolbar. Since `ion-title` inherits the height of the toolbar (44px), your font is getting cut off.
> 
> Our components focus on working with the system fonts, but developers can either a) change the height of the toolbar (not recommended) or b) change the line height of `ion-title` to account for the taller letters.

Thank you :)
