### ISSUE TITLE
bug: SetupConfig does not work with Ionic React (v6)

### ISSUE THREAD

**Issue by BerkeAras** [ionic-team/ionic-framework#24139] opened 2021-11-01 11:02 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Ionic setupConfig does not work with React. Just no behavior, no response, no error.

### Expected Behavior

SetupConfig should override the existing default configuration.

### Steps to Reproduce

Create new ionic react app, update to Ionic v6 [(how can I update to the beta?)](https://github.com/ionic-team/ionic-framework/blob/next/BETA.md), try setupConfig.

### Additional Information

Code Example:

```js
import { useEffect } from 'react';
import { Capacitor } from '@capacitor/core';
import { Keyboard } from '@capacitor/keyboard';
import { IonApp, IonRouterOutlet, IonSplitPane, setupConfig } from '@ionic/react';
import { IonReactRouter } from '@ionic/react-router';
import { Redirect, Route } from 'react-router-dom';

/* Core CSS required for Ionic components to work properly */
import '@ionic/react/css/core.css';

/* Basic CSS for apps built with Ionic */
import '@ionic/react/css/normalize.css';
import '@ionic/react/css/structure.css';
import '@ionic/react/css/typography.css';

/* Optional CSS utils that can be commented out */
import '@ionic/react/css/padding.css';
import '@ionic/react/css/float-elements.css';
import '@ionic/react/css/text-alignment.css';
import '@ionic/react/css/text-transformation.css';
import '@ionic/react/css/flex-utils.css';
import '@ionic/react/css/display.css';


/* Theme variables */
import './theme/variables.scss';

/* Pages */
import PageHome from './pages/default/Home/Home';

setupConfig({ mode: 'md' });

const App = () => {
.........
```

**Comment by amandaesmith3** [comment] 2021-11-02 15:57
Thanks for the report; confirming I can replicate 👍 I'm indeed only seeing this with React (not Angular or Vue) and confirmed that `setupConfig` itself isn't working, rather than it being any particular property.

It looks like the issue is here: https://github.com/ionic-team/ionic-framework/blob/next/core/src/utils/config.ts#L206 The check is always returning, as `Ionic.config` is defined and `Ionic.config.constructor.name` is `'Config'`.

**Comment by liamdebeasi** [comment] 2021-11-22 20:32
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/24254, and a fix will be available in an upcoming release of Ionic Framework.

In order to make this change we unfortunately had to make a small breaking change due to how the new custom elements build works. In Ionic 6, developers will need to import and call the `setupIonicReact` function exported from `@ionic/react`. This function is used in place of `setupConfig`, but should be called by all developers even if they are not setting a custom config.

This is noted in the breaking changes guide: https://github.com/ionic-team/ionic-framework/blob/next/BREAKING.md#config-2

We will make sure to note this when the Ionic 6 migration guide goes live. The `setupIonicReact` function will be available in an upcoming release of Ionic 6. Thank you!

**Closed by liamdebeasi** 2021-11-22 20:32 UTC
Labels: package: core, type: bug, v6
