### ISSUE TITLE
bug: [V7.5] Labels do not follow the ng-invalid state with reactive form

### ISSUE THREAD

**Issue by petrot** [ionic-team/ionic-framework#28579] opened 2023-11-27 11:47 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

We have a complex reactive form with custom validation. When we select an option for an "A" field, an another "B" ("C", "D"....) field will be required. With the current Ionic version, the ion-select doesn't get the ion-invalid state (but the field has an ng-invalid class - so the core validation works).

We have a fix for this issue, the problem is that the field is untouched, so we have to call the "markAllAsTouched" method, but I think it should be unnecessary.

### Expected Behavior

Show the invalid highlight without calling the "touch" method programmatically.

### Steps to Reproduce

We have a small demo:

https://stackblitz.com/edit/angular-3kbqb5-13rjnz?devToolsHeight=33&file=src%2Fapp%2Fexample.component.ts

Without the fix:

1) Choose a required field in the 1st select (e.g "Fruit")
2) The 2nd select (the fruit field) became required, but the label doesn't show the highlight

If you check the inspector, the ion-select for the "Fruit" item has "ion-valid" and "ng-invalid" classes. After you click to the select and you click the Cancel on the popup, it gets the "ng-touched" and the "ion-invalid" classes.

With the fix:

0) Uncomment lines 59-60. (markAllAsTouched() lines)
1) Choose a required field in the 1st select (e.g "Fruit")
2) The 2nd select (the fruit field) became required, and the label shows the red hlighlight

### Ionic Info

Ionic:

   Ionic CLI                     : 7.1.5
   Ionic Framework               : @ionic/angular 7.5.4
   @angular-devkit/build-angular : 16.2.10
   @angular-devkit/schematics    : 16.2.10
   @angular/cli                  : 16.2.10
   @ionic/angular-toolkit        : 7.0.0

Capacitor:

   Capacitor CLI      : 5.5.1
   @capacitor/android : 5.5.1
   @capacitor/core    : 5.5.1
   @capacitor/ios     : 5.5.1

Utility:

   cordova-res                          : 0.15.4
   native-run (update available: 2.0.0) : 1.7.4

System:

   NodeJS : v16.17.0  
   npm    : 8.15.0
   OS     : macOS Unknown

**Comment by liamdebeasi** [comment] 2023-11-27 14:56
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. This behavior is by design. Showing the red/invalid state only when `ion-invalid` is set causes fields to show up as invalid when the view is presented for the first time (since the fields have not been touched yet). This is confusing for users because they have not interacted with the field yet, so it's not immediately clear why there is an error on the page.

Instead, we only show the invalid state once the user has interacted with the control so it's clear the red/invalid state is being shown in response to their actions on the form control in question.

While you can use the `markAllAsTouched` workaround, it might be better to only show either the Fruit or Vegetable select once an option from `Choose a required item` has been selected. There may be other changes to the UI you can make such as adding a red asterisk to the Fruit/Vegetable label so it's more clear to the user that the field is required.

**Closed by liamdebeasi** 2023-11-27 14:56 UTC
Labels: triage

**Comment by petrot** [comment] 2023-11-27 15:40
@liamdebeasi thanks for the detailed answer and your hard work!

**Comment by setter-clgx** [comment] 2023-11-27 15:52
@liamdebeasi,  to make sure i understand what you are saying, if any form field sets or unsets validation on another form field the subsequent field needs to be focused (either manually by the user or manually via code) to register the validation change?

**Comment by liamdebeasi** [comment] 2023-11-27 17:09
> to make sure i understand what you are saying, if any form field sets or unsets validation on another form field the subsequent field needs to be focused (either manually by the user or manually via code) to trigger the UI style validation change?

The field that had its validation state changed needs to be marked as touched, not focused. Focusing will change the visual state of the component whereas marking it as touched is a form validation-specific behavior.
