### ISSUE TITLE
bug: IonContent always display an unexpected y-axis scroll bar (ionic6/React)

### ISSUE THREAD

**Issue by immortalt** [ionic-team/ionic-framework#25840] opened 2022-08-27 01:32 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

When the style is IOS, the <main> in IonContent component in a Tab App would display an unexpected y-axis scroll bar, and the content inside the IonContent can be scroll up or down a little, maybe 1 or 2 px.
![image](https://user-images.githubusercontent.com/17811951/187008756-a64178d4-9aac-4e62-922f-73b19a4cf02f.png)
But this problem would be fixed if the style is MD,
![image](https://user-images.githubusercontent.com/17811951/187008819-663ddc0f-2aa5-4d81-a67f-afbea3264927.png)
or modify this part of css: https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/content/content.scss
![image](https://user-images.githubusercontent.com/17811951/187008810-ac0f6aa8-1252-4b56-8405-da85e24dd386.png)
from
```
.overscroll::before {
  bottom: -1px;
}
```
to 
```
.overscroll::before {
  bottom: 0px;
}
```
However, I cannot find a way to override this part of CSS.
Are there any way to fix this problem or just let me override this CSS?

### Expected Behavior
In iOS style,
After I cancel this bad css:
![image](https://user-images.githubusercontent.com/17811951/187008904-2ef92372-9a92-4de0-a288-2ffe4a5c7690.png)
this unexpected scroll bar disappeared.
![image](https://user-images.githubusercontent.com/17811951/187008913-5cd5d29a-1f89-4f23-9c70-1da066ef1adc.png)
There shouldn't be an unexpected scroll bar.

### Steps to Reproduce

Create a new ionic 6 project from cli which the version as late as 2022-08-26.
Then modify any tab page, for example Tab3.tsx.
```
 <IonPage>
      <IonHeader>
        <IonToolbar>
          <IonTitle>Settings</IonTitle>
        </IonToolbar>
      </IonHeader>
      <IonContent>123</IonContent>
    </IonPage>
```

### Ionic Info

Ionic:
   Ionic CLI       : 6.20.1
   Ionic Framework : @ionic/react 6.2.4
Capacitor:
   Capacitor CLI      : 4.1.0
   @capacitor/android : not installed
   @capacitor/core    : 4.1.0
   @capacitor/ios     : not installed
Utility:
   cordova-res : 0.15.4
   native-run  : 1.6.0
System:
   NodeJS : v16.16.0
   npm    : 8.11.0
   OS     : Linux 5.15

**Comment by liamdebeasi** [comment] 2022-08-29 13:20
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The behavior you are seeing is the result of Ionic enabling rubber band scrolling on `ion-content` when running in iOS mode.

We do this by setting `top: -1px` and` bottom: -1px` on the `::before` and `::after` psuedo elements. The end result is a scroll bar is visible on iOS mode when debugging in Chrome. On iOS, the scrollbar is automatically hidden so this will not show up.

The same change is not needed on MD mode because Android device do not have the same rubber band/overflow scrolling style that iOS has. 

You can disable this by setting `forceOverscroll={false}` on `IonContent`: https://ionicframework.com/docs/api/content#forceoverscroll

**Closed by liamdebeasi** 2022-08-29 13:20 UTC
Labels: triage
