### ISSUE TITLE
bug: IonChange event not fired when clear button is clicked on ion-searchbar

### ISSUE THREAD

**Issue by adedayojs** [ionic-team/ionic-framework#28613] opened 2023-11-30 14:20 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When I have ionChange event in <ion-searchbar>. Clicking the clear button, The ionChange event isn't triggered.

### Expected Behavior

According to the documentation 

`The ionChange event is fired when the value has been committed by the user. This can happen when the element loses focus or when the "Enter" key is pressed. ionChange can also fire when clicking the clear or cancel buttons.`

### Steps to Reproduce

1. use this line of code `<ion-searchbar (ionChange)="updateFilter($event)" show-clear-button="always"></ion-searchbar>`
2. Type in an input
3. Exit the box or press enter (The ionChange event is fired)
4. Now click the clear button
5. Change event is not fired until i click out of the field

Note: I am using the standalone approach

https://github.com/ionic-team/ionic-framework/assets/52340442/3653aea8-c301-42e5-8828-df89993b194d

### Ionic Info

Ionic:

   Ionic CLI                     : 7.1.5 (/Users/adedayojs/.config/yarn/global/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.5.6
   @angular-devkit/build-angular : 16.2.9
   @angular-devkit/schematics    : 15.2.10
   @angular/cli                  : 16.2.9
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.5.1
   @capacitor/android : 5.5.1
   @capacitor/core    : 5.5.1
   @capacitor/ios     : not installed

Utility:

   cordova-res                          : not installed globally
   native-run (update available: 2.0.0) : 1.7.4

System:

   NodeJS : v20.9.0 (/Users/adedayojs/.nvm/versions/node/v20.9.0/bin/node)
   npm    : 10.1.0
   OS     : macOS Unknown

**Comment by liamdebeasi** [comment] 2023-11-30 14:35
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. As per the documentation, `ionChange` is only fired once the value has been committed including when the clear button is clicked. The input is still focused even after clicking the clear button, so the value has not been committed yet. As a result, `ionChange` only fires after you blur the input.

**Closed by liamdebeasi** 2023-11-30 14:35 UTC
Labels: triage

**Comment by adedayojs** [comment] 2023-11-30 14:43
> Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. As per the documentation, `ionChange` is only fired once the value has been committed including when the clear button is clicked. The input is still focused even after clicking the clear button, so the value has not been committed yet. As a result, `ionChange` only fires after you blur the input.

Thanks for the timely response.
I guess the last part of the documentation was misleading in this case and i'd suggest it should be revisited.

Thanks

**Comment by adedayojs** [comment] 2023-11-30 14:43
> Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. As per the documentation, `ionChange` is only fired once the value has been committed including when the clear button is clicked. The input is still focused even after clicking the clear button, so the value has not been committed yet. As a result, `ionChange` only fires after you blur the input.

Thanks for the timely response.
I guess the last part of the documentation was misleading in this case and i'd suggest it should be revisited.

Thanks
