### ISSUE TITLE
feat: ion-datetime add (optional) button to clear date field

### ISSUE THREAD

**Issue by basvdijk** [ionic-team/ionic-framework#22280] opened 2020-10-08 15:43 UTC
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

When using a date picker in an optional field it might be that the user makes a mistake. Currently there is no way to remove the date other than via an external button which clears the form field.

**Describe Preferred Solution**

Ideal would be to have an option `showClearbutton` which shows or hides the clear button.

**Describe Alternatives**

 I've tried to mimic the desired behaviour with the pickeroptions below. However the handler for Done got the picker object instead of the ISO date.

```
        buttons: [
            {
                text: 'Clear',
                handler: () => this.clearField(optionalDateField)
            },
            {
                text: 'Cancel',
                role: 'cancel'
            },
            {
                text: 'Done',
                handler: (e) => {
                    this.form.controls[optionalDateField].setValue(e);
                }

            }
        ]
```

**Related Code**

**Additional Context**

**Comment by liamdebeasi** [comment] 2020-10-08 15:47
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/20048. We plan on updating datetime to allow for custom cancel buttons.

**Closed by liamdebeasi** 2020-10-08 15:47 UTC
Labels: triage

**Comment by basvdijk** [comment] 2020-10-08 15:49
@liamdebeasi This is not the same issue as #20048. I want a button which clears the picker form element. Cancel is a different function right?

**Comment by liamdebeasi** [comment] 2020-10-08 15:52
Cancel is a different function, but the underlying issue and work required to resolve both is the same.

**Comment by basvdijk** [comment] 2020-10-08 15:54
@liamdebeasi ok, just to be sure, with the the planned update I can:
- define a custom 'ok' button which gives me the isodate instead of the picker object
- define a custom 'clear' button which cancels the picker and clears the field

**Comment by liamdebeasi** [comment] 2020-10-08 15:55
Yes that sounds correct. We plan on adding better support for custom buttons to datetime as well as allowing developers to control what happens when you click a button (set the datetime value, clear the value, don't do anything, etc).

**Comment by basvdijk** [comment] 2020-10-08 15:56
@liamdebeasi That's great, thanks for clarifying! Any thoughts about when this is implemented?

**Comment by liamdebeasi** [comment] 2020-10-08 15:59
So this fix is going to require a breaking change, meaning it will not be available until Ionic Framework v6. We do not have a timeline yet (working on getting Ionic Vue out first), but we are definitely interested in focusing on datetime improvements with this upcoming major release.

**Comment by basvdijk** [comment] 2020-10-08 16:07
Ok, then I know that for the new release of my whisky app (https://get.drammer.com/) I need to find a workaround, thanks!
