### ISSUE TITLE
bug: IonInput's onIonChange not fired on Safari when type="file" and file was selected

### ISSUE THREAD

**Issue by larsblumberg** [ionic-team/ionic-framework#21841] opened 2020-07-29 15:04 UTC
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

Safari 13.0.5 on macOS 10.15

**Current behavior:**
`IonInput`'s `onIonChange` is not fired when file was selected

**Expected behavior:**
`IonInput`'s `onIonChange` is fired when file was selected

**Steps to reproduce:**
```
<IonInput type="file" onIonChange={e => console.log('onIonChange', e)} />
```

**Other information:**
Works on Firefox though

**Ionic info:**

```

Ionic:

   Ionic CLI       : 6.10.1 (/Users/lars/.config/yarn/global/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.2.2

Capacitor:

   Capacitor CLI   : 2.0.2
   @capacitor/core : 2.2.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v14.4.0 (/usr/local/Cellar/node/14.4.0/bin/node)
   npm    : 6.14.4
   OS     : macOS Catalina
```

**Comment by liamdebeasi** [comment] 2020-07-29 15:38
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. We do not currently support `type="file"` in `ion-input`, which is why `onIonChange` does not work with it. TypeScript should have given you an error, but I'm not sure why it did not.

**Closed by liamdebeasi** 2020-07-29 15:38 UTC
Labels: triage

**Comment by larsblumberg** [comment] 2020-07-30 09:22
I'm not able to relate with your response and I think you're wrong here.

Ionic _does_ support `type="file"` as there's multiple evidence (listing a few):

1. The Ionic documentation for the property `accept` and `multiple` document that type can be set to `file`:

https://ionicframework.com/docs/api/input#properties

<img width="641" alt="Screenshot 2020-07-30 at 11 15 49" src="https://user-images.githubusercontent.com/5980316/88905710-dae9d780-d256-11ea-987e-5b43076d4221.png">

<img width="643" alt="Screenshot 2020-07-30 at 11 19 41" src="https://user-images.githubusercontent.com/5980316/88905727-de7d5e80-d256-11ea-85ac-a6c24732a3ff.png">

2. IonInput _does_ work on Firefox, Safari (and probably Chrome, too, not tested) with `type="file"`:

<img width="381" alt="Screenshot 2020-07-30 at 11 16 38" src="https://user-images.githubusercontent.com/5980316/88905209-57c88180-d256-11ea-9344-a903b5027a61.png">

3. `onIonChange` is properly fired on Firefox when a file was selected.

Given this evidence I suggest to reinvestigate and rethink your conclusion.

**Comment by liamdebeasi** [comment] 2020-07-30 13:32
I double checked with the team, and `type="file"` is not supposed to be supported with `ion-input`. I am not sure why the `accept` property was added -- it looks like it was added during the early development of Ionic v4 before we decided to only allow text type inputs. The documentation states that `ion-input` is intended for text type inputs only:

> It is meant for text type inputs only, such as "text", "password", "email", "number", "search", "tel", and "url".

Source: https://ionicframework.com/docs/api/input


It may be the case that `onIonChange` works properly in Firefox, but we do not currently support `type="file"` with `ion-input`. We are always open to new feature requests, so if you would like to see this added to the framework please [create a new feature request](https://github.com/ionic-team/ionic-framework/issues/new?assignees=&labels=&template=feature_request.md&title=feat%3A+). Please be sure to include your use case as that will be very helpful when evaluating new feature requests.

Thank you!

**Comment by larsblumberg** [comment] 2020-07-31 07:44
Thanks for getting back to this, @liamdebeasi. I guess you will be updating your documentation to avoid any confusion on this feature set.

As we use the file upload feature currently only internally, it's just fine as it is of now. In case Ionic already provides any alternative for selecting files to upload, I'd be glad to know more about it.

**Comment by liamdebeasi** [comment] 2020-07-31 13:20
Yep, I will remove mention of "file" from the `multiple` prop description. As for the `accept`, prop I will look into removing it entirely for Ionic Framework v6. `accept` is only used for `type="file"`, but removing it would be a breaking change, so I would need to wait for the next major release.

Ionic Framework does not have a specific uploader component, so it might be easiest to use `<input type="file">` and style it using CSS. CSS Tricks has a good article on how to do that with some code you can copy and paste: https://css-tricks.com/snippets/css/custom-file-input-styling-webkitblink/

**Comment by larsblumberg** [comment] 2020-08-03 10:04
Thanks @liamdebeasi. We can easily go with an alternative, non-Ionic solution. Semantically I understand why you don't want your `ion-text` component support files. I'm looking forward to the release of v6!

**Comment by liamdebeasi** [comment] 2020-08-03 13:09
Thanks! Yeah the documentation was a mistake on our part, so we will be more mindful of this moving forward.
