### ISSUE TITLE
bug: Ionic Segment needs scrollable in modal to animate properly (svelte project)

### ISSUE THREAD

**Issue by Tommertom** [ionic-team/ionic-framework#22187] opened 2020-09-27 18:32 UTC
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**
If I add a segment to a modal component in svelte, the animation while selecting different options is off - the ripple is shown on the old selected segment, not on the newly selected segment. WHen I add `scrollable` to the segment, the bug is gone

This only appears in a modal which is shown in my svelte project. I haven't tested it in other projects (angular etc)

https://www.youtube.com/watch?v=5PcSZWrI41Y

See above

**Expected behavior:**
The ripple to show on the segment selected.

**Steps to reproduce:**
Clone project https://github.com/Tommertom/svelte-ionic-app, add segment to ModalExtra.svelte without `scrollable` option and run code.

**Related code:**
Gives issue:
```
  <ion-segment value="{codeLanguage}" on:ionChange="{segmentChange}" >
    <ion-segment-button value="svelte">
      <ion-label>Svelte</ion-label>
    </ion-segment-button>
    <ion-segment-button value="js">
      <ion-label>Javascript</ion-label>
    </ion-segment-button>
  </ion-segment>
```

Does not give issue:

```
  <ion-segment value="{codeLanguage}" on:ionChange="{segmentChange}" scrollable>
    <ion-segment-button value="svelte">
      <ion-label>Svelte</ion-label>
    </ion-segment-button>
    <ion-segment-button value="js">
      <ion-label>Javascript</ion-label>
    </ion-segment-button>
  </ion-segment>
```

(see SourceViewer.svelte)

**Ionic info:**

```
i[WARN] You are not in an Ionic project directory. Project context may be missing.

Ionic:

   Ionic CLI : 6.11.0

Utility:

   cordova-res (update available: 0.15.1) : 0.11.0
   native-run (update available: 1.0.0)   : 0.3.0

System:

   NodeJS : v12.13.0
   npm    : 6.12.0
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment] 2022-03-16 13:42
Thanks for the issue and apologies for the delay in response. I am not able to reproduce this with the latest release of Ionic 6, so it is likely that the issue has been resolved.

I am going to close this, but if you are still running into issues please open a new issue with a GitHub repo. Thanks!

**Closed by liamdebeasi** 2022-03-16 13:42 UTC
Labels: triage
