### ISSUE TITLE
bug: ionic react does not support history@5.x

### ISSUE THREAD

**Issue by justinpathrose** [ionic-team/ionic-framework#23294] opened 2021-05-12 14:04 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.6.6**

**Current behavior:**

In Ionic React, the nested route declared is not rendered when navigated to the corresponding url after upgrading to the latest version of ionic(5.6.6)

**Expected behavior:**

The nested route is rendered.

**Steps to reproduce:**

Please check this link for the code. This is from the example of nested navigation from the ionic docs, but the ionic packages have been updated to version 5.6.6 - https://stackblitz.com/edit/ionic-react-routing-bhuvg6?file=src/index.tsx

**Related code:**

App.tsx

```
  <IonApp>
    <IonReactRouter>
      <IonRouterOutlet>
        <Route path="/dashboard" render={props => <DashboardPage {...props} />} />
        <Route exact path="/" render={() => <Redirect to="/dashboard" />} />
      </IonRouterOutlet>
    </IonReactRouter>
  </IonApp>
```

DashboardPage.tsx

```
    <IonRouterOutlet>
      <Route exact path={match.url} component={UsersListPage} />
      <Route path={`${match.url}/users/:id`} component={UserDetailPage} />
    </IonRouterOutlet>
```

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.10.1 (C:\Users\justi\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/react 5.6.6

Capacitor:

   Capacitor CLI   : not installed
   @capacitor/core : 2.4.7

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.19.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.8
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment] 2021-05-12 14:27
Thanks for the issue. Can you provide some steps to reproduce the issue? Clicking each of the user items in your example renders the nested route when I try it.

**Comment by justinpathrose** [comment] 2021-05-12 15:44
> Thanks for the issue. Can you provide some steps to reproduce the issue? Clicking each of the user items in your example renders the nested route when I try it.

Are you seeing a blank page? Sorry to not have mentioned in detail. So the URL in the address bar changes, but the component in the route is not rendered if you can look the code.  The route /dashboard/users/3 should have rendered the component - UserDetailPage.tsx. 

Can you check this link which has the same example running version 5.1.1 https://stackblitz.com/edit/ionic-react-routing-qegvvf?file=src/pages/UserDetailPage.tsx

**Comment by liamdebeasi** [comment] 2021-05-12 15:49
On Ionic React v5.6.6 after clicking the "User 3" button on `/dashboard`, I am presented with the following view on `/dashboard/users/3`:

![image](https://user-images.githubusercontent.com/2721089/118005073-0d614e80-b318-11eb-8fde-2230b668d99a.png)

**Comment by justinpathrose** [comment] 2021-05-12 16:18
> On Ionic React v5.6.6 after clicking the "User 3" button on `/dashboard`, I am presented with the following view on `/dashboard/users/3`:
> 
> ![image](https://user-images.githubusercontent.com/2721089/118005073-0d614e80-b318-11eb-8fde-2230b668d99a.png)

That is very strange.  It does not work when I try it. Could you please double check.

This is the link with v 5.6.6 which does not work for me - https://ionic-react-routing-bhuvg6.stackblitz.io/dashboard
Another thing I observed was that in version 5.6.6 the nested route works if I load the link directly - https://ionic-react-routing-bhuvg6.stackblitz.io/dashboard/users/3

This is the link with v 5.1.1 which works - https://ionic-react-routing-qegvvf.stackblitz.io/dashboard

**Comment by liamdebeasi** [comment] 2021-05-12 21:17
Thanks. The problem here looks to be related to the `history@5.0.0` dependency. Downgrading to `4.x` resolves the issue, so it seems like you are installing a newer version of `history` than what Ionic React is expecting.

In `history@4.x` the route location and route action are received as separate parameters. So you would have something like this:

```js
// action: 'REPLACE'
// location: { pathname: '/dashboard' }
const handlerHistoryChange = (location, action) => {
  ...
}
```

In `history@5.x` the route location and route action are part of the same object:
```js
// opts: { action: 'REPLACE', location: { pathname: '/dashboard' } }
const handlerHistoryChange = (opts) => {
  ...
}
```

Ionic React expects the old way, so its `action` param is now `undefined`. As a temporary workaround I would stick with `history@4.x` but I can see if this is something we can support on our end.

**Comment by liamdebeasi** [comment] 2021-05-12 21:38
React Router v5 expects `history@4.x`, so I do not recommend using `history@5.x` right now since you may run into other errors.

React Router v6 will be using `history@5.x`, so I do still think we should support this in Ionic React.

Can you try the following dev build and let me know if it resolves the issue?

```
npm install @ionic/react@5.7.0-dev.202105122134.ef72e07 @ionic/react-router@5.7.0-dev.202105122134.ef72e07
```

**Comment by justinpathrose** [comment] 2021-05-14 09:37
> React Router v5 expects `history@4.x`, so I do not recommend using `history@5.x` right now since you may run into other errors.
> 
> React Router v6 will be using `history@5.x`, so I do still think we should support this in Ionic React.
> 
> Can you try the following dev build and let me know if it resolves the issue?
> 
> ```
> npm install @ionic/react@5.7.0-dev.202105122134.ef72e07 @ionic/react-router@5.7.0-dev.202105122134.ef72e07
> ```

Thank you! Both the solutions worked for me.

**Comment by liamdebeasi** [comment] 2021-05-14 13:03
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/23297, and a fix will be available in an upcoming release of Ionic Framework.

**Closed** 2021-05-14 13:03 UTC
Labels: package: react, type: bug
