### ISSUE TITLE
bug: Open toast message not updating on message change

### ISSUE THREAD

**Issue by acommend** [ionic-team/ionic-framework#25302] opened 2022-05-18 01:33 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

Updating the Vue ref for the toast message attribute does not update the open toast message.

### Expected Behavior

Expected the open toast message to react to ref changes.

### Steps to Reproduce

1. Open toast with a ref for the message attribute and duration 0 to remain open
2. Update ref to see that the message does not update in the open toast

### Code Reproduction URL

https://github.com/acommend/toast-update

### Ionic Info

Ionic:

   Ionic CLI       : 6.18.1 (C:\Users\Tony\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/vue 6.1.3

Capacitor:

   Capacitor CLI      : 3.4.3
   @capacitor/android : 3.4.3
   @capacitor/core    : 3.4.3
   @capacitor/ios     : 3.4.3

Utility:

   cordova-res : 0.15.3
   native-run  : 1.5.0

System:

   NodeJS : v16.9.1 (C:\Program Files\nodejs\node.exe)
   npm    : 7.21.1
   OS     : Windows 10

**Comment by liamdebeasi** [comment] 2022-05-18 12:46
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/22799.

**Closed by liamdebeasi** 2022-05-18 12:46 UTC
Labels: triage
