### ISSUE TITLE
bug: IonDateTime is behind IonModal

### ISSUE THREAD

**Issue by BerkeAras** [ionic-team/ionic-framework#22512] opened 2020-11-17 17:49 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
IonDateTime is behind IonModal.

**Expected behavior:**
IonDateTime should be over IonModal.

**Steps to reproduce:**
- Create IonModal with IonDateTime.
- Open IonDateTime.

**Comment by liamdebeasi** [comment] 2020-11-17 18:38
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/21181. (same underlying issue)

**Closed by liamdebeasi** 2020-11-17 18:38 UTC
Labels: triage
