### ISSUE TITLE
bug: voiceover focus

### ISSUE THREAD

**Issue by Malnag** [ionic-team/ionic-framework#27727] opened 2023-06-30 12:22 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Navigating between different pages is reading from top of the page instead of reading the next where I left.

edit functionality will take to the previous page after edit when I come back it’s not focus the next element after edit.

Remove option on the same page is populating Modal for delete confirmation once the user confirm after deleting the first element it has to focus on next element instead it focusing on top of the page

### Expected Behavior

Page navigation has to read from where it was left

### Steps to Reproduce

Navigate between pages when we come back it has to focus on where we left

### Ionic Info

Ionic 7

**Comment by liamdebeasi** [comment] 2023-06-30 12:55
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/23650.

**Closed by liamdebeasi** 2023-06-30 12:55 UTC
Labels: triage
