### ISSUE TITLE
bug: Ion-Item-Sliding stopped on list updated

### ISSUE THREAD

**Issue by SherifMoShalaby** [ionic-team/ionic-framework#18281] opened 2019-05-15 08:21 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

Ion-item-sliding stopped after updating the list

**Expected behavior:**

should be working with no problems !

**Steps to reproduce: please clone the git repo found below**

1. run the application
2. slide the item named 'list3' from the right to left and press the + icon button
3. the behavior of the add here is to unshift the current item to the start
4. try to slide the unshifted item at the index 0 from the right, it will not

**Related code:**

https://github.com/SherifMoShalaby/IonicBugs.git

**Other information:**

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (C:\Users\sshalaby\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.4.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

System:

   NodeJS : v10.15.2 (C:\Program Files\nodejs\node.exe)
   npm    : 6.9.0
   OS     : Windows 10
```

**Comment by topalavlad** [comment] 2019-06-10 22:36
@SherifMoShalaby - not sure if this is a bug or not but adding the same object twice in the array that you pass to `*ngFor` is a bit weird.

> the behavior of the add here is to unshift the current item to the start
Not sure if you wanted `onAdd()` to duplicate the current item, or move it at the start

If duplicating it is really what you want, you can use `trackBy` as a workaround:
```
<ion-item-sliding *ngFor="let list of lists; let i = index; trackBy: trackByFn" #itemSliding>


trackByFn(index) {
    return index;
}
```

**Comment by liamdebeasi** [comment] 2022-07-08 15:16
Thanks for the issue. I am not able to reproduce this anymore, so it looks like the issue was fixed in a previous version of Ionic. I am going to close this, but feel free to open a new issue. Thanks!

**Closed by liamdebeasi** 2022-07-08 15:16 UTC
Labels: package: core, type: bug
