### ISSUE TITLE
feat: slot for button in ion-input

### ISSUE THREAD

**Issue by luqasmateus** [ionic-team/ionic-framework#28029] opened 2023-08-19 18:00 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

With the new `ion-input` syntax, I am not able to create inputs with embedded buttons anymore. In version 6, I used `slot="end"` on `ion-item` to achieve that effect (still had to move the button with CSS when using a floating label, but it worked). 

### Describe the Use Case

A show/hide password button inside the input. Would also be a way to customize the button that appears when using `[clearInput]="true"`.
Material Design 2 has a couple examples of uses to that feature here: https://m2.material.io/components/text-fields#anatomy (under "Icons").

### Describe Preferred Solution

A button slot in `ion-input` would do it, just like the new label slot.

### Related Code

Here's an example using the legacy syntax: https://github.com/luqasmateus/ion-input-button-slot

**Comment by amandaejohnston** [comment] 2023-08-21 14:23
Thank you for the issue. I'm going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/26297.

**Closed by amandaejohnston** 2023-08-21 14:23 UTC
Labels: triage
