### ISSUE TITLE
bug: Breadcrumb Icon dissapears after updating breadcrumbs

### ISSUE THREAD

**Issue by joxy379** [ionic-team/ionic-framework#23694] opened 2021-07-27 08:25 UTC
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

I load my breadcrumb in via typescipt. The initial render is ok. But when I update the breadcrumb values in typescript the icon dissapears.

https://user-images.githubusercontent.com/36665384/127121331-6c6842a3-c538-4782-8664-ab2eeb27cdef.mp4

### Expected Behavior

To render the breadcrumb separator on breadcrumb change 

### Steps to Reproduce

In HTML:
```
<ion-breadcrumbs>
    <ion-breadcrumb *ngFor="let breadcrumb of breadCrumbs"
      >{{breadcrumb.name}}</ion-breadcrumb
    >
  </ion-breadcrumbs>

<ion-button (click)="changeBreadcrumbs()">Change Breadcrumbs</ion-button>
```

in TS:
```
import { Component } from '@angular/core';

@Component({
  selector: 'app-home',
  templateUrl: 'home.page.html',
  styleUrls: ['home.page.scss'],
})
export class HomePage {
  breadCrumbs = [{ name: 'bread1' }, { name: 'bread2' }];

  constructor() {}

  changeBreadcrumbs(): void {
    this.breadCrumbs = [{ name: 'newbread1' }, { name: 'newbread2' }];
  }
}

```

### Code Reproduction URL

https://github.com/joxy379/IonicBreadcrumbBug

### Ionic Info

```
Ionic:

   Ionic CLI                     : 6.16.3 (C:\Users\Ruben\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.0.0-beta.2
   @angular-devkit/build-angular : 12.1.3
   @angular-devkit/schematics    : 12.1.3
   @angular/cli                  : 12.1.3
   @ionic/angular-toolkit        : 4.0.0

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v14.15.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.8
   OS     : Windows 10

```

**Comment by liamdebeasi** [comment] 2021-07-27 14:11
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/23573.

**Closed by liamdebeasi** 2021-07-27 14:11 UTC
Labels: triage
