### ISSUE TITLE
bug: @ionic/vue fix modalController types to allow Vue "Component" type.

### ISSUE THREAD

**Issue by mattsteve** [ionic-team/ionic-framework#23364] opened 2021-05-25 21:20 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
When using modalController to instantiate a Vue component in a modal, I'm having issues passing an async component.

ComponentRef typings are generic enough to include "Function":
https://github.com/ionic-team/ionic-framework/blob/8e0e5da7407adecb7471b3a6b0ac059337761355/core/src/interface.d.ts#L56

But don't allow passing a Vue "Component" directly:
https://github.com/vuejs/vue-next/blob/master/packages/runtime-core/src/component.ts#L144

**Expected behavior:**
Types should match actual behavior of modalController.

**Steps to reproduce:**
Use Vue's defineAsyncComponent to instantiate a component that handles a dynamic import. Can't pass the result of defineAsyncComponent to the "component" property in modalController according to Typescript, though it actually does work if Typescript is ignored.

**Related code:**
```
import { defineAsyncComponent } from 'vue';
import { modalController } from '@ionic/vue';
modalController.create({
    component: defineAsyncComponent(() => import('@/components/component.vue'))
});
```

**Comment by liamdebeasi** [comment] 2021-05-25 21:38
Thanks for the issue. Can you paste in the exact TypeScript error that you are getting?

**Comment by liamdebeasi** [comment] 2021-05-25 21:46
Oh actually, in that `@/components/componet.vue` file, are you defining the component using the `defineComponent` function imported from Vue?

```js
import { defineComponent } from 'vue';

export default defineComponent({
  ...
});
```

`defineComponent` provides additional type information for TypeScript, so that might be what the issue is here.

**Comment by mattsteve** [comment] 2021-05-26 16:34
@liamdebeasi yes

**Comment by mattsteve** [comment] 2021-05-26 16:52
```
ERROR in /home/user/projects/example/src/components/component.ts(122,17):
122:17 Type '{}' is not assignable to type 'ComponentRef'.
  Type '{}' is missing the following properties from type 'HTMLElement': accessKey, accessKeyLabel, autocapitalize, dir, and 234 more.
    120 |             const modal = await modalController.create({
  > 121 |                 component: defineAsyncComponent(() => import(/* webpackChunkName: "downtime" */ '@/components/component.vue')),
        |                 ^
Version: typescript 4.2.4
```

**Comment by mattsteve** [comment] 2021-05-26 16:57
It's an incompatibility with the ["Component" type in Vue runtime-core](https://github.com/vuejs/vue-next/blob/master/packages/runtime-core/src/component.ts#L144) and the ["ComponentRef" type in Ionic core](https://github.com/ionic-team/ionic-framework/blob/8e0e5da7407adecb7471b3a6b0ac059337761355/core/src/interface.d.ts#L56).

**defineAsyncComponent()** returns the Vue/runtime-core "Component" type, modalController component property expects something compatible with Ionic/core "ComponentRef".

**Comment by liamdebeasi** [comment] 2021-05-26 16:59
Can you reproduce this in an Ionic starter app and provide a link to the repo? I am not seeing this on my end -- TypeScript does not throw that error.

**Comment by mattsteve** [comment] 2021-05-26 17:00
What code are you using?

**Comment by liamdebeasi** [comment] 2021-05-26 17:20
**Home.vue** in my `setup` function:
```js
const modal = await modalController.create({
  component: defineAsyncComponent(() => import('@/views/TestCmp.vue'))
});
    
await modal.present();
```

And then the `TestCmp.vue` definition:
```js
<template>
  Hello World
</template>

<script lang="ts">
  import { defineComponent } from 'vue';
  
  export default defineComponent({});
</script>
```

**Comment by mattsteve** [comment] 2021-05-26 17:26
Try creating a modal outside of a Vue component, it might be eating your typescript errors.

https://github.com/mattsteve/ionic-vue-modal-async-component

npm run serve - Typescript it will complain in the terminal but the serve still works to open the modal.
npm run build - Build fails due to typescript error.

**Comment by liamdebeasi** [comment] 2021-05-28 13:02
Hey there,

I can reproduce this in your app, though I cannot reproduce this in a blank Ionic starter app when I try to create the modal outside of my Vue component. I am still digging into this, and I will update this thread when I have more info. Thanks!

**Comment by liamdebeasi** [comment] 2021-05-28 13:47
Ok figured it out. Looks like there was a bug in `@vue/cli-plugin-typescript` that has been fixed in newer versions. Updating `@vue/cli-plugin-typescript` to the latest version fixed the issue.

**Closed by liamdebeasi** 2021-05-28 13:47 UTC
Labels: triage
