### ISSUE TITLE
bug: Ionic styles not available in custom React components with prod build

### ISSUE THREAD

**Issue by stasdre** [ionic-team/ionic-framework#25573] opened 2022-07-04 07:51 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

We have 2 applications. We also created our own UI library of components (we store it in a separate repository and use it as an npm dependency). In UI library we use ionic components, add the styles we need and use these custom components in our applications. In applications and the UI library, we use React v17.0.2.

The problem is that if we use a component from our UI library in one of our applications, styles for ionic components disappear after build  application in production. Global and additional ionic styles in applications are imported. If we run the application in development mode, everything is good with the styles. But as soon as the project is built, the styles that ionic uses disappear.

### Expected Behavior

We expect that by using our custom components based on ionic components, we will be able to use them in our applications and their styles will be saved after the project is built in production.

### Steps to Reproduce

Example UI component:

```javascript
const SegmentWrapper = styled(IonSegment)'
    min-height: 32px; 
    --background: #d6f2f9;
';

export const SegmentLabel = styled(IonLabel)'
    font-weight: 400;
    font-size: 14px;
    line-height: 16px;
    color: #1d201f;
';

type SegmentType = {
    id: string;
    label: string;
};

type SegmentProps = {
    segments: SegmentType[];
    selected?: string;
    onChange?: (id: string) => void;
};

const Segment: FC<SegmentProps> = ({ segments, selected, onChange }) => {
  return (
    <SegmentWrapper
      scrollable
      mode="ios"
      value={selected}
      onIonChange={(e) => onChange?.(e.detail.value as string)}
    >
      {segments.map((item) => (
        <IonSegmentButton key={item.id} value={item.id}>
          <SegmentLabel>{item.label}</SegmentLabel>
        </IonSegmentButton>
      ))}
    </SegmentWrapper>
  );
};

export default Segment;
```

In application we use this component:

```javascript
const segments: SegmentType[] = [
  { id: 'feed', label: 'Tab 1' },
  { id: 'info', label: 'Tab 2' },
];

<Segment
  segments={segments}
  selected={selectedSegment}
  onChange={setSelectedSegment}
/>
```

If we run `npm run start` we will see that the component is displayed as needed and :host styles are applied:

<img width="429" alt="image" src="https://user-images.githubusercontent.com/20515687/177104596-a0dbb4a4-65be-43f2-ace5-45f5acda2e45.png">
<img width="452" alt="image" src="https://user-images.githubusercontent.com/20515687/177104859-94780761-6d0d-4199-b72b-fa24615f7d91.png">

But if we run `npm run build` and open production build we will see that our custom styles are present but ionic component styles are gone: 

<img width="396" alt="image" src="https://user-images.githubusercontent.com/20515687/177105807-63d6fc37-7f46-4151-9863-e9861e70d807.png">
<img width="454" alt="image" src="https://user-images.githubusercontent.com/20515687/177105936-6c16efe1-d1ce-43a9-8d92-77265e0c6bdc.png">

### Ionic Info

<img width="1083" alt="image" src="https://user-images.githubusercontent.com/20515687/177106570-b69a6799-31ad-4c3e-9251-0bf74a52b1e2.png">

### Additional Information

Our UI library was tried to build in different ways: with rollup, only with TS, with react-script. But it doesn't affect the build production application. 

Noticed only one feature. If in our application, in any place, we use the ionic component and in another place use our custom component, then the styles do not disappear and everything is OK. But that's not what we want, we want to use our UI

**Comment by liamdebeasi** [comment] 2022-07-05 13:29
Thanks for the issue. Can you please provide a minimal GitHub repo I can use to verify this behavior?

**Comment by stasdre** [comment] 2022-07-10 10:23
Hi @liamdebeasi! I created examples for you. 
This example of UI lib https://github.com/stasdre/mindly-test-ui
This example app where we use UI lib https://github.com/stasdre/mindly-test

**Comment by liamdebeasi** [comment] 2022-07-12 13:35
Thanks. The problem appears to be that you are not calling `setupIonicReact` in `mindly-test-ui`, causing the `mode` to not be setup correctly. Can you add that to `mindly-test-ui` and let me know if that resolves the issue?

**Comment by stasdre** [comment] 2022-07-24 09:36
Thanks. It's really work after added `setupIonicReact` in our UI lib. Thank you fore help!

**Comment by liamdebeasi** [comment] 2022-07-26 18:03
Glad the issue is resolved! I am going to close this.

**Closed by liamdebeasi** 2022-07-26 18:03 UTC
Labels: triage
