### ISSUE TITLE
bug: Picker scrolling many columns with 200+ values each on android is janky

### ISSUE THREAD

**Issue by mwyld** [ionic-team/ionic-framework#22395] opened 2020-10-27 08:48 UTC
I have a picker with 3 columns and about 200 options in each. On iOS this performs fine but on android it scrolls very janky

![image](https://user-images.githubusercontent.com/12820928/97276501-2d736980-182f-11eb-88a4-1ab19cfa604f.png)

# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

```"@angular/common": "~8.2.14",
    "@angular/core": "~8.2.14",
    "@angular/forms": "~8.2.14",
    "@angular/platform-browser": "~8.2.14",
    "@angular/platform-browser-dynamic": "~8.2.14",
    "@angular/router": "~8.2.14",
    "@capacitor/android": "^2.4.2",
    "@capacitor/core": "^2.4.2",
    "@capacitor/ios": "^2.4.2",
    "@ionic-native/core": "^5.28.0",
    "@ionic-native/splash-screen": "^5.28.0",
    "@ionic-native/status-bar": "^5.28.0",
    "@ionic/angular": "^5.3.5",
    "@ngx-translate/core": "^12.1.2",
    "@ngx-translate/http-loader": "^4.0.0",
    "core-js": "^2.5.4",
    "rxjs": "~6.5.1",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"
```

**Current behavior:**
When you scroll the large dataset iOS seems fine however android seems more jolty and tends to jump to the next/prev value to the one your trying to select

**Expected behavior:**
Android has smooth scrolling of the picker like the iOS one

**Steps to reproduce:**
Create a picker with many columns and 200+ values in each

**Related code:**

N/A

**Other information:**

**Ionic info:**
```
Ionic:

   Ionic CLI                     : 6.12.0 (/Users/mwyld/.nvm/versions/node/v12.16.3/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.3.5
   @angular-devkit/build-angular : 0.803.26
   @angular-devkit/schematics    : 8.3.26
   @angular/cli                  : 8.3.26
   @ionic/angular-toolkit        : 2.3.3

Capacitor:

   Capacitor CLI   : 2.4.2
   @capacitor/core : 2.4.2

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.16.3 (/Users/mwyld/.nvm/versions/node/v12.16.3/bin/node)
   npm    : 6.14.4
   OS     : macOS Catalina
```

**Comment by liamdebeasi** [comment] 2020-10-27 13:10
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/16681. This issue is being tracked in https://github.com/ionic-team/ionic-framework/issues/16630.

**Closed by liamdebeasi** 2020-10-27 13:10 UTC
Labels: triage
