### ISSUE TITLE
bug: Ionic 4&5: Scroll position wrong

### ISSUE THREAD

**Issue by KevinBassaDevelopment** [ionic-team/ionic-framework#20821] opened 2020-03-19 13:03 UTC
# Bug Report

**Ionic version:**
[x] ** 5.0.5**  (Bug was also present in 4.11.6)

**Current behavior:**

1. When switching from 1 page to another, after the second page has finished loading, it scrolls down to the same height as the previous page was.
2. When going back to the 1st page, it does not remember the scroll position, but go to 0 again.

**Expected behavior:**
A new page should always start at scroll position 0.
Going back on a previous page on the stack should get the same scroll position it was when it was left.

**Steps to reproduce:**
Behaviour can be viewed in the Ionic Conference App: https://github.com/ionic-team/ionic-conference-app
See the "Schedule" Tab.

- scroll down
- open event
- when event page has a scrollbar, it will scroll down to same height as schedule page was
- press back
- now schedule page is again at the top of the page

The video was taken with v4.11.6, but its the same with v5.0.5

![ezgif com-optimize](https://user-images.githubusercontent.com/11556950/77070356-5c4c7600-69ea-11ea-8f16-2975881e0e59.gif)

**Ionic info:**
```
Ionic:

   Ionic CLI                     : 5.4.16
   Ionic Framework               : @ionic/angular 5.0.5
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.17
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res                          : not installed
   native-run (update available: 0.3.0) : 0.2.9

System:

   NodeJS : v10.15.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment] 2020-03-19 13:09
Thanks for the issue. What browser are you testing this on?

**Comment by KevinBassaDevelopment** [comment] 2020-03-19 13:19
The bug occurs on Firefox.

On ionic v4 there was a workaround:
I stored the scroll position on each page & applied it in ionViewWillEnter() (to restore it when going back) and ionViewDidEnter() (to have pos 0 when going to new page).

ionViewDidEnter() now stopped working in v5, because the page scrolls afterwards down to the position of the previous page.

**Comment by KevinBassaDevelopment** [comment] 2020-04-02 15:15
When will this bug be looked on? It makes Ionic quite annoying to use on firefox.

**Comment by KevinBassaDevelopment** [comment] 2020-04-13 10:35
Sorry to bother you, but I need to know if I should roll back to Ionic 4 or if there is a fix planned so that Ionic 5 again works on Firefox.

**Comment by KevinBassaDevelopment** [comment] 2020-04-25 10:25
This issue is also relevant for [Milesteone Ionic for Desktop](https://github.com/ionic-team/ionic/milestone/67), as Scroll is also broken on Desktop Firefox.
And on Desktop, Firefox has nearly 10% market share.

In Ionic 4, it was possible to do a dirty workaround doing manually scrolling to 0 on ionviewdidenter:

```
 private scrollPos = 0;
 public ionViewDidEnter() {
        // workaround because ionic scrolls down on firefox when switching to a new page
        this.content.scrollToPoint(0, this.scrollPos);
      }
```

It would be great if at least some workaround was also possible in Ionic 5.

**Comment by HyperLife1119** [comment] 2020-08-24 15:56
I also encountered this problem.

**Comment by Scan0815** [comment] 2020-10-30 19:18
I have the same issue.

**Comment by 7freaks-otte** [comment] 2020-12-21 14:59
This is really annoying but it seems to be a Firefox issue that also happens in other applications like Facebook for years now.

The only way for me to mitigate this issue was to get the the scrollTop `content.getScrollElement()` on `ionViewDidLeave`, remember it for every page instance, and explicitly set it on `ionViewDidEnter`.

This forces scrollTop to be 0 on new pages (not the last position of the previous page) and resets to the previous position when returning from another page.

This may result in a small visual glitch on Firefox but at least sets the correct position. I haven't tested yet if `ionViewWillEnter` would work better or if it is just too early (before Firefox does its own scrolling).

**Comment by julianpoy** [comment] 2020-12-24 01:21
Can confirm, experiencing this same exact issue.

**Comment by chriswep** [comment] 2021-01-26 10:44
bumped into this issue while implement the desktop version for our app. My workaround:

```
ionViewDidEnter() {
    if (platform.name === 'Firefox') {
        setTimeout(() => this.content.scrollToTop());
    }
}
```

Be warned: If you see a `setTimeout` for something like this you should usually run. This may (and probably will) fail randomly. Since this works for my tests with only an occasional minor visual glitch, i'll go with this until a fix comes around, since it's better than not working at all. What likely is happening here is that the bug happens during the same cycle that `ionViewDidEnter` is executed and that running the fix on the next cycle by `setTimeout` fixes it (almost) instantly.

I use the "platform" library, since i have it loaded anyway. Firefox detection should be easy enough without it though. 

For reference: The issue is not related to scroll-anchoring, disabling it in Firefox has no effect on the issue.

**Comment by D4RKONION** [comment] 2021-03-04 00:43
Just adding to the dismay that this hasn't been fixed yet. Is there a timeline on dealing with this or is this not to be fixed?

**Comment by liamdebeasi** [comment] 2023-04-21 18:38
Hi everyone,

Does this issue reproduce on Ionic 7 with the latest version of Firefox?

**Comment by chriswep** [comment] 2023-04-21 19:58
@liamdebeasi on firefox Ionic 7 i still need to manually scroll to zero on viewEnter otherwise the new page uses the scroll position of the last one

**Comment by liamdebeasi** [comment] 2023-04-21 20:37
Thanks! I am going to add this to our backlog to take a closer look at.

**Comment by thetaPC** [comment] 2023-05-17 15:07
@chriswep what Firefox version are you using? Also please provide a reproduction URL so we can investigate further? Thanks!

**Comment by chriswep** [comment] 2023-05-17 16:36
i'm using the Firefox Developer Edition 114 on macOS. however the issue existed in all versions before that. i can't provide a reproduction URL since in our production app there is the above mentioned fix applied.

**Comment by thetaPC** [comment] 2023-05-17 17:58
Would it be possible to get a video that shows the bug on your end using the [Conference app](https://github.com/ionic-team/ionic-conference-app)? I've tested this on Firefox Developer Edition 114 on macOS and it seems to be working properly. I'm including a video of what I'm doing. Let me know if you see something that I'm missing.

https://github.com/ionic-team/ionic-framework/assets/13530427/c3e57252-0f9d-4061-bf76-453efead9fa2

**Comment by chriswep** [comment] 2023-05-17 19:11
i also tried the conference app and couldn't reproduce it. if i disable the forced `scrollTop = 0` in our app i can reproduce the issue on some page transitions but not all. however at this point i can't invest the time for isolating the issue into a test-project.

**Comment by thetaPC** [comment] 2023-05-17 19:53
Closing the issue since bug cannot be reproduced when using Firefox v95+.

Please update Firefox to any of those versions if you are encountering the bug. If the bug persists, then open a new issue with a minimal reproduction along with the Firefox version. Thank you!

**Closed by thetaPC** 2023-05-17 19:53 UTC
Labels: triage, package: core, type: bug
