### ISSUE TITLE
bug: [ionic-vue] Incorrect view rendered when using router.go(-n) in linear routing

### ISSUE THREAD

**Issue by xxllxhdj** [ionic-team/ionic-framework#29846] opened 2024-09-07 12:43 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/docs/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v8.x

### Current Behavior

<img width="360" alt="image" src="https://github.com/user-attachments/assets/14e335e2-344b-49bf-b420-dfc2d9df9af1">

### Expected Behavior

<img width="350" alt="image" src="https://github.com/user-attachments/assets/8da3be5e-51bc-467e-a102-84b0f827ac4f">

### Steps to Reproduce

1. Open home page, click [Page 1]
2. Click [Page 2] in Page 1
3. Click [Page 3] in Page 2
4. Click [Back] in Page 3
5. Click [Done] in Page 2

### Code Reproduction URL

https://github.com/xxllxhdj/ionic-vue-router-issue

### Ionic Info

@ionic/vue 8.3.0
@ionic/vue-router 8.3.0

**Comment by bokanechase-digistorm** [comment] 2024-09-17 09:07
@xxllxhdj it looks like this might be a duplicate of the issue identified in #28201. I've just submitted a related PR.

**Comment by bentleyo** [comment] 2024-09-17 09:09
@xxllxhdj it looks like this might be a duplicate of the issue identified in https://github.com/ionic-team/ionic-framework/issues/28201. I've just submitted a related PR.

**Comment by thetaPC** [comment] 2024-10-11 23:35
Thank you for submitting the issue! I'm going to have to close it as it's a duplicate of https://github.com/ionic-team/ionic-framework/issues/28201. I recommend subscribing to that issue for updates.

**Closed by thetaPC** 2024-10-11 23:35 UTC
Labels: triage
