### ISSUE TITLE
bug: vue uses nested routing, but I get an error

### ISSUE THREAD

**Issue by lvzhenbo** [ionic-team/ionic-framework#28405] opened 2023-10-25 06:08 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

I've added the page tag, but I still get an error
![image](https://github.com/ionic-team/ionic-framework/assets/32427677/8bb5890e-e84c-4e66-8739-0ab7febe92ce)

### Expected Behavior

The program is running normally.

### Steps to Reproduce

1. I encapsulated the layout
2. Nested page routes within the layout

### Code Reproduction URL

https://github.com/lvzhenbo/ionic-app

### Ionic Info

[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package.json'
       
       Require stack:
       - C:\Users\29422\AppData\Roaming\npm\node_modules\@ionic\cli\lib\project\index.js
       - C:\Users\29422\AppData\Roaming\npm\node_modules\@ionic\cli\lib\index.js
       - C:\Users\29422\AppData\Roaming\npm\node_modules\@ionic\cli\index.js
       - C:\Users\29422\AppData\Roaming\npm\node_modules\@ionic\cli\bin\ionic

Ionic:

   Ionic CLI       : 7.1.1 (C:\Users\29422\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/vue 7.5.1

Capacitor:

   Capacitor CLI      : 5.5.0
   @capacitor/android : 5.5.0
   @capacitor/core    : 5.5.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v20.8.1 (C:\Program Files\nodejs\node.exe)
   npm    : 10.1.0
   OS     : Windows 10

**Comment by liamdebeasi** [comment] 2023-10-25 13:48
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. You are including `@/layout/index.vue` as a page view, so that component needs `IonPage` as well (currently there is only a div). Adding IonPage to that component fixes the issue.

As a side note, I'd also encourage you to reconsider the nested routing approach you have as this pattern can be confusing in mobile apps when used incorrectly: https://ionicframework.com/docs/vue/navigation#linear-routing-versus-non-linear-routing

You could simplify this application by moving the `MenuLayout` to `App.vue`. From there, you can take the contents of `PageLayout` and add it to `App.vue`. This will let you avoid the nested router outlet.

**Closed by liamdebeasi** 2023-10-25 13:48 UTC
Labels: triage
