### ISSUE TITLE
bug: Ionic vue not navigating correctly between tabs after active tab is clicked twice

### ISSUE THREAD

**Issue by DriesBruggeman** [ionic-team/ionic-framework#24395] opened 2021-12-14 10:31 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [X] v6.x

### Current Behavior

When using Ionic Vue tabs starter template when you click the active tab and then try to navigate away from that tab the URL replaces with the route of the tab you clicked on the but component is not rendered. 

### Expected Behavior

When the active tab is clicked no navigation should occur, but when another tab is selected navigation to that clicked tab should occur.

### Steps to Reproduce

1. Start a new project using: ionic start, 
2. Either use or don't use the wizard
3. Use Vue as the framework
4. Use Tabs as the template
5. Wait till the app is generated
6. Serve app using: ionic serve
7. Open the browser on localhost:8100
8. Tab 1 will be loaded, click Tab 2 => Ionic will navigate to Tab 2.
9. Now Tab 2 is active, click Tab 2 again => no navigation occurs, Tab 2 is already active.
10. Now click Tab 1 or Tab 3 => URL changes, but ionic does not navigate.

### Ionic Info

[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package'

       Require stack:
       - C:\Users\Dries\AppData\Roaming\npm\node_modules\@ionic\cli\lib\project\index.js
       - C:\Users\Dries\AppData\Roaming\npm\node_modules\@ionic\cli\lib\index.js
       - C:\Users\Dries\AppData\Roaming\npm\node_modules\@ionic\cli\index.js
       - C:\Users\Dries\AppData\Roaming\npm\node_modules\@ionic\cli\bin\ionic
[WARN] Error loading @capacitor/android package.json: Error: Cannot find module '@capacitor/android/package'

       Require stack:
       - C:\Users\Dries\AppData\Roaming\npm\node_modules\@ionic\cli\lib\project\index.js
       - C:\Users\Dries\AppData\Roaming\npm\node_modules\@ionic\cli\lib\index.js
       - C:\Users\Dries\AppData\Roaming\npm\node_modules\@ionic\cli\index.js
       - C:\Users\Dries\AppData\Roaming\npm\node_modules\@ionic\cli\bin\ionic

Ionic:

   Ionic CLI       : 6.18.1 (C:\Users\Dries\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/vue 6.0.0

Capacitor:

   Capacitor CLI      : 3.3.3
   @capacitor/android : not installed
   @capacitor/core    : 3.3.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v14.17.5 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.14
   OS     : Windows 10

**Comment by liamdebeasi** [comment] 2021-12-14 13:55
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/24353. This issue was already resolved, and a fix will be available in an upcoming release of Ionic.

**Closed by liamdebeasi** 2021-12-14 13:55 UTC
Labels: triage
