### ISSUE TITLE
bug: ion-router / ion-nav not unloading components when switching views (StencilJS app)

### ISSUE THREAD

**Issue by nathanb21** [ionic-team/ionic-framework#19498] opened 2019-09-30 08:13 UTC
# Bug Report

**Ionic version:**
[x] **4.10**

**Current behavior:**
Navigating to different routes using ion-router-link does not unload the previous component as route updates. If I load the routes backwards it changes.

I've uploaded a video demonstrating the issue on [Google Drive](https://drive.google.com/open?id=1dyazr4fjZBY0uS_CiEk7kgkGv0lPHl4V).

**Expected behavior:**
Navigate to new component and unload old component.

**Steps to reproduce:**
In a Stencil app define your `ion-router` with different routes and `ion-router-link` to navigate between. (See example code below on repo)

**Related code:**

Example: https://github.com/nathanb21/stencil-ionic-router-issue

**Comment by nathanb21** [comment] 2019-10-08 17:11
In the app I'm working on I'm using `HTMLIonRouterElement.push`. If I use a `RouterDirection` of `'root'` instead of `'forwards'` it functions correctly.

I guess this removes the ability to go 'back' and have proper history.

I'm working in Electron, where we're not using back/forwards functionality, so workaround works for my usecase!

**Comment by gopherrdiggs** [comment] 2021-02-03 21:53
Ran into this same issue. Like @nathanb21, I have to rely on the `ion-router` `push(url, 'root')` function, but if you watch the DOM as that's happening, `ion-nav` seems to respect that request and remove all previous child nodes, similar to the `setRoot` function on `ion-nav`. The biggest challenge in implementation is to avoid using `href` as the mechanism for routing because `ion-nav` will simply treat that as a push to the stack. 

This doesn't seem like a "bug," but it does seem like developers are forced to choose between well-defined routes or using ion-nav with navigation via component naming.

**Comment by liamdebeasi** [comment] 2022-05-18 19:03
Thanks for the issue and apologies for the delay. Things appear to be working as intended in the GitHub repo. A few things to note:

1. You are missing the global Ionic styles that are required for Ionic to work correctly. As a result, all of the views will be rendered as you navigate.

To fix this, create a `src/global.css` file and add `globalStyle: 'src/global.css',` to `stencil.config.ts`. Add the following inside of `global.css`:

```css
/* Core CSS required for Ionic components to work properly */
@import "~@ionic/core/css/core.css";

/* Basic CSS for apps built with Ionic */
@import "~@ionic/core/css/normalize.css";
@import "~@ionic/core/css/structure.css";
@import "~@ionic/core/css/typography.css";

/* Optional CSS utils that can be commented out */
@import "~@ionic/core/css/padding.css";
@import "~@ionic/core/css/float-elements.css";
@import "~@ionic/core/css/text-alignment.css";
@import "~@ionic/core/css/text-transformation.css";
@import "~@ionic/core/css/flex-utils.css";
```

You may need to restart the Stencil server to see these changes.

Note: The app layout will likely change. This is because the reproduction does not use the correct structural components such as `ion-header` and `ion-content`. Using those components should fix the layout issues.

2. Ionic keeps previous views around in the DOM intentionally. This allows us to support features such as swipe to go back on iOS.

For example, in order to swipe back from page B to page A, page A must still be in the DOM. As a result, when you push from the main page to page one, the main page remains in the DOM.

We also reuse views as appropriate. For example, if you go from /home --> /page-one --> /home, we will reuse the view for `/home`. As a result, this is the same as doing /home --> /page-one --> go back. 

If you want to push multiple instances of the same view, we recommend using parameterized routes (I.e `/page/:id`). This will allow you to push multiple instances of a view and avoid the view reuse strategy.

------

I am going to close this as this is not a bug in Ionic. If you are running into other problems, please feel free to open another issue. Thanks!

**Closed by liamdebeasi** 2022-05-18 19:03 UTC
Labels: triage
