### ISSUE TITLE
bug: Admob Free [ANDROID] plugin jerks the screen when updating ads. But it works on iOs and also worked with ionic 3.

### ISSUE THREAD

**Issue by ivanov84** [ionic-team/ionic-framework#21907] opened 2020-08-11 08:42 UTC
# Bug Report
Admob Free [ANDROID] plugin jerks the screen when updating ads. But it works on iOs and also worked with ionic 3.

**Ionic version:**
[x] **5.x**

**Current behavior:**
Admob Free [ANDROID] plugin jerks the screen when updating ads

**Expected behavior:**
Admob Free [ANDROID] plugin shoould not jerk the screen when updating ads

**Steps to reproduce:**
ionic 5
cordova-android 8.1.0
cordova-plugin-admob-free 0.27.0

**Related code:**
```
const options: AdMobFreeBannerConfig = {
  id: this.user.admobid.banner,
  isTesting: false,
  autoShow: false
};
this.adMobFree.banner.config(options);              
this.adMobFree.banner.prepare().then(() => {
  this.adMobFree.banner.show();
});
```

Other information:

on IOS+ionic5 with same plugin this is not happening - **works**
on ANDROID+IOS+ionic3 with same plugin this is not happening - **works**
on ANDROID+ionic5 with same plugin this is happening - **not works**

I think that something is wrong with scroll height for ion-tabs and ion-footer components. How can I stop to update position? At least can I delay a render effect for these components?

Also reported here:
https://github.com/ionic-team/ionic-native/issues/3504

Please look at gif:
![89662442-c489ee80-d8dc-11ea-8156-cc5c45b7a531](https://user-images.githubusercontent.com/9296077/89876841-e37fcd80-dbc7-11ea-94a3-961c68f1f9ba.gif)

**Comment by ivanov84** [comment] 2020-08-12 14:29
Just copy code that I provided and run on android device... How can I run on device here???

**Comment by liamdebeasi** [comment] 2020-08-17 15:02
Please provide this code reproduction as a GitHub repo that I can download and run. Code snippets are not typically enough for us to reproduce the issue.

**Comment by ivanov84** [comment] 2020-09-01 19:18
@liamdebeasi I think it would be easier just to download my app and look at this on real device. Because banner works only on device with configured admob ids.

Jerks appear not on start. Please use app at least 10 minutes to test - jerks pull ion-tabs also.

My app:
https://play.google.com/store/apps/details?id=club.olympapp.android

**Comment by liamdebeasi** [comment] 2020-09-02 13:45
I need to see the source code in order to correctly determine whether or not this is an Ionic Framework bug. I cannot resolve the issue if I cannot properly diagnose it first.

**Comment by ivanov84** [comment] 2020-09-03 13:49
@liamdebeasi done:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/9296077/92122731-819c3780-ee04-11ea-93d8-ee4dbeebd9ab.gif)

source:
https://olympapp.club/simple-tabs.rar

**Comment by liamdebeasi** [comment] 2020-09-03 15:04
Thanks, I was able to get ads to show using a test AdMob ID provided by Google: https://developers.google.com/admob/android/test-ads.

When loading/switching ads, I do see the tabs moving, but that is to be expected since the AdMob plugin appears to resize the webview whenever it loads in a new ad. Do you have an example of this working in Ionic Framework v3?

**Comment by ivanov84** [comment] 2020-09-03 15:19
@liamdebeasi yes:
http://olympapp.club/version-136.rar

**Comment by liamdebeasi** [comment] 2020-09-03 15:56
Thanks, are you able to provide the source code? I am unable to debug release APK packages in Chrome.

**Comment by ivanov84** [comment] 2020-09-03 16:32
@liamdebeasi right now I use latest version of ionic, so I cannot create an reproduction with ionic 3. Btw I noticed that in ionic 3 this thing happens too, but it's executing really fast, so it does not bother the user. Right now I'm trying to find a way to hold a view. If you have any suggestions how to fix it I would really thankfull to you.

**Comment by liamdebeasi** [comment] 2020-09-03 16:34
Do you have a debug build of the APK? I think I can use dev tools with that. It should be an `android-debug.apk` file I believe.

**Comment by ivanov84** [comment] 2020-09-03 16:42
@liamdebeasi sorry, I am not very experienced developer... I don't have a debug build... But ionic 3 build works fast - that's a reason that users accepted situation before.

**Comment by liamdebeasi** [comment] 2020-09-03 17:12
Thanks for the follow up. Unfortunately, I still do not see anything that would indicate this is a bug in Ionic Framework. The behavior I am seeing is that the webview is being resized when ads are shown. This is causing the tabs to move up/down which is to be expected when the webview is resizing from the bottom.

I think a fix for this would be to ensure that the admob plugin is not continually resizing the webview every time it switches ads. You might want to considering asking the admob plugin developer if there is a way to ensure that the banner ads do not constantly resize the webview. Perhaps there is a way to have a fixed area that ads can load into so the plugin does not need to completely hide the ad before showing another one.

**Closed by liamdebeasi** 2020-09-03 17:12 UTC
Labels: triage
