### ISSUE TITLE
bug: stacked modals missing backdrop and box-shadow (incl. repro)

### ISSUE THREAD

**Issue by bitflower** [ionic-team/ionic-framework#23278] opened 2021-05-06 08:34 UTC
# Bug Report

**Ionic version:**
[x] **5.5.6**

**Current behavior:**
Stacking modals in `ionic/core@5.6.6` I’m having issue with the backdrop and box-shadow of the 2nd modal. In my case it’s a “confirm dialog” on top of a “file gallery”. Looking at the HTML layering and CSS architecture all seems fine. z-indexes are in place just right. This is how it looks like:

![image](https://user-images.githubusercontent.com/6666636/117266797-e6a5a280-ae55-11eb-873a-05f6dc11807a.png)

I was able to fake the box-shadow on the small modal. But still I’m missing the covering effect of the backdrop over the 1. modal content. The rendered DOM:

![image (1)](https://user-images.githubusercontent.com/6666636/117266832-f2916480-ae55-11eb-9210-531ac39bd2da.png)

When I move the 2nd modal up in the DOM in the DevTools I get a bit closer but **losing the shadow** in the “big” modal:

![image (2)](https://user-images.githubusercontent.com/6666636/117266872-fd4bf980-ae55-11eb-8f88-804f3107123a.png)

Outcome:

![image (3)](https://user-images.githubusercontent.com/6666636/117266903-050b9e00-ae56-11eb-88ca-b5341d03b994.png)

I fiddled with all kinds of `z-index` variations without luck. 

**Expected behavior:**
- modal 1 is covered with backdrop of modal 2
- modal 2 has box-shadow

**Steps to reproduce:**
See repo: https://github.com/bitflower/modal-test

`npm i`
`npm start`

Click button "Open Profile in Modal"
Click button "Delete"

**Related code:**
https://github.com/bitflower/modal-test

**Ionic info:**

This is a pure Stencil app. No framework. I never use the CLI hence the version below doesn't matter.

```
Ionic:

   Ionic CLI : 5.4.16

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v14.8.0
   npm    : 6.14.11
   OS     : macOS Catalina
```

**Comment by DwieDima** [comment] 2021-05-06 12:47
this was added on purpose, heres the issue

https://github.com/ionic-team/ionic-framework/issues/20800

you can add backdrop opacity by providing `--backdrop-opacity: 0.3;` to your modal.

**Comment by liamdebeasi** [comment] 2021-05-06 13:07
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. This is intentional as pushing many modals would cause the content behind the modal to become very dark otherwise. To disable this behavior, you can set `--backdrop-opacity` to a non-zero value as mentioned in https://github.com/ionic-team/ionic-framework/issues/23278#issuecomment-833494491.

**Closed by liamdebeasi** 2021-05-06 13:07 UTC
Labels: triage

**Comment by bitflower** [comment] 2021-05-06 13:14
Hi guys, thanks for the quick reply. Just tried and while it solves the covering of the previous modal content it doesn't for the shadow on the 2nd modal box. The 2nd issue also persists: the shadow in the previous modal gets lost. See the result:

![Bildschirmfoto 2021-05-06 um 15 13 09](https://user-images.githubusercontent.com/6666636/117304127-b114af80-ae7d-11eb-9742-c83bae1688d2.png)

Just let me know if this an edge you maybe think of solving. If so I could get my hands dirty and try to provide a PR. If not I'll probably solve it "locally".

Thanks!

**Comment by liamdebeasi** [comment] 2021-05-06 13:21
Thanks for the follow up. So we typically work under the assumption that stacked modals are the same size and only show the shadow on the first modal, otherwise you would run into the same problem as with stacking the backdrops. The solution here is to set the `--box-shadow` var on the small modal as well. 

Here are the exact values we use for MD mode:

```css
--box-shadow: 0 28px 48px rgba(0, 0, 0, 0.4);
--backdrop-opacity: var(--ion-backdrop-opacity, 0.32);
```

**Comment by bitflower** [comment] 2021-05-06 13:28
Wow, @liamdebeasi I'm impressed! I'll see what I can come up with for the docs to represent this. As a minimum contribution!

**Comment by bitflower** [comment] 2021-05-06 18:59
Here you go: https://github.com/ionic-team/ionic-framework/pull/23279
