### ISSUE TITLE
Ionic 4 text highlight selection not working as expected

### ISSUE THREAD

**Issue by kkbrains** [ionic-team/ionic-framework#17753] opened 2019-03-12 00:05 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

Highlighting text selection component is not staying on the selected region
**Expected behavior:**

Text Highlight selection have to stay on the selected region. Expected to work like on Safari or other browser text selection
**Steps to reproduce:**

Create a new ionic 4 app, load div text items inside ion-content and enable user-select for ion-content in CSS

**Related code:**

![ezgif-1-b611fd736f57](https://user-images.githubusercontent.com/21117138/54165867-aa18cf00-44b6-11e9-8b8d-ff64af0b6c53.gif)

**Comment by brandyscarney** [comment] 2019-04-16 17:04
Thanks for the issue!

Note to team: I was able to reproduce this using the following test: http://localhost:3333/src/components/select/test/standalone

And adding an `ion-app`/`ion-content` wrapper with this CSS:

```
ion-content {
  user-select: text;
  -webkit-user-select: text;
}
```

Loading it in Safari on my phone allowed me to reproduce.

**Comment by larpo1** [comment] 2019-07-03 12:44
Can confirm this is still a problem. Any update?

**Comment by liamdebeasi** [comment] 2021-03-31 20:11
Hi everyone,

It looks like this was an issue in WebKit that has since been fixed. On iOS 14 I can observe that the blue highlight hides while scrolling and re-appears in the correct location after stopping. Closing as the issue has been fixed on newer versions of iOS.

**Closed by liamdebeasi** 2021-03-31 20:11 UTC
Labels: package: core, type: bug
