### ISSUE TITLE
bug: popover of useIonPopover only triggered once

### ISSUE THREAD

**Issue by dizayn-design** [ionic-team/ionic-framework#24580] opened 2022-01-14 22:13 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

the popover of `useIonPopover` can only be triggered once when a `trigger` is used.

### Expected Behavior

the popover should be triggerable countless times.

### Steps to Reproduce

Just press the 'Foo' button of the following sample code multiple times:

```
import React from 'react';
import {
  IonButton,
  IonContent,
  IonItem,
  IonList,
  IonListHeader,
  IonPage,
  useIonPopover,
} from '@ionic/react';

const PopoverList: React.FC<{
  onHide: () => void;
}> = () => (
  <IonList>
    <IonListHeader>Ionic</IonListHeader>
    <IonItem button>Learn Ionic</IonItem>
  </IonList>
);

const Experiment: React.FC = () => {

  const [presentWithElement, dismissWithElement] = useIonPopover(
    <PopoverList onHide={() => dismissWithElement()} />
  );

  return (
    <IonPage>
      <IonContent>
        <IonButton
        id='foo'
          expand="block"
          onClick={(e) =>
            presentWithElement({
              trigger: 'foo',
              reference: 'trigger', side: 'bottom', triggerAction: 'context-menu'
            })
          }
        >
          Foo
        </IonButton>
      </IonContent>
    </IonPage>
  );
};

export default Experiment;
```

### Ionic Info

Ionic:

   Ionic CLI       : 6.18.1 (C:\Users\User\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/react 6.0.2

Utility:

   cordova-res : 0.15.3
   native-run  : 1.5.0

System:

   NodeJS : v16.13.0 (C:\Program Files\nodejs\node.exe)
   npm    : 8.1.0

**Comment by amandaesmith3** [comment] 2022-01-18 21:44
Thanks for the issue. The `trigger` prop and `useIonPopover` hook are two separate methods of presenting, and aren't meant to be used at the same time on the same popover. Below is an example using only `trigger`; could you give it a try and let me know if it resolves your issue?

Note that `onHide` is no longer needed since you can click outside the popover to close it automatically, or set `dismissOnSelect={true}` on the `IonPopover` to have it dismiss when an option is selected. If you'd like more fine-grained control over whether the popover is open, while still being able to easily set props on the `IonPopover` itself, you may find the `isOpen` prop easier ([docs](https://ionicframework.com/docs/api/popover#inline-popover-with-state)).

```tsx
const PopoverList: React.FC = () => (
  <IonList>
    <IonListHeader>Ionic</IonListHeader>
    <IonItem button>Learn Ionic</IonItem>
  </IonList>
);

const Experiment: React.FC = () => {
  return (
    <IonPage>
      <IonContent>
        <IonButton id='foo' expand='block'>Foo</IonButton>
        <IonPopover trigger='foo' side='bottom' triggerAction='context-menu'>
          <PopoverList />
        </IonPopover>
      </IonContent>
    </IonPage>
  );
};
```

**Comment by dizayn-design** [comment] 2022-01-27 21:07
unfortunately your sample doesn't work for me. No Popover gets shown when pressing the button.

**Comment by amandaesmith3** [comment] 2022-01-27 21:18
Are you right-clicking the button? I carried over your use of `triggerAction='context-menu'`, which causes the popover to appear on right-click in place of the default context menu behavior.

**Comment by dizayn-design** [comment] 2022-01-27 21:20
oh I see.. sorry for that. When I right-click it appears.

**Comment by amandaesmith3** [comment] 2022-01-27 21:25
Excellent 👍 I'm going to go ahead and close this issue out since it sounds like things are resolved. If you had any other concerns, feel free to open a separate issue with its own reproduction. Thank you for using Ionic!

**Closed by amandaesmith3** 2022-01-27 21:25 UTC
Labels: triage
