### ISSUE TITLE
bug: ngOnInit executes again after navigating back to the page

### ISSUE THREAD

**Issue by dan-mrwebsites** [ionic-team/ionic-framework#28999] opened 2024-02-08 06:16 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

ngOnInit seems to execute again after navigating back to the page that was previously initialize or loaded. My understanding based on the documentation is that ngOnInit should execute only once during initialization and ionViewDidEnter should fire every time the page is loaded or navigating back to the page.

### Expected Behavior

We are expecting that ngOnInit should execute only once when the page is initialized or loaded. And also ngOnInit should not execute again when the user navigate back to the pages that was previously loaded or initialized.

### Steps to Reproduce

1. Home page is loaded by default when app starts (ngOnInit and ionViewDidEnter executes)
2. Click Open Second page (ngOnInit and ionViewDidEnter executes)
3. Click Open Third page (ngOnInit and ionViewDidEnter executes)
4. Click Open Second page (only ionViewDidEnter executes) *which is what we expect
5. Click Open Third page (ngOnInit and ionViewDidEnter executes) *we expect that only ionViewDidEnter should execute here

### Code Reproduction URL

https://github.com/dan-mrwebsites/myTestGitHub.git

### Ionic Info

Ionic:

   Ionic CLI                     : 7.1.1 (C:\Users\Dan\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 7.7.1
   @angular-devkit/build-angular : 17.1.2
   @angular-devkit/schematics    : 17.1.2
   @angular/cli                  : 17.1.2
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.7.0
   @capacitor/android : 5.7.0
   @capacitor/core    : 5.7.0
   @capacitor/ios     : 5.7.0

Utility:

   cordova-res : 0.15.3
   native-run  : 2.0.1

System:

   NodeJS : v20.11.0 (C:\Program Files\nodejs\node.exe)
   npm    : 10.4.0
   OS     : Windows 10

**Comment by liamdebeasi** [comment] 2024-02-08 14:13
Thanks for the report. I can reproduce the reported behavior, but this is not a bug in Ionic. The reason this is happening is when you go from `/three` to `/second`, Ionic re-uses the existing `/second` instance already in the stack. As a result, going from `/three` to the existing `/second` is the same as doing `/three` and then going back. In other words, the view for `/three` is popped off the stack, and the component associated with it is destroyed. When you go to `/three` again, a new instance of the view is created, so `ngOnInit` fires.

 The behavior here is a bit unusual for navigation, and we're looking to improve this behavior in the future. Typically in mobile applications pushing multiple instances of the same view is confusing since they visually look the same, but any data on the original instance is perceived to have been lost because the user does not know that there are 2 instances of the same view. Ionic tries to automatically account for that with this behavior.

I am going to close this since this is not a bug in Ionic, but let me know if you have any questions.

**Closed by liamdebeasi** 2024-02-08 14:13 UTC
Labels: triage
