### ISSUE TITLE
bug: ion-datetime navigation skips months

### ISSUE THREAD

**Issue by maxcaber** [ionic-team/ionic-framework#24743] opened 2022-02-08 19:32 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

When swiping left to right or clicking the arrow navigation buttons the calendar will advance or retrieve two months instead of going to the next or previous month.

### Expected Behavior

Clicking the next month arrow, the calendar should advance to the next month.

### Steps to Reproduce

The is reproduced in the ionic documentation demo, as well as running the sample React code on this page: https://ionicframework.com/docs/api/datetime

### Code Reproduction URL

https://ionicframework.com/docs/api/datetime

### Ionic Info

Microsoft Windows [Version 10.0.19042.1466]
(c) Microsoft Corporation. All rights reserved.

C:\Temp\ionic-test>ionic info
[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module
       '@capacitor/ios/package'
       
       Require stack:
       - C:\Users\Max Caber\AppData\Roaming\npm\node_modules\@ionic\cli\lib\project\index.js
       - C:\Users\Max Caber\AppData\Roaming\npm\node_modules\@ionic\cli\lib\index.js        
       - C:\Users\Max Caber\AppData\Roaming\npm\node_modules\@ionic\cli\index.js
       - C:\Users\Max Caber\AppData\Roaming\npm\node_modules\@ionic\cli\bin\ionic
[WARN] Error loading @capacitor/android package.json: Error: Cannot find module
       '@capacitor/android/package'

       Require stack:
       - C:\Users\Max Caber\AppData\Roaming\npm\node_modules\@ionic\cli\lib\project\index.js    
       - C:\Users\Max Caber\AppData\Roaming\npm\node_modules\@ionic\cli\lib\index.js
       - C:\Users\Max Caber\AppData\Roaming\npm\node_modules\@ionic\cli\index.js
       - C:\Users\Max Caber\AppData\Roaming\npm\node_modules\@ionic\cli\bin\ionic

Ionic:

   Ionic CLI       : 6.18.1 (C:\Users\Max Caber\AppData\Roaming\npm\node_modules\@ionic\cli)    
   Ionic Framework : @ionic/react 6.0.5

Capacitor:

   Capacitor CLI      : 3.4.0
   @capacitor/android : not installed
   @capacitor/core    : 3.4.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v14.18.0 (C:\Program Files\nodejs\node.exe)
   npm    : 7.24.1
   OS     : Windows 10

**Comment by amandaesmith3** [comment] 2022-02-08 21:09
Thanks for the issue. I'm going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/24712.

**Closed by amandaesmith3** 2022-02-08 21:09 UTC
Labels: triage

**Comment by maxcaber** [comment] 2022-02-08 21:13
I'm sorry, I thought I searched everything before posting.  Can you send me a link to where I would have found that already existing issue?  Thanks,Max
    On Tuesday, February 8, 2022, 01:09:37 PM PST, Amanda Smith ***@***.***> wrote:  
 
 


Thanks for the issue. I'm going to close this as a duplicate of #24712.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by amandaesmith3** [comment] 2022-02-08 21:19
You can search issues in the framework repo here: https://github.com/ionic-team/ionic-framework/issues This one may have slipped under your radar because it was already closed (since the fix has been merged in and will be released soon) and the search defaults to open issues only. Removing the `is:open` from the search and trying the keywords `datetime month` yields the original issue as well as other duplicates that were opened recently.

**Comment by maxcaber** [comment] 2022-02-09 03:21
Thanks!
    On Tuesday, February 8, 2022, 01:19:39 PM PST, Amanda Smith ***@***.***> wrote:  
 
 


You can search issues in the framework repo here: https://github.com/ionic-team/ionic-framework/issues This one may have slipped under your radar because it was already closed (since the fix has been merged in and will be released soon) and the search defaults to open issues only. Removing the is:open from the search and trying the keywords datetime month yields the original issue as well as other duplicates that were opened recently.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
