### ISSUE TITLE
bug: Ion-sellect inside of ion-popover

### ISSUE THREAD

**Issue by victororlyk** [ionic-team/ionic-framework#19979] opened 2019-11-23 11:31 UTC
# Bug Report

**Ionic version:**

[x] **4.6.3**

**Current behavior:**

when I use select inside of popover it is going under the general popover
**Expected behavior:**

the select popover should be on top of general popover
**Steps to reproduce:**

**Related code:**

```
import React from 'react';
import { IonHeader, IonToolbar, IonPage, IonTitle, IonContent, IonButton } from '@ionic/react';

async function presentPopover(event: React.SyntheticEvent) {
  const popoverElement = Object.assign(document.createElement('ion-popover'), {
    component: 'popover-example-page',
    event: event
  });
  document.body.appendChild(popoverElement);
  return await popoverElement.present();
}

customElements.define('popover-example-page', class ModalContent extends HTMLElement {
  connectedCallback() {
    this.innerHTML = `
          <ion-list>
            <ion-list-header>Ionic</ion-list-header>
            <ion-item button>Learn Ionic</ion-item>
            <ion-item button>Documentation</ion-item>
            <ion-item button>Showcase</ion-item>
             <ion-select interface="popover">
              <ion-select-option value="nes">NES</ion-select-option>
              <ion-select-option value="n64">Nintendo64</ion-select-option>
              <ion-select-option value="ps">PlayStation</ion-select-option>
              <ion-select-option value="genesis">Sega Genesis</ion-select-option>
              <ion-select-option value="saturn">Sega Saturn</ion-select-option>
              <ion-select-option value="snes">SNES</ion-select-option>
          </ion-select>
          </ion-list>
          <ion-button expand="block" onClick="dismissPopover()">Close</ion-button>
        `;
  }
});
const Tab3Page: React.FC = () => {
  return (
    <IonPage>
      <IonHeader>
        <IonToolbar>
          <IonTitle>Tab Three</IonTitle>
        </IonToolbar>
      </IonHeader>
      <IonContent >
<IonButton onClick={presentPopover}>hello</IonButton>
      </IonContent>
    </IonPage>
  );
};

export default Tab3Page;

```

**Other information:**

<img width="408" alt="Screenshot 2019-11-23 at 13 30 26" src="https://user-images.githubusercontent.com/33072590/69477966-74720700-0df5-11ea-8715-7d163675776d.png">

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by charlesj1** [comment] 2020-01-28 21:43
This is a problem for me too. As well as being poor UI, the user is unable to make a selection without closing the popover in the process, so switching the ion-select interface to action-sheet doesn't work as a workaround.

**Comment by liamdebeasi** [comment] 2021-09-16 17:09
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. This is not the correct usage of `IonPopover` in a React environment.

The main issue is that `IonSelect` is being attached inside of `IonApp`, but you are attaching `IonPopover` to the `body`. `body` is one level higher up in the DOM than `IonApp`, so the popover is always going to appear on top of `IonSelect`.

Since this is an issue from 2019, it is likely that some of our docs were not quite right when it comes to Ionic React usage. I recommend taking a look at the popover docs again as they have the latest React usage: https://ionicframework.com/docs/api/popover#usage and https://ionicframework.com/docs/api/select#usage (You may need to click the "React" tab under the "Usage" heading). 

Using the examples above, I was able to get the select to correctly appear on top of the popover.

**Closed by liamdebeasi** 2021-09-16 17:09 UTC
Labels: triage
