### ISSUE TITLE
bug: ion-tabs creates an uncontrollable ion-router-outlet

### ISSUE THREAD

**Issue by fobaz** [ionic-team/ionic-framework#21748] opened 2020-07-14 03:30 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**
Using ionic-angular with Angular 10.

**Current behavior:**

 `<ion-tabs>` creates a new `<ion-router-outlet>`

**Expected behavior:**

Should use the nearest router-outlet, or, I suggest one specified in an attribute.

**Other information:**

Not sure if this is a bug report or a feature/help request.
What I am trying to do is to have a specific layout. Pseudo code:
```
<ion-tabs outlet="main">tabs and etc.</ion-tabs>
<ion-grid>
<ion-col>1</ion-col>
<ion-col> <ion-router-outlet name="main"> ...should be used by ion-tabs... </ion-router-outlet></ion-col>
<ion-col>2</ion-col>
</ion-grid>
```

**Comment by liamdebeasi** [comment] 2020-07-14 13:32
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. You should not be placing a nested `ion-router-outlet` inside of `ion-tabs`. The tabs context is a separate navigation context from the root `ion-router-outlet`. If you are trying to make child pages within the tabs context, you should use the `tabs-routing.module.ts` file instead. While we do not recommend manually controlling the router outlet created by `ion-tabs`, you can use a `querySelector` to get a reference to it and call its methods.

**Closed by liamdebeasi** 2020-07-14 13:32 UTC
Labels: triage
