### ISSUE TITLE
bug: Cannot change display mode of the component dynamically

### ISSUE THREAD

**Issue by turanofff** [ionic-team/ionic-framework#29429] opened 2024-05-01 00:37 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

I am trying to change the look of `ion-radio` dynamically between `ios` and `md' mode and it doesn't work as expected. 

### Expected Behavior

The look of component changes according to the mode settings.

### Steps to Reproduce

I have prepared a stackblitz example of what's happening.

When flicking between the modes nothing happen until you toggle visibility. But it also looks like after initial visibility toggle, the global `mode` setting will alway prevail no matter what is set on component level. 

### Code Reproduction URL

https://stackblitz.com/edit/angular-ywh4p1-sevh9y

### Ionic Info

ionic core 7.6.2
ionic angular 7.6.2.
angular core 17.0.1

**Comment by liamdebeasi** [comment] 2024-05-01 13:29
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. This is to be expected. The mode property, along with the global Ionic config, is not designed to be reactive. If you'd like to change the mode on a property you'll need to render a new instance of the component.

**Closed by liamdebeasi** 2024-05-01 13:29 UTC
Labels: triage
