### ISSUE TITLE
bug: datetime max min timezone issue

### ISSUE THREAD

**Issue by NormanV41** [ionic-team/ionic-framework#24242] opened 2021-11-18 00:01 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [X] v6.x

### Current Behavior

To reproduce the issue, follow these steps:

- Set up a basic ion-datetime field.
- Set min and max to "2021-11-02T04:00:00.000Z", and "2021-12-01T04:00:00.000Z", respectively. Note that the local timezone for me is Central Standard Time (GMT-6) so the min and max date value in my timezone is "2021-11-01" and "2021-11-30" respectively.

The result shown is that the allowed dates to introduce are from 2021-11-02 to 2021-12-01. Since ion-datetime values correctly consider the local timezone, the date 2021-11-01 has to be allowed, and 2021-12-01 should not be allowed.

### Expected Behavior

The expected behavior is that ion-datetime calculate correctly the dates allowed taking into consideration the timezone.

### Steps to Reproduce

- Set up a basic ion-datetime field.
- Set min and max to "2021-11-02T04:00:00.000Z", and "2021-12-01T04:00:00.000Z", respectively. Note that the local timezone for me is Central Standard Time (GMT-6) so the min and max date value in my timezone is "2021-11-01" and "2021-11-30" respectively.

### Code Reproduction URL

https://github.com/NormanV41/datetime-min-max-issue

### Ionic Info

WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package'
       
       Require stack:
       - /usr/lib/node_modules/@ionic/cli/lib/project/index.js
       - /usr/lib/node_modules/@ionic/cli/lib/index.js
       - /usr/lib/node_modules/@ionic/cli/index.js
       - /usr/lib/node_modules/@ionic/cli/bin/ionic
[WARN] Error loading @capacitor/android package.json: Error: Cannot find module '@capacitor/android/package'
       
       Require stack:
       - /usr/lib/node_modules/@ionic/cli/lib/project/index.js
       - /usr/lib/node_modules/@ionic/cli/lib/index.js
       - /usr/lib/node_modules/@ionic/cli/index.js
       - /usr/lib/node_modules/@ionic/cli/bin/ionic

Ionic:

   Ionic CLI                     : 6.18.0 (/usr/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.0-rc.3
   @angular-devkit/build-angular : 12.1.4
   @angular-devkit/schematics    : 12.1.4
   @angular/cli                  : 12.1.4
   @ionic/angular-toolkit        : 4.0.0

Capacitor:

   Capacitor CLI      : 3.2.5
   @capacitor/android : not installed
   @capacitor/core    : 3.2.5
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.3
   native-run  : 1.5.0

System:

   NodeJS : v14.16.1 (/usr/bin/node)
   npm    : 6.14.12
   OS     : Linux 5.14

  ─────────────────────────────────────────────────

     Ionic CLI update available: 6.18.0 → 6.18.1
          Run npm i -g @ionic/cli to update

  ─────────────────────────────────────────────────

**Comment by liamdebeasi** [comment] 2022-06-13 15:25
Thanks for the issue. After discussing this issue with the team, we have determined that `ion-datetime` is working as intended here. According to the [ion-datetime Time Zone documentation](https://ionicframework.com/docs/api/datetime#time-zones), this component intentionally does not manipulate or set the time zone inside of a datetime control. This means that developers are responsible for handling any time zone conversions themselves with a library such as [date-fns-tz](https://github.com/marnusw/date-fns-tz). This was done to provide a consistent and predictable experience for app developers.

I am going to close this. Thanks!

**Closed by liamdebeasi** 2022-06-13 15:25 UTC
Labels: package: core, type: bug
