### ISSUE TITLE
bug: ion-slides regression in modals (unusable after 4.11.0)

### ISSUE THREAD

**Issue by omardoma** [ionic-team/ionic-framework#19638] opened 2019-10-11 19:25 UTC
# Bug Report

**Ionic version:**

**4.11.0**

**Current behavior:**
ion-slides now behaves strangely when placed in modals after v4.11.0, touch events aren't correctly handled and scrolling is not working, as well as layout is stretched with incorrect dimensions calculation.

v4.10.3 is working correctly.

**Expected behavior:**
It should work as before

**Steps to reproduce:**
Put an ion-slides with 2 or 3 photos in a modal page and present it, try to drag left or right, you will get stuck between photos.

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.4.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.0
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.2, (and 12 other plugins)

Utility:

   cordova-res : 0.6.0 (update available: 0.8.0)
   native-run  : 0.2.8 

System:

   Android SDK Tools : 26.1.1 (/Users/omardoma/Library/Android/sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.2
   NodeJS            : v10.16.3 (/usr/local/Cellar/node@10/10.16.3/bin/node)
   npm               : 6.9.0
   OS                : macOS Mojave
   Xcode             : Xcode 11.1 Build version 11A1027
```

**Comment by liamdebeasi** [comment] 2019-10-11 19:47
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue? The 4.11.0 release just had Ionic React changes, so nothing in your Ionic Angular app should be different.

**Comment by omardoma** [comment] 2019-10-13 09:47
Sorry for the late reply, I have prepared a StackBlitz demo with my current code: https://stackblitz.com/edit/ionic-v4-slides-modal-bug

However what's weird is that the bug happens non-deterministically, sometimes it happens, sometimes it doesn't, If I had to make a guess, then I would say something is blocking the slides from  loading and firing the ionSlidesDidLoad event, that's why the swiping functionality and the layout is messed up.

I will investigate further and post my findings, till then please let me know if there is anything else I can help with in debugging it.

**Comment by liamdebeasi** [comment] 2019-10-18 16:09
Thanks for the follow up. I am unable to reproduce this issue using the repo you provided. Is this happening on a particular platform (iOS vs Android)?

**Comment by omardoma** [comment] 2019-10-22 00:09
Well it happens on all platforms (Browser, iOS & Android), basically what happens is, sliding becomes very glitchy, and the slides size becomes very expanded.

I believe a new issue #19641 refers to the same problem happening on React.

**Comment by omardoma** [comment] 2019-10-22 00:12
Till now I am unable to narrow down the factors that lead to the bug, all I know at the moment is that slides behave non-deterministically when places inside modals, and downgrading to 4.10.3 fixes the issue. I know the 4.11.0 release only added React support and that it doesn't make sense, but that's what I could find by trial and error.

**Comment by omardoma** [comment] 2019-10-22 00:19
I have tried opening the StackBlitz demo I have provided and I believe that you can replicate the behavior if you open the modal, try sliding the image slowly halfway. If it doesn't occur then try closing the modal and retrying the mentioned steps again.

One thing I noticed is, if the bug occurs, triggering a window resize event by maybe opening the console, fixes the slides and it works normally.

**Comment by liamdebeasi** [comment] 2019-10-22 12:58
Are there any particular steps to reproduce that I should be following? I am still unable to reproduce the issue using the StackBlitz.

**Comment by SimonGolms** [comment] 2019-10-23 12:31
I can confirm the bug with the StackBlitz example as I am also affected by the linked issue for the react package.

Unfortunately, the error really occurs randomly and cannot really be reproduced . You can try to swipe back and forward several times with e.g. pressed mouse button, close modal and open it again and redo some swiping. Repeat the process multiple times until the bug appears.

Example where it happens after the first try:
![23-10-_2019_14-28-45](https://user-images.githubusercontent.com/17799657/67392860-96336080-f5a1-11e9-94e0-f7b657800848.gif)

**Comment by omardoma** [comment] 2019-10-23 14:29
One thing to note is that the bug can be fixed whenever it occurs by simple triggering a window resize

**Comment by marpstar** [comment] 2019-10-23 18:54
We're seeing this issue as well. Oddly if we switch our tsconfig's `target` to `es5` instead of `es2015` it seems to work consistently.

**Comment by omardoma** [comment] 2019-10-24 09:08
@marpstar That's really weird. In my case, I can't really change the target to es5 because I am using Angular 8 and its differential loading, so doing so will disable it.

**Comment by marpstar** [comment] 2019-10-24 12:55
@omardoma I agree that switching back to ES5 isn’t ideal. I’d like to see this fixed but thought the ES5 tidbit was worth mentioning for anyone who tries to fix.

**Comment by omardoma** [comment] 2019-10-24 15:13
@marpstar Yeah definitely, thanks a lot for mentioning that, will fallback to it if the issue wasn't fixed shortly!

**Comment by omardoma** [comment] 2019-10-30 00:12
@liamdebeasi Any update on this issue, please? We really want to update our Ionic version to the latest to get some bug fixes we need, but this issue is holding us back

**Comment by SimonGolms** [comment] 2019-10-30 08:08
> One thing to note is that the bug can be fixed whenever it occurs by simply triggering a window resize

Good hint. I was able to fix it with the following exemplary workaround for my use case.

```html
// slides-modal.component.html
...
<ion-content>
  <ion-slides #sliderRef>
    <ion-slide>
       ...
    </ion-slide>
  </ion-slides>
</ion-content>
...
```

```javascript
// slides-modal.component.ts
import { Component, OnInit, ViewChild } from '@angular/core';
import { ModalController, IonSlides } from '@ionic/angular';

@Component({
  selector: 'app-slides-modal',
  templateUrl: './slides-modal.component.html',
  styleUrls: ['./slides-modal.component.scss']
})
export class SlidesModalComponent implements OnInit {

  @ViewChild('sliderRef', { static: true }) protected slides: IonSlides;

  constructor(private modalController: ModalController) {}

  ngOnInit() {
    this.slides.update();
  }
}
```

**Comment by liamdebeasi** [comment] 2019-10-30 14:30
Hi everyone,

I was able to reproduce this issue. I will look into this a bit more. Thanks!

**Comment by liamdebeasi** [comment] 2019-10-30 15:26
I was able to reproduce this bug in Ionic 4.10.0, so it doesn't seem like a 4.11 regression. I'm going to dig into this a bit more and see where the bug originally appeared.

**Comment by omardoma** [comment] 2019-10-30 16:19
Great, thanks for looking into that, feel free to rename the issue's name if it applies in 4.10.x as well. I named it this way because it never happened with me except past 4.11.x

**Comment by ctcampbell** [comment] 2019-11-18 14:56
FWIW that workaround doesn't work for me.

**Comment by ctcampbell** [comment] 2019-11-25 16:14
Any progress being made on this?

**Comment by netsesame2** [comment] 2019-12-04 08:13
My issue is slides will not swipe in a modal when it is first opened. Open the modal again, the slides works.

Following the above suggest, I solved the issue simply by add a .update() call:
```
slides.update();
```
Don't know why.

**Comment by bohdanbirdie** [comment] 2019-12-04 11:26
@netsesame2 thanks for the hint, looks like it worked for me

+1 to this issue tho

**Comment by tiagomsmagalhaes** [comment] 2019-12-10 17:45
I have found this issue without the modal use case, just simple routing back and forth.

After trying `ChangeDetectorRef` or @SimonGolms solution without success I have added a ngIf to my slider-wrapper and set the variable to true on `AfterContentChecked`and it worked without hiccups. 

Haven't tried on previous hooks.

**Comment by ebk46** [comment] 2020-01-03 04:09
I'm having this issue as well. I'm using React 4.11.7, and in addition to the sliding problem, I also have a problem where sometimes the slide simply will not work at all. I can swipe and it emits the onIonSlideNextStart / ...PrevStart events but the slide itself does not change.

**Comment by ctcampbell** [comment] 2020-01-05 09:44
Any chance of this getting fixed?

**Comment by ctcampbell** [comment] 2020-01-13 17:50
Why is nobody from the Ionic team even acknowledging that this problem needs resolution?

**Comment by liamdebeasi** [comment] 2020-01-13 18:15
Hi,

I am hiding your comment as it is off topic and not constructive to getting this issue resolved. I will try to take a look at this issue this week.
We have acknowledged this is an issue [here](https://github.com/ionic-team/ionic/issues/19638#issuecomment-547963461). We are looking into a resolution; however, since it appears randomly it is a bit tricky to resolve. Additionally, a few users on this thread have provided temporary workarounds. I will post another update here when I have more information to share.

**Comment by SimonGolms** [comment] 2020-02-11 20:11
Hi @liamdebeasi, any news regarding this bug?
I noticed that after calling `modal.present()` several times with a `<ion-slides>` component, the nested `<ion-slide>` elements are not handled correctly. In case this bug appears, `swiper.length()` returns `0`. 

While my first [workaround](https://github.com/ionic-team/ionic/issues/19638#issuecomment-547782785) unfortunately didn't really work, I want to share another possible workaround, were I was not able to reproduce the bug after intensive testing.

```html
// slides-modal.component.html
...
<ion-content>
  <ion-slides #sliderRef></ion-slides>
</ion-content>
...
```

```javascript
// slides-modal.component.ts
import { Component, OnInit, ViewChild } from '@angular/core';
import { ModalController, IonSlides } from '@ionic/angular';

@Component({
  selector: 'app-slides-modal',
  templateUrl: './slides-modal.component.html',
  styleUrls: ['./slides-modal.component.scss']
})
export class SlidesModalComponent implements OnInit {

  @ViewChild('sliderRef', { static: true }) protected slides: IonSlides;

  src = './assets/img.png'
  constructor(private modalController: ModalController) {}

  async ngOnInit() {
    const swiper = await this.slides.getSwiper();
    swiper.appendSlide(`<ion-slide><img src="${this.src}"/></ion-slide>`);
    ...
  }
}
```

**Comment by NikolaDeveloper** [comment] 2020-02-20 18:54
Is there any workaround for react?

**Comment by FranzSw** [comment] 2020-03-02 13:53
Would love to hear some news on this.

@NikolaDeveloper Here's a one line fix / workaround for React:
```
// ...
<IonSlides onIonSlidesDidLoad={function(this: any){this.update()}}>
//...
```

It basically just calls `update` on IonSlides after loading.

**Comment by robsonos** [comment] 2020-04-20 13:17
Fixed it with the ionViewDidEnter hook instead:

`
ngOnInit() {
    this.slides.update();
  }
`

**Comment by kheftel** [comment] 2020-08-09 01:27
For anyone that's interested, with `@ionic/angular` 5.2.1, I had to change the workaround to the following for pagination to work on the second load of the modal. Looks like you have to use `ElementRef<IonSlides>` instead of using `IonSlides` directly with `ViewChild`. Took me a couple days to figure this out so I'm posting in case anyone else is stuck on it.

template:
```
<ion-slides pager="true" #sliderRef>
```

component:
```
@Component({
  selector: 'app-slidesmodal',
  templateUrl: 'slidesmodal.page.html',
  styleUrls: ['slidesmodal.page.scss'],
})
export class SlidesModalPage {
  @Input() modalController: ModalController
  @ViewChild('sliderRef') slides: ElementRef<IonSlides>;

  constructor(
  ) {}

  ionViewDidEnter() {
    this.slides.nativeElement.update();
  }
}
```

ionic info:
```
Ionic:

   Ionic CLI                     : 6.10.1
   Ionic Framework               : @ionic/angular 5.2.1
   @angular-devkit/build-angular : 0.901.8
   @angular-devkit/schematics    : 9.1.7
   @angular/cli                  : 9.1.8
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 2.2.1
   @capacitor/core : 2.3.0

Utility:

   cordova-res (update available: 0.15.1) : 0.14.0
   native-run                             : 1.0.0

System:

   NodeJS : v12.17.0
   npm    : 6.14.5
   OS     : macOS Catalina
```

**Comment by dimitribocquet** [comment] 2020-08-12 06:41
@kheftel Is you have only one `ion-slides` in your component, you can do that to get `IonSlides` without `ElementRef` :

```
@ViewChild(IonSlides) slides: IonSlides;

ionViewWillEnter() {
	this.alive = true;
	this.slides.update()
}
```

**Comment by kheftel** [comment] 2020-08-12 18:26
> @kheftel If you have only one `ion-slides` in your component, you can do that to get `IonSlides` without `ElementRef` :
> 
> ```
> @ViewChild(IonSlides) slides: IonSlides;
> 
> ionViewWillEnter() {
> 	this.slides.update()
> }
> ```

I tried that first, but, sadly it didn't work and my slides variable was still an `ElementRef`, and iirc its `nativeElement` didn't have an `update` function.

**Comment by rastafan** [comment] 2020-09-28 09:34
We stumpled upon something like this these days. Rendering an ion-slides inside a modal causes the ion-slides component to be rendered wrong.

More specifically, the slides are rendered "centered" inside the ion-slides. We have three slides, so we see the second one in the screen, and inspecting the dom the first slide is on the right, outside the screen.

We are sliding the slides programamtically using buttons, and they work, but they are rendered completely out of place.

The slides.update trick did not solve the issue.

Hiding the slides with *ngIf and showing them after ionViewDidEnter rendered them correctly, but they still flash rendered bad before being rendered good, which is quite ugly.

This seems to be related to the slides being rendered while outside the view or in a moment where they can not access the correct view size (just as hypotesis, not sure about this).

**Comment by ThierryLib** [comment] 2020-12-10 07:42
I have got a similar problem with Ionic-Angular, only on Safari. My iOS App is not affected.
When launching programmatically my component with a slider in a modal, it opens properly and after a fraction of a second it moves by half the size of the modal and stays between two slides.
Example here: https://app.latourneedesproducteurs.com/drivefermierdesaintvictor 
Select a product and click on "Réserver" to open the modal.

I tried the *ngIf and the slides.update(), but nothing worked for me.
Chrome, Firefox and mobile apps are ok.

It's pretty ambarrassing.

**Comment by dheimoz** [comment] 2021-03-01 17:19
In case you are looking this solution applied to Vue 3, here it is. First your ion-slides component needs a ref. For instance "slides"
```html
<ion-content fullscreen class="ion-padding" scroll-y="false">
    <ion-slides ref="slides">
      <ion-slide>
        <h1>Slide 1</h1>
      </ion-slide>
      <ion-slide>
        <h1>Slide 2</h1>
      </ion-slide>
      <ion-slide>
        <h1>Slide 3</h1>
      </ion-slide>
    </ion-slides>
  </ion-content>
```

Then in your setup

```js
setup() {
    const slides = ref();
    onMounted(() => {
      slides.value.$el.update();
    });
    return { slides };
  },
```

This way, when the Modal is present and mounted the slides component is updated.

Hope this helps. I believe there is no other to make work because it is not a problem with the IonicFramework but the integration with Swyper.js

**Comment by liamdebeasi** [comment] 2021-12-02 00:56
Hi everyone,

This was resolved via https://github.com/ionic-team/ionic-framework/pull/24257 and a fix will be available in an upcoming release of Ionic. This fix will be available in both Ionic 5 and Ionic 6. Thanks!

**Closed by liamdebeasi** 2021-12-02 00:56 UTC
Labels: package: core, type: bug
