### ISSUE TITLE
bug: lazy loaded standalone components are included in initial chunk files (angular, esbuild)

### ISSUE THREAD

**Issue by patricsteiner** [ionic-team/ionic-framework#28810] opened 2024-01-10 16:02 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When I use an ionic standalone component in a lazy-loaded component, it is still added to the initial chunk files.

### Expected Behavior

It should be lazily loaded and not be part of the initial chunk size.

### Steps to Reproduce

1. create a new ionic angular project with standalone components
2. create a new component that is lazily loaded
3. in that component, use an ionic component (eg ion-button) and import it in the components import array (from /standalone)
4. build the app and inspect the chunk files --> the ion-button will be in the initial chunk

### Ionic Info

```
Ionic:

   Ionic CLI                     : 5.4.16 (C:\Users\patri\AppData\Local\npm-cache\_npx\864a9e3c2cd0cf50\node_modules\ionic)
   Ionic Framework               : not installed
   @angular-devkit/build-angular : 17.0.9
   @angular-devkit/schematics    : 17.0.9
   @angular/cli                  : 17.0.9
   @ionic/angular-toolkit        : 9.0.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v20.10.0 (C:\Program Files\nodejs\node.exe)
   npm    : 10.1.0
   OS     : Windows 10

```

### Additional Information

Am I missing something here, is this the intended behaviour?

**Comment by liamdebeasi** [comment] 2024-01-10 16:24
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. Webpack/ESBuild is working as intended here. Imports from a single entry point cannot be split up across chunks, so importing Ionic components from the same entry point will cause them to be added to the same chunk. In this case, `provideIonicAngular` is added to the initial chunk, so all other Ionic imports get added there too.

However, we realize this behavior is not ideal for some applications. More information is available on https://github.com/ionic-team/ionic-framework/issues/28574#issuecomment-1833977900.

**Closed by liamdebeasi** 2024-01-10 16:24 UTC
Labels: triage

**Comment by patricsteiner** [comment] 2024-01-10 20:17
@liamdebeasi thank you so much for the explanation! I'm sorry I didn't see the other issue you linked 🤦
But in this case, I really don't understand how the tradeoff of having a much larger initial chunk size and in return having a _potentially_ smaller total size is worth it? Especially in larger Ionic apps, where almost all components are used throughout the whole app anyway, but most of them are only used lazily? That's exactly the situation I'm in: Our bundle sized increased from 1.3mb to 2.1mb just by migrating to ionic standalone. The ionic chunk is 800kb, and basically contains every ionic component there is.
As far as I'm concerned, everybody is always fighting to minimize that initial chunk size to maximize loading speed, or am I missing something?

**Comment by liamdebeasi** [comment] 2024-01-15 17:14
> But in this case, I really don't understand how the tradeoff of having a much larger initial chunk size and in return having a potentially smaller total size is worth it?

In an ideal world, both the overall size and the initial chunk is optimized. This is what we are trying to work towards in the thread I linked.

------

While the initial chunk may get larger for some apps, the added load may not have a noticeable impact on load time (for a mobile app this is typically time to interactive). It really depends on each application. For some applications, this trade off may be acceptable. I don't mean to say that there aren't performance concerns with this approach, but the large bundle size might not have as significant of an impact on load time in the context of a mobile application distributed through the App Store.

For example, if the app is a binary downloaded from the App Store then the initial chunk will be loaded from disk fairly quickly. How long the chunk takes to execute partially depends on what kind of code is being run. In this case, Ionic component instances are being registered which should be a fairly quick operation and should not cause any kind of layout thrashing.
