### ISSUE TITLE
bug: ion-modal crashes after fast clicking React

### ISSUE THREAD

**Issue by Vilius-Stankaitis** [ionic-team/ionic-framework#22582] opened 2020-11-26 11:54 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
https://codesandbox.io/s/small-star-psz3b?file=/package.json&resolutionWidth=328&resolutionHeight=675
```

**Other information:**

Until version 5.0.7 ion-modal not allowing fast clicking. If I use mode="md" works fine.

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by Vilius-Stankaitis** [comment] 2020-11-26 12:03
Issue here -> when version > 5.0.7

https://codesandbox.io/s/small-star-psz3b?file=/package.json:30-177&resolutionWidth=328&resolutionHeight=675

**Comment by liamdebeasi** [comment] 2020-11-30 14:55
Thanks for the issue. Can you provide some steps to reproduce the issue?

**Comment by Vilius-Stankaitis** [comment] 2020-12-01 21:04
https://codesandbox.io/s/small-star-psz3b?file=/package.json:30-177&resolutionWidth=328&resolutionHeight=675

->  fast click the button several times.

<img width="531" alt="Screenshot 2020-12-01 at 21 03 02" src="https://user-images.githubusercontent.com/53124253/100796547-bfffbd80-3418-11eb-8f7d-63f6a393b14d.png">

**Comment by liamdebeasi** [comment] 2020-12-02 14:09
Thanks for the follow up. I am going to close this as this is not a bug in Ionic Framework. The problem here is that you are not properly updating the "showModal" state. Since you are using `useState` in React, you need to explicitly set the show modal state to `false` when the modal has closed:

```jsx
<IonModal isOpen={showModal} onDidDismiss={() => setShowModal(false)}>...</IonModal>
```

The examples are not very clear about this so I will make sure to update the docs: https://ionicframework.com/docs/api/modal#usage

**Closed by liamdebeasi** 2020-12-02 14:09 UTC
Labels: triage
