### ISSUE TITLE
bug: Datetime with default title not working correctly (v6)

### ISSUE THREAD

**Issue by martinmitteregger** [ionic-team/ionic-framework#23745] opened 2021-08-09 08:34 UTC
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Using `[showDefaultTitle]="true"` the datetime does not change months correctly. If changing month in one direction only one step is possible and the month name does not change. Changing into the other direction the month with current selected date is skipped and only one step is possible, too.

Using `[showDefaultTitle]="false"` or without the property the behavior is like expected - it is possible to move several months into past or future (although the month name changes slowly)

### Expected Behavior

It is possible to move several months into past or future instead of only one month. Furthermore the month with current selected date is not skipped during moving.

### Steps to Reproduce

Show datetime chooser with option `[showDefaultTitle]="true"` inside of a modal (see repo).

### Code Reproduction URL

https://github.com/martinmitteregger/datepicker-bug/

### Ionic Info

```
Ionic:

   Ionic CLI                     : 6.12.3 (C:\Users\xxx\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.0.0-beta.3
   @angular-devkit/build-angular : 12.1.4
   @angular-devkit/schematics    : 12.2.0
   @angular/cli                  : 12.1.4
   @ionic/angular-toolkit        : 4.0.0

Capacitor:

   Capacitor CLI   : not installed
   @capacitor/core : 3.1.2

Utility:

   cordova-res (update available: 0.15.2) : 0.15.1
   native-run (update available: 1.3.0)   : 1.0.0

System:

   NodeJS : v16.3.0 (C:\Program Files\nodejs\node.exe)
   npm    : 7.17.0
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment] 2021-08-09 13:02
Thanks for the issue. Can you please provide some steps to reproduce the issue? I cannot reproduce this behavior on my end.

**Comment by martinmitteregger** [comment] 2021-08-09 13:20
@liamdebeasi I perform the following steps:
1. start the provided app with `ionic serve`
2. open the datetime chooser by clicking into the input field
3. Starting point is the date today
3. navigate into the past -> should change to July, June,... but only one step is possible and month label keeps "August"
4. navigate into the future - > should display August, September,... but august get skipped and no further steps are possible

I hope this information is enough - if not I will try to screen capture the behavior.

**Comment by liamdebeasi** [comment] 2021-08-09 13:27
What browser are you testing this on? I am testing this on the latest versions of Safari and Chrome and cannot reproduce the issue.

**Comment by martinmitteregger** [comment] 2021-08-09 14:00
You are right - switched last week for testing purposes to Microsoft Edge and thought it should work the same because both are using chromium. The answer is obviously no.
Sorry for the general bug ticket - it works on Chrome like expected but its still an issue using Microsoft Edge.

**Comment by liamdebeasi** [comment] 2021-08-09 14:08
What version of Microsoft Edge are you using? I am testing this on v92.0.902.67 and it is working as expected.

**Comment by martinmitteregger** [comment] 2021-08-09 14:27
Strange - i have the same version.

**Comment by liamdebeasi** [comment] 2021-08-09 14:28
Can you send a video of the issue happening on your end?

**Comment by martinmitteregger** [comment] 2021-08-09 15:03
@liamdebeasi i hope you can see the issues
https://user-images.githubusercontent.com/15977182/128728214-736c5a9b-fcb1-4837-b529-13655ceda164.mp4

**Comment by liamdebeasi** [comment] 2021-08-09 15:12
The app in the video looks different than the app that was sent over. Am I able to get access to a minimal version of that app?

**Comment by liamdebeasi** [comment] 2021-08-09 15:19
Are there any errors in the console?

**Comment by martinmitteregger** [comment] 2021-08-09 15:19
No there are no errors in the console

**Comment by liamdebeasi** [comment] 2021-08-09 15:25
Hmm that's strange. Here is what I can see on my end: 

https://user-images.githubusercontent.com/2721089/128731632-d2fda218-3f38-4a0e-82cf-ebdd545b6435.mov

Do you have any plugins/extensions running in Microsoft Edge?

**Comment by martinmitteregger** [comment] 2021-08-09 19:21
No I do not have any plugins or extensions running.
Its very strange because I just tried to run it with version 6.0.1 but it did not work either. And what I understand even less is that it does not work now with chrome either. Might be a weird problem on my side - in any case, thank you for your time.

**Comment by liamdebeasi** [comment] 2021-08-17 12:37
I checked with another team member, and they were unable to reproduce the issue either. I am going to close this issue for now. If you have additional info that can help us reproduce the issue please feel free to reply here, and we will be more than happy to take another look. Thank you!

**Closed by liamdebeasi** 2021-08-17 12:37 UTC
Labels: triage
