### ISSUE TITLE
feat: Allow host nodes or root node to be specified for overlay components created at runtime

### ISSUE THREAD

**Issue by joelmeaders** [ionic-team/ionic-framework#28590] opened 2023-11-28 19:00 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

I'd like to be able to specify which dom nodes things like overlays (and by extension modals, alerts, popovers etc...) are hosted in or are created under. This would help in cases where Ionic Apps are embedded as micro-frontends and give greater options for customization.

Currently `AngularFrameworkDelegate` calls `CreateComponent<C>` from renderer3 in Angular. Renderer3 has an option named hostElement which causes Angular to render the component on that node. Exposing that would allow for this flexibility.

On creation or presentation maybe we can specify what node is used as part of the options:
`this.modalController.create({ overlayHostElement: myExternalHtmlElement })`

Or as another option - maybe we can specify which host node to use for all overlays at the module level:
`IonicModule.forRoot({ hostElementRoot: myExternalHtmlElement })`

### Describe the Use Case

This is unconventional for Ionic, but many of our applications are embedded into our off-the-shelf CMS. We have full featured applications and small "micro-frontends". This took a fair amount of effort to accomplish with Ionic but many of the issues caused by our unconventional use were solved via CSS and we're nearly at an acceptable solution.

The final thing we're working on are things that need to overlay the entire page and not just the embedded app. Our first solution to this was by convention - wrapping the Ionic controllers for modals, alerts etc... and placing in some code that moves the node after creation and before display. Our "deeper" solution modifies `AngularFrameworkDelegate` to move the overlay container node in the method `attachViewToDom()`.

Ideally this could be handled at the framework level instead of us hacking around and creating tech debt.

### Describe Preferred Solution

On creation or presentation maybe we can specify what node is used as part of the options:
`this.modalController.create({ overlayHostElement: myExternalHtmlElement })`

Or as another option - maybe we can specify which host node to use for all overlays at the module level:
`IonicModule.forRoot({ hostElementRoot: myExternalHtmlElement })`

### Describe Alternatives

As an alternative, allow us to provide our own `AngularFrameworkDelegate`. By design various things Ionic Common and Core aren't exported and thus we cannot easily solve this via inheritance/extension.

**Comment by liamdebeasi** [comment] 2023-11-28 21:31
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/24198.

**Closed by liamdebeasi** 2023-11-28 21:31 UTC
Labels: triage
