### ISSUE TITLE
bug: ion-fab-button when [disabled]="true" doesn't stop click

### ISSUE THREAD

**Issue by ryaa** [ionic-team/ionic-framework#23808] opened 2021-08-24 14:30 UTC
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

When ion-fab-button is disabled the click event is still fired - see https://stackblitz.com/edit/ionic-angular-v5-xtamdg?file=src%2Fapp%2Fapp.component.html

### Expected Behavior

Click event should not be fired when ion-fab-button is disabled

### Steps to Reproduce

add [disabled]="true" to ion-fab-button

### Code Reproduction URL

https://stackblitz.com/edit/ionic-angular-v5-xtamdg?file=src%2Fapp%2Fapp.component.html

### Ionic Info

Ionic:

   Ionic CLI                     : 6.12.4 (/Users/alexryltsov/.nvm/versions/node/v12.16.3/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.5.4
   @angular-devkit/build-angular : 0.1100.7
   @angular-devkit/schematics    : 11.0.7
   @angular/cli                  : 11.0.7
   @ionic/angular-toolkit        : 2.3.3

Capacitor:

   Capacitor CLI   : 2.4.6
   @capacitor/core : 2.4.6

Utility:

   cordova-res (update available: 0.15.3) : 0.15.1
   native-run                             : not installed

System:

   NodeJS : v12.16.3 (/Users/alexryltsov/.nvm/versions/node/v12.16.3/bin/node)
   npm    : 6.14.11
   OS     : macOS Big Sur

### Additional Information

Please also see https://github.com/ionic-team/ionic-framework/issues/14719 and https://github.com/ionic-team/ionic-framework/issues/15120

**Comment by liamdebeasi** [comment] 2021-08-24 19:56
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/22881.

**Closed by liamdebeasi** 2021-08-24 19:56 UTC
Labels: triage
