### ISSUE TITLE
bug: Sliding does not work in an ion-item-sliding component if an *ngIf used on the ion-item-options 

### ISSUE THREAD

**Issue by adwilson** [ionic-team/ionic-framework#27258] opened 2023-04-21 10:04 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

We are using the `<ion-item-sliding>` component in our app. The sliding is only used selectively based on a condition which we achieved by adding an *ngIf to the `<ion-item-options>` component. In v6 and below this behaviour worked fine. Those where the condition did not match were still, non-moving items, those that did would slide with the sliding gesture.

Since v7, this is no longer the case. Any presence of the *ngIf removes the ability to slide any item even if it meets the condition.

### Expected Behavior

Expected it to work as it did in v6 where it would allow sliding where the condition was met. There is no mention of any changes to the sliding components in any of the changelogs.

### Steps to Reproduce

Taken from the provided StackBlitz URL...

```
<ion-list>
  <ion-item-sliding *ngFor="let animal of animals">
    <ion-item>{{ animal }}</ion-item>
    <!--
      The sliding does not work on any item when the *ngIf is present below, remove it and it works fine.
    -->
    <ion-item-options side="end" *ngIf="animal === 'Dog'">
      <ion-item-option>It's a dog</ion-item-option>
    </ion-item-options>
  </ion-item-sliding>
</ion-list>
```

Then observe from the preview window how the sliding does not work on any item until the *ngIf is removed.

### Code Reproduction URL

https://stackblitz.com/edit/angular-bsbwpu

### Ionic Info

Ionic:

   Ionic CLI                     : 7.0.1
   Ionic Framework               : @ionic/angular 7.0.2
   @angular-devkit/build-angular : 15.1.1
   @angular-devkit/schematics    : 14.1.2
   @angular/cli                  : 15.1.1
   @ionic/angular-toolkit        : 7.0.0

Capacitor:

   Capacitor CLI      : 4.0.1
   @capacitor/android : 4.0.1
   @capacitor/core    : 4.0.1
   @capacitor/ios     : 4.0.1

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.1

System:

   NodeJS : v18.13.0 (C:\Program Files\nodejs\node.exe)
   npm    : 8.19.3
   OS     : Windows 10

**Comment by amandaejohnston** [comment] 2023-04-21 14:08
Thank you for the issue. I'm unable to replicate this; the Dog sliders work as intended. Screencast below. What browser are you testing on?

https://user-images.githubusercontent.com/90629384/233656964-4560f5cf-ecfb-4e8f-955d-c8b4209c4e66.mp4

**Comment by adwilson** [comment] 2023-04-21 15:04
Hmm, I can swear that wasn't working before. The place we found the issue was within Electron and that is still the case. OK, I'll close this and see if I find what is really going on then. Thanks for your time.

**Comment by DmitrySharabin** [comment] 2023-04-22 14:24
I face the same issue. I stumbled on it after upgrading to version 7. I haven't faced this issue previously. So it seems to me it might be a regression.

https://user-images.githubusercontent.com/9166277/233789823-4859518e-3b8d-481a-8f08-181e75833712.mp4

The flow in the screen recording corresponds to the following (simplified) code snippet. As you can see from the recording, if I visit the same root the second time in a row, everything starts working as it should. And it happens all over my code where I try to show/hide item options with `*ngIf`.

```html
<ion-content [fullscreen]="true">
	<ng-container *ngIf="lawFirm$ | async as lawFirm; else loading">
		...
		<ion-list>
			...
			<ion-item-sliding *ngFor="let lawyer of lawFirm.lawyers">
				<ion-item-options side="start" *ngIf="lawFirm.isActive">
					<ion-item-option *ngIf="lawyer.isActive" >
						<ion-icon slot="icon-only" name="ban"></ion-icon>
					</ion-item-option>
					<ion-item-option *ngIf="!lawyer.isActive" >
						<ion-icon slot="icon-only" name="arrow-undo"></ion-icon>
					</ion-item-option>

					<ion-item-option>
						<ion-icon slot="icon-only" name="trash"></ion-icon>
					</ion-item-option>
				</ion-item-options>

				<ion-item>
					<ion-label>{{ lawyer }}</ion-label>
				</ion-item>

				<ion-item-options side="end" *ngIf="lawFirm.isActive && lawyer.isActive">
					<ion-item-option>
						<ion-icon slot="icon-only" name="pencil"></ion-icon>
					</ion-item-option>
				</ion-item-options>
			</ion-item-sliding>
		</ion-list>
	</ng-container>
</ion-content>
```

@amandaejohnston, could you please give this issue another look? 🙏🏻

**Comment by amandaejohnston** [comment] 2023-04-24 14:11
@DmitrySharabin Could you post a link to a Stackblitz app or Github repo replicating the issue?

**Comment by adwilson** [comment] 2023-04-24 14:42
I got this to replicate in the StackBlitz I provided... https://stackblitz.com/edit/angular-bsbwpu. What I did was surround the ion-list in an ion-content (I was just trying anything out!), saved the file. I removed the ion-content again, saved it and it stops working in the instant refresh. This might a quirk of how StackBlitz works in that doesn't do a full refresh. If you do a full refresh the slider works fine again. That explains why I was getting a reproduction and you didn't @amandaejohnston.

**Comment by amandaejohnston** [comment] 2023-04-24 18:22
Thank you! I'm able to replicate it consistently now. I just need to dig further into why exactly it's happening.

**Comment by amandaejohnston** [comment] 2023-04-24 19:35
@DmitrySharabin I'm able to slide all the Dog sliders in your example, with the buttons appearing as expected. What browser are you testing on?

**Comment by DmitrySharabin** [comment] 2023-04-24 20:12
> @DmitrySharabin I'm able to slide all the Dog sliders in your example, with the buttons appearing as expected. What browser are you testing on?

Yes, after the app is launched, everything works as expected. But if you chose another animal from the drop-down above the list of animals (e.g., cat), you won’t be able to slide the corresponding slider (the Cat one).

**Comment by amandaejohnston** [comment] 2023-04-24 20:20
Digging in further, it looks like this issue is, at the root, actually the same as https://github.com/ionic-team/ionic-framework/issues/25578. So, I'm going to close this as a duplicate of that other issue. I'll post a link to the latest reproduction over there, since I think it's a cleaner demonstration of the bug than what we've already got.

**Closed by amandaejohnston** 2023-04-24 20:20 UTC
Labels: triage

**Comment by lajith111** [comment] 2023-04-28 06:27
@amandaejohnston #25578 its related since vesion 6 . But after upgrading v6 to v7  i am facing issue..please reopen issue

**Comment by lajith111** [comment] 2023-04-28 06:37
> Digging in further, it looks like this issue is, at the root, actually the same as #25578. So, I'm going to close this as a duplicate of that other issue. I'll post a link to the latest reproduction over there, since I think it's a cleaner demonstration of the bug than what we've already got.

@amandaejohnston https://github.com/ionic-team/ionic-framework/issues/25578 since version 6. I have upgrading my app from v6 to v7, After upgrade slider is disabled . In v6 if i change the tab item sliding is working fine ..but disabled in v7. So i request you to Please check again
