### ISSUE TITLE
bug: chrome v69, intersection observer continues to fire with datetime

### ISSUE THREAD

**Issue by zhuhuanzi** [ionic-team/ionic-framework#24980] opened 2022-03-23 06:12 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

```
<ion-datetime hour-cycle="h12" locale="en-GB"></ion-datetime>
```

### Expected Behavior
```
<ion-datetime hour-cycle="h12" locale="en-GB"></ion-datetime>
```

### Steps to Reproduce

create new project and add this code

### Ionic Info

  "dependencies": {
    "@angular/common": "~13.2.2",
    "@angular/core": "~13.2.2",
    "@angular/forms": "~13.2.2",
    "@angular/platform-browser": "~13.2.2",
    "@angular/platform-browser-dynamic": "~13.2.2",
    "@angular/router": "~13.2.2",
    "@capacitor/android": "3.4.3",
    "@capacitor/app": "1.1.1",
    "@capacitor/core": "3.4.3",
    "@capacitor/haptics": "1.1.4",
    "@capacitor/keyboard": "1.2.2",
    "@capacitor/status-bar": "1.0.8",
    "@ionic/angular": "^6.0.12",
    "rxjs": "~6.6.0",
    "tslib": "^2.2.0",
    "zone.js": "~0.11.4"
  },

### Additional Information

I have searched for existing issues,such as https://github.com/ionic-team/ionic-framework/pull/24475,
It's good on Android 12(Android System WebView 96.0.4664.61),
but it doesn't work on Android 9（Android System WebView 69.0.3497.100）.

**Comment by zhuhuanzi** [comment] 2022-03-23 06:13
![41109921ee31b64248d2237484833bd](https://user-images.githubusercontent.com/26531688/159635175-407c6ecc-8c43-45c1-b90e-4bcd5205a173.jpg)

**Comment by zhuhuanzi** [comment] 2022-03-23 06:19
https://user-images.githubusercontent.com/26531688/159635955-d578db70-e4fa-4058-b48c-edf3b809920e.mp4

**Comment by liamdebeasi** [comment] 2022-03-23 14:25
Thanks for the issue. Are you able to update the system webview on the Android 9 device? Version 69 is quite old.

**Comment by zhuhuanzi** [comment] 2022-03-24 08:05
@liamdebeasi update webview is not feasible,more than one software may appear in the system,the system is still running at a lower version.
![007b6defc1446254c5378649c4c249d](https://user-images.githubusercontent.com/26531688/159870259-0700eac5-4702-4996-a419-40e73ee2216f.jpg)

**Comment by liamdebeasi** [comment] 2022-03-30 13:28
Thanks for the update. Let me check with the team on this. The issue is likely a bug in an older version of the Chrome/Android WebView. Unfortunately, I do not have access to that version of the webview, making it hard to develop a workaround at the moment.

**Comment by liamdebeasi** [comment] 2022-03-30 14:30
My colleague was able to reproduce this on an older Android 9 simulator. I will assign the `bug` label.

**Comment by zhaoxiongxing** [comment] 2022-06-01 13:35
I have the same problem

**Comment by kyoz** [comment] 2022-06-30 09:53
For more information, this issue happen on iOS 12.2 and below too.

When using ion-date time on iOS device which below or equal 12.2 version, there is some error relate to `IntersectionObserver`.

It's seem below that version, IntersectionObserver on iOS's safari didn't support really well.

I'v tried to add a `intersection-observer` polyfill and the error gone away, but then this issue happen.

I'm not planning to support iOS which below 12.4. But I hope these infos will help to investigate the issue.

**Comment by liamdebeasi** [comment] 2022-06-30 13:14
Ionic 6 support iOS 13.0+: https://ionicframework.com/docs/reference/browser-support#mobile-browsers

We do not recommend using Ionic 6 on anything older than iOS 13.0 as you will likely run into unsupported features as noted in https://github.com/ionic-team/ionic-framework/issues/24980#issuecomment-1171009930.

**Comment by ShubhamKhatri2** [comment] 2022-07-02 08:32
Please resolve this issue as soon as possible, because it's affecting our business

**Comment by liamdebeasi** [comment] 2022-07-15 18:58
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/25586, and a fix will be available in an upcoming release of Ionic Framework.

**Closed** 2022-07-15 18:58 UTC
Labels: type: bug, bug: external
