### ISSUE TITLE
bug: authoheight sheet modal bugs out when component is an ion-content

### ISSUE THREAD

**Issue by jmedellinc** [ionic-team/ionic-framework#27846] opened 2023-07-24 19:20 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

First of all, thanks for implementing the auto height sheetModal.. I had a helper doing with the dynamic adjustment of breakpoints but was a less than ideal workaround.. the auto-height works beautifuylly

Now to the bug:
When the component loaded into a sheet modal with --height:'auto', the modal is shown empty

https://github.com/ionic-team/ionic-framework/assets/105754419/6b45bde8-6044-4f43-8539-5b02fc732474

### Expected Behavior

The modal content should be shown

### Steps to Reproduce

1. https://ionicframework.com/docs/api/modal#auto-height-sheet
2. open in stackblitz
3. enclose <div class="block">Block of Content</div> in an ion-content
4. open the modal and it shows empty

To verify it's the ion-content
1. https://ionicframework.com/docs/api/modal#controller-modals
2. open in stackblitz
3. add to example.component.ts's modalCtrl.create:
````
      breakpoints:[0,1],
      initialBreakpoint: 1,
      cssClass: 'autoHeightModal'
````
4. Add to global.scss
````
.autoHeightModal {
  --height:300px
}
````
Open the modal and see how only the ion-header shows..

### Code Reproduction URL

https://ionicframework.com/docs/api/modal

### Ionic Info

not applicable.. running latest @ionic docs

### Additional Information

One fix is to eliminate the ion-content and everything in a div..
However, that has the undesired side-effect that outside of ion-content, scroll-assist events don't get fired.. Which is of course not desired..

What I'm doing is using again the aforementioned helper, but with different intent 
* I create a div sibling with the dynamic height of the ion-content height, outside of the ion-content, which sets the sheet modal height
* The content has to be put in the "slot=fixed" portion of the ion-content for the content to show.. (otherwise it's missing)

**Comment by liamdebeasi** [comment] 2023-07-25 19:23
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. As per the [modal documentation](https://ionicframework.com/docs/api/modal#custom-dialogs) `ion-content` should be used where the height of the dialog is known ahead of time. If you don't know the height of the container ahead of time then `ion-content` should not be used.

The reason for this is `ion-content` is sized based upon the remaining space available in its parent container. However, a dialog with `--height: auto` means the parent container is going to be sized based on the size of the children. This creates a conflict where the content needs the parent height to be defined, but the parent needs the content height to be defined. This results in the reported behavior where the content height is 0.

**Closed by liamdebeasi** 2023-07-25 19:23 UTC
Labels: triage

**Comment by jmedellinc** [comment] 2023-07-25 19:28
Thanks for the heads up!
Sorry for not finding that in the docs..

One question:
¿Does scroll-assist work outside of an ion-content?  It wasn't firing for me..

@liamdebeasi
