### ISSUE TITLE
bug: ion-content first element not be clickable (IOS)

### ISSUE THREAD

**Issue by JayzeeHuang** [ionic-team/ionic-framework#22045] opened 2020-09-07 22:23 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

ion-content first element not be clickable when on real device and simulator (IOS only)

**Expected behavior:**

ion-content first element can be click and work

**Steps to reproduce:**

1. Generate tabs with angular and cordova
2. Replace tab1.page.html with the code provided below
3. Build ios and run
4. First item not working all the time, but 2 and 3 works fine

**Related code:**

[https://github.com/JayzeeHuang/ion-content-issue](url)

```
<ion-header [translucent]="true">
  <ion-toolbar style="height: 0;"></ion-toolbar>
</ion-header>
<ion-content>
  <ion-item href="https://www.ionicframework.com">
    <ion-label>
      Anchor Item 1
    </ion-label>
  </ion-item>
  <ion-item href="https://www.ionicframework.com">
    <ion-label>
      Anchor Item 2
    </ion-label>
  </ion-item>
  <ion-item href="https://www.ionicframework.com">
    <ion-label>
      Anchor Item 3
    </ion-label>
  </ion-item>
</ion-content>
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.11.8 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.3.2
   @angular-devkit/build-angular : 0.1000.8
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : ios 6.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 4 other plugins)

Utility:

   cordova-res (update available: 0.15.1) : 0.13.0
   native-run (update available: 1.0.0)   : 0.2.8

System:

   ios-deploy : 1.10.0
   ios-sim    : 8.0.2
   NodeJS     : v12.16.2 (/usr/local/bin/node)
   npm        : 6.14.8
   OS         : macOS Catalina
   Xcode      : Xcode 11.7 Build version 11E801a
```

**Comment by JayzeeHuang** [comment] 2020-09-08 23:36
https://github.com/JayzeeHuang/ion-content-issue

sample code

**Comment by liamdebeasi** [comment] 2020-09-21 14:59
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. Even though your toolbar has `height: 0`, the inner `.toolbar-content` has a minimum height of 44px, so it is still covering the first item. You can use the `--min-height` CSS variable to control this: https://ionicframework.com/docs/api/toolbar#css-custom-properties

**Closed by liamdebeasi** 2020-09-21 14:59 UTC
Labels: ionitron: needs reproduction
