### ISSUE TITLE
bug: angular, moving elements inside of ion-router-outlet causes dom tree mismatch during hydration

### ISSUE THREAD

**Issue by bashoogzaad** [ionic-team/ionic-framework#28534] opened 2023-11-15 15:26 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When starting a new project with `ionic start` with the option `Angular Standalone`, then `@angular/ssr` is not working correctly. When adding `@angular/ssr`, the Angular CLI is adding files, such as `app.config.server.ts`. This file is referring to `app.config.ts`. This file is however not present, so you have to create is. Not a big deal.

However, after `npm run dev:serve`, the application is running, but gets an error:

```
main.ts:12 ERROR Error: NG0501: During hydration Angular expected more sibling nodes to be present.

Actual DOM is:

<ion-app>
  …
  <ion-router-outlet>…</ion-router-outlet>
  <!-- container -->  <-- AT THIS LOCATION
</ion-app>

To fix this problem:
  * check corresponding component for hydration-related issues
  * check to see if your template has valid HTML structure
  * or skip hydration by adding the 'ngSkipHydration' attribute to its host node in a template

 Find more at https://angular.io/errors/NG0501
    at validateSiblingNodeExists (core.mjs:18669:15)
    at siblingAfter (core.mjs:19187:22)
    at locateDehydratedViewsInContainer (core.mjs:19395:32)
    at populateDehydratedViewsInLContainerImpl (core.mjs:20174:44)
    at locateOrCreateAnchorNode (core.mjs:20189:10)
    at createContainerRef (core.mjs:20086:5)
    at injectViewContainerRef (core.mjs:19846:12)
    at core.mjs:4188:29
    at runInInjectorProfilerContext (core.mjs:867:9)
    at lookupTokenUsingNodeInjector (core.mjs:4187:17)
```

This is just a starter project with 'list' prefill.

### Expected Behavior

The application should run correctly, and must be able to hydrate the components.

### Steps to Reproduce

1. ionic start -> Angular Standalone -> list prefill
2. ng add @angular/ssr
3. Create app.config.ts based on main.ts
4. npm run dev:ssr

### Ionic Info

Ionic:

   Ionic CLI                     : 7.1.5 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.5.4
   @angular-devkit/build-angular : 17.0.0
   @angular-devkit/schematics    : 17.0.0
   @angular/cli                  : 17.0.0
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.5.1
   @capacitor/android : not installed
   @capacitor/core    : 5.5.1
   @capacitor/ios     : not installed

Utility:

   cordova-res                          : not installed globally
   native-run (update available: 2.0.0) : 1.7.4

System:

   NodeJS : v18.18.2 (/usr/local/Cellar/node@18/18.18.2/bin/node)
   npm    : 9.8.1
   OS     : macOS Unknown

**Comment by liamdebeasi** [comment] 2023-11-15 15:29
Can you provide a reproduction we can run? SSR issues can be a bit tricky, so having a full sample will save us a lot of time.

**Comment by bashoogzaad** [comment] 2023-11-15 15:33
Hi @liamdebeasi , thanks for your quick response! I have created a repo here: https://github.com/bashoogzaad/ionic-ssr-test

**Comment by liamdebeasi** [comment] 2023-11-15 15:36
Does the issue persist if you use `@ionic/angular-universal`? https://ionic.io/blog/ssr-with-angular-universal-and-ionic

**Comment by bashoogzaad** [comment] 2023-11-15 15:41
I am not able to use that, that one is based on ngModules and I am using Angular Standalone (as the preferred solution nowadays). And Angular SSR should work out of the box in v17 (maybe this is related: https://forum.ionicframework.com/t/angular-universal-update/213522/2)

**Comment by liamdebeasi** [comment] 2023-11-15 15:54
You should be able to use NgModules in a standalone application still: https://angular.io/guide/standalone-components#using-existing-ngmodules-in-a-standalone-component. The module would be passed to the imports array in your app component.

Also, I'm not able to reproduce the issue in your sample repo: 

```
Error: src/app/app.config.server.ts:3:27 - error TS2307: Cannot find module './app.config' or its corresponding type declarations.

3 import { appConfig } from './app.config';
```

Can you make sure there's an `app.config` file in the repo?

**Comment by liamdebeasi** [comment] 2023-11-16 14:57
Thanks! So the problem appears to be that we are moving children inside of `ion-router-outlet`. By default, the current view's component is mounted as a sibling of `ion-router-outlet`. However, the component needs to be a child of `ion-router-outlet` so things like page transitions and swipe to go back can work properly.

To work around this, we move the element inside of `ion-router-outlet`: https://github.com/ionic-team/ionic-framework/blob/9d57758e3ec1095c6eb951d2640b95084b711bbc/packages/angular/common/src/providers/angular-delegate.ts#L175

This causes a DOM tree mismatch during hydration because Angular was expecting the view's component to be a sibling of `ion-router-outlet`. According to https://angular.io/guide/hydration#third-party-libraries-with-dom-manipulation, you can avoid this by setting `ngSkipHydration` on the component that renders `ion-router-outlet`.

However, this would mean setting `ngSkipHydration` on the root element which defeats the purpose of having hydration in the first place. To fix this, we likely need to update our implementation to ensure that view components are mounted in the correct place the first time so we don't need to move anything around in the DOM.

**Comment by liamdebeasi** [comment] 2023-11-16 16:03
Also wanted to set appropriate expectations: `@angular/ssr` does not support Web Components at the moment, so even if we fix this issue (which we should) there will still be other issues. For example, Stencil renders comments inside of scoped components for style encapsulation. These comments cause `@angular/ssr` to break. A good example of this is the `ion-header` component.

Unfortunately, this is not something we can address as the Angular team needs to add support for Web Components to the `@angular/ssr` package. If this is something import for your use case, I recommend providing feedback to the Angular team on https://github.com/angular/angular/issues.

**Comment by stevebrowndotco** [comment] 2023-11-29 21:55
@liamdebeasi might be worth noting that the Lit framework team, which also uses web components, is claiming that they are working on SSR support now, according to here. https://lit.dev/docs/ssr/overview/ Maybe the Ionic Team could consider a similar approach?

**Comment by liamdebeasi** [comment] 2023-11-29 22:13
We'd probably still advocate for getting Web Component support in `@angular/ssr`. Even if Stencil had a Stencil-specific SSR solution, the Angular team (and React and Vue teams) would likely need to add Stencil-specific integrations to make that SSR solution compatible with the JS Framework. It's certainly possible, but it would be a sizable effort to build and maintain all of these different integrations.

**Comment by eideard-hm** [comment] 2023-12-19 13:09
Does this mean that server side rendering is not yet possible?

**Comment by liamdebeasi** [comment] 2024-01-09 14:18
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/28544, and a fix will be available in an upcoming release of Ionic Framework.

We chose to ship this in a major release of Ionic Framework to account for any unexpected behavior changes. There should be no behavior changes, but how views are mounted are important to the functionality of page transitions and swipe to go back, so we'd like a public testing period.

> Does this mean that server side rendering is not yet possible?

You can use the `@ionic/angular-server` package with Angular Universal for some SSR support. However, Angular's `@angular/ssr` package does not support Web Components yet and cannot be used with Ionic.

**Closed by liamdebeasi** 2024-01-09 14:18 UTC
Labels: package: angular, type: bug
