### ISSUE TITLE
bug: IonicSafeString encapsulated string shows undefined with alertController.create

### ISSUE THREAD

**Issue by elpollodiablo** [ionic-team/ionic-framework#28365] opened 2023-10-17 09:44 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

with 
```
const message = 'some text<br/><br/>and html'
const alert = await this.ionicAlert.create({
   message: new IonicSafeString(message),
   ...
});
```
will produce an alert with "undefined"

With

```
IonicModule.forRoot({
  innerHTMLTemplatesEnabled: true,
  ...
})
```
both `message: message` and `new IonicSafeString(message)` display interpreted html

### Expected Behavior

with
```
IonicModule.forRoot({
  innerHTMLTemplatesEnabled: false,
  ...
})
```

`message: message` displays message as plaintext and`new IonicSafeString(message)` displays interpreted html

### Steps to Reproduce

1. create an alertController triggered alert with `message: new IonicSafeString('some<br/>htmltext')`

### Ionic Info

Ionic:

   Ionic CLI                     : 7.1.1 (/Users/philip/.nvm/versions/node/v18.17.1/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.3.1
   @angular-devkit/build-angular : 15.2.9
   @angular-devkit/schematics    : 15.2.9
   @angular/cli                  : 15.2.9
   @ionic/angular-toolkit        : not installed

Capacitor:

   Capacitor CLI      : 4.8.1
   @capacitor/android : 4.8.1
   @capacitor/core    : 4.8.1
   @capacitor/ios     : 4.8.1

Cordova:

   Cordova CLI       : not installed
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res                          : not installed globally
   native-run (update available: 1.7.3) : 1.7.2

System:

   ios-deploy : 1.11.4
   ios-sim    : 8.0.2
   NodeJS     : v18.17.1 (/Users/philip/.nvm/versions/node/v18.17.1/bin/node)
   npm        : 6.14.18
   OS         : macOS Unknown
   Xcode      : Xcode 14.3.1 Build version 14E300c

**Comment by liamdebeasi** [comment] 2023-10-17 13:24
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. `ionicSafeString` is a special class that is used to eject from the sanitizer during the custom HTML template process. However, in order for this to work both the sanitizer and custom HTML parsing (innerHTMLTemplatesEnabled) needs to be enabled. In other words, if `innerHTMLTemplatesEnabled` is `false` then `IonicSafeString` should not be used.

Under the hood, if custom HTML templates are disabled, we render the message property using JSX: https://github.com/ionic-team/ionic-framework/blob/ed7a5e5f4a63522651d86ff900b241643c7c1019/core/src/components/alert/alert.tsx#L700-L703

Since JSX receives an `IonicSafeString` class instead of plaintext, it doesn't know how to render it and `undefined` is rendered instead. I do think this could be more clear on the docs, so I opened https://github.com/ionic-team/ionic-docs/pull/3198 to clarify.

**Closed by liamdebeasi** 2023-10-17 13:24 UTC
Labels: triage
