### ISSUE TITLE
bug: In @ionic/angular when opening a modal containing an ion-tabs, the wrong page is displayed

### ISSUE THREAD

**Issue by CharlesGrimont** [ionic-team/ionic-framework#24944] opened 2022-03-16 11:36 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Having the following pages:

* Page1
* TabsPage
* TabPage1
* TabPage2
* TabPage3

**TabsPage** contains an ion-tabs component with 3 ion-tab-buttons, each button opens TabPage1, TabPage2, TabPage3 respectively.

When using a modalController to open TabsPage from Page1, this results in the page displaying incorrectly and the following behaviors:

* Into the modal TabsPage, TabPage1 and Page 1 content are mixed
* ion-tab-buttons are not working 
* TabsPage routes are not the one used, instead, Page1 routes are used

### Expected Behavior

* I expected the following things:
  * Modal TabsPage to be displayed correctly.
  * ion-tab-buttons to open expected page
  * TabsPage routes to be the one to be used within modal. 
  * Also Expects Guards to be working

### Steps to Reproduce

In @ionic/angular v 6.0.11 and @angular/* v 13.2.6

Starting from ionic "defaults" projetcs

```shell
$ ionic start myApp tabs
```
Create a Page named ContactPage add an ion-button into this page, and on click with ModalController present existing TabsPage as a modal page.

Also see the code reproduction URL

```shell
$ npm start
```

click on Open Modal button to se the behavior 

### Code Reproduction URL

https://github.com/CharlesGrimont/repro-bug-ionic

### Ionic Info

[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package'

       Require stack:
       - C:\Users\grimo\AppData\Roaming\npm\node_modules\@ionic\cli\lib\project\index.js
       - C:\Users\grimo\AppData\Roaming\npm\node_modules\@ionic\cli\lib\index.js
       - C:\Users\grimo\AppData\Roaming\npm\node_modules\@ionic\cli\index.js
       - C:\Users\grimo\AppData\Roaming\npm\node_modules\@ionic\cli\bin\ionic
[WARN] Error loading @capacitor/android package.json: Error: Cannot find module '@capacitor/android/package'

       Require stack:
       - C:\Users\grimo\AppData\Roaming\npm\node_modules\@ionic\cli\lib\project\index.js
       - C:\Users\grimo\AppData\Roaming\npm\node_modules\@ionic\cli\lib\index.js
       - C:\Users\grimo\AppData\Roaming\npm\node_modules\@ionic\cli\index.js
       - C:\Users\grimo\AppData\Roaming\npm\node_modules\@ionic\cli\bin\ionic

Ionic:

   Ionic CLI                     : 6.18.2 (C:\Users\grimo\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.0.11
   @angular-devkit/build-angular : 13.2.6
   @angular-devkit/schematics    : 13.2.6
   @angular/cli                  : 13.2.6
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.4.3
   @capacitor/android : not installed
   @capacitor/core    : 3.4.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v16.13.2 (C:\Program Files\nodejs\node.exe)
   npm    : 8.1.2
   OS     : Windows 10

**Comment by liamdebeasi** [comment] 2022-03-16 12:55
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The IonTabs component is a routing component, meaning it is tied to the state of the router (Angular Router, in this case). IonModal intentionally does not integrate with routing and is presented outside of the routing context. As a result, routing components such as IonTabs should not be used inside of non-routing components such as IonModal.

We intend for IonTabs to be used as a top level component inside of routing.

If you are interested in creating a non-routing tabs interface, I recommend trying out [ion-segment](https://ionicframework.com/docs/api/segment) instead. Thanks!

**Closed by liamdebeasi** 2022-03-16 12:55 UTC
Labels: triage
