### ISSUE TITLE
feat: ion-datetime label should be removable when presentation is set to time only

### ISSUE THREAD

**Issue by bchehraz** [ionic-team/ionic-framework#23662] opened 2021-07-21 00:00 UTC
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

(v6)
When the `presentation` property of an `ion-datetime` is set to `"time"` only. There's still a "Time" label appended to the front of the picker component. There should be a way to remove the label.

<img width="258" alt="Screen Shot 2021-07-20 at 4 17 46 PM" src="https://user-images.githubusercontent.com/7946204/126407035-9b29333b-736b-49ad-a800-4b50ef04e240.png">

### Describe the Use Case

On my app I have a few forms that require multiple time input fields, e.g. Begin and End fields. Using the `ion-datetime` with presentation set to "time" only, I want to be able to delete the label all together (to allow for inserting my own label beside the component).

### Describe Preferred Solution

- Allow for a `timeLabel` prop which is true or false by default.
- Would also be nice if we can just customize the label, where if it's left blank that there is no label, but null is set to the default label.

**Comment by EinfachHans** [comment] 2021-07-21 08:00
Duplicate of #23555 and resolved by #23557

**Comment by liamdebeasi** [comment] 2021-07-21 12:56
Thanks for the issue. As noted above this was resolved via #23577 and this functionality will be available in v6 beta 2.

**Closed by liamdebeasi** 2021-07-21 12:56 UTC
Labels: triage
