### ISSUE TITLE
bug: Injected services not available when using popover/modal from service

### ISSUE THREAD

**Issue by bvx89** [ionic-team/ionic-framework#22424] opened 2020-11-03 14:31 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

When using a service to create popovers/modal, the providers declared in the components module are not available inside the component. The only way for the providers to be available to the component is to add the providers in the `app.module.ts`'s providers list.

**Expected behavior:**

The providers in the module for the component sent to the popover should be available inside the component

**Steps to reproduce:**

Have an application structure like this:
- page
  - subcomponent
     - subcomponent.module.ts
     - subcomponent.component.ts
     - subcomponent.service.ts
  - page.component.ts
  - page.module.ts
- shared.service.ts

**Related code:**

**shared.service.ts**
```typescript
@Injectable({
   providedIn: 'root'
})
export class SharedService {
   constructor(popoverCtrl: PopoverController) { }

   async createPopover(opts: PopoverOptions) {
      const popover = await this.popoverCtrl.create(opts);
      return popover.present();
   }
}
```

**page.component.ts**
```typescript
@Component()
export class PageComponent {
   constructor(
      popoverCtrl: PopoverController,
      sharedService: SharedService,
   ) { }

   async works() {
      const popover = await this.popoverCtrl.create({
          component: SubComponent
      });
      return popover.present();
   }

   fails() {
      return this.sharedService.createPopover({
          component: SubComponent
      });
   }
}
```

**subcomponent.component.ts**
```typescript
@Component()
export class SubComponent {
   constructor(subComponentService: SubComponentService) { }
}
```

**subcomponent.service.ts**
```typescript
@Injectable()
export class SubComponentService {
}
```

**subcomponent.module.ts**
```typescript
@NgModule({
    declarations: [
        SubComponent,
    ],
    imports: [
        IonicModule,
    ],
    exports: [
        SubComponent,
    ],
    providers: [
        SubComponentService
    ]
})
export class SubComponentModule { }
```

**page.module.ts**
```typescript
@NgModule({
    declarations: [
        PageComponent,
    ],
    imports: [
        IonicModule,
        SubComponentModule,
    ],
    exports: [
        SubComponent,
    ],
    providers: [
        SubComponentService
    ]
})
export class PageModule { }
```

Link to example repo:
[https://github.com/bvx89/ionic-bug](https://github.com/bvx89/ionic-bug)

**Other information:**

I'm using lazy loaded modules for routing in my application, not sure if that's relevant. The reason for putting the popover/modal inside a shared service is to make it easier to write tests and to reduce the number of injected services inside components.

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.10.1 (/home/bvx89/.nvm/versions/node/v12.13.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.4.1
   @angular-devkit/build-angular : 0.1002.0
   @angular-devkit/schematics    : 10.2.0
   @angular/cli                  : 10.2.0
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res                          : not installed
   native-run (update available: 1.2.1) : 0.3.0

System:

   Android SDK Tools : 26.1.1 (/opt/android-sdk)
   NodeJS            : v12.13.0 (/home/bvx89/.nvm/versions/node/v12.13.0/bin/node)
   npm               : 6.13.7
   OS                : Linux 5.9


  ──────────────────────────────────────────────────

     Ionic CLI update available: 6.10.1 → 6.11.11
          Run npm i -g @ionic/cli to update

  ──────────────────────────────────────────────────
```

**Comment by liamdebeasi** [comment] 2020-11-03 14:49
Thanks for the issue. Can you provide this as a full GitHub repo?

**Comment by bvx89** [comment] 2020-11-04 11:41
@liamdebeasi Hi, I've updated the issue with a link to my github repo with the working/faulty versions. If you uncomment the import/provider-code in AppModule, the popover/modal will start working again.

**Comment by liamdebeasi** [comment] 2020-11-04 16:32
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. Your `subpage.service.ts` file was missing a `providedIn: 'root'` in your injectable definition. Injectors provide injectables in one of two ways:

1. By associating them with an `@NgModule` or other `InjectorType`
2. By specifying that the injectable should be provided in one of the following injectors: `'root'`, `'platform'`, or `'any'`

Because your service did not use `providedIn`, Angular assumed that the injectable would be associated via an NgModule, which it was not. This is why uncommenting the lines in `app.module.ts` fixed the issue as you associated the injectable with an `@NgModule`.

For more information, please see:

 https://angular.io/api/core/Injectable#options
https://angular.io/guide/architecture-services#providing-services

**Closed by liamdebeasi** 2020-11-04 16:32 UTC
Labels: ionitron: needs reproduction

**Comment by bvx89** [comment] 2020-11-05 10:04
@liamdebeasi You were right, there was a problem with my setup. I wanted to have the providers scoped to my component, so I removed the `providedIn: 'root'` from the injection on purpose to achieve this affect. The angular docs says that you can do it this way, but adding the providers list to the module-definition did not work when using modal/overlay.

The solution was actually to move the `providers` list from the `@NgModule` to the `@Component`, as suggested [here](https://github.com/angular/angular-cli/issues/10170#issuecomment-513804204). I'm adding this comment in case anyone else stumbles upon this issue.
