### ISSUE TITLE
bug: ion-skeleton-text animation is not correct

### ISSUE THREAD

**Issue by danielehrhardt** [ionic-team/ionic-framework#22694] opened 2020-12-18 14:56 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
If the skeleton text is used on a device like a Tablet it does flicker in the Middle of the Animation
![captured](https://user-images.githubusercontent.com/19570043/102628234-a44f2380-4149-11eb-8f66-3228667830ff.gif)

**Expected behavior:**
Smooth Animation no flickering.

**Steps to reproduce:**
`<ion-skeleton-text [animated]="true" ></ion-skeleton-text>`
Use this on a FullHD Browser window. 

**Related code:**
https://stackblitz.com/edit/skeleton-flickering

**Ionic info:**

```
   Ionic CLI                     : 6.12.2 (C:\Users\Daniel\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.5.1
   @angular-devkit/build-angular : 0.1100.3
   @angular-devkit/schematics    : 11.0.3
   @angular/cli                  : 11.0.3
   @ionic/angular-toolkit        : 3.0.0

Capacitor:

   Capacitor CLI   : 2.4.4
   @capacitor/core : 2.4.4

Utility:

   cordova-res : 0.15.2
   native-run  : not installed

System:

   NodeJS : v14.15.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.9
   OS     : Windows 10
```

**Comment by patrickbussmann** [comment] 2020-12-18 14:59
Same issue here (on same project) 😀
(but with MacBook Pro Safari & Chrome)

**Comment by liamdebeasi** [comment] 2020-12-18 15:21
Thanks for the issue. What device are you testing this on? I cannot reproduce this on my end.

**Comment by danielehrhardt** [comment] 2020-12-18 15:22
> Thanks for the issue. What device are you testing this on? I cannot reproduce this on my end.

You can see it in Google Chrome, Firefox, Edge. 
https://skeleton-flickering.stackblitz.io

**Comment by danielehrhardt** [comment] 2020-12-18 15:24
If it is above the 800px 
![image](https://user-images.githubusercontent.com/19570043/102630943-7a97fb80-414d-11eb-8049-d79c6c2a4f30.png)

**Comment by liamdebeasi** [comment] 2020-12-18 15:29
Thanks for the browser info. What physical device are you testing this on? (MacBook Pro, iPad, etc)

I tested this in Chrome on a MacBook Pro (using the internal display as well as an external display) and cannot reproduce the issue.

**Comment by danielehrhardt** [comment] 2020-12-18 15:29
> Thanks for the browser info. What physical device are you testing this on? (MacBook Pro, iPad, etc)
> 
> I tested this in Chrome on a MacBook Pro (using the internal display as well as an external display) and cannot reproduce the issue.

Could you see the Issue in the Gif i attached?
Maybe you are not able to see what the Problem is?

**Comment by liamdebeasi** [comment] 2020-12-18 15:31
I can see the flickering in the "Hello" title in the gif. What kind of Mac are you testing on?

**Comment by danielehrhardt** [comment] 2020-12-18 15:32
> I can see the flickering in the "Hello" title in the gif. What kind of Mac are you testing on?

Okay, then you did not get what i mean. 
When the Shine will arrive the end of the skeleton item it will reset a bit back.

**Comment by liamdebeasi** [comment] 2020-12-18 15:34
Thanks for the clarification. Now _that_ I can reproduce 😄 . Let me look into this a bit more.

**Comment by danielehrhardt** [comment] 2020-12-18 15:40
> Thanks for the clarification. Now _that_ I can reproduce 😄 . Let me look into this a bit more.

Here is a possible fix:
https://stackblitz.com/edit/skeleton-flickering

**Comment by liamdebeasi** [comment] 2020-12-18 15:42
I can reproduce this back to 4.11.13. I will look into a fix.

**Comment by danielehrhardt** [comment] 2020-12-18 18:19
> I can reproduce this back to 4.11.13. ~I will look into a fix.~ edit: If someone wants to try and implement the other solution in [#22694 (comment)](https://github.com/ionic-team/ionic-framework/issues/22694#issuecomment-748163096) or fix the issue using a modified `background-position` animation, please feel free! I will add the help wanted label.

I do not understand. I already attached a Solution for it?
Should i create a PR?

**Comment by liamdebeasi** [comment] 2020-12-18 18:31
If you think your solution would resolve the issue, then I recommend creating a PR. Instructions on how to do so can be found here: https://ionicframework.com/docs/contributing/how-to-contribute.

**Comment by liamdebeasi** [comment] 2021-05-24 12:52
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/22697, and a fix will be available in an upcoming release of Ionic Framework.

**Closed by liamdebeasi** 2021-05-24 12:52 UTC
Labels: help wanted, package: core, type: bug
