### ISSUE TITLE
bug: Month navigator on android not working

### ISSUE THREAD

**Issue by sufian1985** [ionic-team/ionic-framework#24511] opened 2022-01-05 03:10 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Currently it goes forward or back one month and after that it doesn't work. Then when you select any date of current month the month is automatically updated which shouldn't happen.
Using mode "ios" of datetime picker but issue replicating with mode "android" as well

### Expected Behavior

The month should be properly navigated and should not change when a date of the current month is selected

### Steps to Reproduce

This is how i have ion datetime within a modal

<ion-datetime
      style="border-radius: 0; border-top-left-radius: 15px; border-top-right-radius: 15px;"
      value="{{data}}"
      #popoverDatetime
      presentation={{presentationType}}
      [minuteValues]="minutesArr"
      hour-cycle="h12"
      (ionChange)="dateValue = popoverDatetime.value"
      [min]="minValue"
      [max]="maxValue"
      mode="ios"
    >  
    </ion-datetime>

### Ionic Info

Ionic:

   Ionic CLI                     : 6.18.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.1
   @angular-devkit/build-angular : 13.0.4
   @angular-devkit/schematics    : 13.0.4
   @angular/cli                  : 13.0.4
   @ionic/angular-toolkit        : 5.0.3

Capacitor:

   Capacitor CLI      : 3.3.3
   @capacitor/android : 3.3.3
   @capacitor/core    : 3.3.3
   @capacitor/ios     : 3.3.3

Utility:

   cordova-res (update available: 0.15.4) : 0.15.3
   native-run                             : 1.5.0

System:

   NodeJS : v14.18.1 (/usr/local/bin/node)
   npm    : 6.14.15
   OS     : macOS Monterey

**Comment by hatsantos** [comment] 2022-01-06 02:15
Maybe related to https://github.com/ionic-team/ionic-framework/issues/24500

**Comment by sufian1985** [comment] 2022-01-06 03:01
Yes i think it is the same issue

**Comment by amandaesmith3** [comment] 2022-01-06 15:11
Thanks for the issue. I'm going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/24500.

**Closed by amandaesmith3** 2022-01-06 15:11 UTC
Labels: holiday triage
