### ISSUE TITLE
Builder '@ionic/angular-toolkit:cordova-build' cannot be resolved.bug: 

### ISSUE THREAD

**Issue by camoi3** [ionic-team/ionic-framework#24914] opened 2022-03-09 21:29 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [X] v4.x
- [ ] v5.x
- [ ] v6.x

### Current Behavior

I can't run the command  >ionic cordova build android

Builder '@ionic/angular-toolkit:cordova-build' cannot be resolved.
Error: Builder '@ionic/angular-toolkit:cordova-build' cannot be resolved.

### Expected Behavior

crear apk para pruebas

### Steps to Reproduce

 run the command  >ionic cordova build android

### Ionic Info

Ionic:

   Ionic CLI                     : 6.18.1 (C:\Users\christian.montano\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 4.5.0
   @angular-devkit/build-angular : 0.13.10
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 6.0.0

Cordova:

   Cordova CLI       : 11.0.0
   Cordova Platforms : android 10.1.1, ios 4.5.5
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 8 other plugins)

Utility:

   cordova-res : 0.11.0
   native-run  : not installed globally

System:

   Android SDK Tools : 26.1.1 (C:\Users\christian.montano\AppData\Local\Android\android-sdk)
   NodeJS            : v16.14.0 (C:\Program Files\nodejs\node.exe)
   npm               : 8.5.2
   OS                : Windows 10

**Comment by liamdebeasi** [comment] 2022-03-09 22:43
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. Please make sure you have the `@ionic/cordova-builders` package installed: https://ionicframework.com/blog/updates-to-ionic-angular-toolkit/

This is noted in the breaking changes log for `@ionic/angular-toolkit@6.0.0`: https://github.com/ionic-team/angular-toolkit/releases/tag/%40ionic%2Fangular-toolkit%406.0.0

**Closed by liamdebeasi** 2022-03-09 22:43 UTC
Labels: triage
