### ISSUE TITLE
feat: Timeline component

### ISSUE THREAD

**Issue by GerardvdStelt** [ionic-team/ionic-framework#24390] opened 2021-12-14 09:28 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

A timeline component like https://mui.com/components/timeline/

### Describe the Use Case

Would be nice to have a timeline component available in Ionic.

**Comment by liamdebeasi** [comment] 2021-12-14 13:48
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/18491.

**Closed by liamdebeasi** 2021-12-14 13:48 UTC
Labels: triage
