### ISSUE TITLE
bug: ion-datetime min="2022" attribute causes hangups in date presentation

### ISSUE THREAD

**Issue by pkunszt** [ionic-team/ionic-framework#25736] opened 2022-08-07 08:01 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

When using the min attribute using a year only in date presentation (say min="2022"), the component will have at least two problems: 

1. the month-year dropdown will not show months and cannot be dismissed after the year has changed
2. navigating the month using the < > buttons in the top right corner will work upwards until the end of year. after december 2022, it switches to december 2021 and hangs, with the following message in the console:

[Ionic Warning]: The value provided to ion-datetime is out of bounds.

Min: {"year":2022}
Max: undefined
Value: {"year":1,"month":8,"day":7,"hour":9,"minute":39,"tzOffset":76}

### Expected Behavior

- The min="2022" attribute sets the minimum to January 1st 2022
- The min="2022-08" attribute sets the minimum to August 1st, 2022
- The min="2022-08-06" attribute sets the minimum to August 6th, 2022

the component behaves as advertised, the month navigation buttons < > work as expected, the year-month dropdown shows months-years only starting the given month.

### Steps to Reproduce

`<ion-datetime presentation="date"
              [min]="2022">
</ion-datetime>`

min is valid if i set the year only. if i set the value to year-month, then navigating the months backwards is buggy (cannot use < button to come back to january next year, and the year-month-dropdown shows only ONE year), there should be already an issue for that. however, for only the year in the date

- clicking on the month-year the dropdown often does not show the month, and after scrolling the wheel for year it gets stuck and cannot be closed

AND

- navigating beyond the end of the year (next month button > is presset at December of this year) will cause the component to show December 2001 (not January 2023), it cannot be navigated anymore (it hangs), and in the browser console (chromium) it shows the error given above.

### Ionic Info

Ionic:

   Ionic CLI                     : 6.20.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.2.1
   @angular-devkit/build-angular : 14.1.1
   @angular-devkit/schematics    : 14.1.1
   @angular/cli                  : 14.1.1
   @ionic/angular-toolkit        : 6.1.0

Utility:

   cordova-res (update available: 0.15.4) : 0.15.1
   native-run (update available: 1.6.0)   : 1.0.0

System:

   NodeJS : v14.18.0 (/usr/local/bin/node)
   npm    : 8.13.2
   OS     : macOS Monterey

**Comment by liamdebeasi** [comment] 2022-08-09 14:02
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/25708.

**Closed by liamdebeasi** 2022-08-09 14:02 UTC
Labels: triage
