### ISSUE TITLE
How to preload Ionic components in v5

### ISSUE THREAD

**Issue by rabhilashbanapuram** [ionic-team/ionic-framework#22183] opened 2020-09-26 11:20 UTC
# Bug Report

**Ionic version:**

[x] **5.x**

**Current behavior:**
Ionic components are downloaded only when they are requested.

**Expected behavior:**
Option to download Ionic components along with the webpage.

**Detailed Info**
We have an Ionic5-Angular app that is also being deployed as a web app. It’s nice that Ionic lazy loads all of its components - it greatly reduces the bundle size. However, we’re running into issues when it comes to user interactions that trigger lazy-loaded components.

As an example, we have a button that triggers a Dialog. When deployed, there is a noticeable delay between tapping the button and the dialog being displayed. When tested on a slow 2G internet connection, it took nearly a minute for the dialog to display.
Once it has loaded once everything is fine but we are finding that the more impatient users are tapping the button several times because it looks broken.

I want the web browser to download the ionic component together in advance while downloading the web page not when it’s requested.

Can somebody please tell me how to preload ionic components.

Thank you,
Abhilash

**Comment by Tommertom** [comment] 2020-09-27 18:43
You either need to remove lazy loading (so your routing and module setup needs to change), or use the angular service worker to prefetch all assets. The latter probably being easiest to try.

Don't think this is a bug, nor Ionic related though. More angular.

**Comment by elvisgraho** [comment] 2020-09-28 08:13
Why not load components that you need in app module and lazy load other components? In the description of your issue it seems that it is lazy-loading or not-lazy-loading issue when in fact you can use both in your application.

And with the button-tapping issue you can replace the button text with a spinner when the button is clicked.

**Comment by liamdebeasi** [comment] 2020-09-28 12:53
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/19016#issuecomment-641538817.

**Closed by liamdebeasi** 2020-09-28 12:53 UTC
Labels: triage
