### ISSUE TITLE
Ionic documentation on Status bar

### ISSUE THREAD

**Issue by NoxFly** [ionic-team/ionic-framework#25455] opened 2022-06-13 11:59 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Hello,

Here we see that the Ionic documentation says it's not compatible with Capacitor for this feature :
https://ionicframework.com/docs/native/status-bar#capacitor

Whilst it is, according to capacitor :
https://capacitorjs.com/docs/apis/status-bar

Is the doc not up to date for this feature ? Or is it really not compatible ?

### Describe the Use Case

/

**Comment by liamdebeasi** [comment] 2022-06-13 15:27
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework.

Those are two different packages for different projects. The first one is for a [awesome-cordova-plugins](https://github.com/danielsogl/awesome-cordova-plugins) (formerly known as Ionic Native) which provides plugins for Cordova/PhoneGap projects. The second one is for Capacitor.

**Closed by liamdebeasi** 2022-06-13 15:27 UTC
Labels: triage
