### ISSUE TITLE
bug: using switch/ngIf causes label to flicker

### ISSUE THREAD

**Issue by DavidStrausz** [ionic-team/ionic-framework#22541] opened 2020-11-20 16:32 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
When switching between multiple ion-item components with a stacked label they cause an ugly flicker. It seems like the label is first rendered in the default position and then it switches to the stacked position.
This was the way I noticed the bug - it probably also happens in a lot of other situations where an ion-item with a stacked label is rendered.

Example gif:

<img src="https://user-images.githubusercontent.com/7592254/99824278-ceff8980-2b55-11eb-826a-1da6859db705.gif" width="250">

**Expected behavior:**
No flicker :)

**Steps to reproduce:**

- Clone example repo
- npm i
- ionic s
- On Tab 1 use the segments to switch between the ion-items with stacked labels

**Related code:**
Github app: [stacked-label-flicker](https://github.com/DavidStrausz/stacked-label-flicker)

**Other information:**

- Happens in md and ios mode
- Happens with Angular 10 and 11
- Happens when running on a device and also when running the browser
- Happens with @ionic/angular 5.0.0 and also 5.5.0

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.4 (C:\Users\dstrauss.VENTO\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 5.5.0
   @angular-devkit/build-angular : 0.1100.2                                                      |   
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 11.0.2                                                        | 36
   @ionic/angular-toolkit        : 2.3.3
                                                                                                 |   
Utility:
                                                                                         -module | 12
   cordova-res : 0.15.1
   native-run  : 0.2.8

System:

   NodeJS : v14.3.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.5
   OS     : Windows 10
```

**Comment by DavidStrausz** [comment] 2021-01-25 16:48
FYI: The behaviour is still observable with ionic 5.5.2 and angular 11.1.0.

**Comment by Chreggii** [comment] 2021-04-08 09:22
Any update regarding this issue?

**Comment by sean-perkins** [comment] 2021-12-01 19:07
Follow-up on this issue.

The problem is that `ion-item` does not know to apply the `.item-label-stacked` class until after `ion-label` renders and emits `ionStyle`. This causes a render cycle to complete with the incorrect styles, before applying the correct class.

In the interim, you can help `ion-item` render correctly by directly applying the class to the element when you know it's contents contains a stacked label.

```html
<ion-item class="item-label-stacked">
  <ion-label position="stacked">Test</ion-label>
  <ion-input value="123"></ion-input>
</ion-item>
```

**Comment by DavidStrausz** [comment] 2021-12-02 14:54
Thank you @sean-perkins! The suggested workaround works perfectly for now!

**Comment by liamdebeasi** [comment] 2023-02-03 18:28
Thanks for the report. In Ionic 7 we are introducing a new syntax for working with ion-input. Additionally, Ionic 7 has a performance improvement for Ionic Angular that should reduce the initialization time for Ionic components. This issue is fixed when using the improvements in Ionic 7. Please see https://ionic.io/blog/announcing-the-ionic-7-beta for more on Ionic 7 as well as how to get started with the Ionic 7 beta.

The work required to resolve this has been completed, so I am going to close this thread. Let me know if there are any questions.

**Closed by liamdebeasi** 2023-02-03 18:28 UTC
Labels: package: angular, type: bug
