### ISSUE TITLE
bug: modal dismiss on backdrop tap while gesture

### ISSUE THREAD

**Issue by EinfachHans** [ionic-team/ionic-framework#22381] opened 2020-10-23 10:28 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

Just mentioned the following bug: While swiping down an iOS card style modal and you press with another finger on the backdrop, the gesture bugs and resets (the buggy itself can be webkit related)? And what it even more strange: If you press on the backdrop where a button in the modal would be, the click event is executed

**Expected behavior:**

While swiping the modal, a second tap (wherever) should not cause anything and should be ignored

**Steps to reproduce:**

**Related code:** 

Repo: https://github.com/EinfachHans/modal-backdrop-bug

Swipe down the modal and while swiping press with a finger on top of the backdrop. You will see that the gestures bugs and the alert (that is presented on the modals button) will be shown

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.12.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.4.1
   @angular-devkit/build-angular : 0.1000.8
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : ios 6.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 4 other plugins)

Utility:

   cordova-res                          : 0.15.1
   native-run (update available: 1.2.2) : 1.0.0

System:

   Android SDK Tools : 25.2.3 (/Users/hanskrywalsky/Library/Android/sdk)
   ios-deploy        : 1.10.0
   ios-sim           : 8.0.2
   NodeJS            : v12.18.3 (/usr/local/bin/node)
   npm               : 6.14.8
   OS                : macOS Catalina
   Xcode             : Xcode 12.1 Build version 12A7403
```

**Comment by liamdebeasi** [comment] 2020-10-23 13:50
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/21136. This feature would resolve the issue you are seeing.

**Closed by liamdebeasi** 2020-10-23 13:50 UTC
Labels: triage
