### ISSUE TITLE
bug: use vue in ionic is error

### ISSUE THREAD

**Issue by Darker1998** [ionic-team/ionic-framework#23566] opened 2021-07-02 07:17 UTC
![image](https://user-images.githubusercontent.com/47914523/124236058-9a6e9a00-db48-11eb-9906-65785aa24a8d.png)

**Comment by willmartindev** [comment] 2021-07-03 16:10
Thanks for the issue. I am going to close this as a duplicate of #23570

**Closed by willmartindev** 2021-07-03 16:10 UTC
Labels: triage
