### ISSUE TITLE
bug: angular (external), ion-item input disabled state does not get updated if formControl changes

### ISSUE THREAD

**Issue by muuvmuuv** [ionic-team/ionic-framework#25020] opened 2022-03-30 11:01 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [X] v4.x
- [X] v5.x
- [X] v6.x

### Current Behavior

Having an ion-input inside ion-item while replacing the FormControl for an ion-input does not update/trigger the item-interactive-disabled state, which results in all fields being disabled if they have been before the FormControl change.

### Expected Behavior

If the FormControl changes, trigger validation changes.

### Steps to Reproduce

- Put ion-input into ion-item
- Add Angular FormControl to ion-input
- Disable through FormControl
- Change the FormControl after some time
- Still disabled

### Code Reproduction URL

https://codesandbox.io/s/crazy-euler-z1kuve

### Ionic Info

Ionic:

   Ionic CLI : 6.18.2

Utility:

   cordova-res : 0.15.4
   native-run  : not installed globally

System:

   NodeJS : v16.13.2
   npm    : 8.1.2
   OS     : macOS Monterey

**Comment by amandaesmith3** [comment] 2022-04-04 14:15
Thanks for the issue. The linked CodeSandbox just shows a blank screen on my end ([screenshot](https://i.gyazo.com/42e9288683299207ad3445a9836ab550.png)). Could you have another look at it?

**Comment by muuvmuuv** [comment] 2022-04-05 12:34
@amandaesmith3 it should work again. Just some weird dep issues with codesandbox.

**Comment by amandaesmith3** [comment] 2022-04-05 13:57
Thanks, it's working now 👍 This is caused by a bug in Angular. If I do the same with a plain `<input>`, the same behavior happens. It looks like this is the issue to follow in the Angular repo: https://github.com/angular/angular/issues/35309 I also found a couple others that have some potential workarounds: https://github.com/angular/angular/issues/15206 | https://github.com/angular/angular/issues/17806

**Comment by muuvmuuv** [comment] 2022-04-06 08:56
@amandaesmith3 thanks, you are right. I thought it was specifically to the ion-input, but that makes sense and the Angular Issues seem to be what I am experiencing, so I am closing this here.

**Comment by amandaesmith3** [comment] 2022-04-06 13:48
I'll keep this open so other people can find it if they run into the same thing. We'll close the issue once things are resolved on Angular's side 👍

**Comment by liamdebeasi** [comment] 2022-11-21 22:43
Hey there,

It looks like this was resolved in Angular (https://github.com/angular/angular/issues/35309) so I am going to close this. Please let me know if you have any questions.

**Closed by liamdebeasi** 2022-11-21 22:43 UTC
Labels: type: bug, bug: external
