### ISSUE TITLE
bug: Ionic React / SwiperJS incompatibility

### ISSUE THREAD

**Issue by Toto5931** [ionic-team/ionic-framework#22001] opened 2020-08-28 17:52 UTC
#Bug Report

**Ionic version:**
[x] **5.3.2

**Current behavior:**
In a blank Ionic application, the Swiper from swiperjs.com does not work:
When moving to the next slide, the spring effect that moves the slide back in its original position at mouse up does not work. The slide stays at the middle, at the position where the mouse left it.
However it works well in a simple react app without Ionic

Note: I am using the Swiper directly instead of IonSlides due to the issue https://github.com/ionic-team/ionic-framework/issues/18784 

**Expected behavior:**
The slide should go back in the correct position at mouse up.

**Steps to reproduce:**
https://github.com/Toto5931/ionic_swiper_bug

**Related code:**

```
<IonApp>
    <IonPage>
      <IonContent>

        <Swiper>
          <SwiperSlide>Slide1</SwiperSlide>
          <SwiperSlide>Slide2</SwiperSlide>
          <SwiperSlide>Slide3</SwiperSlide>
        </Swiper>

      </IonContent>
    </IonPage>
  </IonApp>
```

**Other information:**

**Ionic info:**
```
Ionic:

   Ionic CLI       : 6.5.0 (C:\Users\zorro\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/react 5.3.2

Capacitor:

   Capacitor CLI   : 2.4.0
   @capacitor/core : 2.4.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.16.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.13.4
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment] 2020-08-28 18:25
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. We only support Swiper usage via the `ion-slides` component because it has additional code that helps it work better in Ionic Framework. I will look into https://github.com/ionic-team/ionic-framework/issues/18784 to try and get it resolved.

**Closed by liamdebeasi** 2020-08-28 18:25 UTC
Labels: triage

**Comment by Toto5931** [comment] 2020-09-04 07:57
Thank you for you help. Do you know when #18784 could be resolved? 
Thanks
