### ISSUE TITLE
bug: leaving view still scrollable during swipe to go back

### ISSUE THREAD

**Issue by supersongpiao** [ionic-team/ionic-framework#19206] opened 2019-08-28 07:25 UTC
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

In the use of gestures to slide back, ion-item-sliding slides and ion-slides slides, these horizontal slides do not allow vertical sliding. When I use these features to slide horizontally, the page can slide vertically, I think this experience is not very friendly, these problems only exist on the iPhone.

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**Comment by liamdebeasi** [comment] 2019-08-29 13:15
Thanks for this issue. This seems like a bug the more I think about it. Can you provide steps to reproduce the issue you are describing?

**Comment by supersongpiao** [comment] 2019-08-30 08:22
> Thanks for this issue. This seems like a bug the more I think about it. Can you provide steps to reproduce the issue you are describing?


![CB552BC5ABF6D694F686A712CC26D756](https://user-images.githubusercontent.com/31645741/64005063-25903a80-cb42-11e9-911b-b28bfa9fa7ba.gif)
![E82CE4E092D5D895EA31906D84B170BF](https://user-images.githubusercontent.com/31645741/64005064-25903a80-cb42-11e9-841a-64c04a72fcd0.gif)
![FE0BF642EABBE6AD48820ADCC26C4723](https://user-images.githubusercontent.com/31645741/64005067-2628d100-cb42-11e9-8d6a-7440aafbd7ba.gif)

I selected three gifs to show the problems I encountered.

**Comment by liamdebeasi** [comment] 2021-08-19 20:56
Thanks for the issue. This looks like it was resolved in [Framework v5.6.11](https://github.com/ionic-team/ionic-framework/releases/tag/v5.6.11). I am no longer able to reproduce this issue, so I am going to close this out.

If you can still reproduce the issue, please feel free to reply with a code reproduction, and I will be more than happy to take another look.

**Closed by liamdebeasi** 2021-08-19 20:56 UTC
Labels: package: core, type: bug
