### ISSUE TITLE
bug: ion-datetime 6.0.7 sometimes still jumps 2 months + swipe/drag doesn't work (Android)

### ISSUE THREAD

**Issue by ciccilleju** [ionic-team/ionic-framework#24770] opened 2022-02-10 22:24 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

If I use a ion datetime inside a popover and I try to drag/swipe for changing months it doesn't work (android) and sometimes it jumps (even after the 6.0.7 update) 2 months as you can see from the video. The issue occurs on Android only, works fine on iOS and Pwa

### Expected Behavior

Swipe should display next/prev month and not stopping at half size

### Steps to Reproduce

Swipe from  left to right the datetime window and push the arrow

### Ionic Info

Ionic CLI : 6.18.1 (/usr/local/lib/node_modules/@ionic/cli)
Ionic Framework : @ionic/angular 6.0.7
@angular-devkit/build-angular : 13.2.2
@angular-devkit/schematics : 13.2.2
@angular/cli : 13.2.2
@ionic/angular-toolkit : 6.0.0

Capacitor:

Capacitor CLI : 3.4.0
@capacitor/android : 3.4.0
@capacitor/core : 3.4.0
@capacitor/ios : 3.4.0 #

**Comment by ciccilleju** [comment] 2022-02-10 23:02
Here the video

**Comment by ciccilleju** [comment] 2022-02-10 23:08
If I create a new app the datetime now works fine with version 6.0.7 but my app (where I previously had 6.0.5) doesn't work. There is something (like a cache) that maybe is still in my node modules?
What do you suggest?

**Comment by indraraj26** [comment] 2022-02-11 07:17
if with latest version is working fine the. i would suggest delete node-modules folder and package-lock.json then do npm i

Also do let me know how did you upgrade the project from 6.0.5 to 6.0.7

**Comment by ciccilleju** [comment] 2022-02-11 07:21
> if with latest version is working fine the. i would suggest delete node-modules folder and package-lock.json then do npm i
> 
> Also do let me know how did you upgrade the project from 6.0.5 to 6.0.7

I've updated with npm install @ionic/angular@latest and @ionic/core@latest   

I tried to delete node modules folder and then I wasn't able to use the app, even after reinstalling all the dependencies. 
I will try again today

The weird thing is that I only face this issue on android

**Comment by ciccilleju** [comment] 2022-02-11 17:13
I think I've solved the mistery: I had "mode: ios" in my app.module.ts file
Removing it made the datetime working again

**Comment by indraraj26** [comment] 2022-02-12 04:25
if you are sure because of that you had jump behavior on date-time. Please share reproducible repo to reproduce it with that we can have proper fix .

**Comment by ciccilleju** [comment] 2022-02-12 07:12
Yes, i will upload it within this week 

https://user-images.githubusercontent.com/42606234/153701231-51c0b846-bd7a-4897-8bef-df91a213b34d.mp4

**Comment by cspurple** [comment] 2022-02-24 06:49
Updating to 6.0.9 appears to fix the issue in the reproduction above. Previously it was not working with 6.0.7, 6.0.8.

**Comment by liamdebeasi** [comment] 2022-02-24 15:00
Thanks! Ionic 6.0.9 was released yesterday which has fixes for datetime that should resolve this issue.

I am going to close this. If you are still running into problems, please open a new issue and provide a reproduction.

**Closed by liamdebeasi** 2022-02-24 15:00 UTC
Labels: triage
