### ISSUE TITLE
bug: admob video reward is not loading to screen

### ISSUE THREAD

**Issue by ivanov84** [ionic-team/ionic-framework#21816] opened 2020-07-25 17:45 UTC
#21775 Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
video reward does not start or fail

**Expected behavior:**
video reward starts and user should see at on screen

**Steps to reproduce:**
1. Create simple app with admob and ionic-webview
2. Add button and write logic to run video reward
3. Attach simple mediation in order to get video ad always. Just create in root android folder file "build-extras.gradle" and add few lines:
```
dependencies {
    implementation 'com.unity3d.ads:unity-ads:2.2.1'
    implementation 'com.google.ads.mediation:unity:2.2.1.0'
}
```

**Related code:**
Process stops with this last log and don't give either succeed or fail:
D/CordovaWebViewImpl: >>> loadUrl(javascript:cordova.fireDocumentEvent('admob.rewardvideo.events.LOAD');)

All troubles start when I installed ionic 5.

**If I get www folder from my previous apk and make new build with cordova then all works fine.
But if I put in cordova "new generated with ionic 5 build" with exactly the same code from ionic 4 then works nothing.**

My idea: I think that emiter "Load video" is not caught with new ionic build because ionic "core" work different then before. I dont know what is in ionic source code. So I need help. Please help.

admob plugin:
https://github.com/ratson/cordova-plugin-admob-free

I think that something go wrong in this place:
https://github.com/ratson/cordova-plugin-admob-free/blob/master/src/js/reward-video.js#L65

I checked that "prepared" status passes and then calls that line. I don't know what is happening next.

Logic for ionic:
```
    Start() {
        const options: AdMobFreeRewardVideoConfig = {
            id: 'ca-app-pub-000000000000000000000/000000000',
            isTesting: true,
            autoShow: false
        };

        this.adMobFree.rewardVideo.config(options);

        this.adMobFree.rewardVideo.prepare().then((data) => {
            this.adMobFree.rewardVideo.show();
        }).catch(e =>
            console.log('PROBLEM LOADING REWARDVIDEO: ', e)
        );
    }
```

![image](https://user-images.githubusercontent.com/9296077/88462530-ae2f6c00-ceb4-11ea-83e9-72fdf8db90c1.png)

**Comment by ivanov84** [comment] 2020-07-25 19:14
SOOOOOOOLVED!!!!!!! 😆😆😆

It's a really BUG!!!!!

This construction really does not work in new ionic 5!!!!

```
const options: AdMobFreeRewardVideoConfig = {
  id: 'ca-app-pub-000000000000000000000/000000000',
  isTesting: true,
  autoShow: false
};

this.adMobFree.rewardVideo.config(options);

this.adMobFree.rewardVideo.prepare().then((data) => {
  this.adMobFree.rewardVideo.show();
});
```


But we can disable **autoShow: false** and delete  **this.adMobFree.rewardVideo.show();** and video reward starts to work!!!

P.S.: in new ionic some one forgot to add this method "show()" in somewhere in source code 😉

**Comment by liamdebeasi** [comment] 2020-07-27 12:54
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. We do not manage the AdMob plugin, so I recommend you file an issue with the plugin author on their repo: https://github.com/ratson/cordova-plugin-admob-free

**Closed by liamdebeasi** 2020-07-27 12:54 UTC
Labels: triage

**Comment by ivanov84** [comment] 2020-07-29 08:35
@liamdebeasi it a bug in Ionix Framework!!!! You didn't call methid show() for reward video in "index.d.ts" or something. Please read explanations carefully.

**Comment by ivanov84** [comment] 2020-07-29 08:36
@liamdebeasi it is a bug in @ionic-native/admob-free

**Comment by liamdebeasi** [comment] 2020-07-29 12:54
This repo is dedicated to bugs pertaining to Ionic Framework, not Ionic Native. The repo for Ionic Native is https://github.com/ionic-team/ionic-native.

Additionally, the `@ionic-native/admob-free` package is just a wrapper around the Cordova admob plugin. If there is a bug in the plugin's functionality it is likely an issue with the Cordova plugin. If there is an issue with the types, it is possible it is an Ionic Native issue, and I recommend you open an issue on that repo.

**Comment by ivanov84** [comment] 2020-08-07 14:39
@liamdebeasi I think it's bug with wrapper because in ionic 4 all works fine

**Comment by liamdebeasi** [comment] 2020-08-07 18:45
I recommend opening an issue on https://github.com/ionic-team/ionic-native.

**Comment by ivanov84** [comment] 2020-08-07 21:49
@liamdebeasi I wrote that I found way around. No need. Thanks.
