### ISSUE TITLE
feat: IonSlides should watch for changes inside the options Input, not just the whole object

### ISSUE THREAD

**Issue by dpalou** [ionic-team/ionic-framework#22618] opened 2020-12-03 10:45 UTC
# Feature Request

**Ionic version:**
[x] **5.5.1**

**Describe the Feature Request**
If you initialize IonSlides with a certain _options_ object and afterwards you change some property of that _options_ object, the new value isn't applied. The only way for IonSlides to detect the change is to re-create the whole options object. In our case we have an issue with _slidesPerView_, we change the value dynamically and it doesn't get updated.

Example:

```
<ion-slides [options]="slideOpts">

slideOpts = {
    slidesPerView: 3,
};
...
updateSlides(): void {
    ...
    this.slideOpts.slidesPerView = newSlidesPerView;
}
```

The code above doesn't work. However, if I add this line at the end then it does work:

`this.slideOpts = Object.assign({}, this.slideOpts);`

**Describe Preferred Solution**
Ideally IonSlides should detect that a property has changed and update the Swiper without having to re-create the options object.

**Describe Alternatives**
The only way I found to make it work is re-creating the options object. We have several pages with slides, so this workaround needs to be applied in all those pages.

**Comment by liamdebeasi** [comment] 2020-12-03 14:27
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. This behavior is due to how Stencil (what Ionic Framework is built with) works. When updating a reactive object, you should use the spread operator as mutating an object will not trigger an update:

```js
this.slidesOpts = { ...this.slidesOpts, slidesPerView: newSlidesPerView }
```

For more information please see: https://stenciljs.com/docs/reactive-data#updating-an-object

**Closed by liamdebeasi** 2020-12-03 14:27 UTC
Labels: triage
