### ISSUE TITLE
feat: to be able to scroll ion-picker options with mouse scroll wheel

### ISSUE THREAD

**Issue by alperkay** [ionic-team/ionic-framework#24614] opened 2022-01-20 19:28 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

When the user is on a desktop browser, the ion-picker should be able to scrollable with mousewheel. 

### Describe the Use Case

Currently, the user has to drag with the mouse and it's not a nice user experience.

**Comment by liamdebeasi** [comment] 2022-01-20 21:18
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/15505.

**Closed by liamdebeasi** 2022-01-20 21:18 UTC
Labels: triage
