### ISSUE TITLE
bug: [Angular][TypeScript] Incorrect "ionScroll" event typing

### ISSUE THREAD

**Issue by hakimio** [ionic-team/ionic-framework#24392] opened 2021-12-14 09:55 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Correctly typed `ion-content` `ionScroll` event handler like in the following example fails to compile in production build when Angular `strictTemplates` are enabled in `tsconfig.json` (default behavior for new Angular v12 and v13 projects).
```ts
onContentScroll(scrollEvent: CustomEvent<ScrollDetail>) {
    // some code
}
```
Angular expects `scrollEvent` to be typed as `Event`, but it's actually `CustomEvent`.
Error:
```
Argument of type 'Event' is not assignable to parameter of type 'CustomEvent<ScrollDetail>'.
Type 'Event' is missing the following properties from type 'CustomEvent<ScrollDetail>': detail, initCustomEvent
```

### Expected Behavior

Production build should succeed without any errors when Angular `strictTemplates` are enabled.

### Steps to Reproduce

- Enable Angular `strictTemplates`
- Set correct typing for your `ion-content` scroll event argument (`CustomEvent<ScrollDetail>`)
- Try to compile production build of your Angular app.

### Ionic Info

Ionic CLI                     : 6.18.1
   Ionic Framework               : @ionic/angular 6.0.0
   @angular-devkit/build-angular : 13.0.2
   @angular-devkit/schematics    : 13.0.2
   @angular/cli                  : 13.0.2
   @ionic/angular-toolkit        : 5.0.4-testing.4

Capacitor:

   Capacitor CLI      : 3.3.1
   @capacitor/android : not installed
   @capacitor/core    : 3.3.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.3
   native-run  : 1.5.0

System:

   NodeJS : v14.18.1
   npm    : 7.24.2
   OS     : Windows 10

**Comment by liamdebeasi** [comment] 2021-12-14 13:52
Thanks for the issue. In Ionic 6 we added new interfaces to help with this. Can you try using the `ScrollCustomEvent` instead?

```typescript
import { ScrollCustomEvent } from '@ionic/angular';

onContentScroll(scrollEvent: ScrollCustomEvent) {
    // some code
}
```

See https://ionicframework.com/docs/api/content#scrollcustomevent for more info.

**Comment by liamdebeasi** [comment] 2021-12-14 13:53
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/24245.

**Closed by liamdebeasi** 2021-12-14 13:53 UTC
Labels: needs: reply
