### ISSUE TITLE
bug: ionic vue modal and popover do not get application context

### ISSUE THREAD

**Issue by dev-kr2020** [ionic-team/ionic-framework#22079] opened 2020-09-12 19:15 UTC
Ionic Vue beta  with Vue 3...  Vue vue-i18n-next is not working .. tab1 in sample
<template>
  <ion-page>
    <ion-header>
      <ion-toolbar>
        <ion-title>Tab 1</ion-title>
      </ion-toolbar>

    </ion-header>
    <ion-content :fullscreen="true">
      <ion-header collapse="condense">
        <ion-toolbar>
          <ion-title size="large">Tab 1</ion-title>
          <p>{{ t("message.hello") }}</p>
        </ion-toolbar>
      </ion-header>     
     
      <ExploreContainer name="Tab 1 page" />
    </ion-content>
  </ion-page>
</template>

<script>
import { IonPage, IonHeader, IonToolbar, IonTitle, IonContent } from '@ionic/vue';
import ExploreContainer from '@/components/ExploreContainer.vue';

export default  {
  name: 'Tab1',
  components: { ExploreContainer, IonHeader, IonToolbar, IonTitle, IonContent, IonPage }
}
</script>

**Comment by dev-kr2020** [comment] 2020-09-14 13:49
create project as instructed in the beta release article
added vue-i18n-next to it. In main.ts.. import import i18n from '@/i18n' and add .use(i18n) to app instance. 
****
main.ts
**********
import i18n from '@/i18n'
......
createApp(App).use(store).use(i18n).......

*******************
i18n.ts
*******************
import { createI18n, LocaleMessages, VueMessageType } from 'vue-i18n'

function loadLocaleMessages() {
const locales = require.context('./locales', true, /[A-Za-z0-9-,\s]+.json$/i)
const messages: LocaleMessages = {}
locales.keys().forEach(key => {
const matched = key.match(/([A-Za-z0-9-]+)./i)
if (matched && matched.length > 1) {
const locale = matched[1]
messages[locale] = locales(key)
}
})
return messages
}
const i18n = createI18n({

locale: process.env.VUE_APP_I18N_LOCALE || 'en',
fallbackLocale: process.env.VUE_APP_I18N_FALLBACK_LOCALE || 'en',
messages: loadLocaleMessages()

})

export default i18n;
*****************
/locale/en.json
*****************
{
"message": {
"hello": "hello world",
}
} 

*******************
in tab1.ts add {{ t("message.hello") }} there is no error displayed but all tab view will go-off
***************

**Comment by dev-kr2020** [comment] 2020-09-23 23:04
Below is the repository -code - only vue3 with i18n works but with ion it do not 
https://github.com/dev-kr2020/sample-vue3-i18n

https://github.com/dev-kr2020/sample-ionicvue3-i18n

getting following error
Uncaught (in promise) TypeError: _ctx.t is not a function
    at eval (eval at ./node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/vue-loader-v16/dist/templateLoader.js?!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader-v16/dist/index.js?!./src/views/Tabs.vue?vue&type=template&id=6a83f7b8&bindings={"ellipse":"setup","square":"setup","triangle":"setup"} (app.js:1054), <anonymous>:41:160)

**Comment by dev-kr2020** [comment] 2020-09-24 13:09
@liamdebeasi sample code is provided

**Comment by liamdebeasi** [comment] 2020-09-24 14:27
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. This looks to be an incorrect usage of `vue-i18n`:

1. In `Tabs.vue` you did not import `useI18n`, so the `t` function is not going to be defined.
2. Once you do import it, you need to make sure you return the `t` function in `setup` after calling `useI18n`:

```typescript
...
setup() {
  const { t } = useI18n();

  return {
    ellipse,
    square,
    triangle,
    t
  }
}
```

In your Ionic Vue application, I was able to get I18N support working after doing those two things.

**Comment by dev-kr2020** [comment] 2020-09-24 17:19
that worked .. thanks a lot..

**Comment by dev-kr2020** [comment] 2020-09-24 20:25
one more question: for  popoverController and other control, do i have to do same setup to get this.$ionic

**Comment by liamdebeasi** [comment] 2020-09-24 20:33
It's a bit different now. You have 2 options: controller or in-template. We are still working on docs for both, but here is how you would use them. You will need to be on Ionic Vue 0.5.0 or newer to use the in-template components.

**Controller**

You can use overlays via a controller by importing the component's appropriate controller:
```typescript
<template>
  <ion-page>
    <ion-content>
      <ion-button @click="openPopover">Open Popover</ion-button>
    </ion-content>
  </ion-page>
</template>

<script lang="ts">
import { 
  IonButton, 
  IonContent, 
  IonPage,
  popoverController
} from '@ionic/vue';
import { defineComponent } from 'vue';
import PopoverContentComponent from '@/components/PopoverContentComponent.vue';

export default defineComponent({
  name: 'Home',
  components: {
    IonButton, 
    IonContent, 
    IonPage
  },
  setup() {
    const openPopover = async () => {
      const popover = await popoverController.create({
        component: PopoverContentComponent,
        ...
      });

     await popover.present();
    }
    
    return { openPopover }
  }
})
```

**Template**

You can use overlays such as popover in template if you would prefer not to import a controller:
```typescript
<template>
  <ion-page>
    <ion-content>
      <ion-button @click="setPopoverOpen">Open Popover</ion-button>
      
      <ion-popover
        css-class="my-popover-class"
        :is-open="isPopoverOpen"
        @onDidDismiss="setPopoverClosed"
      >
        <PopoverContentComponent></PopoverContentComponent>
      </ion-popover>
    </ion-content>
  </ion-page>
</template>

<script lang="ts">
import { 
  IonButton, 
  IonContent, 
  IonPopover, 
  IonPage
} from '@ionic/vue';
import { defineComponent, ref } from 'vue';
import PopoverContentComponent from '@/components/PopoverContentComponent.vue';

export default defineComponent({
  name: 'Home',
  components: {
    PopoverContentComponent,
    IonButton, 
    IonContent, 
    IonPopover, 
    IonPage
  },
  setup() {
    const isPopoverOpen = ref(false);
    const setPopoverOpen = () => isPopoverOpen.value = true;
    const setPopoverClosed = () => isPopoverOpen.value = false;
    
    return {
      isPopoverOpen,
      setPopoverOpen,
      setPopoverClosed
    }
  }
})
```

**Comment by dev-kr2020** [comment] 2020-09-25 20:04
thanks but i am getting following error
framework-delegate-d1eb6504.js?b457:11 Uncaught (in promise) Error: framework delegate is missing
    at eval (framework-delegate-d1eb6504.js?b457:11)
    at step (tslib.es6.js?9ab4:100)
    at Object.eval [as next] (tslib.es6.js?9ab4:81)
    at eval (tslib.es6.js?9ab4:74)
    at new Promise (<anonymous>)
    at __awaiter (tslib.es6.js?9ab4:70)
    at attachComponent (framework-delegate-d1eb6504.js?b457:2)
    at class_1.eval (ion-popover.entry.js?4285:313)
    at step (tslib.es6.js?9ab4:100)
    at Object.eval [as next] (tslib.es6.js?9ab4:81)

**Comment by dev-kr2020** [comment] 2020-09-25 21:36
here is the source code
https://github.com/dev-kr2020/sample-ionicvue3-i18n

Issues
1. Popover is giving error - framework delegation
2. Navigate from menu with have tab -  to login, you will see all tab buttons even through it is different page
3. if you go with login to log out .. you will see 2 headers

your help will be appreciated.

**Comment by liamdebeasi** [comment] 2020-09-28 13:30
Please update to Ionic Vue 0.5.0 these issues have been resolved already.

**Comment by dev-kr2020** [comment] 2020-09-29 12:52
@liamdebeasi : updated to 0.5.0 and delegation error is no longer coming up, but popover is not taking parent property. Checked the example updated in document but it do not say anything on how to pass values between popover or modal

**Comment by liamdebeasi** [comment] 2020-09-29 13:28
If using a controller, you pass in data as you would normally:

```typescript
await modalController
  .create({
    component: Modal,
    componentProps: {
      title: 'Hello World'
    }
  });
```

If you are using an overlay in-template, you set the data directly as a prop:

```html
<ion-modal
  :is-open="isOpenRef"
  @onDidDismiss="setIsOpen(false)"
  title="Hello World"
>
  <Modal></Modal>
</ion-modal>
```

**Comment by dev-kr2020** [comment] 2020-09-29 13:33
triggering method on parent when changes happens in popover.. 
$parent, $store, $i18n, context are not coming up in popover and modal.. normally it should pass as it popover is another component and all global or context variable should be available. unfortunately it is not. thats why we used to pass parent and access all context related variables from parents. below is the discussion on this
https://github.com/ModusCreateOrg/ionic-vue/issues/38
Now passing parent is not taking in.. any other solution

**Comment by liamdebeasi** [comment] 2020-09-29 13:56
Can you update your example to show this issue happening? Also the issue in https://github.com/ModusCreateOrg/ionic-vue/issues/38 is not for our Ionic Vue integration -- that is a different package.

**Comment by dev-kr2020** [comment] 2020-09-29 14:35
updated source code in below repository 
https://github.com/dev-kr2020/sample-ionicvue3-i18n

1. Popover (filter in header component) is not taking context hence it is not coming up
2. Popover have save button which will call parent method to save filter - not able to get to this point
3. in Account page, Ion-item disable property is not binding .. it is not toggling

**Comment by dev-kr2020** [comment] 2020-09-29 14:41
also in  https://github.com/ModusCreateOrg/ionic-vue/issues/38 , they are talking about vuex, global variable $store which is popular integration with vue for store. this $store should be available to popover, modal.. etc. i will try to update the example

**Comment by liamdebeasi** [comment] 2020-09-29 16:38
Thanks! #3 should be resolved by https://github.com/ionic-team/ionic-framework/pull/22204. I am still looking into #1. It looks like when we dynamically create Vue components, they are not linked up to the global application context, leading to the errors you are experiencing.

**Comment by liamdebeasi** [comment] 2020-09-30 14:30
I am going to re-open this so I can properly track a fix for issue 1 in https://github.com/ionic-team/ionic-framework/issues/22079#issuecomment-700748377.

**Comment by dev-kr2020** [comment] 2020-09-30 16:05
@liamdebeasi : updated the project https://github.com/dev-kr2020/sample-ionicvue3-i18n with 
1. Shows store functionality 
2. showing bug
a. select component popover interface is not showing up properly in account example 
b. we should able to use component HeaderFilterPopover as popover or page - filter example is added
c. modal or popover should able to take page as well as component - there should not be any difference as page is also a component

**Comment by Livijn** [comment] 2020-10-02 11:54
I suppose this is why I am receiving tons of warnings from components used in my modal: 
```
[Vue warn]: injection "navManager" not found. 
  at <Anonymous color="white" fill="clear" onClick=fn<bound close> > 
  at <Anonymous slot="start" > 
  at <Anonymous color="primary" > 
  at <Anonymous> 
  at <IonPage> 
  at <SearchModal >
```

**Comment by dev-kr2020** [comment] 2020-10-05 12:37
not getting any of the warning... please check

**Comment by liamdebeasi** [comment] 2020-10-08 19:57
Hi everyone,

Can you try the following dev build and let me know if it resolves the issue?

```
npm install @ionic/vue@5.4.0-dev.202010081857.bfc0b25 @ionic/vue-router@5.4.0-dev.202010081857.bfc0b25 --save-exact
```

@dev-kr2020 There are a few changes you will need to make regarding the original workarounds you had in place:

1. You no longer need to pass in `this` in `componentProps` in `Header.vue`
2. You do not need to use the `ion-page` component in `HeaderFilterPopover.vue` - that component is only for pages tied to routing. Though if you plan to use `HeaderFilterPopover` as an actual page tied to routing, you should keep it.
3. `this.$parent.saveFilter` will not work here because `HeaderFilterPopover` is not rendered as a child of `Header`. You can either pass the `saveFilter` method in as a prop, or move it to a shared utility file.

**Comment by xlanghejianfeng** [comment] 2020-10-09 06:36
runtime-core.esm-bundler.js?5c40:38 [Vue warn]: injection "navManager" not found. 
  at <Anonymous slot="end" color="light" onClick=fn<dismiss> > 
  at <Anonymous slot="end" > 
  at <Anonymous color="primary" > 
  at <IonHeader> 
  at <Modal>


not work   modal

**Comment by liamdebeasi** [comment] 2020-10-09 13:32
@xlanghejianfeng  Can you please provide a GitHub repo that I can use to reproduce the issue?

**Comment by dev-kr2020** [comment] 2020-10-09 15:51
@liamdebeasi 
Looks like Popover is working fine but there is a issue with modal
1. when modal component along with ion-page is used, modal is coming up with no visibility of contents. when i click mouse on content events are generating. it is rendering but not visible. 
2. When i use div as root for modal component contents are shrink to button height with vertical scroll,  to avoid this i have to use  class="ion-page" for div. 
3. storeFront icon is not defined in ion/vue .. -- what is the strategy to include newly available icons to ion-vue?

**Comment by liamdebeasi** [comment] 2020-10-09 17:04
> @liamdebeasi
> Looks like Popover is working fine but there is a issue with modal
> 
> 1. when modal component along with ion-page is used, modal is coming up with no visibility of contents. when i click mouse on content events are generating. it is rendering but not visible.
> 2. When i use div as root for modal component contents are shrink to button height with vertical scroll,  to avoid this i have to use  class="ion-page" for div.
> 3. storeFront icon is not defined in ion/vue .. -- what is the strategy to include newly available icons to ion-vue?
> 4. Modal backdrop is not closing the modal

1. This is a bug. I will fix -thanks!
2. Can you provide a code reproduction of the issue in your repo?
3. You likely have an old version of ionicons. Try updating to the latest: `npm install ionicons@latest`
4. Can you provide a code reproduction of the issue in your repo? I cannot reproduce this.

**Comment by dev-kr2020** [comment] 2020-10-12 13:55
@liamdebeasi : updated the project https://github.com/dev-kr2020/sample-ionicvue3-i18n with
1. Edit a/c from header - using ion-page - rendering but not visible
2. filter - radio options is not taking the component properly - it is not displaying the chip/icon   - this will save lots of effort
3. When you select filter from menu - it says "can't set the property mounted -  i think this is because filter component root element is div and not page. if i change to page, then header filter will not work. 
4. Modal, popover component when used inline in template or as with in method... all options should be available, like defining the emits, passing function as props, capturing emits..

and thanks for the storefront icon resolution.

**Comment by liamdebeasi** [comment] 2020-10-12 15:45
@dev-kr2020

1. Yes, this is a bug. I will address this separately.
2. Where are you setting the icons? I do not see any icons being used in `HeaderFilterPopover.vue`.
3. Selecting "Filter" from the ion-menu does not throw this error for me.
4. I am not sure this makes sense to do. When using Modal and Popover inline in a template, I think it makes more sense to set props, defining emits, etc directly on the component rather than on `ion-modal` or `ion-popver`. We cover this briefly in our usage docs: https://ionicframework.com/docs/api/modal#usage (switch to the Vue tab). That being said, you can set `component-props` on `ion-modal` to pass to your component, but I think at that point it is easier to set them directly on the user-defined component.

I am going to close this issue out shortly as it sounds like the original issue (modals and popovers are not getting application context) has been resolved. For any other issues you are running into, please create a new issue. Thanks!

**Comment by liamdebeasi** [comment] 2020-10-12 19:07
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/22282, and a fix will be available in an upcoming release of Ionic Framework.

I will address the `ion-page` issue here:

**Closed by liamdebeasi** 2020-10-12 19:07 UTC
Labels: package: vue, type: bug
