### ISSUE TITLE
bug:  route change triggers url change but does not render

### ISSUE THREAD

**Issue by tx-tim** [ionic-team/ionic-framework#21746] opened 2020-07-13 20:50 UTC
# Bug Report

**Ionic version:**
[x]   "@ionic/react": "^5.0.7",
[x]   "@ionic/react-router": "^5.0.7"

I'm attempting to set up two "sections" of the app - one for authentication and one for the application.  The application should be rendered within an IonTabBar but authentication components should not; they should just have the components needed to credential or register.

**Current behavior:**
Login components are rendered at /login.  At this point context.isAuthed is `false`
Click login navigates to /tab1
context.isAuthed updates to `true`
url changes to /tab1
Login components render
IonTabBar does not render
Tab1 components do not render within IonTabBar

**Expected behavior:**
Login components are rendered at `/login`.  At this point context.isAuthed is `false`
Click login navigates to /tab1
context.isAuthed updates to `true`
url changes to `/tab1`
IonTabBar renders
Tab1 components render within IonTabBar
Login components do not render

Similar to #20707 

**Video of the bug:**
![Jul-13-2020 15-19-38](https://user-images.githubusercontent.com/636371/87350146-111c1d00-c51d-11ea-9889-0b76262a7d3b.gif)

**Related code:**
This is the routing code in App.tsx

```
    <IonApp>
      <Context.Provider value={[context, setContext]}>
        <IonReactRouter>
          <IonRouterOutlet>
            <Route
              path="/"
              exact
              render={() => {
                console.log(
                  "App - route render redirect context.isAuthed",
                  context.isAuthed
                );
                return context.isAuthed ? (
                  <Redirect to="/tabcontainer" />
                ) : (
                  <Redirect to="/login" />
                );
              }}
            />
            <Route path="/login" component={Login} exact />
            <Route path="/tabcontainer" component={TabContainer} exact />
          </IonRouterOutlet>
        </IonReactRouter>
      </Context.Provider>
    </IonApp>
```
I did it this way because the docs at https://ionicframework.com/docs/react/navigation say "Switch from React Router has no effect when used inside of an IonRouterOutlet"

Note that, after some investigation, I did add the`Switch` component as a direct child of `IonRouterOutlet`.  The `Switch` does take effect when navigating to Tab 1 (via redirect to check if `context.isAuthed == true`) 

However, when setting the url programmatically e.g. when logging out
```
        <IonButton
          onClick={(e) => {
            console.log("e", e);
            setContext({ isAuthed: false });
            console.log(
              "isAuthed in explorecontainer context.isAuthed",
              context.isAuthed
            );
            history.replace("/login");
          }}
        >
          Logout
        </IonButton>
```

The url is changed but the view does not update.

I'm open the the idea that I'm doing something wrong, but it isn't clear what it is.  At the least, it seems that the documentation should be updated to clarify the role of the `Switch` component, as I've come across several SO posts that suggest using `Switch` anyway will work.  Some more thorough documentation about how to use the IonReactRouter would be much appreciated; i do get that ReactRouter is a dependency that you don't want to have to document, but there are mobile specific patterns that some documentation would benefit.

**Ionic info:**

**Steps to Reproduce**
Fork/Clone the repository here https://github.com/tx-tim/stacksintabs
Install dependencies and `npm start` the project

Comment out the `<Switch>` component on line 53 of App.tsx to see the components of both Routes rendered.
Remove the comments and see the components of only the /login route rendered

```
Ionic:

   Ionic CLI       : 6.10.1
   Ionic Framework : @ionic/react 5.2.3

Capacitor:

   Capacitor CLI   : 2.2.1
   @capacitor/core : 2.2.1

Utility:

   cordova-res (update available: 0.15.1) : 0.15.0
   native-run                             : 1.0.0

System:

   NodeJS : v12.13.1
   npm    : 6.14.5
   OS     : macOS Mojave

```

**Comment by tx-tim** [comment] 2020-07-13 21:58
Steps to reproduce added to original bug report

**Comment by liamdebeasi** [comment] 2020-07-20 13:52
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. When defining `IonTab`, you should not define another instance of `IonReactRouter`. Removing that from your `Hio.tsx` file fixes the issue for me.

**Closed by liamdebeasi** 2020-07-20 13:52 UTC
