### ISSUE TITLE
bug: dark mode not working anymore on Android phone

### ISSUE THREAD

**Issue by andreas-aeschlimann** [ionic-team/ionic-framework#23132] opened 2021-04-01 22:48 UTC
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
`window.matchMedia('(prefers-color-scheme: dark)').matches` always returns false on Android device (tested on Samsung Galaxy S21 and Android emulator Pixel 4 XL API 30) while returning true on iOS or web. Our other app with the exact same code works as expected. I assume this is an issue with the newest Ionic or Capacitor (?) version.

**Expected behavior:**
Should return true when dark mode is activated.

**Steps to reproduce:**
I provided a repo. It is a default starter project with only a HomePage.

**Related code:**
See: https://github.com/andreas-aeschlimann/ionic-android-dark-mode-test

The only edited code is here:
https://github.com/andreas-aeschlimann/ionic-android-dark-mode-test/blob/e21bca8bd7bf069de48f70716b22f1d33491e053/src/app/home/home.page.ts#L9-L23

- Check out the repo and run `npm i`
- Run `ionic capacitor run android --livereload --host=0.0.0.0`
- Start the app through Android Studio on your device

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.13.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.6.3
   @angular-devkit/build-angular : 0.1102.6
   @angular-devkit/schematics    : 11.2.6
   @angular/cli                  : 11.2.6
   @ionic/angular-toolkit        : 3.1.1

Capacitor:

   Capacitor CLI   : 2.4.7
   @capacitor/core : 2.4.7

Utility:

   cordova-res (update available: 0.15.3) : 0.15.1
   native-run                             : not installed

System:

   NodeJS : v10.16.0 (/usr/local/bin/node)
   npm    : 7.8.0
   OS     : macOS Big Sur

```

**Comment by liamdebeasi** [comment] 2021-04-02 15:29
Thanks for the issue. What version of the Android WebView are you running? You can find this by inspecting the app on your Android device and logging `window.navigator.userAgent` to the console.

**Comment by andreas-aeschlimann** [comment] 2021-04-02 16:00
Comparing the two projects, I found that I forgot to do the following implementation in MainActivity.java. When I add the following code, it works as expected:

```

  @Override
  public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    // Initializes the Bridge
    this.init(savedInstanceState, new ArrayList<Class<? extends Plugin>>() {{
      // Additional plugins you've installed go here
      // Ex: add(TotallyAwesomePlugin.class);
    }});

    this.setDarkMode();
  }

  @Override
  public void onResume() {
    super.onResume();
    this.setDarkMode();
  }

  /**
   * Set the dark mode according to the system setting.
   */
  private void setDarkMode() {
    int nightModeFlags = getResources().getConfiguration().uiMode & Configuration.UI_MODE_NIGHT_MASK;
    WebSettings webSettings = this.bridge.getWebView().getSettings();

    if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.Q) {
      webSettings.setForceDark(nightModeFlags == Configuration.UI_MODE_NIGHT_YES ? WebSettings.FORCE_DARK_ON : WebSettings.FORCE_DARK_OFF);
    }
  }
``` 

Should this be on the documentation page for dark mode? I didn't find it and there are some discussions about it on the GitHub of Capacitor.

**Comment by liamdebeasi** [comment] 2021-04-02 16:05
Thanks! This looks like a bug in the Android/Chrome WebView. I found a discussion about this on the Capacitor GitHub: https://github.com/ionic-team/capacitor/discussions/1978

I am going to close this since this is not a bug in Ionic Framework, but I will look into reporting this to the Chromium team.

**Closed by liamdebeasi** 2021-04-02 16:05 UTC
Labels: triage
