### ISSUE TITLE
bug: Unsolvable warnings & errors in unit tests.

### ISSUE THREAD

**Issue by aezur** [ionic-team/ionic-framework#21977] opened 2020-08-26 04:47 UTC
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**
1.
When I generate a page, the unit test `.spec` file already has  `IonicModule.forRoot()` in the imports. When the unit test is run, there is a console warning: `WARN: 'Ionic Angular was already initialized. Make sure IonicModule.forRoot() is just called once.'`. When the line is removed, an error appears: `ERROR: ''ionic-header' is not a known element:`. (Any ionic element causes this)

2.
When using any `ionicon`, the unit tests warn of a 404. For example, `:WARN [web-server]: 404: /svg/logo-google.svg`.

**Expected behavior:**
Warnings should not be displayed for default and generated behavior, or the offending behavior should be fixed.

**Steps to reproduce:**
Create an app.
Run `ionic g page test-page`.
Add an `ionicon` to it.
Run `npm test`.

**Other information:**
This commit seems to have added the 'Already initialized' warning: #19393

**Ionic info:**
```
Ionic:

   Ionic CLI                     : 6.11.0 (C:\Users\aezur\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.3.1
   @angular-devkit/build-angular : 0.1000.7
   @angular-devkit/schematics    : 10.0.7
   @angular/cli                  : 10.0.7
   @ionic/angular-toolkit        : 2.3.2

Capacitor:

   Capacitor CLI   : 2.4.0
   @capacitor/core : 2.4.0

Utility:

   cordova-res : 0.15.1
   native-run  : 1.0.0

System:

   NodeJS : v12.2.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.9.0
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment] 2020-08-26 13:51
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/19926.

**Closed by liamdebeasi** 2020-08-26 13:51 UTC
Labels: triage
