### ISSUE TITLE
bug: helper-text and error-text styling inconsistencies

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/ionic-framework#26737] opened 2023-02-05 22:34 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [ ] v6.x
- [X] v7.x
- [ ] Nightly

### Current Behavior

Comparing the new `error-text` and `helper-text` in v7 to the slotted `ion-notes` used in v6 there are some important differences in how they render. These are:

1. In v6, the slotted helper text rendered with a lighter color than with v7
2. In v7, if the input is within an `ion-item` in an `ion-list`, then an extra line is displayed under the error text, and this line does not go away if the error text goes away

### Expected Behavior

1. There should be no extra line rendered under the `error-text` or `helper-text` when the input is used in an `ion-list` based form within an `ion-item`
2. Docs should exist on styling the `error-text` and `helper-text`
3. The `error-text`, `helper-text`, `label`, and `label-placement` should all be fully documented in the `properties` area where they currently are not listed

### Steps to Reproduce

1. Grab the code repo from the URL provided.
2. Click the `Show Error` button
3. Note the extra line under the "New Hotness" - ideally this would not be here
4. Click the `Reset` button
5. Note that there are no longer any messages, but that extra line stays around
6. Reload the page
7. Click `Show Helper`
8. Note the extra line under the "New Hotness" again - ideally this would not be here
9. Note also the lighter text with the old way - this is cool so long as there is a way to style the helper-text. If there is, it is not currently obvious from the docs.

### Code Reproduction URL

https://github.com/kensodemann/test-error-text

### Ionic Info

[0] % ionic info

Ionic:

   Ionic CLI       : 6.20.8 (/Users/ken/.volta/tools/image/packages/@ionic/cli/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 7.0.0-beta.1

Capacitor:

   Capacitor CLI      : 4.6.3
   @capacitor/android : 4.6.3
   @capacitor/core    : 4.6.3
   @capacitor/ios     : 4.6.3

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.1

System:

   NodeJS : v18.12.1 (/Users/ken/.volta/tools/image/node/18.12.1/bin/node)
   npm    : 9.2.0
   OS     : macOS

**Comment by liamdebeasi** [comment] 2023-02-06 14:19
Thanks for testing Ionic 7! There are multiple issues here, so I summarized them below:

> In v6, the slotted helper text rendered with a lighter color than with v7

This is a bug and is fixed in https://github.com/ionic-team/ionic-framework/pull/26739. I updated the helper text color to match the counter text color.

> In v7, if the input is within an ion-item in an ion-list, then an extra line is displayed under the error text, and this line does not go away if the error text goes away

This is also a bug and is fixed in https://github.com/ionic-team/ionic-framework/pull/26739. We now treat empty string values as not having helper/error text.

> There should be no extra line rendered under the error-text or helper-text when the input is used in an ion-list based form within an ion-item

This is the intended behavior since the helper/error text features have been moved onto `ion-input`. You can remove this line using `lines="none"` on `ion-item`: https://ionicframework.com/docs/api/item#item-lines

> Docs should exist on styling the error-text and helper-text

This will be added in https://github.com/ionic-team/ionic-docs/pull/2759.

> The error-text, helper-text, label, and label-placement should all be fully documented in the properties area where they currently are not listed

This is a bug in our documentation website and will be fixed soon. Our automatic scripts only pull in the latest version of Ionic, so we need to update it to handle multiple versions.

**Comment by kensodemann** [comment] 2023-02-06 15:10
> This is the intended behavior since the helper/error text features have been moved onto ion-input. You can remove this line using lines="none" on ion-item: https://ionicframework.com/docs/api/item#item-lines

This is also a little weird, though, as it removes the line under the input such that I no longer have a line (which makes sense, but isn't really what I want):

![Screenshot 2023-02-06 at 8 47 11 AM](https://user-images.githubusercontent.com/1526846/217004287-382c27f7-c3a4-45b4-832e-e6e768ea2513.png)

It _does_ look nicer than having the double lines when I show the error:

![Screenshot 2023-02-06 at 8 47 44 AM](https://user-images.githubusercontent.com/1526846/217004382-400867ef-7831-4fa3-872e-3aa6d8b8f335.png)

But ideally I would have a way to:

1. Show the line like normal when I have an input as part of a list-based form?
2. Display the error text without the extra line?

For example, perhaps leaving `lines="none"` on the `ion-item`, telling the `ion-input` that it _should_ have a line on the bottom, and then not rendering an extra line 🤷‍♂️

I can kinda do that by not putting the `ion-input` in an `ion-list -> ion-item -> ion-input` type structure and then using `fill=solid`:

![Screenshot 2023-02-06 at 9 07 23 AM](https://user-images.githubusercontent.com/1526846/217008310-d586b7d0-1ddb-4608-804c-8ebf8d056ded.png)

That mostly works with the error message (though it is weirdly indented):

![Screenshot 2023-02-06 at 9 07 53 AM](https://user-images.githubusercontent.com/1526846/217008451-4ede7d90-2c88-474d-9e66-abc82c2f9d2b.png)

But I don't seem to be able to find a good way to keep the `ion-list -> ion-item -> ion-input` structure in a form, still have the lines between the inputs, but _not_ have an extra line when displaying helper-text or error-text.

**Comment by liamdebeasi** [comment] 2023-02-07 14:13
I'm not sure I understand this:

> still have the lines between the inputs, but not have an extra line when displaying helper-text or error-text.

You can use `lines="none"` to accomplish this. This provides the same layout as what you are getting now in Ionic v6: https://codepen.io/liamdebeasi/pen/abjxPmb?editors=1010

(There is a height difference here, but that is because we fixed a sizing bug in v7)

> That mostly works with the error message (though it is weirdly indented):

The helper text is supposed to be indented when using `fill="solid"` to align with the MD spec. Additionally, the fill styles define the input containers so you should not use those in a list view with ion-item. See https://ionicframework.com/docs/v7/api/input#filled-inputs

**Comment by kensodemann** [comment] 2023-02-09 15:49
Status update:

> > In v6, the slotted helper text rendered with a lighter color than with v7
> 
> This is a bug and is fixed in https://github.com/ionic-team/ionic-framework/pull/26739. I updated the helper text color to match the counter text color.
> 
> > In v7, if the input is within an ion-item in an ion-list, then an extra line is displayed under the error text, and this line does not go away if the error text goes away
> 
> This is also a bug and is fixed in https://github.com/ionic-team/ionic-framework/pull/26739. We now treat empty string values as not having helper/error text.

I have verified that these bits are fixed.

> > There should be no extra line rendered under the error-text or helper-text when the input is used in an ion-list based form within an ion-item
> 
> This is the intended behavior since the helper/error text features have been moved onto ion-input. You can remove this line using lines="none" on ion-item: https://ionicframework.com/docs/api/item#item-lines

As per our internal calls, the aesthetic is off when the input is in an item as `lines="none"` does not provide clear indication of an input and the double line is not desired when not using `lines="none"`. This still being worked on, so I will leave this issue open.

**Closed** 2023-03-09 16:39 UTC
Labels: package: core, type: bug
