### ISSUE TITLE
ion-select-option not updating on alert interface when data model changes

### ISSUE THREAD

**Issue by mic345** [ionic-team/ionic-framework#26475] opened 2022-12-13 11:24 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

When the data model for `ion-select-options` is changed, the displayed options on already opened modal (alert interface) are not updated. Rather the options are only updated after the modal is closed and opened again.

See the attached video, in which the data used for the options is updated while the "loading..." option is displayed on the modal. The "loading..." options on the modal is not changed until the modal is closed and reopened. 

[Ionic-App (3).webm](https://user-images.githubusercontent.com/36601023/207303607-211dace3-e6e5-42b5-9e2a-33d0022a527d.webm)

### Expected Behavior

The displayed options should be changed when the options' data changes without the user need to close the modal and open it again.

### Steps to Reproduce

1. Download the ionic hello world app.
2. Add an `ion-select` with two `ion-select-option`s, taking their value and labels from an array of options.
3. Add a `timer` that updates the array after 4-5 seconds.
4. Run the app.
5. Open the select.
6. Wait 4-5 seconds.
7. Bug: the displayed options are not updated.

### Ionic Info

$ ionic info

Ionic:

   Ionic CLI                     : 6.18.0 (/home/***/.config/yarn/global/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.2.6
   @angular-devkit/build-angular : 14.2.2
   @angular-devkit/schematics    : 13.3.9
   @angular/cli                  : 14.2.2
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 4.2.0
   @capacitor/android : not installed
   @capacitor/core    : 4.2.0
   @capacitor/ios     : 4.2.0

Utility:

   cordova-res                          : not installed globally
   native-run (update available: 1.7.1) : 1.7.0

System:

   NodeJS : v16.13.0 (/home/***/.nvm/versions/node/v16.13.0/bin/node)
   npm    : 8.1.0
   OS     : Linux 5.10

**Comment by liamdebeasi** [comment] 2022-12-13 14:06
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/19324. Note: This issue references updated the selected value of the `ion-select`, but the underlying issue is the same.

**Closed by liamdebeasi** 2022-12-13 14:06 UTC
Labels: triage

**Comment by mic345** [comment] 2022-12-14 12:21
Hi Liam and thanks for the quick response 👍

I'm not sure those should be marked as duplicates, since https://github.com/ionic-team/ionic-framework/issues/19324 seems to have workarounds and this one doesn't, hence the priority may differ. We tried various workarounds, but once the alert is open it doesn’t change.

**Comment by liamdebeasi** [comment] 2022-12-21 01:13
Hey there,

The linked issue mentions the selected value, but both issues relate back to the same flaw in `ion-select` which is that it is not reactive to asynchronous data. We will likely want to account for both use cases in this fix which is why I merged the threads.

**Comment by mic345** [comment] 2022-12-22 12:29
Well, I guess every organization has its own methodologies for handling bug reports. We'll be waiting for the fix,

Thanks for your help on this one, and have a terrific holiday season 😊
Mic.
