### ISSUE TITLE
bug: Itarated items of list inside ion-menu can't be clickable

### ISSUE THREAD

**Issue by Lexpeartha** [ionic-team/ionic-framework#23169] opened 2021-04-08 20:24 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
Currently looping over items in list does render elements as expected, but no matter how hard I try, it just doesn't make them clickable in any way. Even when `button` attribute is added along with `router-direction`(or even regular `@click`) it just doesn't work.

**Expected behavior:**
I expect this to make `ion-item` clickable, as per described in docs.

**Steps to reproduce:**
I don't think I did anything too special, maybe just having same component hierarchy would replicate issue

**Related code:**

```
<template>
  <ion-menu
    menu-id="menu"
    content-id="main-content"
    type="overlay"
    :swipe-gesture="true"
    side="start"
  >
    <ion-content>
      <ion-card class="profile-card ion-padding-end" color="primary">
        <!-- Some component to display user profile-->
      </ion-card>

      <!-- List 1 -->
      <ion-list>
        <ion-list-header class="ion-padding-top">
          <ion-label class="menu-label" color="secondary">
            Quick access menu
          </ion-label>
        </ion-list-header>

        <ion-item
          button
          detail="false"
          lines="none"
          v-for="(item, $index) in quickMenuItems"
          :key="$index"
        >
          <ion-label color="primary">{{ item.name }}</ion-label>
          <ion-icon slot="start" color="primary" :icon="item.icon"></ion-icon>
        </ion-item>
      </ion-list>
      
      
      <!-- List 2 (the one where it was noticed to cause issue) -->
      <ion-list>
        <ion-list-header class="ion-padding-top">
          <ion-label class="menu-label" color="secondary">
            Navigate app
          </ion-label>
        </ion-list-header>

        <ion-item
          button
          @click="sayHi"
          router-direction="/app/search"
          detail="false"
          lines="none"
          v-for="(item, $index) in menuItems"
          :key="$index"
        >
          <ion-label lines="none" color="primary">{{ item.name }}</ion-label>
          <ion-icon slot="start" color="primary" :icon="item.icon"></ion-icon>
        </ion-item>
      </ion-list>
    </ion-content>
    
    <ion-footer translucent>
      <ion-toolbar>
        <!-- Buttons in this toolbar function, removed for simplicity -->
      </ion-toolbar>
    </ion-footer>
  </ion-menu>
</template>

<script lang="ts">
  import { defineComponent } from "vue";
  import {
    IonMenu,
    IonCard,
    IonCardTitle,
    IonCardSubtitle,
    IonCardHeader,
    IonContent,
    IonFooter,
    IonButtons,
    IonButton,
    IonToolbar,
    IonLabel,
    IonIcon,
    IonList,
    IonListHeader,
    IonItem,
  } from "@ionic/vue";
  import {
    home,
    search,
    information,
    personCircle,
    eye,
    map,
    settings,
    save,
  } from "ionicons/icons";

  export default defineComponent({
    components: {
      IonMenu,
      IonCard,
      IonCardTitle,
      IonCardSubtitle,
      IonCardHeader,
      IonContent,
      IonFooter,
      IonButtons,
      IonButton,
      IonToolbar,
      IonLabel,
      IonIcon,
      IonList,
      IonListHeader,
      IonItem,
    },
    setup() {
      const icons = {
        home,
        search,
        info: information,
        profile: personCircle,
        explore: map,
        settings,
        eye,
        save,
      };

      const quickMenuItems = [
        {
          name: "Recently viewed",
          icon: icons.eye,
        },
        {
          name: "Saved estates",
          icon: icons.save,
        },
      ];

      const menuItems = [
        {
          name: "Home",
          icon: icons.home,
          route: "/app/home",
        },
        {
          name: "Explore",
          icon: icons.explore,
          route: "/app/explore",
        },
        {
          name: "Search",
          icon: icons.search,
          route: "/app/search",
        },
        {
          name: "Profile",
          icon: icons.info,
          route: "/app/profile",
        },
      ];

      const sayHi = () => {
        console.log("You clicked item!");
      };

      return {
        quickMenuItems,
        menuItems,
        icons,
        sayHi,
      };
    },
  });
</script>

<style scoped>
  // Removed for simplicity
</style>

```

**Other information:**
There are no errors anywhere, so I do believe this is issue with Ionic

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.13.1 (/usr/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 5.6.3

Capacitor:

   Capacitor CLI   : 2.4.7
   @capacitor/core : 2.4.7

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v14.16.0 (/usr/bin/node)
   npm    : 7.8.0
   OS     : Linux 5.8
```

**Comment by Lexpeartha** [comment] 2021-04-09 05:06
I've made a repo of the **demo** project: https://github.com/Lexpeartha/ionic-vue-demo

Component I was talking about is in _src/layout/AppMenu.vue_

**Comment by liamdebeasi** [comment] 2021-04-09 14:15
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The `content-id` property on `ion-menu` refers to the content in the primary view, not the `ion-menu`. We use this ID to prevent content behind the menu from being clickable when the menu is open. Because you set `content-id` to be the ID of the `ion-page` that wraps your `ion-menu`, Ionic Framework was making the menu non-clickable since it thought it was the primary view.

To resolve this, add `id="main-content"` to `app-navigation` instead. I updated the docs for `ion-menu` because I think the `content-id` property description is a bit confusing: https://ionicframework.com/docs/api/menu#properties

**Closed by liamdebeasi** 2021-04-09 14:15 UTC
Labels: ionitron: needs reproduction
