### ISSUE TITLE
IonRefresher throws "TypeError: contentEl.componentOnReady is not a function"

### ISSUE THREAD

**Issue by Janaka-Steph** [ionic-team/ionic-framework#25790] opened 2022-08-19 17:42 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

The IonRefresher component does not trigger anything and this error appears in console:
```
ion-refresher.js:526 Uncaught (in promise) TypeError: contentEl.componentOnReady is not a function
    at Refresher.pullMin.connectedCallback (ion-refresher.js:526:1)
    at Refresher.pullMin.connectedCallback (index.js:2310:1)
    at appendChild (react-dom.development.js:10261:1)
    at insertOrAppendPlacementNode (react-dom.development.js:21224:1)
    at insertOrAppendPlacementNode (react-dom.development.js:21230:1)
    at insertOrAppendPlacementNode (react-dom.development.js:21230:1)
    at insertOrAppendPlacementNode (react-dom.development.js:21230:1)
    at insertOrAppendPlacementNode (react-dom.development.js:21230:1)
    at insertOrAppendPlacementNode (react-dom.development.js:21230:1)
    at insertOrAppendPlacementNode (react-dom.development.js:21230:1)
```

### Expected Behavior

It just works

### Steps to Reproduce

 ionic start (I selected the tabs app)
 
 Insert IonRefresher after IonContent
 
 ```
<IonPage>
      <IonHeader>
        <IonToolbar>
          <IonTitle>Tab 1</IonTitle>
        </IonToolbar>
      </IonHeader>
      <IonContent fullscreen>
        <IonRefresher slot="fixed" onIonRefresh={console.log}></IonRefresher>
        <IonHeader collapse="condense">
          <IonToolbar>
            <IonTitle size="large">Tab 1</IonTitle>
          </IonToolbar>
        </IonHeader>
        <ExploreContainer name="Tab 1 page" />
      </IonContent>
    </IonPage>
```

### Ionic Info

▶ ionic info 

Ionic:

   Ionic CLI       : 6.18.2 (/opt/homebrew/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 6.2.3

Capacitor:

   Capacitor CLI      : 3.7.0
   @capacitor/android : 3.7.0
   @capacitor/core    : 3.7.0
   @capacitor/ios     : 3.7.0

Utility:

   cordova-res : 0.15.4
   native-run  : 1.6.0

System:

   NodeJS : v16.17.0 (/usr/local/bin/node)
   npm    : 8.1.4
   OS     : macOS Monterey

**Comment by liamdebeasi** [comment] 2022-08-19 18:05
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/25782.

There is a dev build with a fix available in https://github.com/ionic-team/ionic-framework/issues/25782#issuecomment-1219641757.

**Closed by liamdebeasi** 2022-08-19 18:05 UTC
Labels: triage
