### ISSUE TITLE
bug: ion-input autocapitalize type should be string literal type

### ISSUE THREAD

**Issue by rangzen** [ionic-team/ionic-framework#21463] opened 2020-06-09 12:13 UTC
# Bug Report

**Ionic version:**
[x] **5.0.7**

**Current behavior:**
autocapitalize is a string.

**Expected behavior:**
autocapitalize should be 'on' or 'off'.

I will send a PR.

**Comment by liamdebeasi** [comment] 2022-10-10 20:07
Thanks for the issue, and apologies for the delay. While the experience here is not ideal, the `autocapitalize` property is working as intended.

The underlying problem is with how TypeScript types the `autocapitalize` property: https://github.com/microsoft/TypeScript/blob/9c87ded2b3fc4ba4a9a7656e9be39d5e404e6ab6/lib/lib.dom.d.ts#L6360

As shown in the link, the `autocapitalize` property is of type `string` in TypeScript's codebase. This means that any type narrowing we do is going to cause a TypeScript error. In this case `'off' | 'on' | 'none' | 'sentences' | 'words' | 'characters'` is narrower than the expected `string` type which is why you got the errors in https://github.com/ionic-team/ionic-framework/pull/21464#issuecomment-641353959.

If TypeScript narrows their types, we will be more than happy to reconsider adding this change to Ionic's codebase. I am going to close this, but let me know if you have any questions. Thank you!

**Closed by liamdebeasi** 2022-10-10 20:07 UTC
Labels: package: core, type: bug
