### ISSUE TITLE
bug: Floating labels overlapping numeric input with incorrect data

### ISSUE THREAD

**Issue by omardoma** [ionic-team/ionic-framework#19595] opened 2019-10-08 22:05 UTC
# Bug Report

**Ionic version:**
**4.10.2**

Kindly check issue #10453 which was closed while the bug still persists with the latest version of Ionic, it describes the behavior in details.

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.4.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.10.2
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic 5.4.4, cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.1, (and 14 other plugins)

Utility:

   cordova-res : 0.6.0 (update available: 0.8.0)
   native-run  : 0.2.8 

System:

   Android SDK Tools : 26.1.1 (/Users/omardoma/Library/Android/sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.2
   NodeJS            : v10.16.3 (/usr/local/Cellar/node@10/10.16.3/bin/node)
   npm               : 6.9.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.3 Build version 10G8
```

**Comment by liamdebeasi** [comment] 2019-10-10 13:00
Thanks for the issue. Looks like that issue was for Ionic 3. Is this still an issue in Ionic 4?

**Comment by sean-perkins** [comment] 2022-03-12 02:52
Closing as duplicate of #18037

**Closed by sean-perkins** 2022-03-12 02:52 UTC
Labels: package: core, type: bug
