### ISSUE TITLE
bug: ionic vue, ionic react back button incorrectly shows up when replacing back to root page

### ISSUE THREAD

**Issue by maxschwarzmueller** [ionic-team/ionic-framework#22528] opened 2020-11-19 07:26 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

Bug occurs in **Ionic + Vue** apps.

**Current behavior:**
If `$router.replace(...)` is used to go to back to another page, a back-button is rendered though that button then doesn't do anything.

**Expected behavior:**
Since `replace()` is used, not `push()`, **no back button** should be displayed.

**Steps to reproduce:**
Minimal reproduction repo: [https://github.com/maxschwarzmueller/ionic-vue-back-button-bug](https://github.com/maxschwarzmueller/ionic-vue-back-button-bug)

Run `ionic serve` in this project, click "Go to second page" and then on that page "Go back (replace)". The back button will show up (but not do anything) on the first (Home) page.

**Related code:**

Minimal reproduction repo: [https://github.com/maxschwarzmueller/ionic-vue-back-button-bug](https://github.com/maxschwarzmueller/ionic-vue-back-button-bug)

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.12.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 5.5.0

Capacitor:

   Capacitor CLI   : 2.4.3
   @capacitor/core : 2.4.3

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v14.11.0 (/usr/local/bin/node)
   npm    : 6.14.8
   OS     : macOS Catalina
```

**Comment by liamdebeasi** [comment] 2020-12-11 14:32
Just tried this in Ionic React, and it looks like this is a bug there as well.

**Comment by liamdebeasi** [comment] 2021-01-08 18:12
Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue?

```
npm install @ionic/vue@5.6.0-dev.202101081806.8564071 @ionic/vue-router@5.6.0-dev.202101081806.8564071
```

**Comment by liamdebeasi** [comment] 2021-01-13 15:10
I confirmed the fix on my end and merged the changes in via https://github.com/ionic-team/ionic-framework/pull/22750, but please feel free to give the dev build a test!

**Closed by liamdebeasi** 2021-01-13 15:10 UTC
Labels: package: react, package: vue, type: bug
