### ISSUE TITLE
bug: Ionic 7 and Angular 

### ISSUE THREAD

**Issue by marshall86** [ionic-team/ionic-framework#28038] opened 2023-08-22 08:37 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

According to the Ionic docs, to upgrade Ionic to the latest version, It's currently needed to install rxjs@7.5.0, unfortunately, this rxjs version is not yet compatible with Angular (it supports up to rxjs 7.4.0)

### Expected Behavior

Update the documentation and make Ionic compatible with rxjs 7.4.0

### Steps to Reproduce

You can check the following links:

https://ionicframework.com/docs/updating/7-0
https://angular.io/guide/versions

### Ionic Info

Ionic:

   Ionic CLI                     : 5.4.16 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 6.7.5
   @angular-devkit/build-angular : 16.2.0
   @angular-devkit/schematics    : 15.2.9
   @angular/cli                  : 16.2.0
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI   : 4.6.1
   @capacitor/core : 4.6.1

Cordova:

   Cordova CLI       : 11.1.0
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res                          : 0.15.4
   native-run (update available: 1.7.2) : 1.7.1

System:

   NodeJS : v18.10.0
   npm    : 8.19.2
   OS     : macOS Ventura
   Xcode  : Xcode 14.3.1 Build version 14E300c

**Comment by liamdebeasi** [comment] 2023-08-22 13:10
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The Angular package file states that it support `rxjs@^7.4.0`: https://angular.io/guide/versions#actively-supported-versions

The `^` means that it supports newer minor releases within that same major version. In other words, it supports 7.4.0, 7.5.0, 7.6.0, etc but does not support rxjs 8.0.0. As a result, the 7.5.0+ recommendation in the upgrade guide is correct here.

You can verify this by running `npm ls rxjs` in an Ionic Angular starter application. As of writing, `rxjs@7.8.1` should be installed.

**Closed by liamdebeasi** 2023-08-22 13:10 UTC
Labels: triage

**Comment by liamdebeasi** [comment] 2023-08-22 13:56
Can you provide a reproduction case? I'm not able to reproduce this on my end.
