### ISSUE TITLE
bug: The "Profile" page on this app scrolls fine with Xcode 11.7, but not with Xcode 12.2

### ISSUE THREAD

**Issue by ZakAttakk** [ionic-team/ionic-framework#22717] opened 2020-12-23 20:24 UTC
I'm going to keep this simple.  The "Profile" page of the below Ionic app does not scroll when I run it on Xcode 12.2.  However, the page scrolls fine when run on Xcode 11.7.  Isn't this obviously an Ionic bug?

https://github.com/ZakAttakk/problemApp

You may need to switch back and forth one or two times between the two pages before seeing the scrolling problem.  Thanks for any and all feedback and assistance.

Zach

**Comment by liamdebeasi** [comment] 2020-12-28 15:23
Thanks for the issue. The version of Xcode you deploy with should not have any impact on application scrolling, so the issue is likely somewhere else. I took a look at your application and noticed that the `Profile2` page does not use `IonContent`, which is required for a page to be scrollable.

I am going to close this as this is more of a support issue, but if you have further questions I recommend opening a thread on our forums: http://forum.ionicframework.com/. Thanks!

**Closed by liamdebeasi** 2020-12-28 15:23 UTC
Labels: holiday triage
