### ISSUE TITLE
bug: open ion-menu in tabs template to not work correct

### ISSUE THREAD

**Issue by Dalmi200** [ionic-team/ionic-framework#27473] opened 2023-05-13 17:06 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

in each tab there should be an ion menu.
but as soon as i open the menu in different tabs it doesn't work correctly anymore and suddenly open the menu in another tab.
the same error was reported before in v5 [#24240](https://github.com/ionic-team/ionic-framework/issues/24240) .

### Expected Behavior

all menus works properly in different tabs

### Steps to Reproduce

1. open and close menu on page 1
2. go to tab page2 
3. open and close menu on page 2
4. go back to tab page1
5. menu does not open when clicked, but opens in tab2

### Ionic Info

Ionic:

   Ionic CLI                     : 7.0.1 (AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 7.0.6
   @angular-devkit/build-angular : 16.0.1
   @angular-devkit/schematics    : 16.0.1
   @angular/cli                  : 16.0.1
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.0.3
   @capacitor/android : not installed
   @capacitor/core    : 5.0.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.2

System:

   NodeJS : v18.12.1 (H:\Program Files\nodejs\node.exe)
   npm    : 8.19.2

   OS     : Windows 10

### Additional Information

New project with tab-template and angular. 
use basic usage ion-menu from docs.

with contentId="main-content1", contentId="main-content2" ...
and id="main-content1", id="main-content2" ...

**Comment by liamdebeasi** [comment] 2023-05-15 13:50
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/18974.

**Closed by liamdebeasi** 2023-05-15 13:50 UTC
Labels: triage
