### ISSUE TITLE
Keyboard scrollassist delay when focusing on ion-input

### ISSUE THREAD

**Issue by Boosten** [ionic-team/ionic-framework#22194] opened 2020-09-28 14:01 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

Delay in scrolling the content when a keyboard is sliding up.

**Expected behavior:**

Keyboard should be presented immediately. 

**Steps to reproduce:**
I made a simple ionic + capacitor app repo to demonstrate the issue: 
[Ionic scroll delay demo](https://github.com/Boosten/ionic-scroll-delay-demo)

![ionic scrollAssist](https://media0.giphy.com/media/h8rep5t6gaDFQBEmNZ/giphy.gif?cid=4d1e4f29a9d5245d9f14a44f921257f508e5194fb42d6b6e&rid=giphy.gif)

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.11.9 (/Users/kevinboosten/.nvm/versions/node/v10.16.2/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.3.4
   @angular-devkit/build-angular : 0.1000.8
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Capacitor:

   Capacitor CLI   : 2.4.2
   @capacitor/core : 2.4.2

Utility:

   cordova-res                          : not installed
   native-run (update available: 1.2.0) : 1.0.0

System:

   NodeJS : v10.16.2 (/Users/kevinboosten/.nvm/versions/node/v10.16.2/bin/node)
   npm    : 6.9.0
   OS     : macOS Catalina
```

_Originally posted by @Boosten in https://github.com/ionic-team/ionic-framework/pull/20987#issuecomment-678629365_

**Comment by liamdebeasi** [comment] 2020-09-28 14:04
That doesn't look like the scroll assist, it looks like the entire web view is resizing. The scroll assist will only scroll if it thinks the input is going to be covered by the keyboard. In your GIF, the keyboard never covers the input and I see a quick flash of black above the keyboard. Can you try disabling webview resizing and see if that resolves the issue?

**Comment by Boosten** [comment] 2020-09-28 14:08
@liamdebeasi you're quick! I was still editing my issue because I submitted it too early 😀. I'll check it out.

**Comment by Boosten** [comment] 2020-09-29 07:23
@liamdebeasi I changed the webview resizing behavior to this: 
```
"plugins": {
    "Keyboard": {
      "resize": "none"
    }
  }
```

But that completely disables the scrolling behavior. 

I added a sample repo https://github.com/Boosten/ionic-scroll-delay-demo

**Comment by liamdebeasi** [comment] 2020-09-29 13:55
Thanks! I took a look at your repo. A few things to note:

1. The keyboard scroll assist utility will only scroll to the input if it has enough scrolling real estate to do so. For example, if it needs to scroll 100px down, but the content is not scrollable it will not scroll.

2. When using Capacitor/Cordova, opening the keyboard will typically resize the webview. In that case, the scroll assist needs to wait for the keyboard to open and the webview to resize before it has enough scrolling real estate. This results in the slight delay you are noticing. Some inputs higher up on the screen may have less of a delay because of their smaller scrolling requirement.

3. The flash of black you are seeing is the webview resizing. This happens mostly when showing/hiding the password autofill bar.

4. To avoid the flash of black you _should_ be able to disable webview resizing. There is a known bug where this causes the scroll assist to not work properly: https://github.com/ionic-team/ionic-framework/issues/18532.

I am going to close this issue as the delay you noted is the intended behavior. I can look into a fix for https://github.com/ionic-team/ionic-framework/issues/18532 so that you can use scroll assist with webview resizing turned off.

**Closed by liamdebeasi** 2020-09-29 13:55 UTC
Labels: triage

**Comment by Boosten** [comment] 2020-09-30 09:52
Thanks for your comprehensive answer! It's a pity that this is intended behavior because it makes the first impression with an Ionic + Capacitor app less good for new users, but I now understand why. 
I'll take a look at #18532 to see if this can help me a bit.

**Comment by liamdebeasi** [comment] 2020-09-30 13:32
Great, let me know if you have any suggestions on #18532. Keyboards/Input focusing has always been a challenge in webview-based applications which is why the scroll assist utility exists. Frameworks like Ionic Framework have other solutions but with similar limitations.
