### ISSUE TITLE
bug: Ionic React - IonBackButton navigates to defaultHref route instead of navigating up the history stack

### ISSUE THREAD

**Issue by ar-daniel** [ionic-team/ionic-framework#22544] opened 2020-11-21 08:49 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x** - v 5.5.0

**Current behavior:**

IonBackButton navigates to homepage(or defaultHref) either on first click or after one/two levels, instead of going up the history stack.

**Expected behavior:**

IonBackButton to navigate back up the history stack

**Steps to reproduce:**

Ive used the ion tabs example app and added the IonBackButton to it. Sample code hosted in Stackblitz.
IonBackbutton is placed on all the tabs. By default the sample app starts on the home page.
Please navigate to all the 3 different tabs and then try navigating back using the back button.

**Related code:**
https://stackblitz.com/edit/ionic-react-ts-ionbackbutton-navigation-issue?file=package.json

**Other information:**

I believe this worked in v5.2.x

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.12.2 (/usr/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.5.0

Capacitor:

   Capacitor CLI   : 2.4.3
   @capacitor/core : 2.4.3

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v14.15.1 (/usr/bin/node)
   npm    : 6.14.8
   OS     : Linux 5.4
```

Please help solve the issue. Thanks

**Comment by dmartinjs** [comment] 2020-11-22 14:44
I have also the same bug.

**Comment by liamdebeasi** [comment] 2020-11-23 14:43
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. Each tab is treated as its own individual stack, and clicking the `ion-back-button` is designed to leave the entire tabs context altogether.

If you had the following navigation:

`/home` --> `/tabs/tab1` --> `/tabs/tab1/child`: Clicking the `ion-back-button` in `Child` would take you back to `/tabs/tab1` as you are still within the Tab1 stack.

If you had this instead:

`/home` --> `/tabs/tab1` --> `/tabs/tab2`: Clicking the `ion-back-button` in `Tab2` would take you back to `/home` as switching tabs sets the root page within the tabs navigation context.

This was done to keep the tabs behavior close to how tabs in native iOS and Android applications behave. The previous behavior in v5.2.0 was the incorrect behavior that was fixed in newer versions. Thanks!

**Closed by liamdebeasi** 2020-11-23 14:43 UTC
Labels: triage

**Comment by dmartinjs** [comment] 2020-11-23 15:04
@liamdebeasi outside of the tricks with tabs mentioned above, 
I have this bug on basic implementation of IonBackButton.

Project code : https://github.com/dmartinjs/formula1
Code example: https://github.com/dmartinjs/formula1/blob/master/src/pages/RaceDetails.tsx#L22
to test it: 
```
clone the project
cd formula1
npm i
npm run start
```

![IonBackButtonBug](https://user-images.githubusercontent.com/53537199/99977880-84744c00-2da5-11eb-81c2-72742b78083e.gif)

**Comment by ar-daniel** [comment] 2020-11-26 09:54
ok @liamdebeasi  Thanks for the clarification.

For others who might have necessity for the back button to navigate to previous route, can try using the following custom back button in place of IonBackButton

```
....

  const history = useHistory()

  return (
              ...
              <IonButton onClick={()=> history.goBack() } >
              <IonIcon slot="icon-only" icon={arrowBack} />
            </IonButton>
             .....
  )
...

```
replace icon arrowback to which ever suits the platform
