### ISSUE TITLE
bug: ion-header is moved offscreen in modal

### ISSUE THREAD

**Issue by aparajita** [ionic-team/ionic-framework#22514] opened 2020-11-18 00:35 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

@liamdebeasi This might be one for you.

When you click on an ion-label paired with an ion-input/ion-textarea within an ion-item that is within an ion-modal, the entire modal is shifted up to make space for the keyboard, rather than just the ion-content. This can push the ion-header partially or completely offscreen.

**Expected behavior:**

Only the ion-content should be offset, not the ion-header.

**Steps to reproduce:**

1. Download the project listed below.
1. npm install.
1. npm run ios. Run from Xcode.
1. Click on the "Modal" button.
1. Click on the "Five" label. Wait for the keyboard to appear.
1. Click on the "Six" label. You should see the header move offscreen.

You will see the same behavior on Android.

**Related code:**

Reduction/demo is here: https://github.com/aparajita/ionic-input-problem

This was created via `ionic start inputtest --type=vue blank`. Nothing changed other than taking out the large header, adding the markup, and adding some CSS.

The file `inputs.mov` at 34 seconds shows the behavior that I get in iOS.

**Other information:**

When running on iOS, `window.navigator.appVersion` returns:

```
5.0 (iPhone; CPU iPhone OS 14_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148
```

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.12.1 (/Users/aparajita/.fnm/node-versions/v15.0.1/installation/pnpm-global/4/node_modules/.pnpm/@ionic/cli@6.12.1/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 5.4.4

Capacitor:

   Capacitor CLI   : 2.4.2
   @capacitor/core : 2.4.2

Utility:

   cordova-res : not installed
   native-run  : 1.2.2

System:

   NodeJS : v15.0.1 (/Users/aparajita/.fnm/node-versions/v15.0.1/installation/bin/node)
   npm    : 7.0.3
   OS     : macOS Catalina
```

**Comment by liamdebeasi** [comment] 2020-11-18 15:40
Thanks for the issue. What kind of iPhone are you testing this on? I cannot reproduce this on my iPhone 11.

**Comment by aparajita** [comment] 2020-11-18 19:27
iPhone 7. Try any non-notched phone (real or simulator).

**Comment by liamdebeasi** [comment] 2020-11-18 22:22
Thanks. This issue looks to be caused by your `h-full` class. Is there a reason why you need to explicitly set the height of the modal component to `100%`? Ionic Framework should automatically display it at full size. From what I can tell, doing this interferes with the framework's ability to properly suppress Safari/WKWebView's autoscrolling behavior.

**Comment by aparajita** [comment] 2020-11-18 23:21
Yes, that was the cause. Note that I put the containing div in Modal.vue because at one point Vue was complaining that it couldn't emit an event to a multi-root component (or something like that). As soon as you wrap the ion-header and ion-content in a containing div **without** setting it to full height, when the modal comes up only the top few pixels of the "One" label is visible. When you tap that, the rest of the items appear. Screen recording attached.

Take out all `h-full` classes and keep the containing div in Modal.vue and see if you get the same behavior. If we can't reliably have a containing div in a modal's component, that needs to be documented.

**Comment by liamdebeasi** [comment] 2020-11-18 23:30
I took a closer look and it seems like this is related to the `display: block` on the `div` element, which is something added by the user agent not Ionic Framework.

If you need to add a wrapper div, my recommendation is to add the `.ion-page` class or use the `ion-page` component and target that in your CSS instead. I am going to close this issue, but I will update the docs to clarify this behavior.

**Closed by liamdebeasi** 2020-11-18 23:30 UTC
Labels: triage

**Comment by aparajita** [comment] 2020-11-18 23:46
What isn't clear in the docs is whether there should be `ion-page` or not. The example given does **not** have `ion-page`. It would be good to clarify that.

**Comment by aparajita** [comment] 2020-11-18 23:47
Thanks for taking a look!

**Comment by liamdebeasi** [comment] 2020-11-18 23:54
Yeah I agree it is confusing. The reason there is no `ion-page` in the example is because we automatically add it for you. If you look at the DOM for `ion-modal`, you'll see that your modal component is injected inside of a `div class="ion-page"`. Of course, if you wrap your component in another `div` you will need to re-add `.ion-page` which is something that is not stated (but should be) in the docs.

**Comment by aparajita** [comment] 2020-11-19 00:07
Yes, I know `ion-page` is added for us, I've been digging deeply into the DOM output for the last few days.

But the necessity to manually add it when there is a wrapping div is not optional, it's required — and too easy to forget — so you might as well always show it in examples.

**Comment by aparajita** [comment] 2020-11-19 01:24
Those coming from Vue 2 will out of habit wrap components in an enclosing div, so this is a critical point for the docs.
