### ISSUE TITLE
bug: Time selector does not update in ion-datetime when passing properties

### ISSUE THREAD

**Issue by SpraylnlPray** [ionic-team/ionic-framework#24516] opened 2022-01-05 18:23 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

When having the `ion-datetime` component open, clicking on the preselected time to open the `ion-picker` to select the time and changing the values, the value shown in the background does not reflect the one currently selected in the `ion-picker`.
![Screenshot](https://user-images.githubusercontent.com/33932864/148265107-dab4bacf-c883-41a7-88f7-26561917c044.png)
 
This did not happen with @ionic/angular 6.0.0-rc.3 but does appear after upgrading to @ionic/angular 6.0.1

Furthermore it does seem to work fine, when only using `<ion-datetime></ion-datetime>`, however when using
`          <ion-datetime
            [(ngModel)]="dateValue"
            (ionChange)="formatDate()"
            [showDefaultButtons]="true"
          ></ion-datetime>` (or with any other properties) it won't work anymore.

### Expected Behavior

The value in the background gets updated either instantly or after a short debounce time.

### Steps to Reproduce

1. Clone [the datetime migration example](https://github.com/ionic-team/datetime-migration-samples/)
2. Switch to `next`, run `npm install` and `ionic serve` and try the application (works as expected)
3. Run `npm install @ionic/angular@6` (as described in [upgrading to ionic 6](https://ionicframework.com/docs/intro/upgrading-to-ionic-6#angular). The version should now be 6.0.1
4.  Run `ionic serve` and try the application

### Ionic Info

[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package'

       Require stack:
       - C:\Users\<usr>\AppData\Roaming\npm\node_modules\@ionic\cli\lib\project\index.js
       - C:\Users\<usr>\AppData\Roaming\npm\node_modules\@ionic\cli\lib\index.js
       - C:\Users\<usr>\AppData\Roaming\npm\node_modules\@ionic\cli\index.js
       - C:\Users\<usr>\AppData\Roaming\npm\node_modules\@ionic\cli\bin\ionic
       
[WARN] Error loading @capacitor/android package.json: Error: Cannot find module '@capacitor/android/package'

       Require stack:
       - C:\Users\<usr>\AppData\Roaming\npm\node_modules\@ionic\cli\lib\project\index.js
       - C:\Users\<usr>\AppData\Roaming\npm\node_modules\@ionic\cli\lib\index.js
       - C:\Users\<usr>\AppData\Roaming\npm\node_modules\@ionic\cli\index.js
       - C:\Users\<usr>\AppData\Roaming\npm\node_modules\@ionic\cli\bin\ionic

Ionic:
   Ionic CLI                     : 6.18.1 (C:\Users\<usr>\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.0.1
   @angular-devkit/build-angular : 12.1.4
   @angular-devkit/schematics    : 12.1.4
   @angular/cli                  : 12.1.4
   @ionic/angular-toolkit        : 4.0.0

Capacitor:
   Capacitor CLI      : 3.3.2
   @capacitor/android : not installed
   @capacitor/core    : 3.3.2
   @capacitor/ios     : not installed

Utility:
   cordova-res : not installed globally
   native-run  : 1.5.0

System:
   NodeJS : v14.15.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.8
   OS     : Windows 10

**Comment by sean-perkins** [comment] 2022-01-05 18:25
Hello @SpraylnlPray thanks for reporting this issue.

This is a duplicate of #24451 and has been resolved in #24454.

The fix will be available in the next patch release.

**Closed by sean-perkins** 2022-01-05 18:25 UTC
Labels: holiday triage
