### ISSUE TITLE
feat(overlays): intercept lifecycle events globally

### ISSUE THREAD

**Issue by DwieDima** [ionic-team/ionic-framework#27852] opened 2023-07-25 14:01 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Currently it is not possible to listen to overlay events like `ionModalDidDismiss`, `ionModalDidPresent`, `ionModalWillDismiss`, `ionModalWillPresent` globally.
Instead this is only possible for a specific instance:

```typescript
  public async openModal(): Promise<void> {
    const modal = await this.modalController.create({
      component: MyModalPage,
    });

    await modal.present();
    modal.addEventListener('ionModalDidDismiss', () => {
      // modal dismissed
    });
  }
```

This accounts to all overlay types, like `AlertController`, `PopoverController` ...

### Describe the Use Case

Extending overlays analogously to the `MenuController` would allow us to react globally to overlay events. An example, which is currently difficult to implement, would be tracking overlays using google analytics:

```typescript
    this.modalController.ionModalDidPresent.subscribe((event) => {
      const id = event.detail.id; // modal name
      Analytics.trackEvent({ name: 'MODAL OPEN', params: { id })
    });

    this.modalController.ionModalDidDismiss.subscribe((event) => {
      const id = event.detail.id; // modal name
      const dismissData = event.detail.data; // data which optionally can be provided from modalController.dismiss({ data })
      Analytics.trackEvent({ name: 'MODAL CLOSE', params: { id, dismissData })
    });
```

### Describe Preferred Solution

Overlays should be extended analogously to the `MenuConroller`:

```typescript
    this.modalController.ionModalDidDismiss.subscribe(() => {
      // do something if any modal instance did dismiss
    });

    this.modalController.ionModalDidPresent.subscribe(() => {
      // do something if any modal instance did present
    });

    this.modalController.ionModalWillDismiss.subscribe(() => {
      // do something if any modal instance will dismiss
    });

    this.modalController.ionModalWillPresent.subscribe(() => {
      // do something if any modal instance will present
    });
```

### Describe Alternatives

Maybe this could be manually achieved by using MutationObserver?
But using this approach, i was not able to get the detail data from `dismiss()` directly. Instead i have to get the modal by the `id` from Node and then subscribe to the event listener, which is very complicated to maintain.
Using the described solution would eliminate a lot of code / maintenance (and pain).

```typescript
const observer = new MutationObserver((mutations) => {
    mutations.forEach((mutation) => {
      if (mutation.type === 'childList') {
        mutation.addedNodes.forEach((node) => {
          switch (node.nodeName) {
            case 'ION-MODAL':
              // do something 
              break;
            case 'ION-ALERT':
              // do something
              break;
            // other overlays
          }
        });
        mutation.removedNodes.forEach((node) => {
          switch (node.nodeName) {
            case 'ION-MODAL':
              // do something
              break;
            case 'ION-ALERT':
              // do something
              break;
            // other overlays
          }
        });
      }
    });
  });

observer.observe(document.body, { childList: true, subtree: true });
```

**Comment by sean-perkins** [comment] 2023-07-25 17:08
Hello @DwieDima thanks for this feature request!

Currently you can do this to accomplish the behavior you are requesting:
```ts
export class AppComponent {
  private document = inject(DOCUMENT);

  ngOnInit() {
    this.document.addEventListener('ionModalDidPresent', (ev: CustomEvent) => {
      const { detail, target } = ev;
      console.log('modal did present', {
        target,
        detail,
      });
    });

    this.document.addEventListener('ionModalDidDismiss', (ev: CustomEvent) => {
      const { detail, target } = ev;
      console.log('modal did dismiss', {
        target,
        detail,
      });
    });
  }
}
```

Demo: https://stackblitz.com/edit/angular-ck5skn

> Note: With Stackblitz reloading, making changes can result in multiple event listeners being added to the `document`.

Since Ionic components are web components, the custom events propagate to the root of the DOM. While a standard Angular component output (observables) do not pass component boundaries. 

Does this suffice for your use case? You would adapt the events for the overlays that you are wanting to subscribe to.

**Comment by DwieDima** [comment] 2023-07-26 09:10
Hi @sean-perkins thanks a lot for your solution and the stackblitz!
This resolves our requirement 🎉

**Comment by liamdebeasi** [comment] 2023-07-26 13:52
Glad to hear the issue is resolved! I am going to close this.

**Closed by liamdebeasi** 2023-07-26 13:52 UTC
Labels: triage
