### ISSUE TITLE
stencil warnint 

### ISSUE THREAD

**Issue by SimonovAlex** [ionic-team/ionic-framework#22355] opened 2020-10-20 08:45 UTC
![warning](https://user-images.githubusercontent.com/20050653/96557324-c69c0080-12c2-11eb-9a49-0fbc199ae7f8.png)

this problem occurs because of the extra render in ion-item
to solve this problem, you should move the assignment of state multipleInputs from componentDidLoad to another lifecycle method
for example: connectedCallback or componentWillLoad
please solve it as soon as possible

https://github.com/ionic-team/ionic-framework/blob/1a2e5322fb7ac0dd6bd3d0705b8e32f9d3649bfc/core/src/components/item/item.tsx#L169

**Comment by liamdebeasi** [comment] 2020-10-20 18:42
Thanks for the issue. That message you are getting is just a warning and should not interfere with your app. Is there a particular performance issue that you are running into because of this?

**Comment by SimonovAlex** [comment] 2020-10-21 08:13
thanks for the answer
I cannot say that this problem significantly slows down my applications, but I would like to use the most optimized tools.

**Comment by liamdebeasi** [comment] 2020-10-23 18:06
Thanks for the clarification. So moving this would be a bit tricky because of how component lifecycles work in Stencil. Moving this logic to `componentWillLoad` would mean Ionic Framework would potentially miss certain inputs if they were slotted in `ion-item` as custom components. This would result in a regression, breaking user applications.

If this additional render is actively causing issues in your application please follow up with a code reproduction of the issue and we can re-evaluate. Otherwise, I am going to close this issue for now. Thank you!

**Closed by liamdebeasi** 2020-10-23 18:06 UTC
Labels: triage
