### ISSUE TITLE
bug: v6 datetime does not show if rapidly presented multiple times

### ISSUE THREAD

**Issue by kazlauskis** [ionic-team/ionic-framework#25234] opened 2022-05-04 10:52 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

It is pretty much the same issue as the #24112 which was closed and is locked now. In our case we are placing the datetime component inside an accordion instead of a modal.

https://user-images.githubusercontent.com/7383162/166667783-7fd54f01-4dec-457c-99b2-2248851cf77c.mov

### Expected Behavior

The datetime picker should show a full calendar.

### Steps to Reproduce

Quickly tap on the accordion.

### Ionic Info

Ionic:

   Ionic CLI : 6.6.0
```
    "@ionic/core": "^6.1.3",
    "@ionic/react": "^6.1.3",
```
Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v16.13.2
   npm    : 8.1.2
   OS     : macOS

### Additional Information

It is easier to reproduce this on somewhat slower devices.

**Comment by liamdebeasi** [comment] 2022-05-04 15:31
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/24542. The underlying issue in both of these threads is the same.

**Closed by liamdebeasi** 2022-05-04 15:31 UTC
Labels: triage
