### ISSUE TITLE
bug: input/change event with form components do not trigger

### ISSUE THREAD

**Issue by stanimirsp5** [ionic-team/ionic-framework#27292] opened 2023-04-26 20:39 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When I have`ionInput` event in `<ion-range>`. The `ionInput` event isn't triggered. 

### Expected Behavior

I expect `ionInput ` event to be triggered and to be fired continuously while I'm dragging the knob on `ion-range`.

### Steps to Reproduce

1. Use that line of code `<ion-range @ionInput="onIonInput"></ion-range>`
2. Drag the knob
3. Event won't be triggered and `onIonInput()` won't be called.

### Code Reproduction URL

https://stackblitz.com/edit/angular-ivdjbp?file=src/components/Example.vue

### Ionic Info

Ionic:

   Ionic CLI       : 6.20.8 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 7.0.4

Capacitor:

   Capacitor CLI      : 4.7.3
   @capacitor/android : 4.8.0
   @capacitor/core    : 4.7.3
   @capacitor/ios     : 4.8.0

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v14.17.2 (/usr/local/bin/node)
   npm    : 6.14.13
   OS     : macOS Monterey

**Comment by tgangso** [comment] 2023-05-08 08:10
In ionic 7 in angular, I found that the model does not update when dragging, not sure if intentional or not. At least it broke my uses of ion-range. But the ionInput does indeed trigger when dragging in angular at least. Could be related?

Workaround:
<ion-range [(ngModel)]="rangevalue" (ionInput)="rangevalue= $event?.detail?.value">

**Comment by liamdebeasi** [comment] 2023-07-10 16:12
The root issue is caused by Ionic not having a way of synchronously updating the `v-model` ref. This results in a (hacky) workaround that has limitations. We're trying to get a feature added to Vue that would make this easier to implement (see: https://github.com/vuejs/core/issues/8652) but we are also looking at alternative implementation patterns in the meantime.

**Comment by liamdebeasi** [comment] 2023-09-27 14:06
As a workaround you should be able to listen for `@v-ion-input` instead of `@ionInput` or `@v-ion-change` instead of `@ionChange` temporarily until we can get a fix in place.

**Comment by liamdebeasi** [comment] 2023-10-27 20:07
Hi everyone,

Can you give this dev build a try and let me know if it resolves the issue?

```
npm install @ionic/vue@7.5.3-dev.11698436643.117def41 @ionic/vue-router@7.5.3-dev.11698436643.117def41
```

**Comment by liamdebeasi** [comment] 2023-10-30 14:42
Can do! Thanks for testing.

**Comment by liamdebeasi** [comment] 2023-11-13 20:30
Thanks for the report. This was fixed by updating our `@stencil/vue-output-target` dependency: https://github.com/ionic-team/ionic-framework/pull/28508. The fix will be available in an upcoming release of Ionic.

**Closed by liamdebeasi** 2023-11-13 20:30 UTC
Labels: package: vue, type: bug
