### ISSUE TITLE
bug: component doesn't load in testing

### ISSUE THREAD

**Issue by xnousnow** [ionic-team/ionic-framework#26882] opened 2023-03-01 12:10 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] v7.x
- [ ] Nightly

### Current Behavior

The test(s) for any component that uses an Ionic component fails: It returns an empty element. Please check the 'steps to reproduce' for more information.

### Expected Behavior

The test should work and the `wrapper.html()` shouldn't return the blank element.

### Steps to Reproduce

1. Clone my repository: `Unit-test-dont-work`
2. Run the test: `npm run test:unit`
3. Get the error. I wrote descriptions on the test file.

### Code Reproduction URL

https://github.com/xnousnow/Unit-test-dont-work

### Ionic Info

```ansi
[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package'
       
       Require stack:
       - /usr/local/lib/node_modules/@ionic/cli/lib/project/index.js
       - /usr/local/lib/node_modules/@ionic/cli/lib/index.js
       - /usr/local/lib/node_modules/@ionic/cli/index.js
       - /usr/local/lib/node_modules/@ionic/cli/bin/ionic
[WARN] Error loading @capacitor/android package.json: Error: Cannot find module '@capacitor/android/package'
       
       Require stack:
       - /usr/local/lib/node_modules/@ionic/cli/lib/project/index.js
       - /usr/local/lib/node_modules/@ionic/cli/lib/index.js
       - /usr/local/lib/node_modules/@ionic/cli/index.js
       - /usr/local/lib/node_modules/@ionic/cli/bin/ionic

Ionic:

   Ionic CLI       : 6.20.4 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 6.5.6

Capacitor:

   Capacitor CLI      : 4.7.0
   @capacitor/android : not installed
   @capacitor/core    : 4.7.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.1

System:

   NodeJS : v18.9.1 (/usr/local/bin/node)
   npm    : 9.5.0
   OS     : macOS
```

**Comment by liamdebeasi** [comment] 2023-03-01 13:41
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/22633. The issue here is with overlay components (modal, popover, etc). These components need mocks in order to be tested properly.

**Closed by liamdebeasi** 2023-03-01 13:41 UTC
Labels: triage

**Comment by xnousnow** [comment] 2023-03-02 09:41
For people that got this issue by searching, I committed a simple fix in that repo. the workaround was not putting `ion-modal` in the component:
## ❌ Before
**Any component:**
```html
<YourModalComponent />
```
**YourModalComponent:**
```html
<template>
  <ion-modal>...</ion-modal>
</template>
```
## ✅ After
**Any component**
```html
<ion-modal>
  <YourModalComponent />
</ion-modal>
```
**YourModalComponent:**
```html
<ion-modal>...</ion-modal>
```
