### ISSUE TITLE
bug: chrome 95 not updating opacity on button

### ISSUE THREAD

**Issue by armspativong** [ionic-team/ionic-framework#24140] opened 2021-11-01 11:35 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

After entering a page, when I tries to programtically update value to the variable binded to the [disabled] attribute of ion-button inside ion-buttons (Especially when ion-buttons is in ion-footer) from false to true/true to false, the opacity of the button doesn't change until I focus it once by hovering or clicking on it even though the event from clicking on it works normally.

I also tried added detectChanges() from ChangeDetectorRef of Angular but it's still not working.

And I also tried changing ion-button to normal html button and it works fine as expected.

### Expected Behavior

Updating value to the variable binded to the [disabled] attribute of ion-button inside ion-buttons should trigger opacity of the button.

### Steps to Reproduce

Put ion-button inside ion-buttons in a page with [disabled] atrribute which binding to a varaible and change the value of it programtically after enter the page.

### Code Reproduction URL

https://github.com/armspativong/ionic-issues.git

### Ionic Info

Ionic:

-    Ionic CLI                     : 6.18.0 (/usr/local/lib/node_modules/@ionic/cli)
-    Ionic Framework               : @ionic/angular 5.8.5
-    @angular-devkit/build-angular : 12.2.12
-    @angular-devkit/schematics    : 12.2.12
-    @angular/cli                  : 12.2.12
-    @ionic/angular-toolkit        : 4.0.0

Capacitor:

-    Capacitor CLI      : 3.2.5
-    @capacitor/android : 3.2.5
-    @capacitor/core    : 3.2.5
-    @capacitor/ios     : 3.2.5

Utility:

-    cordova-res : not installed globally
-    native-run  : 1.5.0

System:

-    NodeJS : v14.17.6 (/usr/local/bin/node)
-    npm    : 8.1.1
-    OS     : macOS Monterey

**Comment by liamdebeasi** [comment] 2021-11-01 16:03
Thanks for the issue. Can you please check your code reproduction to ensure it is correct? I cannot reproduce this behavior on my end.

**Comment by armspativong** [comment] 2021-11-01 17:07
Yes, I just checked the same code from attached [repo](https://github.com/armspativong/ionic-issues.git), still happening. 

Please see the video. (Served with Chrome)
https://user-images.githubusercontent.com/6150371/139709452-63e13a77-732a-4fbf-918a-8bf299cf0e48.mp4

*And also happens in Android production build.
https://user-images.githubusercontent.com/6150371/139711035-f07a33a1-1061-4e3d-97ac-51e444723c3a.mp4

*Haven't test in iOS yet

> Thanks for the issue. Can you please check your code reproduction to ensure it is correct? I cannot reproduce this behavior on my end.

**Comment by liamdebeasi** [comment] 2021-11-01 17:12
What version of Chrome are you using? It is working fine for me in Chrome 95:

https://user-images.githubusercontent.com/2721089/139711791-04c062cd-d722-41a8-936c-7f577bfd6bc2.mov

**Comment by armspativong** [comment] 2021-11-01 17:15
Version 95.0.4638.54 (Official Build) (arm64) 😢

**Comment by liamdebeasi** [comment] 2021-11-01 17:20
Does this happen during development builds too, or only during a production build?

**Comment by armspativong** [comment] 2021-11-01 17:25
also happens during development builds and livereload

**Comment by liamdebeasi** [comment] 2021-11-01 17:26
Thanks. Does this happen in non-Chromium browsers? (I.e Safari or Firefox)

**Comment by armspativong** [comment] 2021-11-01 17:31
Oh, it happens only on Chrome. Just trying on Safari and Firefox and it's working fine.

**Comment by liamdebeasi** [comment] 2021-11-01 17:41
Can you see if you have an update available in Chrome? I am running `95.0.4638.69` which is slightly newer than the version you have installed.

**Comment by armspativong** [comment] 2021-11-01 17:45
Yes I just updated to 95.0.4638.69, also restarted my mac but the issue is still happening.

**Comment by armspativong** [comment] 2021-11-01 17:48
Is this because M1 processor??? so confusing. Tomorrow I'll try again with windows at my office.

**Comment by liamdebeasi** [comment] 2021-11-01 17:57
I had another team member test on their M1 Mac and they were unable to reproduce the issue in Chrome. Let me know if you can reproduce it on your Windows machine.

**Comment by armspativong** [comment] 2021-11-01 18:04
Okay, thank you.

**Comment by chrisbinnefeld** [comment] 2021-11-02 08:21
@liamdebeasi @armspativong I can observe the same problem on my windows machine. On Chrome Version 95.0.4638.69.

![cb015DRrWc](https://user-images.githubusercontent.com/36038291/139809779-f6cba2d0-d869-4cd7-90d2-71432996b1c6.gif)

The button on the top left side should be enabled and disabled multiple times in the gif. As you can see, the styles are getting removed and added correctly but the button is not updated. 

On Edge (Version 95.0.1020.40) everything works as expected.

**Comment by armspativong** [comment] 2021-11-02 10:32
I'm just trying on Windows and getting same issue as on MacOS
https://user-images.githubusercontent.com/6150371/139830041-440bceb3-aabc-4188-af08-1d68d68a988a.mp4

This is happening on ionic serve and also in production build on both web and Android

Ionic:

-    Ionic CLI                     : 6.18.0 (C:\Users\armes\AppData\Roaming\npm\node_modules\@ionic\cli)
-    Ionic Framework               : @ionic/angular 5.8.5
-    @angular-devkit/build-angular : 12.2.12
-    @angular-devkit/schematics    : 12.2.12
-    @angular/cli                  : 12.2.12
-    @ionic/angular-toolkit        : 4.0.0

Capacitor:

-    Capacitor CLI      : 3.2.5
-    @capacitor/android : not installed
-    @capacitor/core    : 3.2.5
-    @capacitor/ios     : not installed

Utility:

-    cordova-res : not installed globally
-    native-run  : 1.5.0

System:

-    NodeJS : v16.13.0 (C:\Program Files\nodejs\node.exe)
-    npm    : 8.1.2
-    OS     : Windows 10

**Comment by almothafar** [comment] 2021-11-02 13:38
I confirm this issue happening in Chrome (Version 95.0.4638.69 (Official Build) (64-bit)) and works fine in Safari and Firefox 94.0 (64-bit) 
This issue happened recently after updating chrome.

**Comment by liamdebeasi** [comment] 2021-11-02 13:46
Thanks everyone! Seems to be a legit issue. I am going to dig into this a bit more today.

**Comment by liamdebeasi** [comment] 2021-11-02 21:20
I can reproduce the issue now. Definitely seems to be a Chrome-specific bug. I am going to spend more time and see if I can reproduce this outside of Ionic.

**Comment by liamdebeasi** [comment] 2021-11-03 14:17
Hi everyone,

I can reproduce this outside of Ionic and have verified this as a bug in Chrome. I tested the upcoming Chrome 96 release and can confirm that the issue is resolved there.

I will close this issue out once Chrome 96 has been released. Thanks!

**Comment by herobarua** [comment] 2021-11-14 09:51
I am use code that way, it seems issue resolved my end
`ion-button {
      &.button-clear {
        --opacity: 1.0;

        &:hover,
        &.ion-activated {
          --opacity: 0.7;
        }
        &.button-disabled{
          --opacity: 0.7;
        }
      }
}`

**Comment by liamdebeasi** [comment] 2021-11-16 15:34
Hi everyone,

Chrome 96 has been released which has a fix for this issue. I am going to close this issue out. Thanks for reporting this!

**Closed by liamdebeasi** 2021-11-16 15:34 UTC
Labels: type: bug, bug: external
