### ISSUE TITLE
Datetime picker's default value ignores min datetime

### ISSUE THREAD

**Issue by manu2504** [ionic-team/ionic-framework#25291] opened 2022-05-16 16:33 UTC
**Ionic version:**
[] **4.x**
[] **5.x**
[x] **6.x**

**I'm submitting a ...** 
[x] bug report
[ ] feature request

**Current behavior:**
The datetime picker's default time is now, even if the min attribute is in the future.

It is still possible to set the default value manually, by setting `[value] = min_time`, but one would expect the default value cannot be lower than the min time.

**Expected behavior:**
The default time should not be lower than the min datetime. It should correspond to the min datetime if the min datetime is in the future.

**Steps to reproduce:**
Create a ion-datetime component. Set its min attribute in the future (example '2022-05-16T18:20:00Z' if testing on 2022-05-16T18:05:00Z). Observe the datetime picker (currently selected on date = today and time = now):
<img width="573" alt="Screenshot 2022-05-16 at 18 05 29" src="https://user-images.githubusercontent.com/25584381/168636757-6a1cba87-0783-4839-bc31-022b48e61220.png">

**Related code:**

```
<ion-datetime hour-cycle="h23" [min]="2022-05-16T18:20:00Z"></ion-datetime>
```

**Ionic info:** 

```
Ionic:

   Ionic CLI                     : 6.18.1 (/Users/macbookpro/.nvm/versions/node/v12.22.1/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.9
   @angular-devkit/build-angular : 13.2.5
   @angular-devkit/schematics    : 13.2.5
   @angular/cli                  : 13.2.5
   @ionic/angular-toolkit        : 6.0.0

Capacitor:

   Capacitor CLI      : not installed
   @capacitor/android : not installed
   @capacitor/core    : not installed
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v12.22.1 (/Users/macbookpro/.nvm/versions/node/v12.22.1/bin/node)
   npm    : 6.14.16
   OS     : macOS Big Sur
```

**Comment by liamdebeasi** [comment] 2022-05-16 19:06
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/24881.

**Closed by liamdebeasi** 2022-05-16 19:06 UTC
Labels: triage
