### ISSUE TITLE
bug: `ion-item` slot="error" not visible in Safari

### ISSUE THREAD

**Issue by luongtu996** [ionic-team/ionic-framework#24575] opened 2022-01-14 08:47 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

The new slot "error" does not work on my ipad 8, and iphone 7.
i found 
```
::slotted([slot=error])
```
allways display:none;

<img width="286" alt="Screenshot 2022-01-14 at 15 41 54" src="https://user-images.githubusercontent.com/26574116/149484684-49ef888e-1174-4459-a65b-a6fe993de2f1.png">

### Expected Behavior

Items with the error slot should show up as expected.

### Steps to Reproduce

Just try on real device
```
 <ion-item class="ion-invalid">
          <ion-label position="stacked">Name</ion-label>
          <ion-input></ion-input>
          <ion-note slot="error">Test</ion-note>
 </ion-item>
```

### Ionic Info

```
Ionic:

   Ionic CLI                     : 6.18.1 (.../.nvm/versions/node/v14.17.1/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.2
   @angular-devkit/build-angular : 13.1.2
   @angular-devkit/schematics    : 12.2.14
   @angular/cli                  : 13.1.2
   @ionic/angular-toolkit        : 5.0.3

Capacitor:

   Capacitor CLI      : 3.3.4
   @capacitor/android : 3.3.4
   @capacitor/core    : 3.3.4
   @capacitor/ios     : 3.3.4

Utility:

   cordova-res (update available: 0.15.4) : 0.15.3
   native-run                             : 1.5.0

System:

   NodeJS : v14.17.1 (.../.nvm/versions/node/v14.17.1/bin/node)
   npm    : 7.19.0
   OS     : macOS Monterey
```

**Comment by vildhjarta8** [comment] 2022-01-14 11:25
+1. Not working for me.

https://github.com/ionic-team/ionic-framework/issues/24445#issuecomment-1013035382

**Comment by luongtu996** [comment] 2022-01-14 11:49
i have to force css for item

```
.html
<ion-item>
  <ion-label position="stacked">Email</ion-label>
   <ion-input></ion-input>
   <div slot="error">
     show error here 
   </div>
</ion-item>


global.scss
ion-item {
  &.item-interactive.ion-invalid{
    div[slot="error"] {
      display: block !important;
    }
  }
}

```

**Comment by amandaesmith3** [comment] 2022-01-14 14:59
Thanks for the issue. I'm going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/24445. I know there was discussion about the `ion-invalid` class being the missing piece, and your example here has that already, but this seems like the best way to keep discussion tidy. Feel free to post additional details on your setup over in that thread. cc @sean-perkins

**Comment by sean-perkins** [comment] 2022-01-14 17:15
Ok looks like this is a slightly different issue, but relates to the error slot not showing in Safari (due to some style ordering). I'm going to re-open this issue and update the title to reflect the bug. 

I'll open a PR shortly that addresses this issue.

**Closed** 2022-01-14 17:36 UTC
Labels: package: core, type: bug
