### ISSUE TITLE
bug: ion nav component

### ISSUE THREAD

**Issue by EslamNemr** [ionic-team/ionic-framework#23681] opened 2021-07-24 03:27 UTC
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

ion nav component with ionic/vue 
when trying to pop to another view all forward views component in the stack didn't unmounted or removed from the dom which cause memory leak.
even using remove function just remove the view and didn't unmount or destroy the component and also didn't remove dom element

### Expected Behavior

its should just keep the pervious element in the stack and remove or unmount all the forward.

### Steps to Reproduce

1- add nav component and pop to any view
2- check dom elements still there
3- check vnode subtree or vue dev tool still unmounted.

**Comment by liamdebeasi** [comment] 2021-07-26 13:16
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/21831.

**Closed by liamdebeasi** 2021-07-26 13:16 UTC
Labels: triage

**Comment by EslamNemr** [comment] 2021-08-02 12:27
i would like to leave my solution here for any one use ionic/vue nav component
in file 
[https://github.com/ionic-team/ionic-framework/blob/main/packages/vue/src/components/IonNav.ts](
)

i return views which is the array of created component vnode as props then i managed to delete it from my component
it seems the bug in framework delegate and core component remove view function.

  setup() {
    const views = shallowRef([]);

    /**
     * Allows us to create the component
     * within the Vue application context.
     */
    const addView = (component: VNode) => views.value = [...views.value, component];
    const removeView = (component: VNode) => views.value = views.value.filter(cmp => cmp !== component);

    const delegate = VueDelegate(addView, removeView);
    return () => {
      return h(
        'ion-nav',
        { delegate, views },
        views.value
      )
    }
  }
});
