### ISSUE TITLE
bug: ion-datetime's pickerOptions doesn't change the columns display.

### ISSUE THREAD

**Issue by pciseran** [ionic-team/ionic-framework#23178] opened 2021-04-11 08:55 UTC
# Bug Report

**Ionic version:**
6.13.1

**Current behavior:**

ion-datetime's pickerOptions doesn't change the columns display.
**Expected behavior:**
Columns should have changed according to the ones set in pickerOptions.columns

**Steps to reproduce:**
```
@ViewChild("IonDatetime") ionDateTime: IonDatetime
pickerColumns: PickerColumn[]
pickerOptions: DatetimeOptions  //also tried with pickerOptions type

  constructor() {
      this.pickerColumns=[{
      name: 'hours',
     selectedIndex : 0,
      options: [
        {
          text: '1',
          value: '01',
          selected:true,
          
        },
        {
          text: '2',
          value: '02'
        }
      ]
    },{
      name: 'min',
      selectedIndex:0,
      options: [
        {
          text: '1',
          selected:true,
          value: '01'
        },
        {
          text: '2',
          value: '02'
        }
      ]
    }]
this.pickerOptions= {
  id:"options",
  buttons: [{
    text: 'Cancel',
    role:'cancel',
    handler: () => console.log('cancel')
  }, {
    text: 'Ok',
    handler: (data) => {
      console.log('Data', data);
    }
  }],
  columns :this.pickerColumns;
}
  }

  ionViewDidEnter() {    
this.ionDateTime.pickerOptions=this.pickerOptions;
}
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.13.1 (C:\Users\pcise\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.6.0
   @angular-devkit/build-angular : 0.1101.4
   @angular-devkit/schematics    : 11.1.4
   @angular/cli                  : 11.1.4
   @ionic/angular-toolkit        : 3.1.0

Capacitor:

   Capacitor CLI   : 2.4.7
   @capacitor/core : 2.4.7

Utility:

   cordova-res (update available: 0.15.3) : 0.11.0
   native-run (update available: 1.3.0)   : 1.0.0

System:

   NodeJS : v14.15.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.4
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment] 2021-04-12 13:19
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/17664 (same underlying issue, though the specific behavior on this thread is slightly different)

**Closed by liamdebeasi** 2021-04-12 13:19 UTC
Labels: triage
