### ISSUE TITLE
bug: Ionic framework blocks any initial transitions

### ISSUE THREAD

**Issue by roman-rr** [ionic-team/ionic-framework#27984] opened 2023-08-14 03:27 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v4.x, v5.x, v6.x, v7.x, Nightly

### Current Behavior

Ionic frameworks block any transitions on elements at the application initialization. 
Therefore, `transitionend` callback not available and animation not visible. 

### Expected Behavior

Ionic initialization do not interrupt transitions for other elements. 

### Steps to Reproduce

1. Run demo (with Ionic bundle) 10 times and see results https://jsfiddle.net/romantonoff/9wxLudpo/
2. Run demo (without Ionic bundle) 10 times and see results https://jsfiddle.net/romantonoff/nhd7orj3/

### Code Reproduction URL

https://jsfiddle.net/romantonoff/9wxLudpo/

### Ionic Info

```
Ionic:
   Ionic CLI                     : 6.20.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : not installed
   @angular-devkit/build-angular : 16.2.0
   @angular-devkit/schematics    : 16.2.0
   @angular/cli                  : 16.2.0
   @ionic/angular-toolkit        : 9.0.0

Cordova:

   Cordova CLI       : 11.0.0
   Cordova Platforms : ios 6.3.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 3 other plugins)

Utility:

   cordova-res (update available: 0.15.4) : 0.14.0
   native-run (update available: 1.7.2)   : 1.4.0

System:

   Android SDK Tools : 26.1.1 (/Users/romanrr/Library/Android/sdk)
   ios-deploy        : 1.10.0
   ios-sim           : 8.0.2
   NodeJS            : v18.16.0 (/usr/local/bin/node)
   npm               : 9.5.1
   OS                : macOS
   Xcode             : Xcode 15.0 Build version 15A5161b
```

### Additional Information

Example code (transition will be blocked):
```js
let circle = document.querySelector('.circle');

window.onload = async function () {
  circle.style.transition = 'all 300ms ease';
  circle.style.transform = 'translateX(300px)';
}
```

Adding promise `await document.querySelector('ion-app').componentOnReady();` solve **80%** of all initializations:
```js
let circle = document.querySelector('.circle');

window.onload = async function () {
  await document.querySelector('ion-app').componentOnReady(); 
  circle.style.transition = 'all 300ms ease';
  circle.style.transform = 'translateX(300px)';
}
```

Adding promise and `withrequestAnimationFrame` will resolve **99%** of this issue:
```js
let circle = document.querySelector('.circle');

window.onload = async function () {
  await document.querySelector('ion-app').componentOnReady(); 
  await new Promise(resolve => requestAnimationFrame(resolve));
  circle.style.transition = 'all 300ms ease';
  circle.style.transform = 'translateX(300px)';
}
```

**Comment by liamdebeasi** [comment] 2023-08-14 13:34
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. As per the [`transitionend` spec](https://developer.mozilla.org/en-US/docs/Web/API/Element/transitionend_event), this is the correct behavior: 

> The transitionend event is fired when a [CSS transition](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_transitions/Using_CSS_transitions) has completed. In the case where a transition is removed before completion, such as if the [transition-property](https://developer.mozilla.org/en-US/docs/Web/CSS/transition-property) is removed or [display](https://developer.mozilla.org/en-US/docs/Web/CSS/display) is set to none, then the event will not be generated.

Ionic's lazy loaded components are hidden using `display: none` until they are hydrated. The provided example runs a transition on an element while it is still hidden which is why `transitionend` does not fire. `componentOnReady` resolves once the component instance is loaded, not necessarily once it is hydrated which is why that solution does not work all the time.

-----

Non-lazy loaded builds of Ionic such as those imported from `@ionic/core/components` do not have this same restriction as components do not need to be hydrated. You will likely still need to use something like a `requestAnimationFrame` since styles are loaded async. Alternatively, you could add a MutationObserver to the lazy loaded component you want to animate and listen for the `hydrated` class to be added.

**Closed by liamdebeasi** 2023-08-14 13:34 UTC
Labels: triage
