### ISSUE TITLE
bug: Side Navigation (ion-split-pane) Breaks Navigation

### ISSUE THREAD

**Issue by elvisgraho** [ionic-team/ionic-framework#23391] opened 2021-06-01 10:00 UTC
# Bug Report

**Ionic version:**
[x] **5.6.8**

**Current behavior:**
When side navigation is enabled, there is a bug that causes the page transitions to get stuck.

**Steps to reproduce:**
https://github.com/elvisgraho/ionic-bug/tree/main

You would need to generate iOS project. 

Spam the buttons that trigger navigation (endless loop), and you eventually will get stuck. Do not do swipe gestures, i just spam the button with a finger.

When side navigation is disabled (boolean in app.component.ts), you cannot possibly reproduce the bug. But when the side navigation is enabled, you can reproduce the bug by spamming buttons.

**Ionic info:**
(same issues with capacitor 2)
```
Ionic:

   Ionic CLI                     : 5.4.16
   Ionic Framework               : @ionic/angular 5.6.8
   @angular-devkit/build-angular : 12.0.2
   @angular-devkit/schematics    : 11.2.6
   @angular/cli                  : 12.0.2
   @ionic/angular-toolkit        : 3.1.1

Capacitor:

   Capacitor CLI   : 3.0.0
   @capacitor/core : 3.0.0

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : 0.15.3
   native-run  : 1.3.0

System:

   Android SDK Tools : 26.1.1 (/Users/graholskise/Library/Android/sdk)
   NodeJS            : v12.22.1 (/Users/graholskise/.nvm/versions/node/v12.22.1/bin/node)
   npm               : 6.14.12
   OS                : macOS Big Sur
   Xcode             : Xcode 12.5 Build version 12E262

```

**Comment by liamdebeasi** [comment] 2021-06-01 13:42
Thanks for the issue. The problem here seems to be related to the mixing of `ion-router-outlet` and `router-outlet`. This issue does not reproduce when using only `ion-router-outlet`.

When using Ionic Angular we recommend using `ion-router-outlet` instead of the regular `router-outlet`. That being said I understand there are some issues with `ion-router-outlet` when using nested outlets. You can work around this issue by either using `ion-router-outlet` for all outlets or by avoiding nested outlets altogether.

If you want to avoid nested outlets, your routing config would look something like this:

```ts
const routes: Routes = [
  {
    path: 'home',
    component: HomePage,
    children: [
      {
        path: '',
        component: ControlPanelComponent,
      },
    ],
  },

  {
    path: 'app-contacts',
    component: HomePage,
    children: [
      {
        path: '',
        component: ContactsControlPanelComponent,
      },
    ],
  },
  {
    path: 'app-contacts/company-list',
    component: CompanyListComponent,
  }
];
```
We are already tracking nested outlet issues in https://github.com/ionic-team/ionic-framework/issues/18197 so I am going to close this in favor of that issue.

**Closed by liamdebeasi** 2021-06-01 13:42 UTC
Labels: triage
