### ISSUE TITLE
bug: IonInput failed to push up by keyboard and show strange whitespace above keyboard while manually scrolled to IonInput 

### ISSUE THREAD

**Issue by lclrobert2020** [ionic-team/ionic-framework#23179] opened 2021-04-11 14:35 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
This bug only appears on website made by ionic react when browsed by iOS mobile Safari only (tested on Iphone 11 and Iphone 6+). I am not sure if app made by ionic react will trigger this bug.
When a IonInput is a the bottom or nearly the bottom of the page. Safari failed to scroll to the IonInput and the pop up keyboard will block the IonInput.
When manually scrolled to the bottom IonInput, a large empty white space(if you use dark mode in iOS it will become empty dark space) will be added above the keyboard.

**Expected behavior:**
The browser should be scrolled to the Ioninput so that the pop up keyboard won't block the input.
There should not be white empty space added above the keyboard.
Android Chrome works well and only mobile iOS will show this problem.

**Steps to reproduce:**

Init a blank project first by 

ionic start myApp blank --type=react
cd myApp

Put the related code to the Home.tsx in src/pages/Home.tsx

Build the app and serve it
yarn build 
serve -s build

Visit the website by using iOS Safari

**Related code:**
See snippets

```
import React, { useState } from 'react';
import { IonContent, IonHeader, IonPage, IonTitle, IonToolbar, IonInput, IonItem, IonLabel, IonList, IonItemDivider } from '@ionic/react';
import ExploreContainer from '../components/ExploreContainer';
import './Home.css';

const Home: React.FC = () => {
  const [text, setText] = useState<string>();
  const [number, setNumber] = useState<number>();

  return (
    <IonPage>
      <IonHeader>
        <IonToolbar>
          <IonTitle>IonInput Examples</IonTitle>
        </IonToolbar>
      </IonHeader>
      <IonContent color="primary" fullscreen>
        <h1>123i213j</h1>
        <h1>123i213j</h1>
        <h1>123i213j</h1>
        <h1>123i213j</h1>
        <h1>123i213j</h1>
        <h1>123i213j</h1>
        <h1>123i213j</h1>
        <h1>123i213j</h1>
        <h1>123i213j</h1>
        <h1>123i213j</h1>
        <h1>123i213j</h1>
        <h1>123i213j</h1>
        <h1>123i213j</h1>
        <h1>123i213j</h1>
        <h1>123i213j</h1>
        <h1>123i213j</h1>
        <h1>123i213j</h1>
        <h1>123i213j</h1>
        <h1>123i213j</h1><h1>123i213j</h1>
        <IonList className="ion-no-margin">
          <IonItemDivider>Default Input with Placeholder</IonItemDivider>
          <IonItem >
            <IonInput value={text} placeholder="Enter Input" onIonChange={e => setText(e.detail.value!)}></IonInput>
          </IonItem>
        </IonList>
      </IonContent>
    </IonPage>
  );
};

export default Home;
```

**Other information:**

See this video 
https://www.youtube.com/watch?v=kIau_Ilm5iA&ab_channel=Non
**Ionic info:**

```
insert the output from ionic info here

Ionic:

   Ionic CLI       : 6.13.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.6.4

Capacitor:

   Capacitor CLI   : 2.4.7
   @capacitor/core : 2.4.7

Utility:

   cordova-res : 0.15.3
   native-run  : not installed

System:

   NodeJS : v15.10.0 (/usr/local/Cellar/node/15.10.0/bin/node)
   npm    : 7.5.3
   OS     : macOS Big Sur
```

**Comment by liamdebeasi** [comment] 2021-04-12 13:31
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/18532 (same underlying issue, though in that thread the issue manifests in a slightly different way).

**Closed by liamdebeasi** 2021-04-12 13:31 UTC
Labels: triage
