### ISSUE TITLE
feat: Swipe back animation that follows touch

### ISSUE THREAD

**Issue by Cyral** [ionic-team/ionic-framework#23028] opened 2021-03-08 13:51 UTC
# Feature Request

**Ionic version:**

[x] **5.x**

**Describe the Feature Request**

The swipe back animation should follow the finger while swiping back. Currently the animation is either all or nothing, once it detects you want to go back it starts the animation and it cannot be stopped.

**Describe Preferred Solution**
 Every non-ionic app I've seen will make the swipe back follow your finger as you slide it, so that you can "unslide" it and remain on the page. It would feel much more native if this was implemented.

**Describe Alternatives**

N/A

**Related Code**

**Additional Context**

**Comment by liamdebeasi** [comment] 2021-03-08 14:16
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/22342.

**Closed by liamdebeasi** 2021-03-08 14:16 UTC
Labels: triage
