### ISSUE TITLE
bug: Changes to ion-input and ion-range not reflecting

### ISSUE THREAD

**Issue by StevieApp** [ionic-team/ionic-framework#24540] opened 2022-01-09 13:01 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

I have been trying to display a rating after selecting in an ion-range but it's not updating the value in the modal. It's updating in the parent but not in the modal.
Here's what I'm working with.

```
<ion-modal trigger="open-rate">
                <ng-template>
                    <ion-content>
                        <ion-card mode="ios">
                            <ion-card-header style="text-align: center;">
                                <ion-card-title>{{'Rate' | translate}} {{menuname | translate}}</ion-card-title>
                                <ion-card-title color="secondary">
                                    {{rating.number}}
                                </ion-card-title>
                            </ion-card-header>
                            <ion-item>
                                <ion-range min="0" max="5" [(ngModel)]="rating.number" [pin]="true" [snaps]="true" [ticks]="true">
                                </ion-range>
                            </ion-item>
                        </ion-card>
                    </ion-content>
                </ng-template>
```

### Expected Behavior

I need to be a able to preview the value after making a change to the ion range. I have tried to call change detector ref to detect changes but it's not working. When the element is outside the ion-modal, the value shows. But inside the modal it does not update.

### Steps to Reproduce

Just use the default modal from ionic page then add the ion range to it. Then try to display the changes within the modal and outside to see the difference. Use web to see the changes reflecting when the value is being displayed outside the modal since it doesn't cover the whole screen.

**Comment by sean-perkins** [comment] 2022-01-09 23:26
Duplicate of #24502 has been resolved in #24521.

The fixes will be available in the upcoming patch release (6.0.2).

Thanks!

**Closed by sean-perkins** 2022-01-09 23:26 UTC
Labels: triage
