### ISSUE TITLE
bug: fixed position on elements does not work, because of main.inner-scroll

### ISSUE THREAD

**Issue by BerkeAras** [ionic-team/ionic-framework#22498] opened 2020-11-14 15:03 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
In version 5.4.4 child elements of ion-content cannot be fixed using position: fixed. Elements are scrolling up when ion-content is scrolled down.

**Expected behavior:**
Elements with position: fixed should be fixed.

**Steps to reproduce:**
See codepen example.

**Related code:**

Make preview window smaller to make ion-content scrollable:

Issue on ionic 5.4.4: [https://codepen.io/BerkeAras/pen/oNLmqPP](https://codepen.io/BerkeAras/pen/oNLmqPP)
Issue on ionic 5.4.1: [https://codepen.io/BerkeAras/pen/XWKOExe](https://codepen.io/BerkeAras/pen/XWKOExe)

**Comment by armespavong** [comment] 2020-11-15 14:24
Agreed

**Comment by liamdebeasi** [comment] 2020-11-16 14:26
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/22473.

**Closed by liamdebeasi** 2020-11-16 14:26 UTC
Labels: triage
