### ISSUE TITLE
bug: Cannot prevent accordion from toggling

### ISSUE THREAD

**Issue by acontreras89** [ionic-team/ionic-framework#28635] opened 2023-12-05 10:33 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

In the following setup:

```jsx
const handleClick = ev => {
  ev.stopPropagation()
  ev.preventDefault()
}

// ...

<IonAccordionGroup>
  <IonAccordion>
    <IonIcon icon={addCircleOutline} onClick={handleClick} />
  </IonAccordion>
</IonAccordionGroup>
```

Clicking on the icon does not prevent the accordion from expanding/collapsing.

### Expected Behavior

Calling `ev.stopPropagation()` for a click event captured inside an accordion header **should prevent the accordion** from expanding/collapsing.

### Steps to Reproduce

1. Create a minimal layout as per the example above
2. Click on the icon
3. Observe how the accordion is expanded/collapsed

### Code Reproduction URL

Example in [CodeSandbox](https://codesandbox.io/p/sandbox/strange-flower-wg9ms2)

### Ionic Info

I am using `@ionic/react` in a project based on [`create-react-app`](https://create-react-app.dev/), so there is no info to attach here.

**Comment by liamdebeasi** [comment] 2023-12-05 15:36
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The reason for this behavior is React creates synthetic events: https://react.dev/reference/react-dom/components/common#react-event-object. While they implement many of the same features as native events, they are a separate feature.

Your code listens for the synthetic click event. Calling `stopPropagation` on this synthetic event only stops the synthetic event propagation through the React tree. `IonAccordion` listens for the native click event (not the synthetic click event), so your `stopPropagation()` will never prevent that native event from propagating.

To get the desired behavior, the native `click` event listener needs to be listened for instead. Here's a demo in React: https://codesandbox.io/p/sandbox/nice-hill-9fqsfw?file=%2Fsrc%2FApp.tsx%3A38%2C8

**Closed by liamdebeasi** 2023-12-05 15:36 UTC
Labels: triage

**Comment by acontreras89** [comment] 2023-12-05 22:45
Well, I wasn't thinking of this as a bug in Ionic Framework, but rather **a bug in its React integration** (i.e. the `@ionic/react` package.) When I see some sort of _oficial React adapters_ for other libraries or frameworks, I expect them to actually integrate with React, not just be wrapped with it. (although, to be completely honest, more often than not this expectation isn't met.)

And don't take me wrong, I understand that React is opinionated about events. I've always wondered why they would use synthetic events at all, and I can only imagine it must be hard to work around this abstraction in most situations... (it is sometimes hard in userland too.)

But bear with me for a little longer and we might get to some place in between.

---

> To get the desired behavior, the native click event listener needs to be listened for instead

This doesn't quite do the trick. It does prevent the accordion's state from toggling but it also prevents the React component's click handler from firing. You would have to perform whatever action you may need from within the native listener too. But then again, and coming back to my previous point, we are no longer using React then.

You can also access the DOM event through `ev.nativeEvent`, but it doesn't help either. Again, this is due to how React's event system works:

> _Under the hood, React attaches event handlers at the root_
> [React docs](https://react.dev/reference/react-dom/components/common#react-event-object-caveats)

So, by the time we are able to access the DOM event this way we have that:
- `ev.nativeEvent.target` points to the correct underlying DOM element
- `ev.nativeEvent.currentTarget` points to the React root, which means we are already too late...

(Strangely enough, this **does delay** the accordion's toggle for a second or two 🤔)

---

Another potential workaround that I found is to add a listener for the [capture phase](https://www.w3.org/TR/DOM-Level-3-Events/#event-flow) of the event. However, this solution is far from perfect because `@ionic/react` doesn't support `onClickCapture` handlers (or any `on<Event>Capture` handlers, as far as I know.) So you need to do some extra hacking:

```jsx
<div onClickCapture={ev => {
  if (ev.target.dataset.stopPropagation) {
    ev.stopPropagation()
    onIconClick() // <--------------------- you still have to do this ...
  }
}}>
  <IonAccordionGroup>
    <IonAccordion>
      <IonItem slot="header">
        <IonLabel>Foo</IonLabel>
        <IonIcon
          slot="end"
          icon={addCircleOutline}
          onClick={onIconClick} // <------- ... because this handler will not be called
          data-stop-propagation
        />
      </IonItem>
    </IonAccordion>
  </IonAccordionGroup>
</div>
```

Now, **this might be a good compromise** for the `@ionic/react` library. `on<Event>Capture` handlers are part of [React's API](https://react.dev/learn/responding-to-events#capture-phase-events), and they come in pretty handy in this kind of situations (_event race conditions_, so to speak.) 

Adding support for them (where regular handlers are already supported) would give us users more tools to work with in our integrations. And it doesn't feel as discouraging as integrating with (or working around) React's event system.

That said, it is up to you to give my issue another chance or not 🙃

**Comment by acontreras89** [comment] 2023-12-12 08:39
@liamdebeasi I hope you get a chance to take a look at my last comment 🤞 I believe you might find my idea interesting to say the least
