### ISSUE TITLE
bug: Mobile device web browser address bar/ status bar auto hide/show on scrolling is not working with ionic

### ISSUE THREAD

**Issue by Jangaiah** [ionic-team/ionic-framework#26420] opened 2022-12-06 06:23 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

While accessing application through mobile web browser (i.e. safari, chrome in iPhone & chrome in android), browser address bar/ status bar is stick there and not auto hiding or showing on scrolling the content page, which is the default behaviour of browser.

### Expected Behavior

While accessing application through mobile web browser (i.e. safari, chrome in iPhone & chrome in android), browser address bar/ status bar should  auto hide/show on scrolling the content page, which is the default behaviour of browser.

### Steps to Reproduce

Post deploying the ionic app to any environment and accessing on mobile web browser through url

### Ionic Info

Below are version used in app:

   "@capacitor-community/firebase-analytics": "^1.0.1",
    "@capacitor/android": "3.5.1",
    "@capacitor/app": "1.0.2",
    "@capacitor/browser": "^1.0.3",
    "@capacitor/camera": "^1.0.3",
    "@capacitor/core": "^3.0.2",
    "@capacitor/device": "^1.0.2",
    "@capacitor/filesystem": "^1.0.2",
    "@capacitor/haptics": "1.0.2",
    "@capacitor/ios": "3.3.4",
    "@capacitor/keyboard": "1.0.2",
    "@capacitor/share": "^1.0.3",
    "@capacitor/splash-screen": "^1.2.2",
    "@capacitor/status-bar": "1.0.2",
    "@capacitor/storage": "^1.0.3",
    "@ionic/angular": "^6.0.1",
    "@ionic/core": "^6.0.1",
    "@ionic/pwa-elements": "^3.0.2",

**Comment by liamdebeasi** [comment] 2022-12-06 14:16
Thanks for the report. I can reproduce this behavior, but this is not a bug in Ionic. The address bar only auto-hides when scrolling on the `body` element. Ionic apps scroll on `ion-content`, so this behavior does not happen automatically. https://github.com/ionic-team/ionic-framework/issues/19081#issuecomment-948987368 has more information on the issue, but the short answer is this is an intentional behavior of mobile web browsers and outside our control. I am going to close this, but let me know if you have any questions.

**Closed by liamdebeasi** 2022-12-06 14:16 UTC
Labels: triage
