### ISSUE TITLE
bug: Tabs-bar flickers when opening keyboard

### ISSUE THREAD

**Issue by matbravob** [ionic-team/ionic-framework#27815] opened 2023-07-17 20:00 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When i press in a searchbar the tabs-bar ficklers for a brief moment on top of the keyboard. It occurs everytime.
Im working with Ionic/Angular.

Hope someone can help me :)

### Expected Behavior

No flicker - tabs-bar hidden when keyboard opens

### Steps to Reproduce

create a new ionic app from tab template
add an ion-input on tab2
run in android simulator
click in/out input to open keyboard (multiple times)

### Ionic Info

Ionic:

   Ionic CLI                     : 7.1.1 (C:\Users\Mateo Bravo\AppData\Roaming\nvm\v18.16.0\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 7.1.3
   @angular-devkit/build-angular : 16.0.1
   @angular-devkit/schematics    : 16.0.1
   @angular/cli                  : 16.0.1
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.0.3
   @capacitor/android : 5.0.3
   @capacitor/core    : 5.0.3
   @capacitor/ios     : 5.0.3

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v18.16.0 (C:\Program Files\nodejs\node.exe)
   npm    : 9.5.1
   OS     : Windows 10

### Additional Information

My problem is the same as the issue #20262 but i can resolve it with the resolution given
[](https://github.com/ionic-team/ionic-framework/issues/20262#issue-553408020)
[](https://github.com/ionic-team/ionic-framework/issues/20262#issuecomment-577224945)

**Comment by matbravob** [comment] 2023-07-18 12:45
<app-header></app-header>

<ion-content>
  <ion-tabs>
  
    <ion-tab-bar slot="bottom" id="main-content">
      
      <ion-tab-button tab="dashboard">
        <ion-icon name="stats-chart-sharp" size="large" aria-hidden="true"></ion-icon>
      </ion-tab-button>
      
      <ion-tab-button tab="device-search">
        <ion-icon name="search" size="large" aria-hidden="true"></ion-icon>
      </ion-tab-button>
      
      <ion-tab-button tab="search-history">
        <ion-icon name="reload-circle-outline" size="large" aria-hidden="true"></ion-icon>
      </ion-tab-button>
      
      <ion-tab-button>
          <ion-menu-button >
            <ion-icon name="person" size="large"></ion-icon>
          </ion-menu-button>
      </ion-tab-button>
        
    </ion-tab-bar>

  </ion-tabs>
</ion-content>

<app-menu></app-menu>

**Comment by matbravob** [comment] 2023-07-18 12:46
<ion-content>

  <app-segment [buttons]="buttons" (onView)="changeView($event)"></app-segment>

  <div *ngIf="address" class="ion-padding">
    <ion-searchbar [placeholder]="this.appService.CoreCommonLiterals.FindDevice" type="text" enterKeyHint="search" [(ngModel)]="deviceToSearch" (keyup)="searchAddress()"></ion-searchbar>
    <ion-button class="squarebutton icon" (click)="openAddressFilters()">
      <ion-icon slot="icon-only" name="options" size="large"></ion-icon>
    </ion-button>
    
    <app-list [deviceList]="addressList"></app-list>
  </div>

  <div *ngIf="location"></div>

  <div *ngIf="groups" class="ion-padding">
    <ion-searchbar [placeholder]="this.appService.CoreCommonLiterals.FindDevice" type="text" enterKeyHint="search" [(ngModel)]="deviceToSearch"></ion-searchbar>
    <ion-button class="squarebutton icon" (click)="openGroupsFilters()">
      <ion-icon slot="icon-only" name="options" size="large"></ion-icon>
    </ion-button> 
    
    <app-list></app-list>
  </div>

</ion-content>

<app-filters-modal #filtersModal [toFilterList]="addressFilters" (onClose)="setAddressFilters($event)"></app-filters-modal>

**Comment by matbravob** [comment] 2023-07-18 12:46
<ion-searchbar [placeholder]="this.appService.CoreCommonLiterals.FindDevice" type="text" enterKeyHint="search" [(ngModel)]="deviceToSearch" (keyup)="searchAddress()"></ion-searchbar>
    <ion-button class="squarebutton icon" (click)="openAddressFilters()">
      <ion-icon slot="icon-only" name="options" size="large"></ion-icon>
    </ion-button>
    
    <app-list [deviceList]="addressList"></app-list>

**Comment by amandaejohnston** [comment] 2023-07-18 14:06
Could you create a minimal Github repo showing the issue and post a link to that? Having a runnable sample will enable us to both troubleshoot the issue and ensure the fix works down the road. Make sure it only contains the code necessary to reproduce the issue.

**Comment by matbravob** [comment] 2023-07-20 15:14
It was my fault, i was adding 'android:windowSoftInputMode="adjustPan"' in the wrong place, thank you for the rapid response!

**Comment by liamdebeasi** [comment] 2023-07-20 15:24
Glad the issue is resolved! I am going to close this.

**Closed by liamdebeasi** 2023-07-20 15:24 UTC
Labels: triage
