### ISSUE TITLE
ion-datetime ionChange event is emitted when selecting month/year

### ISSUE THREAD

**Issue by mariossavva** [ionic-team/ionic-framework#27223] opened 2023-04-18 01:49 UTC
**Ionic version:**

[] **4.x**
[ ] **5.x**
[ ] **6.x**
[x] **7.x**

**I'm submitting a ...** 

[x] bug report
[ ] feature request

**Current behavior:**

When trying to select the month/year in a datetime component, the ionChange event is emitted even though i have not selected an actual date yet which causes the popover to close because it thinks that the date has already been selected.

**Expected behavior:**

The ionChange event should only be emitted when an actual date is selected and not the month/year part of it.

**Steps to reproduce:**

See video attached.

https://user-images.githubusercontent.com/32732988/232648287-19ffc294-8f50-4702-9c84-362413d768aa.mov

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** 

```
Ionic:

   Ionic CLI                     : 7.0.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.0.2
   @angular-devkit/build-angular : 15.2.6
   @angular-devkit/schematics    : 15.2.6
   @angular/cli                  : 15.2.6
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 4.7.3
   @capacitor/android : 4.7.3
   @capacitor/core    : 4.7.3
   @capacitor/ios     : 4.7.3

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v18.15.0 (/usr/local/bin/node)
   npm    : 9.6.4
   OS     : macOS Unknown
```

**Comment by mariossavva** [comment] 2023-04-22 14:45
Added code reproduction here:

https://ionic-idqoaz.stackblitz.io
https://stackblitz.com/edit/ionic-idqoaz?file=src/index.html

**Comment by mariossavva** [comment] 2023-05-02 00:54
@amandaejohnston So i've updated the code on stackblitz to use the ion-datetime-button but it still has the same issue. When i select a date i would like the popover to close and have the new date selected. But when i try to change the month/year I have not yet selected a date but the event gets emitted thus closing the popover.

**Comment by amandaejohnston** [comment] 2023-05-02 14:07
I would recommend using the [`showDefaultButtons` prop or `buttons` slot](https://ionicframework.com/docs/api/datetime#buttons) instead of automatically closing the popover, for better user experience. We've received a feature request to allow that auto-closing behavior out of the box before, and decided it is not a use case we want to support: https://github.com/ionic-team/ionic-framework/issues/26531#issuecomment-1377318740

You may find this workaround from that thread useful if confirmation buttons still don't suit your use case: https://codepen.io/liamdebeasi/pen/bGjqxVa

I'm going to close this out as everything is working as intended, but please let me know if you have any further questions.

**Closed by amandaejohnston** 2023-05-02 14:07 UTC
Labels: triage

**Comment by craigstanton** [comment] 2023-05-08 01:51
I'm looking for the same feature that @mariossavva wants and I don't think it is related to auto closing in the way @amandaejohnston does. If on Jan 1st the date picker is opened, then Jan 1st is selected. If the user taps the month/year button to choose another month, as soon as they rotate the wheels to pick another month the ionChange event is fired even though the user has not picked a day in the month. For example if they were told to guess the date of Easter, and they changed the month to April, it would fire and event claiming they had picked April 1st, when really I think it should wait until the month/year wheels are hidden and the user taps on a day of the month. The user can pan back and forward between months using the arrows in the top right and that does not fire any events as far as I can see, so it would be consistent to let them scroll the month/year wheels without events firing.

It would be up to the individual dev to close the date picker if they wanted to after the event was received.

**Comment by amandaejohnston** [comment] 2023-05-08 14:08
@craigstanton The problem is that when the month/year wheels are changed, the value automatically updates, which is why the `ionChange` event fires. (This is to match native behavior.) In your example, what if the user selects the day first, then the month? Or the correct day (but not month) is already selected for some other reason? Once the month/year wheels are closed, they would already have the correct date selected. To close the overlay, they would then need to tap some other date, then back onto the one they want.

In your case, I would still recommend using the `showDefaultButtons` prop or `buttons` slot as described in my above post. That would maintain usability and match native behavior. Users would click Confirm when they're done regardless of how they arrived at their choice.

**Comment by craigstanton** [comment] 2023-05-08 19:57
I haven't done a large user sample, but for my experience if I picked the month then came back to the grid of days I would not expect the day to be selected.

In your examples you count changing the month the user is viewing as selecting that month along with the previously selected day of the month, but that doesn't happen when using the arrows in the top right, only when using the wheels. For my particular interface I'd be happy to just hide the wheel selectors and make users use the arrows since they are only using the next month, or the one after. If there's a way to do that I'll take it, though I would prefer the experience of only getting events when someone taps on a day in the grid.

**Comment by mariossavva** [comment] 2023-05-09 17:13
I am in the same boat at @craigstanton. Scrolling the year/month should not fire the ionChange event. It is very weird...
