### ISSUE TITLE
bug: icon click in item focuses input

### ISSUE THREAD

**Issue by EinfachHans** [ionic-team/ionic-framework#25875] opened 2022-09-02 14:51 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

We have an input in our app which we now want to extend by a camera scanner, so we added an icon at the iiems end to open the scanner. Clicking this icon will focus the input and show the keyboard.

This should be change-able by preventing the click event, but that doesn't work 🤔

### Expected Behavior

When using 

```
event.preventDefault();
event.stopPropagation();
```

the input should not focus

### Steps to Reproduce

See attached Stackblitz, just click on the camera icon

### Code Reproduction URL

https://stackblitz.com/edit/ionic6-angular13-ve7khj?file=src%2Fapp%2Fapp.component.html

### Ionic Info

From the app:

Ionic:

   Ionic CLI                     : 6.20.1 (/Users/hans/.nvm/versions/node/v16.14.2/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.2.3
   @angular-devkit/build-angular : 14.1.3
   @angular-devkit/schematics    : 14.1.3
   @angular/cli                  : 14.1.3
   @ionic/angular-toolkit        : 7.0.0

Capacitor:

   Capacitor CLI      : 4.0.1
   @capacitor/android : 4.0.1
   @capacitor/core    : 4.0.1
   @capacitor/ios     : 4.0.1

Cordova:

   Cordova CLI       : 10.0.0 (cordova-lib@10.1.0)
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res                          : 0.15.4
   native-run (update available: 1.7.0) : 1.6.0

System:

   Android SDK Tools : 25.2.3 (/Users/hans/Library/Android/sdk)
   ios-deploy        : 1.10.0
   NodeJS            : v16.14.2 (/Users/hans/.nvm/versions/node/v16.14.2/bin/node)
   npm               : 8.17.0
   OS                : macOS Monterey
   Xcode             : Xcode 13.4.1 Build version 13F100

**Comment by liamdebeasi** [comment] 2022-09-02 16:37
Thanks for the report. I am going to close this as this is not a bug in Ionic Framework.

`ion-item` has a Shadow DOM feature called `delegatesFocus` which forward focus to the first focusable element when `ion-item` is focused. Clicking the icon will cause the input to be focused since the icon is inside of `ion-item`. 

However, focusable elements inside of `ion-item` will retain focus when activated. So for example, if you clicked an `ion-button` inside of `ion-item`, the input would not be focused because the button would have focus. In your application, `ion-icon` is not a focusable element which is why the reported behavior is happening. Wrapping the icon in a button fixes this issue.

**Closed by liamdebeasi** 2022-09-02 16:37 UTC
Labels: triage

**Comment by EinfachHans** [comment] 2022-09-02 18:46
@liamdebeasi same behavior for an button as a replacement for the icon - stackblitz is updated

**Comment by liamdebeasi** [comment] 2022-09-02 18:50
I tested your update in Chrome and the input does not receive focus.

https://user-images.githubusercontent.com/2721089/188218747-5825be1c-ba35-490e-b864-24d3f45270f7.mov

**Comment by EinfachHans** [comment] 2022-09-02 18:52
your' right, seems like this only happens in safari

**Comment by liamdebeasi** [comment] 2022-09-02 18:54
I believe buttons in WebKit/Safari do not receive focus, so that could be why this behavior is happening. Once we complete the form component migration (https://github.com/ionic-team/ionic-framework/discussions/25661) I think we will likely remove the `delegatesFocus` feature as it was only added for form components.
