### ISSUE TITLE
bug: Datetime Picker does not scale on Android (a11y)

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/ionic-framework#19270] opened 2019-09-04 19:52 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

On Android, if a user sets the font size to a fairly large size the display of the values in the datetime picker changes to ellipses.

**Expected behavior:**

I am not entirely sure what should be expected since obviously the font could reach too big of a size to display, but there still is room in many cases before ellipses are displayed, so perhaps use the available room?

Or maybe hold the font size steady if possible (though the Android font scaling does not seem to work that way as the font size does actually stay the same in the CSS, so 🤷🏻‍♂️

**Steps to reproduce:**

1. build this: https://github.com/kensodemann/datetime-picker-a11y
1. install on Android device
1. in system menu, increase the system font size up from default a few times
1. eventually you will get the ellipses

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.7 (/Users/kensodemann/.nvm/versions/node/v10.16.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.9.0
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.3 (cordova-lib@9.0.2)
   Cordova Platforms : android 8.0.0, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.1, (and 4 other plugins)

Utility:

   cordova-res : 0.3.0 (update available: 0.6.0)
   native-run  : 0.2.4 (update available: 0.2.8)

System:

   Android SDK Tools : 26.1.1 (/Users/kensodemann/Library/Android/sdk/)
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.2
   NodeJS            : v10.16.0 (/Users/kensodemann/.nvm/versions/node/v10.16.0/bin/node)
   npm               : 6.11.2
   OS                : macOS Mojave
   Xcode             : Xcode 10.3 Build version 10G8
```

**Comment by willmartindev** [comment] 2021-06-28 05:50
Cannot reproduce in Framework v6, closing.

**Closed by willmartindev** 2021-06-28 05:50 UTC
Labels: package: core, type: bug
