### ISSUE TITLE
bug(angular) : side menu requires two click sometime 

### ISSUE THREAD

**Issue by indraraj26** [ionic-team/ionic-framework#21955] opened 2020-08-22 16:24 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

Sidemenu ion-item requires two click sometime 

Steps 1: drag menu from left
Steps 2: click on home.
steps 3: click on search
step 4: click on home
step 5: click on search
repeat this you will notice menu does not close and also does not trigger click. 

![image](https://user-images.githubusercontent.com/23274631/90960704-35c2c780-e4c1-11ea-8185-d30413acffd7.png)

**Expected behavior:**

It should trigger click listener once i clicked

**Steps to reproduce:**

**Related code:**

Repo: https://github.com/indraraj26/side-menu-click-bug

**Other information:**

**Ionic info:**

```
ionic info

Ionic:

   Ionic CLI                     : 6.11.0 (C:\Users\indra26\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.3.1
   @angular-devkit/build-angular : 0.1000.6
   @angular-devkit/schematics    : 10.0.6
   @angular/cli                  : 10.0.6
   @ionic/angular-toolkit        : 2.3.0

Capacitor:

   Capacitor CLI   : 2.4.0
   @capacitor/core : 2.4.0

Utility:

   cordova-res : 0.15.1
   native-run  : 1.0.0

System:

   NodeJS : v10.16.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.9.0
   OS     : Windows 10

```

**Comment by liamdebeasi** [comment] 2020-08-24 13:20
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/21459.

**Closed by liamdebeasi** 2020-08-24 13:20 UTC
Labels: triage
