### ISSUE TITLE
bug: Ion-Input placeholder text bounces on input focus

### ISSUE THREAD

**Issue by SoCuul** [ionic-team/ionic-framework#27174] opened 2023-04-11 21:34 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x, Nightly

### Current Behavior

When an `ion-input` element is focused, the placeholder text sort-of bounces around, before returning to its desired location.

### Expected Behavior

The placeholder text should remain in the specified location when focused.

### Steps to Reproduce

1. Focus on an input by trying to enter a value.

### Code Reproduction URL

https://github.com/SoCuul/ioninput-placeholder-bug/tree/main

### Ionic Info

Ionic:

   Ionic CLI       : 7.0.0 (/Users/socuul/.nvm/versions/node/v18.12.1/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 7.0.1

Capacitor:

   Capacitor CLI      : 4.7.3
   @capacitor/android : not installed
   @capacitor/core    : 4.7.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.2

System:

   NodeJS : v18.12.1 (/Users/socuul/.nvm/versions/node/v18.12.1/bin/node)
   npm    : 9.6.3
   OS     : macOS Unknown

**Comment by amandaejohnston** [comment] 2023-04-12 17:36
Thank you for the issue. I'm unable to reproduce the bug using the provided repo. What browser/device and version are you testing on? Also, I noticed you are using the legacy syntax with your inputs (note the warnings logged in the console for each input). Can you confirm if this reproduces using the updated syntax?

**Comment by Ajax-ua** [comment] 2023-04-13 07:29
I have the same issue using @ionic/angular. 
```
      <ion-list class="list">
        <ion-item class="item">
            <ion-input
                label=""
                inputmode="email"
                placeholder="Email"
            >
            </ion-input>
        </ion-item>
        <ion-item class="item">
            <ion-input
                label=""
                type="password"
                placeholder="Password"
            >
            </ion-input>
        </ion-item>
      </ion-list>
```
In my case the issue persists **only for the first** ion-input in the list.
Please note that I've added the `label` attribute to apply updated syntax so there are no warnings logged but I set it empty because I don't need anything to be displayed.

**Comment by PleoCreative** [comment] 2023-04-19 22:29
Getting the same issue here using v7 new syntax either `floating` or `stacked` `labelPlacement`, however when focusing an input the input value jumps up (video attached). By inspecting the DOM on focus it looks like a another input with class ‘cloned-input’ this looks to push the original input up. Problem only appears to be on iOS, however have only tested on Android emulators and issue is not happening. Any ideas or thoughts as to why this is happening?

https://user-images.githubusercontent.com/10227063/233213476-c81e540e-d804-43ad-83dc-b05999619e9e.MOV

**Comment by amandaejohnston** [comment] 2023-04-20 14:56
Thank you for the screencast. It looks like this is the same issue as https://github.com/ionic-team/ionic-framework/issues/27249. While that one is much newer, there's already a PR up to fix it, so I think it makes sense to fold this in with that one. @SoCuul Can you confirm if the recording posted in the previous comment is the same issue you're running into?

**Comment by SoCuul** [comment] 2023-04-20 20:31
> Thank you for the screencast. It looks like this is the same issue as https://github.com/ionic-team/ionic-framework/issues/27249. While that one is much newer, there's already a PR up to fix it, so I think it makes sense to fold this in with that one. @SoCuul Can you confirm if the recording posted in the previous comment is the same issue you're running into?

I can confirm this is the same issue I am experiencing.

**Comment by amandaejohnston** [comment] 2023-04-20 20:38
Okay, perfect. In that case, I'm going to close this both as a duplicate of https://github.com/ionic-team/ionic-framework/issues/27249, and because the fix for it was just merged in earlier today 😄 It will be available in a future release of Ionic.

**Closed by amandaejohnston** 2023-04-20 20:38 UTC
Labels: triage
