### ISSUE TITLE
bug: Line appears below first ion-list item when using inset and lines-"none" attributes together 

### ISSUE THREAD

**Issue by dexster** [ionic-team/ionic-framework#23735] opened 2021-08-06 13:06 UTC
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

Using ion-list with both `lines="none"` and `inset="true"` attributes causes a line to show beneath the first item. Removing the inset causes the line to disappear 

### Expected Behavior

No lines should be visible

### Steps to Reproduce

Using the example from the ionic docs add the inset and lines attributes

```
<ion-list lines="none" inset="true">
  <ion-item>
    <ion-label>Pokémon Yellow</ion-label>
  </ion-item>
  <ion-item>
    <ion-label>Mega Man X</ion-label>
  </ion-item>
  <ion-item>
    <ion-label>The Legend of Zelda</ion-label>
  </ion-item>
  <ion-item>
    <ion-label>Pac-Man</ion-label>
  </ion-item>
  <ion-item>
    <ion-label>Super Mario World</ion-label>
  </ion-item>
</ion-list>
```

### Ionic Info

Ionic:

   Ionic CLI : 6.15.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v14.15.5
   npm    : 6.14.11
   OS     : macOS Big Sur

"@ionic/angular": "^5.6.13",

### Additional Information

This `list-inset` class is the culprit and has a higher specificity than the `lines-none` class 

```
.list-md.list-inset ion-item:first-child {
    --border-radius: 2px 2px 0 0;
    --border-width: 0 0 1px 0;
```

```
.list-md-lines-none .item {
    --border-width: 0;
    --inner-border-width: 0;
}
```

**Comment by liamdebeasi** [comment] 2021-08-06 13:43
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/20819.

**Closed by liamdebeasi** 2021-08-06 13:43 UTC
Labels: triage

**Comment by dexster** [comment] 2021-08-06 14:34
Aah, okay. I did search for an open issue first. Clearly my search skills need improvement
