### ISSUE TITLE
bug: ReferenceError: Cannot access 'IonRouterOutlet' before initialization

### ISSUE THREAD

**Issue by ggarg2** [ionic-team/ionic-framework#28625] opened 2023-12-04 08:10 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Hi Team,

We are using Ionic and Angular to building our application. This issue we are getting after upgrading Angular to 17.0.5

Please have a look at the error below.

```typescript
10:39:19 am [vite] Error when evaluating SSR module /main.server.mjs:
|- ReferenceError: Cannot access 'IonRouterOutlet' before initialization
    at eval (d:/dev/bag2bag/ng-17/node_modules/@ionic/angular/fesm2020/ionic-angular-standalone.mjs:122:55)
    at eval (d:/dev/bag2bag/ng-17/node_modules/@ionic/angular/fesm2020/ionic-angular-standalone.mjs:148:1)
    at async instantiateModule (file:///D:/dev/bag2bag/ng-17/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:56052:9)

10:39:19 am [vite] Internal server error: Cannot access 'IonRouterOutlet' before initialization
      at eval (d:/dev/bag2bag/ng-17/node_modules/@ionic/angular/fesm2020/ionic-angular-standalone.mjs:122:55)
      at eval (d:/dev/bag2bag/ng-17/node_modules/@ionic/angular/fesm2020/ionic-angular-standalone.mjs:148:1)
      at async instantiateModule (file:///D:/dev/bag2bag/ng-17/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:56052:9)
10:39:19 am [vite] Internal server error: Cannot access 'IonRouterOutlet' before initialization
      at eval (d:/dev/bag2bag/ng-17/node_modules/@ionic/angular/fesm2020/ionic-angular-standalone.mjs:122:55)
      at eval (d:/dev/bag2bag/ng-17/node_modules/@ionic/angular/fesm2020/ionic-angular-standalone.mjs:148:1)
      at async instantiateModule (file:///D:/dev/bag2bag/ng-17/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:56052:9) (x2)
``` 

Package.json

```typescript
{
  "name": "ng-17",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test",
    "serve:ssr:ng-17": "node dist/ng-17/server/server.mjs"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^17.0.5",
    "@angular/common": "^17.0.5",
    "@angular/compiler": "^17.0.5",
    "@angular/core": "^17.0.5",
    "@angular/forms": "^17.0.5",
    "@angular/platform-browser": "^17.0.5",
    "@angular/platform-browser-dynamic": "^17.0.5",
    "@angular/platform-server": "^17.0.5",
    "@angular/router": "^17.0.5",
    "@angular/ssr": "^17.0.5",
    "@ionic/angular": "^7.5.7",
    "express": "^4.18.2",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.14.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^17.0.5",
    "@angular/cli": "^17.0.5",
    "@angular/compiler-cli": "^17.0.5",
    "@ionic/angular-toolkit": "^10.0.0",
    "@types/express": "^4.17.17",
    "@types/jasmine": "~5.1.0",
    "@types/node": "^18.18.0",
    "jasmine-core": "~5.1.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.2.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.1.0",
    "ng-packagr": "^17.0.0",
    "typescript": "~5.2.2"
  }
}

``` 

app component html

```html
<ion-app>
  <ion-header>
    <ion-buttons>
      <ion-back-button></ion-back-button>
    </ion-buttons>

  </ion-header>

  <ion-content>
    hello world
  </ion-content>

</ion-app>
```

app component ts

```typescript

import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import {IonApp, IonBackButton, IonButtons, IonContent, IonHeader} from "@ionic/angular/standalone";

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet, IonApp, IonHeader, IonButtons, IonBackButton, IonContent],
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss'
})
export class AppComponent {
  title = 'ng-17';
}


```

app config ts

```typescript
import { ApplicationConfig } from '@angular/core';
import { provideRouter } from '@angular/router';

import { routes } from './app.routes';
import { provideClientHydration } from '@angular/platform-browser';
import { provideIonicAngular } from '@ionic/angular/standalone';

export const appConfig: ApplicationConfig = {
  providers: [provideRouter(routes), provideClientHydration(), provideIonicAngular({})]
};

``` 

```

app config server ts

```typescript
import { mergeApplicationConfig, ApplicationConfig } from '@angular/core';
import { provideServerRendering } from '@angular/platform-server';
import { appConfig } from './app.config';

const serverConfig: ApplicationConfig = {
  providers: [
    provideServerRendering()
  ]
};

export const config = mergeApplicationConfig(appConfig, serverConfig);


``` 

app routes ts
```typescript
import { Routes } from '@angular/router';

export const routes: Routes = [];

``` 

main ts
```typescript
import { bootstrapApplication } from '@angular/platform-browser';
import { appConfig } from './app/app.config';
import { AppComponent } from './app/app.component';

bootstrapApplication(AppComponent, appConfig)
  .catch((err) => console.error(err));

```
 
main server ts
```typescript

import { bootstrapApplication } from '@angular/platform-browser';
import { AppComponent } from './app/app.component';
import { config } from './app/app.config.server';

const bootstrap = () => bootstrapApplication(AppComponent, config);

export default bootstrap;

```

server.ts

```typescript
import { APP_BASE_HREF } from '@angular/common';
import { CommonEngine } from '@angular/ssr';
import express, {Express} from 'express';
import { fileURLToPath } from 'node:url';
import { dirname, join, resolve } from 'node:path';
import bootstrap from './src/main.server';

// The Express app is exported so that it can be used by serverless Functions.
export function app(): express.Express {
  const server: Express = express();
  const serverDistFolder: string = dirname(fileURLToPath(import.meta.url));
  const browserDistFolder : string = resolve(serverDistFolder, '../browser');
  const indexHtml: string = join(serverDistFolder, 'index.server.html');

  const commonEngine = new CommonEngine();

  server.set('view engine', 'html');
  server.set('views', browserDistFolder);

  // Example Express Rest API endpoints
  // server.get('/api/**', (req, res) => { });
  // Serve static files from /browser
  server.get('*.*', express.static(browserDistFolder, {
    maxAge: '1y'
  }));

  // All regular routes use the Angular engine
  server.get('*', (req, res, next) => {
    const { protocol, originalUrl, baseUrl, headers } = req;

    commonEngine
      .render({
        bootstrap,
        documentFilePath: indexHtml,
        url: `${protocol}://${headers.host}${originalUrl}`,
        publicPath: browserDistFolder,
        providers: [{ provide: APP_BASE_HREF, useValue: baseUrl }],
      })
      .then((html) => res.send(html))
      .catch((err) => next(err));
  });

  return server;
}

function run(): void {
  const port = process.env['PORT'] || 4000;

  // Start up the Node server
  const server = app();
  server.listen(port, () => {
    console.log(`Node Express server listening on http://localhost:${port}`);
  });
}

run();

```

### Expected Behavior

This suppose to not throw any error.

### Steps to Reproduce

Create new Angular project. (Use Angular ^17.0.5 version)
Add Ionic - ng add @ionic/angular
ng server

### Ionic Info

Ionic:

   Ionic CLI                     : 7.1.5 (C:\Users\gaura\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 7.5.7
   @angular-devkit/build-angular : 17.0.5
   @angular-devkit/schematics    : 17.0.5
   @angular/cli                  : 17.0.5
   @ionic/angular-toolkit        : 10.0.0

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v20.10.0 (C:\Program Files\nodejs\node.exe)
   npm    : 10.2.4
   OS     : Windows 10

**Comment by ggarg2** [comment] 2023-12-04 18:59
Please find the repository - https://github.com/ggarg2/ionic-angular-17-0-5

**Comment by liamdebeasi** [comment] 2023-12-06 15:02
Does this happen if you use Webpack in your project instead?

**Comment by ggarg2** [comment] 2023-12-06 17:21
Hi @liamdebeasi, After upgrading to Angular 17.x.x, I have not tried webpack but let me tell you one thing may be it will help you to analyse.

I was not getting any error when I was using below angular dependencies. Something is broken after updating to 17.0.5.

```typescript

"@angular/animations": "^17.0.4",
    "@angular/common": "^17.0.4",
    "@angular/core": "^17.0.4",
   "@angular/forms": "^17.0.4",
    "@angular/platform-browser": "^17.0.4",
    "@angular/platform-browser-dynamic": "^17.0.4",
    "@angular/platform-server": "^17.0.4",
    "@angular/router": "^17.0.4",
    "@angular/service-worker": "^17.0.4",
    "@angular/ssr": "^17.0.3",
=====================

"@angular-devkit/architect": "^0.1700.3",
    "@angular-devkit/build-angular": "^17.0.3",
    "@angular-devkit/core": "^17.0.3",
    "@angular-devkit/schematics": "^17.0.3",
    "@angular/cli": "^17.0.3",
    "@angular/compiler": "^17.0.4",
    "@angular/compiler-cli": "^17.0.4",
    "@angular/language-service": "^17.0.4",
```

**Comment by sean-perkins** [comment] 2023-12-07 00:12
Hello @ggarg2 thanks for reporting this issue! 

This specific error comes from our use of import aliases in our implementation: https://github.com/ionic-team/ionic-framework/blob/ec9228f54feaeadb423543c3f83bc6cf2229e1cb/packages/angular/standalone/src/navigation/router-outlet.ts#L4

In Ionic Framework we could avoid the import alias by giving the common implementations of these components used as providers an unique name.

I'll be reaching out to the Angular team to identify if this is a responsibility of Angular, Vite, etc. Using import aliases shouldn't impact variable access. 

Regardless of this error message, you will receive a client-side error when using `@angular/ssr` hydration with Ionic Framework: 

```
core.mjs:11751 ERROR Error: NG0500: During hydration Angular expected <ion-buttons> but found a comment node.

Angular expected this DOM:
  <ion-buttons>…</ion-buttons>  <-- AT THIS LOCATION
  …

Actual DOM is:
<ion-header _ngcontent-ng-c4070505595="">
  <!--  -->  <-- AT THIS LOCATION
  …
</ion-header>
```

Ionic Framework does not support the new hydration model from Angular. You will need to add `ngSkipHydration` to `ion-app` to avoid this error.  This nullifies the benefits of having this hydration configuration to begin with.

**Comment by ggarg2** [comment] 2023-12-07 05:27
Hi @sean-perkins,  Thank you for acknowledge this issue and for the SSR tip.

I have handled the SSR issue. I am not useing IonicServerModule in server side rendering. I am not sure if this is a good way but to enable hydration I don't have any other option.

```typescript
const serverConfig: ApplicationConfig = {
  providers: [
    provideServerRendering()
  ]
};

export const config = mergeApplicationConfig(appConfig, serverConfig);
```

**Comment by ggarg2** [comment] 2023-12-07 06:51
Hi @sean-perkins, @liamdebeasi @eideard-hm 

Please update the Angular to ^17.0.6 and Ionic to ^7.5.7. This issue is fixed. We can close this issue. Thank you guys for your valuable time :)

**Comment by liamdebeasi** [comment] 2023-12-07 14:44
Thanks for info! I can reproduce the issue in your sample app with Ionic Angular v7.5.7 and Angular 17.0.5. The issue no longer reproduces in Ionic Angular v7.5.7 and Angular 17.0.6. I am going to close this since the reported issue no longer reproduces.

Please note that the SSR limitations Sean mentioned in https://github.com/ionic-team/ionic-framework/issues/28625#issuecomment-1843919548 will still apply even after updating to Angular 17.0.6.

**Closed by liamdebeasi** 2023-12-07 14:44 UTC
Labels: triage
