### ISSUE TITLE
bug: SplitPane not working when Menu is wrapped in a Component

### ISSUE THREAD

**Issue by nickwinger** [ionic-team/ionic-framework#20681] opened 2020-03-03 09:22 UTC
# Bug Report
When wrappen the  menu inside a SpliePane in it's own component (e.g. `<my-menu>`) the SplitPane is not working as expected (2 Panes are shown)

**Ionic version:**

[x] **5.x**
latest

**Current behavior:**

When wrapping the menu inside a SplitPane in it's own component (e.g. <my-menu>)
2 Panes are shwon

**Expected behavior:**

The SplitPane should work as if i would put the `<ion-menu>` right underneath the SplitPane

**Steps to reproduce:**

**Related code:**
not working:
```
<ion-split-pane when="xl" contentId="main">
  <my-menu></my-menu>

  <ion-router-outlet main id="main"></ion-router-outlet>
</ion-split-pane>
```

working:
```
<ion-split-pane when="xl" contentId="main">
  <ion-menu>...</ion-menu>

  <ion-router-outlet main id="main"></ion-router-outlet>
</ion-split-pane>
```

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment] 2020-03-03 14:15
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?

**Comment by nickwinger** [comment] 2020-03-05 08:23
Here is the repo where you can reproduce the issue:
https://github.com/nickwinger/ionicMenuBug

The menu should be permanent open on desktop but it isn't

**Comment by liamdebeasi** [comment] 2020-03-05 20:51
Thanks for the follow up. I need to dig into this more, but at first glance it does not look like this is possible. The `ion-menu` in your app is missing these styles: https://github.com/ionic-team/ionic/blob/master/core/src/components/split-pane/split-pane.scss#L56-L61.

The problem is that the `::slotted` pseudo-element only works on slotted top-level nodes. Since the top level node is your `wrapped-menu` component, the styles will not get applied.

**Comment by nickwinger** [comment] 2020-03-06 08:48
hmm, i copied the css-classes applied to the ion-menu when it is not wrapped to the wrapped ion-menu but it still not showing.
I guess there must be more into showing the menu but only css-classes (styles) ?
is it really only css classes handling the menu show/hide state ?

**Comment by liamdebeasi** [comment] 2020-03-19 19:53
Can you try the following dev build and let me know if it fixes the issue?

`npm i @ionic/angular@5.1.0-dev.202003191943.dae1ce8`

**Comment by cnanders** [comment] 2020-11-11 05:07
This bug is still happening as of 5.4.3.  If you get rid of the`<ion-split-pane>` it works as advertised with `<ion-menu>` wrapped in its own component, e.g., `<my-side-menu>`

`<ion-app>
    <my-side-menu></side-side-menu>
    <ion-router-outlet></ion-router-outlet>
</ion-app>`

**Comment by jbagaresgaray** [comment] 2021-04-07 13:56
This bug is still happening as of 5.6.3 for **@ionic/vue**

```
<IonSplitPane content-id="main-content">
     <Sidebar />
     <ion-router-outlet id="main-content" ></ion-router-outlet>
</IonSplitPane>
```

**Comment by MRDNZ** [comment] 2023-01-03 14:04
Bug is still there in "@ionic/angular": "^6.1.4". Is there any update/progress on this subject? It is impossible to wrap split-pane/menu logic in separate components

**Comment by akshay-trex** [comment] 2023-04-17 05:43
any update on the fix for this bug?

**Comment by philjones88** [comment] 2023-08-23 13:09
Still in v7

**Comment by ZenulAbidin** [comment] 2023-10-07 04:59
Latest version of @ionic/angular ^7.4.3 still has this problem - using href instead of routerLink is an acceptable but not satisfactory workaround.

**Comment by arrighidante** [comment] 2023-12-21 22:12
Still failing in @ionic/angular7.6.1

**Comment by liamdebeasi** [comment] 2024-01-10 21:40
Hi everyone,

Here is a dev build if anyone is interested in testing a proposed fix: `7.6.2-dev.11704922151.1fd3369f`

Install example:

```
npm install @ionic/react@7.6.2-dev.11704922151.1fd3369f @ionic/react-router@7.6.2-dev.11704922151.1fd3369f
```

**Comment by liamdebeasi** [comment] 2024-01-15 20:33
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/28801, and a fix will be available in an upcoming release of Ionic Framework. We are shipping this in a major release of Ionic to de-risk some of the internal infrastructure changes we made to resolve this bug. Feel free to continue testing the dev build, and let me know if you run into any issues.

**Closed by liamdebeasi** 2024-01-15 20:33 UTC
Labels: package: core, type: bug
