### ISSUE TITLE
bug: If overlapping ionModals, the first one glitches

### ISSUE THREAD

**Issue by OstrIvan** [ionic-team/ionic-framework#28384] opened 2023-10-19 08:23 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Brief description:
You are in a view where you have imported two ionModal where each one is inside a different component.

You click a button that opens the first component. In that modal, there is an input that invokes the second component. This modal opens and you have to choose an option or close the modal. Whatever you do, once you close the second modal, the first one glitches.

### Video example:

https://github.com/ionic-team/ionic-framework/assets/111231036/7c03ea70-fe93-4163-ad70-d935ccd8d821

### Expected Behavior

Once the upper modal closes, the first overlapped should be looking good and not glitching.

### Steps to Reproduce

You will need a view and two components.
1. Add an ionModal to each component and import them into the view.
2. Open the first ionModal. There should be an input or button to activate the second one.
3. Then complete an action in the second one to close it and pass data to the first one. This should be done in the view file (See attached example, on the left side is the view and on the right the modal component)
<img width="2048" alt="Screenshot 2023-10-19 at 10 05 23" src="https://github.com/ionic-team/ionic-framework/assets/111231036/79add60f-6341-443d-8979-34be085d9d28">

Once this happens, the first modal starts glitching...

### Ionic Info

Ionic:

   Ionic CLI       : 6.20.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 7.5.0

Capacitor:

   Capacitor CLI      : 5.5.0
   @capacitor/android : 5.5.0
   @capacitor/core    : 5.5.0
   @capacitor/ios     : 5.5.0

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.3

System:

   NodeJS : v18.13.0 (/usr/local/bin/node)
   npm    : 8.19.3
   OS     : macOS

**Comment by liamdebeasi** [comment] 2023-10-19 13:36
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/28378.

**Closed by liamdebeasi** 2023-10-19 13:36 UTC
Labels: triage
