### ISSUE TITLE
bug: In Firefox, when the page returns, ion-content will automatically scroll to the top

### ISSUE THREAD

**Issue by HyperLife1119** [ionic-team/ionic-framework#21958] opened 2020-08-23 14:46 UTC
# Bug Report

**Ionic version:**

 **5.x**

**Current behavior:**

In Firefox, first scroll to page A to the bottom, then navigate to page B, and then return to page A. At this time, page A automatically scrolls back to the top. (No scroll animation)
This may be caused by `ion-content` incompatibility with Firefox?
My version of firefox is currently the latest official version. This problem occurs in both the desktop and mobile versions of Firefox

**Expected behavior:**

Normally, when returning from page B to page A, page A still maintains the previous scroll height (it is normal in Chrome browser)

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment] 2020-08-24 13:23
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/20821.

**Closed by liamdebeasi** 2020-08-24 13:23 UTC
Labels: triage
