### ISSUE TITLE
bug: Button no click feedack.

### ISSUE THREAD

**Issue by infacto** [ionic-team/ionic-framework#25097] opened 2022-04-11 10:02 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

No button click feedback. Just boring and bad UX.

![demo](https://user-images.githubusercontent.com/60390085/162711890-3abc2cc5-938b-4389-8a02-485ab8993043.gif)

### Expected Behavior

![demo](https://user-images.githubusercontent.com/60390085/162715343-c6ef7f3a-93dd-4d12-a60e-bed4374db935.gif)

### Steps to Reproduce

https://ionicframework.com/docs/api/button
https://material.io/components/buttons

### Ionic Info

v6
https://ionicframework.com/docs/api/button (latest on issue creation)

### Additional Information

Maybe just docs / demo issue? The buttons feels dead. But that had worked before. Ok, the iOS buttons have never had a ripple effect. But it would be nice if we breathed more life into it.

**Comment by SaroGFX** [comment] 2022-04-11 10:42
I think you can enable Ripple globally or use the ripple effect to get this behaviour or use the component: https://ionicframework.com/docs/api/ripple-effect

But it was working for me by default without any extra configuration (At least for Android MD). So I'm not sure if you tried adding a button?

**Comment by sean-perkins** [comment] 2022-04-12 02:06
Duplicate of #25094, closing to organize communication in that thread. Thanks for reporting this!

**Closed by sean-perkins** 2022-04-12 02:06 UTC
Labels: triage
