### ISSUE TITLE
bug: Unexpected ion-menu opening on another page

### ISSUE THREAD

**Issue by alexgavard** [ionic-team/ionic-framework#29412] opened 2024-04-28 21:29 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

The problem occurs when using ion-menu with the **side="end"** propertie to open the menu on the right side. The behavior is perfect on the home screen. However, when navigating to another page, such as a detail page, and simulating a swipe from the right side, this results in the menu being open when returning to the home screen.

https://github.com/ionic-team/ionic-framework/assets/164131636/3e513e8d-7866-4047-83e3-1dec6b605c63

### Expected Behavior

The menu should not open on a new page. When using the **side="start"** propertie to open the menu on the left side, this problem does not occur.

### Steps to Reproduce

1. Click on the 'Detail' button.
2. Perform a swipe from the right side as if you were going to open the menu.
3. Return to the home screen.

### Code Reproduction URL

https://github.com/alexgavard/ionic-demo

### Ionic Info

Ionic:

   Ionic CLI                     : 7.2.0 (/Users/alex/.nvm/versions/node/v20.10.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 8.0.1
   @angular-devkit/build-angular : 17.3.6
   @angular-devkit/schematics    : 17.3.6
   @angular/cli                  : 17.3.6
   @ionic/angular-toolkit        : 11.0.1

Capacitor:

   Capacitor CLI      : 6.0.0
   @capacitor/android : not installed
   @capacitor/core    : 6.0.0
   @capacitor/ios     : 6.0.0

Utility:

   cordova-res : 0.15.4
   native-run  : 2.0.1

System:

   NodeJS : v20.10.0 (/Users/alex/.nvm/versions/node/v20.10.0/bin/node)
   npm    : 10.2.5
   OS     : macOS Unknown

**Comment by liamdebeasi** [comment] 2024-05-01 13:33
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/25272.

**Closed by liamdebeasi** 2024-05-01 13:33 UTC
Labels: triage
