### ISSUE TITLE
feat: nested reorder option for ion-reorder

### ISSUE THREAD

**Issue by ivinantony** [ionic-team/ionic-framework#25754] opened 2022-08-12 05:22 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Nested reorder option for ion-reorder

### Describe the Use Case

Assume that we have many users and we need to make some of them in to a group. Currently we can only move it in an array but not able to move to a nested array

### Describe Preferred Solution

Option to move a item to its parent/child array

### Describe Alternatives

Now i just created a single array from a nested array with a flag and header to show the group

### Related Code

Something nice and similar like trello

**Comment by liamdebeasi** [comment] 2022-08-12 13:13
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/23022.

**Closed by liamdebeasi** 2022-08-12 13:13 UTC
Labels: triage
