### ISSUE TITLE
bug: ion-item is not clickable if there is any other element inside it

### ISSUE THREAD

**Issue by indraraj26** [ionic-team/ionic-framework#25738] opened 2022-08-07 16:34 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

if there is an element inside in ion-item and when you click on ion-item it will not select/check the checkbox/radio.

### Expected Behavior

It should select the checkbox/radio if you click on empty space.

### Steps to Reproduce

download reproduction 
1. npm i & ionic serve
2.  click on empty space

When every other element is hidden then it is working fine, In image it is the first case
Try to click on yellow mark.
![image](https://user-images.githubusercontent.com/23274631/183301258-293faf39-227c-4dc3-9d93-22c499c154e4.png)

### Code Reproduction URL

https://github.com/indraraj26/storage-boolean-issue/tree/ion-item-clickable

### Ionic Info

Ionic:

   Ionic CLI                     : 6.19.0 (C:\Users\user\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.1.3
   @angular-devkit/build-angular : 13.2.6
   @angular-devkit/schematics    : 13.2.6
   @angular/cli                  : 13.2.6
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.5.0
   @capacitor/android : 3.6.0
   @capacitor/core    : 3.6.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.5.0

System:

   NodeJS : v14.17.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.13
   OS     : Windows 10

**Comment by liamdebeasi** [comment] 2022-08-09 14:16
Thanks for the issue. Unfortunately, this is the intended behavior when using multiple interactive elements within a single `ion-item`. When there is only one interactive within the item, we can assume that clicking anywhere inside of the item should trigger that interactive.

When there are multiple interactives, we cannot make that same assumption. This has the side effect of no longer letting the label/white space trigger the checkbox/radio in your examples. Specifically, this is the code responsible for the unexpected behaviors in your app: https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/item/item.tsx#L237

The good news is that the proposals we have for form components in https://github.com/ionic-team/ionic-framework/discussions/25660 and https://github.com/ionic-team/ionic-framework/discussions/25661 should make this behavior a bit more predictable.

I am going to close this for now, but let me know if you have any other questions. We are tracking work on these form component changes internally, and this is a priority for us. Thanks!

**Closed by liamdebeasi** 2022-08-09 14:16 UTC
Labels: triage

**Comment by indraraj26** [comment] 2022-08-09 19:26
Thank you Liam.

So current workaround would be to listen ion-item click and check target then toggle the state of checkbox/radio. Is that correct?

**Comment by liamdebeasi** [comment] 2022-08-09 19:39
Yes, that should work here.
