### ISSUE TITLE
feat: mutiple date ion-datetime

### ISSUE THREAD

**Issue by phyr0s** [ionic-team/ionic-framework#25382] opened 2022-06-01 08:01 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Allow to ion-datetime to select a range of dates and multiple single dates.

### Describe the Use Case

Example:

Allow to select Monday and Saturday

Allow to select  range Monday to Saturday

### Describe Preferred Solution

Create new input "selection" with values 'range' and 'multiple'. If is range or multiple should return an array of dates instead a simple date.

**Comment by phyr0s** [comment] 2022-06-01 10:50
Related #23572

**Comment by liamdebeasi** [comment] 2022-06-01 12:58
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/24674.

**Closed by liamdebeasi** 2022-06-01 12:58 UTC
Labels: triage
