### ISSUE TITLE
bug: "contenteditable" div inside ion-item is not editable

### ISSUE THREAD

**Issue by danielabhishekamm** [ionic-team/ionic-framework#28259] opened 2023-09-29 07:10 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v6.x, v7.x

### Current Behavior

A div with attribute "contenteditable" set to true is not editable when it is within an ion-item. This issue is found in Chrome versions 117 and 118. It works fine in Chrome 116.

Here's an example of the issue - 
https://stackblitz.com/edit/angular-ybmbwp?file=src%2Fapp%2Fexample.component.css,src%2Fapp%2Fexample.component.html

### Expected Behavior

A div with "contenteditable" attribute set to true should be editable within an ion-item, as it was in the previous Chrome versions.

### Steps to Reproduce

1. Create an ion-item
2. Add a div to this ion-item
3. Give appropriate width and height to the div
4. Set "contenteditable" attribute to true on this div
5. Test if the div is editable

Example - https://stackblitz.com/edit/angular-ybmbwp?file=src%2Fapp%2Fexample.component.css,src%2Fapp%2Fexample.component.html

### Code Reproduction URL

https://stackblitz.com/edit/angular-ybmbwp?file=src%2Fapp%2Fexample.component.css,src%2Fapp%2Fexample.component.html

### Ionic Info

Ionic:

   Ionic CLI                     : 6.20.9 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.3.1
   @angular-devkit/build-angular : 14.2.6
   @angular-devkit/schematics    : 12.1.4
   @angular/cli                  : 14.2.12
   @ionic/angular-toolkit        : 4.0.0

Capacitor:

   Capacitor CLI      : 3.1.2
   @capacitor/android : 3.1.2
   @capacitor/core    : 3.1.2
   @capacitor/ios     : 3.1.2

Utility:

   cordova-res                          : not installed globally
   native-run (update available: 1.7.3) : 1.4.0

System:

   NodeJS : v14.21.3 (/Users/danielabhishekam/.nvm/versions/node/v14.21.3/bin/node)
   npm    : 6.14.18
   OS     : macOS Unknown

**Comment by liamdebeasi** [comment] 2023-09-29 13:45
Thanks for the report. I can reproduce this on Chrome 117. However, this bug appears to be resolved in the upcoming Chrome 119 release. I am going to close this since is not a bug in Ionic, but let me know if you have questions.

**Closed by liamdebeasi** 2023-09-29 13:45 UTC
Labels: triage
