### ISSUE TITLE
bug: Building Ionic cordova android returns ERROR "An unhandled exception occurred: Project target does not exist."

### ISSUE THREAD

**Issue by MoAsmar** [ionic-team/ionic-framework#24940] opened 2022-03-15 08:46 UTC
### Prerequisites

- [ ] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Ionic cordova build android is not working and returning the below error:

![image](https://user-images.githubusercontent.com/8542126/158336874-bdfdda47-97f3-4ffb-9ad5-0c7549a55057.png)

### Expected Behavior

Ionic Cordova should build the project for android normally.

### Steps to Reproduce

```
$ ionic start --cordova

Pick a framework!

Please select the JavaScript framework to use for your new app. To bypass this prompt next time, supply a value for the
--type option.

? Framework: Angular

Every great app needs a name!

Please enter the full name of your app. You can change this at any time. To bypass this prompt next time, supply name,
the first argument to ionic start.

? Project name: temp-ionic6

Let's pick the perfect starter template!

Starter templates are ready-to-go Ionic apps that come packed with everything you need to build your app. To bypass this
prompt next time, supply template, the second argument to ionic start.

? Starter template: sidemenu
√ Preparing directory .\temp-ionic6 in 2.06ms
√ Downloading and extracting sidemenu starter in 474.11ms
....
....
....
....
Your Ionic app is ready! Follow these next steps:

- Go to your new project: cd .\temp-ionic6
- Run ionic serve within the app directory to see your app in the browser
- Run ionic cordova platform add to add a native iOS or Android project using Cordova
- Generate your app icon and splash screens using cordova-res
- Explore the Ionic docs for components, tutorials, and more: https://ion.link/docs
- Building an enterprise app? Ionic has Enterprise Support and Features: https://ion.link/enterprise-edition

$ ionic cordova platform add android
√ Creating .\www directory for you in 3.60ms
> cordova.cmd platform add android

You have been opted out of telemetry. To change this, run: cordova telemetry on.
Using cordova-fetch for cordova-android@^10.1.1
Adding android project...
Creating Cordova project for the Android platform:
        Path: platforms\android
        Package: io.ionic.starter
        Name: temp-ionic6
        Activity: MainActivity
        Android target: android-30
Subproject Path: CordovaLib
Subproject Path: app
Android project created with cordova-android@10.1.1
....
....
....
[cordova-res] Generated 18 resources for android
[cordova-res] Wrote to config.xml

$ionic cordova build android
> ng.cmd run app:ionic-cordova-build --platform=android
An unhandled exception occurred: Project target does not exist.
See "C:\Users\MOALAS~1\AppData\Local\Temp\ng-DDj9ln\angular-errors.log" for further details.
[ERROR] An error occurred while running subprocess ng.
```

### Code Reproduction URL

https://github.com/MoAsmar/temp-ionic6

### Ionic Info

```
Ionic:

   Ionic CLI                     : 6.18.2 (C:\Users\moalasmar\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.0.11
   @angular-devkit/build-angular : 13.2.6
   @angular-devkit/schematics    : 13.2.6
   @angular/cli                  : 13.2.6
   @ionic/angular-toolkit        : 6.1.0

Cordova:

   Cordova CLI       : 11.0.0
   Cordova Platforms : android 10.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 3 other plugins)

Utility:

   cordova-res : 0.15.4
   native-run  : 1.5.0

System:

   Android SDK Tools : 26.1.1 (C:\Users\moalasmar\AppData\Local\Android\Sdk)
   NodeJS            : v16.14.0 (C:\Program Files\nodejs\node.exe)
   npm               : 8.5.4
   OS                : Windows 10

```

**Comment by MoAsmar** [comment] 2022-03-15 10:03
After lots of research and trials, I found the solution with the help of those 2 guys: 
[@jwt02180](https://forum.ionicframework.com/u/jwt02180) from ionic Forums & [@kwiatko](https://stackoverflow.com/users/9398808/kwiatko) from StackOverflow.

Basically, Some configurations are messed up when building ionic cordova app from scratch using cli with initial configurations.

- **1st part of the solution**: https://stackoverflow.com/a/64404485/4086736

> The cause of the problem is the name of your default project and its builds. For some reason, Ionic has a problem in resolving it. I didn't find a direct answer in the [docs](https://ionicframework.com/docs/cli/configuration/), but using multi-project configuration seems to work. If you change your ionic.config.json to look like:
> 
> ```
> {
>   "defaultProject": "Angular7",
>   "projects": {
>     "Angular7": {
>       "name": "Angular7",
>       "integrations": {},
>       "type": "angular"
>     }
>   }
> }
> ```

Where "Angular7" is the project name, in my case "temp-ionic6"

- **2nd part of the solution:** https://forum.ionicframework.com/t/ionic-cordova-build-android-throwing-error-in-ionic-6-project/221213/2

> If you run this command: ng add @ionic/cordova-builders it should add the required builders that are missing from the angular.json file generated by the Ionic CLI.


**Be aware** that you might need to delete node_modules folder & package-lock.json before running the build command again, to make sure package json includes the updated project name. 

- **Results:**

I have created a separate branch for my reproduction repo with the fixed issue here [https://github.com/MoAsmar/temp-ionic6/tree/working-build](https://github.com/MoAsmar/temp-ionic6/tree/working-build)

All done, running `ionic cordova build android` now works perfectly, 
![image](https://user-images.githubusercontent.com/8542126/158353330-41cfb751-a914-4204-bef2-206a01942eec.png)

**NOTE:** 
if you face this error "> No usable Android build tools found. Highest 30.x installed version is 30.0.2; minimum version required is 30.0.3" after adding both fixes, then you should go to Android SDK and download the latest build-tools which is the minimum required 30.0.3 or above then update it in your environment variables.

**Lastly, this doesn't mean the bug is resolved, this is a manual fix & should be added to build config by ionic by default, this way we don't need to take these steps every time we create a new cordova-based ionic angular app to fix cordova build.**

**Comment by liamdebeasi** [comment] 2022-03-15 13:06
Hey there,

This is due to users needing to add the new `@ionic/cordova-builders` package if they are updating to `@ionic/angular-toolkit@6`. This is noted in the breaking changes log: https://github.com/ionic-team/angular-toolkit/releases/tag/%40ionic%2Fangular-toolkit%406.0.0 Developers upgrading their apps should take note of any changes in these logs when updating across major versions of this package

For new applications, developers can run `ng add @ionic/cordova-builders` as noted to resolve the issue. However, I agree that this should be done automatically when creating an app via the CLI. We have a new addition to the Ionic CLI coming soon that will automatically run `ng add @ionic/cordova-builders`. I am going to flag this PR with the team so we can increase its priority. 

I am going to close this as this is not a bug in Ionic Framework, but you can track progress on this new CLI feature here: https://github.com/ionic-team/ionic-cli/pull/4823. Thanks!

**Comment by liamdebeasi** [comment] 2022-03-15 13:07
There is also a new testing version of the CLI if you would like to give this change a try:

```
npm install -g @ionic/cli@testing
ionic start my-app tabs --type angular --cordova
```

**Closed by liamdebeasi** 2022-03-15 13:06 UTC
Labels: triage

**Comment by liamdebeasi** [comment] 2022-03-15 13:55
Ionic CLI v6.19.0 has been released with this fix:

```
npm install -g @ionic/cli@latest
```

**Comment by MoAsmar** [comment] 2022-03-15 18:14
I will try to uninstall ionic & install it again (latest & fresh), because the solution I tried and mentioned above breaks the ionic serve command and the error "Project does not exist" prompts again on serve !!

**Comment by raghav14** [comment] 2022-03-16 07:53
For me it got resolved only by just running `ng add @ionic/cordova-builders`. No need to change the `ionic.config.json`.
I'm using ionic/cli@5.4.16 and cordova 10. Thanks for the help everyone.

**Comment by Isaacn123** [comment] 2022-03-17 23:03
me am still getting  the error after doing all the above suggestions 
 ng run app:ionic-cordova-build --platform=android
An unhandled exception occurred: Project target does not exist.
See "/private/var/folders/zv/y54bkz192jvfltllwmhmrjp80000gn/T/ng-ku1K0T/angular-errors.log" for further details.
[ERROR] An error occurred while running subprocess ng.
        
        ng run app:ionic-cordova-build --platform=android exited with exit code
        127.

**Comment by MoAsmar** [comment] 2022-03-19 22:36
> me am still getting the error after doing all the above suggestions ng run app:ionic-cordova-build --platform=android An unhandled exception occurred: Project target does not exist. See "/private/var/folders/zv/y54bkz192jvfltllwmhmrjp80000gn/T/ng-ku1K0T/angular-errors.log" for further details. [ERROR] An error occurred while running subprocess ng.
> 
> ```
>     ng run app:ionic-cordova-build --platform=android exited with exit code
>     127.
> ```

Please run `ionic info` and past it here

**Comment by Isaacn123** [comment] 2022-03-20 08:58
Ionic:

   Ionic CLI                     : 6.19.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.6.11
   @angular-devkit/build-angular : 12.1.2
   @angular-devkit/schematics    : 12.1.2
   @angular/cli                  : 12.1.2
   @ionic/angular-toolkit        : 4.0.0

Cordova:

   Cordova CLI       : 11.0.0
   Cordova Platforms : android 10.1.1, ios 6.2.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 15 other plugins)

Utility:

   cordova-res (update available: 0.15.4) : 0.15.3
   native-run (update available: 1.5.0)   : 1.3.0

System:

   Android SDK Tools : 26.1.1 (/Users/nsambaisaac/Library/Android/sdk)
   ios-sim           : 8.0.2
   NodeJS            : v14.16.1 (/usr/local/bin/node)
   npm               : 6.14.12
   OS                : macOS Big Sur
   Xcode             : Xcode 12.2 Build version 12B45b

**Comment by Isaacn123** [comment] 2022-03-21 16:27
as you can see  project is up to date and also am using sdk as 30 
now am not sure what is causing this error.. but have found out that when i convert my project to using capacitor no errors  happen  i thick ionic team might have intensionary started disabling  Cordova. coz this is rare Error

**Comment by aaadipop** [comment] 2022-03-23 08:36
same here for ios

```
ionic info

Ionic:

   Ionic CLI                     : 6.19.0 (/opt/homebrew/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.12
   @angular-devkit/build-angular : 13.2.6
   @angular-devkit/schematics    : 13.2.6
   @angular/cli                  : 13.2.6
   @ionic/angular-toolkit        : 6.1.0

Cordova:

   Cordova CLI       : 11.0.0
   Cordova Platforms : ios 6.2.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 3 other plugins)

Utility:

   cordova-res (update available: 0.15.4) : 0.15.3
   native-run                             : 1.5.0

System:

   ios-deploy : 1.11.4
   ios-sim    : 8.0.2
   NodeJS     : v16.14.2 (/usr/local/bin/node)
   npm        : 8.5.5
   OS         : macOS Big Sur
   Xcode      : Xcode 13.2.1 Build version 13C100
```

**Comment by binaryops-wiebo** [comment] 2022-03-24 22:52
I encountered this error as well, on a new machine, new node install etc. The issue was that I did not have a global install of the Angular cli. The command to add the @ionic/cordova-builders failed when creating the project. I ran the command manually: npx ng add @ionic/cordova-builders. It modified the angular.json file to add the required Project targets. At that point everything built and ran fine.

**Comment by Isaacn123** [comment] 2022-03-24 23:00
hello @binaryops-wiebo  thanks . am going to try do that but had forced me to convert my entire project to Flutter cause this project has been working well for now 5 years with every year making updates to it but now suddenly am not able getting errors....

**Comment by Isaacn123** [comment] 2022-04-10 11:57
yah thanx @binaryops-wiebo  i tried to run ng add @ionic/cordova-builders and it fixed the problem installed the required builders that where  missing from the angular.json

**Comment by Isaacn123** [comment] 2022-04-10 11:57
yah thanx @binaryops-wiebo  i tried to run ng add @ionic/cordova-builders and it fixed the problem installed the required builders that where  missing from the angular.json

**Comment by Isaacn123** [comment] 2022-04-10 11:58
yah thanx @binaryops-wiebo  i tried to run ng add @ionic/cordova-builders and it fixed the problem installed the required builders that where  missing from the angular.json

**Comment by Isaacn123** [comment] 2022-04-10 14:33
but now am having white screen no errors  displayed in chrom dev-tools  APPComponent does not fire. 
any ides on this issue??
