### ISSUE TITLE
bug: Buttons in footer overlaps for a second inside modal when navigating using ion-nav

### ISSUE THREAD

**Issue by gcelestial24** [ionic-team/ionic-framework#25947] opened 2022-09-15 13:15 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

When navigating in modal, buttons with fill="clear" in the footer overlaps for a second before changing.

https://user-images.githubusercontent.com/55013017/190412559-dec89de7-5584-479f-972f-87c2f81207d7.mp4

### Expected Behavior

When navigating in modal, it should have the same behavior as when navigating in route.

https://user-images.githubusercontent.com/55013017/190412804-f1b958b5-22da-4061-b864-41b9944faabf.mp4

### Steps to Reproduce

- create a modal with navigation
- add button in footer with fill=clear
- current behavior should be observed

### Code Reproduction URL

https://github.com/gcelestial24/modal-routing-animation-bug

### Ionic Info

Ionic:

   Ionic CLI                     : 6.20.1
   Ionic Framework               : @ionic/angular 6.2.7
   @angular-devkit/build-angular : 14.2.2
   @angular-devkit/schematics    : 14.2.2
   @angular/cli                  : 14.2.2
   @ionic/angular-toolkit        : 6.1.0

Cordova:

   Cordova CLI       : 11.0.0
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : 0.15.4
   native-run  : 1.6.0

System:

   Android SDK Tools : 26.1.1 
   NodeJS            : v14.18.3
   npm               : 6.14.15
   OS                : Windows 10

### Additional Information

I believe this also happens with the default button but not that noticeable unless one is longer than the other.

I do not know if this is related https://github.com/ionic-team/ionic-framework/issues/25677 but it is the closest issue I can find that is the same as I am experiencing.

**Comment by liamdebeasi** [comment] 2022-09-15 13:49
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The reason why this is happening is the toolbar in the entering component inside of the modal does not have a background color. The `color` property on the toolbar is set to `white`, which is not a defined color in your application. As a result, the button in the leaving component will appear to overlap with the toolbar in the entering component.

This does not happen in your non-modal context because the toolbars all have background colors there. Perhaps you are missing the color definition for `white` or maybe you meant to use the `light` color instead? Ensuring that the toolbar has a background color should resolve this issue.

**Closed by liamdebeasi** 2022-09-15 13:49 UTC
Labels: triage

**Comment by gcelestial24** [comment] 2022-09-15 14:02
That fixes it thanks!!! I wonder where did I get that `white` color. I should read the documentation more 😅
