### ISSUE TITLE
bug: ion-button stays highlighted/selected when clicked

### ISSUE THREAD

**Issue by mobilemarines** [ionic-team/ionic-framework#23665] opened 2021-07-21 10:06 UTC
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

On an android device(tested on Android 9 so far), after clicking the ion-button, it stays highlighted. The effect seems to be the same like when hovering in the browser. Can´t really tell, as when inspecting the webview on the device, as soon as I select the ion-button in the dom, the effect disappears. So unforutnatelly I can´t see which classes are still applied on the button.
Was able to reproduce the issue with a blank template and only added an ion-button like below. Didn´t change any stylings.
The same issue also happened with ion-buttons in modals.

### Expected Behavior

The button should be highlighted for a moment as a user feedback, but then switch back to the default color.

### Steps to Reproduce

`<ion-header [translucent]="true">
  <ion-toolbar>
    <ion-button>Test</ion-button>
    <ion-title>
      Test
    </ion-title>
  </ion-toolbar>
</ion-header>`

### Code Reproduction URL

https://github.com/mobilemarines/ionButtonTest/tree/master

### Ionic Info

Ionic:

   Ionic CLI                     : 5.4.4 (C:\Users\vogt\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 5.6.11
   @angular-devkit/build-angular : 12.1.2
   @angular-devkit/schematics    : 12.1.2
   @angular/cli                  : 12.1.2
   @ionic/angular-toolkit        : 4.0.0

Utility:

   cordova-res : 0.15.3
   native-run  : 1.4.0

System:

   NodeJS : v12.18.2 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.5
   OS     : Windows 10

### Additional Information

{
  "name": "ionic-app-base",
  "version": "0.0.0",
  "author": "Ionic Framework",
  "homepage": "https://ionicframework.com/",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "~12.1.1",
    "@angular/compiler": "~12.1.1",
    "@angular/core": "~12.1.1",
    "@angular/forms": "~12.1.1",
    "@angular/platform-browser": "~12.1.1",
    "@angular/platform-browser-dynamic": "~12.1.1",
    "@angular/router": "~12.1.1",
    "@capacitor/android": "^3.1.1",
    "@capacitor/core": "3.1.1",
    "@ionic/angular": "^5.5.2",
    "rxjs": "~6.6.0",
    "tslib": "^2.2.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~12.1.1",
    "@angular-eslint/builder": "~12.0.0",
    "@angular-eslint/eslint-plugin": "~12.0.0",
    "@angular-eslint/eslint-plugin-template": "~12.0.0",
    "@angular-eslint/template-parser": "~12.0.0",
    "@angular/cli": "~12.1.1",
    "@angular/compiler": "~12.1.1",
    "@angular/compiler-cli": "~12.1.1",
    "@angular/language-service": "~12.0.1",
    "@capacitor/cli": "3.1.1",
    "@ionic/angular-toolkit": "^4.0.0",
    "@types/jasmine": "~3.6.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "@typescript-eslint/eslint-plugin": "4.16.1",
    "@typescript-eslint/parser": "4.16.1",
    "eslint": "^7.6.0",
    "eslint-plugin-import": "2.22.1",
    "eslint-plugin-jsdoc": "30.7.6",
    "eslint-plugin-prefer-arrow": "1.2.2",
    "jasmine-core": "~3.8.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~6.3.2",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "typescript": "~4.2.4"
  }
}

**Comment by mobilemarines** [comment] 2021-07-22 09:03
@liamdebeasi Added a github repo that reproduces the issue. Tanks for the fast response.
Best regards

**Comment by liamdebeasi** [comment] 2021-07-27 14:20
Thanks for the follow up. What version of the webview are you testing this on? You can find this out by logging `window.navigator.userAgent` to the console when inspecting the app.

**Comment by mobilemarines** [comment] 2021-07-27 14:48
I tested this on 2 devices up to now. One has the Chrome 92.0.4515.115 and the other device uses the Android System WebView 91.0.4472.164.

**Comment by liamdebeasi** [comment] 2021-07-27 14:52
Thanks! I tested this on my Android device and was unable to reproduce the issue. Can you clarify the steps to reproduce?

https://user-images.githubusercontent.com/2721089/127176283-2a93004e-dd4d-4278-8591-25b7702654d4.mp4

**Comment by mobilemarines** [comment] 2021-07-27 15:05
Oh I see. We build an app with ionic and capacitor. Our build steps are in the readme.md. So I guess there must be something mixed up after the android build.

**Comment by mobilemarines** [comment] 2021-07-27 15:13
Wanted to cancel a comment and accidently closed the issue. I´ll change the background to a darker blue qickly, so you can see the difference better on  screenshots.

**Comment by liamdebeasi** [comment] 2021-07-27 15:15
Let me check in Capacitor real quick. Maybe there is a difference between browser and webview.

**Comment by mobilemarines** [comment] 2021-07-27 15:19
Alright. Thanks for you help.

**Comment by liamdebeasi** [comment] 2021-07-27 15:30
Here is the app running in Capacitor and it seems to be working fine:
https://user-images.githubusercontent.com/2721089/127182564-47f2b9bd-38f0-4c20-bec7-fc6610013c82.mp4

I am running Chrome 92.0.4515.115. What devices have you tested this on? I am testing on a Pixel 4a.

**Comment by mobilemarines** [comment] 2021-07-27 15:48
My devices are a Xiaomi Mi A1 and a Xiaomi POCO X3 NFC. If you touch hold that button, you can see the button background will get slightly brighter. This effect stays there for me until I touch somewhere else on the screen. Even when I just click the button the brightend up button will stay like this. I´ll attach screenshots. One moment.

**Comment by mobilemarines** [comment] 2021-07-27 15:51
![ion_button_brighter](https://user-images.githubusercontent.com/50991581/127185948-f7b54ef2-f719-4bb6-8ca5-ccfe32fdbae6.png)
![ion_button_dark](https://user-images.githubusercontent.com/50991581/127185951-20285fdd-dc01-4013-9122-0a683f3c7163.png)

**Comment by liamdebeasi** [comment] 2021-07-27 15:57
It might be an issue with how the device dispatches touch events. Do you have any other Android devices you can test on?

**Comment by mobilemarines** [comment] 2021-07-27 16:01
Unfortunately not. I haven´t been able to reproduce this issue in the emulators. I will reach out to my colleagues tomorrow and will get back to you when I got more info or examples. Appreciate your help and your quick responses! Thanks!

**Comment by mobilemarines** [comment] 2021-07-29 08:54
Hi Liam. My colleague also has a Pixel, but as I wasn´t able to reproduce this in the emulator I guess it´s a manufacturer specific issue. Thanks for you help.

**Comment by liamdebeasi** [comment] 2021-08-02 13:20
Thanks for the follow up. You might want to consider opening an issue on the Chromium bug tracker: https://bugs.chromium.org/p/chromium/issues/list

Chromium is the engine that powers Google Chrome, so there may be a bug in Chromium that only reproduces on the types of device you are using.

I am going to close this for now since I am unable to reproduce the issue, but if you have additional info that lets us reproduce the issue on other devices feel free to follow up and I can take another look. Thanks!

**Closed by liamdebeasi** 2021-08-02 13:20 UTC
Labels: triage
