### ISSUE TITLE
bug: Disabling menu doesn't work since last npm update

### ISSUE THREAD

**Issue by telpat0298** [ionic-team/ionic-framework#28366] opened 2023-10-17 09:54 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Im using the `ion-menu` tag together with the `ion-menu-toggle` for the side menu in our application. On certain pages i don't want to display the menu and the menu toggle. Therefore I'm using the `MenuController` to enable/disable the menu programatically with `this.menu.enable(false, "main-menu");` inside the `ngInit` and `viewWillEnter` hooks. Since the last npm update disabling the menu with `this.menu.enable(false, "main-menu");` has no effect. The button is still visible and the menu can be swiped open. I've create [this](https://stackblitz.com/edit/ionic7-menu-issue) stackblitz to recreate the issue.

### Expected Behavior

The menu should not be swipable and the menu toggle should be hidden when disabled.

### Steps to Reproduce

[Stackblitz](https://stackblitz.com/edit/ionic7-menu-issue)

### Code Reproduction URL

[this](https://stackblitz.com/edit/ionic7-menu-issue)

### Ionic Info

Ionic:

   Ionic CLI                     : 7.1.1 (/opt/homebrew/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.5.0
   @angular-devkit/build-angular : 16.2.6
   @angular-devkit/schematics    : 16.2.6
   @angular/cli                  : 16.2.6
   @ionic/angular-toolkit        : 10.0.0

Capacitor:

   Capacitor CLI      : 5.5.0
   @capacitor/android : 5.5.0
   @capacitor/core    : 5.5.0
   @capacitor/ios     : 5.5.0

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.3

System:

   NodeJS : v18.17.0 (/opt/homebrew/Cellar/node@18/18.17.0/bin/node)
   npm    : 9.8.1
   OS     : macOS Unknown

**Comment by liamdebeasi** [comment] 2023-10-17 13:10
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/28337. The fix for this has been merged and will be available later this week. In the meantime, you can access the fix using a nightly build of Ionic: `npm install @ionic/angular@nightly`

**Closed by liamdebeasi** 2023-10-17 13:10 UTC
Labels: triage
