### ISSUE TITLE
bug: Angular ion-back-button goes to wrong route when routing to a page outside of the tabs routing module

### ISSUE THREAD

**Issue by hoi4** [ionic-team/ionic-framework#23218] opened 2021-04-21 12:46 UTC
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
Clicking the ion-back-button in the subpage of tab2 takes me back to tab1 instead of tab2. See video below.
Seems to be a regression of #17278.

https://user-images.githubusercontent.com/23243256/115555218-8dfbd480-a2af-11eb-9a2b-889a310ecdc3.mov

**Expected behavior:**
Clicking the ion-back-button should take me back to tab2

**Notes:**
- Routing of the subpage is done in the app routing module

[Repo to reproduce](https://github.com/hoi4/ion-back-button-issue)

**Ionic info:**
```
Ionic:

   Ionic CLI                     : 6.13.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.6.4
   @angular-devkit/build-angular : 0.1102.9
   @angular-devkit/schematics    : 11.2.9
   @angular/cli                  : 11.2.9
   @ionic/angular-toolkit        : 3.1.1

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v14.15.1 (/usr/local/Cellar/node@14/14.15.1/bin/node)
   npm    : 6.14.11
   OS     : macOS Big Sur
```

**Comment by liamdebeasi** [comment] 2021-04-21 13:18
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/19801.

I did some debugging and this does not seem be a regression of https://github.com/ionic-team/ionic-framework/issues/17278 as the code added for that issue is never triggered in your application. When the app goes to the tabs context, the primary outlet is going to redirect you back to `/tabs` which will redirect you to `/tabs/tab1`. We need to add additional logic to redirect you to the previously active tab.

**Closed by liamdebeasi** 2021-04-21 13:18 UTC
Labels: triage

**Comment by hoi4** [comment] 2021-04-22 15:21
@liamdebeasi Thank you! Is there a rough time estimate for this additional logic?
