### ISSUE TITLE
bug: keyboards event does not return exact keyCode or which 

### ISSUE THREAD

**Issue by indraraj26** [ionic-team/ionic-framework#22099] opened 2020-09-16 09:59 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

All it returns 229 for all key press and key: "Unidentified", I think it is related to browser engine.
I think it is related to https://bugs.chromium.org/p/chromium/issues/detail?id=935275

**Expected behavior:**

It should return exact keyCode or which 

**Steps to reproduce:**

**Related code:**

Repo: https://github.com/indraraj26/ionic5-starter-tabs-sidemenu/tree/keyboard-event

html 
```
	<ion-textarea (keyup)="onKeyUp($event.which)"></ion-textarea>
	<ion-textarea (keydown)="onKeyDown($event.which)"></ion-textarea>
	<ion-textarea (keypress)="onKeyPress($event.which)"></ion-textarea>
	<textarea (keypress)="onHtmlTextArea($event.which)"></textarea>
```
```
	@HostListener('keydown', ['$event']) onKeyup(event: any) {
		console.log(event, 'hostlistern');
		console.log(event.which, 'hostlistern');
	}

	onKeyUp(e) {
		console.log(e);
	}
	onKeyDown(e) {
		console.log(e);
	}
	onKeyPress(e) {
		console.log(e);
	}
	onHtmlTextArea(e) {
		console.log(e, 'htmltext');
	}
```
```
navigator.userAgent
"Mozilla/5.0 (Linux; Android 7.1.2; Redmi 4A Build/N2G47H; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/83.0.4103.106 Mobile Safari/537.36"
```

**Other information:**

**Ionic info:**

```
ionic info

Ionic:

   Ionic CLI                     : 6.11.0 (C:\Users\indra26\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.3.2
   @angular-devkit/build-angular : 0.1000.8
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : android 9.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 6 other plugins)

Utility:

   cordova-res : 0.15.1
   native-run  : 1.0.0

System:

   Android SDK Tools : 26.1.1 (C:\Users\indra26\AppData\Local\Android\Sdk)
   NodeJS            : v10.16.3 (C:\Program Files\nodejs\node.exe)
   npm               : 6.9.0
   OS                : Windows 10
```

**Comment by liamdebeasi** [comment] 2020-09-16 13:11
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The keyCode issue appears to be related to the Chromium issue as you suggested.

**Closed by liamdebeasi** 2020-09-16 13:11 UTC
Labels: triage

**Comment by sardhara-piyush** [comment] 2020-09-16 19:42
Hello @liamdebeasi 
Is there any other way to get mobile keyboard key name or keyCode in ionic ?

**Comment by liamdebeasi** [comment] 2020-09-17 17:21
This is a bug in Chromium, so there is nothing Ionic Framework can do to workaround it.

**Comment by sardhara-piyush** [comment] 2020-09-17 18:14
@liamdebeasi  Thanks for replay.
Let me try with safari browser and let you know is working on safari or not.
