### ISSUE TITLE
bug: ion-popover with property showBackdrop=false has still a backdrop

### ISSUE THREAD

**Issue by Floscho2402** [ionic-team/ionic-framework#25461] opened 2022-06-13 21:22 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

When creating an ion-popover with the property showBackdrop=false the page will still be covered by a backdrop. The backdrop is not visible, but when using the inspect mode you can see that the backdrop is still there. This blocks all clicks on the elements behind it.

### Expected Behavior

When setting showBackdrop=false I expect that there is no backdrop after opening the popover and other elements on the page are clickable.

### Steps to Reproduce

Just click on the button in the example and the popover will open.

### Code Reproduction URL

https://github.com/Floscho2402/ion-popover-backdrop-issue

### Ionic Info

Ionic:

   Ionic CLI                     : 6.18.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.1.9
   @angular-devkit/build-angular : 14.0.1
   @angular-devkit/schematics    : 14.0.1
   @angular/cli                  : 14.0.1
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.5.1
   @capacitor/android : not installed
   @capacitor/core    : 3.5.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.6.0

System:

   NodeJS : v16.13.0 (/usr/local/bin/node)
   npm    : 8.1.0
   OS     : macOS Monterey

**Comment by liamdebeasi** [comment] 2022-06-13 22:19
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The `showBackdrop` property is a bit confusing, but it controls whether or not the backdrop is visible. It does not control whether or not the backdrop is active/enabled.

The `showBackdrop` property is really geared towards developers who do not want the default screen darkening effect provided by the backdrop.

We do not recommend getting rid of the backdrop and allowing users to click behind the popover, but if you would like to do it, you can accomplish this using the following CSS:

```css
ion-popover {
  pointer-events: none;
}

ion-popover::part(content) {
  pointer-events: all;
}
```

Note: The CSS needs to be applied globally and cannot be scoped to your component.

-----

I do think the description for this property is a bit confusing, so I have created https://github.com/ionic-team/ionic-framework/pull/25462 to better describe what this property controls.

**Closed by liamdebeasi** 2022-06-13 22:19 UTC
Labels: triage
