### ISSUE TITLE
feat: ion-datetime: add picker style presentation that includes the day

### ISSUE THREAD

**Issue by cperez87** [ionic-team/ionic-framework#24942] opened 2022-03-15 19:40 UTC
**Ionic version:**

[x] **6.x**

**I'm submitting a ...** 

[ ] bug report
[x] feature request

**Describe the Feature Request**
The v4 & v5 datetime picker style had some advantages in terms of user experience over the new v6 datetime picker. The v6 style works great when the date you are trying to select in close to a known date (eg Todays date). The user only needs to select the date or move a few months. 
But for scenarios where a user needs to enter a Birth Date, Issue/Expiration date (like for passport), etc, where the year is too far back/future it requires more work.
- User must realize to click on month-year at the top to switch (instead of using the arrows)
- User must realize to click again on the month-year to go back to the days view

**Describe Alternative**
Picker style date input like in v5. Add a day-month-year presentation option.

**Comment by liamdebeasi** [comment] 2022-03-16 12:50
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/23981.

**Closed by liamdebeasi** 2022-03-16 12:50 UTC
Labels: triage
