### ISSUE TITLE
bug: tapping ion-back-button multiple times goes back multiple pages

### ISSUE THREAD

**Issue by Sjoerd** [ionic-team/ionic-framework#18455] opened 2019-06-04 09:58 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

If you tap twice at a back button (while there is no back button on the previous page), you go 2 pages back instead of one. 
**Expected behavior:**

Go one page back
**Steps to reproduce:**

Create a app with 3 screens, navigate to the thirth screen, add a back button there (`<ion-back-button />`), double tap it
**Related code:**

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.0.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.5.0-dev.201905231504.7ab9479
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 9.0.0
   Cordova Platforms : android 8.0.0, browser 6.0.0, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 7 other plugins)

Utility:

   cordova-res : 0.3.0
   native-run  : 0.2.2

System:

   Android SDK Tools : 26.1.1 (/usr/local/share/android-sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.1
   NodeJS            : v11.9.0 (/usr/local/bin/node)
   npm               : 6.9.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.2.1 Build version 10E1001
```

**Comment by leszekkadlof** [comment] 2019-06-05 05:29
This double-tap on any button is an issue - causes multiple click events to run which causes issues. 

Perhaps an optional directive on the button (or a global sass variable) can be considered to allowing user to disable multiple event calls when button is double-tapped or rapid tapped? 

It's too tedious to implement stop guards on every button across an entire application when most buttons are single click actions.

**Comment by dansiemens** [comment] 2019-06-06 22:40
Double tap also causing #18104

**Comment by brandyscarney** [comment] 2019-06-10 21:52
Thanks for the issue! Does this only happen on specific devices or can it be reproduced in Chrome?

**Comment by dansiemens** [comment] 2019-06-12 17:39
I've been able to consistently reproduce on both Android and iOS devices.

**Comment by Sjoerrdd** [comment] 2019-06-12 17:57
> Thanks for the issue! Does this only happen on specific devices or can it be reproduced in Chrome?

As far as I know only in iOS  and Android.

**Comment by alterhu2020** [comment] 2019-06-13 03:20
I met this issue for a long time , the <ion-page> had added the css class `.ion-page-invisible` when in the blank page, firstly I think the weird issue caused from our vue router navigation, until I search this issue and found it in this opened issue, please help it ,thanks very much.

**Comment by alterhu2020** [comment] 2019-06-23 08:04
@brandyscarney , I remove the code ` enteringEl.classList.add('ion-page', 'ion-page-invisible');`  in this file: https://github.com/ionic-team/ionic/blob/fa1317359a/vue/src/components/ion-vue-router.ts ,and it can prevent this issue.

**Comment by wilk-polarny** [comment] 2019-09-03 16:29
@brandyscarney , did you have a chance to look at this?
Also: Weird things happen if you double tap a back button with only one page in the history - this somehow messes up the navigation (with back buttons disappearing, tab bars freezing and not being able to navigate at all,...). Especially with route guards, which is another story.

**Comment by drewctate** [comment] 2020-02-19 02:46
Having the same issue as the original poster.

**Comment by drewctate** [comment] 2020-03-04 13:41
Well, until this is properly addressed, I've built a custom back-button component that prevents it. In case it's useful for others, I'll share the code.
## Usage
```html
<app-back-button backHref="/home"></app-back-button>
```

## Source Code
```ts
import { Component, Input } from '@angular/core';
import { NavController } from '@ionic/angular';

@Component({
  selector: 'app-back-button',
  templateUrl: './back-button.component.html'
})
export class BackButtonComponent {
  @Input() backHref: string;
  public buttonDisabled = false;

  constructor(private navCtrl: NavController) {}

  public async onClick (ev: Event) {
    if (!this.backHref) return;

    this.buttonDisabled = true;
    await this.navCtrl.navigateBack([this.backHref]);
    this.buttonDisabled = false;

    ev.preventDefault();
  }
}
```
```html
<ion-button [disabled]="buttonDisabled" (click)="onClick($event)">
  <ion-icon name="chevron-back-outline"></ion-icon>
  Back
</ion-button>
```

**Comment by jdlopezq** [comment] 2020-06-05 04:04
Hi i'm a similar behavior, on my app when you double click this button de navigation it's trigger twice, even if you click it 3 or 4 times it navigates back the same times as clicked, and when you don't have pages on the stack the button disappears, i'm kind of worry because this endanger the integrity of my app :( this can be duplicated on iOS ,android and with ionic serve on Chrome.

**Comment by drewctate** [comment] 2020-06-05 04:38
Hi @jdlopezq. I had the same situation, but I was able to fix the problem by building an identical custom component. See my comment above https://github.com/ionic-team/ionic/issues/18455#issuecomment-594528996

**Comment by austin43** [comment] 2020-07-13 16:52
This problem also exists on ionic/react.  I created a custom component similar to @drewctate to resolve this in the mean time.  

A few things to note:
* this will only work if your back button exists inside an IonPage
* it uses a different icon than IonBackButton, but I actually prefer it as it has a larger button area and looks better

```import React, { useState } from 'react'
import { IonButton, IonIcon, useIonViewDidEnter } from '@ionic/react'
import { useHistory } from 'react-router'
import { chevronBackOutline } from 'ionicons/icons'
import styles from './AppBackButton.module.scss'

export const AppBackButton: React.FC = () => {
	const [disabled, setDisabled] = useState(true)
	const history = useHistory()

	useIonViewDidEnter(() => {
		setDisabled(false)
	})

	const onClick = () => {
		setDisabled(true)
		if (!disabled) history.goBack()
	}

	return (
		<IonButton className={styles.button} onClick={onClick} disabled={disabled}>
			<IonIcon icon={chevronBackOutline} />
		</IonButton>
	)
}
```

**Comment by drewctate** [comment] 2020-07-13 21:18
@austin43 nice work!

**Comment by cmeuser** [comment] 2020-08-31 21:13
This problem still exists using Ionic/Angular.

**Comment by selected-pixel-jameson** [comment] 2020-09-01 12:55
Would really appreciate a fix for this as it's definitely going to cause issues.

**Comment by DexterHuang** [comment] 2020-10-03 11:07
the issue still exists, only happens when using native android

**Comment by codrodev** [comment] 2020-10-19 06:35
I solved this issue by setting the defaultHref attribute of the ion-back-button to =" " then added a [disabled]="flag". this flag will disable and enable the button on a (click) function and Voilà

backButtonDisabled = false;

<ion-back-button
	(click)="backButtonPressed()"
	[disabled]="backButtonDisabled"
	defaultHref=""
></ion-back-button>

backButtonPressed() {
	this.backButtonDisabled = true;
	this.navCntrl.navigateBack('/map');
}

**Comment by expcapitaldev** [comment] 2020-12-17 07:32
any updates?

**Comment by Chamiyalt** [comment] 2021-02-03 06:11
This issue still exists using Ionic 5.x

**Comment by kensodemann** [comment] 2021-06-01 19:51
@liamdebeasi - I have a sample repo that can repro this. Let me know if you need it and I will get it uploaded.

**Comment by ramseyfeng** [comment] 2021-06-07 03:30
Issue still exists on the latest ionic/angular.
Is there any update on this issue?
Or is there any suggested work round for this?

**Comment by ramseyfeng** [comment] 2021-06-07 06:40
My temporary solution before it got fixed:

Use `ion-button` instead of the `ion-back-button`

`<ion-button (click)="clickBackButton()">
  <ion-icon name="chevron-back" size="large"></ion-icon>
</ion-button>`

And in TS, use debounce for the navControl.back() method:

```
private navBack = debounce(() => {
    console.log('clickBackButton');
    this.navCtrl.back({
      animated: true,
      animationDirection: 'back',
    });
  }, 500);

clickBackButton() {
    this.navBack();
  }
```

**Comment by liamdebeasi** [comment] 2021-06-28 19:03
Hi everyone,

We appreciate your patience as we work to resolve this issue. Can everyone try the following dev build and let me know if it resolves the issue?

**Angular**
```
npm install @ionic/angular@5.7.0-dev.202106281826.d4f4f3f
```

**React**
```
npm install @ionic/react@5.7.0-dev.202106281826.d4f4f3f @ionic/react-router@5.7.0-dev.202106281826.d4f4f3f
```

**Vue**
```
npm install @ionic/vue@5.7.0-dev.202106281826.d4f4f3f @ionic/vue-router@5.7.0-dev.202106281826.d4f4f3f
```

**Stencil/Vanilla JavaScript**
```
npm install @ionic/core@5.7.0-dev.202106281826.d4f4f3f
```

**Comment by ramseyfeng** [comment] 2021-06-30 01:58
@liamdebeasi I just tried the angular version, it got fixed! 👍

**Comment by liamdebeasi** [comment] 2021-07-01 14:44
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/23526, and a fix will be available in an upcoming release of Ionic Framework.

**Closed** 2021-07-01 14:44 UTC
Labels: package: core, type: bug

**Comment by andrewctate** [comment] 2021-07-01 18:46
cc: @gshigeto
