### ISSUE TITLE
 bug: changing months on datetime jumps by 2 months

### ISSUE THREAD

**Issue by bipin-52165** [ionic-team/ionic-framework#25608] opened 2022-07-11 14:57 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

The user opens the ion-datetime in a modal, tap the next and previous buttons (< and >) and occasionally a month is skipped when these buttons are tapped. And also does on swipe left/right too

### Expected Behavior

It should jump to 1 month only instead of two month

### Steps to Reproduce

Open any ion-datetime with at least presentation="date". Click the next (>) or back (<) buttons. Observe the months changing. It even happens in the emulator of https://ionicframework.com/docs/api/datetime example.

### Code Reproduction URL

https://ionicframework.com/docs/api/datetime

### Ionic Info

Ionic:

   Ionic CLI                     : 6.20.1 (/home/dell/.npm-global/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.12
   @angular-devkit/build-angular : 13.2.6
   @angular-devkit/schematics    : 13.2.6
   @angular/cli                  : 13.2.6
   @ionic/angular-toolkit        : 6.1.0

Cordova:

   Cordova CLI       : 11.0.0
   Cordova Platforms : android 10.1.2
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 7 other plugins)

Utility:

   cordova-res                          : not installed globally
   native-run (update available: 1.6.0) : 1.5.0

System:

   Android SDK Tools : 26.1.1 (/home/dell/Android/Sdk)
   NodeJS            : v14.20.0 (/usr/bin/node)
   npm               : 6.14.5
   OS                : Linux 4.15

**Comment by liamdebeasi** [comment] 2022-07-12 13:16
Thanks for the issue. Does this only happen when using a datetime in a modal?

**Comment by bipin-52165** [comment] 2022-07-12 13:25
> Thanks for the issue. Does this only happen when using a datetime in a modal?

It happened with and without modal

**Comment by liamdebeasi** [comment] 2022-07-12 13:26
Thanks. What browser and operating system are you testing on? I am testing in Chrome on macOS and I cannot reproduce this behavior.

**Comment by liamdebeasi** [comment] 2022-07-12 13:30
Can you send a screen recording of the issue happening?

**Comment by KANekT** [comment] 2022-07-13 06:41
https://user-images.githubusercontent.com/580273/178667651-724e5c53-f220-4b81-8231-d3dcc3cd7b13.mp4

firefox 102 windows 10 utc +3 Moskow

**Comment by liamdebeasi** [comment] 2022-07-13 13:21
Thanks. If you have a project to test with, you can give `6.1.14-dev.11657300607.18e0f2d1` a try. It looks like the PR in https://github.com/ionic-team/ionic-framework/pull/25586 may fix the issue.

**Comment by eeschiavo** [comment] 2022-07-15 08:34
Same problem here. I just tried `6.1.14-dev.11657300607.18e0f2d1` and can confirm it works correctly.

**Comment by liamdebeasi** [comment] 2022-07-15 18:58
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/25586, and a fix will be available in an upcoming release of Ionic Framework.

**Closed** 2022-07-15 18:58 UTC
Labels: triage
