### ISSUE TITLE
bug: Clicking button in ion-item causes ion-input to focus on iPhone

### ISSUE THREAD

**Issue by michaelmesser** [ionic-team/ionic-framework#21790] opened 2020-07-21 19:29 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x** with React

**Current behavior:**
Clicking the button brings the up the keyboard but hitting the keys does not work

**Expected behavior:**
Clicking the button does not bring up the keyboard

**Steps to reproduce:**
```html
<IonList className="results">
              <IonItem>
                <IonLabel class="ion-text-wrap" style={{ maxWidth: "none" }}>
                  Test
                  <p>123456</p>
                </IonLabel>
                <IonNote color="primary" slot="end">
                  <IonButton>
                    <IonIcon icon={removeOutline} />
                  </IonButton>
                  <IonInput
                    inputMode="decimal"
                    value="1"
                    type="number"
                    step="1"
                    min="0"
                    style={{
                      display: "inline-block",
                      width: "30px",
                      height: "100%",
                      textAlign: "right",
                    }}
                  />
                  <IonButton>
                    <IonIcon icon={addOutline} />
                  </IonButton>
                </IonNote>
              </IonItem>
</IonList>
```

**Related code:**

https://stackblitz.com/edit/react-xbcmhe

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.10.1 (C:\Users\michaelmesser\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/react 5.2.3

Capacitor:

   Capacitor CLI   : 2.2.1
   @capacitor/core : 2.2.1

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.17.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.4
   OS     : Windows 10

```

**Comment by liamdebeasi** [comment] 2020-07-22 00:57
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/21509.

**Closed by liamdebeasi** 2020-07-22 00:57 UTC
Labels: triage
