### ISSUE TITLE
bug: datetime previous / next month button trigger's twice

### ISSUE THREAD

**Issue by mread1208** [ionic-team/ionic-framework#24724] opened 2022-02-04 22:07 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

When you try and navigate between "previous" and "next" months, the calendar event triggers twice.  For example: If I'm on February and I select the "Next" arrow (>), instead of being taken to "March" I'm shown "April".  The issue also happens with the "Previous" button where if I'm on February, and I click the "Previous" arrow (<), I should be taken to January 2022, but I'm instead taken to December 2021.

If I roll back to `@ionic/angular: "6.0.0"`, the issue goes away, but as soon as I bump past `@ionic/angular: "6.0.1"` the issue shows up again.  Looks to be something introduced around that time (as that's when ionic core version was bumped to 6.0.5).

### Expected Behavior

Clicking on the Previous / Next arrows should only navigate a single month instead of double.

### Steps to Reproduce

You can see this very issue on the Ionic Framework Docs page by clicking on the previous / next arrows on any of the examples: https://ionicframework.com/docs/api/datetime.  I also created a Stackblitz below.

### Code Reproduction URL

I created a StackBlitz using Angular 13 with `@ionic/angular: "6.0.1"` that highlights the issue. 

- [Code URL](https://stackblitz.com/edit/angular-ivy-49scux?file=src/app/app.component.html)
- [Working Example](https://angular-ivy-49scux.stackblitz.io)

I also have a working StackBlitz using Angular 13 with `@ionic/angular: "6.0.0"`

- [Code URL](https://stackblitz.com/edit/angular-ivy-965724)
- [Working Example](https://angular-ivy-965724.stackblitz.io)

### Ionic Info

Ionic:

   Ionic CLI                     : 6.18.1
   Ionic Framework               : @ionic/angular 6.0.5
   @angular-devkit/build-angular : 13.2.2
   @angular-devkit/schematics    : 13.2.2
   @angular/cli                  : 13.2.2
   @ionic/angular-toolkit        : 6.0.0

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : android 9.1.0, ios 6.2.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 17 other plugins)

Utility:

   cordova-res (update available: 0.15.4) : 0.15.3
   native-run (update available: 1.5.0)   : 0.2.9

System:

   Android SDK Tools : 26.1.1
   ios-deploy        : 1.10.0
   ios-sim           : 8.0.2
   NodeJS            : v14.17.5
   npm               : 7.22.0
   OS                : macOS Catalina
   Xcode             : Xcode 11.3.1 Build version 11C504

**Comment by amandaesmith3** [comment] 2022-02-07 15:05
Thanks for the issue. I'm going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/24712. This has been resolved with https://github.com/ionic-team/ionic-framework/pull/24713 and the fix will be available in the next Ionic release. In the meantime, you can downgrade to Ionic 6.0.4 as a workaround.

**Closed by amandaesmith3** 2022-02-07 15:05 UTC
Labels: triage

**Comment by pioneersingh321** [comment] 2022-02-08 09:00
how can we downgrade to 6.0.4 version ?

**Comment by amandaesmith3** [comment] 2022-02-08 14:54
Yup, exactly 👍

**Comment by mread1208** [comment] 2022-02-08 16:28
Yes, that will do the trick, but I noticed this issue happening on `6.0.1`, `6.0.2`, `6.0.3` and `6.0.4`... I actually had to roll mine back all the way to `6.0.0`:

`npm install @ionic/angular@6.0.0`
