### ISSUE TITLE
bug: angular standalone form control inputs not being proxied

### ISSUE THREAD

**Issue by van9petryk** [ionic-team/ionic-framework#28431] opened 2023-10-30 07:42 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x, Nightly

### Current Behavior

`labelPlacement="floating"` or `labelPlacement="stacked"`
not work in standalone starter project

Maybe some problems with styles in starter template, don't know.

### Expected Behavior

Should work like described in doc

### Steps to Reproduce

Create starter project and copy this example
https://ionicframework.com/docs/api/input#label-placement

### Code Reproduction URL

https://github.com/van9petryk/two-input.git

### Ionic Info

 Ionic CLI                     : 7.1.1
   Ionic Framework               : @ionic/angular 7.5.3-dev.11698340692.18daff2f
   @angular-devkit/build-angular : 16.2.8
   @angular-devkit/schematics    : 16.2.8
   @angular/cli                  : 16.2.8
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.5.1
   @capacitor/android : 5.5.1
   @capacitor/core    : 5.5.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.4

### Additional Information
Link to stackblitz, but it won't start on stackblitz
https://stackblitz.com/edit/github-p1koog

**Comment by liamdebeasi** [comment] 2023-10-30 16:55
Thanks for the report. I can reproduce this. It looks like inputs aren't being proxied to the underlying control. I'll take a closer look.

**Comment by liamdebeasi** [comment] 2023-10-30 19:29
Here's a dev build if you are interested in testing the proposed fix:

```
npm install @ionic/angular@7.5.3-dev.11698693746.12de705e
```

**Comment by ntorrey** [comment] 2023-10-30 19:40
Thank you! The input labels seem to be working better for me. However, I have an `<ion-datetime [preferWheel]="true">` component which now displays correctly (before it would show the normal datepicker), but the dates are still not selectable for some reason. Not sure if it's the same issue or another one.

**Comment by liamdebeasi** [comment] 2023-10-30 19:44
I tried your reproduction from https://github.com/ionic-team/ionic-framework/issues/28429 with the dev build, and I'm able to select dates:

https://github.com/ionic-team/ionic-framework/assets/2721089/1152d3f7-8bb8-450b-8441-bd92d3ee7754

**Comment by ntorrey** [comment] 2023-10-30 20:10
Now that I'm trying to update to the dev build in my reproduction app, I'm getting `500 Internal Server Error - GET https://registry.npmjs.org/@ionic%2fangular - KV GET failed: 401 Unauthorized`
Hopefully it's just a temporary error. 
As soon as it's back up and running I will try reproducing it in a modal (which is where it's not working for me in a different app).

**Comment by liamdebeasi** [comment] 2023-10-30 20:19
Yeah looks like there's an NPM outage: https://status.npmjs.org/incidents/zdznxkrp22py

**Comment by liamdebeasi** [comment] 2023-10-30 20:50
This appears to be a separate issue.

**Comment by liamdebeasi** [comment] 2023-10-31 18:29
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/28434, and a fix will be available in an upcoming release of Ionic Framework.

**Closed** 2023-10-31 18:28 UTC
Labels: package: angular, type: bug
