### ISSUE TITLE
bug: normalize css does not account for buttons

### ISSUE THREAD

**Issue by josh-byster** [ionic-team/ionic-framework#23928] opened 2021-09-15 04:03 UTC
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Hi, something I noticed is that the CSS normalize does not zero-out padding defined for buttons. WebKit defines [different padding rules](https://trac.webkit.org/browser/trunk/Source/WebCore/css/html.css#L831) in the user agent stylesheet depending on whether the app is running natively on iOS.

```
831 #if !(defined(WTF_PLATFORM_IOS_FAMILY) && WTF_PLATFORM_IOS_FAMILY)
832	    color: ButtonText;
833	    padding: 2px 6px 3px 6px;
834	    border: 2px outset ButtonFace;
835	    background-color: ButtonFace;
836	#else
837	    padding: 0 1.0em;
838	    border: 1px solid -webkit-control-background;
839	    font: 11px system-ui;
840	    background-color: -apple-system-opaque-secondary-fill;
841	    color: -apple-system-blue;
842	#endif
```

This is a bit difficult to debug, since neither responsive design mode on Safari nor Chrome's emulator will exercise the `else` code-path. The only way to see it is actually running on an iOS device / simulator.

### Describe the Use Case

This would help with debugging, as we wouldn't need to rely on the user agent stylesheet conditionals to ensure our button sizes will not differ (if not using a native `IonButton`).

### Describe Preferred Solution

I suggest setting `padding: 0` in `normalize.css` for buttons, perhaps with more specificity than just this.

### Additional Information

![image](https://user-images.githubusercontent.com/8664074/133368643-561b09d2-ec26-40d0-b896-0f454f380a84.png)
![image](https://user-images.githubusercontent.com/8664074/133368664-30cfaaab-6cf2-4a2b-80b7-6e8af5ca415d.png)

These two screenshots are from Web Inspector, the former in the browser, and the latter attached to my native iOS device. We can see the fallback to the webkit user agent stylesheet in the case of a `<button>`.

**Comment by liamdebeasi** [comment] 2021-09-15 13:56
Thanks for the issue. Can you provide a code example to help me reproduce this behavior?

**Comment by josh-byster** [comment] 2021-09-16 03:27
Sure thing, thanks for the response! In a blank ionic project, take the following example of HTML:

```
<div>
  <button>1</button>
  <button>2</button>
  <button>3</button>
  <button>4</button>
  <button>5</button>
</div>
```

And the following CSS:

```
button {
  width: 75px;
  font-size: 50px;
  display: inline-block;
}
```
In Chrome dev tools (same in Safari), if we try to emulate iPhone X, we see the following 5 buttons as rectangles fitting on one line (5x 75px buttons in a 375px width screen):
![image](https://user-images.githubusercontent.com/8664074/133544159-bea4bbca-e1e6-4ef1-aa0a-3996bf26685d.png)

However on the native iPhone, we see:
![IMG_6348](https://user-images.githubusercontent.com/8664074/133544385-706b5122-55bd-4d17-b75a-ffb7b9f7fc6e.PNG)

So both color and button width are different. When running on iPhone, it's `1em` padding; when not, it's `6px` horizontal padding. 
 
I think if the normalization set defaults for these cases, we would have consistency and wouldn't fall back to the user agent stylesheet, which has some native case switching as described above.

**Comment by liamdebeasi** [comment] 2021-09-20 15:57
Thanks. Looks like the basis for our normalize styles is a project that is no longer maintained (https://github.com/necolas/normalize.css), but I think this is something worthwhile adding.

**Comment by liamdebeasi** [comment] 2021-09-20 16:02
I am going to add the `help wanted` label since I think this is a great issue for community members looking to contribute to Ionic.

In terms of what needs to get fixed, we need to add a padding to: https://github.com/ionic-team/ionic-framework/blob/main/core/src/css/normalize.scss#L164

This would be adding opinionated styles to the `button` element, but Ionic itself is an opinionated platform with our own `ion-button` component. Also I think having consistency across platforms is more important than avoiding an opinionated style here.

**Comment by MaximPVladimirovich** [comment] 2022-10-24 15:11
I would like to try to fix the issue and submit a pr for this.

**Comment by liamdebeasi** [comment] 2022-11-18 18:57
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/26214, and a fix will be available in an upcoming release of Ionic Framework.

**Closed** 2022-11-18 18:57 UTC
Labels: help wanted, package: core, type: bug
