### ISSUE TITLE
bug: ion-select does not render default value if `value` (or `ngModel`) are initialized before ion-select-option

### ISSUE THREAD

**Issue by RangerRick** [ionic-team/ionic-framework#22103] opened 2020-09-17 00:20 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x** (Angular)

**Current behavior:**
`<ion-select>` will not display the currently selected value if `value=""` or `[(ngModel)]=` are initialized _before_ the list of `<ion-select-option>` tags that contain the selected value.

See [this imgur](https://imgur.com/cY1bQiT) for a visual of the behavior.

**Expected behavior:**
The select would show "Seattle Garages" once all the promises are resolved.

**Steps to reproduce:**

Here is a basic stackblitz of what's happening (in Tab 1):

https://stackblitz.com/edit/ionic-v5-ion-select-initialization

**Other information:**
In the process of making that stackblitz, I figured out what was going on.  If the `teams` property (which is iterated over to create the `<ion-select-option>` entries) is initialized from a promise _after_ the `ngModel` gets set, the default value never shows.

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.11.8 (/Users/ranger/.fnm/node-versions/v10.16.0/installation/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.3.2
   @angular-devkit/build-angular : 0.1001.1
   @angular-devkit/schematics    : 10.0.7
   @angular/cli                  : 10.1.1
   @ionic/angular-toolkit        : 2.3.3

Capacitor:

   Capacitor CLI   : 2.4.1
   @capacitor/core : 2.4.1

Utility:

   cordova-res : 0.15.1
   native-run  : not installed

System:

   NodeJS : v10.16.0 (/Users/ranger/.fnm/node-versions/v10.16.0/installation/bin/node)
   npm    : 6.14.8
   OS     : macOS Catalina
```

**Comment by liamdebeasi** [comment] 2020-09-17 13:13
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/19324 (same underlying issue).

**Closed by liamdebeasi** 2020-09-17 13:13 UTC
Labels: triage
