### ISSUE TITLE
bug: transition configuration not working on ionic/vue

### ISSUE THREAD

**Issue by florian72810** [ionic-team/ionic-framework#23265] opened 2021-05-04 10:11 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
I want to configure a specific animation on modalEnter / modalLeave, loadingEnter / loadingLeave, etc.
It does not work and trigger an error `Cannot read property 'enteringEl' of undefined`

**Expected behavior:**
The animation works and does not trigger error.

**Steps to reproduce:**

Ionic Starter blank with example for modal, loading and Action Sheet: [https://github.com/florian72810/ionic-starter-blank-vue-transition](https://github.com/florian72810/ionic-starter-blank-vue-transition)

**Related code:**

The error happens if I set the configuration globally or in the constructor.

**Global configuration**

```
const app = createApp(App)
  .use(IonicVue, {
    navAnimation: iosTransitionAnimation,
    actionSheetEnter: iosTransitionAnimation,
    actionSheetLeave: iosTransitionAnimation,
    alertEnter: iosTransitionAnimation,
    alertLeave: iosTransitionAnimation,
    loadingEnter: iosTransitionAnimation,
    loadingLeave: iosTransitionAnimation,
    modalEnter: iosTransitionAnimation,
    modalLeave: iosTransitionAnimation,
    pickerEnter: iosTransitionAnimation,
    pickerLeave: iosTransitionAnimation,
    popoverEnter: iosTransitionAnimation,
    popoverLeave: iosTransitionAnimation,
    toastEnter: iosTransitionAnimation,
    toastLeave: iosTransitionAnimation
  })
  .use(router);
```

**Constructor**

```
modalController.create({
  component: ExampleModalVue,
  enterAnimation: iosTransitionAnimation,
  leaveAnimation: iosTransitionAnimation
}).then(modal => modal.present());
```

**Other information:**

I did not tried everything but I suspect no transition is working: actionSheetEnter, actionSheetLeave, alertEnter, alertLeave, loadingEnter, loadingLeave, modalEnter, modalLeave, pickerEnter, pickerLeave, popoverEnter, popoverLeave, toastEnter, toastLeave.

The global configuration for "navAnimation" configuration does work as expected (for page transition forward/back)

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.12.3 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 5.6.6

Capacitor:

   Capacitor CLI   : 2.4.7
   @capacitor/core : 2.4.7

Utility:

   cordova-res : not installed
   native-run  : 1.3.0

System:

   NodeJS : v14.15.4 (/Users/foxer/.nvm/versions/node/v14.15.4/bin/node)
   npm    : 6.14.10
   OS     : macOS Big Sur
```

**Comment by liamdebeasi** [comment] 2021-05-04 14:41
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The `iosTransitionAnimation` is for page transitions, not for transitions on overlay components. The animation is not working for things like modals or toasts because they are overlay components.

**Closed by liamdebeasi** 2021-05-04 14:41 UTC
Labels: triage
