### ISSUE TITLE
bug: ion-refresher overscoll on iOS

### ISSUE THREAD

**Issue by benthieu** [ionic-team/ionic-framework#22013] opened 2020-08-31 14:28 UTC
# Bug Report

The ion-refresher does not work properly under iOS. When the refresher is visible and the content is scrolled, the content has a padding top and is not properly resized, which makes some content on the bottom not visible.

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
![Screenrecording iOS](https://github.com/benthieu/ionic-refresher-ios-bug/raw/master/readme_resource/bug_ios_11x414.gif)

**Expected behavior:**
Content size should be resized, and content on the bottom should not be cut, while the refresher is active.

**Steps to reproduce:**
Create a new ionic starter. Insert an ion-refresher in a page.

**Related code:**
[Link to repository](https://github.com/benthieu/ionic-refresher-ios-bug)

```html
<ion-content>
  <ion-refresher slot="fixed" (ionRefresh)="refresh($event)">
    <ion-refresher-content></ion-refresher-content>
  </ion-refresher>
  <p>
    ...
  </p>
</ion-content>
```
```typescript
public refresh(event: any): void {
  window.setTimeout(() => {
    if (event && event.target) {
      event.target.complete();
    }
  }, 5000);
}
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.11.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.3.2
   @angular-devkit/build-angular : 0.1000.8
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : 9.0.3 (cordova-lib@9.0.2)
   Cordova Platforms : ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 4 other plugins)

Utility:

   cordova-res : 0.15.1
   native-run  : 1.0.0

System:

   Android SDK Tools : 26.1.1 (/Users/.../Library/Android/sdk)
   ios-deploy        : 1.10.0
   ios-sim           : 8.0.2
   NodeJS            : v10.15.3 (/usr/local/bin/node)
   npm               : 6.14.8
   OS                : macOS Catalina
   Xcode             : Xcode 11.6 Build version 11E708
```

**Comment by liamdebeasi** [comment] 2020-08-31 14:44
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/21328.

**Closed by liamdebeasi** 2020-08-31 14:44 UTC
Labels: triage

**Comment by indraraj26** [comment] 2020-09-01 16:11
Please provide some workaround ?

**Comment by benthieu** [comment] 2020-09-01 16:24
@indraraj26 there is no workaround. Just follow and watch this issue https://github.com/ionic-team/ionic-framework/issues/21328
and wait for it to be resolved

**Comment by indraraj26** [comment] 2020-09-02 04:41
It's been 3 months i don't know how enterprise application will live with these kind of bugs, There are more than 200 bugs which needs to be align and solve. For me it's look like i should go back to ionic 3, ionic 3 was much more stable than ionic 4 and 5 except it does not have that much component and it can be done with css.
