### ISSUE TITLE
bug: [ionic-react] React lifecycle hooks not rerun on array "deps" changes

### ISSUE THREAD

**Issue by edolix** [ionic-team/ionic-framework#21792] opened 2020-07-22 09:49 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

Following [React LifeCycle Methods](https://ionicframework.com/docs/react/lifecycle#react-lifecycle-methods) it seems we should use `useIonViewWillEnter` instead of `useEffect` in a React FC. 
In a IonPage i need to set some deps to `useEffect` in order to dispatch side effects (base on Redux state updates).

Passing the second argument (`deps?: any[]`) to any of the _useIonView*_ hooks do not re-run the LifeCycleCallback function.

**Expected behavior:**

I'd expect the `LifeCycleCallback` to re-run when one of the dependencies value change in the FC. Using `useEffect` works as expected **but** (ref [the blog post](https://ionicframework.com/docs/react/lifecycle#react-lifecycle-methods)) Ionic will take the IonPage in the background so the `useEffect` callback will be executed even after the user navigates to other views because - for React - the component is still mounted. This would create unexpected side effects between different IonPage that are using Redux `useSelector` to trigger its own `useEffect` callbacks.

**Steps to reproduce:**

**Related code:**
Sample stackblitz - see the console logs for `useIonViewWillEnter` vs `useEffect`

https://stackblitz.com/edit/ionic-react-loading-96xecj?file=LoadingPage.jsx

```
  const [value, setValue] = useState('');

  useIonViewWillEnter(() => {
    console.log('useIonViewWillEnter: value is:', value)
  }, [value])

  useEffect(() => {
    console.log('useEffect: value is:', value)
  }, [value])
```

**Other information:**

I'm not sure if this will be considered as a bug or not but - from the @ionic-react types i saw the `deps` array so i think there should be a way to force a re-run of these hooks.

```ts
import { LifeCycleCallback } from '../contexts/IonLifeCycleContext';
export declare const useIonViewWillEnter: (callback: LifeCycleCallback, deps?: any[]) => void;
export declare const useIonViewDidEnter: (callback: LifeCycleCallback, deps?: any[]) => void;
export declare const useIonViewWillLeave: (callback: LifeCycleCallback, deps?: any[]) => void;
export declare const useIonViewDidLeave: (callback: LifeCycleCallback, deps?: any[]) => void;
```

Thanks!

**Comment by liamdebeasi** [comment] 2020-07-22 15:14
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. If you want a hook to fire when `value` is changed, you should stick with just `useEffect`. Lifecycle hooks such as `useIonViewWillEnter` are designed to only run once when a view has transitioned.

**Closed by liamdebeasi** 2020-07-22 15:14 UTC
Labels: triage

**Comment by edolix** [comment] 2020-07-22 15:34
Thanks @liamdebeasi - I'm having side effects when the IonPage with `useEffect` is hidden (=> it should be destroyed but Ionic keeps it for transitions and state management).
Have you any suggestions as workaround in Ionic? I can use a boolean state variable to track if the page is "active" or not but seems like an hack (?)
Thanks again!

**Comment by liamdebeasi** [comment] 2020-07-22 15:40
Can you update your StackBlitz to show me the issue you are running into? I can probably provide better advice once I can see the issue.

**Comment by edolix** [comment] 2020-07-29 13:53
Sorry the delay @liamdebeasi - i'll try to provide you a new StackBlitz with the issue.
Thanks again for now 👍
