### ISSUE TITLE
bug(item-sliding): methods not available on ion-item-sliding for Vue

### ISSUE THREAD

**Issue by loyaj** [ionic-team/ionic-framework#27412] opened 2023-05-06 23:55 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v6.x, v7.x

### Current Behavior

The methods (including `open` and `close`) are not available on the template ref of the `ion-item-sliding` component. Calling either of these methods (eg. from button handlers) logs an error to the browser's js console rather than having the intended effect (e.g. opening or closing the sliding item).

Furthermore, it appears that the only keys available on the template ref are `disabled`, `ionDrag`, and `routerLink`.

### Expected Behavior

The [ionic documentation for ion-item-sliding](https://ionicframework.com/docs/api/item-sliding#methods) lists `open` and `close` among the available methods. After binding a template ref to an IonItemSliding component, calling `open` should programmatically slide the item to expose the sliding item options, and calling `close` should return the sliding item to the initial state, hiding the options.

I would expect all methods in the documentation to be available, including `open`, `close`, `closeOpened`, `getOpenAmount`, and `getSlidingRatio`.

### Steps to Reproduce

1. `npm install`
2. `npm run dev`
3. Browse to the URL served by vite
   * The UI consists of a sliding item and two buttons: one for opening the sliding item and one for closing it.
4. Click the "Open sliding item" button
5. Observe that the sliding item does not open.
   * Open the browser developer tools console and notice the error logged there:
     `ionItemSlidingRef.value.open is not a function`
6. Manually slide the item open using your pointing device
7. Click the "Close sliding item" button
8. Observe that the sliding item does not close.
   * In the browser developer tools console, notice the error logged there:
     `ionItemSlidingRef.value.close is not a function`

### Code Reproduction URL

https://github.com/loyaj/ion-item-sliding-open-repro

### Ionic Info

[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package.json'

       Require stack:
       - /Users/schwa/.nvm/versions/node/v18.15.0/lib/node_modules/@ionic/cli/lib/project/index.js
       - /Users/schwa/.nvm/versions/node/v18.15.0/lib/node_modules/@ionic/cli/lib/index.js
       - /Users/schwa/.nvm/versions/node/v18.15.0/lib/node_modules/@ionic/cli/index.js
       - /Users/schwa/.nvm/versions/node/v18.15.0/lib/node_modules/@ionic/cli/bin/ionic
[WARN] Error loading @capacitor/android package.json: Error: Cannot find module '@capacitor/android/package.json'

       Require stack:
       - /Users/schwa/.nvm/versions/node/v18.15.0/lib/node_modules/@ionic/cli/lib/project/index.js
       - /Users/schwa/.nvm/versions/node/v18.15.0/lib/node_modules/@ionic/cli/lib/index.js
       - /Users/schwa/.nvm/versions/node/v18.15.0/lib/node_modules/@ionic/cli/index.js
       - /Users/schwa/.nvm/versions/node/v18.15.0/lib/node_modules/@ionic/cli/bin/ionic

Ionic:

   Ionic CLI       : 7.1.1 (/Users/schwa/.nvm/versions/node/v18.15.0/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 7.0.5

Capacitor:

   Capacitor CLI      : 5.0.1
   @capacitor/android : not installed
   @capacitor/core    : 5.0.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v18.15.0 (/Users/schwa/.nvm/versions/node/v18.15.0/bin/node)
   npm    : 9.5.0
   OS     : macOS Monterey

### Additional Information

Reproduction initialized with the following command:
```
ionic start "IonItemSliding open repro" blank --type=vue
```

View reproduction here:
[![Open reproduction in StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/github/loyaj/ion-item-sliding-open-repro?file=src%2Fviews%2FHomePage.vue)

**Comment by liamdebeasi** [comment] 2023-05-08 12:51
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. As mentioned in the [Ionic Vue Documentation](https://ionicframework.com/docs/vue/quickstart#calling-methods-on-components), you need to access `$el` before calling methods. The [Ionic Vue Troubleshooting Guide](https://ionicframework.com/docs/vue/troubleshooting#method-on-component-is-not-a-function) has more information.

So in this case you would do `ionItemSlidingRef.value.$el.open("start")` instead of `ionItemSlidingRef.value.open("start")`.

**Closed by liamdebeasi** 2023-05-08 12:51 UTC
Labels: triage

**Comment by loyaj** [comment] 2023-05-09 00:20
Ah, yes. The docs are abundantly clear, I just didn't find them for some reason. Thanks!
