### ISSUE TITLE
bug: `ion-input` - Vue3 - input does not update it's value when the corresponding value is changed programatically

### ISSUE THREAD

**Issue by mateuszRybczonek** [ionic-team/ionic-framework#22955] opened 2021-02-22 10:12 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

Vue: 3.0.5
Ionic Vue: 5.5.3

`ion-input` value is not updating the input value when the corresponding data value is changed programatically.

The issue appeared after upgrading from 5.5.2 to 5.5.3. (see example sandboxes for 5.5.2 and 5.5.3).

https://codesandbox.io/s/vue-3-ionic-input-issue-552-working-fine-e1w33
https://codesandbox.io/s/vue-3-ionic-input-issue-553-not-working-anymore-dqlns

**Expected behavior:**
The input value updates to always reflect the corresponding data value.

**Comment by liamdebeasi** [comment] 2021-02-22 16:46
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/22886. (same underlying issue) I have a fix in the works and will put a dev build in that thread soon for testing.

**Closed by liamdebeasi** 2021-02-22 16:46 UTC
Labels: triage
