### ISSUE TITLE
bug: ion-datetime-button error

### ISSUE THREAD

**Issue by vadimwe** [ionic-team/ionic-framework#25735] opened 2022-08-06 14:43 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

`<ion-datetime-button></ion-datetime-button>
          <ion-modal [keepContentsMounted]="true">
            <ng-template>
              <ion-datetime id="datetime"></ion-datetime>
            </ng-template>
          </ion-modal>`

Gives error: 'ion-datetime-button' is not a known element

### Expected Behavior

button + modal

### Steps to Reproduce

<ion-datetime-button></ion-datetime-button> with latest ionic

### Ionic Info

Ionic:

   Ionic CLI                     : 6.20.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.2.1
   @angular-devkit/build-angular : 14.1.1
   @angular-devkit/schematics    : 13.3.9
   @angular/cli                  : 14.1.1
   @ionic/angular-toolkit        : 6.1.0

Cordova:

   Cordova CLI       : 11.0.0
   Cordova Platforms : android 11.0.0, ios 6.2.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 15 other plugins)

Utility:

   cordova-res : 0.15.4
   native-run  : 1.6.0

System:

   Android SDK Tools : 26.1.1 (/Users/vs/Library/Android/sdk)
   ios-deploy        : 1.11.4
   ios-sim           : 8.0.2
   NodeJS            : v14.18.1 (/usr/local/bin/node)
   npm               : 6.14.15
   OS                : macOS Monterey
   Xcode             : Xcode 13.4.1 Build version 13F100

**Comment by msindev** [comment] 2022-08-07 15:13
I am facing the same issue.

**Comment by crebuh** [comment] 2022-08-08 14:34
same issue

**Comment by vadimwe** [comment] 2022-08-08 14:50
Actually It works, except errors in vscode IDE

**Comment by crebuh** [comment] 2022-08-08 14:52
Yea I had to update from 6.1.9 to 6.2.1 now it works

**Comment by vadimwe** [comment] 2022-08-08 14:54
There is also missing situation with no value provided (e.g. users should select without default set)

**Comment by sean-perkins** [comment] 2022-08-09 13:14
`ion-datetime-button` is a feature released in 6.2.0. It will not be available on any version < 6.2.0. 

There is a known bug with datetime button and Angular (the original reported issue), where the component is not registered on the module. We have a PR merged to resolve that: https://github.com/ionic-team/ionic-framework/pull/25727.

A dev-build is available for that fix: `6.2.2-dev.11659713704.173144dc`. That will be releasing in a patch version later this week. 

Please open a separate issue to report any issues with selecting dates.

**Comment by liamdebeasi** [comment] 2022-08-09 20:22
Hi everyone,

This issue was resolved in https://github.com/ionic-team/ionic-framework/commit/76ad1d18c81272435db1994977aa9dd5d880504a, and the fix will be available in an upcoming release of Ionic. This fix is also available in the latest Ionic nightly for developers who wish to try the fix sooner: https://github.com/ionic-team/ionic-framework/releases/tag/v6.2.2-nightly.20220809

I am going to close this as the issue is resolved. Thanks!

**Closed by liamdebeasi** 2022-08-09 20:22 UTC
Labels: triage

**Comment by andreaslarssen** [comment] 2022-08-26 10:17
> There is also missing behaviour with no value provided (e.g. users should select without default set)

@vadimwe It's still not possible to sett an empty start value? I just updated the framework and it broke my previous workaround top achieve this. Do you know if there's an open issue on this?
