### ISSUE TITLE
bug: andriod transition flash on back button in ionic v7

### ISSUE THREAD

**Issue by beenotung** [ionic-team/ionic-framework#27575] opened 2023-05-30 20:29 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Navigating to next page from routerLink in md mode case the page header to flash.

This bug appears in both stencil and angular projects.

And this bug doesn't appear in ios mode.

Attached screen recording showing navigation w/wo the flash.

Screen recording of navigating md mode with flashing page header:

https://github.com/ionic-team/ionic-framework/assets/6007292/93fb1294-2abc-4a28-8f3b-4cb2bfb142e6

Screen recording of navigating in ios mode without flashing page header:

https://github.com/ionic-team/ionic-framework/assets/6007292/646a8064-967a-46ec-9995-46fdd2a9c475

### Expected Behavior

Navigating in md mode should not cause the page header to flash. It should be as smooth as in ios mode.

### Steps to Reproduce

1. install latest version cli: `npm i -g @ionic/cli`
2. create new project: `ionic start` or `npm init stencil`
3. select angular project tab template, or ionic stencil pwa starter
4. update tab 3, add ion-list and ion-item with link to item page
5. create item page
6. run the project developer server: `npm start`
7. go to tab 3, click the ion-item to navigate to item page, observe the transition effect and page header

### Code Reproduction URL

https://github.com/beenotung/ionic-7-andriod-navigation-bug-demo

### Ionic Info

Ionic:

   Ionic CLI                     : 7.1.1 (C:\Users\USER\AppData\Local\pnpm\global\5\.pnpm\@ionic+cli@7.1.1\node_modules\@io
nic\cli)
   Ionic Framework               : @ionic/angular 7.0.9
   @angular-devkit/build-angular : 16.0.3
   @angular-devkit/schematics    : 16.0.3
   @angular/cli                  : 16.0.3
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.0.4
   @capacitor/android : not installed
   @capacitor/core    : 5.0.4
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v18.15.0 (C:\Users\USER\AppData\Roaming\nvm\v18.15.0\node.exe)
   npm    : 9.6.7
   OS     : Windows 10

**Comment by beenotung** [comment] 2023-05-30 20:51
This bug seems only happening in firefox desktop, it's smooth without flash on firefox mobile (real andriod phone)

**Comment by beenotung** [comment] 2023-05-30 21:02
This bug is not appearing on chrome desktop as well

**Comment by liamdebeasi** [comment] 2023-05-30 21:07
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/26620.

**Closed by liamdebeasi** 2023-05-30 21:07 UTC
Labels: triage
