### ISSUE TITLE
bug:  ion-img can sometimes not load in on a lower-end CPU device due to Intersection Observer API behavior

### ISSUE THREAD

**Issue by Jacob-McKay** [ionic-team/ionic-framework#23703] opened 2021-07-30 02:47 UTC
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

Sometimes (on a lower-end mobile device, or chrome browser with CPU throttling enabled), the ion-img will not display even when it is scrolled into view.  This is because the Intersection Observer API may pass in multiple items to the callback where the code assumes only one item (where the last item is the current value stating the img is in the viewport).

### Expected Behavior

If the ion-img has been supplied a src, and has been scrolled into view, I expect the image to load and be visible to the user.

### Steps to Reproduce

Linked is an experiment you can run with CPU Throttling enabled in your code, it's kind of what my app is doing, it has a bunch of images hooked up to the Intersection Observer API and you will see logged to the console the times that there is more than one item in the callback.

### Code Reproduction URL

https://codepen.io/Jacob-McKay/pen/LYympzR

**Comment by liamdebeasi** [comment] 2021-08-02 13:15
Thanks for the issue. Can you provide some additional steps to reproduce the issue? I tried your CodePen on a low end device with CPU throttling enabled. I was able to get multiple entries per IO callback, but the first entry (index zero) was the entry that stated the img is in the viewport, so I was not able to reproduce the exact behavior you described.

**Comment by liamdebeasi** [comment] 2021-08-02 19:39
I am looking at this a bit more and I think your solution in https://github.com/ionic-team/ionic-framework/pull/23704 is correct. The Intersection Observer entries go from oldest to newest, so the last entry should represent the latest state of the `ion-img`.

**Comment by liamdebeasi** [comment] 2021-08-09 20:19
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/23704, and a fix will be available in an upcoming release of Ionic Framework.

**Closed** 2021-08-09 20:18 UTC
Labels: package: core, type: bug
