### ISSUE TITLE
bug: Angular icon component ignores title

### ISSUE THREAD

**Issue by andreaslarssen** [ionic-team/ionic-framework#24999] opened 2022-03-25 10:27 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

Ionic ignores the title attr. on the icon component:

```
<ion-icon name="reload-outline" title="myFunkyTitle" ></ion-icon>
```
Title = "Reload"

### Expected Behavior

The icon to show the title

### Steps to Reproduce

Put this:

```
<ion-icon name="reload-outline" title="myFunkyTitle" ></ion-icon>
```

in an Anulgar app running Ionic5

### Ionic Info

Ionic:

   Ionic CLI : 6.17.0

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v14.17.5
   npm    : 7.21.1
   OS     : Linux 5.13

**Comment by amandaesmith3** [comment] 2022-03-28 14:03
Thanks for the issue. I'm going to close this as a duplicate of https://github.com/ionic-team/ionicons/issues/1049.

**Closed by amandaesmith3** 2022-03-28 14:03 UTC
Labels: triage
