### ISSUE TITLE
bug: IonContent onIonScroll events don't fire if a ref is passed to the IonContent

### ISSUE THREAD

**Issue by aub** [ionic-team/ionic-framework#22609] opened 2020-12-01 20:00 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] 5.5.1

**Current behavior:**
In a React app, if you have an IonContent with an `onIonScroll` handler, `scrollEvents` passed as true, and a `ref`, it will not fire the `onIonScroll` handler. This works in 5.5.0 and is broken in 5.5.1.

I can provide demos apps for these, but I think some other things were also broken here as well:

* If you provide a ref to IonContent and a `className` the class name won't be applied.
* The className thing is also true for IonMenu.

And I think the real bug might be that if you pass a ref to an Ionic component then other props are ignored.

**Expected behavior:**
The scroll handler will always fire.

**Steps to reproduce:**

**Related code:**

[Here is a demo app](https://github.com/withgrayce/scroll-events-fail-demo) that reproduces the problem. It seems to be related to [this change](https://github.com/ionic-team/ionic-framework/compare/v5.5.0...v5.5.1#diff-63f0145af82c5cb486a293fb438e6e353c21c30a85d8ae19dd6ccc38d455053c) in the framework, which happened in 5.5.1 and is related to refs.

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.11.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.5.1

Capacitor:

   Capacitor CLI   : 2.4.4
   @capacitor/core : 2.4.4

Utility:

   cordova-res (update available: 0.15.2) : 0.15.1
   native-run (update available: 1.2.2)   : 1.0.0

System:

   NodeJS : v14.14.0 (/Users/aubrey/.nvm/versions/node/v14.14.0/bin/node)
   npm    : 6.14.8
   OS     : macOS Catalina
```

**Comment by elylucas** [comment] 2020-12-02 17:59
Thanks @aub, we got a fix in and it will be in the next release.

**Comment by PatrickG** [comment] 2020-12-04 09:13
Same thing happens on `IonInput`, if you pass a `ref` no `onIonChange/onIonInput` events are fired.

**Closed** 2020-12-08 20:45 UTC
Labels: package: react

**Comment by ar-daniel** [comment] 2020-12-23 17:01
This bug fix saved my day. I had got long stuck with issue when associating ref with IonInput - it only created default IonInput without taking any additional attributes or css styling. Was unable to reproduce the issue as it was working in the test file. Finally a lucky attempt to upgrade to 5.5.2 solved the issue. Thanks for reporting the issue and fixing it.

**Comment by appletreeat56** [comment] 2020-12-30 16:42
Thanks for the fix. Saved me from the dilemma of going back to version 4.
