### ISSUE TITLE
feat(picker): inline picker 

### ISSUE THREAD

**Issue by DwieDima** [ionic-team/ionic-framework#21796] opened 2020-07-23 10:35 UTC
# Feature Request

**Ionic version:**

[x] **5.x**

**Describe the Feature Request**

By default Apple has a inline picker for date/time and custom properties.
Currently ion-datetime and ion-picker can only be presented as overlay.
It would be great if ionic would also provide this component to get one step closer to the native!

Alarm App             |  Reminder App
:-------------------------:|:-------------------------:
<img src="https://user-images.githubusercontent.com/26873275/88274238-a8326300-ccdb-11ea-9b62-d3d8cb34c70e.PNG" width="650">  |  ![reminder_picker](https://user-images.githubusercontent.com/26873275/88274254-af597100-ccdb-11ea-9305-829ff2f8a3d5.gif)

**Describe Preferred Solution**

### ion-datetime
should be extended by the following input properties:
- `type`: `'overlay' | 'inline'`
- `expanded`: `boolean`
  - when type is set to `inline`, whether component is expanded or hidden by ion-item (see Reminder App)

- when `expanded=true` date on ion-item is at start and label is hidden
- when `expanded=false` date on ion-item is at end and label is visible

should be extended by the following methods:
- `toggle()`
  - to trigger expand animation programatically
- `isHidden()`
  - whether picker is toggled or not

```
<ion-item>
  <ion-label>My Alarm</ion-label>
  <ion-datetime displayFormat="MM DD YY" placeholder="Select Date" type="inline" expanded="true"></ion-datetime>
</ion-item>
```

### ion-picker

Should be available as HTML component.
should be extended by the following input properties:
- `type`: `'overlay' | 'inline'`
- `expanded`: `boolean`
  - when type is set to `inline`, whether component is expanded or hidden by ion-item

- when `expanded=true` date on ion-item is at start and label is hidden
- when `expanded=false` date on ion-item is at end and label is visible 

should be extended by the following methods:
- `toggle()`
  - to trigger expand animation programatically
- `isHidden()`
  - whether picker is toggled or not

```
<ion-item>
  <ion-label>Choose Genre</ion-label>
  <ion-picker [columns]="columns" placeholder="select option" type="inline" expanded="true"></ion-picker>
</ion-item>
```

**Both components should return on change a hapic feedback like the native picker.**

**Describe Alternatives**
Actually i havent found any. Using native picker plugins still uses overlay.

**Comment by liamdebeasi** [comment] 2020-07-23 13:11
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/19642.

**Closed by liamdebeasi** 2020-07-23 13:11 UTC
