### ISSUE TITLE
bug: ion-datetime ionBlur fires when clicking on specific parts of the picker

### ISSUE THREAD

**Issue by rlovasz** [ionic-team/ionic-framework#28785] opened 2024-01-05 14:31 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Using ion-datetime component I found that clicking on specific parts of the component the ionBlur event fires. The purple areas on below images:
![image](https://github.com/ionic-team/ionic-framework/assets/21507175/5d1a2ddf-b3ea-4fee-8daa-da122b7dc19c)
![image](https://github.com/ionic-team/ionic-framework/assets/21507175/55035fa8-0acd-4dfd-90e6-7e3ed73125c7)
![image](https://github.com/ionic-team/ionic-framework/assets/21507175/1c9ca2fa-de2b-4eda-9ecf-a78f71f9590d)

### Expected Behavior

Clicking on any area of the datetime component the blur event is not firing.

### Steps to Reproduce

1. Open the month selector
2. Click on one of the purple areas
3. blur shows up in console

### Code Reproduction URL

https://github.com/rlovasz/datetime-blur-bug-reproduction

### Ionic Info

Ionic:

   Ionic CLI                     : 7.2.0 (/Users/rlovasz/.nvm/versions/node/v16.14.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.6.3
   @angular-devkit/build-angular : 17.0.9
   @angular-devkit/schematics    : 17.0.9
   @angular/cli                  : 17.0.9
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.6.0
   @capacitor/android : not installed
   @capacitor/core    : 5.6.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 2.0.0

System:

   NodeJS : v16.14.0 (/Users/rlovasz/.nvm/versions/node/v16.14.0/bin/node)
   npm    : 8.3.1
   OS     : macOS Unknown

### Additional Information

I would like to use ionBlur to close the datepicker if the user clicks outside of the component, and this behaviour is unpleasant.

**Comment by liamdebeasi** [comment] 2024-01-05 16:50
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The `ionFocus` and `ionBlur` events fire when focusable parts of the element are either focused or blurred. Clicking a non-focusable element causes `ionBlur` to fire because the clicked element cannot be focused.

For example, in Chrome clicking a calendar day button will cause `ionFocus` to be fired because buttons are focusable. Since the button is inside of `ion-datetime`, `document.activeElement` is `ion-datetime` due to retargeting. However, if you click the days of the week labels (i.e. "Mon" or "M") then `ionBlur` fires. That is because this text is not considered a focusable element. Similarly, `document.activeElement` no longer references `ion-datetime`.

The purple areas reproduce the issue because they contain non-focusable elements. I am going to close this, but let me know if you have any questions.

**Closed by liamdebeasi** 2024-01-05 16:50 UTC
Labels: holiday triage
