### ISSUE TITLE
bug: Swipe back animation stops working when navigating recursive pages

### ISSUE THREAD

**Issue by aeharding** [ionic-team/ionic-framework#27707] opened 2023-06-27 05:48 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Hi there! I have the following routes:
```
/tab1/:communityName
/tab1/:communityName/posts
```

Say I do the following:

```
/tab1/communityone => /tab1/communityone/posts => /tab1/communitytwo
```

then, if I swipe back, I can go from /tab1/communitytwo to /tab1/communityone/posts. But I cannot swipe back from /tab1/communityone/posts to /tab1/communityone.

See attached video

### Expected Behavior

Should be able to swipe back like normal.

### Steps to Reproduce

1. Open test repo
2. Press "to /tab1/firstcommunity"
3. Press "to /tab1/firstcommunity/posts"
4. Press "to /tab1/secondcommunity" 
5. Swipe back (should succeed)
6. Swipe back (should fail)

https://github.com/ionic-team/ionic-framework/assets/2166114/7f231e46-7fd5-4590-b677-b19b66f46b80

### Code Reproduction URL

https://github.com/aeharding/nested-tabs

### Ionic Info

```
➜  nested-tabs git:(main) ionic info
[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package.json'

       Require stack:
       - /Users/aeharding/.nvm/versions/node/v18.15.0/lib/node_modules/@ionic/cli/lib/project/index.js
       - /Users/aeharding/.nvm/versions/node/v18.15.0/lib/node_modules/@ionic/cli/lib/index.js
       - /Users/aeharding/.nvm/versions/node/v18.15.0/lib/node_modules/@ionic/cli/index.js
       - /Users/aeharding/.nvm/versions/node/v18.15.0/lib/node_modules/@ionic/cli/bin/ionic
[WARN] Error loading @capacitor/android package.json: Error: Cannot find module '@capacitor/android/package.json'

       Require stack:
       - /Users/aeharding/.nvm/versions/node/v18.15.0/lib/node_modules/@ionic/cli/lib/project/index.js
       - /Users/aeharding/.nvm/versions/node/v18.15.0/lib/node_modules/@ionic/cli/lib/index.js
       - /Users/aeharding/.nvm/versions/node/v18.15.0/lib/node_modules/@ionic/cli/index.js
       - /Users/aeharding/.nvm/versions/node/v18.15.0/lib/node_modules/@ionic/cli/bin/ionic

Ionic:

   Ionic CLI       : 7.1.1 (/Users/aeharding/.nvm/versions/node/v18.15.0/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 7.1.1

Capacitor:

   Capacitor CLI      : 5.0.5
   @capacitor/android : not installed
   @capacitor/core    : 5.0.5
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v18.15.0 (/Users/aeharding/.nvm/versions/node/v18.15.0/bin/node)
   npm    : 9.5.0
   OS     : macOS Unknown
```

**Comment by liamdebeasi** [comment] 2023-06-27 14:02
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/26524. The problem here is Ionic React should be creating a new instance of `Tab1Community` when routing to `/tab1/secondcommunity`. However, it is incorrectly re-using the instance for `/tab1/firstcommunity`.

**Closed by liamdebeasi** 2023-06-27 14:02 UTC
Labels: triage

**Comment by aeharding** [comment] 2023-06-27 14:04
Thanks. I apologize for the duplicate issue. I guess I am bad at searching 😅

**Comment by liamdebeasi** [comment] 2023-06-27 14:04
Not a problem 😄
