### ISSUE TITLE
bug: @ionic/core,ES5 strict mode problem, Ionic cannot run on Android 5.1/API 22

### ISSUE THREAD

**Issue by pipoa** [ionic-team/ionic-framework#22354] opened 2020-10-20 07:26 UTC
**ISSUE:**
@Ionic/core problem, It causes ionic not able to run on android 5.1, because ES, strict mode problem.

**Error Message:**
Uncaught SyntaxError: In strict mode code, **functions can only be declared at top level or immediately within another function.**

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
cannot run in android 5.1

**Code Snippet:**
See ERROR line below, at line: function checkIfURLIsSupported() 
```
/***/ "./node_modules/@ionic/core/dist/esm/polyfills/index.js":
/*!**************************************************************!*\
  !*** ./node_modules/@ionic/core/dist/esm/polyfills/index.js ***!
  \**************************************************************/
/*! exports provided: applyPolyfills */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "applyPolyfills", function() { return applyPolyfills; });
function applyPolyfills() {
  var promises = [];
  if (typeof window !== 'undefined') {
    var win = window;

    if (!win.customElements ||
      (win.Element && (!win.Element.prototype.closest || !win.Element.prototype.matches || !win.Element.prototype.remove || !win.Element.prototype.getRootNode))) {
      promises.push(__webpack_require__.e(/*! import() | polyfills-dom */ "polyfills-dom").then(__webpack_require__.t.bind(null, /*! ./dom.js */ "./node_modules/@ionic/core/dist/esm/polyfills/dom.js", 7)));
    }

    function checkIfURLIsSupported() {  <===== ERROR: BROWSER COMPLAINS THIS
      try {
        var u = new URL('b', 'http://a');
        u.pathname = 'c%20d';
        return (u.href === 'http://a/c%20d') && u.searchParams;
      } catch (e) {
        return false;
      }
    }

    if (
      'function' !== typeof Object.assign || !Object.entries ||
      !Array.prototype.find || !Array.prototype.includes ||
      !String.prototype.startsWith || !String.prototype.endsWith ||
      (win.NodeList && !win.NodeList.prototype.forEach) ||
      !win.fetch ||
      !checkIfURLIsSupported() ||
      typeof WeakMap == 'undefined'
    ) {
      promises.push(__webpack_require__.e(/*! import() | polyfills-core-js */ "polyfills-core-js").then(__webpack_require__.t.bind(null, /*! ./core-js.js */ "./node_modules/@ionic/core/dist/esm/polyfills/core-js.js", 7)));
    }
  }
  return Promise.all(promises);
}


```
**Expected behavior:**
should work correctly

**Other information:**
It seems **checkIfURLIsSupported** should move to the top of  **applyPolyfills**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.11.11 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.3.1
   @angular-devkit/build-angular : 0.901.12
   @angular-devkit/schematics    : 9.1.12
   @angular/cli                  : 9.1.12
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 9.0.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.2.1, (and 27 other plugins)

Utility:

   cordova-res                          : 0.15.1
   native-run (update available: 1.2.2) : 1.2.1

System:

   Android SDK Tools : 26.1.1 (/Users/avex/Library/Android/sdk)
   ios-deploy        : 1.11.2
   ios-sim           : 8.0.2
   NodeJS            : v12.18.3 (/usr/local/bin/node)
   npm               : 6.14.6
   OS                : macOS Catalina
   Xcode             : Xcode 11.2.1 Build version 11B500```

**Comment by liamdebeasi** [comment] 2020-10-20 13:57
What version of the Chromium web view does your device use? You can find this out by logging `window.navigator.userAgent` when inspecting the app in Chrome Dev Tools.

**Comment by pipoa** [comment] 2020-10-21 03:49
> What version of the Chromium web view does your device use? You can find this out by logging `window.navigator.userAgent` when inspecting the app in Chrome Dev Tools.

Hi @liamdebeasi , this is window.navigator.userAgent, I just run it in emulator

`"Mozilla/5.0 (Linux; Android 5.1.1; Android SDK built for x86_64 Build/LMY48X) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/39.0.0.0 Mobile Safari/537.36"
`

as error message said, move `checkIfURLIsSupported`  to the top of applyPolyfills can solve the problem

**Comment by liamdebeasi** [comment] 2020-10-21 15:17
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. We do not recommend testing your apps on the Android emulator as those typically have very old versions of the Chromium WebView. Your simulator uses Chrome 39, but the latest version is Chrome 86.

Ionic Framework does not support these old versions of Chrome as they lack many of the modern Web APIs that are needed. I recommend testing either on a physical device or on an emulator with a newer version of Android. The newer emulators typically let you add the Play Store Service which will let you update your webview.

The other option here would be to change your `browserslist` file to add support for older versions of Chrome: https://github.com/browserslist/browserslist.

**Closed by liamdebeasi** 2020-10-21 15:17 UTC
Labels: triage
