### ISSUE TITLE
bug: ipadOS fullsize modal / presentingElement not getting cardStyle

### ISSUE THREAD

**Issue by sbittmann** [ionic-team/ionic-framework#22422] opened 2020-11-03 09:25 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

Actual its not possible to make a fullscreen modal on ipadOS with changing the presentingElement (ion-app) to backgroundCard

**Expected behavior:**

The presentingElement for example ion-app should get cardStyle and in top of the app there should be a blackspace.
This Site has been mentioned in a previous Issue (https://github.com/ionic-team/ionic-framework/issues/20255), please take a note on the "Extra Extra Extra Large content size" on ipadOS.
https://hacknicity.medium.com/view-controller-presentation-changes-in-ios-13-ac8c901ebc4e

**Steps to reproduce:**

Use the modal example from the documentation. 
(https://ionicframework.com/docs/demos/api/modal/index.html?ionic:mode=ios)
Create big modal. 
Add presentingElement
Open modal on ios screensize and the presentingElement gets nice cardStyle Animation.
Open same modal with ipad-screensize and the presentingElement is not changing. 

**Related code:**
See https://github.com/sbittmann/ionicCardStyleIssue

**Other information:**

I think problem is based in
ionic-framework/core/src/components/modal/animations/ios.enter.ts
Line 31-32:
```
  if (presentingEl) {
    const isMobile = window.innerWidth < 768;
```
And Line 44:
```
    if (isMobile) {
```

**Comment by liamdebeasi** [comment] 2020-11-03 14:48
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The "card style modal" on iPadOS is not supposed to show up in the same way as it does on an iPhone. I tested this out in a native Swift application on devices running iOS 14, and this is what the swipeable modals look like:

| iPhone 12 | iPad Pro (11 inch) |
|-----------|---------------------|
| ![Screen Shot 2020-11-03 at 9 21 40 AM](https://user-images.githubusercontent.com/2721089/97996629-0203f800-1db6-11eb-9377-ad47d12c0940.png) | ![Screen Shot 2020-11-03 at 9 21 38 AM](https://user-images.githubusercontent.com/2721089/97996649-08926f80-1db6-11eb-8288-b0e0acf3259c.png) |


I was not able to reproduce the "ExtraExtraExtraLarge" content size category on iOS 14 with an iPad Pro 11 inch, nor was I able to find it used in any native apps, so I don't think it is used anymore in iOS 14. I can only find the "ExtraExtraExtraLarge" content size option in the Apple Developer Docs in the context of fonts: https://developer.apple.com/search/?q=ExtraExtraExtraLarge&type=Documentation

**Closed by liamdebeasi** 2020-11-03 14:48 UTC
Labels: triage
