### ISSUE TITLE
bug: Ionic 5 sidemenu application showing wrong page on back navigation

### ISSUE THREAD

**Issue by techiesalman** [ionic-team/ionic-framework#22305] opened 2020-10-13 06:07 UTC
# Bug Report

**Ionic version:**
 @ionic/angular 5.3.3

**Current behavior:**
Assume scenario user is on root page. Now from side menu he click one menu and navigates to page B and from page B clicks one link and navigates to page C. Now when user clicks hardware back button or navbar back button from page C then instead of going back to page B it navigates to root page. If properly observed then you can see in url it navigated to proper page but showing wrong content page.

**Expected behavior:**
It should have navigated properly to page B from page C.

**Steps to reproduce:**
I have created one POC project on StackBlitz to check about this issue. Url is: https://stackblitz.com/edit/github-qrhuyg
To produce this issue I have created Ionic sidemenu project then created some components. Installed some third party libraries which you can see in app.module. Created service and models to bring some records from api and after that I ran the project and issue started to come. 

Note: If you create a simple sidemenu application without any service and libraries navigation works properly in that case.

**Ionic info:**
```

**Ionic:**
   Ionic CLI                     : 6.4.1 (C:\Users\Abcd\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.3.3
   @angular-devkit/build-angular : 0.1000.8
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

**Cordova:**
   Cordova CLI       : not installed
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 14 other plugins)
**Utility:**
   cordova-res : 0.15.1
   native-run  : 0.2.5
**System:**
   Android SDK Tools : 26.1.1 (C:\Users\Abcd\AppData\Local\Android\Sdk)
   NodeJS            : v12.16.1 (C:\Program Files\nodejs\node.exe)
   npm               : 6.13.4
   OS                : Windows 10

```

**Comment by liamdebeasi** [comment] 2020-10-14 13:49
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. Page B is being navigated to correctly, but your custom CSS in `global.scss` is causing the root page to be shown over Page B. Removing the custom `.ion-page` styles resolves this issue.

**Closed by liamdebeasi** 2020-10-14 13:49 UTC
Labels: triage
