### ISSUE TITLE
Navigating to error page from error handler when error thrown in ngOnInit

### ISSUE THREAD

**Issue by jonmikelm** [ionic-team/ionic-framework#16246] opened 2018-11-06 16:48 UTC
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)             : 4.2.1 (D:\Users\******\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.15
   @angular-devkit/build-angular : 0.7.5
   @angular-devkit/schematics    : 0.7.5
   @angular/cli                  : 6.2.5
   @ionic/angular-toolkit        : not installed

System:

   NodeJS : v10.11.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 7
```

**Describe the Bug**
When an error is thrown in the ngOnInit method of a page component, and a custom error handler is defined to redirect to an error page, both the page that generated the error and the error page are rendered inside the ion-router-outlet.

**Steps to Reproduce**
1. Navigate to a page, e.g:
```
this.navCtrlr.navigateRoot('public/page1');
```
2. Throw an error in ngOnInit
```
ngOnInit() {
  throw 'error';
}
```
3. Handle the error in a custom angular error handler
```
public handleError(error: any): void {
  const navCtrlr = this.injector.get(NavController);
  ngZone.run(() => {
    navCtrlr.navigateRoot('public/errorPage');
  });
}
```
4. Inspect DOM and verify that ion-router-outlet contains both components, with page1 on top.
```
<ion-router-outlet>
  <page-1>...</page-1>
  <error-page>...</error-page>
</ion-router-outlet>
```
**Related Code**

**Expected Behavior**
The navigation to page1 should be canceled and the component removed from outlet. The error page should be shown.

**Additional Context**
I've tried with and without using ngZone while navigating in the custom error handler but the result is the same.
This old angular issue is closed but problems can be related:
https://github.com/angular/angular/issues/19218

**Comment by selipso** [comment] 2018-11-06 17:32
Have you tried using a route guard? It seems like that would be a more appropriate method for what you are trying to achieve. 

https://codeburst.io/using-angular-route-guard-for-securing-routes-eabf5b86b4d1

**Comment by almothafar** [comment] 2018-11-07 08:09
I feel it could be a side effect for the router issues that appeared with beta 15, do you have the same issue in beta 13? look at #16244

**Comment by jonmikelm** [comment] 2018-11-07 08:45
I've just tested it with beta 13 and the result is the same.

**Comment by liamdebeasi** [comment] 2022-05-23 20:08
Thanks for the issue. I am not able to reproduce this behavior with the latest version of Ionic 6 and Angular 13, so I am going to close this. If you are still running into problems, please open a new issue.

**Closed by liamdebeasi** 2022-05-23 20:08 UTC
Labels: package: angular
