### ISSUE TITLE
bug: vue add pwa not working with ionic 6 tabs

### ISSUE THREAD

**Issue by DriesBruggeman** [ionic-team/ionic-framework#24397] opened 2021-12-14 11:04 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

After creating a brand new ionic 6 vue application using the tabs template and running vue add pwa to get pwa features ionic serve no longer works.

### Expected Behavior

Ionic serve still works after running vue add pwa

### Steps to Reproduce

1. Run: ionic start
2. Choose Vue as the framework
3. Choose tabs as the template
4. Run ionic serve to check the app is correctly working
5. Shut down ionic serve
6. Run: vue add pwa
7. Run: ionic serve

### Code Reproduction URL

https://github.com/DriesBruggeman/ion6-pwa-crashing-tabs

### Ionic Info

[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package'

       Require stack:
       - C:\Users\Dries\AppData\Roaming\npm\node_modules\@ionic\cli\lib\project\index.js
       - C:\Users\Dries\AppData\Roaming\npm\node_modules\@ionic\cli\lib\index.js
       - C:\Users\Dries\AppData\Roaming\npm\node_modules\@ionic\cli\index.js
       - C:\Users\Dries\AppData\Roaming\npm\node_modules\@ionic\cli\bin\ionic
[WARN] Error loading @capacitor/android package.json: Error: Cannot find module '@capacitor/android/package'

       Require stack:
       - C:\Users\Dries\AppData\Roaming\npm\node_modules\@ionic\cli\lib\project\index.js
       - C:\Users\Dries\AppData\Roaming\npm\node_modules\@ionic\cli\lib\index.js
       - C:\Users\Dries\AppData\Roaming\npm\node_modules\@ionic\cli\index.js
       - C:\Users\Dries\AppData\Roaming\npm\node_modules\@ionic\cli\bin\ionic

Ionic:

   Ionic CLI       : 6.18.1 (C:\Users\Dries\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/vue 6.0.0

Capacitor:

   Capacitor CLI      : 3.3.3
   @capacitor/android : not installed
   @capacitor/core    : 3.3.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v14.17.5 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.14
   OS     : Windows 10

### Additional Information

 vue-cli-service.cmd serve
[9%] setup (compilation vue-cli:pwa-html-plugin)
[vue-cli-service] (node:14540) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'tapAsync' of undefined
[vue-cli-service]     at C:\Users\Dries\Desktop\Nieuwe map\test-ion\node_modules\@vue\cli-plugin-pwa\lib\HtmlPwaPlugin.js:62:63
[vue-cli-service]     at Hook.eval [as call] (eval at create (C:\Users\Dries\Desktop\Nieuwe map\test-ion\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:256:1)
[vue-cli-service]     at Hook.CALL_DELEGATE [as _call] (C:\Users\Dries\Desktop\Nieuwe map\test-ion\node_modules\tapable\lib\Hook.js:14:14)
[vue-cli-service]     at Compiler.newCompilation (C:\Users\Dries\Desktop\Nieuwe map\test-ion\node_modules\webpack\lib\Compiler.js:1055:26)
[vue-cli-service]     at C:\Users\Dries\Desktop\Nieuwe map\test-ion\node_modules\webpack\lib\Compiler.js:1099:29
[vue-cli-service]     at Hook.eval [as callAsync] (eval at create (C:\Users\Dries\Desktop\Nieuwe map\test-ion\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:40:1)
[vue-cli-service]     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Users\Dries\Desktop\Nieuwe map\test-ion\node_modules\tapable\lib\Hook.js:18:14)
[vue-cli-service]     at Compiler.compile (C:\Users\Dries\Desktop\Nieuwe map\test-ion\node_modules\webpack\lib\Compiler.js:1094:28)
[vue-cli-service]     at C:\Users\Dries\Desktop\Nieuwe map\test-ion\node_modules\webpack\lib\Watching.js:214:19
[vue-cli-service]     at _next0 (eval at create (C:\Users\Dries\Desktop\Nieuwe map\test-ion\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:41:1)
[vue-cli-service] (Use `node --trace-warnings ...` to show where the warning was created)
[vue-cli-service] (node:14540) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[vue-cli-service] (node:14540) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

===================

vue -V returns: @vue/cli 4.5.15

**Comment by DriesBruggeman** [comment] 2021-12-14 14:03
Reproduction project: https://github.com/DriesBruggeman/ion6-pwa-crashing-tabs

**Comment by DriesBruggeman** [comment] 2021-12-14 16:28
When I found this issue I was running node 14.17.5, I've tried with 16.13.1 but it is still the same issue.

**Comment by liamdebeasi** [comment] 2021-12-16 20:08
Thanks! I can reproduce this behavior. The error is coming from the `@vue/cli-plugin-pwa` dependency, which is something that is not managed by Ionic. Additionally, I can reproduce this in Ionic 5, so it does not seem to be specific to Ionic 6.

I recommend opening an issue on the [Vue CLI Repo](https://github.com/vuejs/vue-cli) so this behavior can get resolved. I am going to close this as this is not a bug in Ionic. Thank you!

**Closed by liamdebeasi** 2021-12-16 20:08 UTC
Labels: triage
