### ISSUE TITLE
bug: UI issues with ion-textarea

### ISSUE THREAD

**Issue by RouR** [ionic-team/ionic-framework#24000] opened 2021-09-30 20:42 UTC
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

![bug](https://user-images.githubusercontent.com/1227355/135526581-afd350c1-1158-4865-88b7-99b8e51d611c.jpg)

### Expected Behavior

![expected](https://user-images.githubusercontent.com/1227355/135526618-992bba10-0e3a-4554-b0e9-e8eeab496f79.jpg)

### Steps to Reproduce

1. copy the repo
2. npm run start

### Code Reproduction URL

https://github.com/RouR/ionic-bug2

### Ionic Info

```
Ionic:

   Ionic CLI                     : 6.16.3 (C:\Users\someuser\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.0.0-beta.6
   @angular-devkit/build-angular : 12.1.4
   @angular-devkit/schematics    : not installed
   @angular/cli                  : 12.1.4
   @ionic/angular-toolkit        : 4.0.0

Capacitor:

   Capacitor CLI      : 3.2.4
   @capacitor/android : not installed
   @capacitor/core    : 3.2.4
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.4.1

System:

   NodeJS : v14.15.4 (C:\Program Files\nodejs\node.exe)
   npm    : 7.20.0
   OS     : Windows 10
```

### Additional Information

Also please check padding for max-length counters. I can't define it, but there's something wrong there, too.

**Comment by liamdebeasi** [comment] 2021-09-30 21:18
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/21242.

**Closed by liamdebeasi** 2021-09-30 21:18 UTC
Labels: triage
