### ISSUE TITLE
bug: vue, replacing routes can cause replacement to happen 2x

### ISSUE THREAD

**Issue by outdoorfish** [ionic-team/ionic-framework#25017] opened 2022-03-30 08:27 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

sometimes back button not work

### Expected Behavior

back button working

### Steps to Reproduce

issue 1

1.  click Go To Sub Page (push)  /a -> /sub/1
2. click sub2 (replace)  /sub/1 -> /sub/2
3. click back button (not work)

issue 2
1. click tab button /a -> /b
2. click tab button /b -> /a
3. click Go To Sub Page (push)  /a -> /sub/1
4. click sub2 (replace)  /sub/1 -> /sub/2
5. click back button (work) /sub/2 -> /a
6. click Go To Sub Page (push)  /a -> /sub/1
7. click sub2 (replace)  /sub/1 -> /sub/2
8. click back button (not work)

https://user-images.githubusercontent.com/92348687/160971313-5a3f0e1a-1b5d-4616-a97f-bdfa45859564.mov

https://user-images.githubusercontent.com/92348687/160971303-4eb7f554-e925-4a90-a428-9fd5fa5ddb6e.mov

### Code Reproduction URL

https://github.com/outdoorfish/ionic-back-button-issue

### Ionic Info

Ionic:

   Ionic CLI : 6.18.1

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v14.16.0
   npm    : 6.14.11
   OS     : macOS Big Sur

**Comment by liamdebeasi** [comment] 2022-04-20 21:25
Thanks for the issue. The problem here is that we are internally performing the replace operation twice when going to `sub/2`.

This logic handles wiping the future history when replacing: https://github.com/ionic-team/ionic-framework/blob/main/packages/vue-router/src/router.ts#L374-L375

But in the case of `sub/2`, there is extra logic in the `locationHistory.add` method that causes the route to get replaced again: https://github.com/ionic-team/ionic-framework/blob/main/packages/vue-router/src/locationHistory.ts#L9-L11

The result is that we lose the previous route history. Now that we are using `clearHistory` we should probably remove this automatic replacing logic in `locationHistory.add`.

**Comment by liamdebeasi** [comment] 2022-04-20 21:44
Can you try the following dev build and let me know if it resolves the issue?

```
npm install @ionic/vue@6.1.3-dev.11650490791.156717e3 @ionic/vue-router@6.1.3-dev.11650490791.156717e3
```

**Comment by outdoorfish** [comment] 2022-04-22 06:31
thanks, it resolve this issue

but i found another problem 

1. click tab button /a -> /b
2. click Go To Sub Page (push) /b -> /sub/1
3. click sub2 (replace) /sub/1 -> /sub/2
4. click router-link (push) /sub/2 -> /a

route path "/a" is correct, but ion-page display "/b"


https://user-images.githubusercontent.com/92348687/164615255-8a2f9cbc-93a9-468b-8445-0e723814796a.mov

**Comment by Khirkhoff** [comment] 2022-04-22 09:23
I'm also still facing an issue with the new build that you posted @liamdebeasi 
The console is showing: Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'e.mount=!1').

**My flow is:**
1) TAB1 -> push child page (TAB1/CHILD)
2) click TAB2 
3) click TAB1 twice to go to parent page
4) push child page again (TAB1/CHILD)
5) click TAB2
6) click TAB1 twice to go to parent page
7) click TAB2

**Comment by liamdebeasi** [comment] 2022-04-22 13:16
@outdoorfish Thanks for testing! I can reproduce this behavior. However, I can reproduce this behavior with the latest version of Ionic, so this does not appear to be caused by the dev build. 

Additionally, navigating across tabs is an anti-pattern and not something we support. Tabs are design to be individual stacks that do not interact, so going from Tab A to Tab B programmatically is not something developers should do in their app (even if there's additional redirects in there).

Another way to think of this: Tabs should only be switched by a user pressing a tab button in the tab bar.

--------

@Jannik-KJ This does not sound related to the issue described on this thread. Can you open a separate issue?

**Comment by Jannik-KJ** [comment] 2022-04-22 13:47
@liamdebeasi Ah okay sorry, think it relates to this then #24303
Thought they were somehow connected

**Comment by liamdebeasi** [comment] 2022-04-25 13:56
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/25171, and a fix will be available in an upcoming release of Ionic Framework.

**Closed** 2022-04-25 13:56 UTC
Labels: package: vue, type: bug
