### ISSUE TITLE
bug: ion-content does not bubble scroll event

### ISSUE THREAD

**Issue by gabrielcursino** [ionic-team/ionic-framework#23697] opened 2021-07-27 23:01 UTC
### Prequisites

- [x] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

After add an eventListener with `useCapture = true` to listen to all scroll events, ion-content not bubbles the event

### Expected Behavior

Bubble scroll event if ion-content scrolls

### Steps to Reproduce

Add to a app with ion-content:

```js
document.addEventListener('scroll', (e) => {
  console.log(e); // Does nothing if ion-content scrolls
}, true);
```

### Ionic Info

@ionic/vue 5.6.12

**Comment by willmartindev** [comment] 2021-07-30 13:52
Hi, thanks for the issue! Can you please reproduce this issue in an Ionic starter app and provide a link to the repo?

**Comment by gabrielcursino** [comment] 2021-07-30 21:18
Hi, https://github.com/gabrielcursino/bubble-scroll-test

**Comment by gabrielcursino** [comment] 2021-07-30 21:19
See Home.vue

```js
...
document.addEventListener('scroll', e => {
    console.log(e.target); // Does nothing if ion-content scrolls
}, true);
...
```

`.custom-scroll` when scrolled triggers the event listener

But `ion-content` does not

**Comment by liamdebeasi** [comment] 2021-08-06 14:23
Thanks for the follow. Events will only escape the Shadow DOM if `event.composed` is `true`. In the case of your `document.addEventListener` code the `scroll` event is not composed so it will not escape the Shadow DOM. This is the intended behavior of the Shadow DOM and not something Ionic Framework can control. That being said, we recommend developers use the `scrollEvents` property on `ion-content` that lets you listen for `ionScroll`, `ionScrollEnd`, and `ionScrollStart` events. See https://ionicframework.com/docs/api/content#properties for more information.

I am going to close this as this is not a bug in Ionic Framework.

**Closed by liamdebeasi** 2021-08-06 14:23 UTC
Labels: ionitron: needs reproduction

**Comment by gabrielcursino** [comment] 2021-08-06 16:32
Ok, in my case I need it to an external library, so `ion-content` events don't solve it, but I understand

Thanks!

**Comment by liamdebeasi** [comment] 2021-08-06 16:34
Could you clarify what the incompatibility between the external library and `ion-content` is? Happy to help if there is something we can do to improve compatibility on the Ionic side.

**Comment by gabrielcursino** [comment] 2021-08-10 15:10
@liamdebeasi I have this tooltip library https://github.com/ionited/tooltip, but it is not directly related to Ionic, so i can't listen for Ionic specific events.

It listens for scroll events to [update](https://github.com/ionited/tooltip/blob/8a941e839e64db32da873ffb1b4675346becb312/src/core.ts#L131) tooltips position if necessary.

With ion-content the [`eventListener`](https://github.com/ionited/tooltip/blob/8a941e839e64db32da873ffb1b4675346becb312/src/core.ts#L131) is not triggered as did you explain, but with other scrollable elements it works well.

**Comment by liamdebeasi** [comment] 2021-08-10 16:52
Thanks! You could listen for the `ionScroll` event and dispatch a [CustomEvent](https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent) named `scroll`. It's a bit of a hacky solution, but it might be worth a shot.

**Comment by gabrielcursino** [comment] 2021-08-10 21:00
Thanks for the sugestion!
