### ISSUE TITLE
bug: When the tabs property of ion-router-outlet is set to true, the navigation animation does not work

### ISSUE THREAD

**Issue by HyperLife1119** [ionic-team/ionic-framework#23599] opened 2021-07-11 16:18 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[o] **5.x**
[ ] **6.x**

**Current behavior:**

I am customizing the tab component (using angular routing navigation). In order to reuse the status of each tab (component), I set the tabs property of ion-router-outlet to true.
When the tabs property of ion-router-outlet is set to true, the navigation animation does not work (When the tabs property of ion-router-outlet is set to false, the navigation animation can work).

**Expected behavior:**

When the tabs property of ion-router-outlet is set to true, the navigation animation should work normally

**Steps to reproduce:**

**Related code:**

```html
<ion-router-outlet class="router-outlet" tabs="true" [animation]="slide(routerOutlet)"></ion-router-outlet>
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment] 2021-07-12 12:56
Thanks for the issue. Can you please reproduce this issue in an Ionic starter app and provide a link to the repo?

**Comment by HyperLife1119** [comment] 2021-07-12 14:29
https://stackblitz.com/edit/github-grcpxb?file=src/app/home/home.page.html

**Comment by HyperLife1119** [comment] 2021-07-12 16:29
> https://stackblitz.com/edit/github-grcpxb?file=src/app/home/home.page.html

A minimal example is provided here. @liamdebeasi

**Comment by HyperLife1119** [comment] 2021-07-15 17:32
do not forget me @liamdebeasi

**Comment by liamdebeasi** [comment] 2021-07-15 17:48
Hi there,

You do not need to ping me. I am aware of the issue, but I have not had a chance to follow up yet.

I will post here when I have more info to share.

**Comment by HyperLife1119** [comment] 2021-07-16 09:11
OK

**Comment by liamdebeasi** [comment] 2021-07-16 13:55
I took a look at your repo, and this looks to be the correct behavior. When you set `tab="true"`, pushing pages within `ion-router-outlet` are considered to be the same as switching tabs: https://github.com/ionic-team/ionic-framework/blob/d8a2db73e2a51bd39d92f10577cd803bb58e6dc0/angular/src/directives/navigation/stack-controller.ts#L58-L62

That being said, the `tabs` property is not a public API and should not be used directly by developers. Is there a reason why you are doing it this way instead of using `ion-tabs`?

**Comment by HyperLife1119** [comment] 2021-07-16 15:01
I need to customize the tabs component, mainly to maintain the status of each tab when the tab routing is switched.

**Comment by liamdebeasi** [comment] 2021-07-16 15:06
The existing `ion-tabs` component should do that for you already, so you may want to double check your original `ion-tabs` usage.

The `tabs` property was designed with `ion-tabs` in mind, and the behavior noted in this thread is the intended behavior when used with `ion-tabs`. Custom implementations of tabs using the `tabs` property on `ion-router-outlet` is not something we are looking to support at the moment, so I am going to close this issue.

**Closed by liamdebeasi** 2021-07-16 15:06 UTC
Labels: triage

**Comment by HyperLife1119** [comment] 2021-07-16 15:19
If I use ion-tabs, how do I add navigation animations? @liamdebeasi

**Comment by liamdebeasi** [comment] 2021-07-16 15:23
If you are referring to adding animations when switching tabs, then that is not something we support at the moment. If this is something you would like to see, I recommend creating a feature request.

**Comment by HyperLife1119** [comment] 2021-07-16 15:25
OK, thank you!
