### ISSUE TITLE
bug: cannot use yarn to install packages or ionic CLI will break

### ISSUE THREAD

**Issue by mishchief** [ionic-team/ionic-framework#25224] opened 2022-05-02 18:40 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

I removed node_modules and installed them again using yarn (my preferred package manager) and now I get the following errors when I try to run `ionic cap sync`:

```
> react-scripts build
Creating an optimized production build...
Failed to compile.

Module not found: Error: Can't resolve 'rxjs' in '/Dev/my-ionic-app/node_modules/@ionic-native/core/decorators'


[ERROR] An error occurred while running subprocess react-scripts.

        react-scripts build exited with exit code 1.

        Re-running this command with the --verbose flag may provide more
        information.
```

This was a fresh install using `ionic start my-ionic-app blank --type=react` the only additional packages I installed were the following:
```
npm install @ionic-native/core
npm install @ionic-native/barcode-scanner
npm install phonegap-plugin-barcodescanner
```

### Expected Behavior

ionic cap sync succeeds running.

### Steps to Reproduce

1. Fresh install using `ionic start my-ionic-app blank --type=react`
2.  Install the following: 
```
npm install @ionic-native/core
npm install @ionic-native/barcode-scanner
npm install phonegap-plugin-barcodescanner
```
4. Remove node_modules (rm -rf node_modules)
5. Run `yarn install`
6. Try running `ionic cap sync`

### Ionic Info

Ionic:

   Ionic CLI       : 6.19.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 6.1.3

Capacitor:

   Capacitor CLI      : 3.5.0
   @capacitor/android : 3.5.0
   @capacitor/core    : 3.5.0
   @capacitor/ios     : 3.5.0

Utility:
   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v16.13.0 (/usr/local/bin/node)
   npm    : 8.1.0
   OS     : macOS Big Sur

**Comment by liamdebeasi** [comment] 2022-05-02 20:08
Thanks for the issue. The Ionic Team does not maintain the `@ionic-native` packages anymore. See https://ionicframework.com/blog/a-new-chapter-for-ionic-native/ for more information.

I recommend you file an issue on the new Ionic Native repo here: https://github.com/danielsogl/awesome-cordova-plugins.

I am going to close this as this is not a bug in Ionic.

**Closed by liamdebeasi** 2022-05-02 20:08 UTC
Labels: triage
