### ISSUE TITLE
bug: datetime, having a max with a date that is one less than the current date prevents navigation

### ISSUE THREAD

**Issue by Yura13** [ionic-team/ionic-framework#24882] opened 2022-03-04 18:07 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Couldn't move to the next month
![image](https://user-images.githubusercontent.com/17030431/156816926-3ecec668-5bf0-441b-bd30-3d42681fc2aa.png)

### Expected Behavior

I should be able to navigate to the next month.

### Steps to Reproduce

I am able to select dates only in the current month.
Min date is 2022-03-04
Max date is 2022-04-03

### Ionic Info

Ionic:

Ionic CLI : 6.18.1 (C:\Users\Xiaomi\AppData\Roaming\nvm\v16.13.2\node_modules@ionic\cli)
Ionic Framework : @ionic/angular 6.0.10
@angular-devkit/build-angular : 13.1.3
@angular-devkit/schematics : 13.1.3
@angular/cli : 13.1.3
@ionic/angular-toolkit : 5.0.3

Cordova:

Cordova CLI : 10.0.0 (cordova-lib@10.1.0)
Cordova Platforms : android 9.1.0, browser 6.0.0
Cordova Plugins : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, cordova-plugin-ionic 5.5.1, (and 28 other plugins)

Utility:

cordova-res : not installed globally
native-run : 1.5.0

System:

Android SDK Tools : 26.1.1 (C:\Android\android-sdk)
NodeJS : v16.13.2 (C:\Program Files\nodejs\node.exe)
npm : 8.1.2
OS : Windows 10

**Comment by pabloweinx** [comment] 2022-03-08 12:25
Same issue here. It does not only happens with the max, but also with the min. Let's imagine the following scenario:

- We open the calendar for setting the start date, and the current month is March
- Depending on the start date we select, we'll also set it as the min calendar value.
- The max date will be calculated by adding 7 days to the the min.
- Well, we set the start date on January, the 1st. (by navigating two months back)
- When we're going to set the end date, we open its calendar also on March with all days disabled as well as the navigation arrows, so we cannot set the end date (from February the 1st to February the 7th) as we did set.

There are more. If we swipe left the enough or with the keyboard, sometimes we can navigate the months back although the navigations arrows are disabled, so we can set the end date.

A second scenario is: we set as first date for example March the 25th, and the max date will be set on the first week of April. Well, when we open the end date calendar, we only can select from March 25th to March 31st, and cannot navigate to April because the arrows are disabled. It happens, in general, when the min and max dates are distributed along 2 consecutive months.

I wish this issue could be fixed.

Big hugs to the Ionic Team!

**Comment by philkonick** [comment] 2022-03-15 11:47
This is still an issue in 6.0.11. 

If the min date is in the previous month, and the day of the min date is greater than the day of today (i.e. 15), the navigation arrow will not work. Likewise if the max date is in the next month and the max day is less than the day of today, it will also not work. 

Swiping over the months, and selecting them from the selector in the top left work correctly regardless.

**Comment by brettrobison** [comment] 2022-05-02 15:09
Still an issue in 6.1.3. Not able to go back and forth months using the top navigation (previous/next buttons and month dropdown). I did confirm that you are able to swipe back and forth to change months, but this is still a very confusing user experience.

Any updates on when this might be fixed?

**Comment by sean-perkins** [comment] 2022-05-02 16:03
Can someone facing this problem test with this dev build: `6.1.3-dev.11650654723.120c74ee`? 

This should be a duplicate of the issue resolved by this PR: https://github.com/ionic-team/ionic-framework/pull/25182, I just did not catch that it was already reported when triaging.

**Comment by brettrobison** [comment] 2022-05-02 17:02
@sean-perkins Confirmed that 6.1.3-dev.11650654723.120c74ee fixes issue

**Comment by sean-perkins** [comment] 2022-05-02 17:03
@brettrobison Awesome, I am gong to close out this issue. The PR has been merged into main. It will be available both in our nightly build as well as the patch release this week. 

Thanks!

**Closed by sean-perkins** 2022-05-02 17:03 UTC
Labels: package: core, type: bug
