### ISSUE TITLE
bug: vue, ion-select interface popover doesn't display ion-select-options

### ISSUE THREAD

**Issue by anttironty** [ionic-team/ionic-framework#24059] opened 2021-10-12 12:40 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

When trying to open ion-select with popover interface, ion-select-options are not displayed. This used to work in v5 without any problems.

[Image of **not opened** ion-select with interface popover](https://tinyimg.io/i/TEiEukC.png)
[Image of **opened** ion-select with interface popover](https://tinyimg.io/i/ypdABdy.png)

### Expected Behavior

ion-select-options should be displayed and selectable, just like they were in v5

### Steps to Reproduce

Follow [v6 beta ion-select docs](https://beta.ionicframework.com/docs/api/select#interface-options-5) to create ion-select component with popover interface in ionic/vue v6 rc0

Reproduction repository is linked

### Code Reproduction URL

https://github.com/anttironty/ionic6_select_popover_debug

### Ionic Info

Ionic:

   Ionic CLI       : 6.17.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 6.0.0-rc.0

Capacitor:

   Capacitor CLI      : 3.2.4
   @capacitor/android : not installed
   @capacitor/core    : 3.2.4
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.3
   native-run  : 1.5.0

System:

   NodeJS : v16.6.2 (/usr/local/bin/node)
   npm    : 7.20.3
   OS     : macOS Big Sur

**Comment by liamdebeasi** [comment] 2021-10-12 13:16
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/23571.

**Closed by liamdebeasi** 2021-10-12 13:16 UTC
Labels: triage
