### ISSUE TITLE
bug: Ionic version upgrade from 7.4.4 to 7.5.0 brokes layout

### ISSUE THREAD

**Issue by berdachuk** [ionic-team/ionic-framework#28398] opened 2023-10-23 20:50 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Ufter Ionic version upgrade from 7.4.4 to 7.5.0 internal components size changed and layout broken.
![current](https://github.com/ionic-team/ionic-framework/assets/32128390/e4741553-2005-4bf0-8632-b805ad5439c2)

### Expected Behavior

![expexted](https://github.com/ionic-team/ionic-framework/assets/32128390/72fba1d8-c1e4-4600-b116-ca5dd9985361)

### Steps to Reproduce

1. open provided sample url or use sample code:
```
<ion-header>
  <ion-toolbar color="primary">
    <ion-title>Emails</ion-title>
  </ion-toolbar>
  <ion-toolbar>
    <ion-chip>
      <ion-select (ionChange)="onChangeFilter($event)"
                  interface="popover" value="{{selectedFilter}}">
        <ion-select-option value="0">
          Inbox
        </ion-select-option>
        <ion-select-option value="1">
          Sent
        </ion-select-option>
        <ion-select-option value="2">
          Spam
        </ion-select-option>
      </ion-select>
      <ion-button (click)="editFilter($event)" fill="clear" mode="ios">
        <ion-icon name="pencil"></ion-icon> edit
      </ion-button>
    </ion-chip>
  </ion-toolbar>
</ion-header>
```

2. in package.json change version from "@ionic/angular": "7.4.4" to "@ionic/angular": "^7.5.0"

### Code Reproduction URL

https://stackblitz.com/edit/angular-vmhxmp-xd9mbb?file=src%2Fapp%2Fexample.component.html

### Ionic Info

[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package.json'
       
       Require stack:
       - /home/berdachuk/.nvm/versions/node/v18.18.2/lib/node_modules/@ionic/cli/lib/project/index.js
       - /home/berdachuk/.nvm/versions/node/v18.18.2/lib/node_modules/@ionic/cli/lib/index.js
       - /home/berdachuk/.nvm/versions/node/v18.18.2/lib/node_modules/@ionic/cli/index.js
       - /home/berdachuk/.nvm/versions/node/v18.18.2/lib/node_modules/@ionic/cli/bin/ionic
[WARN] Error loading @capacitor/android package.json: Error: Cannot find module '@capacitor/android/package.json'
       
       Require stack:
       - /home/berdachuk/.nvm/versions/node/v18.18.2/lib/node_modules/@ionic/cli/lib/project/index.js
       - /home/berdachuk/.nvm/versions/node/v18.18.2/lib/node_modules/@ionic/cli/lib/index.js
       - /home/berdachuk/.nvm/versions/node/v18.18.2/lib/node_modules/@ionic/cli/index.js
       - /home/berdachuk/.nvm/versions/node/v18.18.2/lib/node_modules/@ionic/cli/bin/ionic

Ionic:

   Ionic CLI                     : 7.1.1 (/home/berdachuk/.nvm/versions/node/v18.18.2/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.5.0
   @angular-devkit/build-angular : 16.2.7
   @angular-devkit/schematics    : 16.2.7
   @angular/cli                  : 16.2.7
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.5.0
   @capacitor/android : not installed
   @capacitor/core    : 5.5.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.3

System:

   NodeJS : v18.18.2 (/home/berdachuk/.nvm/versions/node/v18.18.2/bin/node)
   npm    : 9.8.1
   OS     : Linux 6.2

**Comment by liamdebeasi** [comment] 2023-10-23 21:26
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. We changed chip to use a `min-height` instead of `height` to support [Dynamic Font Scaling](https://ionicframework.com/docs/layout/dynamic-font-scaling). This means that instead of clipping any elements which flow outside the bounds of the chip, the chip will now expand to accommodate the intrinsic size of its children.

If you install 7.4.4 and run your sample, you'll see that `ion-select` is actually being clipped by `ion-chip`: 

![image](https://github.com/ionic-team/ionic-framework/assets/2721089/3911b544-4b50-47f6-b1d6-c291681fcd5c)

This is incorrect because if you allow the select text to wrap you'll see that it actually gets cut off by the chip so it's no longer readable: 
![image](https://github.com/ionic-team/ionic-framework/assets/2721089/bc397141-4345-4704-86b0-2fb7f1a987ef)

With Ionic 7.5.0, you'll see that the long text remains readable:

![image](https://github.com/ionic-team/ionic-framework/assets/2721089/09e8923e-4d83-4483-989e-4307c9466ee5)

7.4.4 example: https://codepen.io/liamdebeasi/pen/jOdEBbY
7.5.0 example: https://codepen.io/liamdebeasi/pen/WNPbpQZ

-----

If this is not a behavior you want, you can override the min height of the `ion-select`. I don't recommend this since this may degrade the experience for users who want larger text: https://codepen.io/liamdebeasi/pen/qBgErZe. Let me know if you have any questions.

**Closed by liamdebeasi** 2023-10-23 21:26 UTC
Labels: triage

**Comment by berdachuk** [comment] 2023-10-23 22:28
Hi @liamdebeasi 
Thank you

**Comment by sberdachuk-epam** [comment] 2023-10-24 21:02
Hi @liamdebeasi please update related documentation on the https://ionicframework.com/docs/api/chip page.
Now it is hot clear that you changed chip to use a min-height instead of height
