### ISSUE TITLE
Bug : ios14 Page Transitions is slow

### ISSUE THREAD

**Issue by bhandaribhumin** [ionic-team/ionic-framework#21767] opened 2020-07-16 17:28 UTC
hey team, I am using ios14 beta and I realize when I navigate one page to another page "Page Transitions" is little solve to redirect to the next page!

![slow](https://user-images.githubusercontent.com/3336047/87702827-8c006480-c7b7-11ea-919d-3fc9dd47a672.gif)

**Comment by liamdebeasi** [comment] 2020-07-16 17:35
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/21613#issuecomment-648149256.

**Closed by liamdebeasi** 2020-07-16 17:35 UTC
Labels: triage
