### ISSUE TITLE
bug: unable to use nested routing using ion-content inside child view

### ISSUE THREAD

**Issue by daniel-zero** [ionic-team/ionic-framework#25172] opened 2022-04-22 08:46 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

When a nested view is used including `ion-content` inside the child view, the page will be rendered empty and no content from the child-page will be displayed.

![Screenshot 2022-04-22 at 10 44 32](https://user-images.githubusercontent.com/95087607/164652590-efe65725-b1f0-48f7-a7b8-54a1080ca4af.png)

### Expected Behavior

It should be possible to build and use nested router-views with `ion-content` used in the child views.

### Steps to Reproduce

**parent router definition**
```ts
const routes: Routes = [
  {
    path: '',
    component: HomePage,
    children: [
      {
        path: '',
        redirectTo: 'foo',
        pathMatch: 'full',
      },
      {
        path: 'foo',
        loadChildren: () =>
          import('../foo/foo.module').then((m) => m.FooPageModule),
      }
    ],
  },
];
```

**parent page**
```html
<ion-header>
  <ion-toolbar>
    <ion-title>Parent Page</ion-title>
  </ion-toolbar>
</ion-header>

<router-outlet></router-outlet>
```

**child page**
```html
<ion-content>
  <h1>Foo Page</h1>
</ion-content>
```

### Code Reproduction URL

https://github.com/daniel-zero/ionic-bug-router-outlet

### Ionic Info

Ionic:

   Ionic CLI                     : 6.19.0 (/Users/danielsogl/.nvm/versions/node/v16.14.2/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.1.2
   @angular-devkit/build-angular : 13.2.6
   @angular-devkit/schematics    : 13.2.6
   @angular/cli                  : 13.2.6
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.4.3
   @capacitor/android : not installed
   @capacitor/core    : 3.4.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v16.14.2 (/Users/danielsogl/.nvm/versions/node/v16.14.2/bin/node)
   npm    : 8.7.0
   OS     : macOS Monterey

**Comment by daniel-zero** [comment] 2022-04-22 08:56
One thing I also noticed. When using `ion-router-outlet` the child-page content is rendered but thew view will then ignore the already rendered `ion-header`



```html
<ion-header>
  <ion-toolbar>
    <ion-title>Parent Page</ion-title>
  </ion-toolbar>
</ion-header>

<ion-router-outlet></ion-router-outlet>
```

```html
<ion-content>
  <h1>Foo Page</h1>
</ion-content>
```

![Screenshot 2022-04-22 at 10 55 28](https://user-images.githubusercontent.com/95087607/164669588-68186a87-5409-4d4d-ac4f-67c251b40c20.png)

**Comment by liamdebeasi** [comment] 2022-04-22 13:24
Thanks for the issue. I am going to close this as this is not a bug in Ionic. I see a couple issues in your app:

1. You should be using `ion-router-outlet`. At this time you cannot mix and match `ion-router-outlet` and `router-outlet` usages.
2. The nested router outlet needs to be wrapped in an `ion-content`.

Making these two changes fix the issue for me.

**Closed by liamdebeasi** 2022-04-22 13:24 UTC
Labels: triage
