### ISSUE TITLE
bug: ion-datetime does not scroll month to selected date if date does not change

### ISSUE THREAD

**Issue by aparajita** [ionic-team/ionic-framework#28678] opened 2023-12-08 22:57 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

If the calendar is showing a month other the month of the selected date, and the same date is assigned to the selected date, the calendar does not scroll to the selected date.

This is unexpected behavior, as the intention in setting the selected date is not only to set the date but also scroll the calendar to that date, and inconsistent behavior because setting the selected date when it changes does scroll the calendar.

### Expected Behavior

The calendar should always scroll to the selected date, even if its value does not change.

### Steps to Reproduce

1. Go to https://stackblitz.com/edit/8d9oqr?file=src%2Fcomponents%2FExample.vue,package.json
2. Scroll to another month.
3. Click "Reset". The month does not scroll.
4. Click "Reset with fix". The month does scroll.

### Code Reproduction URL

https://stackblitz.com/edit/8d9oqr?file=src%2Fcomponents%2FExample.vue,package.json

### Ionic Info

Ionic:

   Ionic CLI : 7.1.5 (/Users/aparajita/Developer/projects/clients/willsub/apps-monorepo/node_modules/.pnpm/@ionic+cli@7.1.5/node_modules/@ionic/cli)

Capacitor:

   Capacitor CLI      : 5.5.1
   @capacitor/android : 5.5.1 (/Users/aparajita/Developer/projects/clients/willsub/apps-monorepo/node_modules/.pnpm/@capacitor+android@5.5.1_@capacitor+core@5.5.1/node_modules/@capacitor/android)
   @capacitor/core    : 5.5.1 (/Users/aparajita/Developer/projects/clients/willsub/apps-monorepo/node_modules/.pnpm/@capacitor+core@5.5.1/node_modules/@capacitor/core)
   @capacitor/ios     : 5.5.1 (/Users/aparajita/Developer/projects/clients/willsub/apps-monorepo/node_modules/.pnpm/@capacitor+ios@5.5.1_@capacitor+core@5.5.1/node_modules/@capacitor/ios)

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v21.2.0 (/Users/aparajita/Library/pnpm/nodejs/21.2.0/bin/node)
   npm    : 10.2.3
   OS     : macOS 13.6.1

### Additional Information

I can't think of a use case in which the intentional setting of the current date would not desire the month scrolling.

I was able to work around this by:

- Checking if the selectedDate is today.
- If so, set the selectedDate to tomorrow.
- In window.setTimeout(..., 0), set the selectedDate to today.

Kind of an ugly hack, and probably not desired.

**Comment by liamdebeasi** [comment] 2023-12-09 01:56
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The intent behind the "scroll to selected value" feature is to only run when the value of the datetime has changed.

As per the [Datetime docs](https://ionicframework.com/docs/api/datetime#setting-values-asynchronously), this behavior is designed for when the value of the datetime is set asynchronously (such as from an API callback). Datetime is working as intended because the sample application does not change the datetime's value.

**Closed by liamdebeasi** 2023-12-09 01:56 UTC
Labels: triage
