### ISSUE TITLE
bug:  in Ionic React, fallback routes do not work , cause issues with empty parameters on routes

### ISSUE THREAD

**Issue by davideshay** [ionic-team/ionic-framework#26971] opened 2023-03-15 16:04 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

If I have a set of routes that works fine if I start with the "main" page, or even if I directly navigate to a route with an ID -- say in my example "/gallery/5", things work fine.

If I then setup a fallback route, that redirects to the same main page, routing from that page to the gallery page which requires an ID is broken and no longer passes parameters.  It does indeed load the fallback route/page correctly, but navigation is broken from that point on.

### Expected Behavior

Fallback routes should work as they do in standard React Router v5, and not disrupt the operation of subsequent routes with parameters.

### Steps to Reproduce

1.   Use the code URL shown below.
2.   To show successful behavior, navigate to the root "/" of the project in the browser, (you will be redirected to "main" page via a history.push), then select on the gallery button. You should see 8 images shown. All works well.
3.   To show the unsuccessful behavior, navigate to an invalid route, i.e. "/zzz". It wll successfully fall-back to the main page, but the button to take you to the gallery will take you to an empty page. You will see several errors in the console, as well as the console.log of the "params" object from useParams. This object is now empty, but in step 2 of above it correctly extracts the route parameters.

### Code Reproduction URL

https://stackblitz.com/edit/angular-bkt8gs?file=src/App.tsx

### Ionic Info

Cannot run from stackblitz.

**Comment by liamdebeasi** [comment] 2023-03-17 19:51
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/23743.

**Closed by liamdebeasi** 2023-03-17 19:51 UTC
Labels: triage
