### ISSUE TITLE
bug: navCtrl.pop not working

### ISSUE THREAD

**Issue by EinfachHans** [ionic-team/ionic-framework#25860] opened 2022-08-31 10:35 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

In an app we have a page with a tob tab bar, where i added a back button (as a tab button) via the usage of `navCtrl.pop()` - This button sometimes doesn't work when we opened our detail page from there - See linked repo & attached steps 

### Expected Behavior

The button/ the `.pop()` function should work always

### Example 1
1. Click in the Home Tab on the **forward** button
2. Click the back button

### Example 2
1. Click in the Home Tab on the **forward** button
2. Click the **Detail** button
4. Click the back button
5. Click on another tab at the top
6. Click the back button

## Not Working
1. Click in the Home Tab on the **forward** button
2. Click the **Detail** button
3. Click the back button
4. Click the back button

### Code Reproduction URL

https://github.com/EinfachHans/ionic-nav-ctrl-bug

### Ionic Info

Ionic:

   Ionic CLI                     : 6.20.1 (/Users/hans/.nvm/versions/node/v16.14.2/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.2.4
   @angular-devkit/build-angular : 14.2.1
   @angular-devkit/schematics    : 14.2.1
   @angular/cli                  : 14.2.1
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 4.1.0
   @capacitor/android : not installed
   @capacitor/core    : 4.1.0
   @capacitor/ios     : not installed

Utility:

   cordova-res (update available: 0.15.4) : 0.15.1
   native-run                             : 1.6.0

System:

   NodeJS : v16.14.2 (/Users/hans/.nvm/versions/node/v16.14.2/bin/node)
   npm    : 8.6.0
   OS     : macOS Monterey

**Comment by liamdebeasi** [comment] 2022-08-31 13:29
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/18593.

There is a dev build with a proposed fix in https://github.com/ionic-team/ionic-framework/issues/18593#issuecomment-1232063849.

**Closed by liamdebeasi** 2022-08-31 13:29 UTC
Labels: triage
