### ISSUE TITLE
bug: stencil async task queue causes scroll position to be reset

### ISSUE THREAD

**Issue by NiklasMerz** [ionic-team/ionic-framework#22775] opened 2021-01-15 14:36 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

The issue is kind of hard to describe better check the steps to reproduce. I have a page with many items and a button at the bottom. When I click the button an object bound to the items changes and the page scrolls to the top.

I think these changes may have caused this: 

https://github.com/ionic-team/ionic-framework/pull/22489
https://github.com/ionic-team/ionic-framework/pull/22180

**Expected behavior:**

I would not expect the scroll position to change in this case. We have large forms with many inputs and some of them trigger a refresh to get data from the server. If a refresh runs the data gets updated and the page scrolls to the top. This is very bad UX because the user cannot continue to fill in the form where they left off.

**Steps to reproduce:**

- Go to my test page: https://ionicreproscroll.web.app
- Scroll to bottom and click refresh button
- Items should change and scroll to top

**Related code:**

Test Page: https://ionicreproscroll.web.app

Repo for test page: https://github.com/NiklasMerz/scroll-repro

**Other information:**
The issue appeared after updating ionic to the latest version. I cannot reproduce this issue with Version 5.4.0 and below which indicates that the PRs linked above started to introduce the issue in version 5.4.1.

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.12.3 (/Users/niklasmerz/.nvm/versions/node/v12.14.1/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.5.2
   @angular-devkit/build-angular : 0.1000.8
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Utility:

   cordova-res (update available: 0.15.2) : 0.9.0
   native-run (update available: 1.3.0)   : 0.3.0

System:

   NodeJS : v12.14.1 (/Users/niklasmerz/.nvm/versions/node/v12.14.1/bin/node)
   npm    : 6.14.10
   OS     : macOS Catalina
```

**Comment by liamdebeasi** [comment] 2021-01-15 16:23
Thanks for the issue. Could your confirm when you started noticing this issue? I can see this behavior happen in Ionic Framework v5.4.0 on both Chrome and Safari.

**Comment by NiklasMerz** [comment] 2021-02-03 08:45
I went back to Ionic version 5.3.2 and the issue was gone again. Anything I can do about that? I am not really sure where to look in Ionics code.

**Comment by liamdebeasi** [comment] 2021-02-03 14:41
This issue seems to happen because we created a new stacking context in https://github.com/ionic-team/ionic-framework/blob/master/core/src/components/content/content.scss#L103. Unfortunately, we cannot revert this change since it would re-introduce a performance issue in WebKit.

I am still trying to determine if this is a WebKit bug or something else.

**Comment by NiklasMerz** [comment] 2021-02-03 14:44
Alright, that's what I though as well. I just have no idea how this works and how to isolate this issue. Let me know if I can help with something.

Thank you for your effort. I am a huge fan of your WebKit bug reports ;).

**Comment by NiklasMerz** [comment] 2021-02-09 08:08
Possibly this is not a WebKit bug. I can see the same issue in Firefox and Chrome with my repro: https://ionicreproscroll.web.app/home

**Comment by liamdebeasi** [comment] 2021-02-09 14:18
Does the issue still appear in 5.3.2 in Firefox and Chrome?

**Comment by NiklasMerz** [comment] 2021-02-09 15:09
That's kind of strange. I downgraded https://ionicreproscroll.web.app/home to 5.3.2 now. The issue appears on Chrome, FF and Safari on Mac. Safari on iOS does not show the issue.

Looks like iOS and desktop work differently but I would consider the behavior in Safari on iOS with Ionic 5.3.2 correct. The page should not scroll.

**Comment by selected-pixel-jameson** [comment] 2021-03-06 12:21
This bug still exists  using any version of @ionic/core greater than 5.4.1, including the latest version (5.6.0) which claims this has been fixed. 

This DOESN'T happen on the following:
- Chrome
- Brave
- Android Native App
- Edge

This DOES happen on the following:
- iOS Native
- Safari Desktop
- Firefox


This is my package file: 
```
    "@angular/animations": "^9.1.12",
    "@angular/cdk": "^9.2.1",
    "@angular/common": "^9.1.12",
    "@angular/core": "^9.1.12",
    "@angular/forms": "^9.1.12",
    "@angular/material": "^9.2.4",
    "@angular/platform-browser": "^9.1.12",
    "@angular/platform-browser-dynamic": "^9.1.12",
    "@angular/router": "^9.1.12",
    "@capacitor-community/facebook-login": "^1.0.1",
    "@capacitor/android": "^2.4.4",
    "@capacitor/core": "^2.4.4",
    "@capacitor/ios": "^2.4.4",
    "@ionic-native/core": "^5.30.0",
    "@ionic-native/in-app-purchase-2": "^5.30.0",
    "@ionic-native/native-storage": "^5.30.0",
    "@ionic-native/splash-screen": "^5.30.0",
    "@ionic-native/status-bar": "^5.30.0",
    "@ionic/angular": "^5.6.0",
    "@ionic/core": "^5.6.0",
    "@ionic/pwa-elements": "^1.5.1",
    "@types/jquery": "^3.5.1",
    "capacitor-apple-login": "git+https://github.com/rlfrahm/capacitor-apple-login.git",
    "capacitor-branch-deep-links": "^3.0.0",
    "capacitor-rate-app": "0.0.2",
    "cc.fovea.cordova.purchase": "^10.1.1",
    "cordova-plugin-nativestorage": "^2.3.2",
    "core-js": "^2.5.4",
    "moment": "^2.27.0",
    "ngx-braintree": "^8.0.0",
    "ngx-ionic-image-viewer": "^0.7.1",
    "ngx-moment": "^4.0.1",
    "ngx-swiper-wrapper": "^9.0.1",
    "onesignal-cordova-plugin": "^2.11.0",
    "rxjs": "~6.5.1",
    "smoothscroll-polyfill": "^0.4.4",
    "tslib": "^1.9.0",
    "uuid": "^8.1.0",
    "zone.js": "~0.9.1"
```
Maybe I'm missing something to get 5.6.0 to fix the issue. In any case this is a huge UX issue for the iOS version of my app.

**Comment by selected-pixel-jameson** [comment] 2021-03-09 14:27
I'm just curious if this is something that is being worked on, I don't see an attached PR. Or if there is a suggested work around for this issue at all? Maybe I'm doing something wrong, but this seems like a rather large issue that has now existed for 5 months or so. I'm honestly surprised more people haven't reported this issue. So maybe I am doing something wrong or out of the ordinary??

It's a hard thing to have to decide between iOS performance issues or a pretty dramatic UX issue. Just trying to figure out how to explain this one to my client or resolve it through a workaround. 

Thank you for the continued development of the Ionic Framework.

**Comment by liamdebeasi** [comment] 2021-03-09 16:46
There is no fix in the works at the moment. The issue seems to be in this commit: https://github.com/ionic-team/ionic-framework/commit/c83826aa733594cf8041e34d5b4832907d7bc530 But beyond that I have not been able to isolate anything else.

**Comment by selected-pixel-jameson** [comment] 2021-04-05 14:31
Does the Ionic team have any intention to fix this issue? This is preventing updating past version 5.4.1.

**Comment by selected-pixel-jameson** [comment] 2021-04-17 10:16
This is still an issue in version 5.6.4. 

@NiklasMerz Are you still seeing this issue? Did you find a work-around?

**Comment by NiklasMerz** [comment] 2021-04-17 10:29
Unfortunately not yet. I use an older version of Ionic. Would love to see this fixed but I could not find a solution in Ionics code myself.

**Comment by selected-pixel-jameson** [comment] 2021-04-23 09:06
@NiklasMerz The thing that I don't get is how we seem to be the only two people who are having this issue....  The UX paradigm which causes this issue seems like a pretty common scenario. Indicator on a list item -> View Detail -> Remove Indicator on List Item. This is how every email application works.

**Comment by selected-pixel-jameson** [comment] 2021-04-29 14:21
@liamdebeasi Is there anyway to get this prioritized? I've been unable to update the version of Ionic I'm using for 6 months now. Are there  any directions on how I could go about building a local version of the Ionic framework to attempt to debug this and submit a PR? Or should I just dive in? I'm not trying to be annoying or difficult. Sorry if it's coming off that way, but this is a major issue for my clients application, which has a pretty significant App Store presence.

**Comment by liamdebeasi** [comment] 2021-04-29 16:26
I did some more digging and was able to identify the change that caused this issue. Stencil has a "task queue" that schedules DOM reads and writes across frames to efficiently render and reduce layout thrashing.

In Stencil 1, the task queue used the `congestionAsync` setting. This was great for apps running animations and CPU intensive tasks as it split up tasks across multiple frames, but introduced unnecessary performance hits at startup. In Stencil 2, the task queue used the `async` setting which just schedules tasks in the next frame to prevent layout thrashing.

The Stencil team does not have plans to change the default from `async` back to `congestionAsync` and I do not think it would be good for Ionic Framework to change it either as the previous performance issues would be re-introduced. I am working with the Stencil team to try and improve the `async` task queue to help avoid the issue noted in this thread. Thanks!

**Comment by selected-pixel-jameson** [comment] 2021-04-29 16:35
@liamdebeasi Thank you for the update. I understand that this is complicated and that there are many working parts. Do you have any suggestions for potential works arounds? Being able to flag content in large lists as viewed / updated within our app is absolutely necessary. With this bug it takes users back to the top of really long lists so it would be a huge hinderance and would make certain portions of our application impractical.

**Comment by liamdebeasi** [comment] 2021-04-29 16:48
Where the issue is in how Stencil manages the task queue, I am not aware of a good workaround currently other than staying on an older version of Ionic Framework. I am going to continue investigating a fix and will post an update here when I have more to share.

**Comment by ralscha** [comment] 2021-05-16 06:53
Same problem here. Everything works fine with 5.6.7 on Chrome but on iOS it always scrolls to the top. Had to go back to 5.4.1, which works fine for me on iOS and Android (it's a Capacitor app).

**Comment by liamdebeasi** [comment] 2021-05-26 18:42
Hello! So we figured out what the issue is. While the issue is more visible now that we are using the `async` queue, the bug is not in Stencil/Framework.

I was able to reproduce this in React and Vue as well. The problem in Angular is that if you aren't using `trackBy`, Angular has no way of giving elements in a list a stable identity. As a result, when you "refresh" the list, Angular destroys all of the DOM nodes and re-creates them, but since Stencil adds the styles in after the elements have been re-added to the DOM, the scroll position gets reset to the top since the `ion-item` dimensions have changed.

Note that that identifier you provide must not change. So in the demo app that was originally provided, the `'Field ' + i` value should not be used as an identifier since that value will change. As a result, we recommend creating an object with a `key` that is the index in your for-loop and your `value`:

**app.component.html**
```html
<ion-item *ngFor="let field of fields;trackBy:trackId">
    {{field.value}}
 </ion-item>
```

**app.component.ts**
```typescript
trackId(index: number, fieldObject: any) {
  return fieldObject.id;
} 
```

We are going to note this in the docs since we think it is an import point to note. I will close this issue out when the docs have been released. Thanks!

**Comment by selected-pixel-jameson** [comment] 2021-05-26 19:10
OMG! I think that you are right. I will try this out on the code as soon as I get a chance. Super pumped that we'll finally be able to updated. Thank you!

**Comment by liamdebeasi** [comment] 2021-05-27 13:58
Hi everyone,

We recently shipped updated performance docs which talk about using loops with Ionic components, so I am going to close this thread out since the issue has been resolved. Thanks for the report!

Angular: https://ionicframework.com/docs/angular/performance
Vue: https://ionicframework.com/docs/vue/performance
React: https://ionicframework.com/docs/react/performance

(Docs just deployed, so may need to do a hard refresh on some of these pages).

**Closed by liamdebeasi** 2021-05-27 13:58 UTC
Labels: type: bug

**Comment by NiklasMerz** [comment] 2021-05-27 14:16
Thank you for helping with this and the great documentation. `trackBy` etc. are probably the optimal solution for many apps.

We actually want to recreate every list item in our app. Each item contains a slightly more complex component that should initialize with new data. I need to try a few things to see if this is working for us.
