### ISSUE TITLE
bug: SCSS Variables not updating with dark theme

### ISSUE THREAD

**Issue by wiggitamoo** [ionic-team/ionic-framework#21752] opened 2020-07-14 22:08 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

Variables used in scss take the light theme of the variable.

If the variable below is referenced, then it uses the light theme for the value.
```
color: var(--ion-color-light);
```

**Expected behavior:**

The variable should display the color specified in the variables.scss file depending on the selected theme.

If dark theme is selected it should use something similar to: 
```
  --ion-color-light: #222428;
```

if the light theme is selected it should use a value similar to:
```
  --ion-color-light: #f4f5f8;
```

**Steps to reproduce:**

Add a variable in scss that should change with the dark theme

For example: 

```
border: rgba(var(--ion-color-light-rgb), 0.5) solid medium;
or
color: var(--ion-color-dark);
```

**Comment by liamdebeasi** [comment] 2020-07-15 13:15
Thanks for the issue. How are you switching between dark/light mode? The browser handles dark mode detection via the `prefers-color-scheme: dark` media query, so any issues you are seeing are unlikely to be Ionic Framework related.

**Comment by wiggitamoo** [comment] 2020-07-15 13:58
Yes, I am using the default **prefers-color-scheme** media query that comes shipped with Ionic 5, dark mode is working as expected. 

The problem is, when I reference a variable using `var()`, as described in the issue, the light and dark colors don't change with the theme; rather they maintain the color described under `:root {}` in the **variables.scss** file. 

Is this intended behavior?

**Comment by liamdebeasi** [comment] 2020-07-15 14:13
Can you send over a full repo? I will take a look.

**Comment by wiggitamoo** [comment] 2020-07-15 15:53
I put a simple example together here.

https://github.com/wiggitamoo/ionic-5-dark-mode-issue

Thanks!

**Comment by liamdebeasi** [comment] 2020-07-15 16:17
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. From what I am seeing, you set `--ion-color-dark: #222428` on `:root`, and then you set `--ion-color-dark: #f4f5f8;` in your `browser-dark` mixin, but your mixin is never used. This is likely why you are not seeing the CSS Variable updating.

**Closed by liamdebeasi** 2020-07-15 16:17 UTC
Labels: triage

**Comment by wiggitamoo** [comment] 2020-07-15 17:45
Good catch, I now notice a typo I made regarding the browser-dark mixin. Now working as expected, thanks!
