### ISSUE TITLE
bug: this.platform.is('tablet') showing as `true` for pixel 4 XL

### ISSUE THREAD

**Issue by tmk1991** [ionic-team/ionic-framework#21753] opened 2020-07-15 02:02 UTC
# Bug Report

**Ionic version:**
[X] **4.x**

**Current behavior:**this.platform.is('tablet') showing as `true` for pixel 4 XL

**Expected behavior:**

Pixel 4 XL is not a tablet

**Steps to reproduce:**
this.platform.is('tablet') showing as `true` for pixel 4 XL

Same as https://github.com/ionic-team/ionic-framework/issues/15434

**Comment by liamdebeasi** [comment] 2020-07-15 13:12
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/19737. It is not possible for us to cover 100% of devices with platform detection, so we have opted to give developers a way of overriding/extending our functions.

**Closed by liamdebeasi** 2020-07-15 13:12 UTC
Labels: triage
