### ISSUE TITLE
bug: ion-button expand option not working correctly

### ISSUE THREAD

**Issue by SaroGFX** [ionic-team/ionic-framework#26565] opened 2023-01-05 12:22 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [ ] v6.x
- [ ] Nightly

### Current Behavior

Currently both the `expand='full'` and `expand='block'` will make it full with. Only the border radius changes.

<img width="791" alt="Screenshot 2023-01-05 at 13 16 31" src="https://user-images.githubusercontent.com/3781800/210778541-bf565688-2a12-46b6-a8da-b9d109f4efbc.png">

### Expected Behavior

It should not be full width for the `block` property and It shouldn't affect the border radius.

### Steps to Reproduce

```html
<ion-button expand="block">Block</ion-button>
<ion-button expand="full">Full</ion-button>
```

### Code Reproduction URL

https://stackblitz.com/run?file=src%2Fapp%2Fapp.component.ts

### Ionic Info

Ionic:

   Ionic CLI       : 6.20.3 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 6.2.7

Capacitor:

   Capacitor CLI      : 4.1.0
   @capacitor/android : 4.1.0
   @capacitor/core    : 4.1.0
   @capacitor/ios     : 4.1.0

Utility:

   cordova-res                          : 0.15.4
   native-run (update available: 1.7.1) : 1.6.0

System:

   NodeJS : v16.14.0 (/usr/local/bin/node)
   npm    : 8.3.1
   OS     : macOS

**Comment by liamdebeasi** [comment] 2023-01-05 16:35
Thanks for the report. Can you clarify your expected behavior? The reported behavior is stated in the docs for the `expand` property:

> Set to "block" for a full-width button or to "full" for a full-width button with square corners and no left or right borders.

In other words, both values are designed to make the `ion-button` full width. By default, the `ion-button` has a border radius, so the `'full'` option also removes the border radius.

**Comment by liamdebeasi** [comment] 2023-01-09 14:07
"inline block" is referring to the value for the [CSS display property](https://developer.mozilla.org/en-US/docs/Web/CSS/display), not the `block` value in Ionic's `expand` property

**Comment by SaroGFX** [comment] 2023-01-09 14:16
Ah yes, I misinterpreted `block` with it being inherently inline. But it is not, my bad. Maybe it can be a bit clearer when there is also a prop value for the default e.g. `expand= inline` as this is also the case with some the other options.

**Comment by liamdebeasi** [comment] 2023-01-09 14:19
Would it help if we changed the documentation something a bit clearer? Possible wording:

> This property lets you specify how wide the button should be. By default, buttons have `display: inline-block`, but setting this property will change the button to a full-width element with `display: block`.

**Comment by liamdebeasi** [comment] 2023-01-09 14:35
I think the intent around "full" is that it visually is supposed to expand the full width of a page (i.e. not be able to see the edges of the button).

**Comment by SaroGFX** [comment] 2023-01-09 14:54
Thank you for following up. I think that is clear now, however the difference between full and expand appears to only be the border radius. So maybe in a future version, it could be more appropriate for it to be included as e.g. `shape='sharp'` instead. And scrap the `expand='block'` option and only keep 'expand="full"'. Bit of a breaking change recommendation, so I don't expect this to change ;)

**Comment by liamdebeasi** [comment] 2023-01-10 13:58
Thanks for the feedback! I do agree that the naming is a bit confusing. However, we likely will not change the values due to that being a breaking change (as you noted). We will definitely keep this feedback in mind as we move forward though. If more developers mention that these value names are confusing, it may make sense to change the names.

I am going to close this as I merged a clarification to the behavior of `expand` in https://github.com/ionic-team/ionic-docs/pull/2693. Let me know if you have any questions.

**Closed by liamdebeasi** 2023-01-10 13:58 UTC
Labels: triage
