### ISSUE TITLE
bug: deprecated findDOMNode usage with React.StrictMode

### ISSUE THREAD

**Issue by turbothinh** [ionic-team/ionic-framework#20972] opened 2020-04-05 15:49 UTC
# Bug Report

**Ionic version:**
[x] **4.x**
"@ionic/react": "^5.0.7"

**Current behavior:**

I am trying to install Ionic React to a fresh create-react-app but hit the error 
> findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of IonComponent which is inside StrictMode
quite a lot. I notice that if I create the app with `ionic start`, it won't notice because the `<App />` component is not wrapped inside `React.StrictMode`. Does that mean that you guys don't support StrictMode right now, what is the plan for Ion components to work with `StrictMode`?

**Expected behavior:**

Avoid using `findDOMNode` to refer to an element, hence not getting this error on React Strict mode

**Steps to reproduce:**

1. Create a React app with `create-react-app`
2. Make sure `<App />` component is wrapped inside `React.StrictMode`
3. Create a component with `IonReactRouter`
```
import React, { FC } from 'react';
import { IonApp, IonRouterOutlet } from '@ionic/react';
import { IonReactRouter } from '@ionic/react-router';
import { Redirect, Route } from 'react-router-dom';
import { Home } from './pages/home';
import { About } from './pages/about';
import { Error } from './pages/error';

export const Router: FC = ({ children }) => (
	<IonApp>
		<IonReactRouter>
			<IonRouterOutlet>
				<Route path="/" exact component={Home} />
				<Route path="/about" exact component={About} />
				<Route path="/404" exact component={Error} />
				<Route path="/contact" render={() => <Redirect to="/error" />} exact={true} />
			</IonRouterOutlet>
			{children}
		</IonReactRouter>
	</IonApp>
);
```
or
```
import React from 'react';
import { IonTabBar, IonIcon, IonLabel, IonTabButton } from '@ionic/react';
import { home, callOutline, informationCircleOutline } from 'ionicons/icons';

export const Tabbar = () => (
	<IonTabBar slot="bottom">
		<IonTabButton tab="home" href="/home">
			<IonIcon icon={home} />
			<IonLabel>Home</IonLabel>
		</IonTabButton>
		<IonTabButton tab="about" href="/about">
			<IonIcon icon={informationCircleOutline} />
			<IonLabel>About</IonLabel>
		</IonTabButton>
		<IonTabButton tab="contact" href="/contact">
			<IonIcon icon={callOutline} />
			<IonLabel>Contact</IonLabel>
		</IonTabButton>
	</IonTabBar>
);
```

4. Run `yarn start`
5. Check browser console

![image](https://user-images.githubusercontent.com/14198542/78502954-fe4abd00-7763-11ea-9f22-93d694c25f0c.png)

**Comment by kiily** [comment] 2020-04-10 22:31
I can reproduce this error exactly in a clean repo. I created it with CRA (which now wraps the app in `React.StrictMode` and this immediately fails. I followed an even simpler implementation than found here: https://dev.to/ionic/adding-ionic-react-to-an-existing-react-project-4kib

I have isolated this in a template repo, https://github.com/kiily/react-ts-pwa-ionic-capacitor, you can checkout the `feat-ionic-react` branch for the relevant implementation.

Additionally feel free to use this as a template to reproduce issues related to CRA apps using Ionic React and Capacitor (there were added manually instead of creating the app with the Ionic CLI).

**Comment by peterennis** [comment] 2020-05-15 01:42
Related: https://github.com/ant-design/ant-design/issues/22493

**Comment by vimaleurakaa** [comment] 2020-06-04 14:42
+1 Happens same thing to me

**Comment by peterpeterparker** [comment] 2020-07-02 05:49
The same error in material-ui: https://github.com/mui-org/material-ui/issues/13394

**Comment by GabrielMajeri** [comment] 2020-08-18 16:42
The problematic line is in `createComponent.tsx`:

https://github.com/ionic-team/ionic-framework/blob/c171ccbd37c1ee4b4934758a3a759170ff357cb2/packages/react/src/components/createComponent.tsx#L38

It uses the `findDOMNode` API, [which is discouraged from use](https://reactjs.org/docs/react-dom.html#finddomnode).

**Comment by mlynch** [comment] 2020-09-12 00:33
Just acknowledging we're aware of this issue. Just hit it myself adding Ionic React to an existing React app. Technically, it's a warning as functionality is not impacted, but regardless we need to fix it to avoid the future breaking change.

**Comment by peterpeterparker** [comment] 2020-11-12 07:30
@mlynch it's been two months since your msg and seven since the issue was opened, therefore, may I ask what's the status? is there any workaround? something blocker?  any hints?

**Comment by turbothinh** [comment] 2020-11-12 08:42
Sorry that I have missed some communications here. My workaround was to not use React in Strict mode. :(

**Comment by bard** [comment] 2020-11-22 14:45
I see there's been for a couple of months [a PR pending review](https://github.com/ionic-team/ionic-framework/pull/21932) which claims to fix the issue. Is anything blocking it? It's really easy to miss important things in the console when it's being spammed by the `findDOMNode` errors.

**Comment by GabrielMajeri** [comment] 2020-11-25 21:08
The PR (https://github.com/ionic-team/ionic-framework/pull/21932) has been merged :tada:

**Comment by elylucas** [comment] 2020-11-25 21:22
Thanks all for your patience on this one, and thanks @GabrielMajeri for the pull request! The fix will be in the release.

**Closed** 2020-11-25 21:21 UTC
Labels: package: react
