### ISSUE TITLE
bug: reorder handle in item wraps like text

### ISSUE THREAD

**Issue by Jodelopa** [ionic-team/ionic-framework#28761] opened 2023-12-27 13:09 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

After patch 7.6 there is a different behaviour of the reorder handle in an Item with a checkbox as content. 
If width is not sufficient for the label text, it wraps to a new line with the label.

### Expected Behavior

Handle stays in place and only the label warps to new line

### Steps to Reproduce

source example provided

### Code Reproduction URL

https://stackblitz.com/edit/l3ahfh?file=src%2Fmain.tsx

### Ionic Info

ionic 7.6.2

**Comment by liamdebeasi** [comment] 2024-01-02 21:25
Thanks for the issue. I am going to close this as a duplicate of #28769.

**Closed by liamdebeasi** 2024-01-02 21:25 UTC
Labels: holiday triage
