### ISSUE TITLE
bug: ion-datetime reset function doesn't work properly for time zones with 30 and 45 minutes

### ISSUE THREAD

**Issue by cconti1** [ionic-team/ionic-framework#25112] opened 2022-04-13 12:04 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

We use the reset function to allow the user to set the time to the current time. 

This functionality doesn't seem to work for timezones that have 30 or 45 minutes, like India that is GMT+05:30.
The reset function will set the time to be GMT+05:00.

List of countries with time zones that have 30 or 45 minutes [here](https://www.timeanddate.com/time/time-zones-interesting.html).

You can reproduce the issue in your web page as well, setting the computer time zone to India (or any of the countries with 30/45 minutes time zones) and see that the clear button for time will reset the time to GMT+05:00 instead of GMT+05:30.

### Expected Behavior

The reset function should reset the time to the current browser time in ant time zone

### Steps to Reproduce

Set the browser to any time zone that has 30/45 minutes in it, for example India that is GMT+05:30.
Go to the ionic doc for ion-datetime https://ionicframework.com/docs/api/datetime
Try the reset function or the clear button that should reset the time to the current time of the browser.
You will see time is set to GMT+05:00 and not GMT+05:30.

### Ionic Info

Ionic:

   Ionic CLI                     : 5.4.16 
   Ionic Framework               : @ionic/angular 6.0.8
   @angular-devkit/build-angular : 13.3.0
   @angular-devkit/schematics    : 13.2.3
   @angular/cli                  : 13.3.0
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI   : 3.2.0
   @capacitor/core : 3.4.3

Cordova:

   Cordova CLI       : not installed
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed
   native-run  : 1.5.0

System:

   NodeJS : v16.13.2
   npm    : 8.1.2
   OS     : macOS Monterey
   Xcode  : Xcode 13.3 Build version 13E113

**Comment by liamdebeasi** [comment] 2022-04-13 12:58
Thanks for the issue. What browser are you testing this in? I am testing this in Chrome and am unable to reproduce the behavior described here.

**Comment by cconti1** [comment] 2022-04-13 13:17
I'm with Chrome too
Version 100.0.4896.88 (Official Build) (arm64)
Just tried again and reproduced it again. I set my timezone to India and click the reset time in the demo https://ionicframework.com/docs/api/datetime

![Screen Shot 2022-04-13 at 6 43 59 PM](https://user-images.githubusercontent.com/39490048/163188720-602a7f65-d3b3-4360-bab5-ab37489e53e9.png)

**Comment by liamdebeasi** [comment] 2022-04-13 16:37
Thanks, I can reproduce this. The issue is that we do not account for 30 or 45 minute timezones as the original issue states. In the following code, we also need to call `setMinutes` and add the minute remainder from the timezone offset: https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/datetime/utils/data.ts#L30

Can you try the following dev build and let me know if it resolves the issue?

```
6.1.1-dev.11649867515.1fbce32f
```

This dev build is applicable to any Ionic package (`@ionic/angular`, `@ionic/vue`, etc).

Example:

```
npm install @ionic/angular@6.1.1-dev.11649867515.1fbce32f
```

**Comment by cconti1** [comment] 2022-04-14 08:29
Thank you so much, the fix seems working fine. 
I didn't mentioned that earlier, but the issue would effect the date too, when resetting it just after midnight, it would have shown the previous date. 
The build provided seems to fix both scenarios for us. 

When will that be released? So we can make sure we upgrade our ionic/angular dependency

**Comment by liamdebeasi** [comment] 2022-04-14 13:18
We do not provide release dates ahead of time. However, a patch is typically released in the next version of Ionic once it has been merged into `main`.

**Comment by liamdebeasi** [comment] 2022-04-14 17:09
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/25120, and a fix will be available in an upcoming release of Ionic Framework.

**Closed** 2022-04-14 17:09 UTC
Labels: package: core, type: bug
