### ISSUE TITLE
bug: ion-datetime jumps to 00 when hour is higher than 12

### ISSUE THREAD

**Issue by mbakker96** [ionic-team/ionic-framework#22267] opened 2020-10-07 09:23 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
when the hour is larger than 12 hours and you click on another hour it jumps to '00:xx'. 

**Expected behavior:**
When the hour has the selected value 14 and you click on 13, it should jump to 13. 

**Steps to reproduce:**
Place an ion-date component with format `HH:mm`. Active the date picker and press one hour above the selected hour. 

**Related code:**

```
<ion-datetime style="border: 1px solid black" displayFormat="HH:mm" [ngClass]="{error: inError}"></ion-datetime>
```

**Other information:**
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/10044261/95312605-7028ce00-088f-11eb-9d84-04ca404f8332.gif)

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.11.9 (/Users/martijn/.nvm/versions/node/v10.22.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.3.4
   @angular-devkit/build-angular : 0.1000.8
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Utility:

   cordova-res                          : 0.15.1
   native-run (update available: 1.2.1) : 1.1.0

System:

   NodeJS : v10.22.0 (/Users/martijn/.nvm/versions/node/v10.22.0/bin/node)
   npm    : 6.14.6
   OS     : macOS Big Sur
```

**Comment by liamdebeasi** [comment] 2020-10-07 13:26
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/22149 (same underlying issue). This issue has been resolved and should be available in an upcoming release of Ionic Framework.

**Closed by liamdebeasi** 2020-10-07 13:26 UTC
Labels: triage
