### ISSUE TITLE
bug: swipe to go back not working on iOS

### ISSUE THREAD

**Issue by anuragnagardeveloper** [ionic-team/ionic-framework#19558] opened 2019-10-06 17:05 UTC
swipe back not working in ios. we have to use back button on toolbar in order to navigate back to previous page.

**Comment by liamdebeasi** [comment] 2019-10-07 13:35
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/19491.

**Comment by liamdebeasi** [comment] 2019-10-07 13:36
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?

**Comment by eternityBUG** [comment] 2019-10-08 15:20
It happened to me, too

**Comment by eternityBUG** [comment] 2019-10-09 01:58
swipe to go back
Slide back now needs to slide two-thirds of the way back

**Comment by liamdebeasi** [comment] 2019-10-09 19:07
Hmm can you provide an example of this happening? I am still seeing the gesture needing to go 1/2 of the way back.

**Comment by anuragnagardeveloper** [comment] 2019-10-14 16:09
steps to reproduce:
Step1 : ionic start app1 --type=react (choose conference from option)
Step2 : ionic serve 
Here the swipe back feature not working which is a main feature of ios app

**Comment by liamdebeasi** [comment] 2019-10-14 16:16
Thanks for the follow up. Looks like the react ionic conference app is using an old version of @ionic/react (and therefore an old version of @ionic/core). One of our other team members is working on updating the react ionic conference app with the latest version of @ionic/react.

For now, can you give swipe to go back a try with one of the other starters (blank, tabs, sidemenu, etc)?

**Comment by anuragnagardeveloper** [comment] 2019-10-14 16:38
Hi 
I am using the following but it is throwing error  "Type '{ children: Element[]; id: string; swipeGesture: string; }' is not assignable to type 'IntrinsicAttributes & Pick<IonicReactExternalProps<IonRouterOut"
 


<IonApp>
    <IonReactRouter>
      <IonSplitPane contentId="main">
        <Menu appPages={appPages} />
        <IonRouterOutlet id="main" swipeGesture="true">
          <Route path="/home" component={Home} exact={true} />
          <Route path="/home/list" component={List} exact={true} />
          <Route exact path="/" render={() => <Redirect to="/home" />} />
        </IonRouterOutlet>
      </IonSplitPane>
    </IonReactRouter>
  </IonApp>

**Comment by anuragnagardeveloper** [comment] 2019-10-14 16:45
Type '{ children: Element[]; id: string; swipeGesture: string; }' is not assignable to type 'IntrinsicAttributes & Pick<IonicReactExternalProps<IonRouterOut


  <IonApp>
    <IonReactRouter>
      <IonSplitPane contentId="main">
        <Menu appPages={appPages} />
        <IonRouterOutlet id="main" swipeGesture="true">
          <Route path="/home" component={Home} exact={true} />
          <Route path="/home/list" component={List} exact={true} />
          <Route exact path="/" render={() => <Redirect to="/home" />} />
        </IonRouterOutlet>
      </IonSplitPane>
    </IonReactRouter>
  </IonApp>

**Comment by anuragnagardeveloper** [comment] 2019-10-14 16:46
IonApp
    <IonReactRouter>
      <IonSplitPane contentId="main">
        <Menu appPages={appPages} />
        <IonRouterOutlet id="main" swipeGesture="true">
          <Route path="/home" component={Home} exact={true} />
          <Route path="/home/list" component={List} exact={true} />
          <Route exact path="/" render={() => <Redirect to="/home" />} />
        </IonRouterOutlet>
      </IonSplitPane>
    </IonReactRouter>
  /IonApp

**Comment by anuragnagardeveloper** [comment] 2019-10-14 17:29
I have also tried the following in sidemenu app but still swipe back not working

import {setupConfig} from '@ionic/core'
setupConfig({
  swipeBackEnabled:true
});

**Comment by anuragnagardeveloper** [comment] 2019-10-21 17:40
Hey

Any update on this?

**Comment by liamdebeasi** [comment] 2020-06-25 20:54
Thanks for the issue. Is this still an issue with the latest version of Ionic Framework? If so, please provide a repo with the code required to reproduce this issue.

**Closed** 2020-07-09 21:30 UTC
Labels: needs: reply
