### ISSUE TITLE
feat: scroll to selected item in ion-select

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/ionic-framework#22165] opened 2020-09-24 18:30 UTC
# Feature Request

**Ionic version:**
[x] **5.x**

**Describe the Feature Request**
When you have a reasonably long list of items that are being displayed in an `ion-select`, it would be helpful if the list would scroll such that the currently selected item is in view.

With recent changes, this is less of a problem on desktop as the Tab key will do this when you tab in to the select, but on mobile it is a bit clumsy currently to scroll down to the currently selected item.

**Describe Preferred Solution**
See this demo: https://github.com/kensodemann/demo-select

It has one select that uses the default `alert` interface and the other using the `popover` interface.

For both of them, select an item that you would need to scroll down to. Upon next opening that same select, it will start at the top rather than scrolling to the selected item.

**Comment by kensodemann** [comment] 2020-09-24 18:33
For reference, Angular MD's select will scroll to the selected item if there are several in the list: https://material.angular.io/components/select/overview (see the state picker a bit down the screen)

**Comment by liamdebeasi** [comment] 2020-09-24 19:02
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/19296.

**Closed by liamdebeasi** 2020-09-24 19:02 UTC
Labels: triage
