### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by zoultrex** [ionic-team/ionic-framework#28492] opened 2023-11-08 15:02 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Segment button clickable area does not decrease as the heigh changes to a lower value than the default **when in web mobile mode (example iphone 12 pro)**
My component is structure as follows:
ion toolbar > ion segment > ion segment button + ion label
My css is targeting toolbar, segment and segment button, also changes the label paddings
Applying borders around the components and inspecting on chrome reveals all areas are decreased and there are no overflows but still, the segment button is clicable way off its render area

### Expected Behavior

The clickable area of a segment button should respect its height

### Steps to Reproduce

create a segment with the elements specified above, put them inside an ion toolbar and decrease their heigh in half or less than whatever is the default value, you can see that if you decrease it a lot you can even click outside of it, making it hard to have other buttons close to it inside the toolbar like back buttons, menu etc
**You must render the screen as mobile on chrome devtools, choose iphone 12 pro or similar**

### Code Reproduction URL

https://flems.io/#0=N4IgzgpgNhDGAuEAmIBcIB0ALeBbKIANCAGYCWMYaA2qAHYCGuEamO+RIsA9nYn6wA87KAD4AOnQAEU4RAZIJ0mbPhl4MUQEleZWFIAqEMPEEB6NRohKVssLABOZAA7wp8AJ7OIAXnEhcbiQAVxh-KTAHWD8QHHhnMFQzM1gkOgwAKzAkaDIANwcMOgh4MzpnXDMAATJdWBTuBwgzJDITM1q6PQ66jGNcTLB-UXN7J1cbFUEoMjoAaykmqBiTD0osCBLwrCaSGLiEpJS0wZyZgqKSsorqzu6eJpSwMB6u2AwAI2C6JBgMWGe4TMk3MGwUSkEHyCHhBnQAtGCcg5JjJBPD4NxuFAPgxkZJbKj4V94Bi6GAIlBuPAVvBcfBhviCYTeHCcbA5qzgiTeFIciQGKF4AjdjEAMTDcxEhjszncugoqavWWksAK5l0OGWTQAZQAwgBBABykpZWusjNRSoxWJxeOU6s1mOxuKksCgDGeK1gDA13ocSDAjptuIZ9qm8MgAHNmHxXe7Pf57D64X6A3CozH6SApHkGFBgr5-MSVaGmQ6MxA+MqeW6PWAvcnU4GK1WPvA6OFc-nCyA+QKoFm1QS0Sz3R9oHG6w3fbi0y2hWPoMMACIQfmCk0axdiC3DpXz6vy3e2Ecag-Fmvx+uJ70z-3NiDRytCtsd7NdgsrR+Z0tlh3bycE3AW8U1nB8nyrbdhm1b9n03OFtyHS0I1g1suVJId4PnBV4OtZ07WQllEQgAjZHhHg+GfQDrxAeFnAUVo6EjX8T2cURnCaZ4pBIABGAAmQgpGcLkpFmKRAg+CgIHEoIIEE2AsExSAIm4ZhROcRTihks4pBmOZpP4oSHG4cw2OPKRGXgij+HgCEzChJAYUkUE8B3Ds6E4SAYAQToqHQPiADZUAAdgCkAAF9CHoJgWHQQZOGs59WAiqKQEYZhWH+Z4Et4GzMqTO80zw21gEZOE4VwWYEQgMhIxwVApAAZgABmcAAPABuRkoX9EiGp49reQ9DYkCkD5uy6uhwskSQMAK0D73TVD4FK5RysqjUNlq+qmtazrusaJF+sGpBhuQRZkEm6b3LmkCmyWiCX3bVaZA26rtvgBq+L2jqLOUXAGDa966s+3b2smmQeqOqQBraoawBGsb3XZK6ZvSeb7oPbcXvE3FIyqjFnAan7GQBhx8Y1KFuVwYnwcZEhcvTMgAC8IH6vi6amzzoDgNReD8kAeMa1BAoigBdcKgA

### Ionic Info

Ionic:

   Ionic CLI       : 7.1.1 (/Users/grf/.config/yarn/global/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 7.5.0

Capacitor:

   Capacitor CLI      : 5.4.2
   @capacitor/android : 5.5.0
   @capacitor/core    : 5.5.1
   @capacitor/ios     : 5.5.1

Utility:

   cordova-res                          : not installed globally
   native-run (update available: 2.0.0) : 1.7.3

System:

   NodeJS : v18.17.1 (/Users/grf/.nvm/versions/node/v18.17.1/bin/node)
   npm    : 9.6.7
   OS     : macOS Big Sur

### Additional Information

--min-heigh as well as other css heigh related properties were used and tested to try to make the clicakble area respect the height of the component but nothing worked

**Comment by liamdebeasi** [comment] 2023-11-08 15:13
Can you please provide a reproduction case for this? The playground you linked to does not apply any of the styling customizations you noted as necessary to reproduce the issue.

**Comment by zoultrex** [comment] 2023-11-08 15:49
> Can you please provide a reproduction case for this? The playground you linked to does not apply any of the styling customizations you noted as necessary to reproduce the issue.

@liamdebeasi I just updated the bug report. Added a reproducible link, but most importantly I forgot to mention that you must render the screen in web mode, I used chrome devtools for that and choose iphone 12 pro

Could you check it out?

**Comment by liamdebeasi** [comment] 2023-11-08 16:56
Does this happen on a physical device? I can only reproduce this in Chrome's mobile device simulation which leads me to think this is a bug in how the browser simulated touch events in this mode.

**Comment by zoultrex** [comment] 2023-11-08 17:50
> Does this happen on a physical device? I can only reproduce this in Chrome's mobile device simulation which leads me to think this is a bug in how the browser simulates touch events in this mode.

I tested on a build for android on a physical device (galaxy s21 fe) and inside the app this does not happen
Also tested on firefox using the same developer tools to simulate a mobile device and the issue also does not happen.

I guess we can say this is chrome/chromium related then?

Do you have any suggestion for a better approach with the code or the css that might not cause this problem? Or even a workaround?

Thanks for looking into this so quickly 👍

**Comment by liamdebeasi** [comment] 2023-11-08 18:03
Yes, this seems to be related to the Chrome Dev Tools touch event simulation. I'm not aware of any workaround since this inaccuracy is coming from the browser. It sounds like this should not impact production applications though since it's specific to dev tools.

**Comment by liamdebeasi** [comment] 2023-11-08 19:24
Going to close this since this isn't an Ionic bug, but let me know if you have any questions. Thanks!

You can optionally file some feedback on https://bugs.chromium.org/p/chromium/issues/list. There may be some improvements the dev tools team can make to the mobile touch emulation.

**Closed by liamdebeasi** 2023-11-08 19:24 UTC
Labels: needs: reply
