### ISSUE TITLE
bug: ionic app ios 14, background blink on touch tap

### ISSUE THREAD

**Issue by Minipap** [ionic-team/ionic-framework#22202] opened 2020-09-29 13:01 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[ ] **5.x**
[x] **6.11.9**

**Current behavior:**
Every time i tap on the screen, the background blink like it's refreshing.

**Expected behavior:**
it shouldn't blink on every tap.

**Related code:**
i set the background with ion-content in the global.scss:

ion-content {
    --background: url('/assets/icon/background.png') no-repeat center center / cover;
    --offset-top: 0px !important;
    --offset-bottom: 0px !important;
}

**Other information:**
i think it's an IOS 14 problem since with IOS 13.5 it doesn't happen.

**Ionic info:**

Ionic:

   Ionic CLI                     : 6.11.9 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.2.3
   @angular-devkit/build-angular : 0.901.11
   @angular-devkit/schematics    : 9.1.8
   @angular/cli                  : 9.1.11
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 2.2.1
   @capacitor/core : 2.2.1

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 6 other plugins)

Utility:

   cordova-res                          : 0.15.1
   native-run (update available: 1.2.0) : 1.0.0

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.2
   NodeJS     : v12.18.0 (/usr/local/bin/node)
   npm        : 6.14.8
   OS         : macOS Catalina
   Xcode      : Xcode 12.0 Build version 12A7209

**Comment by liamdebeasi** [comment] 2020-09-29 13:51
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. This was a bug in WebKit (the engine that powers Safari/the webview on iOS): https://bugs.webkit.org/show_bug.cgi?id=216048

It appears the bug has been fixed but not yet shipped on iOS. See https://github.com/ionic-team/ionic-framework/issues/17494#issuecomment-492647992 for a temporary workaround.

**Closed by liamdebeasi** 2020-09-29 13:51 UTC
Labels: triage
