### ISSUE TITLE
bug(ion-select): No longer possible to set `margin: auto` on `::part(icon)`

### ISSUE THREAD

**Issue by lincolnthree** [ionic-team/ionic-framework#27392] opened 2023-05-04 14:30 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When using the modern form syntax, it is no longer possible to control the margin of the `icon` part using automatically calculated margins when the width of the `ion-select` is set larger than its content (such as `100%` or a fixed pixel amount like `150px`):

![image](https://user-images.githubusercontent.com/362329/236237223-9d58aaea-aa92-4e82-9fa4-7ce59030fd88.png)

One used to be able to modify the spacing of the 'icon' from the text using the shadow part and an automatic margin. But now it seems there's a new style on the `.native-wrapper` that prevents modifying the margin using auto in the modern form syntax. Setting a fixed pixel margin on the icon works fine. 

Code that should work:
```
ion-select::part(icon) {
  margin-left: auto;
  margin-right: 15px;
}

```

### Expected Behavior

I expect the Modern form control to be customizable the same way such that full-width select inputs can be styled to match our application theme. Setting the `.native-wrapper` to `width: 100%` in the element debugger also resolves this. (And does not appear to break other styling.)

![image](https://user-images.githubusercontent.com/362329/236238414-1ddb3b75-cc08-4953-9f5b-fdaf07c74894.png)

### Steps to Reproduce

1. Run sample app.
2. View tab 1.
3. Enjoy

### Code Reproduction URL

https://github.com/lincolnthree/ionic-bugs/tree/issue-27392

### Ionic Info

Ionic:

   Ionic CLI                     : 7.0.1 (/Users/lincoln/.nvm/versions/node/v16.14.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.0.5
   @angular-devkit/build-angular : 15.2.6
   @angular-devkit/schematics    : 15.2.6
   @angular/cli                  : 15.2.6
   @ionic/angular-toolkit        : 9.0.0

**Comment by liamdebeasi** [comment] 2023-05-04 14:47
Thanks for the report. I can reproduce this, though the behavior here is intentional. The "native-wrapper" is designed to take up only as much width as it needs to match the iOS and MD specs. The `margin: auto` styles worked in Ionic v6 due to the old select not matching the iOS/MD spec which is why this behavior broke when updating to the new form architecture.

However, if you had access to `.native-wrapper` as a shadow part you could set `width: 100%` to customize that behavior and achieve the desired result. We have plans to expose this element as a shadow part in https://github.com/ionic-team/ionic-framework/issues/27112, so I am going to merge the two threads.

When this feature ships you will be able to do something like the following (naming subject to change):

```css
ion-select::part(wrapper) {
  width: 100%;
}
```

Here's what should look like:

![image](https://user-images.githubusercontent.com/2721089/236243628-d5d5cf30-8416-4439-86bf-5c71888a9bb4.png)


I am going to close this in favor of #27112, but let me know if you have questions.

**Closed by liamdebeasi** 2023-05-04 14:47 UTC
Labels: triage

**Comment by lincolnthree** [comment] 2023-05-04 14:54
Perfect. That will absolutely solve this and I'm always a fan of extensibility vs. assumptions (I like your solution)! Thank you :)
