### ISSUE TITLE
feat: Datetime add time-compact presentation style

### ISSUE THREAD

**Issue by JesseB0rn** [ionic-team/ionic-framework#24402] opened 2021-12-14 20:56 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

When used with `time-date` presentation style or similar, the datetime component renders the time as follows:

<img width="241" alt="image" src="https://user-images.githubusercontent.com/50794219/146077140-94bac099-cfab-4edd-84e4-e0908d04bdd9.png">

When used as `time`, sadly like this:
<img width="217" alt="image" src="https://user-images.githubusercontent.com/50794219/146077469-6b68eafb-8a8a-4c37-ba72-1263e5498da4.png">

### Describe the Use Case

- When multiple times are needed for only one date, ex. Start & end times

### Describe Preferred Solution

I suggest a new presentation style `time-compact`, that only renders the time picker as seen in `time-date` presentation.

**Comment by liamdebeasi** [comment] 2021-12-14 21:55
Thanks for the issue. Can you describe the use case for adding this?

**Comment by JesseB0rn** [comment] 2021-12-15 06:05
When a timepicker that is visually the same as the date-time picker is required:
- Start and end time
- multiple Times
- compacter layout for timepicking

**Comment by amandaesmith3** [comment] 2022-02-24 16:28
Thanks for the issue! While discussing with the team how we would approach this API, we've decided this use case would be solved by making some of the improvements described here: https://github.com/ionic-team/ionic-framework/issues/24477 In particular, we're planning to add a new API that displays an `ion-input` (or something similar) that, when clicked, opens an `ion-datetime` in an overlay. Having this work with `presentation="time"` will cover the use case here for `time-compact`.

As such, I'm going to close this issue and the connected PR as a duplicate of https://github.com/ionic-team/ionic-framework/issues/24477. We're actively planning this feature out, and we will post on that issue when we have more to share. Thank you for the issue and your PR contribution; it's been very helpful in making sure we're serving everyone's needs. 👍

**Closed by amandaesmith3** 2022-02-24 16:28 UTC
Labels: type: feature request, package: core

**Comment by DwieDima** [comment] 2022-02-28 14:59
@amandaesmith3 is this behavior besides for `time` also for all properties of `ion-datetime` [presentation](https://ionicframework.com/docs/api/datetime#presentation) styles on your roadmap?.

**Comment by JesseB0rn** [comment] 2022-02-28 18:35
Any status on #24539
