### ISSUE TITLE
bug: ionic vue query string not properly reconstructed when going back

### ISSUE THREAD

**Issue by zct1989** [ionic-team/ionic-framework#22517] opened 2020-11-18 10:35 UTC
# Bug Report

**Ionic version:**

[x] **5.x**

the bug appear at **Vue** environment

**Current behavior:**

If home page url has  query params when back to home page while report error because the url is error

**Expected behavior:**

can normal reback home page

**Steps to reproduce:**

home page url  has query param for example:  `http://example.com/page1?code=xxx`

when back to home the reback url will be set `http://example.com/page1code=xxx`

**Related code:**

routeInfo.search will be set value but not contain question mark 

https://github.com/ionic-team/ionic-framework/blob/33768e1d0ce5be2b9f6cb49faab6fbaa636e94a3/packages/vue-router/src/router.ts#L185

but when back to home page,this url is wrong

https://github.com/ionic-team/ionic-framework/blob/33768e1d0ce5be2b9f6cb49faab6fbaa636e94a3/packages/vue-router/src/router.ts#L90

because question mark is miss

**Comment by liamdebeasi** [comment] 2020-11-18 14:44
Thanks for the issue. Can you please reproduce this in an Ionic starter app and provide a link to the GitHub repo? I am unable to reproduce this on my end.

**Comment by zct1989** [comment] 2020-11-19 01:36
> Thanks for the issue. Can you please reproduce this in an Ionic starter app and provide a link to the GitHub repo? I am unable to reproduce this on my end.

@liamdebeasi 

I reproduce the bug in this git repo:

`https://github.com/zct1989/ionic-vue-router-demo`

when enter to the home page, please add the url params to reproduce the bug:

eg: http://localhost:8080?code=123

then  redirect to the page2 page by button ,will be found can't reback the home page, please try it.

**Comment by liamdebeasi** [comment] 2020-11-19 15:01
Thanks! Can you please clarify the steps to reproduce this issue? I am still unable to reproduce the issue. Here are the steps I am following:

1. Open app. You will be redirected to `http://localhost:8100/tabs/tab1`.
2. Add `?hello=123` to the URL to get `http://localhost:8100/tabs/tab1?hello=123`.
3. Click "Redirect to Page 2". You will be taken to the new page.
4. Click the `ion-back-button` in the top left. You will be taken back to `tabs/tab1?hello=123`. In this step, I am seeing the question mark being added properly.

I tested this on 86.0.4240.198.

**Comment by zct1989** [comment] 2020-11-20 02:56
There is my reproduct steps:
1. Open app. You will be redirected to http://localhost:8100/tabs/tab1.
2. Add ?hello=123 to the URL to get http://localhost:8100/tabs/tab1?hello=123.
3. Click "Redirect to Page1". You will redirect to new page named Page1
4. Then Click "Redirect to Page2" .You will countinue redirect to new page named Page2
5. Click the ion-back-button. you will back to page1.
6. Click the ion-back-button again. you will be found not reback tabs page

now will see url address will be set `http://localhost:8080/tabs/tab1hello=123`

you need to tabs -> page1 -> page2 ->page1 -> tabs

you will be found can't reback to tabs page

I capture the picture:

![1605840809959.jpg](https://i.loli.net/2020/11/20/JNGcMXaIjApSofU.jpg)

**Comment by liamdebeasi** [comment] 2020-11-20 14:49
When I land on `tabs/tab1` I only see a button that says "Redirect to Page2" which does nothing when I click it. Can you please double check your repo and ensure that I have the correct code?

**Comment by zct1989** [comment] 2020-11-23 02:32
I checked the rope code and not found any error, please to exec git clone again ,Thanks.

I have deploy it on GitHub page, you can visit it on below:

[https://zct1989.github.io/ionic-vue-router-demo?code=123](https://zct1989.github.io/ionic-vue-router-demo?code=123)

**Comment by liamdebeasi** [comment] 2020-11-24 15:09
Thanks for pushing the update to your repo. I was able to reproduce this bug.

**Comment by liamdebeasi** [comment] 2020-12-02 21:41
Can you try the following dev build, and let me know if it resolves the issue?

```
npm install @ionic/vue@5.6.0-dev.202012022136.dc9faa6 @ionic/vue-router@5.6.0-dev.202012022136.dc9faa6
```

You will also need the latest version of the `vue-router` pre-release:

```
npm install vue-router@next
```

**Comment by zct1989** [comment] 2020-12-05 09:34
It's working fine now , thanks 👍

**Comment by liamdebeasi** [comment] 2020-12-07 20:17
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/22615, and a fix will be available in an upcoming release of Ionic Framework.

**Closed by liamdebeasi** 2020-12-07 20:17 UTC
Labels: package: vue, type: bug
