### ISSUE TITLE
feat: add ability for routing integrations to not cache views

### ISSUE THREAD

**Issue by NiklasMerz** [ionic-team/ionic-framework#19531] opened 2019-10-02 15:10 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

It looks like the back button does not show up in some cases when it should. This happens if one page gets opened a second time.

Possibly pages get initialized without 'can-go-back' and this does not get updated.

**Wrong behavior:**
My app opens a "list page" which can open a "detail page" which can open the "list page" with other query params again. This "list page" does not show an `ionic-back-button`.

**Expected behavior:**

I would expect the `ionic-back-button` to show on the last "list page" and take me back to the "detail page" and from there another `ionic-back-button` to the first "list page".

**Steps to reproduce:**

- Start app on home page
- Click on button on homepage at the bottom "LIST"
- Navigated to ListPage
- Click on "Item 1"
- Navigated to Homepage
-> **There is no back button**

If I use the list page from menu, the back-button will show on the home page. But if I go to the list page again from there, the button will disappear as well.

**Related code:**

This is my [test case](https://github.com/NiklasMerz/repro-ionic-back).

**Other information:**

**Ionic info:**

New menu template
```
Ionic:

   Ionic CLI                     : 5.4.1 (/Users/gedysintraware/.nvm/versions/node/v10.13.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.10.0
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Utility:

   cordova-res : 0.6.0 
   native-run  : 0.2.8 

System:

   NodeJS : v10.13.0 (/Users/gedysintraware/.nvm/versions/node/v10.13.0/bin/node)
   npm    : 6.4.1
   OS     : macOS Mojave

```

**Comment by marcoromag** [comment] 2019-10-02 15:39
same happens with React apps

**Comment by NiklasMerz** [comment] 2019-10-04 08:16
I added a test case for this to the Angular test app in this repro, which shows a diffrent flavor of this issue quite well. Would love to create a PR for that and I am looking for a fix!

Steps to reproduce with this test:
* `npm start` in "angular/test/testapp"
* Go to `localhost:4200`
* Click "Router link test"
* Click "Query params and fragment" at the bottom
* Click "Go to page 3"
* Click "Go to page 2 again...."

Now we are on page 2 and can see a back button. This is different from my repro app, but not correct, too. If I click on page I get redirected to `/router-link`and not page 3 like expected.

**Comment by NiklasMerz** [comment] 2019-10-04 12:11
My further debugging results. Views are reused from the stack if they are navigated to the second time.

This line is responsible for losing the history before the first appearance of the view after using it the second time: https://github.com/ionic-team/ionic/blob/bfb704e2d2abf7a1e95e00e65206488c5a3558b7/angular/src/directives/navigation/stack-utils.ts#L24

I will update this post with new results to get this resolved quickly. Because of this bug our routing and navigation with back button is quite chaotic. Our app uses a few pages with different parameters very often in one navigation tree.

**Comment by NiklasMerz** [comment] 2019-10-04 13:07
**I found a possible workaround!**

Exisiting pages are reused if the URL matches. If I open an existing page a seconde time using a different URL it looks like the back button works as expected. Nevertheless there should be a fix for this. Since I'm not really sure how pages should be reused, I'm unsure how to fix this.

**Comment by NiklasMerz** [comment] 2019-10-30 15:14
Sorry for pushing this, but is this considered as a bug?

Now I have to do an ugly workaround and add to every page a garbage random paramter to avoid this caching issue. I would like to remove that as soon as possible.

**Comment by NiklasMerz** [comment] 2020-04-03 11:34
Sorry but bumping this again to prevent getting this locked.

**Comment by liamdebeasi** [comment] 2020-10-30 15:10
Thanks for the issue. By default, all of our routing integrations will re-use existing views if they match the same URL. For example:

`/a` --> `/b` --> `/a` would re-use the rendered view for `/a` and `ion-back-button` would not appear since it is on the root view.

While this is working as intended, I can understand that this may not be expected or desirable in some situations. Changing this would be a breaking change that we can look into, or we can look into making this an opt-in feature. Either way there is certainly going to need to be some discussion about how to implement this.

For anyone who is running into this scenario: Would you be able to provide a use case and a code sample that can help us understand how this behavior affects your applications? Thanks!

**Comment by HriBB** [comment] 2020-11-20 00:42
I had a similar problem and solved it by defining multiple routes with similar path. Now when you go down the herarchy, new view is created each time. 

```jsx
export const View = () => (
  <IonReactRouter>
    <IonSplitPane contentId="main">
      <Menu />
      <IonRouterOutlet id="main">
        <Route path="/module" component={Module.List} exact />
        <Route path="/module/:f1" component={Module.List} exact />
        <Route path="/module/:f1/:f2" component={Module.List} exact />
        <Route path="/module/:f1/:f2/:f3" component={Module.List} exact />
        <Route component={NotFound} />
      </IonRouterOutlet>
    </IonSplitPane>
  </IonReactRouter>
);
```

I was surprised by this behavior at first, thought it was a bug in my app, but then I figured that Ionic must be doing some caching. After using the above setup, it works. 

I think it's a cool feature, but needs to be mentioned more in the docs. Maybe with nice big bold font :)

**Comment by NoelDeMartin** [comment] 2021-06-16 14:56
> For anyone who is running into this scenario: Would you be able to provide a use case and a code sample that can help us understand how this behavior affects your applications? Thanks!

At [Moodle](https://moodle.com/) we're migrating the mobile app from Ionic 3 to Ionic 5, and we've found that this breaks some navigation we relied upon before; in the fashion I outlined in #23455.

In particular, Moodle is an LMS (learning management system) with a lot of customization options. Given the nature of our software, there is a lot of interconnected pages. The specific scenario where we found this breaking down is navigating between pages in a course. Imagine that you are doing an activity linking to a section from another activity (a very common scenario). In this case, it is desirable to preserve the navigation stack in case you want to go back to the activity you came from.

If you want to look at the code you can find it here: https://github.com/moodlehq/moodleapp

**Comment by liamdebeasi** [comment] 2022-04-12 19:31
Hi there,

Thanks for filing the issue and providing more context around the various use cases. The team has decided not to implement this feature.

Caching views allow us to improve performance on lower end devices and add functionality such as swipe to go back on iOS. Removing this functionality would make it more difficult to have a performant swipe to go back gesture.

The use case in https://github.com/ionic-team/ionic-framework/issues/19531#issuecomment-862451879 mentioned linking to other pages in a single course. This kind of pattern would benefit from parameterized URLs. By using parameterized URLs you can ensure that Ionic creates new instances of the same component whenever the parameters in the URL change.

For example, given a routing configuration of `/a/:id`, routes `/a/1` and `/a/2` would get two separate instances of the same component. We recommend using parameterized URLs when you need to create a new instance of a page.

I am going to close this. Thanks!

**Closed by liamdebeasi** 2022-04-12 19:31 UTC
Labels: type: feature request, package: angular, package: vue, package: react

**Comment by NoelDeMartin** [comment] 2022-04-13 07:46
@liamdebassi Thanks for the update.

We are already using parametrized urls in our app, the problem is that as I mentioned in https://github.com/ionic-team/ionic-framework/issues/23455 we can have pages linking to the exact same page that is already in the stack. For example, imagine that Wikipedia builds an Ionic app. If you start navigating between articles, you'll eventually [end up in a page you already visited](https://en.wikipedia.org/wiki/Wikipedia:Getting_to_Philosophy). But you wouldn't want to lose all the navigation history.

One solution would be to add a parameter that is a unique id in every route, which isn't related with the content of the page (maybe that's what you meant?). I guess that would work, but it'd be cumbersome to do that for every route in the app. And it doesn't make for pretty urls (although that's not a problem for us since we don't publish our app as a website).

In any case, thanks for letting us know about your decision. We'll try to find some workarounds in our side.
