### ISSUE TITLE
bug: If alert or modal is opened and android talkback is on then background elements are also read.

### ISSUE THREAD

**Issue by Jalpesh009** [ionic-team/ionic-framework#23716] opened 2021-08-03 11:51 UTC
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

Background elements are also read If alert or modal is opened and android talkback is on.

### Expected Behavior

Background element should not be read If modal or alert is opened.

### Steps to Reproduce

1. Turn on talkback.
2. Open modal or alert. 
3. Swipe left then right. then focus will go to background elements.

### Ionic Info

Ionic:

Ionic CLI : 6.16.3 (/usr/local/lib/node_modules/@ionic/cli)
Ionic Framework : @ionic/angular 5.6.9
@angular-devkit/build-angular : 0.1000.8
@angular-devkit/schematics : 10.0.8
@angular/cli : 10.0.8
@ionic/angular-toolkit : 2.3.3

Cordova:

Cordova CLI : 10.0.0
Cordova Platforms : ios 6.2.0
Cordova Plugins : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 2.5.1, (and 16 other plugins)

System:

ios-sim : 8.0.2
NodeJS : v14.17.0 (/usr/local/bin/node)
npm : 6.14.13
OS : macOS Big Sur
Xcode : Xcode 12.5 Build version 12E262```

**Comment by liamdebeasi** [comment] 2021-08-03 12:51
Thanks for the issue. Can you reproduce this in an Ionic starter app and provide a link to the repo?

**Comment by Jalpesh009** [comment] 2021-08-04 09:15
Thanks for the reply. 
If talkback is on and when we open alert and then if we swipe left or swipe right then focus is trapped in whole background.(It speaks like ionic app webview appname). That should not be case. if alert is opened, Focus should trap in alert itself. 

Please refer this link for code. https://stackblitz.com/edit/ionic-angular-v5-ajm2pu

**Comment by HyperLife1119** [comment] 2021-08-04 16:52
In the latest version, there seems to be a problem of click penetration. Clicking the back button in the upper left corner of the modal box will also start the back button in the upper left corner of the page.

**Comment by liamdebeasi** [comment] 2021-08-12 17:43
Thanks for the StackBlitz. Are you able to reproduce this issue on the latest version of Ionic Framework? Your StackBlitz is using Ionic Angular v5.0.6. I am able to reproduce the issue on that version, but not on the latest version (v5.6.13)

**Comment by Jalpesh009** [comment] 2021-08-13 09:00
Thanks for the reply. It is not reproducible in iOS device. I am still able to reproduce this issue in latest version(v5.6.13) in android device.

**Comment by liamdebeasi** [comment] 2023-02-15 22:15
Thanks for the report. There have been several improvements to focus trapping in Ionic 6, and I am no longer able to reproduce this issue. I am going to close this, but let me know if there are any questions.

**Closed by liamdebeasi** 2023-02-15 22:15 UTC
Labels: type: bug, a11y
