### ISSUE TITLE
bug: backdrop filter does not work anymore

### ISSUE THREAD

**Issue by danielehrhardt** [ionic-team/ionic-framework#22495] opened 2020-11-13 12:35 UTC
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
The Backdrop Filter does not work anymore at all. 
`backdrop-filter: blur(26px);`
![image](https://user-images.githubusercontent.com/19570043/99072725-def6f680-25b4-11eb-98b7-c12041f36452.png)

**Expected behavior:**
![image](https://user-images.githubusercontent.com/19570043/99072778-fa620180-25b4-11eb-9a1e-6c91d2ca9f06.png)

**Steps to reproduce:**
After I update the Ionic Angular Version:
```
--    "@ionic/angular": "5.4.1",
++    "@ionic/angular": "5.4.2",
```

**Related code:**

**Comment by danielehrhardt** [comment] 2020-11-13 12:43
https://github.com/ionic-team/ionic-framework/issues/22176

**Comment by liamdebeasi** [comment] 2020-11-13 14:35
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/22176.

**Closed by liamdebeasi** 2020-11-13 14:35 UTC
Labels: triage
