### ISSUE TITLE
bug: IonPicker on android is very slow.

### ISSUE THREAD

**Issue by pritamsoni-hsr** [ionic-team/ionic-framework#21836] opened 2020-07-29 03:00 UTC
# Bug Report

**Ionic version:**

[x] **5.2.3**

**Current behavior:**

IonPicker on Android is very slow in terms of scrolling, it works well on iOS.

**Expected behavior:**

Scrolling Speed should be high, and can have a configurable prop?

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment] 2020-07-29 13:06
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/18679 (same underlying issue). We are tracking all datetime/picker issues in https://github.com/ionic-team/ionic-framework/issues/16630.

**Closed by liamdebeasi** 2020-07-29 13:06 UTC
Labels: triage
