### ISSUE TITLE
SCSS @import vs @use.

### ISSUE THREAD

**Issue by infacto** [ionic-team/ionic-framework#22444] opened 2020-11-06 12:47 UTC
It's not a bug report, new feature, or support, but a little bit of everything. (Nothing for forums.) It's about to discuss the Ionic source code here and the use of [@import](https://sass-lang.com/documentation/at-rules/import) instead of [@use](https://sass-lang.com/documentation/at-rules/use).

The Ionic source code uses for example [mixins](https://github.com/ionic-team/ionic-framework/blob/master/core/src/themes/ionic.mixins.scss) and [everwhere](https://github.com/ionic-team/ionic-framework/blob/master/core/src/css/padding.scss) import.

I just naively wondering why is `@import` used over `@use`. See [docs](https://sass-lang.com/documentation/at-rules/import). The `@use` is more releated to `import` in TypeScript. But maybe I'm wrong. Why this decision? Personally, I also use import. But got some critics. So what's about pros? What's better? Should we move to `@use`? You could say: It's fine to use `@import` and close it.

> The Sass team discourages the continued use of the @import rule. Sass will gradually phase it out over the next few years, and eventually remove it from the language entirely. Prefer the @use rule instead.

**Comment by jaredcbaum** [comment] 2020-11-06 17:12
Hey, infacto.  Good questions!  I was actually talking about this recently with a member of the framework team.

> I just naively wondering why is @import used over @use.
The code was created before `@use` was available in scss.

> Should we move to @use?
Yes, it decreases clashes in the global namespace and allows for namespacing in general.  Besides that, since the sass team plans to phase `@import` out, it's probably not the best choice for new projects.

Here are some resources if you wanted to dive a little deeper:

- [Css Tricks Article](https://css-tricks.com/introducing-sass-modules/#:~:text=The%20new%20%40use%20is%20similar,considered%20private%2C%20and%20not%20imported.)

- [Medium Article](https://medium.com/@stefaniefluin/the-new-sass-module-system-out-with-import-in-with-use-e1bd8ba032d0)

**Comment by liamdebeasi** [comment] 2021-09-16 19:47
Thanks for the issue. When building Ionic only `@import` was available at the time, so we went with that. In general it is recommended to use `@use`, but `@import` still works.

I am going to close this as this is not a bug in Ionic Framework. That being said, we are tracking some infrastructure upgrades internally and `@import` vs `@use` is something we are actively discussing. Thanks!

**Closed by liamdebeasi** 2021-09-16 19:47 UTC
Labels: needs: investigation
