### ISSUE TITLE
[beta 16] label doesn't align well with icons inside items

### ISSUE THREAD

**Issue by simonhaenisch** [ionic-team/ionic-framework#16422] opened 2018-11-22 02:41 UTC
# Bug Report

**Ionic Info**

```
@ionic/core@4.0.0-beta.16
```

**Describe the Bug**

Following #16182, the `ion-label` doesn't align well with an `ion-icon` inside an `ion-item` anymore. It becomes very apparent, for example, when using an item within a card-header (see fiddle).

| Before (Beta 15) | After (Beta 16) |
|-|-|
| http://jsfiddle.net/simonhaenisch/7y4tdbvm/ | http://jsfiddle.net/simonhaenisch/gwm1t6rb/ |
| ![image](https://user-images.githubusercontent.com/3410759/48878770-c6dcb880-ee6d-11e8-924d-7f213afebc76.png) | ![image](https://user-images.githubusercontent.com/3410759/48878781-d2c87a80-ee6d-11e8-9039-10aeb56afe49.png) |

I think it might be that it's supposed to align with the bottom of the icon (which might come from the MD spec?), however it just looks off. Looking at the screenshots in #16182, it also doesn't seem like it's supposed to be that way (e. g. single-line item with the bluetooth icon).

**Expected Behavior**

It should look pretty :unicorn:

**Additional Context**

<img src="https://user-images.githubusercontent.com/3410759/48878425-381b6c00-ee6c-11e8-9ff3-b2681ea43eb2.png" width="307">

This style rule also breaks chips wrapped within icons because chips contain labels (see https://github.com/ionic-team/ionic/issues/16352#issuecomment-440857500).

Current work-around is to overwrite it in my global stylesheet:

```css
.item .sc-ion-label-md-h {
  margin: 10px 0;
  line-height: 1.2 !important;
}
```

**Comment by manucorporat** [comment] 2018-11-29 00:50
can you share your markup?

**Comment by manucorporat** [comment] 2018-11-29 00:52
It should be:

```html
<ion-item>
  <ion-icon slot=“start”></ion-icon>
  <ion-label>Text</ion-label>
</ion-item>
```

**Comment by manucorporat** [comment] 2018-11-29 01:48
sorry i missed the http://jsfiddle.net/simonhaenisch/gwm1t6rb/
We will look into it

**Comment by simonhaenisch** [comment] 2018-12-28 04:13
Seems that it's slightly better in RC.0 (compare http://jsfiddle.net/simonhaenisch/7ew18qn3/ to http://jsfiddle.net/simonhaenisch/gwm1t6rb/), but not sure that's the desired outcome?

**Comment by trazek** [comment] 2019-01-21 21:02
Hi @simonhaenisch, I will take a look soon and report back

**Comment by trazek** [comment] 2019-01-22 04:06
@simonhaenisch are you still seeing this issue in RC.2?

**Comment by trazek** [comment] 2019-01-22 15:26
Ok great. I'll take a look at those

**Comment by trazek** [comment] 2019-01-22 16:38
@simonhaenisch when looking at those fiddles, I didn't see the "g" being cut off actually. Can you show me a fiddle with it being cut off? 

Looking at the spec: https://material.io/design/components/lists.html#specs, it suggests list items with icons should be 56px in height but currently in RC.2, the height is calculated as 48px. Perhaps RC.2 has not updated to the latest MD spec.

And when using `ion-label` (at least for MD), have you tried using `p` tags for text? Using the proper tag inside the `ion-label` ensures the text gets the styling as currently configured and interrupted by Ionic.

**Comment by simonhaenisch** [comment] 2019-01-22 21:18
@trazek you are right, wrapping the text inside the label inside a `p` or `h2` (or I guess any block element) aligns it properly, and characters that go below the baseline don't get cut off anymore... however all the examples in the docs suggest using text directly inside the `ion-label` (you can check any of the examples in the API docs, e. g. `input`, `item`, `item-divider`, `label`, `list`, `list-header`, `note`, `radio`, `segment`, `toggle`, ...).

**Comment by trazek** [comment] 2019-01-22 22:43
Yeah I think the docs are in flux because of the looming v4 update. Maybe we can create an issue to update the docs in this manner.

**Comment by simonhaenisch** [comment] 2019-01-22 22:59
Not sure that this is just a docs issue, see Manu's comment above: https://github.com/ionic-team/ionic/issues/16422#issuecomment-442663570. Pretty sure it's supposed to work with text directly inside the label.

**Comment by trazek** [comment] 2019-01-23 18:45
Yes it's true but I could argue, if one expects to have an `ion-label` render according to the MD spec, they should use the proper typography level. 

@manucorporat do you think this is reasonable? Should the typography level default to `body-1` (`p`) or something if `ion-label` is used without any containing tags?

**Comment by liamdebeasi** [comment] 2019-02-13 17:25
Hi @simonhaenisch,

I've created a PR that should fix the issue you've been seeing. Could you test with your use case and see if it fixes it for you? I've looked at our tests and they seem to look good.

https://github.com/ionic-team/ionic/pull/17489

Thanks!

**Comment by simonhaenisch** [comment] 2019-02-14 08:01
Thanks for looking into this... the `16px` top margin for the slotted icon seems off, i. e. the icon is not vertically centered anymore (because margin-bottom is `12px`).

| 12px | 16 px |
| - | - |
| <img src="https://user-images.githubusercontent.com/3410759/52771517-0ed83980-3071-11e9-9f41-4902c8878696.png" width="140"> | <img src="https://user-images.githubusercontent.com/3410759/52771538-1ac3fb80-3071-11e9-85d8-01fe8497f73c.png" width="134"> |
| <img src="https://user-images.githubusercontent.com/3410759/52771473-efd9a780-3070-11e9-9acb-5b7b52a4f514.png" width="136"> | <img src="https://user-images.githubusercontent.com/3410759/52771483-fa943c80-3070-11e9-93d0-6ffeb3965eef.png" width="139"> |

At least to me the 12px top margin looks more correct. All it needs is the `10px` top margin change for the ion-label, so that top and bottom margin are the same and it gets vertically centered properly. Or is it not supposed to be centered?

**Comment by liamdebeasi** [comment] 2019-02-14 13:52
@simonhaenisch Thanks for checking this out. I reverted the 16px changes -- I decided I wanted to focus on this fix before updating the item per the MD spec.

So I added the `10px` top change you suggested, but there still seemed to be a 1px offset. I ended up changing the line-height of the label to 18px (I believe it was at 19px originally).

**Comment by brandyscarney** [comment] 2019-04-16 17:34
Is this still an issue in latest? I created a Codepen using `4.2.0` and the icons appear to be aligned: https://codepen.io/brandyscarney/pen/VNyrNR?editors=1010

**Comment by simonhaenisch** [comment] 2019-04-23 14:06
@brandyscarney I just opened your pen and in Chrome (macOS 10.14.4) the label is still a tiny bit cut off at the bottom for me:

| Label height: `18px` | Label height: `19px` |
|-|-|
|  ![image](https://user-images.githubusercontent.com/3410759/56586355-de1bff80-65df-11e9-92a2-d7673d2f7661.png) | ![image](https://user-images.githubusercontent.com/3410759/56586441-073c9000-65e0-11e9-81d8-76532bcb5588.png) |

I also think that the icon looks more nicely aligned if the label height is `19px`. But I'm not totally sure how they are supposed to be aligned. I assume vertically centered?

**Comment by simonhaenisch** [comment] 2020-03-29 17:50
@brandyscarney in my global stylesheet (Stencil + Ionic PWA) I still have

```cs
.item .sc-ion-label-md-h {
  margin: 10px 0;
  line-height: 1.2 !important;
}
```

and I still think it looks more correct (after upgrading to 5.0.7 just now). When I remove it, I still get my labels cut off by what I think is half a pixel:

![image](https://user-images.githubusercontent.com/3410759/77856198-cbe61080-71f5-11ea-81da-2c4da1d6bfe3.png)

Applying mentioned workaround makes it look like this:

![image](https://user-images.githubusercontent.com/3410759/77856187-ba046d80-71f5-11ea-9cf9-d6abdf7641af.png)

This is on macOS, rendered font is Helvetica Neue. I enforce md mode for my app btw. The icon alignment also looks better to me.

(Not saying that my workaround is the correct way to fix this.)

**Comment by liamdebeasi** [comment] 2023-09-21 14:38
Hi everyone,

I took a closer look at this in Ionic 7, and the label + icon alignments appear to be working correctly. I am unable to reproduce the originally reported behavior with Ionic 7 (though I can reproduce it on Ionic 4).

Here some examples of the alignment in Chrome 117 with Ionic 7.4.1:

The orange signifies the boundary of the `ion-icon` and `ion-label` elements. There is 12px of whitespace between the top of the item and the top of the icon as well as 12px of whitespace between the bottom of the item and the bottom of the icon. Each label has 2px of space on the bottom but 3px of space on the top likely due to the element having an odd numbered height. However, the label itself is centered within the item container.

![Screenshot 2023-09-21 at 10 29 17 AM](https://github.com/ionic-team/ionic-framework/assets/2721089/1bb3a497-ae2f-4314-b4c4-020990f94007)

![Screenshot 2023-09-21 at 10 30 11 AM](https://github.com/ionic-team/ionic-framework/assets/2721089/c72396f4-fb28-4714-a285-d0e3a53cf432)

I am going to close this, but let me know if there are any questions.

**Closed by liamdebeasi** 2023-09-21 14:38 UTC
Labels: package: core, type: bug
