### ISSUE TITLE
bug: ion-nav won't work Vue

### ISSUE THREAD

**Issue by LeoMartinDev** [ionic-team/ionic-framework#22184] opened 2020-09-26 14:37 UTC
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
<ion-nav /> is not usable with latest @ionic/vue

**Related code:**

```
<template>
  <ion-nav :root="Test"></ion-nav>
</template>

<script>
import Test from './Test.vue';

export default {
    components: { Test },
}
</script>
```

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.11.8-testing.0 (/home/hidden/.nvm/versions/node/v14.12.0/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 0.5.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v14.12.0 (/home/hidden/.nvm/versions/node/v14.12.0/bin/node)
   npm    : 6.14.8
   OS     : Linux 4.19
```

**Comment by liamdebeasi** [comment] 2020-09-28 12:54
Thanks, no need to provide a reproduction. I think I know what the issue is.

**Comment by liamdebeasi** [comment] 2020-09-28 15:38
Can you try this dev build and let me know if it resolves the issue?

```shell
npm i @ionic/vue@0.6.0-dev.202009281526.96596ba @ionic/vue-router@0.6.0-dev.202009281526.96596ba
```

The one difference is that you should provide `Test` in `setup` as it is only being used as the data of a prop, not actually being rendered in your template:

```typescript
...
setup() {
  return { Test }
}
```

**Comment by liamdebeasi** [comment] 2020-09-30 14:16
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/22197, and a fix will be available in an upcoming release of Ionic Framework.

**Closed by liamdebeasi** 2020-09-30 14:16 UTC
Labels: package: vue, type: bug
