### ISSUE TITLE
bug: Ionic Gesture interferes with ionic swipe

### ISSUE THREAD

**Issue by philippendrulat** [ionic-team/ionic-framework#23163] opened 2021-04-08 10:13 UTC
# Bug Report

**Ionic version:**
[x] **5.6.3**

**Current behavior:**
As soon as I register a gesture on an element, the menu swipe doesn't work anymore when I am swiping over the element, even with a blank gesture

**Expected behavior:**
The menu swipe gesture and my custom gesture should work together

**Steps to reproduce:**

To recreate:
* ionic start sidemenu
* remove the split pane around the menu in src/app/app.component.html
* Create the gesture in src/app/folder/gesture.directive.ts
* register the gesture in src/app/folder/folder.module.ts
* add the gesture to the div with the id container in src/app/folder/folder.page.html
* enlarge the div in src/app/folder/folder.page.scss, stick to upper screen and make grey

To reproduce:
* `npm start`
* Go to http://localhost:4200
* The gesture is registered on the upper half of the screen (grey background)
* If you try to swipe open the menu on the upper half of the screen, it won't open. The lower half works

**Related code:**

https://github.com/philippendrulat/MenuBug

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.12.3 (C:\Users\Philipp\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.6.3
   @angular-devkit/build-angular : 0.1102.8
   @angular-devkit/schematics    : 11.2.8
   @angular/cli                  : 11.2.8
   @ionic/angular-toolkit        : 3.1.1

Utility:

   cordova-res                          : 0.15.3
   native-run (update available: 1.3.0) : 0.2.8

System:

   NodeJS : v14.16.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.11
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment] 2021-04-08 13:15
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The problem is that your gesture is always going to fire before the menu gesture fires because your gesture threshold is `0`. As soon as you click, your custom gesture will activate. Setting the threshold to `1` or greater resolves the issue.

**Closed by liamdebeasi** 2021-04-08 13:15 UTC
Labels: triage

**Comment by philippendrulat** [comment] 2021-04-08 14:17
Thank you for the fast response. Maybe I have to explain our use case.
We are using a custom longpress and tap directive. There is no moving when I am tapping. So if we set the threshold to 1, the "tap" event won't fire anymore (even if the menu works again). Why do the gestures interfere with each other anyway? 

We were using hammerjs gestures before, but they were not working properly, which is why we had to create our own.

**Comment by liamdebeasi** [comment] 2021-04-08 14:28
While the two gestures do not listen on the same elements, both elements overlap resulting in a conflict. The menu gesture listens on `ion-router-outlet`, and your gray square is inside of `ion-router-outlet`.

There is not a good way to reconcile these two gestures as there is no way to know if a user is going to swipe before your custom gesture fires because the threshold is `0`. I can think of 2 options for what you could do:

1. Use the `canStart` callback to disable the gesture if it is close to the edge of where the menu gesture can fire:

```js
...
el: this.el.nativeElement,
threshold: 0,
gestureName: 'app-long-press',
canStart: (ev) => ev.startX > 30, // You might need to fine tune this value
...
```

2. Disable the menu swipe gesture by setting `[swipeGesture]="false"` on `ion-menu`.

We could update our gesture logic so that both gestures always fire, but then you could get situations where the menu accidentally opens when people try to tap so I don't think that's a good idea.

**Comment by philippendrulat** [comment] 2021-04-08 14:47
The first solution won't work because we are creating something like a file browser and then the user won't be able to click on the file icon to open the file (since it's the leftmost element)
The second solution is unfortunately also no solution for our product. We need both in this view.

What I don't understand: Your threshold for the menu is 30 (pixels?), which should mean the menu opens after I moved the cursor 30 units. I already disabled the longpress when the user moved the cursor to much.
As I understood it, if I want to prevent other events to fire, I would use preventDefault() on the event. Together with the gesturePriority I can select the order of gestures to handle and then I could prevent the next gesture by using event.preventDefault().

Right now, you are right, this is not a bug but intended behavior, which means we can't use the gesture controller.
Again, thank you for your help.

**Comment by liamdebeasi** [comment] 2021-04-08 14:50
The first workaround checks to see if the starting x coordinate is greater than 30 pixels, not that you need to swipe 30 pixels in order for the gesture to activate.

**Comment by liamdebeasi** [comment] 2021-04-08 14:53
Also I'm curious -- why do you need a "tap" gesture? Couldn't you just add a `(click)` handler or use `(pointerdown)`?

**Comment by philippendrulat** [comment] 2021-04-08 14:58
Yeah but this means that the user won't be able to click on a document if he clicks on the icon 
![Screenshot-app](https://user-images.githubusercontent.com/15322673/114049044-635f5400-988b-11eb-8f7a-b1c6c7c16c4e.jpg)

We don't necessarily need the tap gesture, but we have a longpress gesture, which means we have to differenciate between tap and long press
