### ISSUE TITLE
bug: View goes above the safe areas in iPhone X and also in devices having notch.

### ISSUE THREAD

**Issue by adnanganie** [ionic-team/ionic-framework#24170] opened 2021-11-05 11:28 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

![5ab4df16-15db-44fc-859a-5fc3f67d02f3](https://user-images.githubusercontent.com/15443192/140503255-1793576d-5b0f-4310-ae58-f7e9c1de306d.png)

### Expected Behavior

Should be below the safe-area

### Steps to Reproduce

not using ion-content

**Comment by liamdebeasi** [comment] 2021-11-05 13:58
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The general expectation is that all pages have an `ion-header`, `ion-toolbar`, and `ion-title` as is common with many mobile apps. It is there in the header/toolbar combo that we add the safe area padding. Because `ion-content` does not concern itself with `ion-header`, it does not dynamically add in safe area padding if an `ion-header` is not used.

To add the safe area padding to your content, you can add the following CSS:

```css
ion-content {
  --padding-top: var(--ion-safe-area-top);
}
```

I am going to close this issue. Thanks!

**Closed by liamdebeasi** 2021-11-05 13:58 UTC
Labels: triage
