### ISSUE TITLE
bug: ion-textarea defaults to zero height when inside ion-item and input attribute is used and slot behaviour confusing

### ISSUE THREAD

**Issue by Lxstr** [ionic-team/ionic-framework#23663] opened 2021-07-21 02:42 UTC
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

Supply more than one line of text to an ion-textarea that is within ion-item:

- Via attribute (value={`words are \n \n put here`}) gives a zero height when the page is refreshed or loaded.
- Via slot (<ion-textarea>{`words are \n \n put here`}<) gives correct behaviour but this content does not appear within the child textarea element resulting in uneditable and duplicate text with any inputs

### Expected Behavior

Height behaviour of using slot, output behaviour of using attribute.

### Steps to Reproduce

Production demo - 
https://cranky-swartz-c7bdf8.netlify.app/

variously type text into each area and refresh the page 

### Code Reproduction URL

https://cranky-swartz-c7bdf8.netlify.app/

### Ionic Info

Ionic:

   ionic (Ionic CLI) : 4.12.0

System:

   NodeJS : v16.1.0
   npm    : 7.11.2
   OS     : macOS Big Sur

### Additional Information

Related issue: #18993

**Comment by liamdebeasi** [comment] 2021-07-21 12:59
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/21242.

**Closed by liamdebeasi** 2021-07-21 12:59 UTC
Labels: triage

**Comment by Lxstr** [comment] 2021-07-22 02:44
Hi @liamdebeasi my mistake, I missed that issue. I've continued discussion there. Cheers
