### ISSUE TITLE
bug: Popover focus trap breaks usage of material input fields which are rendered outside of the popover

### ISSUE THREAD

**Issue by digaus** [ionic-team/ionic-framework#25593] opened 2022-07-08 08:22 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

Cannot focus the input inside `mat-select` popover which is placed inside an Ionic Popover.

Reason is this change: https://github.com/ionic-team/ionic-framework/commit/fff4aec6cfbd48566594a05f4af57dd0578977a8#diff-e6fe3d2c2375aaff02644f8767f36a3c49825d333f9764644871b0541a95b296R150

Since the input is rendered inside the cdk overlay it is outside of the popover and will be caught by the focus trap.

![image](https://user-images.githubusercontent.com/15358538/177948983-c51d6754-0c8f-4c2b-8ea0-5e38fb5ed264.png)

### Expected Behavior

Being able to focus inputs outside the popover element if they are on top of the backdrop.

### Steps to Reproduce

Add an input to the mat-select inside a popover

### Ionic Info

Am not using the Ionic CLI, only `"@ionic/angular": "6.1.12"`

**Comment by digaus** [comment] 2022-07-08 08:28
Nevermind, I can just add `ion-disable-focus-trap`

**Comment by digaus** [comment] 2022-07-08 08:37
Reopen because it is not documented anywhere but in code:

https://github.com/ionic-team/ionic-framework/blob/main/core/src/utils/overlays.ts#L151

**Comment by liamdebeasi** [comment] 2022-07-08 13:43
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/24646.

You can use `ion-disable-focus-trap`, but it is a private API and not subject to the normal breaking change rules so use with caution.

**Closed by liamdebeasi** 2022-07-08 13:43 UTC
Labels: triage
