### ISSUE TITLE
bug: Side menu gets overlapped by the menu-bar on iPhone 11/12 max

### ISSUE THREAD

**Issue by basvdijk** [ionic-team/ionic-framework#22681] opened 2020-12-15 08:05 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
When generating a new side-menu project, the menu content gets overlapped by the menu-bar on the iPhone 11/12 Max
![image](https://user-images.githubusercontent.com/644550/102187400-3b02b280-3eb4-11eb-85af-e0db717936fa.png)

**Expected behavior:**
The top of the side menu being below the menu-bar

**Steps to reproduce:**
ionic start (choose Angular, side-menu)
npx cap add ios
npx cap copy && npx cap sync

Open `app.component.html` and add "this is a test" as shown below

```
      <ion-content>
        This is a test
        <ion-list id="inbox-list">`
```

ionic build --prod
npx cap open ios

Run the app in the iPhone 11 Max simulator
Open the side menu

You'll see the text is covered
![image](https://user-images.githubusercontent.com/644550/102187282-13abe580-3eb4-11eb-8518-0c7a4c8d02a9.png)

**Related code:**
You can't see the behaviour in the browser. You have to run it in a iPhone 11/12 Max (simulator).

Github repo with test project: https://github.com/basvdijk/ionic-side-menu-ios-overlap

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.11.8 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.5.2
   @angular-devkit/build-angular : 0.1000.8
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Capacitor:

   Capacitor CLI   : 2.4.5
   @capacitor/core : 2.4.5

Utility:

   cordova-res (update available: 0.15.2) : 0.14.0
   native-run (update available: 1.3.0)   : 0.3.0

System:

   NodeJS : v12.13.0 (/usr/local/bin/node)
   npm    : 6.14.5
   OS     : macOS Catalina
```

**Comment by BerkeAras** [comment] 2020-12-15 08:12
@basvdijk Could you reproduce this? A repository would be great 👍

**Comment by basvdijk** [comment] 2020-12-15 08:15
@BerkeAras Here you go: https://github.com/basvdijk/ionic-side-menu-ios-overlap

**Comment by liamdebeasi** [comment] 2020-12-15 14:28
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/19482.

**Closed by liamdebeasi** 2020-12-15 14:28 UTC
Labels: triage

**Comment by basvdijk** [comment] 2020-12-15 14:31
@liamdebeasi I couldn't find when searching thanks! Do you know in what release this fix is packed?
