### ISSUE TITLE
bug: Popover overflowing if in footer

### ISSUE THREAD

**Issue by Eraldo** [ionic-team/ionic-framework#25594] opened 2022-07-08 10:02 UTC
### Ionic Framework Version

- [X] v6.x

### Current Behavior

The popover renders in such a way that I cannot still see its content as it is off screen.

<img width="283" alt="image" src="https://user-images.githubusercontent.com/73378/177967706-091ea69b-b920-421d-85b7-dbba6863437a.png">

### Expected Behavior

The popover renders in such a way that I can still see its content.

Example: (manually repositioned via hardcoding in console after rendering)
<img width="277" alt="image" src="https://user-images.githubusercontent.com/73378/177968010-a72ea96c-2b43-4ce6-8084-cc79aa3cc9b0.png">

### Steps to Reproduce

1. Run this stackblitz: https://ionic-angular-popover-overflow-issue.stackblitz.io/
2. Click on the trigger button down in the footer of the running application.
3. Verify that the popover content is not visible.

### Code Reproduction URL

https://stackblitz.com/edit/ionic-angular-popover-overflow-issue?file=src%2Fapp%2Fapp.component.html

### Ionic Info

```
Ionic:

   Ionic CLI                     : 6.20.1 (/opt/homebrew/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.1.11
   @angular-devkit/build-angular : 14.0.0
   @angular-devkit/schematics    : 13.3.5
   @angular/cli                  : 14.0.0
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.5.1
   @capacitor/android : not installed
   @capacitor/core    : 3.5.1
   @capacitor/ios     : not installed

Utility:

   cordova-res                          : not installed globally
   native-run (update available: 1.6.0) : 1.5.0

System:

   NodeJS : v18.4.0 (/opt/homebrew/Cellar/node/18.4.0/bin/node)
   npm    : 8.12.1
   OS     : macOS Monterey

```

**Comment by leighbriody** [comment] 2022-07-08 10:48
Hello,

Not sure if this is the correct way your looking to resolve this but its a solution that worked for me :).

1) I added a class to the <ion-popover> element called "popover"
2) Then I added a style to this in the CSS file to change the position and keep it above it.


**Ionic Popover**
<ion-popover trigger="trigger-button" side="top" class="popover">
      <ng-template>
        <ion-content class="popover">
          <ion-list>
            <ion-item>
              <ion-label> Item 1 </ion-label>
            </ion-item>
            <ion-item>
              <ion-label> Item 2 </ion-label>
            </ion-item>
          </ion-list>
        </ion-content>
      </ng-template>
    </ion-popover>

**style.css**
.popover {
  position: static;
  margin-bottom: 32%;
}


_**Result**_
<img width="335" alt="result" src="https://user-images.githubusercontent.com/56975162/177978114-7ff57fcd-1969-4bd1-80ad-c0e9f17caa0e.png">

**Comment by liamdebeasi** [comment] 2022-07-08 13:42
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/24780.

**Closed by liamdebeasi** 2022-07-08 13:42 UTC
Labels: triage
