### ISSUE TITLE
bug: Standalone components not usable in jest

### ISSUE THREAD

**Issue by Squixx** [ionic-team/ionic-framework#28667] opened 2023-12-07 16:10 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When using the ionic angular standalone components, jest will error out on imports within @stencil

e.g.
```
/node_modules/.pnpm/ionicons@7.2.1/node_modules/ionicons/components/ion-icon.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import { proxyCustomElement, HTMLElement, Build, h, Host } from '@stencil/core/internal/client';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      4 | import { NgModule } from '@angular/core';
      5 | import { ReactiveFormsModule } from '@angular/forms';
    > 6 | import {
        | ^
      7 |   ActionSheetController,
      8 |   IonActionSheet,
      9 |   IonPicker,

 ```
      
Normally (or atleast when not using standalone), you can transformIgnore stencil:
      
`transformIgnorePatterns: ['node_modules/(?!.*.mjs$|@ionic|@angular|@stencil|\\.pnpm/.*(@ionic|@stencil))'],`

        
 However with underlying imports this doesnt work (standalone -> component -> stencil) 
        
Now, as components were dynamically loaded this wasnt much of an issue.
      
However as `browser-esbuild ` cant be supported without using standalone components as said
      
https://github.com/ionic-team/ionic-framework/issues/28500
      
this becomes a blocking issue for moving towards esbuild for anyone who uses jest.
      
      
      
      

### Expected Behavior

jest tests can run when using standalone component imports

### Steps to Reproduce

I'll add a reproduction url start of next week

### Ionic Info

Ionic:

   Ionic CLI                     : 5.4.16 (/home/coredalae/.npm/_npx/864a9e3c2cd0cf50/node_modules/ionic)
   Ionic Framework               : not installed
   @angular-devkit/build-angular : 17.0.6 (/node_modules/.pnpm/@angular-devkit+build-angular@17.0.6_@angular+compiler-cli@17.0.6_@angular+service-worker@17._jfcdvyd4726gg7yc6y7g5hs5zi/node_modules/@angular-devkit/build-angular)
   @angular-devkit/schematics    : 17.0.6 (/node_modules/.pnpm/@angular-devkit+schematics@17.0.6/node_modules/@angular-devkit/schematics)
   @angular/cli                  : 17.0.6 (/node_modules/.pnpm/@angular+cli@17.0.6/node_modules/@angular/cli)
   @ionic/angular-toolkit        : 9.0.0 (/node_modules/.pnpm/@ionic+angular-toolkit@9.0.0/node_modules/@ionic/angular-toolkit)

Capacitor:

   Capacitor CLI   : 5.5.1
   @capacitor/core : 5.5.1 (/node_modules/.pnpm/@capacitor+core@5.5.1/node_modules/@capacitor/core)

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v20.10.0 (/home/coredalae/.nvm/versions/node/v20.10.0/bin/node)
   npm    : 10.2.3
   OS     : Linux 5.15

**Comment by liamdebeasi** [comment] 2023-12-07 16:38
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. Ionic's standalone components are ES Modules which Jest does not support. The `transformIgnorePatterns` usage is recommended here to transpile ES Modules to a format that Jest can use.

Adding the following to your Jest config should resolve the issue:

```json
{
  ...,
  "transformIgnorePatterns": ["node_modules/(?!(@ionic/angular|@ionic/core|ionicons|@stencil/core|@angular/*)/)"]
}
```

I've added a PR to note this on the Ionic docs: https://github.com/ionic-team/ionic-docs/pull/3298

**Closed by liamdebeasi** 2023-12-07 16:38 UTC
Labels: triage
