### ISSUE TITLE
feat: ion-datetime with multiple date selection

### ISSUE THREAD

**Issue by Saqib92** [ionic-team/ionic-framework#24674] opened 2022-01-28 09:54 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

There should be an option to select multiple dates or Date range to select Multiple dates. 

### Describe the Use Case

Use case might be a travel related application. like if someone wants to reserve hotel room he can select a range of multiple dates. 

### Describe Preferred Solution

New option to pass in properties. `[range]="true"` and for multiple different dates : `[multiple]="true"` and default `false` for both. 

### Describe Alternatives

https://github.com/hsuanxyz/ion2-calendar

### Related Code

`<ion-datetime [range]="true"></ion-datetime>`

### Additional Information
<img width="400" alt="calendar-1" src="https://user-images.githubusercontent.com/7135885/151526011-6b3e6b80-da1c-4dc8-bf00-375464059617.png">

Can take range example from here:
https://github.com/hsuanxyz/ion2-calendar

**Comment by amandaesmith3** [comment] 2022-01-28 16:16
Thanks for the feature request. Selecting a range of dates is a duplicate of https://github.com/ionic-team/ionic-framework/issues/23572, but we can use this to track selecting multiple, separate dates. I discussed with the team and we agree this feature would be a good fit for Ionic 👍

**Comment by liamdebeasi** [comment] 2022-07-26 20:30
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/25514, and this feature should be available in an upcoming minor release of Ionic.

**Closed by liamdebeasi** 2022-07-26 20:30 UTC
Labels: type: feature request, package: core
