### ISSUE TITLE
bug: NullInjectorError with modal providers dependencies

### ISSUE THREAD

**Issue by AnTiiK** [ionic-team/ionic-framework#23071] opened 2021-03-18 16:52 UTC
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
NullInjectorError when opening a modal through a service not provided in the root and which contains another service also not provided in the root.
Both services are injected into modules that are correctly injected in the sub-services (there are no errors in the injection chain)

**Expected behavior:**
The modal should open without triggering NullInjectorError exception

**Steps to reproduce:**
See repro 

**Related code:**
https://stackblitz.com/edit/angular-ivy-sdkokk?devtoolsheight=33&file=src/app/home/home.component.html

**Other information:**
The workaround is to inject the "in root" provider into a shared module

**Ionic info:**

```
Ionic:

   Ionic CLI : 6.12.4

Utility:

   cordova-res : 0.15.3
   native-run  : 1.3.0

System:

   NodeJS : v12.20.1
   npm    : 6.14.10
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment] 2021-03-18 19:18
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. By declaring providers in the two modal components you are creating new instances and disconnecting from the root providers. Here is a StackBlitz which shows the correct way to add these providers: https://stackblitz.com/edit/angular-ivy-fgwq9z?file=src%2Fapp%2Fmodal1%2Fmodal1.module.ts

**Closed by liamdebeasi** 2021-03-18 19:18 UTC
Labels: triage
