### ISSUE TITLE
bug: IonInput of type password does not recognize autofill of credentials by iOS Password Manager or LastPass

### ISSUE THREAD

**Issue by ldikmans** [ionic-team/ionic-framework#24167] opened 2021-11-05 00:28 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [X] v6.x

### Current Behavior

Given a simple form with 2 IonInput elements (user/password login). It can be set up to be recognized by iOS Password Manager to fill in credentials from iOS Keychain.

The login button will be enabled when the password and username are both filled. 
The read values button will display the value when pressed.

Input elements are actually filled with data, BUT the IonInput of type password does not recognize the changed value of the underlying native html input element. This can be visually seen as the login button is not enabled. Also when reading the value from IonInput it is just empty.

### Expected Behavior

The onInput event to be fired and the login button to be enabled
The read values button to return the username and password that was automatically completed by the password manager

### Steps to Reproduce

1. Create an ionic app based on an empty template `ionic start MyIonicApp blank --type=react`
2. Add two inputfields and two buttons. The first button will be enabled when both the username and password are present, the second button reads the values from the variables
3. Add iOS support `ionic cap add ios`
4. Install the pod 'pod install' 
4. Run the app in the simulator
5. Login and use a password manager to automatically fill the password field

Login button stays disabled, read values shows empty password field

### Code Reproduction URL

https://github.com/ldikmans/InputFIeldBug.git

### Ionic Info

Ionic:

   Ionic CLI       : 6.16.3 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.8.5

Capacitor:

   Capacitor CLI      : 3.3.0
   @capacitor/android : 3.3.0
   @capacitor/core    : 3.3.0
   @capacitor/ios     : 3.3.0

Utility:

   cordova-res (update available: 0.15.3) : 0.15.1
   native-run                             : 1.5.0

System:

   NodeJS : v14.15.4 (/usr/local/Cellar/node@14/14.15.4/bin/node)
   npm    : 6.14.10
   OS     : macOS Monterey

### Additional Information

This seems the same issue as is described in this (stale) issue that was closed because there was no reproduction code added: [https://github.com/ionic-team/ionic-framework/issues/22682](https://github.com/ionic-team/ionic-framework/issues/22682)

screen shot in simulator of disabled login button (when using password manager)

![image](https://user-images.githubusercontent.com/14298582/140438526-808c617f-6314-436f-a158-6b965874291c.png)

screen shot in simulator of enabled login button (when typing the password)

![image](https://user-images.githubusercontent.com/14298582/140438664-c8d17a0f-2c26-4d43-b339-173aa43c6dfc.png)

**Comment by liamdebeasi** [comment] 2021-11-05 13:59
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/23335.

**Closed by liamdebeasi** 2021-11-05 13:59 UTC
Labels: triage

**Comment by ldikmans** [comment] 2021-11-05 15:03
In the issue mentioned a workaround is described for Angular.

The workaround for Ionic React is as follows:

`useIonViewDidEnter(async () => {
    const passwordInput = document.getElementById("login-form-input-password") as HTMLIonInputElement;

    passwordInput.onchange = (event: any) => {
      if (event.target?.value) {
         setPassword(event.target?.value);
}
    };

    const usernameInput = document.getElementById("login-form-input-name") as HTMLIonInputElement;

    usernameInput.onchange = (event: any) => {
      if(event.target?.value){
        setUsername(event.target?.value);
    };

  });`
