### ISSUE TITLE
bug: Menu Drag-Gestures bugs since Cordova-ios@6.1.0

### ISSUE THREAD

**Issue by HansKrywaa** [ionic-team/ionic-framework#21876] opened 2020-08-04 15:50 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

I just upgraded my App from **cordova-ios** `5.1.1` to `6.1.0`. Now the Menu bugs while drag gesture. See the attached Video: https://www.dropbox.com/s/r4kvp9vsz6vfu7v/Ionic%20Bug.MP4?dl=0

**Expected behavior:**

Not to bug while dragging 😃

**Ionic info:**

```
Ionic CLI                     : 6.11.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.3.1
   @angular-devkit/build-angular : 0.1000.5
   @angular-devkit/schematics    : 10.0.5
   @angular/cli                  : 10.0.5
   @ionic/angular-toolkit        : 2.3.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : ios 6.1.0-dev
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 50 other plugins)

Utility:

   cordova-res : 0.15.1
   native-run  : 1.0.0

System:

   Android SDK Tools : 25.2.3 (/Users/hanskrywalsky/Library/Android/sdk)
   ios-deploy        : 1.10.0
   ios-sim           : 8.0.2
   NodeJS            : v12.16.1 (/usr/local/bin/node)
   npm               : 6.14.7
   OS                : macOS Catalina
   Xcode             : Xcode 11.6 Build version 11E708
```

**Comment by HansKrywaa** [comment] 2020-08-04 17:51
Hey @liamdebeasi 😊
I just created this Repo: https://github.com/HansKrywaa/ionic-menu-bug

Additional Info: I don't use `cordova-ios@6.1.0` directly, i uses [this Fork](https://github.com/dpa99c/cordova-ios), because it uses the latest `cordova-common`, which resolves some [other Issues](https://github.com/apache/cordova-common/compare/rel/4.0.1...master). The Problem seems to be because of this, but because this will be released in a future Reason it should work as well? 🤔

**Comment by liamdebeasi** [comment] 2020-08-05 13:39
Does this issue happen when using an official version of cordova-ios? If this is only happening using a fork, it likely is not a bug in Ionic Framework.

**Comment by HansKrywaa** [comment] 2020-08-05 13:45
It happens if i use the Fork, **BUT** the only Change to `6.1.0` is that the Fork uses the Master Branch of `cordova-common`, instead of `4.0.1` ([See here](https://github.com/apache/cordova-ios/compare/rel/6.1.0...dpa99c:master)). So as this Changes in **cordova-common** will be released in a Future Version, this Changes will be relevant? 🤔

**Comment by liamdebeasi** [comment] 2020-08-05 13:55
What version of iOS are you testing this on?

**Comment by HansKrywaa** [comment] 2020-08-05 13:56
13.6 iPhone 11 Pro

**Comment by liamdebeasi** [comment] 2020-08-05 14:02
Thanks! I can reproduce this on Cordova, but not on Capacitor. Seems to be a bug in Cordova, but I will keep digging.

**Comment by liamdebeasi** [comment] 2020-08-05 14:42
The issue appeared after this PR (https://github.com/apache/cordova-ios/pull/790) in cordova-ios@6.0.0. For now, I recommend sticking with cordova-ios@5.1.1 or using Capacitor.

**Comment by HansKrywaa** [comment] 2020-08-05 14:45
Capacitor is sadly not possible, because the mai  part of out app is Google Maps. Also I'm using `cordova-ios@6.1.0` without this Bug. Only the Fork with the other **cordova-common** makes this buggy 🤔 So can it really be because of a PR in **6.0.0**?

**Comment by liamdebeasi** [comment] 2020-08-05 14:52
I was able to reproduce this issue in stable versions of cordova-ios 6.0.0 and 6.1.0 (but not 5.1.1). I cloned `cordova-ios` and built it locally, resetting commits until I found that the bug happens only after https://github.com/apache/cordova-ios/pull/790.

(Also, the Google Maps developer is working on a Capacitor plugin https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/2781 😄 )

**Comment by HansKrywaa** [comment] 2020-08-05 14:55
Okay i will open a Issue in Cordova-Ios for the Moment 😊 Thank you!

**Comment by liamdebeasi** [comment] 2020-08-05 15:10
I further isolated the issue. It looks there is some kind of performance problem with Cordova when managing Web Animations. I will create a reproduction and add a follow up to your issue.

Once I do that I will close this issue out. Thanks!

**Comment by liamdebeasi** [comment] 2020-08-05 16:11
Hmm it looks like I was using some cached dependencies when I did my original test.

I can reproduce this issue on cordova-ios@6.0.0 and on your fork, but not on cordova-ios@6.1.0. I am not entirely sure why this bug is happening -- it looks like a performance issue from my end. I recommend sticking with stable versions of cordova for now. If the issue appears in a stable release of cordova-ios, we can take another look.

**Closed by liamdebeasi** 2020-08-05 16:11 UTC
Labels: triage
