### ISSUE TITLE
bug: ion-modal throws exception in Ionic Vue Beta

### ISSUE THREAD

**Issue by afshad1** [ionic-team/ionic-framework#22144] opened 2020-09-22 19:58 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

Error when using Modal component:
```
"Error: framework delegate is missing
    at eval (webpack-internal:///./node_modules/@ionic/core/dist/esm-es5/framework-delegate-d1eb6504.js:15:27)
    at step (webpack-internal:///./node_modules/tslib/tslib.es6.js:124:23)
    at Object.eval [as next] (webpack-internal:///./node_modules/tslib/tslib.es6.js:105:53)
    at eval (webpack-internal:///./node_modules/tslib/tslib.es6.js:98:71)
    at new Promise (<anonymous>)
    at __awaiter (webpack-internal:///./node_modules/tslib/tslib.es6.js:94:12)
    at attachComponent (webpack-internal:///./node_modules/@ionic/core/dist/esm-es5/framework-delegate-d1eb6504.js:6:157)
    at class_1.eval (webpack-internal:///./node_modules/@ionic/core/dist/esm-es5/ion-modal.entry.js:405:120)
    at step (webpack-internal:///./node_modules/tslib/tslib.es6.js:124:23)
    at Object.eval [as next] (webpack-internal:///./node_modules/tslib/tslib.es6.js:105:53)"
```

**Expected behavior:**

Modal component is showing up

**Steps to reproduce:**

Used the code from blog post in chapter "Doing Things the Vue Way":
https://ionicframework.com/blog/announcing-the-new-ionic-vue-beta/

1. Created new ionic app using
`ionic start my-app tabs --type vue --tag vue-beta`

2. Added new Modal component

3. Added Button for opening modal component

**Related code:**

```
<template>
  <ion-page class="ion-page">
    <ion-content class="ion-content ion-padding">
      <ion-button @click="openModal">Open Modal</ion-button>
    </ion-content>
  </ion-page>
</template>

<script>
import Modal from './modal.vue'

export default {
  methods: {
    openModal() {
      return this.$ionic.modalController
        .create({
          component: Modal,
          cssClass: 'my-custom-class',
          componentProps: {
            data: {
              content: 'New Content',
            },
            propsData: {
              title: 'New title',
            },
          },
        })
        .then(m => m.present())
    },
  },
}
</script>
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment] 2020-09-22 20:08
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/22090.

**Closed by liamdebeasi** 2020-09-22 20:08 UTC
Labels: triage
