### ISSUE TITLE
bug: ion-content automatically scrolls to routerLink

### ISSUE THREAD

**Issue by bashoogzaad** [ionic-team/ionic-framework#24660] opened 2022-01-26 10:30 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

I am using Angular with Ionic 6.

When opening the side-menu, the `ion-content` is automatically scrolling to the highest routerLink. That means the scroll position is not preserved, which is not very obvious for users. I have tested this with the Ionic Conference App by extending the height of the list in the ion-content, which results in the ion-content being able to scroll. When reopening the menu, the ion-content scrolls to the top.

### Expected Behavior

I would expect that the scroll position is being preserved, but maybe this behaviour is intentional.

### Steps to Reproduce

Clone the Ionic conference app for Angular, extend the height such that the ion-content is scrollable and reopen the menu.

### Code Reproduction URL

https://github.com/ionic-team/ionic-conference-app

### Ionic Info

Ionic:

   Ionic CLI                     : 6.18.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.0-rc.2
   @angular-devkit/build-angular : 13.0.1
   @angular-devkit/schematics    : 13.0.1
   @angular/cli                  : 13.0.1
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : not installed
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   ios-sim : 8.0.2
   NodeJS  : v17.2.0 (/usr/local/Cellar/node/17.2.0/bin/node)
   npm     : 8.1.4
   OS      : macOS Big Sur
   Xcode   : Xcode 13.2.1 Build version 13C100

**Comment by sean-perkins** [comment] 2022-01-26 16:37
Closing as a duplicate of #24634. Thanks for reporting this issue! I'll add the additional information you've provided in this issue into the original.

**Closed by sean-perkins** 2022-01-26 16:37 UTC
Labels: triage
