### ISSUE TITLE
bug: ion-item with solid fill inside ion-accordion content is missing bottom border in md-mode

### ISSUE THREAD

**Issue by PhilippeKayser** [ionic-team/ionic-framework#24613] opened 2022-01-20 19:04 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Having an ion-item with fill="solid" inside an ion-accordion, the bottom border is missing when mode is md. ion-item is correctly rendered when mode is ios.

### Expected Behavior

The ion-item should have the bottom border visible

### Steps to Reproduce

Implementation reproducing the issue is available in the repository provided.

### Code Reproduction URL

https://github.com/PhilippeKayser/ion-accordion-bug

### Ionic Info

Ionic:

   Ionic CLI                     : 6.18.1 (/Users/philippe/.config/yarn/global/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.3
   @angular-devkit/build-angular : 13.1.4
   @angular-devkit/schematics    : 12.2.15
   @angular/cli                  : 13.1.4
   @ionic/angular-toolkit        : 5.0.3

Capacitor:

   Capacitor CLI      : 3.4.0
   @capacitor/android : not installed
   @capacitor/core    : 3.4.0
   @capacitor/ios     : not installed

Utility:

   cordova-res (update available: 0.15.4) : 0.15.3
   native-run                             : 1.5.0

System:

   NodeJS : v16.13.1 (/usr/local/bin/node)
   npm    : 8.3.0
   OS     : macOS Monterey

### Additional Information

I'm not sure, but it seems a bit like the border is "there" but just overlayed by something else, as the border appears when focused, but a bit thinner than if it weren't in the accordion component. I hope you see what I mean.

**Comment by liamdebeasi** [comment] 2022-01-20 22:09
Thanks, I can reproduce this. The issue is that our styles intend to remove the border on the `ion-item` in the header of an accordion, but we target all `ion-item` elements inside of an accordion, resulting in this issue: https://github.com/ionic-team/ionic-framework/blob/main/core/src/css/core.scss#L285

**Comment by liamdebeasi** [comment] 2022-01-21 14:42
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/24618, and a fix will be available in an upcoming release of Ionic Framework.

**Closed** 2022-01-21 14:42 UTC
Labels: package: core, type: bug
