### ISSUE TITLE
bug: ionic vue vscode incorrectly warning about deprecated slots

### ISSUE THREAD

**Issue by Sacrekin** [ionic-team/ionic-framework#22236] opened 2020-10-02 11:25 UTC
# Bug Report

**Ionic version:**
[x] **5.x**
**Ionic Vue version:**
0.4.0

**Current behavior:**
Ionic components rely upon Slot attributes which is deprecated in V3 in favor of the v-slot template directive.

**Expected behavior:**
Compliance with V3

**Steps to reproduce:**
Using for example the Ionic-Range, there is no way to position the label using the new v-slot directive

**Related code:**

In the example below, the "start" label **will not show** using the V3 v-slot directive; Using the slot attribute for the "end" label **does show** as expected, albeit using a deprecated approach

            <ion-range min="-200" max="200" color="secondary" v-model="range">
              <template v-slot:start>
                <ion-label>{{range}}</ion-label>
              </template>
              <ion-label slot="end">{{range}}</ion-label>
            </ion-range>

**Comment by liamdebeasi** [comment] 2020-10-05 13:18
Thanks for the issue. The slots Ionic Framework uses are not the same as Vue 2 slots. The slots we use are Web Component slots and are valid usage: https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_templates_and_slots.

**Comment by nathantaal** [comment] 2020-10-09 09:54
@liamdebeasi but how do you suggest we fix this, becuase eslint hardly fails on this, meaning development is not possible. Maybe you can overwrite this error by creating a stylelint for ionic vue?

**Comment by liamdebeasi** [comment] 2020-10-09 13:37
What I did to solve this was I disabled the slot check in the `.eslintrc.js` file for the Ionic Vue starter apps. Here is what the eslint file looks like:

```js
module.exports = {
  root: true,
  env: {
    node: true
  },
  'extends': [
    'plugin:vue/vue3-essential',
    'eslint:recommended',
    '@vue/typescript/recommended'
  ],
  parserOptions: {
    ecmaVersion: 2020
  },
  rules: {
    'no-console': process.env.NODE_ENV === 'production' ? 'warn' : 'off',
    'no-debugger': process.env.NODE_ENV === 'production' ? 'warn' : 'off',
    'vue/no-deprecated-slot-attribute': 'off',
    '@typescript-eslint/no-explicit-any': 'off',
  },
  overrides: [
    {
      files: [
        '**/__tests__/*.{j,t}s?(x)',
        '**/tests/unit/**/*.spec.{j,t}s?(x)'
      ],
      env: {
        jest: true
      }
    }
  ]
}
```

Note the `'vue/no-deprecated-slot-attribute': 'off',` line. Let me know if this does not solve the issue.

**Comment by Sacrekin** [comment] 2020-10-11 13:48
As it goes, this rule was already included in my current project. And I still get the eslint warning as follows:


Used on content inserted into child components to indicate which named slot the content belongs to.

API Reference

[vue/no-deprecated-slot-attribute]
`slot` attributes are deprecated.eslint-plugin-vue


________________________________

**Comment by Sacrekin** [comment] 2020-10-11 13:53
my-app@0.0.1 C:\Users\Chouchou\ionicTest\my-app
+-- @ionic/vue@0.4.0
+-- @ionic/vue-router@0.4.0
+-- @types/jest@24.9.1
+-- @typescript-eslint/eslint-plugin@2.34.0
+-- @typescript-eslint/parser@2.34.0
+-- @vue/cli-plugin-babel@4.5.6
+-- @vue/cli-plugin-e2e-cypress@4.5.6
+-- @vue/cli-plugin-eslint@4.5.6
+-- @vue/cli-plugin-router@4.5.6
+-- @vue/cli-plugin-typescript@4.5.6
+-- @vue/cli-plugin-unit-jest@4.5.6
+-- @vue/cli-service@4.5.6
+-- @vue/compiler-sfc@3.0.0
+-- @vue/eslint-config-typescript@5.1.0
+-- @vue/test-utils@2.0.0-beta.6
+-- core-js@3.6.5
+-- eslint@6.8.0
+-- eslint-plugin-vue@7.0.1
+-- typescript@3.9.7
+-- vue@3.0.0
+-- vue-jest@5.0.0-alpha.4
`-- vue-router@4.0.0-beta.13

________________________________

**Comment by nathantaal** [comment] 2020-10-11 18:28
For me, this doesn't fix it neither

**Comment by liamdebeasi** [comment] 2020-10-12 15:56
What is the exact error/warning you are getting?

**Comment by Sacrekin** [comment] 2020-10-12 16:35
Used on content inserted into child components to indicate which named slot the content belongs to.

API Reference

[vue/no-deprecated-slot-attribute]
`slot` attributes are deprecated.eslint-plugin-vue

In VS Code, getting the wiggled red line below the slot. Hovering on it, I get the tip you see above.

________________________________

**Comment by liamdebeasi** [comment] 2020-10-12 16:36
@Sacrekin What does your `.eslintrc.js` file look like?

**Comment by Sacrekin** [comment] 2020-10-13 08:10
module.exports = {
  root: true,
  env: {
    node: true
  },
  'extends': [
    'plugin:vue/vue3-essential',
    'eslint:recommended',
    '@vue/typescript/recommended'
  ],
  parserOptions: {
    ecmaVersion: 2020
  },
  rules: {
    'no-console': process.env.NODE_ENV === 'production' ? 'warn' : 'off',
    'no-debugger': process.env.NODE_ENV === 'production' ? 'warn' : 'off',
    'vue/no-deprecated-slot-attribute': 'off',
    '@typescript-eslint/no-explicit-any': 'off',
  },
  overrides: [
    {
      files: [
        '**/__tests__/*.{j,t}s?(x)',
        '**/tests/unit/**/*.spec.{j,t}s?(x)'
      ],
      env: {
        jest: true
      }
    }
  ]
}



________________________________

**Comment by liamdebeasi** [comment] 2020-10-14 16:39
@Sacrekin Can you reproduce this in a blank Ionic Vue starter app? I am not sure why you are still getting the warning even after disabling it and cannot reproduce this on my end.

**Comment by Sacrekin** [comment] 2020-10-15 09:02
Did create a blank ionic starter app & migrated my test boilerplate app (very simple test).

Still getting the underline under scope on ion-label on tab 2 view.

I have posted the stater app directory on github: https://github.com/Sacrekin/TestIonic4Vue/tree/master/demo

________________________________

**Comment by liamdebeasi** [comment] 2020-10-15 13:58
Thanks! Is this warning from the VSCode ESLint plugin? I do see that it recognizes slot as a V2 API, but I don't see the warning (granted I don't see the warning even if I remove the `'vue/no-deprecated-slot-attribute': 'off'`)

**Comment by Sacrekin** [comment] 2020-10-15 16:30
Yes, it is from the VS Code plugin.

By the way, since we have this exchange, do you think you'll be able to add the global component registration? This point is certainly more important to us than the slot warning, albeit we appreciate the attention to details.

KInd rgds

________________________________

**Comment by liamdebeasi** [comment] 2020-10-15 16:32
Ok thanks -- I do not normally use VS Code, so I will investigate this some more. Regarding global component registration we have https://github.com/ionic-team/ionic-framework/issues/22182 which I see you opened. If we do add it, it won't be right at launch. I still need to look into it some more.

**Comment by Sacrekin** [comment] 2020-10-16 08:13
Thanks.

With regards to global registration, I have tested & it works fine. Appreciate the warning but by globally registering the layout & initial page UI components, I can already reduce substantially the registration list in the other views.

A+

________________________________

**Comment by Alyssa-Crawford-dmi** [comment] 2020-11-10 15:22
I am also getting errors from the linter about the usage of slots. 

[vue/no-unused-vars]
'start' is defined but never used

I am using a new ionic app and copy pasted the icon-items media-items example. 
I tried adding ```"vue/no-unused-vars": "off",``` to the .eslintrc.js file to see if that would fix it, but no luck

**Comment by 1beb** [comment] 2020-11-15 04:22
Can verify that this is happening for vsCode: 

![image](https://user-images.githubusercontent.com/421859/99162835-2f16ab80-26d0-11eb-870f-00e308e14a12.png)

and my `.eslint.js`:

![image](https://user-images.githubusercontent.com/421859/99162842-42c21200-26d0-11eb-8bba-0ed0858dd4a9.png)

It's definitely being told to ignore this particular linting error, but seems to ignore being told to ignore. How meta!

**Comment by Alyssa-Crawford-dmi** [comment] 2020-11-16 12:37
I created a side menu app since side bar was not an option. Beyond that, with the same configuration I got the same error as you, no-deprecated-slot attribute

**Comment by liamdebeasi** [comment] 2020-11-16 14:22
I am going to open this issue back up. At the moment I am not quite sure why disabling the eslint rule fixes it in other IDEs but not in VSCode.

**Comment by oliveready7** [comment] 2020-11-20 08:01
Hi guys,

I believe you're getting this issue because the Vetur plugin, not ESLint. 

Turn off the Vetur setting "validate vue-html in <template> using eslint-plugin-vue" and you'll see your project abiding by your .eslintrc.js rules.

<img width="811" alt="Screenshot 2020-11-20 at 07 58 36" src="https://user-images.githubusercontent.com/31158817/99775008-8076ce80-2b06-11eb-9781-54ebf5f565b6.png">

**Comment by 1beb** [comment] 2020-11-20 20:03
Check out the big brain on Oliver! Thx!

**Comment by mavyfaby** [comment] 2020-12-29 13:06
Thank you @oliveready7. You saved my day!

**Comment by liamdebeasi** [comment] 2021-01-06 20:16
Hey everyone,

I did some more digging and this actually seems like the intended behavior for Vetur. (See: https://github.com/vuejs/vetur/issues/2113)

The Vetur docs recommend doing what was suggested in https://github.com/ionic-team/ionic-framework/issues/22236#issuecomment-731000931. (See: https://vuejs.github.io/vetur/guide/linting-error.html#linting)

I am going to close this issue, but I have added a troubleshooting guide to Ionic Vue docs which should cover this issue for other developers: https://ionicframework.com/docs/vue/troubleshooting.

**Closed by liamdebeasi** 2021-01-06 20:16 UTC
Labels: package: vue
