### ISSUE TITLE
bug: parameterized routes do not play animations or set props on vue 3.4+

### ISSUE THREAD

**Issue by lvzhenbo** [ionic-team/ionic-framework#28774] opened 2024-01-03 13:18 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

The inability to jump is simply the original behavior of the vue-router

### Expected Behavior

Should have jumped.

### Steps to Reproduce

Update vue to 3.4, update @vitejs/plugin-vue to 5.0

### Code Reproduction URL

https://github.com/lvzhenbo/tsdm-app/tree/652cd1de3281772d6bdd2642d37b73567918efbc

### Ionic Info

[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package.json'

       Require stack:
       -
       C:\Users\29422\Desktop\tsdm-app\node_modules\.pnpm\@ionic+cli@7.2.0\node_modules\@ionic\cli\lib\project\index.js
       - C:\Users\29422\Desktop\tsdm-app\node_modules\.pnpm\@ionic+cli@7.2.0\node_modules\@ionic\cli\lib\index.js
       - C:\Users\29422\Desktop\tsdm-app\node_modules\.pnpm\@ionic+cli@7.2.0\node_modules\@ionic\cli\index.js
       - C:\Users\29422\Desktop\tsdm-app\node_modules\.pnpm\@ionic+cli@7.2.0\node_modules\@ionic\cli\bin\ionic

Ionic:

   Ionic CLI       : 7.2.0
   Ionic Framework : @ionic/vue 7.6.2

Capacitor:

   Capacitor CLI      : 5.6.0
   @capacitor/android : 5.6.0
   @capacitor/core    : 5.6.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v20.9.0 (C:\Program Files\nodejs\node.exe)
   npm    : 10.1.0
   OS     : Windows 10

**Comment by liamdebeasi** [comment] 2024-01-03 14:13
Hi there,

Can you please create a reproduction of the issue that includes only the code required to reproduce the problem?

**Comment by lvzhenbo** [comment] 2024-01-03 17:30
> Hi there,
> 
> Can you please create a reproduction of the issue that includes only the code required to reproduce the problem?

https://github.com/lvzhenbo/ionic-vue3.4

There are two commits here, the latest commit is the incorrect case and the penultimate commit is the correct case. Then it's a matter of clicking on the selection bar to switch routes, and you'll see some one page will refresh and the other won't

**Comment by lvzhenbo** [comment] 2024-01-03 17:31
I was creating the demo and realized that it may have nothing to do with the vue version update and everything to do with the @vitejs/plugin-vue version update

> > Hi there,
> > Can you please create a reproduction of the issue that includes only the code required to reproduce the problem?
> 
> [lvzhenbo/ionic-vue3.4](https://github.com/lvzhenbo/ionic-vue3.4)
> 
> There are two commits here, the latest commit is the incorrect case and the penultimate commit is the correct case. Then it's a matter of clicking on the selection bar to switch routes, and you'll see some one page will refresh and the other won't

**Comment by lvzhenbo** [comment] 2024-01-03 19:16
> Updating from Vue 3.3.13 to Vue 3.4.4 causes the issue to appear. However, I'm still able to reproduce the issue if I remove Ionic Framework from the application. Have you tried reporting this to the Vue team?

For vue-router this anomaly is instead normal. Related documentation: https://router.vuejs.org/guide/essentials/dynamic-matching.html#Reacting-to-Params-Changes

So I'm guessing that ionic has a workaround for this situation, which is now broken due to a vue version upgrade

**Comment by pavi2410** [comment] 2024-01-04 18:11
Here's a minimal reproduction of the bug: https://stackblitz.com/edit/web-platform-1yixqm?file=index.html

**Comment by ih84ds** [comment] 2024-01-07 21:22
> Updating from Vue 3.3.13 to Vue 3.4.4 causes the issue to appear. However, I'm still able to reproduce the issue if I remove Ionic Framework from the application. Have you tried reporting this to the Vue team?

Confirmed that downgrading my project from vue 3.4 to 3.3 resolved this issue. I was not able to find a workaround so that I could stay on 3.4.

It seems vue-router's `onBeforeRouteUpdate()` is firing and the `to` route has the correct params... but  the props are not being updated with the new parameters. I'm not sure how to coerce the props into seeing the new parameters. Seems like there *should* be a way...

**Comment by torgnywalin** [comment] 2024-01-16 15:53
We had a similar experience. When upgrading to vue 3.4.5 it started to reuse components when routing between two paths using same route with different params (`user/1`, `user/2`). Downgrading to 3.3.8 (the version we had before upgrade) solved the issue.

To me it seems like vue-router is following the documentation: 
 - routes will reuse components when route changes
 - using watcher or `onBeforeRouteUpdate` to update the component is working. 
 - Since component is reused we dont get ionic animations on navigation.

**Comment by maelp** [comment] 2024-01-17 17:17
Interested in knowing when this will be solved. Is this a vue issue, or is this that the ionic-vue-router should be updated to conform to the new vue-router ?

**Comment by liamdebeasi** [comment] 2024-01-17 17:41
It appears this new behavior is due to a breaking change in Vue: https://github.com/vuejs/core/issues/9916#issuecomment-1872602294

The commit for this has been reverted because it was a bigger breaking change than the team expected: https://github.com/vuejs/core/issues/9965#issuecomment-1875067499

I don't see the commit tagged in a release so I don't think it has been published yet. However, according to that comment it sounds like they still plan to ship this change at some point so I think it makes sense to prepare Ionic Vue for that future now.

**Comment by lvzhenbo** [comment] 2024-01-17 17:48
> It appears this new behavior is due to a breaking change in Vue: [vuejs/core#9916 (comment)](https://github.com/vuejs/core/issues/9916#issuecomment-1872602294)
> 
> The commit for this has been reverted because it was a bigger breaking change than the team expected: [vuejs/core#9965 (comment)](https://github.com/vuejs/core/issues/9965#issuecomment-1875067499)
> 
> It sounds like this was already released, so maybe there's something else causing an issue too.

From the [changelog](https://github.com/vuejs/core/blob/main/CHANGELOG.md#340-slam-dunk-2023-12-29), is it related to this pr (https://github.com/vuejs/core/pull/5912) ?

**Comment by liamdebeasi** [comment] 2024-01-17 18:10
Yeah that looks like it is related too. I'll start looking into how we can mitigate this inside of Ionic.

**Comment by liamdebeasi** [comment] 2024-01-17 21:29
Can everyone try the following dev build and let me know if the issue is resolved in their apps with Vue 3.4+?

```
npm install @ionic/vue@7.6.6-dev.11705526292.1bc0acb5 @ionic/vue-router@7.6.6-dev.11705526292.1bc0acb5
```

If you're using Vite you might need to remove `node_modules/.vite` before testing.

**Comment by lvzhenbo** [comment] 2024-01-17 21:37
https://github.com/lvzhenbo/ionic-vue3.4 
Validated, jumps fine, should be solved

**Comment by ih84ds** [comment] 2024-01-17 22:06
> Can everyone try the following dev build and let me know if the issue is resolved in their apps with Vue 3.4+?

Confirmed. That dev build works with `vue@3.4.14` for the routes I was experiencing the issue on.

**Comment by maelp** [comment] 2024-01-17 22:51
Nice! Will this be released in the next ionic update?

**Comment by mneciunas** [comment] 2024-01-18 14:05
> Can everyone try the following dev build and let me know if the issue is resolved in their apps with Vue 3.4+?
I can confirm as well, fixed the issue for me.

**Comment by liamdebeasi** [comment] 2024-01-19 21:44
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/28846, and a fix will be available in an upcoming release of Ionic Framework.

**Closed** 2024-01-19 21:43 UTC
Labels: package: vue, type: bug

**Comment by maelp** [comment] 2024-01-23 09:07
Thanks! Do you know when the release will be shipped?

**Comment by liamdebeasi** [comment] 2024-01-23 14:23
The bug fix will follow our patch release schedule: https://ionicframework.com/docs/reference/versioning#release-schedule
