### ISSUE TITLE
bug: Ionic Capacitor janky iOS scrolling

### ISSUE THREAD

**Issue by ollydixon** [ionic-team/ionic-framework#22393] opened 2020-10-26 21:30 UTC
We're reviewing Ionic as a future development solution. There are a few things we noticed that don't work correctly from the first hour of use. I really hoped these things would have been fixed since the last time I used Cordova ( 7 years ago ) but they have not 😔

The main issue is that when scrolling on iOS it's very janky, as in it jumps around / gives the impression of low quality. (Video: https://filebin.net/w0bnqyh4jrw76mbp/Screen_Recording_2020-10-26_at_22.25.35.mp4?t=syhhn23f)

The second one is that the components do not match the same actions as web. For example; IonRefresher doesn't work for desktop or Electron, not good.

Any ideas how we would fix the scrolling issue?

**Comment by liamdebeasi** [comment] 2020-10-26 21:46
Hey there,

This is actually a bug in WebKit, the engine that powers Safari/WKWebview, and not a bug in Capacitor.

The good news is that the bug has been fixed (see: https://bugs.webkit.org/show_bug.cgi?id=209968), the bad news is that the fix has not shipped yet.

From my understanding, this issue happens when you are overscrolling/rubber banding and you do something that causes a paint. Can you send your app's code in a GitHub repo? I can try and recommend and alternative to whatever CSS property you are changing.

**Comment by liamdebeasi** [comment] 2020-10-26 21:48
Regarding your other point, IonRefresher is really a touch-focused component so I don't think a pull to refresh experience with a mouse is going to be good regardless of which framework's refresher component you use.

**Comment by ollydixon** [comment] 2020-10-27 07:30
@liamdebeasi thanks Liam. It sucks that WebKit has this error is there any workaround? Disabling bounce shows a host of other errors.

Ah; it's a shame the platform isn't consistent with IonRefresher, what else isn't it consisent with? We now have to test every component across the platforms that really sucks.

I was really hoping this was in a professional state for development, I guess I'll come back in 2 years.

**Comment by liamdebeasi** [comment] 2020-10-27 13:07
As I mentioned previously, if you send your application code I can recommend a workaround to the WebKit issue. 

Regarding the IonRefresher, it is up to specifications, the problem is that the pull to refresh gesture has always been touch-focused which is why you do not find it in many desktop applications. The one exception I can think of is Apple News on macOS, but even then the pull to refresh gesture there is pretty janky.

The only other component I can think of that is not well suited for desktop is `ion-datetime`, but we are in the process of revamping it. One alternative I can recommend is https://github.com/duetds/date-picker which is well designed and works great on desktop.


Ionic Framework is production ready, so I hope it fits your use case! I am going to close this issue, but feel free to follow up with the repo and I can take a look.

**Closed by liamdebeasi** 2020-10-27 13:07 UTC
Labels: triage

**Comment by ollydixon** [comment] 2020-10-27 13:18
@liamdebeasi if I gave that janky scroll to a client test app and said this is a finished product they'd laugh us out of the room. 🙈. It's not production ready.

**Comment by liamdebeasi** [comment] 2020-10-27 13:21
Like I said before that scrolling jank is a WebKit bug and not a bug in Ionic Framework. I am going to lock this thread as the original issue has been addressed, thanks!
