### ISSUE TITLE
bug: month-year date formatter return invalid date for months with 30 days

### ISSUE THREAD

**Issue by jainank** [ionic-team/ionic-framework#25867] opened 2022-08-31 16:48 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

Today is Oct 31, 2022.
I am using the ion-datetime picker to let users pick only month-year.
So, I set the presentation as month-year.

After I select a month which has 30 days only, for ex: Nov-2025, I get date as (2025-11-31T09:00)(ISO Date).

Since November can't have 31 days, this bug is reproducible only on the 31st of the month.

Attached screenshot aswell from datetime class.
![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/1823533/187733887-9b9dde25-63b7-43a8-b703-13d82b673e19.png)

### Expected Behavior

It should return a valid date.

### Steps to Reproduce

- set presentation as month-year
- make sure current calender date is 31st
- select any month which has 30 days

### Ionic Info

Ionic:

   Ionic CLI                     : 6.18.1
   Ionic Framework               : @ionic/angular 6.1.9
   @angular-devkit/build-angular : 13.2.2
   @angular-devkit/schematics    : 13.2.2
   @angular/cli                  : 13.2.2
   @ionic/angular-toolkit        : 6.0.0

Cordova:

   Cordova CLI       : 10.0.0 (cordova-lib@10.1.0)
   Cordova Platforms : android 10.1.1, ios 6.2.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 36 other plugins)

Utility:

   cordova-res (update available: 0.15.4) : 0.15.0
   native-run                             : not installed globally

System:

   Android SDK Tools : 26.1.1 (/Users/ankitjain/Library/Android/sdk)
   ios-deploy        : 1.11.3
   ios-sim           : 8.0.2
   NodeJS            : v14.15.1 (/Users/ankitjain/.nvm/versions/node/v14.15.1/bin/node)
   npm               : 6.14.8
   OS                : macOS Monterey
   Xcode             : Xcode 13.3 Build version 13E113

**Comment by liamdebeasi** [comment] 2022-08-31 17:58
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/25585.

Note: The particular issue mentions preserving the date when switching the month, but the underlying issue is the same. I mention some possible solutions in https://github.com/ionic-team/ionic-framework/issues/25585#issuecomment-1177681781:

> If the selected day does not exist (for example, going from July 31 to June would not work because there is no June 31), then the selected date should be the closest previous date. For the July --> June example, June 30 would be selected because it is the closest previous date.

**Closed by liamdebeasi** 2022-08-31 17:58 UTC
Labels: triage
