### ISSUE TITLE
bug: Inline Modal that is opened from a Controller modal does not listen to events 

### ISSUE THREAD

**Issue by ldikmans** [ionic-team/ionic-framework#28840] opened 2024-01-17 10:22 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

We have a controller modal with an image inside. Clicking on the image will open an inline modal with the image, so you can zoom etc. This inline modal does not listen to events.

### Expected Behavior

The inline modal that is opened from the controller modal listens to events.

### Steps to Reproduce

1.  Get the code from the repository
2  Run npm install
3. Run the app (ionic serve)
4. Open the first modal
5. Open the second modal
6. Try to close it -> fails, except when you click in the page (outside of the modal)

### Code Reproduction URL

https://github.com/ldikmans/ionic-react-nested-modal-bug

### Ionic Info

Ionic:

   Ionic CLI       : 7.1.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 7.5.0

Capacitor:

   Capacitor CLI      : 5.5.0
   @capacitor/android : 5.5.0
   @capacitor/core    : 5.5.0
   @capacitor/ios     : 5.5.0

Utility:

   cordova-res                          : 0.15.4
   native-run (update available: 2.0.0) : 1.7.3

System:

   NodeJS : v20.8.0 (/usr/local/Cellar/node/20.8.0/bin/node)
   npm    : 10.1.0
   OS     : macOS Unknown

### Additional Information

This bug is very similar to [https://github.com/ionic-team/ionic-framework/issues/28819](https://github.com/ionic-team/ionic-framework/issues/28819).

I have added a custom listener to the button, that solves the problem but it is a lot of work and obviously not the way to go because we picked the framework because it handles the issue. It would mean we would have to add custom listeners for gestures etc.

When you use a controller modal inside the controller modal it works. So maybe this is timing issue?

**Comment by liamdebeasi** [comment] 2024-01-17 17:10
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/28819.

**Closed by liamdebeasi** 2024-01-17 17:10 UTC
Labels: triage
