### ISSUE TITLE
bug: ion-split-pane with two menus + ion-menu-button breaking on Safari

### ISSUE THREAD

**Issue by AVatch** [ionic-team/ionic-framework#21742] opened 2020-07-13 15:27 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

When opening and closing the menus on Safari (Version 14.0 (16610.1.15.51.6)) using the ion-menu-button or programmatically causes erratic behavior (see video attached).

**Expected behavior:**

Menus should open and close as expected on the user input.

**Steps to reproduce:**

**Related code:**
A sample application via GitHub
https://github.com/AVatch/ionic-safari-menu-toggle-bug

**Other information:**
Video
https://youtu.be/nqY-DHrd9Ow

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.10.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.2.3
   @angular-devkit/build-angular : 0.901.11
   @angular-devkit/schematics    : 9.1.11
   @angular/cli                  : 9.1.11
   @ionic/angular-toolkit        : 2.2.0


Capacitor:

   Capacitor CLI   : 2.2.1
   @capacitor/core : 2.2.1

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v14.4.0 (/usr/local/bin/node)
   npm    : 6.14.5
   OS     : macOS
```

**Comment by liamdebeasi** [comment] 2020-07-13 16:23
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. There is a bug in Safari 14 that causes issues with cubic-bezier easing curves when using Web Animations that is causing this behavior. I reported the bug (https://bugs.webkit.org/show_bug.cgi?id=213495), and it has since been fixed. The patch should land in an upcoming macOS Big Sur/iOS 14 beta.

**Closed by liamdebeasi** 2020-07-13 16:23 UTC
Labels: triage

**Comment by AVatch** [comment] 2020-07-13 16:25
Perfect - just sharing to bring it up on your radar since I couldn't find a previous issues on it. Thanks!
