### ISSUE TITLE
bug: React IonTab do not display in mobile client

### ISSUE THREAD

**Issue by TheSoils** [ionic-team/ionic-framework#27705] opened 2023-06-27 02:02 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

I want to use tab in my app, and follow the content "working with tabs" in the doc "react navigation" ,  it is success in broswer, but get blank in ios and android mobile phone
![image](https://github.com/ionic-team/ionic-framework/assets/29093597/41fe0acf-a571-4e41-80f5-ca0cb4254d63)
![image](https://github.com/ionic-team/ionic-framework/assets/29093597/51bf94da-5b86-457f-a3bd-7157e9497286)
![image](https://github.com/ionic-team/ionic-framework/assets/29093597/3f2bdb08-c872-4227-9cef-01d27d7176de)
![image](https://github.com/ionic-team/ionic-framework/assets/29093597/cc5935d1-5049-46f2-9a32-fb901ffd001d)

### Expected Behavior

success display in mobile client

### Steps to Reproduce

1. ionstart a new app
2. follow "working with tabs" in "react navigation"

### Ionic Info

Ionic:

   Ionic CLI       : 7.1.1 (/Users/wyman/.nvm/versions/node/v16.19.0/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 7.1.0

Capacitor:

   Capacitor CLI      : 5.0.5
   @capacitor/android : 5.0.5
   @capacitor/core    : 5.0.5
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.2

System:

   NodeJS : v16.19.0 (/Users/wyman/.nvm/versions/node/v16.19.0/bin/node)
   npm    : 9.6.1
   OS     : macOS Unknown

### Additional Information

if change <IonRouterOutlet> to <Switch> in <App>, it display success

**Comment by liamdebeasi** [comment] 2023-06-27 13:56
Thanks for the report. What version of the Chromium webview is running on the device that shows the white screen? You can find by this logging `window.navigator.userAgent` when inspecting the app with Chrome Dev Tools.

**Comment by TheSoils** [comment] 2023-06-28 00:41
> Thanks for the report. What version of the Chromium webview is running on the device that shows the white screen? You can find by this logging `window.navigator.userAgent` when inspecting the app with Chrome Dev Tools.

the user agent is 'Mozilla/5.0 (Linux; Android 13; sdk_gphone64_arm64 Build/TE1A.220922.028; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/103.0.5060.71 Mobile Safari/537.36'

**Comment by TheSoils** [comment] 2023-06-28 00:43
it is also white in ios
![image](https://github.com/ionic-team/ionic-framework/assets/29093597/cb4e764e-2ff5-476b-93b9-2c3b1e93749a)

**Comment by TheSoils** [comment] 2023-06-28 00:47
> Thanks for the report. What version of the Chromium webview is running on the device that shows the white screen? You can find by this logging `window.navigator.userAgent` when inspecting the app with Chrome Dev Tools.

Change IonRouterOutlet to Switch In App component, it display success。 so can not use IonRouterOutlet in root Component or it is a bug? It seems that this point was not mentioned in guid docs..

**Comment by TheSoils** [comment] 2023-06-28 16:21
> It's hard to say what the issue is without being able to reproduce the issue on my end. Can you provide a GitHub repo with the code required to reproduce the white screen?

https://github.com/TheSoils/ion-tab-test

**Comment by liamdebeasi** [comment] 2023-06-28 20:12
Thanks for the reproduction. In `Tabs.tsx` there is an additional `IonPage` component. `IonTabs` adds its own `IonPage` component, so you do not need to add another one. Removing the `IonPage` in that file should fix the white screen issue.

**Comment by TheSoils** [comment] 2023-06-29 00:17
> Thanks for the reproduction. In `Tabs.tsx` there is an additional `IonPage` component. `IonTabs` adds its own `IonPage` component, so you do not need to add another one. Removing the `IonPage` in that file should fix the white screen issue.

yes，remove the IonPage in Tabs, it display success, thx!
so it is wrong in the guide doc？
Maybe it is necessary to modify the doc
![image](https://github.com/ionic-team/ionic-framework/assets/29093597/e1ccf58a-49ef-4f93-a0ec-21ebebbe1129)

**Comment by liamdebeasi** [comment] 2023-06-29 13:51
Yes, good catch! I opened a PR to fix this on the docs: https://github.com/ionic-team/ionic-docs/pull/3012. I am going to close this since the issue is resolved, but let me know if you have questions.

-----

More detail on why this happens for those interested: `IonTabs` renders a `PageManager` component: https://github.com/ionic-team/ionic-framework/blob/1f06be4a31965f2a949b4866a585aee6af0af29d/packages/react/src/components/navigation/IonTabs.tsx#L157C14-L157C25

This component renders a `div` with the `ion-page` class applied. The IonPage component also renders a PageManager.

IonPage: https://github.com/ionic-team/ionic-framework/blob/1f06be4a31965f2a949b4866a585aee6af0af29d/packages/react/src/components/IonPage.tsx#L27C12-L27C12

PageMananger: https://github.com/ionic-team/ionic-framework/blob/1f06be4a31965f2a949b4866a585aee6af0af29d/packages/react/src/routing/PageManager.tsx#L75

**Closed** 2023-06-29 13:51 UTC
Labels: triage
