### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by M-a-c** [ionic-team/ionic-framework#23523] opened 2021-06-28 06:53 UTC
# Bug Report

**Ionic version:**
[x] **6.x**

**Current behavior:**
provide `undefined` for https://ionicframework.com/docs/utilities/gestures#gestureconfig *direction*.

**Expected behavior:**
undefined should give you `X AND Y` behavior, it explicitly gives you `Y` behavior. (which undefined is not `Y` explicitly)
`X` gives you `X`
not putting anything gives `X` (the default)
putting `Y` gives you `Y`

**Steps to reproduce:**
add
```direction: undefined,```

in this code pen 
https://codepen.io/ionic/pen/xxKBYdL
inside the `createGesture` object

*possible solutions*
1.  make undefined X AND Y behavior
2. remove undefined as an accepted `type`
3. default to `X` on undefined ?

This is the offending area.
> https://github.com/ionic-team/ionic-framework/blame/master/core/src/utils/gesture/recognizers.ts#L11 

Related to #21704.

**Comment by liamdebeasi** [comment] 2021-06-28 12:51
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/21704.

**Closed by liamdebeasi** 2021-06-28 12:51 UTC
Labels: triage
