### ISSUE TITLE
bug: ion-input ionChange fires also when value is changed externally

### ISSUE THREAD

**Issue by Suxsem** [ionic-team/ionic-framework#22732] opened 2021-01-03 16:12 UTC
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**
I'm using Ionic-VUE

```
                  <ion-input
                    :value="locationText"
                    @ionChange="getPlacePredictions($event.target.value)"
                    ></ion-input>
```
The getPlacePredictions functions shows a list of search results. When a user click on one of them I update locationText to reflect the user choice.
But then ionChange fires again, showing again the list of search results.

**Expected behavior:**
The ionChange event should only fire when the value is changed from the input component, NOT when it's changed externally.

Thank you

**Comment by liamdebeasi** [comment] 2021-01-04 14:30
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/20106 (same underlying behavior).

**Closed by liamdebeasi** 2021-01-04 14:30 UTC
Labels: holiday triage
