### ISSUE TITLE
bug: a11y - Focus Not Limited Within Modal

### ISSUE THREAD

**Issue by gurpreetonebcg** [ionic-team/ionic-framework#23603] opened 2021-07-12 05:57 UTC
# Bug Report

**Ionic version:**

```
@ionic/angular 5.6.0
```

**Current behavior:**

When the modal is open, focus is not limited within modal.  Moving focus past the OK button moves focus to back to the top of the page forcing user to navigate through all of the page content again in order to return focus to the modal.

**Expected behavior:**

Focus remains within modal until modal is closed.

**Steps to reproduce:**

Take the code from attached link or install .apk provide in attached link, start talk back screen reader open any overlay component from provided .apk, keep navigating with screen reader you will see focus moves on extra 2 div's only in android devices. This issue occurs because this type of 2 <div> tag are present there in overlay component. & some times the focus moves behind the overlay component.  
```
<div tabindex="0" class="sc-ion-alert-md"></div>
```
[Download .apk here](https://drive.google.com/file/d/1IOanXH8NcaVeYhiTrfjEveQBrpMH8IhI/view?usp=sharing)

**Related code:**

[Downlead code here](https://drive.google.com/file/d/1TfR-9kxiYYeVQkr6WOEjHaSuN_ZIq9my/view?usp=sharing) 

**Other information:**

[Screen shorts of issues](https://drive.google.com/file/d/1R_nbGhsy2owYC1FEYgRVbqrnNXvsOrNz/view?usp=sharing)

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.11.8
   Ionic Framework               : @ionic/angular 5.6.0
   @angular-devkit/build-angular : 0.1101.4
   @angular-devkit/schematics    : 11.1.4
   @angular/cli                  : 11.1.4
   @ionic/angular-toolkit        : 3.1.0

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : android 9.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 4 other plugins)

Utility:

   cordova-res : 0.11.0
   native-run  : 1.0.0
```

**Comment by liamdebeasi** [comment] 2021-07-12 13:06
Thanks for the issue. Can you please provide some steps to reproduce the issue? I am testing your application on a device running Android 11 with TalkBack enabled and the focus is staying within the overlays.

**Comment by gurpreetonebcg** [comment] 2021-07-21 10:07
Thanks for reply,

I have tested this on Samsung Galaxy J8 with android 10 OS.

[Screen Short](https://drive.google.com/file/d/13tfPCaKQYrDd-ZP-YaNG8cTQfVZvfsJ1/view?usp=sharing)

I have tried to debug and found that this is due to tabindex="0" added on <div>

[Code Screen Short](https://drive.google.com/file/d/1R_nbGhsy2owYC1FEYgRVbqrnNXvsOrNz/view?usp=sharing)

**Comment by liamdebeasi** [comment] 2021-07-22 13:22
The elements with `tabindex="0"` are there to prevent focus from leaving the overlay. Are you able to clarify the steps to reproduce? I cannot reproduce this behavior on my end.

**Comment by gurpreetonebcg** [comment] 2021-08-02 06:48
This issue is only occurring in android devices. when you open any alert or popup box then right swipe you will see focus moves to a rectangular element before reaching to the first element of the popup & when you read whole content of popup then right swipe from the last item of popup, the focus will move again to a rectangular element. Please refer to the attach video. https://drive.google.com/file/d/1WED4jlVcs86bo2yAB5eKZoEqN9RLIdLp/view?usp=sharing

In attached video you will see when popup opens then on right swipe focus moves to right bottom corner in a rectangular box & when you reach to OK button then right swipe focus again move to a rectangular box at the right bottom corner. Please refer to the highlighted areas of attached screen shorts.
![image](https://user-images.githubusercontent.com/77607352/127816135-9fe8d6ce-d29c-47f0-a9b2-cec653cf9a23.png)
![image](https://user-images.githubusercontent.com/77607352/127816195-b4003508-2681-479a-bdf2-0062f9383a50.png)

**Comment by vitor-antonio** [comment] 2021-11-04 15:17
Had the same issue within our app. Only appears on Android devices. First element that got focus has the modal itself and then later was the weird div containing `tabindex="0" `. When using TalkBack and linear navigation, this was reading some of the elements of the modal in a wrong way, confusing the users.

Also, it was possible to navigate back to the elements of the component that raised/called the modal, meaning that the focus was not being correctly trapped.

![image](https://user-images.githubusercontent.com/13060810/140339349-2ac724e6-e09e-4ca2-8082-662afb8154af.png)

I've used some **work around** for this.
```
let elements = document.getElementsByClassName('sc-ion-modal-md');

for (let index = 0; index < elements.length; index++) {
  const element = elements.item(index);
  if(!element.hasAttribute("role")){
    element.setAttribute('aria-hidden', 'true')
    element.setAttribute('tabindex', '-1');
  }
}
```

![image](https://user-images.githubusercontent.com/13060810/140344378-2572659d-985c-43da-95e3-1a5aae9dd72b.png)


Like this, we basically telling Talkback to ignore those elements and this works well with keyboard/linear navigation.
Also, to help with trap focus issue, I've added `[attr.aria-hidden]="isShowingFiltersPopup"` to the component that calls the modal.

And like that, everything works as expected for unsighted users, and keeps the focus limited to the open modal.

**Comment by amandaesmith3** [comment] 2021-11-16 15:33
Thanks for the report. The `tabindex="0"` elements are there to enable focus trapping. Setting their `tabindex` to `-1` breaks focus trapping on desktop in particular and may cause other issues.

There are two separate problems being reported here:
1. Focus can be moved to elements behind the modal, such as the button that opened it.
2. Focus can be moved to hidden elements in the bottom right corner (as shown in your screenshots).

I can replicate issue 1 using TalkBack on Ionic 5.6.0. However, focus trapping is working correctly on my end with the latest version of Ionic Angular (5.8.5). Could you try updating and let me know how that goes?

That said, I can also replicate issue 2, even on the latest Ionic version. Setting `aria-hidden="true"` on the `tabindex="0"` elements may do the trick, but it will need more testing on all devices. I'll update this ticket to cover issue 2 once we've confirmed that issue 1 is resolved by updating Ionic.

**Closed** 2021-11-30 16:25 UTC
Labels: needs: reply
