### ISSUE TITLE
bug: Modal not showing prop content in ionic vue

### ISSUE THREAD

**Issue by dlodeprojuicer** [ionic-team/ionic-framework#22239] opened 2020-10-02 14:24 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Ionic/Vue version:**

[x] **0.5.2**

**Current behavior:**
Prop variables are `undefined` when passing prop data from parent to modal.

**Expected behavior:**
Modal should be able to use dynamic prop data

**Steps to reproduce:**
Code snippet from [docs](https://ionicframework.com/docs/api/modal)

**Related code:**

**Modal.vue**
```
<template>
  <div>
    <ion-header>
      <ion-toolbar>
        <ion-title>{{ title }}</ion-title>
      </ion-toolbar>
    </ion-header>
    <ion-content class="ion-padding">
      {{ content }}
    </ion-content>
  </div>
</template>

<script>
import { IonContent, IonHeader, IonTitle, IonToolbar } from '@ionic/vue';
import { defineComponent } from 'vue';

export default defineComponent({
  name: 'Modal',
  props: {
    title: { type: String },
    content: { type: String },
  },
  data() {
    return {
    }
  },
  components: { IonContent, IonHeader, IonTitle, IonToolbar },
  beforeMount() {
    console.log("Title 2", this.title) // undefined 
  },
  mounted() {
    console.log("Title", this.title) // undefined
  }
});
</script>
```

**Page.vue**
```
<template>
  <ion-page>
    <ion-content class="ion-padding">
      <ion-button @click="openModal">Open Modal</ion-button>
    </ion-content>
  </ion-page>
</template>

<script>
import { IonButton, IonContent, IonPage, modalController } from '@ionic/vue';
import Modal from './Modal.vue'

export default {
  components: { IonButton, IonContent, IonPage },
  methods: {
    async openModal() {
      const modal = await modalController
        .create({
          component: Modal,
          cssClass: 'my-custom-class',
          componentProps: {
            data: {
              content: 'Content from parent',
            },
            propsData: {
              title: 'New from parent',
            },
          },
        })
      return modal.present();
    },
  },
}
</script>
```

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.11.8-testing.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 0.5.2

Capacitor:

   Capacitor CLI   : 2.4.1
   @capacitor/core : 2.4.1

Utility:

   cordova-res : 0.15.1
   native-run  : not installed

System:

   NodeJS : v12.18.0 (/usr/local/bin/node)
   npm    : 6.14.4
   OS     : macOS Catalina
```

**Comment by KEVDEVR** [comment] 2020-10-03 14:14
I noticed the same issue in my project.

**Comment by liamdebeasi** [comment] 2020-10-05 13:16
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The documentation for that usage is incorrect. In your use case, you would do:


```typescript
const modal = await modalController
  .create({
    component: Modal,
    cssClass: 'my-custom-class',
    componentProps: {
      content: 'Content from parent',
      title: 'New from parent',
    }
  });
return modal.present();
```

I have updated the docs here: https://github.com/ionic-team/ionic-framework/pull/22201

**Closed by liamdebeasi** 2020-10-05 13:16 UTC
Labels: triage
