### ISSUE TITLE
bug: can't dismiss controller modal that has nested inline modal

### ISSUE THREAD

**Issue by jsoand** [ionic-team/ionic-framework#24431] opened 2021-12-16 21:44 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

ModalController dismiss does not close current modal if the modal uses ion-datetime as inline modal in it's HTML template.

### Expected Behavior

ModalController dismiss should close the currently opened modal even if it has inline modal in it's template

### Steps to Reproduce

1. Click "open modal" button to open modal
2. Click "close" button to dismiss modal => error modal not closed

### Code Reproduction URL

https://stackblitz.com/edit/angular-ivy-wbuz7j?file=src/app/app.component.ts

### Ionic Info

latest ionic/angular

**Comment by yasiel06** [comment] 2021-12-27 16:30
Hi @jsoand.

The same thing happened to me and I have solved it by assigning an id to the modal, then in the dismiss method you pass the id.

// Open modal
const modal = await this.modalController.create({
    component: FiltersComponent,
    id: "modal-filters", // id for ur modal
    initialBreakpoint: 0.5,
    breakpoints: [0.2, 0.5, 1]
  });

// Dismiss modal
this.modalController.dismiss({}, "", "modal-filters"); // Pass the modal id in the third parameter

Greetings and hope this solves your problem.

**Comment by amandaesmith3** [comment] 2022-01-05 15:20
Thanks for the issue, I'm able to reproduce. I saw this bug on both Angular and Vue using `modalController`. The inline nested modal doesn't even need anything in it; just `<ion-modal></ion-modal>` will trigger the behavior.

**Comment by amandaesmith3** [comment] 2022-01-25 16:16
As it turns out, the root cause here was the same as the issue addressed in https://github.com/ionic-team/ionic-framework/pull/24547. The fix has been released in Ionic 6.0.3, so I'm closing this issue out. Thanks for using Ionic!

**Closed by amandaesmith3** 2022-01-25 16:16 UTC
Labels: package: angular, package: vue, type: bug
