### ISSUE TITLE
bug: onClick items do not fire in modals when modal's parent is wrapped in ion-nav

### ISSUE THREAD

**Issue by vu0tran** [ionic-team/ionic-framework#28596] opened 2023-11-29 00:18 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When you have items in a modal with onClick and you click it, the onClick fires. However, if the modal's parent is wrapped in IonNav, the onClicks no longer work.

### Expected Behavior

Even when items are wrapped in IonNav, the onClick should fire appropriately

### Steps to Reproduce

https://stackblitz.com/edit/gmg8ka-zmyzmx?file=src%2Fmain.tsx

1. Click the "click me" div. See that it does not work
2. Comment out // return <ExampleScreen />; 
3. Click the "click me" div, see that it does fire the alert as long as the parent is not wrapped in IonNav

### Code Reproduction URL

https://stackblitz.com/edit/gmg8ka-zmyzmx?file=src%2Fmain.tsx

### Ionic Info

7.5.6

**Comment by vu0tran** [comment] 2023-11-29 00:19
Might be a dupe:

https://github.com/ionic-team/ionic-framework/issues/27843

**Comment by vu0tran** [comment] 2023-11-29 00:20
Note, this happens for popovers too

**Comment by amandaejohnston** [comment] 2023-11-29 14:22
Thank you for the issue, I'm going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/27843. I'll raise the issue with the team internally 👍

**Closed by amandaejohnston** 2023-11-29 14:22 UTC
Labels: triage
