### ISSUE TITLE
bug: Modal does not load inner custom Components when created via ModalController

### ISSUE THREAD

**Issue by RingoRohe** [ionic-team/ionic-framework#26053] opened 2022-09-30 15:10 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

Custom Components inside Modals are not loaded/rendered correctly when using ModalController. Only the empty Tag is inserted to the Markup. Everything works fine when using the inline Modal Method instead ModalController.

### Expected Behavior

Custom Components should render in Modals.

### Steps to Reproduce

Create a Modal with the ModalController and a custom Modal Component:
```
  async openModal() {
    const m = await this.modalController.create({
      component: ModalComponent
    });
    m.present();

    const { data, role } = await m.onDidDismiss();

    if (role === 'confirm') {
      alert(`Data: ${data}!`);
    }
  }
```

Inside the Template of the ModalComponent, insert another custom Component:

```
...
<ion-content class="ion-padding">
  <h1>here I am...</h1>
  <app-inner-component></app-inner-component> <!-- This one -->
</ion-content>
```

### Code Reproduction URL

https://github.com/RingoRohe/modal-test

### Ionic Info

```
Ionic:

   Ionic CLI                     : 5.4.16 (/home/ringo/.npm/_npx/864a9e3c2cd0cf50/node_modules/ionic)
   Ionic Framework               : @ionic/angular 6.2.9
   @angular-devkit/build-angular : 14.2.4
   @angular-devkit/schematics    : 14.2.4
   @angular/cli                  : 14.2.4
   @ionic/angular-toolkit        : 6.1.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v18.8.0 (/usr/bin/node)
   npm    : 8.19.1
   OS     : Linux 5.18
```

**Comment by liamdebeasi** [comment] 2022-09-30 16:04
Thanks for the report. This appears to be a problem with how your component modules are configured, not Ionic. There are a few problems:

1. `HomePageModule` needs to provide the `ModalComponentModule` to the `imports` array.
2. `ModalComponentModule` needs to provide the `InnerComponentModule` to the `imports` array instead of providing `InnerComponent`.
3. `InnerComponentModule` needs to provide `InnerComponent` in the `exports` array instead of the `imports` array.

Making the above changes resolves the issue. I am going to close this as this is not a bug in Ionic, but let me know if you have any additional questions.

**Closed by liamdebeasi** 2022-09-30 16:04 UTC
Labels: triage

**Comment by RingoRohe** [comment] 2022-09-30 16:26
Dammit... m(
Thank you.
