### ISSUE TITLE
bug: datetime - month navigation broken when min attribute is set

### ISSUE THREAD

**Issue by antoine92190** [ionic-team/ionic-framework#25870] opened 2022-09-01 10:03 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

 Issue when using the datetime picker with the below code:
```
<ion-modal [trigger]="elementId">
    <ng-template>
        <ion-datetime min="2022-09-01">
        </ion-datetime>
    </ng-template>
</ion-modal>
```
- Set a `min` attribute
- Navigate to the next year, for example January 2023
- Go back to the previous month => the displayed month is September 2023 instead of December 2022

https://user-images.githubusercontent.com/16256207/187888708-6f7ac3a6-c369-43ec-804e-d89a4384d8b1.mov

### Ionic Info

Ionic:

   Ionic CLI                     : 6.20.1 (/Users/antoinedupont/.npm-packages/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.2.5
   @angular-devkit/build-angular : 13.2.6 (/Users/antoinedupont/dev/agorapulse/platform/frontend/node_modules/@angular-devkit/build-angular)
   @angular-devkit/schematics    : 13.3.9
   @angular/cli                  : 13.2.4 (/Users/antoinedupont/dev/agorapulse/platform/frontend/node_modules/@angular/cli)
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.2.4
   @capacitor/android : 3.2.4
   @capacitor/core    : 3.2.4
   @capacitor/ios     : 3.2.4

Cordova:

   Cordova CLI       : 11.0.0
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed globally
   native-run  : 1.6.0

System:

   NodeJS : v14.17.0 (/usr/local/bin/node)
   npm    : 6.14.13
   OS     : macOS Monterey
   Xcode  : Xcode 13.4.1 Build version 13F100

**Comment by liamdebeasi** [comment] 2022-09-01 12:57
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/25870. (The issue mentions using `max`, but the underlying cause is the same)

**Closed by liamdebeasi** 2022-09-01 12:57 UTC
Labels: triage
