### ISSUE TITLE
bug:  ion-badge a11y(iOS) - Screen reader is not reading aria-label in iOS

### ISSUE THREAD

**Issue by RenAlbiorix** [ionic-team/ionic-framework#23361] opened 2021-05-25 11:59 UTC
# Bug Report

**Ionic version:**
[x] **4.x**
[x] **5.x**

**Current behavior:**

Screen reader is not reading `aria-label` on ion-bagde or `ion-label` inside `ion-badge`

**Expected behavior:**

Screen reader should read text from `aria-lable ` on ion-badge. It's reading text inside `ion-badge`.
It's specific to iOS only. In android it's reading `aria-label` on `ion-badge`.

**Steps to reproduce:**

Put `aria-label` on `ion-badge` or `ion-label` inside `ion-badge`

**Related code:**

```
<ion-badge aria-label="1 new notification">1</ion-badge>
<ion-badge ><ion-label aria-label="1 new notification">1 <ion-label></ion-badge>
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.16.1 (C:\Users\...\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.5.4
   @angular-devkit/build-angular : 0.901.14
   @angular-devkit/schematics    : 9.1.14
   @angular/cli                  : 9.1.14
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : not installed
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v14.16.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.12
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment] 2021-05-25 12:44
Thanks for the issue. Can you provide an example of the problem you are trying to solve in your app? If you are trying to have an icon with a badge icon, it is better to assign a label to that entire group rather than the badge icon by itself.

**Comment by RenAlbiorix** [comment] 2021-05-25 13:11
I am using ion-badge for new notifications. I'd like screen reader to read as "2 new notifications". 
With `<ion-badge aria-label="2 new notifications">2</ion-badge>` in android screen reader is reading "2 new notifications" whereas in iOS it reads as "2".

**Comment by liamdebeasi** [comment] 2021-05-25 13:14
Thanks! Any chance you could provide a more complete example of what you are trying to do? I am not sure how much control we have over this since the end result is essentially the same as doing the following:

```html
<div class="badge" aria-label="Hello World">99</div>
```

VoiceOver on iOS will read "99"
TalkBack on Android will read "Hello World"

I am interested in seeing if there is an alternative approach we can take that would give you the desired results.

**Comment by RenAlbiorix** [comment] 2021-05-25 13:20
I have tried this both 
```
<ion-badge aria-label="2 new notifications">2</ion-badge>
<ion-badge ><ion-label aria-label="2 new notifications">2 <ion-label></ion-badge>
```

VoiceOver on iOS is reading "2"
TalkBack on Android is reading "2 new notifications"

So my question is there any way we can get the same result as android in ios(aria-label reading)?

**Comment by liamdebeasi** [comment] 2021-05-25 13:23
I understand that those two examples do not work. What I am trying to understand is the broader scope of what you are trying to create. Are you trying to create tab buttons with a badge icon, items in a list with a badge, or something different? Based upon what you are trying to do, I can recommend an approach that should give you the results you want.

**Comment by RenAlbiorix** [comment] 2021-05-25 13:26
I have ion item with avatar & on that avatar i have badge for new messages. I have below scenarios.
![image](https://user-images.githubusercontent.com/70148715/119505674-d022a500-bd8a-11eb-9cdc-aae34bf518f9.png)
![image](https://user-images.githubusercontent.com/70148715/119505742-e466a200-bd8a-11eb-948b-66bf25f93919.png)

**Comment by liamdebeasi** [comment] 2021-05-25 13:35
Thanks! For both examples, I would put the `aria-label` on the `ion-label` inside of the `ion-item` and set `aria-hidden="true"` on the `ion-badge`. Here is an example:

```html
<ion-item button="true">
  <ion-label aria-label="Messages (6 new messages)">Messages</ion-label>
  <ion-badge aria-hidden="true">6</ion-badge>
</ion-item>
```

The discrepancy between screen readers with `ion-badge` does not appear to be a bug in Ionic Framework as I am able to reproduce this behavior with a regular `div` element. I am going to close this issue for now, but for additional assistance implementing these behaviors in your app feel free to open a thread on the forums: https://forum.ionicframework.com/.

**Closed by liamdebeasi** 2021-05-25 13:35 UTC
Labels: triage
