### ISSUE TITLE
bug: ion-popover steals focus after dismissal

### ISSUE THREAD

**Issue by Staon** [ionic-team/ionic-framework#23137] opened 2021-04-03 09:08 UTC
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
If the `ion-popover` is opened with `keyboardClose=false` and it is dismissed, it forcefully sets focus on the component which had focus at the time of opening (#21768) even though the focus has been changed meanwhile by the _Tab_ or _Shift+Tab_ keys.

**Expected behavior:**
Focus stays at the component where it is at the time of the dismissal.

**Steps to reproduce:**

- Prepare two ion-inputs, first of them opening the ion-popover with `keyboardClose=false` on getting focus and closing the popover on losing focus.
- Enter the first input. The popover shows. Then pres _Tab_ to change focus to the second input. The popover dismisses but after a while the focus is set back to the first input and the popover appears again.

**Related code:**
Simple example application is here: https://github.com/Staon/ionic-bug

**Other information:**
I'm trying to make an autosuggest component by combining the IonInput and IonPopover. This issue is a real blocker.

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.13.1 (/home/staon/.nvm/versions/node/v15.10.0/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.6.3

Capacitor:

   Capacitor CLI   : 2.4.7
   @capacitor/core : 2.4.7

Utility:

   cordova-res : 0.15.3
   native-run  : 1.3.0

System:

   NodeJS : v15.10.0 (/home/staon/.nvm/versions/node/v15.10.0/bin/node)
   npm    : 7.5.3
   OS     : Linux 5.8
```

**Comment by liamdebeasi** [comment] 2021-04-05 13:28
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/22795.

**Closed by liamdebeasi** 2021-04-05 13:28 UTC
Labels: triage
