### ISSUE TITLE
bug: ion-label with class="ion-text-nowrap" forces any content at the end of an ion-item to wrap

### ISSUE THREAD

**Issue by harry-molyneux** [ionic-team/ionic-framework#28800] opened 2024-01-09 14:11 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

The bug is apparent when an `<ion-item>` has an `<ion-label>` with `class="ion-text-nowrap"` and there is also some other element slotted at the end of the `<ion-item>` (eg. an `<ion-badge>`). The bug also appears when there is no element at the end of the `<ion-item>` but the `<ion-item>` has attributes `button="true"` and `detail="true"` (so it has a detail arrow at the end instead).

The issue is that the contents at the end of the `<ion-item>` is wrapped below the `<ion-label>` when the contents of the `<ion-label>` is too long.

Below are three examples of this issue:
1. `<ion-item>` with attributes `button="true"` and `detail="true"` and a simple `<ion-label>` with just text inside.
2. `<ion-item>` with attributes `button="true"` and `detail="true"` and an `<ion-label>` with a `<h2>` heading and `<p>` inside.
3. `<ion-item>` with an `<ion-badge>` with `slot="end"` and an `<ion-label>` with a `<h2>` heading and `<p>` inside.

![image](https://github.com/ionic-team/ionic-framework/assets/68756225/d790ba5a-fd20-4746-bb25-0137c9aeefbc)

### Expected Behavior

The contents of the `<ion-label>` should be cut before it forces the contents at the end of the `<ion-item>` to wrap. See image below: 

![image](https://github.com/ionic-team/ionic-framework/assets/68756225/8d4fa9b7-c270-4b68-b919-92e4ebac0547)

This appears to be an issue with the `flex` property of the `<div class="input-wrapper">` element.

In previous versions of Ionic, we observe that this element had `flex: 1 1 0%;`. If this is applied, the issue appears to be resolved.

![image](https://github.com/ionic-team/ionic-framework/assets/68756225/52f5b231-4b34-4d05-8086-7119cb030c4b)

Therefore, the proposed expected behaviour is that the `<div class="input-wrapper">` element within the `shadow-root` of an `<ion-item>` should have `flex: 1 1 0%;` if it contains an `<ion-label>` with `class="ion-text-nowrap"`.

### Steps to Reproduce

1. Set up an `<ion-item>` element with attributes `button="true"` and `detail="true"`.
2. Add an `<ion-label>` with `class="ion-text-nowrap"` into the `<ion-item>` and add some long text into it eg "Multi-line text that should wrap when it is too long to fit on one line. Lorem ipsum dolor sit amet, consectetur adipiscing elit.".
3. Observe that the detail arrow is wrapped beneath the label.

### Code Reproduction URL

https://github.com/harry-molyneux/ionic-item-label-wrapping-bug

### Ionic Info

Ionic:

   Ionic CLI                     : 7.1.6 (/Users/harry/.nvm/versions/node/v18.18.2/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.6.2
   @angular-devkit/build-angular : 17.0.7
   @angular-devkit/schematics    : 17.0.7
   @angular/cli                  : 17.0.7
   @ionic/angular-toolkit        : 10.0.0

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v18.18.2 (/Users/harry/.nvm/versions/node/v18.18.2/bin/node)
   npm    : 9.8.1
   OS     : macOS Unknown

**Comment by liamdebeasi** [comment] 2024-01-09 15:28
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/28769.

**Closed by liamdebeasi** 2024-01-09 15:28 UTC
Labels: triage
