### ISSUE TITLE
bug: wrong routing on ion-tabs with nested pages

### ISSUE THREAD

**Issue by baycik** [ionic-team/ionic-framework#27131] opened 2023-04-06 06:59 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

I have build application using ionic/vue. I have used ion-tabs with nested pages. From time to time it freezed on wrong page while wrong tab was selected on tabbar. So I decided to figure out what the problem is.

In sample application 
1) go to Tab 1 > Sub page 1
2) go to Tab 2 > Sub page 2
3) go to Tab 1 again and press back button
4) route became tab2/tab2sub while app still at tab1

Tab1 and Tab2 buttons has no effect when pressed
To unfreeze Tab buttons we need to press to Tab3 button

Related issue is when we are at tab2/tab2sub route and user presses reload button, Tab2 sticks to this sub route and pressing tabbutton only refreshes page an not taking to tab2 route 

### Expected Behavior

1) go to Tab 1 > Sub page 1
2) go to Tab 2 > Sub page 2
3) go to Tab 1 again and press back button
4) route became tab2/tab2sub and tab2 is active
5) when reloaded eather tab2 parent page must be shown or nested tab2/tab2sub but pressing to tabbutton should take to root tab2/route

### Steps to Reproduce

1) go to Tab 1 > Sub page 1
2) go to Tab 2 > Sub page 2
3) go to Tab 1 again and press back button

### Code Reproduction URL

https://github.com/ket47/tabs.git

### Ionic Info

Ionic:

   Ionic CLI       : 6.18.1 (C:\Users\bayci\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/vue 7.0.1

Capacitor:

   Capacitor CLI      : 4.7.3
   @capacitor/android : not installed
   @capacitor/core    : 4.7.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.2

System:

   NodeJS : v18.4.0 (C:\Program Files\nodejs\node.exe)
   npm    : 7.23.0
   OS     : Windows 10

### Additional Information

The problem is that I have deployed my application and user experience is terrible. I saw related to tabs not addressed for very long time. I think this bug is high priority because routing and tabs are backbone of application. I like ionic but if I knew fundamental component as tabs is not working properly I would prefered different framework.

While this bug is being fixed what would you recomend to use instead of tabs

**Comment by liamdebeasi** [comment] 2023-04-06 13:17
Thanks for the report. I can reproduce the reported behavior, but Ionic is working as intended. Tabs in mobile applications are stack-based. If you were on Tab 1/Sub Page and you pressed the `ion-back-button`, you would be brought back to Tab 1. However, the browser does not know how stack-based navigation works. This means that when you press the _browser_ back button you are going to be taken to the previous route you were on (regardless of the current stack). In your steps to reproduce, this means that you are going to come back to Tab 2/Sub Page since that is the last route the browser was on.

For this reason, I don't recommend deploying Tabs-based applications in a browser environment because you have less control over how users navigate your application. If you are using Tabs I recommend only deploying to a standalone environment such as Capacitor.

**Comment by liamdebeasi** [comment] 2023-04-06 13:18
https://ionicframework.com/docs/vue/navigation#non-linear-routing has more information on how non-linear/stack base routing works. It also discusses some of the problems with doing `router.go(-1)` or going back 1 view regardless of the current stack.

**Comment by liamdebeasi** [comment] 2023-04-06 13:53
> But how I supposed to prevent user from hidding hardware back button?

When running an app in Capacitor we customize the hardware back button behavior to work correctly with tabs.

> I think that it would be great to add linear routing option to ionic tabs, because power and philosophy of Ionic is that i can create app that works on web and as native app!

We don't have plans to add a linear option to tabs at the moment since Ionic is designed to match the behavior of native mobile apps, not web apps.

**Comment by baycik** [comment] 2023-04-06 14:17
I think that ionic-team should consider adding browser compatible tab solution. Routing behavior varies from app to app as you mentioned at one post here on this repo. Some apps uses linear some nonlinear some mixed. I think desion must make app developer to best suit it needs.

Anyway Liam, tabs have issue even with back button. I have updated repo and added back button so

1) tab1->sub page
2) tab2->sub page
3)tab1 press backButton
4)tab2 press backButton
backButton does not work.

**Comment by liamdebeasi** [comment] 2023-04-06 14:20
> I think that ionic-team should consider adding browser compatible tab solution. Routing behavior varies from app to app as you mentioned at one post here on this repo. Some apps uses linear some nonlinear some mixed. I think desion must make app developer to best suit it needs.

We plan to re-evaluate the non-linear tabs in the future, but we are focused on refining/fixing bugs in the non-linear approach at the moment since that is what many Ionic devs are using when they implement tabs.

> Anyway Liam, tabs have issue even with back button. I have updated repo and added back button so

I believe this is a separate bug: https://github.com/ionic-team/ionic-framework/issues/25213

------

I am going to close this since the original behavior is working as intended. I recommend following https://github.com/ionic-team/ionic-framework/issues/25213 for updates on the other tabs bug. Let me know if you have other questions.

**Closed by liamdebeasi** 2023-04-06 14:20 UTC
Labels: triage
