### ISSUE TITLE
feat: We need Data Table as component

### ISSUE THREAD

**Issue by ShubhamKhatri2** [ionic-team/ionic-framework#25679] opened 2022-07-27 05:15 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

We are using 3rd party data tables which are not supporting certain things like direct CSV to data table, JSON or Array to data table like all, and it's good looking whit ionic based application. So  we request to give new feature for Data table as component.

### Describe the Use Case

Data tables are widely use in the market and its a basic functionality for any front end framework. sortable, searchable, pagination and with scrollbar and custom CSS data tables look very good and represent it very much better then simple tbale.

### Describe Preferred Solution

DATA table as component is very good solution.

### Describe Alternatives

material data table, NGX data table, Data Tables, but they are 3rd party and not easy as well.

**Comment by liamdebeasi** [comment] 2022-07-27 15:47
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/17629.

**Closed by liamdebeasi** 2022-07-27 15:47 UTC
Labels: triage
