### ISSUE TITLE
bug: inconsistency in the style of highlighted dates

### ISSUE THREAD

**Issue by GerardoPrototype** [ionic-team/ionic-framework#29428] opened 2024-05-01 00:18 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When you add marked dates to the calendar it displays the style correctly. but when you select that date it loses the style
<img width="1524" alt="Captura de pantalla 2024-04-30 a la(s) 5 13 17 p m" src="https://github.com/ionic-team/ionic-framework/assets/133162777/ea4bd64a-4b19-463f-ba27-0ca8b71a4af2">

### Expected Behavior

the desired behavior would be. When selecting a marked date, it does not delete its style.
<img width="1524" alt="Captura de pantalla 2024-04-30 a la(s) 5 04 02 p m" src="https://github.com/ionic-team/ionic-framework/assets/133162777/405afe94-6351-4474-b8f5-adab17354f18">
This design where I can see a highlighted date and with the active style is currently impossible

### Steps to Reproduce

create an ion-date component with highlighted dates. Select a date and see how your style is eliminated

### Code Reproduction URL

https://ionicframework.com/docs/api/datetime#using-array

### Ionic Info

Ionic:

   Ionic CLI                     : 7.2.0 (/Users/gerardo/.nvm/versions/node/v18.18.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.8.4
   @angular-devkit/build-angular : 17.1.3
   @angular-devkit/schematics    : 17.1.3
   @angular/cli                  : 17.1.3
   @ionic/angular-toolkit        : 10.1.1

Capacitor:

   Capacitor CLI      : 5.7.4
   @capacitor/android : 5.7.4
   @capacitor/core    : 5.7.4
   @capacitor/ios     : 5.7.4

Utility:

   cordova-res : not installed globally
   native-run  : 2.0.1

System:

   NodeJS : v18.18.0 (/Users/gerardo/.nvm/versions/node/v18.18.0/bin/node)
   npm    : 10.1.0
   OS     : macOS Unknown

**Comment by liamdebeasi** [comment] 2024-05-01 13:31
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. As explained on the [Datetime documentation](https://ionicframework.com/docs/api/datetime#highlighting-specific-dates), the style of the selected date(s) will always override custom highlights. This was done to ensure that users always know which dates are selected.

**Closed by liamdebeasi** 2024-05-01 13:31 UTC
Labels: triage
