### ISSUE TITLE
bug: ion-range not rendering with initial values

### ISSUE THREAD

**Issue by playaz87** [ionic-team/ionic-framework#28187] opened 2023-09-16 09:19 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

The `value` property of `ion-range` is ignored on first render. This can be overcome by using `setTimeout` to set state to correctly render the knobs of the `ion-range`

However, this workaround does not work if the `IonRange` has `dualKnobs` set to `true` and is inside an `IonModal`

### Expected Behavior

`IonRange` knobs to render at initial values.

### Steps to Reproduce

1. Create `IonRange` component
2. Set its value
3. Render...

### Code Reproduction URL

https://github.com/playaz87/ionic-7-range-bug

### Ionic Info

Ionic:

   Ionic CLI       : 7.1.1 (/home/alex/.nvm/versions/node/v18.17.1/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 7.4.0

Capacitor:

   Capacitor CLI      : 5.3.0
   @capacitor/android : 5.3.0
   @capacitor/core    : 5.3.0
   @capacitor/ios     : 5.3.0

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v18.17.1 (/home/alex/.nvm/versions/node/v18.17.1/bin/node)
   npm    : 9.6.7
   OS     : Linux 5.15

**Comment by liamdebeasi** [comment] 2023-09-18 13:03
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/25444.

**Closed by liamdebeasi** 2023-09-18 13:03 UTC
Labels: triage
