### ISSUE TITLE
bug: Pages not being removed from DOM

### ISSUE THREAD

**Issue by yetkinaykan** [ionic-team/ionic-framework#23408] opened 2021-06-03 07:29 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

When the tab is changed, the old tab is not deleted from the DOM.

**Expected behavior:**

Deleting the old tab from the dom when the tab changes

**Steps to reproduce:**

**Related code:**

```
<IonApp>
    <IonReactRouter>
      <IonTabs>
        <IonRouterOutlet>
          <Route exact path="/tab1">
            <Tab1 />
          </Route>
          <Route exact path="/tab2">
            <Tab2 />
          </Route>
          <Route path="/tab3">
            <Tab3 />
          </Route>
          <Route exact path="/">
            <Redirect to="/tab1" />
          </Route>
        </IonRouterOutlet>
        <IonTabBar slot="bottom">
          <IonTabButton tab="tab1" href="/tab1">
            <IonIcon icon={triangle} />
            <IonLabel>Tab 1</IonLabel>
          </IonTabButton>
          <IonTabButton tab="tab2" href="/tab2">
            <IonIcon icon={ellipse} />
            <IonLabel>Tab 2</IonLabel>
          </IonTabButton>
          <IonTabButton tab="tab3" href="/tab3">
            <IonIcon icon={square} />
            <IonLabel>Tab 3</IonLabel>
          </IonTabButton>
        </IonTabBar>
      </IonTabs>
    </IonReactRouter>
  </IonApp>
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.15.0 
   Ionic Framework : @ionic/react 5.6.8

Utility:

   cordova-res : not installed
   native-run  : 1.3.0

System:

   NodeJS : v14.15.2
   npm    : 6.14.9
   OS     : Windows 10
```

**Comment by yetkinaykan** [comment] 2021-06-03 11:40
I guess it is required for Hardware Back Button. Is there a way to re-render a page? Without using lifecycles.

**Comment by liamdebeasi** [comment] 2021-06-03 12:38
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. This is an intentional behavior for performance and routing (such as hardware back button support as you mentioned). Not sure that there is a way to force a component to re-render without using lifecycles. That being said, if you need to force a page to re-render I would suggest revisiting your component's code to see if you can make any data on that page reactive so that React knows to update it automatically.

**Closed by liamdebeasi** 2021-06-03 12:38 UTC
Labels: triage

**Comment by yetkinaykan** [comment] 2021-06-04 21:46
@liamdebeasi Could you please review this? It can introduce incredible performance issues with dynamic routes.

![Speakers](https://user-images.githubusercontent.com/56234617/120865680-2cf63a80-c597-11eb-8b9e-1ee1922abdb5.png)
