### ISSUE TITLE
bug: TabBar can show the wrong content when navigating from non-page

### ISSUE THREAD

**Issue by biesbjerg** [ionic-team/ionic-framework#28389] opened 2023-10-20 11:37 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When navigating from a tab page to a root page, to another root page, then back to a tab page, the wrong content is shown.

Please see reproduction url and this video:

![RPReplay_Final1697801671](https://github.com/ionic-team/ionic-framework/assets/230182/83338a54-5f16-4036-a701-3880593ec3e0)

### Expected Behavior

The correct content for the selected tab should be shown

### Steps to Reproduce

1. Click on “Tab 2” on TabBar
2. Click button “Go to DetailPage” 
3. Click button “Go to LoginPage”
4. Click button “Go to Tab3Page”

As expected, you end up at `/tabs/tab3` with “Tab 3” highlighted in the TabBar — but unexpectedly the contents is “Tab 2”

See reproduction URL or https://codesandbox.io/p/sandbox/github/biesbjerg/TabsNavBug/tree/main

### Code Reproduction URL

https://github.com/biesbjerg/TabsNavBug

### Ionic Info

```
Ionic:

   Ionic CLI       : 7.1.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 7.5.1

Capacitor:

   Capacitor CLI      : 5.5.0
   @capacitor/android : not installed
   @capacitor/core    : 5.5.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.3

System:

   NodeJS : v18.15.0 (/usr/local/bin/node)
   npm    : 9.5.0
   OS     : macOS Unknown
```

**Comment by liamdebeasi** [comment] 2023-10-20 13:55
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. As per the [Switching Between Tabs documentation](https://ionicframework.com/docs/vue/navigation#switching-between-tabs) your application should never link across tabs. In other words, tabs should only be changed by the user tapping a tab button in the tab bar.

The reason for this is in mobile apps each tab is its own navigation stack, and items across stacks do not interact. This is different from how tabs work in a traditional web application.

This reproduction is slightly different since you go to Tab 2, then leave tabs altogether, than come back to Tab 3 but the same rules apply. Let me know if you have any other questions.

**Closed by liamdebeasi** 2023-10-20 13:55 UTC
Labels: triage

**Comment by biesbjerg** [comment] 2023-10-20 14:49
The minimal reproduction was just to showcase the (imo very unexpected) behavior. 

In reality it can happen for a number of reasons out of our control.

For exampe:
- User's session expires while on Tab 2, so they are logged out and taken to the login page (without tabs).
- After logging in, we want to show them Tab 1, since it's the default tab when starting the app.
(It could also be a new user logging in, so we don't want to have them start at Tab 2 (which might not even exist for that user in case it's a dynamic tab)

Or another example:
- User receives a push notification that they have received a new messages (while on a page without tabs). 
- Internally the app calls `router.push()` to open the newly received message.

Hope you agree that those are valid use cases! I'm sure I can think of more 😄

After debugging for a while, it seems `.ion-page-hidden` never gets added (or maybe to the wrong element) when leaving the tab. I feel like only a single tab (within a TabBar instance) should be able to exist without `.ion-page-hidden` which I (maybe naively think would solve this issue). If I add it manually via devtools to the tab, the correct content shows.

**Comment by liamdebeasi** [comment] 2023-10-20 15:57
> User's session expires while on Tab 2, so they are logged out and taken to the login page (without tabs).
After logging in, we want to show them Tab 1, since it's the default tab when starting the app.
(It could also be a new user logging in, so we don't want to have them start at Tab 2 (which might not even exist for that user in case it's a dynamic tab)

That is a valid use case, but you'll need to make sure the old tabs instance is destroyed or otherwise not re-used. One way to do this is to use `router.go(n)` where `n` is the negative number that takes you back to a login page. You could also use `router.go(n)` to go to the state before the tabs page and use `router.replace` to replace that state with the login page. That will ensure the tabs instance is destroyed and not re-used.

**Comment by biesbjerg** [comment] 2023-10-20 16:13
Thanks for the suggestions! 

If the app starts with a valid authKey the TabsPage will be first in the stack, so there won't be a page before. 

I don't think anyone expects a wrong view to be shown for a tab without warning, even if it's against best practices most of the time — May I ask if there's a reason why we couldn't fix the underlying issue of the active tab page not being hidden when navigating to another outlet?

**Comment by liamdebeasi** [comment] 2023-10-20 18:07
> If the app starts with a valid authKey the TabsPage will be first in the stack, so there won't be a page before.

In that case I'd recommend going back to that first route (the TabsPage) and calling `router.replace()`. That will let you replace the active tabs state with the login page.

> May I ask if there's a reason why we couldn't fix the underlying issue of the active tab page not being hidden when navigating to another outlet?

When you transition away from a tab view to a non-tabbed view the entire `ion-tabs` component transitions away. However, the tab content is still considered active within the context of `ion-tabs`, so it should not be hidden within the tabs context.
