### ISSUE TITLE
bug: Button Click in Item focuses Input

### ISSUE THREAD

**Issue by HansKrywaa** [ionic-team/ionic-framework#21887] opened 2020-08-06 13:23 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

I have a Scenario where i have an Item like in the provided Repo. You can see that if you click the upper Button the Input below becomes focused. (You can test than on a Mac via simple `serve`). On native iOS this is very disgusting as the keyboard opens of course.

**Expected behavior:**

Only focus the Input if i click into it.

**Steps to reproduce:**

I created this Repo where you can see it: https://github.com/HansKrywaa/item-focus-bug
I just created it s simple as possible with the same structure as in our main app.

**Other information:**

**Ionic info:** (of main app)

```
Ionic CLI                     : 6.11.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.3.1
   @angular-devkit/build-angular : 0.1000.5
   @angular-devkit/schematics    : 10.0.5
   @angular/cli                  : 10.0.5
   @ionic/angular-toolkit        : 2.3.0

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : android 9.0.0, ios 6.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 50 other plugins)

Utility:

   cordova-res : 0.15.1
   native-run  : 1.0.0

System:

   Android SDK Tools : 25.2.3 (/Users/hanskrywalsky/Library/Android/sdk)
   ios-deploy        : 1.10.0
   ios-sim           : 8.0.2
   NodeJS            : v12.16.1 (/usr/local/bin/node)
   npm               : 6.14.7
   OS                : macOS Catalina
   Xcode             : Xcode 11.6 Build version 11E708
```

**Comment by liamdebeasi** [comment] 2020-08-06 13:33
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/21509.

**Closed by liamdebeasi** 2020-08-06 13:33 UTC
Labels: triage

**Comment by HansKrywaa** [comment] 2020-08-06 13:35
Sorry, didn't found that one
