### ISSUE TITLE
bug: nav, swipe back transition gets stuck with swiping quickly

### ISSUE THREAD

**Issue by Ensaphelon** [ionic-team/ionic-framework#27893] opened 2023-07-30 16:59 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Currently, when using `ion-nav` and having at least two transitions between two screens, there is a chance that it will not be possible to go back from the nested page. this behaviour is totally random

### Expected Behavior

All transitions between pages should work correctly, regardless of the nesting of pages and the frequency of transitions between them.

### Steps to Reproduce

1. Set up a basic example using `iov-nav`, `ion-link`, `ion-content` with a root page and the nested one
2. Navigate to the nested page
3. Swipe back
4. Repeat 2 and 3 steps until the bug appears

### Code Reproduction URL

https://replit.com/@RamilMusaiev/React-TypeScript-1#src/App.tsx

### Ionic Info

Since I was integrating ionic on top of the existing project the output is corresponding

```
ionic info
[WARN] You are not in an Ionic project directory. Project context may be missing.

Ionic:

   Ionic CLI : 7.1.1

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v18.16.0
   npm    : 9.5.1
   OS     : macOS Unknown
```

### Additional Information

Here is the video:

https://github.com/ionic-team/ionic-framework/assets/5896973/05be8a67-1c80-4cb9-8714-a2c6dc81806f

As you can see, at some point the subpage has the CSS property `pointer-events: none;` even though I was right on the subpage. When I tried to override this property in the browser, the page became responsive again, but the swipe back gesture didn't work.

**Comment by liamdebeasi** [comment] 2023-07-31 13:54
Thanks for the report. How do I run your sample code on `replit`? I tried clicking the "Run" button, but I just get a white screen.

**Comment by Ensaphelon** [comment] 2023-07-31 14:31
@liamdebeasi thanks for the quick reaction, I recorded another video by running `replit` under incognito mode, seems working for me:


https://github.com/ionic-team/ionic-framework/assets/5896973/04e00e37-f415-4b3a-b3bb-e8488914b2d9

**Comment by liamdebeasi** [comment] 2023-07-31 14:51
Thanks, incognito mode seemed to work. However, I am unable to reproduce the reported behavior. What browser/version are you testing this on?

**Comment by Ensaphelon** [comment] 2023-07-31 15:13
I am using Chrome `114.0.5735.198`, on macOS Ventura `13.3.1 (a)`.

But initially, I faced this bug when I was navigating in our app, it is a native application with injected webview, which runs a usual web inside. Also, I am able to reproduce it on the iOS simulator `iPhone 13, iOS 16.2`.

This bug is actually very unstable to reproduce, on my phone I had to pull the screen back and forth for about a minute or two to reproduce the problem. The fastest way was to move the screen as I showed in the opening video: you need to pull the screen to the right a little and release. You need to repeat this until the problem appears.

**Comment by liamdebeasi** [comment] 2023-08-01 13:28
Thanks, I can reproduce this now. It looks like this is the same bug as https://github.com/ionic-team/ionic-framework/issues/22895 but for `ion-nav`.

**Comment by liamdebeasi** [comment] 2023-08-01 13:44
Can you try the following dev build and let me know if it resolves the issue?

```
7.2.2-dev.11690896715.12338339
```

Install Example:

```
npm install @ionic/react@7.2.2-dev.11690896715.12338339 @ionic/react-router@7.2.2-dev.11690896715.12338339
```

**Comment by Ensaphelon** [comment] 2023-08-01 15:49
@liamdebeasi it seems that the problem was fixed in the build you specified, thank you very much. Waiting for the `v7.2.2` release 🤝 

Just in case putting here the working example: https://replit.com/@RamilMusaiev/React-TypeScript-3

**Comment by liamdebeasi** [comment] 2023-08-02 19:20
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/27904, and a fix will be available in an upcoming release of Ionic Framework.

**Closed** 2023-08-02 19:19 UTC
Labels: package: core, type: bug
