### ISSUE TITLE
feat: Modal swipe to close - sensitive should be higher

### ISSUE THREAD

**Issue by snimavat** [ionic-team/ionic-framework#25087] opened 2022-04-08 17:28 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Either increase the default sensitivity for swipe to close modals, or give. some callback / configurability which can be used to enable swipe to close with less efforts.

### Describe the Use Case

Sheet modals supports swipe to close. So user can pull the modal down and it will close. the functionality works, but the swipe sensitivity is very less compared to the the other popular apps (Eg sheet modals of FB App)

I have a modal with 80% break point, It is quite difficult to close an ionic sheet modal with a single swipe, it takes me two to three efforts before i can close it, or else, i will have to start swipe from very top of the modal. 

If i swipe the modal from some where at middle, and do a quick pull down, it will jump back to its original position without closing.  This is very non user friendly, when using FB, i can see how less efforts / pull I need to close their sheet modals.

Either we need some thing configurable for swipe sensitivity, or the default swipe to close sensitivity need to be increased

### Describe Alternatives

None

### Related Code

None

### Additional Information

None

**Comment by liamdebeasi** [comment] 2022-04-08 19:48
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/24296.

**Closed by liamdebeasi** 2022-04-08 19:48 UTC
Labels: triage
