### ISSUE TITLE
bug (Angular) : default ion-back-button is not working 

### ISSUE THREAD

**Issue by indraraj26** [ionic-team/ionic-framework#21988] opened 2020-08-27 07:42 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

I followed the  [docs](https://ionicframework.com/docs/api/back-button) and pick the first option default back button, I added in children page and back button is showing properly but when i click on it nothing happens

**Expected behavior:**

When i click on back button it should take me to previous route/component

**Steps to reproduce:**

**Related code:**

![image](https://user-images.githubusercontent.com/23274631/91411872-973eb980-e866-11ea-9e20-599797b36780.png)
![image](https://user-images.githubusercontent.com/23274631/91411891-9c036d80-e866-11ea-8825-cc24d84945dc.png)
home.ts to navigate
```
	onChildrenHandler(i) {
		this._router.navigate([i], { relativeTo: this._route })
	}
```
on children.html
```
<ion-header>
  <ion-toolbar>
    <ion-buttons slot="start">
      <ion-back-button></ion-back-button>
    </ion-buttons>
    <ion-title>children</ion-title>
  </ion-toolbar>
</ion-header>
<ion-content>

</ion-content>
<ion-footer>

</ion-footer>
```

**Other information:**

**Ionic info:**

```
ionic info

Ionic:

   Ionic CLI                     : 6.11.0 (C:\Users\indra26\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.3.1
   @angular-devkit/build-angular : 0.1000.7
   @angular-devkit/schematics    : 10.0.7
   @angular/cli                  : 10.0.7
   @ionic/angular-toolkit        : 2.3.2

Utility:

   cordova-res : 0.15.1
   native-run  : 1.0.0

System:

   NodeJS : v10.16.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.9.0
   OS     : Windows 10

```

**Comment by indraraj26** [comment] 2020-08-27 14:35
Hi Liam, 

I forget to put link. 
here you go : https://github.com/indraraj26/ionic5-starter-tabs-sidemenu/tree/ion-back-button-click
branch: ion-back-button-click

Thank you

**Comment by liamdebeasi** [comment] 2020-08-28 16:12
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. Your routing setup is incorrect. You should be managing pages from the "main" routing modules. Take a look at our conference app setup for examples:

1. Base pages: https://github.com/ionic-team/ionic-conference-app/blob/024450f4a820576c5366d90956551372fd891d36/src/app/app-routing.module.ts
2. Nested with tabs: https://github.com/ionic-team/ionic-conference-app/blob/024450f4a820576c5366d90956551372fd891d36/src/app/pages/tabs-page/tabs-page-routing.module.ts

For top level routes, the conference app manages them in `app-routing.module.ts`. For routes nested inside of tabs, the conference app manages them in `tabs-page-routing.module.ts`. Notice that it does not manage child routes inside of the routing module for each page.

It looks like you want to have a child page inside of the home page. While we do not recommend this as it can lead to a confusing user experience with nested navigation, you can achieve this by adding an additional `ion-router-outlet` inside of the home page. From there, you could manage the child routes in `home-routing.module.ts` like how the conference app manages child pages of tabs in `tabs-page-routing.module.ts`.

**Closed by liamdebeasi** 2020-08-28 16:12 UTC
Labels: ionitron: needs reproduction

**Comment by indraraj26** [comment] 2020-08-28 17:01
Hi,

If the routing setup is incorrect how it is working in plain angular project?  This is really sad i have been using same routing in all angular project.

As per comment, it look like it is limitation of ion-router-outlet.

**Comment by liamdebeasi** [comment] 2020-08-28 17:05
The routing configuration is incorrect in that it does not really make sense to translate that to a mobile application. It may have worked in a regular Angular application because navigation in a browser is linear. Ionic Framework uses stack-based navigation which is closer to how mobile applications behave. This issue could very well be a limitation of `ion-router-outlet`, but this is also not something we are likely to support as it goes against how stack-based navigation is supposed to behave.

**Comment by indraraj26** [comment] 2020-08-30 06:52
Hi Liam, 

I just did as you said but that will render children component inside home component as it has ion-router-outlet, is there any other way around to make it work with navigation.

if i don't add ion-router-outlet in home component then children component is not rendering.

I have updated my repo
Repo: https://github.com/indraraj26/ionic5-starter-tabs-sidemenu/tree/ion-back-button-click
Branch: ion-back-button-click
