### ISSUE TITLE
bug: ion-datetime with pickerOptions cannot add Cancel button

### ISSUE THREAD

**Issue by satocw** [ionic-team/ionic-framework#19441] opened 2019-09-25 03:51 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

I'm using ion-datetime with pickerOptions. I want to add custom 'Cancel' button, but when I select 'Cancel', the ion-datetime doesn't display the original value.

**Expected behavior:**

When I select 'Cancel' button, I want ion-datetime to display the original value.

**Steps to reproduce:**

https://stackblitz.com/edit/ionic-v4-angular-tabs-6plufr?file=src%2Fapp%2Ftab1%2Ftab1.page.ts

1. Open datetime picker, change value and select 'Cancel'.
2. Datetime displays original value (10:00), which is an expected behavior.
3. Open datetime picker, change value and select 'Cancel' again.
4. Datetime displays the changed value. 

**Related code:**
When not using pickerOptions, Ionic Datetime adds default cancel button, with handler `this.updateDatetimeValue(this.value)`.(https://github.com/ionic-team/ionic/blob/master/core/src/components/datetime/datetime.tsx#L310)

I want to do the exact same thing, but it seems there is no way to do that from my custom pickerOptions.

Ionic Datetime is also watching the property 'value', (https://github.com/ionic-team/ionic/blob/master/core/src/components/datetime/datetime.tsx#L194-L201) so I tried changing the value from my component, but that didn't solve.

I suppose it is a bug of Ionic, or if it's not a bug, I want to know how I can implement 'Cancel' behavior with custom pickerOptions.

Thank you,

**Comment by satocw** [comment] 2019-09-25 07:29
Ok, I found a solution.
```
pickerOptions = {
  buttons: [
    {
      text: 'Cancel',
      role: 'cancel',
      handler: (e) => {
        this.value = null;
        setTimeout(() => {
          this.value = "10:00" // original value
        }, 0);
      }
    }
  ]
};
```
Writing like the above can fire `valueChanged()` event of Ion Datetime.
So every time I select 'Cancel', original time can be displayed.

**Comment by brandyscarney** [comment] 2020-09-30 22:20
Thank you for the issue! I'm going to close this as a duplicate of #20048 since there are more comments on that one.

**Closed by brandyscarney** 2020-09-30 22:20 UTC
Labels: triage
