### ISSUE TITLE
bug: IonDatetime has wrong position 

### ISSUE THREAD

**Issue by mixalbl4-127** [ionic-team/ionic-framework#24531] opened 2022-01-07 14:06 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

![image](https://user-images.githubusercontent.com/3511307/148554622-3ef1a03c-ff81-4867-800a-eae2077dcb16.png)

### Expected Behavior

![image](https://user-images.githubusercontent.com/3511307/148554718-057e4df8-452e-44dc-82bc-969912790b3a.png)

### Steps to Reproduce

1. Create new **blank react** app by `ionic start`
2. Add dateTime cmp to any place (for example: `<IonDatetime value="2012-12-15T13:47:20.789"></IonDatetime>` to `ExploreContainer.tsx`
3. Open in mobile mode.
4. Click to Time.

### Ionic Info

ionic info
[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package'
       
       Require stack:
       - /home/stealth/.nvm/versions/node/v14.18.2/lib/node_modules/@ionic/cli/lib/project/index.js
       - /home/stealth/.nvm/versions/node/v14.18.2/lib/node_modules/@ionic/cli/lib/index.js
       - /home/stealth/.nvm/versions/node/v14.18.2/lib/node_modules/@ionic/cli/index.js
       - /home/stealth/.nvm/versions/node/v14.18.2/lib/node_modules/@ionic/cli/bin/ionic
[WARN] Error loading @capacitor/android package.json: Error: Cannot find module '@capacitor/android/package'
       
       Require stack:
       - /home/stealth/.nvm/versions/node/v14.18.2/lib/node_modules/@ionic/cli/lib/project/index.js
       - /home/stealth/.nvm/versions/node/v14.18.2/lib/node_modules/@ionic/cli/lib/index.js
       - /home/stealth/.nvm/versions/node/v14.18.2/lib/node_modules/@ionic/cli/index.js
       - /home/stealth/.nvm/versions/node/v14.18.2/lib/node_modules/@ionic/cli/bin/ionic

Ionic:

   Ionic CLI       : 6.18.1 (/home/stealth/.nvm/versions/node/v14.18.2/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 6.0.1

Capacitor:

   Capacitor CLI      : 3.3.4
   @capacitor/android : not installed
   @capacitor/core    : 3.3.4
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v14.18.2 (/home/stealth/.nvm/versions/node/v14.18.2/bin/node)
   npm    : 8.3.0
   OS     : Linux 5.11

**Comment by mixalbl4-127** [comment] 2022-01-07 15:07
I dont know why, but it happends because of replace click event target in this place: `await deepReady(this.usersElement);` in `@ionic/core/components/overlays.js` for popover.
**Before execution deepReady:**
![image](https://user-images.githubusercontent.com/3511307/148563230-83dea46e-5c3b-4fad-af6b-c588bc23a867.png)
After deepReady:
![image](https://user-images.githubusercontent.com/3511307/148563280-71dd788c-d335-4f4a-ae22-05335715151e.png)

**Comment by mixalbl4-127** [comment] 2022-01-07 15:32
I think this is a explain: https://stackoverflow.com/questions/63607966/event-target-changed-in-settimeout-in-shadow-dom

**Comment by liamdebeasi** [comment] 2022-01-07 16:07
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/24415.

**Closed by liamdebeasi** 2022-01-07 16:07 UTC
Labels: holiday triage
