### ISSUE TITLE
bug: Tabs flicker when keyboard is closed when Input loses focus

### ISSUE THREAD

**Issue by informatikTirol** [ionic-team/ionic-framework#27386] opened 2023-05-04 06:38 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Tabs flicker when keyboard is closed when Input loses focus, see video or image below

![Ns+Z](https://user-images.githubusercontent.com/16346085/236128313-39d50c2d-306d-48ed-bd74-184c35414a91.jpg)

https://user-images.githubusercontent.com/16346085/236128184-1aeb01d0-8ecd-44ec-b3d0-89d2096e0738.MP4

### Expected Behavior

No flickering 

### Steps to Reproduce

1. Set focus to input on tab 1
2. Remove focus from input
3. See tab flicker when keyboard is closing

### Code Reproduction URL

https://www.dropbox.com/s/x8shnps8lyijaeq/IONIC7Flicker.zip?dl=0

### Ionic Info

Ionic:

   Ionic CLI                     : 7.1.1 (/Users/aj/.nvm/versions/node/v16.14.2/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.0.5
   @angular-devkit/build-angular : 15.2.8
   @angular-devkit/schematics    : 15.2.8
   @angular/cli                  : 15.2.8
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.0.0
   @capacitor/android : not installed
   @capacitor/core    : 5.0.0
   @capacitor/ios     : 5.0.0

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.2

System:

   NodeJS : v16.14.2 (/Users/aj/.nvm/versions/node/v16.14.2/bin/node)
   npm    : 8.5.0
   OS     : macOS Unknown

**Comment by mapsandapps** [comment] 2023-05-04 12:00
Hi! Thank you for the issue. I'm going to close this as a duplicate of #25990.

**Closed by mapsandapps** 2023-05-04 12:00 UTC
Labels: triage
