### ISSUE TITLE
bug: ion-tab with nested navigation

### ISSUE THREAD

**Issue by antonio-spinelli** [ionic-team/ionic-framework#24339] opened 2021-12-07 15:05 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

When we have a page with his own `ion-router-outlet` inside a tab page, we can't return to the last navigated page if we switch between tab pages.

### Expected Behavior

If we switch between tab pages, nested routes should be keep.

### Steps to Reproduce

Create a Tab component.
Create a Tab1 component with an `ion-router-outlet` and with at least 2 children: A and B (just simple components). Add it as child of tab component.
Create a Tab2 simple component and add it as child of tab component.
Click on Tab1. First component A should be displayed. Navigate to component B
Click on Tab2.
Click on Tab1.

Navigation is now back to component A :(

### Code Reproduction URL

https://stackblitz.com/edit/ionic-angular-v5-h4fnec

### Ionic Info

Ionic:

   Ionic CLI                     : 6.17.0
   Ionic Framework               : @ionic/angular 5.9.1
   @angular-devkit/build-angular : 12.2.3
   @angular-devkit/schematics    : 12.0.5
   @angular/cli                  : 12.2.3
   @ionic/angular-toolkit        : 5.0.3

Capacitor:

   Capacitor CLI      : 3.2.0
   @capacitor/android : not installed
   @capacitor/core    : 3.2.0
   @capacitor/ios     : not installed

Utility:

   cordova-res                          : 0.15.3
   native-run (update available: 1.5.0) : 1.4.0

System:

   NodeJS : v14.17.6
   npm    : 6.14.15
   OS     : macOS Big Sur

### Additional Information

I don't really know if it's a bug or a request for a feature. I think it's an expected behaviour and i didn't find simple solution for handle it, without creating my own history for resume the right path inside tab1

**Comment by sean-perkins** [comment] 2021-12-07 17:54
@antonio-spinelli thanks for reporting this issue!

I'm going to close this issue out as a duplicate of #16949 as it relates closely. 

While not an ideal solution, removing the default path match in your `nested-navigation.module.ts` does improve the nested routing retention (with other downsides/logic that has to be maintained). 

This piece:
```ts
{ path: '', redirectTo: 'page-1', pathMatch: 'full' },
```

I would strongly encourage avoiding using a blank path with lazy loading and move your tab routes under a `tabs` prefix. 

We aim to improve the routing experience across our eco-system in the future. Please upvote 16949 to let us know it's important to you.

**Closed by sean-perkins** 2021-12-07 17:54 UTC
Labels: triage

**Comment by antonio-spinelli** [comment] 2021-12-09 16:30
> @antonio-spinelli thanks for reporting this issue!
> 
> I'm going to close this issue out as a duplicate of #16949 as it relates closely.
> 
> While not an ideal solution, removing the default path match in your `nested-navigation.module.ts` does improve the nested routing retention (with other downsides/logic that has to be maintained).
> 
> This piece:
> 
> ```ts
> { path: '', redirectTo: 'page-1', pathMatch: 'full' },
> ```
> 
> I would strongly encourage avoiding using a blank path with lazy loading and move your tab routes under a `tabs` prefix.
> 
> We aim to improve the routing experience across our eco-system in the future. Please upvote 16949 to let us know it's important to you.

sorry @sean-perkins, didn't notice that that issue was related to my case. I already seen it before post this issue but I must admit that I thought it wasn't related to mine.
By the way if I remove the redirect Tab1 it will not show anything on first start.
Why you recommend to do not use blank path with lazy loading module? How do I manage them without? I can work with relative path with that without knows which module load that module. I even work with lazy module loaded in different path that need those "pages".
