### ISSUE TITLE
bug: Item input changes display from one device to another

### ISSUE THREAD

**Issue by StriderRanger** [ionic-team/ionic-framework#22009] opened 2020-08-31 00:09 UTC
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
I have an Item input text with a personalized display, but this display isn't the same across all devices:
In [this example](https://stackblitz.com/edit/ionic5-ion-item-responsivity-prblm), the label in the empty input items looks correct as shown in this image:
![image](https://user-images.githubusercontent.com/15088185/91672053-5cb17700-eb1b-11ea-9f60-eebf37183f6f.png)

But this display does not remain the same when tested in Chrom Dev Tools while choosing a specific device (Like the iPhone 6/7/8 for example). As you might notice, the labels become more close to the border than before:
![image](https://user-images.githubusercontent.com/15088185/91672157-21637800-eb1c-11ea-8ce6-b081da861cc1.png)

The same behavior was noticed after running the application in an actual device (Asus Zenfone 3/Android 8.0)

**Expected behavior:**
The position of the labels should remain the same across any device.

**Steps to reproduce:**

- Open the chrome DevTools and choose iPhone 6/7/8 device

- Acces the example app with the url: https://ionic5-ion-item-responsivity-prblm.stackblitz.io/

Ionic Angular StackBlitz: https://stackblitz.com/edit/ionic5-ion-item-responsivity-prblm

**Ionic info:**

```
   Ionic CLI : 5.4.16
   Ionic Framework : @ionic/angular 5.3.1
   @angular-devkit/build-angular : 0.1000.8
   @angular-devkit/schematics : 10.0.8
   @angular/cli : 10.0.8
   @ionic/angular-toolkit : 2.3.3
```

**Comment by liamdebeasi** [comment] 2020-08-31 13:29
Thanks for the issue. I am unable to reproduce the issue you are describing. Am I following the correct steps?

1. Open the StackBlitz in Chrome.
2. Observe that the labels look correct as in the first image.
3. Select a device to emulate (I chose iPhone 6/7/8).

From what I understand, the labels should look closer to the second image, but they still render correctly for me.

**Comment by StriderRanger** [comment] 2020-08-31 13:46
@liamdebeasi  Thanks for your reply. The steps are all correct except that you should refresh the page when you select the simulated device, I noticed the problem in any chosen device from the Chrome DevTools.
I'd like also to add that when running the app in a real device via `ionic cordova run android --device` the display of the Item input becomes different than from a web browser, or a Chrome simulated device, and still incorrect.

Thanks!

**Comment by liamdebeasi** [comment] 2020-08-31 13:59
Thanks. Are you able to reproduce this outside of StackBlitz? I was able to reproduce it in StackBlitz but not outside of it.

**Comment by StriderRanger** [comment] 2020-08-31 14:32
@liamdebeasi Besides my local development environment, I only tested this issue in stackblitz. The "Ionic Info" in the description are related to the dev environment.
I'd be glad to provide any information that will help to better understand the problem.

**Comment by StriderRanger** [comment] 2020-08-31 14:35
@liamdebeasi Just to make sure, did you copy the css properties related to the `ion-item` from Stackblitz to your test environment?

**Comment by liamdebeasi** [comment] 2020-08-31 14:41
Thanks, I forgot about the CSS. I can reproduce this issue now; however, this issue appears to be caused by your custom CSS. I am able to reproduce the issue when I start the app in iOS mode, regardless of whether or not I am using Chrome's device emulation.

I am going to close this as this is not a bug in Ionic Framework. The floating labels and inputs rely on having spacing and dimensions be consistent, so it is likely that when changing the height of the item, you also need to change the height of the input/label as well.

**Closed by liamdebeasi** 2020-08-31 14:41 UTC
Labels: triage
