### ISSUE TITLE
bug: ion-datetime displays 0:00 pm on phone chromium browsers

### ISSUE THREAD

**Issue by JoeBoxr** [ionic-team/ionic-framework#25862] opened 2022-08-31 13:51 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

When selecting the time on the datetime popup and setting 12:00 pm, the resulting value in datetime component is 0:00 pm.   This only occurs on phone devices (Android version 12 for this test) running chromium browser (chrome, edge etc.).  It works as expected with Firefox on mobile.

### Expected Behavior

It's expected that 12:00 pm selected in the time popup results in a 12:00 pm value in datetime component.

### Steps to Reproduce

Use the following code in a mobile (Android 12) web app.

`<ion-datetime-button datetime="openTime"></ion-datetime-button>
    <ion-modal [keepContentsMounted]="true">
      <ng-template>
        <ion-datetime hourCycle="h12" id="openTime" presentation="time" showDefaultButtons="true"
          doneText="Ok"></ion-datetime>
      </ng-template>
    </ion-modal>`
![time-bug](https://user-images.githubusercontent.com/6962529/187694777-02436ac6-2962-4558-bb51-6b90a63f6357.jpg)

### Code Reproduction URL

https://angular-ivy-ptcjwe.stackblitz.io

### Ionic Info

Ionic:

   Ionic CLI                     : 5.4.4 (C:\Users\Admin\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 6.2.4
   @angular-devkit/build-angular : 13.3.3
   @angular-devkit/schematics    : 13.2.6
   @angular/cli                  : 13.3.3
   @ionic/angular-toolkit        : 6.1.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v14.17.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.13
   OS     : Windows 10

**Comment by liamdebeasi** [comment] 2022-08-31 14:30
Thanks for the report. What version of Chrome are you testing this on? I am testing this on Chrome 104 on Android 13 and am unable to reproduce this issue. The datetime button renders "12:00 PM" as expected.

**Comment by JoeBoxr** [comment] 2022-08-31 15:28
Hello.

It's on Android 12 running Chrome 104 and Chrome dev 106

**Comment by liamdebeasi** [comment] 2022-08-31 16:02
Do you have any additional information that could help me reproduce the issue? I see the text being rendered as "12:00 PM":
![Screenshot_20220831-120119](https://user-images.githubusercontent.com/2721089/187725035-42de8257-5d4b-49fb-aaa9-a5a2915ddcd3.png)

**Comment by JoeBoxr** [comment] 2022-08-31 16:39
Shows up fine on a tablet running Android 11 and a phone running Android 6.  Seems to be isolated to just Android 12

**Comment by JoeBoxr** [comment] 2022-08-31 16:44
The Android 12 device I'm using is running OnePlus OxygenOS which may be the underlining problem to this issue

**Comment by liamdebeasi** [comment] 2022-08-31 18:12
Thanks for the additional information. What is the locale being used on your device? You can find this by logging `navigator.language` when inspecting the app using Chrome developer tools.

**Comment by JoeBoxr** [comment] 2022-08-31 18:24
Hello.

For some reason it's showing up as en-GB on this device when it should be en-US.  This is obviously an OS issue and thank you for your time looking into this.

**Comment by liamdebeasi** [comment] 2022-08-31 18:59
Thanks! Setting the locale to `en-GB` is what triggered the issue for me. I can confirm that this is a bug.

Ionic uses [Intl.DateTimeFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat) to handle most of the date and time localization. One of the options we use here is `hour12` which lets us control whether to show the time in a 12 hour or 24 hour format.

It looks like there is a bug in Chromium-based browsers (Chrome, Edge, Brave, etc) where "12:00 pm" is incorrectly rendered as "0:00 pm" even when setting `hour12: true`: https://bugs.chromium.org/p/chromium/issues/detail?id=1347316&q=hour12&can=2. Using the `hourCycle` option instead seems to resolve the issue. We should probably use this anyways since it will make supporting https://github.com/ionic-team/ionic-framework/issues/23750 easier.

**Comment by liamdebeasi** [comment] 2022-08-31 19:12
Here is a dev build if you would like to test the proposed fix:

```
npm install @ionic/angular@6.2.6-dev.11661972719.14922e17
```

You may need to install this to a local application as StackBlitz sometimes has trouble installing dev builds.

**Comment by liamdebeasi** [comment] 2022-09-06 14:25
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/25869, and a fix will be available in an upcoming release of Ionic Framework. Please feel free to continue testing the dev build.

**Closed by liamdebeasi** 2022-09-06 14:25 UTC
Labels: type: bug, bug: external
