### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by mayankkataria** [ionic-team/ionic-framework#25472] opened 2022-06-15 12:27 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

When I open the time popover in ```ion-datetime``` and close it, then calendar month changes to previous month.

### Expected Behavior

Month should not change

### Steps to Reproduce

1. Navigate to [ionic's official site](https://ionicframework.com/docs/api/datetime)
2. Scroll to 'Custom Locale' in virtual device screen
3. Click on time and time popover will open
4. Click anywhere on screen except time popover to close it
5. The month will change to previous month

### Ionic Info

Ionic:

   Ionic CLI                     : 6.19.1 (/home/arcgate/.nvm/versions/node/v14.15.5/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.1.7
   @angular-devkit/build-angular : 13.2.6
   @angular-devkit/schematics    : 13.3.7
   @angular/cli                  : 13.2.6
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.5.1
   @capacitor/android : 3.5.1
   @capacitor/core    : 3.5.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.6.0

System:

   NodeJS : v14.15.5 (/home/arcgate/.nvm/versions/node/v14.15.5/bin/node)
   npm    : 6.14.11
   OS     : Linux 5.14

**Comment by liamdebeasi** [comment] 2022-06-15 16:58
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/25438.

There is a dev build with a fix in https://github.com/ionic-team/ionic-framework/issues/25438#issuecomment-1156712199.

**Closed by liamdebeasi** 2022-06-15 16:58 UTC
Labels: triage
