### ISSUE TITLE
bug: Ion-Nav will trigger angular lifecycle function twice after launch it second time

### ISSUE THREAD

**Issue by Coder7777** [ionic-team/ionic-framework#26578] opened 2023-01-06 23:42 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

1st time -> trigger ngOnInit once,
2nd time -> trigger ngOnInit twice,
3rd time -> trigger ngOnInit twice,
.....
....
nth time -> trigger ngOnInit twice,

### Expected Behavior

1st time -> trigger ngOnInit once,
2nd time -> trigger ngOnInit once,
3rd time -> trigger ngOnInit once,
.....
....
nth time -> trigger ngOnInit once,

### Steps to Reproduce

I refer to ionic official blog to use Ion-Nav, but the lifecycle function will be triggered twice.

official post : https://ionic.io/blog/how-to-navigate-in-ionic-modals-with-ion-nav

I upload my code and video, it can reproduce this issue.
https://github.com/Coder7777/customNavigation.git.
 
https://user-images.githubusercontent.com/17242425/211117859-80b24437-a374-4b5a-ada8-a77c603887c0.mov

### Code Reproduction URL

https://github.com/Coder7777/customNavigation.git

### Ionic Info

Ionic:

   Ionic CLI                     : 6.20.3 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.4.1
   @angular-devkit/build-angular : 15.0.5
   @angular-devkit/schematics    : 15.0.5
   @angular/cli                  : 15.0.5
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 4.6.1
   @capacitor/android : not installed
   @capacitor/core    : 4.6.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.1

System:

   NodeJS : v16.13.2 (/usr/local/bin/node)
   npm    : 8.1.2
   OS     : macOS

**Comment by DwieDima** [comment] 2023-01-09 08:48
#25675

**Comment by liamdebeasi** [comment] 2023-01-09 13:47
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/25675.

**Closed by liamdebeasi** 2023-01-09 13:47 UTC
Labels: triage
