### ISSUE TITLE
feat: Make `subtree` an optional prop for the Mutation Observer in `slides.tsx`

### ISSUE THREAD

**Issue by nathanb21** [ionic-team/ionic-framework#22960] opened 2021-02-23 12:46 UTC
# Feature Request

**Ionic version:**

[x] **5.5**

**Describe the Feature Request**
There's an issue within `ion-slides` where if any dynamic content is contained within the slide, and this updates whilst a user has partially dragged the slide, the slide position will reset to center until the user continues to drag. This can create a poorer experience whilst a user interacts with an ion-slides element.

The issue is caused by `swiper.update()` being called from within `slides.tsx` when child components are modified in the DOM in any way. There's an example of this behaviour at https://codesandbox.io/s/ion-slides-debug-test-case-ztgn1

**Describe Preferred Solution**
```
@Prop() watchDeepChildDomChanges = true;

...

{
  childList: true,
  subtree: this.watchDeepChildDomChanges
}

...
```

**Related Code**

**Additional Context**

We likely want childList to always be true, as that will be the `ion-slide` elements, when these are added / removed we need swiper to update.

Subtree is on any further children and may not be necessary in all use-cases, see https://developer.mozilla.org/en-US/docs/Web/API/MutationObserverInit/childList

The default `true` could be deprecated for `false` if there's notable performance gains, but this discussion would be separate and simply adding the prop to configure this would be highly beneficial.

**Comment by liamdebeasi** [comment] 2021-02-23 14:35
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/21739.

**Closed by liamdebeasi** 2021-02-23 14:35 UTC
Labels: triage
