### ISSUE TITLE
bug: IonInput clears value when switching between type text and password

### ISSUE THREAD

**Issue by JustACodeMonkey** [ionic-team/ionic-framework#28122] opened 2023-09-05 20:32 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When giving users the ability to show their password, switching the IonInput type from password to text and then back to password resets the input value IF the user tries to type more characters when the input type is returned to password.

HTML snippet
```
<ion-input
  label="Password"
  [type]="type"
></ion-input>
```

TS snippet
```
type = 'password';

changeType(newType: 'password' | 'text') {
  this.type = newType;
}
```

### Expected Behavior

Switching between type text and password should not cause the input's value to reset if the user tries to modify the value.

### Steps to Reproduce

1. See StackBlitz URL https://stackblitz.com/edit/angular-k6p3uf-rhnga3?file=src%2Fapp%2Fexample.component.html,src%2Fapp%2Fexample.component.ts
2. Enter abc in the password field
3. Click the TEXT button to switch to type="text"
4. Enter def after abc in the password field
5. Click the PASSWORD button to switch to type="password"
6. Click at the end of the entered text in the password field (after the dot for the "f")
7. Type g ... abcdef is reset and the password is now only g

### Code Reproduction URL

https://stackblitz.com/edit/angular-k6p3uf-rhnga3?file=src%2Fapp%2Fexample.component.html,src%2Fapp%2Fexample.component.ts

### Ionic Info

Angular 16.0.1
Ionic 7.3.2

StackBlitz depencies
![image](https://github.com/ionic-team/ionic-framework/assets/10424675/e00787f9-0c8f-4730-9d67-ceb1b8fa3644)

### Additional Information

I have tried using reactive forms and patching the value in a timeout after the switch between type text and password but that doesn't help either.

**Comment by liamdebeasi** [comment] 2023-09-05 20:56
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. As per the [input documentation](https://ionicframework.com/docs/api/input#clearonedit), the `clearOnEdit` property defaults to `true` when the input is of type `password`. 

This feature is designed for users who want to correct a mistyped password. Since the password is obscured, `clearOnEdit` will clear the text field since users may not know where the typo is. This allows them to re-enter their password without having to manually clear the mistyped password first.

Since your app provides a way to show the entered password, you should set `[clearOnEdit]="false"` to disable this auto-clearing behavior.

**Closed by liamdebeasi** 2023-09-05 20:56 UTC
Labels: triage

**Comment by JustACodeMonkey** [comment] 2023-09-06 12:17
> Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. As per the [input documentation](https://ionicframework.com/docs/api/input#clearonedit), the `clearOnEdit` property defaults to `true` when the input is of type `password`.
> 
> This feature is designed for users who want to correct a mistyped password. Since the password is obscured, `clearOnEdit` will clear the text field since users may not know where the typo is. This allows them to re-enter their password without having to manually clear the mistyped password first.
> 
> Since your app provides a way to show the entered password, you should set `[clearOnEdit]="false"` to disable this auto-clearing behavior.

Thank you @liamdebeasi . I completely missed that property in the docs.
