### ISSUE TITLE
bug: Input caret visible through all layers

### ISSUE THREAD

**Issue by DanyloKatranGitHub** [ionic-team/ionic-framework#23814] opened 2021-08-25 01:19 UTC
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

![image](https://user-images.githubusercontent.com/58117904/130709934-422fa680-905a-44d4-b9ca-fb45bbf7a34f.png)
![image](https://user-images.githubusercontent.com/58117904/130709950-b56c488a-59e4-44e3-9e84-3aefecbf4ca1.png)

iOS. Input caret visible through all layers.
You can see a blue caret in the top left corner through the header on 2nd screenshot.

### Expected Behavior

Caret is not visible through the header.

### Steps to Reproduce

Focus input. Scroll down so the header covers input. You can see blinking input caret through the header.

### Code Reproduction URL

https://github.com/DanyloKatranGitHub/ionic-cursor-issue

### Ionic Info

Ionic:

   Ionic CLI                     : 6.17.0 (C:\Users\danil\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.6.14
   @angular-devkit/build-angular : 12.1.4
   @angular-devkit/schematics    : 12.2.2
   @angular/cli                  : 12.1.4
   @ionic/angular-toolkit        : 4.0.0

Capacitor:

   Capacitor CLI      : 3.2.0
   @capacitor/android : 3.2.0
   @capacitor/core    : 3.2.0
   @capacitor/ios     : 3.2.0

Utility:

   cordova-res : 0.15.3
   native-run  : 1.4.0

System:

   NodeJS : v14.15.1 (C:\Program Files\nodejs\node.exe)
   npm    : 7.13.0

### Additional Information

This is only iOS bug.
I found this issue: https://github.com/ionic-team/ionic-framework/issues/26 but it is closed with no info on this ceratin bug.

**Comment by liamdebeasi** [comment] 2021-08-25 13:06
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. This is a long standing issue on iOS and not something we can fix. The main issue stems from the fact that the caret is part of the native iOS layer and not part of the web layer. As a result, the caret does not know that it is supposed to be "under" the header. You can see the same issue on any website that has a sticky header with an input in the scrollable area.

We have a [Hide Caret](https://github.com/ionic-team/ionic-framework/wiki/Utilities#input-shims) utility that hides the caret on scroll to help avoid the same issue, but when there is no scrolling the caret will appear.

**Closed by liamdebeasi** 2021-08-25 13:06 UTC
Labels: triage
