### ISSUE TITLE
feat: Mask support for IonInput

### ISSUE THREAD

**Issue by jonit-dev** [ionic-team/ionic-framework#22452] opened 2020-11-08 02:19 UTC
# Feature Request

IonInput mask support

**Ionic version:**
5

**Describe the Feature Request**
There's no straitghforward way to implement this on IonInput and this is a BASIC feature for any app.

**Describe Preferred Solution**
Example for international phone number
<IonInput mask="+9 (999) 999-9999"}/>  

**Describe Alternatives**
- Create it on your own, not using Ionic react components
- Maybe some other third party library out there that I'm not aware of (Tried react-input-mask, without success)

**Comment by liamdebeasi** [comment] 2020-11-09 14:28
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/15424.

**Closed by liamdebeasi** 2020-11-09 14:28 UTC
Labels: triage
