### ISSUE TITLE
bug: Form not submitting during "Enter" press when multiple ion-input inside of form.

### ISSUE THREAD

**Issue by mattsteve** [ionic-team/ionic-framework#25004] opened 2022-03-26 04:16 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

When a single ion-input is inside a form with a submit button, pressing enter while focused inside of that input submits the form.

When multiple ion-input are inside a form with a submit button, pressing enter in either input does not submit the form.

### Expected Behavior

No matter how many inputs are inside of a form when a submit button is present, pressing enter inside of them should submit the form.

### Steps to Reproduce

Add 2 ion-input to a form, with a ion-button type="submit".

```
<form action="javascript:void(0)" onsubmit="checkSubmit()">
  <ion-item>
    <ion-label position="stacked">Type anything, then press Enter:</ion-label>
    <ion-input />
  </ion-item>
  <ion-item style="--padding-start: 0">
    <ion-label position="stacked">Another Input:</ion-label>
    <ion-input />
  </ion-item>
  <ion-button type="submit" class="ion-margin-top">
    Submit
  </ion-button>
</form>
```

### Code Reproduction URL

https://jsfiddle.net/nmfer04s/

### Ionic Info

N/A

### Additional Information

I believe this is a regression, it was working when I was using Ionic 5.

**Comment by EinfachHans** [comment] 2022-03-26 12:18
Mhh i don't know if this would be the correct behavior 🤔 I would not want this in my apps, because i just want to submit the form on the last input... You can easily add this by adding `(keyup.enter)="..."` on every input or create a directive

**Comment by mattsteve** [comment] 2022-03-26 16:05
The "correct" default behavior is what's in the spec. E.g. mimic what a raw HTML form does. It's not important what you want specifically in your application. You can always change default be whatever you want, as you mentioned.

This bug is to get HTML forms working to spec, and working how they should work to meet WAI ARIA 2.0 accessibility compliance. People with disabilities rely on a HTML form's default behaviors (screen readers, special controllers for people with motor disabilities  emulate keyboard controls).

**Comment by mattsteve** [comment] 2022-03-26 16:16
Also, most likely it's working the way it is currently not by carefully considered design decision, but by quirks of using the shadow DOM.

**Comment by sean-perkins** [comment] 2022-03-28 17:13
This does appear to be a bug. `ion-input` does not use shadow DOM, so there is some event listener preventing the event from bubbling when multiple inputs are present in a form.

Will capture as a bug and prioritize.

**Comment by mattsteve** [comment] 2022-03-28 18:14
`ion-input` doesn't but `ion-button` does. Replace the ion-button with a normal button in the reproduction & press enter.

**Comment by liamdebeasi** [comment] 2022-03-29 13:27
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/19368.

**Closed by liamdebeasi** 2022-03-29 13:27 UTC
Labels: package: core, type: bug
