### ISSUE TITLE
bug: life-cycle methods don't work in ionModal (react)

### ISSUE THREAD

**Issue by andyindahouse** [ionic-team/ionic-framework#22186] opened 2020-09-27 14:42 UTC
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**
I'm trying to use the lifecycles (useIonViewWillEnter, useIonViewDidEnter) provided by ionic but these don't work when they're into a modal.

You can reproduce it here: https://codesandbox.io/s/ionic-react-router-forked-wjqoy?file=/src/App.tsx

**Expected behavior:**

These hooks works in components into a modal in the same way that they do when they're into a IonPage directly.

**Steps to reproduce:**

You can reproduce it here: https://codesandbox.io/s/ionic-react-router-forked-wjqoy?file=/src/App.tsx

**Related code:**

You can reproduce it here: https://codesandbox.io/s/ionic-react-router-forked-wjqoy?file=/src/App.tsx

**Other information:**

If you added a IonPage to the modal, they work but this has other sideEffects because of you have a IonPage into other IonPage. So I'm not sure that this is the way to go. I understand that you should have these hooks in any componente inside of the IonModal in the same way that the components into IonPage, Don't I?

Thanks in advance 👍

**Comment by liamdebeasi** [comment] 2020-09-28 13:06
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The lifecycle hooks `useIonViewWillEnter` and others are for use in routing environments. IonModal exists outside of the router, so these hooks do not work here. Instead, you should be using the default React component lifecycle hooks.

**Closed by liamdebeasi** 2020-09-28 13:06 UTC
Labels: triage

**Comment by andyindahouse** [comment] 2020-09-30 17:33
hmmm, I'm getting problems with React component lifecycle hooks because of when it runs the modal is not presented yet. By the way, How can I listen modal events from React? events like **ionModalDidPresent**, I'm seeing the doc but I can't find react example

**Comment by liamdebeasi** [comment] 2020-09-30 18:38
Hmm yeah we should update that example. Here is how you would use it in React:

```jsx
<IonModal
  isOpen={showModal}
  onDidPresent={() => doSomething()}
  onDidDismiss={() => doSomethingAgain()}
>
  <p>This is modal content</p>
</IonModal>
```

Basically it's the same usage as all the other overlay components such as [Popover](https://ionicframework.com/docs/api/popover#usage)

**Comment by andyindahouse** [comment] 2020-10-01 17:23
Oh, I see, thx! :D
