### ISSUE TITLE
bug: safe-area-inset-top appears to be 0 when compiling for macOS 11 beta

### ISSUE THREAD

**Issue by AVatch** [ionic-team/ionic-framework#21621] opened 2020-06-24 18:20 UTC
# Bug Report

With the beta for MacOs and iOS14 I wanted to see how our ionic app would render on desktop since you can set your iPad apps to target desktop with the latest Xcode. So everything works except it appears that the `safe-area-inset-top` is not being set properly.

This means the `--ion-safe-area-top` is not correct and as seen in the screenshot below results in the status bar overlapping with the top toolbar. 

This is more of a heads up for upcoming compatibility than anything being broken.

**Ionic version:**
[x] **5.x**

**Current behavior:**
App status bar overlaps with top toolbar

**Expected behavior:**
Toolbar should not have status bar overlap.

**Steps to reproduce:**
Create an app and target Mac

**Related code:**

**Other information:**
<img width="1077" alt="Screen Shot 2020-06-24 at 2 14 55 PM" src="https://user-images.githubusercontent.com/1807958/85611118-a23a5b00-b625-11ea-8b87-1750340595d0.png">

**Ionic info:**

```

Ionic:

   Ionic CLI                     : 6.10.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.2.2
   @angular-devkit/build-angular : 0.901.9
   @angular-devkit/schematics    : 9.1.9
   @angular/cli                  : 9.1.9
   @ionic/angular-toolkit        : 2.2.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v14.4.0 (/usr/local/bin/node)
   npm    : 6.14.5
   OS     : macOS
```

**Comment by mhartington** [comment] 2020-06-25 16:19
Note that this exist in releases prior to macOS 11.

Since the env-variables are set by the webview, WKWebview might need to account for this internally.

**Comment by liamdebeasi** [comment] 2020-07-08 16:54
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. I was able to reproduce this in a Mac Catalyst app without Ionic Framework or Capacitor. Ionic Framework is utilizing the safe area values correctly, it's just that WebKit is setting the values to `0` all the time.

I opened an issue with the WebKit team: https://bugs.webkit.org/show_bug.cgi?id=213752.

**Closed by liamdebeasi** 2020-07-08 16:54 UTC
Labels: triage
