### ISSUE TITLE
bug: router.replace eventually breaks routing

### ISSUE THREAD

**Issue by tigohenryschultz** [ionic-team/ionic-framework#24432] opened 2021-12-17 00:05 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

After navigating around using router.push and router.replace, eventually a view will linger.

### Expected Behavior

Correct rendering of leaving/entering view items.

### Steps to Reproduce

Navigating from View A1 -(replace)-> B/1 -(push)-> B/2  -(back button)-> B/1 -(replace)-> A1 -(replace)-> B1

B1 never gets render and is glitched onto A1.

<img src="https://user-images.githubusercontent.com/75696293/146278422-06e4fd09-3541-4919-83ba-c6bcfcb27863.png" width="350px" />

### Ionic Info

Ionic:

   Ionic CLI : 6.16.3

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v14.17.3
   npm    : 6.14.13
   OS     : Windows 10

**Comment by sean-perkins** [comment] 2021-12-17 16:50
Partially related to: #24226

We may decide to group the Vue routing issues together to reduce individual & overlapping tasks for us internally.

**Comment by tigohenryschultz** [comment] 2021-12-17 17:13
> Partially related to: #24226
> 
> We may decide to group the Vue routing issues together to reduce individual & overlapping tasks for us internally.

Since I have a good understand of routing now I don't mind tackling the issues/tickets regarding it, they're pretty high priority issues for the company I work for and we don't want any negative app reviews from routes breaking so I've been given the go ahead to work on this.

**Comment by tigohenryschultz** [comment] 2021-12-20 18:51
Working on this issue in this pull request: https://github.com/ionic-team/ionic-framework/pull/24433

**Comment by liamdebeasi** [comment] 2022-01-07 19:15
@tigohenryschultz Do you have a reproduction case for this router.replace issue? I have a fix for https://github.com/ionic-team/ionic-framework/issues/24226 and would like to test to see if my patch also fixes this issue.

Note that this patch does not fix https://github.com/ionic-team/ionic-framework/issues/23873 since that example does not use replace.

**Comment by tigohenryschultz** [comment] 2022-01-07 21:48
> @tigohenryschultz Do you have a reproduction case for this router.replace issue? I have a fix for #24226 and would like to test to see if my patch also fixes this issue.
> 
> Note that this patch does not fix #23873 since that example does not use replace.

I've been side tracked getting the original test cases to pass but I do plan on adding tests for this specific scenario I ran into and the other ones I found while refactoring the code. Like:

Sometimes a ViewItem would be added to multiple outlets 
The last tab you were on would not have ion-page-hidden when navigating away until re-entering the tab so the life cycles would not fire for it.

On Monday I can add a test case for the specific scenario I ran into

**Comment by Lokilein** [comment] 2022-01-20 09:45
I think I got a similar/ the same issue (details here => [Ionic Forum: Ionic 5/6 with Vue: Pages do not change sometimes (URL does)](https://forum.ionicframework.com/t/ionic-5-6-with-vue-pages-do-not-change-sometimes-url-does/219363/5) )
I tried some things, but using push instead of replace or back seems to help. I updated to ionic/vue 6.0.2 and still got the issue.

**Comment by tigohenryschultz** [comment] 2022-01-20 16:30
I've fixed this issue in a pull request but they have not merged it in yet.

**Comment by liamdebeasi** [comment] 2022-02-01 17:40
Hi @Lokilein and @tigohenryschultz,

I am investigating a fix for this issue. However, in order to verify the fix I need to test against a sample reproduction of the issue reported in this thread.

Can you provide a GitHub repo that I can use to reproduce the issue described in https://github.com/ionic-team/ionic-framework/issues/24432#issue-1082745995?

**Comment by tigohenryschultz** [comment] 2022-02-01 19:54
prevRouteLastPathname becomes incorrect after some navigation  steps causing the IonRouterOutlet to not find the correct 'leaving' viewItem. I'll try to create a sample if I have time but it is fixed in the pull request.

**Comment by liamdebeasi** [comment] 2022-02-01 20:01
Thanks, a GitHub repo would be great. Even if the resolution here is to move forward with your PR, we would still need the sample app.

**Comment by liamdebeasi** [comment] 2022-02-01 20:33
Let's start with the GitHub repo for this particular bug and then we can assess from there. Thanks!

**Comment by Lokilein** [comment] 2022-02-04 14:07
Hi there. I cannot share my repository, but I've recreated the bug here with instructions to reproduce it:
https://github.com/Lokilein/ionicRoutingBug

**Comment by liamdebeasi** [comment] 2022-02-04 14:48
Thanks! This particular reproduction does not use `router.replace` which is what is causing the issue reported in this thread. Does this reproduce a different issue?

**Comment by Lokilein** [comment] 2022-02-04 15:55
Hmm, actually I am not completly sure. The original description also used the back action and the result is the same. I have to check if replace makes any difference, but I think it causes the same issue, that's why I replaced everything with push in my project for now.

**Comment by liamdebeasi** [comment] 2022-02-04 15:57
Ok thanks. I have a potential solution that I am working on now. I will post a dev build here when it is ready for testing.

**Comment by Lokilein** [comment] 2022-02-04 16:05
Okay I've updated my example and now it fails faster by using the back button the first time. URL is changing but the page remains.

**Comment by liamdebeasi** [comment] 2022-02-04 17:35
Thanks! Can you try the following dev build and let me know if it resolves the issue?

```
npm install @ionic/vue@6.0.6-dev.1643995688.8c79635 @ionic/vue-router@6.0.6-dev.1643995688.8c79635
```

This dev build fixes the main `replace` issue in this thread as well as the other issue you reported in https://github.com/ionic-team/ionic-framework/issues/24432. (Turns out, they were related bugs 😄 )

**Comment by Lokilein** [comment] 2022-02-07 08:15
This looks much better! I cannot reproduce any issue with this anymore, neither with back nor with replace 👍  Thank you very much!

Can you tell when this will be in main?

**Comment by liamdebeasi** [comment] 2022-02-07 14:03
I do not have an estimate of when this fix will be merged as it still needs to be reviewed by the team.

**Comment by liamdebeasi** [comment] 2022-02-07 20:37
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/24721 and a fix will be available in an upcoming release of Ionic Framework.

Please feel free to continue testing the dev build.

**Closed** 2022-02-07 20:37 UTC
Labels: package: vue, type: bug
