### ISSUE TITLE
bug: ionic checkbox displays undefinded instead of box

### ISSUE THREAD

**Issue by nagdevbharat** [ionic-team/ionic-framework#22899] opened 2021-02-09 13:54 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

Currently when i set id attribute on ion-checkbox it shows undefined instead of checkbox when id consists special character.
it gives error in console `Error: Failed to execute 'querySelector' on 'Document': 'label[for=check.1]' is not a valid selector`

**Expected behavior:**

Checkbox should be displayed properly as previously it worked.

**Steps to reproduce:**

add checkbox with id attribute
add special characters in id.

**Related code:**

A sample application via GitHub

StackBlitz (https://stackblitz.com)
https://stackblitz.com/edit/ionic-v4-angular-tabs-rbjr9o?file=src/app/tab1/tab1.page.html

```
<ion-checkbox id="check-1"></ion-checkbox> this works
<ion-checkbox id="check.1"></ion-checkbox> this does not
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.12.1 
   Ionic Framework               : @ionic/angular 5.5.2
   @angular-devkit/build-angular : 0.1101.3
   @angular-devkit/schematics    : 11.1.3
   @angular/cli                  : 11.1.3
   @ionic/angular-toolkit        : 3.0.0

Capacitor:

   Capacitor CLI   : 2.4.4
   @capacitor/core : 2.4.4

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.23.0
   npm    : 6.14.8
   OS     : macOS Big Sur
   Xcode  : Xcode 12.2 Build version 12B45b
```

**Comment by liamdebeasi** [comment] 2021-02-09 14:15
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/22678.

**Closed by liamdebeasi** 2021-02-09 14:15 UTC
Labels: triage
