### ISSUE TITLE
bug: ion-datetime aria-labels are hardcoded and doesn't match locale value

### ISSUE THREAD

**Issue by Edigregorio** [ionic-team/ionic-framework#29563] opened 2024-05-29 12:58 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/docs/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

ion-datetime aria-labels are hardcoded and doesn't match locale value. If I use voiceover or talkback on ion-datetime I listen the aria-labels "previous month", "next month" and "today" in english even if locale value is Italian.

### Expected Behavior

Aria-labels will change according to locale value language.

### Steps to Reproduce

Go to ion-datetime with voiceover or talkback and click on previous/next month arrows.
Go to ion-datetime with voiceover or talkback and click on today.

### Code Reproduction URL

/

### Ionic Info

Ionic:

   Ionic CLI                     : 7.2.0 (/Users/e.digregorio/.nvm/versions/node/v18.16.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.7.5
   @angular-devkit/build-angular : 17.3.7
   @angular-devkit/schematics    : 17.3.7
   @angular/cli                  : 17.3.7
   @ionic/angular-toolkit        : 11.0.1

Cordova:

   Cordova CLI       : 12.0.0 (cordova-lib@12.0.1)
   Cordova Platforms : ios 7.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 24 other plugins)

Utility:

   cordova-res : 0.15.4
   native-run  : 2.0.1

System:

   ios-deploy : 1.12.2
   ios-sim    : 8.0.2
   NodeJS     : v20.12.2 (/Users/e.digregorio/.nvm/versions/node/v20.12.2/bin/node)
   npm        : 10.5.0
   OS         : macOS Unknown
   Xcode      : Xcode 15.0.1 Build version 15A507

**Comment by brandyscarney** [comment] 2024-05-29 15:59
Thank you for the issue! I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/25859. Please subscribe to that issue for updates. 🙂

**Closed by brandyscarney** 2024-05-29 15:59 UTC
Labels: triage
