### ISSUE TITLE
bug: ion-datetime: set initial value fails for month-year and year (always shows current date))

### ISSUE THREAD

**Issue by scotthardin** [ionic-team/ionic-framework#24909] opened 2022-03-09 18:59 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Each screenshot uses ISO date of value="2012-12-15T13:47:20.789" except value the one titled month-year (value="2012-12").  The html used to generate these screenshots is in the steps to reproduce below.

Docs say initial value can be set using value attribute; however, it works only for presentation = [date, date-time, time-date]: 
<img width="391" alt="Screen Shot 2022-03-09 at 1 49 15 PM" src="https://user-images.githubusercontent.com/5597004/157511687-9242cb19-ca30-4ee3-ba44-ed30bfd93b4f.png">

With all the other presentation = [month, month-year, time, year], the control is set to the current date (the value is ignored):
<img width="378" alt="Screen Shot 2022-03-09 at 1 49 24 PM" src="https://user-images.githubusercontent.com/5597004/157511708-410b5b11-0f2f-4c29-9618-8c8f157a18d7.png">

### Expected Behavior

If value is set to an ISO 8601 date, it should be reflected in the initial value for the control.

### Steps to Reproduce

Paste this html into any ionic angular project.

```
date
<ion-datetime presentation="date" value="2012-12-15T13:47:20.789"></ion-datetime>
<br />
date-time
<ion-datetime presentation="date-time" value="2012-12-15T13:47:20.789"></ion-datetime>
<br />
time-date
<ion-datetime presentation="time-date" value="2012-12-15T13:47:20.789"></ion-datetime>
<br />
month
<ion-datetime presentation="month" value="2012-12-15T13:47:20.789"></ion-datetime>
<br />
month-year
<ion-datetime presentation="month-year" value="2012-12-15T13:47:20.789"></ion-datetime>
month-year (value="2012-12")
<ion-datetime presentation="month-year" value="2012-12"></ion-datetime>
<br />
time
<ion-datetime presentation="time" value="2012-12-15T13:47:20.789"></ion-datetime>
<br />
year
<ion-datetime presentation="year" value="2012-12-15T13:47:20.789"></ion-datetime>
```

### Code Reproduction URL

Getting Started Wizard said "Unable to create app, please ping us on Twitter and try the manual install below." 

### Ionic Info

Ionic:

   Ionic CLI                     : 6.18.2 (/Users/scott/.nvm/versions/node/v16.13.1/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.10
   @angular-devkit/build-angular : 13.2.5
   @angular-devkit/schematics    : 13.2.5
   @angular/cli                  : 13.2.5
   @ionic/angular-toolkit        : 6.0.0

Capacitor:

   Capacitor CLI      : 3.4.3
   @capacitor/android : 3.4.3
   @capacitor/core    : 3.4.3
   @capacitor/ios     : 3.4.3

Utility:

   cordova-res : 0.15.4
   native-run  : 1.5.0

System:

   NodeJS : v16.13.1 (/Users/scott/.nvm/versions/node/v16.13.1/bin/node)
   npm    : 8.5.1
   OS     : macOS Monterey

**Comment by liamdebeasi** [comment] 2022-03-09 20:21
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/24878.

**Closed by liamdebeasi** 2022-03-09 20:21 UTC
Labels: triage
