### ISSUE TITLE
bug: router.go() not working as expected in ionic vue app

### ISSUE THREAD

**Issue by TaraWei-twobulls** [ionic-team/ionic-framework#28201] opened 2023-09-20 06:39 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Actual behaviour: app view is in Page2 but url is Page1's.

### Expected Behavior

Expected to be in Page1 for both url and view.

### Steps to Reproduce

1. Home page > Page 1 > Page2 > Page3 using ionRouter.push()
2. Page3 > Page2 using ionRouter.back()
3. Trigger history.go(-2) or router.go(-2) in Page2
[4f603fb4-1c47-478f-9229-391b3fcef05c.webm](https://github.com/ionic-team/ionic-framework/assets/107837804/9e600f49-ed7f-42d6-bc18-72839b5c0fc9)

### Code Reproduction URL

https://github.com/TaraWei-twobulls/Ionic-vue-app-router-issue-reproduction/tree/main

### Ionic Info

Ionic:

   Ionic CLI       : 7.1.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 7.1.2

Capacitor:

   Capacitor CLI      : 5.1.1
   @capacitor/android : 5.1.1
   @capacitor/core    : 5.1.1
   @capacitor/ios     : 5.1.1

### Additional Information

  Seems  ionic outlet view does not know where the current view is, and it always go back from the last view in stack though user has been back to the previous view

**Comment by TaraWei-twobulls** [comment] 2023-09-22 03:29
Reproduction added. Please find the example codebase and the issue recording.

**Comment by liamdebeasi** [comment] 2023-09-22 17:10
Did you push the complete code? I see `myApp` is added as a submodule, but there's no information in there so I can't initialize it.

**Comment by TaraWei-twobulls** [comment] 2023-09-26 02:46
Sorry just noticed that and updated it.
Please run `npm i` and` ionice serve` to run it locally.

**Comment by thetaPC** [comment] 2023-11-17 19:27
Thank you for reporting the issue. I can confirm that the `router.go()` is not navigating to the correct view. This issue has been categorized as a bug to prioritize in our backlog.

**Comment by bentleyo** [comment] 2024-09-13 06:59
Has there been any update on this one @thetaPC?

We're also running into this problem. It causes navigation to be quite unreliable in some situations and doesn't give us confidence in the ability to navigate backwards in the history stack.

**Comment by thetaPC** [comment] 2024-09-13 17:13
Thank you for reaching out. I wanted to let you know that the issue is still in our backlog. At the moment, we don’t have a specific timeline for when it will be addressed. However, rest assured that it's on our radar, and we will update this issue as soon as we have more information.

**Comment by bentleyo** [comment] 2024-09-17 09:11
@thetaPC I have just submitted a PR for this issue https://github.com/ionic-team/ionic-framework/pull/29877.

It looks like https://github.com/ionic-team/ionic-framework/issues/29846 might be a duplicate of this issue.

**Closed** 2024-10-22 20:43 UTC
Labels: type: bug

**Comment by thetaPC** [comment] 2024-10-22 20:52
Thanks for the issue! This has been resolved via PR https://github.com/ionic-team/ionic-framework/pull/29877 and will be available in an upcoming release of Ionic.
