### ISSUE TITLE
bug: Using Redirect from 'react-router' doesn't work

### ISSUE THREAD

**Issue by andyperlitch** [ionic-team/ionic-framework#22230] opened 2020-10-01 19:30 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

When rendering a `<Redirect />` (from 'react-router'; `IonRedirect` is simply broken as far as I can tell), the appropriate `<Route />` does not get rendered. Refreshing the page once on this route also does not render the expected view. (Minimal reproduction linked below).

**Expected behavior:**
The redirect should render the expected page, both on click of `<IonTabButton>` (in the case of my reproduction code), and on page refresh.

**Steps to reproduce:**

Assume we have two routes: `/tab3` and `/tab3/:id`, and a router setup like this:

```
<IonRouterOutlet>
  <Route path="/tab3" component={Tab3} /> {/* `exact` omitted, so extensions `path` should match */}
</IonRouterOutlet>
```

In the `render` method of the `Tab3` component passed to the `Route`, I want to redirect if the `:id` is not present, like so:

```
import { Redirect, useParams } from 'react-router'

const Tab3 = () => {
  const { id } = useParams()
  if (!id) {
    return <Redirect to="/tab3/defaultId" />
  }
  return (/* other jsx */)
}
```

I expect this to re-render `Tab3` with `id: 'defaultId``, however this does not happen.

Here's a minimal reproduction of the problem:
https://github.com/andyperlitch/ion-redirect-question/tree/redirect-problem

I initialized this project using the cmd: `ionic start redirect-error tabs --type=react --capacitor`.
Here are the only changes I've made: https://github.com/andyperlitch/ion-redirect-question/compare/redirect-problem?diff=split#diff-354ac40d75fac96af44f92051f2d56c5

**Comment by jcampbell05** [comment] 2020-10-02 18:12
I also want to add to this that when using a redirect like this I've found that sometime the parameters from the url aren't correct passed to the view. Instead the only way I got it to work is bodge a redirect like so.

<img width="566" alt="Screenshot 2020-10-02 at 19 07 49" src="https://user-images.githubusercontent.com/1484989/94955892-30569500-04e3-11eb-84de-315c63bf0840.png">

**Comment by aabanaag** [comment] 2020-10-21 01:24
Any ideas why the redirect doesn't work? I encountered this issue but I have two separate projects using the same version one uses the redirect but works on the newer one is not working.

**Comment by elylucas** [comment] 2020-10-30 14:41
Hi @andyperlitch,

I took a look at your git repo, and the reason its not working is you don't have a route setup to handle tab3/{id}. If you add this route to your main `App.tsx` file under the rest of the routes it appears to function as intended (it redirects to tab3/1 and the console writes out "tab3: id present 1"): 

```
<Route path="/tab3/:id" component={Tab3} />
```

Let us know if that fixes your issue. I'm going to close this for now but feel free to comment back here and we can take another look if needed.

**Comment by elylucas** [comment] 2020-10-30 14:42
@jcampbell05 and @aabanaag, would you be able to provide reproduction repos for what you are running into?

**Closed by elylucas** 2020-10-30 14:41 UTC
Labels: triage

**Comment by jcampbell05** [comment] 2020-10-30 15:29
I'll have a look.
