### ISSUE TITLE
bug: Cannot override or style ion-input component

### ISSUE THREAD

**Issue by KasTasElis** [ionic-team/ionic-framework#25904] opened 2022-09-09 12:08 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

I am attempting to override CSS variables as instructed by Ionic docs for ion-input component. This does not work.

I have included a "control" ion-button component that clearly shows a CSS variable override working for an ion-button component.

### Expected Behavior

The padding, colour and background CSS variable overrides should display red color.

### Steps to Reproduce

The issue is already presented. Please see the theme.css file and the app output. 

I have included a "control" ion-button component that clearly shows a CSS variable override working for an ion-button component.

### Code Reproduction URL

https://codesandbox.io/s/bug-demo-ionic-ion-input-theming-does-not-work-gkd6ge

### Ionic Info

cant do it in a sandbox.

**Comment by liamdebeasi** [comment] 2022-09-09 13:03
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/17425.

The issue is that Ionic's internal styles are more specific than the input styles you provided in your application. Using a more specific selector such as `ion-input.custom-class` works around the issue. Please follow #17425 for updates on this issue.

**Closed by liamdebeasi** 2022-09-09 13:03 UTC
Labels: triage
