### ISSUE TITLE
bug: ion-datetime wheel @ionChange event not triggering

### ISSUE THREAD

**Issue by baartho** [ionic-team/ionic-framework#26503] opened 2022-12-16 18:54 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

if the user selects today's date then clicks on OK, the @ionChange event is not triggered. 

If one changes any of the fields (day, month or year) then the event is trigerred as expected

### Expected Behavior

The event should be triggered in all circunstamces.

### Steps to Reproduce

Code to reproduce: 

```
<ion-datetime
    id="datetime"
    presentation="date"
    locale="pt-BR" 
  @ionChange="setDataNascimentoString($event)"
  cancel-text="Cancelar"
  done-text="Ok"
  :show-default-buttons="true"
  :prefer-wheel="true" 
></ion-datetime>



setDataNascimentoString(event){
   console.log(event);
}
```

a) Steps to reproduce
1 - Do not change anything and simply click "OK". The @ionChange event won't be triggered

b) steps to reproduce 
1 - change any of the fields (day, month or year) and you can even change it back to the original value 
2 - Click on OK and the even WILL be triggered this time

### Ionic Info

[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package'

       Require stack:
       - C:\Users\bartho\AppData\Roaming\npm\node_modules\@ionic\cli\lib\project\index.js
       - C:\Users\bartho\AppData\Roaming\npm\node_modules\@ionic\cli\lib\index.js
       - C:\Users\bartho\AppData\Roaming\npm\node_modules\@ionic\cli\index.js
       - C:\Users\bartho\AppData\Roaming\npm\node_modules\@ionic\cli\bin\ionic

Ionic:

   Ionic CLI       : 6.20.0 (C:\Users\bartho\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/vue 6.3.9

Capacitor:

   Capacitor CLI      : 3.5.1
   @capacitor/android : 3.5.1
   @capacitor/core    : 3.5.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.6.0

System:

   NodeJS : v16.13.1 (C:\Program Files\nodejs\node.exe)
   npm    : 8.5.0
   OS     : Windows 10

**Comment by liamdebeasi** [comment] 2022-12-16 19:25
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/25839.

**Closed by liamdebeasi** 2022-12-16 19:25 UTC
Labels: triage
