### ISSUE TITLE
bug: ion-popover context-menu trigger not working on iOS

### ISSUE THREAD

**Issue by anderslutzhoft** [ionic-team/ionic-framework#27884] opened 2023-07-28 16:46 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When applying `trigger-action="context-menu"` on an ion-popover element does not show the popover on iOS. Not even the example in the documentation
https://ionicframework.com/docs/api/popover seems to work.

### Expected Behavior

Long press on trigger element should show the popover.

### Steps to Reproduce

1. Open https://ionicframework.com/docs/api/popover#triggers on iOS device
2. Scroll to Triggers
3. Press/long press on Right-Click Me button

Same applies on my local project

### Code Reproduction URL

https://ionicframework.com/docs/api/popover#triggers

### Ionic Info

Ionic:

   Ionic CLI       : 7.1.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 7.1.3

Capacitor:

   Capacitor CLI      : 5.0.0-rc.2
   @capacitor/android : 5.0.0-rc.2
   @capacitor/core    : 5.0.0-rc.2
   @capacitor/ios     : 5.0.0-rc.2

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v18.15.0 (/usr/local/bin/node)
   npm    : 9.5.0
   OS     : macOS Unknown

**Comment by liamdebeasi** [comment] 2023-07-28 17:04
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/25471.

**Closed by liamdebeasi** 2023-07-28 17:04 UTC
Labels: triage
