### ISSUE TITLE
bug: Remove margin from select popover.

### ISSUE THREAD

**Issue by infacto** [ionic-team/ionic-framework#23971] opened 2021-09-23 11:48 UTC
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

The popover always scrolls a pixel which looks weird and untidy.

![demo](https://user-images.githubusercontent.com/60390085/134500705-8ea614d5-5145-45b4-b9ca-f3032e578f34.gif) 👎 

![image](https://user-images.githubusercontent.com/60390085/134500454-397dea70-593b-42e3-aa4d-001c12a0a906.png)

Why is `margin-top` and `margin-bottom` set to `-1px`?

Related [source code](https://github.com/ionic-team/ionic-framework/blob/v5.8.1/core/src/components/select-popover/select-popover.vars.scss).

### Expected Behavior

Don't scroll. Set margin to 0 and in this example padding is also 0. But margin 0 will fix this issue.

![demo](https://user-images.githubusercontent.com/60390085/134501290-40b05b80-b7e6-4535-a9fb-e19bbe855a62.gif) 👍 

### Steps to Reproduce

```html
<ion-list class="ion-no-padding">
  <ion-item-group>
    <ion-item>
      <ion-label>Select Option</ion-label>
      <ion-select placeholder="Please select." interface="popover">
        <ion-select-option> A </ion-select-option>
        <ion-select-option> B </ion-select-option>
        <ion-select-option> C </ion-select-option>
      </ion-select>
    </ion-item>
  </ion-item-group>
</ion-list>
```

Play with that. Then add following css to the `global.scss`.

```scss
.sc-ion-select-popover {
  padding: 0 !important;
  margin: 0 !important;
}
```

Enjoy.

Personally I prever `ion-no-padding` for lists. We could set this by default for the list. Just consider it for the select popover interface. But the primary issue is to fix the unnecessary scroll behavior (margin).

### Ionic Info

```text
Ionic:

   Ionic CLI                     : 6.16.1
   Ionic Framework               : @ionic/angular 5.8.1
   @angular-devkit/build-angular : 12.1.4
   @angular-devkit/schematics    : 12.1.4
   @angular/cli                  : 12.1.4
   @ionic/angular-toolkit        : 4.0.0

System:

   NodeJS : v14.15.1
   npm    : 6.14.8
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment] 2021-09-23 12:57
Thanks, I can reproduce this. Looks like these `-1px` margins go all the way back to Ionic v3: https://github.com/ionic-team/ionic-v3/blob/master/src/components/select/select.scss#L7-L15.

The original context is no longer there as I cannot find an associated PR or GitHub issue. My current guess is this was added to work around some old Chromium/WebKit/UIWebView bug.

I will look into removing it.

**Comment by liamdebeasi** [comment] 2021-09-23 14:05
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/23972 and a fix will be available in an upcoming release of Ionic Framework.

**Closed by liamdebeasi** 2021-09-23 14:05 UTC
Labels: package: core, type: bug
