### ISSUE TITLE
feat: Emit event when datetime month changes

### ISSUE THREAD

**Issue by henkjurriens** [ionic-team/ionic-framework#25730] opened 2022-08-05 18:44 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

A feature request for the datetime component.  Emit an event when datetime changes.

### Describe the Use Case

I want to update a title with the current month. But currently when I changes datetime, for example next or previous month, the title is only updated when I select a day.

### Describe Preferred Solution

Emit an event when datetime changes.

### Additional Information

https://user-images.githubusercontent.com/211346/183141441-1fe5787c-d6fa-449c-a4bf-aff124d880a6.mov

**Comment by liamdebeasi** [comment] 2022-08-05 19:07
Thanks for the issue. Can you help me understand what you are trying to build? In particular, why do you have a second month label when one is already displayed in the datetime component?

**Comment by henkjurriens** [comment] 2022-08-05 19:45
Hi Liam,

If you click on the title you can toggle to display or hide the datetime picker. So if you select the next month this should reflect in the title. See my little demo.

In my activities view I like to switch between a month view and a list view.


￼

Best wishes

Henk

**Comment by henkjurriens** [comment] 2022-08-05 19:47
https://user-images.githubusercontent.com/211346/183150056-215c2c8b-a4ff-4508-bc69-4bd789c6f09b.mov

**Comment by liamdebeasi** [comment] 2022-08-09 14:20
Thanks for the additional information. Since the datetime collapses, would make more sense to display the selected date rather than the month that is being shown in the date picker? My concern here is that the "active" month is an implementation detail and should not be exposed to applications. In general, developers should only be concerned with the date/time value that the end user has confirmed.

**Comment by liamdebeasi** [comment] 2022-08-09 17:33
Are you referring to the smaller calendar component in the sidebar?
![image](https://user-images.githubusercontent.com/2721089/183720811-56a41d76-103f-49e7-bcca-4c8d41b39dd3.png)

Or are you looking at the big scheduler in the main view?

**Comment by liamdebeasi** [comment] 2022-08-09 17:34
If you are referring to the big scheduler in the main view, then `ion-datetime` is not the correct component to use here. You likely want to use a scheduler component instead of a date picker component. For example, MobiScroll has a scheduler component that is separate from its date picker component: https://mobiscroll.com/event-calendar-scheduler

**Comment by henkjurriens** [comment] 2022-08-09 17:40
Mobiscroll  is not a solution for me. I thought an emit event was a quite general solution. But I'll think about another solution. Thanks so far.

**Comment by liamdebeasi** [comment] 2022-08-09 17:43
While exposing the "active" month would be easy for us to implement, it would allow devs to tightly couple the state of their app to the internal state of an Ionic component which is not a practice we want to encourage. Is Mobiscroll not a solution due to the price? If so, there may be free alternatives.

**Comment by henkjurriens** [comment] 2022-08-09 17:52
Thanks for your help!

**Comment by liamdebeasi** [comment] 2022-08-09 20:23
No problem. I am going to close this for now, but let me know if you have any additional questions.

**Closed by liamdebeasi** 2022-08-09 20:23 UTC
Labels: triage

**Comment by chvonrohr** [comment] 2022-08-11 06:51
We have the same feature request. 
Our case: We have an appointment booking showing available timeslots by day. for that, we load timeslots for the full month and show when selecting a day (and only activating dates with timeslots.
So on "month-change" we would like to load timeslots for that month and update activate days in the calendar. can we workaround this atm somehow?

**Comment by chvonrohr** [comment] 2022-08-12 07:11
I tried to come up with a workaround, but it's very annoying as that way, it's only possible to retrieve new month after a timeout (which is not fix with snap CSS):

```ts
 (this.datetimeComponent as any)?.el.addEventListener('click', (e: Event) => {
    setTimeout(() => {
      const firstButton = document
        .querySelector('ion-datetime')
        .shadowRoot.querySelector('.calendar-month:nth-of-type(2) button[data-day="1"]'); // find actual/center month

      if (firstButton) {
        const newViewMonth = padStart(`${+firstButton.getAttribute('data-month') + 1}`, 2, '0');
        const newViewDate = `${firstButton.getAttribute('data-year')}-${newViewMonth}-01`;
      }
    }, 550);
```

**Comment by liamdebeasi** [comment] 2022-08-12 13:09
Another workaround that uses `MutationObserver`:

```js
const observer = new MutationObserver((mutationRecords) => {
  if (mutationRecords) {
    window.dispatchEvent(new CustomEvent('datetimeMonthDidChange'));
  }
});
const initDatetimeChangeEvent = () => {
  observer.observe(document.querySelector('ion-datetime').shadowRoot.querySelector('.calendar-body'), {
    subtree: true,
    childList: true
  });
}
```

**Comment by chvonrohr** [comment] 2022-08-12 14:02
@liamdebeasi thanks for that hint - also works for getting informed about the event (so replaces the click listeners).
Though, is it somehow possible to determine the new month? I tried from the mutation records, but it's a lot going on there. Maybe you - with "under the hood"-knowledge have some idea?

**Comment by liamdebeasi** [comment] 2022-08-12 14:11
You can probably grab the information from the `.calendar-header` element. That should read something like "August 2022".

If you are looking for the raw numeric month, then you can get the `data-month` from one of the day elements inside of `.calendar-month`. Note that our months are one indexed unlike JS Date (example: month 8 is August not September)

**Comment by chvonrohr** [comment] 2022-08-12 14:19
@liamdebeasi nice idea 😎 
what I'm struggling a bit:

- taking from `.calendar-header` -> means converting text (possibly from different languages) to a date
- taking from `.calendar-month -> which one is active?

in both cases, I'd like to load data, before the animation is finished. otherwise its 500ms + network request...
any ideas? otherwise I'll try to investigate a bit.

**Comment by liamdebeasi** [comment] 2022-08-12 14:21
We render 3 `.calendar-month` elements for performance reasons:

0th index: previous month
1st index: current/active month
2nd index: next month

As long as you grab the 1st indexed month element, you should be able to get the correct raw data.

**Comment by chvonrohr** [comment] 2022-08-12 15:32
ok, so in this case we would again need to know from the event in which direction we are heading and be tedious to make this work also for the month dropdown selection.

I tried a few things with the mutation records. As they appear to be updated once they arrive in the mutator, I can search for the middle month. It's not too easy though and an output would be very welcome 😄.

So my solution for now:

```ts
// as you proposed initialising a MutationObserver, but adding mutationRecords to the event details
const observer = new MutationObserver((mutationRecords) => {
  if (mutationRecords) {
    window.dispatchEvent(new CustomEvent('datetimeMonthDidChange', { detail: mutationRecords }));
  }
});

observer.observe(
  document
    .querySelector('mia-doctor-appoinment-arzthaus-timeslot ion-datetime')
    .shadowRoot.querySelector('.calendar-body'),
  {
    subtree: true,
    childList: true,
  }
);
```

then from the event, we derive the "middle-month"

```ts
window.addEventListener('datetimeMonthDidChange', (ev) => {
      // get month-targets from all mutations
      const mutatedMonths = (ev as CustomEvent<MutationRecord[]>).detail?.filter((n) =>
        (n.target as Element).classList.contains('calendar-month-grid')
      );

      // find unique month/years
      let months: { month: number; year: number }[] = Array.from(mutatedMonths).reduce((a, monthMutation) => {
        const thisMonth = Array.from(monthMutation.target?.childNodes).find((n) => (n as any)?.dataset?.day === '1');
        const { month, year } = (thisMonth as any).dataset;
        if (a.find((n) => n.month === month && n.year === year)) return a;
        return [...a, { month, year }];
      }, []);

      // we search the middle month
      months = months.sort((a, b) => (a.year === b.year ? a.month - b.month : a.year - b.year));
      const activeMonth = months.length > 2 ? months[1] : null;
});
```
