### ISSUE TITLE
feat: Add ability to select specific weekdays for <ion-datetime>.

### ISSUE THREAD

**Issue by joshangehr** [ionic-team/ionic-framework#24556] opened 2022-01-11 20:12 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Add a new `weekDays` property to the `<ion-datetime>` component that allows users to include specific weekdays as selectable days.

### Describe the Use Case

The `<ion-datetime>` component does not currently provide a way to select or deselect calendar weekdays from its interface. This feature would solve this problem by allowing users to choose and allow specific calendar weekdays that should be selectable within its interface `[ Monday, Tuesday, Thursday ]`.

Example:

> I run an office providing therapy six days a week—the office is closed on Tuesdays. I'd like to let people make their own appointments, but they should not be able to make any appointments on Tuesdays.

### Describe Preferred Solution

Add a new `weekDays` property that accepts an array of weekdays (or whatever value is easiest to work with) as a value.

Currently, there exists an option for `dayValues`, but this option loses its utility a bit when viewing multiple months. For example, if a provider is looking to blacklist any appointments from being made on Tuesdays, they currently have no way of doing so easily.

### Describe Alternatives

**Alternative 1**

An alternative would be to fire an event when the month is changed—this is actually what I was looking into latching onto to begin with, but no event is fired. If there were an event fired on the month change, we could recalculate the day numbers that should be blacklisted based on the month.

Example:

> I toggle forward to July from June and listen for that event. When that event fires, I can retrieve the month and make sure that I get the `dayValues` for all Tuesdays in that month. I can then pass all numbers—other than the Tuesdays—to the existing `dayValues` property.

This may be a solution with less side effects or complications than the Preferred Solution.

**Alternative 2**

Another alternative would be to provide access to a shadow part that would enable disabling certain days based on CSS. For example, the entire issue could be resolved if adding disabled styles to a selector like `[data-day-of-week="6"]` were possible.

**Comment by liamdebeasi** [comment] 2022-01-12 16:00
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/24207.

**Closed by liamdebeasi** 2022-01-12 16:00 UTC
Labels: triage
