### ISSUE TITLE
bug: app.component.html:1 ERROR NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

### ISSUE THREAD

**Issue by scotch83** [ionic-team/ionic-framework#29848] opened 2024-09-08 14:38 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/docs/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v8.x

### Current Behavior

When creating a new app using the CLI, using **angular standalone**, run npm start, nothing is shown in the browser and the console shows this error:

```
core.mjs:7397 ERROR NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at addStyle (index.js:858:34)
    at attachStyles (index.js:887:20)
    at index.js:1705:5
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (asyncToGenerator.js:3:1)
    at _next (asyncToGenerator.js:17:1)
    at asyncToGenerator.js:22:1
    at new ZoneAwarePromise (zone.js:2702:25)
    at asyncToGenerator.js:14:1
    at updateComponent (index.js:1699:20)
```
## Further investigation
1. removing all the html generated code does not show the error.
2. removing only the ion-app shows the error but also show the page

It feels like there is something wrong in the IonApp component

### Expected Behavior

The app is shown in the browser and no error appears in the console

### Steps to Reproduce

1. run `ionic start test-app`
2. run `npm start` from the app root directory
3. open the browser and navigate to `localhost:4200` (nothing appears, only a black screen)
4. open also the console pressing F12 to see the error

### Code Reproduction URL

https://stackblitz.com/~/github.com/scotch83/test-ionic-angular-standalone

### Ionic Info

**ionic info**
[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package.json'
       
       Require stack:
       - /Users/scotch-83/.nvm/versions/node/v22.6.0/lib/node_modules/@ionic/cli/lib/project/index.js
       - /Users/scotch-83/.nvm/versions/node/v22.6.0/lib/node_modules/@ionic/cli/lib/index.js
       - /Users/scotch-83/.nvm/versions/node/v22.6.0/lib/node_modules/@ionic/cli/index.js
       - /Users/scotch-83/.nvm/versions/node/v22.6.0/lib/node_modules/@ionic/cli/bin/ionic
[WARN] Error loading @capacitor/android package.json: Error: Cannot find module '@capacitor/android/package.json'
       
       Require stack:
       - /Users/scotch-83/.nvm/versions/node/v22.6.0/lib/node_modules/@ionic/cli/lib/project/index.js
       - /Users/scotch-83/.nvm/versions/node/v22.6.0/lib/node_modules/@ionic/cli/lib/index.js
       - /Users/scotch-83/.nvm/versions/node/v22.6.0/lib/node_modules/@ionic/cli/index.js
       - /Users/scotch-83/.nvm/versions/node/v22.6.0/lib/node_modules/@ionic/cli/bin/ionic

Ionic:

   Ionic CLI                     : 7.2.0 (/Users/scotch-83/.nvm/versions/node/v22.6.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 8.3.0
   @angular-devkit/build-angular : 18.2.3
   @angular-devkit/schematics    : 18.2.3
   @angular/cli                  : 18.2.3
   @ionic/angular-toolkit        : 11.0.1

Capacitor:

   Capacitor CLI      : 6.1.2
   @capacitor/android : not installed
   @capacitor/core    : 6.1.2
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 2.0.1

System:

   NodeJS : v22.6.0 (/Users/scotch-83/.nvm/versions/node/v22.6.0/bin/node)
   npm    : 10.8.2
   OS     : macOS Unknown

### Additional Information

Ionic info did not find information about my mac:

MacOS Sonoma 14.5

Chip: Apple Silicon M2 Pro

**Comment by TangierDreams** [comment] 2024-09-09 15:40
I'm having the same problem with my app in Ionic/Angular. It only happens when I run my app in Chrome. If I run it in Firefox it works without error. No idea what's happening.

**Comment by brandyscarney** [comment] 2024-09-09 19:34
Thank you for the issue! I was unable to reproduce this with the same versions listed in `ionic info`. I created a new app using the Angular standalone list starter.

Your `ionic info` says `8.3.0` but the StackBlitz example is using `8.0.0`. Could you please try to update this version and verify that you are still seeing the problem? 

This error should've been resolved by `@stencil/core@4.19.2` and Ionic Framework [v8.2.5](https://github.com/ionic-team/ionic-framework/releases/tag/v8.2.5): https://github.com/ionic-team/ionic-framework/issues/29681#issuecomment-2206400149

**Comment by scotch83** [comment] 2024-09-10 10:37
I did update the version on the stackblitz but maybe it is worth considering the other user saying this is happening only in Chrome. This is an issue happening in both versions of Angular Ionic (8.0.0 and 8.3.0) consider also marking packages in `package.json` with `^` normally will install [the latest compatible version based on semver](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#dependencies), so anything between >=8.0.0 and <9.0.0


> Thank you for the issue! I was unable to reproduce this with the same versions listed in `ionic info`. I created a new app using the Angular standalone list starter.
> 
> Your `ionic info` says `8.3.0` but the StackBlitz example is using `8.0.0`. Could you please try to update this version and verify that you are still seeing the problem?
> 
> This error should've been resolved by `@stencil/core@4.19.2` and Ionic Framework [v8.2.5](https://github.com/ionic-team/ionic-framework/releases/tag/v8.2.5): [#29681 (comment)](https://github.com/ionic-team/ionic-framework/issues/29681#issuecomment-2206400149)

**Comment by scotch83** [comment] 2024-09-10 10:40
on safari npm start is failing and not running the app 🤔

**Comment by JayTailor45** [comment] 2024-09-10 13:40
I can verify that I face the same issue with Chrome. For Brave and Safari, it is working for me.

**Comment by tanner-reits** [comment] 2024-09-10 21:11
Hey all, I'm also not having any luck reproducing the issue. I spun up a new app using the Ionic CLI and tested in Chrome, Safari, and Firefox. Also checked out the Stackblitz repro in each browser.

**Comment by deny-joefakri** [comment] 2024-09-12 09:51
I’m experiencing the same issue and would like to know if there has been any progress or solution to this. Could you please provide an update?

**Comment by tanner-reits** [comment] 2024-09-13 20:17
Hey again everyone, I've created a dev build of Ionic using a build of Stencil with the change @masonicboom had suggested. This is kind of a shot in the dark as I still haven't been able to reproduce the issue with Ionic, but thought we'd give it a shot. If anyone can install the build and let us know if that resolves the issue, that would be awesome! The versions are as follows:

```
@ionic/core@8.3.1-dev.11726258029.1014159b
@ionic/react@8.3.1-dev.11726258029.1014159b
@ionic/angular@8.3.1-dev.11726258029.1014159b
@ionic/vue@8.3.1-dev.11726258029.1014159b
```

**Comment by scotch83** [comment] 2024-09-16 21:36
unfortunately I try with the builds you have released for testing and yet it doesn't work. 
It is so strange that this is happening only on my side and you cannot reproduce it, to me it happens all the times with the repo I have added here, I can consistently reproduce it. I am available for screen sharing and investigation if you want, but can't do more than this. I figure out there is something wrong with the stencil library but I could not really find out what.

**Comment by tanner-reits** [comment] 2024-09-17 15:34
Hey all. We've reverted the version of Stencil used in the [v8.2.9](https://github.com/ionic-team/ionic-framework/releases/tag/v8.2.9) and [v8.3.1](https://github.com/ionic-team/ionic-framework/releases/tag/v8.3.1) releases of Ionic Framework as a temporary solution to this issue until we can investigate further.

**Closed** 2024-09-24 21:15 UTC
Labels: triage
