### ISSUE TITLE
bug: ion-select doesn't display selected value if ion-select-option array if filled asynchornously

### ISSUE THREAD

**Issue by MaximS** [ionic-team/ionic-framework#22748] opened 2021-01-08 16:27 UTC
**Ionic version:**
[x] **5.x** (in Angular 11 project)

**Current behavior:**
1. I set a value for `<ion-select>`, for example using Angular's reactive forms `setValue` (or patchValue), while an array for `<ion-select-option>` is empty. 
2. The `<ion-select-option>` array if filled asynchornously
3. `<ion-select>` does not display its current value

(If I fill an array of <ion-select-option> before setting current value then everything is fine)

**Expected behavior:**
`<ion-select>` should rerender itself when `<ion-select-option>` array if filled - to display already set current value. So it shoud not depend on the sequence of events: "current value is set" and "options array is filled"

**Steps to reproduce:**
See demo at [stackblitz](https://stackblitz.com/edit/ionic-5-angular-10-start-template-uqfjnh?file=src%2Fapp%2Faddress-dialog%2Faddress-dialog.component.ts). See the second part with the "Click me" button to open a dialog.
Note, the demo reflects workaround behavior (see below). To see a problem comment lines 87-89 (with `combineLatest`) and uncomment line 93 with `this.addressForm.patchValue(this.address)`

Let's assume I have three ovservables for three `<ion-select>` options:

```
  types: Observable<AddressType[]>;
  roles: Observable<AddressRole[]>;
  states: Observable<AddressState[]>;
```
Then in template I have something like (for each of them)

```
        <ion-select formControlName="type">
          <ion-select-option *ngFor="let t of types | async" [value]="t.id">{{ t.name }}</ion-select-option>
        </ion-select>
```
In `ngOnInit` I have all this observables set up correctly.
Then I set a current value for `<ion-select>` using `this.addressForm.patchValue(this.address)`.
It appears that the current value is set before the values for `<ion-select-option>` are returned from observables - they are subscribed from a template `async` `pipes` but has not emmited any value. And since there is no options at this moment, the component doesn't display any current value at all. And when options come from observable the component doesn't try to match its current value against them.

Current workaround is 
```
    combineLatest([this.types, this.roles, this.states])
      .pipe(first())
      .subscribe(() => this.addressForm.patchValue(this.address))
```
But it's not convenient at all.

**Comment by liamdebeasi** [comment] 2021-01-08 16:46
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/19324.

**Closed by liamdebeasi** 2021-01-08 16:46 UTC
Labels: triage
