### ISSUE TITLE
bug: Ion-nav throws error when using input signals

### ISSUE THREAD

**Issue by OwenKelvin** [ionic-team/ionic-framework#29555] opened 2024-05-27 13:39 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/docs/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v8.x

### Current Behavior

An error is thrown in the console and input is not set

> ERROR TypeError: ctx.myProp is not a function
    at NavLinksComponent_Template (nav-links.component.html:4:7)
    at executeTemplate (core.mjs:11458:9)
    at refreshView (core.mjs:13000:13)
    at detectChangesInView (core.mjs:13231:9)
    at detectChangesInViewIfAttached (core.mjs:13191:5)
    at detectChangesInComponent (core.mjs:13180:5)
    at detectChangesInChildComponents (core.mjs:13244:9)
    at refreshView (core.mjs:13054:13)
    at detectChangesInView (core.mjs:13231:9)
    at detectChangesInViewWhileDirty (core.mjs:12929:9)

### Expected Behavior

Component should load without any errors

### Steps to Reproduce

Declare an input as an input signal

```ts

export class MyComponent {
 myProps = input('In Component Two');
 }
```

In another component add an `ion-nav-link`

```html
 <ion-nav-link router-direction="forward" [component]="component" [componentProps]="{myProps: 'Transfered data'}">
```

Observe console when someone is trying to navigate

### Code Reproduction URL

https://stackblitz.com/edit/angular-gvxypx

### Ionic Info

Ionic CLI : 7.2.0 (/Users/owen/.nvm/versions/node/v20.11.1/lib/node_modules/@ionic/cli)
Ionic Framework : @ionic/angular 8.2.0
@angular-devkit/build-angular : 18.0.0
@angular-devkit/schematics : 18.0.0
@angular/cli : 18.0.0

**Comment by thetaPC** [comment] 2024-06-12 20:42
Thank you for submitting the issue!

Discussed this with the team and we found a few issues that need to be corrected for input signals to work.

1. In order to use the signals API with `ion-nav` child components, you need to enable the flag in `main.ts`:

```
provideIonicAngular({ useSetInputAPI: true }),
```

2.  All child components that have attached `componentProps` need to have an `@Input()` or `input` class member for those props. In your case, `page-three.component.ts` should be updated to have:

```
export class PageThreeComponent {
  myProps = input();
}
```

3.  There is a typo in `example.component.html` where it is assigning `rootParams` to `myProp` not `myProps.`:

```
[rootParams]="{ myProps: 'From Root' }"
``` 

There's a [working reproduction](https://stackblitz.com/edit/angular-gvxypx-o7hbdu?file=src%2Fmain.ts) that includes all this corrections if you would like to fork it. Be advised that this StackBlitz workspace may not exist in the future.

I'll be closing this issue since the above steps provide the solution.

**Closed by thetaPC** 2024-06-12 20:42 UTC
Labels: triage
