### ISSUE TITLE
bug: ion-progress-bar uses ARIA incorrectly

### ISSUE THREAD

**Issue by iBobik** [ionic-team/ionic-framework#27801] opened 2023-07-14 15:33 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Currently it renders aria-valuenow between 0-1, but [spec](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/roles/progressbar_role) requires decimal value, so reader will say only 0 at the start and 1 at the end, nothing between.

```
<ion-progress-bar data-v-cf57d396="" class="md progress-bar-determinate" role="progressbar" aria-valuenow="0.08562491100541822" aria-valuemin="0" aria-valuemax="1"></ion-progress-bar>
```

### Expected Behavior

It should just multiply all attributes by 100 and round valuenow:

```
<ion-progress-bar data-v-cf57d396="" class="md progress-bar-determinate" role="progressbar" aria-valuenow="8" aria-valuemin="0" aria-valuemax="100"></ion-progress-bar>
```

### Steps to Reproduce

1. <ion-progress-bar :value="0.08562491100541822" />
2. Let screen reader read it.

### Code Reproduction URL

https://ionicframework.com/docs/usage/v6/progress-bar/determinate/demo.html?ionic:mode=md

### Ionic Info

Ionic:

   Ionic CLI : 5.4.16

Utility:

   cordova-res : not installed
   native-run  : 1.7.2

System:

   NodeJS : v18.16.1
   npm    : 9.5.1
   OS     : macOS Unknown

**Comment by liamdebeasi** [comment] 2023-07-14 20:01
Thanks for the report. Can you clarify what the expected behavior is? If I am understanding the spec correctly, then Ionic's implementation is not wrong. According to https://w3c.github.io/aria/#aria-valuenow, `aria-valuenow` is a decimal, and assistive technologies should announce that value as a percent (i.e. `0.05` gets read as `5 percent`).

Ionic's implementation sets `aria-valuenow` to be the `value` property value: https://github.com/ionic-team/ionic-framework/blob/d5f4e0a49882b7ed09383465bef58677f6690f59/core/src/components/progress-bar/progress-bar.tsx#L65.

The demo you linked does set `value` (and therefore `aria-valuenow`) to a decimal. I also tested `ion-progress-bar` against the native [progress element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/progress) on both TalkBack and VoiceOver. The behavior of `ion-progress-bar` aligns with the native progress behavior.

When highlighting both `ion-progress-bar` and `<progress>`, VoiceOver first announced the decimal value and then the percentage value. TalkBack only announced the decimal value. However, neither continually read the value as the value updated. TalkBack did play a tone every time the value changed for both `ion-progress-bar` and `<progress>`.

**Comment by iBobik** [comment] 2023-07-14 20:34
Sorry, not decimal but integer. It does not read 0,05, but 5 with max on a 100, not 1.14. 7. 2023 v 22:02, Liam DeBeasi ***@***.***>:﻿
Thanks for the report. Can you clarify what the expected behavior is? If I am understanding the spec correctly, then Ionic's implementation is not wrong. According to https://w3c.github.io/aria/#aria-valuenow, aria-valuenow is a decimal, and assistive technologies should announce that value as a percent (i.e. 0.05 gets read as 5 percent).
Ionic's implementation sets aria-valuenow to be the value property value: https://github.com/ionic-team/ionic-framework/blob/d5f4e0a49882b7ed09383465bef58677f6690f59/core/src/components/progress-bar/progress-bar.tsx#L65.
The demo you linked does set value (and therefore aria-valuenow) to a decimal. I also tested ion-progress-bar against the native progress element on both TalkBack and VoiceOver. The behavior of ion-progress-bar aligns with the native progress behavior.
When highlighting both ion-progress-bar and <progress>, VoiceOver first announced the decimal value and then the percentage value. TalkBack only announced the decimal value. However, neither continually read the value as the value updated. TalkBack did play a tone every time the value changed for both ion-progress-bar and <progress>.

**Comment by liamdebeasi** [comment] 2023-07-14 21:09
> Sorry, not decimal but integer. It does not read 0,05, but 5 with max on a 100

Thanks for the clarification. However, it looks like `ion-progress-bar` is following the spec correctly by using decimal values. `ion-progress-bar` has a `aria-minvalue` of `0` and `aria-maxvalue` of `1`, so using a decimal value is correct since it respects the upper and lower bounds of the progress bar.

Can you clarify why you want the decimal to be read as an integer?

**Comment by iBobik** [comment] 2023-07-15 13:37
Min and max can be 0 and 1, but issue is with value - readers did not read anything between, so progress bar was useless for our blind tester.Sorry about specs, my mistake, I see it actually allows 0-1 range.Honza Pobořil💬Signal14. 7. 2023 v 23:09, Liam DeBeasi ***@***.***>:﻿

Sorry, not decimal but integer. It does not read 0,05, but 5 with max on a 100

Thanks for the clarification. However, it looks like ion-progress-bar is following the spec correctly by using decimal values. ion-progress-bar has a aria-minvalue of 0 and aria-maxvalue of 1, so using a decimal value is correct since it respects the upper and lower bounds of the progress bar.
Can you clarify why you want the decimal to be read as an integer?

**Comment by liamdebeasi** [comment] 2023-07-17 15:28
> Min and max can be 0 and 1, but issue is with value - readers did not read anything between, so progress bar was useless for our blind tester.

As I mentioned in https://github.com/ionic-team/ionic-framework/issues/27801#issuecomment-1636447186 Ionic is following the spec correctly. While I understand the reported behavior is not desired, this is a platform-level behavior and not something that Ionic can control. Android + TalkBack seems to provide tones as the value updates, though other platforms do not do that. I do think it would be valuable to have screen readers provide some kind of indication that the progress value has changed.

Ionic is working as intended here, so I am going to close this. However, this kind of feedback is very valuable to browser vendors so I think it's worth filing feedback. I'm not sure what platform you are testing on, but I've provided links to file feedback with browser vendors:

Webkit (Safari): https://bugs.webkit.org/
Gecko (Firefox): https://bugzilla.mozilla.org/home
Chromium (Chrome): https://bugs.chromium.org/p/chromium/issues/list

The MDN docs also provide recommendations for describing regions when the progress element is done loading: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/progress#describing_a_particular_region

**Closed by liamdebeasi** 2023-07-17 15:28 UTC
Labels: triage
