### ISSUE TITLE
bug: Ion Select does not open on production build

### ISSUE THREAD

**Issue by milanharia** [ionic-team/ionic-framework#24833] opened 2022-02-22 13:58 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

When tapping on an ion item that contains an ion select, the ion select overlay does not appear. This seems to have broken in v6.0.2 as it works fine in v6.0.1. 

https://user-images.githubusercontent.com/76167627/155145934-f20ea051-79fe-4e7f-a6c1-428a90ce6f30.mp4

### Expected Behavior

I expect the select overlay to appear when tapping on the item so that I can select one of the options.

### Steps to Reproduce

This issue occurs when running a production build on iOS and android on any version of ionic later than v6.0.1.

### Code Reproduction URL

- https://github.com/sean-perkins/gh-24833-ion-select

### Ionic Info

Ionic:

   Ionic CLI       : 6.18.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 6.0.8

Capacitor:

   Capacitor CLI      : 3.2.5
   @capacitor/android : 3.3.2
   @capacitor/core    : 3.2.5
   @capacitor/ios     : 3.2.5

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v16.13.0 (/usr/local/bin/node)
   npm    : 8.1.0
   OS     : macOS Monterey

**Comment by sean-perkins** [comment] 2022-02-22 15:52
@milanharia thanks for reporting this issue. I am able to reproduce locally. I've updated your issue with a link to a reproduction application.

Reproduction steps:
1. `npm run build`
2. Install `serve` globally or local to project
3. `serve -s build`
4. Open `http://localhost:3000/home`
5. Click on the select
6. See that the action sheet does not display.

**Comment by sean-perkins** [comment] 2022-02-22 15:56
Actually this looks like it's a duplicate of #24807 and has been resolved in this PR #24810. The fix will be available in the next release of Ionic.

**Closed by sean-perkins** 2022-02-22 15:56 UTC
Labels: package: react, type: bug
