### ISSUE TITLE
bug: ion-menu and ion-modal together

### ISSUE THREAD

**Issue by guilhermeagirardi** [ionic-team/ionic-framework#23979] opened 2021-09-24 13:15 UTC
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

For some reason, I can't use ion-menu and ion-modal together. When I click on the icon to open the menu, the ion-modal disappears. In addition to the ion-modal disappearing, from that moment on the menu behavior is strange, it no longer closes by dragging with the touch, it only closes by clicking on the outside.

### Expected Behavior

That ion-modal doesn't disappear when I use ion-menu and that ion-menu works correctly (drag-to-close effect).

### Steps to Reproduce

https://drive.google.com/file/d/17j1MMEjsOP4RPoQMtlOzoyVzf576a6Zq/view

### Code Reproduction URL

https://github.com/guilhermeagirardi/ionic-issue-code-reproduction

### Ionic Info

$ ionic info
[WARN] You are not in an Ionic project directory. Project context may be missing.

Ionic:

   Ionic CLI : 6.17.1

Utility:

   cordova-res : 0.15.3
   native-run  : 1.3.0

System:

   NodeJS : v14.17.6
   npm    : 7.16.0
   OS     : Windows 10

**Comment by liamdebeasi** [comment] 2021-09-24 14:50
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The problem here is that the `ion-modal` still has a backdrop even when using the sheet modal. Clicking the backdrop dismisses the modal by default. Given that your initial breakpoint is `0.05`, the backdrop will have an opacity of `5%` making it hard to see.

For this use case, you can use the `backdrop-breakpoint` property which determines the point after which the backdrop will become active. Setting `:backdrop-breakpoint="0.05"` means that the backdrop will begin to fade in starting at offset `0.06`.

More information can be found on the v6 docs: https://beta.ionicframework.com/docs/api/modal#sheet-modal

**Closed by liamdebeasi** 2021-09-24 14:50 UTC
Labels: triage

**Comment by guilhermeagirardi** [comment] 2021-09-24 15:25
Hello @liamdebeasi, thanks for the help!

Your note solved the problem of disappearing the ion-modal, but I still have the same problem in the ion-menu, I can't drag to close. Look:

https://drive.google.com/file/d/1uqmfZn-BwjzhbVvndK3FLT4DxB2gyjlZ/view

I don't know how to solve this problem.

**Comment by liamdebeasi** [comment] 2021-09-29 21:30
The issue here is that the sheet modal gesture has a higher priority than the menu gesture priority, so the modal gesture is always going to activate. I need to look and see if this is the intended behavior.

**Comment by guilhermeagirardi** [comment] 2021-09-30 01:20
I believe that's what it is. I tried to solve it but couldn't, at the moment I'm using https://github.com/roman-rr/cupertino-pane as an alternative.

**Comment by liamdebeasi** [comment] 2021-10-08 17:33
Going to reopen this. Two things need to happen here:

1. The `gesturePriority` values for the modal gestures need to be lower than the gesture for the menu.
2. We need to adjust this code: https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/menu/menu.tsx#L371

Currently, the menu gesture will not activate if there is an open modal. This is to prevent a swipe gesture on a modal from opening the menu underneath. However, with a partially opened sheet modal being able to open the menu may be a desired behavior.

Additionally, it looks like the menu gesture listens on `document` which might also cause some issues here: https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/menu/menu.tsx#L194

Changing the listening element from `document` to something more specific may remove the need for https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/menu/menu.tsx#L371, potentially allowing this to work without any additional effort.

**Comment by guilhermeagirardi** [comment] 2021-10-11 17:45
Perfect @liamdebeasi, thanks for your efforts.

I really don't understand and I don't have enough knowledge to resolve this issue, internally. But I'm available for whatever it takes.

🤝

**Comment by I-am-abdulazeez** [comment] 2022-01-20 10:34
Hi, @liamdebeasi is there any fix for this yet, having the same problem
