### ISSUE TITLE
bug: Warning: Unknown event handler property `onIonTabsWillChange`. It will be ignored.

### ISSUE THREAD

**Issue by bartoszgolebiowski** [ionic-team/ionic-framework#22040] opened 2020-09-06 21:21 UTC
I got a warning but it works.
```
  return (
    <IonTabs onIonTabsWillChange={(e) => onChange(e.detail.tab)}>
      <IonRouterOutlet>
        {tabNames.map((tab) => (
          <Route key={tab} path={`/${tab}`} render={() => <></>} />
        ))}
      </IonRouterOutlet>
      <IonTabBar
        style={{ heigth: "56px" }}
        slot="bottom"
        selectedTab={selected}
      >
        {children}
      </IonTabBar>
    </IonTabs>
  );
```

![image](https://user-images.githubusercontent.com/39523638/92335458-6006ae80-f097-11ea-9717-f9bf8ca8e238.png)
```
{
  "name": "ionic",
  "version": "0.0.1",
  "private": true,
  "dependencies": {
    "@capacitor/android": "^2.4.0",
    "@capacitor/core": "2.4.0",
    "@capacitor/ios": "^2.4.0",
    "@ionic/react": "^5.0.7",
    "@ionic/react-router": "^5.0.7",
    "ionicons": "^5.0.0",
    "react": "^16.13.0",
    "react-dom": "^16.13.0",
    "react-router": "^5.1.2",
    "react-router-dom": "^5.1.2"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@capacitor/cli": "2.4.0",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.4.0",
    "@testing-library/user-event": "^8.0.3",
    "@types/jest": "^24.0.25",
    "@types/node": "^12.12.24",
    "@types/react": "^16.9.17",
    "@types/react-dom": "^16.9.4",
    "@types/react-router": "^5.1.4",
    "@types/react-router-dom": "^5.1.3",
    "react-scripts": "3.4.0",
    "typescript": "3.8.3"
  },
  "description": "An Ionic project"
}
```

**Comment by bartoszgolebiowski** [comment] 2020-09-14 20:33
https://github.com/bartoszgolebiowski/ionic/tree/slide-bars-routing

**Comment by liamdebeasi** [comment] 2020-10-01 22:59
Thanks! Looks like this is a duplicate of https://github.com/ionic-team/ionic-framework/issues/21827.

**Closed by liamdebeasi** 2020-10-01 22:59 UTC
Labels: needs: investigation, package: react
