### ISSUE TITLE
bug: On setting route query param ionic makes everything hidden.

### ISSUE THREAD

**Issue by stripathix** [ionic-team/ionic-framework#22229] opened 2020-10-01 19:25 UTC
# Bug Report

**Ionic version:**
```
 "dependencies": {
    "@ionic/vue": "0.5.0",
    "@ionic/vue-router": "0.5.0",
    "core-js": "^3.6.5",
    "vue": "^3.0.0-0",
    "vue-router": "^4.0.0-0"
  },
```

**Current behavior:**
When we set query param from a method the ionic makes the whole screen blank.
```
setRouteQuery() {
      const queryParam = {
        workshopdirectory: 'test',
        workshopid: 'test2',
        title: 'test3',
      };
      this.$router.push({ query: queryParam });
    },
```

**Expected behavior:**
When was using vue2 then it was just working fine. Looks like there is hidden class added.
<img width="431" alt="Screenshot 2020-10-02 at 12 53 54 AM" src="https://user-images.githubusercontent.com/8480351/94853951-c76f0e80-0449-11eb-9aa4-7879c26a1a14.png">

**Steps to reproduce:**
Use this GitHub repository https://github.com/stripathix/ionic-modal-issue/tree/master/my-app
From tab1 click on "Set Route Param" button. Then the screen goes blank

**Related code:**
https://github.com/stripathix/ionic-modal-issue/tree/master/my-app

**Comment by liamdebeasi** [comment] 2020-10-05 19:29
Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue?

```
npm install @ionic/vue@0.6.0-dev.202010051922.f5d657c @ionic/vue-router@0.6.0-dev.202010051922.f5d657c
```

**Comment by liamdebeasi** [comment] 2020-10-06 18:13
I have merged in a fix for this here: https://github.com/ionic-team/ionic-framework/pull/22253. I am going to close this issue, but please let me know if you run into any issues!

**Closed by liamdebeasi** 2020-10-06 18:13 UTC
Labels: package: vue, type: bug

**Comment by stripathix** [comment] 2020-10-07 18:22
Thank @liamdebeasi  for fixing it. It works :-). Sorry for the late reply was not well.

**Comment by liamdebeasi** [comment] 2020-10-07 18:23
Glad to hear the issue is resolved. Hope you are feeling better!
