### ISSUE TITLE
bug: ios safari swipe back transition Execution is messed up

### ISSUE THREAD

**Issue by d1y** [ionic-team/ionic-framework#25819] opened 2022-08-25 06:14 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

The `@ionic/vue` I used, iOS Safari returns to the previous page, and the animation will be executed again

### Expected Behavior

Return to the previous page. The animation will only be triggered once 😂

### Steps to Reproduce

https://user-images.githubusercontent.com/45585937/186583853-a35d2a64-0b42-4807-ab4b-379d5873982f.mov

### Ionic Info

Our project is running on the web, no cross platform code is used

```
[WARN] You are not in an Ionic project directory. Project context may be missing.

Ionic:

   Ionic CLI : 6.20.1

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v16.16.0
   npm    : 8.11.0
   OS     : macOS Monterey

```

### Additional Information

> the `main.ts` file

```ts
app.use(IonicVue, {
  mode: "md",
})

app.use(router)
router.isReady().then(() => {
  app.mount("#app")
})
```

> the `router.ts` file

```ts
const router = createRouter({
  history: createWebHashHistory('/'),
  routes: [] // !!ignore the line
})

export default router

```

I don't know what happened, but I know that this seems to be Safari's default behavior (sliding left and right) 🧐

**Comment by liamdebeasi** [comment] 2022-08-25 13:00
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. When you navigate back in an Ionic app, we will play the page leaving transition. What is happening here is you are triggering the native iOS swipe to go back transition. Since you are also going back, the Ionic page transition will play as well.

Unfortunately, we are not aware of a reliable way to suppress this built-in swipe back gesture. There is a related issue here: https://github.com/ionic-team/ionic-framework/issues/22299. I proposed a new feature to the Web Manifest working group that should resolve this issue at least when running apps as a PWA: https://github.com/w3c/manifest/issues/1041.

While I understand this may not be the desired result, Ionic is working as intended here. Other developers have discussed workarounds in #22299 that you may fine valuable for your use case. Thanks for the report!

**Closed by liamdebeasi** 2022-08-25 13:00 UTC
Labels: triage

**Comment by liamdebeasi** [comment] 2022-08-25 20:39
You could certainly disable animations in Ionic. That may be the best path forward so that the swipe to go back gesture on iOS does not interfere with Ionic.

**Comment by liamdebeasi** [comment] 2022-08-26 13:36
The [Ionic Vue Configuration Documentation](https://ionicframework.com/docs/vue/config) shows you how to disable animations globally. The [Router Outlet animated property](https://ionicframework.com/docs/api/router-outlet#properties) goes over how to disable only page transitions.

**Comment by liamdebeasi** [comment] 2022-08-26 14:32
I don't have access to the code, so it is hard to say what the issue is. There may be a delay of a few frames when swapping out active/inactive pages.
