### ISSUE TITLE
Back button only read first occurrence of router

### ISSUE THREAD

**Issue by 3adeling** [ionic-team/ionic-framework#18569] opened 2019-06-18 14:16 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

In a fresh ionic tabs project, when navigating forward in the app using routerLink.. once the same router is visited, for the second time, the back button will only the see the first occurrence in the navigation stack

Ex: tab1 > page1 > page2>page3>page2  
now when the user click the hardware back button or the <ion-back-button> it will go to page1 instead of page3

**Expected behavior:**

back button should redirect user to the previous page which is page 3 in the previous example

**Steps to reproduce:**

1. create new ionic 4 project with tabs template
2. create pages: page1, page2, page3
3. add button in:
- tab1 redirecting to page1
- page1 redirecting to page2
- page2 redirecting to page3
- page3 redirecting to page2
4. run project
5. now click one all buttons untill you click on the button in page3.
6. now click on back button (hardware or <ion-back-button>)
7. page1 will be shown instead in page3

**Related code:**
please see:
https://github.com/3adeling/navigation-issue

**Other information:**

**Ionic info:**

**Comment by liamdebeasi** [comment] 2019-06-19 13:23
Hi there,

Thanks for the issue! Can you clarify the issue you are seeing? 

I am seeing the following behavior:

Start on Tab 1, click button to Page 1
On Page 1, click button to Page 2
On Page 2, click button to Page 3
On Page 3, click button to Page 1
On Page 1, click back button
Redirected to Page 3

This appears to be the correct behavior, so I am interested in finding out how to reproduce the behavior you are reporting.

Thanks!

**Comment by 3adeling** [comment] 2019-06-19 15:13
Are you using chrome back button?! please don't because it works fine.

The issue is happening when using both the **ion-back-button** in the header OR the **device back button**

**Comment by liamdebeasi** [comment] 2019-06-26 13:25
Thanks for the follow up! I am able to reproduce this.

At first glance, it looks like the framework is trying to re-use the `Page 1` component, including its navigation state.

We will look into this!

**Comment by liamdebeasi** [comment] 2024-02-28 22:59
Hi everyone,

Apologies for the delay. Upon further investigation, Ionic is working as intended here. The router integration in Ionic has a behavior where views are automatically reused.

For example, consider a scenario where a user has entered their email on `/page-2`. They then navigate to `/page-3`. From there, they click a button that pushes the app to `/page-2`. Normally, this would create a new instance of `/page-2`. However, this is confusing for the user because it looks like they went back to the first instance of `/page-2` and lost the data they input.

Ionic tries to account for this by re-using the original `/page-a` instance. In other words, the behavior here is the same as doing tab1 > page1 > page2 > page3 > go back.

While Ionic is working as intended here, we realize this behavior may be unexpected in some scenarios. The team has plans to improve this behavior so developers have more control over when views are reused. I am going to close this for now, but let me know if you have any questions.

**Closed by liamdebeasi** 2024-02-28 22:59 UTC
Labels: package: angular, type: bug
