### ISSUE TITLE
bug: "CustomElements not defined" while executing the unit tests.

### ISSUE THREAD

**Issue by anantsharma1310** [ionic-team/ionic-framework#24149] opened 2021-11-02 12:02 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

We were executing our unit tests using Mocha test runner but after importing `@ionic/react` (version: 5.8.4) in our components, mocha started to throw error before getting to any test case. Everything else is working fine on web and IOS/Android devices, but we are not able to get a workaround for our unit tests. We have debugged ourselves and we like to share our findings. `customElements` is a method available in a window object. Since we are using a `jsdom`, we do get `window.customElements` in our test cases. However, in ionic code, we found that there was a piece of code which is accessing `customElements` method using `window` in `if` condition and inside `if` block, it is using `this` reference to access customElements method which will definitely throw an error since `this` is not equal to `window` in the test runner env.
Attaching the buggy code, we can also post a PR for the fix if it's too much work but if possible, please expedite it.

Thank you

```
if (typeof window !== 'undefined' && window.customElements) {
    const element = customElements.get('ion-tabs'); // should be window.customElements
    if (!element) {
        customElements.define('ion-tabs', IonTabsElement); / should be window.customElements
    }
}
```

### Expected Behavior

Should execute in test env as well.

### Steps to Reproduce

You can use any test runner to run any dummy test case, it should throw an error right if you are testing component has imported `@ionic/react`. 

### Ionic Info

@ionic/react":  5.8.4
jsdom: 16.6.0
mocha: 8.4.0

**Comment by anantsharma1310** [comment] 2021-11-03 02:53
[](https://github.com/ionic-team/ionic-framework/pull/24156)

**Comment by anantsharma1310** [comment] 2021-11-03 02:54
Submitted the pull request for the fix. Please take a look, these are the small changes but unblock us big time.

https://github.com/ionic-team/ionic-framework/pull/24156

Let us know if we still need to provide the code reproduction url.

**Comment by liamdebeasi** [comment] 2021-11-09 00:34
Hi there,

Yes, we still need a code reproduction so we can verify the fix. Can you please send over a GitHub repo?

**Comment by anantsharma1310** [comment] 2021-11-11 14:55
Hey

I appreciate your prompt response.
I have created a sample repo on Github with instructions to replicate the issue.

https://github.com/anantsharma1310/ionic-react-unit-test

Do let us know if you guys need something else.

Thank you

**Comment by liamdebeasi** [comment] 2021-11-15 22:47
Can you double check your repo? I get the following error when running `npm test`:

```
SyntaxError: /Users/liamdebeasi/Ionic/ionic-react-unit-test/src/App.test.js: Support for the experimental syntax 'jsx' isn't currently enabled (16:29):

  14 | describe("Testing <App/> Component", () => {
  15 |    it("App renders a message", () => {
> 16 |       const wrapper = mount(<App />);
     |                             ^
  17 |       expect(wrapper.find('p[data-testid="message"]')).to.be.exist;
  18 |    });
  19 | });

```

**Comment by rishu1702** [comment] 2021-11-16 11:40
Hey

I appreciate your prompt response.
I have made some changes on the repo please take the latest pull and follow the same steps again.


https://github.com/anantsharma1310/ionic-react-unit-test
Do let us know if you guys need something else.


Thankyou
________________________________

**Comment by liamdebeasi** [comment] 2021-11-16 15:16
Thanks! I can reproduce this behavior. This indeed looks like a bug.

**Comment by liamdebeasi** [comment] 2021-12-06 22:06
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/24156, and a fix will be available in an upcoming release of Ionic Framework. Thank you for the PR!

**Closed** 2021-12-06 22:06 UTC
Labels: package: react, type: bug
