### ISSUE TITLE
bug: ios header collapse refresh overlap

### ISSUE THREAD

**Issue by danielehrhardt** [ionic-team/ionic-framework#22565] opened 2020-11-25 17:35 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

![screen-capture](https://user-images.githubusercontent.com/19570043/100262900-179bb600-2f4d-11eb-9091-4eda8f11e06d.gif)
**Expected behavior:**

https://s3.amazonaws.com/ionicframework.com/videos/refresher-light.mov

**Steps to reproduce:**

https://stackblitz.com/edit/ionic-angular-v5-xllyvv

**Related code:**
```
<ion-app>
	<ion-header translucent="true">
		<ion-toolbar>
			<ion-buttons collapse="true" slot="end">
				<ion-button>Click Me</ion-button>
			</ion-buttons>
			<ion-title>Settings</ion-title>
		</ion-toolbar>
	</ion-header>

	<ion-content fullscreen="true">
		<ion-header collapse="condense">
			<ion-toolbar>
				<ion-buttons collapse="true" slot="end">
					<ion-button>Click Me</ion-button>
				</ion-buttons>
				<ion-title size="large">Settings</ion-title>
			</ion-toolbar>
			<ion-toolbar>
				<ion-searchbar></ion-searchbar>
			</ion-toolbar>
		</ion-header>
		<ion-refresher slot="fixed">
			<ion-refresher-content></ion-refresher-content>
		</ion-refresher>


	</ion-content>
</ion-app>
```

**Ionic info:**
Latest Version

**Comment by liamdebeasi** [comment] 2020-11-25 17:54
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/18714.

**Closed by liamdebeasi** 2020-11-25 17:54 UTC
Labels: triage
