### ISSUE TITLE
bug: Focus is not getting trapped in overlay components when screen reader is active

### ISSUE THREAD

**Issue by gurpreetonebcg** [ionic-team/ionic-framework#23053] opened 2021-03-16 13:00 UTC
# Focus is not getting trapped in overlay components when screen reader is active

**Ionic version:**
```
@ionic/angular 5.6.0
```

**Current behavior:**
Focus is not getting trapped in overlay components such as alert box, action sheets, date picker, select boxes, modals. if user keeps navigating in these overlay components focus will move out of them to the content present behind it.

**Expected behavior:**
it should be trapped within the overlay component.

**Steps to reproduce:**
Take the code from attached link or install .apk provide in attached link, start talk back screen reader open any overlay component from provided .apk, keep navigating with screen reader you will see focus moves behind the overlay component. Issue can be reproduecd for every overlay component added in provided code.
- Alerts
- Action sheet
- Modal
- Select box
- Select Popover
- Loader
- Date-time picker

[Download .apk here](https://drive.google.com/file/d/1IOanXH8NcaVeYhiTrfjEveQBrpMH8IhI/view?usp=sharing)

**Related code:**

[Downlead code here](https://drive.google.com/file/d/1TfR-9kxiYYeVQkr6WOEjHaSuN_ZIq9my/view?usp=sharing) 

**Other information:**

[Screen shorts of issues](https://drive.google.com/drive/folders/14dSf83tvbK34cY86Wuw-p3pkG8wUMetZ?usp=sharing)

This issue is causing some other issues as well
- User can navigate back even when user is restricted with alert popup
- User is able to open multiple overlay components at a time - [Screen Short](https://drive.google.com/file/d/12HLv3w5VtJSDwa8ghtJ0KqNHqA3elvZR/view?usp=sharing)

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.11.8
   Ionic Framework               : @ionic/angular 5.6.0
   @angular-devkit/build-angular : 0.1101.4
   @angular-devkit/schematics    : 11.1.4
   @angular/cli                  : 11.1.4
   @ionic/angular-toolkit        : 3.1.0

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : android 9.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 4 other plugins)

Utility:

   cordova-res : 0.11.0
   native-run  : 1.0.0
```

**Comment by gurpreetonebcg** [comment] 2021-04-02 09:02
Hi guys, Can we just get and quick update on this. This is an urgent for our app to met a11y guidelines.

**Comment by amandaesmith3** [comment] 2021-11-16 14:21
Thanks for the issue! I'm going to close this as a duplicate of your other post (https://github.com/ionic-team/ionic-framework/issues/23603) since there's already discussion on that thread. I'll investigate further and report back over there once I have more to share.

**Closed by amandaesmith3** 2021-11-16 14:21 UTC
Labels: triage
