### ISSUE TITLE
bug: ion-select showing multiple alert windows stacked on top of each other

### ISSUE THREAD

**Issue by zzjrzz** [ionic-team/ionic-framework#25126] opened 2022-04-14 00:35 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Immediately after loading a page, click on `ion-select` component in rapid successions. (spam click)
This will create multiple alert select windows. 

Video of behavior: 
<video src="https://user-images.githubusercontent.com/13732623/164767757-1dabadf3-b3ee-4a3e-bd4a-3cd4769a2f42.mp4"></video>

### Expected Behavior

I expect only one alert select window to appear.
If multiple are presented at once, the user is confused as they have to dismiss multiple windows.

### Steps to Reproduce

Clear all browser caches - load an application for the first time
IMMEDIATELY spam click the component
Happens on: https://ionicframework.com/docs/api/select

### Ionic Info

                          
[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module
       '@capacitor/ios/package'
       
       Require stack:
       -
       C:\Users\AppData\Roaming\nvm\v16.13.2\node_modules\@ionic\cli\lib\projec
t\index.js
       -
       C:\Users\AppData\Roaming\nvm\v16.13.2\node_modules\@ionic\cli\lib\index.
js
       - C:\Users\AppData\Roaming\nvm\v16.13.2\node_modules\@ionic\cli\index.js
       -
       C:\Users\AppData\Roaming\nvm\v16.13.2\node_modules\@ionic\cli\bin\ionic 
[WARN] Error loading @capacitor/android package.json: Error: Cannot find module
       '@capacitor/android/package'

       Require stack:
       -
       C:\Users\AppData\Roaming\nvm\v16.13.2\node_modules\@ionic\cli\lib\projec
t\index.js
       -
       C:\Users\AppData\Roaming\nvm\v16.13.2\node_modules\@ionic\cli\lib\index.
js
       - C:\Users\AppData\Roaming\nvm\v16.13.2\node_modules\@ionic\cli\index.js
       -
       C:\Users\AppData\Roaming\nvm\v16.13.2\node_modules\@ionic\cli\bin\ionic 

Ionic:

   Ionic CLI                     : 6.19.0 (C:\Users\AppData\Roaming\nvm\v16.13.
2\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.0.9
   @angular-devkit/build-angular : 13.0.4
   @angular-devkit/schematics    : 13.0.4
   @angular/cli                  : 13.0.4
   @ionic/angular-toolkit        : 5.0.3

Capacitor:

   Capacitor CLI      : 3.4.1
   @capacitor/android : not installed
   @capacitor/core    : 3.4.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v16.13.2 (C:\Program Files\nodejs\node.exe)
   npm    : 8.1.2
   OS     : Windows 10

**Comment by sean-perkins** [comment] 2022-04-22 17:51
Thanks for reporting this issue!

From our discord conversation, I think the likely culprit is here:

https://github.com/ionic-team/ionic-framework/blob/a6a772a38d15419ad4a60b6afeb66d91f6736934/core/src/components/select/select.tsx#L191-L192

We are setting `isExpanded` internally, after the overlay is opened, but this means you could open multiple windows in the duration of that function call.

I think we likely just need to switch these lines. I'll get a dev build for you to test with.

**Comment by sean-perkins** [comment] 2022-04-22 18:11
Can you test with this dev build:
```
6.1.3-dev.11650650446.100eff34
```

I locally confirmed that with the dev build, calling the `.click()` method manually multiple times in quick succession will only open a single alert window.

**Comment by zzjrzz** [comment] 2022-04-23 07:47
Thanks for the fix, will test it in the coming days.
Am I okay to close the issue if resolved?

**Comment by sean-perkins** [comment] 2022-04-24 23:48
@zzjrzz you can leave the issue open, it will automatically be closed when the PR that resolves the issue is merged into `main`. 

Our process is typically:
- Triage/verify issue
- Create a dev build for the reporter to verify
- PR is opened for the dev team to review
- Reporter will verify the dev build, if available
- PR is merged and issue is closed

**Closed** 2022-04-26 01:36 UTC
Labels: package: core, type: bug
