### ISSUE TITLE
bug: wrong navigation animation applied

### ISSUE THREAD

**Issue by JustasKuizinas** [ionic-team/ionic-framework#18079] opened 2019-04-19 10:22 UTC
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
I am using only routerLink to navigate between pages.
For example I Have pageA and pageB.
From pageA I navigate to pageB, forward animation appears.
Then from pageB I try to navigate to pageA, as pageA is already in the cache ionic doesnt push new page but uses cached version, the problem is that then wrong navigation animation is applied and it confuses user.

**Expected behavior:**
Ionic should automatically apply correct animation, for my example ionic should apply back animation not forward.

**Steps to reproduce:**
1. checkout https://github.com/JustasKuizinas/ionic-blank
2. npm install & ionic serve
3. press button 'CONTACT', correct navigation animation appears.
4. press button 'HOME, wrong animation, it should be backward not forward

**Related code:**
https://github.com/JustasKuizinas/ionic-blank

**Ionic info:**
```
Ionic:
   ionic (Ionic CLI)             : 4.12.0 (C:\Users\JK\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.3.0
   @angular-devkit/build-angular : 0.13.8
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.8
   @ionic/angular-toolkit        : 1.4.1

System:

   NodeJS : v11.11.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.9.0
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment] 2024-01-05 19:11
Thanks for the report and apologies for the delay. I took a closer look at this issue. Going from A --> B, and then pushing A in the forward direction should re-use the previous instance of component A. Since your application is pushing a view, the forward animation is used. I do think this behavior could be improved and made clearer for developers. The team has plans to improve this in the future, but for now I am going to close this because Ionic is working as intended.

In terms of an alternative strategy, you can manually override the direction:

```html
<ion-button routerLink="/home" routerDirection="back">Back to home</ion-button>
```

Let me know if you have any questions.

**Closed by liamdebeasi** 2024-01-05 19:11 UTC
Labels: package: angular, type: bug
