### ISSUE TITLE
ion-back-button defaultTransition

### ISSUE THREAD

**Issue by TylerAHolden** [ionic-team/ionic-framework#17053] opened 2019-01-11 06:18 UTC
# Feature Request

**Ionic version:**
[x] **4.x**

**Describe the Feature Request**

ion-back-button has defaultHref which is great but typically when you need to use that defaultHref you want to navigate "backwards" into a navigation stack that doesnt exist... thus you would normally actually want the transition to go back NOT forward. Currently when you land on a URL with no previous navigation stack and you hit the ion back button it actually transitions forwards

**Describe Preferred Solution**

add defaultTransition directive

**Describe Alternatives**

add defaultTransition directive

**Related Code**

**Additional Context**

**Comment by manucorporat** [comment] 2019-01-11 14:11
ion-back-button defaultHref should navigate backwards already

**Comment by NG-tylerholden** [comment] 2019-01-11 15:09
I think you have to be a few "pages" deep

Maybe I have navigation setup wrong but for my specific example if you land on
tabs/home/account/account-settings

the defaultHref is set to 'tabs/home/account'

but the ion-back-button will transition forward on this.

**Comment by manucorporat** [comment] 2019-01-12 08:51
Can your provide a repo case that reproduces the issue? ion-back-button should never transition going forward

**Comment by NG-tylerholden** [comment] 2019-01-12 17:08
<a href='https://github.com/NG-tylerholden/back-button-test.git'>Test Repo</a>

Start at localhost /tabs/tab1/page1/page2/page3 then hit the back button - navigates forward.

**Comment by manucorporat** [comment] 2019-01-13 14:10
Your repo can't reproduce the issue, this path does not exist: `/tabs/tab1/page1/page2/page3`

**Comment by NG-tylerholden** [comment] 2019-01-13 16:12
Oh thats my bad, I forgot to push the pages to the repo haha. That was probably just the base ionic 4 template. Try now.

**Comment by maxschwarzmueller** [comment] 2019-02-14 14:08
I can confirm this bug in both your shared repo as well as a project I'm working on.

I couldn't trace down the issue entirely unfortunately - only thing I noticed whilst debugging is that `StackController` `setActive()` gets called twice for back button clicks after a page reload. It only gets called once in projects where this bug does not occur (e.g. the Ionic conference app) and for back button clicks where the page hasn't been reloaded before.

When I inspected the behavior in the Chrome devtools, it looked like the "back" animation was consumed in a redundant transition where active and entering view were equal (same URL). 

1. Execution for back button click (after page reload)
![image](https://user-images.githubusercontent.com/28806196/52791804-1f38e600-306a-11e9-8c0b-c460ffe16833.png)

2. Execution for the same back button click (i.e. animation/ navigation didn't complete in-between)
![image](https://user-images.githubusercontent.com/28806196/52791820-27912100-306a-11e9-9211-28962cd828cb.png)

The second time `setActive()` executes, `enteringView` and `this.activeView` are different as they should be. But the animation/ direction is already reset to `forward` by that time and due to the `NavController` guessing a `forward` animation, this type of animation plays.

I see no logical difference between the routing setup of the conference app and this demo project or my own project (in all projects, the tabs page gets lazy loaded, so do the routes nested in the tabs) but maybe the above behavior can be a good starting point for further debugging?

I don't think this is a feature request as it's currently labeled, it seems to be a bug instead.

**Comment by KyDenZ** [comment] 2019-07-31 22:14
Hello,

I have the same problem with the latest version of Ionic 4.7.1.

I currently pass my application (Ionic 3 / Cordova> Ionic 4 / Capacitor). On Ionic 3 I could do as on the Facebook Messenger application: The menu accessible from the tabs. Once you are on the menu you can go back (on the tabs) or open a page (eg settings).

If I open the settings, and I press the ion-back-button component I find myself on the menu, then if I go back to the tabs, I would be pushed to settings.

Workaround pending correction:
this.navCtrl.back ();
The navigation will be correct.

**Comment by liamdebeasi** [comment] 2023-10-13 16:46
Hi everyone,

I tested using the provided repo in https://github.com/ionic-team/ionic-framework/issues/17053#issuecomment-453763915. Using the installed version I was able to reproduce the issue. However, after updating both Ionic and Angular to their latest versions, this issues no longer reproduces. I am going to close this. If you are still running into a problem with navigation, please open a new issue and include a reproduction case. Thank you!

**Closed by liamdebeasi** 2023-10-13 16:46 UTC
Labels: type: feature request, package: core
