### ISSUE TITLE
bug: ng add @angular/pwa fails on v7

### ISSUE THREAD

**Issue by tryagaintmr** [ionic-team/ionic-framework#27395] opened 2023-05-04 17:26 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Hello,

After creating a new ionic application with v7, the bootstrapping of the application is done by main.ts.

As a result running the command 

`ng add @angular/pwa`

```
ℹ Using package manager: npm
✔ Found compatible package version: @angular/pwa@15.2.8.
✔ Package information loaded.

The package @angular/pwa@15.2.8 will be installed and executed.
Would you like to proceed? Yes

✔ Packages successfully installed.
Bootstrap call not found
```
then nothing is added in the solution : no manifest, no reference in the index.html head etc.

### Expected Behavior

Expected behavior  : 

A successful addition of @angular/pwa 

### Steps to Reproduce

1. Create a new ionic app v7
2. run `ng add @angular/pwa`

### Ionic Info

[WARN] Error loading @ionic/angular package.json: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath
       './package' is not defined by "exports" in
       C:\Source\Repos\project\myapp\node_modules\@ionic\angular\package.json
[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package'

       Require stack:
       - C:\Users\xxx\AppData\Roaming\nvm\v18.15.0\node_modules\@ionic\cli\lib\project\index.js
       - C:\Users\xxx\AppData\Roaming\nvm\v18.15.0\node_modules\@ionic\cli\lib\index.js
       - C:\Users\xxx\AppData\Roaming\nvm\v18.15.0\node_modules\@ionic\cli\index.js
       - C:\Users\xxx\AppData\Roaming\nvm\v18.15.0\node_modules\@ionic\cli\bin\ionic
[WARN] Error loading @capacitor/android package.json: Error: Cannot find module '@capacitor/android/package'

       Require stack:
       - C:\Users\xxx\AppData\Roaming\nvm\v18.15.0\node_modules\@ionic\cli\lib\project\index.js
       - C:\Users\xxx\AppData\Roaming\nvm\v18.15.0\node_modules\@ionic\cli\lib\index.js
       - C:\Users\xxx\AppData\Roaming\nvm\v18.15.0\node_modules\@ionic\cli\index.js
       - C:\Users\xxx\AppData\Roaming\nvm\v18.15.0\node_modules\@ionic\cli\bin\ionic

Ionic:

   Ionic CLI                     : 6.20.9 (C:\Users\xxx\AppData\Roaming\nvm\v18.15.0\node_modules\@ionic\cli)
   Ionic Framework               : not installed
   @angular-devkit/build-angular : 15.2.4
   @angular-devkit/schematics    : 15.2.4
   @angular/cli                  : 15.2.4
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 4.7.3
   @capacitor/android : not installed
   @capacitor/core    : 4.7.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v18.15.0 (C:\Program Files\nodejs\node.exe)
   npm    : 9.6.3
   OS     : Windows 10

**Comment by liamdebeasi** [comment] 2023-05-04 18:01
Thanks for the report. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/27144#issuecomment-1500687794.

There was a bug with `@angular/pwa@15` where it did not support standalone components. This was fixed in `@angular/pwa@16` which came out earlier today.

In terms of avoiding this issue, I recommend updating to Angular 16 (https://update.angular.io/) and using `@angular/pwa@16`. If you are unable to update to Angular 16, I recommend using NgModules instead of Standalone components until you are able to update to Angular 16. Our Ionic Angular starters were recently updated to ship with Angular 16 too. Let me know if you have any questions.

**Closed by liamdebeasi** 2023-05-04 18:01 UTC
Labels: triage
