### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by seanaguinaga** [ionic-team/ionic-framework#25040] opened 2022-03-31 20:41 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

<img width="1444" alt="Screen Shot 2022-03-31 at 13 42 00" src="https://user-images.githubusercontent.com/15254340/161145711-c04634c6-ffbb-4f6a-aa44-90f5f1a14353.png">

### Expected Behavior

Test would succeed

### Steps to Reproduce

https://github.com/seanaguinaga/nx-jest-ionic-repro

```
npm install

nx test ionic
```

### Ionic Info

```
Ionic:

   Ionic CLI       : 6.19.0 (/opt/homebrew/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 6.0.14 (/Users/sean/GitHub/nx-jest-ionic-repro/node_modules/@ionic/react)

Capacitor:

   Capacitor CLI      : not installed
   @capacitor/android : 3.4.3 (/Users/sean/GitHub/nx-jest-ionic-repro/node_modules/@capacitor/android)
   @capacitor/core    : 3.4.3 (/Users/sean/GitHub/nx-jest-ionic-repro/node_modules/@capacitor/core)
   @capacitor/ios     : 3.4.3 (/Users/sean/GitHub/nx-jest-ionic-repro/node_modules/@capacitor/ios)

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v16.14.2 (/opt/homebrew/Cellar/node@16/16.14.2/bin/node)
   npm    : 8.5.0
   OS     : macOS Monterey
```

### Additional Information

https://ionicframework.com/docs/intro/upgrading-to-ionic-6#testing

Here's the same issue on NX - not sure who can help

Will sync status between two

**Comment by liamdebeasi** [comment] 2022-04-07 15:24
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. As you noted in your issue via https://ionicframework.com/docs/intro/upgrading-to-ionic-6#testing, Jest does not support ES Modules. As a result, the ES Modules need to be transpiled down to Common JS.

I do see that you added the correct `transformIgnorePatterns`, but it does not look like the transpilation is happening. Unfortunately since this is a project level configuration and not an Ionic configuration, we are unable to provide technical support. I recommend posting on the [Ionic Forums](https://forum.ionicframework.com/) for help with getting your project to respect the `transformIgnorePatterns` option.

**Closed by liamdebeasi** 2022-04-07 15:24 UTC
Labels: triage
