### ISSUE TITLE
bug: Swiping up or down on unscrollable modal panel scrolls the page behind the modal panel

### ISSUE THREAD

**Issue by RHinderiks** [ionic-team/ionic-framework#17971] opened 2019-04-05 12:22 UTC
# Bug Report

**Ionic version:**

[x] 4.2.0

**Current behavior:**
When scrolling up or down on a non scrollable modal panel it scrolls the page in the background

**Expected behavior:**
Touch events should not act on pages behind a full page element (modal panel in this case)

**Steps to reproduce:**
Create a page with a list of items to scroll through
Clicking on one of these items opens a modal panel
Make up and down swipe gestures on this modal panel
Close modal panel and notice the page in the background has been scrolled instead

**Related code:**

Our modal panel uses forceOverscroll false to prevent scrolling on the modal panel

```
<ion-content [forceOverscroll]="false">
```

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.2.0
   @angular-devkit/build-angular : 0.13.8
   @angular-devkit/schematics    : 7.3.8
   @angular/cli                  : 7.3.8
   @ionic/angular-toolkit        : 1.5.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : ios 5.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 20 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/rh/Library/Android/sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 7.0.0
   NodeJS            : v8.11.4 (/Users/rh/.nvm/versions/node/v8.11.4/bin/node)
   npm               : 6.7.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.2 Build version 10E125
```

**Comment by alexwolfwang** [comment] 2019-04-08 13:42
same problem to me. I'm using ngif to switch the different content to display in the modal. The scroll function is correct in the first modal. But the scroll function is incorrect in the second modal. The content cannot be scrolled in the modal, but the background page is scrolled.

**Comment by KevinKelchen** [comment] 2019-04-17 15:24
What platforms are you experiencing this issue on? iOS? Android? Specific desktop/mobile web browsers?

**Comment by alexwolfwang** [comment] 2019-04-17 15:31
Desktop and Android works fine. The issue only appears on iOS browsers.

**Comment by KevinKelchen** [comment] 2019-04-17 15:40
Same here. Just noticing this issue.

Searching online so far I've come across a similar issue but specifically relating to the `<html`> and `<body>` elements. See [here](https://bugs.webkit.org/show_bug.cgi?id=153852), [here](https://teamtreehouse.com/community/overflow-hidden-not-working-in-ios-safari), and [here](https://medium.com/jsdownunder/locking-body-scroll-for-all-devices-22def9615177). I also see [this issue](https://bugs.webkit.org/show_bug.cgi?id=134449) which is not specific to those elements.

**Comment by alexwolfwang** [comment] 2019-04-17 17:49
There is another issue of scrolling that the ion-content cannot be scrolled after you closed a modal which above it.

**Comment by RHinderiks** [comment] 2019-05-06 09:59
Is there any news on this issue?

**Comment by rafalschmidt97** [comment] 2019-07-18 09:12
Maybe some variation might help (not tested):

```
.backdrop-no-scroll {
  ion-content {
    --overflow: hidden;
  }
}
```

**Comment by anagstef** [comment] 2019-08-02 13:39
@rafalschmidt97 Worked for me! Thanks! Indeed, I set your CSS on global scale and then override it on specific modals that i want to be scrollable.

**Comment by alexwolfwang** [comment] 2019-08-02 14:17
@rafalschmidt97 That really works.

**Comment by Livijn** [comment] 2019-08-15 09:28
Setting `--overflow: hidden;` on the modal's `ion-content` does work, however when a user scrolls on the modal, it instead scrolls the content behind that modal.

**Comment by rafalschmidt97** [comment] 2019-08-15 09:35
> Setting `--overflow: hidden;` on the modal's `ion-content` does work, however when a user scrolls on the modal, it instead scrolls the content behind that modal.

You have to put it in globals instead of component styles. Because it just blocks every single ion-scroll 😅 I'm aware that it's not perfect solution.

**Comment by Livijn** [comment] 2019-08-15 09:38
And how would I handle cases where the modal should be able to scroll?

**Comment by RHinderiks** [comment] 2019-08-15 09:41
@Livijn  This would make the modal scrollable again
.backdrop-no-scroll {
    ion-content {
        --overflow: hidden;
    }

    ion-modal ion-content{
        --overflow: auto;
    }
}

**Comment by rafalschmidt97** [comment] 2019-08-15 09:42
> And how would I handle cases where the modal should be able to scroll?

As I said above you have to force it back 😂

**Comment by Livijn** [comment] 2019-08-15 09:45
Yeah sorry, didn't think that through. Here's how I solved it:
```
.backdrop-no-scroll {
  ion-content:not([scrollable]) {
    --overflow: hidden;
  }
}
```

And then per scrollable modal: `<ion-content scrollable>`.

**Comment by RHinderiks** [comment] 2019-08-15 09:50
@Livijn This would still cause the backdrop to scroll on your scrollable modals right?

**Comment by Livijn** [comment] 2019-08-15 09:52
> @Livijn This would still cause the backdrop to scroll on your scrollable modals right?

Yes, it inherits the default scroll behaviour of an `<ion-content>`.

**Comment by RHinderiks** [comment] 2019-08-15 10:04
@Livijn But you don't want the backdrop to scroll underneath you modal panel (which is what the bug is)

**Comment by Livijn** [comment] 2019-08-15 11:56
> @Livijn But you don't want the backdrop to scroll underneath you modal panel (which is what the bug is)

If you are wondering if the parent of the modal also scrolls when scrolling the modal, then no. When scrolling the modal's `<ion-content>`, it doesn't propagate down to the parent.

**Comment by RHinderiks** [comment] 2019-08-15 12:11
@Livijn But your fix is only applied to modals without Scrollable, wouldn't the models with scrollable still scroll their parent?

**Comment by Livijn** [comment] 2019-08-15 12:21
> @Livijn But your fix is only applied to modals without Scrollable, wouldn't the models with scrollable still scroll their parent?

No, they don't do that by default either. I am using `@ionic/vue` though, but should be the same.

**Comment by haredev** [comment] 2019-10-29 10:18
Thanks @rafalschmidt97! and @Livijn 

Our case was a bit different in that we had a modal opening another modal that should be moveable (we used interactjs for that). The problem was that moving this above all modal was scrolling the content behind where actually the point of moving it was to be able to see areas behind. 
  
**Inspired by your fix, and since we had many modals that needed to scroll;** we instead made sure that when we open our moveable modal we add a class to ion-app. we applied your css to that specific class in global.css. And when dismissing the modal we remove the class. 

in Modal code
`public ngOnInit() {
    const ionApp = document.getElementsByTagName("ion-app")
    if (ionApp ) {
      const firstItem = ionApp.item(0)
      if (firstItem) {
        firstItem.classList.add("disable-scroll");
        console.log('Disabled scroll')
      }
    }
  }

  public ngOnDestroy() {
    const ionApp = document.getElementsByTagName("ion-app")
    if (ionApp ) {
      const firstItem = ionApp.item(0)
      if (firstItem && firstItem.classList.contains("disable-scroll")) {
        firstItem.classList.remove("disable-scroll");
        console.log('enabled scroll')
      }
    }
  }`

and global.scss
`.disable-scroll {
  ion-content {
    --overflow: hidden;
  }
}`

**Comment by vimalnallasamy** [comment] 2019-12-05 07:56
> Maybe this might works (not tested - put it in your global styles):
> 
> ```
> .backdrop-no-scroll {
>   ion-content {
>     --overflow: hidden;
>   }
> }
> ```
> 
> Keep in mind that you will probably block modal scroll as well if you are using ion-content there. But you can always force it back in modal.

thanks man works fine for me

**Comment by lincolnthree** [comment] 2020-06-03 12:54
This is occurring for our users again even without modals open. Usually when the keyboard is open this can be reproduced easily by trying to scroll past the beginning or end of the page. The scroll bounce will occur on the root page itself and "lock" scrolling interactions for a few seconds.

Has anyone else had this occur without modals?

**Comment by lincolnthree** [comment] 2020-06-03 12:56
Disregard, I believe this is a different issue. I misunderstood.

**Comment by feng-xiao** [comment] 2020-10-28 11:22
@liamdebeasi Can Ionic team fix this issue? It happens on Ionic 5 as well.

**Comment by HenokG** [comment] 2020-12-02 12:49
> Maybe this might works (not tested - put it in your global styles):
> 
> ```
> .backdrop-no-scroll {
>   ion-content {
>     --overflow: hidden;
>   }
> }
> ```
> 
> Keep in mind that you will probably block modal scroll as well if you are using ion-content there. But you can always force it back in modal.

this solution works but it brings in another known problem in iOS, the update of `overflow` will trigger the update of `-webkit-overflow-scrolling`, [this causes a visible flash/flickering](https://stackoverflow.com/questions/17747239/ios-flicker-bug-when-the-css-overflowscroll-is-changed-to-overflowhidden)

**Comment by liamdebeasi** [comment] 2022-04-29 15:39
Thanks for the issue. This was due to an issue in iOS/WebKit that has since been resolved (it was resolved around the release of iOS 13/iOS 14).

I recommend updating to the latest version of iOS to receive this fix.

**Closed by liamdebeasi** 2022-04-29 15:39 UTC
Labels: package: core, type: bug
