### ISSUE TITLE
bug: Modal dialog is closing after selecting an option in dropdown

### ISSUE THREAD

**Issue by Yura13** [ionic-team/ionic-framework#25133] opened 2022-04-15 12:07 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Modal dialog is closing after selecting an option in dropdown.

### Expected Behavior

User should be able to select an option in dropdown without closing the modal dialog

### Steps to Reproduce

Open modal with dropdown inside.

### Ionic Info

Ionic:

   Ionic CLI                     : 6.19.0 (C:\Users\Xiaomi\AppData\Roaming\nvm\v16.13.2\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.1.0
   @angular-devkit/build-angular : 13.3.2
   @angular-devkit/schematics    : 13.3.2
   @angular/cli                  : 13.3.2
   @ionic/angular-toolkit        : 5.0.3

Cordova:

   Cordova CLI       : 10.0.0 (cordova-lib@10.1.0)
   Cordova Platforms : android 10.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, cordova-plugin-ionic 5.5.2, (and 32 other plugins)

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   Android SDK Tools : 26.1.1 (C:\Android\android-sdk)
   NodeJS            : v16.13.2 (C:\Program Files\nodejs\node.exe)
   npm               : 8.1.2
   OS                : Windows 10

**Comment by liamdebeasi** [comment] 2022-04-15 13:24
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/25124.

**Closed by liamdebeasi** 2022-04-15 13:24 UTC
Labels: triage
