### ISSUE TITLE
bug: <ion-img> not appearing since 4.6.* (worked in 4.5.x)

### ISSUE THREAD

**Issue by lincolnthree** [ionic-team/ionic-framework#18734] opened 2019-07-08 20:35 UTC
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**

Currently, the `<ion-img>` tags do not load when they are initially loaded in the viewport. They also do not reliably load when they are scrolled into the viewport from offscreen. I'm assuming something is broken with the load trigger in 4.6.x/Stencil One.

The strange part is that it works fine in Electron / Capacitor, but does not load on Chrome. 

It seems to work a little better on Safari, but I do still see the issue occasionally with random images.

Which images fail to load seems random, but the same images fail each time on refresh, so that makes me think there's something pseudorandom going on. Not 100% random.

**Expected behavior:**

ion-img should load its image when in the viewport.

**Steps to reproduce:**

I tried creating a sample app, but could not reproduce the issue. I really don't know. As I mentioned, the images load fine in Electron/Capacitor, but do not load in native Chrome. And load better in Safari, but not 100%.

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
Lincolns-MacBook-Pro-2:topdecked-unified lincoln$ ionic info

Ionic:

   Ionic CLI                     : 5.2.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.6.1-dev.201907052128.7953088
   @angular-devkit/build-angular : 0.800.3
   @angular-devkit/schematics    : 7.3.1
   @angular/cli                  : 8.0.3
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   Android SDK Tools : 26.1.1 (/usr/local/share/android-sdk)
   ios-deploy        : 1.9.4
   NodeJS            : v12.3.1 (/usr/local/Cellar/node/12.3.1/bin/node)
   npm               : 6.9.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.2.1 Build version 10E1001


```

Tagging issue https://github.com/ionic-team/ionic/issues/18655

**Comment by lincolnthree** [comment] 2019-07-08 20:44
Here's a video of the issue since I can't seem to reproduce in a sample app, or figure out why some images load but others don't:

https://www.youtube.com/watch?v=PXglOJ6vd3w&feature=youtu.be

When I inspect the ion images in the dom, the image tag itself has not been populated with a src:

![Screen Shot 2019-07-08 at 4 44 07 PM](https://user-images.githubusercontent.com/362329/60841397-b6c8dd80-a19f-11e9-90c4-625992997a39.png)

**Comment by liamdebeasi** [comment] 2019-07-09 13:43
Thanks for the issue! Can you test this with the latest dev build of Ionic and see if this fixes the issue you are seeing? `npm i @ionic/angular@dev`

**Comment by lincolnthree** [comment] 2019-07-09 13:52
@liamdebeasi On it! Thanks for the reply :)

**Comment by lincolnthree** [comment] 2019-07-09 13:54
@liamdebeasi That's a negative :(

**Comment by lincolnthree** [comment] 2019-07-09 13:54
```
Lincolns-MacBook-Pro-2:topdecked-unified lincoln$ ionic info

Ionic:

   Ionic CLI                     : 5.2.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.7.0-dev.201907061735.e059fc8
   @angular-devkit/build-angular : 0.800.3
   @angular-devkit/schematics    : 7.3.1
   @angular/cli                  : 8.0.3
   @ionic/angular-toolkit        : 1.5.1


```

**Comment by liamdebeasi** [comment] 2019-07-09 13:56
Ok thanks for checking! Are you able to provide a repository with the code required to reproduce this issue?

**Comment by lincolnthree** [comment] 2019-07-09 14:03
@liamdebeasi Technically I could, but ... are you and anyone else who'd look at the code able to sign an NDA? :/

**Comment by liamdebeasi** [comment] 2019-07-09 14:04
It doesn't have to be your product-specific code. I'm mostly interested in seeing an example of an `ion-img` not loading. Is this issue happening with all `ion-img` elements or certain images?

**Comment by lincolnthree** [comment] 2019-07-09 14:12
@liamdebeasi I tried to reproduce in a sample app, but was unable to do so. The issue seems to happen most frequently with `<ion-img>` elements that are loaded in a named router outlet.

`<ion-img>` is encapsulated in a custom component (the same component used in other areas of the page that load just fine.)

Actually, I just realized that the other user having issues with the images not loading in tabs might also be similar, since the new Ionic tabs are implemented using named router outlets.

**Comment by lincolnthree** [comment] 2019-07-09 14:29
I'll try to give more info if I can, hopefully this will help:

Images that do not render seem to have a width of 0. They do appear to have a height:

![image](https://user-images.githubusercontent.com/362329/60896331-28526b80-a234-11e9-956c-99d5305a236d.png)

When I manually set a width (for example 50px) on the `<img>` tag element in the DOM, nothing happens. But when I manually set its height, the image src attribute is populated and the image loads immediately.

**Comment by lincolnthree** [comment] 2019-07-09 14:36
Okay, I found something interesting. I set a `min-height: 1px` on the `<ion-img>` and that appears to have gotten things working. I'm going to do more testing and see if it breaks again.

**Comment by liamdebeasi** [comment] 2019-07-09 14:37
Thanks for the follow up. The tabs starter does not use named router outlets, so I don't think that would be the cause in the case of a tabs application.

We aren't able to fix this issue if we can't reproduce it, so any code that can help us reliably reproduce this issue is appreciate. Thanks!

**Comment by lincolnthree** [comment] 2019-07-09 14:38
@liamdebeasi Understood. I wish I could help more than just dumping my entire app on you (it's massive.)

**Comment by lincolnthree** [comment] 2019-07-09 15:16
@brandyscarney Sorry to bug you, but if someone from the Ionic team could take a minute or two to tell us how to go about sending a PR for this, I'd try to make it happen. Or even just where to start in the source and/or how you'd like it done.

I tried hacking the Ionic distribution to get things working but apparently didn't get the right incantation...

Thanks!

**Comment by brandyscarney** [comment] 2019-07-09 15:24
It could possibly be related to this https://github.com/ionic-team/ionic/pull/18708

**Comment by lincolnthree** [comment] 2019-07-11 14:00
Putting this here for others who might run across this problem. Setting a min-height on the ion-img element seems to resolve the issue:

in your global.scss (or other relevant stylesheet):
```
:root {
  ion-img {
    /** 
     * Bug fix for:
     * https://github.com/ionic-team/ionic/issues/18734
     */
    min-height: 1px !important;
  }
}
```

**Comment by cmer4** [comment] 2019-07-16 09:22
Hey guys, I have seen this issue with my app as well. I will try to deploy it to live environment on Friday this week and have you access it and can share code as well if no one will provide example. But yes I confirm randomly images are not loading.

Will try min-height trick

**Comment by liamdebeasi** [comment] 2019-07-16 13:26
@cmer4 If you could provide a code reproduction of the issue, that would be very helpful. Thanks!

**Comment by dlodeprojuicer** [comment] 2019-07-24 23:26
I came across issue. I had my images in src/assets folder 

```
Ionic cli: 5.2.3
Vue cli: 3.9.2

"@ionic/core": "^4.6.2",
"@ionic/vue": "0.0.4",
```
If src points to an image in **src/assets** like so `../assets/logo.png` in `<ion-img>` the image will not display. Th image must be in **public/img** like so `../img/logo.png`.

When using `<img>` tag the src must point to **src/assets** like so `../assets/logo.png`

Demo: https://ionic-images.netlify.com/
Repo: https://github.com/dlodeprojuicer/ionic-images

**Comment by gRegorLove** [comment] 2019-07-31 21:52
I have run into this several times with `ion-img` as the first element inside an `ion-card-content`, testing in browser. Since ion-img is lazy loaded when in view, I _think_ it has something to do with the parent element somehow "covering" it, so it never gets lazy loaded. If I add a `margin-top: 1px` to the ion-img, the image loads pretty reliably. The min-height trick above sounds similar. I am still debugging and will update if I find anything more solid.

```
Ionic:

   Ionic CLI                     : 5.2.1 (C:\Users\gRegor\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.6.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1
```

**Comment by sprucify** [comment] 2019-08-02 14:38
I started to see ion-img images not loading on Android 9 devices.
But I also migrated to Angular 8, so I'm not sure what the real cause is.

I can confirm that `min-height: 1px !important;` workaround worked for now.
Tested on Samsung S10 Android 9

**Comment by jet174** [comment] 2019-08-10 10:35
same problem

**Comment by vdias38** [comment] 2019-10-15 11:24
I have same issue, occurs randomly, I mean on a list of cards, some imgs appears and others no, even if urls of imgs are same.
https://crud-angularfirestore-ionic4.web.app ([source code on github](https://github.com/meumobi/mmb-demos.crud-angularfirestore-ionic4), check `items-list` page)
I can confirm that `min-height: 1px !important;` workaround worked for now.

**Comment by cherzog** [comment] 2019-11-05 16:39
Same Problem here. But not everytime. Maybe some kind of race condition.

Pressing F5 in Browser: it works 8 times out of 10. 

If it doesn't work, the DOM look like described here: 

https://github.com/ionic-team/ionic/issues/18734#issuecomment-509384809

**Comment by codyburleson** [comment] 2019-11-09 05:18
I've had the same issue in the Chrome browser (random images in ion-img not loading) and can confirm that min-height: 1px !important; workaround worked for me also.

**Comment by madhurgoyal3** [comment] 2019-11-13 15:06
I also had the same issue, and min-height: 1px !important; workaround worked for me also.

**Comment by andreas-aeschlimann** [comment] 2019-11-30 21:24
I have the issue that images very unreliably load with lazy loading (ion-img).

It appears to me that this issue is related to the view port. The images that don't load are usually those images that are within the viewport at initial load. When I scroll down and up again, the images begin to appear.

It is quite a severe issue because it is totally random but easily reproduceable because it happens a lot. The user is then left without any image, it does not show the fallback image neither.

**Comment by andreas-aeschlimann** [comment] 2019-11-30 21:43
> Putting this here for others who might run across this problem. Setting a min-height on the ion-img element seems to resolve the issue:
> 
> in your global.scss (or other relevant stylesheet):
> 
> ```
> :root {
>   ion-img {
>     /** 
>      * Bug fix for:
>      * https://github.com/ionic-team/ionic/issues/18734
>      */
>     min-height: 1px !important;
>   }
> }
> ```

Unfortunately, I cannot confirm this. It did not work for our app. Images that are in the viewport at initial load did not always load properly.

**Comment by vdias38** [comment] 2019-12-02 10:26
Hi @andreas-aeschlimann, did you use tab bar on your page ? The workaround works for me only on pages without tab bar (check my [stackblitz demo](https://crud-angularfirestore-ionic4.web.app/)), but don't if I use a tab-bar.

**Comment by andreas-aeschlimann** [comment] 2019-12-02 11:17
Yes, I have tabs as well, especially on the start page. Not on all pages, so I am not sure (yet) if it works on those without tabs.

**Comment by nuryagdym** [comment] 2019-12-24 06:16
In my case it, I faced this error ONLY on android v7.0.0 on Android Studio.

`Ionic:

   Ionic CLI                     : 5.4.10
   Ionic Framework               : @ionic/angular 4.11.5
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.3.20
   @ionic/angular-toolkit        : 2.1.1
Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
`

**Comment by carloliwanag** [comment] 2019-12-30 04:04
> > Putting this here for others who might run across this problem. Setting a min-height on the ion-img element seems to resolve the issue:
> > in your global.scss (or other relevant stylesheet):
> > ```
> > :root {
> >   ion-img {
> >     /** 
> >      * Bug fix for:
> >      * https://github.com/ionic-team/ionic/issues/18734
> >      */
> >     min-height: 1px !important;
> >   }
> > }
> > ```
> 
> Unfortunately, I cannot confirm this. It did not work for our app. Images that are in the viewport at initial load did not always load properly.

This worked for me. Thanks!

**Comment by armn** [comment] 2020-01-14 19:21
I have a similiar issue — on some page loads the ``<img>`` elements don't get their src on initial load, although they are in viewport. If I start to scroll around, the images appear when entering the viewport.

It could have something to do with tabs or the column layout CSS I'm using, but not 100% what causes it yet.

It can be semi-reliably replicated in https://draugs.app/app/animals, just hit refresh a few times. Source code is available at https://github.com/armn/draugs

**Comment by andreas-aeschlimann** [comment] 2020-01-14 22:18
@armn this is exactly the issue we have as well. Scrolling down and up usually makes the images load, unless they are in a fixed container.

**Comment by nprail** [comment] 2020-01-25 17:48
I am also encountering this issue when upgrading from Ionic Angular `4.1.1` to `4.11.10` (Angular `7.2.16`). The `min-height` CSS workaround does not do the trick for me. 

I'm using an `ion-grid` with two rows. The second row has all of the images that don't always load. I removed the first row to post a simplified code snippet but that fixed the issue. 

Here is a full template code snippet that doesn't work most of the time. The TS basically just loads `events` from an API in `ngOnInit`.  I tried to create a Stackblitz demo but it refused to install the dependency versions that I specified... 
```
<ion-content>
  <ion-grid>
    <ion-row class="ion-align-items-center">
      <ion-col>
        <ion-img src="../../assets/wm-logo.svg"></ion-img>
        <p class="ion-text-center">Which event are you attending?</p>
        <ion-searchbar
          placeholder="Search for an event..."
          [(ngModel)]="queryText"
          (ionChange)="search()"
        ></ion-searchbar>
      </ion-col>
    </ion-row>
    <ion-row>
      <ion-col *ngFor="let event of events" size="6">
        <ion-card class="ion-text-center" (click)="goToEvent(event)">
          <ion-img [src]="event.org.appSettings && event.org.appSettings.icon">
          </ion-img>
          <ion-card-header>
            <ion-card-title style="font-size: 15px;">
              {{ event.name }}
            </ion-card-title>
            <ion-card-subtitle>
              {{ event.startDate | date: 'MMM d' }} - {{ event.endDate | date:
              'mediumDate' }}
            </ion-card-subtitle>
          </ion-card-header>

          <ion-button class="ion-margin-bottom" size="small">Open</ion-button>
        </ion-card>
      </ion-col>
    </ion-row>
  </ion-grid>
</ion-content>

```

**Comment by nprail** [comment] 2020-01-25 23:27
Upgrading to `@ionic/angular@5.0.0-rc.0` seems to have resolved the issue for me.

**Comment by andreas-aeschlimann** [comment] 2020-01-25 23:29
> Upgrading to `@ionic/angular@5.0.0-rc.0` seems to have resolved the issue for me.

I am glad to read that, thanks. I will upgrade as soon as Ionic 5 officially releases.

**Comment by liamdebeasi** [comment] 2020-01-27 14:52
Could everyone please try Ionic `5.0.0-rc0` and let me know if it fixes the issue? I've been trying it in a few examples apps provided in this thread and the issues appears to be fixed in that version.

**Comment by codyburleson** [comment] 2020-01-29 01:33
> Could everyone please try Ionic `5.0.0-rc0` and let me know if it fixes the issue? I've been trying it in a few examples apps provided in this thread and the issues appears to be fixed in that version.

It does not fix the issue in my test case. First of all, for a quick look, take a look at this page in Chrome on my test (staging) site:

https://staging.codyburleson.com/photos/jack-depope

That is using Ionic 5.0.0-rc.0 and WITHOUT the following work-around in `global/app.css`...

```
ion-img {
  min-height: 1px !important;
}
```
If I uncomment the CSS stanza above (e.g. if I use the old work-around), and reload, the images all load fine again.

If you would like to test this locally with my staging branch, see:

https://github.com/codyburleson/cburleson-pwa/tree/staging

**Comment by armn** [comment] 2020-02-04 21:54
> Could everyone please try Ionic `5.0.0-rc0` and let me know if it fixes the issue? I've been trying it in a few examples apps provided in this thread and the issues appears to be fixed in that version.

Thank you! I updated to `5.0.0-rc.2` and in my case the issue appears to be resolved (without the min-height workaround).

**Comment by ebeliejinfren** [comment] 2020-02-23 18:09
ionic 5.0.1
it not correct working in custom horizontal scroll

**Comment by philmerrell** [comment] 2020-03-19 18:43
I came across this for the first time today. I'm using `@ionic/angular 5.0.5`:

Here's the html that is causing this behavior for me:

```
<ion-card routerLink="/tabs/home/faculty">
  <ion-img src="/assets/home/faculty.jpg"></ion-img>
  <ion-item color="secondary" detail>
    <h2>FACULTY</h2>
  </ion-item>
</ion-card>
<ion-card routerLink="/tabs/home/student">
  <ion-img src="/assets/home/student.jpg"></ion-img>
  <ion-item color="secondary" detail>
    <h2>STUDENT</h2>
  </ion-item>
</ion-card>
<ion-card routerLink="/tabs/home/staff">
  <ion-img src="/assets/home/staff.jpg"></ion-img>
  <ion-item color="secondary" detail>
    <h2>STAFF</h2>
  </ion-item>
</ion-card>
```
For some reason, with this configuration, the middle image doesn't load, but strangely, it will load as soon as I click on it to go to the view.

If I comment out the `ion-card` components, then all the `ion-img` components load properly.  If I replace `ion-img` with the standard `img` tag, the images load as expected.

Seems to be an issue with multiple cards and the `ion-img` inside.

Thanks for the css work around, that does fix it.

**Comment by austinhutchison** [comment] 2020-05-24 16:23
I am experiencing this issue, CSS workaround was successful - thank you @lincolnthree 

```
Ionic:

   ionic (Ionic CLI)             : 4.10.3 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 5.0.4
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4, ios 5.1.1
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 9 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/austinhutchison/Library/Android/sdk)
   ios-sim           : 8.0.2
   NodeJS            : v12.16.1 (/Users/austinhutchison/.nvm/versions/node/v12.16.1/bin/node)
   npm               : 6.13.4
   OS                : macOS Mojave
   Xcode             : Xcode 10.1 Build version 10B61
```

**Comment by lincolnthree** [comment] 2020-05-25 16:42
Welcome :)

**Comment by andrei0x309** [comment] 2020-06-06 16:58
I am having the same issue on Android version 5.1.1, the issue doesn't appear on newer versions of Android, I tested Android 6 ,7, 8 and ion-img works but not on [ Andoid 5.1.1 ]. 
Regular img element works also on Android 5.1.1. 

I am using Ionic -> -- @ionic/angular@5.1.1

Using the CSS workaround doesn't solve the issue, and the CSS workaround doesn't seem do be necessary on newer android versions where it works without it.
Also no problem in browser(aka ionic serve). 

I am considering to make a osVersion check to use img instead of ion-img on older devices like 5.1.1...

**Comment by fkromer** [comment] 2020-08-05 14:52
With ionic + angular it turned out that absolute references (`<ion-img src="/assets/<rootdirimage>.png"></ion-img>` or `<ion-img src="/assets/<some-subdir>/<subdirimage>.png"></ion-img>`) work just fine with the `angular.json` mentioned with `ionic serve` (served from `src/assets/`) as well as with `ionic build` + http serving of the output directory (served from `<output-dir>/assets/`). Hope this helps.

**Comment by selected-pixel-jameson** [comment] 2020-08-19 13:32
This also happens with standard <img> tags. I had to apply the same fix to get it to work when loading a regular image. 

```
:root {
  img{
    min-height: 1px !important;
  }
}
```

See https://github.com/SimonGolms/ngx-ionic-image-viewer/issues/41. This is where I came across this issue. It only happens on Android.

**Comment by svmszcck** [comment] 2022-01-22 19:27
Solution of @lincolnthree fixed the problem for ionic 6 with vue.

**Comment by fabbioamaral** [comment] 2022-08-01 14:10
@ionic/angular: 4.4.2 app here.

<ion-img> wasn't loading the first image present within ion-slides. It only showed after I interacted with the slides. 
My solution was to replace <ion-img> for <img> tag, since <ion-img> uses lazy loading and in my case I needed to load few images.

**Comment by liamdebeasi** [comment] 2022-11-22 21:38
Hi everyone,

Does this issue still reproduce on the latest version of Ionic 6? I am not able to reproduce this on my end anymore.

**Comment by andrei0x309** [comment] 2022-11-22 21:51
A long time ago, when this happened to me was with an older Android 5, and I didn't have any issues with newer Androids.

With ionic 6 I tested on android( 10 - api29, and 11 api30), and found no issue.

I'll install an emulator with 5.1 and test it in 10 minutes to see if this is an issue for such an old Webview.

**Comment by andrei0x309** [comment] 2022-11-22 23:53
Pretty bad news, for `Ionic 6` it seems it doesn't work at all for API `21`, `22`, `23`. 

I mean I tried directly the templates for Vue & react provided and generated with ionic CLI and then just bundle in an APK.

At API 24 starts to work, also no problem with `ion-image` probably docs should change to bump the minimum version to 24 and close this issue, and maybe in `gradlew` the minimum should be set also to `24`. 

Test APK (react template for CLI)
[app-debug-react-template.zip](https://github.com/ionic-team/ionic-framework/files/10071889/app-debug-react-template.zip)

Woking version: API 24 ( Android 7)
![image](https://user-images.githubusercontent.com/3593329/203443741-feae7918-39eb-4df7-888e-0ea90e815718.png)


On `21`,`22`,`23` will be a blank screen probably webview implementation missing something that is used in Ionic v6.

I think bumping to a minimum 24 is reasonable especially because google has enacted a policy that hides your apps if you don't target an API that's within 2 years back.

**Comment by liamdebeasi** [comment] 2022-11-23 14:05
The webview version, not the API version, impacts the ability to run Ionic applications. For example, Ionic 6 apps must use v60+ of the Chromium webview found on Android. What webview versions are you running on each of the affected devices? You can find this by logging `window.navigator.userAgent` when inspecting the app with Chrome Dev Tools.

I will also note that Android emulators are not a great way of testing Ionic apps as many typically do not allow their webviews to be autoupdated due to their lack of Google Play Services. As a result, it is possible these emulators are running a very outdated version of the webview. (Note: Some newer emulators allow you to install Google Play Services, but most older emulators do not)

**Comment by andrei0x309** [comment] 2022-11-23 22:01
@liamdebeasi Yeah correct I am talking about stock versions of the official images for `API 22`, and `API 23`, I didn't try to update the webview and I ran with the stock one packed in the image, the emulators allow store upgrades if you run with google images with google services. 

And you don't need to run de-googled images unless you develop apps that need root permissions which is very rare these days.

So I can try to upgrade the webview for both `22` and `23` to see if that works...

But I think `22` and `23` should be deprecated because if you have the stock webview a user would not understand why the APP doesn't work which is pretty bad, there's no error like `incompatible webview` or something just a blank screen. 
Plus the capacitor has a special case where it uses these outdated webviews only for this APIs as `API 24` has chrome bundled and from `24+` capacitor starts using chrome. 

I'll try to update the webviews with play store to the latest to see the results.

**Comment by andrei0x309** [comment] 2022-11-24 10:42
![image](https://user-images.githubusercontent.com/3593329/203764108-ab91aaf1-758d-4dc3-bd12-70037bc6a11c.png)

Works with an updated webview right now `API 22` can update up to `webview 95` and 23 up to `webview 106` stock is 44.
Probably on real devices webview will be updated.
So yeah probably safe to close this.

**Comment by liamdebeasi** [comment] 2022-11-29 14:07
Thanks for checking! I will close this as it sounds like the issue is resolved. If anyone is still running into this issue please reply here with a reproduction case.

**Closed by liamdebeasi** 2022-11-29 14:07 UTC
Labels: triage, package: core, type: bug
