### ISSUE TITLE
feat:  hide scrollbar on mobile browser scroll down like most jquery mobile ui

### ISSUE THREAD

**Issue by michaelokoh** [ionic-team/ionic-framework#23407] opened 2021-06-03 05:53 UTC
Been trying to enable the hide browser bar functionality when the user scrolls down on mobile like many jquery webpages do but it seems the ionic viewport is interfering with this. perhaps you can make a change so ionic apps can have more room on the screen
For example check how dev.to behaves when scroll down

**Comment by liamdebeasi** [comment] 2021-06-03 12:40
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/19081.

**Closed by liamdebeasi** 2021-06-03 12:40 UTC
Labels: triage
