### ISSUE TITLE
bug: ion-textarea and ion-input with element tag css style is getting ignored

### ISSUE THREAD

**Issue by indraraj26** [ionic-team/ionic-framework#21861] opened 2020-08-01 13:05 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

https://codepen.io/indraraj26/pen/bGEXLxo

**Expected behavior:**

It should apply ion-textarea and ion-input style

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by indraraj26** [comment] 2020-08-01 13:12
what i noticed if you add custom class onto the ion-textarea then it is applying css style
```
<ion-item>
  <ion-textarea class="test" placeholder="Enter more information here..."></ion-textarea>
</ion-item>
    <ion-item>
```
```
.test {
	--placeholder-color: blue;
	--color: red;
}

```

**Comment by liamdebeasi** [comment] 2020-08-03 13:22
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/17425.

**Closed by liamdebeasi** 2020-08-03 13:22 UTC
Labels: triage
