### ISSUE TITLE
feat: Add a class to prevent the swipeToClose behavior

### ISSUE THREAD

**Issue by rodrigo-fonseca** [ionic-team/ionic-framework#26179] opened 2022-10-27 11:30 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

 Is possible to add a feature like "noSwipingClass" from Swiper for the swipeToClose behavior from Modal?

### Describe the Use Case

I'm using the "swipeToClose" feature on my Modal, but on some elements on my Modal I would like to prevent this behavior despite others...

**Comment by amandaejohnston** [comment] 2022-10-27 14:04
Thanks for the feature request. Could you give more detail on your use case for this?

**Comment by DwieDima** [comment] 2022-10-28 09:09
you could get the modal instance and programmatically toggle the swipeToClose functionality:

```typescript

private activeModal: HTMLIonModalElement;

public constructor(private modalController: ModalController) {}

public async ngOnInit(): Promise<void> {
   this.activeModal = await this.modalController.getTop();
}

public toggleSwipeToClose(canSwipeToClose: boolean): void {
   this.activeModal.swipeToClose = canSwipeToClose;
}

```

**Comment by rodrigo-fonseca** [comment] 2022-10-28 09:34
> Thanks for the feature request. Could you give more detail on your use case for this?

I've those icons bellow that I would like to move free on my Modal... I would like to remove the swipeToClose behavior when moving those icons, basically is this...

<img width="1792" alt="Captura de Tela 2022-10-28 às 10 30 52" src="https://user-images.githubusercontent.com/16529344/198555178-a5adc763-1f1c-495a-8e5f-a42960c6976c.png">

**Comment by rodrigo-fonseca** [comment] 2022-10-28 09:39
> not tested, but you could get the modal instance and programmatically toggle the swipeToClose functionality:
> 
> ```ts
> private activeModal: HTMLIonModalElement;
> 
> public constructor(private modalController: ModalController) {}
> 
> public async ngOnInit(): Promise<void> {
>    this.activeModal = await this.modalController.getTop();
> }
> 
> public toggleSwipeToClose(canSwipeToClose: boolean): void {
>    this.activeModal.swipeToClose = canSwipeToClose;
> }
> ```

Sorry, I didn't get it, and actually I'm using React (but I can understand the logic on Angular btw). Can you please give me a brief explanation on how and when I would call those methods (example: toggleSwipeToClose)

**Comment by DwieDima** [comment] 2022-10-28 12:13
I'm not a react dev, but it should look like this:

```typescript

const modal = useRef<HTMLIonModalElement>(null);

function toggleSwipeToClose(canSwipeToClose: boolean) {
   modal.current?.swipeToClose = canSwipeToClose;
}

```

This just grabs the active instance of your modal, where you can override the `swipeToClose` property. I've used this once to override the `animated` property and it worked.

You should call `toggleSwipeToClose(false)` on move start and call `toggleSwipeToClose(true)` on move end. 
Your library for dragging should have these events.

**Comment by DwieDima** [comment] 2022-11-09 23:49
@rodrigo-fonseca did this sample resolved 
your issue?

**Comment by rodrigo-fonseca** [comment] 2022-11-10 03:44
> @rodrigo-fonseca did this sample resolved
> your issue?

YES! Thank You!!

**Comment by liamdebeasi** [comment] 2022-11-15 17:22
Hey there,

It sounds like the issue is resolved as per https://github.com/ionic-team/ionic-framework/issues/26179#issuecomment-1309728709, so I am going to close this. Please let me know if this is not the case, and I can reopen the issue.

**Closed by liamdebeasi** 2022-11-15 17:22 UTC
Labels: triage
