### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by rafaelsilvestrini** [ionic-team/ionic-framework#26030] opened 2022-09-28 09:33 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

The latest version of ionic 6, ion-input type="number", max and min attribute form validation does not work.

But changing to TEXT type works normally.

### Expected Behavior

Character limiter should work for all types

### Steps to Reproduce

Just change the attribute (Parameters) to type Number

### Ionic Info

Ionic:

   Ionic CLI                     : 6.20.1 (C:\Users\Silvestrini\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.2.0
   @angular-devkit/build-angular : 14.1.0
   @angular-devkit/schematics    : 14.1.0
   @angular/cli                  : 14.1.0
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 4.0.1
   @capacitor/android : not installed
   @capacitor/core    : 4.0.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.6.0

System:

   NodeJS : v14.15.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.8
   OS     : Windows 10

**Comment by liamdebeasi** [comment] 2022-09-28 13:24
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/23480.

**Closed by liamdebeasi** 2022-09-28 13:24 UTC
Labels: triage
