### ISSUE TITLE
bug: ion-item-sliding click event on ion-item not recognized immediately after swipe gesture

### ISSUE THREAD

**Issue by Umfi** [ionic-team/ionic-framework#23793] opened 2021-08-19 17:16 UTC
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

When I swipe an ion-item-sliding to open it's options and swipe back to close its options a click handler on the main element of the ion-item-sliding is not recognized immediately. We have to wait a short time, until the click is recognized again. usualy works on the second click.

### Expected Behavior

Click on ion-item (main content of ion-item-sliding) should recognized click event immediately when the options are fully closed.

### Steps to Reproduce

swipe ion-item-sliding element to open its options
swipe back to close its options
click on main content of ion-sliding

### Code Reproduction URL

https://github.com/Umfi/ionic-ion-item-sliding-bug

### Ionic Info

[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module
       '@capacitor/ios/package'
       
       Require stack:
       - /usr/local/lib/node_modules/@ionic/cli/lib/project/index.js
       - /usr/local/lib/node_modules/@ionic/cli/lib/index.js
       - /usr/local/lib/node_modules/@ionic/cli/index.js
       - /usr/local/lib/node_modules/@ionic/cli/bin/ionic
[WARN] Error loading @capacitor/android package.json: Error: Cannot find module
       '@capacitor/android/package'
       
       Require stack:
       - /usr/local/lib/node_modules/@ionic/cli/lib/project/index.js
       - /usr/local/lib/node_modules/@ionic/cli/lib/index.js
       - /usr/local/lib/node_modules/@ionic/cli/index.js
       - /usr/local/lib/node_modules/@ionic/cli/bin/ionic

Ionic:

   Ionic CLI       : 6.16.3 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 5.6.14

Capacitor:

   Capacitor CLI      : 3.2.0
   @capacitor/android : not installed
   @capacitor/core    : 3.2.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.3
   native-run  : 1.4.0

System:

   NodeJS : v14.17.1 (/usr/local/bin/node)
   npm    : 7.20.3
   OS     : Linux 5.4

### Additional Information

I am using Ionic Vue.

**Comment by liamdebeasi** [comment] 2021-08-19 20:53
Thanks for the issue. This looks to be a duplicate of https://github.com/ionic-team/ionic-framework/issues/22722. Both this issue and #22722 appear to be related to these few lines of code: https://github.com/ionic-team/ionic-framework/blob/f81d18c6f9f1bce056afda1cac4cf6d6ace0a7ca/core/src/components/item-sliding/item-sliding.tsx#L361-L364

If we can do without the `setTimeout`, I think we will be able to resolve both issues. I will post any updates on #22722. Thanks!

**Closed by liamdebeasi** 2021-08-19 20:53 UTC
Labels: triage
