### ISSUE TITLE
bug: SSR TypeError: Cannot read property 'whenDefined' of null (ion-menu)

### ISSUE THREAD

**Issue by jicasada** [ionic-team/ionic-framework#24782] opened 2022-02-14 19:37 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

When adding the menu component and running server-side rendering (SSR) the following error is received:

`unhandledRejection TypeError: Cannot read property 'whenDefined' of null
    at /ext/git/github/jicasada/ionicframework-bug-ion-menu-ssr/ionicframework-bug-ion-menu-ssr/dist/app/server/main.js:42769:34
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/ext/git/github/jicasada/ionicframework-bug-ion-menu-ssr/ionicframework-bug-ion-menu-ssr/dist/app/server/main.js:149520:24)
    at _next (/ext/git/github/jicasada/ionicframework-bug-ion-menu-ssr/ionicframework-bug-ion-menu-ssr/dist/app/server/main.js:149542:9)
    at /ext/git/github/jicasada/ionicframework-bug-ion-menu-ssr/ionicframework-bug-ion-menu-ssr/dist/app/server/main.js:149549:7
    at new ZoneAwarePromise (/ext/git/github/jicasada/ionicframework-bug-ion-menu-ssr/ionicframework-bug-ion-menu-ssr/dist/app/server/main.js:147605:23)
    at /ext/git/github/jicasada/ionicframework-bug-ion-menu-ssr/ionicframework-bug-ion-menu-ssr/dist/app/server/main.js:149538:12
    at Menu.connectedCallback (/ext/git/github/jicasada/ionicframework-bug-ion-menu-ssr/ionicframework-bug-ion-menu-ssr/dist/app/server/main.js:42780:11)
    at safeCall$1 (/ext/git/github/jicasada/ionicframework-bug-ion-menu-ssr/ionicframework-bug-ion-menu-ssr/dist/app/server/main.js:27714:20)
    at fireConnectedCallback (/ext/git/github/jicasada/ionicframework-bug-ion-menu-ssr/ionicframework-bug-ion-menu-ssr/dist/app/server/main.js:27892:7)

TypeError: Cannot read property 'whenDefined' of null
    at /ext/git/github/jicasada/ionicframework-bug-ion-menu-ssr/ionicframework-bug-ion-menu-ssr/dist/app/server/main.js:42769:34
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/ext/git/github/jicasada/ionicframework-bug-ion-menu-ssr/ionicframework-bug-ion-menu-ssr/dist/app/server/main.js:149520:24)
    at _next (/ext/git/github/jicasada/ionicframework-bug-ion-menu-ssr/ionicframework-bug-ion-menu-ssr/dist/app/server/main.js:149542:9)
    at /ext/git/github/jicasada/ionicframework-bug-ion-menu-ssr/ionicframework-bug-ion-menu-ssr/dist/app/server/main.js:149549:7
    at new ZoneAwarePromise (/ext/git/github/jicasada/ionicframework-bug-ion-menu-ssr/ionicframework-bug-ion-menu-ssr/dist/app/server/main.js:147605:23)
    at /ext/git/github/jicasada/ionicframework-bug-ion-menu-ssr/ionicframework-bug-ion-menu-ssr/dist/app/server/main.js:149538:12
    at Menu.connectedCallback (/ext/git/github/jicasada/ionicframework-bug-ion-menu-ssr/ionicframework-bug-ion-menu-ssr/dist/app/server/main.js:42780:11)
    at safeCall$1 (/ext/git/github/jicasada/ionicframework-bug-ion-menu-ssr/ionicframework-bug-ion-menu-ssr/dist/app/server/main.js:27714:20)
    at fireConnectedCallback (/ext/git/github/jicasada/ionicframework-bug-ion-menu-ssr/ionicframework-bug-ion-menu-ssr/dist/app/server/main.js:27892:7)`

### Expected Behavior

No exception

### Steps to Reproduce

Run the following commnds:
`git clone https://github.com/jicasada/ionicframework-bug-ion-menu-ssr.git`
`cd ionicframework-bug-ion-menu-ssr`
`npm install`
`npm run dev:ssr`

Access to http://localhosth:4200 

### Code Reproduction URL

https://github.com/jicasada/ionicframework-bug-ion-menu-ssr

### Ionic Info

Ionic:

   Ionic CLI                     : 6.18.1 (/home/jicasada/.nvm/versions/node/v12.22.9/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.7
   @angular-devkit/build-angular : 13.0.4
   @angular-devkit/schematics    : 13.0.4
   @angular/cli                  : 13.0.4
   @ionic/angular-toolkit        : 5.0.3

Capacitor:

   Capacitor CLI      : 3.4.0
   @capacitor/android : not installed
   @capacitor/core    : 3.4.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v12.22.9 (/home/jicasada/.nvm/versions/node/v12.22.9/bin/node)
   npm    : 6.14.15
   OS     : Linux 5.11`

**Comment by liamdebeasi** [comment] 2022-02-14 23:25
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/24714. (Author mentions the 'whenDefined' error a few posts down).

**Closed by liamdebeasi** 2022-02-14 23:25 UTC
Labels: package: core, type: bug
