### ISSUE TITLE
bug: ion-toggle change twice

### ISSUE THREAD

**Issue by jongbonga** [ionic-team/ionic-framework#24138] opened 2021-10-31 19:26 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

`ionChange` event on `ion-toggle` fires twice

### Expected Behavior

the event should only fire once

### Steps to Reproduce

I'm really sorry about posting this issue and not being able to reproduce it on a blank app, but I cannot understand why it's happening, even after stripping the whole page from everything except the event.

The same issue was experienced [here](https://forum.ionicframework.com/t/ion-toggle-ionchange-triggered/139187/21) sometime this year.

My code is as simple as 

```
<ion-header>
  <ion-toolbar>
    <ion-buttons slot="start">
      <ion-menu-button></ion-menu-button>
    </ion-buttons>
    <ion-title>
      test
    </ion-title>
    <ion-toggle
      slot="end"
      [checked]="configQuery.select('online') | async"
      (ionChange)="updateOnlineStatus($event)"
    ></ion-toggle>
  </ion-toolbar>
</ion-header>
```
```
  updateOnlineStatus(event) {
    console.log(event.detail.checked);
  }
```

and for some reason, it fires twice every time without fail. with or without the `[checked]` value

### Ionic Info

```
Ionic:

   Ionic CLI                     : 6.18.0 (/Users/jonathan/.nvm/versions/node/v16.4.2/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.0-rc.1
   @angular-devkit/build-angular : 12.2.12
   @angular-devkit/schematics    : 12.2.12
   @angular/cli                  : 12.2.12
   @ionic/angular-toolkit        : 5.0.0
```

**Comment by liamdebeasi** [comment] 2021-11-01 15:53
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/24057.

**Closed by liamdebeasi** 2021-11-01 15:53 UTC
Labels: triage
