### ISSUE TITLE
bug: ion-input has no placeholder text when type="date" or type="datetime-local"

### ISSUE THREAD

**Issue by blakerouse** [ionic-team/ionic-framework#24557] opened 2022-01-11 20:56 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

`<ion-input type="date" placeholder="Open time" formControlName="start"></ion-input>`
`<ion-input type="datetime-local" placeholder="Open time" formControlName="start"></ion-input>`

Results in the "Open time" placeholder not being used. The input shows up with an empty placeholder.

### Expected Behavior

That the placeholder would show up in the input, before a date/time is selected.

### Steps to Reproduce

Create an ion-input with either of the following with the form value empty (tried both `undefined` and `null`) and neither resulted in the placeholder showing up.

`<ion-input type="date" placeholder="Open time" formControlName="start"></ion-input>`
`<ion-input type="datetime-local" placeholder="Open time" formControlName="start"></ion-input>`

### Ionic Info

```
Ionic:

   Ionic CLI                     : 6.18.1
   Ionic Framework               : @ionic/angular 6.0.2
   @angular-devkit/build-angular : 13.1.2
   @angular-devkit/schematics    : 13.1.2
   @angular/cli                  : 13.1.2
   @ionic/angular-toolkit        : 5.0.3

Capacitor:

   Capacitor CLI      : 3.3.4
   @capacitor/android : 3.3.4
   @capacitor/core    : 3.3.4
   @capacitor/ios     : 3.3.4

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v14.18.2
   npm    : 6.14.15
   OS     : macOS Big Sur
```

**Comment by liamdebeasi** [comment] 2022-01-12 16:04
Thanks for the issue. The `type="date"` or `type="datetime-local"` render a native `<input>` under the hood, placeholder is not a supported attribute. See "Supported common attributes" for an example: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local

While this is working as intended, this is not clear in the docs so I will be sure to update it.

**Comment by liamdebeasi** [comment] 2022-01-12 16:45
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/24567, and a fix will be available in an upcoming release of Ionic Framework.

**Closed** 2022-01-12 16:44 UTC
Labels: triage

**Comment by blakerouse** [comment] 2022-01-13 13:17
@liamdebeasi Thanks for the information. Glad it was added to the documentation that will make it clearer.

If anyone is wanting to get the placeholders to show up the following CSS works around the issue. I have it set only for iOS because Android does show a placeholder (not the value provided), but on IOS its just blank and looks incorrect without the following CSS.

```
ion-input[type="date"],
ion-input[type="time"] {
    &.ios:not(.has-value) {
        & > input {
            &::before{
                content: attr(placeholder);

                color: var(--placeholder-color);
                opacity: var(--placeholder-opacity);
            }
        }
    }
}
```
