### ISSUE TITLE
bug: When in the mobile browser an input field is selected on a page that has scrollable content, a double scroll can appear that blocks the user from scrolling the content, but instead scrolls the entire app

### ISSUE THREAD

**Issue by lvdkleij** [ionic-team/ionic-framework#25889] opened 2022-09-07 08:37 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

When in the mobile browser an input field is selected on a page that has scrollable content, a double scroll can appear that blocks the user from scrolling the actual content, but instead scrolls the entire app. So far, I've tested this in Safari and Chrome, both appear to have this issue.

https://user-images.githubusercontent.com/73385580/188830051-65020bc9-9534-48dd-8dc6-f7de6631867c.MP4

### Expected Behavior

I would expect that after selecting an input field, the user can only scroll the content, instead of the entire app.

### Steps to Reproduce

Create a new (blank) ionic project and add some scrollable content with an input field in the home.html file. 

Please see: https://github.com/lvdkleij/double-scroll-with-input for an example. You can also view a live demo here: https://double-scroll-with-input.web.app.

### Code Reproduction URL

https://github.com/lvdkleij/double-scroll-with-input

### Ionic Info

Ionic:

   Ionic CLI                     : 6.20.1 (/Users/lucasvanderkleij/.config/yarn/global/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.2.5
   @angular-devkit/build-angular : 14.2.1
   @angular-devkit/schematics    : 13.3.9
   @angular/cli                  : 14.2.1
   @ionic/angular-toolkit        : 6.1.0

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v16.14.0 (/usr/local/bin/node)
   npm    : 8.3.1
   OS     : macOS Monterey

### Additional Information

I've tried to solve it by changing several settings (e.g. scrollAssit, scrollPadding, fullscreen (in ion-content), scrollY (in ion-content), overflow: hidden in html and body), but with no luck.

**Comment by liamdebeasi** [comment] 2022-09-07 17:20
Thanks for the report. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/23001. This issue references PWAs, but it looks like it is also possible to reproduce this bug in mobile Safari. According to the WebKit team, there appears to be an issue where the document is scrollable when it should not be.

If you add a `scroll` event listener you should see that there are events emitted with `#document` as the target. Please follow the linked issue for updates.

**Closed by liamdebeasi** 2022-09-07 17:20 UTC
Labels: triage
