### ISSUE TITLE
The browser does not display 100% of the height of the site

### ISSUE THREAD

**Issue by KyDenZ** [ionic-team/ionic-framework#20178] opened 2019-08-01 22:30 UTC
Description of the problem:
I am currently going from Ionic 3 / Cordova to Ionic 4 / Capacitor. I use the Plugin Browser to display a site developed also with Ionic. And I realize that the Browser plugin does not display 100% of the page height.

Tabs are not displayed entirely.

![Simulator Screen Shot - iPhone Xs - 2019-08-02 at 00 20 34](https://user-images.githubusercontent.com/7247673/62331234-a0225780-b4bb-11e9-9bae-0e0ec638bd65.png)

Affected platform
- [?] Android
- [x] iOS

OS of the development machine
- [x] macOS

Capacitor version:
1.1.1

node version:
10.15.3

npm version:
6.4.1

Steps to reproduce:
Use the application generated by the CLI with the tabs, add the browser plugin, and open from an IOS emulator (Android to test). Then open the browser with url localhost: 8100.

Thanks

**Comment by jcesarmobile** [comment] 2020-01-09 17:30
I've reproduced with latest Ionic.
Moved to ionic repo since it's a problem on Ionic or tabs template.
The problem is the app is not properly displayed inside `SFSafariViewController` (that Capacitor uses in the Browser plugin).
It's not related to Capacitor, can happen on any app that uses `SFSafariViewController` as "in app browser" (such as twitter does, among others) 
Can be reproduced by tweeting this ionic app and opening the link
`https://debeasi-ionic.firebaseapp.com/`

**Comment by liamdebeasi** [comment] 2021-09-17 14:55
Thanks for the issue. I am going to close this issue as it looks like this was an old bug on iOS that has since been resolved. I can reproduce the issue on iOS 12 but cannot reproduce the issue on iOS 13 and newer.

I recommend updating to the latest version of iOS to receive this fix. Thanks!

**Closed by liamdebeasi** 2021-09-17 14:55 UTC
Labels: triage
