### ISSUE TITLE
bug: After switching month in ion-datetime, generateMonth() does not execute.

### ISSUE THREAD

**Issue by tatsuyasenbom** [ionic-team/ionic-framework#24406] opened 2021-12-15 01:22 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

# Google Chrome on Android 12
* In Chrome on Android, After switching month in ion-datetime, generateMonth() does not execute.
* Probably due to the above, the screen operation and screen display do not match.

https://user-images.githubusercontent.com/87968771/146105099-4cf29feb-69ee-4f68-9f22-d79dc16dede5.mp4

# Safari on iPhone iOS 15.1 or Windows10
* However, it will be reflected correctly in Google Chrome on Windows or Safari on iOS.

https://user-images.githubusercontent.com/87968771/146105303-4a583ba0-8d09-4822-8875-fe36c0cda4a8.mp4

### Expected Behavior

I want you to improve the behavior of Google Chrome on Android.

### Steps to Reproduce

1. Run the code below to build.
    ```html
    <ion-label>{{ report_date | date:"yyyy年MM月dd日 (EEE)" }}</ion-label>
    <ion-popover [isOpen]="isPopover" arrow="false" style="--offset-y: -35%;">
      <ng-template>
        <ion-datetime (ionChange)="onChangeDate($event)" showDefaultTitle="true" presentation="date">
          <div slot="title">報告日</div>
        </ion-datetime>
      </ng-template>
    </ion-popover>
    ```
2. I did the same operation as the video I uploaded to Current Behavior.

### Ionic Info

```powershell
Ionic:

   Ionic CLI                     : 6.18.1 (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.0.0
   @angular-devkit/build-angular : 12.2.14
   @angular-devkit/schematics    : 12.2.14
   @angular/cli                  : 12.2.14
   @ionic/angular-toolkit        : 5.0.3

Capacitor:

   Capacitor CLI      : 3.2.5
   @capacitor/android : 3.3.3
   @capacitor/core    : 3.2.5
   @capacitor/ios     : 3.3.3

Utility:

   cordova-res : 0.15.4
   native-run  : 1.5.0

System:

   NodeJS : v14.17.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.13
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment] 2021-12-15 14:14
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/24305.

**Closed by liamdebeasi** 2021-12-15 14:14 UTC
Labels: triage
