### ISSUE TITLE
feat: Modal OnBackdropDismiss handler

### ISSUE THREAD

**Issue by serridavide** [ionic-team/ionic-framework#22902] opened 2021-02-10 08:36 UTC
# Feature Request

**Ionic version:**
[x] **4.x**

**Describe the Feature Request**

Ionic modal dismiss from backdrop data passing. In line with modalController.dismiss(data).

**Describe Preferred Solution**
OnBackdropDismiss event handler into the modal component to set the data. Data will be returned into OnDidDismiss() and related handlers just like the regular dismiss.

**Describe Alternatives**
A new handling system related to the regular dismiss for the backdrop, with a OnDidBackdropDismiss, OnBackdropDismiss,OnBackdropWillDismiss and so on. Not ideal but would get the job done.

**Related Code**

```
public dismiss() {
    // using the injected ModalController this page
    // can "dismiss" itself and optionally pass back data
    this.modalController.dismiss({
      data: this.data    });
  }

this.modalController.OnBackdropDismiss({
data: this.data});
```

**Additional Context**

**Comment by liamdebeasi** [comment] 2021-02-10 14:25
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/21979.

**Closed by liamdebeasi** 2021-02-10 14:25 UTC
Labels: triage
