### ISSUE TITLE
feat(ion-input): outlined floating and stacked 

### ISSUE THREAD

**Issue by indraraj26** [ionic-team/ionic-framework#22670] opened 2020-12-13 13:54 UTC
# Feature Request

**Ionic version:**

[x] **5.x**

**Describe the Feature Request**

I would like to have this kind of input without playing with css. It would be great to have this in core.
![image](https://user-images.githubusercontent.com/23274631/102013742-04278200-3d78-11eb-9969-feced06af723.png)
spec link: https://material.io/components/text-fields

**Describe Preferred Solution**

new property on ion-input fill="outline" by default solid
example : https://ionicframework.com/docs/api/button
We will have to make sure that it works great with ion-item so that we can add icon (slot start | end) inside the ion-input

**Describe Alternatives**

**Related Code**

**Additional Context**

**Comment by liamdebeasi** [comment] 2020-12-14 14:41
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/19619.

**Closed by liamdebeasi** 2020-12-14 14:41 UTC
Labels: triage
