### ISSUE TITLE
bug: Angular routerLink does not seem to take target in to account when using ion-item and ion-button

### ISSUE THREAD

**Issue by j-oppenhuis** [ionic-team/ionic-framework#28881] opened 2024-01-25 15:36 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v6.x, v7.x

### Current Behavior

Currently when using an `ion-item` and `ion-button` element in combination with `routerLink` and `target`, the target does not seem to be used. 

### Expected Behavior

The working should be the same as when using an `anchor` element. When for example `target` is set to `_blank` and `routerLink` is set to `/detail` a new tab should be opened in the browser. 

### Steps to Reproduce

```html
<!--This works-->
<a href="/orders/2" target="_blank">
  <ion-label>Anchor target _blank</ion-label>
</a>
<!--This does not-->
<ion-item routerLink="/orders/1" target="_blank">
  <ion-label>IonItem target _blank</ion-label>
</ion-item>
```

### Code Reproduction URL

https://stackblitz.com/edit/angular-rjzq6z-f5ejub?file=tsconfig.json

### Ionic Info

Ionic:

Ionic CLI : 7.1.1
Ionic Framework : @ionic/angular 7.2.3
@angular-devkit/build-angular : 16.2.0
@angular-devkit/schematics : 16.2.0
@angular/cli : 16.2.0
@ionic/angular-toolkit : 9.0.0

Capacitor:

Capacitor CLI : 5.1.1
@capacitor/android : 5.1.1
@capacitor/core : 5.1.1
@capacitor/ios : 5.1.1

Utility:

cordova-res : not installed globally
native-run : 1.7.2

System:

NodeJS : v16.19.0
npm : 8.19.3
OS : macOS Unknown

**Comment by swamyreddy54** [comment] 2024-01-26 07:13
<ion-item>
  <a [routerLink]="'/orders/1'" target="_blank">
    <ion-label>IonItem with Anchor target _blank</ion-label>
  </a>
</ion-item>

if possible try to add the anchor tag

**Comment by swamyreddy54** [comment] 2024-01-26 07:13
<ion-item>
  <a [routerLink]="'/orders/1'" target="_blank">
    <ion-label>IonItem with Anchor target _blank</ion-label>
  </a>
</ion-item>

**Comment by j-oppenhuis** [comment] 2024-01-26 15:48
In stackblitz I created a simple application with an anchor, ion-item and ion-button. You can find it here: https://stackblitz.com/edit/angular-rjzq6z-f5ejub?file=tsconfig.json

**Comment by sean-perkins** [comment] 2024-01-29 23:49
Hello @j-oppenhuis, thanks for the reproduction! I have identified that this bug is a duplicate of #26394.

Amanda previously mentioned it here: https://github.com/ionic-team/ionic-framework/issues/26394#issuecomment-1348786611, but with Ionic Framework focusing on mobile applications, we have not prioritized the behavior of opening content in a new tab within the context of a webview for our own components. 

I mentioned it in the [PR to add support for the anchor tag](https://github.com/ionic-team/ionic-framework/pull/25014), but if you are interested in submitting a fix for this issue, we will likely need to render an anchor around the element or within the shadow root to enable the functionality without excessive key listeners. 

I'm going to close this ticket in favor of the existing one. Feel free to upvote that issue if you would like to see it prioritized. 

Thanks!

**Closed by sean-perkins** 2024-01-29 23:49 UTC
Labels: triage
