### ISSUE TITLE
bug: ion-modal does not display with height: auto in Ionic 6

### ISSUE THREAD

**Issue by askilondz** [ionic-team/ionic-framework#25092] opened 2022-04-08 19:11 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Using a custom class in global.scss, cannot scale a modal's height based on its content. No modal content appears except the modal backdrop.

```js 
ion-modal {
    --background: #fff;

    &.auto-height {
        --border-radius: 16px;

        &::part(content) {
            width: 95vw;
            max-width: 450px;
            height: auto;
        }
    }
}
```

### Expected Behavior

Expect to be able to scale modal height automatically based on its content.

### Steps to Reproduce

Display a modal using the ModalController and set its class to use the .auto-height class in the css above.

### Ionic Info

Ionic CLI                     : 6.18.2
   Ionic Framework               : @ionic/angular 6.0.13
   @angular-devkit/build-angular : 13.2.6
   @angular-devkit/schematics    : 13.2.6
   @angular/cli                  : 13.2.6
   @ionic/angular-toolkit        : 6.1.0

**Comment by liamdebeasi** [comment] 2022-04-08 19:48
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/24080.

**Closed by liamdebeasi** 2022-04-08 19:48 UTC
Labels: triage
