### ISSUE TITLE
bug: datetime drop-down Month Day picker does not allow year selection past current year (ionic 6.3.6)

### ISSUE THREAD

**Issue by richardkshergold** [ionic-team/ionic-framework#26270] opened 2022-11-11 15:11 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

Running on iOS using Ionic 6.3.6 if I display the date picker and click on the Month and Year (top left) the drop-down appears displaying all months but only Years up to and including the current year.

### Expected Behavior

You should be able to select future years?

### Steps to Reproduce

Create an <ion-datetime> component and test the month / year drop-down

### Ionic Info

Ionic:

   Ionic CLI                     : 6.20.1 (/Users/xxx/.nvm/versions/node/v14.18.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.3.6
   @angular-devkit/build-angular : 13.2.6
   @angular-devkit/schematics    : 13.2.6
   @angular/cli                  : 13.2.6
   @ionic/angular-toolkit        : 5.0.3

Capacitor:

   Capacitor CLI      : 4.1.0
   @capacitor/android : 4.3.0
   @capacitor/core    : 4.3.0
   @capacitor/ios     : 4.3.0

Utility:

   cordova-res                          : 0.15.4
   native-run (update available: 1.7.1) : 1.6.0

System:

   NodeJS : v14.18.0 (/Users/xxx/.nvm/versions/node/v14.18.0/bin/node)
   npm    : 8.19.3
   OS     : macOS Monterey

**Comment by sean-perkins** [comment] 2022-11-11 16:18
Thank you for reporting this issue @richardkshergold.

I am going to close this as a duplicate of #25293. Feel free to upvote and track that issue.

**Closed by sean-perkins** 2022-11-11 16:18 UTC
Labels: triage
