### ISSUE TITLE
bug: IonModal ionic/react@v7 does not respond to click event

### ISSUE THREAD

**Issue by jaydenintusurg** [ionic-team/ionic-framework#28055] opened 2023-08-24 17:22 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

```
<IonModal
    isOpen={isOpen}
    onDidDismiss={closeModal}
>
  <div onClick={() => closeModal()>Click to close</div>
  <textarea
          value={message}
          onChange={handleInputChange}
          type='textarea'
   />
</IonModal>

const closeModal = () => setIsOpen(false);
```

I have code like above and when onclick the `closeModal` didn't get call at all. It felt like the modal has something transparent on top of it but what's weird is that I can click and type in the textarea no problem. It just doesn't respond to any click event.

### Expected Behavior

When onClick, the modal should close.

### Steps to Reproduce

Install ionic/react v7 and copy paste code above. Open chrome with mobile view, open the modal and try to close it. 

### Ionic Info

NA

**Comment by sean-perkins** [comment] 2023-08-24 22:33
@jaydenintusurg can you please provide a reproduction? I am unable to reproduce: https://stackblitz.com/edit/gmg8ka?file=src%2Fmain.tsx

As a best practice in accessibility, you should never have a click event attached to a div (unless you are manually specifying the aria-role and even here it is very discouraged). The appropriate interactable element is a `button` or `a` tag.

**Comment by jaydenintusurg** [comment] 2023-08-24 23:26
I notice you are using useRef to open and close the modal. In my repo, I am using useState instead. But even so I couldn't reproduce on stackblitz. Below is my attempt. Not sure if I am missing some kind of setup in my repo.

https://stackblitz.com/edit/gmg8ka-9ou1wq?file=src%2Fmain.tsx,src%2Findex.tsx,src%2FApp.tsx

**Comment by jaydenintusurg** [comment] 2023-08-24 23:43
After much experiement, looks like using <IonModal> along with other regular html tag is not sufficient. Wrapping IonModal with <IonApp> fixed the issue

**Comment by amandaejohnston** [comment] 2023-08-25 14:44
It sounds like you were able to resolve things on your end, so I'll go ahead and close this out. Let us know if you run into more trouble though, including a minimal Github repo or Stackblitz link reproducing the issue. Thank you!

**Closed by amandaejohnston** 2023-08-25 14:44 UTC
Labels: ionitron: needs reproduction
