### ISSUE TITLE
bug: Ion-picker

### ISSUE THREAD

**Issue by matteodib** [ionic-team/ionic-framework#26421] opened 2022-12-06 09:44 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [x] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x
- [ ] Nightly

### Current Behavior

As in the attachment if a user clicks a second time on the picker button this happens, one option goes above all the others
![ion picker bug](https://user-images.githubusercontent.com/81627423/205875632-bd91b610-9fbf-4fac-91c0-abddfa62302d.png)

### Expected Behavior

I would know if someone found some workaround on it.

### Steps to Reproduce

To reproduce the bug : click once on the picker, scroll down to another option then close it. Click again on the picker  

### Ionic Info

Ionic:

   Ionic CLI                     : 6.20.1 (C:\Users\matte\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.9.3
   @angular-devkit/build-angular : 12.1.4
   @angular-devkit/schematics    : 12.1.4
   @angular/cli                  : 12.1.4
   @ionic/angular-toolkit        : 4.0.0

Capacitor:

   Capacitor CLI      : 3.3.1
   @capacitor/android : 3.3.2
   @capacitor/core    : 3.4.1
   @capacitor/ios     : 3.4.0

Cordova:

   Cordova CLI       : not installed
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v16.16.0 (C:\Program Files\nodejs\node.exe)
   npm    : 8.11.0
   OS     : Windows 10

**Comment by liamdebeasi** [comment] 2022-12-06 14:12
Thanks for the report. I noticed you are running Ionic 5.9.3. Does this issue reproduce on Ionic 6? We no longer provide updates to Ionic 5.x.

**Comment by matteodib** [comment] 2022-12-06 14:44
Actually i don't know if it reproduces on Ionic 6..

**Comment by liamdebeasi** [comment] 2022-12-06 15:23
Glad to hear the issue is resolved by upgrading. I am going to close this, but let me know if you have any additional questions.

**Closed by liamdebeasi** 2022-12-06 15:23 UTC
Labels: triage
