### ISSUE TITLE
feat: Support disabling of scrollAssist on single <ion-input/searchbar/etc> elements

### ISSUE THREAD

**Issue by lincolnthree** [ionic-team/ionic-framework#23267] opened 2021-05-04 16:14 UTC
# Feature Request

**Ionic version:**

[x] **5.x**

**Describe the Feature Request**

Currently, `scrollAssist` is provided as an 'all or nothing' solution. It is either on for everything, or off for everything, unless I have missed something.

**Describe Preferred Solution**

It would be great if there were a way to override the global configuration on a per-input / searchbar / picker basis.

**Describe Alternatives**

None that I know of, but would love to know if this is already possible somehow.

**Related Code**

**Additional Context**

**Comment by liamdebeasi** [comment] 2021-05-04 17:14
Thanks for the issue. Could you provide an example of when having scroll assist on for everything causes issues?

**Comment by lincolnthree** [comment] 2021-05-04 22:24
@liamdebeasi Yes. I use a `position: sticky` `ion-searchbar` that floats at the top of most screens (see www.topdecked.com/cards for an example). 

Clicking on the searchbar w/scrollAssist causes the scroll position to be reset to the top of the view, since the searchbar is technically very close to the top of the DOM. 

However... scrolling is harmful in this scenario because it destroys the user's scroll position, and resets the virtual scroll element.)

**Comment by liamdebeasi** [comment] 2021-05-04 22:34
I am able to reproduce this when running as a PWA, but not the browser. Scroll assist should not be activating here since the input is fully in view. Are you able to create a minimal code reproduction of the issue? I can take a look and see if I can get scroll assist working better with sticky inputs.

**Comment by lincolnthree** [comment] 2021-05-05 15:19
@liamdebeasi Ah right. That's correct - so sorry. It only happens in PWA mode. For minimal repro, currently swamped - I am not 100% sure if/when I'll be able to get to it. (Sorry to be that guy on this issue.)

**Comment by liamdebeasi** [comment] 2021-05-06 13:02
No problem -- whenever you can! Our GitHub bot may automatically close this issue out after some time, but if you get a reproduction after that happens feel free to just open a new issue and reference this one.

**Closed** 2021-05-20 13:19 UTC
Labels: needs: reply
