### ISSUE TITLE
bug: ionInfinite event not triggering within rx-angular virtual scroller using ion-content-scroll-host

### ISSUE THREAD

**Issue by drakedeatonuk** [ionic-team/ionic-framework#28234] opened 2023-09-26 12:14 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Currently the below code (taken from the code reproduction provided further below) does not trigger the `ionInfinite` event when the `ion-infinite-scroll` is scrolled to:

```
  <rx-virtual-scroll-viewport scrollWindow [itemSize]="80" class="ion-content-scroll-host">
    <ion-infinite-scroll class="ion-infinite-scroll tw-mt-4 tw-pb-3" (ionInfinite)="onIonInfinite($event)"
      position="top" threshold="15%">
      <ion-infinite-scroll-content class="tw-mb-16" loadingSpinner="crescent"> </ion-infinite-scroll-content>
    </ion-infinite-scroll>
    <div *rxVirtualFor="let item of items">
      <div style="height: 50px; background-color: palegreen; margin: 10px; height: 30px; width: 100%">
        <p style="color:black;">
          {{item}}
        </p>
      </div>
    </div>
  </rx-virtual-scroll-viewport>
```

### Expected Behavior

I would expect that when the `ion-infinite-scroll` is scrolled into view, that the `ionInfinite` event would be fired, triggering the `onIonInfinite` function.

### Steps to Reproduce

to reproduce the issue:
0. download the repo.
1. install deps.
2. run:
```
npx ng serve app --port 4200 --host localhost       
```
3. navigate to http://localhost:4200/
4. scroll up & down the page, and notice how NO console.log, 'in onIonInfinite' is printed to the console - thus no `ionInfinite` event is being triggered.

### Code Reproduction URL

https://github.com/drakedeatonuk/rx-angular-virtual-scroll-bug-reprod

### Ionic Info

Ionic:
   Ionic CLI                     : 7.1.1
   Ionic Framework               : @ionic/angular 7.4.1
   @angular-devkit/build-angular : 16.2.3
   @angular-devkit/schematics    : 16.2.3
   @angular/cli                  : 16.2.3
   @ionic/angular-toolkit        : not installed

Capacitor:
   Capacitor CLI      : 4.7.0
   @capacitor/android : not installed
   @capacitor/core    : not installed
   @capacitor/ios     : 4.7.0

Utility:
   cordova-res : not installed globally
   native-run  : 1.7.2

System:
   NodeJS : v19.8.1 (/opt/homebrew/Cellar/node/19.8.1/bin/node)
   npm    : 9.5.1
   OS     : macOS

### Additional Information

I'm wondering if it's a compatibility issue with the `@rx-angular/template` library? I'm  unsure how the `ion-content-scroll-host` works under the hood.

Haven't any useful links on this particular issue.

**Comment by liamdebeasi** [comment] 2023-09-26 13:09
Can you make your repo public?

**Comment by drakedeatonuk** [comment] 2023-09-26 13:11
woops, wrong link sorry @liamdebeasi - just updated it!

**Comment by drakedeatonuk** [comment] 2023-09-27 08:16
Gotchya - I've implemented what you've suggested and I can confirm that the child div is firing scroll events & that adding the `ion-content-scroll-host` class to that child div enables the `ionInfinite` event to fire as expected.

Thanks for the insight @liamdebeasi 🙏 much appreciated!

**Comment by liamdebeasi** [comment] 2023-09-27 13:19
Glad the issue is resolved! Going to close this thread out.

**Closed by liamdebeasi** 2023-09-27 13:19 UTC
Labels: triage
