### ISSUE TITLE
feat:  Tooltip Component

### ISSUE THREAD

**Issue by farisfaisalthena** [ionic-team/ionic-framework#23689] opened 2021-07-26 08:51 UTC
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Add a new tooltip component similar like Angular Material https://material.angular.io/components/tooltip/overview

### Describe the Use Case

Suitable to be used for Desktop

**Comment by liamdebeasi** [comment] 2021-07-26 12:36
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/14924.

**Closed by liamdebeasi** 2021-07-26 12:36 UTC
Labels: triage
