### ISSUE TITLE
feat: Option to place the app in the middle of the screen when running on browser

### ISSUE THREAD

**Issue by RRGT19** [ionic-team/ionic-framework#28012] opened 2023-08-16 22:48 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

When the application is running in the browser and on large monitors, the visual aspect leaves much to be desired due to the large width.

An example of the content in the center of the screen could be [Expedia](https://www.expedia.com/Hotel-Search?adults=2&d1=2023-08-26&d2=2023-08-30&destination=Brooklyn%2C%20New%20York%2C%20United%20States%20of%20America&endDate=2023-08-30&latLong=40.678177%2C-73.94416&regionId=177851&rooms=1&semdtl=&sort=RECOMMENDED&startDate=2023-08-26&theme=&useRewards=true&userIntent=), where they have the content perfectly centered and it is easier to read and manipulate regardless of the size of your monitor. Also, [booking](https://www.booking.com/searchresults.html?ss=Brooklyn%2C+New+York+State%2C+United+States&ssne=Dominican+Republic&ssne_untouched=Dominican+Republic&label=gen173nr-1FCAEoggI46AdIM1gEaD-IAQGYATG4AQfIAQzYAQHoAQH4AQOIAgGoAgO4Avej9aYGwAIB0gIkMThlZTc1YjEtNTU3ZC00YjY5LWJkOTQtNjc0YjBiMmE1YzI02AIF4AIB&aid=304142&lang=en-us&sb=1&src_elem=sb&src=index&dest_id=20085207&dest_type=city&ac_position=0&ac_click_type=b&ac_langcode=en&ac_suggestion_list_length=5&search_selected=true&search_pageview_id=9a2fa03bddc90008&ac_meta=GhA5YTJmYTAzYmRkYzkwMDA4IAAoATICZW46BGJyb29AAEoAUAA%3D&checkin=2023-08-25&checkout=2023-08-27&group_adults=2&no_rooms=1&group_children=0&sb_travel_purpose=leisure) is a good example.

### Describe the Use Case

Apart from having our mobile application published on the platforms, we also want to take advantage of the same code to deploy the application in web mode and offer our users the same experience.

![Screenshot 2023-08-16 at 6 38 09 PM](https://github.com/ionic-team/ionic-framework/assets/33521443/a99cc649-86ec-4acd-a807-0056b42d77cc)

By default, the `ion-split-pane` and the content inside the` ion-router-outlet` is very wide, mainly the `ion-router-outlet`. On 2k/4k monitors the experience and usability is very low, or at least for us.

I have seen that several developers have the same question and/or requirement and they try to do the famous workaround, but it doesn't work properly.

Apparently, it is a requirement among many of the developers who use Ionic and want to run the application in a browser.

### Describe Preferred Solution

Instead of trying to center the content myself, the famous workaround, I'd like an option that turns this mode on, perhaps by **adding a class** somewhere or some configuration in the `IonicModule`.

### Related Code

I have tried to do it myself with this CSS on `global.scss`. It seems to work perfectly, but I'm not sure if it will have implications with any Ionic component.

```scss
body {
  background-color: black;
}

ion-app {
  margin: 0 auto;
  max-width: 75rem;
}
```

![Screenshot 2023-08-16 at 6 35 33 PM](https://github.com/ionic-team/ionic-framework/assets/33521443/9c9c1ef9-4125-40dc-9674-2bbcfeff44e0)

**Demo here:**
https://github.com/RRGT19/ionic-demo-full-screen

The CSS is on [global.scss](https://github.com/RRGT19/ionic-demo-full-screen/blob/master/src/global.scss#L32)

**Comment by liamdebeasi** [comment] 2023-08-17 12:58
Hey there,

Ionic Framework is targeted for mobile applications, so adding desktop support is out of scope for the project. That being said, the CSS you are using is the approach I would recommend. You are modifying the `ion-app` container which all of your content will be rendered inside of. As a result, pretty much all components should account for that adjusted width.

One thing that might look a little weird are [Card Modals on iOS](https://ionicframework.com/docs/api/modal#card-modal) since we scale the presenting view when opening a modal. Other than that, everything should work as intended. I am going to close this, but let me know if you have questions.

**Closed by liamdebeasi** 2023-08-17 12:58 UTC
Labels: triage

**Comment by RRGT19** [comment] 2023-08-30 22:48
Hi @liamdebeasi 

Thank you for always being available to help us.

We want to use the App in browser mode to avoid going into web development completely from scratch. Right now, we have a problem that we haven't been able to fix via CSS.

The `ion-select` of type **popover** appears to not correctly recognize the width and height that `app-root` has.

![Screenshot 2023-08-30 at 6 40 55 PM](https://github.com/ionic-team/ionic-framework/assets/33521443/576b3d3e-2873-4b84-aa41-8eaad51926f8)

Options appear very low on the screen, and sometimes very far to the right. It is never central and just below the ion-select. I hope you don't mind taking a look, maybe there is some other CSS property in `app-root` that we need to adjust. We have tried several things, but none have worked.

![Screenshot 2023-08-30 at 6 45 21 PM](https://github.com/ionic-team/ionic-framework/assets/33521443/34902f0e-fb91-44fc-b74d-21bb0d8b3e93)

**Demo:**
https://github.com/RRGT19/ionic-demo-full-screen/tree/feature/tablet

Take a look at the [index.html](https://github.com/RRGT19/ionic-demo-full-screen/blob/feature/tablet/src/index.html#L40) and the [global.scss](https://github.com/RRGT19/ionic-demo-full-screen/blob/feature/tablet/src/global.scss) file.

Other types of `ion-select` seems to work properly, for example the `action-sheet` interface and the `default` style. But popover is not.

Thanks again for the support.

**Comment by liamdebeasi** [comment] 2023-08-31 14:32
Popover's position is calculated using [getBoundingClientRect()](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect) which provides size and position information relative to the viewport.

Popover also assumes that the app container matches the dimensions of the viewport. Since your app container does not match the dimensions of the viewport, you'll need to offset the popover position by however much you altered the app container by.

You can use popover's `--offset-y` CSS Variable to adjust the popover up or down based on your needs. For example, doing the following brings the popover closer to the trigger button:

```css
ion-popover {
  --offset-y: -88px;
}
```

I determined this value by calling `getBoundingClientRect` on the `.tablet` element and using the `top` result.

**Comment by RRGT19** [comment] 2023-08-31 19:07
@liamdebeasi 

Thanks a lot for the recommendation. I can see the information of `document.getElementsByClassName("tablet")[0].getBoundingClientRect();` to get the values to set the offset.

However, depending on the width of the viewport, how long or how short the `ion-select` options are, it behaves differently. The offset configured to resolve 1 case does not apply to all the others. For example, if the select is at the top of the screen (first element in ion-content, it works fine. But if the select is at the bottom, it doesn't work very well and even goes off screen instead of showing above the `ion-select`.

I was thinking that maybe it's better to try not to go against an established behavior and just change the `interface` of the `ion-select` to type `alert` when the platform is `browser`. Seems like a valid sacrifice given the different scenarios.

Thanks again for all your help so far.
