### ISSUE TITLE
bug: ion-note slot="error" not seen in items with checkbox

### ISSUE THREAD

**Issue by Marius-Romanus** [ionic-team/ionic-framework#24537] opened 2022-01-08 21:41 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Hi, new ion-note slot="error" not seen in items with checkbox. I don't know if it is a bug or it has not been added, but it will be interesting for forms and accept terms and conditions.

### Expected Behavior

They should appear the same as the items with inputs.

### Steps to Reproduce

```
<form [formGroup]="form">
      <ion-list>
        <ion-item>
          <ion-label position="floating">Text</ion-label>
          <ion-input formControlName="text" type="text"></ion-input>
          <ion-note slot="error">error text OK</ion-note>
        </ion-item>
        <ion-item>
          <ion-label>Terms</ion-label>
          <ion-checkbox slot="start" formControlName="terms"></ion-checkbox>
          <ion-note slot="error">error terms KO</ion-note>
        </ion-item>
      </ion-list>
    </form>
```

### Code Reproduction URL

https://stackblitz.com/edit/ionic-angular-v5-zehycf?file=src%2Fapp%2Fapp.component.html

### Ionic Info

Ionic:

   Ionic CLI : 6.18.1

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v17.3.0
   npm    : 8.3.0
   OS     : Windows 10

**Comment by amandaesmith3** [comment] 2022-01-14 16:29
Thanks for the issue. This looks like a duplicate of https://github.com/ionic-team/ionic-framework/issues/24445. I noticed that if I use `ion-label` instead of `ion-note`, the error message appears, as the OP there described. Feel free to post additional details on that thread.

**Closed by amandaesmith3** 2022-01-14 16:29 UTC
Labels: triage
