### ISSUE TITLE
bug: (Vue) Cannot use `router-direction` on a `router-link` element

### ISSUE THREAD

**Issue by GC-Mark** [ionic-team/ionic-framework#22815] opened 2021-01-25 16:21 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

The following works, but `router-direction` is ignored...

```html
<router-link class="relative block" router-direction="root" :to="{ name: 'search' }">
  <div class="py-4 text-sm font-bold uppercase">Search</div>
</router-link>
```

With the following, the router-direction is respected...

```html
<ion-item router-link="/search" router-direction="root">
  <div class="py-4 text-sm font-bold uppercase">Search</div>
</ion-item>
```

**Expected behavior:**

`router-direction` should be respected when set via `router-link`.

**Steps to reproduce:**
See above

**Related code:**

```
See above
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.12.3 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 5.6.0-dev.202101081806.8564071

Capacitor:

   Capacitor CLI   : 3.0.0-beta.1
   @capacitor/core : 3.0.0-beta.1

Utility:

   cordova-res : not installed
   native-run  : 1.3.0

System:

   NodeJS : v12.20.0 (/usr/local/bin/node)
   npm    : 6.14.11
   OS     : macOS Big Sur
```

**Comment by liamdebeasi** [comment] 2021-01-25 17:05
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The `router-link` component is a Vue Router component, so it is not designed to work with `router-direction`. Instead, what you can do is use the `router-link` and `router-direction` properties on components such as `ion-button` or `ion-item`.

**Closed by liamdebeasi** 2021-01-25 17:05 UTC
Labels: triage

**Comment by JayBizzle** [comment] 2021-01-25 17:34
I thought as much. 

Is it possible to use named routes on the solutions you highlighted?

Thanks

**Comment by liamdebeasi** [comment] 2021-01-25 20:44
Yes, it should work:

```html
<ion-button :router-link="{ name: 'search' }">Search</ion-button>
```
