### ISSUE TITLE
bug: Ionic 5 Angular 12 Routing issue with previous component not destroyed and back to previous page

### ISSUE THREAD

**Issue by veeravetrivel** [ionic-team/ionic-framework#23765] opened 2021-08-12 04:10 UTC
### Prequisites

- [ ] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

- Angular routing `this.router.navigate(['/login']);` while navigating its navigated but the previous view is not destroyed.
- While coming back to previous page the OnInit and constructor is not fired.
- Global variable declared has the same value its has before routing
- In the DOM previous page is also available.

### Expected Behavior

- Once navigating to other page `this.router.navigate(['/login']);` the previous view must be destroyed and ngOnDestroy must me called.
- Once came back to the previous view component must be rendered from first from OnInit and Global variables as declared at top. 

### Steps to Reproduce

1. At first at page at initial routing /login
2. Then navigated to `this.router.navigate(['/dashboard']);`
3. Again navigating to `this.router.navigate(['/login']);`
4. Login Component ngOnInit and constructor is not fired and Global variable value remains in last state.

@liamdebeasi

**Comment by liamdebeasi** [comment] 2021-08-12 12:32
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. This is the intended behavior in Ionic Angular applications. Pages are only removed from the DOM when they are "popped", for instance, by pressing the back button in the UI or the browser's back button.

Our documentation explains how lifecycles work in Ionic Framework. I recommend reading it as it covers many of the behaviors you are reporting: https://ionicframework.com/docs/angular/lifecycle

**Closed by liamdebeasi** 2021-08-12 12:32 UTC
Labels: triage
