### ISSUE TITLE
bug: Navigation "freeze"

### ISSUE THREAD

**Issue by migo315** [ionic-team/ionic-framework#24530] opened 2022-01-07 12:57 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [X] v6.x

### Current Behavior

I have already noticed for months that sporadically the navigation is "frozen" when clicking back. Today I could identify a click path where this always occurs.

Here a Video: https://youtu.be/5_T19qqz3_w

Click path in video:

1. Start Component A
2. Click to Component B
3. Click to Component C1
4. Click to Component D1
5. Click to Component E
6. Back to Component D1 -> C1 -> B
9. Click to Component C2
10. Click to Component D2
11. Back to Component C2  <-- Now frozen. It seems, that component B is removed instead component D2.

It's happen with Ionic 5 (5.9.3) and 6 (6.0.1), with and without route animations. Interestingly, it does not occur when I use createMemoryHistory. With createWebHistory and createWebHashHistory the error occurs. 

### Expected Behavior

When I click back, I also see the previous page.

### Steps to Reproduce

Use this click path with the sample project I created:
1. Start Component A
2. Click to Component B
3. Click to Component C1
4. Click to Component D1
5. Click to Component E
6. Back to Component D1 -> C1 -> B
9. Click to Component C2
10. Click to Component D2
11. Back to Component C2  <-- Now frozen. It seems, that component B is removed instead component D2.

### Code Reproduction URL

https://github.com/migo315/ionic-bug

### Ionic Info

Ionic:

   Ionic CLI       : 6.12.3 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 6.0.1

Utility:

   cordova-res (update available: 0.15.4) : 0.15.3
   native-run                             : 1.5.0

System:

   NodeJS : v14.15.1 (/usr/local/bin/node)
   npm    : 7.20.1
   OS     : macOS Big Sur

**Comment by PhungDuyAnh** [comment] 2022-01-07 13:12
Great

**Comment by migo315** [comment] 2022-01-11 21:46
I should also mention that the above click path is for reproduction. 

There are numerous click combination that "accidentally" lead to this error. In apps with some navigation levels, it's probably only a matter of time before users suddenly can't navigate anymore. Basically, the user only needs to use the navigation long enough in an app with deeper levels.

**Comment by liamdebeasi** [comment] 2022-01-12 16:51
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/23873 (same underlying issue).

**Closed by liamdebeasi** 2022-01-12 16:51 UTC
Labels: holiday triage
