### ISSUE TITLE
bug: ion-button fill="clear" type make faded when hover the button, is there any soluation to avoid that?

### ISSUE THREAD

**Issue by herobarua** [ionic-team/ionic-framework#24151] opened 2021-11-02 15:19 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

Current now in chrome browser, using ion-button fill type "clear" it going to fade

### Expected Behavior

it need to fade our or normal again when cursor out the button

### Steps to Reproduce

just use button like 
<ion-buton fill="clear">Test Button</ion-button>
![image](https://user-images.githubusercontent.com/1532317/139876135-02556eb2-a6e7-48f7-b0f6-d71c985c36bd.png)

### Ionic Info

Ionic:

   Ionic CLI                     : 6.16.3 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.4.0
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 9.0.6
   @angular/cli                  : 8.3.26
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : android 9.1.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 18 other plugins)

Utility:

   cordova-res (update available: 0.15.3) : 0.15.1
   native-run (update available: 1.5.0)   : 0.2.8

System:

   ios-deploy : 1.11.4
   ios-sim    : 8.0.2
   NodeJS     : v14.16.1 (/usr/local/bin/node)
   npm        : 6.14.12
   OS         : macOS Big Sur
   Xcode      : Xcode 13.0 Build version 13A233

### Additional Information

Here below image where it faded after hover the button, it not only this place,it all over the app when using chrome browser.
![image](https://user-images.githubusercontent.com/1532317/139875459-bba046d3-5a30-4552-b2b8-fd17cec38a6d.png)

**Comment by herobarua** [comment] 2021-11-02 17:54
Here starter package and image screenshot
[photo-gallery.zip](https://github.com/ionic-team/ionic-framework/files/7463001/photo-gallery.zip)
![139876135-02556eb2-a6e7-48f7-b0f6-d71c985c36bd](https://user-images.githubusercontent.com/1532317/139919392-4cd11b26-02f3-4efc-89ff-91bc7f2f42dc.png)

**Comment by MarkChrisLevy** [comment] 2021-11-14 09:47
Duplicate #24140

**Comment by liamdebeasi** [comment] 2021-11-15 18:34
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/24140.

**Closed by liamdebeasi** 2021-11-15 18:34 UTC
Labels: ionitron: needs reproduction
