### ISSUE TITLE
bug: attachShadow property on ion-acordion is not exported from stencil

### ISSUE THREAD

**Issue by andirsun** [ionic-team/ionic-framework#24154] opened 2021-11-02 20:36 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

My project does not compile since yesterday, this is the bug 
```
Failed to compile.

./node_modules/@ionic/core/components/ion-accordion.js
Attempted import error: 'attachShadow' is not exported from '@stencil/core/internal/client'.

```

### Expected Behavior

Compile normal way

### Steps to Reproduce

Update to last version RC.1

**Comment by liamdebeasi** [comment] 2021-11-02 21:15
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/24153.

Please see https://github.com/ionic-team/ionic-framework/issues/24153#issuecomment-958052376.

**Closed by liamdebeasi** 2021-11-02 21:15 UTC
Labels: triage
