### ISSUE TITLE
bug: ion-datetime multiple property changes month view based on first selection

### ISSUE THREAD

**Issue by chawes13** [ionic-team/ionic-framework#28859] opened 2024-01-19 18:59 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When using the `multiple` property on the `ion-datetime` element, the calendar automatically flips the user back to the month where the first date was selected.

### Expected Behavior

The month view of the calendar should not automatically change on a user.

### Steps to Reproduce

1. Render `<IonDatetime multiple={true} />`
2. Select a date in the month first displayed
3. Toggle to the next month
4. Select a date
5. Calendar automatically switches back to the month first displayed

### Code Reproduction URL

https://stackblitz.com/edit/dmuthj

### Ionic Info

Ionic:

   Ionic CLI : 5.4.16

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v18.18.0
   npm    : 10.2.3
   OS     : Linux 5.0

### Additional Information

Recording: https://share.zight.com/E0uJEvqJ

This behavior isn't present on our production app, which is running `7.0.4`.

**Comment by liamdebeasi** [comment] 2024-01-19 19:11
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/28602. We merged a fix in recently, so it will be available in an upcoming release of Ionic.

**Closed by liamdebeasi** 2024-01-19 19:11 UTC
Labels: triage

**Comment by chawes13** [comment] 2024-01-19 19:36
Oh shoot I only searched open existing issues 🤦 🤦 . Sorry about that!
