### ISSUE TITLE
bug: Search Button on Keyboard not working iOS

### ISSUE THREAD

**Issue by farisfaisalthena** [ionic-team/ionic-framework#22839] opened 2021-01-29 16:33 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
When using the iOS keyboard and pressing on search, it does not respond in the app as shown [here](https://www.youtube.com/watch?v=AqieY2LJCEg)

**Expected behavior:**
When clicking the search button, it should start searching based on the logic provided in the ts file

**Steps to reproduce:**
1. Create an empty ionic app
2. add searchbar
3. run on native device

**Related code:**
In Html template
` <ion-searchbar enterkeyhint="search" placeholder="Search for a player" [(ngModel)]="searchTerm">
      </ion-searchbar>`
In ts file
`  searchPlayer() {
    this.isLoading = true;
    if (this.searchTerm == '') {
      this.showToastMessage('Search field cannot be empty!', 'danger')
      this.isLoading = false
    } else if (this.searchTerm != '') {
      this.apiSvc.getStatistics(this.searchTerm).subscribe(res => {
        this.statistics$ = res
        this.isLoading = false;
      });
    }
  }`

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.12.3 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.5.3
   @angular-devkit/build-angular : 0.1101.2
   @angular-devkit/schematics    : 11.0.5
   @angular/cli                  : 11.1.2
   @ionic/angular-toolkit        : 3.0.0

Capacitor:

   Capacitor CLI   : 2.4.6
   @capacitor/core : 2.4.6

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v14.15.4 (/usr/local/bin/node)
   npm    : 6.14.10

```

**Comment by liamdebeasi** [comment] 2021-01-29 17:07
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. Your `ion-searchbar` does not have a keypress binding, so pressing the "search" key is not going to do anything. To fix this, you could probably do the following: `<ion-searchbar (keydown.enter)="onKeydown($event)">...`.

**Closed by liamdebeasi** 2021-01-29 17:07 UTC
Labels: triage
