### ISSUE TITLE
ion-fab-list with texts

### ISSUE THREAD

**Issue by bodinaren** [ionic-team/ionic-framework#17586] opened 2019-02-22 21:08 UTC
# Feature Request

**Ionic version:**
[x] **4.x**

**Describe the Feature Request**
I'd like to see the `ion-fab-list` having support for texts or other content besides just `ion-fab-button`. In my case I would like to show texts.

**Describe Preferred Solution**
As a matter of fact, you _can_ already have text instead of icons pretty easily by using an `ion-button` inside instead of an `ion-fab-button`. It's a simple matter of adding two extra styles as shown below.

**Related Code**
[Stackblitz example](https://stackblitz.com/edit/ionic-4-template-pn5vbt?file=src%2Fapp%2Fhome%2Fhome.page.css)

This is the relevant CSS:
```
ion-fab[horizontal="start"] ion-fab-list {
  left: 0;
  align-items: flex-start;
}

ion-fab[horizontal="end"] ion-fab-list {
  right: 0;
  align-items: flex-end;
}
```

It does need slightly more advanced styling that what I've done here. It'd need to adjust for RTL, and you might also want to limit it to `ion-fab-list[side="top"]` and `ion-fab-list[side="bottom"]` as they're the only two cases where this makes sense.

**Additional**
I would be willing to submit a PR for this if approved.

**Comment by djuerges** [comment] 2020-05-22 21:36
needing this in v5+

**Comment by Keelback** [comment] 2021-02-02 08:33
Hope that it will come soon.
The problem is also discussed here: https://forum.ionicframework.com/t/ionic-tutorial-beautiful-custom-tabs-with-custom-icons/177780

**Comment by liamdebeasi** [comment] 2022-09-02 16:19
Hi everyone,

At the moment we do not have plans to implement this. The [Material Design spec for Floating Action Buttons](https://material.io/components/buttons-floating-action-button#anatomy) states that regular FABs should not have text. (See the "Icon" section).

There is an option for extended FABs (https://material.io/components/buttons-floating-action-button#extended-fab) but this appears to be different than what is being requested here. If developers want extended FABs to be added to Ionic, I recommend following https://github.com/ionic-team/ionic-framework/issues/21526.

I am going to close this for now, but let me know if there are any questions. Thank you!

**Closed by liamdebeasi** 2022-09-02 16:19 UTC
Labels: type: feature request, package: core

**Comment by ingljo** [comment] 2022-09-02 20:13
Ok, thats fair enough.

In my case I needed to get a label beside the icon, as shown in the specc
attached.

But I solved it by creating my own component.

Keep up the good work.
Best regards

**Comment by ingljo** [comment] 2022-09-02 20:15
![Screenshot_20220902-220658_Chrome](https://user-images.githubusercontent.com/4353623/188229484-548fa3ca-afde-49ac-ac64-275cc5365263.jpg)
