### ISSUE TITLE
bug: input blurring utility causes non input and textarea elements to be blurred

### ISSUE THREAD

**Issue by jkyoutsey** [ionic-team/ionic-framework#29072] opened 2024-02-19 14:27 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

In an Ionic Angular application with video.js installed at latest (8.10.x) when running in either Chrome with DevTools in mobile device mode, or actually running on a device (simulator in xcode or deployed to a mobile device) the playback rates button will open and then immediately close the menu with the rate buttons in it. Sometimes a longer press will cause it to stay open, but a tap is always an immediate open/close. This ONLY happens in an Ionic app. Outside of Ionic the videojs menus work perfectly.

### Expected Behavior

When clicking on a videojs control button Ionic doesn't interfere with videojs behavior.

### Steps to Reproduce

1. Follow the instructions in the readme on the linked repo

### Code Reproduction URL

https://github.com/jkyoutsey/ionic-videojs-playback-rates-flicker-bug

### Ionic Info

Ionic:

   Ionic CLI : 7.2.0

Utility:

   cordova-res : not installed globally
   native-run  : 2.0.1

System:

   NodeJS : v20.11.1
   npm    : 10.2.4
   OS     : macOS Unknown

**Comment by liamdebeasi** [comment] 2024-02-29 14:38
Thanks, I can reproduce this. [This blur call](https://github.com/ionic-team/ionic-framework/blob/5a5f330705f77a8971119fad448101a5504d8e5e/core/src/utils/input-shims/hacks/input-blurring.ts#L47) appears to be causing the behavior. My understanding of this utility is that it's only applicable to text inputs, so [this line seems suspect](https://github.com/ionic-team/ionic-framework/blob/5a5f330705f77a8971119fad448101a5504d8e5e/core/src/utils/input-shims/hacks/input-blurring.ts#L30) because it implies that only inputs and textarea should be blurred. However, the way this code is written ensures that the opposite happens.

**Comment by liamdebeasi** [comment] 2024-02-29 14:55
As a temporary workaround, you can set `inputBlurring: false` in `provideIonicAngular`.

**Comment by liamdebeasi** [comment] 2024-03-01 17:22
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/29104, and a fix will be available in an upcoming release of Ionic Framework. In Ionic 8 we will be disabling this utility by default which should resolve the issue reported here. In the meantime, you can use the workaround I [mentioned above](https://github.com/ionic-team/ionic-framework/issues/29072#issuecomment-1971316987).

**Closed by liamdebeasi** 2024-03-01 17:22 UTC
Labels: package: core, type: bug
