### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by krystof018** [ionic-team/ionic-framework#26147] opened 2022-10-17 17:45 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

When I run `ionic serve` and change any file in my docker enviroment. Page doesn't reload or change its contents after manual reload, I must stop the process and run `ionic serve` again. Everything works correctly when I change the file using for example nano inside the container. 

### Expected Behavior

Page should reload just fine even when changing the file in the host system

### Steps to Reproduce

Run docker compose up in attatched repo. Edit any file.

### Code Reproduction URL

https://github.com/krystof018/ionic-no-update-error

### Ionic Info

```
[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package'
       
       Require stack:
       - /usr/lib/node_modules/@ionic/cli/lib/project/index.js
       - /usr/lib/node_modules/@ionic/cli/lib/index.js
       - /usr/lib/node_modules/@ionic/cli/index.js
       - /usr/lib/node_modules/@ionic/cli/bin/ionic
[WARN] Error loading @capacitor/android package.json: Error: Cannot find module '@capacitor/android/package'
       
       Require stack:
       - /usr/lib/node_modules/@ionic/cli/lib/project/index.js
       - /usr/lib/node_modules/@ionic/cli/lib/index.js
       - /usr/lib/node_modules/@ionic/cli/index.js
       - /usr/lib/node_modules/@ionic/cli/bin/ionic

Ionic:

   Ionic CLI       : 6.16.1 (/usr/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 6.3.2

Capacitor:

   Capacitor CLI      : 4.3.0
   @capacitor/android : not installed
   @capacitor/core    : 4.3.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.1

System:

   NodeJS : v14.16.1 (/usr/bin/node)
   npm    : 6.14.12
   OS     : Linux 5.10

```

**Comment by liamdebeasi** [comment] 2022-10-17 18:35
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The Vue CLI handles live reload, not Ionic. (The `ionic serve` command is a wrapper for `vue-cli-service serve`). I recommend posting an issue on the [Vue CLI GitHub repo](https://github.com/vuejs/vue-cli) instead. Alternatively, you could post on the [Ionic Forum](https://forum.ionicframework.com/) if you want additional assistance debugging the issue. Let me know if you have any questions.

**Closed by liamdebeasi** 2022-10-17 18:35 UTC
Labels: triage
