### ISSUE TITLE
bug: ionic 6 menu gesture is not working good on RTL app

### ISSUE THREAD

**Issue by nadavhalfon** [ionic-team/ionic-framework#25842] opened 2022-08-28 01:21 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

When setting dir="rtl" on the html tag inside 'index.html', the ionic menu swipe gesture has problems, instead of 'menu-swipe' gesture the ionic reacts to the swipe as 'goback-swipe' (according to gesture controller debug).
This means RTL apps can't use menu which located at site="start"

### Expected Behavior

The swiping gestures should work on RTL app which has menu located with side="start"

### Steps to Reproduce

Set on the html tag dir="rtl", and place site="start" on the ion-menu

### Ionic Info

    "@ionic/angular": "^6.2.4",
    "@ionic/pwa-elements": "^3.1.1",
    "@capacitor/core": "^4.0.1",
    "@capacitor/ios": "^4.0.1",
    "@capacitor/android": "^4.0.1",

**Comment by liamdebeasi** [comment] 2022-08-29 13:13
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/19489.

**Closed by liamdebeasi** 2022-08-29 13:13 UTC
Labels: triage
