### ISSUE TITLE
bug: scrolling should not cause range to move

### ISSUE THREAD

**Issue by fudom** [ionic-team/ionic-framework#28844] opened 2024-01-17 15:14 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- v6.x
- v7.x

### Current Behavior

If you have `ion-range` in a scrolling container, the range is changed when you trying to scroll.
If an [ion-range](https://ionicframework.com/docs/v6/api/range) is in a scroll container, the range will change when you want to scroll. That's really annoying. You don't want to change any value, when you only want to scroll.

### Expected Behavior

Scrolling should be possible without changing the range.

### Steps to Reproduce

In my case, I have a popover with a list of input items and a range included. When try to scroll. See code link below.

The weird thing is, that every implementation with the same Ionic version works a bit different. In my app, when you try to scroll and hit the range at beginning, the scrolling is completly blocked and instead the range is moving. In Stackblitz example, scrolling and range moving is at same time. But anyway... I looking for a solution to block accidentally value changed by range on scrolling. Currently I thining about toggle enable/disable with a click on a range. Maybe not the best UX but better than unwanted changes. What do you think? 

DL;TR: The range should not move when a container is scrolled. (touch)

### Code Reproduction URL

Ionic 6: https://stackblitz.com/edit/ionic6-angular14-4cu2m9?file=src%2Fapp%2Fapp.component.html
Ionic 7: https://stackblitz.com/edit/ionic7-angular14-6rxgf7?file=src%2Fapp%2Fapp.component.html

![demo](https://github.com/ionic-team/ionic-framework/assets/143608856/0e80487c-63d6-429e-ad2c-e478770ee19d)

Again: In my app: When I try to scroll, the scroll is blocked and only the range is moving. I don't know why, but it does not really matter. This is also not wanted behavior. How to prevent the range from moving during scrolling?

### Ionic Info

v6-lts and latest (v7) ng-v14 - tested in Chrome, Windows
(ionic info does not work in my repo.)

### Additional Information

Ref: #19004

**Comment by mapsandapps** [comment] 2024-01-17 15:38
Thank you for submitting this issue. I'm going to close this as a duplicate of #28487.

**Closed by mapsandapps** 2024-01-17 15:38 UTC
Labels: triage
