### ISSUE TITLE
bug: ion-menu within ion-modal causes overlapping part to disappear

### ISSUE THREAD

**Issue by tho-masn** [ionic-team/ionic-framework#23851] opened 2021-08-31 08:44 UTC
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

I have a use case, where I need to use ion-menu components within an ion-modal component for building kind of a navigation structure within a modal. To give some context, I use this approach mainly for selector components, where the modal contains a list of selected values, and clicking a value should trigger a menu for selecting a different value.

I know there is a similar approach by using the ion-nav component like shown here (https://dev.to/aaronksaunders/how-to-navigate-in-ionic-modals-with-ion-nav-in-vuejs-4emb), but it has some drawbacks so it doesn't fit for my use-case.

Anyway, the ion-menu approach works perfectly fine, except from a minor, but nasty UI glitch. As soon as the ion-menu within an ion-modal opens, AND the ion-modal uses a presenting-element, the overlapping part on top of the screen disappears, like shown in the screenrecording below (second 3):

https://user-images.githubusercontent.com/23264228/131471535-8fa022b1-2e56-40e4-8b3a-41d2fa7aed69.mov

### Expected Behavior

The overlapping section should be present, after showing the ion-menu within the ion-modal

### Steps to Reproduce

- Use ionic vue
- Create a modal and use the presenting-element option
- Add a menu to the modal
- Add a trigger in the modal to open the menu

### Code Reproduction URL

https://github.com/tho-masn/ionic-issues/tree/v5-ion-modal-subpage

**Comment by liamdebeasi** [comment] 2021-08-31 12:55
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. Given the current usage in your app, the `content-id` property on your `ion-menu` should refer to the `ion-content` inside of the modal, not your `ion-router-outlet`.

**Closed by liamdebeasi** 2021-08-31 12:55 UTC
Labels: triage

**Comment by tho-masn** [comment] 2021-08-31 13:29
Oh, wow - works like a charm! I was confused about the documentation, but now it makes sense.
Thanks for your quick reply.
