### ISSUE TITLE
bug: controlled IonInput get stuck when validation fails

### ISSUE THREAD

**Issue by tekno0ryder** [ionic-team/ionic-framework#27532] opened 2023-05-22 22:14 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

We are using a combination of `Ionic v7` + `react-hook-form` + `zod`, when trying to use a controlled version of`<IonInput>` whenever submitting the form and re-validation happens the input receives an old value instead of submitting the new one.

### Expected Behavior

The new value should be submitted.

### Steps to Reproduce
- Add a value
- Submit
- Remove the value
- Submit

Result: input will receive old value

### Code Reproduction URL

https://stackblitz.com/edit/react-ts-jjecqw?file=App.tsx

### Ionic Info

```
Ionic:

   Ionic CLI : 7.1.1

Utility:

   cordova-res                          : not installed globally
   native-run (update available: 1.7.2) : 1.7.1

System:

   NodeJS : v18.12.1
   npm    : 8.19.2
   OS     : macOS Unknown

```

### Additional Information

There is a workaround which is changing `reValidateMode` to `onSubmit`

**Comment by sean-perkins** [comment] 2023-05-24 02:09
Hello @tekno0ryder thanks for reporting this issue!

I'm not as experienced with react-hook-forms or using zod, but it appears that handling the `onChange` during `onIonInput` instead of `onIonChange`, behaves as you expect:

Forked reproduction: https://stackblitz.com/edit/react-ts-25eu97?file=App.tsx

Can you let me know if this is sufficient for your use case? I do not believe you can transform the value as part of the change event life cycle with `ion-input`, before the value is committed.

**Comment by tekno0ryder** [comment] 2023-05-24 08:23
Thanks @sean-perkins, that works as expected!

This need to be documented better since it was perfectly working on Ionic v6 so it's a break change.

**Comment by liamdebeasi** [comment] 2023-05-24 12:30
In Ionic 7 we updated `ionChange` and `ionInput` to behave more like the native `change` and `input` browser events, respectively.  The `ionChange` event now fires once the `value` of the input is changed by the user _and_ the input loses focus/the user presses enter.

This is documented as a breaking change: https://github.com/ionic-team/ionic-framework/blob/main/BREAKING.md#input

**Comment by thetaPC** [comment] 2023-06-03 00:12
Thank you for submitting the issue! I was able to replicate the issue. As mentioned prior, "the `ionChange` event now fires once the value of the input is changed by the user and the input loses focus/the user presses enter." Due to this, Zod picks up the old value.

In order to get the correct value, the code must be updated to use `setValue` instead of `onChange`:

```ts
const {
    handleSubmit,
    control,
    formState: { errors },
    setValue
  } = useForm({
    resolver: zodResolver(schema),
  });
...
<IonInput
   ...
   onIonChange={(event: any) => {
     setValue("name", event.detail.value);
   }}
   ...
/>
...
```

Closing this issue since can be resolved by using React Hook Form's `setValue()` [function](https://www.react-hook-form.com/api/useform/setvalue/).

**Closed by thetaPC** 2023-06-03 00:12 UTC
Labels: triage
