### ISSUE TITLE
bug: Ionic Vue Router: Navigation with query params does not work properly

### ISSUE THREAD

**Issue by Predarion** [ionic-team/ionic-framework#24289] opened 2021-12-01 06:45 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [X] v6.x

### Current Behavior

Currently, when routing back to a perviously visited page that with a query param, the URL gets messed up. I think the screenrecording explains it quite well:

https://user-images.githubusercontent.com/24892172/144184850-9874d7a8-6990-47c3-a524-20eb160b4d3c.mov

### Expected Behavior

When executing step 5, I expect to be routed to tab2/subpage having the path and query parameter set corretly, i.e. URL: 
```
http://localhost:8100/tabs/tabs2/subpage?test=this-is-a-test-value
```

### Steps to Reproduce

1. Run app in terminal using
```
ionic serve
```

2. go to http://localhost:8100
3. You will be redirect to Tab1. Now, press "Tab2" button in Tabbar
4. You will be routed to Tab2. Now press the RouterLink "Go to: /tabs/tab2/subpage"
5. You will be routed to Tab2Subpage. Now press "Tab1" button in Tabbar
6. You will be routed to Tab1. Now press "Tab2" button in Tabbar
7. Routing will now fail as the app tries to route to 
```
http://localhost:8100/tabs/tab2/subpagetest=this-is-a-test-value?test=this-is-a-test-value
```

### Code Reproduction URL

https://github.com/Predarion/ionic-vue-tabs-routing-query-bug

### Ionic Info

```
Ionic:

   Ionic CLI       : 6.18.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 5.8.5

Capacitor:

   Capacitor CLI      : 3.3.1
   @capacitor/android : not installed
   @capacitor/core    : 3.3.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v16.13.0 (/usr/local/bin/node)
   npm    : 8.1.0
   OS     : macOS Big Sur
```

### Additional Information

I also tested this with

```
"@ionic/vue": "6.0.0-rc.2",
"@ionic/vue-router": "6.0.0-rc.2",
```
having the same behaviour.

**Comment by liamdebeasi** [comment] 2021-12-01 15:29
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/23699.

**Closed by liamdebeasi** 2021-12-01 15:29 UTC
Labels: triage
