### ISSUE TITLE
bug: [hidden] flag doesn't work with Ionic components

### ISSUE THREAD

**Issue by aces-tm** [ionic-team/ionic-framework#27646] opened 2023-06-14 14:46 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When `[hidden]="true"` flag is added to any Ionic component, the component does not hide in UI.

### Expected Behavior

When `[hidden]="true"` is added to Ionic component, it should be hidden

### Steps to Reproduce

Steps to reproduce:

- Create a new app
- Add [hidden]="true" to any Ionic component

For example:
```
<ion-icon [hidden]="true" slot="start" name="add"></ion-icon>
```

### Ionic Info

Ionic:

   Ionic CLI                     : 7.1.1 (/Users/andjelicnikola/.nvm/versions/node/v18.10.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.0.12
   @angular-devkit/build-angular : 16.1.0
   @angular-devkit/schematics    : 16.1.0
   @angular/cli                  : 16.1.0
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.0.5
   @capacitor/android : not installed
   @capacitor/core    : 5.0.5
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v18.10.0 (/Users/andjelicnikola/.nvm/versions/node/v18.10.0/bin/node)
   npm    : 8.19.2
   OS     : macOS Unknown

### Additional Information

This looks like a major change from v6 that I couldn't find anywhere in change logs. It will take weeks to fix the app.

**Comment by liamdebeasi** [comment] 2023-06-14 15:58
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. This was a documented breaking change in Ionic 7. Please see https://github.com/ionic-team/ionic-framework/blob/main/BREAKING.md#css-utilities for more information.

**Closed by liamdebeasi** 2023-06-14 15:58 UTC
Labels: triage
