### ISSUE TITLE
bug: Floating label overlaps invalid input in Safari

### ISSUE THREAD

**Issue by TonySpegel** [ionic-team/ionic-framework#18037] opened 2019-04-15 16:11 UTC
# Bug Report

**Ionic version:**
4.x

**Current behavior:**
When using a number input in combination with a floating label the label overlaps with the input when typing in a value such as ```10.```
It's pretty much this: https://github.com/ionic-team/ionic/issues/10453

**Expected behavior:**
The label should stay on top when the input is invalid

**Steps to reproduce:**
Create a small form like this:
```
<form
      (submit)="onSubmit($event, settingsForm)"
      [formGroup]="userForm"
      class="zns-form"
  >
      <ion-list>
          <ion-item>
              <ion-label position="floating">nope</ion-label>
              <ion-input
                  formControlName="age"
                  step="1"
                  type="number"
              >
              </ion-input>
          </ion-item>
      </ion-list>
  </form>
```
type in a value such as ```10.``` an leave the input

**Related code:**

StackBlitz (https://stackblitz.com/edit/ionic-v4-wmwhow?file=src%2Fapp%2Fapp.component.html)

**Comment by brandyscarney** [comment] 2019-05-01 21:56
Thanks for the issue! What version are you using? The Stackblitz provided is using:

```json
"@ionic/angular": "4.0.0-beta.7"
``` 

This is a really old version released 8 months ago, our latest production version is `4.3.1`. We have some release notes up now for our latest production version: https://ionicframework.com/docs/release-notes.

I'm also not able to reproduce this in the provided Stackblitz:

<img src="http://g.recordit.co/VD1N2ww5do.gif">

Could you please provide a minimal code example for us to reproduce on latest? Thanks!

**Comment by TonySpegel** [comment] 2019-05-03 11:58
Hi, this is weird, using the same Stackblitz with 4.0.0-beta.7 running on Chrome 74.0.3729.131 with a German Keyboard Layout I can reproduce my Bug:
![4 0 0-beta 7](https://user-images.githubusercontent.com/1145514/57135006-415c1d80-6da8-11e9-9962-fc6279fdc852.gif)
The same applies for 4.0.0 (which we are using in our Product).
I couldn't use 4.3.1 with Stackblitz for unknown reasons

**Comment by wendyvelie** [comment] 2019-08-21 16:59
I'm having a similar issue, using  @ionic/angular version 4.1.0. I can repro with the Stackblitz above by entering "10.0.0"

**Comment by sean-perkins** [comment] 2022-03-12 02:45
Tested against v6 and confirmed this issue still exists, only present in Safari. 

Created a new reproduction (based on the v4 example): https://github.com/sean-perkins/gh-18037-ng-floating-label

**Comment by liamdebeasi** [comment] 2022-11-23 14:09
Thanks for the report. In Ionic 7 we are introducing a new syntax for working with form components such as `ion-input`. One of the benefits of this change is that it resolves the reported issue here. I am going to close this since the work to resolve this issue has been completed. We will have a public beta testing period for Ionic 7 in the future. You can learn more about the `ion-input` changes here: https://github.com/ionic-team/ionic-framework/discussions/25661

Please let me know if you have any questions.

**Closed by liamdebeasi** 2022-11-23 14:09 UTC
Labels: package: core, type: bug
