### ISSUE TITLE
bug: IonInput race condition with IonChange and IonBlur

### ISSUE THREAD

**Issue by scottix** [ionic-team/ionic-framework#23195] opened 2021-04-15 16:59 UTC
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
I found the bug when we were trying to support the Bitwarden autofill and coming up with an issue.  
Basically we found the onBlur event would occur before the onChange.  
This causes an issue because we tie the validation to the onBlur. So if the value is not updated before the onBlur event, it would do the validation on an empty input.

**Expected behavior:**
onChange should trigger the value update or at-least make sure the value is updated, since there is a delay option, before onBlur gets called.

**Steps to reproduce:**
Sample app below to test ion-input and native input.  

I used Bitwarden to trigger the autofill

![Selection_865](https://user-images.githubusercontent.com/435727/114908549-0efb2d80-9dd1-11eb-87da-ad436bfb0788.png)

![Selection_866](https://user-images.githubusercontent.com/435727/114908625-1f130d00-9dd1-11eb-98a7-3eee45b4dbbb.png)

**Related code:**
https://github.com/scottix/ionic-bitwarden

**Other information:**

**Ionic info:**
```
Ionic:

   Ionic CLI       : 6.13.1 (/usr/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 5.6.4

Capacitor:

   Capacitor CLI   : 2.4.7
   @capacitor/core : 2.4.7

Utility:

   cordova-res : 0.15.3
   native-run  : not installed

System:

   NodeJS : v12.22.1 (/usr/bin/node)
   npm    : 6.14.12
   OS     : Linux 5.4
```

**Comment by liamdebeasi** [comment] 2021-04-15 17:40
Thanks for the issue. I can reproduce this behavior, though `ionChange` does not behave exactly the same as the native `change` event. `ionChange` does not fire when the native `change` event fires because the `value` property on the Web Component has not been updated yet. Since we need to wait for the property to change, this guarantees that `ionChange` will fire after `ionBlur`. 

Could you please describe in more detail what kinds of problems this causes in your app? One thing you might be able to do is run your validation inside a `requestAnimationFrame` to ensure that it grabs the latest value.

**Comment by scottix** [comment] 2021-04-15 18:58
I mean fundamentally it breaks how forms work in HTML, In a native input you are guaranteed the value being set when onBlur occurs.
We use onBlur to check for validation on the input, but since the value is empty because it hasn't updated yet. It comes back as an error.
So basically we can't use the onBlur event.

Example screenshot
![Selection_870](https://user-images.githubusercontent.com/435727/114923560-d1eb6700-9de1-11eb-9522-733a2447f03f.png)

**Comment by liamdebeasi** [comment] 2021-04-15 19:06
So the value _is_ being set on the native input before `onBlur` occurs, just not on the Web Component itself. It might be better to grab the native `input` and set the onchange listener there:

```js
const addChangeListener = async () => {
  const nativeInput = await ionInputRef.getInputElement();
  nativeInput.onchange = () => {
    // do your validation in here
  }
}
```

That being said, I think it would make more sense to run your validation once `ionChange` has fired rather than `ionBlur` since that means the value of the input has changed. If you are worried about the validation running too frequently (say if a user is typing their email in rather than using autofill), you can use the `debounce` property to ensure that the validation only fires once the user stops typing:

```html
<!-- debounce is set to 100ms -->
<ion-input @ion-change="onChange" :debounce="100"></ion-input>
```

Can you try either/both of those and let me know if it resolves the issue?

**Comment by scottix** [comment] 2021-04-15 19:15
Ya I can figure out a workaround, but if the goal is to mimic native input, it's still a race condition bug.

**Comment by liamdebeasi** [comment] 2021-04-15 19:20
`ionChange` was never intended to be a direct replacement for the native `onchange` event. For example, `ionChange` fires whenever the value is changed whereas `onchange` fires if the value has changed but only once the input is blurred (for text inputs at least).

I spoke with the team we are not really comfortable changing the behavior of how `ionChange` works since it would be a breaking change for a large number of Ionic apps. I am going to close this issue, but definitely feel free to give one of the workarounds I posted a try.

**Closed by liamdebeasi** 2021-04-15 19:20 UTC
Labels: triage

**Comment by czzplnm** [comment] 2021-04-15 20:13
Should probably add this to your docs so other people can make sense of this weird behavior.
