### ISSUE TITLE
bug: componentOnReady() is not defined with @ionic/react

### ISSUE THREAD

**Issue by roman-rr** [ionic-team/ionic-framework#28555] opened 2023-11-19 12:36 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v6.x, v7.x

### Current Behavior

I'm using this method with JavaScript (no-framework) app like this:
```javascript
await (<any>document.querySelector('ion-app')).componentOnReady();
```
And it's working perfect with this normal js [Ionic bundle ](https://cdn.jsdelivr.net/npm/@ionic/core/dist/ionic/ionic.js)
[Here is example](https://jsfiddle.net/romantonoff/zbk6mnj9)

But when I use it as part of  app with "@ionic/react": "^7.0.0", I have error that `componentOnReady()`is not defined. 

Does `componentOnReady()` has been removed from React version?

### Expected Behavior

`componentOnReady()` method available with React bundle.

### Steps to Reproduce

1. git clone https://github.com/chrisk-7777/ionic-7-pane-demo
2. cd ionic-7-pane-demo
3. npm i
4. npm run dev
5. click "open pane" button that call `componentOnReady()` on `ion-app`
6. See error

### Code Reproduction URL

https://github.com/chrisk-7777/ionic-7-pane-demo

### Ionic Info

Ionic:

   Ionic CLI : 6.20.0

Utility:

   cordova-res (update available: 0.15.4) : 0.14.0
   native-run (update available: 2.0.0)   : 1.7.3

System:

   NodeJS : v18.16.0
   npm    : 9.5.1
   OS     : macOS

  ────────────────────────────────────────────────

     Ionic CLI update available: 6.20.0 → 7.1.3
         Run npm i -g @ionic/cli to update

  ────────────────────────────────────────────────

**Comment by liamdebeasi** [comment] 2023-11-20 14:35
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The `componentOnReady` method is an API provided by Stencil and is only available for lazy loaded builds of Ionic using the `dist` output target: https://stenciljs.com/docs/distribution

Ionic React uses the [dist-custom-elements](https://stenciljs.com/docs/custom-elements) output target from Stencil which avoids lazily loading components. This improves dead code elimination and application start up time. Since Ionic React does not make use of the lazy loading approach, the `componentOnReady` method is not provided.

We do make use of `componentOnReady` in limited scenarios internally, though we fallback to a `requestAnimationFrame` when `componentOnReady` is not defined: https://github.com/ionic-team/ionic-framework/blob/adb01e251672518f0f6e067d65777a2a062dbe48/core/src/utils/helpers.ts#L72-L79C3

**Closed by liamdebeasi** 2023-11-20 14:35 UTC
Labels: triage
