### ISSUE TITLE
bug: @ionic/react selector :not(.hydrated) display none at body when no JavaScript files are loaded

### ISSUE THREAD

**Issue by felquis** [ionic-team/ionic-framework#23654] opened 2021-07-18 19:19 UTC
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

Stuck in white screen because only styles are imported not JavaScript files
```
html:not(.hydrated) body {
    display: none;
}
```

### Expected Behavior

Not be stuck with white screen

### Steps to Reproduce

Start a project with:
```
yarn create next-app --typescript
```

Install @ionic/react module:
```
yarn add @ionic/react
``` 

Import default styles: as of https://ionicframework.com/docs/intro/cdn#ionic-react
open pages/_app.tsx and add these lines
```
 /* Core CSS required for Ionic components to work properly */
import '@ionic/react/css/core.css';

/* Basic CSS for apps built with Ionic */
import '@ionic/react/css/normalize.css';
import '@ionic/react/css/structure.css'; // <- this is file introduces the potentially problematic selector
import '@ionic/react/css/typography.css';

/* Optional CSS utils that can be commented out */
import '@ionic/react/css/padding.css';
import '@ionic/react/css/float-elements.css';
import '@ionic/react/css/text-alignment.css';
import '@ionic/react/css/text-transformation.css';
import '@ionic/react/css/flex-utils.css';
import '@ionic/react/css/display.css';
```

### Code Reproduction URL

https://github.com/felquis/ionic-nextjs-white-screen-with-default-styles-only

### Ionic Info

ionic info
[WARN] You are not in an Ionic project directory. Project context may be
       missing.

Ionic:

   Ionic CLI : 6.16.3

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v16.3.0
   npm    : 7.15.1
   OS     : macOS Catalina

### Additional Information

Why would someone use all ionic default styles in a website without ionic javascript? In my case, I'd render ionic specific components on a sub page, while I keep global styles loaded. Once @ionic/react works with ssr https://github.com/ionic-team/ionic-framework/issues/23651 I may use some components in the marketing home page.

It can be solved with a method that's meant to remove hydrated class even when not using any ionic component.

**Comment by liamdebeasi** [comment] 2021-07-19 13:01
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. Ionic Framework components are currently lazy loaded by default. Once they are loaded they go through a process called "hydration".

Before the component is hydrated, we hide the app to prevent a flash of unstyled content. We do this by adding the following CSS to your app via the `core.css` file that you imported:

```css
html:not(.hydrated) body {
    display: none;
}
```

If you are using at least one Ionic Framework component, hydration will happen and your app will show up. If you are not using any Ionic Framework components then there is no need to load the Ionic Framework CSS.

**Closed by liamdebeasi** 2021-07-19 13:01 UTC
Labels: triage
