### ISSUE TITLE
bug: iOS 16 user interface elements broken

### ISSUE THREAD

**Issue by BinDohry** [ionic-team/ionic-framework#26012] opened 2022-09-25 09:52 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

- User interface elements are broken when using Ionic app on a physical iOS device.
- Elements are broken randomly when interacting with the app such as opening modals, navigating to different tabs/views.
- Not reproducible on iOS simulator, MS Edge macOS, Safari on macOS.
- UI bugs appeared only AFTER updating to iOS 16 from iOS 15.

Images of broken UI elements in my app: [https://imgur.com/a/qsFUpRl](https://imgur.com/a/qsFUpRl)
Please excuse the red rectangles as my app is still under development and I'd prefer not to showcase the screens.

### Expected Behavior

UI elements look normal and function as designed.

### Steps to Reproduce

Build and deploy an Ionic app with Xcode on a physical iOS 16 device and interact with numerous views/elements.

As for the code reproduction URL, I tried using the Ionic starter app template just by itself and tested to see if the broken UI elements appear but they didn't. I suspect this is because the starter template is very basic and my app has a lot of UI elements as a normal app is expected to have. I'm hoping this issue is already known so I don't have to go through the trouble of setting up a whole app with modals, tabs, routing, etc. Also, there has been others in the Ionic Discord that have encountered the same UI related issues on iOS 16.

### Ionic Info

Ionic:

   Ionic CLI       : 6.20.1 (/opt/homebrew/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 6.2.8

Capacitor:

   Capacitor CLI      : 4.3.0
   @capacitor/android : 4.3.0
   @capacitor/core    : 4.3.0
   @capacitor/ios     : 4.3.0

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.1

System:

   NodeJS : v18.8.0 (/opt/homebrew/Cellar/node/18.8.0/bin/node)
   npm    : 8.19.2
   OS     : macOS Monterey

- I'm using React (17.0.2) - Tried updating to 18 but same UI issues.

**Comment by koczka** [comment] 2022-09-26 07:38
Hi,

This issue is related to a WebKit bug introduced as a byproduct when apple was fixing another bug, released in iOS 15.6 and is still an issue in the current 16 and 16.0.2 version of iOS

Related issue can be found here #25760

**Comment by liamdebeasi** [comment] 2022-09-26 12:51
Thanks for the report. At the moment I do not know if this is the same as https://github.com/ionic-team/ionic-framework/issues/25760. Can you please provide a GitHub repo that reproduces the issue?

**Comment by liamdebeasi** [comment] 2022-10-03 16:11
Glad to hear the issue is resolved. The San Francisco font is already available on iOS devices, so you should not need to bundle them again.

For example, you can use `font-family: -apple-system` to explicitly set the font to the default font on iOS. There are other font variants you can read about here: https://webkit.org/blog/3709/using-the-system-font-in-web-content/

I am going to close this, but let me know if you have any other questions.

**Closed by liamdebeasi** 2022-10-03 16:11 UTC
Labels: triage
