### ISSUE TITLE
bug: ion-input type="date" doesn't work correct in Safari 14 on Mac OS X

### ISSUE THREAD

**Issue by tubauwe** [ionic-team/ionic-framework#22245] opened 2020-10-03 15:06 UTC
**Short description of the problem:**
In my PWA created with ionic (angular) the tag `<ion-input type="date">` doesn't work correct in Safari 14 on Mac OS X. There’s no small calendar to select the wanted date anymore and the written date isn’t accepted in the right (localized) format.

It doesn't matter on the used way to test. The problem exists using `ionic serve` or after `ionic build --prod` and deploying the PWA to my webserver.

Here's some example code:
```
<ion-item>
      <ion-label>Date</ion-label>
      <ion-input type="date" [(ngModel)]="dateOfEvent"></ion-input>
</ion-item>
```

**Ionic Information**
```
Ionic:

   Ionic CLI                     : 6.11.10 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.3.4
   @angular-devkit/build-angular : 0.901.12
   @angular-devkit/schematics    : 9.1.12
   @angular/cli                  : 9.1.12
   @ionic/angular-toolkit        : 2.3.3

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.14.1 (/usr/local/bin/node)
   npm    : 6.14.8
   OS     : macOS Catalina
```

**Comment by liamdebeasi** [comment] 2020-10-05 13:20
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. Safari on macOS does not support `input[type="date"]`, which is why the calendar is not popping up: https://caniuse.com/?search=input%20date

**Closed by liamdebeasi** 2020-10-05 13:20 UTC
Labels: triage
