### ISSUE TITLE
bug: ion-action-sheet component blocks scroll of the "body" element ("backdrop-no-scroll" toggle isn't working as expected)

### ISSUE THREAD

**Issue by sviatcraft** [ionic-team/ionic-framework#28218] opened 2023-09-22 14:20 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Application (html `<body>`) is not scrollable when `ion-action-sheet` is used in v7. In v6 it works fine.
Class "backdrop-no-scroll" is always part of "body" tag when "ion-action-sheet" is used in v7.

### Expected Behavior

Expect behavior as in v6:
"backdrop-no-scroll" is not part of "body" by default;
"backdrop-no-scroll" is part of "body" when ion-action-sheet is open;
"backdrop-no-scroll" is not part of "body" when ion-action-sheet is closed;

### Steps to Reproduce

https://github.com/ionic-team/ionic-framework/assets/62302382/87d394d1-de3e-43ae-8616-9e2ff95293ff

### Ionic Info

Reproduced on https://ionicframework.com/docs/api/action-sheet
v7 - reproducible;
v6- not reproducible;

### Additional Information

I'm not sure what is expected behavior here.
I wanted to use "backdrop-no-scroll" as indicator for my custom horizontal-swipe gesture, to disable vertical scrolling.
Than I noticed that "backdrop-no-scroll" class is always part of "body" tag, and it is happening if I am using "ion-action-sheet".
Than I saw that it behaves like that in v7, and in v6 it behaves differently.

**Comment by liamdebeasi** [comment] 2023-09-22 17:07
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/23942.

This behavior appeared to change in Ionic 7 because inline Action Sheets in v6 weren't truly inline. v6 Action Sheets used controllers, so the actual action sheet was only created once it was presented (thus avoiding this bug). One of the problems with this approach is that the component properties were not reactive. In Ionic 7 we updated the implementation to use true inline Action Sheets which revealed this bug.

Follow #23942 for updates, though I'm going to bump this up in priority since it has come up a few times now.

**Closed by liamdebeasi** 2023-09-22 17:07 UTC
Labels: triage
