### ISSUE TITLE
bug: ion-back-button not working

### ISSUE THREAD

**Issue by mrSingh007** [ionic-team/ionic-framework#25002] opened 2022-03-25 17:12 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

when clicking on ion-back-button its not taking to last page from history. It seems like its not taking 'defaultHref' value.

### Expected Behavior

should take to the last page when clicked on ion-back-button

### Steps to Reproduce

here is demo setup https://github.com/mrSingh007/coupleApp (just ignore firebase environment )

1. use router-outlet as following and navigate forward to any page which have ion-back-button
```
<ion-app>
  <ion-router-outlet id="main" ></ion-router-outlet>
</ion-app>

```
2. click on back button.

### Code Reproduction URL

https://github.com/mrSingh007/coupleApp

### Ionic Info

Ionic:

   Ionic CLI                     : 6.18.2 (/Users/USER/.volta/tools/image/packages/@ionic/cli/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.13
   @angular-devkit/build-angular : 13.2.6
   @angular-devkit/schematics    : 13.2.6
   @angular/cli                  : 13.2.6
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.4.3
   @capacitor/android : 3.4.3
   @capacitor/core    : 3.4.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v16.14.0 
   npm    : 7.5.6
   OS     : macOS Monterey

### Additional Information

as i analyzed the generated code and found out that 'defaultHref' is undefined. Even button have this property

```
   this.type = 'button';
    this.onClick = async (ev) => {
      const nav = this.el.closest('ion-nav');
      ev.preventDefault();
      if (nav && await nav.canGoBack()) {
        return nav.pop({ animationBuilder: this.routerAnimation, skipIfBusy: true });
      }
      return openURL(this.defaultHref, ev, 'back', this.routerAnimation);
    };
  }
  componentWillLoad() {
    this.inheritedAttributes = inheritAttributes(this.el, ['aria-label']);
    if (this.defaultHref === undefined) {
      this.defaultHref = config.get('backButtonDefaultHref');
    }
  }
```

**Comment by liamdebeasi** [comment] 2022-03-29 13:59
Thanks for the issue. I am unable to verify that this is a bug in Ionic. While I do not see any obvious issues at the moment, I am only able to reproduce this behavior in your application. The Ionic list starter application, which uses similar steps as your app, does not reproduce this issue.

Can you try debugging your app a bit more? It might be helpful to start with the Ionic List starter application: 

```
ionic start myApp list --type=angular
```

**Comment by liamdebeasi** [comment] 2022-03-30 13:29
Yes, IonicModule is needed for all pages. If you create pages using the Ionic CLI this should be automatically configured for you.

I am going to close this as this is not a bug in Ionic.

**Closed by liamdebeasi** 2022-03-30 13:29 UTC
Labels: triage
