### ISSUE TITLE
bug: IonReorder items animate twice in Firefox

### ISSUE THREAD

**Issue by mtrosenstein** [ionic-team/ionic-framework#21182] opened 2020-05-01 13:59 UTC
# Bug Report

**Ionic version:**
**5.x**

**Current behavior:**

With IonReorder, when a user drags an item to a new location the "displaced" items use a translateY animation to reposition themselves. When the dragged item is released, the displaced items animate a second time, even though they are already positioned correctly. The user experience is that some items "jump" unexpectedly.

**Expected behavior:**

The translateY animation should only run only once, with no "jump" when the reorder completes.

**Steps to reproduce:**

The easiest way to reproduce is to view the [official ion-reorder example](https://ionicframework.com/docs/api/reorder/). Click the "Toggle" text to enable reordering. Next, slowly drag "Item 1" to the location of "Item 4". Notice how the other items translate to their new locations. Then release "Item 1" in its final location and notice how the other items animate again.

**Comment by liamdebeasi** [comment] 2020-05-01 14:05
Thanks for the issue. What browser/version are you testing this on? I am not seeing this on Chrome 81.

**Comment by mtrosenstein** [comment] 2020-05-01 14:42
Ahh, good question. I see the problem on Firefox 75.0.

**Comment by wibed** [comment] 2020-11-02 13:49
I can confirm the bug persists on Firefox 82 on osx

I can't say if it animates twice, but it looks like bouncing back even if the array passed, is reordered correctly.
on safari it animates as expected

**Comment by duerra** [comment] 2021-06-28 19:14
I can confirm the bug is still present as of Firefox 89.

**Comment by liamdebeasi** [comment] 2022-11-21 15:51
Hi there,

I have a dev build with a proposed fix if anyone is interested in testing:

```
6.3.8-dev.11669044540.14469944
```

**Comment by liamdebeasi** [comment] 2022-11-22 16:39
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/26326, and a fix will be available in an upcoming release of Ionic Framework. Please feel free to continue testing the dev build, and let me know if you run into any issues.

**Closed** 2022-11-22 16:38 UTC
Labels: package: core, type: bug
