### ISSUE TITLE
bug: ion-datetime on iOS

### ISSUE THREAD

**Issue by mariossavva** [ionic-team/ionic-framework#24424] opened 2021-12-16 00:32 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

1. datetime on ios doesn't display correctly.
2. when the popover is set to dismissOnSelect=true clicking on the header the change the month/year the popover goes away. also it goes away when clicking on any label.
3. the month scrolls and stops working

see video below:

https://user-images.githubusercontent.com/32732988/146286133-24e81dfa-3be2-431d-9aa2-72f010d9677d.mov

### Expected Behavior

1. the arrows on the header should display correctly
2. the popover should close only when selecting a date
3. it should not scroll horizontally

### Steps to Reproduce

add a popover with a datetime:

<ion-button id="open-date-input">2021-12-15</ion-button>
<ion-popover trigger="open-date-input" [dismissOnSelect]="true">
    <ng-template>
        <ion-datetime presentation="date"></ion-datetime>
     </ng-template>
</ion-popover>

### Ionic Info

Ionic:

   Ionic CLI                     : 6.18.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.1
   @angular-devkit/build-angular : 13.1.2
   @angular-devkit/schematics    : 13.1.2
   @angular/cli                  : 13.1.2
   @ionic/angular-toolkit        : 5.0.3

Capacitor:
   Capacitor CLI      : 3.3.3
   @capacitor/android : 3.3.3
   @capacitor/core    : 3.3.3
   @capacitor/ios     : 3.3.3

Utility:
   cordova-res : not installed globally
   native-run  : 1.5.0

System:
   NodeJS : v14.17.5 (/usr/local/bin/node)
   npm    : 8.3.0
   OS     : macOS Big Sur

**Comment by sean-perkins** [comment] 2021-12-16 01:06
Hello @mariossavva thanks for the issue!

`dismissOnSelect` is intended to be used for automatically dismissing the popover when a click event happens within its container. 

To accomplish the behavior you are discussing, I would recommend something similar to:

```html
<ion-popover #dateInputPopover trigger="open-date-input">
   <ion-datetime (ionChange)="datetimeValueChange(dateInputPopover)"></ion-datetime>
</ion-popover>
```

```ts
datetimeValueChange(popoverEl) {
  popoverEl.dismiss();
}
```

Basically, not leveraging `dismissOnSelect` and instead dismissing the popover whenever the datetime value changes. If this isn't sufficient, you could consider introducing a confirm button into your popover's UI.

Can you let me know if this pattern solves your issue?

**Comment by mariossavva** [comment] 2021-12-16 01:22
@sean-perkins yes this issue is resolved with dismissing the popover manually the way you suggested it. thanks

the width issue on ios still remains. is there a style i could change to make it wider to fit the top right arrow?

**Comment by sean-perkins** [comment] 2021-12-16 01:28
> @sean-perkins yes this issue is resolved with dismissing the popover manually the way you suggested it. thanks
> 
> the width issue on ios still remains. is there a style i could change to make it wider to fit the top right arrow?

If you can provide a code reproduction, I can likely debug the issue.

If you wanted to quickly try using `size="cover"` for the popover to allow the popover width to match the width of the trigger; that may resolve it.

Otherwise `ion-popover` does support CSS variables to adjust the width manually:
```css
ion-popover {
  --min-width: 350px;
  --width: 350px;
}

**Comment by mariossavva** [comment] 2021-12-16 15:30
@sean-perkins setting both the size="cover" and the width of the popover worked perfectly. thank you.

the one issue that remains is the scrolling of the calendar from left to right (or right to left) that gets stuck. it's only an ios issue.

the div **calendar-body ion-focusable** gets a style with pointer events set to none when scrolling but this does not happen on android (md) see below:

android:
`<div class="calendar-body ion-focusable" tabindex="0" style="">`

ios:
`<div class="calendar-body ion-focusable" tabindex="0" style="pointer-events: none;">`

let me know if you need more info

**Comment by sean-perkins** [comment] 2021-12-16 15:50
@mariossavva awesome, glad to hear that works 👍 

For the iOS swipe gesture issue, would it be possible to get a screen recording of the issue for reference? Specifically on iOS, we have to disable pointer events at the end of the swipe gesture (but before the gesture is completed), so that the container can snap in place before they swipe again. That style should get "cleaned up" when the month you are swiping to snaps in place. 

Also any additional information on the device/OS version you are testing on would be helpful. Thanks!

**Comment by mariossavva** [comment] 2021-12-16 16:01
@sean-perkins the video at the beginning of this issue displays the issue at the very of the video.

but i just realized that it works fine in the iOS simulator. the issue is only detectable in the chrome "simulator" when set to an iPhone device when debugging which is not a real issue but keep it mind for others.

thanks again for all your help. you can close this bug if you want

**Comment by sean-perkins** [comment] 2021-12-16 19:24
@mariossavva ahh, yes I see it as well in the device preview. I'm working on another date time issue, I'll see if there's any simple adjustments to the intersection observer that would work consistent in device preview as on a real device.

I'm going to close this issue for now 👍  thanks!

**Closed by sean-perkins** 2021-12-16 19:24 UTC
Labels: triage
