### ISSUE TITLE
bug: sidemenu not working on old devices

### ISSUE THREAD

**Issue by emaklakov** [ionic-team/ionic-framework#20038] opened 2019-12-04 18:50 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

When I run an app (e.g.: default ionic starter app) the sidemenu does not work on older devices (e.g.: android 5 with chrome 37).

**Expected behavior:**

Sidemenu should also work on older devices.

**Steps to reproduce:**

1. `ionic start newApp blank`
2. `cd ./newApp`
3. `ionic cordova run android`
4. click on sidemenu
5. in console see error: Uncaught TypeError: undefined is not a function
`class_1.prototype.onBackdropClick = function (ev) {
 if (this._isOpen && this.lastOnEnd < ev.timeStamp - 100) {
var shouldClose = (ev.composedPath)
? !ev.composedPath().includes(this.menuInnerEl) // <--- here is error
: false;
 if (shouldClose) {
 ev.preventDefault();
ev.stopPropagation();
this.close();
            }
        }
    };`

**Other information:**

Android 5.0 Chrome 37

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.4.9 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.5
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.1.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 4 other plugins)

Utility:

   cordova-res : 0.7.0 (update available: 0.8.1)
   native-run  : 0.2.8 (update available: 0.3.0)

System:

   Android SDK Tools : 26.1.1 (/Users/emaklakov/Library/Android/sdk)
   ios-deploy        : 1.9.4
   NodeJS            : v10.16.3 (/usr/local/bin/node)
   npm               : 6.13.0
   OS                : macOS Mojave
   Xcode             : Xcode 11.2.1 Build version 11B500
```

**Comment by ogoguel** [comment] 2020-02-27 21:44
due to Array.prototypes.includes not defined on Lolipop
temporary fix : include import 'core-js/es7/array' in polyfill

**Comment by josh-m-sharpe** [comment] 2020-03-16 04:24
We also see this error.  It appears to be triggered every time we push a new version to Google Play which then presumably automatically runs the app on a variety of devices.  Here is the report with some additional device/version info in our sentry.io error report:

<img width="670" alt="Screen Shot 2020-03-16 at 9 52 36 AM" src="https://user-images.githubusercontent.com/39473/76723081-14202000-676c-11ea-9e30-2481e77d7570.png">

**Comment by liamdebeasi** [comment] 2020-07-08 20:45
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/17781 (same underlying issue). While we do support Android 5 and 6, there is a small percentage of devices running versions of Android where the webview is fixed and cannot be upgraded.

Versions such as Chrome 37 are so old and lack many of the modern web features we have today. For further details, including suggestions on how to add support to these older devices, please see: https://github.com/ionic-team/ionic-framework/issues/17781#issuecomment-636126472.

**Closed by liamdebeasi** 2020-07-08 20:45 UTC
Labels: triage
