### ISSUE TITLE
bug: Toasts have light background with dark theme and dark background with light theme

### ISSUE THREAD

**Issue by somq** [ionic-team/ionic-framework#21807] opened 2020-07-23 22:39 UTC
# Bug Report

**Ionic version:**

[x] **5.x**

**Current behavior:**
Toasts background are light on dark background and dark on light background

Screenshots

Light: https://prnt.sc/tnj90z
Dark: https://prnt.sc/tnj8rw

**Expected behavior:**
I feel like toasts should be dark with dark background and light with light backgrounds

**Steps to reproduce:**

1. Run the conference app starter
2. Create a toast
3. Switch theme

**Other information:**

The weird thing is that toasts backgrounds should be good as far as I understand ([--ion-color-step-200](https://github.com/ionic-team/ionic-framework/blob/master/core/src/components/toast/toast.md.vars.scss#L7)), but instead backgrounds seem to be --ion-color-step-800.

**Comment by liamdebeasi** [comment] 2020-07-24 13:54
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. This is an intentional design. The light  mode design for Toast (or Snackbars) is a dark background on light backgrounds: https://material.io/components/snackbars.

**Closed by liamdebeasi** 2020-07-24 13:54 UTC
Labels: triage
