### ISSUE TITLE
bug: ion-search-bar can't redefine non-configurable property "animated" on reload of the component

### ISSUE THREAD

**Issue by waltercruz** [ionic-team/ionic-framework#28433] opened 2023-10-30 17:13 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When I first load the ion-searchbar component, it works properly. When I go to to another page, and get back to a page that has ion-searchbar again, I got an error on console

### Expected Behavior

It should work every time :)

### Steps to Reproduce

1. Load the project
2. Click menu to to to the search page
3. ion-searchbar works properly
4. click on menu to go to the inbox
5. click on menu again to go to search
6. there's now an error on console and the ion-searchbar doesn't work

### Code Reproduction URL

https://github.com/waltercruz/ionic-bug

### Ionic Info

Ionic:

   Ionic CLI                     : 7.1.1 (/Users/waltercruz/.nvm/versions/node/v20.9.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.5.2
   @angular-devkit/build-angular : 16.2.8
   @angular-devkit/schematics    : 16.2.8
   @angular/cli                  : 16.2.8
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.5.1
   @capacitor/android : 5.5.1
   @capacitor/core    : 5.5.1
   @capacitor/ios     : not installed

Utility:

   cordova-res                          : not installed globally
   native-run (update available: 2.0.0) : 1.7.4

System:

   NodeJS : v20.9.0 (/Users/waltercruz/.nvm/versions/node/v20.9.0/bin/node)
   npm    : 10.1.0
   OS     : macOS Unknown

### Additional Information

The error on console:

```
Error: Uncaught (in promise): TypeError: can't redefine non-configurable property "animated"
980/proxyInputs/<@http://localhost:8100/vendor.js:118481:12
proxyInputs@http://localhost:8100/vendor.js:118480:10
ngOnInit@http://localhost:8100/vendor.js:123482:16
callHookInternal@http://localhost:8100/vendor.js:69297:10
callHook@http://localhost:8100/vendor.js:69321:23
callHooks@http://localhost:8100/vendor.js:69281:17
executeInitAndCheckHooks@http://localhost:8100/vendor.js:69235:14
refreshView@http://localhost:8100/vendor.js:78575:35
detectChangesInView@http://localhost:8100/vendor.js:78723:16
detectChangesInComponent@http://localhost:8100/vendor.js:78701:22
detectChangesInChildComponents@http://localhost:8100/vendor.js:78735:29
refreshView@http://localhost:8100/vendor.js:78611:37
detectChangesInternal@http://localhost:8100/vendor.js:78502:16
detectChanges@http://localhost:8100/vendor.js:79011:26
setActive@http://localhost:8100/vendor.js:116403:42
activateWith@http://localhost:8100/vendor.js:116840:20
activateRoutes@http://localhost:8100/vendor.js:110409:28
7947/activateChildRoutes/<@http://localhost:8100/vendor.js:110363:12
activateChildRoutes@http://localhost:8100/vendor.js:110362:25
activate@http://localhost:8100/vendor.js:110273:10
7947/activateRoutes/<@http://localhost:8100/vendor.js:110257:120
9736/map/</<@http://localhost:8100/vendor.js:50347:31
5678/OperatorSubscriber/this._next<@http://localhost:8100/vendor.js:50029:15
next@http://localhost:8100/vendor.js:49099:12
3738/tap/</<@http://localhost:8100/vendor.js:50931:18
5678/OperatorSubscriber/this._next<@http://localhost:8100/vendor.js:50029:15
next@http://localhost:8100/vendor.js:49099:12
9736/map/</<@http://localhost:8100/vendor.js:50347:18
5678/OperatorSubscriber/this._next<@http://localhost:8100/vendor.js:50029:15
next@http://localhost:8100/vendor.js:49099:12
1891/switchMap/</</innerSubscriber<@http://localhost:8100/vendor.js:50789:243
5678/OperatorSubscriber/this._next<@http://localhost:8100/vendor.js:50029:15
next@http://localhost:8100/vendor.js:49099:12
9736/map/</<@http://localhost:8100/vendor.js:50347:18
5678/OperatorSubscriber/this._next<@http://localhost:8100/vendor.js:50029:15
next@http://localhost:8100/vendor.js:49099:12
384/fromArrayLike/<@http://localhost:8100/vendor.js:49867:18
_trySubscribe@http://localhost:8100/vendor.js:48829:19
2235/subscribe/<@http://localhost:8100/vendor.js:48823:113
errorContext@http://localhost:8100/vendor.js:51543:5
subscribe@http://localhost:8100/vendor.js:48818:69
9736/map/<@http://localhost:8100/vendor.js:50346:12
4114/operate/</<@http://localhost:8100/vendor.js:51815:18
2235/subscribe/<@http://localhost:8100/vendor.js:48823:42
errorContext@http://localhost:8100/vendor.js:51543:5
subscribe@http://localhost:8100/vendor.js:48818:69
1891/switchMap/</<@http://localhost:8100/vendor.js:50789:100
5678/OperatorSubscriber/this._next<@http://localhost:8100/vendor.js:50029:15
next@http://localhost:8100/vendor.js:49099:12
1891/switchMap/</</innerSubscriber<@http://localhost:8100/vendor.js:50789:243
5678/OperatorSubscriber/this._next<@http://localhost:8100/vendor.js:50029:15
next@http://localhost:8100/vendor.js:49099:12
9736/map/</<@http://localhost:8100/vendor.js:50347:18
5678/OperatorSubscriber/this._next<@http://localhost:8100/vendor.js:50029:15
next@http://localhost:8100/vendor.js:49099:12
1527/take/</<@http://localhost:8100/vendor.js:50824:20
5678/OperatorSubscriber/this._next<@http://localhost:8100/vendor.js:50029:15
next@http://localhost:8100/vendor.js:49099:12
728/defaultIfEmpty/</<@http://localhost:8100/vendor.js:50172:20
5678/OperatorSubscriber/this._complete<@http://localhost:8100/vendor.js:50045:9
complete@http://localhost:8100/vendor.js:49115:12
384/fromArrayLike/<@http://localhost:8100/vendor.js:49869:16
_trySubscribe@http://localhost:8100/vendor.js:48829:19
2235/subscribe/<@http://localhost:8100/vendor.js:48823:113
errorContext@http://localhost:8100/vendor.js:51543:5
subscribe@http://localhost:8100/vendor.js:48818:69
728/defaultIfEmpty/<@http://localhost:8100/vendor.js:50167:12
4114/operate/</<@http://localhost:8100/vendor.js:51815:18
2235/subscribe/<@http://localhost:8100/vendor.js:48823:42
errorContext@http://localhost:8100/vendor.js:51543:5
subscribe@http://localhost:8100/vendor.js:48818:69
1527/take/<@http://localhost:8100/vendor.js:50822:12
4114/operate/</<@http://localhost:8100/vendor.js:51815:18
2235/subscribe/<@http://localhost:8100/vendor.js:48823:42
errorContext@http://localhost:8100/vendor.js:51543:5
subscribe@http://localhost:8100/vendor.js:48818:69
9736/map/<@http://localhost:8100/vendor.js:50346:12
4114/operate/</<@http://localhost:8100/vendor.js:51815:18
2235/subscribe/<@http://localhost:8100/vendor.js:48823:42
errorContext@http://localhost:8100/vendor.js:51543:5
subscribe@http://localhost:8100/vendor.js:48818:69
1891/switchMap/</<@http://localhost:8100/vendor.js:50789:100
5678/OperatorSubscriber/this._next<@http://localhost:8100/vendor.js:50029:15
next@http://localhost:8100/vendor.js:49099:12
1891/switchMap/</</innerSubscriber<@http://localhost:8100/vendor.js:50789:243
5678/OperatorSubscriber/this._next<@http://localhost:8100/vendor.js:50029:15
next@http://localhost:8100/vendor.js:49099:12
9736/map/</<@http://localhost:8100/vendor.js:50347:18
5678/OperatorSubscriber/this._next<@http://localhost:8100/vendor.js:50029:15
next@http://localhost:8100/vendor.js:49099:12
3738/tap/</<@http://localhost:8100/vendor.js:50931:18
5678/OperatorSubscriber/this._next<@http://localhost:8100/vendor.js:50029:15
next@http://localhost:8100/vendor.js:49099:12
1891/switchMap/</</innerSubscriber<@http://localhost:8100/vendor.js:50789:243
5678/OperatorSubscriber/this._next<@http://localhost:8100/vendor.js:50029:15
next@http://localhost:8100/vendor.js:49099:12
3738/tap/</<@http://localhost:8100/vendor.js:50931:18
5678/OperatorSubscriber/this._next<@http://localhost:8100/vendor.js:50029:15
next@http://localhost:8100/vendor.js:49099:12
8164/mergeInternals/doInnerSub/<@http://localhost:8100/vendor.js:50431:20
5678/OperatorSubscriber/this._next<@http://localhost:8100/vendor.js:50029:15
next@http://localhost:8100/vendor.js:49099:12
8164/mergeInternals/doInnerSub/<@http://localhost:8100/vendor.js:50431:20
5678/OperatorSubscriber/this._next<@http://localhost:8100/vendor.js:50029:15
next@http://localhost:8100/vendor.js:49099:12
384/fromArrayLike/<@http://localhost:8100/vendor.js:49867:18
_trySubscribe@http://localhost:8100/vendor.js:48829:19
2235/subscribe/<@http://localhost:8100/vendor.js:48823:113
errorContext@http://localhost:8100/vendor.js:51543:5
subscribe@http://localhost:8100/vendor.js:48818:69
doInnerSub@http://localhost:8100/vendor.js:50426:95
outerNext@http://localhost:8100/vendor.js:50421:52
5678/OperatorSubscriber/this._next<@http://localhost:8100/vendor.js:50029:15
next@http://localhost:8100/vendor.js:49099:12
7344/takeLast/</<@http://localhost:8100/vendor.js:50860:20
5678/OperatorSubscriber/this._complete<@http://localhost:8100/vendor.js:50045:9
complete@http://localhost:8100/vendor.js:49115:12
3738/tap/</<@http://localhost:8100/vendor.js:50936:18
5678/OperatorSubscriber/this._complete<@http://localhost:8100/vendor.js:50045:9
complete@http://localhost:8100/vendor.js:49115:12
checkComplete@http://localhost:8100/vendor.js:50418:18
8164/mergeInternals/<@http://localhost:8100/vendor.js:50456:5
5678/OperatorSubscriber/this._complete<@http://localhost:8100/vendor.js:50045:9
complete@http://localhost:8100/vendor.js:49115:12
```

**Comment by liamdebeasi** [comment] 2023-10-30 17:20
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/28418. This bug has already been addressed, and the fix will be in this week's release of Ionic. You can use the `nightly` build of Ionic to test: `npm install @ionic/angular@nightly`.

**Closed by liamdebeasi** 2023-10-30 17:20 UTC
Labels: triage
