### ISSUE TITLE
bug: SSR only renders in material design mode

### ISSUE THREAD

**Issue by archevis** [ionic-team/ionic-framework#23210] opened 2021-04-19 14:03 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
SSR with @ionic/angular-server only produces "md" mode, even on iOS devices.

**Expected behavior:**
Rendering the correct mode; mode="md" for Android and mode=" ios" for iOS.

**Steps to reproduce:**
1. ionic start ssr-test
2. cd ssr-test
3. npm install @angular/animations
4. ng add @nguniversal/express-engine
5. npm install @ionic/angular-server
6. Add IonicServerModule to imports in src/app/app.server.module.ts
7. npm run build:ssr && npm run serve:ssr
8. visit http://localhost:4000 and view page source

**Ionic info:**

Ionic:

   Ionic CLI                     : 6.13.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.6.4
   @angular-devkit/build-angular : 0.1102.9
   @angular-devkit/schematics    : 11.2.9
   @angular/cli                  : 11.2.9
   @ionic/angular-toolkit        : 3.1.1

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.18.2 (/usr/bin/node)
   npm    : 7.9.0
   OS     : Linux 5.11

**Comment by liamdebeasi** [comment] 2021-04-19 14:31
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/22121.

**Closed by liamdebeasi** 2021-04-19 14:31 UTC
Labels: triage
