### ISSUE TITLE
bug: NS_ERROR_FAILURE in Firefox 105, when `.fillText` is called on `canvas`'s context, inside `ion-content`

### ISSUE THREAD

**Issue by rozpuszczalny** [ionic-team/ionic-framework#26039] opened 2022-09-29 10:50 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

Originally, the issue was showing itself by throwing an error in chart.js library (ref: chartjs/Chart.js#10720), when the chart.js chart was being drawn into the canvas element, which is inside the `ion-content` element.

But further investigation of mine shown that the issue is related to the `canvas` element being inside `ion-content` element. If one would like to write an text using `.fillText`, or even change font styling by using `.font` results in `NS_ERROR_FAILURE`.

![obraz](https://user-images.githubusercontent.com/7627635/193010739-e7e1d472-eae7-436a-b3ba-19ae8dbe0858.png)

```ts
ngAfterViewInit() {
  const ctx = this.canva.nativeElement.getContext('2d');

  ctx.fillText('Hello, world', 10, 10);
}
```

If the `canvas` element is not a child of `ion-content`, then it works just fine.

### Expected Behavior

Text-related actions on `canvas` `2d` context should not throw an error

### Steps to Reproduce

1. Generate Ionic + Angular project
2. Create `canvas` element inside `ion-content` element, in the Ionic Page
3. Add selector (e.g. `#canva`) to the `canvas` element
4. Query the element by Angular's `ViewChild`
5. Get 2d context in Angular's `ngAfterViewInit`
6. Call `.flllText('hello, world', 10, 10)` on 2d context

Expected: hello, world is visible
Actual: An error is thrown

### Code Reproduction URL

https://stackblitz.com/edit/angular-ivy-pyvhyk?file=src/app/pages/index/index.page.ts

### Ionic Info

Reproduced in stackblitz environment, see above (newest Angular and newest Ionic)

`ionic info` from my project, from which originally I had issue:

```
$ ionic info

Ionic:

   Ionic CLI                     : 6.20.1 (/home/tomek/.nvm/versions/node/v14.17.6/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.6.11
   @angular-devkit/build-angular : 0.1102.14
   @angular-devkit/schematics    : 9.1.12
   @angular/cli                  : 11.2.14
   @ionic/angular-toolkit        : 2.3.3

Capacitor:

   Capacitor CLI      : 3.1.1
   @capacitor/android : 3.1.1
   @capacitor/core    : 3.1.1
   @capacitor/ios     : 3.1.1

Utility:

   cordova-res                          : not installed globally
   native-run (update available: 1.7.1) : 1.4.0

System:

   NodeJS : v14.17.6 (/home/tomek/.nvm/versions/node/v14.17.6/bin/node)
   npm    : 6.14.15
   OS     : Linux 5.10
```

### Additional Information

It only happens on Firefox 105. Previous Firefox (probably? see mozregression results) versions were working fine. Tested on Windows 10 machine, I don't know if it also happens on Linux and MacOS.

Users of chart.js report that the issue happens to them on react ionic as well.

Running `mozregression` on the stackblitz above gave following results:

<details>
<summary>mozgregression results</summary>
<pre>
2022-09-29T14:42:57.958000: INFO : application_display_name: Firefox Nightly
2022-09-29T14:42:57.958000: INFO : application_id: {ec8030f7-c20a-464f-9b0e-13a3a9e97384}
2022-09-29T14:42:57.958000: INFO : application_name: Firefox
2022-09-29T14:42:57.958000: INFO : application_remotingname: firefox
2022-09-29T14:42:57.958000: INFO : application_repository: https://hg.mozilla.org/integration/autoland
2022-09-29T14:42:57.958000: INFO : application_vendor: Mozilla
2022-09-29T14:42:57.958000: INFO : application_version: 96.0a1
2022-09-29T14:42:57.958000: INFO : platform_buildid: 20211116165611
2022-09-29T14:42:57.958000: INFO : platform_changeset: 5aa4d866a171d9cb0502678028667d987cb3d534
2022-09-29T14:42:57.958000: INFO : platform_repository: https://hg.mozilla.org/integration/autoland
2022-09-29T14:42:57.958000: INFO : platform_version: 96.0a1
2022-09-29T14:43:11.136000: INFO : Narrowed integration regression window from [9afe4618, 33a125a2] (3 builds) to [9afe4618, 5aa4d866] (2 builds) (~1 steps left)
2022-09-29T14:43:11.151000: DEBUG : Starting merge handling...
2022-09-29T14:43:11.151000: DEBUG : Using url: https://hg.mozilla.org/integration/autoland/json-pushes?changeset=5aa4d866a171d9cb0502678028667d987cb3d534&full=1
2022-09-29T14:43:11.152000: DEBUG : redo: attempt 1/3
2022-09-29T14:43:11.152000: DEBUG : redo: retry: calling _default_get with args: ('https://hg.mozilla.org/integration/autoland/json-pushes?changeset=5aa4d866a171d9cb0502678028667d987cb3d534&full=1',), kwargs: {}, attempt #1
2022-09-29T14:43:11.160000: DEBUG : urllib3.connectionpool: Resetting dropped connection: hg.mozilla.org
2022-09-29T14:43:12.465000: DEBUG : urllib3.connectionpool: https://hg.mozilla.org:443 "GET /integration/autoland/json-pushes?changeset=5aa4d866a171d9cb0502678028667d987cb3d534&full=1 HTTP/1.1" 200 None
2022-09-29T14:43:12.502000: DEBUG : Found commit message:
Bug 1483798 - Avoid returning the computed styles of nodes that aren't in the flat tree. r=xidorn

As per spec. This could cause wrong styles to be returned because we
fill the bloom filter based on flat tree ancestors, which was ultimately
the root cause of bug 1737131.

Differential Revision: https://phabricator.services.mozilla.com/D131074

2022-09-29T14:43:12.502000: DEBUG : Did not find a branch, checking all integration branches
2022-09-29T14:43:12.504000: INFO : The bisection is done.
2022-09-29T14:43:12.505000: INFO : Stopped
</pre>
</details>

I've tried to reproduce the issue by using raw HTML custom element and slot, but it worked just fine:

https://stackblitz.com/edit/js-7vrflj?file=index.js

I also tried to reproduce the issue by using vanilla js Ionic version, but I was unable to. See the code below:

<details>
<summary>Vanilla JS code</summary>
<pre>
&lt;!DOCTYPE html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&nbsp;&nbsp;&lt;meta charset="UTF-8"&gt;
&nbsp;&nbsp;&lt;meta http-equiv="X-UA-Compatible" content="IE=edge"&gt;
&nbsp;&nbsp;&lt;meta name="viewport" content="width=device-width, initial-scale=1.0"&gt;
&nbsp;&nbsp;&lt;title&gt;Document&lt;/title&gt;
&nbsp;&nbsp;&lt;script type="module" src="https://cdn.jsdelivr.net/npm/@ionic/core/dist/ionic/ionic.esm.js"&gt;&lt;/script&gt;
&nbsp;&nbsp;&lt;script nomodule src="https://cdn.jsdelivr.net/npm/@ionic/core/dist/ionic/ionic.js"&gt;&lt;/script&gt;
&nbsp;&nbsp;&lt;link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@ionic/core/css/ionic.bundle.css" /&gt;&lt;/head&gt;
&lt;body&gt;
&nbsp;&nbsp;&lt;ion-app&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&lt;ion-router&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;ion-route url="/" component="test-canvas"&gt;&lt;/ion-route&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&lt;/ion-router&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&lt;ion-router-outlet&gt;&lt;/ion-router-outlet&gt;
&nbsp;&nbsp;&lt;/ion-app&gt;

&nbsp;&nbsp;&lt;script&gt;
&nbsp;&nbsp;&nbsp;&nbsp;class TestCanvas extends HTMLElement {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#shadowRoot;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;constructor() {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;super();
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;this.#shadowRoot = this.attachShadow({ mode: 'open' });
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;this.#shadowRoot.innerHTML = &#96;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;ion-content&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;ion-content&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;canvas id="app" style="width: 100px; height: 100px"&gt;&lt;/canvas&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Hello, world!
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/ion-content&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/ion-content&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#96;;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/** @type {HTMLCanvasElement} */
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const canvas = this.#shadowRoot.getElementById('app');
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const ctx = canvas.getContext('2d');
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ctx.fillText('hello, world', 10, 10);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;customElements.define('test-canvas', TestCanvas);
&nbsp;&nbsp;&lt;/script&gt;
&lt;/body&gt;
&lt;/html&gt;
</pre>
</details>

**Comment by losciur** [comment] 2022-09-29 11:39
I have the same issue working with an Ionic Angular Capacitor project using chart.js.
My `ionic info`
```
Ionic:

   Ionic CLI                     : 6.20.1 (/home/losciur/.nvm/versions/node/v14.17.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.2.7
   @angular-devkit/build-angular : 14.2.2
   @angular-devkit/schematics    : 14.2.2
   @angular/cli                  : 14.2.2
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 4.2.0
   @capacitor/android : 4.2.0
   @capacitor/core    : 4.2.0
   @capacitor/ios     : 4.2.0

Utility:

   cordova-res (update available: 0.15.4) : 0.15.3
   native-run (update available: 1.7.1)   : 1.7.0

System:

   NodeJS : v14.17.0 (/home/losciur/.nvm/versions/node/v14.17.0/bin/node)
   npm    : 6.14.13
   OS     : Linux 5.4
```

**Comment by liamdebeasi** [comment] 2022-09-29 13:54
Thanks for the report. I can reproduce this issue with Firefox 105, however this does not appear to be an Ionic issue. Firefox 104 does not reproduce the issue, indicating that this may be a regression. A couple things I discovered:

1. This issue happens on any Shadow DOM component, not just `ion-content`. (Non-shadow DOM components do not reproduce the issue).
2. Wrapping the canvas code in a `setTimeout` avoids the issue. 

I'll keep digging to see if I can narrow this issue down further.

**Comment by losciur** [comment] 2022-09-29 14:20
I can confirm that with a `setTimeout` we can avoids the issue

**Comment by liamdebeasi** [comment] 2022-09-29 15:05
I don't see anything in Ionic's codebase that could be causing this issue. The `NS_ERROR_FAILURE` does not tell me much, but the issue appears to be related to rendering text. For example, `ctx.fillText('Hello world', 10, 10);` triggers the issue, but `ctx.fillRect(10, 10, 10, 10);` does not.

Did you file an issue with the Firefox team?

**Comment by rozpuszczalny** [comment] 2022-09-29 16:17
No, until this point 😉  https://bugzilla.mozilla.org/show_bug.cgi?id=1792860

I first created an issue here, since I couldn't reproduce faulty behavior without Ionic components (so e.g. by creating a custom element with shadow DOM).

If you can create a sandbox showing the problem without using Ionic components, then it would be wonderful if you would add a comment in the Firefox Bugzilla issue, which I just created (link above).

And yeah, even `ctx.font = '12px sans-serif'` triggers the issue, so it's really weird...

**Comment by hardmaster92** [comment] 2022-09-29 19:55
I've had a similar issue. Use the `ionViewDidEnter` lifecycle hook instead of `ngOnInit` or `ngAfterViewInit`. This might help in all kinds of issues related to initializing ionic pages

**Comment by liamdebeasi** [comment] 2022-10-11 21:13
Hi everyone,

I was able to isolate the issue. This problem appears when drawing on a canvas passed to a Shadow DOM component that does not have a `<slot>`. Stencil renders the `<slot>` for a component asynchronously, so there is a time between when the component has been upgraded to use the Shadow DOM and when it has `<slot>` added to the DOM. During this time, the canvas code executes which triggers this bug.

Full details are available on https://bugzilla.mozilla.org/show_bug.cgi?id=1792860#c3.

I am going to close this as this is not a bug in Ionic. I recommend following the Bugzilla thread above for updates. Thanks for the report!

**Closed by liamdebeasi** 2022-10-11 21:13 UTC
Labels: triage

**Comment by Facj** [comment] 2022-10-18 14:50
Hi,

While this issue remains unsolved, how can I implement the setTimeout workaround in Ionic React?
[Here ](https://codesandbox.io/s/firefox-error-rj98p) there is a minimal example of my code. It always fails for Ionic 5 and it sometimes fails for Ionic 6 so I am trying to solve the issue in Ionic 5 where it is easier to reproduce.

**Comment by Facj** [comment] 2022-10-20 10:57
Hi again,

By including a setTimeout in React useEffect, the issue is solved but I need to set a considerable delay to make it work.
[My example in codesandbox](https://codesandbox.io/s/firefox-error-with-settimeout-738lpo) works with a 300ms delay, my real application in Ionic 6 needs at least 500ms. 
As a result, I need a high delay value and I have no way to ensure what it is the right value but guessing and testing.
Is there any other way to have this issue solved?

**Comment by hardmaster92** [comment] 2022-10-20 19:45
@Facj please refer to my comment above - use the lifecycle hook `ionViewDidEnter` and put your code there, this would solve the problem. Ionic has special lifecycle hooks for views because the framework related ones don't ensure that an ionic view is loaded

**Comment by Facj** [comment] 2022-10-24 07:15
@hardmaster92 thank you for your reply.

In your previous comment, you suggest using ionViewDidEnter lifecycle hook instead of framework related ones.
However, [my original code](https://codesandbox.io/s/firefox-error-rj98p) does not include any lifecycle hook, neither Ionic nor framework related.

It does not include imperative code either, only component rendering and configuration.
As a result, I am not sure of what should I include inside lifecycle hook ionViewDidEnter.

**Comment by hardmaster92** [comment] 2022-10-25 19:57
> 



> @hardmaster92 thank you for your reply.
> 
> In your previous comment, you suggest using ionViewDidEnter lifecycle hook instead of framework related ones. However, [my original code](https://codesandbox.io/s/firefox-error-rj98p) does not include any lifecycle hook, neither Ionic nor framework related.
> 
> It does not include imperative code either, only component rendering and configuration. As a result, I am not sure of what should I include inside lifecycle hook ionViewDidEnter.

It's where you render your Chart.js chart (it was also my case with the exception that I was using Angular and I implemented te chart.js adaptation myseld instead of using an external library). 

So in your case with a functional component you might try initializing the chart component using the `useIonViewWillEnter` hook for functional React components (either the component itself or the `data` object for the chart).
