### ISSUE TITLE
bug: ionic v6 no longer supports line breaks in the ion-toast component

### ISSUE THREAD

**Issue by corysmc** [ionic-team/ionic-framework#25778] opened 2022-08-17 21:47 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

Ionic v6 does not allow for line breaks in a toast.

<img width="713" alt="image" src="https://user-images.githubusercontent.com/6452188/185248777-fcc2424c-8a99-4800-a6ac-2ae90c7a643f.png">

### Expected Behavior

Ionic v5 allowed for line breaks in toast messages.

<img width="714" alt="image" src="https://user-images.githubusercontent.com/6452188/185248187-83a48674-6b6d-42ae-8647-623256c9cfd9.png">

### Steps to Reproduce

```tsx
const [presentToast] = useIonToast();

presentToast({
  message: "This is a message. \n this should be on a new line",
});
```

### Code Reproduction URL

[Ionic v6](https://codepen.io/corysmc/pen/oNqJZgw?editors=1010)
[Ionic v5](https://codepen.io/corysmc/pen/dymwvoz?editors=1010)

### Ionic Info

Ionic:

   Ionic CLI       : 6.20.1 
   Ionic Framework : @ionic/react 6.2.3-dev.11660337759.18ea0f7e

Capacitor:

   Capacitor CLI      : 4.0.1
   @capacitor/android : not installed
   @capacitor/core    : 4.0.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.6.0

System:

   NodeJS : v14.18.0 
   npm    : 6.14.15
   OS     : macOS Big Sur

### Additional Information

Related request:

https://github.com/ionic-team/pwa-elements/issues/34

**Comment by liamdebeasi** [comment] 2022-08-17 22:23
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. As noted in the [Ionic 6 breaking changes document](https://github.com/ionic-team/ionic-framework/blob/main/BREAKING.md#toast), the `--white-space` variable for `ion-toast` now defaults to `normal` instead of `pre-wrap`. This change was made to resolve https://github.com/ionic-team/ionic-framework/issues/21486.

To have toast respect line breaks, set `--white-space: pre-wrap`.

**Closed by liamdebeasi** 2022-08-17 22:23 UTC
Labels: triage
