### ISSUE TITLE
feat: Implementing a (swipe-up) bottom drawer with animations

### ISSUE THREAD

**Issue by nakamuraos** [ionic-team/ionic-framework#23839] opened 2021-08-28 16:11 UTC
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Implementing a (swipe-up) bottom drawer with animations as below image:
![](https://dev-to-uploads.s3.amazonaws.com/uploads/articles/vwmh0uc690lsi1speex8.png)

### Describe the Use Case

A modal can resize by users

**Comment by reslear** [comment] 2021-08-28 17:22
:) 
https://twitter.com/LiamDeBeasi/status/1430943354930581504

**Comment by EinfachHans** [comment] 2021-08-28 17:54
Also please search for existing issues before posting a new one: #21039

**Comment by liamdebeasi** [comment] 2021-08-30 13:21
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/21039. (This is coming soon!)

**Closed by liamdebeasi** 2021-08-30 13:21 UTC
Labels: triage
