### ISSUE TITLE
bug: Ionic 4 + Vue.js: Blank screen on Android 5.1 and Android 6.0

### ISSUE THREAD

**Issue by nk2048** [ionic-team/ionic-framework#19810] opened 2019-10-31 12:44 UTC
# Bug Report 

**Ionic version:**
[x] @ionic/core **4.11.3**
[x] @ionic/vue **0.0.4**

**Current behavior:**
Exceptions occur on Android 5.1 as well as on Android 6.0 since @ionic/core 4.6.0

Android 5.1:
"Uncaught TypeError: undefined is not a function", source: webpack-internal:///./node_modules/@ionic/core/dist/esm-es5/css-shim-206ea950-3169f23e.js (496)
Android 6.0:
"Uncaught TypeError: Array.from is not a function", source: webpack-internal:///./node_modules/@ionic/core/dist/esm-es5/css-shim-206ea950-3169f23e.js (496)

**Expected behavior:**
Running application without exceptions and blank screen. Support for Android 5.1 and 6.0.

**Other information:**
We think it's important to support Android 5.1 and 6.0 since many specialized Android devices (e.g. POS) are based on these OS versions.

**Steps to reproduce:**
```
vue create ionic-core-issue
cd ionic-core-issue
vue add router
npm install @ionic/vue
npm install @ionic/core
npm install ionicons@4.5.9-1 --save-dev
vue add cordova // Please select platform Android
```

Please add the following code block to main.js
```
import Ionic from '@ionic/vue';
import '@ionic/core/css/ionic.bundle.css';
Vue.use(Ionic);
```
Buld the app and run on Android 5.1

**Related code:**

main.js
```
import Vue from 'vue'
import App from './App.vue'
import router from './router'
import Ionic from '@ionic/vue';
import '@ionic/core/css/ionic.bundle.css';

Vue.use(Ionic);
Vue.config.productionTip = false

new Vue({
  router,
  render: h => h(App)
}).$mount('#app')
```

package.json
```
{
  "name": "ionic-core-issue",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint",
    "cordova-build-android": "cross-env CORDOVA_PLATFORM=android vue-cli-service cordova-build-android",
    "cordova-build-browser": "cross-env CORDOVA_PLATFORM=browser vue-cli-service cordova-build-browser",
    "cordova-build-ios": "cross-env CORDOVA_PLATFORM=ios vue-cli-service cordova-build-ios",
    "cordova-build-only-www-android": "cross-env CORDOVA_PLATFORM=android vue-cli-service cordova-build-only-www-android",
    "cordova-build-only-www-browser": "cross-env CORDOVA_PLATFORM=browser vue-cli-service cordova-build-only-www-browser",
    "cordova-build-only-www-ios": "cross-env CORDOVA_PLATFORM=ios vue-cli-service cordova-build-only-www-ios",
    "cordova-build-only-www-osx": "cross-env CORDOVA_PLATFORM=osx vue-cli-service cordova-build-only-www-osx",
    "cordova-build-osx": "cross-env CORDOVA_PLATFORM=osx vue-cli-service cordova-build-osx",
    "cordova-prepare": "vue-cli-service cordova-prepare",
    "cordova-serve-android": "cross-env CORDOVA_PLATFORM=android vue-cli-service cordova-serve-android",
    "cordova-serve-browser": "cross-env CORDOVA_PLATFORM=browser vue-cli-service cordova-serve-browser",
    "cordova-serve-ios": "cross-env CORDOVA_PLATFORM=ios vue-cli-service cordova-serve-ios",
    "cordova-serve-osx": "cross-env CORDOVA_PLATFORM=osx vue-cli-service cordova-serve-osx"
  },
  "dependencies": {
    "@ionic/core": "^4.11.3",
    "@ionic/vue": "0.0.4",
    "core-js": "^3.3.2",
    "vue": "^2.6.10",
    "vue-router": "^3.1.3"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^4.0.0",
    "@vue/cli-plugin-eslint": "^4.0.0",
    "@vue/cli-plugin-router": "^4.0.5",
    "@vue/cli-service": "^4.0.0",
    "babel-eslint": "^10.0.3",
    "eslint": "^5.16.0",
    "eslint-plugin-vue": "^5.0.0",
    "ionicons": "^4.5.9-1",
    "vue-cli-plugin-cordova": "^2.3.6",
    "vue-template-compiler": "^2.6.10"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/essential",
      "eslint:recommended"
    ],
    "rules": {},
    "parserOptions": {
      "parser": "babel-eslint"
    }
  },
  "postcss": {
    "plugins": {
      "autoprefixer": {}
    }
  },
  "browserslist": [
    "> 1%",
    "last 2 versions"
  ]
}
```

**Ionic info:**

```
Ionic:

   Ionic CLI : 5.4.2

Utility:

   cordova-res : not installed
   native-run  : 0.2.8

System:

   NodeJS : v10.16.2
   npm    : 6.9.0
   OS     : Windows 10
```

**Vue info:**

```
Environment Info:

  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 10.16.2 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.387.0
  npmPackages:
    @ionic/vue: 0.0.4 => 0.0.4
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.0.0
    @vue/babel-preset-app:  4.0.5
    @vue/babel-preset-jsx:  1.1.1
    @vue/babel-sugar-functional-vue:  1.0.0
    @vue/babel-sugar-inject-h:  1.0.0
    @vue/babel-sugar-v-model:  1.1.1
    @vue/babel-sugar-v-on:  1.1.0
    @vue/cli-overlay:  4.0.5
    @vue/cli-plugin-babel: ^4.0.0 => 4.0.5
    @vue/cli-plugin-eslint: ^4.0.0 => 4.0.5
    @vue/cli-plugin-router: ^4.0.5 => 4.0.5
    @vue/cli-plugin-vuex:  4.0.5
    @vue/cli-service: ^4.0.0 => 4.0.5
    @vue/cli-shared-utils:  4.0.5 (3.12.1)
    @vue/component-compiler-utils:  3.0.0
    @vue/preload-webpack-plugin:  1.1.1
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^5.0.0 => 5.2.3
    vue: ^2.6.10 => 2.6.10
    vue-cli-plugin-cordova: ^2.3.6 => 2.3.6
    vue-eslint-parser:  5.0.0
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.7.1
    vue-router: ^3.1.3 => 3.1.3
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.10 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
  npmGlobalPackages:
    @vue/cli: Not Found
```

**Comment by liamdebeasi** [comment] 2019-10-31 12:55
Thanks for the issue. Can you try this again without the additional `@ionic/core` dependency? `@ionic/vue` should already have a compatible version of `@ionic/core` as a child depndency.

**Comment by nk2048** [comment] 2019-10-31 13:00
I tried it too and got the same result (the same exception).

**Comment by liamdebeasi** [comment] 2019-10-31 13:03
Thanks for the follow up. What is the result of logging `navigator.userAgent` to the console when inspecting the app using Chrome Dev Tools? Either device is fine.

**Comment by hanning2014** [comment] 2019-10-31 13:15
the same error, can help? @liamdebeasi

**Comment by nk2048** [comment] 2019-10-31 21:54
Thank you for taking care of that matter. It's very important to me. 

The result of logging `navigator.userAgent` is:
**on the device with Android 5.1**
`Mozilla/5.0 (Linux; Android 5.1; V1-B18 Build/LMY47I) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/39.0.0.0 Mobile Safari/537.36`
**on the device with Android 6.0**
`Mozilla/5.0 (Linux; Android 6.0; JICAI Q2 Build/MRA58K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/44.0.2403.119 Mobile Safari/537.36`

**Comment by nk2048** [comment] 2019-11-07 10:33
@liamdebeasi As a workaround I tried to update the webview component on our devices with Android 5.1/6.0 to get Ionic working. Unfortunately I failed, since the devices cannot be rooted. Hence, resolution of the issue at the Ionic level is the only way to go. Any ideas?

**Comment by liamdebeasi** [comment] 2019-11-07 14:08
Thanks for the follow up. It looks like there may be some issues with using old versions of the Android WebView. I'll mark this as a bug and will post an update here when I have more info to share. Thanks!

**Comment by 50l3r** [comment] 2020-04-10 07:10
Hi,

I have similar error running ionic vue in Android 6.0

![](https://i.gyazo.com/470cbb729ff3427c6f6c74563a4fd5e2.png)

This is my app:18136 line

`eval("const deals = __webpack_require__(/*! ./_deals */ \"./node_modules/project-sdk/api/_deals.js\");\r\nconst customfeed = __webpack_require__(/*! ./_customfeed */ \"./node_modules/project-sdk/api/_customfeed.js\");\r\nconst tags = __webpack_require__(/*! ./_tags */ \"./node_modules/project-sdk/api/_tags.js\");\r\nconst users = __webpack_require__(/*! ./_users */ \"./node_modules/project-sdk/api/_users.js\");\r\nconst feed = __webpack_require__(/*! ./_feed */ \"./node_modules/project-sdk/api/_feed.js\");\r\nconst comments = __webpack_require__(/*! ./_comments */ \"./node_modules/project-sdk/api/_comments.js\");\r\nconst summaries = __webpack_require__(/*! ./_summaries */ \"./node_modules/project-sdk/api/_summaries.js\");\r\nconst admin = __webpack_require__(/*! ./admin */ \"./node_modules/project-sdk/api/admin/index.js\");\r\n\r\nmodule.exports = {\r\n\tdata() {\r\n\t\treturn {\r\n\t\t\tlimit: 10,\r\n\t\t\tloader: null,\r\n\t\t\tloaderController: null,\r\n\t\t};\r\n\t},\r\n\tmixins: [deals, customfeed, tags, users, feed, comments, summaries, admin],\r\n\tmethods: {\r\n\t\tresetStatus() {\r\n\t\t\tthis.loader = false;\r\n\t\t},\r\n\t\thelpers() {\r\n\t\t\treturn {\r\n\t\t\t\tformatDeals(items, formatDescription = false) {\r\n\t\t\t\t\tconst formatedDeals = [];\r\n\r\n\t\t\t\t\titems.forEach((deal) => {\r\n\t\t\t\t\t\tif (deal.sale_price) { deal.sale_price = parseFloat(deal.sale_price / 100).toString().replace('.', ','); }\r\n\t\t\t\t\t\tif (deal.old_price) { deal.old_price = parseFloat(deal.old_price / 100).toString().replace('.', ','); }\r\n\t\t\t\t\t\tif (deal.description && formatDescription) { deal.description = deal.description.replace(/<\\/?[^>]+?>/gi, '').replace(/<\\/?[a-z]+?$/i, ''); }\r\n\r\n\t\t\t\t\t\tformatedDeals.push(deal);\r\n\t\t\t\t\t});\r\n\r\n\t\t\t\t\treturn formatedDeals;\r\n\t\t\t\t},\r\n\t\t\t};\r\n\t\t},\r\n\t},\r\n};\r\n\n\n//# sourceURL=webpack:///./node_modules/project-sdk/api/index.js?");`

Maybe the arrow functions?

It is difficult for me to use the debugger because its bugged itself

![](https://i.gyazo.com/86e683511c63ca8cb5766226300a4573.png)

**Comment by shoutershub** [comment] 2020-09-06 19:47
Till date, no solution, this is so sad.

**Comment by Sitronik** [comment] 2021-11-08 21:03
Any news on how to fix this problem?

**Comment by liamdebeasi** [comment] 2022-05-16 20:35
Thanks for the issue. I took a closer look and the problem here is that the app is being run on an unsupported version of the Chrome/Android WebView. At the time of writing, we support Android devices with a webview of Chromium 60 or newer. 

The post in https://github.com/ionic-team/ionic-framework/issues/19810#issuecomment-548584562 indicated that the affected devices were using Chromium 39 and 44. 

When it comes to testing with a simulator, we recommend only using simulators that have "Google Play Services" enabled. The reason for this is these devices have webviews that can update. Simulators without "Google Play Services" are typically stuck on webviews that are years old.

In the screenshot below, the "Pixel 4", "Pixel 3a", "Pixel 3", and "Pixel 2" devices have Google Play Services as indicated by the Google Play logo in the "Play Store" column.

![image](https://user-images.githubusercontent.com/2721089/168677627-ac456c3f-89bd-4ff7-992d-d55ac5eb4fad.png)

I am going to close this as this is not a bug in Ionic. Thanks!

**Closed by liamdebeasi** 2022-05-16 20:35 UTC
Labels: package: core, type: bug
