### ISSUE TITLE
bug: react, error when dismissing inline popover after removing containing element

### ISSUE THREAD

**Issue by natqe** [ionic-team/ionic-framework#24391] opened 2021-12-14 09:43 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

When using `IonReorderGroup` with `React.Fragment` with multiple children, the number of `from` and `to` is higher then expected.

### Expected Behavior

Should calculate by the number of `IonReorder` element, or by the number of children that `IonReorderGroup` had (treat `Fragment` as one child).

### Steps to Reproduce

From the docs
```jsx
const items = [1, 2, 3]
function doReorder(event) {
  // The number that printed is wrong and not following the number of the `IonReorder` elements
  console.log('Dragged from index', event.detail.from, 'to', event.detail.to)
  event.detail.complete()
}
<IonReorderGroup disabled={false} onIonItemReorder={doReorder}>
 {items.map((item) => <Fragment key={item}>
    <IonItem>
     <IonLabel>Item {item}</IonLabel>
     <IonReorder slot="end" />
    </IonItem>
    <div></div>
    <div></div>
    <div></div>
    <div></div>
    <div></div>
    <div></div>
   </Fragment>)}
</IonReorderGroup>
```

**Comment by amandaesmith3** [comment] 2021-12-14 16:42
Thanks for the issue. Could you give more detail on your use case for using `Fragment` in this way? `IonReorderGroup` expects each child to be a separate `IonItem`, without any separate adjacent elements.

As it stands, the higher `from` and `to` values seem like intended behavior. This becomes more obvious if the extra `div`s have content inside them, as they get included in the reorder behavior and should therefore be counted.

**Comment by natqe** [comment] 2021-12-14 17:01
@amandaesmith3 this is my use case
```jsx
<>
        <IonItem>
            <IonReorder slot="start" />
            <IonLabel className="flex-column">
                <span>{desc ?? translate.NO_DESC}</span>
                <IonNote>{author ?? translate.NO_CREDITS}</IonNote>
            </IonLabel>
            <IonButtons slot="end">
                <IonButton onClick={openMenu}>
                    <IonIcon icon={ellipsisVertical} slot="icon-only" />
                </IonButton>
            </IonButtons>
        </IonItem>
        <IonPopover showBackdrop={false} ref={menuRef} {...{ event, isOpen }}>
            <IonItem onClick={handleEdit} button>
                {translate.EDIT} {translate.DETAILS}
            </IonItem>
            <IonItem onClick={handleChangeSelected} button>
                {changeOptionText}
            </IonItem>
            <IonItem onClick={handleDelete} button>
                {translate.DELETE}
            </IonItem>
        </IonPopover>
        <IonModal isOpen={openMeta} backdropDismiss={false} presentingElement={modalElement} ref={metaModalRef}>
            <Suspense fallback={null}>
                <ParagraphMeta {...metaProps} dismissModal={dismissMetaModal} />
            </Suspense>
        </IonModal>
        <IonModal backdropDismiss={false} isOpen={videoModalOpen} presentingElement={modalElement} ref={videoModalRef}>
            <Suspense fallback={null}>
                <PostEditVideo dismissModal={dismissVideoModal} />
            </Suspense>
        </IonModal>
        <IonModal backdropDismiss={false} isOpen={urlModalOpen} presentingElement={modalElement} ref={urlModalRef}>
            <Suspense fallback={null}>
                <PostEditUrl dismissModal={dismissUrlModal} />
            </Suspense>
        </IonModal>
    </>
```

**Comment by amandaesmith3** [comment] 2021-12-14 17:34
If you move the popovers and modals inside the `IonItem`, does that resolve the issue?

**Comment by natqe** [comment] 2021-12-14 18:00
@amandaesmith3 its working but its a hack and also crashes another issue when i try to delete an item and the popover is open, its stay open when it inside the item from some reason. also its took me a lot of time to understand that u do not counting Fragment as a element. so my suggestion is to clear it out on the docs or count the number by the `IonReorder` that exist in the list

**Comment by amandaesmith3** [comment] 2021-12-14 20:25
`Fragment` isn't counted as an element because `IonReorderGroup` only looks as the final rendered DOM. It is only intended to be used with `IonItem` or `IonReorder` as direct children. Using `Fragment` causes other elements to be added as siblings to the reorder items, which is not the intended usage.

Could you create a repo that reproduces the popover issue and post a link here?

**Comment by natqe** [comment] 2021-12-15 00:01
@amandaesmith3 yeah, but why it count other elements then 'IonItem' or 'IonReorder'? Better to strict it to count only the children of type 'IonItem' or 'IonReorder'. Anyway for saving the time for react developer that can find themselves straggling why 'Fragment' doesn't work, I think is better to have this topic included in the docs

**Comment by amandaesmith3** [comment] 2021-12-15 14:28
Other elements are counted because they are part of the DOM -- in your original example with the `div`s, if content is added to them, the reorder elements can be moved between them. It wouldn't make sense for those `div`s not to count. See screencast: https://user-images.githubusercontent.com/90629384/146204449-79a26ed2-ba0e-4e02-bc3d-ee42504e3919.mp4

Fragment does not count because it does not render anything in the DOM. Items not in the DOM do not have an index, by definition.

Are you able to solve the popover issue mentioned here?
> when i try to delete an item and the popover is open, its stay open when it inside the item from some reason.

If not, could you provide a repo reproducing the issue, or try closing the popover (setting `isOpen` to `false`) when an item is deleted? It doesn't look like there is a bug with Ionic.

**Comment by natqe** [comment] 2021-12-17 06:43
@amandaesmith3 now i'm facing another issue when trying to create the reproduced code. the item inside the popover is not clickable for some reason.
```jsx
const List = () => {
  const [items, setItems] = useState([1, 2, 3, 4, 5])
  return <>
    {items.map(item => <Item key={item} item={item} setItems={setItems} />)}
  </>
}

const Item = ({ setItems, item }) => {
  const [event, setEvent] = useState(null)
  const [isOpen, setIsOpen] = useState(false)
  return <IonItem>
    item {item}
    <IonButtons slot="end">
      <IonButton onClick={(e) => {
        setEvent(e)
        setIsOpen(true)
      }}>
        <IonIcon icon={ellipsisVertical} slot="icon-only" />
      </IonButton>
    </IonButtons>
    <IonPopover event={event} isOpen={isOpen}>
      <IonItem onClick={() => {
        console.log('clicked') // this is not working
        setEvent(null)
        setIsOpen(false)
        setItems(items => items.filter(i => item !== i))
      }} button>
        remove
      </IonItem>
    </IonPopover>
  </IonItem>
}
```

**Comment by natqe** [comment] 2021-12-17 06:55
@amandaesmith3 I created a little snippet showing the popover issue when it inside an item:
```jsx
import '@ionic/core/css/ionic.bundle.css'
import { IonApp, IonButton, IonButtons, IonIcon, IonItem, IonList, IonPopover, setupIonicReact } from '@ionic/react'
import { ellipsisVertical } from 'ionicons/icons'
import { useState } from 'react'
import { createRoot } from 'react-dom'

const App = () => {
  const [items, setItems] = useState([1, 2, 3, 4, 5])
  return <IonApp>
    <IonList>
      {items.map(item => <Item key={item} item={item} setItems={setItems} />)}
    </IonList>
  </IonApp>
}

const Item = ({ setItems, item }) => {
  const [event, setEvent] = useState(null)
  const [isOpen, setIsOpen] = useState(false)
  return <IonItem>
    item {item}
    <IonButtons slot="end">
      <IonButton onClick={(e) => {
        setEvent(e)
        setIsOpen(true)
      }}>
        <IonIcon icon={ellipsisVertical} slot="icon-only" />
      </IonButton>
    </IonButtons>
    <IonPopover event={event} isOpen={isOpen}>
      <IonItem onClick={() => {
        console.log('clicked') // this is not working
        setEvent(null)
        setIsOpen(false)
        setItems(items => items.filter(i => item !== i))
      }} button>
        remove
      </IonItem>
    </IonPopover>
  </IonItem>
}

createRoot(document.getElementById('root')).render(<App />)
```

**Comment by amandaesmith3** [comment] 2021-12-17 17:10
Thanks! I'm able to reproduce the error. When a popover is opened, it is moved to the bottom of the `ion-app`. The error happens when Ionic tries to move the popover back to its original place, which in this case no longer exists. While a core JS popover fails gracefully, React errors out.

A possible fix would be if the popover could detect that its original location has been removed, and automatically dismiss itself. We'll investigate this as a team and let you know when we have more to share.

In the meantime, a workaround would be to use the `useIonPopover` hook outside the `Item` component. This avoids both the error on dismiss (because the hook simply adds and removes the popover from the DOM, rather than moving it around), and the popover not closing (because its state is managed outside the removed `Item`). Here's a code snippet putting both this and the `IonReorderGroup` together:

```jsx
import { IonButton, IonButtons, IonContent, IonHeader, IonIcon, IonItem, IonPage, IonReorder, IonReorderGroup, IonTitle, IonToolbar, useIonPopover } from '@ionic/react';
import { ellipsisVertical } from 'ionicons/icons'
import { useState } from 'react';

const Home: React.FC = () => {
  const [items, setItems] = useState([1, 2, 3, 4, 5]);
  const [itemToRemove, setItemToRemove] = useState(null);
  const handlePresent = (data) => present(data);
  const handleDismiss = () => dismiss();
  const [present, dismiss] = useIonPopover(Popover, { setItems, itemToRemove, handleDismiss });

  function doReorder(event) {
    console.log('Dragged from index', event.detail.from, 'to', event.detail.to)
    event.detail.complete()
  }

  return (
    <IonPage>
      <IonContent>        
        <IonReorderGroup disabled={false} onIonItemReorder={doReorder}>
          { items.map(item => <Item key={item} item={item} setItemToRemove={setItemToRemove} handlePresent={handlePresent} />) }
        </IonReorderGroup>
      </IonContent>
    </IonPage>
  );
};

const Item = ({ item, setItemToRemove, handlePresent }) => {  
  return <IonItem>
    item {item}
    <IonButtons slot="end">
      <IonButton onClick={(e) => {
        setItemToRemove(item);
        handlePresent({ event: e.nativeEvent });
      }}>
        <IonIcon icon={ellipsisVertical} slot="icon-only" />
      </IonButton>
      <IonReorder />
    </IonButtons>
  </IonItem>
}

const Popover = ({ setItems, itemToRemove, handleDismiss }) => {
  return (
    <IonItem onClick={() => {
      handleDismiss();
      setItems((items) => items.filter((i) => itemToRemove !== i));
    }} button>
      remove
    </IonItem>
  )
}

export default Home;

```

**Comment by amandaesmith3** [comment] 2022-01-12 20:51
I've resolved the error when dismissing the popover via https://github.com/ionic-team/ionic-framework/pull/24569, and the fix will be available in a future release of Ionic 👍 

I talked with the team about the popover staying open when the item is removed, and we decided that this is intended behavior. You can add `dismissOnSelect={true}` to the popover to have it close automatically when "Remove" is clicked: https://ionicframework.com/docs/api/popover#dismissonselect

Alternatively, if you'd like more fine-grained control over the popover's behavior, you can manually dismiss it instead: `document.querySelector('ion-popover:not(.overlay-hidden)').dismiss()`

Thank you for using Ionic!

**Closed** 2022-01-12 20:51 UTC
Labels: package: react, type: bug
