### ISSUE TITLE
bug: Navigation between pages from different nested IonRouterOutlet's breaks UI due to outlets overlap

### ISSUE THREAD

**Issue by alekseykarpenko** [ionic-team/ionic-framework#20219] opened 2020-01-17 08:52 UTC
# Bug Report

**Ionic version:**

[x] **4.11.8** (latest)

**Current behavior:**
When trying to navigate between two pages from different `IonRouterOutlets` UI is flickering and breaks, as non active outlet is on the top of others, making all visible UI elements unreachable.

<img src="https://user-images.githubusercontent.com/4648983/72596964-74821500-3915-11ea-8db7-dfbc1c2e7020.gif" width="250">

**Expected behavior:**
Navigation between two pages from different nested `IonRouterOutlet`'s should be possible. Router outlets shouldn't overlap each other, correctly determining which of them is active now (on the top of others).

<img src="https://user-images.githubusercontent.com/4648983/72597460-844e2900-3916-11ea-900b-9ca4f41c42e1.gif" width="250">

**Steps to reproduce:**

Basically, what I'm trying to do is navigation between two pages `Home` (`/home`) and List (`/list`), both of them are inside global `IonRouterOutlet`, and both have inner `IonRouterOutet` for their own nested routes, as described in [Docs](https://ionicframework.com/docs/react/navigation#nested-routes). And here is a deal: I want to navigate directly from nested route of `Home` (e.g. `/home/welcome`) to the nested route of the `List`  (e.g. `/list/:id`) with correct page transition. And it even works... but only for the first time. Then there are 3 different outlets in DOM overlapping each other, two with `z-index: 0` (one of them is needed),  and another (incorrect) with `z-index:101`, so UI is blocked with transparent alien outlet.

**Related code:**

https://gist.github.com/alekseykarpenko/6e5c71f915cf53eeee896e24ab1ee562/7af928cff5ee6a6553d4fa899d22f5874cc9cb42

**Other information:**

❗️ Looks like this is strictly related to #18197, #18823, #18845 (all of those Angular issues have been opened since last summer). 
The quick workaround for me here was moving `List`'s nested routes into parent `IonRouterOutlet`:

```tsx
<IonApp>
  <IonReactRouter>
      <IonRouterOutlet>
        {/*<Route path="/list" component={ListPage}/>*/}
        <Route path="/list" component={List} exact={true}/>
        <Route path="/list/:id" component={Item}/>
        <Route path="/home" component={HomePage}/>
        <Route path="/" render={() => <Redirect to="/home"/> } exact={true} />
      </IonRouterOutlet>
  </IonReactRouter>
</IonApp>
```
https://gist.github.com/alekseykarpenko/6e5c71f915cf53eeee896e24ab1ee562/7af928cff5ee6a6553d4fa899d22f5874cc9cb42

But that's not a real gold bullet, I want it back 😢 Actually, I have two reasons for that: 1) Use all power of React Router nested routes; and 2) Place `Home` inside Tabs View while `List` will not be there and add Side Menu to both of them within the global `IonRouterOutlet`. 

**Thoughts on fixing this**
Even while both pages are in different nested outlets, they have same global outlet. Looks like navigation goes in right way, but outlet controller can't determine current active outlet, giving incorrect `z-index`.

**Ionic info:**

```
Ionic:

   Ionic CLI       : 5.4.11 (/Users/ak/.nvm/versions/node/v10.16.3/lib/node_modules/ionic)
   Ionic Framework : @ionic/react 4.11.8

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.16.3 (/Users/ak/.nvm/versions/node/v10.16.3/bin/node)
   npm    : 6.9.0
   OS     : macOS Catalina

```

Best regards and thanks for all that you do 💪 Keep em going.

**Comment by alekseykarpenko** [comment] 2020-01-28 00:06
@elylucas any plans on this? It should be a disgusting limitation while building an architecture of the future app ;(

**Comment by jcarignan** [comment] 2020-03-11 04:36
Any updates with this? @elylucas 
The bug is also present in the Ionic Conference React App demo by editing two lines:

**src/components/Menu.tsx:65**
remove `routerDirection="none"` on the _IonItem_

**src/pages/MainTabs.tsx:18**
add `mode="ios"` on the _IonRouterOulet_

What I find really confusing is how the docs says : 
> An IonRouterOutlet should also not be a descendant from another IonRouterOutlet.

**Comment by elylucas** [comment] 2020-06-23 22:55
Hi @alekseykarpenko, @jcarignan,

We have a dev release that provides better support for nested IonRouterOutlet components. There is a new prop on IonRouterOutlet that lets the router know it is a nested outlet to better perform the transition.

If your'e outlet is a nested outlet directly rendered by a Route in a parent outlet, then use the `ionPage` prop on the IonRouterOutlet. Here is an example:

App.tsx:
```
const App: React.FC = () => (
  <IonRouterOutlet>
    <Route path="/sub1" component={Sub1Outlet}  />
    <Route path="/sub2" component={Sub2Outlet} />
  </IonRouterOutlet>
);
```

Sub1Outlet.tsx:
```
const Sub1Outlet: React.FC = () =>  (
    <IonRouterOutlet ionPage>
      <Route path="/sub1" exact={true} 
        render={() => <Redirect to="/sub1/page" />} />
      <Route path="/sub1/page" component={Page1} exact={true} />
    </IonRouterOutlet>
  );
```

Sub2Outlet.tsx:
```
const Sub2Outlet: React.FC = () =>  (
    <IonRouterOutlet ionPage>
      <Route path="/sub2" exact={true} 
        render={() => <Redirect to="/sub2/page" />} />
      <Route path="/sub2/page" component={Page2} exact={true} />
    </IonRouterOutlet>
  );
```

If you can, could you try to install it and let us know if it fixes the issue and if you run into any others? To install it run:

`npm i @ionic/react@5.3.0-dev.202006222125.df37029 @ionic/react-router@5.3.0-dev.202006222125.df37029`

If all goes good this should be available in the next Ionic release.

Thanks!

**Comment by MrWillTurner** [comment] 2020-07-22 14:37
Hi, I had the same problem where my app flickered when navigating and stop working at one point but, your dev release resolved it.

But instead of using two `IonRouterOutlet`  I use only one them on my App page and a `BrowserRouter` on my 'EventPage' to create a page tab system. 

App.tsx
 ```<IonApp>
        <IonReactRouter>
            <IonTabs>
                <IonRouterOutlet>
                    <Switch>
                        <Route path="/event/:id" component={EventPage} exact/>
                        <Route path="/newEvent" component={NewEventPage} exact/>
                        <Route path="/" render={() => <Redirect to="/home"/>} exact/>
                        <Route path="/home" component={Home} exact/>
                        <Route path="/tab2" component={Tab2} exact/>
                        <Route path="/tab2/details" component={Details}/>
                        <Route path="/tab3" component={Tab3} exact/>
                    </Switch>
                </IonRouterOutlet>
                <IonTabBar slot="bottom" color={"primary"}>
                    <IonTabButton tab="tab1" href="/home">
                        <IonLabel>Home</IonLabel>
                    </IonTabButton>
                    <IonTabButton tab="tab2" href="/tab2">
                        <IonLabel>Search</IonLabel>
                    </IonTabButton>
                    <IonTabButton tab="tab3" href="/tab3">
                        <IonLabel>Notifications</IonLabel>
                    </IonTabButton>
                </IonTabBar>
            </IonTabs>
        </IonReactRouter>
    </IonApp>
```


EventPage.tsx:
```        <IonPage>
            <IonHeader>
                <IonToolbar color={"primary"}>
                    <IonButtons slot="start">
                        <IonBackButton defaultHref="/"/>
                    </IonButtons>
                </IonToolbar>
            </IonHeader>
            <IonContent>
                <BrowserRouter>
                    <ul className={"eventTabs"}>
                        <li><NavLink to={`${match.url}details`}  className="tab">Details</NavLink></li>
                        <li><NavLink to={`${match.url}tasks`} className="tab">Tasks</NavLink></li>
                    </ul>
                    <div className="content">
                        <Route path={`${match.url}details`}  component={EventDetails}/>
                        <Route path={`${match.url}tasks`} component={EventTasks}/>
                        <Redirect exact from={`${match.url}`} to={`${match.url}details`} />
                    </div>
                </BrowserRouter>
            </IonContent>
        </IonPage>
```

Thanks for the release.

**Comment by adamduren** [comment] 2020-11-30 16:13
Adding `ionPage` to the nested `IonRouterOutlet` fixed it for me. It seems like documentation for this is needed as well as updates to the Nested Routes section of [Ionic React Navigation](https://ionicframework.com/docs/react/navigation)

**Comment by mauriceackel** [comment] 2021-02-26 01:27
Hello @elylucas, is there any way to confirm that this solution is still working? I am using the following setup of my app:

```
    <IonApp>
      <IonReactRouter>
        <Switch>
          <Route path="/administration/" component={Administration} />
          
          <IonTabs>
            <IonRouterOutlet>
              <Route path="/list/" component={List} />
              <Route path="/account/" component={Account} />
              <Route path="/checkin/" component={CheckIn} exact />

              <Redirect from="/" to="/list/" exact />
            </IonRouterOutlet>

            <IonTabBar slot="bottom">
              <IonTabButton tab="list" href="/list/">
                <IonLabel>List</IonLabel>
              </IonTabButton>
              <IonTabButton tab="account" href="/account/">
                <IonLabel>Account</IonLabel>
              </IonTabButton>
              <IonTabButton tab="checkin" href="/checkin/">
                <IonLabel>Checkin</IonLabel>
              </IonTabButton>
            </IonTabBar>
          </IonTabs>
        </Switch>
      </IonReactRouter>
    </IonApp>
```

And inside my `Account` component I export the following:
```
function AccountRouter({ match }: RouteComponentProps): ReactElement {
  return (
    <IonRouterOutlet ionPage>
      <Route exact path={match.path} component={Account} />
      <Route path={`${match.path}details/`} component={Details} />
      <Route path={`${match.path}credentials/`}  component={Credentials} />
    </IonRouterOutlet>
  );
}
```

So I am basically using the setup as explained in the docs together with your fix proposed here. However, if I navigate to the subpage `Details` inside this nested Ion router outlet an back again, the following happens:


https://user-images.githubusercontent.com/20804369/109241704-168f5480-77da-11eb-9669-d1c4bd0018ec.mov

**Comment by I-am-abdulazeez** [comment] 2021-03-24 14:00
Any solution... currently facing the same issue

**Comment by amandaesmith3** [comment] 2022-02-02 14:36
Hi folks, I wanted to circle back to this.

I've created an issue on the docs repo for the missing `ionPage` prop: https://github.com/ionic-team/ionic-docs/issues/2183 I'll be following up on this in the near future.

As for the flickering issue: since the `ionPage` fix has since been released, and other changes have been made to routing since then, would it be possible to create a minimal repo replicating the issue using the latest version of Ionic 6?

**Comment by amandaesmith3** [comment] 2022-02-16 20:26
Closing this out due to a lack of reproduction for the latest-mentioned issue, and the fact that the original issue has already been solved (the solution just needs documenting). If anyone is still encountering any problems mentioned here on the latest version of Ionic, please open a separate issue with its own code reproduction. Thank you!

**Closed by amandaesmith3** 2022-02-16 20:26 UTC
Labels: package: react, ionitron: needs reproduction
