### ISSUE TITLE
bug: Swipe back animation direction in RTL iOS

### ISSUE THREAD

**Issue by LiveXenon** [ionic-team/ionic-framework#19488] opened 2019-09-28 15:32 UTC
# Bug Report

**Ionic version:**
5.4.1

**Current behavior:**
When you go back through the swipe on ios the animation remains that of LTR.
![RTLSWIPEANIMATIONERROR](https://user-images.githubusercontent.com/34724827/65818835-c2afc300-e215-11e9-82c3-4370210a26b4.gif)

**Ionic info:**

Ionic:

   Ionic CLI                     : 5.4.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.10.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Capacitor:

   Capacitor CLI   : 1.0.0
   @capacitor/core : 1.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 20 other plugins)

Utility:

   cordova-res : 0.3.0 (update available: 0.6.0)
   native-run  : 0.2.8 

System:

   ios-sim : 8.0.2
   NodeJS  : v10.15.0 (/usr/local/bin/node)
   npm     : 6.11.2
   OS      : macOS Mojave
   Xcode   : Xcode 10.3 Build version 10G8

**Comment by abuassar** [comment] 2020-02-29 19:42
this issue still valid in ionic 5.0.4

**Comment by 3adeling** [comment] 2020-07-13 05:32
still valid in ionic 5.2.3

**Comment by blahblehblah** [comment] 2020-08-06 20:35
Devastated that you're ignoring rtl.

**Comment by ItayElgazar** [comment] 2020-11-10 19:31
the issue is still there, is there any workaround?

**Comment by emps** [comment] 2020-12-30 16:20
i need this fix please

**Comment by brhoomjs** [comment] 2021-03-01 23:25
any update?

**Comment by ItayElgazar** [comment] 2021-04-15 13:54
BUMP?

**Comment by Elwazeery** [comment] 2021-07-11 18:14
Still no fix

**Comment by brhoomjs** [comment] 2021-09-10 12:33
> I fixed it by add dir="rtl" to the "ion-app" not the "html" in the index.html

not working

**Comment by NarSiiiS** [comment] 2021-12-06 18:35
still valid in ionic 6

**Comment by liamdebeasi** [comment] 2022-03-01 14:12
Thanks for the issue. Can everyone try the following dev build and let me know if it resolves the issue?

```
6.0.10-dev.11646143594.60e3f1c
```

This dev build applies to all of the Ionic Framework packages. Example:

```
npm install @ionic/angular@6.0.10-dev.11646143594.60e3f1c
```

**Comment by liamdebeasi** [comment] 2022-03-07 13:59
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/24866, and a fix will be available in an upcoming release of Ionic Framework.

Please feel free to continue testing the dev build, and let me know if you run into any issues.

**Closed** 2022-03-07 13:59 UTC
Labels: package: core, type: bug
