### ISSUE TITLE
bug: datetime, ios, looping between months when minimum date is set. wheel stops to current year.

### ISSUE THREAD

**Issue by filipelle** [ionic-team/ionic-framework#28869] opened 2024-01-23 16:20 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When a min value is set to the ionic datetime, when the user click on the caret to go to the next month the interface flickers between the two months. It seems that it was a resolved issue [here](https://github.com/ionic-team/ionic-framework/issues/25752). also the wheel stops at the current year even if there is no max set (see image below)
![Screenshot 2024-01-23 alle 17 12 50](https://github.com/ionic-team/ionic-framework/assets/44807059/d0c4aadb-e4f7-4d29-8232-7d40e4c183ee)

### Expected Behavior

the wheel should let the user go through all the upcoming years.
the user should be able to select a date and the month should change

### Steps to Reproduce

add a datetime in a modal
```
<ion-modal [keepContentsMounted]="true">
      <ng-template>
        <ion-datetime id="datetime" [min]="today"> </ion-datetime>
      </ng-template>
    </ion-modal>
 <ion-datetime-button datetime="datetime" class="dp"></ion-datetime-button>
```
today is an iso string (new Date().toISOString())

tested on iphone 14 pro ios 17.2.1

### Ionic Info

Ionic:

   Ionic CLI                     : 7.1.6 (/opt/homebrew/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.6.2
   @angular-devkit/build-angular : 17.0.8
   @angular-devkit/schematics    : 17.0.8
   @angular/cli                  : 17.0.8
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.6.0
   @capacitor/android : 5.6.0
   @capacitor/core    : 5.6.0
   @capacitor/ios     : 5.6.0

Utility:

   cordova-res : 0.15.4
   native-run  : 2.0.0

System:

   NodeJS : v21.5.0 (/opt/homebrew/Cellar/node/21.5.0/bin/node)
   npm    : 10.2.4
   OS     : macOS Unknown

**Comment by liamdebeasi** [comment] 2024-01-23 21:18
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/28432.

**Closed by liamdebeasi** 2024-01-23 21:18 UTC
Labels: triage
