### ISSUE TITLE
feat: add form attribute for ion-button

### ISSUE THREAD

**Issue by Spinnenzunge** [ionic-team/ionic-framework#23712] opened 2021-08-02 13:50 UTC
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Add the html 5 form attribute (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#attr-form) for buttons on the ion-button component

### Describe the Use Case

This lets the button element inside ion-button associate with a form element in the dom. Especially useful if the ion-button type="submit" can not be placed inside a form element, e.g. if we want to place it inside the ion-footer container but the form is inside ion-content

### Describe Preferred Solution

Just pass the form attribute (and maybe other form specific attributes specified in https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button) to its native button element inside the shadow dom

**Comment by liamdebeasi** [comment] 2021-08-02 14:06
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/21194.

**Closed by liamdebeasi** 2021-08-02 14:06 UTC
Labels: triage
