### ISSUE TITLE
bug: [iOS] Page scroll freezes on first time to scroll page

### ISSUE THREAD

**Issue by tetsuwanadam** [ionic-team/ionic-framework#24732] opened 2022-02-07 15:52 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

In iOS, when first scrolling a page, the scroll freezes midway. Subsequent page scrolls in any page work without issue.

### Expected Behavior

Page should scroll smoothly.

### Steps to Reproduce

After opening the app, scroll any page with a flick.

### Code Reproduction URL

https://github.com/tetsuwanadam/ionic-test/commits/page-initial-scroll-freeze

### Ionic Info

Ionic:

   Ionic CLI       : 6.18.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 6.0.5

Capacitor:

   Capacitor CLI      : 3.4.0
   @capacitor/android : not installed
   @capacitor/core    : 3.4.0
   @capacitor/ios     : 3.4.0

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v16.1.0 (/usr/local/bin/node)
   npm    : 7.24.1
   OS     : macOS Big Sur

### Additional Information

I believe this issue arose either with the iOS 15.3 update or possibly the Ionic Vue 6.0.4 update.

**Comment by liamdebeasi** [comment] 2022-02-07 16:24
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/24435.

**Closed by liamdebeasi** 2022-02-07 16:24 UTC
Labels: triage
