### ISSUE TITLE
bug: legacy radios in ion-select creates retainer when used in popover

### ISSUE THREAD

**Issue by sejalshah1107** [ionic-team/ionic-framework#27786] opened 2023-07-12 18:15 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

I have created a 'ion-select' with interface set as popover.

On selection of an select-option, the DOM Nodes created for displaying the options are not released

### Expected Behavior

DOM Nodes should be released upon selection / dismissal

### Steps to Reproduce

        <ion-select interface="popover" placeholder="testing">
          <ion-select-option *ngFor="let a of [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1], let i = index">
            {{ "page " + (i + 1) }}
          </ion-select-option>
        </ion-select>

the above following code generates the said behaviour. DOM Node count can be monitored in the 'Performance Monitor' tool

### Ionic Info

Ionic:

   Ionic CLI                     : 7.1.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.0.2
   @angular-devkit/build-angular : 15.2.6
   @angular-devkit/schematics    : 15.2.8
   @angular/cli                  : 15.2.8
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 4.7.3
   @capacitor/android : not installed
   @capacitor/core    : 4.7.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v18.16.0 (/home/yg/.nvm/versions/node/v18.16.0/bin/node)
   npm    : 9.5.1
   OS     : Linux 5.15

**Comment by sejalshah1107** [comment] 2023-07-17 17:15
thank you for your response.

as required, please find the code checked in at https://github.com/sejalshah1107/ionic_bugs


best,
sejal

**Comment by liamdebeasi** [comment] 2023-07-18 15:19
Thanks for the reproduction. I can reproduce the reported behavior, and it looks like this impacts the legacy form controls and not the modern form controls. We are planning to update the form controls in `ion-select` to use the modern syntax in https://github.com/ionic-team/ionic-framework/issues/27071, so this issue should be resolved once #27071 is fixed.

**Comment by liamdebeasi** [comment] 2023-08-01 17:55
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/27818, and a fix will be available in an upcoming release of Ionic Framework.

**Closed** 2023-08-01 17:55 UTC
Labels: package: core, type: bug
