### ISSUE TITLE
bug: Gestures don't work if used in the same page as refresher

### ISSUE THREAD

**Issue by AlanAcDz** [ionic-team/ionic-framework#22594] opened 2020-11-28 00:55 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

Attempting to use a gesture defined using the GestureController does not work if there's an ion-refresher element in the same page, even if the gesture's specified direction is 'x'

**Expected behavior:**

The defined gesture should work alongside the refresher

**Steps to reproduce:**

- Inside an Ionic Angular app, create a directive to hold the gesture definition
- If the directive is used in a page that does not have an ion-refresher the gesture works fine
- If the page does have an ion-refresher the gesture does not work

**Related code:**

[Sample application repo](https://github.com/AlanAcDz/ionic-gestures-refresher)

The sample was created with Ionic CLI using tabs template
- Tab 1 shows how the gestures do not work if a refresher is present
- Tab 2 shows that the gestures work if no refresher is there

**Other information:**

Did not test in device but issue is present in both Chrome and Edge browsers.

The defined gesture in the refresher's page does emit the notCaptured event. I have included logs for the gesture's events in the code sample.

I also think #22439 is a related issue but didn't have a reproduction

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.12.1 (\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.5.1
   @angular-devkit/build-angular : 0.1100.2
   @angular-devkit/schematics    : 11.0.2
   @angular/cli                  : 11.0.2
   @ionic/angular-toolkit        : 2.3.3

Capacitor:

   Capacitor CLI   : 2.4.3
   @capacitor/core : 2.4.3

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.16.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.8
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment] 2020-11-30 15:21
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The problem here is that you have not provided a `gesturePriority` when creating your gesture, causing it to have a priority of 0 by default. The refresher gesture has a priority greater than 0, so it will always activate first over your custom gesture.

The refresher has a priority of 31, so setting your gesture to have a priority of 32 or more should be fine.

**Closed by liamdebeasi** 2020-11-30 15:21 UTC
Labels: triage
