### ISSUE TITLE
bug: ion-img should accept draggable prop

### ISSUE THREAD

**Issue by magoarcano** [ionic-team/ionic-framework#21325] opened 2020-05-18 14:08 UTC
This basic functionality of html should work as <img draggable="false> so we can disable the default drag option for <img>

**Comment by magoarcano** [comment] 2020-05-18 20:44
It's simple to reproduce.
I don't mean about Drag and Drop functionality. I mean that by default `<img>` types are draggable: (i.e. you can try to drag the avatar image in this page and you will see a shadowed copy of the image)

I made an app where the user can drag and rotate markers on an image. The experience is annoying if the image is draggable. With normal `<img>` tags works great. But `<ion-img>` doesn't work as expected.

I made demo here: https://stackblitz.com/edit/ionic-pnlxgp?file=pages%2Fhome%2Fhome.html
Steps for reproduce:
**Draggable, OK:**
`<img src= "https://hackernoon.com/hn-images/1*nlhD6_U277a1s_VxSbH11g.jpeg">`
**Not Dragable: OK**
`<img src= "https://hackernoon.com/hn-images/1*nlhD6_U277a1s_VxSbH11g.jpeg"  draggable="false">
`
**Should not be draggable, but it is.**
`<img src= "https://hackernoon.com/hn-images/1*nlhD6_U277a1s_VxSbH11g.jpeg" draggable="false">`

**Comment by cerkiner** [comment] 2020-06-03 03:43
The problem is that the browser defaults to `true` for `<img>` tag's draggable. When rendered `draggable={false}` in stenciljs, it won't pass draggable attribute because it evaluates the absence of an attribute as same as false. Then browser defaults to `draggable="true"` causing an unwanted result.

**Comment by cerkiner** [comment] 2020-06-03 10:29
> The problem is that the browser defaults to `true` for `<img>` tag's draggable. When rendered `draggable={false}` in stenciljs, it won't pass draggable attribute because it evaluates the absence of an attribute as same as false. Then browser defaults to `draggable="true"` causing an unwanted result.
> 
> EDIT;
> Unfortunately, the type of img.draggable attribute is boolean. 
> _(JSX attribute) JSXBase.HTMLAttributes<HTMLImageElement>.draggable?: boolean | undefined_
> 

@liamdebeasi issue mentioned here;  https://github.com/ionic-team/stencil/issues/2484

**Comment by simonhaenisch** [comment] 2020-06-03 11:29
@liamdebeasi I submitted a fix for this in Stencil. So after this is out and upgrading, you'll just need to pass the `draggable` attribute on to the actual image tag here

https://github.com/ionic-team/ionic/blob/c7e94a1f2377bd578dd748038196453975109c20/core/src/components/img/img.tsx#L99-L106

like so:

```tsx
<img
  // ....
  draggable={this.el.getAttribute('draggable') || undefined}
/>
```

**Comment by cerkiner** [comment] 2020-06-08 01:47
I just tested with "@stencil/core": "^1.15.0-2" and I can confirm it will be achievable after stencil upgrade.

**Closed** 2022-02-21 16:50 UTC
Labels: package: core, type: bug
