### ISSUE TITLE
bug: Ion-select unnecessarily triggers `ionChange` event when manually update or set value

### ISSUE THREAD

**Issue by LucidSolutions** [ionic-team/ionic-framework#22768] opened 2021-01-14 13:52 UTC
I’m using a ionic + capacitor.
ion-select unnecessarily triggers `ionChange` event when manually update or set value
How to Fix that?
It should be The change event should be triggered only when the control is toggled by user interaction, not when we set it value in ts code.

## Working Environment

```

Ionic:

   Ionic CLI                     : 6.11.8 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.5.2
   @angular-devkit/build-angular : 0.1000.8
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Capacitor:

   Capacitor CLI   : 2.4.5
   @capacitor/core : 2.4.5

Utility:

   cordova-res : 0.15.1
   native-run  : 1.1.0

System:

   NodeJS : v12.17.0 (/usr/local/bin/node)
   npm    : 6.14.10
   OS     : Linux 4.4

```

## See my sample code on Github

https://github.com/LucidSolutions/ionselect-error

**Comment by liamdebeasi** [comment] 2021-01-14 15:28
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/20106.

**Closed by liamdebeasi** 2021-01-14 15:28 UTC
Labels: triage
