### ISSUE TITLE
bug: List in inline modal last item is cut off

### ISSUE THREAD

**Issue by ZachHandley** [ionic-team/ionic-framework#27470] opened 2023-05-12 22:44 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

I have attempted to create a modal with an `ion-list` inside it in Vue 3.X (latest), it is supposed to show all the way to the bottom, but the content of the modal does not scroll to the last item, it is instead cut off. I have seen the other issues that were supposedly resolved, but perhaps the bug has resurfaced.

### Expected Behavior

Modal scrolls the content

### Steps to Reproduce

1. Create a modal with a toolbar
2. Create enough list items to overflow the parent
3. Experience bug

### Code Reproduction URL

https://stackblitz.com/edit/aawkvs?file=src/components/Example.vue

### Ionic Info

Ionic:

   Ionic CLI       : 7.0.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 7.0.6

Capacitor:

   Capacitor CLI      : 5.0.3
   @capacitor/android : 5.0.3
   @capacitor/core    : 5.0.3
   @capacitor/ios     : 5.0.3

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v20.1.0 (/usr/local/Cellar/node/20.1.0/bin/node)
   npm    : 9.6.4
   OS     : macOS Unknown

### Additional Information

Code reproduction is based on the example online from docs with additional elements copy + pasted

**Comment by typefox09** [comment] 2023-05-14 06:55
I'm having the exact same issue, I noticed the problem is coming from having an ion-header inside of an ion-modal. 

Can also provide minimum code example if needed.
![Screenshot 2023-05-14 at 4 54 50 pm](https://github.com/ionic-team/ionic-framework/assets/61811299/cafaa599-91c0-4087-a2bb-cf811d7e38ff)

**Comment by liamdebeasi** [comment] 2023-05-15 14:11
Actually, this is probably something we could handle automatically inside of Ionic. I'll see if I can apply a fix for this.

**Comment by liamdebeasi** [comment] 2023-05-15 14:50
Here is a dev build with a proposed fix if you are interested in testing:

```
npm install @ionic/vue@7.0.7-dev.11684161625.1b7bb55d @ionic/vue-router@7.0.7-dev.11684161625.1b7bb55d
```

**Comment by typefox09** [comment] 2023-05-16 01:10
In my case the Ion-modal was in it's own component. I can confirm that wrapping the content in an ion-page did fix the issue though. The docs should be updated.

Example:
<ion-modal>
  <ion-page>
       <ion-header>
        <ion-content>
   </ion-page>
</ion-modal>

**Closed** 2023-05-24 13:54 UTC
Labels: package: vue, type: bug
