### ISSUE TITLE
bug: Fresh Vue project from blank template won't build in Xcode

### ISSUE THREAD

**Issue by vanekj** [ionic-team/ionic-framework#22387] opened 2020-10-24 16:45 UTC
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
Running the project in Xcode 11.5 results in build errors.
<img width="1512" alt="xcode-capacitor-cordova-error" src="https://user-images.githubusercontent.com/18655248/97087227-d439e900-1628-11eb-945a-03fc7c98595c.png">

**Expected behavior:**
It should build and run in iOS simulator with success.

**Steps to reproduce:**
1. `xcode-select --install`
1. `brew install cocoapods`
1. `npm install -g @ionic/cli@latest`
1. `ionic start ionic-test-app blank --type vue`
1. `cd ionic-test-app`
1. `ionic integrations enable capacitor`
1. `ionic build`
1. `ionic cap add ios`
1. `ionic cap open ios`
1. Pressing the "Play" button in Xcode results in the error from the screenshot

**Other information:**
I consulted the problem on [Ionic Framework forum](https://forum.ionicframework.com/t/xcode-build-failed-ionic-vue-capacitor/198427). When testing [this project](https://github.com/dlodeprojuicer/ionic-vue-mobile-template-04), it was built with no issues and iOS simulator started.

**Ionic info:**
```
Ionic:

   Ionic CLI       : 6.12.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 5.4.1

Capacitor:

   Capacitor CLI   : 2.4.2
   @capacitor/core : 2.4.2

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.18.3 (/usr/local/bin/node)
   npm    : 6.14.8
   OS     : macOS Catalina
```

**Comment by liamdebeasi** [comment] 2020-10-26 17:10
Thanks for the issue. Have you tried any of the troubleshooting steps in https://capacitorjs.com/docs/v3/ios/troubleshooting?

**Comment by vanekj** [comment] 2020-10-26 17:46
@liamdebeasi, thanks for the reply, I tried [Clean/Rebuild](https://capacitorjs.com/docs/v3/ios/troubleshooting#cleanrebuild) also with [Removing Derived Data](https://capacitorjs.com/docs/v3/ios/troubleshooting#removing-derived-data), but it's still failing (29 issues from CapacitorCordova)

**Comment by liamdebeasi** [comment] 2020-10-26 18:20
Can you try running `npx cap sync` then try running the app again?

**Comment by vanekj** [comment] 2020-10-27 13:29
Unfortunately, the build still fails with the attached errors below.
[xcode_build-errors.log](https://github.com/ionic-team/ionic-framework/files/5445594/xcode_build-errors.log)

**Comment by liamdebeasi** [comment] 2020-10-27 13:34
Thanks! Sorry for the frustration. I am working with the Capacitor team on trying to figure out what's going on here. Two things to try:

1. Can you post your CocoaPods version? You can find it either with `pod --version` or `gem which cocoapods`.
2. Can you go into the `ios` directory and run `pod deintegrate` and `pod install`?

**Comment by vanekj** [comment] 2020-10-28 08:44
No problem, I appreciate your help!

1. `1.10.0` (Installed using Homebrew as Ionic still returned that it's not installed when calling `sudo gem install cocoapods`)
1. It did not help, still the same build errors in Xcode

**Comment by liamdebeasi** [comment] 2020-10-28 14:47
> (Installed using Homebrew as Ionic still returned that it's not installed when installed with sudo gem install cocoapods)

So our current thought is that something is wrong with your CocoaPods installation. The CLI just does `which pod` to check if CocoaPods is installed. If it can't find it when installed via `gem`, then it sounds like something with your environment is not configured correctly.

Some things to try:

1. Uninstall CocoaPods from both Homebrew and gem.
2. Install Cocoapods only via gem. This seems to be the recommended way of installing according to https://cocoapods.org/.
3. Run `which pod`. If you get an error, then something is wrong with your environment and you'll need to correct it first.
4. Once `which pod` is returning the correct cocoapods path (something like `/usr/local/bin/pod`), do `npx cap sync` in your project which will re-install the pods for your Capacitor app. From here you can try running the app again (maybe restart Xcode first to be safe).

Let me know if `which pod` gives you an error or not.

**Comment by vanekj** [comment] 2020-10-28 19:56
So, I made several combinations and this is what **solved the build issue** for me 🥳 

1. `brew remove cocoapods`
1. `sudo gem uninstall cocoapods`

These two calls resolved that `which pod` returned that the `pod` command was not found.
I found that I also have `ruby` installed from Homebrew and so `sudo gem install cocoapods` was still returning that `pod` command was not found. So I had to install cocoapods from Homebrew again.

1. `brew install cocoapods --build-from-source`
1. `brew link --overwrite cocoapods` - I didn't called this command before
1. `brew upgrade cocoapods` - To be sure I have the actual version installed
1. `which pod` returns `/usr/local/bin/pod` which is correct

Now for the Ionic part of the issue.

1. `npx cap sync` - This reinstalled the pods as you (@liamdebeasi) mentioned with success
1. `npx cap open ios` - When using this command, it opens Xcode, where the build failed again, so I tried another command
1. `ionic cap open ios` - This also opens Xcode and the builds failed

In Xcode's left panel, where the opened projects are, I clicked on **App** item and **Show in Finder** which marked **App.xcodeproj** in the `ios/App` directory as the currently opened. So I closed Xcode and double-clicked the **App.xcworkspace**, which opened Xcode, but now the build succeeded and iPhone simulator runs the app with no more issues. Now, even when using `npx cap open ios` it builds and runs with no issues. There are still some warnings in the Xcode, but it runs, so what 🤷🏻‍♂️ . Also `ionic capacitor run ios --livereload --external` runs perfectly and my changes are hot-reloaded in simulator.

I am not exactly sure, what was the issue, if the Homebrew installing process or opening the different Xcode file, but it runs.

Thank you very much @liamdebeasi for your help.

**Comment by liamdebeasi** [comment] 2020-10-28 21:07
Glad it's working now! I was actually able to reproduce the issue a moment ago with the `.xcodeproj` and opening the `.xcworkspace` file fixed it for me.

I am going to close the issue, but I will check with the Capacitor team to see why that might be happening.

**Closed by liamdebeasi** 2020-10-28 21:07 UTC
Labels: triage
