### ISSUE TITLE
bug: v6 beta not working with react and vite

### ISSUE THREAD

**Issue by aaronksaunders** [ionic-team/ionic-framework#23671] opened 2021-07-22 01:51 UTC
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

_Vite, Rollup, and ESBuild — oh my!
As an added bonus, Framework v6 will be usable with tooling such as Vite, Rollup, and ESBuild, giving you even more options for building apps. This is something that developers have been asking us about for a while, so we are excited to roll this support out._

Tried following the project upgrade directions for using with react. Started a new project using vite. Added `IonApp` to project and the application crashed.

Code does not run, error message attached below

### Expected Behavior

code to run without error

### Steps to Reproduce

```
import React from "react";
import "./App.css";
import { IonApp } from "@ionic/react";

function App() {

  return (
    <IonApp>
      <p>Hello Vite + React!</p>
    </IonApp>
  );
}

export default App;
```

### Additional Information

<img width="998" alt="Screen Shot 2021-07-21 at 9 44 35 PM" src="https://user-images.githubusercontent.com/524953/126579996-1ed87536-d4d0-47b8-b49a-887a637ccd5b.png">

**Comment by liamdebeasi** [comment] 2021-07-22 12:57
Thanks for the issue! The new Vite/ESBuild/Rollup support is dependent on the Custom Elements build (mentioned above in the paragraph you quoted from the blog). As of now the Custom Elements build is only in Ionic Vue, so Vite will not work with Ionic React at the moment.

I am going to close this issue since things are working as intended, but we are tracking Custom Elements support internally and will be sure to update the community when support has landed in Ionic React.

**Closed by liamdebeasi** 2021-07-22 12:57 UTC
Labels: triage

**Comment by aaronksaunders** [comment] 2021-07-22 12:59
thanks
