### ISSUE TITLE
bug: NavController pop method doesn't work after navigating from undefined stack to named stack

### ISSUE THREAD

**Issue by dzNavitski** [ionic-team/ionic-framework#22580] opened 2020-11-26 09:20 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
NavController pop method stop working after navigating from undefined stack to named stack. Looks like the topOulet property is wrong. From my investigation problem occurs from race condition in stack-controller.ts **transition** method when switching between pages.

**Expected behavior:**
NavController pop method works after navigating from undefined stack to named stack

**Steps to reproduce:**
1. open tab 1
2. tap "Go to about" button
3. tap "Open about in root"
4. tap "Back" button (in header or content)
5. tap "Back" button in content
6. observe that nothing happened

**Related code:**
https://github.com/dzNavitski/ionic-top-outlet-issue

**Ionic info:**
Invoke command `npm start` to run the app

**Comment by NicolasVargas** [comment] 2020-11-29 17:18
Hi, I'm experiencing the same issue :
A group of tabs and another group of "standalone" routes, linked to the main router outlet.
Once i navigate from a tab to one of my standalone routes, and then I use the pop method to go back, my history is totally messed up.
Maybe `back()` could do a better job outside of my tabs outlets but i'd like to understand why it is ot working correclty with `pop()`

**Comment by liamdebeasi** [comment] 2020-11-30 15:53
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/18593.

**Closed by liamdebeasi** 2020-11-30 15:53 UTC
Labels: triage
