### ISSUE TITLE
bug: When having autofocus on an input in IonModal, it has a weird animation on iOS device

### ISSUE THREAD

**Issue by pitis** [ionic-team/ionic-framework#21357] opened 2020-05-23 07:26 UTC
# Bug Report

**Ionic version:**
5.1.1, but also happened on 5.0.7

**Current behavior:**
When I open an IonModal, it has a weird animation when I have an IonInput with autofocus true in it. This only happens on iOS simulator or device. Not in android or web version.

**Expected behavior:**
The transition is the same like on web and android.

**Steps to reproduce:**
Create an IonModal with an IonInput in it that that autofocus={true}
**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.9.2 (C:\Users\Pitis\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/react 5.1.1

Capacitor:

   Capacitor CLI   : 2.0.1
   @capacitor/core : 2.0.1

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v13.8.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.5
   OS     : Windows 10
```

**Comment by ernofi** [comment] 2020-05-28 13:40
I'm using ionic version 5.1.1.

Here's a video to see how it works on my iPhone 7 Plus: [https://streamable.com/vi6qe3](https://streamable.com/vi6qe3)

You can reproduce the bug with this code:

Page 1
```
<ion-content>
  <ion-button expand="full" routerLink="/page2">Autofocus=true</ion-button>
  <ion-button expand="full" routerLink="/page3">Autofocus=false</ion-button>
</ion-content>
```

Page 2 has ion-input with autofocus set true
```
<ion-content>
  <ion-item>
    <ion-input autofocus="true"></ion-input>
  </ion-item>
</ion-content>
```

Page 3 has ion-input with autofocus set false
```
<ion-content>
  <ion-item>
    <ion-input autofocus="false"></ion-input>
  </ion-item>
</ion-content>
```

**Comment by liamdebeasi** [comment] 2020-06-04 15:30
@ernofi Can you provide this as a full repo I can use to reproduce the issue?

**Comment by ernofi** [comment] 2020-06-05 08:44
@liamdebeasi  [https://github.com/ernofi/ionic-ios-autofocus-transition-bug](Here)

**Comment by liamdebeasi** [comment] 2020-06-15 13:49
Thanks. I was able to reproduce this behavior, but I am not sure what is causing it. I need to investigate this more.

**Comment by liamdebeasi** [comment] 2020-12-03 20:51
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/18257.

**Closed by liamdebeasi** 2020-12-03 20:51 UTC
Labels: triage
