### ISSUE TITLE
bug: Cannot hide scroll bar

### ISSUE THREAD

**Issue by HyperLife1119** [ionic-team/ionic-framework#22388] opened 2020-10-25 06:59 UTC
# Bug Report

**Ionic version:**

**5.x**

**Current behavior:**

Add this style to the `global.scss` file.
```
*::-webkit-scrollbar {
    display: none !important;
}
```
This style cannot take effect in the ionic project

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
*::-webkit-scrollbar {
    display: none !important;
}`
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment] 2020-10-26 13:27
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/18811#issuecomment-512861510.

**Closed by liamdebeasi** 2020-10-26 13:27 UTC
Labels: triage
