### ISSUE TITLE
bug: navigating to the same url twice causes the pages in between to get lost

### ISSUE THREAD

**Issue by Deitsch** [ionic-team/ionic-framework#23119] opened 2021-03-30 11:32 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

When navigating like seen in the picture the `<ion-back-button>` does not navigate back as expected. Actually & Expected are how it appears to be, the red arrow show what i think actually happens. 
<img width="439" alt="Bildschirmfoto 2021-03-30 um 11 02 03" src="https://user-images.githubusercontent.com/44440587/112978371-8edd9280-9157-11eb-890b-7fc4e0afa6d7.png">

**Expected behavior:**
As seen in the picture it would be expected that the `<ion-back-button>` navigates from `Page 1` to `Page 2`

**Steps to reproduce:**

0. open start page `localhost:XXXX/start`
1. navigate to buildings
2. navigate to procedures
3. navigate to buildings
4. press back button (`<-`)

**Related code:**

https://github.com/Deitsch/ionic-navigation-bug

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.13.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.6.3
   @angular-devkit/build-angular : 0.1102.6
   @angular-devkit/schematics    : 11.2.6
   @angular/cli                  : 11.2.6
   @ionic/angular-toolkit        : 3.1.1

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v15.4.0 (/usr/local/Cellar/node/15.4.0/bin/node)
   npm    : 7.7.6
   OS     : macOS Big Sur
```

**Comment by liamdebeasi** [comment] 2021-03-30 12:58
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. Going from `/buildings` to `/procedures` back to `/buildings` will cause Ionic Angular to reuse the first instance of `/buildings`. We should probably be using the back animation here, but really what is happening is the following:

1. Start on `/start`.
2. Navigate to `/buildings`.
3. Navigate to `/procedures`.
4. Pop off the stack to return to `/buildings`.
5. Press the back button to return to `/start`.

If you are looking to have Ionic Angular navigate to a new instance of `/buildings`, then you should be using parameterized URLs (I.e. `/buildings/1` and `/buildings/2`). Thanks!

**Closed by liamdebeasi** 2021-03-30 12:58 UTC
Labels: triage

**Comment by Deitsch** [comment] 2021-03-30 13:10
If i understand correctly i should parameterize the url although it is exactly the same page to achieve what i need? Is this an Angular Bug maybe? Because it does not make sense that the first instance of `/buildings` is used rather than the latest?

**Comment by Deitsch** [comment] 2021-03-30 13:37
Thanks for clarification, it does make sense from a developers point of view, but i still think user experience wise it's an issue because it's simply not what i'd expect to happen on `go back`.

As a result navigation feels inconsistent
`/start -> /buildings/1 --> /procedures/1 --> /buildings/1`: back will return to `/start`
`/start -> /buildings/1 --> /procedures/1 --> /buildings/2`: back will return to `/procedures/1`

**Comment by liamdebeasi** [comment] 2021-03-30 13:50
So part of the issue here is in how the application is being implemented. It is typically expected that if you are using parameterized URLs, then you are showing slightly different content on each instance of the page. For example `/buildings/1` shows content pertaining to Building 1 and `/buildings/2` shows content pertaining to Building 2. If you are showing different content, then there is a visual indication that these are distinct instances of the page.

On the other hand, if you are showing the same content across both pages, then users have no evidence to conclude that these are separate pages. As another example, pretend you have a form on `/buildings/1` that users partially filled out before going to `/procedures/1`. Navigating them to a new instance of `/buildings/1` might cause a user to think their form data was lost because in their mind, they are being taken to the same page they were on before.

Placing this aside, it is not possible for us to know when to reuse or not reuse a component instance given two instances of the same URL because Ionic Angular has no idea what is being rendered in each page. If we were to somehow do this, we would likely get significant memory leaks.

**Comment by Deitsch** [comment] 2021-03-30 14:00
Again, it totally makes sense what you tell me developer wise, but it's just visually confusing. 
I think my main issue here is that when the back happens here at the third arrow i visually receive a forward animation when in fact a back happens.
`/start --> /buildings/1 --> /procedures/1 --> /buildings/1`

**Comment by liamdebeasi** [comment] 2021-03-30 14:02
Yeah the forward animation is pretty confusing. Let me take a look to see if this is something we can detect in Ionic Angular.

**Comment by Deitsch** [comment] 2021-03-31 07:31
Thinking over what you wrote again`otherwise users could infinitely navigate between the Buildings page and the Procedures page` is actually my desired behavior :/

**Comment by liamdebeasi** [comment] 2021-03-31 14:17
So I chatted with the team regarding this and it sounds like some of the behavior you want is something we used to do in Ionic v3, but stopped doing due to the issues I mentioned previously.

To summarize the issues we discussed:

1. Navigating from `/buildings` to `/procedures` back to `/buildings` reuses the previous `/buildings` instance. 

While I think being able to navigate infinitely to new instances of the same page is a confusing user experience, we likely could not safely implement this anyways without opening the door to significant memory leaks. There are likely going to be use cases where this behavior causes issues in applications, so we feel that it is better to stay away from this type of navigation pattern especially where it provides for a confusing user experience.

2. Reusing the previous page instance does not use the "back" animation.

According to the team this is similar to something we did during Ionic v3 where we would "guess" the animation users want to use. We were unable to correctly guess the animation 100% of the time which led to users being frustrated with this functionality. For example, it's easy enough to use the "back" animation when doing `/pageA --> /pageB --> /pageA`, but once you get more complex navigation scenarios such as `/pageA --> /pageB --> /pageC --> /pageA` the "expected behavior" can change based upon the application it is happening in. Questions surrounding what happens to `/pageB` and what animation should be used do not have straightforward answers here.

To account for this, we recommend that developers set the animation themselves by using `routerDirection="back"` when navigating.

I can certainly open up a feature request to try and tackle issue 2, but given the the issues we saw in Ionic v3, I am not sure if this is something the team would want to take on again.
