### ISSUE TITLE
bug: IonRouterOutlet fails to work when dynamically adding Routes after the first render

### ISSUE THREAD

**Issue by pjschrock** [ionic-team/ionic-framework#21329] opened 2020-05-18 16:49 UTC
# Bug Report

**Ionic version:**
5.0.7

**Current behavior:**
When the app first loads and <IonRouterOutlet> is rendered all the routes will not re-render even when they are changed. For instance, several routes/redirects get changed or added after a user logs in, but the IonRouterOutlet will not update routes.  I can see the new routes updated using the inspector, but IonRouterOutlet seems to ignore them as if it has cached them someplace and then ignores any updates.

**Expected behavior:**
When routes are added or removed from IonRouterOutlet at run time, the new routes should become available and the removed ones should no longer exist.

**Steps to reproduce:**
Dynamically generate a series of routes from an array of route data. Run an event like a redux hook update that will cause the App component to re-render and in this process make the routes change. The bug is that the application ignores the route changes.

**Related code:**

--Main App--
```
const App: React.FC = () => {
  const loggedIn = useSelector(SelectLoginStatus);
  const currentUser = useSelector(SelectCurrentUser);

  return (
    <IonApp>
      {console.log(AppRoutesNoAuthRoutes(loggedIn, currentUser))}}
      <IonReactRouter>
        <IonSplitPane contentId="main">
          <Menu />
         <IonRouterOutlet key="AppIonRouterOutlet" id="main">
            {AppRoutes(loggedIn, currentUser)}
          </IonRouterOutlet>
        </IonSplitPane>
      </IonReactRouter>
    </IonApp>
  );
};

export default App;
```

--Route Rendering function--
```
export const AppRoutes = (loggedIn:boolean, currentUser:IUser) => {
    routeInfoArray:IRouteInfo[] = myInfoAray;
    keyPrefix:string = "uniqueKeyPrefix";

    return routeInfoArray.map((route, i) => {
        if(route.roles.filter(role => role === UserRoles.Unregistered).length) {
            return <Route key={`${keyPrefix}-${i}`} path={route.path} component={route.component} exact />
        } else {
            if(loggedIn) {
                if(route.roles.filter(role => role === currentUser.Role || role === UserRoles.AllRegistered).length) {
                    return <Route key={`${keyPrefix}-${i}`} path={route.path} component={route.component} exact />
                } else {
                return <Redirect key={`${keyPrefix}-${i}`} from={route.path} to={AccountRouteInfo[AccountRouteKeys.Unauthorized].path} />
                }
            } else {
                return <Redirect key={`${keyPrefix}-${i}`} from={route.path} to={AccountRouteInfo[AccountRouteKeys.Login].path} />
            }
        }        
    });
}
```

--Notes--
I have noticed that if I nest my routes in a component and then update like this IonRouteOutlet will allow them to be updated.  However, nesting routes in another component causes other problems to happen because this does not appear to be allowed with IonRouteOutlet. I think I need IonRouteOutlet to make the IonSplitPane to work with multiple pages.

**Comment by pjschrock** [comment] 2020-05-18 22:38
Here is the  reproduction code:
https://github.com/pjschrock/ion-router-bug

**Steps to reproduce:**
Run the app. (it dynamically generates a route and adds it to the IonRouterOulet).
Click the button to dynamically add another route.
look in the inspector > components > IonRouterOutlet and you will see the array containing the routes is getting more routes in it.
Click the link to navigate to the newly generated route.
The Route fails and falls back to the catch all route.

**Expected:**
the link should take you to the new route after it was added.

**Comment by pjschrock** [comment] 2020-05-26 16:12
can we at least remove the "needs reproduction" tag from this since I have provided reproduction code...

**Comment by liamdebeasi** [comment] 2020-05-26 16:16
Hey there,

Did you upload your entire code reproduction? I cloned the repo you sent over, but it looks like a blank Ionic starter application. I don't see any button to add a new route.

**Comment by pjschrock** [comment] 2020-05-27 15:34
My bad, I guess I forgot to commit before I pushed the repo, I just pushed the updates and you should see all the reproduction code now.

**Comment by liamdebeasi** [comment] 2020-05-28 20:59
Thanks. I was able to reproduce this behavior. I can confirm that routes currently cannot be added dynamically. We are working on some updates to routing in Ionic React that should fix this issue.

**Comment by elylucas** [comment] 2020-06-22 22:42
Hi @pjschrock,

We have a dev release that should fix this issue. If you can, could you try to install it and let us know if it fixes the issue and if you run into any others? To install it run:

`npm i @ionic/react@5.3.0-dev.202006222125.df37029 @ionic/react-router@5.3.0-dev.202006222125.df37029`

If all goes good this should be available in the next Ionic release.

Thanks!

**Comment by mirco312312** [comment] 2020-06-26 05:11
Hi @elylucas your fix is working for me. 

Similar scenario:
- Added routes on stat up (not logged in)
- Dynamically added more routes after login

**Comment by tarjei** [comment] 2021-05-27 07:34
@pjschrock I guess this issue should be closed now?

**Comment by pjschrock** [comment] 2021-05-27 14:21
yes, the issue was resolved with an update last year.

-- Peter Schrock



Owner of Finest Studios
www.FinestStudios.net
(314) 884-0326

**Comment by liamdebeasi** [comment] 2021-06-01 12:21
Thanks! It sounds like the original issue is resolved, so I am going to close this out. If you run into anything else, please feel free to open a new issue.

**Closed by liamdebeasi** 2021-06-01 12:21 UTC
Labels: package: react, type: bug
