### ISSUE TITLE
bug: Vue reactivity not working within an IonModal component

### ISSUE THREAD

**Issue by wsamoht** [ionic-team/ionic-framework#24321] opened 2021-12-06 16:49 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

I am encountering an issue where reactivity is not working within a custom Vue component that wraps an `IonModal`. Any content within the IonModal isn't reactive. An example is changing a boolean variable to show and hide content within the modal. When changing the boolean value, it doesn’t cause a reactive update to the contents of the modal even though you can see the variable changing in a `console.log`.

I've tried both using Vue's Option API and Composition API.

Below is an example component using the Options API. When changing `showText`, the content doesn't swap in the template between "Show this text if showText = true" and "Show this text if showText = false".

```javascript
<template>
    <IonModal :is-open="isOpen" @did-dismiss="isOpen = false">
        <div class="ion-padding">
            <p class="ion-text-center">showText: {{ showText }}</p>
            <IonButton expand="block" @click="toggleText">
                Toggle showText
            </IonButton>
            <div v-if="showText" class="ion-margin-top ion-text-center">
                Show this text if showText = true
            </div>
            <div v-else class="ion-margin-top ion-text-center">
                Show this text if showText = false
            </div>
        </div>
    </IonModal>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import { IonButton, IonModal } from "@ionic/vue";
export default defineComponent({
    name: "OptionsModal",
    components: {
        IonButton,
        IonModal,
    },
    data() {
        return {
            isOpen: false,
            showText: false,
        };
    },
    mounted() {
        this.isOpen = true;
    },
    methods: {
        toggleText(): void {
            this.showText = !this.showText;
            console.log(`showText = ${this.showText}`);
        },
    },
});
</script>
```

### Expected Behavior

I would expect when changing a reactive variable it would update the template. In the example above, when changing `showText`, it would update the template with the correct text based on the `v-if` and `v-else`.

### Steps to Reproduce

1. Download the [test repo](https://github.com/wsamoht/ionic-modal-reactivity) and run `ionic serve`
2. The default tab is the Options API. Click "Toggle showText". You'll see that the text in the modal doesn't update but in the console you can see the bool is updating switching between `true` and `false`.
3. Test the second tab with the Composition API that has the same issue

The Without Modal tab shows the same code that does work (is reactive) without a modal.

The fourth tab is similar code using the `ModalController`. This appears to be reactive; however, it is not really a feasible option as there is not way to pass data from the component `ModalControllerComponent` back to the `ModalController` component.

### Code Reproduction URL

https://github.com/wsamoht/ionic-modal-reactivity

### Ionic Info

```
Ionic:

   Ionic CLI       : 6.18.1 (/home/twestrick/.npm-global/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 5.9.1

Capacitor:

   Capacitor CLI      : 3.3.2
   @capacitor/android : not installed
   @capacitor/core    : 3.3.2
   @capacitor/ios     : not installed

Utility:

   cordova-res (update available: 0.15.4) : 0.15.2
   native-run                             : 1.5.0

System:

   NodeJS : v14.18.2 (/usr/bin/node)
   npm    : 6.14.15
   OS     : Linux 5.4
```

### Additional Information

Additional discussion can be found in the Ionic Forum post [here](https://forum.ionicframework.com/t/reactivity-not-working-within-an-ionmodal-component/217985/1).

I also tried using Vuex (Vue's store/state management) instead of the local `showText` variable but that also didn't work. It appears nothing is reactive within an IonModal.

**Comment by liamdebeasi** [comment] 2021-12-08 21:04
Thanks for the issue. Can you give this a shot in Ionic 6? We had a few changes to how `ion-modal` is created in Vue applications that may solve this:

```
npm install @ionic/vue@latest @ionic/vue-router@latest
```

**Comment by wsamoht** [comment] 2021-12-09 14:47
I updated to Ionic v6 and it is working as expected. My v6 test code branch is here - https://github.com/wsamoht/ionic-modal-reactivity/tree/ionic-v6.

Your call if you want to fix it in v5. I have a workaround at the moment using multiple modals. I'll also be updating to v6 hopefully in the next couple of weeks.

**Comment by liamdebeasi** [comment] 2021-12-09 16:52
Glad the issue is fixed there. With Ionic 6 we added a more future proof version of `ion-modal` (I.e. we render the actual `ion-modal` rather than a `div` with a controller dynamically adding the modal later). Unfortunately this implementation required a breaking change, so we cannot backport this change to Ionic 5.

I am going to close this since the original issue is resolved in Ionic 6, but definitely let me know if you run into any other issues with reactivity in Vue. Thank you!

**Closed by liamdebeasi** 2021-12-09 16:52 UTC
Labels: triage
