### ISSUE TITLE
bug: [React] Failed to execute 'insertBefore' on 'Node' on Ion Slides

### ISSUE THREAD

**Issue by DexterHill0** [ionic-team/ionic-framework#22985] opened 2021-02-28 15:05 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

The bug seems to be caused if an `IonSlide` is added or shown only when there is another slide "ahead" of it. For example, this would cause an error:
```
{
    showSlide ? <IonSlide>new</IonSlide> : <></>
}
<IonSlide>...</IonSlide>
```
whereas this would __not__ cause an error:
```
<IonSlide>...</IonSlide>
{
    showSlide ? <IonSlide>new<IonSlide> : <></>
}
```
The error I receive is:
```
react-dom.development.js:11340: Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
```
**Expected behavior:**

It should add or show the slide without an error.

**Steps to reproduce:**

Create a blank React project
`ionic start bug blank --type=react`

Paste into `Home.tsx`:
```
const Home: React.FC = () => {

	const [visible, setVisible] = useState({
		"middle": false,
		"end": false,
	});

	const addOrRemoveSlide = (id: string, action: "add" | "remove") => {
		if (action === "add") {
			setVisible({ ...visible, [id]: true });
		} else if (action === "remove") {
			setVisible({ ...visible, [id]: false });
		}
	};

	return (
		<IonContent >
			<IonSlides>
				<IonSlide>
					I am visible by default
				</IonSlide>
				{
					visible.middle ?
						<IonSlide>
							I am not visible by default (no1)
						</IonSlide>
						: <></>
				}
				<IonSlide>
					I am visible by default as well
				</IonSlide>
				{
					visible.end ?
						<IonSlide>
							I am not visible by default (no2)
						</IonSlide>
						: <></>
				}
			</IonSlides>
			Show middle slide<br />
			<IonCheckbox onClick={(e) => addOrRemoveSlide("middle", e.detail ? "add" : "remove")}></IonCheckbox><br />
			Show end slide<br />
			<IonCheckbox onClick={(e) => addOrRemoveSlide("end", e.detail ? "add" : "remove")}></IonCheckbox>
		</IonContent>
	);
};
```
Run `ionic serve`.
Click the "Show end slide" and a new slide will appear without an error. Click "Show middle slide" and it will error.
[CodeSandBox](https://codesandbox.io/s/mystifying-keller-73rpj?file=/src/index.tsx)

**Other information:**

There is already a report on this (issue #18782) but it's been open for over a year and a half and it doesn't seem like much is happening

**Ionic info:**

`ionic info`
```
Ionic:

   Ionic CLI       : 6.12.4 (D:\Dexter\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/react 5.5.4

Capacitor:

   Capacitor CLI   : not installed
   @capacitor/core : 2.4.4

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v14.15.4 (D:\Program Files\nodejs\node.exe)
   npm    : 6.14.10
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment] 2021-03-01 13:42
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/22867.

**Closed by liamdebeasi** 2021-03-01 13:42 UTC
Labels: triage
