### ISSUE TITLE
bug: ion-content is still scrollable while ion-menu is opening.

### ISSUE THREAD

**Issue by BerkeAras** [ionic-team/ionic-framework#21193] opened 2020-05-02 09:37 UTC
# Bug Report

**Ionic version:**

[x] **4.x**
[x] **5.x**

**Current behavior:**

``ion-content`` is still scrollable while ``ion-menu`` is opening. This is happens only with cordova and capacitor, not in the browser.

**Expected behavior:**

``ion-content`` should not be scrollable.

**Steps to reproduce:**

While opening a ``ion-menu``, swipe finger up and down.

**Other information:**

Here you can see it: [https://www.youtube.com/watch?v=K-ImPdKFoiA](https://www.youtube.com/watch?v=K-ImPdKFoiA)

**Comment by lincolnthree** [comment] 2020-05-04 18:01
Confirmed here as well. This happens easily and consistently and results in a *VERY* slow/jittery interaction for the user.

**Comment by BerkeAras** [comment] 2020-07-10 10:33
Are there any updates?

**Comment by lincolnthree** [comment] 2020-08-29 05:41
Still an issue. Seems to have gotten worse specifically in the latest chrome releases. Almost impossible to swipe open any menu without extreme lag / jank. It's almost to the point where I'd consider disabling swipe-to-open because it's just a really bad impression.

Users have been complaining our apps are slow when in reality it's just the menu opening :/

Not sure how to proceed with this as I believe it's a result of the event being captured by multiple elements.

**Comment by lincolnthree** [comment] 2020-08-29 05:44
I stumbled on this, haven't had a chance to dig in too deep yet, but could be useful for finding a solution/workaround?

https://github.com/pawelgrzybek/siema/issues/37

**Comment by lincolnthree** [comment] 2020-08-29 05:54
Possibly related: https://github.com/w3c/pointerevents/issues/303

**Comment by BerkeAras** [comment] 2020-08-29 06:25
Eventually it is possible to disable the scroll feature of IonContent as soon as the menu gets opened.

**Comment by BerkeAras** [comment] 2020-08-29 06:26
I will create create a demo of my solution ASAP.

**Comment by lincolnthree** [comment] 2020-08-29 06:28
I actually think I just came up with a solution as well! Does your look something like this?

```
// mainElmt is the <main> element from IonContent: <main class="inner-scroll scroll-x scroll-y" part="scroll"><slot></slot></main>

  lockContent(lock: boolean) {
    if (lock) {
      this._dom.write(() => {
        this._rnd.setStyle(this.mainElmt, 'pointer-events', 'none');
        Timeout.fn(() => {
          this._dom.write(() => {
            this._rnd.removeStyle(this.mainElmt, 'pointer-events');
          });
        }, 0);
      });
    }
  }
```

**Comment by BerkeAras** [comment] 2020-08-29 06:29
@lincolnthree That looks very good, I've just started to create something. Are you able to create a PR?

**Comment by lincolnthree** [comment] 2020-08-29 06:31
@BerkeAras I probably can tomorrow. Right now I've done this in a directive that attaches to every [ion-conten] element automatically.

What was your solution?

**Comment by BerkeAras** [comment] 2020-08-29 06:32
I dont have a solution. I just created a new project, but I dont have something yet.

**Comment by lincolnthree** [comment] 2020-08-29 06:36
Ah :) Here's something that might help:

```
@Directive({
  selector: 'ion-content'
})
export class IonContentDirective implements OnInit, OnDestroy, AfterViewInit {

  public static locks: IonContentStyleDirective[] = [];

  private mainElmt: HTMLElement;
  private styled = false;

  constructor(
    private _el: ElementRef,
    private _rnd: Renderer2,
    private _dom: DomController
  ) {
    // Very hacky singleton. Don't look at me like that.
    IonContentStyleDirective.locks.push(this);
  }

  static cancelAllPointerEvents() {
    // Call this from a method attached to (ionWillOpen) from your ion-menus
    for (const c of IonContentStyleDirective.locks) {
      c.cancelPointerEvents();
    }
  }

  cancelPointerEvents() {
    this._dom.write(() => {
      this._rnd.setStyle(this.mainElmt, 'pointer-events', 'none');
      Timeout.fn(() => {
        this._dom.write(() => {
          this._rnd.removeStyle(this.mainElmt, 'pointer-events');
        });
      }, 0);
    });
  }

  ngOnInit() {
  }

  ngOnDestroy() {
    Arrays.removeArrayItem(IonContentStyleDirective.locks, this);
  }

  ngAfterViewInit() {
    if ((this._el.nativeElement as HTMLStencilElement).componentOnReady()) {
      (this._el.nativeElement as HTMLStencilElement).componentOnReady().then(() => {
        this.main = this._el.nativeElement.shadowRoot.querySelector('main');
      });
    } 
  }
}
```

**Comment by lincolnthree** [comment] 2020-08-29 06:37
There may be a simpler way, but that's what I did in ~10 minutes.

**Comment by lincolnthree** [comment] 2020-08-29 06:40
I also noticed it helps to do this when the menu is being closed, as well.

**Comment by BerkeAras** [comment] 2020-08-29 06:42
I've just created a very basic version of @lincolnthree's version. This is useful for especially No-Framework Users.

[https://github.com/BerkeAras/Ionic-5-Menu-Swipe-Issue](https://github.com/BerkeAras/Ionic-5-Menu-Swipe-Issue)

**Comment by lincolnthree** [comment] 2020-08-31 14:14
@liamdebeasi Not sure my tag came through since I edited it in. Just making sure you saw it, since I believe we have a viable workaround/fix for this if you want to incorporate it.

This seems to work best when it is called on menu `ionWillClose` and `ionWillClose`, as menus may also have content inside them that can scroll when closing.

**Comment by lincolnthree** [comment] 2020-09-03 17:54
As an additional aside. It seems to improve/reduce menu jitter if the `ion-content::part(scroll)` has `touch-action: pan-y` set in CSS. I believe this prevents the browser from attempting to attach the touch events to this element in the first place.

**Comment by lincolnthree** [comment] 2020-09-03 18:22
@liamdebeasi Facepalm... 🤦  I think the simplest fix is actually just to apply `touch-action: pan-y` to the main/scroll element in `ion-content`. I haven't tested in "all browsers" yet, but just this CSS change seems to resolve all the background-scrolling and jitter issues on chrome/android/and ios safari.

**Comment by lincolnthree** [comment] 2020-09-03 18:24
That said, I'm going to get back to my "day job" and let the dust settle on this one for a bit.

**Comment by lincolnthree** [comment] 2023-03-14 02:44
@liamdebeasi I will try with version 7 and let you know. Unfortunately I do not have an active build with Ionic 6 anymore :)

**Comment by lincolnthree** [comment] 2023-03-15 20:28
Yes, this is still an issue in version 7:

https://user-images.githubusercontent.com/362329/225434342-c3067cfa-b1a4-4f3e-ac36-828c30654107.mp4

**Comment by lincolnthree** [comment] 2023-03-15 20:28
Uhhh.. here's a link. Not sure what happened to that video: https://photos.app.goo.gl/xubuaC4PkMKf9syX6

**Comment by liamdebeasi** [comment] 2023-03-16 15:40
Here's a dev build with a proposed fix if you are interested in testing:

v6: `6.6.3-dev.11678980356.1ab22fc7`

v7: `7.0.0-dev.11678980795.1e4cbe0d`

**Comment by lincolnthree** [comment] 2023-03-17 20:04
Looks good @liamdebeasi -- And nice fix! Thanks for doing this :)

**Comment by liamdebeasi** [comment] 2023-03-17 20:51
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/26976, and a fix will be available in an upcoming release of Ionic Framework.

**Closed** 2023-03-17 20:51 UTC
Labels: package: core, type: bug
