### ISSUE TITLE
bug: Alignment issues between ion-content, ion-header, and ion-footer.

### ISSUE THREAD

**Issue by rodrigoGA** [ionic-team/ionic-framework#27550] opened 2023-05-24 21:40 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

The problem occurs in the desktop version of Chrome. Ionic adds a scroll bar of approximately 16px in ion-content. This margin is not added in the header or footer, making it impossible to align the content properly.
On mobile devices, this problem does not seem to occur.

Based on what I have seen in other issues, it appears that there is no way to modify the scroll bar in ion-content. Therefore, if there is no global solution to this problem, it should be treated as an issue.

### Expected Behavior

be able to align the elements between title, content and footer.

### Steps to Reproduce

Create a page with the following structure

```
<ion-footer class="ion-no-border ">
    <!-- element whitout padding -->
    <element/>
</ion-footer>
<ion-content [fullscreen]="true">
   <!-- scrollbar cause right padding -->
   <element/>
</ion-content>
<ion-footer class="ion-no-border ">
    <!--element whitout padding -->
    <element/>
</ion-footer>
```

### Code Reproduction URL

https://stackblitz.com/edit/3we1ad-t5janm?file=index.html

### Ionic Info

-

### Additional Information

-

**Comment by liamdebeasi** [comment] 2023-05-25 13:22
Thanks for the report. Do you have a screenshot of the issue? I'm not able to reproduce the behavior on my end.

**Comment by rodrigoGA** [comment] 2023-05-25 15:02
I attached a screenshot of the example (https://stackblitz.com/edit/3we1ad-t5janm?file=index.html).
I am opening it in chrome, linux. In my application the problem is with the footer.
It happens with both (ion-header  and  ion-footer),  ion-content adds a margin right of the scroll bar of 16px
![Captura desde 2023-05-25 11-57-49](https://github.com/ionic-team/ionic-framework/assets/2334523/17dbd6ea-088f-4489-b747-fede48964f0c)

**Comment by liamdebeasi** [comment] 2023-05-25 16:03
Thanks for the clarification. This is the correct behavior as the scrollbar is designed to take up width rather than float over the content, though I can understand why this behavior may not be desirable. You may be able to customize the scrollbar behavior as a system-level preference too. For example, on macOS you can customize the scrollbar to always show, never show, or only show while scrolling. If the scrollbar always shows then it takes up width, but if the scrollbar only shows on scroll then it floats over the content.

**Comment by rodrigoGA** [comment] 2023-05-25 16:52
I saw in another issue that mentioned the scroll bar in ion-content cannot be modified. The solution I found to customize the scroll bar is to remove the scroll in ion-content and handle it externally. 
Are you aware that things may not be aligned with the expected behavior? Applications can look quite unprofessional this way.

**Comment by liamdebeasi** [comment] 2023-05-25 17:05
This behavior is specific to desktop devices and does not impact mobile devices. Ionic Framework is a tool for building mobile apps, so the impact on production applications should be low. I do understand that this is an undesirable behavior when previewing on a desktop device. However the browser is working as intended, so there is nothing for us to fix inside of Ionic. I am going to close this, but let me know if you have any questions.

**Closed by liamdebeasi** 2023-05-25 17:05 UTC
Labels: triage
