### ISSUE TITLE
bug: popover position not correct when using CSS on IonApp on large screen

### ISSUE THREAD

**Issue by hereAlexT** [ionic-team/ionic-framework#28608] opened 2023-11-29 23:35 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

I am building an app that can run on mobile and web. In the web version. I want to limit its width and make it in the centre. here is what I do
```css
.custom-mx-auto {
    margin-left: auto;
    margin-right: auto;
}
.custom-max-w-3xl {
    max-width: 48rem/* 768px */;
}
```

```
 <IonApp className='mx-auto custom-max-w-3xl'>
        <IonReactRouter>
         ....
        </IonReactRouter>
    </IonApp>
```
however, I have an issue is that when the screen width becomes larger, the popover position is not right. This only happens when the screen width becomes large
![aed7900cfda4054d47d77d328e881088228ee854_2_1062x1000](https://github.com/ionic-team/ionic-framework/assets/79433869/2e2bf13a-ecf5-4526-bebd-fc02fbd6c5df)

after investigation, it turns out that margin-left: auto; and margin-right: auto; will influence how popover determines position.

I also tried other solutions:
- Using Reference, side, etc: not working
- Using grid: Cannot obtain the same layout as expected. (when applying a grid with IonSplitPane, when the screen gets smaller, it compresses the content rather than keeps the content's width.

### Expected Behavior

correct position

### Steps to Reproduce

App.tsx
```typescript
const App: React.FC = () => {
  return (
    <IonApp className='custom-mx-auto  custom-max-w-3xl'>
        <IonReactRouter>
          <IonSplitPane contentId="main" className="max-width-screen">
        ...
          </IonSplitPane>
        </IonReactRouter>
    </IonApp>
  );
};

```

App.css
```css
.custom-mx-auto {
    margin-left: auto;
    margin-right: auto;
}

.custom-max-w-3xl {
    max-width: 48rem/* 768px */;
}
```
ListOfCards.tsx
```typescript
<IonList>
          {buttonData.map((button) => (
            <IonItem key={button.id}>
              <div>
                <IonCard>
                  <IonLabel>{button.label}</IonLabel>
                  <IonButton id={button.id}>Open Popover</IonButton>

                  <IonPopover trigger={button.id} dismissOnSelect={true}>
                    <IonContent>
                      <IonList>
                        <IonItem button={true} detail={false}>
                          Option 1
                        </IonItem>
                        <IonItem button={true} detail={false}>
                          Option 2
                        </IonItem>
                      </IonList>
                    </IonContent>
                  </IonPopover>


                </IonCard>
              </div>
            </IonItem>
          ))}
        </IonList>

```

### Ionic Info

https://github.com/hereAlexT/ionic-playground/tree/tailwindcss
https://codesandbox.io/p/github/hereAlexT/ionic-playground/master?workspaceId=4d603c45-6c62-4708-979a-b3273b79d6b2&file=%2F.browserslistrc%3A6%2C9

**Comment by liamdebeasi** [comment] 2023-11-30 14:28
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/28012. Ionic is working as intended here. See https://github.com/ionic-team/ionic-framework/issues/28012#issuecomment-1701167120 for more information.

**Closed by liamdebeasi** 2023-11-30 14:28 UTC
Labels: triage
