### ISSUE TITLE
bug: routing breaks after specific sequence of navigations and clicking on ion-back-button

### ISSUE THREAD

**Issue by luxterful** [ionic-team/ionic-framework#23873] opened 2021-09-03 09:27 UTC
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

After following a specific order of navigation steps the ion-back-button changes the path but the back animation does not happen and the view stays the same.

### Expected Behavior

The ion-back-button should trigger the animation and change the view

### Steps to Reproduce

Create a blank ionic vue project and create 3 views.

Add those Views to the router and redirect root to **view 2**

The views have buttons to go to the next view
View 1 -> View 2 -> View 3

The views also have an ion-back-button.

The App starts on view 2

1. go to view 3
2. go back
3. go back
4. go to view 2
5. go to view 3
6. go back
7. go back 

Now the URL shows the path to view 1 but the last animation did not happen and we are still on view 2

![ezgif com-gif-maker](https://user-images.githubusercontent.com/26602700/131980272-58dbfdd7-61c5-43ae-97a7-15fd9ebbe9ee.gif)

### Code Reproduction URL

https://github.com/luxterful/ionic-back-routing-issue

### Ionic Info

Ionic:

   Ionic CLI       : 6.16.3 (/home/lukas/.nvm/versions/node/v14.16.1/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 5.7.0

Capacitor:

   Capacitor CLI      : 3.2.2
   @capacitor/android : not installed
   @capacitor/core    : 3.2.2
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.3
   native-run  : 1.4.1

System:

   NodeJS : v14.16.1 (/home/lukas/.nvm/versions/node/v14.16.1/bin/node)
   npm    : 7.11.2
   OS     : Linux 5.8

**Comment by saragonclapps** [comment] 2021-10-15 17:06
I have the same issue and try many ways to force update but doesn't execute, the event router end trigger without  any error.

**Comment by tigohenryschultz** [comment] 2021-11-03 23:32
I'm running into the issue, quite a big bug in my opinion. I can't seem to figure out what causes it/reliably reproduce it.

**Comment by obnijnil** [comment] 2021-11-13 08:58
Having the same issue, and it's happening occasionally, including not going back when clicking the `ion-back-button` and not going forward when calling Vue router's `router.replace()`.
Have to kill to app or reload the url in the browser to make it navigate properly.

I'm using @ionic/vue 5.8.5, vue 3.2.21 and vue-router 4.0.12.

**Comment by scottix** [comment] 2021-11-18 21:23
We are on 5.9.1 and running into an issue that sounds very similar to this, that is getting stuck on a page randomly when navigating in the app.

It is causing a blocker in our deployment, any idea of a fix?

**Comment by RobinHavre** [comment] 2021-11-25 16:57
We are experiencing the same issue, and for us it's been a pain through all of 5.x and now also on all the RC's for Ionic 6

**Comment by RobinHavre** [comment] 2021-11-25 21:51
As said this bug (or something very similar) has been a pain for us both in v5.x and in v6 RC 0 through 3.

The most important observation is that this bug is only produced when we are navigating using ``ion-back-button`` or using ``router-link`` together with ``router-direction="root"``. 

We have found two workarounds, both of which prevents the bug from happening, but each having their own caveats.

**1. Override the default ``ion-back-button``-behavior.**  
This resolves the ``ion-back-button`` from triggering the bug (but does nothing for ``router-link``).
Example: 
```html
<ion-back-button :default-href="defaultHref" @click.prevent="navigateBack()"></ion-back-button>
```
```js
function navigateBack() {
  router.go(-1);
}
```

**2. Use MemoryHistory instead of WebHistory**  
This seems to resolve both bugs with the navigation breaking, but we would really like to keep using WebHistory.
```js
const router = createRouter({
  // history: createWebHistory(process.env.BASE_URL),
  history: createMemoryHistory(process.env.BASE_URL),
  routes
})
```

These are hacks we are using temporarily, while waiting for the issue to be resolved.

**Comment by maelp** [comment] 2021-12-24 11:58
I have the same issue with VueJS, it seems that `createMemoryHistory` solves it, but then the back button in the browser no longer works, and `createWebHashHistory` does not seem to fix the bug

**Comment by maelp** [comment] 2021-12-24 14:37
As a reference I rewrote my VueJS app to use a single ion-router-outlet, and still this happens. There is sometimes a bug with a missing element (undefined) that Ionic tries to set `classList` to, and then the router stops working

![image](https://user-images.githubusercontent.com/15458/147359612-7a3c35bb-a3e8-47d2-a964-2071cd15e04c.png)

**Comment by tigohenryschultz** [comment] 2021-12-24 17:13
> As a reference I rewrote my VueJS app to use a single ion-router-outlet, and still this happens. There is sometimes a bug with a missing element (undefined) that Ionic tries to set `classList` to, and then the router stops working (leavingEl is because leavingViewItem.ionPageElement is undefined)
> 
> ![image](https://user-images.githubusercontent.com/15458/147359646-2b3dd067-baee-4c26-9a2b-4250c7dce271.png)

This seems like something I fixed in this pull request: https://github.com/ionic-team/ionic-framework/pull/24433
The tabs using another ion-router-outlet seems funky but I was able to have them play nicely.

**Comment by maelp** [comment] 2021-12-25 10:54
I can try with this PR, is it pushed on ionic-6 or can I also use this PR in ionic-5 ?

**Comment by maelp** [comment] 2021-12-25 14:51
@tigohenryschultz how would I go about trying this PR? from my package.json it doesn't seem like the `ionic-framework` package is installed, so I guess it's a dependency of another one? Should I just go in the `node-modules` folder and checkout that version?

**Comment by maelp** [comment] 2021-12-25 15:14
I'm trying to check out your PR in a repo and to `npm install && npm run build` but it seems to fail

**Comment by maelp** [comment] 2021-12-25 15:30
It seems that explicitly tagging `(ev: KeyboardEvent)` fixes that, but wondering how you compiled it?

**Comment by maelp** [comment] 2021-12-25 15:47
I built it (there were errors on angular, but I removed all packages except core, vue, vue-router and it built), and then a `npm link --force` to use them locally, but then when compiling my app I get a lot of errors like this

![image](https://user-images.githubusercontent.com/15458/147388642-c62f4300-bb83-472c-965b-b5dda87baef4.png)

**Comment by maelp** [comment] 2021-12-28 13:16
Seems the bug was for another reason and I fixed it :)

**Comment by Cannonb4ll** [comment] 2022-01-20 08:25
@maelp 

What was the fix you've used?

**Comment by maelp** [comment] 2022-01-20 08:29
If I remember, the issue was that I was calling a method that did not exist when the user clicked on some route in the app, and after fixing this, the router started working normally again :)

**Comment by jreviews** [comment] 2022-01-23 13:43
Having exactly the same issue as @RobinHavre with ionic v6.0.3. Thanks so much for posting your workaround. The only thing that works for me is using MemoryHistory. I am not using tabs and I have `ion-page` on every page.

**Comment by alons182** [comment] 2022-01-24 23:24
Same here... 
my app has more than 3 level and the navigation freezes. The temporary solution is to switch to MemoryHistory

**Comment by tigohenryschultz** [comment] 2022-01-24 23:27
I've refactored quite a bit of the ionic/vue routing code here but it is for version 5.9.x. If you guys could give that a whirl. I'm no longer getting this issue.

https://github.com/ionic-team/ionic-framework/pull/24433

**Comment by jreviews** [comment] 2022-01-24 23:33
It happens for me with just 2 levels: list and detail. Swiping to go back breaks the navigation.

**Comment by liamdebeasi** [comment] 2022-01-27 21:44
Hi there,

Can everyone try the following dev build and let me know if it resolves the issue?

```
npm install @ionic/vue@6.0.5-dev.1643319505.71de250 @ionic/vue-router@6.0.5-dev.1643319505.71de250
```

I tested this dev build on the app in https://github.com/ionic-team/ionic-framework/issues/23873#issue-987585140 and verified that the issue no longer reproduces. (Though additional testing is always appreciated 😄 )

------

For some added context, this issue happens when using `default-href` on `ion-back-button` to go back to a page that had previously not existed. If you are not using `default-href` but running into the same behavior as described in this thread, **please create a new issue**. The issue you are running into is related to a different problem and needs to be triaged separately.

For anyone interested in why this problem was happening, please see the comment I added in the related PR: https://github.com/ionic-team/ionic-framework/pull/24670/files

**Comment by migo315** [comment] 2022-01-27 22:03
Thanks for the fix. I will test it this weekend. :-)

**Comment by alons182** [comment] 2022-01-28 00:44
Hi @liamdebeasi 
I tried it and it seems that the error is fixed... but in an application that uses **sidemenu** the error reappears when I click on a menu item and then navigate through the buttons. I don't know if it is related to the same issues
I leave you some examples

**from Home Page (menu item)**
![ezgif com-gif-maker](https://user-images.githubusercontent.com/1807814/151466291-58439f8c-a865-4435-8ef5-830bea8d8522.gif)

**from List Page (No menu Item)**
![ezgif com-gif-maker2](https://user-images.githubusercontent.com/1807814/151466827-85c18594-dcb3-4a14-988e-cabdaab216b2.gif)

**Comment by liamdebeasi** [comment] 2022-01-28 00:57
Do you have a GitHub repo I can take a look at?

**Comment by alons182** [comment] 2022-01-28 01:21
> Do you have a GitHub repo I can take a look at?

Yes... here https://github.com/alons182/sidemenutest

**Comment by Cannonb4ll** [comment] 2022-01-28 06:56
@liamdebeasi I have tested this in my app with a side menu as well, I don't get the same error @alons182 has with a sidemenu. I will do some more testing to see whether it comes back.

**Comment by liamdebeasi** [comment] 2022-01-31 17:09
Thanks for testing! I resolved those issues and added a new dev build to https://github.com/ionic-team/ionic-framework/issues/23873#issuecomment-1023666066.

Mind giving it another test?

**Comment by Cannonb4ll** [comment] 2022-01-31 17:40
Just did a thoroughly and it seems completely resolved for me now.

**Comment by alons182** [comment] 2022-01-31 17:50
Everything seems to be working fine now

**Comment by jreviews** [comment] 2022-01-31 17:56
Just tested as well and I am no longer getting the error. Many thanks for your efforts @liamdebeasi

**Comment by liamdebeasi** [comment] 2022-02-02 18:36
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/24670, and a fix will be available in an upcoming release of Ionic Framework.

Thank you very much to everyone who helped test and provide feedback! We appreciate your patience as we worked to resolve this issue.

**Closed** 2022-02-02 18:35 UTC
Labels: package: vue, type: bug
