### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by babycourageous** [ionic-team/ionic-framework#24308] opened 2021-12-02 22:03 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

In `ios` mode only - 

if there is an IonButton inside an IonItem w/ IonInput, hovering over the button seems to cause the hover state to lock on hovered and then when you click in the input, it appears to cause the button hover state to toggle back and forth until you click outside the input.

`md` mode does not exhibit this behavior

https://user-images.githubusercontent.com/14936212/144510287-13411231-d11e-4fcc-ac71-40cda5fc7595.mov

### Expected Behavior

Expected behavior is hovering over button should functino as expected - hover on when over, hover off when outside; there should be no interacting with input having focus/flashing cursor

### Steps to Reproduce

In attached github repo, simply fire up the demo and hover over the button - you should see it go to hover state but then not return
if you then click into the input, you should see the button styles flash between hover and not.

### Code Reproduction URL

https://github.com/babycourageous/ionic-input-with-icon-button-bug

### Ionic Info

Ionic:

   Ionic CLI       : 6.17.1
   Ionic Framework : @ionic/react 5.9.1

Capacitor:

   Capacitor CLI      : 3.3.2
   @capacitor/android : not installed
   @capacitor/core    : 3.3.2
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v14.17.6
   npm    : 6.14.15
   OS     : macOS Big Sur

**Comment by liamdebeasi** [comment] 2021-12-03 14:59
Thanks for the issue. What browser and version are you testing this on?

**Comment by liamdebeasi** [comment] 2021-12-03 15:06
Ah nevermind I can reproduce the issue now in Chrome 95. Let me take a closer look.

**Comment by liamdebeasi** [comment] 2021-12-03 15:11
This is a duplicate of https://github.com/ionic-team/ionic-framework/issues/24140. There was a bug in Chrome 95 where the opacity was not being reset properly. This has been fixed in Chrome 96. After updating my browser to Chrome 96 I can no longer reproduce the issue. I am going to close this as this is not a bug in Ionic. Thanks!

**Closed by liamdebeasi** 2021-12-03 15:11 UTC
Labels: triage

**Comment by babycourageous** [comment] 2021-12-04 21:20
@liamdebeasi ah - I'm so sorry i missed that issue in my searches. 
Also I'm not sure what happened to my original title. Let me know if you would like me to update the title to my original, more descriptive one for posterity. 

Thanks again!

**Comment by liamdebeasi** [comment] 2021-12-06 14:38
No problem, I have updated the issue title.

**Comment by babycourageous** [comment] 2021-12-06 16:50
Thanks @liamdebeasi !!
