### ISSUE TITLE
bug: ion-menu containing an ion-accordion scrolls up every time the menu opens

### ISSUE THREAD

**Issue by erikramalho** [ionic-team/ionic-framework#24634] opened 2022-01-24 13:00 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

If we put a ion-accordion inside a ion-menu with a ion-split-pane app, the menu scrolls up every time you close and reopen the ion-menu. The ion-menu scroll up right after the event ionDidOpen finishes.

### Expected Behavior

The ion-menu must keep the scroll postion. This behavior is seen if you put a ion-list + ion-item in a ion-menu.

### Steps to Reproduce

Just create a side menu app (ionic start and side menu) and then place a multiple ion-accordion / ion-accordion-group.  In the link provided, 

1. open the menu, expand the accordion
2. scroll down the menu 
3. click outside the menu to close it
4. reopen the menu: a scroll to top will happen. 

### Code Reproduction URL

https://stackblitz.com/edit/ionic-5-custom-ion-menu-button-jikmqz?file=src/app/tab1/tab1.page.html

### Ionic Info

Ionic CLI : 6.18.1 (/node/v12.22.5/lib/node_modules/@ionic/cli)
Ionic Framework : @ionic/angular 6.0.1
@angular-devkit/build-angular : 12.2.14
@angular-devkit/schematics : 12.2.14
@angular/cli : 12.2.14
@ionic/angular-toolkit : 5.0.1

**Comment by amandaesmith3** [comment] 2022-01-25 19:59
Thanks for the issue, I'm able to replicate in both Angular and core. The bug triggers if you have at least one accordion in a menu. It doesn't trigger with just a list in the menu, but I saw it using just one accordion group with one accordion. It looks like the accordion's content can be anything; you don't necessarily need an `ion-list` anywhere.

**Comment by sean-perkins** [comment] 2022-01-26 16:39
Additional context from #24660, this also appears to happen when the `ion-menu` content container has overflow scrolling. You can replicate in the conference app, by adding additional padding to the menu's content container and toggling the visibility of the menu. The menu's scroll position is always snapping back to the top. 

In that example, it's also replicable with `ion-list`.

**Comment by sean-perkins** [comment] 2022-01-26 17:14
Verified that this issue was introduced in #24076. 

After the menu has finished animating, the menu will focus the immediate child element that matches this query selector:
```
[tabindex]:not([tabindex^="-"]), input:not([type=hidden]):not([tabindex^="-"]), textarea:not([tabindex^="-"]), button:not([tabindex^="-"]), select:not([tabindex^="-"]), .ion-focusable:not([tabindex^="-"])
```

This will either focus an accordion item, a routerLink or other focusable elements. 

Ideally if we need to set the focus target, we should be preserving scroll position of the container.

**Comment by bashoogzaad** [comment] 2022-02-08 09:22
I was wondering if there is any indication on when this will be fixed? If it would scroll to the active routerLink element it would not be a big problem. However, it scrolls to the highest routerLink in the menu, also when the active routerlink is in the bottom. This can be a bit confusing for our customers.

**Comment by erikramalho** [comment] 2022-03-23 17:17
Thanks @JoeMeeks but we need ionic to fix such a dumb thing… hey @amandaesmith3 any updates on it?

**Comment by moekify** [comment] 2022-04-07 10:05
I think/hope it is related, but I'm experiencing the jumpy behavior on page transitions that do not involve the menu changing.

**Comment by amandaesmith3** [comment] 2022-04-07 13:52
@moekify Could you open a separate issue with a reproduction app? This issue is specifically for the menu scroll position jumping on close/reopen.

**Comment by moekify** [comment] 2022-04-07 14:00
> @moekify Could you open a separate issue with a reproduction app? This issue is specifically for the menu scroll position jumping on close/reopen.

Thanks for the swift reply! Before I do that, Is there a way I could test somehow if your open [PR](https://github.com/ionic-team/ionic-framework/pull/25044) fixes the issue I'm experiencing?

**Comment by amandaesmith3** [comment] 2022-04-07 14:18
Sure thing, here's a dev build you can use: `6.0.15-dev.11649340483.1f8857c7` The change is entirely specific to `ion-menu`, though, so I wouldn't expect a difference in your app if the issue doesn't involve one.

**Comment by amandaesmith3** [comment] 2022-04-08 21:01
This has been resolved via https://github.com/ionic-team/ionic-framework/pull/25044, and the fix will be available in a future release of Ionic 👍

**Closed** 2022-04-08 21:01 UTC
Labels: package: core, type: bug

**Comment by aligilani912** [comment] 2022-04-21 08:32
@amandaejohnston can you please guide about the process to fix this issue in the old projects?
