### ISSUE TITLE
bug: Slides doesn't work on IOS Device

### ISSUE THREAD

**Issue by Emile442** [ionic-team/ionic-framework#23035] opened 2021-03-11 17:11 UTC
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
The scrolling is not done completely. You have to move the entire slide with your finger to move on to the next one, otherwise you will get stuck between two. Unlike an android or in the browser where you just need to move your finger to move to the next slide
As if the freemode was active

**Expected behavior:**
Normally it suffices to move a little finger to go to the next slide

**Steps to reproduce:**
Copy from docs the slider and deploy to IOS Device.
Try to swipe slider.

**Related code:**

```vue
<ion-slides pager="true" ref="slides">
    <ion-slide>
        <ion-img src="/assets/img/article-1.jpg"></ion-img>
    </ion-slide>
    <ion-slide>
        <ion-img src="/assets/img/article-1.jpg"></ion-img>
    </ion-slide>
    <ion-slide>
        <ion-img src="/assets/img/article-1.jpg"></ion-img>
    </ion-slide>
</ion-slides>
```

**Other information:**

Related issue #11404 (the solution does not work)

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.13.1 (C:\laragon\bin\nodejs\node-v15\node_modules\@ionic\cli)
   Ionic Framework : @ionic/vue 5.6.0

Capacitor:

   Capacitor CLI   : 2.4.7
   @capacitor/core : 2.4.7

Utility:

   cordova-res : 0.15.3
   native-run  : not installed

System:

   NodeJS : v15.3.0 (C:\laragon\bin\nodejs\node-v15\node.exe)
   npm    : 7.0.14
   OS     : Windows 10```

**Comment by liamdebeasi** [comment] 2021-03-11 20:21
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/22961 (Same underlying issue).

**Closed by liamdebeasi** 2021-03-11 20:21 UTC
Labels: triage
