### ISSUE TITLE
bug: Multiple Side-Menu Bug

### ISSUE THREAD

**Issue by Aupourbau** [ionic-team/ionic-framework#20701] opened 2020-03-05 15:35 UTC
Bug Report

**Ionic version:**
@ionic/react": "5.0.0

**Current behaviour:**
Simple two pages app, each of them has a specific menu.
In Page 1:
- Open Menu 1 (using swipe right or toggle button)
- Close Menu 1  (using swipe right or toggle button)
- Go to Page 2

In Page 2:
- Open Menu 2 (using swipe right or toggle button)
- Close Menu 2  (using swipe right or toggle button)
- Go to Page 1

In Page 1:
- Open Menu 1 using toggle button --> Nothing happens
- Open Menu 1 using swipe right --> After a few tries getting this error:
animation-56279521.js:608 Uncaught TypeError: Failed to set the 'currentTime' property on 'Animation': The provided double value is non-finite.
    at animation-56279521.js:608
    at Array.forEach (<anonymous>)
    at setAnimationStep (animation-56279521.js:607)
    at Object.progressStep (animation-56279521.js:695)
    at animation-56279521.js:693
    at Array.forEach (<anonymous>)
    at Object.progressStep (animation-56279521.js:692)
    at class_1.onMove (ion-menu_3-md.entry.js:335)
    at onMove (ion-menu_3-md.entry.js:119)
    at fireOnMove (index-c38df685.js:482)

**Expected behaviour:**
Expecting the menu to open when coming back to a page

**Related code:**
Code to reproduce the behaviour at below link:
https://github.com/Aupourbau/ionic-multiple-side-menu-bug

If you can let me know what is wrong with my code of fix the bug if it is on your side, it would great!

Thanks!

**Comment by Aupourbau** [comment] 2020-03-05 18:06
I was finally able to fix the issue by using Lifecycle events and setting the menus status to disabled or not.
Repo is also updated with the fix

**Comment by martinkasa** [comment] 2020-03-12 07:36
I had this issue also in Ionic v4. 
My scenario:
* open menu on page 1 -> works
* navigate to page 2 - menu on page 2 -> works
* navigate BACK to page 1 - open menu on page 1 -> does not work anymore

After some debugging I find out "disabled" property on menu1 was set to true after navigation to page 2, BUT even after navigating back to page 1 "disabled" was not restored to false, so menu 1 stopped to work at all.

 ion-split-pane is also affected by this.

**Comment by longgt** [comment] 2020-03-16 03:36
#15916

**Comment by elabayoub** [comment] 2020-04-18 20:32
try setting max-edge-start="0" on undesired pages

**Comment by PAVDSSVD** [comment] 2020-04-18 20:44
* = 8

**Comment by PAVDSSVD** [comment] 2020-04-18 20:45
* 8

**Comment by liamdebeasi** [comment] 2022-05-04 20:52
Thanks for the issue and apologies for the delay. There are a couple known issues with using multiple side menus in an Ionic app. https://github.com/ionic-team/ionic-framework/issues/18974 and https://github.com/ionic-team/ionic-framework/issues/18683 are the main ones.

The GitHub repo provided in the original post no longer exists, and I am not able to reproduce this behavior with the latest version of Ionic 6. I am going to close this issue. If you are still running into this problem please create a new issue and include a GitHub repo that we can use to verify this behavior. Thank you!

**Closed by liamdebeasi** 2022-05-04 20:52 UTC
Labels: triage
