### ISSUE TITLE
bug: modal renders wrong first time loaded if <ion-range> is used in translucent footer toolbar 

### ISSUE THREAD

**Issue by NiklasSchwab** [ionic-team/ionic-framework#21623] opened 2020-06-25 08:05 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
If you have a modal with a fullscreen ion-content and translucent ion-header and ion-footer with a toolbar containing an ion-range (or an ion-radio-group, same behavior), the ion-content will not be rendered fullscreen the first time you open the modal. After the first time it will work if you open it again. It's hard to explain, better check the example out I made, it's a very eye-catching bug...

**Expected behavior:**
The ion-content is always fullscreen, not only from the second time opening it on.

**Steps to reproduce:**
New Ionic Angular app with Ionic 5.2.2 and Angular 9.1.9. Bug occurs in Android App, iOS App or with ionic serve.

**Related code:**

[Simple new Ionic project with a modal with the bug](https://github.com/NiklasSchwab/ionic_modal_bug)

**Other information:**
This worked with Ionic 4 and stopped working after migrating to Ionic 5. I already opened [a topic in the Ionic Forum](https://forum.ionicframework.com/t/canvas-page-with-header-footer-displayed-wrong-when-opening-first-time/191599) with more information about hoe I found the bug and where it's occuring in my real project.

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.10.1
   Ionic Framework               : @ionic/angular 5.2.2
   @angular-devkit/build-angular : 0.901.9
   @angular-devkit/schematics    : 9.1.9
   @angular/cli                  : 9.1.9
   @ionic/angular-toolkit        : 2.2.0

Utility:

   cordova-res : not installed
   native-run  : 1.0.0

System:

   NodeJS : v12.16.3
   npm    : 6.14.4
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment] 2020-06-25 13:20
Thanks for the issue. Can you double check your project? I get a blank screen when opening the modal.

**Comment by NiklasSchwab** [comment] 2020-06-25 14:14
Thanks for the reply. Should be fixed now.

**Comment by mhartington** [comment] 2020-06-25 14:52
Took a look @liamdebeasi 

It seems that when the modal is first opened, the padding offsets are not applied on first show. Meaning we get a solid background.

 
![Screen Shot 2020-06-25 at 10 49 12 AM](https://user-images.githubusercontent.com/2835826/85742766-83919e00-b6d1-11ea-956d-fcee094b377c.png)

Looking at the dom, the `--offset-top` and `--offset-bottom` vars are set to 0 on first show.
![Screen Shot 2020-06-25 at 10 50 42 AM](https://user-images.githubusercontent.com/2835826/85743026-b8055a00-b6d1-11ea-9d2e-cbca7b261e72.png)

Then on subsequent shows, they are set correctly.

![Screen Shot 2020-06-25 at 10 51 22 AM](https://user-images.githubusercontent.com/2835826/85743167-d23f3800-b6d1-11ea-8993-94c63bedbfb3.png)

**Comment by liamdebeasi** [comment] 2020-06-25 15:21
I have confirmed this as a bug. When `ion-content` sets its offsets, it relies on `offsetHeight`. If a parent element has `display: none`, the offset values will be `0` (similar to how `offsetParent` will be `null`). When the modal is used for the first time, there is a race condition where the offsets are set before `display: none` is removed from `ion-modal`.

**Comment by jongbonga** [comment] 2020-07-02 18:00
Hi

Not sure if I should create an issue for my case or just mention it here...

I'm encountering similar issue but with an `ion-textarea` not dispaying properly first time

**First time opening modal**

![Simulator Screen Shot - iPhone 8 Plus - 2020-07-02 at 19 40 17](https://user-images.githubusercontent.com/12111716/86394174-6e52db80-bc9e-11ea-9b26-c73b08c508ef.png)

The weird part is the button displays with no issue

**After closing and reopening** 

![Simulator Screen Shot - iPhone 8 Plus - 2020-07-02 at 19 57 13](https://user-images.githubusercontent.com/12111716/86394223-80cd1500-bc9e-11ea-87e6-74b5333fb340.png)

**Comment by NiklasSchwab** [comment] 2020-07-03 08:47
> Hi
> 
> Not sure if I should create an issue for my case or just mention it here...
> 
> I'm encountering similar issue but with an `ion-textarea` not dispaying properly first time

I guess it's the same bug. I got it with \<ion-range\> and \<ion-radio-group\>, so it's _probably_ a problem with "more complex" ionic components...

**Comment by NiklasSchwab** [comment] 2020-07-03 11:34
I've got a workaround until this is fixed:

1. Get the height of the \<ion-footer\> and \<ion-header\>
2. Set the `--offset-top` and `--offset-bottom` of the \<ion-content\> to these values

So the TS Code could look like this:
```javascript
const headerHeight = document.getElementById('canvasHeader').offsetHeight;
const footerHeight = document.getElementById('canvasFooter').offsetHeight;
const canvasContentElement = document.getElementById('canvasContent');
canvasContentElement.style.setProperty('--offset-top', headerHeight + "px");
canvasContentElement.style.setProperty('--offset-bottom', footerHeight + "px");
```

It might not be a great way to do this, but it gets the job done...

**Comment by liamdebeasi** [comment] 2023-03-02 19:56
Hi everyone,

I am able to reproduce this issue in Ionic 5.2.2, but I cannot reproduce the issue in the latest versions of Ionic 5 and Ionic 6. It appears that this issue was previously fixed, but we did not close this thread. I recommend updating to the latest version of Ionic 6 in order to receive this fix. I am going to close this, but let me know if there are any questions.

**Closed by liamdebeasi** 2023-03-02 19:56 UTC
Labels: package: core, type: bug
