### ISSUE TITLE
bug: React: `IonInput` inside `IonRadioGroup`  fires `onIonChange` event on the radio group

### ISSUE THREAD

**Issue by svilen-ivanov** [ionic-team/ionic-framework#28742] opened 2023-12-20 10:07 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

If I place an `IonInput` inside a `IonRadioGroup`  and I change the value in the input, the `onIonChange` event handler on the **`IonRadioGroup`  fires**.

### Expected Behavior

The `onIonChange` event handler on the `IonRadioGroup`  should fire only if I change the radio selection (i.e. click on the radio buttons

### Steps to Reproduce

```jsx
<IonRadioGroup value="1" onIonChange={(event) => alert(event.detail.value)}>
    <IonInput type="text" placeholder="Enter Input"></IonInput>
    <IonRadio value="1"/>
    <IonRadio value="2"/>
</IonRadioGroup>
```

Type something in the input, blur the input. An alert appears with the input value.

### Code Reproduction URL

https://github.com/svilen-ivanov/ionic-bug

### Ionic Info

[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package.json'
       
       Require stack:
       - /home/buhtum/dev/node_modules/@ionic/cli/lib/project/index.js
       - /home/buhtum/dev/node_modules/@ionic/cli/lib/index.js
       - /home/buhtum/dev/node_modules/@ionic/cli/index.js
       - /home/buhtum/dev/node_modules/@ionic/cli/bin/ionic
[WARN] Error loading @capacitor/android package.json: Error: Cannot find module '@capacitor/android/package.json'
       
       Require stack:
       - /home/buhtum/dev/node_modules/@ionic/cli/lib/project/index.js
       - /home/buhtum/dev/node_modules/@ionic/cli/lib/index.js
       - /home/buhtum/dev/node_modules/@ionic/cli/index.js
       - /home/buhtum/dev/node_modules/@ionic/cli/bin/ionic

Ionic:

   Ionic CLI       : 7.1.6 (/home/buhtum/dev/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 7.6.2

Capacitor:

   Capacitor CLI      : 5.6.0
   @capacitor/android : not installed
   @capacitor/core    : 5.6.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 2.0.0

System:

   NodeJS : v18.17.1 (/usr/bin/node)
   npm    : 9.6.7
   OS     : Linux 6.2

**Comment by svilen-ivanov** [comment] 2023-12-20 10:08
[Here is the change](https://github.com/svilen-ivanov/ionic-bug/commit/f61d1c613c079ae1acf7822f9c0db62516117f2e) that demonstrates the bug

**Comment by svilen-ivanov** [comment] 2023-12-20 10:47
My current workaround is:
```jsx
<IonRadioGroup
  onIonChange={(event) => {
    if (event.target.tagName.toLowerCase() !== "ion-radio-group") {
      console.debug("Ignoring event from non-radio-group element", event.target.tagName);
      return;
    }
    onChange(event.detail.value);
  }}
  //
/>
```

**Comment by liamdebeasi** [comment] 2023-12-20 14:33
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The `ionChange` event bubbles in Ionic. Adding `onIonChange` on `IonRadioGroup` adds an event listener for any `ionChange` event, not `ionChange` specifically for `IonRadioGroup`. As a result, when `IonInput` emits `ionChange` the event will bubble up to `IonRadioGroup` and your event listener will fire.

This behavior aligns with the native browser behavior where `change` events bubble: https://codepen.io/liamdebeasi/pen/NWJKMdW

In this demo, we add a `change` listener on the `.wrapper` element which is a parent of the radio input.

**Closed by liamdebeasi** 2023-12-20 14:33 UTC
Labels: triage

**Comment by svilen-ivanov** [comment] 2023-12-20 16:49
Thank you for your time looking into this report. I agree with your resolution and conclusion. I'm quite surprised with this outcome, but it is consistent with event bubbling.
