### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by nikiphoros** [ionic-team/ionic-framework#24832] opened 2022-02-22 09:51 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

sometimes shows multiple components with a black background after open application

### Expected Behavior

need to show whatever background we have set

### Steps to Reproduce

![WhatsApp Image 2022-02-11 at 11 24 58 PM](https://user-images.githubusercontent.com/39794943/155106822-d735c942-c929-478b-83e0-8b58c484a15c.jpeg)

### Ionic Info

Ionic:

   Ionic CLI                     : 6.18.1 (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.9.2
   @angular-devkit/build-angular : 12.1.4
   @angular-devkit/schematics    : 12.1.4
   @angular/cli                  : 12.1.4
   @ionic/angular-toolkit        : 4.0.0

Cordova:

   Cordova CLI       : 11.0.0
   Cordova Platforms : android 10.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 17 other plugins)

Utility:

   cordova-res : 0.15.4
   native-run  : 1.5.0

System:

   Android SDK Tools : 26.1.1 (E:\sdk)
   NodeJS            : v12.14.0 (C:\Program Files (x86)\nodejs\node.exe)
   npm               : 6.11.2
   OS                : Windows 10

### Additional Information

I have one ionic app that was posted on the play store for the android platform.  earlier everything was good for the last 6 months. nowadays many of my users report to me that sometimes whenever we open the app it shows multiple components with a black background. I have shared images of screenshots with this report 
next, now some of the current projects on which I am currently working have the same issue. 
I am not sure why this happened. I have tried a lot to find a relevant solution on the internet but no luck

**Comment by nikiphoros** [comment] 2022-02-22 09:52
![WhatsApp Image 2022-02-22 at 3 21 52 PM](https://user-images.githubusercontent.com/39794943/155107377-f3c02206-ba04-4a59-a5cc-0594d0857062.jpeg)

**Comment by Umfi** [comment] 2022-02-22 10:44
Currently there is a problem with Dark Mode and Android.

More information here: https://github.com/ionic-team/ionic-framework/issues/24771

**Comment by nikiphoros** [comment] 2022-02-22 11:07
Sir can you please suggest me any temporary solution. If app will only work
for light mode only. That will also work for me
Please help me sir

**Comment by Umfi** [comment] 2022-02-22 11:17
Temporary solution for light mode only:

Remove the `@media (prefers-color-scheme: dark) {}` section in src/theme/variables.css.

In public/index.html replace
`<meta name="color-scheme" content="light dark" />`
with
`<meta name="color-scheme" content="light" />`

This works for me.

**Comment by sean-perkins** [comment] 2022-02-22 15:41
Closing as a duplicate of #24771.

**Closed by sean-perkins** 2022-02-22 15:41 UTC
Labels: triage
