### ISSUE TITLE
bug: Ion-input has delay focus

### ISSUE THREAD

**Issue by franckysolo** [ionic-team/ionic-framework#23908] opened 2021-09-09 11:07 UTC
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

There is a delay with focus when switching ion-inputs

https://user-images.githubusercontent.com/2419646/132673801-07e9d9a0-b481-432d-8b79-05929f32291f.mp4

https://user-images.githubusercontent.com/2419646/132676656-d2bbf834-0a70-4e7c-bf02-4142b770914a.mp4

### Expected Behavior

There should be no delay on focus when switching ion-inputs

### Steps to Reproduce

just switch focus on each field

### Code Reproduction URL

https://github.com/franckysolo/ionic-input-focus

### Ionic Info

```
Ionic:

   Ionic CLI       : 6.17.0 
   Ionic Framework : @ionic/vue 5.6.14

Capacitor:

   Capacitor CLI      : 2.4.9
   @capacitor/android : 2.4.9
   @capacitor/core    : 2.4.9
   @capacitor/ios     : 2.4.9

Utility:

   cordova-res                          : not installed globally
   native-run (update available: 1.4.1) : 1.3.0

System:

   NodeJS : v14.17.6 
   npm    : 6.14.8
   OS     : Linux 4.15
```

### Additional Information

Seems to only happen on ios phone or ios emulator

Bugs related but not solved :

https://github.com/ionic-team/ionic-framework/issues/23869 
https://github.com/ionic-team/ionic-framework/issues/23664

we have another bug who may be related 
in iphone when scrolling page the button sometimes its half covered sometimes its not even showing

https://user-images.githubusercontent.com/2419646/132674899-9163b1bd-e6d3-48bf-bf6b-9d128ba28cb7.mp4

**Comment by liamdebeasi** [comment] 2021-09-09 13:19
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/23664.

**Closed by liamdebeasi** 2021-09-09 13:19 UTC
Labels: triage

**Comment by franckysolo** [comment] 2021-09-09 13:52
@liamdebeasi hi is there a fix for that or a workaround?
