### ISSUE TITLE
bug: routing breaks in ionic/vue when presenting same view in multiple tabs and using ion-back-button

### ISSUE THREAD

**Issue by mmoore99** [ionic-team/ionic-framework#27698] opened 2023-06-24 22:24 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

I am developing an app that has a requirement for the same view to be able to be displayed in multiple tabs simultaneously. This process is described in the ionic docs [here](https://ionicframework.com/docs/vue/navigationl) under the section "Reusing Views Across Tabs":

> Instead, we recommend having routes in each tab that reference the same component. This is a practice done in popular apps like Spotify. For example, you can access an album or podcast from the "Home", "Search", and "Your Library" tabs. When accessing the album or podcast, users stay within that tab. The app does this by creating routes per tab and sharing a common component in the codebase. 

In order to test this functionality I have done the following:

1. Created an app using the standard ionic "tabs" starter project. 
2. Added a "ChildPage1" component with a "Back button" using ion-back-button
3. On each of the three tab pages added a button with a router-link to "Go to ChildPage1"

When navigating around the three tabs and the child tab using the tab buttons, the go to child button and the back button on the child page after a certain sequence of steps the routing breaks. This happens consistently (see the Steps to Reproduce section for the details of how to reproduce the condition). 

### Expected Behavior

Router navigation should not break when the same view is open in multiple tabs at the same time when moving around in the app.

### Steps to Reproduce

Start the app:
- initial display: tab 1,  url=tabs/tab1
- click Go to Child1: correct - displays child1, url=tabs/tab1/child1
- click Tab 2: correct - displays tab2, url=/tabs/tab2
- click Go to Child1: correct - displays child1, url=tabs/tab2/child1
- click Tab 3: correct - displays tab3, url=/tabs/tab3
- click Go to Child1: correct - displays child1, url=tabs/tab3/child1
- click Tab 1: correct - displays child1, url=/tabs/tab1/child1
- click Back: correct - displays tab1, url=/tabs/tab1
- click Go to Child1: correct - displays child1, url=tabs/tab1/child1
- click Tab 3: correct - displays tab3/child1,  url=/tabs/tab3/child1
- click Back: incorrect
	- nothing happens, displays tab3/child1,  url=/tabs/tab3/child1
	- should display tab3, url=/tabs/tab3

- click Tab1: incorrect
	- displays tab3,  url=/tabs/tab1/child1, Tab 3 highlighted
	- should display tab 1,  url=tabs/tab1
- click Tab 2: correct - displays tab2/child1, url=/tabs/tab2/child1
- click Back: incorrect
	- displays: tab3/child1, url=/tabs/tab3/child1
	- should display: tab2, url=tabs/tab2

### Code Reproduction URL

https://stackblitz.com/edit/github-rg4p6g  https://github.com/mmoore99/ionic-vue-tabs-with-children-test

### Ionic Info

@ionic vue = 7.1.0
@ionic vue-router 7.1.0
vue 3.3.4
vue-router 4.2.2

**Comment by liamdebeasi** [comment] 2023-06-26 13:08
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/25213.

**Closed by liamdebeasi** 2023-06-26 13:08 UTC
Labels: triage
