### ISSUE TITLE
bug: iOS Keyboard will not hide on blur if submit is triggered (Enter)

### ISSUE THREAD

**Issue by wilk-polarny** [ionic-team/ionic-framework#20523] opened 2020-02-17 22:38 UTC
# Bug Report

**Ionic version:**
[x] **4.11.9**

**Current behavior:**
When submitting a form (via enter on the phone keyboard) with an `<ion-input>` in focus, the keyboard will not disappear.

A weird thing: I am still able to type into the now invisible (due to forward navigation after submit) input for a few seconds.

**Expected behavior:**
I expect the keyboard to disappear, especially if the submit action handler of the form executes a navigation to another page.

**Steps to reproduce:**
- Create a form with inputs and a submit handler
- Submit the form using the submit button on the keyboard

**Related code:**

None-

**Other information:**
Is this expected behaviour? Do I need to explicitly hide the keyboard on submit?

If this is a bug, I'm not sure whether it's related to the ionic core, the webview plugin or the keyboard plugin.

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.0.1 (/Users/Wilk/.nvm/versions/node/v10.16.3/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 4.11.9
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.1.2

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 4 other plugins)

Utility:

   cordova-res (update available: 0.9.0) : 0.8.1
   native-run                            : 0.3.0

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.2
   NodeJS     : v10.16.3 (/Users/Wilk/.nvm/versions/node/v10.16.3/bin/node)
   npm        : 6.9.0
   OS         : macOS Catalina
   Xcode      : Xcode 11.3.1 Build version 11C504

```

**Comment by liamdebeasi** [comment] 2020-02-17 22:41
Thanks for the issue. The keyboard should disappear. Can you provide a repo with the code required to reproduce this issue?

**Comment by wilk-polarny** [comment] 2020-02-17 23:36
@liamdebeasi , thanks for getting back to me!

I have created a repro repo - while trying to reproduce, I noticed that we are using `keyup.enter` to also listen for the enter event - this might be it. It's a workaround because the `ngSubmit`  callback function will not trigger if one presses the enter key on the device keyboard.

https://github.com/wilk-polarny/repro-ionic-issue-20523

While I think we will have to handle the keyboard ourselves if we use the `keyup.enter` approach, don't you think that the `ngsubmit` callback should be triggered in that case?

My guess is that Enter will only insert a line break if the component is a text-area - shouldn't enter issue a submit action?

**Comment by liamdebeasi** [comment] 2020-02-18 16:23
Thanks for the follow up.

Instead of `<form (ngSubmit)="onSubmit()" (keyup.enter)="onSubmit()">`

try `<form (submit)="onSubmit()">`

This will bind to the native submit event that is emitted. From my end, it looks like the input is blurring properly in that case.

**Comment by wilk-polarny** [comment] 2020-02-18 17:39
@liamdebeasi , thank you! where does the  `(submit)` handling come from? Angular docs only mention the obvious `(ngSubmit)`. Won't `(submit)`cause any side effects like page reloads and so on? - Is (submit) safe to use within Ionic Angular Apps?

Also:

> The FormGroup directive listens for the submit event emitted by the form element and emits an ngSubmit event that you can bind to a callback function.
https://angular.io/guide/reactive-forms

Shouldn't the ngSubmit callback also be called when pressing Enter?
Cause when using a plain angular app, it seems to work.

**Comment by wilk-polarny** [comment] 2020-02-20 18:46
@liamdebeasi , just checked. `(submit)` does not work for the enter key on iOS (use-submit-instead-ngsubmit branch on the repo linked above).

**Comment by wilk-polarny** [comment] 2020-02-27 00:17
Currently, we're simply hiding the keyboard before each router navigation call (with the keyboard plugin) to work around this

**Comment by stewones** [comment] 2021-09-17 18:02
this still an issue as of sep 2021

I'm having to fake a submit button inside the form as workaround

**Comment by liamdebeasi** [comment] 2022-02-28 21:43
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/19368 (same underlying issue).

**Closed by liamdebeasi** 2022-02-28 21:43 UTC
Labels: triage
