### ISSUE TITLE
bug: IOS/Android keyboard appears when tapping on the Hours / Minutes in the timepicker 

### ISSUE THREAD

**Issue by Yura13** [ionic-team/ionic-framework#24889] opened 2022-03-07 10:00 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

![image](https://user-images.githubusercontent.com/17030431/157007935-eca88dcf-99e9-4b3d-918e-2a2cf9db1cbb.png)

### Expected Behavior

It is not convenient to use the scrolling of hours/minutes when the keyboard appears. I believe users don't need a keyboard.

### Steps to Reproduce

Keyboard appears when tapping on the Hours / Minutes in the timepicker 

### Ionic Info

Ionic:

   Ionic CLI                     : 6.18.1 (C:\Users\Xiaomi\AppData\Roaming\nvm\v16.13.2\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.0.10
   @angular-devkit/build-angular : 13.1.3
   @angular-devkit/schematics    : 13.1.3
   @angular/cli                  : 13.1.3
   @ionic/angular-toolkit        : 5.0.3

Cordova:

   Cordova CLI       : 10.0.0 (cordova-lib@10.1.0)
   Cordova Platforms : android 9.1.0, browser 6.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, cordova-plugin-ionic 5.5.1, (and 28 other plugins)

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   Android SDK Tools : 26.1.1 (C:\Android\android-sdk)
   NodeJS            : v16.13.2 (C:\Program Files\nodejs\node.exe)
   npm               : 8.1.2
   OS                : Windows 10

**Comment by liamdebeasi** [comment] 2022-03-07 14:02
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. This behavior is by design is intended to match the iOS time picker. Having the keyboard appear is primarily for accessibility purposes when it is easier to type than swipe.

Here is an example of the iOS picker:

https://user-images.githubusercontent.com/2721089/157048647-43bd3330-97cd-40cd-b149-74fc92aca713.mp4

**Closed by liamdebeasi** 2022-03-07 14:02 UTC
Labels: triage
