### ISSUE TITLE
bug: Specifying provideIonicAngular() in a route provider prevents hydration from completing

### ISSUE THREAD

**Issue by dexster** [ionic-team/ionic-framework#29324] opened 2024-04-11 08:39 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Specifying `provideIonicAngular()` in a route provider prevents the hydration from completing successfully

The CSS display property does not update 

html:not(.hydrated) body {
    display: none;
}

### Expected Behavior

When providing provideIonicAngular() in the bootstrap config it works as expected:

html.ion-ce body {
    display: block;
}
html:not(.hydrated) body {
    ~display: none;~
}

### Steps to Reproduce

Use the reproduction url  below. 
Open main.ts
Inspect the body tag to see the issue.
Uncomment the line and the display works as expected 

### Code Reproduction URL

https://stackblitz.com/edit/angular-pmvzjr?file=src%2Fmain.ts,src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fexample.component.html

### Ionic Info

Ionic:

   Ionic CLI : 7.2.0

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v20.9.0
   npm    : 10.1.0
   OS     : macOS Unknown

**Comment by liamdebeasi** [comment] 2024-04-11 13:44
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. `provideIonicAngular` relies on the Angular standalone components which does not use hydration. Your application is loading code from the hydrated version of Ionic which is why it is expecting hydration to complete. As mentioned in the [documentation](https://ionicframework.com/docs/angular/build-options#usage-with-standalone-based-applications), your application should not mix imports from `@ionic/angular` and `@ionic/angular/standalone` as they use 2 different build systems.

**Closed by liamdebeasi** 2024-04-11 13:44 UTC
Labels: triage

**Comment by liamdebeasi** [comment] 2024-04-11 14:23
`provideIonicAngular` should be set on the root provider. It does not need to be provided individually to each component in the routing definition.

**Comment by liamdebeasi** [comment] 2024-04-11 15:43
You'll want to make sure that the `provideIonicAngular` is added to `main.ts` file in the remote application in that case. `provideIonicAngular` allows you to set a global config, so it needs to be set globally in the context of a single application.

I'm assuming here that the remote application is a complete Angular application instead of a single component.

**Comment by dexster** [comment] 2024-04-11 15:52
It is built as a complete Angular application, so it does have main.ts and everything else that Ionic requires.

When it is integrated inside a host app as a micro-front-end remote, the remotes main.ts and root providers are bypassed and the host loads an entry point to the remote, which is the routes file containing the initial route the host must navigate to. This route needs to provide all the providers that the remote requires.
