### ISSUE TITLE
bug: Cannot change border-color on outline button, independent of the text color

### ISSUE THREAD

**Issue by vandres** [ionic-team/ionic-framework#22515] opened 2020-11-18 09:11 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

Having a simple button:

```
		<ion-button
			(click)="forward()"
			color="secondary"
			fill="outline"
			class="outline-button"
		>{{ 'onboarding.goal.button.skip' | translate }}</ion-button>
```

I would like to change the style of the button, to have the secondary color as text and medium as border-color.

```
.outline-button {
	--border-color: var(--ion-color-medium);
}
```

But that just doesn't work, since the outline button takes its color always from the base color:

![grafik](https://user-images.githubusercontent.com/1436383/99509403-c44ac600-2996-11eb-90f2-26233ffbb3e3.png)

**Expected behavior:**

Respect `--border-color` also for outline buttons

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.12.2 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.4.1
   @angular-devkit/build-angular : 0.1002.0
   @angular-devkit/schematics    : 10.0.7
   @angular/cli                  : 10.2.0
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : ios 6.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, cordova-plugin-ionic 5.4.7, (and 27 other plugins)

Utility:

   cordova-res (update available: 0.15.2) : 0.15.1
   native-run                             : 1.2.2

System:

   ios-deploy : 1.11.3
   ios-sim    : 8.0.2
   NodeJS     : v12.19.1 (/usr/local/bin/node)
   npm        : 6.14.8
   OS         : macOS Catalina
   Xcode      : Xcode 12.2 Build version 12B45b


```

**Comment by liamdebeasi** [comment] 2020-11-18 14:25
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The problem here is that you are trying to set `color="secondary"` and then trying to set the styles again in your CSS. You are giving conflicting styles, and the `color` property is always going to get priority so you should be doing one or the other. 

Here is an example of how you can set the text color to `ion-color-secondary` and the border color to `ion-color-medium`: https://codepen.io/liamdebeasi/pen/ExyJeqe

The styles provided in `:root` are likely already in your application, so the code you want to copy is in `ion-button` in the CSS.

Thanks!

**Closed by liamdebeasi** 2020-11-18 14:25 UTC
Labels: triage
