### ISSUE TITLE
bug: ion-refresh does not work properly when we use custom gesture on the same page

### ISSUE THREAD

**Issue by kristijanmomiroski** [ionic-team/ionic-framework#23201] opened 2021-04-17 00:13 UTC
# Bug Report

**Ionic version:**

[x] **4.x**
[] **5.x**

**Current behavior:**

I'm trying to use gesture created using **GestureController** (long-press & tap) along with ion-refresher, but it doesn't work. Only my custom gesture works, but  ion-refresher doesn't work well.

**Expected behavior:**

I have added custom gesture to ion-item, and what I want to achieve is  when  the user press on any ion-item and pull down, it should invoke the corresponding method **(ionRefresh)** and "refresh" the data.

**Steps to reproduce:**

- Inside an Ionic Angular app, create a directive for long-press
- Create page and add some data using ion-list, ion-item and also add ion-refresher on the same page
- Ion-refresher won't work if you press on any ion-item and pull down, it will work only if you remove directive from ion-item or if you press on some blank space between header and ion-list.

**Related code:**

**Directive Code:**

export class LongPressDirective implements AfterViewInit {
    @Output() press = new EventEmitter();
    @Output() tap = new EventEmitter();
    @Input("delay") delay =  400;
    action: any; 
    start;
    end;
    move = false;

    private longPressActive = false;
    gesturePriorityRes: number = 32;

    constructor(
                    private el: ElementRef,
                    private gestureCtrl: GestureController,
                    private zone: NgZone
                ) {}

    ngAfterViewInit() {
        this.loadLongPressOnElement();
    }

    loadLongPressOnElement() {
        const gesture = this.gestureCtrl.create({
            el: this.el.nativeElement,
            threshold: 0,
            gestureName: 'long-press',
	    gesturePriority: this.gesturePriorityRes,
	    direction: 'y',
            onStart: ev => {
                this.start = new Date().getTime();
                this.longPressActive = true;
                this.longPressAction();
            },
            onMove: ev => {
                this.move = true;
		this.gesturePriorityRes = 30
            },
            onEnd: ev => {
                this.end = new Date().getTime();
                this.longPressActive = false;
                this.tapAction();
            }
        });
        gesture.enable(true);
    }

    private longPressAction() {
        if (this.action) {
            clearInterval(this.action);
        }
        this.action = setTimeout(() => {
            this.zone.run(() => {
                if (this.longPressActive === true) {
                    this.longPressActive = false;
                    this.press.emit();
                }
            });
        }, this.delay);
    }

`<ion-content [scrollY]="!isSelected" scrollEvents="true" color="light" #mainContent>
        <ion-refresher [disabled]="!userData" (ionRefresh)="refreshData($event).subscribe()" slot="fixed">
            <ion-refresher-content></ion-refresher-content>
        </ion-refresher>
        <ion-list lines="full">
            <ion-item custom-long-press *ngFor="let user of userData"
                (click)="openUserData(user)" (press)="userPressed(user)">
                <ion-label>
                    <h2>{{user.firstName}}</h2>
                    <h3>{{user.lastName}}</h3>
                </ion-label>
            </ion-item>
        </ion-list>
 </ion-content>`

**Comment by liamdebeasi** [comment] 2021-04-19 14:34
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The problem is that your gesture is always going to fire before the refresher gesture fires because your gesture threshold is `0`. As soon as you click, your custom gesture will activate. Setting the threshold to `6` or greater resolves the issue as the threshold for the refresher gesture is `5`.

**Closed by liamdebeasi** 2021-04-19 14:34 UTC
Labels: triage
