### ISSUE TITLE
bug: ion-datetime month scrolling breaks when in an accordion on Firefox

### ISSUE THREAD

**Issue by Dziaders** [ionic-team/ionic-framework#28118] opened 2023-09-05 13:09 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When clicked on ion-datetime calendars day element, the whole calendar page slides to previous month. Date gets picked and sent successfully. Only occurs on Firefox (my version is 116.0.3 & i'm working on Ubuntu 22.04.3 LTS). When same code is previewed in chrome it behaves correctly.

### Expected Behavior

When clicked on ion-datetime calendars day element, the element gets highlighted and is shown until ion-datetime component gets closed

### Steps to Reproduce

fragment of my component:

```html
<ion-accordion-group>
  <ion-accordion value="from" class="border-radius-10 ion-margin-vertical" #accordionDateFrom>
    <ion-item slot="header" color="light" lines="none">
      <ion-label
      >{{ 'SENSOR.HISTORY.FROM' | translate }}:
        {{ period.start | amLocale:langService.language | amDateFormat: 'lll' }}</ion-label>
    </ion-item>
    <div slot="content">
      <ion-datetime
        [locale]="translate.currentLang"
        [value]="period.start"
        (ionChange)="setPeriodStart($event); toggleAccordion();"
      ></ion-datetime>
    </div>
  </ion-accordion>
  <ion-accordion value="to" class="border-radius-10">
    <ion-item slot="header" color="light" lines="none">
      <ion-label
      >{{ 'SENSOR.HISTORY.TO' | translate }}
        : {{ period.end | amLocale:langService.language | amDateFormat: 'lll' }}</ion-label>
    </ion-item>
    <div slot="content">
      <ion-datetime
        [locale]="translate.currentLang"
        [value]="period.end"
        (ionChange)="setPeriodEnd($event)"
      ></ion-datetime>
    </div>
  </ion-accordion>
</ion-accordion-group>
```

### Ionic Info

Ionic:

   Ionic CLI                     : 7.1.1 (/home/fb/.asdf/installs/nodejs/19.2.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.0.7
   @angular-devkit/build-angular : 16.0.2
   @angular-devkit/schematics    : 15.2.5
   @angular/cli                  : 16.0.2
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.0.3
   @capacitor/android : not installed
   @capacitor/core    : 5.0.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v19.2.0 (/home/fb/.asdf/installs/nodejs/19.2.0/bin/node)
   npm    : 9.4.2
   OS     : Linux 6.2

**Comment by amandaejohnston** [comment] 2023-09-05 14:54
Thank you for the issue. I'm able to replicate this with just the following:
```html
<ion-accordion-group>
  <ion-accordion>
    <ion-item slot="header" color="light" lines="none">
      <ion-label>Label</ion-label>
    </ion-item>
    <div slot="content">
      <ion-datetime></ion-datetime>
    </div>
  </ion-accordion>
</ion-accordion-group>
```
I'm also unable to replicate in Chrome. It does happen in Ionic core, though, meaning it's not Angular-specific.

I noticed that if you set `animated="false"` on the `ion-accordion-group` to disable animations, the bug goes away. This makes me think that when the datetime's scroll listener (which handles month selection) is initialized, the accordion is still in the process of animating it, which causes some of the position calculations to break. When the bug occurs, clicking dates causes the datetime's month to jump around, which is indicative of scroll listener issues.

**Comment by Dziaders** [comment] 2023-09-13 07:05
I'm glad you were able to replicate the issue. Thanks for the animated="false" tip - it works most of the time :)

**Comment by liamdebeasi** [comment] 2023-12-06 20:46
Hey there! I looked into this bug. When the accordion expands, the datetime's Intersection Observer fires which tries to center the calendar months in view. However, the scroll position then gets re-set to 0px. This appears to be related to our usage of `ion-item` inside of the calendar header as removing it causes the issue to no longer reproduce. It's likely that some feature in there was triggering a Firefox bug.

In Ionic 8 we are removing `ion-item` in favor of a `button` element (which also does not reproduce the issue). Since the work required to avoid this behavior has been completed, I am going to close this issue.

Here is an Ionic 8 dev build if you'd like to test: `7.5.8-dev.11701894917.1c1465bd`

Note that this dev build is subject to [Ionic 8 Breaking Changes](https://github.com/ionic-team/ionic-framework/blob/feature-8.0/BREAKING.md#version-8x). Let me know if you have any questions.

**Closed by liamdebeasi** 2023-12-06 20:46 UTC
Labels: package: core, type: bug
