### ISSUE TITLE
bug: Unexpected ion-back-button in ion-tabs

### ISSUE THREAD

**Issue by mannok** [ionic-team/ionic-framework#25678] opened 2022-07-26 08:52 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

ìon-back-button` shows up when switching between tabs after performed some navigation in certain tab, while it does not supposed to be. Also, clicking on the ìon-back-button` has no response.

### Expected Behavior

Each tab has its own navigation stack, ìon-back-button` should be showed only if there are navigation stacks in current tab. Therefore, switching between tabs should not cause ìon-back-button` visible.

### Steps to Reproduce

1. Clone from the repository I created [https://github.com/mannok/IonBackButtonIssue](https://github.com/mannok/IonBackButtonIssue)
2. Run `npm install`
3. Run `npm run serve`
4. Test in the browser

[video-convert-1658825495219.webm](https://user-images.githubusercontent.com/458220/180965618-424cc536-ad7e-4dc1-a087-c7b78001bbf3.webm)

### Code Reproduction URL

https://github.com/mannok/IonBackButtonIssue

### Ionic Info

Ionic:

   Ionic CLI       : 6.20.1 (d:\Users\xw2564\AppData\Roaming\npm-cache\_npx\34040\node_modules\@ionic\cli)
   Ionic Framework : @ionic/vue 6.1.15

Capacitor:

   Capacitor CLI      : 3.6.0
   @capacitor/android : not installed
   @capacitor/core    : 3.6.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.6.0

System:

   NodeJS : v14.17.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.13
   OS     : Windows 10

**Comment by liamdebeasi** [comment] 2022-07-27 15:58
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/25213. The behavior that is detailed on the linked issue is slightly different, but the underlying bug that is causing these two issues is the same.

**Closed by liamdebeasi** 2022-07-27 15:58 UTC
Labels: triage
