### ISSUE TITLE
bug: When navigating across tabs subpages using defaultHref of back button, origin page is added to history stack

### ISSUE THREAD

**Issue by jeroenkroese** [ionic-team/ionic-framework#18559] opened 2019-06-17 12:11 UTC
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
I'm using the Angular router and the Ionic tabs starter template. The tabs.router.module looks as follows: 
```
  {
    path: 'tabs',
    component: TabsPage,
    children: [
      {
        path: 'tab1',
        children: [
          {
            path: '',
            loadChildren: '../tab1/tab1.module#Tab1PageModule'
          },
          {
            path: 'page2',
            children: [
              {
                path: '',
                loadChildren: '../page2/page2.module#Page2PageModule'
              },
              {
                path: 'page3',
                loadChildren: '../page3/page3.module#Page3PageModule'
              }
            ]
          }
        ]
      },
```
Page2 has a back-button with a property defaultHref="/tabs/tab1". Page 3 has a back-button with a property defaultHref="/tabs/tab1/page2". 

When I navigate directly to localhost:8100/tabs/tab1/page3 and click on the back button, it takes me to /tabs/tab1/page2.  However, when I click on the back button on page 2, it takes me back page 3.

**Expected behavior:**
When clicking on the back button on page 2, coming from page 3, I would expect to be routed to the defaultHref property of the back-button on page 2. Page 3 seems to be added to the history stack. 

**Steps to reproduce:**

See sample repo
```
https://github.com/jeroenkroese/ionic-back-button-issue/
```

**Ionic info:**

```
Ionic:
   ionic (Ionic CLI)             : 4.12.0
   Ionic Framework               : @ionic/angular 4.5.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

System:
   NodeJS : v10.15.3 
   npm    : 6.7.0
   OS     : Windows 10
```

**Comment by lincolnthree** [comment] 2019-06-22 12:55
I believe there is something fishy going on here. I'm seeing similar behavior in my app where using named outlets (like tabs), duplicate pages/views get added to the navigation stack when changing navigation state only in the named outlet (tab) --- while leaving the primary page/view route unchanged.

**Comment by amandaesmith3** [comment] 2022-02-02 22:23
Thanks for the issue. I'm going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/23448. While this issue is much older, we already have the other one tracked as a bug internally, so this seems like the best way to consolidate things.

**Closed by amandaesmith3** 2022-02-02 22:23 UTC
Labels: triage
