### ISSUE TITLE
bug: Chrome adding outline to focused `ion-card` button

### ISSUE THREAD

**Issue by Yohandah** [ionic-team/ionic-framework#21691] opened 2020-07-07 12:15 UTC
# Bug Report
I've found that adding a routerLink to a ion-card makes the card "focusable" and Chrome has a style on the card when it's in the "focus" state :
![image](https://user-images.githubusercontent.com/15921402/86779225-9ace7500-c05b-11ea-95a1-b4c5b002f82d.png)

You can open the stackblitz linked on Firefox and when you press a card there is no black border while on chrome there is.

![Sans titre](https://user-images.githubusercontent.com/15921402/86779733-2ea04100-c05c-11ea-80b8-5c7c494a6396.png)

Maybe ionic should override this Chrome :hover style to reset it by default ? I added this in my styles.global.scss :
```
// reset chrome style
ion-card:focus {
  outline: none;
}
```

I'm also able to fix this by setting a (click) event then navigate with `NavController `instead of a `RouterLink`

**Ionic version:**
[x] **5.x**

**Related code:**

https://ionic-v5-base-test-bordures.stackblitz.io

**Comment by Yohandah** [comment] 2020-07-07 14:02
I am not sure this is a ionic specific bug but it needs to be looked at for the behavior with a RouterLink.

It follows this chromium release : https://blog.chromium.org/2020/03/updates-to-form-controls-and-focus.html

> In addition to improving the default styling, the two teams also tuned up form controls' accessibility and enhanced touch support.

**Comment by liamdebeasi** [comment] 2020-07-08 16:51
I looked into this a bit more, and this appears to be a duplicate of https://github.com/ionic-team/ionic-framework/issues/20632.

When using `routerLink`, Angular forces `tabindex="0"` to the component. There is an open issue on the Angular repo regarding this that we commented on. For more information, please see https://github.com/ionic-team/ionic-framework/issues/20632#issuecomment-592118144.

**Closed by liamdebeasi** 2020-07-08 16:51 UTC
Labels: package: core, type: bug
