### ISSUE TITLE
bug: Swipe back animations on ios do not replicate the native implementation

### ISSUE THREAD

**Issue by milanharia** [ionic-team/ionic-framework#23363] opened 2021-05-25 15:48 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
Currently, when you navigate to a new page on iOS and try to utilise the swipe back gesture to navigate back to the previous page, the animation/gesture does not perform like the standard iOS implementation. Instead it performs similarly to android, where the page instantaneously routes backwards after a small swipe. This can be seen in the attached video below.

**Expected behavior:**
I expect the gesture to perform in the same manner as the native ios implementation where the page swipes back with the user's finger for a more fluid feeling. This navigation is shown working perfectly in the official docs with the ion-nav component (https://ionicframework.com/docs/api/nav), however, this component does not seem to be available to use in React.

**Steps to reproduce:**
For the routing in the app that I showcased in the video I followed the ionic react routing documentation (https://ionicframework.com/docs/react/navigation). See https://stackblitz.com/edit/ionic-react-routing-qegvvf for a similar implementation.

**Other information:**
Current behaviour:

https://user-images.githubusercontent.com/76167627/119528285-f93a3a00-bd78-11eb-8b6e-849ee85f337d.MP4

Expected behaviour:

https://user-images.githubusercontent.com/76167627/119528029-c42de780-bd78-11eb-8d27-e605b526d52c.MP4

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.13.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.6.6

Capacitor:

   Capacitor CLI   : 2.4.7
   @capacitor/core : 2.4.7

Utility:

   cordova-res : not installed
   native-run  : 1.3.0

System:

   NodeJS : v14.15.1 (/usr/local/bin/node)
   npm    : 6.14.8
   OS     : macOS Big Sur


  ─────────────────────────────────────────────────
```

**Comment by liamdebeasi** [comment] 2021-05-25 17:04
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/22342.

**Closed by liamdebeasi** 2021-05-25 17:04 UTC
Labels: triage
