### ISSUE TITLE
bug: ion-datetime emitted undefined if the user is not changed predefined date but just click on Done

### ISSUE THREAD

**Issue by Serg-Mois** [ionic-team/ionic-framework#26612] opened 2023-01-17 16:28 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

see Steps to Reproduce

### Expected Behavior

see Steps to Reproduce

### Steps to Reproduce

Datepicker is opened with the selected current date, you don't change anything and just click on Done. 
Expected result - ionChange/ngModelChange/formControl emitted selected value that was displayed in datepicker on opening. 
Actual result - ionChange/ngModelChange/formControl emitted undefined.  You have to scroll or change predefined value.

<ion-datetime-button datetime="datetime"></ion-datetime-button>

<ion-modal [keepContentsMounted]="true">
  <ng-template>
    <ion-datetime
      (ngModelChange)="valueChanged($event)"
      [(ngModel)]="value"
      presentation="month-year"
      id="datetime"
      [preferWheel]="true"
      [showDefaultButtons]="true"
    >
      <div slot="title">MY TITLE</div>
    </ion-datetime>
  </ng-template>
</ion-modal>

### Code Reproduction URL

https://stackblitz.com/edit/angular-4shiwd-7qhimw?file=src%2Fapp%2Fexample.component.html,src%2Fapp%2Fexample.component.ts

### Ionic Info

    "@ionic/angular": "6.4.1",
    "@ionic/core": "6.4.1"

**Comment by liamdebeasi** [comment] 2023-01-17 20:42
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/25839.

**Closed by liamdebeasi** 2023-01-17 20:42 UTC
Labels: triage

**Comment by saviocamacam** [comment] 2023-01-18 01:20
I think that has another bug related with this issue: when ngModel or FormControlNames are initialized, that value not corresponds with showed value in scroll in year presentation mode.

**Comment by saviocamacam** [comment] 2023-01-18 01:21
When this correction will be launched?
