### ISSUE TITLE
bug: IonList inset=true not working for React

### ISSUE THREAD

**Issue by im-me** [ionic-team/ionic-framework#25096] opened 2022-04-11 09:02 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

When using IonList with the property inset=true, it does not work in React. The list items still look like normal items instead of having the card look.

### Expected Behavior

The items should look like ionCards.

### Steps to Reproduce

Create IonList in react. 
Wrap IonItems within IonItemSliding
Set IonList props inset=true.

Test Output on latest Chrome and Android Emulator.

### Ionic Info

Ionic:

   Ionic CLI       : 6.19.0 (/home/imran/.nvm/versions/node/v16.3.0/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 6.0.11

Capacitor:

   Capacitor CLI      : 3.4.3
   @capacitor/android : 3.4.3
   @capacitor/core    : 3.4.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.5.0

System:

   NodeJS : v16.3.0 (/home/imran/.nvm/versions/node/v16.3.0/bin/node)
   npm    : 8.5.4
   OS     : Linux 5.13

**Comment by amandaesmith3** [comment] 2022-04-13 16:48
Thank you. The `inset` property on `ion-list` only adds margins around the entire list, not individual items. (See: https://ionicframework.com/docs/api/list#inset) For the card look, I would recommend either using the `ion-card` component, or adding CSS margins to the `ion-item`s. You can also remove the bottom border by setting `lines="none"` on each item.

I'm going to close this as not a bug in Ionic. Thanks!

**Closed by amandaesmith3** 2022-04-13 16:48 UTC
Labels: triage
