### ISSUE TITLE
bug: Capacitor compose 1.5 to 1.6

### ISSUE THREAD

**Issue by andretortolano** [ionic-team/ionic-framework#29144] opened 2024-03-12 17:38 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

I have a custom capacitor that under the hood uses compose for rendering views on the android front, everything was working well and fine but if I try to pump up our native library version that brings compose 1.6.x instead of the current 1.5.x, I start seeing a lot of issues, and upon further inspection it seems like its grabbing a bunch of compose*-desktop modules instead of compose*-android ones.

### Expected Behavior

The expected behavior would be to simply update the library and continue using compose in its latest available version

### Steps to Reproduce

1. create project from scratch
2. import androidx.compose.ui:ui:1.6.3 library
3. sync project and run task androidDependencies there will be a bunch of compose*-desktop which is wrong

for testing purposes, if you fall back to 1.5.2 and run androidDependencies again everything looks correct

### Code Reproduction URL

n/a

### Ionic Info

Ionic:

   Ionic CLI       : 7.2.0 (/Users/andret/.nvm/versions/node/v16.20.2/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.9.4

Capacitor:

   Capacitor CLI      : 5.1.1
   @capacitor/android : 5.1.1
   @capacitor/core    : 5.1.1
   @capacitor/ios     : 5.1.1

Utility:

   cordova-res                          : not installed globally
   native-run (update available: 2.0.1) : 1.7.2

System:

   NodeJS : v16.20.2 (/Users/andret/.nvm/versions/node/v16.20.2/bin/node)
   npm    : 8.19.4
   OS     : macOS Unknown

### Additional Information

This update is working on Flutter, I'm not sure who needs to fix this (if this is an issue with Ionic or with the androidx lib) in any case I opened an issue on their end as well.

https://issuetracker.google.com/issues/329138765

[this](https://github.com/appcues/appcues-capacitor-plugin) is the library in question that we provide as a wrapper of our android and ios native implementations

**Comment by liamdebeasi** [comment] 2024-03-12 18:42
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. This repo is for Ionic Framework which only deals with the user interface layer of your application and not any native dependencies. I spoke with the Capacitor team, and Capacitor does not use the compose dependency, so it does not appear to be a Capacitor issue either.

I recommend posting on the [Ionic Forum](https://forum.ionicframework.com) for help debugging this issue. If you are able to point to something inside of Capacitor that is causing this issue, then feel free to create an issue on the [Capacitor repo](https://github.com/ionic-team/capacitor). Let me know if you have any questions!

**Closed by liamdebeasi** 2024-03-12 18:42 UTC
Labels: triage

**Comment by andretortolano** [comment] 2024-03-13 16:01
I agree this is not directly impacted because of the ionic frame work but it looks like there will be eventually a need to include  kotlin gradle plugin for projects just like Flutter does so that androidx components that are built using Kotlin multi-platform (from what I understood) can pick up the proper platform and download the correct packages

https://issuetracker.google.com/issues/328687152

**Comment by liamdebeasi** [comment] 2024-03-13 19:58
In that case I recommend filing feedback on the [Capacitor repo](https://github.com/ionic-team/capacitor) repo. Ionic Framework does not handle the native runtime, so any code modifications would not be made in this repo.
