### ISSUE TITLE
bug: ion-datetime duplicates some months when below a certain year on iOS 14

### ISSUE THREAD

**Issue by denisaSeghedi123** [ionic-team/ionic-framework#24663] opened 2022-01-26 16:30 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Using ion-datetime (ios v12 and v14), for month selector, September is displayed twice.
This issue does not occur for ios v15.

![Screen Shot 2022-01-26 at 6 25 58 PM](https://user-images.githubusercontent.com/72200333/151203984-0476ba21-505c-4d7a-9fa2-99576e161784.png)

### Expected Behavior

display October instead of September twice

### Steps to Reproduce

1. click on month-year dropdown to show the options
2. scroll down on month column options

**Comment by amandaesmith3** [comment] 2022-01-26 21:28
Thanks for the issue. I'm unable to replicate on an iPhone running iOS 14.7.1. Could you create a starter app reproducing the problem and post a link to the repo here? Also, what precise versions of iOS have you tested on so far?

**Comment by denisaSeghedi123** [comment] 2022-01-28 07:20
> Thanks for the issue. I'm unable to replicate on an iPhone running iOS 14.7.1. Could you create a starter app reproducing the problem and post a link to the repo here? Also, what precise versions of iOS have you tested on so far?

I used ios 12.5.4 and ios 14.2

**Comment by denisaSeghedi123** [comment] 2022-01-28 12:25
https://github.com/denisaSeghedi123/ion-datetime-issue

Run the following commands:
- npm install
- npm install -g native-run
- ionic cordova emulate ios (open an iPod touch 7th generation - iOS 14.2)

Steps to reproduce
- Click on Date label (a modal is open)
- Click on arrow icon for month/year
- Scroll down to 1995 (the issue occurs if the year is below 1996)
- Scroll down to September (you’ll see September is displayed twice)

**Comment by amandaesmith3** [comment] 2022-01-31 17:25
Thanks for the extra details! Particularly about the year needing to be below a certain point. I was able to replicate this issue on Xcode Simulator. I was also able to see it in core, meaning it's likely happening in all frameworks, not just Angular.

Interestingly, I see it when the year is at 2006 or earlier, and for me it duplicates March and October. The selected month is also a bit buggy when in this state. [Screencast here.](https://user-images.githubusercontent.com/90629384/151840580-c202fa4f-f08b-40d9-ab2d-2058c0484ae2.mov)

I tried it on 14.2 and 14.3 and replicated both times, even on an iPhone 8. And to summarize from before, I didn't see the issue on my actual iPhone running iOS 14.7.

For context, Ionic v6 doesn't support iOS versions lower than 13: https://ionicframework.com/docs/reference/browser-support

**Comment by realappie** [comment] 2022-02-03 12:11
@amandaesmith3 I missed the iOS 13 support drop in the documentation. We are actually using ionic v6 on iOS 13 without any problems beside the `ion-datetime` right now. Could you elaborate more on the teams motivation of dropping support for iOS13? Is it just some features that ionic v6 doesn't support on iOS 13, or are there other reasons. Thanks👌

**Comment by liamdebeasi** [comment] 2022-02-15 18:48
Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue?

```
npm install @ionic/angular@6.0.8-dev.1644950414.c9ca7ab
```

**Comment by denisaSeghedi123** [comment] 2022-02-16 08:13
@liamdebeasi the issue is partially resolved. On dropdown it looks fine but on calendar-header for October selection, September label is displayed.
<img width="300" alt="Screen Shot 2022-02-16 at 10 13 01 AM" src="https://user-images.githubusercontent.com/72200333/154222889-e5234daf-2c94-4155-b1b9-5ec501f915c4.png">

**Comment by liamdebeasi** [comment] 2022-02-16 19:56
Thanks for testing. Here is a new dev build that should fix that issue:

```
npm install @ionic/angular@6.0.8-dev.1645041087.fc52d96
```

**Comment by denisaSeghedi123** [comment] 2022-02-17 08:33
@liamdebeasi I found a new issue; first month in the dropdown list is December instead of January; before this fix, it worked fine
<img width="294" alt="Screen Shot 2022-02-17 at 10 33 05 AM" src="https://user-images.githubusercontent.com/72200333/154436575-90b8b02e-7dbf-48c5-a078-1d5801af0794.png">

**Comment by liamdebeasi** [comment] 2022-02-17 16:34
Thanks. What is the value of your `ion-datetime` in that screenshot? I cannot reproduce this behavior.

**Comment by liamdebeasi** [comment] 2022-02-22 15:59
Thanks! iOS 14 has some issues with date parsing where it incorrectly takes time zones into account, so that is why these issues keep appearing for certain time zones.

Here is a new dev build that should resolve that issue:

```
npm install @ionic/angular@6.0.8-dev.1645545320.6b18c54
```

**Comment by denisaSeghedi123** [comment] 2022-02-23 08:48
@liamdebeasi Thank you for your promptness and help. It works fine with the last dev build. Please let me know when you have a prod version.
Thanks!

**Comment by liamdebeasi** [comment] 2022-02-23 13:42
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/24792, and a fix will be available in an upcoming release of Ionic Framework.

**Closed** 2022-02-23 13:42 UTC
Labels: package: core, type: bug
