### ISSUE TITLE
bug: Parent click event trigggers sometimes twice when readonly input in element

### ISSUE THREAD

**Issue by hansenchristian** [ionic-team/ionic-framework#28784] opened 2024-01-05 11:55 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When you put a readonly input element in an element like a row, and put a click event listener on the parent element. The click event of the parent is triggered twice from time to time. 

### Expected Behavior

To have a consistent behavior either twice or once. Since Version ~ 17.x.x , this behavior started, before it has been only once.

### Steps to Reproduce

Click on the row items in the example. From time to time the event is triggered twice as seen in the console. 
See example: 
https://stackblitz.com/~/github.com/hansenchristian/angular-gk2xap

### Code Reproduction URL

https://github.com/hansenchristian/angular-gk2xap

### Ionic Info

   @angular-devkit/build-angular : 17.0.7
   @angular-devkit/schematics    : 17.0.7
   @angular/cli                  : 17.0.7

**Comment by liamdebeasi** [comment] 2024-01-05 16:35
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. While I understand this behavior is not desired, we have decided not to suppress this behavior because the browser is doing what it should. Clicking the `<label>` element also dispatches a click on the input element.

https://github.com/ionic-team/ionic-framework/issues/27506#issuecomment-1584805454 has more information on why this behavior is happening. 

I don't know what you are trying to accomplish in your app, but you can use `ionFocus` to detect when the input is focused. You can also use `ionInput` or `ionChange` to detect when the input value changes.

**Closed by liamdebeasi** 2024-01-05 16:35 UTC
Labels: holiday triage
