### ISSUE TITLE
When fab button present at the bottom, bottom part of the page content is not visible

### ISSUE THREAD

**Issue by rajeshwarpatlolla** [ionic-team/ionic-framework#21902] opened 2020-08-09 21:16 UTC
**Ionic version:**
[x] **5.x**

**Current behavior:**

When fab button is present at the bottom of the page, and when u try to scroll the page, the page content at the bottom is covered by the fab button. It is not scrolling till the top of the fab button

**Expected behavior:**

Fab button should not hide the actual content of the page

**Steps to reproduce:**

Add a fab button at the bottom, you will see that the last card is partially covered by the fab button. The user is not able to see weather it's veg item or non veg item in this scenario, which is represented by a square icon with circle at the center.

<img width="378" alt="Screenshot 2020-08-10 at 2 34 22 AM" src="https://user-images.githubusercontent.com/9896335/89741882-965e0780-dab2-11ea-9657-9eb7ef2c0a1d.png">

**Related code:**
```
<ion-fab vertical="bottom" horizontal="end" slot="fixed">
    <ion-fab-button color="success" (click)="createItem()">
      <ion-icon name="add"></ion-icon>
    </ion-fab-button>
</ion-fab>
```
https://stackblitz.com/edit/ionic-fab-tab-open-kjfr47?file=pages%2Fhome%2Fhome.html

**Other information:**

**Ionic info:**
<img width="648" alt="Screenshot 2020-08-10 at 2 36 08 AM" src="https://user-images.githubusercontent.com/9896335/89741877-8e9e6300-dab2-11ea-90f0-b4360f77f462.png">

**Comment by liamdebeasi** [comment] 2020-08-10 13:28
Thanks for the issue. Can you please provide a reproduction of this issue using the latest version of Ionic Framework? Your StackBlitz is using Ionic Framework v3.

Here is a StackBlitz template you can use: https://stackblitz.com/edit/ionic-v4-angular-tabs

**Comment by rajeshwarpatlolla** [comment] 2020-08-10 13:30
I have already added a stackblitz link please check it here https://stackblitz.com/edit/ionic-fab-tab-open-kjfr47?file=pages%2Fhome%2Fhome.html

**Comment by liamdebeasi** [comment] 2020-08-10 13:31
Yes, but it is using Ionic Framework v3, which is no longer being developed. Please create a reproduction using the latest version of Ionic Framework.

**Comment by rajeshwarpatlolla** [comment] 2020-08-10 13:32
It's same issue even with latest version. The issue is not about the version but about the fab button, which is same as in latest version.

**Comment by liamdebeasi** [comment] 2020-08-10 13:36
I understand that, but I need a reproduction on the latest version of the framework in order to fix it.

**Comment by liamdebeasi** [comment] 2020-08-10 18:11
@rajeshwarpatlolla We are a small team, so we ask users to provide code reproductions using the latest version of Ionic Framework. I understand that you can reproduce the bug in Ionic Framework v5, but I am unable to. Please provide a reproduction of the issue using Ionic Framework v5, otherwise I will have to close the issue since I will be unable to fix the issue.

**Comment by rajeshwarpatlolla** [comment] 2020-08-10 18:52
Ok, i created a new version with the link u gave me. Please check it here.

https://stackblitz.com/edit/ionic-v4-angular-tabs-qfjjnn?file=src%2Fapp%2Ftab1%2Ftab1.page.html

If you see the screenshot the content at the bottom right is covered by the fab button.

<img width="520" alt="Screenshot 2020-08-11 at 12 21 25 AM" src="https://user-images.githubusercontent.com/9896335/89819198-a46e5f80-db68-11ea-8cf1-412be267537d.png">

**Comment by indraraj26** [comment] 2020-08-11 12:59
@rajeshwarpatlolla This is not bug, As per UX please add padding-bottom to .scroll-content

**Comment by rajeshwarpatlolla** [comment] 2020-08-11 13:16
There should be standard way right instead of manually doing that. May be additional directive on ion-content, something like <ion-content has-fab-bottom> </ion-content>

**Comment by indraraj26** [comment] 2020-08-11 13:22
No I am not agree with you, It is perfect what ionic is giving. They are already following the standing MD and iOS specs.

**Comment by rajeshwarpatlolla** [comment] 2020-08-11 13:33
Let the ionic team decide that.

**Comment by liamdebeasi** [comment] 2020-08-12 14:23
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. We do not automatically add padding to the bottom of your content because we are unable to reliably guess how developers use FABs in each application. For example, if a FAB is positioned in the top left, it would not make sense for us to add padding since the FAB will never cover the content. Additionally, even if the FAB was placed in the bottom right, there may not be enough content that the FAB covers it. In that instance, adding padding would be incorrect there as well.

We recommend adding the padding yourself. You can do this by adjusting the `--padding-bottom` CSS Variable on `ion-content`: https://ionicframework.com/docs/api/content#css-custom-properties

**Closed by liamdebeasi** 2020-08-12 14:23 UTC
Labels: triage
