### ISSUE TITLE
bug: swipe back while open animation of current page is in progress freezes routing afterwards

### ISSUE THREAD

**Issue by capc0** [ionic-team/ionic-framework#23105] opened 2021-03-26 12:53 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

routing to a subpage and performing a swipe back gesture while the open-animation is still going, leads to a freeze of further routing actions / being unable to route afterwards.

**Expected behavior:**

swipe back should be prevented while the open animation of another page is progress or at least should not cause all routing to fail afterwards.

**Steps to reproduce:**

perform actions mentioned above on iOS device.

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```

Ionic:

   Ionic CLI                     : 6.11.8 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.5.2
   @angular-devkit/build-angular : 0.1102.1
   @angular-devkit/schematics    : 11.2.1
   @angular/cli                  : 11.2.1
   @ionic/angular-toolkit        : 3.0.0

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : ios 6.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 23 other plugins)

Utility:

   cordova-res                          : not installed
   native-run (update available: 1.3.0) : 1.2.2

System:

   ios-deploy : 1.11.2
   ios-sim    : 8.0.2
   NodeJS     : v12.18.4 (/usr/local/bin/node)
   npm        : 6.14.6
   OS         : macOS Catalina
   Xcode      : Xcode 12.4 Build version 12D4e
```

**Comment by capc0** [comment] 2021-03-29 14:21
Reproduction repo is here: https://github.com/capc0/ion-swipe-route-bug

Also I have made a short video to demonstrate the issue.


https://user-images.githubusercontent.com/27284008/112850910-bfb3be00-90aa-11eb-86c1-56a83331ee91.mov

**Comment by liamdebeasi** [comment] 2021-03-29 19:39
Thanks! Looks like this is a duplicate of https://github.com/ionic-team/ionic-framework/issues/15154.

**Closed by liamdebeasi** 2021-03-29 19:39 UTC
Labels: ionitron: needs reproduction
