### ISSUE TITLE
bug: error when using custom events

### ISSUE THREAD

**Issue by farisfaisalthena** [ionic-team/ionic-framework#25232] opened 2022-05-04 02:59 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

When using custom events example `InfiniteScrollCustomEvent`, I will get an error on my IDE as shown below. Please note this happens when I use any custom events such as the refresher custom event etc

<img width="1336" alt="Screenshot 2022-04-27 at 9 16 28 AM" src="https://user-images.githubusercontent.com/61012396/166617458-a157836f-82b8-4a73-bc52-45eb5064428a.png">

### Expected Behavior

When using a custom event, the IDE should not show the error

### Steps to Reproduce

1. Create a fresh Ionic Angular project
2. Enter the following code

In .html
```
<ion-infinite-scroll threshold="100px" (ionInfinite)="loadMore($event)">
          <ion-infinite-scroll-content loadingSpinner="dots" loadingText="Loading More Cosmetics...">
          </ion-infinite-scroll-content>
        </ion-infinite-scroll>
```

In .ts
```
loadMore(ev: InfiniteScrollCustomEvent) {
    this.currentPage.next(this.currentPage.value + 1);

    if (this.currentPage.value === this.maximumPages) {
      ev.target.disabled = true;
    }
  }
```

### Ionic Info

Ionic:

   Ionic CLI                     : 6.19.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.1.3
   @angular-devkit/build-angular : 13.3.4
   @angular-devkit/schematics    : 13.3.4
   @angular/cli                  : 13.3.4
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.5.0
   @capacitor/android : not installed
   @capacitor/core    : 3.5.0
   @capacitor/ios     : 3.5.0

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v16.14.2 (/usr/local/bin/node)
   npm    : 8.5.0
   OS     : macOS Monterey

**Comment by liamdebeasi** [comment] 2022-05-04 15:29
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/24245.

**Closed by liamdebeasi** 2022-05-04 15:29 UTC
Labels: triage
