### ISSUE TITLE
bug: Ion-datetime time picker sometimes initialize with 00:00 and after select new value doesn't trigger IonChange event

### ISSUE THREAD

**Issue by FranciskoNeves** [ionic-team/ionic-framework#24636] opened 2022-01-24 15:08 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

When I open an ion-datetime time picker with a predefined initial value, sometimes, the picker shows 00:00 as the initial value and then I select a value, and ionChange event isn't triggered.

```
<ion-label id="StartTimePicker">{{startDateTime}}</ion-label>


<ion-modal trigger="StartTimePicker" initialBreakpoint="{{timePickerBreakpoint}}">
    <ng-template>
        <ion-content>
            <ion-datetime size="cover" presentation="time" value="{{valueStartTime}}" hour-cycle="h23" showDefaultButtons="true" (ionChange)="changeStartTime($event)" cancelText="{{'cancel' | translate}}" doneText="{{'select' | translate}}"></ion-datetime>
        </ion-content>
    </ng-template>
</ion-modal>
```

### Expected Behavior

Open ion-datetime with the value that we pass into property "value", and after select a new value, trigger ionChange Event

### Steps to Reproduce

First select an hour to change the initial value that we pass to "value" property, and then try to select again a new hour and sometimes the picker will show 00:00 as the initial value.

### Ionic Info

Ionic:

   Ionic CLI                     : 6.18.1 (C:\Users\Francisco.neves\AppData\Roaming\nvm\v16.13.0\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.0.3
   @angular-devkit/build-angular : 12.1.4
   @angular-devkit/schematics    : 13.1.2
   @angular/cli                  : 12.1.4
   @ionic/angular-toolkit        : 4.0.0

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : android 9.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 18 other plugins)

Utility:

   cordova-res : 0.15.4
   native-run  : 1.5.0

System:

   Android SDK Tools : 26.1.1 (C:\Users\Francisco.neves\AppData\Local\Android\Sdk)
   NodeJS            : v16.13.0 (C:\Program Files\nodejs\node.exe)
   npm               : 8.1.0
   OS                : Windows 10

**Comment by FranciskoNeves** [comment] 2022-01-25 11:27
I think the problem is the property initialBreakpoint="{{timePickerBreakpoint}}", because if i remove the property, the time picker works fine

**Comment by amandaesmith3** [comment] 2022-01-26 20:50
Thanks for the issue. The `initialBreakpoint` property is meant to be used with `breakpoints` to set up a [sheet modal](https://ionicframework.com/docs/api/modal#sheet-modal); both are required for that scenario. Assuming that's what you were going for, does the issue persist if you add `breakpoints` to the modal?

If it does, could you create a minimal reproduction in a starter app and post a link to the repo here?

**Comment by FranciskoNeves** [comment] 2022-01-27 10:50
Yes, the issue persist but less frequently.
Setting initialBreakpoints and breakpoints properties creates a sheet modal, but that's not what I want, because I need a modal with a fixed size to fit the ion-datetime time picker and without the bounce effect of the sheet modal.

**Comment by FranciskoNeves** [comment] 2022-01-27 10:57
I already solved the problem with CSS, but I thought that breakpoints will work to set a fixed heith of the modal.

I leave here my solution to define the modal height in different platforms:

In global.scss :
```
.ios{
    ion-modal.time-picker::part(content){
      height: 33vh;
      position: absolute;
      bottom: 0;
    }

    ion-modal.date-picker::part(content){
      height: 45vh;
      position: absolute;
      bottom: 0;
    }
}

.md{
    ion-modal.time-picker::part(content){
      height: 35vh;
      position: absolute;
      bottom: 0;
    }
  
    ion-modal.date-picker::part(content){
      height: 55vh;
      position: absolute;
      bottom: 0;
    }
}
```

**Comment by amandaesmith3** [comment] 2022-01-27 14:59
Glad to hear you were able to get your app fixed! Yeah, `initialBreakpoint` is only for sheet modals. I acknowledge your actual problem is resolved, but it sounds like there might be a bug with sheet modals interacting with `ion-datetime`. I want to take a look at that if possible; could I ask you to create a starter app minimally reproducing the issue?

**Comment by FranciskoNeves** [comment] 2022-01-27 17:41
I created a blank project and the issue continue to happen, but in stackBlitz the error doens't occur... but I leave here the code anyway.

Here it is: https://stackblitz.com/edit/ionic-angular-v5-bynp6v?file=src%2Fapp%2Fapp.component.html

**Comment by amandaesmith3** [comment] 2022-01-27 19:53
Does the issue happen when running the project locally, outside of Stackblitz? Would you be able to upload the project to Github and post a link to the repo, if so?

**Comment by FranciskoNeves** [comment] 2022-01-28 10:24
Well, now I can't replicate the issue locally, I don't know if it was the 6.0.4 version of Ionic or not, but I can't reproduce the issue. If it happen again i will report with a git repo

**Comment by amandaesmith3** [comment] 2022-01-28 14:44
Got it. In that case, I'm going to go ahead and close this out since things are looking good on your end. If you're ever able to reproduce on the latest version of Ionic, let me know here and I'll have a look. Thanks for using Ionic!

**Closed by amandaesmith3** 2022-01-28 14:44 UTC
Labels: ionitron: needs reproduction
