### ISSUE TITLE
feat: Search feature for vue ion-select

### ISSUE THREAD

**Issue by ZoreAnkit** [ionic-team/ionic-framework#24311] opened 2021-12-03 10:27 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Search feature in ion-select for vue framework. It would be helpful if we have ion-searchbar inside select like we have action sheets and pop-over. 

Its difficult to find item if we have huge list. Something like this [https://www.npmjs.com/package/ionic-selectable](url) this package is for angular and vanilla js.

### Describe the Use Case

Searching items in ion-select. 

### Describe Alternatives

[https://www.npmjs.com/package/ionic-selectable](url)

**Comment by liamdebeasi** [comment] 2021-12-03 14:10
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/23799.

**Closed by liamdebeasi** 2021-12-03 14:10 UTC
Labels: triage
