### ISSUE TITLE
bug: tap click utility should improve visual responsivness

### ISSUE THREAD

**Issue by BerkeAras** [ionic-team/ionic-framework#23691] opened 2021-07-26 12:49 UTC
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

Clicking a IonButton causes a small delay (see video). This behavior does not feel native.

### Expected Behavior

No delay after clicking buttons.

### Steps to Reproduce

Just create a button, press it, see issue.

### Ionic Info

```md
Ionic:

   Ionic CLI       : 6.16.3 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.6.12

Capacitor:

   Capacitor CLI      : 3.0.0
   @capacitor/android : not installed
   @capacitor/core    : 3.0.0
   @capacitor/ios     : 3.1.2

Utility:

   cordova-res                          : not installed globally
   native-run (update available: 1.4.0) : 1.3.0

System:

   NodeJS : v14.17.0 (/usr/local/bin/node)
   npm    : 6.14.13
   OS     : macOS Big Sur
```

### Additional Information

https://user-images.githubusercontent.com/36629890/126991261-deeb5782-fd4e-4877-aabb-501e294ecb34.mp4

_**I pressed the button as fast as I could and immediately released it. The "active" state keeps for a few milliseconds.**_

**Comment by liamdebeasi** [comment] 2021-07-26 12:50
Thanks for the issue. Can you create a code reproduction of the issue?

**Comment by BerkeAras** [comment] 2021-07-26 12:51
> Thanks for the issue. Can you create a code reproduction of the issue?

Sure. I'm on it.

**Comment by BerkeAras** [comment] 2021-07-26 13:02
@liamdebeasi

https://github.com/BerkeAras/ionic-button-delay-issue

see the video: The button at the bottom is a native `<button>` component. It turns yellow on active.


https://user-images.githubusercontent.com/36629890/126992969-d66c7de9-f5d7-4a2f-a26f-bc71451a48f1.mp4

**Comment by BerkeAras** [comment] 2021-07-28 13:08
@liamdebeasi Did you see my reproduction? https://github.com/BerkeAras/ionic-button-delay-issue

**Comment by liamdebeasi** [comment] 2021-08-02 17:57
Yes. I have been out of the office for several days and am getting caught up. I will try to take a look later this week.

**Comment by liamdebeasi** [comment] 2021-08-10 13:42
Not really sure what I am looking at here. Can you provide some additional context?

**Comment by BerkeAras** [comment] 2021-08-10 13:44
@liamdebeasi Thanks for your reply. In the repo I provided, you can see the issue by clicking the buttons very fast. The three ion-buttons are unfocusing after a small delay. The 4th button (native button-component) has no delay.

See the video above.

**Comment by liamdebeasi** [comment] 2021-08-10 14:04
It's likely this code: https://github.com/ionic-team/ionic-framework/blob/7315e0157b917d2e3586c64f8082026827812943/core/src/utils/tap-click.ts#L131-L139

As a test, you can add the `ion-activatable-instant` class to an `ion-button` and the issue should go away.

**Comment by liamdebeasi** [comment] 2021-08-10 14:06
Is this throttling any click events or otherwise causing problems in any apps you have?

**Comment by BerkeAras** [comment] 2021-08-10 14:07
> Is this throttling any click events or otherwise causing problems in any apps you have?

I created a keypad, and typing fast is very bad :(

**Comment by liamdebeasi** [comment] 2021-08-10 14:09
Can you clarify what that means? Are click events being dropped?

**Comment by BerkeAras** [comment] 2021-08-10 14:09
> It's likely this code:
> 
> https://github.com/ionic-team/ionic-framework/blob/7315e0157b917d2e3586c64f8082026827812943/core/src/utils/tap-click.ts#L131-L139
> 
> As a test, you can add the `ion-activatable-instant` class to an `ion-button` and the issue should go away.

Works, thanks 😁 But what is the reason, you created this delay?

**Comment by BerkeAras** [comment] 2021-08-10 14:10
> Can you clarify what that means? Are click events being dropped?

On the keypad, if you click multiple times the same button a few events were dropped.

**Comment by sudoritz** [comment] 2021-12-24 17:58
This issue is also showing up in our ionic app. We press buttons quicky as they are DTMF buttons for a we dialer so we can see issue very quickly.

**Comment by sudoGenie** [comment] 2021-12-24 18:10
Actually i forgot to mention there is audio delay when pressing a buttons quiciky it misses and doesn't show instant sound feedback as if i press 1 and then 2 2 you dont hear the audio of 2 2 fast its delays. not sure if this would be our answer.

>  ion-activatable-instant class to an ion-button and the issue should go away.

**Comment by sudoGenie** [comment] 2021-12-27 17:09
> It looks like the `setTimeout` was originally added to avoid layout thrashing, but today we can use `writeTask` in Stencil.
> 
> This utility was originally added ~6 years ago for Ionic v3: https://github.com/ionic-team/ionic-v3/blame/8f76057147e50acec99e21451f877f5cce4a0db6/ionic/components/tap-click/activator.ts
> 
> It went through many iterations from using requestAnimationFrame, to using FastDOM, then to using a setTimeout. I am open to creating a patch which uses a `writeTask` instead of a 200ms `setTimeout`. That should improve the visual responsiveness while avoiding any layout thrashing.

@liamdebeasi 

Would this work when your pressing buttons thta produce sound clicks (DTMF phone dialer) (its very slow and skips so im hoping this would work)

**Comment by sudoGenie** [comment] 2023-01-19 01:28
> It looks like the `setTimeout` was originally added to avoid layout thrashing, but today we can use `writeTask` in Stencil.
> 
> This utility was originally added ~6 years ago for Ionic v3: https://github.com/ionic-team/ionic-v3/blame/8f76057147e50acec99e21451f877f5cce4a0db6/ionic/components/tap-click/activator.ts
> 
> It went through many iterations from using requestAnimationFrame, to using FastDOM, then to using a setTimeout. I am open to creating a patch which uses a `writeTask` instead of a 200ms `setTimeout`. That should improve the visual responsiveness while avoiding any layout thrashing.

Would this resolve why pressing buttons the audio feedback on the short sound is so slow causing

**Comment by liamdebeasi** [comment] 2023-01-19 18:01
Ionic does not handle audio playback, so the issue is likely not with Ionic Framework. I recommend posting on the [Ionic Forums](https://forum.ionicframework.com/) for help debugging this issue.

**Comment by liamdebeasi** [comment] 2023-02-07 21:36
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/26741. This should be available in the next Ionic 7 beta.

The delay for when the activated class is added has been reduced from `200ms` to `100ms`. The delay for when the activated class is removed has been reduced from `200ms` to `150ms`. (Note: We cannot lower the 150 anymore because that interferes with the shadow animation on certain MD components such as `ion-fab-button` and `ion-button`)

**Closed by liamdebeasi** 2023-02-07 21:36 UTC
Labels: package: core, type: bug
