### ISSUE TITLE
bug: Ion Popover renders outside screen when the trigger is too low.

### ISSUE THREAD

**Issue by distante** [ionic-team/ionic-framework#24870] opened 2022-03-03 12:12 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Then opening an ion-popover using a trigger, If the trigger is just above the window limit, the ion-popover do not fix his position
<img width="438" alt="image" src="https://user-images.githubusercontent.com/5490201/156561060-03c6e89f-e254-41c4-a5fe-8b8ede896635.png">

### Expected Behavior

The popover should be opened above the trigger if no space below exists:
<img width="423" alt="image" src="https://user-images.githubusercontent.com/5490201/156561672-e5809447-1b0b-4008-927c-e1cb6d8ce45a.png">
 (I moved manually that popover)

### Steps to Reproduce

Create a list with popover triggers, so one of the items is almost at the end of the screen.
Trigger the popover with the last item.

### Code Reproduction URL

https://github.com/distante/ionic-capacitor-errors

### Ionic Info

Ionic:

   Ionic CLI                     : 6.18.1 
   Ionic Framework               : @ionic/angular 6.0.10 
   @angular-devkit/build-angular : 13.2.0 
   @angular-devkit/schematics    : 13.2.0 
   @angular/cli                  : 13.2.0 
   @ionic/angular-toolkit        : not installed

Capacitor:

   Capacitor CLI      : 3.4.1
   @capacitor/android : 3.4.1
   @capacitor/core    : 3.4.1 
   @capacitor/ios     : 3.4.1

Utility:

   cordova-res : 0.15.4
   native-run  : not installed globally

System:

   NodeJS : v16.13.1 (/Users/saninn/.nvm/versions/node/v16.13.1/bin/node)
   npm    : 8.1.2
   OS     : macOS Monterey

**Comment by Pijuli** [comment] 2022-03-15 09:21
Same here.

I can't see a way of, at least, centering the popover to the middle of the screen.

![image](https://user-images.githubusercontent.com/1220004/158346179-5f84b624-e616-4ad5-81b4-c2811b95f6b5.png)
![image](https://user-images.githubusercontent.com/1220004/158346238-d9542d0c-601f-4527-8103-333b4a32069f.png)

**Comment by MortenGregersen** [comment] 2022-03-15 22:57
Same here
<img width="289" alt="CleanShot 2022-03-15 at 23 57 02@2x" src="https://user-images.githubusercontent.com/759680/158485806-9844fd4d-87b9-44de-a3d7-297c1389a206.png">

**Comment by liamdebeasi** [comment] 2022-03-16 13:34
Hi everyone,

Can someone please provide a GitHub repo that we can use to verify this issue? If we cannot reproduce the issue, we cannot fix it.

**Comment by roblouie** [comment] 2022-03-16 23:16
I was actually just commenting on the discord about this. I can tell you what the exact issue is.

When creating an inline popover, that popover's contents are not rendered into the slot until the popover is rendered. This causes popover.js to see a content height of 0, rendering your content below where it should be.

![image](https://user-images.githubusercontent.com/5448110/158706256-3370d3cb-7ad8-4aa9-ae29-9badc39f3f52.png)

The reason it's zero here is that the slot is empty, as it's contents are not yet rendered:
![image](https://user-images.githubusercontent.com/5448110/158706402-88c598f7-c1fd-4c06-8990-e95b3b644fb4.png)

This breaks the positioning. If you set a height via the css shadow part, you can fix this:
```
ion-popover {
  --height: {{ popoverHeight }}px
}
```

If you do that the popover opens above its trigger as expected. If you have a popover with dynamic height....ya you have a problem. I hacked this fix in in my Vue app:
```
<component v-bind:is="'style'" v-if="isOpen">
  ion-popover {
    --height: {{ items.length * itemHeight }}px
  }
</component>
```

But ya, not ideal. 

In order to fix this, there should be an option for inline popovers to render their contents into the dom. I don't see a way to fix this without that.

**Comment by roblouie** [comment] 2022-03-17 00:09
Update, here is an example demonstrating the behavior on github: https://github.com/roblouie/popoverTest

Another interesting thing is that I found an arguably less sketchy fix:
```
components: {
  IonPopover, // You can actually fix the issue by deleting this line. This stop the vue component from being used
},
 ```

Seems like if I remove this, I use the basic web component version, which as the docs state do in fact render their contents to the dom. Whether you do this or set the height on the shadow part, you can work around the issue, but it's definitely a bug.

**Comment by distante** [comment] 2022-03-17 09:27
> Hi everyone,
> 
> Can someone please provide a GitHub repo that we can use to verify this issue? If we cannot reproduce the issue, we cannot fix it.

Here a reproduction with ionic/angular https://github.com/distante/ionic-capacitor-errors

**Comment by liamdebeasi** [comment] 2022-03-22 13:07
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/24780.

**Closed by liamdebeasi** 2022-03-22 13:07 UTC
Labels: triage

**Comment by distante** [comment] 2022-03-22 13:10
> Thanks for the issue. I am going to close this as a duplicate of #24780.

Ok but my reproduction does not have anything to do with the date picker

**Comment by liamdebeasi** [comment] 2022-03-22 13:19
The underlying issue is the same. I have updated the issue to more accurately reflect the issue.
