### ISSUE TITLE
bug: iOS Modal Drag Animation  Glitches

### ISSUE THREAD

**Issue by robinrobinrobinrobin** [ionic-team/ionic-framework#29369] opened 2024-04-21 14:36 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v8.x

### Current Behavior

When swiping to close the iOS Card Modal it snaps to the top for a split second. Resulting in a glitchy swipe animation. (See the attached video)

https://github.com/ionic-team/ionic-framework/assets/39830658/d4f7dd7a-c516-42fb-8184-8d9d37329e3a

### Expected Behavior

The iOS Card Modal should be as smooth in Safari (iOS and MacOS) as it is on Chrome or other browsers.

### Steps to Reproduce

- Go to any Ionic Card Modal on iOS or Safari (iOS/MacOS) (I also attached a Stackblitz URL)
- Swipe the card down about 1/3 so it doesn't close but travels up again.
- Observe how the card animation glitches at the top of the screen.

### Code Reproduction URL

https://stackblitz.com/edit/z89fp8?file=package.json

### Ionic Info

Ionic:

   Ionic CLI       : 7.1.1 (/opt/homebrew/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 8.0.0

Capacitor:

   Capacitor CLI      : 6.0.0
   @capacitor/android : not installed
   @capacitor/core    : 6.0.0
   @capacitor/ios     : 6.0.0

Utility:

   cordova-res : not installed globally
   native-run  : 2.0.1

System:

   NodeJS : v18.19.0 (/usr/local/bin/node)
   npm    : 10.2.3
   OS     : macOS Unknown

**Comment by EinfachHans** [comment] 2024-04-21 15:14
Probably duplicate of #28467

While this ticket is closed, the fix will be included in upcoming ios 17.5, which is not published yet

**Comment by liamdebeasi** [comment] 2024-04-22 14:00
Thanks for the issue. I am going to close this as a duplicate of #28467. This is a WebKit bug this will be fixed in the upcoming iOS 17.5 release.

**Closed by liamdebeasi** 2024-04-22 14:00 UTC
Labels: triage
