### ISSUE TITLE
bug: Ion input not binding value to the state instead binding to what's been entered.

### ISSUE THREAD

**Issue by Richa-Singh-1** [ionic-team/ionic-framework#22868] opened 2021-02-04 04:50 UTC
# Bug Report

**Ionic version:**
[x] 5.x

**Current behavior:**
For ion input value in input tag is shown based on what is entered(event.target.value) instead of what's been set through value binding via state.
Video : https://drive.google.com/file/d/1CHxSKay65hKG--5yWN-6yXa7FzYkv5L0/view?usp=sharing

**Expected behavior:**
Value should be shown based on what's been set through state .

**Steps to reproduce:**
Please run below commands in  the project :https://github.com/Richa-Singh-1/IonInput-Issue
npm i
npm run start

**Related code:**

```
const App: React.FC = () => {
  const [input, setInput] = useState('');

  const handleInputChange = (val) => {
    console.log(' even.detail.value  ', val);
    const input = val.replace(/\D/g, "");
    console.log('input  ', input);
    setInput(input);
  }
  return (
    <IonApp>
      <IonPage>
        <IonItem>
          <IonInput
            inputmode="numeric"
            maxlength={3}
            value={input}
            placeholder="Enter Input"
            onIonChange={e => handleInputChange(e.detail.value)}>
          </IonInput>

        </IonItem>
      </IonPage>
    </IonApp>
  );
};
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.12.3 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.4.0

Capacitor:

   Capacitor CLI   : 2.4.2
   @capacitor/core : 2.4.2

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.19.0 (/usr/local/bin/node)
   npm    : 6.14.8
   OS     : macOS Catalina
```

**Comment by liamdebeasi** [comment] 2021-02-04 17:01
Thanks for the issue. Can you please double check that your repo is set to public? I cannot access it.

**Comment by Richa-Singh-1** [comment] 2021-02-05 03:44
@liamdebeasi  updated

**Comment by Richa-Singh-1** [comment] 2021-02-10 16:44
@liamdebeasi any updates on the issue?

**Comment by amitkharka** [comment] 2021-02-22 08:41
I'm also facing the same issue. Looks like Stencil **input** components is not behaving as expected.  
https://github.com/ionic-team/ionic-framework/blob/master/core/src/components/input/input.tsx

**Comment by dtarnawsky** [comment] 2021-06-07 19:41
I've created a repo that displays the difference in behavior between what is desired with "input" with what is happening with "ion-input": [https://github.com/dtarnawsky/react-input-vs-ion-input](https://github.com/dtarnawsky/react-input-vs-ion-input)

**Comment by liamdebeasi** [comment] 2021-07-09 20:28
Thanks for the issue. I can reproduce this behavior and while the components are behaving as intended, I agree that the behavior in this scenario is not ideal.

With Ionic React, there are two layers of components: The `ion-input` Web Component and the React component that wraps the Web Component. When you type into `ion-input`, this causes the `value` property on the Web Component to update and `ionChange` to emit.

Taking the reproduction in https://github.com/ionic-team/ionic-framework/issues/22868#issuecomment-856205430 as an example, say you have an input that wants to filter out non-numeric characters.

If you type in `12`, the `value` property in the Web Component is set to `12`, and `ionChange` fires. When `ionChange` fires, the `handleInputChange` function is invoked in the React app, and the application uses the `useState` callback to set the `value` property on the React component. This causes the React component to re-render since the `value` property on the React component has changed.

Now, when you type `b`, the Web Component `value` property is set to `12b` and `ionChange` fires. The `handleInputChange` function is invoked, and the function code filters out the `b`. However, the "filtered" value is `12` which is exactly the same as what it was before we typed the `b`. So when we go to call the `useState` callback and set the `value` property on the React component, the React component does not re-render because the `value` property has not changed. As a result, the underlying Web Component does not get the updated `value`, and the component still shows `12b` in the DOM.

-----

In terms of a temporary workaround you can use the `useState` callback to set the `value` property to the "unfiltered" value and then set it to the "filtered" value immediately after, forcing the React component to re-render.

-----

I need to do some research here on what the appropriate solution is, but I will update this thread when I have more information.

**Comment by liamdebeasi** [comment] 2021-07-09 21:16
So in theory this also impacts React components that just wrap a native `input` element, but React seems to have a special `trackValueOnNode` function that lets it keep the `input` in sync even if the component props do not update (assuming you are using `useState`): https://github.com/facebook/react/blob/cae635054e17a6f107a39d328649137b83f25972/packages/react-dom/src/client/inputValueTracking.js#L51

React does this for other elements such as `textarea` too, but React only sees `ion-input` initially, so it does not call `trackValueOnNode`.

One idea I am going to investigate is if there is a way to customize this so the underlying `track` function can be called on `ion-input` and `ion-textarea`.

**Comment by eric-horodyski** [comment] 2021-08-11 18:37
A similar issue can occur using Ionic Framework Angular. Please see the following repro for an example of how to demonstrate this behavior: https://github.com/eric-horodyski/fw-ng-input-filtering

**Comment by sean-perkins** [comment] 2022-03-14 17:43
Can someone experiencing this issue in a React project, test with this dev build: `6.0.10-dev.11646429436.2d71c72`? 

You can also optionally use this demo reproduction: https://github.com/sean-perkins/react-capture-phase-demo (`pr` branch includes the fix version)

In the demo, you can see the behavior between a standard HTML form using useState as well as with react-hook-form. I also showcase the difference in behavior between mutating a control's value in the ionChange event vs. ionInput event. My recommendation is that developers use ionInput for these mutations, as you will see the key is briefly painted prior to the value being set & re-rendered.

**Comment by cainaf** [comment] 2022-12-09 19:38
Confirming this still happens in Ionic 6

**Comment by liamdebeasi** [comment] 2023-02-22 22:04
Hi everyone,

I appreciate your patience as we worked to resolve this issue. The team has investigated, and we have determined that this is not a bug in Ionic Framework. I have provided an explanation below as well as how developers can work around this behavior in their applications.

We have also provided a playground with a live demo (and working code) for the workaround: https://ionicframework.com/docs/api/input#filtering-user-input

<details><summary>Why is this not a bug in Ionic React?</summary>
<p>

The main issue here is the state of the React component is out of sync with the states of the Web Component and the native `input` element. This behavior impacts any React component that uses `useState` to set the value of a native `<input />` element, including apps not built with Ionic.

React has a special utility calls trackValueOnNode that avoids this behavior by ensuring the React component and native input states are kept in sync: [react/inputValueTracking.js at cae635054e17a6f107a39d328649137b83f25972 · facebook/react](https://github.com/facebook/react/blob/cae635054e17a6f107a39d328649137b83f25972/packages/react-dom/src/client/inputValueTracking.js#L51)

One restriction with this is that the native `input` element must be rendered within the React context to take advantage of this utility. While `ion-input` is rendered inside of the React context, the native `input` element inside of `ion-input` is not. As a result, the Ionic component still has this undesirable behavior.

**Example**

To get a better understanding of how the React component state gets out of sync, I will walk through an example. This example can also be found in the reproduction in https://github.com/ionic-team/ionic-framework/issues/22868#issuecomment-856205430.

The example uses an `ionInput` listener to remove any non-numeric characters from the text input. This callback uses `useState` to update the state of the React component with the modified value. This value is then passed down to the Web Component and the native input element:

```jsx
const [input, setInput] = useState('');

...

const handleInputChange = (val) => {
  const input = val.replace(/\\D/g, "");
  setInput(input);
}

...

<IonInput
  value={input}
  onIonInput={(e: any) => handleInputChange(e.target.value)}>
</IonInput>
```

1. Input initializes with a value of `''`. The native input, `ion-input` Web Component, and `IonInput` React  component wrapper all have a value of `''`.

2. User types `1`:

| | state before `ionInput` callback runs | state after `ionInput` callback runs |
| - | - | - |
| native `input` | `1` | `1` |
| `ion-input` Web Component | `1` | `1` |
| `IonInput` React component | `''` | `1` |

3. User types `2`:

| | state before `ionInput` callback runs | state after `ionInput` callback runs |
| - | - | - |
| native `input` | `12` | `12` |
| `ion-input` Web Component | `12` | `12` |
| `IonInput` React component | `1` | `12` |

4. User types `b`:

| | state before `ionInput` callback runs | state after `ionInput` callback runs |
| - | - | - |
| native `input` | `12b` | `12b` |
| `ion-input` Web Component | `12b` | `12b` |
| `IonInput` React component | `12` | `12` |

The `ionInput` callback fires and the state of the React component is set to `12` again since the `b` was removed. However, the previous state of the React component was also `12` so the React component does not re-render. Since it does not re-render, the value of `12` is not passed down to the Web Component and the native input element. This results in the reported behavior.
</p>
</details>

<details><summary>Why are we not re-implementing the `trackValueOnNode` workaround in Ionic React?</summary>
<p>

We think that implementing this workaround inside of Ionic will lead to brittle and error-prone code and ultimately degrade the stability of Ionic Framework. It's unfortunate that Ionic components are unable to take advantage of this `trackValueOnNode` workaround in React to improve the developer experience, but Ionic's components are working as intended here.
</p>
</details>

<details><summary>Why is this not a bug in Ionic Angular?</summary>
<p>

The reported behavior can be reproduced outside of Ionic using an `<input />` in a regular Angular application. A similar issue was reported to the Angular team, and they said that Angular was working as intended here: https://github.com/angular/angular/issues/44252#issuecomment-985560222

</p>
</details>

<details><summary>Why is this not a bug in Ionic Vue?</summary>
<p>

The reported behavior can be reproduced outside of Ionic using an `<input />` in a regular Vue application. While this behavior may seem confusing, the state variable is not changing so Vue should not re-render the component.

</p>
</details>

<details><summary>How do I implement this workaround in React?</summary>
<p>

Developers will need to update the `ion-input` component in their `ionInput` callback:

```jsx
const [modelValue, setModelValue] = useState('');
const inputEl = useRef<HTMLIonInputElement>(null);

const handleIonInputChange = async (val) => {
  const input = val.replace(/\D/g, "");

  setModelValue(input); 
  
  const ionInputEl = inputEl.current;
  if (ionInputEl) {
    ionInputEl.value = input;
  }
}

...


return (
  <IonInput
    ref={inputEl}
    value={modelValue}
    onIonInput={(e: any) => handleIonInputChange(e.target.value)}>
  </IonInput>
);
```

The important part is `ionInputEl.value = input;` where we update the DOM with the correct value.
</p>
</details>

<details><summary>How do I implement this workaround in Angular?</summary>
<p>

```html
<ion-input
  [value]="modelValue" 
  (ionInput)="onInput($event)" 
  #ionInput
></ion-input>
```

```ts
@ViewChild('ionInput', { static: true }) ionInput!: IonInput;

modelValue = '';

constructor() {}

onInput(ev) {
  const value = ev.target!.value;

  const input = value.replace(/\D/g, "");

  this.modelValue = this.ionInput.value = input;
}
```

The important part here is `this.modelValue = this.ionInput.value = input;` where we update the `modelValue` variable as well as the native input itself. This allows the DOM to be kept in sync.
</p>
</details>

<details><summary>How do I implement this workaround in Vue?</summary>
<p>

```html
<template>
  <ion-input
    ref="ionInputEl" 
    :value="modelValue" 
    @ionInput="ionicChange"
  ></ion-input>
</template>

<script>
...

const ionInputEl = ref();
const modelValue = ref('');

const ionicChange = (ev) => {
  const value = ev.target.value.replace(/\D/g, "");
  
  modelValue.value = value;
    
  const inputEl = ionInputEl.value;
  if (inputEl !== undefined) {
    inputEl.$el.value = value;
  }  
}
</script>
```

The important part is `inputEl.$el.value = value;` where we update the DOM node with the correct value.

</p>
</details>

-----

I am going to close this issue since it is not a bug in Ionic, but let me know if there are any questions. Thanks!

**Closed by liamdebeasi** 2023-02-22 22:04 UTC
Labels: type: bug
