### ISSUE TITLE
bug: ion-datetime min / max properties broken for a 2020 time

### ISSUE THREAD

**Issue by cguy** [ionic-team/ionic-framework#22968] opened 2021-02-24 15:38 UTC
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
With a time from a date in 2020. min & max properties are ignored.

**Expected behavior:**
min & max properties should not be ignored for a datetime in 2020.

**Steps to reproduce:**

This example works (cannot select before 08:00 and after 14:00)
```
    <ion-datetime
        required="true"
        displayFormat="HH:mm"
        name="dateArrivee"
        value="2021-02-25T10:00:00.000Z"
        min="2021-02-25T08:00:00.000Z"
        max="2021-02-25T14:00:00.000Z"
        minuteValues="0,15,30,45"
        display-timezone="utc">
    </ion-datetime>
```

This example doesn't work (empty columns)
```
    <ion-datetime
        required="true"
        displayFormat="HH:mm"
        name="dateArrivee"
        value="2020-12-04T10:00:00.000Z"
        min="2020-12-04T08:00:00.000Z"
        max="2020-12-04T14:00:00.000Z"
        minuteValues="0,15,30,45"
        display-timezone="utc">
    </ion-datetime>
```

This example doesn't work (can select before 08:00)
```
    <ion-datetime
        required="true"
        displayFormat="HH:mm"
        name="dateArrivee"
        value="2020-12-04T10:00:00.000Z"
        min="2020-12-04T08:00:00.000Z"
        minuteValues="0,15,30,45"
        display-timezone="utc">
    </ion-datetime>
```

**Related code:**

StackBlitz (https://stackblitz.com/edit/ionic-5-datetime-bug?file=src/app/app.component.html)

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.13.1
   Ionic Framework               : @ionic/angular 5.5.4
   @angular-devkit/build-angular : 0.1102.1
   @angular-devkit/schematics    : 11.2.1
   @angular/cli                  : 11.2.1
   @ionic/angular-toolkit        : 3.1.0

Capacitor:

   Capacitor CLI   : 2.4.6
   @capacitor/core : 2.4.6

Utility:

   cordova-res : 0.15.3
   native-run  : not installed

System:

   NodeJS : v14.16.0 (C:\Users\c.guy\AppData\Local\Temp\fnm_multishell_11960_1614170904424\node.exe)
   npm    : 6.14.11
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment] 2021-02-24 22:04
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/22056. Datetime issues are being tracked here https://github.com/ionic-team/ionic-framework/issues/16630 (I have added yours to it)

**Closed by liamdebeasi** 2021-02-24 22:04 UTC
Labels: triage
