### ISSUE TITLE
bug: ionBlur and ionFocus doing opposite actions than intended in ion-select with "mutliple" attribute

### ISSUE THREAD

**Issue by Chidexprince** [ionic-team/ionic-framework#22929] opened 2021-02-16 10:00 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

ion-blur: emitted when the select gained focus
ion-focus: emitted when the select lost focus

**Expected behavior:**

ion-Blur : should be emitted when the select loses focus.
ion-focus: should be emitted when the select gains focus
**Steps to reproduce:**

**Related code:**
HTML
<ion-select  (ionBlur)="runOnBlur()" multiple="true" placeholder="Select One">
      <ion-select-option value="brown">Brown</ion-select-option>
      <ion-select-option value="blonde">Blonde</ion-select-option>
      <ion-select-option value="black">Black</ion-select-option>
      <ion-select-option value="red">Red</ion-select-option>
 </ion-select>

<ion-select  (ionFocus)="runOnFocus()" multiple="true" placeholder="Select One">
      <ion-select-option value="brown">Brown</ion-select-option>
      <ion-select-option value="blonde">Blonde</ion-select-option>
      <ion-select-option value="black">Black</ion-select-option>
      <ion-select-option value="red">Red</ion-select-option>
 </ion-select>
TS
public runOnBlur(){
console.log("I am blur")
}

public runOnFocus(){
console.log("I am focus")
}

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment] 2021-02-16 15:03
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/22928.

**Closed by liamdebeasi** 2021-02-16 15:03 UTC
Labels: triage
