### ISSUE TITLE
bug: Ion-datetime :Not able to customise calendar 

### ISSUE THREAD

**Issue by surabhiBh** [ionic-team/ionic-framework#25111] opened 2022-04-13 11:12 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

 Ion-datetime does not accept custom font-size, font family. Not able to give separate colours to arrow icons and selected date. not able to customise picker highlight background colour.

### Expected Behavior

able to customise picker highlight background colour
Should accept custom font-size, font family
Allow separate colours to arrow icons and selected date.

### Steps to Reproduce

Open the official demo, try changing the font-size using custom css.

### Code Reproduction URL

https://ionicframework.com/docs/api/datetime

### Ionic Info

Using Ionic version 6

**Comment by liamdebeasi** [comment] 2022-04-13 12:54
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/24158.

**Closed by liamdebeasi** 2022-04-13 12:54 UTC
Labels: triage
