### ISSUE TITLE
bug: Image inside header is layzloaded after page transition

### ISSUE THREAD

**Issue by danielsogl** [ionic-team/ionic-framework#18881] opened 2019-07-24 16:28 UTC
# Bug Report

I have placed an image inside the `ioni-title` tag. When I navigate from page a to page b, the image is `layzloaded` at about a second after the transition animation stops.

![](https://media.giphy.com/media/J3R1j6qRZVTmiEZsuE/giphy.gif)

**Ionic version:**
[x] **4.6.2**

**Current behavior:**
Image is flickering after transition

**Expected behavior:**
The image should be shown immediately

**Steps to reproduce:**
Place a logo inside the ionic header.

**Related code:**
```html
<ion-header>
  <ion-toolbar>
    <ion-buttons slot="start">
      <ion-back-button></ion-back-button>
    </ion-buttons>
    <ion-title slot="start">
      <img src="assets/logo.svg" />
    </ion-title>
  </ion-toolbar>
  <div><app-fixed-heading [text]="title"></app-fixed-heading></div>
</ion-header>
```

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.3 (/Users/danielsogl/.nvm/versions/node/v12.4.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.6.2
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Capacitor:

   Capacitor CLI   : 1.1.1
   @capacitor/core : 1.1.1

Utility:

   cordova-res : 0.3.0 (update available: 0.6.0)
   native-run  : 0.2.8 

System:

   NodeJS : v12.4.0 (/Users/danielsogl/.nvm/versions/node/v12.4.0/bin/node)
   npm    : 6.10.1
   OS     : macOS Mojave```

**Comment by liamdebeasi** [comment] 2021-09-16 14:11
Thanks for the issue. I noticed some flicking in rendering the image on iOS 12/13, but I cannot reproduce this behavior anymore on iOS 14+.

I am going to close this as the issue appears to have been resolved in newer versions of iOS. If you encounter any additional problems, please open a new issue and include a code reproduction. Thank you!

**Closed by liamdebeasi** 2021-09-16 14:11 UTC
Labels: triage
