### ISSUE TITLE
bug: ionic-title cant be center with icon

### ISSUE THREAD

**Issue by indraraj26** [ionic-team/ionic-framework#21860] opened 2020-08-01 06:35 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

```
ion-title {
  text-align: center;
}
```
![image](https://user-images.githubusercontent.com/23274631/89095800-f12a9b80-d3ee-11ea-8fd6-1fb8d82dc377.png)

![image](https://user-images.githubusercontent.com/23274631/89095838-2b943880-d3ef-11ea-8287-2bef7b94738e.png)

Link : https://codepen.io/indraraj26/pen/GRoboXJ

**Expected behavior:**

It should be center whether toolbar will have one icon or more than one icon.

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by indraraj26** [comment] 2020-08-02 09:02
after debugging if you add mode="ios" to toolbar then it is centering the title properly. it is problem with md spec css
```
<ion-toolbar  mode="ios">
</ion-toolbar>
```

**Comment by liamdebeasi** [comment] 2020-08-03 13:24
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The title in MD mode is supposed to be aligned to starting side/left to follow the Material Design spec, so the behavior you are describing is not supported in this mode.

**Closed by liamdebeasi** 2020-08-03 13:24 UTC
Labels: triage
