### ISSUE TITLE
bug: (angular - ios) ion-content sometimes doesn't apply --padding-bottom

### ISSUE THREAD

**Issue by sergiomilici** [ionic-team/ionic-framework#21967] opened 2020-08-24 13:56 UTC
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**

`ion-content` doesn't have the correct padding-bottom. The content of the page is on top of the padding-bottom of the page. This happens randomly, in my case 9/10 times, in ios mode running in Safari (Desktop) and in ios devices (ios 13.x and 11.x) in an angular project;

**Note**: 
* `ios 13` and `safari desktop`: It happens all the time while loading the page. See [video.](https://github.com/sergiomilici/ionic-bug-example/blob/master/issue_assets/IMG_0565.MOV)
* `ios 11 (simulator)`: Load the page and it seems to be working. Then click the button to show the alert and the error happens, the padding bottom is "gone". It also happens the click not working the first time in ion-buttom (it's reported) and the click produces the padding-bottom to not be applied. See [video](https://github.com/sergiomilici/ionic-bug-example/blob/master/issue_assets/IMG_0633.MOV)

Load the app and it happens, sometimes it doesn't. 
I noticed in an app I'm working on that this happens after triggering an event for example a click (the button I added at the bottom and showing an alert) or when loading some async content with *ngIf using async pipe.

I tried to debug it and I found that in the class `scroll-y` (ion-content -> shadowContent -> main) disabling the props `touch-action` and `overflow-y` and then re-enbling them the problem is fixed so maybe this is a race condition issue. You can see this better in this [video.](https://github.com/sergiomilici/ionic-bug-example/blob/master/issue_assets/IMG_0565.MOV)

**Expected behavior:**
`ion-content` has the correct padding-bottom set by --padding-bottom.

**Steps to reproduce:**
Create an ionic angular blank project and in home.html add a some `ion-item` or any elements that produce scroll on the page after it loads and add padding bottom to ion-content element: ion-content{--padding-bottom: 20px}

I provided a repo with the issue. It's an ionic blank project. I added the ion-content padding bottom and some ion-items to have content to produce scroll. You must run it on safari ios or desktop.

I don't know if this happens in React or just Stencil projects.

**Related code:**

ionic repo with the bug: [https://github.com/sergiomilici/ionic-bug-example](https://github.com/sergiomilici/ionic-bug-example)

In the folder `issue_assets` you can see a video showing the problem.

**Other information:**

**Ionic info:**
```
Ionic:

   Ionic CLI                     : 6.11.0 (/Users/chicho/.nvm/versions/node/v12.13.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.3.1
   @angular-devkit/build-angular : 0.901.12
   @angular-devkit/schematics    : 9.1.12
   @angular/cli                  : 9.1.12
   @ionic/angular-toolkit        : 2.3.0

Utility:

   cordova-res (update available: 0.15.1) : 0.8.1
   native-run                             : 1.0.0

System:

   NodeJS : v12.13.0 (/Users/chicho/.nvm/versions/node/v12.13.0/bin/node)
   npm    : 6.14.7
   OS     : macOS Catalina
```

**Comment by liamdebeasi** [comment] 2020-08-24 14:31
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/20614 (same underlying issue).

**Closed by liamdebeasi** 2020-08-24 14:31 UTC
Labels: triage
