### ISSUE TITLE
bug: searchInput.setFocus() does not work on IOS

### ISSUE THREAD

**Issue by agustindiazg** [ionic-team/ionic-framework#25271] opened 2022-05-10 19:38 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x
- [ ] Nightly

### Current Behavior

When i open a modal with a search input on desktop focus function does work, when doing the same in Safari/Chrome in IOS ir does not

### Expected Behavior

When i open a modal with a search input on desktop/IOS the search input is on focus

### Steps to Reproduce

I have an ionic app using Vue3 and i have this watchEffect, so after the state of the modal is change, it does run.
This does set the focus on Desktop not in Safari (IOS)
```ts
    watchEffect(() => {
      const searchInputElem = searchInput.value?.$el;
      nextTick(() => {
        setTimeout(() => {
          searchInputElem && searchInputElem.setFocus();
        }, 750);
      });
    });
```

### Ionic Info

"@ionic/vue": "5.9.3",
"@ionic/vue-router": "5.9.3",

**Comment by liamdebeasi** [comment] 2022-05-11 13:07
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/24009. The linked issue mentions `autofocus`, but the same focusing mechanisms are used under the hood so it is likely the same issue.

**Closed by liamdebeasi** 2022-05-11 13:07 UTC
Labels: triage
