### ISSUE TITLE
bug: issue with Fixed element within ion-content on Ipad pro Safri, ios 15

### ISSUE THREAD

**Issue by irenagroup** [ionic-team/ionic-framework#23451] opened 2021-06-14 16:47 UTC
**Ionic version:**
5.6.9

**Current behavior:**
Fixed width Div/container does not honor "position:fixed" inside <ion-content></ion-content>. it should start from top:0. y:0;

**Expected behavior:**
It should honor on safari on Ipad latest OS.

**Steps to reproduce:**
Put fixed DIV inside ion-content. here is minimal reproduction behaviour. 

Environment:
ios 15
Ipad Pro

StackBlitz
https://stackblitz.com/edit/ionic-angular-v5-ceehst?file=src%2Fapp%2Fapp.component.html

**Comment by liamdebeasi** [comment] 2021-06-14 18:09
Thanks for the issue. The problem here looks to be that WebKit is not rendering the yellow element when compositing certain layers inside of `ion-content`, not that it is ignoring `position: fixed`. I can reproduce this outside of Ionic Framework, so I think this is a bug in WebKit not Framework.

I am working on verifying this behavior with the WebKit team, but as of right now I do not have a workaround.

**Comment by irenagroup** [comment] 2021-06-14 18:28
Thanks for getting back quickly.

@liamdebeasi  Can you please provide minimal reproduction? I will open bug with Apple

**Comment by liamdebeasi** [comment] 2021-06-14 18:31
Here is a minimal reproduction: https://codepen.io/liamdebeasi/pen/MWpZgXG

I have a WebKit bug written, but I am waiting to hear back from a WebKit team member first to determine which behavior is correct since Safari and Chrome both do something different.

**Comment by liamdebeasi** [comment] 2021-06-14 19:27
I spoke to the WebKit team and this is a long-standing bug in WebKit, so I am not sure of an ETA on when this bug can get fixed.

However, I completely forgot about the `fixed` slot inside of `ion-content` which you can use. The `fixed` slot will render content inside of `ion-content` with `position: fixed`, but it will be outside of the overflow, allowing things to work as expected.

Can you try moving your fixed content inside of the `fixed` slot in `ion-content`?

```html
<div class="fix-content" slot="fixed">
```

**Comment by irenagroup** [comment] 2021-06-14 22:37
I checked with adding the div. The above issue still exists after using slot here.https://stackblitz.com/edit/ionic-angular-v5-wspanb?file=src%2Fapp%2Fhello.component.ts
Some

The issue exists on simulator Ipad pro ios 15. Iphone 11 pro ios 14.6

**Comment by liamdebeasi** [comment] 2021-06-14 22:45
In this new example, you will need to set `slot="fixed"` on the `hello` component instead of on the inner content.

**Comment by irenagroup** [comment] 2021-06-15 00:27
Also it depends on where the content is If you are within first level of ion-content it works.
https://stackblitz.com/edit/ionic-v5-disabled-fab-gqtjhf?file=src%2Fapp%2Fapp.component.html

while in nested component it does not since I guess this is how its setup in ion-content
https://stackblitz.com/edit/ionic-v5-disabled-fab-budkap?file=src%2Fapp%2Fhello.component.html

**Comment by liamdebeasi** [comment] 2021-06-16 13:08
Thanks for the additional information! Since this is a bug in WebKit not Ionic Framework, there is not much more the team here is able to do. I recommend experimenting more with the `fixed` slot as I think that will be the easiest path forward.

I am going to close this issue, but for additional assistance with the `fixed` slot feel free to post on the [Ionic Forum](https://forum.ionicframework.com/).

**Closed by liamdebeasi** 2021-06-16 13:08 UTC
Labels: triage

**Comment by irenagroup** [comment] 2021-06-16 13:34
Sure, I think our case would be more complex in terms we are using the nested components. I guess we will use a cdk to put fixed content outside ion-content.
