### ISSUE TITLE
bug: input overlayed by keyboard in iOS safari

### ISSUE THREAD

**Issue by simonxabris** [ionic-team/ionic-framework#21782] opened 2020-07-19 07:51 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

I have a login page with two `ion-input` components (email, password). When I'm running the app in safari and click in an input field, the keyboard covers up the input fields.

**Expected behavior:**

The expected behavior is that the keyboard should push up page to make the focused input visible.

**Steps to reproduce:**

I created a test repo that you can use to reproduce (https://github.com/simonxabris/ionic-input-bug). It's basically a blank app generated with `ionic start`, the only thing I changed is I added two input fields to the home page. Unfortunately you do need an iphone to test this issue.

**Other information:**

What might be relevant is that I also tested this on an older ionic app using version 4.11.2 of `@ionic/angular` and it works as expected in that version. It also works int he 5.x version if I'm using simple `input` elements instead of `ion-input`'s.

I did some further testing both in my app and in the test files for the `input` component in `ionic/core` and it seems like it's not working when the input element is at the bottom of the page and there's no space below it. If I add some space, for example a 200px margin, the opening in the keyboard scrolls up the input as it should. Based on this finding this might not be ionic specific but related to some safari implementation. If you think the same feel free to close this issue.

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.10.1 (/Users/macbookpro/.volta/tools/image/packages/@ionic/cli/6.10.1)
   Ionic Framework               : @ionic/angular 5.2.3
   @angular-devkit/build-angular : 0.901.11
   @angular-devkit/schematics    : 9.1.11
   @angular/cli                  : 9.1.11
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 2.3.0
   @capacitor/core : 2.3.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.18.2 (/Users/macbookpro/.volta/tools/image/node/12.18.2/bin/node)
   npm    : 6.14.5
   OS     : macOS Catalina

```

**Comment by liamdebeasi** [comment] 2020-07-20 13:30
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/18532. (same underlying problem)

**Closed by liamdebeasi** 2020-07-20 13:30 UTC
Labels: triage
