### ISSUE TITLE
bug: @ionic/angular  ionChange or ion-select not working as expected on form reset

### ISSUE THREAD

**Issue by armanhadifatah** [ionic-team/ionic-framework#19898] opened 2019-11-12 19:26 UTC
# Bug Report
My current version
   Ionic Framework               : @ionic/angular 4.11.3
   @angular-devkit/build-angular : 0.803.3
   @angular-devkit/schematics    : 8.1.2
   @angular/cli                  : 8.3.3
   @ionic/angular-toolkit        : 2.0.0

**Current behavior:**
I think this was a problem before with angular but angular fixed it with the emitEvent:false option, which is now not working in ionic.
I have a reactive form when I want to reset the form with reset even with {emitEvent: false} option it emits an event and by that it run ionChange which is not correct behaver if the option emitEvent:false.

**Expected behavior:**
if the option emitEvent: false, ionChange must not run .

**Steps to reproduce:**
This is what i have in my .html file
`<ion-select slot="end" (ionChange)="onProvinceChanged($event)" formControlName="provinceCtrl" [interfaceOptions]="customPopoverOptions" interface="popover" placeholder="{{'province' | translate}}">
                        <div *ngIf="cities.length > 0">
                            <ion-select-option *ngFor="let city of cities" [value]="city.id">
                                {{city.name | translate}}
                            </ion-select-option>
                        </div>
                    </ion-select>`

And this is what i have in my .ts file
`  onClearFilter(){
    this.form.controls['provinceCtrl'].reset('',{emitEvent: false});
  }`

**Other information:**

**Ionic info:**
Ionic:

   Ionic CLI                     : 5.4.5 (C:\Users\AMD\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.11.3
   @angular-devkit/build-angular : 0.803.3
   @angular-devkit/schematics    : 8.1.2
   @angular/cli                  : 8.3.3
   @ionic/angular-toolkit        : 2.0.0

Capacitor:

   Capacitor CLI   : 1.2.0
   @capacitor/core : 1.1.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : none
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 11 other plugins)

Utility:

   cordova-res : 0.6.0
   native-run  : 0.2.8

System:

   Android SDK Tools : 26.1.1 (C:\Users\AMD\AppData\Local\Android\sdk)
   NodeJS            : v10.16.3 (C:\Program Files\nodejs\node.exe)
   npm               : 4.6.1
   OS                : Windows 10

**Comment by mohammed-ghouse** [comment] 2020-01-25 09:02
Hi, found any fix for this? I'm also running into a similar problem where ionExchange (with ion select)is getting executed in the initial load of the page

**Comment by armanhadifatah** [comment] 2020-04-04 15:31
> Hi, found any fix for this? I'm also running into a similar problem where ionExchange (with ion select)is getting executed in the initial load of the page

Actually there isn't any fix to all ionic select or input because it is different from angular , so for this you can use valueChanges.subscribe on controller and do not use ionic ionChange

**Comment by amandaesmith3** [comment] 2022-02-21 21:01
Thanks for the issue! I know it's been a while, but I wanted to circle back to this. Since the code example is incomplete, I would normally ask for a Github repo that minimally reproduces the issue and go from there. However, since this issue is quite old, I'm going to just close this out. If this is still a problem with the latest version of Ionic, please open a new issue and we'll take a look. Thank you!

**Closed by amandaesmith3** 2022-02-21 21:01 UTC
Labels: triage
