### ISSUE TITLE
bug: Ionic 5 + Angular LoadingController with Http Interceptor Loader Present and Dismiss issue

### ISSUE THREAD

**Issue by Madhukumar1226** [ionic-team/ionic-framework#22277] opened 2020-10-08 08:32 UTC
#  Ionic 5 + Angular LoadingController with Http Interceptor Loader Present and Dismiss issue

**Ionic version:**

[x] **5.x**

**Current behavior:**
Still Loader Present even all http requests completed.

**Expected behavior:**
Dismiss loader when the all http requests completed.
**Steps to reproduce:**

ngOnInit() Method call multiple http requests , using http Interceptor and present and dismiss the loader in intercepotor
**Related code:**
```
public async loaderPresent(): Promise<void> {

    if (!this.isShowing) {
      this.isShowing = true;
      this.loading = await this.loadingController.create({
        cssClass: "my-custom-loader-class",
        message: "Please wait ...",
        backdropDismiss: true
      });
      return await this.loading.present();
    } else {
      this.isShowing = true;
    }
  }
```
```
public async loaderDismiss(): Promise<void> {

   // console.log('Loading dismissed ');

    if (this.loading && this.isShowing) {
      this.isShowing = false;
      await this.loadingController.dismiss();
    }
  }
```

**Other information:**

**Ionic info:**

**Comment by Madhukumar1226** [comment] 2020-10-09 08:21
https://github.com/Madhukumar1226/ionic-Issues.git

Please find the code repo

**Comment by liamdebeasi** [comment] 2020-10-09 13:48
Thanks, I am getting some errors from `HttpClient`. Can you please double check the repo and ensure that the reproduction is working correctly?

I am getting this error:

```
ERROR TypeError: Cannot read property 'method' of undefined
    at HttpXhrBackend.handle (http.js:1568)
    at MyHttpInterceptorService.intercept (interceptor.service.ts:30)
    at HttpInterceptorHandler.handle (http.js:1258)
    at HttpXsrfInterceptor.intercept (http.js:1886)
    at HttpInterceptorHandler.handle (http.js:1258)
    at HttpInterceptingHandler.handle (http.js:1936)
    at MergeMapSubscriber.project (http.js:1082)
    at MergeMapSubscriber._tryNext (mergeMap.js:46)
    at MergeMapSubscriber._next (mergeMap.js:36)
    at MergeMapSubscriber.next (Subscriber.js:49)
```

**Comment by Madhukumar1226** [comment] 2020-10-12 06:32
https://github.com/Madhukumar1226/ionic-Issues.git

@liamdebeasi Please find the code repo for reproducing issue Fixed the code changes and it's working fine please check the issues

**Comment by liamdebeasi** [comment] 2020-10-14 14:07
Can you please clarify the issue you are running into? I tested your application and the `ion-loading` component is being presented and dismissed correctly.

**Comment by Madhukumar1226** [comment] 2020-10-14 14:25
@liamdebeasi  Actually when multiple request calls happen ( in case of success ) if first call dismiss method called then instead of waiting for the remaining requests to finish the last request loader dismiss earlier .

**Comment by liamdebeasi** [comment] 2020-10-14 14:28
Thanks for the follow up. Can you please clarify why you feel this is a bug in `ion-loading`? It sounds like your code is preemptively dismissing the loader.

**Comment by liamdebeasi** [comment] 2020-10-14 15:07
Can you please provide some clear steps for me to reproduce the issue? It still sounds like the issue is that you are dismissing the loader too early.

**Comment by Madhukumar1226** [comment] 2020-10-14 15:18
@liamdebeasi Yes I'm not dismissing the loader but the problem is that only if request not complete it's dismissing.  

Okay let me explain my code structure.
1. I have created one shared folder which contains all my reusable components and services.
2. Inside that shared folder I have form component and http interceptor. Inside the http interceptor before calling request I'm showing the loader... Check the below code

`

intercept(
    request: HttpRequest<any>,
    next: HttpHandler
  ): Observable<HttpEvent<any>> {
   
    this.utilityService.showLoader();
    //console.log(this.authReq);
    return next.handle(request).pipe(
       finalize(() => {
         this.utilityService.hideLoader()
      }) 
    );
  }
`
3. And I have created those methods inside the utility.service.ts file.

**Comment by liamdebeasi** [comment] 2020-10-14 15:37
Thanks for the explanation. Your `finalize` callback is being called every time a request resolves, so the first callback is going to dismiss the loader after a `setTimeout` of 700ms.

When subsequent requests finish, nothing happens because you call `return Promise.resolve()` in `dismissLoader`. This results in the loader being dismissed after 700ms regardless of whether or not the remaining requests have finished.

This appears to be a bug in your application's logic and not a bug in Ionic Framework, so I am going to close this issue. In order to resolve this, you will need a way of waiting for all the requests to resolve before dismissing the loader. You can also enhance this functionality by dismissing the loader early if one or more of the requests fail (regardless of whether or not all have finished).

**Closed by liamdebeasi** 2020-10-14 15:37 UTC
Labels: triage
