### ISSUE TITLE
bug: ion-button with :disabled doesn't revert disabled styling (Vue)

### ISSUE THREAD

**Issue by eric-horodyski** [ionic-team/ionic-framework#24214] opened 2021-11-12 16:08 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

While working with a member of the community, it was discovered that when dynamically computing the `:disabled` attribute of an `ion-button`, the enabled style does not get applied when the button is no longer in a disabled state.

This can be observed when placing an `ion-button` within a block of `ion-buttons` within an `ion-toolbar`. However, an `ion-button` used inside an item, or another structure, does not have this behavior.

### Expected Behavior

If an `ion-button` becomes disabled and then re-enabled, the disabled styling should be removed.

### Steps to Reproduce

1. Run the reproduction attached
2. Press the "Increment Count" button.
3. Observe the buttons become disabled, both functionally and stylistically.
4. Press the "Increment Count" button two more times.
5. Observe the button within an `ion-item` removes its disabled styling, but the button within the `ion-footer` does not. Functionally, both buttons are enabled at this point. 

### Code Reproduction URL

https://github.com/eric-horodyski/fw-vue-disabled-toolbar

### Ionic Info

Ionic:

   Ionic CLI       : 6.18.0 (/Users/eric/.volta/tools/image/packages/@ionic/cli/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 5.8.5

Capacitor:

   Capacitor CLI      : 3.3.1
   @capacitor/android : not installed
   @capacitor/core    : 3.3.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.3
   native-run  : 1.5.0

System:

   NodeJS : v14.17.0 (/Users/eric/.volta/tools/image/node/14.17.0/bin/node)
   npm    : 7.14.0
   OS     : macOS Big Sur

**Comment by liamdebeasi** [comment] 2021-11-12 18:15
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/24140.

**Closed by liamdebeasi** 2021-11-12 18:15 UTC
Labels: triage
