### ISSUE TITLE
bug: React IonSelect "multiple" gets into infinite render loop

### ISSUE THREAD

**Issue by aruljayaraj** [ionic-team/ionic-framework#24691] opened 2022-02-02 12:23 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

1. Select multiple values from the Colors Set 2 dropdown
2. Check the console on the onIonChange and onSubmit event
3. Selected values not displayed onSubmit, it causes an infinite loop.

### Expected Behavior

I've recently upgraded the **@ionic/react** version from **5.6.1 to 6.0.4(latest)** in my project and also updated the RHF from **6.14.1** to **7.25.3(latest)**. I would like to get the selected colors during onSubmit.  It was working in the lower version of Ionic. 

Also, I've raised a ticket with the RHF and they investigated this issue, RHF side is working fine. Here is the discussion link. https://github.com/react-hook-form/react-hook-form/issues/7708

What is the motivation of `valueChanged` detection and then `emit` change?

### Steps to Reproduce

1. Go to the given Sandbox link
2. Select multiple values from the Colors Set 2 dropdown
3. Check the console on the onIonChange and onSubmit event
4. Selected values not displayed onSubmit, it causes an infinite loop.

### Code Reproduction URL

https://codesandbox.io/s/infallible-feather-50dtb?file=/src/App.tsx

**Comment by sean-perkins** [comment] 2022-02-02 17:32
Hello @aruljayaraj thanks for the issue!

This appears to be a duplicate of #20106, we will track the issue through that ticket. 

A community member has commented a workaround that be helpful in the interim to addressing the core issue: https://github.com/ionic-team/ionic-framework/issues/20106#issuecomment-1007325187.

**Closed by sean-perkins** 2022-02-02 17:32 UTC
Labels: triage
