### ISSUE TITLE
bug: can't place multiple form controls in one ion-item when using new syntax

### ISSUE THREAD

**Issue by rdlabo** [ionic-team/ionic-framework#26697] opened 2023-01-29 11:11 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [ ] v6.x
- [X] v7.x
- [ ] Nightly

### Current Behavior

ion-select[slot=end] require attribute of `label` or `area-label`.
But if added, break main label.

#### 1. console.log: `Using ion-select with an ion-label has been deprecated.` , but it displays as expected.

```html
<ion-item>
    <ion-input
            label="Price"
            labelPlacement="fixed"
            value="100.0"
            type="number"
    ></ion-input>
    <ion-select
            slot="end"
            placeholder="UNIT"
            value="USD"
    >
      <ion-select-option value="USD">USD</ion-select-option>
      <ion-select-option value="JPY">JPY</ion-select-option>
    </ion-select>
</ion-item>
```

![スクリーンショット 2023-01-29 午後8 07 28](https://user-images.githubusercontent.com/9690024/215322074-91fd37bf-72c3-4dce-b5a2-b080040579fb.png)

#### 2. If add label to `ion-select`, ion-input is removed:

![スクリーンショット 2023-01-29 午後8 08 49](https://user-images.githubusercontent.com/9690024/215322129-6641d9e8-12b0-4e11-9f22-d0cc21a868d3.png)

### Expected Behavior

ion-select[slot=end] doesn't require attribute of `label` or `area-label`, or else.

### Steps to Reproduce

```
<!-- as expect -->
<ion-item>
    <ion-input
            label="Price"
            labelPlacement="fixed"
            value="100.0"
            type="number"
    ></ion-input>
    <ion-select
            slot="end"
            placeholder="UNIT"
            value="USD"
    >
      <ion-select-option value="USD">USD</ion-select-option>
      <ion-select-option value="JPY">JPY</ion-select-option>
    </ion-select>
  </ion-item>


<!-- removed ion-input -->
  <ion-item>
    <ion-input
            label="Price"
            labelPlacement="fixed"
            value="100.0"
            type="number"
    ></ion-input>
    <ion-select
            label="Price"
            labelPlacement="fixed"
            slot="end"
            placeholder="UNIT"
            value="USD"
    >
      <ion-select-option value="USD">USD</ion-select-option>
      <ion-select-option value="JPY">JPY</ion-select-option>
    </ion-select>
  </ion-item>


<!-- removed ion-input -->
  <ion-item>
    <ion-input
            value="100.0"
            type="number"
    ></ion-input>
    <ion-select
            label="Price"
            labelPlacement="fixed"
            slot="end"
            placeholder="UNIT"
            value="USD"
    >
      <ion-select-option value="USD">USD</ion-select-option>
      <ion-select-option value="JPY">JPY</ion-select-option>
    </ion-select>
  </ion-item>
```

Note: ion-select[slot=end][aria-label] is too.

### Ionic Info

```
Ionic:

   Ionic CLI                     : 6.20.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.0.0-beta.0
   @angular-devkit/build-angular : 15.1.3
   @angular-devkit/schematics    : 15.1.3
   @angular/cli                  : 15.1.3
   @ionic/angular-toolkit        : 7.0.0

Capacitor:

   Capacitor CLI      : 4.6.2
   @capacitor/android : 4.6.2
   @capacitor/core    : 4.6.2
   @capacitor/ios     : 4.6.2

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.1

System:

   NodeJS : v18.12.1 (/usr/local/bin/node)
   npm    : 8.19.3
   OS     : macOS

```

**Comment by amandaejohnston** [comment] 2023-01-31 15:49
Thank you for the issue, I'm able to replicate this. The problem is that when using the updated syntax for `ion-input` and/or `ion-select`, they have their `width` set to 100%, so placing both in the same `ion-item` causes one to be shoved off-screen. We should probably change the width if there are multiple form controls in the same item.

As a workaround, you can use CSS to overwrite the change:
```
ion-select {
  width: auto;
}
```
You can also apply a custom class to the select if needed:
```
<ion-select class="custom-select" aria-label="Price" labelPlacement="fixed" slot="end" placeholder="UNIT" value="USD">
  <ion-select-option value="USD">USD</ion-select-option>
  <ion-select-option value="JPY">JPY</ion-select-option>
</ion-select>
```
```
ion-select.custom-select {
  width: auto;
}
```

**Comment by crhayes** [comment] 2023-02-02 19:33
I have a similar issue. We have multiple UIs that are similar to the below (see price input).

Here we have the label to the left, and the input nestled between a "prefix" (`$`) and a "suffix" (`USD`).

![image](https://user-images.githubusercontent.com/727536/216430514-e0742d1c-ed62-4c1f-b964-d48abf3421e7.png)

Code:

```jsx
<IonItem lines="full">
  <IonLabel position="fixed">Price</IonLabel>
  <span>$</span>
  <IonInput
    type="number"
    value={input.price}
    placeholder="0.00"
    onIonChange={(e) => {
      // implementation
    }}
  />
  <small slot="end">USD</small>
</IonItem>
```

Is there a suggested way to produce a UI like this with the new `IonInput`/`IonItem`? Also, let me know if this comment deserves it's own issue and I will create one!

**Comment by rdlabo** [comment] 2023-02-05 08:32
@crhayes This issue is fixed by https://github.com/ionic-team/ionic-framework/issues/26698#issuecomment-1408689353
You can use `aria-labelledby` attribute.

**Comment by rdlabo** [comment] 2023-02-05 08:38
@amandaejohnston Thanks reply. Your suggestion made this issue resolve! I use `width: auto` and `aria-labelledby`.

```html
<ion-item>
    <ion-label id="label-price">Price</ion-label>
    <ion-input
            aria-labelledby="label-price"
            value="100.0"
            type="number"
    ></ion-input>
    <ion-select
            aria-labelledby="label-price"
            slot="end"
            placeholder="UNIT"
            value="USD"
    >
      <ion-select-option value="USD">USD</ion-select-option>
      <ion-select-option value="JPY">JPY</ion-select-option>
    </ion-select>
  </ion-item>
```

This displayed correctly. Thank you.

**Comment by rdlabo** [comment] 2023-02-05 08:40
1. `ion-input[slot=end]` may be `width: auto` default.
2. We need to be able to set the title of the `ion-select` myself.
( At least in this case the title should be "Currency Unit", not "Price" )

**Comment by amandaejohnston** [comment] 2023-03-06 17:35
This has been resolved via https://github.com/ionic-team/ionic-framework/pull/26897 and the fix will be available in a future release of Ionic 7. Thanks again!

**Closed by amandaejohnston** 2023-03-06 17:35 UTC
Labels: package: core, type: bug
