### ISSUE TITLE
bug: ionItemSliding does not take the className property

### ISSUE THREAD

**Issue by SalahAdDin** [ionic-team/ionic-framework#22617] opened 2020-12-03 09:07 UTC
# Bug Report

**Ionic version:**
[ ] **4.x**
[ ] **5.3.5**
[x] **5.5.1**

**Current behavior:**
Add passing the `className` property to the component it does not render it on the web, even when the property does exist.

**Expected behavior:**
It should pass this property to enable the user to customize the component styles in a intuitive way.

**Steps to reproduce:**
![Captura de Pantalla 2020-12-03 a la(s) 12 04 20](https://user-images.githubusercontent.com/5034215/100987864-17f50c00-3560-11eb-9f6e-8c82376b3c23.png)
![Captura de Pantalla 2020-12-03 a la(s) 12 05 20](https://user-images.githubusercontent.com/5034215/100987870-1a576600-3560-11eb-81c4-2d44a7e56d79.png)

**Related code:**

```
return (
    <IonItemSliding ref={ionItemSlidingRef} className="package-card">
      <IonItem
        lines="none"
      >
        <IonLabel>
        </IonLabel>
      </IonItem>
      <IonItemOptions>
        <IonItemOption color="danger" onClick={() => removeFavoriteSession()}>
          Remove
        </IonItemOption>
      </IonItemOptions>
    </IonItemSliding>
  )
```

**Other information:**
This bug is presented in the newest version, we chose to add a class to this component because it was possible in previous version, it means, it was working; with the newest version it does not work anymore.

**Ionic info:**

```
❯ ionic info

Ionic:

   Ionic CLI       : 6.12.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.5.1

Capacitor:

   Capacitor CLI   : 2.4.4
   @capacitor/core : 2.4.4

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v14.7.0 (/usr/local/Cellar/node/14.7.0/bin/node)
   npm    : 6.14.8
   OS     : macOS Catalina

```

**Comment by liamdebeasi** [comment] 2020-12-03 14:58
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/22609. These issues are related to the same underlying bug in Ionic React. We have a PR up that fixes this issue (https://github.com/ionic-team/ionic-framework/pull/22613), and it should be available in the next release of Ionic React.

**Closed by liamdebeasi** 2020-12-03 14:58 UTC
Labels: triage
