### ISSUE TITLE
bug: ion-refresher not working when using skeleton

### ISSUE THREAD

**Issue by luis-don-dev** [ionic-team/ionic-framework#18112] opened 2019-04-23 21:00 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
When show content and hide skeleton and vice versa switching between tabs refresher stops working

**Expected behavior:**
Switch between tabs and use the refresher normally without it stop working

**Steps to reproduce:**
1. Create new app with tabs boilerplate
2. Put refresher, skeleton div and content div in each tab
3. Set boolean flag to control if skeleton shows of content

**Related code:**
In each tab ion-content I have the following code:

     <ion-refresher slot="fixed" (ionRefresh)="refresh($event)">
          <ion-refresher-content></ion-refresher-content>
     </ion-refresher>

     <div *ngIf="loading">
          <ion-list class="skeleton-list">
               <ion-item *ngFor="let index of [1,2,3,4,5,6,7,8,9,10]">
                    <ion-label>
                         <h3>
                              <ion-skeleton-text animated style="width: 50%"></ion-skeleton-text>
                         </h3>
                         <p>
                              <ion-skeleton-text animated style="width: 80%"></ion-skeleton-text>
                         </p>
                         <p>
                              <ion-skeleton-text animated style="width: 60%"></ion-skeleton-text>
                         </p>
                    </ion-label>
               </ion-item>
          </ion-list>
     </div>

     <div *ngIf="!loading">
          <ion-card class="welcome-card">
               <ion-img src="/assets/shapes.svg"></ion-img>
                    <ion-card-header>
                         <ion-card-subtitle>Get Started</ion-card-subtitle>
                         <ion-card-title>Welcome to Ionic</ion-card-title>
                    </ion-card-header>
               <ion-card-content>
                    <p>Now that your app has been created, you'll want to start building out features and components. Check out some of the resources below for next steps.</p>
               </ion-card-content>
          </ion-card>
     </div>

And in each tab Typescript file I have the following code:

     public loading = false;

     refresh(event) {
          this.loading = true;
          setTimeout(() => {
               this.loading = false;
               event.target.complete();
          }, 200);
     }

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by maxtacco** [comment] 2019-04-23 21:33
We experience the same issue. This may be a duplicate of https://github.com/ionic-team/ionic/issues/16886

**Comment by luis-don-dev** [comment] 2019-04-23 21:52
@maxtacco even if I put style="z-index: 0;" to ion-content it doesn't work, did that work for you?

**Comment by maxtacco** [comment] 2019-04-23 21:54
@luis-don-dev Yes, I've tried it as well with no luck.

**Comment by luis-don-dev** [comment] 2019-04-23 21:58
I was working on my real project facing the same issue then I create a default tabs boilerplate project to make that simple test just to find it doesn't work, I thought it was an issue with my code, hope it gets fixed soon :/

**Comment by luis-don-dev** [comment] 2019-04-23 23:03
What I ended doing was setting the following css to:

ion-refresher{
  display: block;
  z-index: 10;
  visibility: visible;
  height: 100vh;
}

this way ion-refresher is always available but is shows always on the center of the screen but it is working for me right now hope it helps!

**Comment by vannatter** [comment] 2019-05-09 20:05
Yep, same issue.

**Comment by roxteddy** [comment] 2019-06-18 14:16
I think first tab where you used refresher keeps i don't know what even when it is hidden.
If you delete the tab in the inspector, the refresher begin to work on another tab.

I which there were a tab mode without any caching system. Guess I'm just gonna implement a standard router outlet instead.

**Comment by roxteddy** [comment] 2019-06-25 13:25
I found a (nasty?) work-around :

```
pageIsActivated: boolean;

ionViewDidEnter() {
    this.pageIsActivated = true;
}

ionViewWillLeave() {
    this.pageIsActivated = false
}
```

```
<ion-content *ngIf="pageisActivated">
...
</ion-content>
```

This way, unused ion-refresher don't persist on the DOM.

**Comment by maxtacco** [comment] 2019-06-26 21:49
@roxteddy's solution seems to work for me as well but official fix is really required

**Comment by roxteddy** [comment] 2019-06-27 08:16
@maxtacco I agree with that. Actually, I discovered it does not work so good for me because there are cases where lifecycle events are not triggered properly.

**Comment by buuug7** [comment] 2019-09-20 15:04
I solve this problem by add the following code snippet in the component/page that used ion-refresher. For example, if you have two page use ion-refresh, you need add the following code in each of page.

```typescript
// ---
@ViewChild(IonRefresher, { static: false})
   refresher: IonRefresher;

   ionViewDidEnter() {
      this.refresher.disabled = false;
   }

   ionViewWillLeave() {
      this.refresher.disabled = true;
   }
// ---
```

**Comment by andreas-aeschlimann** [comment] 2019-10-01 23:13
And what if the refresher sits in a modal? Then you probably cannot use the `ionViewWillLeave`...

**Comment by andreas-aeschlimann** [comment] 2019-11-03 18:44
I was wondering: Is this a bug or is this expected (then it should be in the docs)? 

Obviously, ion-refresher starts acting weird as soon as you have two of them in the DOM (as in pages with tabs).

**Comment by moritzvieli** [comment] 2019-12-19 07:31
@buuug7  Thanks a lot! I also have multiple refreshers in tab pages and your workaround did the trick! 👍

**Comment by andreas-aeschlimann** [comment] 2019-12-19 07:40
@moritzvieli according to the devs there should be a release soon with a complete reimplementation of the component.

**Comment by andreas-aeschlimann** [comment] 2020-03-18 21:25
Has this been fixed in Ionic 4 or 5?

**Comment by davequested** [comment] 2020-03-31 00:45
We're seeing an issue with this too. If the app is closed, then we get a push notification, click the push notification to open the app, the refresher pull down loads the data, but doesn't display it. Seems to be related to this issue.

**Comment by raghav14** [comment] 2020-05-29 12:37
I'd tabs in which I was using the `ion-refresher`. @buuug7  thanks for the solution. It works smoothly

**Comment by Lizard-King101** [comment] 2020-06-12 15:42
for people using tabs your tabs ion-content needs to be `slot="fixed"`

**Comment by liamdebeasi** [comment] 2022-05-23 20:19
Thanks for the issue. I am not able to reproduce this using the latest version of Ionic 6, so I believe this was resolved. If you are still running into problems, please open a new issue. Thanks!

**Closed by liamdebeasi** 2022-05-23 20:19 UTC
Labels: package: core, type: bug
