### ISSUE TITLE
bug: ion-datetime with presentation time always displays inital value of 00:00

### ISSUE THREAD

**Issue by petenunn** [ionic-team/ionic-framework#24877] opened 2022-03-04 13:36 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

When ion-datetime component is added to an angular template with presentation "time" and a value of "13:30" (say) it displays 0 hours and 0 minutes. Clicking on either the minutes or hours triggers an update and displays the correct values.

### Expected Behavior

The ion-datetime component always displays the initial value of "13:30".

### Steps to Reproduce

Add an ion-datetime to your template with presentation="time" and value="13:30".

### Code Reproduction URL

https://stackblitz.com/edit/ionic6-angular13-rshgqk?file=src/app/app.component.ts

### Ionic Info

Ionic:

   Ionic CLI                     : 6.18.1 (/opt/homebrew/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.10
   @angular-devkit/build-angular : 13.0.4
   @angular-devkit/schematics    : 13.0.4
   @angular/cli                  : 13.0.4
   @ionic/angular-toolkit        : 5.0.3

Capacitor:

   Capacitor CLI      : 3.4.3
   @capacitor/android : not installed
   @capacitor/core    : 3.4.3
   @capacitor/ios     : not installed

Utility:

   cordova-res (update available: 0.15.4) : 0.15.3
   native-run                             : 1.5.0

System:

   NodeJS : v16.14.0 (/usr/local/bin/node)
   npm    : 8.3.1
   OS     : macOS Big Sur

**Comment by liamdebeasi** [comment] 2022-03-04 14:16
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/24878.

**Closed by liamdebeasi** 2022-03-04 14:16 UTC
Labels: triage
