### ISSUE TITLE
bug: IonIcon adds an unwanted margin with IonLabel in IonItem

### ISSUE THREAD

**Issue by WorstTypist** [ionic-team/ionic-framework#28565] opened 2023-11-21 11:29 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

This code:
```jsx
<IonList>
  <IonItem
    data-testid="yt-link"
    color="primary"
    aria-hidden="true"
    className="ion-padding-start ion-padding-end ion-margin-bottom social"
    button
    detail={false}
    onClick={() => {
      navigateExternal(ytUrl);
    }}
  >
    <IonIcon icon={logoYoutube} slot="start" />
    <IonLabel>Subscribe on Youtube</IonLabel>
  </IonItem>
</IonList>
```
behaves as excpected on the browser / PWA:
![image](https://github.com/ionic-team/ionic-framework/assets/88891878/651c84ae-18a5-4a02-8298-7909656329e6)

But on android, there's a bigger margin between Icon and Label:
![image](https://github.com/ionic-team/ionic-framework/assets/88891878/3d06b073-3070-45e0-a0b3-4b7088f2bf06)

Have to mention that I added a custom CSS to change padding inside the item itself, but not between icon and item:
```css
.social {
  --padding-top: 10px;
  --padding-bottom: 10px;
  --padding-start: 26px;
  --padding-end: 26px;
}
```

Nevertheless with or without css override, the same happens.

### Expected Behavior

Padding should remain consistent across apps.

### Steps to Reproduce

Create a list with an item.
Place an icon and label inside

See code inside `current behaviour`

### Ionic Info

Ionic:

   Ionic CLI       : 7.1.1 (C:\Users\I733564\AppData\Local\Volta\tools\image\packages\@ionic\cli\node_modules\@ionic\cli)
   Ionic Framework : @ionic/react 7.5.0

Capacitor:

   Capacitor CLI      : 5.5.0
   @capacitor/android : 5.5.0
   @capacitor/core    : 5.5.0
   @capacitor/ios     : 5.5.0

Utility:

   cordova-res                          : not installed globally
   native-run (update available: 2.0.0) : 1.7.3

System:

   NodeJS : v20.6.1 (C:\Users\I733564\AppData\Local\Volta\tools\image\node\20.6.1\node.exe)
   npm    : 9.8.1
   OS     : Windows 10

**Comment by liamdebeasi** [comment] 2023-11-21 14:19
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The additional padding on the right of the icon is added to match the Material Design specification for lists: https://m2.material.io/components/lists

You can see this in the demo at the link above by clicking the "Icon" radio in the "Before list test" section. On Android devices, Ionic applications run in Material Design mode by default.

However, when the application is running in iOS mode we conform to the iOS specification which does not apply additional padding on the right. If there is a behavior difference it is likely that the app is running in iOS mode on one platform and MD mode on the other. You can verify this by looking at the "mode" attribute set on the `html` element.

**Closed by liamdebeasi** 2023-11-21 14:19 UTC
Labels: triage

**Comment by WorstTypist** [comment] 2023-11-21 15:51
Thx a lot @liamdebeasi for this insight. This was somethingg I was not aware of.
