### ISSUE TITLE
feat: Hide tab bar when visiting tab's children pages

### ISSUE THREAD

**Issue by dev-sammy** [ionic-team/ionic-framework#21814] opened 2020-07-25 08:56 UTC
# Feature Request

**Ionic version:**

[x] **5.x**

**Ionic info**
```
Ionic:

   Ionic CLI                     : 6.6.0 (C:\Users\devsammy\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.2.1
   @angular-devkit/build-angular : 0.901.8
   @angular-devkit/schematics    : 9.1.8
   @angular/cli                  : 9.1.8
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 7 other plugins)

Utility:

   cordova-res                          : not installed
   native-run (update available: 1.0.0) : 0.3.0

System:

   Android SDK Tools : 26.1.1 (C:\Users\devsammy\AppData\Local\Android\Sdk\)
   NodeJS            : v12.16.2 (C:\Program Files\nodejs\node.exe)
   npm               : 6.14.4
   OS                : Windows 10
```

**Describe the Feature Request**

I am using Ionic 5 and want to hide tab bar when going to tab child's child pages and so on , only for parent pages it will show up. In Ionic 3 we had a directive to hide tab on sub pages easily, please make a workaround for it or at least give an explanation of why its blocked.

**Describe Preferred Solution**

I can choose to hide the tab when visiting the child pages, it will only show up in parent pages.

**Related Code**

_My tab page routing module:_

```
import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';

import { TabsPage } from './tabs.page';

const routes: Routes = [
  {
    path: '',
    component: TabsPage,
    children: [
      {
        path: 'home',
        children: [
          {
            path: '',
            loadChildren: () => import('../home/home.module').then(m => m.HomePageModule)
          }
        ]
      },
      {
        path: 'dashboard',
        children: [
          {
            path: '',
            loadChildren: () => import('../dashboard/dashboard.module').then(m => m.DashboardPageModule)
          }
        ]
      },
      {
        path: 'account',
        children: [
          {
            path: '',
            loadChildren: () => import('../account/account.module').then(m => m.AccountPageModule)
          }
        ]
      },
      {
        path: 'settings',
        children: [
          {
            path: '',
            loadChildren: () => import('../settings/settings.module').then(m => m.SettingsPageModule)
          }
        ]
      },
      {
        path: '',
        redirectTo: '/tabs/home',
        pathMatch: 'full'
      }
    ]
  }
];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule],
})
export class TabsPageRoutingModule {}

```

_My tab page html:_

```
<ion-tabs>
  <ion-tab-bar slot="bottom">
    <ion-tab-button tab="home">
      <ion-icon name="home-outline"></ion-icon>
      <ion-label>Home</ion-label>
    </ion-tab-button>

    <ion-tab-button tab="dashboard">
      <ion-icon name="restaurant-outline"></ion-icon>
      <ion-label>Restaurant</ion-label>
    </ion-tab-button>

    <ion-tab-button tab="account">
      <ion-icon name="person-outline"></ion-icon>
      <ion-label>Profile</ion-label>
    </ion-tab-button>

    <ion-tab-button tab="settings">
      <ion-icon name="settings-outline"></ion-icon>
      <ion-label>Settings</ion-label>
    </ion-tab-button>
  </ion-tab-bar>
</ion-tabs>
```

**Comment by DwieDima** [comment] 2020-07-26 09:51
@dev-sammy if you want to navigate inside tabs and hide the tab-bar, you simply define a route outside from tabs-routing-module.
Inside the page, which is defined inside tabs-routing, just navigate to the route defined in app-routing-module.

your `app-routing-module`:

```
const routes: Routes = [
  {
    path: "",
    loadChildren: () =>
      import("./tabs/tabs.module").then((m) => m.TabsPageModule)
  },
  {
    path: "outside",
    loadChildren: () =>
      import("./outside/outside.module").then((m) => m.OutsidePageModule)
  }
];
```

your `tabs-routing-module`:

```
const routes: Routes = [
  {
    path: "tabs",
    component: TabsPage,
    children: [
      {
        path: "tab1",
        loadChildren: () =>
          import("../tab1/tab1.module").then((m) => m.Tab1PageModule)
      },
      {
        path: "",
        redirectTo: "/tabs/tab1",
        pathMatch: "full"
      }
    ]
  },
  {
    path: "",
    redirectTo: "/tabs/tab1",
    pathMatch: "full"
  }
];
```

and your `routing-module` for specific tab for inside navigation:

```

const routes: Routes = [
  {
    path: "",
    component: Tab1Page
  },
  {
    path: "inside",
    loadChildren: () =>
      import("../inside/inside.module").then((m) => m.InsidePageModule)
  }
];
```

**heres a working example: https://github.com/DwieDima/inside-outside-tab-nav**

just take a look at how i have defined the routes in
- `app-routing-module.ts`
- `tabs-routing-module.ts`
- `tab1-routing-module.ts`

and an example navigation in
- `tab1-page.ts`

**Comment by dev-sammy** [comment] 2020-07-27 11:21
> @dev-sammy if you want to navigate inside tabs and hide the tab-bar, you simply define a route outside from tabs-routing-module.
> Inside the page, which is defined inside tabs-routing, just navigate to the route defined in app-routing-module.
> 
> your `app-routing-module`:
> 
> ```
> const routes: Routes = [
>   {
>     path: "",
>     loadChildren: () =>
>       import("./tabs/tabs.module").then((m) => m.TabsPageModule)
>   },
>   {
>     path: "outside",
>     loadChildren: () =>
>       import("./outside/outside.module").then((m) => m.OutsidePageModule)
>   }
> ];
> ```
> 
> your `tabs-routing-module`:
> 
> ```
> const routes: Routes = [
>   {
>     path: "tabs",
>     component: TabsPage,
>     children: [
>       {
>         path: "tab1",
>         loadChildren: () =>
>           import("../tab1/tab1.module").then((m) => m.Tab1PageModule)
>       },
>       {
>         path: "",
>         redirectTo: "/tabs/tab1",
>         pathMatch: "full"
>       }
>     ]
>   },
>   {
>     path: "",
>     redirectTo: "/tabs/tab1",
>     pathMatch: "full"
>   }
> ];
> ```
> 
> and your `routing-module` for specific tab for inside navigation:
> 
> ```
> 
> const routes: Routes = [
>   {
>     path: "",
>     component: Tab1Page
>   },
>   {
>     path: "inside",
>     loadChildren: () =>
>       import("../inside/inside.module").then((m) => m.InsidePageModule)
>   }
> ];
> ```
> 
> **heres a working example: https://github.com/DwieDima/inside-outside-tab-nav**
> 
> just take a look at how i have defined the routes in
> 
> * `app-routing.module.ts`
> * `tabs-routing.module.ts`
> * `tab1-routing.module.ts`
> 
> and an example navigation in
> 
> * `tab1.page.ts`
> 
> If you want to navigate inside tabs to the same page from different tab-page, you also have to define the route in specific `tab-page-routing-module`
> 
> > or at least give an explanation of why its blocked
> 
> since ionic 4, there is no longer a stack navigation (like ionic 2+3 had).
> Here the navigation relies on the angular router (if you're using angular).
> However, you can still use the old fashion push/pop stacked navigation like in Ionic 3 by using [ion-nav](https://ionicframework.com/docs/api/nav) component.
> This should only be used for navigation inside modals or popover

Yes that's the only solution right now to define the routes in root level and not as a child of tabs but I was wondering if there's any way to just visually hide the tab bar when visiting its child just like Ionic 3 had a directive as an optional feature.

**Comment by liamdebeasi** [comment] 2020-07-27 13:01
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/19427.

**Closed by liamdebeasi** 2020-07-27 13:01 UTC
Labels: triage
