### ISSUE TITLE
bug: CDNs not loading resources

### ISSUE THREAD

**Issue by rfideles** [ionic-team/ionic-framework#25874] opened 2022-09-02 13:44 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [ ] v6.x
- [X] Nightly

### Current Behavior

As of yesterday my website stopped rendering due to resources failing to load from ionic/core. Getting a 404 on https://cdn.jsdelivr.net/npm/@ionic/core/dist/ionic/p-d9fa7c89.entry.js. 

### Expected Behavior

Render website properly.

### Steps to Reproduce

Just open the page. Network tab on dev tools will show resources failing to load.

### Code Reproduction URL

https://vrzano.com

### Ionic Info

Project uses CDN files, so Ionic is not installed on project.

**Comment by rfideles** [comment] 2022-09-02 13:46
Another user reported this issue yesterday on an old thread on the forum: https://forum.ionicframework.com/t/ionic-framework-dont-work-with-cdn-since-yesterday/205813

**Comment by liamdebeasi** [comment] 2022-09-02 14:09
Thanks for the report. How are you loading Ionic from the CDN?

I tried your website, and the files load correctly: 
![image](https://user-images.githubusercontent.com/2721089/188167266-8aa78ac4-b6e3-4c2a-8df9-30e2fca067f5.png)

**Comment by liamdebeasi** [comment] 2022-09-02 14:10
It's possible that the hashed file names changed, so you may also want to try clearing your browser cache.

**Comment by ivensgoncalves** [comment] 2022-09-02 14:30
It was happening to me yesterday, and today the error is gone.
The module _p-d9fa7c89.entry.js_ belongs to a previous version of ionic core.
The error started happening right after ionic core has been updated to 6.2.5.
If you try forcing the version, it works: https://cdn.jsdelivr.net/npm/@ionic/core@6.2.4/dist/ionic/p-d9fa7c89.entry.js

**Comment by liamdebeasi** [comment] 2022-09-02 16:31
Thanks for the additional information. The chunk names (i.e. `p-d9fa7c89.entry.js`) are generated by Stencil during the build process. When the contents of files change, these hashes are updated to allow for cache busting. It sounds like there was some caching going on either on your website or in your browser where the old chunk name was trying to be loaded. Since the chunk name changed, the network request failed.

This is not a bug in Ionic, but I would caution against always loading the latest version of Ionic from CDN because it can lead to issues like this. Additionally, when future major versions of Ionic are released, apps that request the latest version from CDN may stop working due to breaking changes. Fixing the version instead allows developers to upgrade apps in a predictable way and ensure that caches are being cleared on deployment.

I am going to close this as this is not a bug in Ionic. Thanks for the report!

**Closed by liamdebeasi** 2022-09-02 16:31 UTC
Labels: triage

**Comment by rfideles** [comment] 2022-09-02 16:54
@liamdebeasi thank you for the feedback. I'll add a fixed version going forward :D

**Comment by ivensgoncalves** [comment] 2022-09-02 16:59
Just to leave additional information of my case... I was not using CDN directly.
I was just using @ionic/react (importing modules) and these CDN files were getting loaded within the library.
I was using @ionic/react:"^6.2.4" but for some reason the library was always trying to load CDN files from latest version.
It was not a browser cache either... I did refresh several times, and I also have my developer tools configured to disable cache all along.
Yesterday I tried to upgrade @ionic/react to 6.2.5, but the error remained the same.
I also tried to delete and recreate my node_modules and package-lock.json, but got same error.

Only today, with no intervention from myself, it started working again.
I have no idea of what really happened, but I believe @ionic/core should force version when trying to load CDN files.

Checking right now my Network panel, I still see scripts like this getting loaded with no version defined.
`https://cdn.jsdelivr.net/npm/@ionic/core/dist/ionic/p-49ecbc15.js`

**Comment by liamdebeasi** [comment] 2022-09-02 17:02
I'm not sure I understand the use case here. You are not using the CDN link, but the CDN files were still being pulled in? Do you have an example I can look at?

**Comment by ivensgoncalves** [comment] 2022-09-02 17:09
@liamdebeasi Yes, every time I run my app locally, or build it, the HTML has these 3 initial attachments. Wouldn't it be the case for any Ionic App?

```
<script type="module" src="https://cdn.jsdelivr.net/npm/@ionic/core/dist/ionic/ionic.esm.js"></script>
<script nomodule src="https://cdn.jsdelivr.net/npm/@ionic/core/dist/ionic/ionic.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@ionic/core/css/ionic.bundle.css" />
```

**Comment by liamdebeasi** [comment] 2022-09-02 17:22
The code snippet you provided loads Ionic from a CDN. However, it loads the latest version which can sometimes cause issues for reasons I stated in https://github.com/ionic-team/ionic-framework/issues/25874#issuecomment-1235699467. If you are using an Ionic app with a package manager such as NPM, we do not pull from a CDN.

**Comment by ivensgoncalves** [comment] 2022-09-02 17:26
@liamdebeasi Weird, I am using package manager... Don't know how it is getting pulled into my HTML then.
Anyways, I will try to create a brand new app and see what happens.
In case I reproduce the same behavior, I will create a new ticket with minimum reproducible code.
Thank you for you time.
