### ISSUE TITLE
bug: Ionic 6 + vite : Error safe area

### ISSUE THREAD

**Issue by nvthuong1996** [ionic-team/ionic-framework#23845] opened 2021-08-30 05:15 UTC
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

I setup vite with ionic 6. I use tab project to test. 
Layout when use vite : safe area incorrect

![image](https://user-images.githubusercontent.com/24992586/131288343-a81156a3-182e-4e30-88b7-b0b1d6f05f3b.png)

### Expected Behavior

Layout use vue-cli :
![image](https://user-images.githubusercontent.com/24992586/131288485-f7ff4fbc-32a9-4297-82ef-85692c79dc8f.png)

### Steps to Reproduce

please see demo project : https://github.com/Tester-Development/vite-ionic-error

**Comment by jakubkoje** [comment] 2021-08-30 12:33
Copy meta tags from index.html created by @ionic/cli

**Comment by liamdebeasi** [comment] 2021-08-30 13:49
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The `index.html` file in your project root does not have `viewport-fit="cover"`. This is required by browser engines in order for safe area to work.

Copying the meta tags from `public/index.html` (which is provided by Ionic) to the root `index.html` fixes the issue.

**Closed by liamdebeasi** 2021-08-30 13:49 UTC
Labels: triage

**Comment by nvthuong1996** [comment] 2021-08-30 15:23
Thank you
