### ISSUE TITLE
Ionic tabs with back button shows child tab briefly after click

### ISSUE THREAD

**Issue by yaozuwang** [ionic-team/ionic-framework#19981] opened 2019-11-23 13:19 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

When you navigate to a tabs page and try to navigate back, it briefly show the child tab page before navigating back.

**Expected behavior:**

Navigate back without showing child tab page.

**Steps to reproduce:**

1. Download the ionic tabs project
2. Add home page with button navigation to tabs page
3. Add back button to tabs page

**Related code:**

https://github.com/yaozuwang/Tabs

**Other information:**

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/7391734/69479322-0575cc00-0e50-11ea-98a2-3d441c108c0d.gif)

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.4.5 (/Users/home/.nvm/versions/node/v10.15.1/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.5
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.1.1

Utility:

   cordova-res : 0.8.1 
   native-run  : not installed

System:

   NodeJS : v10.15.1 (/Users/home/.nvm/versions/node/v10.15.1/bin/node)
   npm    : 6.13.0
   OS     : macOS Mojave
```

**Comment by rashid-02** [comment] 2019-12-06 13:52
This is an important bug. I am facing the same issue while building an app. The hardware back button behaviour is strange, Exit app is not working on back button and it navigates two times on once click.

**Comment by liamdebeasi** [comment] 2020-11-12 22:39
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The problem here is that you have added an `ion-header` to `tabs.page.html`. Since your `ion-tabs` is not wrapped in `ion-content`, the header is going to overlap the header on your Tab1 page. The end result is that when you click the `ion-back-button`, the `ion-header` on `tabs.page.html` transitions away, revealing the `ion-header` in `tab1.page.html`.

I do not recommend having an `ion-header` on `tabs.page.html` as that is really just a wrapper that loads the active tab. However, if you do want to have an `ion-header` in `tabs.page.html` I recommend wrapping `ion-tabs` in an `ion-content` so that transitions work properly and you do not see this brief flash of Tab1 when going back. 

Thanks!

**Closed by liamdebeasi** 2020-11-12 22:39 UTC
Labels: package: core, type: bug
