### ISSUE TITLE
bug: Ion Toast border css properties does not show

### ISSUE THREAD

**Issue by CorentinHcdDev** [ionic-team/ionic-framework#22901] opened 2021-02-09 22:31 UTC
# Bug Report

**Ionic version:**
5.0.0

**Current behavior:**
The ionic toast have issues with some css properties : 
Everything about border does not work except border-radius which works fine.
--button-color does not work too except in IOS mode

**Expected behavior:**

I want to display a border to the toast and it's impossible. The same, i want to change
the color of the button

**Related code:**

```
async presentToast() {
    const toast = await this.toastController.create({
      header: "Test",
      cssClass: "toast-primary",
      position: "top",
      buttons: [
        {
          icon: "close",
          role: "cancel",
          handler: () => {
            console.log("Cancel clicked");
          },
        },
      ]
    });
    toast.present();
  }
```

CSS : 
```
ion-toast {
    --background: #e2ecff; // Display
    --color: var(--ion-color-primary) !important; // Display
    font-family: "Poppins-Medium";
    --box-shadow: none; // Display
    --border-radius: 10px;  // Display
    --border-width: 2px;  // Does not display
    --border-color: var(--ion-color-primary); // Does not display
    --button-color: var(--ion-color-primary); // Does not display
  }
```

**Other information:**
Did not found any other issue related to this
Btw, is there a way to changes css properties from toast-header & toast-message separately ?

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.4.16 (C:\Users\Corentin\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 5.0.1
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.1.2

Capacitor:

   Capacitor CLI   : 1.5.0
   @capacitor/core : 1.5.0

Utility:

   cordova-res (update available: 0.15.2) : 0.15.1
   native-run (update available: 1.2.2)   : 0.2.8

System:

   NodeJS : v12.16.2 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.4
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment] 2021-02-10 14:41
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. You need to include `--border-style: solid` in your CSS as the default is `none`.

This is definitely confusing as our docs do not list the default values. I am working with the team to make the default values clearer in our docs.

The button color issue only impacts buttons with `role: 'cancel'` and is already being tracked here: https://github.com/ionic-team/ionic-framework/issues/21818

**Closed by liamdebeasi** 2021-02-10 14:41 UTC
Labels: triage
