### ISSUE TITLE
bug: IonReorderGroup doesn't render the latest state

### ISSUE THREAD

**Issue by Reiji777** [ionic-team/ionic-framework#24943] opened 2022-03-16 01:30 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

- When attempting to update state in a reorder operation, the state can be correctly updated, but the IonReorderGroup doesn't render the latest state

### Expected Behavior

- Once state is updated, the IonReorderGroup should render according to the latest state

### Steps to Reproduce

- Change the items's orders in the list of the repo below
- You'd see the items' order in the IonReorderGroup are not properly rendered, causing the discrepancy between the IonReorderGroup and the div

<img width="529" alt="Screen Shot 2022-03-16 at 10 12 03 AM" src="https://user-images.githubusercontent.com/41455097/158498410-d0fd505f-5346-4b14-ab7f-0940d02349dd.png">

### Code Reproduction URL

https://github.com/Reiji777/ionic-react-reorder-issue/tree/master

### Ionic Info

Ionic:

   Ionic CLI       : 6.18.2 (/Users/d/.nvm/versions/node/v16.7.0/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 6.0.11

Capacitor:

   Capacitor CLI      : 3.4.3
   @capacitor/android : not installed
   @capacitor/core    : 3.4.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v16.7.0 (/Users/d/.nvm/versions/node/v16.7.0/bin/node)
   npm    : 7.20.3
   OS     : macOS Monterey

### Additional Information
I am basically looking for a way of updating the data that the reorder items render based on.
In reality, I pull data from Firestore through useSelector, and I'd like to update the data according to the reorder operations.

**Comment by liamdebeasi** [comment] 2022-03-16 13:02
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework.

The problem here is that you are not assigning a stable identity to your list. According to the [React Lists and Keys Documentation](https://reactjs.org/docs/lists-and-keys.html#keys), React will default to using the list indexes as keys if you do not provide an explicit key to list items.

React does not recommend using list indexes as keys if the order of the items may change, which is the scenario you have in your application. Adding `key={item}` inside of the loop fixes the issue on my end.

**Closed by liamdebeasi** 2022-03-16 13:02 UTC
Labels: triage
