### ISSUE TITLE
[request] add support for lazyload component module for ng test

### ISSUE THREAD

**Issue by MrBokeh** [ionic-team/ionic-framework#18902] opened 2019-07-26 01:43 UTC
# Feature Request

**Ionic version:**
[x] **4.x**

**Describe the Feature Request**
When I Lazy load the custom component to a page module with added CUSTOM_ELEMENTS_SCHEMA to both component module and app module, after I run ng test, the Karma report shows many errors about ion-[component] is not a known element like the one below, could we add support to that? I don't want to create an individual module for all customer component...

```
'ion-avatar' is not a known element:
1. If 'ion-avatar' is an Angular component, then verify that it is part of this module.
2. If 'ion-avatar' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

```

**Describe Preferred Solution**
Add support for lazyload component module for ng test, no error to be shown

**Describe Alternatives**
Ionic generate component will automatically solve the lazy load issue or add a module when creating a new component

**Comment by amandaesmith3** [comment] 2022-02-18 19:53
Thanks for the issue! I know it's been a while, but I wanted to circle back to this. I would normally ask for a Github repo reproducing the issue, but since this thread is quite old and hasn't gotten any attention since, I'm just going to close it. If this is still a concern in the latest version of Ionic, please open a new issue and ensure the template is fully filled out. Thank you!

**Closed by amandaesmith3** 2022-02-18 19:53 UTC
Labels: triage
