### ISSUE TITLE
bug: NG0303: Can't bind to 'ngModel' since it isn't a known property of 'ion-input'.

### ISSUE THREAD

**Issue by Cristuker** [ionic-team/ionic-framework#23112] opened 2021-03-29 12:07 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
I create some tests whit karma and jamine. The test pass but always show this erros message.

> NG0303: Can't bind to 'ngModel' since it isn't a known property of 'ion-input'.

I try to import FormsModule on my module but still show the error

A example of implementation

**Expected behavior:**

Don't show message: 
> NG0303: Can't bind to 'ngModel' since it isn't a known property of 'ion-input'.

**Steps to reproduce:**
Create a component or page whit ion-input and created a test for him and run.

**Related code:**

```
      <ion-input type="number" 
        placeholder="Insira o Sticker inicial"
        value="{{ stockTakingOrder.stickerInitialNumber }}" 
        [(ngModel)]="stockTakingOrder.stickerInitialNumber"></ion-input>
```

**Other information:**

Angular Version: 11.x

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.13.1 (/home/cristian/.nvm/versions/node/v14.16.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.6.0
   @angular-devkit/build-angular : 0.1102.3
   @angular-devkit/schematics    : 11.2.3
   @angular/cli                  : 11.2.3
   @ionic/angular-toolkit        : 3.1.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v14.16.0 (/home/cristian/.nvm/versions/node/v14.16.0/bin/node)
   npm    : 6.14.11
   OS     : Linux 5.8```

**Comment by Cristuker** [comment] 2021-03-31 23:14
Repo whit code. The steps to run is on readme.md

[here](https://github.com/Cristuker/angular-issue-report/tree/main/myApp)

**Comment by liamdebeasi** [comment] 2021-04-05 19:43
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. You need to include `FormsModule` in your `imports` array when setting up the test bed. When creating a new page in Ionic Angular we add that import inside of your `HomePageModule` file, but since you are using the `HomePage` component directly, you will need to import it yourself.

**Closed by liamdebeasi** 2021-04-05 19:43 UTC
Labels: ionitron: needs reproduction
