### ISSUE TITLE
bug: scrolling not working on iOS for basic HTML content when mode is 'md' and page opened via sidenav

### ISSUE THREAD

**Issue by thoechtl** [ionic-team/ionic-framework#22505] opened 2020-11-16 16:46 UTC
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
When using material design mode (`IonicModule.forRoot({mode: 'md'})`) for iOS, scrolling of basic HTML content (like commonly used on privacy or terms pages) does not work inside `ion-content`, when the page is opened via a **sidenav**. For example an ion-content with only `<p>` tags does not scroll.
Strangely scrolling works when the HTML includes a `<ul>` or `<ol>` for example, or when IonContent `forceOverscroll` is set to true.

**Expected behavior:**
Scrolling should work in all cases.

**Steps to reproduce:**
- Download [sample app](https://github.com/thoechtl/ionic-scrolling-issue)
- `npm install`
- `ionic serve --external`
- Open on iPhone and check sidenav links

**Related code:**
https://github.com/thoechtl/ionic-scrolling-issue

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.12.1 (/Users/thomas/.nvm/versions/node/v12.19.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.4.1
   @angular-devkit/build-angular : 0.1000.8
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.19.0 (/Users/thomas/.nvm/versions/node/v12.19.0/bin/node)
   npm    : 6.14.8
   OS     : macOS Catalina
```

**Comment by liamdebeasi** [comment] 2020-11-16 17:23
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/22306.

**Closed by liamdebeasi** 2020-11-16 17:23 UTC
Labels: triage
