### ISSUE TITLE
bug: focus trapping activates on toast if non-toast presented first

### ISSUE THREAD

**Issue by Pictocube** [ionic-team/ionic-framework#24733] opened 2022-02-07 16:31 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Since Ionic-6 when a ion-toast is displayed, it steal the focus from the ion-input who was initially focused.
After the toast is dismissed, my ion-input still owns the focus (the CSS property “has-focus” is correctly triggered), but the caret inside the input is missing.
`<ion-input _ngcontent-upn-c145="" hidekeyboard="" type="text" required="" ng-reflect-type="text" ng-reflect-required="" ng-reflect-placeholder="Emplacement ?" class="sc-ion-input-md-h sc-ion-input-md-s md hydrated has-focus">
<input class="native-input sc-ion-input-md" autocapitalize="off" autocomplete="off" autocorrect="off" name="ion-input-2" placeholder="Emplacement ?" required="" spellcheck="false" type="text">
</ion-input>`
Then I'm unable to whrite inside my input without re-select it.

### Expected Behavior

I'm exepected to be able to whrite inside my ion-input while the ion-toast is displayed and keeping the focus after the toast is dissmissed.

### Steps to Reproduce

Create a page with a single input and click on it to focus it.
With a timeout for exemple create a simple ion-toast and present it.
`    const toast = await this.toastController.create({
      message: 'This is a test',
      duration: 2000
    });`
`    toast.present();`
Try to whrite something while the ion-toast is displayed (or after it's dissmissed) without clicking on the input.

### Ionic Info

Ionic:
   Ionic CLI                     : 6.18.1
   Ionic Framework               : @ionic/angular 6.0.5
   @angular-devkit/build-angular : 13.2.2
   @angular-devkit/schematics    : 13.2.2
   @angular/cli                  : 13.2.2
   @ionic/angular-toolkit        : 6.0.0
Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : none
   Cordova Plugins   : no whitelisted plugins

Utility:
   cordova-res : not installed globally
   native-run  : 1.5.0
System:
   Android SDK Tools : 26.1.1
   NodeJS            : v16.13.2
   npm               : 8.2.0
   OS                : Windows 10

### Additional Information

Apparently, this a bug due to tabindex valued to `-1` in the ion-toast

More details here : [https://forum.ionicframework.com/t/ionic-version-6-angular-toast-now-holds-focus-preventing-inputs-from-being-used/218430/5](https://forum.ionicframework.com/t/ionic-version-6-angular-toast-now-holds-focus-preventing-inputs-from-being-used/218430/5)

**Comment by Pictocube** [comment] 2022-02-15 10:27
Hi @liamdebeasi, i tried to reproduce the issue from a blank Ionic starter app. Sadly didn't to succed to reproduce it for the moment.
I tried with :
- adding all my dependancies in the package.json and install them
- recreate the same project / page structure
- adding the same directives and scss properties

There might be a strange behaviour due to the complexity of my app. 
Do you have any suggestion to go deeper in the analysis ?(like configurations files who could be interfering for exemple)

Thank you for your time !

**Comment by tonymccallie** [comment] 2022-02-17 17:15
I am having the same issue, but only on Safari or Firefox. When a toast message is present, I cannot focus my form fields. I cannot reproduce this in a clean app. 

We did upgrade this app from Ionic 5 to 6 and upgraded Angular if that helps.

**Comment by papagei-ma** [comment] 2022-02-18 10:08
@tonymccallie  @liamdebeasi  what do you think about
` const toast = await this.toastController.create({
      message,
    });
    toast.removeAttribute('tabindex');
    await toast.present();`
    it does the trick for me. Any thoughts?

**Comment by papagei-ma** [comment] 2022-02-18 11:46
@miljann995 can you try removing 'tabindex'?

**Comment by papagei-ma** [comment] 2022-02-18 12:00
@miljann995 you can see my comment before, I see. You mean, due to showing a loader while routing to the page in my case, that was reproducible. Yet when I refresh the page, which seems not show a loader, the focus was not possible :). Thanks, I think I can sleep now :D.

**Comment by tonymccallie** [comment] 2022-02-18 14:26
@papagei-ma thank you!

toast.removeAttribute('tabindex');

Worked for me.

**Comment by liamdebeasi** [comment] 2022-02-18 14:33
Thanks, I can reproduce this. We have a focus trapping utility that prevents focus from going outside of elements such as modals and alerts for accessibility purposes. Focus trapping should not happen on `ion-toast`, but because `ion-loading` is presented first the focus trapping is enabled.

**Comment by papagei-ma** [comment] 2022-02-18 14:53
@liamdebeasi oh, thank you.

**Comment by liamdebeasi** [comment] 2022-02-18 16:25
Can everyone try the following dev build and let me know if it resolves the issue?

```
6.0.9-dev.1645200028.2062b87
```

This applies to all Angular, React, Vue, and Core packages. Example:

```
npm install @ionic/angular@6.0.9-dev.1645200028.2062b87
```

**Comment by tonymccallie** [comment] 2022-02-18 16:29
@liamdebeasi That version did resolve the issue for me. It works without having to remove tabindex.

**Comment by miljann995** [comment] 2022-02-18 16:29
@liamdebeasi Bug doesn't occur anymore with the `6.0.9-dev.1645200028.2062b87` version in my demo application.

**Comment by Pictocube** [comment] 2022-02-18 16:39
@liamdebeasi same for me, the issue seems to be resolved with your fix 👏 🚀 
Thank you !

**Comment by liamdebeasi** [comment] 2022-02-22 13:56
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/24816, and a fix will be available in an upcoming release of Ionic Framework.

**Closed** 2022-02-22 13:56 UTC
Labels: package: core, type: bug
