### ISSUE TITLE
feat/bug: Ionic input component change event should only triggered when committed by the user.

### ISSUE THREAD

**Issue by infacto** [ionic-team/ionic-framework#24845] opened 2022-02-24 15:11 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

The `ionChange` event e.g. on `<ion-select>` is always triggered when the value changed. Also if programatically set.

The `ionChange` event e.g. on `<ion-select>` is always triggered when the value changes. Even if set programmatically.

The native `change` event of input, select and textarea is only triggered by user.

> The change event is fired for `<input>`, `<select>`, and `<textarea>` elements when an alteration to the element's value is committed by the user. Unlike the input event, the change event is not necessarily fired for each alteration to an element's value.

https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/change_event

Detect changes by user. Respect the native input behavior.

**Comment by liamdebeasi** [comment] 2022-02-24 16:13
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/19651.

**Closed by liamdebeasi** 2022-02-24 16:13 UTC
Labels: triage
