### ISSUE TITLE
bug: Accessibility issue: Backdrop in ion-popover component has invalid aria-hidden value 

### ISSUE THREAD

**Issue by annamelnyk** [ionic-team/ionic-framework#29773] opened 2024-08-15 03:26 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/docs/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Backdrop (shadow part of ion-popover component) contains attribute **aria-hidden=true**, which is not correct from accessibility purposes.
Console shows error below:
`Blocked aria-hidden on a <ion-backdrop> element because the element that just received focus must not be hidden from assistive technology users. Avoid using aria-hidden on a focused element or its ancestor. Consider using the inert attribute instead, which will also prevent focus. For more details, see the aria-hidden section of the WAI-ARIA specification at ` 

### Expected Behavior

Backdrop (shadow part of ion-popover component) NOT contains attribute **aria-hidden**

### Steps to Reproduce

1. Open the <ion-popover> element
2. Click on backdrop
3. Popover will be dismissed and console error will appear

### Code Reproduction URL

https://stackblitz.com/edit/angular-e2jj3l-tpkxhe?file=src%2Fapp%2Fapp.component.html

### Ionic Info

**Ionic:**

   Ionic CLI                     : 7.1.1
   Ionic Framework               : @ionic/angular 7.5.5
   @angular-devkit/build-angular : 16.0.6
   @angular-devkit/schematics    : 16.0.6
   @angular/cli                  : 16.0.6
   @ionic/angular-toolkit        : 9.0.0

**Capacitor:**
   Capacitor CLI      : 5.0.5
   @capacitor/android : 5.0.5
   @capacitor/core    : 5.0.5
   @capacitor/ios     : 5.0.5

**Utility:**
   cordova-res : not installed globally
   native-run  : 1.7.4

**System:**
   NodeJS : v20.13.1
   npm    : 10.5.2
   OS     : Windows 10

**Comment by dev-charles15531** [comment] 2024-08-15 18:18
I am not able to see any sort of warning or error in my console when I click the backdrop.
I am using the issue reproduction url you sent.

**Comment by annamelnyk** [comment] 2024-08-16 02:25
@dev-charles15531 thank you for quick reply.
To see the error open console in browser devTools, not in Stackblitz.

**I did cross browser testing on Windows 11:**
- Chrome v127 - shows error
- Edge v127 - shows error  
- Mozilla v129 - does not show error

**Comment by boluwatifee4** [comment] 2024-08-16 06:12
is this resolved ?

**Comment by wiktor-wrzaszcz** [comment] 2024-08-20 12:38
Bump, its so annoying while debugging. Please fix it! Seeing it on chrome when closing modal as well.

**Comment by annamelnyk** [comment] 2024-08-21 03:39
Hi ionic-team, is there any updates regarding current issue? Thanks in advance!

**Comment by maniya108** [comment] 2024-08-21 07:24
Hi Team, We are using ionic 8.2.7 core and angular 18.2.0. Our team also facing the same issue while opening modal controller and clicking outside to close (backdrop close).

Please refer the below error.

**Blocked aria-hidden on a <ion-backdrop> element because the element that just received focus must not be hidden from assistive technology users. Avoid using aria-hidden on a focused element or its ancestor. Consider using the inert attribute instead, which will also prevent focus. For more details, see the aria-hidden section of the WAI-ARIA specification at https://w3c.github.io/aria/#aria-hidden.** 

`<ion-backdrop part=​"backdrop" tabindex=​"-1" aria-hidden=​"true" class=​"ios" style>​#shadow-root (open)</ion-backdrop>​`
<img width="1394" alt="image" src="https://github.com/user-attachments/assets/67f570d3-de72-4827-969a-0f5444fc9660">

**Comment by D3rDicke** [comment] 2024-08-21 18:41
Hi, i have the same problem is there any fixes or updates ?

**Comment by ingbioservicios** [comment] 2024-08-23 12:50
Hi, i have the same problem is there any fixes or updates ?

**Comment by vityapro** [comment] 2024-08-23 13:11
`"@ionic/vue": "7.8.6",
"nuxt": "^3.13.0"`
Same issue

**Comment by dangduoc** [comment] 2024-08-24 10:45
I have the same problem. Hope it would get fixed soon, thanks!

**Comment by KeyTurns** [comment] 2024-08-24 13:28
Same here! Would really appreciate if they could solve this, it's highly frustrating.

**Comment by Sagie501** [comment] 2024-08-25 10:17
Same for me

**Comment by m345054** [comment] 2024-08-25 20:12
Same

**Comment by doogie99** [comment] 2024-08-26 19:32
Ditto

**Comment by soroush-gh** [comment] 2024-08-27 13:26
Same for me

**Comment by wrodriguezmethodo** [comment] 2024-08-29 22:28
Same

**Comment by ibilux** [comment] 2024-08-30 07:22
Bump

**Comment by tbence94** [comment] 2024-08-30 23:20
+1

**Comment by rajibhasan11** [comment] 2024-09-02 04:31
> I am not able to see any sort of warning or error in my console when I click the backdrop. I am using the issue reproduction url you sent.

You need to use this version of Chrome Version 128.0.6613.85 (Official Build) (64-bit)

**Comment by rajibhasan11** [comment] 2024-09-02 04:35
Same here I am using ionic 5 / angular 13.

> Blocked aria-hidden on a <ion-backdrop> element because the element that just received focus must not be hidden from assistive technology users. Avoid using aria-hidden on a focused element or its ancestor. Consider using the inert attribute instead, which will also prevent focus. For more details, see the aria-hidden section of the WAI-ARIA specification at https://w3c.github.io/aria/#aria-hidden.

**Comment by fabichacon** [comment] 2024-09-02 14:15
Same here
Ionic 6 / Angular 15

**Comment by jackhipson300** [comment] 2024-09-03 21:47
Same here. Using latest version of Ionic React.

**Comment by averyjohnston** [comment] 2024-09-04 21:35
Not sure if this helps or makes things more confusing, but I'm using Ionic React 8.2.7 and Chrome 128.0.6613.120 on a Windows 10 machine, and I'm seeing the error as well. *However,* it seems to be intermittent; refreshing the page often makes the error stop appearing. I was able to get it to reappear once by clearing my cache and refreshing (ctrl+shift+r) but only once. Not sure what the exact trigger is.

**Comment by brandyscarney** [comment] 2024-09-04 22:12
Thank you for the issue! I was unable to reproduce this using Chrome 126, Firefox 128/129/130 or Safari 17. However, after updating Chrome to 128.0.6613.120 I am able to see the error in the original StackBlitz reproduction.

This seems to be caused by Chrome enforcing accessibility rules more strictly. I am marking this as `needs: investigation` because we will need to investigate the best way to fix this.

**Comment by gasci** [comment] 2024-09-05 05:47
I confirm that I am facing the same issue with the latest version of Chrome.

**Comment by Hambat** [comment] 2024-09-12 19:23
The same here "@ionic/angular": "^8.2.0"

**Comment by thetaPC** [comment] 2024-09-12 23:55
Thank you for submitting the issue! I was also able to reproduce the issue.

The error is happening because `tabindex` and `aria-hidden` are being passed to `ion-backdrop`. The `tabindex` attribute is used to make an element focusable, regardless of value. When `aria-hidden` is applied to an element, then the element is hidden from screen readers. This violates the accessibility standards since `ion-backdrop` would be considered a focusable element but not visible to screen readers.

We'll be implementing a solution soon.

**Comment by zolakt** [comment] 2024-10-16 14:51
Are there any workarounds that would suppress this error, until the proper fix is released?

**Comment by shehzad031248** [comment] 2024-10-20 09:00
I have added "CUSTOM_ELEMENTS_SCHEMA" which resolved my issue.

**Comment by seatechdev** [comment] 2024-10-20 19:13
@shehzad031248  - Can you please post the sample code?

**Closed** 2024-10-22 15:18 UTC
Labels: type: bug

**Comment by shehzad031248** [comment] 2024-10-27 08:51
> @shehzad031248 - Can you please post the sample code?

import { CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
@Component({
  selector: 'app-basic-data-form',
  standalone: true,
  templateUrl: './basic-data.page.html',
  styleUrls: ['./basic-data.page.scss'],
  imports: [CommonModule, IonicModule, ReactiveFormsModule],
  providers: [ModalController, BasicDataService, AlertsService, UtilsService, LoadingService],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})

**Comment by thetaPC** [comment] 2024-10-28 15:09
Thanks for the issue! This has been resolved via https://github.com/ionic-team/ionic-framework/pull/29956 and will be available in an upcoming release of Ionic.
