### ISSUE TITLE
bug: window.Ionic.platforms returns ['mobile', 'mobileweb'] instead of ['desktop'] on chromium based browser

### ISSUE THREAD

**Issue by gongAll** [ionic-team/ionic-framework#29227] opened 2024-03-27 12:38 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

On Chromium based laptop browser, I use isPlatform('mobile') but it always returns true and my app always behaves as a mobile one.

Got no problems on Firefox.

Laptop has touchscreen, which seems to be the main problem here.

### Expected Behavior

On Chromium based desktop browser, I want to use isPlatform('mobile') and for it no return false.

### Steps to Reproduce

1. Open page built with Ionic in a chromium based browser on a laptop with touchscreen
2. In terminal, go to window.Ionic.platforms
3. Check that mobile is present on the array of values

### Code Reproduction URL

any Ionic app, issue is in the device that it is opened with.

### Ionic Info

Ionic:
   Ionic CLI: 7.2.0
   Ionic Framework: @ionic/angular 7.7.4
   @angular-devkit/build-angular: 17.3.1
   @angular-devkit/schematics: 17.0.9
   @angular/cli: 17.3.1
   @ionic/angular-toolkit: not installed

Utility:
   cordova-res: not installed globally
   native-run: not installed globally

System:
   NodeJS: v20.10.0
   npm: 10.2.3
   OS: Linux 6.5

### Additional Information

After seeing the issues that are somewhat related to this one, #25625 #26240, got to [this](https://hover-pointer-media-query.glitch.me/) website, where it seems more or less obvious that the way "isMobile" is set is not compatible with laptops with touchscreens (@media(any-pointer: coarse) will always be true).

My suggestion would be to use @media(pointer: coarse), given that most devices with fine pointers will set them as primary.

**Comment by liamdebeasi** [comment] 2024-03-27 13:27
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/24179.

**Closed by liamdebeasi** 2024-03-27 13:27 UTC
Labels: triage
