### ISSUE TITLE
bug: ion-select/ion-select-options does not work in production 

### ISSUE THREAD

**Issue by Ripwords** [ionic-team/ionic-framework#24058] opened 2021-10-11 19:28 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

While running a dev server ( npm run dev using vite ) ion-select/ion-select-option works as expected with no problems as shown here: 
![image](https://user-images.githubusercontent.com/58784686/136844986-8f35eb85-de88-45ba-bccd-1515f5701997.png)

However after building to production, the ion-select/ion-select-option breaks and fails to work as shown here: 
![image](https://user-images.githubusercontent.com/58784686/136845196-e24791b1-05cc-4aaa-b84d-a5eb2fc668bf.png)
( i have repeatedly clicked on the ion-select component and nothing is showing up )

### Expected Behavior

Expected the built production version to work normally as in the dev version

### Steps to Reproduce

I have created a minimal repo for this issue specifically, and i have also published the production version on netlify to highlight the issue

Github repo : https://github.com/Ripwords/ionic-select-test
Netlify app link : https://condescending-montalcini-9080f2.netlify.app

### Code Reproduction URL

https://github.com/Ripwords/ionic-select-test

### Ionic Info

![image](https://user-images.githubusercontent.com/58784686/136845540-59a22afd-96b3-4903-b65e-e624a9b34d21.png)

### Additional Information

I have another ionic/vue5 application using ion-select and it's working properly so i suspect it's either a vite build or ionic/vue6 problem

**Comment by liamdebeasi** [comment] 2021-10-11 21:50
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/23571.

**Closed by liamdebeasi** 2021-10-11 21:50 UTC
Labels: triage

**Comment by Ripwords** [comment] 2021-10-21 03:38
@aaronksaunders this issue is in the rc1 milestone if I'm not mistaken so it's getting fixed in the next release I think
