### ISSUE TITLE
bug: Ionic React Router should treat `exact` correctly

### ISSUE THREAD

**Issue by puku0x** [ionic-team/ionic-framework#21826] opened 2020-07-27 16:11 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.3.0**

**Current behavior:**

It shows MainPage when the path is `/login`.
```tsx
<IonReactRouter>
  <IonRouterOutlet>
    <Route path="/login" component={LoginPage} exact />
    <Route path="/" component={MainPage} />
  </IonRouterOutlet>
</IonReactRouter>
```

**Expected behavior:**

It should show LoginPage as same as react-router because it has `exact`.

**Steps to reproduce:**

Change the react-router sample from this
```tsx
<BrowserRouter>
  <Switch>
    <Route path="/login" component={LoginPage} exact />
    <Route path="/" component={MainPage} />
  </Switch>
</BrowserRouter>
```
to this,
```tsx
<IonReactRouter>
  <IonRouterOutlet>
    <Route path="/login" component={LoginPage} exact />
    <Route path="/" component={MainPage} />
  </IonRouterOutlet>
</IonReactRouter>
```
then go to `/login`.

**Related code:**

https://codesandbox.io/s/ionic-react-router-v530-exact-does-not-work-5zl06?file=/src/App.tsx

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by elylucas** [comment] 2020-07-27 17:11
Hi @puku0x,

Thanks for the issue.

The difference between your examples using BrowserRouter and IonReactRouter is you are using Switches in the BrowserRouter one, which IonReactRouter doesn't support inside of a IonRouterOutlet.

You should be able to achieve the desired result with some changes to your routes. For instance, if you add an `exact` to your MainPage route it functions correctly in this example:

```
<Route path="/" component={MainPage} exact />
```

Going to close this as its not a bug in the framework, but if you have more questions please ask.

Thanks

**Closed by elylucas** 2020-07-27 17:11 UTC
Labels: triage

**Comment by puku0x** [comment] 2020-07-29 16:29
@elylucas Thank you for your reply. 

I think you will find the problem when you build an app with routes which `/login` for login page and `/**` for pages for authenticated user.

**Comment by Aupourbau** [comment] 2020-08-04 09:24
> @elylucas Thank you for your reply.
> 
> I think you will find the problem when you build an app with routes which `/login` for login page and `/**` for pages for authenticated user.

Exactly what happened to me, had to rollback to a previous version
