### ISSUE TITLE
bug: [v4] Back button works wrong for tabs

### ISSUE THREAD

**Issue by apetushkov** [ionic-team/ionic-framework#18624] opened 2019-06-26 10:20 UTC
# Bug Report

**Ionic version:**

[x] **4.5.0**

**Current behavior:**
Clicking back button navigates to previously active tab

**Expected behavior:**
Clicking back button navigates to page which was active before we navigated to tabs.

**Steps to reproduce:**
Please take a look on [demo](https://apetushkov.github.io/ionic-tab-back-nav-issue/)
We starting from landing page, then going to tabs (tab 1), then click on tab 2.
Now click back button (browser or hardware). 

Actual result: You are on tab 1.
Expected result: You are on initial landing page.

From UX point of view, single tab should not be considered as a separate page - it should be just a state of tabs-holder page.

**Related code:**

A sample application [via GitHub](https://github.com/apetushkov/ionic-tab-back-nav-issue)

Also this demo, deployed to [GitHub pages](https://apetushkov.github.io/ionic-tab-back-nav-issue/)

**Other information:**

**Ionic info:**

```

Ionic:

   Ionic CLI                     : 5.0.0 (C:\Users\mentat\AppData\Local\Yarn\Data\global\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.5.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Utility:

   cordova-res : 0.3.0
   native-run  : not installed

System:

   NodeJS : v10.14.2 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10

```

**Comment by pppp0836** [comment] 2019-06-27 10:04
I think this is not issue, When you click back button on web browser, it  just navigates previous URL ,not a  page in a sense.
    So ,if you wanna jump landing page , you should listen window.onhashchange, See this:[https://stackoverflow.com/questions/25806608/how-to-detect-browser-back-button-event-cross-browser](url)

**Comment by ralscha** [comment] 2019-06-27 14:59
I don't think the back button does the wrong thing. It's just how Angular works and every application has different requirements.

There is an easy solution for this by specifying `skipLocationChange: true`.
```
        return this.navCtrl.navigateRoot(url, {
            animated: true,
            animationDirection: 'back',
            skipLocationChange: true
        });
```

The problem is, and it's also the reason why this is an Ionic issue, there is currently no way to specify `skipLocationChange` (and `replaceUrl`) on the `ion-tabs` component.

https://github.com/ionic-team/ionic/blob/master/angular/src/directives/navigation/ion-tabs.ts#L77-L80

I think it would be nice if these two properties could be specified per tab on the `ion-tab-button` component.
```
<ion-tab-button tab="tab1" [skipLocationChange]="true">
<ion-tab-button tab="tab1" [replaceUrl]="true">
```

**Comment by liamdebeasi** [comment] 2020-07-17 20:12
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. This is have Angular Routing/navigation is designed to work. The back button should bring you back to the previous view. In this case, when going from Tab 1 to Tab 2, clicking the back button should bring you from Tab 2 back to Tab 1. 

We likely will not change the behavior of tabs as this is how they work on native iOS and Android applications. That being said, you could probably attach click events to the tab buttons to manually redirect content. That should allow you to use `skipLocationChange` or `replaceUrl`. Thanks!

**Closed by liamdebeasi** 2020-07-17 20:12 UTC
Labels: triage
