### ISSUE TITLE
bug: Class switching prevents element rendering

### ISSUE THREAD

**Issue by TylerBurnett** [ionic-team/ionic-framework#21865] opened 2020-08-03 00:23 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x** React

**Current behavior:**
When using a switching behavior to change attached classes to elements, the element will then fail to render.

**Expected behavior:**
The element should re-render according to the class it has respectively switched to.

**Steps to reproduce:**
- Create an element with a boolean that switches based on user interaction
- Add a ternary operator to the class attribute of the element that switches to two different classes based on boolean.

**Related code:**

Pre Context: 

This is the switching logic inside of the chip which determines its styling based on if it has been activated (onClick).
```
 <IonChip
      onClick={() => (active ? onRemove('catagory') : setShowActionSheet(true))}
      class={active ? 'CatagoryChip_active' : 'CatagoryChip_inactive'}
    >
```

This is the Css classes its using as apart of the ternary operator:

```
.CatagoryChip_active {
  --background: var(--claim-color-primary);
  --color: var(--ion-color-light);
}

.CatagoryChip_active > ion-icon {
  --color: var(--ion-color-light);
}

.CatagoryChip_inactive {
  --background: var(--ion-color-light);
  --color: var(--ion-color-dark);
}

.CatagoryChip_inactive > ion-icon {
  --color: var(--ion-color-dark);
}
```

Now after investigating further into the runtime code I found that the class switching was, in fact, overwriting shadow classes attached to the component, which was stopping the component from then rendering.

![Error](https://user-images.githubusercontent.com/11090043/89135641-4cd16200-d572-11ea-92c3-22ef66fad50d.gif)

**Other information:**

I believe this isn't of my fault seeing as this code was working perfectly fine just a day ago. But after doing a routine npm update this issue began to appear.

An easy workaround for this issue, for the time being, is to add a an immutable key to the parent container which forces the container and children to re-render. Keep in mind this will cause ionic to throw this error message:

```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
```

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.11.0 (C:\Users\tyler\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/react 5.3.1

Capacitor:

   Capacitor CLI   : 2.1.0
   @capacitor/core : 2.1.0

Utility:

   cordova-res : 0.14.1
   native-run  : not installed

System:

   NodeJS : v14.4.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.7
   OS     : Windows 10
```

**Comment by TylerBurnett** [comment] 2020-08-03 22:16
I reproduced the issue outside of my current project with ease. The tester element is a chip located in tab2 of the project.

[Reproduction.zip](https://github.com/ionic-team/ionic-framework/files/5019035/Reproduction.zip)

**Comment by liamdebeasi** [comment] 2020-08-17 15:01
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. When you switch classes, you are also overriding the classes the Ionic Framework adds. You need to make sure you preserve the the `'ios`' (or `'md'`) ,`'ion-activatable'`, and `'hydrated'` classes. In particular, without the `'hydrated'` class, the component will not be shown.

**Closed by liamdebeasi** 2020-08-17 15:01 UTC
Labels: ionitron: needs reproduction
