### ISSUE TITLE
bug: @ionChange doesn’t fire when change made

### ISSUE THREAD

**Issue by OstrIvan** [ionic-team/ionic-framework#28242] opened 2023-09-27 09:18 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

I have a `ion-textarea` Ionic component. It has a `v-model`, `@ionChange` and a `debounce` property.

Whenever I try to write a text inside the input, the `@ionChange` does not fire the event.
The quick solution I found is to use `@ionInput` instead. In my case it waits for the `debounce` ms and then fires the event.

**Demonstration:**

https://github.com/ionic-team/ionic-framework/assets/111231036/7887778d-ef28-4601-8bb0-44af6c6bbbb8

Looks like `@ionChange` is having some issues, because it does not seem to work in `ion-textarea` nor `ion-input`.

### Expected Behavior

To fire whenever you change the content of the input.

### Steps to Reproduce

Create a Vue.js View file:
`Test.vue`:
```
<template>
  <ion-page>
    <ion-content fullscreen>
      <ion-item class="title" lines="none">
        <h5>Test View</h5>
      </ion-item>

      <ion-card
        class="ios bloque"
        style="box-shadow: none; border-radius: 15px"
      >
        <ion-card-content class="ion-no-padding">
          <ion-grid>
            <ion-row>
              <ion-col size="12">

                <ion-textarea
                  v-model="test.ion_change"
                  :autoGrow="true"
                  placeholder="Event trigger — ionChange"
                  @ionChange="(event) => test2(event)"
                  :debounce="1000"
                ></ion-textarea>

              </ion-col>

              <ion-col size="12">

                <ion-textarea
                  v-model="test.ion_input"
                  :autoGrow="true"
                  placeholder="Event trigger — ionInput"
                  @ionInput="(event) => test2(event)"
                  :debounce="1000"
                ></ion-textarea>

              </ion-col>
            </ion-row>
          </ion-grid>
        </ion-card-content>
      </ion-card>
    </ion-content>
  </ion-page>
</template>

<script>
import { IonContent, IonPage, IonTextarea } from '@ionic/vue';

import { ref } from 'vue';

export default {
  name: 'TestView',

  components: {
    IonContent,
    IonPage,
    IonTextarea,
  },

  created() {},

  setup() {
    return {
      test: ref({}),
    };
  },

  methods: {
    test2(event) {
      console.log(event);
    }
  },
};
</script>

```

### Ionic Info

Ionic:

   Ionic CLI       : 6.20.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 7.4.1

Capacitor:

   Capacitor CLI      : 5.4.1
   @capacitor/android : 5.4.1
   @capacitor/core    : 5.4.1
   @capacitor/ios     : 5.4.1

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.3

System:

   NodeJS : v18.13.0 (/usr/local/bin/node)
   npm    : 8.19.3
   OS     : macOS

**Comment by liamdebeasi** [comment] 2023-09-27 13:17
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/27292.

While we work to fix the issue, you can listen for `@v-ion-change` as a temporary workaround instead of `@ionChange`.

**Closed by liamdebeasi** 2023-09-27 13:17 UTC
Labels: triage
