### ISSUE TITLE
bug: Popover somehow duplicates itself

### ISSUE THREAD

**Issue by EinfachHans** [ionic-team/ionic-framework#23129] opened 2021-04-01 16:44 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

I have a Szenario where i open a Popover that shows some added files. It also offers a Add button to Add more Files. Somehow opening the File Selector from within the popover causes the Popover to duplicate itself.

**Expected behavior:**

Don't duplicate the Popover when opening the File Select.

**Steps to reproduce:**

I added a Repo where i tried to reproduce the Szenario i have in my Project. Do these Steps to reproduce:

1. Run Project
2. Click "Open Modal"
3. Click on one of the "Media" button Images
4. Clicking will cause a File Select to open, select **one** File
5. Click the Media Button again will cause popover to show up
6. Click add Button in Toolbar

**Related code:**

Repo: https://github.com/EinfachHans/ionic-popover-bug

**Other information:**

If i dismiss the Popover before opening the Select, the initial Popover will be dismissed, but the duplicated one will be still there.

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.13.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.6.0
   @angular-devkit/build-angular : 0.1102.3
   @angular-devkit/schematics    : 11.2.3
   @angular/cli                  : 11.2.3
   @ionic/angular-toolkit        : 3.1.0

Utility:

   cordova-res (update available: 0.15.3) : 0.15.1
   native-run (update available: 1.3.0)   : 1.0.0

System:

   NodeJS : v14.15.4 (/usr/local/bin/node)
   npm    : 7.6.3
   OS     : macOS Big Sur
```

**Comment by liamdebeasi** [comment] 2021-04-01 17:35
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. When you click the "+" button in the top right of the popover, you call a `select` method on your `app-file-select` component. That `select` method then fires a click event on `this.input.nativeElement` which is the `input type="file"` element. Because click events bubble, the parent click handler on `div class="action"` fires as well, causing another popover to open. 

To account for this, you should add a click handler on your `input type="file"` that calls `ev.stopPropagation()` on the event that is passed in to prevent further propagation of the current event in the capturing/bubbling phases.

**Closed by liamdebeasi** 2021-04-01 17:35 UTC
Labels: triage

**Comment by EinfachHans** [comment] 2021-04-01 19:52
Damn how silly 😒😂 Sorry for Opening and thanks for explaning!
