### ISSUE TITLE
bug: ion-datetime not properly visible with dark color

### ISSUE THREAD

**Issue by prosidney** [ionic-team/ionic-framework#24410] opened 2021-12-15 11:01 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

when ion-datetime is inside the ion-item with color dark, calendar is not correct visible.

<img width="610" alt="image" src="https://user-images.githubusercontent.com/4601009/146170837-2b1888cc-5b37-416c-b941-c61747eba94b.png">

### Expected Behavior

I expect the ion-datetime adapting to the  dark color for proper visibility 

### Steps to Reproduce

Just use this code example

```
    <ion-item color="dark">
      <ion-datetime color="dark">

      </ion-datetime>
    </ion-item>
```

### Ionic Info

Ionic:

   Ionic CLI                     : 6.18.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.0
   @angular-devkit/build-angular : 12.2.14
   @angular-devkit/schematics    : 12.2.14
   @angular/cli                  : 12.2.12
   @ionic/angular-toolkit        : 5.0.3

Capacitor:

   Capacitor CLI      : 3.3.3
   @capacitor/android : 3.3.3
   @capacitor/core    : 3.3.3
   @capacitor/ios     : not installed

Cordova:

   Cordova CLI       : not installed
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v17.2.0 (/usr/local/Cellar/node/17.2.0/bin/node)
   npm    : 8.1.4
   OS     : macOS Big Sur
   Xcode  : Xcode 13.0 Build version 13A233

**Comment by DominikRoth** [comment] 2021-12-15 13:59
Hi,

i ran into the same problem but couldn't find a pattern when this happens. 

It also happens without darkmode.

**Comment by liamdebeasi** [comment] 2021-12-15 14:07
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/24112. This was fixed via https://github.com/ionic-team/ionic-framework/pull/24385 and will be available in an upcoming release of Ionic.

**Closed by liamdebeasi** 2021-12-15 14:07 UTC
Labels: triage
