### ISSUE TITLE
bug: ion-select-item uses non labelled ion-radio 

### ISSUE THREAD

**Issue by distante** [ionic-team/ionic-framework#27563] opened 2023-05-27 05:35 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Opening an `ion-select` element with `ion-select-option` shows warnings
<img width="577" alt="image" src="https://github.com/ionic-team/ionic-framework/assets/5490201/7e1845b1-660f-44b3-b6f0-f53e9a8b89b9">

### Expected Behavior

`ion-select-option` should pass the content text as label

### Steps to Reproduce

1. Open the developer Tools
2. Go to https://ionicframework.com/docs/api/select#popover
3. Open the select.

### Ionic Info

wasn't able to find out how to run this on an nx monorepo...

**Comment by liamdebeasi** [comment] 2023-05-30 13:19
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/27071.

**Closed by liamdebeasi** 2023-05-30 13:19 UTC
Labels: triage
