### ISSUE TITLE
bug: Vue toast Uncaught TypeError: Cannot set properties of undefined (setting '$lazyInstance$')

### ISSUE THREAD

**Issue by wilhantian** [ionic-team/ionic-framework#24503] opened 2022-01-02 06:29 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

An error will be reported when toast is created in an external ts file：

```
Uncaught TypeError: Cannot set properties of undefined (setting '$lazyInstance$')
    at registerInstance (index-06cd27b1.js?cd96:4)
    at new t (overlays-5f2f4ffc.js?9cdf:4)
    at eval (overlays-5f2f4ffc.js?9cdf:4)
    at async toast (toast.ts?e2e3:4)
registerInstance @ index-06cd27b1.js?cd96:4
t @ overlays-5f2f4ffc.js?9cdf:4
eval @ overlays-5f2f4ffc.js?9cdf:4
Promise.then (async)
createOverlay @ overlays-5f2f4ffc.js?9cdf:4
create @ overlays-5f2f4ffc.js?9cdf:4
toast @ toast.ts?e2e3:4
exeHandler @ index.vue?d776:71
exeHandler @ index.vue?b665:33
eval @ runtime-dom.esm-bundler.js?2725:371
callWithErrorHandling @ runtime-core.esm-bundler.js?d2dd:6737
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js?d2dd:6746
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js?d2dd:6756
invoker @ runtime-dom.esm-bundler.js?2725:357
toast.ts?e2e3:11 Uncaught (in promise) TypeError: t.present is not a function
    at toast (toast.ts?e2e3:11)
```

### Expected Behavior

It can run normally like ionic 5.x

### Steps to Reproduce

src/toast.ts
```ts
async function toast(){
    const t = await toastController.create({
        message: 'hello'
    });
    t.present();
}
```
src/*.vue
```ts
import toast from './toast';

defineComponent({
    setup(){
        onMounted(()=>{
            toast(); // Uncaught TypeError: Cannot set properties of undefined (setting '$lazyInstance$')
        });
    }
})
```

### Ionic Info

Ionic:

   Ionic CLI       : 6.18.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 6.0.1

Capacitor:

   Capacitor CLI      : 3.3.3
   @capacitor/android : not installed
   @capacitor/core    : 3.3.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.5.0

System:

   NodeJS : v14.15.0 (/usr/local/bin/node)
   npm    : 6.14.8
   OS     : macOS Monterey

**Comment by NunoSav** [comment] 2022-01-03 09:40
Your function lacks `async` keyword in its definition, not sure if this is the source of the error...
```
async function toast(){
    const t = await toastController.create({
        message: 'hello'
    });
    t.present();
}
```

**Comment by wilhantian** [comment] 2022-01-04 07:05
> Your function lacks `async` keyword in its definition, not sure if this is the source of the error...
> 
> ```
> async function toast(){
>     const t = await toastController.create({
>         message: 'hello'
>     });
>     t.present();
> }
> ```

Actually there is `async` in my code, Actually there is async in my code.

**Comment by sean-perkins** [comment] 2022-01-04 20:56
Hello @wilhantian thanks for reporting this issue.

I'm currently unable to replicate your issue with the provided example. Can you provide an example to reproduce your issue?

Here's a repo that I created with your information: https://github.com/sean-perkins/gh-24503-vue-toast and the toast displays correctly on mount.

**Comment by wsamoht** [comment] 2022-01-06 15:43
I am also seeing this error but with the `loadingController`. I cannot replicate this for the `toastController`.

Here is a project with examples of both.

https://github.com/wsamoht/ionic-gh-24503

**Comment by wsamoht** [comment] 2022-01-06 16:39
I just figured out the fix for this. We need to import from `@ionic/vue` and not `@ionic/core`. That is why my `toastController` was working just fine.

**Comment by sean-perkins** [comment] 2022-01-06 19:08
> I just figured out the fix for this. We need to import from `@ionic/vue` and not `@ionic/core`. That is why my `toastController` was working just fine. Not sure if it is still a bug in `ionic/core`.

Great discovery, thanks!

The Vue package uses the custom elements build of `@ionic/core` web components. The wrappers of the `@ionic/vue` package will define the custom element when `.create()` is called for the controller. 

This shouldn't really be a problem for `@ionic/core`, since you would be required to define the custom elements before mount in your application of choice (if not using our wrappers). 

I'm going to close this issue out for now 👍  thanks again!

**Closed by sean-perkins** 2022-01-06 19:08 UTC
Labels: ionitron: needs reproduction

**Comment by filiphecarvalho** [comment] 2022-01-06 19:45
For those who are having the same problem in react, the solution I found was to import from @ionic/core/components and not from @ionic/core.
