### ISSUE TITLE
bug: reflected aria-* attributes are not updated

### ISSUE THREAD

**Issue by darrylnoakes** [ionic-team/ionic-framework#28036] opened 2023-08-21 21:55 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v6.x

### Current Behavior

I apply `aria-pressed="false"` to an `ion-button`.
The attribute is reflected to the inner native button, as expected.
I update the attribute on the `ion-button` to `"true"`.
The attribute is not changed on the inner button, leading assistive technology to announce the incorrect state.

The same applies with other attributes, such as `aria-label`.

### Expected Behavior

The attribute should be updated on the inner button.

### Steps to Reproduce

1. Apply `aria-pressed="false"` to an `ion-button`.
2. Update the attribute programmatically to `"true"`.
3. Observe that the attribute is not updated on the inner button.

### Ionic Info

```
Ionic:

   Ionic CLI       : 6.16.3 (C:\Users\Darryl\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/vue 6.7.5

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v18.15.0 (C:\Users\Darryl\AppData\Local\Volta\tools\image\node\18.15.0\node.exe)
   npm    : 9.5.0
   OS     : Windows 10
```

Actually Windows 11.

### Additional Information

This means I cannot make accessible toggle buttons in any practical way, and currently will have to remove all the work I had done before I discovered this.

**Comment by liamdebeasi** [comment] 2023-08-22 13:05
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/27477. The linked issue references `ion-input`, but this bug applies to more than just `ion-input` as noted here.

**Closed by liamdebeasi** 2023-08-22 13:05 UTC
Labels: triage
