### ISSUE TITLE
bug: The effect displayed on the web terminal is the same as that displayed on the mobile terminal

### ISSUE THREAD

**Issue by 5tiaowu** [ionic-team/ionic-framework#27792] opened 2023-07-13 10:26 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

![image](https://github.com/ionic-team/ionic-framework/assets/108533707/0bb0312f-a5e3-4f07-b246-59cc95ccce05)

### Expected Behavior

The effect displayed on the web terminal is the same as that displayed on the mobile terminal

### Steps to Reproduce

ionic build
ionic capacitor add android

### Ionic Info

没有任何输出

**Comment by 5tiaowu** [comment] 2023-07-13 11:09
![image](https://github.com/ionic-team/ionic-framework/assets/108533707/b8daf20f-06dd-4f51-ad5c-3d5b5d803e28)

**Comment by 5tiaowu** [comment] 2023-07-13 11:10
![image](https://github.com/ionic-team/ionic-framework/assets/108533707/5af5f3c0-6fd2-4de3-838c-bec5567faffd)

**Comment by 5tiaowu** [comment] 2023-07-13 13:08
https://github.com/5tiaowu/MagicHands_Env/releases/download/1/demo.zip
This compressed package contains the complete code, including the built android and ionic projects, you can download and see if you can fully reproduce the problem

**Comment by 5tiaowu** [comment] 2023-07-13 13:36
> Thanks for the issue! This issue has been labeled as `needs reproduction`. This label is added to issues that need a code reproduction.
> 
> Please reproduce this issue in an Ionic starter application and provide a way for us to access it (GitHub repo, StackBlitz, etc). Without a reliable code reproduction, it is unlikely we will be able to resolve the issue, leading to it being closed.
> 
> If you have already provided a code snippet and are seeing this message, it is likely that the code snippet was not enough for our team to reproduce the issue.
> 
> For a guide on how to create a good reproduction, see our [Contributing Guide](https://ionicframework.com/docs/contributing/how-to-contribute#creating-a-good-code-reproduction).
> 

已经上传

**Comment by 5tiaowu** [comment] 2023-07-14 06:36
hello

**Comment by 5tiaowu** [comment] 2023-07-14 13:32
还在吗

**Comment by liamdebeasi** [comment] 2023-07-14 13:51
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The problem here is you did not import IonButton, IonInput, and IonItem. As a result, when building for production those components were not included in your final bundle. This resulted in the reported behavior. Importing those components in the relevant files fixes the issue.

**Closed by liamdebeasi** 2023-07-14 13:51 UTC
