### ISSUE TITLE
bug: interactive items in ion-item unexpectedly being focused with delegatesFocus

### ISSUE THREAD

**Issue by larsblumberg** [ionic-team/ionic-framework#21982] opened 2020-08-26 15:10 UTC
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
On Safari in macOS or iOS, `IonInput` (`ion-input`) steals focus when its value gets changed programmatically.

**Expected behavior:**

`ion-input` doesn't take the focus.

**Steps to reproduce:**
The following code snippet reproduces the effect that when an `ion-input`’s value got changed progammatically, here via a button click, then the `ion-input` will receive focus automatically as an effect. This effect is only observable within an `ion-item` container.

Apart from the fact that this might be unwanted and thus should be controllable by the programmer, it also comes with the side effect of the virtual keyboard popping up since the input receives focus. That’s only acceptable if the user sets focus explicitely on the input. However in this case, the input surprisingly "steals" the focus.

**Related code:**

```jsx
const Test = () => {
  const [value, setValue] = useState("")
  return <IonItem>
    <IonInput value={value} onIonChange={e => setValue(e.detail.value)} />
    <IonButton onClick={() => setValue("foo")}>foo</IonButton>
  </IonItem>
}
```

Full demo project available here: https://github.com/larsblumberg/ion-input-focus-stealing-on-safari

**Other information:**

Effect only observable when input is contained within an `ion-item` and only in Safari on macOS and iOS.

**Ionic info:**

```
Ionic:
   Ionic CLI       : 6.11.1 (/Users/lars/.config/yarn/global/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.2.2

Capacitor:
   Capacitor CLI   : 2.0.2
   @capacitor/core : 2.2.0

Utility:
   cordova-res : not installed
   native-run  : not installed

System:
   NodeJS : v14.4.0 (/usr/local/Cellar/node/14.4.0/bin/node)
   npm    : 6.14.4
   OS     : macOS Catalina
```

**Comment by liamdebeasi** [comment] 2020-08-26 15:34
Thanks for the issue. Can you reproduce this in a blank Ionic starter app and provide a link to the GitHub repo?

**Comment by larsblumberg** [comment] 2020-08-26 19:22
Here's a full Ionic app which reproduces this issue on Safari in macOS and iOS: https://github.com/larsblumberg/ion-input-focus-stealing-on-safari

**Comment by larsblumberg** [comment] 2020-08-28 08:10
@liamdebeasi If you have any workaround in mind that I could apply, that would be helpful. Due to this issue our iOS app has this awkward behavior that the virtual keyboard opens when the button is tapped (which changes an input value).

**Comment by larsblumberg** [comment] 2020-09-11 18:59
thanks for the update

**Comment by larsblumberg** [comment] 2020-09-25 08:34
I've upgrade this issue's [demo app](https://github.com/larsblumberg/ion-input-focus-stealing-on-safari) to `@ionic/react` v. `5.3.3` as [its release document](https://github.com/ionic-team/ionic-framework/releases/tag/v5.3.3) states that the other, related issue #22307 (linked by @liamdebeasi) addresses the same underlying bug. However, the behavior I'm describing here isn't fixed and it's still an issue (bug).

**Comment by liamdebeasi** [comment] 2020-09-25 12:26
I can reproduce. Looks like we need to account for other focusable elements besides `ion-input` and `ion-textarea` as well.

**Comment by brandyscarney** [comment] 2020-09-29 16:11
@liamdebeasi So this was definitely introduced by `5.1.1` aka adding `delegatesFocus` to item in order to fix tabindex not properly being passed down, but I don't think it's related to the code here: https://github.com/ionic-team/ionic-framework/blob/d03807a44353af2b2906c6bcbafc2ccadaee3aa3/core/src/components/item/item.tsx#L180-L212

That code was added because the input was "kind of" getting focus but not really - the keyboard was opening when the item was pressed but the input didn't have focus. So that just made it so the input actually received the focus it was supposed to have.

In my testing of this issue, the input is getting focus *only* on the first button click, *only* when the value changes, and *only* in Safari. This always evaluates to false since the event target is the `ion-button` so it isn't actually hitting this at all: https://github.com/ionic-team/ionic-framework/blob/d03807a44353af2b2906c6bcbafc2ccadaee3aa3/core/src/components/item/item.tsx#L191

Has this been tested with iOS 14? I think it may be another webkit bug with delegatesFocus. 

Let me know if I'm misunderstanding this!

**Comment by larsblumberg** [comment] 2020-10-08 14:07
> Has this been tested with iOS 14?

On iOS 14.0 the bug still manifests.

As well as on MacOS, Safari 14.0

**Comment by xclusive36** [comment] 2020-11-27 22:03
To force ion-input to not steal focus,
Set ion-button with attribute  tabIndex="1",
Set ion-input with attribute  tabIndex="2"

`<Ion-Item>
    <ion-input tabIndex="2"></ion-input>
    <ion-button slot="end" tabIndex="1">Go</ion-button>
</ion-item>`

As a side effect, the ion-button will take on a border when focused.
Add to css to remove the border.

`ion-button:focus{
    outline: none;
}`

**Comment by arnotixe** [comment] 2021-01-07 22:36
Same here, angular 10, capacitor+ionic5. Clicklistener on ion-avatar silently fails (is not trigged) when sticking an ion-input into the same ion-item as the ion-avatar. Screenshot:
![image](https://user-images.githubusercontent.com/500938/103952640-c1569100-510e-11eb-97d4-cd882dd8a5ba.png)

**Comment by floifyed** [comment] 2021-05-03 19:27
Running Ionic React v5.5.4 and am still seeing this issue with textareas. 

I have a page with a text input and a text area, and clicking between the two items I see the focus jump back to the textarea.

**Comment by Suxsem** [comment] 2022-01-27 11:01
@liamdebeasi any news? thank you!

**Comment by grantmk** [comment] 2023-08-29 06:19
Same issue ion Mac / Safari. Due to following structure, clicking anywhere in the content area would snap focus to the input. Also meant user couldn't select and copy text in the content area (_and we know that users hate being restricted from using your app in ways you didn't intend..._)

```
<ion-reorder-group>
  <ion-item>
    <ion-card>
      <ion-input>
      <content>. <!-- Clicking anywhere in here (including buttons) snaps focus to ion-input above -->
```
      
Solved this by adding tabindex="0" to the container card:

`<ion-card tabindex="0">`

The only difference for the user is that keyboard tabs now include the whole card on the way to actual inputs. Can't foresee any other issues but happy to be corrected if there are.

**Comment by alexbainbridge** [comment] 2023-09-21 07:35
Another workaround is change ion-item to a div with display:flex

**Comment by liamdebeasi** [comment] 2024-03-06 16:00
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/29091, and a fix will be available in an upcoming major release of Ionic Framework.

**Closed by liamdebeasi** 2024-03-06 16:00 UTC
Labels: package: core, type: bug
