### ISSUE TITLE
bug: a11y - Action sheet buttons Are Not Recognized Controls

### ISSUE THREAD

**Issue by gurpreetonebcg** [ionic-team/ionic-framework#23601] opened 2021-07-12 05:28 UTC
# Bug Report

**Ionic version:**

```
@ionic/angular 5.6.0
```

**Current behavior:**

When using VoiceOver or Talkback and Focused on any of the buttons in the action sheet such as cancel button, they are not recognized as controls & are not informing user that action need to perform to activate the button.

**Expected behavior:**

All UI components to include buttons will be recognized controls. The screen reader will announce such as “cancel button double tap to activate”.

**Steps to reproduce:**

Take the code from attached link or install .apk provide in attached link, start talk back screen reader open app and navigate to action sheet & open the action sheet & navigate to the buttons in action sheet  you will observe that screen reader is only announcing it as button & not providing instruction to activate the button.

[Download .apk here](https://drive.google.com/file/d/1IOanXH8NcaVeYhiTrfjEveQBrpMH8IhI/view?usp=sharing)

**Related code:**

[Downlead code here](https://drive.google.com/file/d/1TfR-9kxiYYeVQkr6WOEjHaSuN_ZIq9my/view?usp=sharing) 

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.11.8
   Ionic Framework               : @ionic/angular 5.6.0
   @angular-devkit/build-angular : 0.1101.4
   @angular-devkit/schematics    : 11.1.4
   @angular/cli                  : 11.1.4
   @ionic/angular-toolkit        : 3.1.0

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : android 9.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 4 other plugins)

Utility:

   cordova-res : 0.11.0
   native-run  : 1.0.0
```

**Comment by liamdebeasi** [comment] 2021-07-12 12:50
Thanks for the issue. Can you please provide some steps to reproduce the issue? I am testing this on VoiceOver on macOS and it is announcing instructions on how to activate the controls. Additionally, I can reproduce this behavior with VoiceOver on iOS, but this behavior is the same as just using a regular `<button>` element without Ionic Framework, so it appears to be intended.

Also it would be helpful if you provided what browser/operating system version you are testing this on.

**Comment by gurpreetonebcg** [comment] 2021-07-21 10:14
Thanks for reply,

We have tested this on iPhone 7 with OS 13.5. We have found that all buttons are reader as button & provided the instructions on how to activate them, but buttons under action sheet are not announced such.

For example in provided code if you focus on Modal button, it will provide instructions on how to activate but in action sheet its not working as expected.

I guess the behavior should be consistent throughout, as it is announcing the instructions with <ion-button> but not with <button>

**Comment by liamdebeasi** [comment] 2021-07-22 13:19
Thanks for the additional information. Are you able to test on a device running iOS 14? The behavior I am experiencing is that VoiceOver does not read the instructions to activate a button on iOS 14+, so perhaps the behavior you are experiencing is a bug in iOS 13.

For both `ion-button` and a native `button` VoiceOver will announce the button and its role, but will not give instructions on how to activate it.

**Comment by gurpreetonebcg** [comment] 2021-08-02 06:51
Am testing this on android 10, Please refer to the attached video you will see all the button are recognized as buttons & screen reader announce them as "Button double tap to activate", but the buttons inside the action sheet like Delete, Share, Cancel buttons are just announced as "Button" they are not recognized as controls & not announce as "Double tap to activate."
Video: https://drive.google.com/file/d/1qAJ-jLERUnsiieNZRsM-dTt2YG8RRwA5/view?usp=sharing

**Comment by liamdebeasi** [comment] 2022-05-03 14:28
Thanks for the issue and apologies for the delay. I took a closer look into this issue. It turns out that the behavior you were seeing was related to a bug in the Chromium webview that has since been resolved.

I tested your app on the latest version of Chrome with Android 7 and Android 12 and was not able to reproduce the issue.

When it comes to testing with a simulator, we recommend only using simulators that have "Google Play Services" enabled. The reason for this is these devices have webviews that can update. Simulators without "Google Play Services" are typically stuck on webviews that are years old.

In the screenshot below, the "Pixel 4", "Pixel 3a", "Pixel 3", and "Pixel 2" devices have Google Play Services as indicated by the Google Play logo in the "Play Store" column.

![image](https://user-images.githubusercontent.com/2721089/166472478-e34acf41-fd06-4a79-b899-54ec95ea2fb7.png)

------

I am going to close this as the issue appears to be resolved. Please feel free to open a new issue if you run into any other problems. Thanks!

**Closed by liamdebeasi** 2022-05-03 14:28 UTC
Labels: triage
