### ISSUE TITLE
bug: platform is detect as mobile when using a desktop with touchscreen enable

### ISSUE THREAD

**Issue by youri-guacalab** [ionic-team/ionic-framework#22693] opened 2020-12-18 11:25 UTC
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**
On windows laptop computers that have a touchscreen monitor, `platform.is('mobile')` returns true.

**Expected behavior:**
In the case describe above, `platform.is('mobile')` should return false.

**Steps to reproduce:**
Just call `platform.is('mobile')` on windows laptop computers with touchscreen enable. It is caused by `window.matchMedia('(any-pointer:coarse)').matches`. As touch screen is disabled, it works fine.

**Related code:**
A stackblitz example (it requires a touchscreen monitor): [https://stackblitz.com/edit/ionic-angular-v5-kfazhu](https://stackblitz.com/edit/ionic-angular-v5-kfazhu)

**Comment by liamdebeasi** [comment] 2020-12-18 14:37
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/19942.

**Closed by liamdebeasi** 2020-12-18 14:37 UTC
Labels: triage

**Comment by youri-guacalab** [comment] 2020-12-18 14:41
Sorry, I missed that. Thank you.
Is there any workaround ?

**Comment by liamdebeasi** [comment] 2020-12-18 14:42
You can try this: https://github.com/ionic-team/ionic-framework/issues/19942#issuecomment-580403531
