### ISSUE TITLE
bug: Ionic Vue Router opens in-app Safari instead of changing pages

### ISSUE THREAD

**Issue by Ripwords** [ionic-team/ionic-framework#22802] opened 2021-01-21 03:03 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

I was working on an app and i could not get IonicVueRouter to switch tabs like the normal VueRouter would, instead the IonicVueRouter opens the in-app safari on iOS 

https://user-images.githubusercontent.com/58784686/105276782-1ac5c200-5bdd-11eb-9449-4c6c94b7292e.mov

I suspected i might have done something wrong so i started from scratch and used Ionic tabs template fresh out of the CLI without changing any code, but i am still getting the same behavior. Here's a recording of what it looks like with the Ionic tabs template 

https://user-images.githubusercontent.com/58784686/105274102-75f4b600-5bd7-11eb-8d0d-00f84b205c7c.MP4

I was unable to debug this on chrome or iOS safari, as the application works fine on browsers, the problem only arises when i use "add to home screen" and install it on iOS

**Expected behavior:**

The expected behavior is for ionic app to change pages without opening the in-app safari 

**Steps to reproduce:**

The only thing i did to get this behavior is to use this CLI command:
`ionic start AppName tabs --type vue`
and then i followed the docs to convert my project into js from ts

This behavior was also produced when i build the application from the blank template and implementing ionic vue router manually.

I tried it on the only android device i can find and an old iOS12 device which this problem did not occur, is it possible that it is because of the latest iOS version?

**Related code:**

```
ionic start AppName tabs --type vue
```
Add to home screen using safari on iOS14.2 and iOS14.3

**Other information:**

iOS 14.3 (18C66) - iPhone 11
iOS 14.2 - iPad 7th Gen
iOS  13.6.1 - iPhone 7th Gen

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.12.3 (C:\Users\teohj\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/vue 5.5.2

Capacitor:

   Capacitor CLI   : 2.4.6
   @capacitor/core : 2.4.6

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.18.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.5
   OS     : Windows 10

```

**Comment by liamdebeasi** [comment] 2021-01-21 14:33
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/19890.

**Closed by liamdebeasi** 2021-01-21 14:33 UTC
Labels: triage

**Comment by liamdebeasi** [comment] 2021-01-21 14:50
The problem is that your app does not have a `manifest.json` file. I recommend following our PWA guide here: https://ionicframework.com/docs/vue/pwa
