### ISSUE TITLE
bug: [v4](ion-select)The list in the popover is hidden

### ISSUE THREAD

**Issue by cedcn** [ionic-team/ionic-framework#28741] opened 2023-12-20 08:20 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v4.x

### Current Behavior

Chrome Version: 120.0.6099.109 (latest)
![SCR-20231220-mg2](https://github.com/ionic-team/ionic-framework/assets/11457566/e7346cd8-4520-46cc-a1b5-3d496353c164)

### Expected Behavior

normal

### Steps to Reproduce

visit https://ionicframework.com/docs/v4/api/select then click the second item

### Ionic Info

nothing

**Comment by liamdebeasi** [comment] 2023-12-20 14:14
Thanks for letting us know! Unfortunately, Chrome shipped a `popover` attribute that conflicts with the popovers in older versions of Ionic. We don't maintain Ionic v4 anymore, but I think it's worth updating the docs to note this limitation. I'm going to close this since this is not a bug in Ionic, bug I'll make sure the docs get updated.

**Closed by liamdebeasi** 2023-12-20 14:14 UTC
Labels: triage
