### ISSUE TITLE
bug: datetime doesn't scroll correctly

### ISSUE THREAD

**Issue by stonewoodman** [ionic-team/ionic-framework#24500] opened 2021-12-31 14:02 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

ion-datetime: 
If you scroll horizontally or use the buttons to swipe, no new panels were created and you can no select a day from other months.
The date panel has only the current, previous and next month, because the IntersectionObserver was not fired. 

I changed the threshold to 0.99 instead of 1 and it works.
This behavior is only in Chrome and Android WebView. In Firefox works both 1 and 0.99 correctly.

### Expected Behavior

If you scroll horizontally or use the buttons to swipe, the other months should appear.

### Steps to Reproduce

npm start
http://localhost:3333/src/components/datetime/test/basic

### Ionic Info

Ionic:

   Ionic CLI : 6.16.3

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v14.17.1
   npm    : 6.14.13
   OS     : Windows 10

**Comment by jhonnathanH** [comment] 2022-01-03 00:12
same issue @stonewoodman how u fix?

**Comment by stonewoodman** [comment] 2022-01-03 00:21
Hi @jhonnathanH,
i created a Pull-Request #24501
There a no other workaround for this bug

**Comment by hatsantos** [comment] 2022-01-03 19:57
Same issue... This also happens in my app.

This behavior occurs in Chrome (96.0.4664.110) and also on Android WebView (96.0.4664.104). 
In other browsers like Firefox or Edge it seems to work.

If I force the component mode to "ios" <ion-datetime mode="ios"> the problem does no happen in Chrome, only in the Android device (webview).

**Comment by hatsantos** [comment] 2022-01-03 21:30
@stonewoodman I tried to apply your fix... but the bug steal persists when running on a android device:

![image](https://user-images.githubusercontent.com/36542752/147982345-15b70923-9385-448c-ae3e-882c2870b02c.png)

If mode "ios" mode is set even in a Android, shouldn't the other value also be 0.99?

**Comment by stonewoodman** [comment] 2022-01-04 12:06
I will take a closer look again.

I think that the values should not depend on the mode, but on the browser engine.

**Comment by hatsantos** [comment] 2022-01-04 12:19
I hardcoded the values [0.7, 0.99] : 0.99 in the www output and run the app on a Android device.

I added two different datetime inputs,  with:

```
<ion-datetime mode="ios">
<ion-datetime mode="md">
 ```
 
This way it seems to work in both cases. But you can test it your self, and see if this makes sense.

**Comment by stonewoodman** [comment] 2022-01-04 21:00
I must close my pull request (#24501), because the value 0.99 is not the perfect fix and works not correctly as i thought.
Currently I have no fix for this issue.

**Comment by amandaesmith3** [comment] 2022-01-06 15:17
Thanks for the issue! Are you, by chance, using a monitor with the display scaling set to something besides 100% (a 4K monitor for example) or do you have the browser zoomed in? I'm wondering if this is a duplicate of https://github.com/ionic-team/ionic-framework/issues/23985, since I can't replicate the issue except by one of those methods.

If not, could you post a video going through the steps you're taking, so I can be 100% sure I understand the issue?

**Comment by hatsantos** [comment] 2022-01-06 16:56
The bug happens in Chrome (works in Firefox and Edge), but I'm only using the browser while developing the app.
I'm using a 2K monitor for developing.

But the main and real issue is Android. My testing device is a OnePlus 5T with Android 10 and this happens on the device.

**Comment by sufian1985** [comment] 2022-01-06 18:30
Just to add here. I have tested this on android emulator and actual android device (multiple) and the issue persists

**Comment by amandaesmith3** [comment] 2022-01-06 18:57
I'm still unable to replicate, unfortunately. I tried my physical Galaxy S10e on Android 11, and an emulated OnePlus 5T on Android 10, both with Chrome. Could you post a video showing how to trigger the bug, so I can be absolutely sure we're on the same page? I want to eliminate as many variables as possible.

**Comment by stonewoodman** [comment] 2022-01-06 20:19
@amandaesmith3 
The Android WebView on my smartphone (Galaxy S10) was updated to version 97.0.4692.70 on 4th January.
I can no longer reproduce this bug. It works correctly.

**Comment by hatsantos** [comment] 2022-01-06 20:57
I prepared a demo app to reproduce the bug.

Just create a Angular Tab app from de ionic CLI and made a few changes so I could explain and show the problem.
[TesteIonic6IonDatetime.zip](https://github.com/ionic-team/ionic-framework/files/7824559/TesteIonic6IonDatetime.zip)

As suggested, I also recorded a video. In the video I'm running the app on Edge and also Chrome.

On Android I'm running the app on my testing device, a OnePlus 5T with Android 10 and the latest available webview udpate.

https://user-images.githubusercontent.com/36542752/148450730-84d5cfac-b970-4697-915f-07478b9fafcf.mp4

**Comment by liamdebeasi** [comment] 2022-01-07 16:15
Hi everyone,

This appears to be the same issue as https://github.com/ionic-team/ionic-framework/issues/24305. The behavior in question is a bug in Chrome and has since been resolved in Chrome 97, which was released on January 4th, 2022. Your browser/webview should update automatically in the coming days in most cases, but you can also manually update via the Google Play Store. Thank you!

**Closed by liamdebeasi** 2022-01-07 16:15 UTC
Labels: triage

**Comment by sufian1985** [comment] 2022-01-12 13:45
https://share.getcloudapp.com/Wnuqby2v

@sufian1985 as we can see in the above video that when I click on left arrow , I move to the previous month but when I click on right arrow , I am unable to move to the next month
