### ISSUE TITLE
bug: Long pressing ion-button doesn't emit click event but set the button to active (on Android 12)

### ISSUE THREAD

**Issue by darron1217** [ionic-team/ionic-framework#24801] opened 2022-02-16 09:02 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [X] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Long pressing ion-tab-button set the button color to active but doesn't navigate once released. The tab before the long press is still opened and also have the active color, that means there are two tabs with active color..

### Expected Behavior

The tab should either switch to the newly long pressed tab or the current one should still be active ignoring the long pressed tab and only one single active color should be present.

### Steps to Reproduce

Create a tab view with four tab-buttons long press any tab button that is currently not active for about 5 secs then release. (on Android Device)

### Ionic Info

```
Ionic:

   Ionic CLI       : 6.18.1
   Ionic Framework : @ionic/react 6.0.3

Capacitor:

   Capacitor CLI      : 3.3.3
   @capacitor/android : 3.3.3
   @capacitor/core    : 3.3.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.5.0

System:

   NodeJS : v14.18.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.15
   OS     : Windows 10
```

### Additional Information

previous issue #19263

**Comment by darron1217** [comment] 2022-02-17 02:20
@liamdebeasi 
I found that this issue occurs on Android 12.0
But it wasn't reproduced on Android 8.1

**Comment by darron1217** [comment] 2022-02-17 04:20
I've just reproduced it with ionic tabs stater template. (tested on Android 12)
![Animation](https://user-images.githubusercontent.com/8064923/154404568-9c41b4e0-3fe5-4aeb-a81f-f6f7a1e5a255.gif)

**Comment by vimalkumar015** [comment] 2022-02-18 08:43
@liamdebeasi added the [reproduction repo link](https://github.com/vimalkumar015/Long-press-tab-button-repro) to the issue.

**Comment by liamdebeasi** [comment] 2022-02-24 14:53
Apologies for the delay. What version of the Chrome WebView are you running when testing your app?

I am testing on `98.0.4758.101` and I cannot reproduce this behavior.

**Comment by vimalkumar015** [comment] 2022-02-25 15:13
while running in chrome browser no issues. I encountered the issue in Android 12.

**Comment by liamdebeasi** [comment] 2022-02-25 15:14
When you run an Ionic app on Android 12, you are running on a version of the Chrome WebView.

I am interested in knowing what version of the webview you are running. You can find this by logging `window.navigator.userAgent` when inspecting the app with Chrome Dev Tools.

**Comment by vimalkumar015** [comment] 2022-02-25 15:23
mine is Chrome/91.0.4472.114

**Comment by liamdebeasi** [comment] 2022-02-25 15:26
Thanks! Can you try updating your webview to the latest version? There was a similar issue with Chrome 91 that was reported several months ago (see: https://github.com/ionic-team/ionic-framework/issues/23665). It seems likely that this was fixed in a newer version of the webview.

You can update the webview in the Google Play app. It should be called something like "Android System WebView".

**Comment by vimalkumar015** [comment] 2022-02-25 15:52
Yes, after updating there is no issue occurrence.

**Comment by liamdebeasi** [comment] 2022-02-25 16:03
Great! I am going to close this since the issue here is with the Chrome WebView and is resolved by updating.

**Closed by liamdebeasi** 2022-02-25 16:03 UTC
Labels: triage

**Comment by darron1217** [comment] 2022-02-26 03:00
@liamdebeasi 
I've tested it with Android Webview `98.0.4758.101` on Samsung Galaxy note 10+ device.
I guess this issue is related with manufacturer. But I hope we can find out the way to make ionic compatible with variable manufacturer..
So... would you mind re-opening this issue?

**Comment by liamdebeasi** [comment] 2022-02-28 13:52
Manufacturer-specific bugs are not things we typically provide workarounds for.

Are you able to reproduce this on non-Samsung Galaxy Note devices?
