### ISSUE TITLE
bug: iOS 14 device continued scrolling over ion-content/ion-tabs will get hang

### ISSUE THREAD

**Issue by eun-choi** [ionic-team/ionic-framework#22205] opened 2020-09-29 17:31 UTC
# Bug Report

**Ionic version:**
[x] **5.3.4**

**Current behavior:**
Only iOS 14 devices have issues with scrolling.
The x-axis and y-axis scroll recognition on ion-content is not smooth.
And if i trying to scroll over and over again, it gets hang.
This occurs especially frequently in tabbed screens via ion-tabs.
FYI, explicitly adding pointer-events, z-index, will-change or changing 2d transform has not been fundamentally resolved.

**Expected behavior:**
There is no problem with Android devices or below iOS 13.7
As with Android or iOS 13, the scroll should continue without any problems.

**Steps to reproduce:**
1) Create an ion-tabs structure.
2) Make the ion-content a long scrollable area in one of the ion-tabs.
3) E.g, create over 1000 card content using *ngFor and ion-card.
4) After build, run on iOS 14 device.
5) The app freezes after repeated scrolling.

**Ionic info:**
```
Ionic:

   Ionic CLI                     : 6.11.9 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.3.4
   @angular-devkit/build-angular : 0.1001.3
   @angular-devkit/schematics    : 10.1.3
   @angular/cli                  : 10.1.3
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : android 9.0.0, ios 6.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 36 other plugins)

Utility:

   cordova-res                          : 0.15.1
   native-run (update available: 1.2.0) : 1.1.0

System:

   Android SDK Tools : 26.1.1 (/Users/Library/Android/sdk)
   ios-deploy        : 1.10.0
   ios-sim           : 8.0.2
   NodeJS            : v12.18.4 (/usr/local/bin/node)
   npm               : 6.14.8
   OS                : macOS Catalina
   Xcode             : Xcode 12.0.1 Build version 12A7300
```

**Comment by eun-choi** [comment] 2020-09-29 17:50
FYI, Finding the part specified by translateZ() or translate3d() and changing it to 2d transform or removing it has some effect.
Also, explicitly adding pointer-events: auto and will-change: transform it has some effect.
However, neither can fundamentally solve the problem.

**Comment by liamdebeasi** [comment] 2020-09-29 18:03
Hey there, can you provide a GitHub repo I can use to reproduce this issue? Given the scale of how many cards you are using it would be good to see an example rather than some code snippets.

**Comment by eun-choi** [comment] 2020-10-01 16:56
@liamdebeasi After trying various methods, I found the most effective one.
1) Adjust the scroll-x and scroll-y values in ion-app_8.entry.js ​​as shown below:
```
.scroll-y,
.scroll-x {
  -webkit-overflow-scrolling: touch;
  will-change: scroll-position, transform;
  pointer-events: auto;
}

.scroll-y {
  touch-action: pan-y;
  overflow-y: scroll;
  overscroll-behavior-y: contain;
}

.scroll-x {
  touch-action: pan-x;
  overflow-x: scroll;
  overscroll-behavior-x: contain;
}

```
2) Enable passive events in zone-flags.ts as shown below:
```
(window as any)['__zone_symbol__PASSIVE_EVENTS'] = ['touchstart', 'touchmove', 'touchend', 'touchcancel', 'scroll'];
```
Is there a better way than this?

**Comment by liamdebeasi** [comment] 2020-10-01 17:09
It's hard to give any good advice without being able to reproduce the issue myself. Can you provide a GitHub repo that I can use to reproduce this issue?

**Comment by StevieWag** [comment] 2020-10-02 05:17
@liamdebeasi we are running into the same issue on ios 14. 

we are using a simple template like this and the content is not scrolling:

```
<ion-content>
  <ion-grid class="ion-padding">
    <ion-row>
      <ion-col>
        <p class="order-3" [innerHTML]="'menu.info' | translate"></p>
      </ion-col>
    </ion-row>
  </ion-grid>
</ion-content>
```

The same holds true when you use lists within the row/col structure

**Comment by StevieWag** [comment] 2020-10-02 14:19
A workaround which worked for us was to load component data onInit with a short timeOut (not really cool but didn't find another solution so far) base on the check if the device runs on iOS 14

```
ngOnInit() {
    const osMajor = this.device.majorOs;
    if (osMajor && this.device.deviceInfo && this.device.deviceInfo.operatingSystem === 'ios' && osMajor >= 14) {
      setTimeout(() => {
        this.showContent = true;
      }, 500);
    } else {
      this.showContent = true;
    }
  }
```

**Comment by YannaAlghamdi** [comment] 2020-10-04 11:41
Hi, 

Also encountered the same issue on ionic 4 and tried these:
`
.content-ios {
  pointer-events: auto !important;    // to fix scroll lock on ios
}
`
and this
`
.ios ion-content {
  pointer-events: auto !important;
}`

but unfortunately, none of them works.

**Comment by eun-choi** [comment] 2020-10-04 11:56
The occurrence frequency is higher when the scroll area is longer, the amount of content is larger or the device performance is lower.

iOS14 devices with occasional problems: iPhone 11, iPhone XS, iPhone XR, iPhone X, iPhone 8
iOS14 devices with frequent problems: iPhone 7, iPhone 6S, iPhone SE

**Comment by conde2** [comment] 2020-10-04 15:15
@liamdebeasi 

When scrolling in IOS PWA sometime the entire page scrolls and then freeze, if you try to scroll the ion content you are not able to. In my case it is possible to see the scrollbar as it is scrolling the entire page like a single block.

If you see this report, there are alot of people still reporting the same issue for the newest ionic, but reporting in the wrong place.
https://github.com/ionic-team/ionic-v3/issues/984#issuecomment-702663628


The Ion start examples can reproduce this just add it as PWA make sure ion content has enought content to be scrollable and try to scroll clicking in the tab bar moving to the top.

A sample application via GitHub
Just use the start tabs content and add enought content to be scrollable, using ion Slides is also a good idea

**Comment by liamdebeasi** [comment] 2020-10-05 13:25
Hi there,

Could someone please provide this as a GitHub repo I can use to reproduce the issue? As I mentioned previously, code snippets are typically not enough for us to be able to reproduce the issue.

**Comment by liamdebeasi** [comment] 2020-10-26 18:46
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!

**Closed by liamdebeasi** 2020-10-26 18:46 UTC
Labels: ionitron: needs reproduction
