### ISSUE TITLE
bug: Popover backdrop

### ISSUE THREAD

**Issue by asa47** [ionic-team/ionic-framework#23909] opened 2021-09-09 11:46 UTC
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Currently after triggering a popover, it doesn't show the backdrop on iOS devices, and it doesn't dismiss the popover after tapping "away" (tapping on the backdrop)

```
async function openPopover(ev: Event) {
      const popover = await popoverController
        .create({
          component: Popover,
          cssClass: 'popover-class',
          event: ev,
          translucent: false,
          showBackdrop: true,
          backdropDismiss: true
        });
      await popover.present();
}
```

### Expected Behavior

1. The backdrop should be visible on iOS devices.
1. To be able to dismiss the popover by tapping on the backdrop.

### Steps to Reproduce

Just tap on a button and trigger the popver:

https://user-images.githubusercontent.com/7304626/132679443-ef2fc662-08cb-418a-9665-61d5c3b935a3.mov

### Code Reproduction URL

https://github.com/asa47/popover-example

### Ionic Info

Ionic:

   Ionic CLI       : 6.17.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 6.0.0-dev.202109081359.195d817

Capacitor:

   Capacitor CLI      : 3.2.2
   @capacitor/android : not installed
   @capacitor/core    : 3.2.2
   @capacitor/ios     : 3.2.2

Utility:

   cordova-res (update available: 0.15.3) : 0.15.2
   native-run                             : 1.4.1

System:

   NodeJS : v12.4.0 (/usr/local/bin/node)
   npm    : 6.9.0
   OS     : macOS Big Sur

### Additional Information

Could it be related to this bug? https://github.com/ionic-team/ionic-framework/issues/23856

**Comment by liamdebeasi** [comment] 2021-09-09 13:23
Thanks for the issue. I am not able to reproduce this on my end. What version of iOS are you testing this on? Also it looks like you were testing this on a dev build of Ionic. Can you try this again on the the latest beta version? 

```
npm install @ionic/vue@next @ionic/vue-router@next
```

**Comment by asa47** [comment] 2021-09-09 13:53
I have run `npm install @ionic/vue@next @ionic/vue-router@next`, and I have tested it on actual device and simulator, but the issue is still present. Am I missing something?

https://user-images.githubusercontent.com/7304626/132698510-7824accd-5774-4a38-8a04-2106e0a507f5.mov

My iOS device:
iOS 14.7.1
iPad 6th generation

Simulator iOS devices:
iOS 14.5
iPhone 8
iPad 5th generation

**Comment by liamdebeasi** [comment] 2021-09-13 21:04
Thanks! I can reproduce the issue now. Going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/23571. The underlying issue in both threads is that child components of Ionic components are not getting registered when using the Custom Elements build in Stencil. We are working with the Stencil team to resolve this issue and will update https://github.com/ionic-team/ionic-framework/issues/23571 when we have more to share.

**Closed by liamdebeasi** 2021-09-13 21:04 UTC
Labels: triage
