### ISSUE TITLE
bug: ionic react hardware back button does not go back to correct tab

### ISSUE THREAD

**Issue by berat** [ionic-team/ionic-framework#22262] opened 2020-10-06 20:37 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

I made a mobile application with ionic5 as react and simply used tabs. I accidentally pressed the tab I was in at that moment 2 times and when I click the Hardware back button on my Android phone, it redirected it to that tab again.

**Expected behavior:**

Shouldn't it don't be kept in memory when I click that tab again while in the tab I am in? Or when I click on that tab, I shouldn't do any redirection. How many times I click on that tab, I want to go to the tab I am in before that tab.

**Steps to reproduce:**

I can't provide an example, but we can think like this.

There are 3 tabs: Homepage, Search and Profile.
First, I click on the search tab while on the homepage and go to that page.
While on the search page, I click the search tab 1 or more times.
When I press the back button on my Android phone, it redirects me back to the Search page.

**Related code:**
I use a structure like this.
```
<IonReactRouter>
  <IonTabs>
    <IonRouterOutlet>
      <Route path="/" render={() => <Redirect to="/home" />} exact/>
      <Route path="/search" component={SearchScreen} exact />
      <Route path="/profile" exact component={ProfileScreen} />
    </IonRouterOutlet>
    <IonTabBar className="tab-bar-box" slot="bottom">
      <IonTabButton
        className="tab-button"
        tab="tab1"
        href="/home">
        <div className="tab-bar-item feed" />
        <IonLabel>{strings.tabs.feed}</IonLabel>
      </IonTabButton>
      <IonTabButton
        className="tab-button"
        tab="tab4"
        href="/search">
        <div className="tab-bar-item search" />
        <IonLabel>{strings.tabs.search}</IonLabel>
      </IonTabButton>
      <IonTabButton
        className="tab-button"
        tab="tab5"
        href="/profile">
        <div className="tab-bar-item profile" />
        <IonLabel>{strings.tabs.profile}</IonLabel>
      </IonTabButton>
    </IonTabBar>
  </IonTabs>
</IonReactRouter>
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.11.10 (/Users/root/.config/yarn/global/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.1.1

Capacitor:

   Capacitor CLI   : 1.5.2
   @capacitor/core : 1.3.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v14.12.0 (/usr/local/Cellar/node/14.12.0/bin/node)
   npm    : 6.14.8
   OS     : macOS Catalina
```

**Comment by berat** [comment] 2020-10-15 13:30
There is no solution to this bug?

**Comment by liamdebeasi** [comment] 2020-10-15 13:32
Can you reproduce this issue in a blank Ionic starter application? Code snippets are not usually enough for us to reproduce the issue.

**Comment by berat** [comment] 2020-10-15 15:19
It worked very strangely. But how come this problem? I am sure I have taken any action to create this

**Comment by liamdebeasi** [comment] 2020-10-15 15:23
Without being able to reproduce the issue myself, I do not know. Can you reproduce this issue in an Ionic starter app and provide the link to the repo?

**Comment by berat** [comment] 2020-10-16 09:08
https://codesandbox.io/s/github/aaronksaunders/ionic-react-tabs-tut

I found something like this on the internet. The problem here is when we enter the application on the android phone and press the back button of the device when we click on the same tab, the loop continues over the same tab.

**Comment by liamdebeasi** [comment] 2020-11-03 18:19
Apologies for the delay. Can you please provide some steps to reproduce the issue? I am not able to reproduce the issue in the CodeSandbox provided.

**Comment by berat** [comment] 2020-11-09 12:55
Sorry for the delay, @liamdebeasi ! I've created a sample application and I'm sending it to you. https://codesandbox.io/s/youthful-shirley-69wub?file=/src/index.jsx

It will probably work correctly when you check it in the browser. But when you try it on your mobile device as apk, it will be wrong. Namely.
 
pageThree> pageTwo> pageThree will go to pageOne if you press the back button of the device after following these paths. When he presses the back button again, it performs a refresh on that page.

**Comment by liamdebeasi** [comment] 2020-11-09 18:08
Thanks! Any chance you could just send this as a GitHub repo? For some reason the CodeSandbox is not loading (I get a blank screen).

**Comment by berat** [comment] 2020-11-09 19:38
@liamdebeasi Yeah, sure! You can reach on here https://github.com/berat/ionic-tab-examples

**Comment by liamdebeasi** [comment] 2020-11-10 17:55
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. You have a few issues with your routing setup that are contributing to the issue:

1. You had a typo in your `PageOne` route. It should be `/PageOne` not `/pageOne`.
2. Your initial route configuration was wrong. You had the following:

```js
<Route path={"/PageOne"} component={App} />
 <Route>
  <Redirect to={"/PageOne"} />
</Route>
```

An alternative configuration could be: 

```js
<Route path="/" component={App} />
```

That being said, your route structure is a bit confusing. I would recommend putting all tabs under a `/tabs` path. Right now, you have all non-tabs and all tabs pages under the same root path which can lead to issues.

Your main routing config would look something like the following:

```js
<Route path="/tabs" component={App} />
<Redirect path="/" to="/tabs" />
```

Your tabs routing config would then look something like the following:

```js
<Route path="/tabs" render={() => <Redirect to="/tabs/PageOne" />} exact />
<Route path="/tabs/PageOne" component={PageOne} exact />
<Route path="/tabs/PageTwo" component={PageTwo} exact />
<Route path="/tabs/PageThree" component={PageThree} exact />
<Redirect exact from="/signIn" to="/companyfeed" />
```

3. This is not causing this particular issue, but we do recommend placing an `IonRouterOutlet` at the root and using `IonReactRouter`. Right now, you use the regular `Router` instance and only render an `IonRouterOutlet` under the `/out` path.

**Comment by berat** [comment] 2020-11-10 20:19
Yes, I noticed the typo later. But after fixing these errors, I still encounter the same problem while trying on my mobile phone.

**Comment by liamdebeasi** [comment] 2020-11-10 20:49
Thanks, I can reproduce this behavior in an Ionic React tabs starter app as well. I must have been reproducing a different issue.

**Comment by berat** [comment] 2020-11-10 22:18
I'll try to send you a video during the day.

**Comment by liamdebeasi** [comment] 2020-11-10 23:28
Thanks! You don't need to if you don't want to -- I can reproduce the issue that you are describing on my end.

**Comment by liamdebeasi** [comment] 2020-12-07 16:24
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/22559, and a fix will be available in an upcoming release of Ionic Framework.

**Closed by liamdebeasi** 2020-12-07 16:24 UTC
Labels: package: react, type: bug

**Comment by berat** [comment] 2020-12-21 13:51
Hey @liamdebeasi , I just upgrade ionic/react package and I got this error : `TypeError: props.onSetCurrentTab is not a function` 

![image](https://user-images.githubusercontent.com/10505575/102783949-bed50700-43ac-11eb-9a2e-eb8c06e8a588.png)

Codes are again the same as above
