### ISSUE TITLE
new_feature: Can Ionic support Micro Front End Architecture?

### ISSUE THREAD

**Issue by raghavanand17** [ionic-team/ionic-framework#22809] opened 2021-01-22 08:56 UTC
# Feature Request

**Ionic version:** 

[x] **4.x**

**Describe the Feature Request**

[x] Does Ionic Framework support Micro Front End Architecture? I don't know whether it is supporting or not. If it does, then how to achieve micro front ends in Ionic Framework?

**Describe Preferred Solution**

[x] Micro Front Ends will be very useful for the upcoming mobile app development era where each page of a mobile application or each section or each component of a page in a mobile application can be deployed independently and if any changes were to be made to a page, we can only stop that page and make changes to the page and re deploy the page to application. Remaining all pages  of the application will not be affected due to the change made in this page. This is the best feature to be made in Ionic Framework. I don't it is there or not. Please help me with this issue...!

**Example**

This is an example of micro front ends where each component of a web page is made with different front end languages, deployed independently and can be displayed in the same web page under the micro front end architecture. This feature will be very helpful in web applications and Amazon, Instagram are developing micro front ends to the next level. But this will be a great feature if it is also can be done in Ionic Framework for Mobile Applications.

![image](https://user-images.githubusercontent.com/58618647/105467921-55eaf280-5cbc-11eb-94c7-c662f9e1784c.png)

**Comment by liamdebeasi** [comment] 2021-01-22 14:07
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/22810.

**Closed by liamdebeasi** 2021-01-22 14:07 UTC
Labels: triage
