### ISSUE TITLE
bug: SSR Ionic/Angular error: win.matchMedia is not a function

### ISSUE THREAD

**Issue by dodongphure** [ionic-team/ionic-framework#23076] opened 2021-03-20 09:25 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

In `app.component.ts`, I just check current platform: `console.log(this.platform.is('pwa'));`
Will has this error:
```
ERROR, Error: Uncaught (in promise): TypeError: win.matchMedia is not a function
TypeError: win.matchMedia is not a function
```
At this line of code:
`const isPWA = (win) => !!(win.matchMedia('(display-mode: standalone)').matches || win.navigator.standalone);`

**Expected behavior:**

**Steps to reproduce:**

Just start blank project with angular 9/10, ionic 5, and Angular Universal.

**Related code:**

Here's a github repo I cloned to reproduce https://github.com/KevinBassaDevelopment/ionic-ssr-flickering-example
Then add `console.log(this.platform.is('pwa'));` in `initializeApp()` in `app.component.ts`.

**Other information:**

**Ionic info:**

```
Ionic CLI                     : 5.4.1
Ionic Framework               : @ionic/angular 5.6.0
@angular-devkit/build-angular : 0.1101.4
@angular-devkit/schematics    : 7.3.1
@angular/cli                  : 11.1.4
@ionic/angular-toolkit        : 3.1.0
@ionic/angular-server         : 5.6.0
```

**Comment by liamdebeasi** [comment] 2021-03-22 14:16
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/22703. (This issue references React, but it's the same underlying problem)

**Closed by liamdebeasi** 2021-03-22 14:16 UTC
Labels: triage
