### ISSUE TITLE
bug: ion-input type="number" min and max n ot working

### ISSUE THREAD

**Issue by rahulserver** [ionic-team/ionic-framework#23221] opened 2021-04-22 07:54 UTC
# Bug Report

**Ionic version**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

Neither min, nor max work for me in `ion-input`. And this happens for angular as well as vue. (Haven't tried react).
**Expected behavior:**

I should not be able to put any value lower than min or higher than max. (just like maxlength and minlength work)
**Steps to reproduce:**

Just create an angular or vue project using ionic cli and put an ion-input with mix and min attributes.
**Related code:**
The angular ionic bug replicated in this repo.
https://github.com/rahulserver/ionangularbug

The vue ionic replicated in this repo:
https://github.com/rahulserver/ionicvuebug

**Other information:**

I tried various variations like 
`<ion-input type="number" min="2" max="20"></ion-input>`
`<ion-input type="number" min=2 max=20></ion-input>`
None of these work. Either this issue should be fixed, or the docs must be updated to show that the these validators do not stop manual entry of values outside range.
**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.13.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 5.6.4

Capacitor:

   Capacitor CLI   : 2.4.7
   @capacitor/core : 2.4.7

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.18.3 (/usr/local/bin/node)
   npm    : 6.14.6
   OS     : macOS Big Sur
```

**Comment by liamdebeasi** [comment] 2021-04-22 13:35
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The `max` and `min` properties are passed to the underlying native `input` and as such as subject to the behavior that has been implemented by browser vendors.

If the value exceeds the `max` or is less than the `min`, then the input fails [constraint validation](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/HTML5/Constraint_validation). In other words, users can still enter any number they want, but if the number is out of the accepted range then the form will not submit.

You can see the same behavior using a native `input` outside of Ionic Framework: https://codepen.io/liamdebeasi/pen/rNjQEYK

To limit the values that users can enter you can either add some JavaScript to do this or write a regex for the `pattern` property.

**Closed by liamdebeasi** 2021-04-22 13:35 UTC
Labels: triage
