### ISSUE TITLE
bug: ion-refresher appears and gets stuck when scrolling downwards

### ISSUE THREAD

**Issue by telpat0298** [ionic-team/ionic-framework#23245] opened 2021-04-28 16:25 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

When scrolling downwards ( by swiping upwards), the refresher appears on the top of the screen and gets stuck and is not spinning (shown in the screenshot). Refreshing normally by swiping downwards is working. Also refreshing normally makes the stuck refresher icon disappear.

**Expected behavior:**

The refresher icon should not appear when swiping upwards.

**Steps to reproduce:**

The ion-refresher element is the first element of the ion-content element and is followed by the list items

**Related code:**

```
<ion-content id="list-view-container">
        <ion-refresher slot="fixed" (ionRefresh)="doRefresh($event)">
            <ion-refresher-content></ion-refresher-content>
        </ion-refresher>
		<ng-container #instrumentscontainer></ng-container>
        <app-empty [dataCount]="dataCount"></app-empty>
</ion-content>
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.14.0 (/usr/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.6.5
   @angular-devkit/build-angular : 0.1102.10
   @angular-devkit/schematics    : 11.2.10
   @angular/cli                  : 11.2.10
   @ionic/angular-toolkit        : 2.3.3

Capacitor:

   Capacitor CLI   : 2.4.7
   @capacitor/core : 2.4.7

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v14.16.1 (/usr/bin/node)
   npm    : 7.11.1
   OS     : Linux 4.19
```
![image](https://user-images.githubusercontent.com/48835517/116438236-8e1b4780-a84e-11eb-907e-0d1483e761de.png)

**Comment by liamdebeasi** [comment] 2021-04-30 15:33
Thanks for the issue. Can you reproduce this in an Ionic starter app and provide a link to the repo? I am unable to reproduce the issue using the code provided.

**Comment by telpat0298** [comment] 2021-05-03 21:25
Thank you for your answer. 

I could not reproduce this issue on stackblitz but i was able to reproduce it locally on my machine. This [github repo](https://github.com/telpat0298/ion-refresher-issue) contains a minimal reproduction of this issue. 
Culprit of this issue seems to be the combination of 
- two nested ion-content components containing the refresher component
- padding on the first, outer ion-content component. 

In this configuration, the refresher component is getting stuck when scrolling downwards(by swiping upwards).

**Comment by liamdebeasi** [comment] 2021-05-03 21:30
Thanks for the follow up. There should only be one `ion-content` per view (see: https://ionicframework.com/docs/api/content). Does the issue happen without the second nested `ion-content`?

**Comment by StavM** [comment] 2021-05-06 14:40
@liamdebeasi

We are facing this issue as well.

This issue was introduced since version **5.6.1** and we suspect it's caused by the change done in [this line of code
](https://github.com/ionic-team/ionic-framework/commit/67617fbc0f7ec825f1fa4c6e7e2da70e3fcd2d66#diff-b29397aad7f5dbb9aef05f5ce05a3bc7df6ae3858de670c6c4dcca0db23bc6a5R310)

From what we've seen since version 5.6.1 the framework immediately applies `this.state = RefresherState.Pulling;` in its gesture's `onStart ` callback, without checking the **DIRECTION** of the gesture (I believe you're checking `event.velocityY` value to determine that) as it was done prior to the change (in the `onMove` callback).

As seen here, there is no check done to validate the Y direction of the mouse/finger 'pull'  (gesture).
and it just triggers immediately. causing the class `.refresher-pulling` to be applied to the <ion-refresher> element.
![image](https://user-images.githubusercontent.com/6926633/117315893-c941fa00-ae90-11eb-809c-4712f84da202.png)

This in turn, will cause the child element `div.refresher-pulling` element to gain `display: flex` instead of `display: none` and make it visible.
![image](https://user-images.githubusercontent.com/6926633/117316325-29d13700-ae91-11eb-9279-38adf32badab.png)

The reason you're not seeing it immediately (and probably why you couldn't reproduce) is because the header by default, has a higher z-index value than the `<ion-refresher>` element's so it's covering it. if you increase the z-index value of the refresher, you'll see it immediately
![image](https://user-images.githubusercontent.com/6926633/117316808-9e0bda80-ae91-11eb-947a-c009a5b64071.png)

Again, thi sonly happens since version 5.6.1 and its probably due to a missing if statement.

**Comment by avidan-chen** [comment] 2021-05-06 15:08
@liamdebeasi we are due for a release next week and this is a blocker for us, would it possible for you to release a quick fix (even as a "dev" version, not necessarily a stable version) before the end of next week? As @StavM mentioned, it seems all that's missing is the "if" statement in on the onStart() handler (for MD only), to verify the direction is indeed pulling down and not up. It's very noticeable in our app (since we also use padding top for the entire page due to various UX considerations) - when the user starts scrolling down, the refresher appears immediately and is stuck on the page.

**Comment by liamdebeasi** [comment] 2021-05-06 15:10
Can you provide a reproduction of the issue with steps to reproduce? I was only able to reproduce it using the example in https://github.com/ionic-team/ionic-framework/issues/23245#issue-870129680 because there were two `ion-content` components. When using one `ion-content` I cannot reproduce the issue.

**Comment by StavM** [comment] 2021-05-06 17:52
@liamdebeasi 

https://stackblitz.com/edit/ionic-5-angular-10-start-template-ay8frp?file=src/app/tab1/tab1.page.html

![image](https://user-images.githubusercontent.com/6926633/117343437-f7cdce00-aeac-11eb-800e-ffb8c8c90aec.png)

**Comment by liamdebeasi** [comment] 2021-05-07 14:32
Thanks! Can you try the following dev build and let me know if it resolves the issue?

```
npm install @ionic/angular@5.7.0-dev.202105071428.1e5eabe
```

**Comment by StavM** [comment] 2021-05-09 05:17
Yes @liamdebeasi  your package seems to solves the issue.

**Comment by liamdebeasi** [comment] 2021-05-10 13:38
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/23283, and a fix will be available in an upcoming release of Ionic Framework.

**Closed by liamdebeasi** 2021-05-10 13:38 UTC
Labels: package: core, type: bug
