### ISSUE TITLE
bug: Unable to create new ionic project due to package being deprecated!

### ISSUE THREAD

**Issue by doc-han** [ionic-team/ionic-framework#21794] opened 2020-07-22 12:17 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.4.16**

**Current behavior:**

I've been trying to start a new Ionic project by running `ionic start project-name` and selecting type afterwards but it has been failing and giving the error below. Seems a deprecated package is making it unable to install all dependencies.

**Expected behavior:**

I expect my project to be initialized

**Steps to reproduce:**

Ionic info might help. Issue comes when creating a new project

**Related code:**

```
> npm.cmd i
npm WARN deprecated tslint@6.1.2: TSLint has been deprecated in favor of ESLint. Please see https://github.com/palantir/tslint/issues/4534 for more information.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm ERR! Unexpected end of JSON input while parsing near '...6YdtJg2/YPF8th+KZX9A1'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Han\AppData\Roaming\npm-cache\_logs\2020-07-22T12_04_34_644Z-debug.log
[ERROR] An error occurred while running subprocess npm.

        npm.cmd i exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI : 5.4.16

Utility:

   cordova-res (update available: 0.15.1) : 0.14.0
   native-run                             : 1.0.0

System:

   NodeJS : v12.16.1
   npm    : 6.14.5
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment] 2020-07-22 13:10
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. It looks like there is an error with one of the dependencies having invalid JSON, not that TSLint is deprecated:

```
npm ERR! Unexpected end of JSON input while parsing near '...6YdtJg2/YPF8th+KZX9A1'
```

I am not able to reproduce this, so it is likely a temporary issue. If the issue persists, I recommend ensuring your version of Node/npm is up to date as well as your version of the Ionic CLI (`npm i -g @ionic/cli`).

**Closed by liamdebeasi** 2020-07-22 13:10 UTC
Labels: triage
