### ISSUE TITLE
bug: Ionic Vue - `keep-contents-mounted` issue with `vue/prefer-true-attribute-shorthand` listing rule

### ISSUE THREAD

**Issue by Ericlm** [ionic-team/ionic-framework#28165] opened 2023-09-13 14:16 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

The vue linter is reporting an issue on the `<IonModal>` component when it's used with the `keep-contents-mounted` props. The linter wants to replace `:keep-contents-mounted="true"` with `keep-contents-mounted`, because it is preferred as a shortand. 
But when the `:keep-contents-mounted="true"` is replaced by `keep-contents-mounted`, the IonModal wrapping the IonDateTime doesn't show up, and so does the `<IonDatetimeButton>`. The error is as follow: `[Ionic Error]: No ion-datetime instance found for ID 'durationIonDatetime'. `.

### Expected Behavior

The modal and the input should show up whether the props has the syntax: `:keep-contents-mounted="true"` but also with the shortand syntax : `keep-contents-mounted`.

### Steps to Reproduce

1. Setup a <IonDatetimeButton slot="end" datetime="testing" /> inside an Ionic App
2. Add the following in the template:
``` vue
<IonModal v-if="canShowDuration" keep-contents-mounted>
  <IonDatetime
    id="testing"
    presentation="time"
    :value="duration"
    @ion-change="onInput"
  />
</IonModal>
```
3. It shouldn't work, but with the props as `:keep-contents-mounted="true"`, it should display the input and show the modal on input.

### Ionic Info

Ionic:

   Ionic CLI       : 7.1.1 (/Users/guillaumetorreilles/.asdf/installs/nodejs/20.6.1/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 7.3.3

Capacitor:

   Capacitor CLI      : 5.3.0
   @capacitor/android : 5.3.0
   @capacitor/core    : 5.3.0
   @capacitor/ios     : 5.3.0

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v20.6.1 (/Users/guillaumetorreilles/.asdf/installs/nodejs/20.6.1/bin/node)
   npm    : 9.8.1
   OS     : macOS Unknown

**Comment by liamdebeasi** [comment] 2023-09-13 15:55
Thanks for the report. The problem is we check for truth `keepContentsMounted` values here: https://github.com/ionic-team/ionic-framework/blob/f82709595d5031a759e35b11dbcccb0ea5870ce0/packages/vue/src/vue-component-lib/overlays.ts#L180

When you do `keep-contents-mounted` the value gets set as `''` which is a falsy value.

**Comment by liamdebeasi** [comment] 2023-09-13 16:17
Here's a dev build if you want to test the proposed fix:

```
npm install @ionic/vue@7.3.5-dev.11694621267.1e5f63c2 @ionic/vue-router@7.3.5-dev.11694621267.1e5f63c2
```

**Comment by Ericlm** [comment] 2023-09-13 17:11
> Here's a dev build if you want to test the proposed fix:
> 
> ```
> npm install @ionic/vue@7.3.5-dev.11694621267.1e5f63c2 @ionic/vue-router@7.3.5-dev.11694621267.1e5f63c2
> ```

I just tested it and it works perfectly fine! 😃

**Comment by liamdebeasi** [comment] 2023-09-14 18:27
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/28167, and a fix will be available in an upcoming release of Ionic Framework.

**Closed** 2023-09-14 18:26 UTC
Labels: package: vue, type: bug
