### ISSUE TITLE
bug: tapping quickly during page transition causes visual flickers

### ISSUE THREAD

**Issue by roman-rr** [ionic-team/ionic-framework#23208] opened 2021-04-18 20:53 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
Fast routing forwards with click to button do show next route page before end transition as blink.

**Expected behavior:**
Do not show next route page until transition is finished, even if we click to button and initiate next route event fast.

**Steps to reproduce:**
1. Install workspace
```bash
git clone https://github.com/roman-rr/ionic-fastroute-bug.git
cd ionic-fastroute-bug
npm i
ionic serve 
```
2. Click fast to button (initiate change route)
3. Click fast to second button (initiate next change route)

**Related code:**
https://github.com/roman-rr/ionic-fastroute-bug

```
insert short code snippets here
```

**Other information:**
![ezgif-1-f1d2967a918e](https://user-images.githubusercontent.com/10646478/115160369-01d88a00-a0c2-11eb-8610-9f2df753dc89.gif)

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.11.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.6.4
   @angular-devkit/build-angular : 0.1102.9
   @angular-devkit/schematics    : 11.2.9
   @angular/cli                  : 11.2.9
   @ionic/angular-toolkit        : 3.1.1

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : ios 6.2.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 4 other plugins)

Utility:

   cordova-res (update available: 0.15.3) : 0.14.0
   native-run (update available: 1.3.0)   : 0.3.0

System:

   Android SDK Tools : 26.1.1 (/Users/romanrr/Library/Android/sdk)
   ios-deploy        : 1.10.0
   ios-sim           : 8.0.2
   NodeJS            : v14.6.0 (/usr/local/bin/node)
   npm               : 6.14.7
   OS                : macOS Big Sur
   Xcode             : Xcode 12.3 Build version 12C33
```

**Comment by achakra21** [comment] 2021-05-02 11:54
I also faced the same issue the transitions are not smooth,till it get fixed is there any alternative solutions?

**Comment by HyperLife1119** [comment] 2021-05-09 16:59
This problem also occurs when swiping right back.

**Comment by cathypark** [comment] 2021-05-19 10:10
I also faced the same issue too

**Comment by liamdebeasi** [comment] 2021-09-09 20:14
The original GitHub repo was deleted. Does this issue still reproduce on the latest version of Ionic Framework? (v5.7.0 as of writing)

**Comment by liamdebeasi** [comment] 2022-05-16 20:51
Thanks for the issue. I am going to close this as I am not able to reproduce this on the latest version of Ionic Angular v6. If this is still a problem, please open a new issue. Thanks!

**Closed by liamdebeasi** 2022-05-16 20:51 UTC
Labels: package: core, type: bug
