### ISSUE TITLE
bug: large title + refresher problems

### ISSUE THREAD

**Issue by EinfachHans** [ionic-team/ionic-framework#23951] opened 2021-09-20 11:45 UTC
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

Cheers 😊 

I'm currently experiencing some problems in combination of ios large title and ion refresher (repo attached):

1. I have `color="primary"` defined on both Toolbars, but the Screen looks like:
<img src="https://user-images.githubusercontent.com/20899975/133996002-305bd4ad-9388-465b-b725-40b4602dd734.png" width="250">

2. Refresher is show to late, as the Content's `background-content` seems to overlap it
<img src="https://user-images.githubusercontent.com/20899975/133996438-82453d60-41ea-44d8-8c52-fdf4f3b6cc6a.gif" width="300">

If i remove the `top` style on the IonContent's `background-content` it looks better (see expected behavior) - i guess this is not a solution 😃 but maybe helps to understand the problem

3. The last problem is visible in the video in **Expected behavior 2.**. I would think that the background of the ion refresher is the same like the content 's one. Even if i set `color="primary"` on the refresher or it's content it does not work 100% if i pull down too far

### Expected Behavior

1. The full Header (so both Toolbars) should have the Color
2. With both Problems 1 + 2 fixed this should look like:
<img src="https://user-images.githubusercontent.com/20899975/133996320-dd66e503-2348-4f9a-aae8-395b21ceb898.gif" width="300">
3. The refresher should fit to the content's background color

### Steps to Reproduce

See Repo:

- `ionic serve`

### Code Reproduction URL

https://github.com/EinfachHans/large-header-refresher

**Comment by liamdebeasi** [comment] 2021-09-20 14:07
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/18714.

**Closed by liamdebeasi** 2021-09-20 14:07 UTC
Labels: triage

**Comment by EinfachHans** [comment] 2021-09-20 14:08
@liamdebeasi i think not all  of the three described problems are included there 🤔

**Comment by liamdebeasi** [comment] 2021-09-20 14:21
For issue 1, you need to set `color` on the content to not have the white space above your large title. This is documented in https://ionicframework.com/docs/api/title#styling-collapsible-large-titles.

For issue 3, the refresher does not have a `color` property, so setting `color` won't do anything. Instead, you can set the `background` of the `ion-refresher` if you want it to take on a particular color. In terms of `ion-refresher` not taking on the color of `ion-content`, this is intentional because the refresher is supposed to sit "under" the content with the entire content shifting down to reveal the refresher.

**Comment by EinfachHans** [comment] 2021-09-20 14:33
Issue 3 is sadly not completely resolved with this, because if you pull down to far you will see the contents background color 🤔

**Comment by liamdebeasi** [comment] 2021-09-20 14:54
Right, you're supposed to see the content's background color but the refresher is not designed to automatically take on the background color of the content.

**Comment by EinfachHans** [comment] 2021-09-20 15:12
Than combining the Large Title with the Refresher is not recommended? Because this looks not good that way

**Comment by liamdebeasi** [comment] 2021-09-20 15:14
We recommend using the "native" refreshers as those are what modern versions of iOS/Android are both using. The refresher you are using is mainly there for legacy purposes (older versions of iOS that we support)

**Comment by EinfachHans** [comment] 2021-09-20 15:19
This happens with the native Refresher on iOS too 🤔

**Comment by liamdebeasi** [comment] 2021-09-20 15:23
I can't reproduce this with the native refresher on iOS. The native refresher takes on the background color of `ion-content`.

**Comment by EinfachHans** [comment] 2021-09-20 15:59
Yes it takes the Color of the Content, but in this case it should be the color of the Header's Toolbar right? See the last added Gif: I want the Header to be in primary color and the content to be default white. The Gap that comes up when scrolling down doesn't looks nice.

**Comment by liamdebeasi** [comment] 2021-09-20 16:05
No, the native refresher should take on the color of the content. The reason for this is when the large title is expanded, the "collapsed" header is hidden using `opacity: 0` which means you will see the `ion-content` background. If you look at the Settings app on iOS you can see that the "collapsed" header is hidden the content background is shown. This is also why `fullscreen="true"` is required when using the large title.

**Comment by EinfachHans** [comment] 2021-09-20 16:15
Okay understand, i guess than this is not really possible (and not really normal?) like we would like to do this in our app 😃

**Comment by liamdebeasi** [comment] 2021-09-20 16:18
Yeah the way theming works with the native refresher on iOS is a bit odd, but in the native apps it looks like the entire toolbar hides with opacity instead of just hiding the title.

**Comment by EinfachHans** [comment] 2021-10-01 14:58
@liamdebeasi Hey there, small follow up about this topic: Just saw it in a native app, this is how i thought this should look like:

https://user-images.githubusercontent.com/20899975/135641890-228ed15d-8b4f-4619-9eed-21e1519fe2b4.MOV

Sorry for the really bad blackbox haha but it's very sensitive data 😅

**Comment by EinfachHans** [comment] 2021-10-05 12:42
@liamdebeasi did you see my video? I guess it's bug in current framework version
