### ISSUE TITLE
bug: ionic angular 7.5, cannot access menus with menuController

### ISSUE THREAD

**Issue by rvcroffi** [ionic-team/ionic-framework#28337] opened 2023-10-11 22:12 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

After upgrade @ionic/angular from 7.4.4 to 7.5.0 MenuController.enable() stop working.

### Expected Behavior

A menu initially disabled should be enabled after calling enable(true) from MenuController on app.component.ts.

### Steps to Reproduce

1. Create a new Ionic sidemenu app (angular).
2. Run `npm i @ionic/angular@7.4.4`
3. Disable ion-menu on app.component.html `<ion-menu contentId="main-content" type="overlay" [disabled]="true">`
4. Enable the menu on app.component.ts when platform is ready:
```
constructor(private menuCtrl: MenuController, private platform: Platform) {
    this.platform.ready().then(() => {
      this.menuCtrl.enable(true);
    });
  }
```
5. Run `ionic serve` and you will see the menu enabled (as expected).
6. Stop ionic serve and run `npm i @ionic/angular@7.5.0`
7. Run `ionic serve` again and the menu will be disabled.

### Code Reproduction URL

https://stackblitz.com/edit/angular-lgwu3i?file=src%2Fapp%2Fapp.component.ts

### Ionic Info

Ionic:

   Ionic CLI                     : 7.1.1
   Ionic Framework               : @ionic/angular 7.5.0
   @angular-devkit/build-angular : 16.2.6
   @angular-devkit/schematics    : 16.2.6
   @angular/cli                  : 16.2.6
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.5.0
   @capacitor/android : not installed
   @capacitor/core    : 5.5.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.3

System:

   NodeJS : v18.16.0 (C:\Program Files\nodejs\node.exe)
   npm    : 9.6.7
   OS     : Windows 10

**Comment by liamdebeasi** [comment] 2023-10-12 13:08
Thanks for reporting this! I can reproduce the reported behavior. The problem is with the introduction of our standalone work,  we now unintentionally create separate instances of the menuController. So the menu itself is registered with menuController A, but the application is using menuController B which is why `enable` does not appear to work. (since menuController B does not know about the menus in menuController A)

As a temporary workaround, you can use `menuController` from `@ionic/core` instead of `MenuController` from `@ionic/angular`. I'll work on a fix for this.

**Comment by liamdebeasi** [comment] 2023-10-12 14:09
Here's a dev build if you would like to test a proposed fix:

```
npm install @ionic/angular@7.5.1-dev.11697119260.14aa9ab3
```

**Closed** 2023-10-12 19:50 UTC
Labels: package: angular, type: bug

**Comment by liamdebeasi** [comment] 2023-10-12 19:53
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/28343, and a fix will be available in an upcoming release of Ionic Framework. Feel free to continue testing the dev build, and let me know if you have any questions!
