### ISSUE TITLE
bug: isPlatform('android') returning true on "ionic serve" on windows desktop

### ISSUE THREAD

**Issue by altelante** [ionic-team/ionic-framework#27471] opened 2023-05-13 13:54 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Using "@ionic/react": "^7.0.0", I run the app on Windows 10 with ionic serve and import isPlatform from @ionic/react.
I run isPlatform('android') and get true. This breaks my development environment as I use sqlite plugin with a fallback to regular browser SQL if not running on device.

for further info - getPlatforms returns  ['android', 'tablet', 'mobile', 'mobileweb']

If you need any more info I'll be glad to share.

### Expected Behavior

I should get "false".

### Steps to Reproduce

1. Create an ionic-react app on Windows 10, running Chrome.
2. import isPlatform from @ionic/react
3. check for isPlatform('android') and get "true"

### Ionic Info

[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package.json'

       Require stack:
       - C:\Users\altel\AppData\Roaming\nvm\v18.16.0\node_modules\@ionic\cli\lib\project\index.js
       - C:\Users\altel\AppData\Roaming\nvm\v18.16.0\node_modules\@ionic\cli\lib\index.js
       - C:\Users\altel\AppData\Roaming\nvm\v18.16.0\node_modules\@ionic\cli\index.js
       - C:\Users\altel\AppData\Roaming\nvm\v18.16.0\node_modules\@ionic\cli\bin\ionic

Ionic:

   Ionic CLI       : 7.0.1 (C:\Users\altel\AppData\Roaming\nvm\v18.16.0\node_modules\@ionic\cli)
   Ionic Framework : @ionic/react 7.0.3

Capacitor:

   Capacitor CLI      : 5.0.1
   @capacitor/android : 5.0.1
   @capacitor/core    : 5.0.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.2

System:

   NodeJS : v18.16.0 (C:\Program Files\nodejs\node.exe)
   npm    : 9.5.1
   OS     : Windows 10

**Comment by liamdebeasi** [comment] 2023-05-15 13:52
Thanks for the report. What is the user agent provided by your browser? In general I don't recommend relying on testing the user agent to determine device capabilities because user agents can be easily spoofed.

**Comment by altelante** [comment] 2023-05-16 08:15
I managed to understand what's causing the issue: 

Again, I'm with Chrome on Windows 10, and using ionic serve.

I, like most people (I assume) use Chrome with a viewport similar to the device we want to deploy on in real life.

When you activate chrome console with a "responsive" device mode with arbitrary dimensions the `navigator.userAgent` returns 'Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Mobile Safari/537.36'

If you deactivate the responsive device mode and leave the console open without manipulating the screen size, the `navigator.userAgent` will return 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36'

My conclusions:

1. I think it's worth at least to note this in the ionic documentation under "Platform" (if I'd know that the Platform utility determines the device type using that method - and not some flag Ionic will plant during build time for the specific platform - I'd assume something in my local machine is spoofing the value).

2. I don't know if you have plans to change this logic in the future, but for me the easiest way would be to plant some platform flag when building for each platform, and when using ionic serve these flags won't be present.

Thanks for the quick comment though,
Shay

**Comment by liamdebeasi** [comment] 2023-05-16 12:41
Thanks for the follow up. What you described makes sense and seems to be the reason why `isPlatform('android')` is returning the unexpected value.

We don't have plans to change our platform detection at the moment given how many developers rely on the current behavior. However, we expose APIs so developers can customize the platform detection methods for use cases where our detection is not sufficient: https://ionicframework.com/docs/react/platform#customizing-platform-detection-functions.

If you have ideas for how we can improve our documentation, I'd be happy to review a PR. We'd probably want to update the following pages:

Angular: https://github.com/ionic-team/ionic-docs/edit/main/docs/angular/platform.md
React: https://github.com/ionic-team/ionic-docs/edit/main/docs/react/platform.md
Vue: https://github.com/ionic-team/ionic-docs/edit/main/docs/vue/platform.md

I am going to close this since Ionic is working as intended, but let me know if you have questions.

**Closed by liamdebeasi** 2023-05-16 12:41 UTC
Labels: triage
