### ISSUE TITLE
bug: ref blocks onIonChange

### ISSUE THREAD

**Issue by kutoman** [ionic-team/ionic-framework#22890] opened 2021-02-08 13:54 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

In ionic react when a ref hook is used on a IonInput component, the component's `onIonChange` callback won't get triggered anyomre (eg. 'changed' doesn't get logged in the console). 

**Expected behavior:**

I would expect that a ref hook won't affect the `onIonChange` callback

**Steps to reproduce:**

it's reproducable just by adding the `ref` attribute on the `IonInput` component. `useRef` is not even required for this.

**Related code:**

```ts
export const Dummy: React.FC = () => {

    return (<IonPopover 
        isOpen={true}>
        <IonItem lines="none">
            <IonInput type="number"
                ref = {()=>{}} // as soon as this line is removed the callback gets triggered on change events
                onIonChange={() => console.log('changed') }
            />
        </IonItem>
    </IonPopover>)
}
```

**Other information:**

**Ionic info:**

```
...nothing related
```

**Comment by liamdebeasi** [comment] 2021-02-08 14:25
Thanks for the issue. The problem looks like you are not passing a valid `ref` to the `IonInput` component. I would not expect the component to work properly when using an invalid ref as Ionic React components forward that ref to the internal Web Component.

Passing a valid ref using `useRef` fixes the issue on my end. Can you try that and let me know how it goes?

**Comment by kutoman** [comment] 2021-02-09 09:53
@liamdebeasi actually, I initially was using the ref hook properly so that I investigated the issue further. Just for demonstration pruporses I tried to narrow the source of the issue down. This example isn't working for me either:

```ts
export const Dummy: React.FC = () => {

    const ref: MutableRefObject<HTMLIonInputElement|null> = useRef(null)

    return (<IonPopover 
        isOpen={true}>
        <IonItem lines="none">
            <IonInput type="number"
                ref = {ref}
                onIonChange={() => console.log('changed') }
            />
        </IonItem>
    </IonPopover>)
}
```

**Comment by liamdebeasi** [comment] 2021-02-09 14:13
Thanks. Can you reproduce this in a blank Ionic starter app and provide a link to the repo? I cannot reproduce this behavior using the code provided.

**Comment by kutoman** [comment] 2021-02-15 14:34
I couldn't reproduce this in a newly created ionic react project. Then I noticed that my ionic react environment was a bit outdated (5.0.7). After updating the packages it worked.

**Comment by liamdebeasi** [comment] 2021-02-26 19:56
Ok great! I am going to close this for now, but if you run into any other problems feel free to open a new issue. Thanks!

**Closed by liamdebeasi** 2021-02-26 19:56 UTC
Labels: needs: reply
