### ISSUE TITLE
bug: Vue - Tabs - 5.9.2 - Routing from non-tab sub page to a tab page breaks routing

### ISSUE THREAD

**Issue by Predarion** [ionic-team/ionic-framework#24362] opened 2021-12-10 07:52 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

When routing from a page that is not inside /tabs/ routing to a sub page of /tabs/tabx/supage, the wrong page is presented:

https://user-images.githubusercontent.com/24892172/145536544-b63872e3-b343-4b57-9f60-e1261014a504.mov

It seems like the app loads the last visisted tab page instead of the page where the route is going to.

### Expected Behavior

I expect to be routed to Tab2 page in step 7.

### Steps to Reproduce

1. Go to /tabs/tab1
2. Click "Tab3"-Button
3. Click "Tab1"-Button
4. Click link "Route to /not-a-tab-page"
5. Click link "Route to /not-a-tab-page/subpage"
6. Click link "Route to /tabs/tab2"
7. You will be routed to Tab1 page instead of Tab2 page. URL is set correct. TabBar highlights correct TabButton.

### Code Reproduction URL

https://github.com/Predarion/ionic-vue-tabs-shows-wrong-tab-page

### Ionic Info

[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package'

       Require stack:
       - /usr/local/lib/node_modules/@ionic/cli/lib/project/index.js
       - /usr/local/lib/node_modules/@ionic/cli/lib/index.js
       - /usr/local/lib/node_modules/@ionic/cli/index.js
       - /usr/local/lib/node_modules/@ionic/cli/bin/ionic
[WARN] Error loading @capacitor/android package.json: Error: Cannot find module '@capacitor/android/package'

       Require stack:
       - /usr/local/lib/node_modules/@ionic/cli/lib/project/index.js
       - /usr/local/lib/node_modules/@ionic/cli/lib/index.js
       - /usr/local/lib/node_modules/@ionic/cli/index.js
       - /usr/local/lib/node_modules/@ionic/cli/bin/ionic

Ionic:

   Ionic CLI       : 6.18.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 5.9.2

Capacitor:

   Capacitor CLI      : 3.3.3
   @capacitor/android : not installed
   @capacitor/core    : 3.3.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v16.13.0 (/usr/local/bin/node)
   npm    : 8.1.0
   OS     : macOS Big Sur

### Additional Information

The behavior also occurs with version 5.9.1

**Comment by Predarion** [comment] 2021-12-10 07:58
@liamdebeasi this is the issue I mentioned yesterday in https://github.com/ionic-team/ionic-framework/issues/24353#issuecomment-990012612. This is a different issue than yesterdays (#24353) and not resolved with its dev build. I would really appreciate it if you also investigate this one.

**Comment by liamdebeasi** [comment] 2021-12-10 13:58
Thanks. Did this work on a previous version of Ionic Vue, or has this behavior always been present?

**Comment by liamdebeasi** [comment] 2021-12-10 14:04
It looks like this is a duplicate of https://github.com/ionic-team/ionic-framework/issues/23058. I am going to close this and track progress on this issue in #23058. Thanks!

**Closed by liamdebeasi** 2021-12-10 14:04 UTC
Labels: needs: reply
