### ISSUE TITLE
bug: ios, menu disappears on rtl mode when focusing element in menu

### ISSUE THREAD

**Issue by yonatancohen** [ionic-team/ionic-framework#25192] opened 2022-04-26 11:18 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

When doc type is in RTL mode, the menu open then auto close itself.
- Only happens on the first toggle.
 

### Expected Behavior

One click to open the menu.

### Steps to Reproduce

Create a simple menu project, edit the `<html>` tag to `<html lang="he" dir="rtl">` in the index page.

### Ionic Info

`Ionic:

   Ionic CLI                     : 6.19.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.1.2
   @angular-devkit/build-angular : 13.3.3
   @angular-devkit/schematics    : 13.3.3
   @angular/cli                  : 13.3.3
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.5.0
   @capacitor/android : 3.5.0
   @capacitor/core    : 3.5.0
   @capacitor/ios     : 3.5.0

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v16.13.0 (/usr/local/bin/node)
   npm    : 8.1.3
   OS     : macOS Monterey
`

**Comment by liamdebeasi** [comment] 2022-04-26 12:54
Thanks for the issue. I tried reproducing this in a sidemenu Ionic starter app but was unable to reproduce the issue. Can you provide a GitHub repo I can use to verify this behavior?

**Comment by yonatancohen** [comment] 2022-04-27 09:49
Hi Liam,

A link to the github which I created:
https://github.com/yonatancohen/menu-test/

Also, I forgot to mention - this only happens when I run the application in
ios/android.

**Comment by liamdebeasi** [comment] 2022-05-18 16:14
I reported the issue to the WebKit team: https://bugs.webkit.org/show_bug.cgi?id=240582

Changing `translate3d` to `translateX` here seems to fix the issue: https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/menu/menu.scss#L41

We should not need to do a 3d transform, so I will see if it is feasible to change this.

**Comment by liamdebeasi** [comment] 2022-05-18 16:28
Can you try the following dev build, and let me know if it resolves the issue?

```
npm install @ionic/angular@6.1.6-dev.11652891005.1ac88bcc
```

**Comment by liamdebeasi** [comment] 2022-05-19 18:17
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/25309, and a fix will be available in an upcoming release of Ionic Framework.

Please feel free to continue testing, and let me know if you run into any issues.

**Closed** 2022-05-19 18:16 UTC
Labels: type: bug, bug: external
