### ISSUE TITLE
bug: ion-infinite-scroll is not working with popover

### ISSUE THREAD

**Issue by iampavanarora** [ionic-team/ionic-framework#19114] opened 2019-08-16 13:27 UTC
# Bug Report

**Ionic version:**
[x] **4.7.0**

**Current behaviour:**
infinite-scroll is not working in ionic popover it just take an place in elements its proper working in pages and modals but its not working in popover
**Expected behaviour:**
Needs to works in popovers like it works in modals and page

**Steps to reproduce:**
Just simply place ion-infinite-scroll and open popover it black space but yet not working

```
insert short code snippets here
    <ion-list>
            <ion-item *ngFor="let test of testdata"
                (click)="setSelected(test)">
                    {{test.name}}
            </ion-item>
        </ion-list>
        <ion-infinite-scroll threshold="50px" (ionInfinite)="loadMoreData($event)">
            <ion-infinite-scroll-content
            loadingSpinner="crescent"
            loadingText="Plese Wait...">
            </ion-infinite-scroll-content>
        </ion-infinite-scroll>
```

**Comment by liamdebeasi** [comment] 2019-08-19 13:25
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue? I tried using the code you provided, but the infinite scroll component fired as expected.

**Comment by iampavanarora** [comment] 2019-08-20 04:31
@liamdebeasi  here is the repo url for check this issue
https://github.com/iampavanarora/ionic-4

**Comment by pawan-logiciel** [comment] 2019-08-27 09:08
@liamdebeasi any update on this?

**Comment by iampavanarora** [comment] 2019-08-27 09:13
@liamdebeasi  any update on this ?

**Comment by tajinder-logiciel** [comment] 2019-09-18 12:12
@liamdebeasi any update regarding this,I am also getting this issue

**Comment by sapabg** [comment] 2019-11-06 09:56
Same here. The event does not get triggered when I reach the bottom.

**Comment by liamdebeasi** [comment] 2019-11-06 13:30
Apologies for the delay. I was able to reproduce this issue using the repo provided. We will look into a fix for this. Thanks!

**Comment by Yermo** [comment] 2019-12-01 01:00
FWIW, the same seems to be happening in an ion-modal.

**Comment by PabloHernanVila** [comment] 2020-06-20 02:29
Is there any workaround for making ion-infinite-scroll work inside a ion-popover?

**Comment by JunaidAlam36** [comment] 2020-09-03 21:41
still nothing on this?? I am facing same issue... ionInfinite is not event triggered in ion modal at end of the list... using ionic version 5+

**Comment by PabloHernanVila** [comment] 2020-09-04 03:16
It seems that it's not supported to use ion-infinite inside pop-over or modals.

**Comment by kt-at-cbx** [comment] 2020-09-28 03:23
Sad. I am also getting this issue.

> 
> 
> It seems that it's not supported to use ion-infinite inside pop-over or modals.

Is there any workaround to achieve infinite scroll in popover or modals?

**Comment by liamdebeasi** [comment] 2022-06-09 20:32
Thanks for the issue. I am no longer able to reproduce this issue on the latest version of Ionic using the GitHub repo provided in https://github.com/ionic-team/ionic-framework/issues/19114#issuecomment-522848523.

I am going to close this for now. If this is still a bug, please provide a new reproduction that we can use to verify this behavior.

**Closed by liamdebeasi** 2022-06-09 20:32 UTC
Labels: package: core, type: bug
