### ISSUE TITLE
bug: deprecation warning is shown for ion-input with label prop set to undefined

### ISSUE THREAD

**Issue by ryaa** [ionic-team/ionic-framework#27161] opened 2023-04-11 12:58 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When ion-input has label prop set to undefined, the deprecation warning is still displayed in the console
```
[Ionic Warning]: ion-input now requires providing a label with either the "label" property or the "aria-label" attribute. To migrate, remove any usage of "ion-label" and pass the label text to either the "label" property or the "aria-label" attribute.

Example: <ion-input label="Email"></ion-input>
Example with aria-label: <ion-input aria-label="Email"></ion-input>

For inputs that do not render the label immediately next to the input, developers may continue to use "ion-label" but must manually associate the label with the input by using "aria-labelledby".

Developers can use the "legacy" property to continue using the legacy form markup. This property will be removed in an upcoming major release of Ionic where this form control will use the modern form markup. <i
```

### Expected Behavior

No warning shown as the ion-input is intended to be be rendered without label.

### Steps to Reproduce

<ion-input [label]="undefined"></ion-input>
OR
<ion-input></ion-input> (the label default value of undefined is used)

### Ionic Info

```
Ionic:

   Ionic CLI                     : 7.0.1 (/Users/alexryltsov/.nvm/versions/node/v18.15.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.0.1
   @angular-devkit/build-angular : 15.2.5
   @angular-devkit/schematics    : 15.2.5
   @angular/cli                  : 15.2.5
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 4.7.3
   @capacitor/android : 4.7.3
   @capacitor/core    : 4.7.3
   @capacitor/ios     : 4.7.3

Utility:

   cordova-res                          : not installed globally
   native-run (update available: 1.7.2) : 1.7.1

System:

   NodeJS : v18.15.0 (/Users/alexryltsov/.nvm/versions/node/v18.15.0/bin/node)
   npm    : 9.6.4
   OS     : macOS Unknown
```

**Comment by Julien-Marcou** [comment] 2023-04-11 14:10
I believe this is intended, inputs without a label should have an aria-label for accessibility reasons (aria-label are not visible in your UI, it's only here to describe the input for tools like screen readers).

You should define an aria-label for your input like this `<ion-input aria-label="Label"></ion-input>` to get rid of the warning.

**Comment by amandaejohnston** [comment] 2023-04-11 14:20
I can confirm that this behavior is intended. As Julien-Marcou said, if you would like an input without a visible label, you can add an `aria-label` instead so that your input is still accessible for those using screen readers.

I'm going to close this out as things are working as intended, but please let me know if you run into additional trouble after setting a defined `label` or `aria-label`.

**Closed by amandaejohnston** 2023-04-11 14:20 UTC
Labels: triage
