### ISSUE TITLE
bug: UI Component - ion-loading

### ISSUE THREAD

**Issue by asangadev** [ionic-team/ionic-framework#24538] opened 2022-01-08 22:22 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

1. We can see the Spinner and Backdrop with `ionic serve`.  We can see the backdrop and the spinner. Please see below as expected:

![Screen Shot 2022-01-09 at 9 03 06 am](https://user-images.githubusercontent.com/16328655/148661587-aab387e3-a58d-4fd6-abd8-2deb7826a3e8.png)

2. Then you run `ionic capacitor build ios` and run in iOS simulator. The spinner and the backdrop are mining here:

<img width="506" alt="Screen Shot 2022-01-09 at 9 03 43 am" src="https://user-images.githubusercontent.com/16328655/148661603-9caafe22-c7af-4461-b8f2-89475672aa92.png">

### Expected Behavior

The backdrop and the spinner needs to be there on iOS devices.

### Steps to Reproduce

1. Create a blank ionic vue app: https://ionicframework.com/docs/vue/quickstart

2. Add this view from the example here (from the vue tab): https://ionicframework.com/docs/api/loading#usage

3. Upgrade the ionic from version 5 to 6: https://ionicframework.com/docs/intro/upgrading-to-ionic-6#vue

FY: Works perfectly fine with ionic version [5.9.3](https://github.com/ionic-team/ionic-framework/releases/tag/v5.9.3)

### Code Reproduction URL

https://github.com/asangadev/ionic-6

### Ionic Info

```
Ionic:

   Ionic CLI       : 6.18.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 6.0.1

Capacitor:

   Capacitor CLI      : 3.3.4
   @capacitor/android : not installed
   @capacitor/core    : 3.3.4
   @capacitor/ios     : 3.3.4

Utility:

   cordova-res (update available: 0.15.4) : 0.15.3
   native-run                             : 1.5.0

System:

   NodeJS : v14.17.0 (/usr/local/bin/node)
   npm    : 7.13.0
   OS     : macOS Monterey
```

### Additional Information

Please see the repo here: https://github.com/asangadev/ionic-6

**Comment by liamdebeasi** [comment] 2022-01-10 15:13
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/24463.

**Closed by liamdebeasi** 2022-01-10 15:13 UTC
Labels: triage

**Comment by asangadev** [comment] 2022-01-10 23:35
> Thanks for the issue. I am going to close this as a duplicate of #24463.

@liamdebeasi sorry didn't see that one!
