### ISSUE TITLE
bug: refresher incorrectly uses native refresher when it should not

### ISSUE THREAD

**Issue by andreas-aeschlimann** [ionic-team/ionic-framework#22706] opened 2020-12-20 15:08 UTC
**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
The docs (https://ionicframework.com/docs/api/refresher) contain the following example for a refresher:

```
<ion-content>
    <ion-refresher slot="fixed" (ionRefresh)="doRefresh($event)">
        <ion-refresher-content
                pullingIcon="chevron-down-circle-outline"
                pullingText="Pull to refresh"
                refreshingSpinner="circles"
                refreshingText="Refreshing...">
        </ion-refresher-content>
    </ion-refresher>
</ion-content>
```

On an MD device or browser, this leads to the following error:

```
Uncaught (in promise) TypeError: Cannot read property 'shadowRoot' of null
    at getElementRoot (helpers-90f46169.js:66)
    at Refresher.setupMDNativeRefresher (ion-refresher_2.entry.js:410)
    at Refresher.setupNativeRefresher (ion-refresher_2.entry.js:505)
    at Refresher.checkNativeRefresher (ion-refresher_2.entry.js:273)
```

**Expected behavior:**
Examples from the docs should work

**Steps to reproduce:**
See above

**Related code:**
See above

**Other information:**
I noticed that the error occurs because the pulling icon is not available/supported on Android. The documentation on how to use the pulling icon is somewhat cumbersome. It just refers to the spinner docs, but the spinner works differently.

**Ionic info:**
```
Ionic:

   Ionic CLI                     : 6.12.3 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.5.2
   @angular-devkit/build-angular : 0.1100.5
   @angular-devkit/schematics    : 11.0.5
   @angular/cli                  : 11.0.5
   @ionic/angular-toolkit        : 3.0.0

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res (update available: 0.15.2) : 0.15.1
   native-run                             : not installed

System:

   NodeJS : v10.16.0 (/usr/local/bin/node)
   npm    : 6.14.9
   OS     : macOS Big Sur
   Xcode  : Xcode 12.2 Build version 12B45b
```

**Comment by BerkeAras** [comment] 2020-12-20 22:46
@andreas-aeschlimann Could you please provide an Repository for Reproducing? I found an bug in the documentation, but it is another bug. I cannot reproduce yours.

**Comment by fssgh** [comment] 2020-12-28 14:42
**Me Too.**
### use following code has error
```
<ion-content>
  <ion-refresher slot="fixed" (ionRefresh)="doRefresh($event)">
    <ion-refresher-content
      pullingIcon="arrow-down-outline"
      pullingText="下拉刷新"
      refreshingSpinner="circles"
      refreshingText="刷新中..."
    ></ion-refresher-content>
  </ion-refresher>
</ion-content>
```
### use following code no error
```
<ion-content>
  <ion-refresher slot="fixed" (ionRefresh)="doRefresh($event)">
    <ion-refresher-content></ion-refresher-content>
  </ion-refresher>
</ion-content>
```

**Comment by ZhongYueHui** [comment] 2021-01-03 02:28
<ion-refresher-content> 标签增加属性 pullingIcon 即会出现这种情况

**Comment by ZhongYueHui** [comment] 2021-01-03 02:32
> **离子版本：**
> [] **4.x**
> [x] **5.x**
> 
> **当前行为：**
> 文档（https://ionicframework.com/docs/api/refresher）包含以下刷新示例：
> 
> ```
> <ion-content>
>     <ion-refresher slot="fixed" (ionRefresh)="doRefresh($event)">
>         <ion-refresher-content
>                 pullingIcon="chevron-down-circle-outline"
>                 pullingText="Pull to refresh"
>                 refreshingSpinner="circles"
>                 refreshingText="Refreshing...">
>         </ion-refresher-content>
>     </ion-refresher>
> </ion-content>
> ```
> 
> 在MD设备或浏览器上，这导致以下错误：
> 
> ```
> Uncaught (in promise) TypeError: Cannot read property 'shadowRoot' of null
>     at getElementRoot (helpers-90f46169.js:66)
>     at Refresher.setupMDNativeRefresher (ion-refresher_2.entry.js:410)
>     at Refresher.setupNativeRefresher (ion-refresher_2.entry.js:505)
>     at Refresher.checkNativeRefresher (ion-refresher_2.entry.js:273)
> ```
> 
> **预期的行为：**
> 应使用文档中的示例
> 
> **复制步骤：**
> 见上文
> 
> **相关代码：**
> 见上文
> 
> **其他信息：**
> 我注意到发生错误是因为在Android上不可用/不支持拉动图标。有关如何使用拉动图标的文档有些繁琐。它仅引用微调器文档，但微调器的工作方式不同。
> 
> **离子信息：**
> 
> ```
> Ionic:
> 
>    Ionic CLI                     : 6.12.3 (/usr/local/lib/node_modules/@ionic/cli)
>    Ionic Framework               : @ionic/angular 5.5.2
>    @angular-devkit/build-angular : 0.1100.5
>    @angular-devkit/schematics    : 11.0.5
>    @angular/cli                  : 11.0.5
>    @ionic/angular-toolkit        : 3.0.0
> 
> Cordova:
> 
>    Cordova CLI       : 10.0.0
>    Cordova Platforms : not available
>    Cordova Plugins   : not available
> 
> Utility:
> 
>    cordova-res (update available: 0.15.2) : 0.15.1
>    native-run                             : not installed
> 
> System:
> 
>    NodeJS : v10.16.0 (/usr/local/bin/node)
>    npm    : 6.14.9
>    OS     : macOS Big Sur
>    Xcode  : Xcode 12.2 Build version 12B45b
> ```

try use iPhone device

**Comment by ZhongYueHui** [comment] 2021-01-03 02:33
> **我也是。**
> 离子版本：
> 5.5.2
> 
> ### 使用以下代码有错误
> ```
> <ion-content>
>   <ion-refresher slot="fixed" (ionRefresh)="doRefresh($event)">
>     <ion-refresher-content
>       pullingIcon="arrow-down-outline"
>       pullingText="下拉刷新"
>       refreshingSpinner="circles"
>       refreshingText="刷新中..."
>     ></ion-refresher-content>
>   </ion-refresher>
> </ion-content>
> ```
> 
> ### 使用以下代码没有错误
> ```
> <ion-content>
>   <ion-refresher slot="fixed" (ionRefresh)="doRefresh($event)">
>     <ion-refresher-content></ion-refresher-content>
>   </ion-refresher>
> </ion-content>
> ```

try use iPhone device

**Comment by Dark-Existed** [comment] 2021-01-07 13:21
the same to me
if add pullingIcon it will cause this issue

**Comment by liamdebeasi** [comment] 2021-01-12 14:45
> Thanks for the issue! This issue has been labeled as `needs reproduction`. This label is added to issues that need a code reproduction.
> 
> Please reproduce this issue in an Ionic starter application and provide a way for us to access it (GitHub repo, StackBlitz, etc). Without a reliable code reproduction, it is unlikely we will be able to resolve the issue, leading to it being closed.
> 
> If you have already provided a code snippet and are seeing this message, it is likely that the code snippet was not enough for our team to reproduce the issue.
> 
> For a guide on how to create a good reproduction, see our [Contributing Guide](https://ionicframework.com/docs/contributing/how-to-contribute#creating-a-good-code-reproduction).

Can someone please reproduce this in an Ionic starter app and provide a link to the repo? Code snippets are not typically enough for us to be able to reproduce the issue.

**Comment by fssgh** [comment] 2021-01-15 03:04
@liamdebeasi  please see this  [https://github.com/fssgh/refresherTest.git](url)   reproduce this issue

**Comment by liamdebeasi** [comment] 2021-01-20 22:18
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/22800, and a fix will be available in an upcoming release of Ionic Framework.

Here is a dev build if anyone would like to test the fix:

**Angular**
```
npm install @ionic/angular@5.6.0-dev.202101202158.ca7b5b7
```

**React**
```
npm install @ionic/react@5.6.0-dev.202101202158.ca7b5b7 @ionic/react-router@5.6.0-dev.202101202158.ca7b5b7
```

**Vue**
```
npm install @ionic/vue@5.6.0-dev.202101202158.ca7b5b7 @ionic/vue-router@5.6.0-dev.202101202158.ca7b5b7
```

**Stencil/Vanilla JavaScript**
```
npm install @ionic/core@5.6.0-dev.202101202158.ca7b5b7
```

**Closed by liamdebeasi** 2021-01-20 22:18 UTC
Labels: package: core, type: bug
