### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by miguelcorreia19** [ionic-team/ionic-framework#23067] opened 2021-03-17 19:01 UTC
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
Occur error when disabling IonMenu by actions and crash the app.
Error: ASSERT: _before() should be called while animating

**Expected behavior:**
Disable the menu on the login page, in React.

**Steps to reproduce:**
I have done several tests and used the base app ionic-react-conference-app and a new one with the latest packages, and the error persists.

I just want to disable the menu on the login page.

To do that I use the state in reducer (menuEnabled on session action), with react hook useEffect and useIonViewDidEnter on Login.tsx page, to disable the menu. And to enable (after login), I call an action on useIonViewDidEnter or in the function that will redirect.

If I log in and after that, open the menu the app crash with the following error:
Error: ASSERT: _before() should be called while animating

**Related code:**
I reproduce this issue in [codesandbox](https://codesandbox.io/s/ionmenu-report-1-i9kbj) with the ionic-react-conference-app.

PS: you can login with any username and password

Thanks!

**Comment by liamdebeasi** [comment] 2021-03-17 19:30
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/19676.

**Closed by liamdebeasi** 2021-03-17 19:30 UTC
Labels: triage
