### ISSUE TITLE
ioninc-react android6 SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by 25juan** [ionic-team/ionic-framework#20583] opened 2020-02-21 14:57 UTC
# Bug Report

**Ionic version:**

[x] **5.0.0**

**Current behavior:**
android5 blank screen.
Android9 is OK.
android studio terminal info
```
W/System: Ignoring header Cookie because its value was null.
W/Capacitor/Console: File: http://192.168.0.103:8100/ - Line 988 - Msg: The key "viewport-fit" is not recognized and ignored.
W/System: Ignoring header Cookie because its value was null.
W/System: Ignoring header Cookie because its value was null.
E/Capacitor/Console: File: capacitor-runtime.js - Line 361 - Msg: SyntaxError: Unexpected identifier
E/Capacitor: JavaScript Error: {"type":"js.error","error":{"message":"Uncaught SyntaxError: Unexpected identifier","url":"http://192.168.0.103:8100/static/js/8.chunk.js","line":7430,"col":9,"errorObject":"{}"}}
E/Capacitor/Console: File: http://192.168.0.103:8100/static/js/8.chunk.js - Line 7430 - Msg: Uncaught SyntaxError: Unexpected identifier
W/System: Ignoring header Cookie because its value was null.
W/art: Method processed more than once: java.util.Map com.android.webview.chromium.WebViewUrlWatcher.readConfigFile()
D/WebViewUrlWatcher: watchUrlIfNeeded, url: http://192.168.0.103:8100/
E/libEGL: called unimplemented OpenGL ES API
D/Capacitor: SplashScreen was automatically hidden after the launch timeout. You should call `SplashScreen.hide()` as soon as your web app is loaded (or increase the timeout).Read more at https://capacitor.ionicframework.com/docs/apis/splash-screen/#hiding-the-splash-screen
E/libEGL: called unimplemented OpenGL ES API

```

**Expected behavior:**

show tabs screen

**Steps to reproduce:**
1、`ionic start IonicTabs tabs --type=react` init project.
2、`npm run build`
3、`ionic cap run android -l --external` run project on android6.(API23)
4、Android6 blank screen
i do not edit the tabs template code .
**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.0.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.0.1

Capacitor:

   Capacitor CLI   : 1.5.0
   @capacitor/core : 1.5.0

Utility:

   cordova-res                          : not installed
   native-run (update available: 0.3.0) : 0.2.9

System:

   NodeJS : v10.15.0 (/usr/local/bin/node)
   npm    : 6.13.7
   OS     : macOS Catalina
```

**Comment by liamdebeasi** [comment] 2021-09-16 19:35
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The problem here is likely that the webview installed to your Android device is too outdated and does not support a certain web API that your application relies on. This API could be required by Ionic, Stencil, React, or any other dependency you have installed in your application.

In general, Ionic supports Chromium v60+ without any polyfills. You can run `window.navigator.userAgent` in the dev tools console when inspecting your application to determine which version of Chromium you are running.

A couple options for how to go about resolving this:

1. See if you can update the Android System WebView from the Google Play Store. Typically this autoupdates, but it is possible that the autoupdate got disabled at some point.
2. Use [react-app-polyfill](https://github.com/facebook/create-react-app/blob/main/packages/react-app-polyfill/README.md) which includes polyfills in your Create React App for older browsers.

For any questions regarding implementing `react-app-polyfill`, I recommend posting on the [Ionic Forum](https://forum.ionicframework.com/). Thank you!

**Closed by liamdebeasi** 2021-09-16 19:35 UTC
Labels: triage
