### ISSUE TITLE
bug: Two fingers causes ion-item-sliding to not close in Android

### ISSUE THREAD

**Issue by Lightk3ira** [ionic-team/ionic-framework#23969] opened 2021-09-22 20:33 UTC
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

The bug occurs when you have multiple ion-sliding-items. When you slide an item with 1 finger and then simultaneously touch another slider item, then let go of them, when sliding a new item the original sliding item will not close. As shown in the image below of the outcome. This is a bare bones example that is running on a mobile device and is mirrored using google chromes device inspector.

![image](https://user-images.githubusercontent.com/8987009/134414854-0396a7d6-3668-4e24-8f1f-b8f80ac6cdc2.png)

### Expected Behavior

The expected behavior is that when sliding an item and touching another item, when you slide another item after it should close the previous ion-sliding-item.

### Steps to Reproduce

1) Create a new empty angular ionic application
2) Create a list of ion-sliding-items each with 1 or many options
3) Build the application for Android
4) Run the application on Android device
5) Place finger on one of the ion-sliding-items
6) Start dragging, do not lift finger
7) During the previous steps drag use another finger and tap and hold another ion-sliding-item
8) Let go of the second finger and let go of your sliding finger
9) One ion-item-sliding should be open, this is correct
10) Place your finger on a different ion-sliding-item that is closed and swipe it open
11) You should now see the first ion-sliding-item was not closed. There should now be two ion-sliding-items that are open

### Ionic Info

Ionic:

   Ionic CLI                     : 6.12.3 (C:\Users\xt27901\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.6.14
   @angular-devkit/build-angular : 12.1.4
   @angular-devkit/schematics    : 12.1.4
   @angular/cli                  : 12.1.4
   @ionic/angular-toolkit        : 4.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 4 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 1.0.0

System:

   Android SDK Tools : 26.1.1 (C:\Users\xt27901\AppData\Local\Android\Sdk)
   NodeJS            : v14.17.4 (C:\Program Files\nodejs\node.exe)
   npm               : 6.14.14
   OS                : Windows 10

### Additional Information

Cannot seem to push a repo due to proxies. However this is the relevant code you need to add after creating a new application 

 <ion-item-sliding>
      <ion-item>
        <ion-label>
          <h2>HubStruck Notifications</h2>
          <p>A new message in your network</p>
          <p>Oceanic Next has joined your network</p>
        </ion-label>
        <ion-note slot="end">
          10:45 AM
        </ion-note>
      </ion-item>

      <ion-item-options side="end">
        <ion-item-option color="danger">
          <ion-icon slot="icon-only" name="trash"></ion-icon>
        </ion-item-option>
        <ion-item-option>
          <ion-icon slot="icon-only" name="star"></ion-icon>
        </ion-item-option>
      </ion-item-options>
    </ion-item-sliding>

    <ion-item-sliding>
      <ion-item>
        <ion-label>
          <h2>HubStruck Notifications</h2>
          <p>A new message in your network</p>
          <p>Oceanic Next has joined your network</p>
        </ion-label>
        <ion-note slot="end">
          10:45 AM
        </ion-note>
      </ion-item>

      <ion-item-options side="end">
        <ion-item-option color="danger">
          <ion-icon slot="icon-only" name="trash"></ion-icon>
        </ion-item-option>
        <ion-item-option>
          <ion-icon slot="icon-only" name="star"></ion-icon>
        </ion-item-option>
      </ion-item-options>
    </ion-item-sliding>

    <ion-item-sliding>
      <ion-item>
        <ion-label>
          <h2>HubStruck Notifications</h2>
          <p>A new message in your network</p>
          <p>Oceanic Next has joined your network</p>
        </ion-label>
        <ion-note slot="end">
          10:45 AM
        </ion-note>
      </ion-item>

      <ion-item-options side="end">
        <ion-item-option color="danger">
          <ion-icon slot="icon-only" name="trash"></ion-icon>
        </ion-item-option>
        <ion-item-option>
          <ion-icon slot="icon-only" name="star"></ion-icon>
        </ion-item-option>
      </ion-item-options>
    </ion-item-sliding>

**Comment by liamdebeasi** [comment] 2021-09-23 13:35
Thanks for the issue. I can reproduce this on iOS as well, though it is a bit harder to reproduce. The issue is that even after attempting to close the item, we are still accepting a gestures. Moving the item sliding a tiny bit will cause the item to remain open.

**Comment by liamdebeasi** [comment] 2021-09-23 14:02
Can you try the following dev build and let me know if it resolves the issue?

```
npm install @ionic/angular@5.9.0-dev.202109231358.4c3aac6
```

**Comment by Lightk3ira** [comment] 2021-09-23 15:12
Thank you, I will pull and test and have our QA team test as well. WIll update you on the details ASAP

**Comment by Lightk3ira** [comment] 2021-09-23 19:08
@liamdebeasi My team and I have tested this bug dilligently and it appears the issue is now resolved. It is working perfectly now.

**Comment by liamdebeasi** [comment] 2021-09-23 20:05
Thank you for testing!

**Comment by liamdebeasi** [comment] 2021-09-23 20:08
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/23973, and a fix will be available in an upcoming release of Ionic Framework.

**Closed** 2021-09-23 20:08 UTC
Labels: package: core, type: bug

**Comment by Lightk3ira** [comment] 2021-09-24 14:01
Thank you so much for the quick responses and fix. It is much appreciated. If there is anything else I can do please feel free to reach out. 

Thanks again!

**Comment by Lightk3ira** [comment] 2021-09-24 14:03
Do you have an ETA when that release will occur with the fix?

**Comment by liamdebeasi** [comment] 2021-09-24 14:26
We release roughly every 2-3 weeks with our most recent release on September 15. (There was a 5.8.1 release a few days ago, but that was a hotfix to fix a regression).
