### ISSUE TITLE
bug: footer disappears in modal sheet for Angular

### ISSUE THREAD

**Issue by SuvorovAlexey** [ionic-team/ionic-framework#25880] opened 2022-09-05 16:31 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

Footer is not fixed on the bottom of a page.
If I use sheet modal with breakpoints, I dont`t see **ion-footer** with the exception case when I open modal with breakpoint = 1.

![example](https://user-images.githubusercontent.com/55634865/188487596-300f4567-dbca-4039-80ca-e7eb12569a55.gif)

### Expected Behavior

Ion-footer fixed and visible at bottom of the page on any breakpoint.

### Steps to Reproduce

1. Create new project ionic + **Angular**
2. Create new modal with ion-header, ion-content and ion-footer (not matter inline modal or modalController)
3. Add different breakpoints for modal (for example you can use array with values [0.3, 0.6, 1] ).
4. Try to see ion footer when breakpoints is not equal 1

### Ionic Info

Ionic:

   Ionic CLI                     : 5.4.16 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 6.2.4
   @angular-devkit/build-angular : 13.2.6
   @angular-devkit/schematics    : 13.2.6
   @angular/cli                  : 13.3.8
   @ionic/angular-toolkit        : 3.1.1

Cordova:

   Cordova CLI       : 11.0.0
   Cordova Platforms : android, ios
   Cordova Plugins   : no whitelisted plugins (1 plugins total)

Utility:

   cordova-res : 0.15.4
   native-run  : not installed

System:

   Android SDK Tools : 26.1.1 (/home/alexey/Android/Sdk/)
   NodeJS            : v16.14.1 (/home/alexey/.nvm/versions/node/v16.14.1/bin/node)
   npm               : 8.5.0
   OS                : Linux 5.15

  ────────────────────────────────────────────────────────────

### Additional Information

**IMPORTANT :** This bug has been fixed for React https://github.com/ionic-team/ionic-framework/pull/24510 but I stiil see this bug in Angular

**Comment by SuvorovAlexey** [comment] 2022-09-08 08:39
@liamdebeasi
reproduction with StackBlitz:
Application URL: https://ionic6-angular13-szrffo.stackblitz.io
Editor URL: https://stackblitz.com/edit/ionic6-angular13-szrffo?file=src/app/app.component.html

**Comment by liamdebeasi** [comment] 2022-09-09 15:48
Thanks for the follow up. When you swipe to expand the sheet, you are moving the sheet, not resizing it. As a result, the footer will be off screen until the sheet is fully expanded. This is the intended behavior and is the same as what the header is doing. For this reason we typically do not recommend using footers or bottom toolbars in sheet modals.

**Comment by oneclickwebstudio** [comment] 2022-09-17 09:44
@liamdebeasi is it possible to add some attribute for modal ion-footer to make it fixed on bottom even if modal is not fully expanded?

**Comment by liamdebeasi** [comment] 2022-09-19 13:55
There is no attribute to do that because it would break the flex layout and likely impact the size of the `ion-content` inside of the modal. You could try using `position: absolute` and see if that helps for your app.

**Closed** 2022-10-05 19:26 UTC
Labels: needs: reply
