### ISSUE TITLE
bug: Keyboard - Chrome/Webview weird resizes

### ISSUE THREAD

**Issue by roman-rr** [ionic-team/ionic-framework#22664] opened 2020-12-11 19:06 UTC
# Bug Report
I create a div with `position:fixed` inside of `ion-content`. 
If div placed with `transform: translateX(550px)` which is lower than keyboard height, view (or ion-app or ion-content, i don't sure) will be moved up, or height resized, when keyboard open. 
Issue reproduced only on Android webview. 
Note: if you remove svg element from div with fixed position, view will resized back.
Perfect solution if view will not be moved or resized at all when keyboard open. 
Issue similar to [this](https://github.com/ionic-team/ionic-framework/issues/19065). 

**Ionic version:**
[x] **4.x**
[x] **5.x**

**Current behavior:**

**Expected behavior:**
View will not resized and moved when keyboard open. The same as for normal inputs. 

**Steps to reproduce:**
```bash
$ git clone https://github.com/roman-rr/ionic-keyboard-bug-demo.git
$ cd ionic-keyboard-bug-demo
$ npm i
$ ionic cordova run android
```
1. Tap input or textarea
2. ion-app resized or moved up
3. tap any place to close keyboard
4. ion-app doesn't resized back

**Related code:**
https://github.com/roman-rr/ionic-keyboard-bug-demo

**Other information:**
Please note that this is significant issue for our [package](https://github.com/roman-rr/cupertino-pane), and demo repository i provide here without our package, to show that it is ionic issue. 
We have last 5 issues in repository, which referred to this issue. 

**Ionic info:**

```
Any ionic version, but only on Android webview
```

**Comment by tigohenryschultz** [comment] 2020-12-11 19:42
Same thing is happening to me. I am unable to reproduce it on another test component I am making. The div that is position:fixed; seems to be pushed up when the keyboard is present even though it is set to top: 0; bottom: 0; left: 0; right: 0;

**Comment by liamdebeasi** [comment] 2020-12-11 22:09
Thanks for the issue. The issue here is that when the keyboard opens, Chromium attempts to scroll the content into view. However, it does not seem to reset the scroll position when the keyboard closes. This seems to be related to the fact that `#pane-container` extends off screen. If `#pane-container` were small enough such that it did not extend off screen, Chromium would reset the scroll position. Additionally, since we have `overflow: hidden` on `ion-app`, you are unable to scroll back up to the top.

While I can safely say this is not an Ionic Framework bug, I am not 100% certain that this is a Chromium bug. That being said, I uploaded a minimal reproduction to a GitHub repo here: https://github.com/liamdebeasi/chromium-scroll. If you feel that this is a Chromium bug, then I recommend creating a new issue on the [Chromium Issue Tracker](https://bugs.chromium.org/p/chromium/issues/list).

In terms of a temporary workaround, you may want to try setting `scrollTop = 0` on the scrollable content when the keyboard closes. However, it may make more sense to update your component so that it avoids this behavior entirely, if possible.

I am going to close this as this is not a bug in Ionic Framework. Thanks!

**Closed by liamdebeasi** 2020-12-11 22:09 UTC
Labels: triage

**Comment by tigohenryschultz** [comment] 2020-12-11 22:11
Here is an example of my issue, it might be a little different from yours.

In my pictures the ion-content element is being 'pushed' up for some reason, causing the 'canvas' element that i have fixed position/height and to move with it.

My code is not resizing anything when the keyboard triggers 'resize' and I can not figure out what is moving the ion-content section up and shrinking the height. I tried to reproduce this in a very simple component but was unable to.

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/75696293/101959532-59b63000-3bba-11eb-9a4e-dddfeab4ae30.png)
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/75696293/101959534-5a4ec680-3bba-11eb-8b18-e61b9cb95048.png)

**Comment by liamdebeasi** [comment] 2020-12-11 22:18
> @liamdebeasi would your response also apply to my issue with the keyboard being shown, not closed?

Can't say for certain, but it looks very similar.

**Comment by tigohenryschultz** [comment] 2020-12-11 23:06
@liamdebeasi 
Turns out the bug is if you position the element with 'top' instead of 'bottom' then it will try to calculate and fix the placement for you.

I was position the input with top: x, and changing it to bottom: 50px, since it should always be 50px from the bottom fixed it.

**Comment by tigohenryschultz** [comment] 2020-12-12 00:51
@liamdebeasi  Here is the bug: https://github.com/tigohenryschultz/keyboard-fixed-pos-bug


Step 1) Dynamically create an input after load and then use top/fixed to position it. 
Step 2) Click the input and your screen will move up weird
