### ISSUE TITLE
feat: Add template for SolidJS and a Getting Started ionic/solidjs to https://ionicframework.com/

### ISSUE THREAD

**Issue by PaulOst** [ionic-team/ionic-framework#26583] opened 2023-01-10 05:58 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Add first class support for SolidJS, including a typescript-ready template for working with Ionic's Web Components in JSX files. Document support of SolidJS in all the appropriate places in the ionicframework.com web site. e.g., Getting Started ionic/solidjs

### Describe the Use Case

1. Support this installation of the box:
   $ npm install -g @ionic/cli
   $ ionic start myApp tabs --type solidjs
   $ ionic serve

**Comment by liamdebeasi** [comment] 2023-01-10 13:56
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/25970.

**Closed by liamdebeasi** 2023-01-10 13:56 UTC
Labels: triage
