### ISSUE TITLE
bug: Firefox freeze on iOS

### ISSUE THREAD

**Issue by mebibou** [ionic-team/ionic-framework#19888] opened 2019-11-11 08:09 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
On Firefox for iOS, sometimes the page will freeze when the page contains a form and focusing in and out of form fields. The page will freeze for about 10 seconds before it can be interacted with again.
The same page does not causes any kind of freeze on Safari or Chrome on the same device (iOS `13.1.3`)

**Expected behavior:**

**Steps to reproduce:**
Using the stackblitz below I was able to reproduce, it takes a bit of time to make the page freeze but basically need to tap on a field, and another one, close the keyboard with the Close button (top right) and at some point the pages completely freezes and need to wait quite a while before it responds again

**Related code:**

https://stackblitz.com/edit/ionic-v4-angular-tabs-rj1tex?file=src/app/tab1/tab1.page.ts

**Other information:**

Tested on an iPhone 8+ running iOS `13.1.3` on Firefox `20.1 (16561)`

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.4.5 (/.nvm/versions/node/v12.5.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.3
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Utility:

   cordova-res : 0.6.0 (update available: 0.8.1)
   native-run  : 0.2.5 (update available: 0.2.9)

System:

   NodeJS : v12.5.0 (/nvm/versions/node/v12.5.0/bin/node)
   npm    : 6.13.0
   OS     : macOS Catalina
```

**Comment by liamdebeasi** [comment] 2021-09-16 17:13
Thanks for the issue. I am not able to reproduce this anymore using the latest version of Firefox on the latest version of iOS, so I am going to close this thread out. It is possible that there was an issue with iOS 13/Firefox 20 that was resolved in a later update.

If you encounter any additional problems, please open a new issue and include a code reproduction. Thank you!

**Closed by liamdebeasi** 2021-09-16 17:13 UTC
Labels: triage
