### ISSUE TITLE
bug: Label of ion-input is clipped and has zero padding-start when the placement is floating

### ISSUE THREAD

**Issue by aameen951** [ionic-team/ionic-framework#28301] opened 2023-10-07 17:48 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Start padding is zero on `ion-input` which `label-placement=floating` and `fill=outline` when placed inside `ion-item`. Also, the label is being clipped when it moves to the top.

![chrome_HPL2yqYbgP](https://github.com/ionic-team/ionic-framework/assets/7351160/af36ade8-b119-4a94-ad8f-7a4e5ff63123)

### Expected Behavior

The padding should be 16px.

### Steps to Reproduce

```vue
<template>
  <ion-page>

    <ion-content>

      <IonList :inset="true">

        <IonItem >
          <IonInput labelPlacement="stacked" fill=outline label="Input"></IonInput>
        </IonItem>

      </IonList>

    </ion-content>
  </ion-page>
</template>

<script setup lang="ts">
import { IonPage, IonContent, IonInput, IonList, IonItem } from '@ionic/vue';

</script>
```

### Ionic Info

F:\Workspace\all\acc-test>ionic info
[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package.json'
       
       Require stack:
       - C:\Users\Ameen\AppData\Roaming\npm\node_modules\@ionic\cli\lib\project\index.js
       - C:\Users\Ameen\AppData\Roaming\npm\node_modules\@ionic\cli\lib\index.js
       - C:\Users\Ameen\AppData\Roaming\npm\node_modules\@ionic\cli\index.js
       - C:\Users\Ameen\AppData\Roaming\npm\node_modules\@ionic\cli\bin\ionic

Ionic:

   Ionic CLI       : 7.1.1 (C:\Users\Ameen\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/vue 7.4.3

Capacitor:

   Capacitor CLI      : 5.4.2
   @capacitor/android : 5.4.2
   @capacitor/core    : 5.4.2
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.3

System:

   NodeJS : v18.12.0 (C:\Program Files\nodejs\node.exe)
   npm    : 9.8.1
   OS     : Windows 10

**Comment by liamdebeasi** [comment] 2023-10-09 13:01
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. As per the [input docs](https://ionicframework.com/docs/api/input#filled-inputs), filled inputs should not be used inside of `ion-item` because the filled inputs already visually defines the input container.

**Closed by liamdebeasi** 2023-10-09 13:01 UTC
Labels: triage
