### ISSUE TITLE
bug: Inline select error when using popover interface

### ISSUE THREAD

**Issue by acommend** [ionic-team/ionic-framework#26703] opened 2023-01-31 01:48 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [ ] v6.x
- [X] v7.x
- [ ] Nightly

### Current Behavior

Attempting to open an inline select when using the popover interface reports the following console error:

```
index.js?874b:1830 Uncaught (in promise) TypeError: Invalid value used as weak map key
    at WeakMap.set (<anonymous>)
    at Object.attachViewToDom (index.js?874b:1830:1)
    at attachComponent (framework-delegate.js?e7e5:10:1)
    at Popover.hasController.present (popover.js?59f0:1249:1)
    at Select.cancelText.open (ion-select.js?5f01:196:1
```

### Expected Behavior

The inline select popover should display the available options without error.

### Steps to Reproduce

1. Create an inline select with some select options with the interface set to "popover"
2. Render the select
3. Attempt to use the select to display the available options

### Code Reproduction URL

https://github.com/acommend/select-popover-error

### Ionic Info

Ionic:

   Ionic CLI       : 6.20.3 (C:\Users\Tony\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/vue 7.0.0-beta.0

Capacitor:

   Capacitor CLI      : 4.6.2
   @capacitor/android : not installed
   @capacitor/core    : 4.6.2
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.1

System:

   NodeJS : v16.18.1 (C:\Program Files\nodejs\node.exe)
   npm    : 8.19.2
   OS     : Windows 10

**Comment by liamdebeasi** [comment] 2023-01-31 16:25
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/26695. There is a dev build available in https://github.com/ionic-team/ionic-framework/issues/26695#issuecomment-1408668167. The fix for this bug has been merged and will be available in an upcoming release of Ionic. Let me know if you have any questions.

**Closed by liamdebeasi** 2023-01-31 16:25 UTC
Labels: triage
