### ISSUE TITLE
feat: progress bar style

### ISSUE THREAD

**Issue by pritamsoni-hsr** [ionic-team/ionic-framework#21728] opened 2020-07-11 22:02 UTC
# Feature Request

**Ionic version:**

[x] **5.x**

**Describe the Feature Request**

Border with IonProgressBar

**Describe Preferred Solution**

IonProgressBar uses transform:scaleX which doesn't allow adding any border-radius property (or other in general and will scale them accordingly) using `{width:(e*100%)}` instead would be a better approach when progress bar is not updating very frequently.

**Describe Alternatives**

**Related Code**

**Additional Context**

**Comment by liamdebeasi** [comment] 2020-07-13 13:04
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/20062. (same underlying issue)

**Closed by liamdebeasi** 2020-07-13 13:04 UTC
Labels: triage
