### ISSUE TITLE
bug: broken Anchor-Link scrolling

### ISSUE THREAD

**Issue by Floscho2402** [ionic-team/ionic-framework#26557] opened 2023-01-03 14:15 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

I'm using anchor-links inside my html templates. These Links are using angulars router like this:
`<a [routerLink]="['./']" [fragment]="'section-id'">go to section</a><section id="section-id">...</section>`

My RouterModule configuration looks like this:
`RouterModule.forRoot(routes, { preloadingStrategy: PreloadAllModules, anchorScrolling: 'enabled', onSameUrlNavigation: 'reload' })`

When clicking on the anchor link nothing happens. There is no reaction at all. But when the anchor-link points on an focusable element (like button, input, etc) everything works as expected. Setting tabindex=0 on the section fixes the issue also, but this should not be necessary.

### Expected Behavior

Anchor scrolling should always work, regardless of which element is the target. I tested this on a plain Angular project without Ionic and it was scrolling as expected (see reproduction section).

### Steps to Reproduce

I prepared two repositories. One with an Ionic starter app including one single page with some content and two anchor links for testing. The second repository includes an plain angular starter app with the same test page.
In the Angular project, you can see that it scrolls to the desired element at any time without having to set a tabindex there. In the Ionic project, only the anchor link that points to the section with tabindex=0 works.

It's enough to run the apps via 'ng serve' or 'ionic serve', go to localhost:4200 or localhost:8100 and reduce your browser-window height, so that the page is scrollable. Now click on the anchor-links at top of the page. The Code can be found here:

### Code Reproduction URL

https://github.com/Floscho2402/angular-working-anchor-links
https://github.com/Floscho2402/ionic-broken-anchor-links

### Ionic Info

Ionic:

   Ionic CLI                     : 6.18.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.4.1
   @angular-devkit/build-angular : 15.0.4
   @angular-devkit/schematics    : 15.0.4
   @angular/cli                  : 15.0.4
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.5.1
   @capacitor/android : not installed
   @capacitor/core    : 3.5.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.1

System:

   NodeJS : v16.13.0 (/usr/local/bin/node)
   npm    : 8.1.0
   OS     : macOS Monterey

**Comment by liamdebeasi** [comment] 2023-01-04 20:00
Thanks for the report. This looks like a duplicate of https://github.com/ionic-team/ionic-framework/issues/19365, so I am going to merge the two. Let me know if you have any questions.

**Closed by liamdebeasi** 2023-01-04 20:00 UTC
Labels: holiday triage
