### ISSUE TITLE
bug: The year / month selected in the year / month picker will be reflected in the calendar with a one-month shift.

### ISSUE THREAD

**Issue by tatsuyasenbom** [ionic-team/ionic-framework#24405] opened 2021-12-15 01:02 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

# Safari on iPhone iOS 15.1
* In Safari on iOS, after the ion-datetime embedded in ion-popover is displayed, the year / month selected in the year / month picker will be reflected in the calendar with a one-month shift.

https://user-images.githubusercontent.com/87968771/146101658-5c7cff37-9617-4e5d-b32e-ccb31797beb1.mp4

# Google Chrome on Android 12 or Windows10
* However, it will be reflected correctly on Google Chrome on Android or Windows.

https://user-images.githubusercontent.com/87968771/146101870-ee8c0f4d-673e-485f-b51c-56f27592abf3.mp4

### Expected Behavior

* I want you to improve the behavior of Safari on iOS.

### Steps to Reproduce

1. Run the code below to build.
    ```ts
    <ion-label>{{ report_date | date:"yyyy年MM月dd日 (EEE)" }}</ion-label>
    <ion-popover [isOpen]="isPopover" arrow="false" style="--offset-y: -35%;">
      <ng-template>
        <ion-datetime (ionChange)="onChangeDate($event)" showDefaultTitle="true" presentation="date">
          <div slot="title">報告日</div>
        </ion-datetime>
      </ng-template>
    </ion-popover>
    ```
2. I did the same operation as the video I uploaded to Current Behavior.

### Code Reproduction URL

* [add ion-datetime on ion-popover](https://github.com/tatsuyasenbom/ionic-angular-sample/commit/572165a25ec97044eb2a2a2920143664f23fa1b1)

### Ionic Info

```powershell
Ionic:

   Ionic CLI                     : 6.18.1 (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.0.1
   @angular-devkit/build-angular : 13.0.4
   @angular-devkit/schematics    : 13.0.4
   @angular/cli                  : 13.0.4
   @ionic/angular-toolkit        : 5.0.3

Capacitor:

   Capacitor CLI      : 3.3.3
   @capacitor/android : not installed
   @capacitor/core    : 3.3.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.5.0

System:

   NodeJS : v14.17.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.13
   OS     : Windows 10
```

**Comment by amandaesmith3** [comment] 2021-12-15 14:45
Thanks for the issue. Could you create a starter app that reproduces the problem and post a link to the repo here?

**Comment by tatsuyasenbom** [comment] 2021-12-16 02:39
> 

* I made a sample to reproduce the task using Ionic 6.0.1 x Angular 13.0.4.
    * [add ion-datetime on ion-popover](https://github.com/tatsuyasenbom/ionic-angular-sample/commit/572165a25ec97044eb2a2a2920143664f23fa1b1)
* Below are the builded files. I will attach it just in case.
    * [www.zip](https://github.com/ionic-team/ionic-framework/files/7724186/www.zip)

**Comment by amandaesmith3** [comment] 2021-12-16 16:47
Thanks! I'm able to replicate. It looks like the issue is that the datetime is too small, which is causing the intersection observers to fire when they shouldn't. As a workaround, you can set the datetime to a higher width -- it looks like `276px` does the trick.

Some other interesting things:
- I could only reproduce on iOS 15.0, 15.1, and 15.2. I could *not* reproduce on iOS 14.7.
- The bug only happens on iOS mode. MD mode works, even on iOS 15.

**Comment by tatsuyasenbom** [comment] 2021-12-17 01:00
> Thanks! I'm able to replicate. It looks like the issue is that the datetime is too small, which is causing the intersection observers to fire when they shouldn't. As a workaround, you can set the datetime to a higher width -- it looks like `276px` does the trick.
> 
> Some other interesting things:
> 
> * I could only reproduce on iOS 15.0, 15.1, and 15.2. I could _not_ reproduce on iOS 14.7.
> * The bug only happens on iOS mode. MD mode works, even on iOS 15.

Thank you for your answer !

I have avoided this phenomenon by fixing the mode to md once.

I'm looking forward to working properly with ios mode by default !

**Comment by liamdebeasi** [comment] 2022-01-11 20:12
Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue?

```
npm install @ionic/angular@6.0.2-dev.1641931632.6a7e2d1
```

**Comment by tatsuyasenbom** [comment] 2022-01-12 04:17
> Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue?
> 
> ```
> npm install @ionic/angular@6.0.2-dev.1641931632.6a7e2d1
> ```

Thank you very much for contacting me.

I built 315793a63bb60d29063cdcb11438a64d24d6bc10 and confirmed that Safari on iPhone iOS 15.2 improved the problem.

**Comment by liamdebeasi** [comment] 2022-01-12 15:24
Glad to hear the fix is working for you! This has been resolved via https://github.com/ionic-team/ionic-framework/pull/24554, and a fix will be available in an upcoming release of Ionic Framework.

**Closed** 2022-01-12 15:24 UTC
Labels: package: core, type: bug
