### ISSUE TITLE
bug: Slowly sideslip will switch multiple times

### ISSUE THREAD

**Issue by Cyclone77** [ionic-team/ionic-framework#25248] opened 2022-05-06 09:15 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

https://user-images.githubusercontent.com/10395760/167103087-0cf8f099-9517-441a-a63e-759c220096f6.mp4

### Expected Behavior

Return to previous page

### Steps to Reproduce

https://docs-demo.ionic.io/?ionic:mode=ios

ios15,safari

### Ionic Info

https://docs-demo.ionic.io/?ionic:mode=ios

**Comment by liamdebeasi** [comment] 2022-05-09 15:03
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. When running an Ionic app in the browser you have two separate swipe to go back gestures to deal with: Ionic's and the one provided by iOS (I.e. the native gesture).

In the example above, you are swiping on the native iOS swipe gesture, not Ionic's swipe gesture. When you change pages Ionic will automatically run a page transition. While it may appear to be a duplicate transition, the reality is that there is only one Ionic transition. The other transition comes from iOS.

This is more or less the same issue as https://github.com/ionic-team/ionic-framework/issues/22299. At the moment there is no way to disable the native iOS swipe to go back gesture. Please follow #22299 for updates on this. Thanks!

**Closed by liamdebeasi** 2022-05-09 15:03 UTC
Labels: triage
