### ISSUE TITLE
bug: Status Bar from iOS overlaps when IonPage does not have an IonHeader (Ionic + Vue)

### ISSUE THREAD

**Issue by amiraiouaz** [ionic-team/ionic-framework#25081] opened 2022-04-08 06:45 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Hello everyone,

First of all thanks for this great framework.

I just started a project with Ionic 6 and Vue using the tabs starter template and I am having the following issue on iOS when I have a page without an IonHeader (just with a IonContent) :

<img width="433" alt="image" src="https://user-images.githubusercontent.com/22788646/162378628-2747948c-469e-4a7f-82a8-26e956892f80.png">

The content goes under the Status Bar. When I read the docs for the layout :

<img width="722" alt="image" src="https://user-images.githubusercontent.com/22788646/162379216-0c1bbae4-d529-41ec-a370-e6d40a9549de.png">

It says the IonHeader is not required.

Is there any ways to fix this ? (No issues in Android)

Thank you !

### Expected Behavior

When I use a IonHeader, it works : 

<img width="441" alt="image" src="https://user-images.githubusercontent.com/22788646/162378812-1e969522-3a3a-4b38-b9f1-465fc92a7705.png">

### Steps to Reproduce

Just start a new Ionic Project using Vue and the tabs starter template and modify the Tab1Page with the following code : 

```
<template>
  <ion-page>
    <ion-content>
      <h1 class="ion-text-center">Tab 1</h1>

      <ExploreContainer name="Tab 1 page" />
    </ion-content>
  </ion-page>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import { IonPage, IonContent } from "@ionic/vue";
import ExploreContainer from "@/components/ExploreContainer.vue";

export default defineComponent({
  name: "Tab1Page",
  components: { ExploreContainer, IonContent, IonPage },
});
</script>
```

### Ionic Info

Ionic:

   Ionic CLI       : 6.18.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 6.0.15

Capacitor:

   Capacitor CLI      : 3.4.3
   @capacitor/android : not installed
   @capacitor/core    : 3.4.3
   @capacitor/ios     : 3.4.3

Utility:

   cordova-res (update available: 0.15.4) : 0.15.2
   native-run                             : 1.5.0

System:

   NodeJS : v17.3.1 (/usr/local/Cellar/node/17.3.1/bin/node)
   npm    : 8.3.0
   OS     : macOS Big Sur

**Comment by liamdebeasi** [comment] 2022-04-08 13:18
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework.

We intended for all pages to have an `ion-header` with an `ion-toolbar`.  We have code that applies the safe area to the first toolbar so that your header does not overlap with the statusbar: https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/header/header.scss#L17-L19

In the event you do not want a header on a page, you can apply the safe area padding by targeting the `ion-content`:

```css
ion-content {
  --padding-top: var(--ion-safe-area-top, 0);
}

**Closed by liamdebeasi** 2022-04-08 13:18 UTC
Labels: triage

**Comment by amiraiouaz** [comment] 2022-04-08 13:41
> 

Thanks a lot the for explanation ! Everything is working now !
