### ISSUE TITLE
Ionic split pane getting hide when navigate to some page and coming back again to first page.

### ISSUE THREAD

**Issue by yogeshshsf** [ionic-team/ionic-framework#18551] opened 2019-06-15 09:32 UTC
I am using 2 split-pane, firstmenu/firstpage will be my home screen. from firstpage i am navigating to secondmenu/secondpage. now when i return back to firstmenu/firstpage, the split-pane is getting hide. can someone tells me where is the issue. i have have github setup for this:
https://github.com/yogeshshsf/SplitpaneDemo

**Comment by Mooiq** [comment] 2019-06-24 08:03
I have the same problem

**Comment by ErlendEllingsen** [comment] 2019-07-07 17:30
Also having the same behaviour.

**Comment by liamdebeasi** [comment] 2022-04-25 14:16
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/18683 (related underlying issue).

**Closed by liamdebeasi** 2022-04-25 14:16 UTC
Labels: triage
