### ISSUE TITLE
bug: modal does not reopen after clicking outside 

### ISSUE THREAD

**Issue by Toto5931** [ionic-team/ionic-framework#22663] opened 2020-12-11 18:34 UTC
# Bug Report

**Ionic version:**
[x] **5.5.1**

**Current behavior:**
I have a simple app with a button "Show modal" as in the example of the documentation. The modal opens when I click. On a big screen the modal does not occupy all the screen. If I click oustide the modal, it closes correctly. But if I want to reopen again it does not open, nothing happens

**Expected behavior:**
The modal should open, even after being closed by a click outside it

**Steps to reproduce:**
Download https://github.com/Toto5931/ionic-bug-modal and "ionic serve", click on the button, click outside of the modal and click again on the button: it does not open

**Related code:**
```
const App: React.FC = () => {
  const [showModal, setShowModal] = useState(false);
  return (
    <IonApp>
      <IonContent>
        <IonModal isOpen={showModal} cssClass='my-custom-class'>
          <p>This is modal content</p>
          <IonButton onClick={() => setShowModal(false)}>Close Modal</IonButton>
        </IonModal>
        <IonButton onClick={() => setShowModal(true)}>Show Modal</IonButton>
      </IonContent>
    </IonApp>
  );
}
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.5.0 (C:\Users\zorro\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/react 5.5.2

Capacitor:

   Capacitor CLI   : 2.4.4
   @capacitor/core : 2.4.4

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.16.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.13.4
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment] 2020-12-11 19:01
Thanks for the follow up. I am going to close this as this is not a bug in Ionic Framework. The problem here is that you are not properly updating the "showModal" state. Since you are using useState in React, you need to explicitly set the show modal state to false when the modal has closed:

```jsx
<IonModal isOpen={showModal} onDidDismiss={() => setShowModal(false)}>...</IonModal>
```

**Closed by liamdebeasi** 2020-12-11 19:01 UTC
Labels: triage
