### ISSUE TITLE
feat(generic): placeholder-font-size

### ISSUE THREAD

**Issue by indraraj26** [ionic-team/ionic-framework#21862] opened 2020-08-01 13:17 UTC
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

::placeholder style is not getting applied
https://codepen.io/indraraj26/pen/VweoQqe

**Describe Preferred Solution**

expose placeholder-font-size 

**Describe Alternatives**

**Related Code**

**Additional Context**

**Comment by liamdebeasi** [comment] 2020-08-03 13:25
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. You need to target the inner `input` for this to work:

```css
.test input::placeholder {
  font-size: 5px;
}
```

**Closed by liamdebeasi** 2020-08-03 13:25 UTC
Labels: triage

**Comment by indraraj26** [comment] 2020-08-09 15:46
https://github.com/ionic-team/ionic-framework/issues/21898
