### ISSUE TITLE
bug: ion-content scroll not working

### ISSUE THREAD

**Issue by ansocha** [ionic-team/ionic-framework#25729] opened 2022-08-05 17:42 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

```
@ViewChild(IonContent) content: IonContent;

console.log(this.content); //reference to ion-content valid

this.content.scrollToBottom(); //but won't scroll
```

and

```
<ion-content [scrollEvents]="true" 
       (ionScrollEnd)="logScrollEnd($event)"> // won't trigger
  
   <!-- long list of items -->

</ion-content>
```

### Expected Behavior

Basically trying to get the ion-content to scroll and trigger events in a browser as per the documentation.

### Steps to Reproduce

Setup a component with a ion-content with [scrollEvents]="true" .

Events and methods don't work.

### Ionic Info

Ionic:

   Ionic CLI                     : 6.20.1 (/home/jargon/.npm-global/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.2.1
   @angular-devkit/build-angular : 14.1.1
   @angular-devkit/schematics    : 14.1.1
   @angular/cli                  : 14.1.1
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 4.0.1
   @capacitor/android : 4.0.1
   @capacitor/core    : 4.0.1
   @capacitor/ios     : 4.0.1

Utility:

   cordova-res : not installed globally
   native-run  : 1.6.0

System:

   NodeJS : v14.17.3 (/usr/bin/node)
   npm    : 8.16.0

**Comment by sean-perkins** [comment] 2022-08-05 18:09
@ansocha can you please provide a reproduction?

I am unable to reproduce with the information you have provided: https://stackblitz.com/edit/angular-ewr4yq
* Scroll events emit correctly
* IonContent scrolls to bottom programmatically

**Comment by ansocha** [comment] 2022-08-05 20:06
Closing this. I reinstalled all packages. Started new project and it now works.

thank you

**Comment by amandaejohnston** [comment] 2022-08-08 13:59
Closing this out per the above, but let us know if you're able to reproduce the issue in a starter app and we'll take a look 👍

**Closed by amandaejohnston** 2022-08-08 13:59 UTC
Labels: ionitron: needs reproduction
