### ISSUE TITLE
bug: Ionic Vue Back Button disappears

### ISSUE THREAD

**Issue by BerkeAras** [ionic-team/ionic-framework#22340] opened 2020-10-17 08:07 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
The IonBackButton in Ionic Vue disappears after fully navigating to page. While transition it is visible.

**Expected behavior:**
IonBackButton should not disappear and should be visible.

**Steps to reproduce:**
Navigate to page "Page-2"

**Related code:**
[https://github.com/BerkeAras/Ionic-Vue-BackButton-Issue/tree/master/myApp](https://github.com/BerkeAras/Ionic-Vue-BackButton-Issue/tree/master/myApp)

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.12.0 (C:\Users\Berke\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/vue 5.4.0

Capacitor:

   Capacitor CLI   : 2.4.2
   @capacitor/core : 2.4.2

Utility:

   cordova-res : 0.15.1
   native-run  : not installed

System:

   NodeJS : v12.18.2 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.5
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment] 2020-10-19 15:04
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. You placed your `ion-back-button` in the collapsible header, not the main header. Your template should look like this:

```html
<template>
  <ion-page>
    <ion-header :translucent="true">
      <ion-toolbar>
        <ion-buttons slot="start">
          <ion-back-button></ion-back-button>
        </ion-buttons>
        <ion-title>Blank</ion-title>
      </ion-toolbar>
    </ion-header>
    
    <ion-content :fullscreen="true">
      <ion-header collapse="condense">
        <ion-toolbar>
          <ion-title size="large">Page 2</ion-title>
        </ion-toolbar>
      </ion-header>
    
      <div id="container">
        <strong>Page 2</strong>
    	</div>
    </ion-content>
  </ion-page>
</template>
```

**Closed by liamdebeasi** 2020-10-19 15:04 UTC
Labels: triage
