### ISSUE TITLE
feat: Date and Time Pickers Infinite Scroll

### ISSUE THREAD

**Issue by clowcher** [ionic-team/ionic-framework#28770] opened 2024-01-02 14:38 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

It would be great if the `ion-datetime` component could infinitely scroll over the options like the native iOS alarm app does. 

![image](https://github.com/ionic-team/ionic-framework/assets/101572065/9ae190b3-74f3-431a-a6da-cc8b94d621a6)

Essentially, when you get to `12` or `24` on the hours wheel, it would let you keep scrolling back to `1`.
And same for minutes, when you get to `59` you can keep scrolling to get back to `0`.

### Describe the Use Case

We've had multiple customers request this feature on our app. It would mainly be a Quality of Life improvement and isn't solving a major problem or anything. It just makes the time picker much faster and easier to use. 

I can't speak for Android as much, but our iOS customers are familiar with this feature and seem to be confused when our app doesn't work the same way. 

### Related Code

in Vue: 

`<ion-datetime :infinite-scroll="true" />`
OR
`<ion-datetime infinite-scroll />`

or maybe `continuous-scroll` ?

**Comment by mapsandapps** [comment] 2024-01-02 15:11
Hi, thanks for the issue. I'm going to close this as a duplicate of #26268.

**Closed by mapsandapps** 2024-01-02 15:11 UTC
Labels: holiday triage

**Comment by clowcher** [comment] 2024-01-02 16:47
ah sorry about that! I kept searching things like "infinite" or "continuous" scroll and that one never popped up.
