### ISSUE TITLE
bug: ionic react, onIonScroll triggered frequently even without scrolling

### ISSUE THREAD

**Issue by Richa-Singh-1** [ionic-team/ionic-framework#22752] opened 2021-01-10 14:22 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
The top header flickers continously before beign shown or hidden because of multiple onIonScroll event triggered. 

**Expected behavior:**
The top header should be  hidden/ displayed  on scroll without flickering.

**Steps to reproduce:**
Please use this sample code https://github.com/Richa-Singh-1/ionic-onScroll-fired-multiple-times to reproduce.
*Behavior seems fine when length of scrollable content is within certain limit( ex: add 4-5 more divs and the bug won't reproduce)

**Related code:**
https://github.com/Richa-Singh-1/ionic-onScroll-fired-multiple-times

```
<IonContent
          scrollEvents={true}
          onIonScroll={(e) => onscroll(e.detail.scrollTop)} 
        >
```

**Other information:**

**Ionic info:**

"@ionic/react": "5.4.0",
"react": "17.0.1",

```
ionic:

   Ionic CLI       : 5.4.16 (/usr/local/lib/node_modules/ionic)
   Ionic Framework : @ionic/react 5.4.0

Capacitor:

   Capacitor CLI   : 2.4.2
   @capacitor/core : 2.4.2

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.19.0 (/usr/local/bin/node)
   npm    : 6.14.8
   OS     : macOS Catalina
```

**Comment by liamdebeasi** [comment] 2021-01-11 14:50
Thanks for the issue. I can only reproduce this behavior when scrolling overflow happens in Safari (the rubber band effect). Is this what you are referring to?

**Comment by Richa-Singh-1** [comment] 2021-01-11 15:14
The bug reproduces on Chrome too(desktop+ mobile view both).
On chrome, please switch to iphoneX(mobile view).

**Comment by liamdebeasi** [comment] 2021-01-11 15:17
Can you provide some steps to reproduce the issue? I cannot reproduce this in Chrome.

**Comment by Richa-Singh-1** [comment] 2021-01-11 15:51
@liamdebeasi You could try keeping 2 divs extra from overflow(chrome:iphoneX).

**Comment by liamdebeasi** [comment] 2021-01-11 20:27
The behavior I am seeing is the moment I try and scroll down, the header hides. The moment I try and scroll up, the header shows. Is this the behavior you are describing?

If not, can you provide a video of the behavior you are experiencing?

**Comment by Richa-Singh-1** [comment] 2021-01-11 20:36
Placed movie(bug)  @ https://drive.google.com/drive/folders/1oZPFO11jkAwsg7faCQHIxpz7Ua4-qKQV?usp=sharing

**Comment by liamdebeasi** [comment] 2021-01-11 20:42
Thanks. What version of Chrome are you testing this on?

**Comment by Richa-Singh-1** [comment] 2021-01-11 20:42
@liamdebeasi  Version 87.0.4280.88 (Official Build) (x86_64)

**Comment by liamdebeasi** [comment] 2021-01-11 20:51
Thanks. I was able to reproduce this behavior -- the key was setting it to the "iPhone X" simulation setting. 

I am going to close this as this is not a bug in Ionic Framework. The problem is that you are setting `display: none` on the toolbar, which is going to cause the scrollable content to be repainted, causing another scroll event to fire. Because of the dimensions on the iPhone X setting, the scroll amount in this new scroll event is just enough to cause your `onScroll` callback to set `display: block` on the toolbar, thus causing another scroll.

**Closed by liamdebeasi** 2021-01-11 20:51 UTC
Labels: triage
