### ISSUE TITLE
bug: Ionic/Angular (Nested) Router issue, next Component not loading and not being displayed 

### ISSUE THREAD

**Issue by ThomasOliver545** [ionic-team/ionic-framework#19340] opened 2019-09-13 19:17 UTC
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
In our Ionic/Angular Application we are seeing a quite strange behavior and are not able to solve it.
When we navigate in our app to e.g. this route:
`http://localhost:8100/tabs/projects/5d3b0763537555635c7f9e12`
and wether if we route in our html like
`[routerLink]="['add-report']"`
or in the component over
`this.router.navigate(['./add-report'], { relativeTo: this.route});`

Then it adds 'add-report' to the route, so the route looks like this:
`http://localhost:8100/tabs/projects/5d3b0763537555635c7f9e12/add-report`

But the component is not loaded and not displayed.

**Expected behavior:**
The component should be loaded and displayed if the route changes.

**Steps to reproduce:**

In our Ionic/Angular Application we are seeing a quite strange behavior and are not able to solve it.
When we navigate in our app to e.g. this route:
`http://localhost:8100/tabs/projects/5d3b0763537555635c7f9e12`
and wether if we route in our html like
`[routerLink]="['add-report']"`
or in the component over
`this.router.navigate(['./add-report'], { relativeTo: this.route});`

Then it adds 'add-report' to the route, so the route looks like this:
`http://localhost:8100/tabs/projects/5d3b0763537555635c7f9e12/add-report`

But the component is not loaded and not displayed.

Either if we use the routing like:

 `{
    path: ':projectId',
    component: ProjectOverviewComponent,
    children: [
      {
        path: 'add-report',
        component: AddReportComponent
      }
    ]`

with a `<router-outlet>` 
or the router-module, it is not working.

If you need more information please ask.

**Comment by meanstack-perficient** [comment] 2019-10-19 00:13
same issues here loading nested route configurations that require router-outlet

not fun, I am using trial and error to name my child outlet to get something to stick

all I see in the markup of elements is <router-outlet> when I should be seeing elements of the child component projected

Has this child content projection been nailed down yet?

I know it may be picky about header/content layout... 
but I cannot get anything to render here

**Comment by amandaesmith3** [comment] 2022-02-15 21:02
Thanks for the issue! I know it's been a while, but I wanted to circle back to this. The original post is missing a proper code reproduction, such as a Github repo minimally replicating the issue. Normally I would just ask for one and go from there, but since this thread is quite old and hasn't gotten any attention since, I'm just going to close this out.

If this is still a problem you're having in the latest version of Ionic, please open a new issue and ensure the template is fully filled out. Thank you!

**Closed by amandaesmith3** 2022-02-15 21:02 UTC
Labels: triage
