### ISSUE TITLE
bug: type problems with vue-tsc

### ISSUE THREAD

**Issue by aparajita** [ionic-team/ionic-framework#25503] opened 2022-06-19 03:53 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

`vue-tsc` used to work without issues with Ionic 5. I just upgraded an app to Ionic 6 and I'm getting this same error on every use of an Ionic component in an SFC template:

```
Type '{ class: string; }' is not assignable to type 'IntrinsicAttributes & Partial<{}> & Omit<Readonly<IonButton & InputProps> & VNodeProps & AllowedComponentProps & ComponentCustomProps, never>'.
  Property 'modelValue' is missing in type '{ class: string; }' but required in type 'Omit<Readonly<IonButton & InputProps> & VNodeProps & AllowedComponentProps & ComponentCustomProps, never>'.

148       <IonButton
           ~~~~~~~~~

  node_modules/.pnpm/@ionic+vue@6.1.10/node_modules/@ionic/vue/dist/types/vue-component-lib/utils.d.ts:2:5
    2     modelValue: string | boolean;
          ~~~~~~~~~~
    'modelValue' is declared here.
```

### Expected Behavior

No error.

### Steps to Reproduce

```sh
% ionic start vue-tsc blank --type vue
% cd vue-tsc
% npm i -D vue-tsc
% node_modules/.bin/vue-tsc --noEmit

<bunch of error output>

Found 7 errors in the same file, starting at: src/views/HomePage.vue:3
```

### Ionic Info

Ionic:

   Ionic CLI       : 6.20.0 (/Users/aparajita/Library/pnpm/global/5/.pnpm/@ionic+cli@6.20.0/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 6.1.10

Capacitor:

   Capacitor CLI      : 3.6.0
   @capacitor/android : not installed
   @capacitor/core    : 3.6.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v18.4.0 (/Users/aparajita/.fnm/node-versions/v18.4.0/installation/bin/node)
   npm    : 8.12.1
   OS     : macOS Monterey

### Additional Information

vue-tsc v0.38.0

vue-tsc does a lot stricter checking than @typescript/eslint, so it well could be a problem with the Ionic types.

**Comment by KANekT** [comment] 2022-06-19 05:31
Duplicate https://github.com/ionic-team/ionic-framework/issues/25485

**Comment by liamdebeasi** [comment] 2022-06-21 12:51
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/25485.

There is a dev build in https://github.com/ionic-team/ionic-framework/issues/25485#issuecomment-1158975412 with a fix. This fix will be shipped to production in the next release of Ionic.

**Closed by liamdebeasi** 2022-06-21 12:51 UTC
Labels: triage
