### ISSUE TITLE
bug: choppy modal animation

### ISSUE THREAD

**Issue by farisfaisalthena** [ionic-team/ionic-framework#25851] opened 2022-08-30 13:13 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

When having a modal presented and adding searchbar on the header and button on the footer will cause the modal animation to be wierd when keyboard is currently opened. The video can be seen [here](https://www.youtube.com/watch?v=uRHBe3AG6Rg)

### Expected Behavior

The dismiss modal animation should be smooth regardless if the keyboard is open or not

### Steps to Reproduce

1. Create new Ionic project
2. Create a modal
3. Add searchbar on the header and `ion-button` on the footer

### Ionic Info

Ionic:

   Ionic CLI                     : 6.19.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.2.4
   @angular-devkit/build-angular : 14.2.1
   @angular-devkit/schematics    : 14.2.1
   @angular/cli                  : 14.2.1
   @ionic/angular-toolkit        : 7.0.0

Capacitor:

   Capacitor CLI      : 4.1.0
   @capacitor/android : 4.1.0
   @capacitor/core    : 4.1.0
   @capacitor/ios     : 4.1.0

Utility:

   cordova-res : 0.15.4
   native-run  : 1.6.0

System:

   NodeJS : v16.17.0 (/usr/local/bin/node)
   npm    : 8.15.0
   OS     : macOS Monterey

**Comment by liamdebeasi** [comment] 2022-08-30 13:47
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/22018.

**Closed by liamdebeasi** 2022-08-30 13:47 UTC
Labels: triage
