### ISSUE TITLE
feat: @ionic/angular ion-tabs can't access ion-router-outlet properties

### ISSUE THREAD

**Issue by greg-md** [ionic-team/ionic-framework#28539] opened 2023-11-15 23:44 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Please provide a way to manage `ion-router-outlet` within `ion-tabs` for Angular, like you did for Vue in https://github.com/ionic-team/ionic-framework/issues/23321

### Describe the Use Case

I would like to customize animations for child pages within specific tabs.

### Describe Preferred Solution

It can be done the same way as for vue, to make it required inside ion-tabs:
```
<ion-tabs>
  <ion-router-outlet></ion-router-outlet>
  <ion-tab-bar>...</ion-tab-bar>
</ion-tabs>
```

**Comment by liamdebeasi** [comment] 2023-11-16 14:16
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/19330.

**Closed by liamdebeasi** 2023-11-16 14:16 UTC
Labels: triage
