### ISSUE TITLE
bug: ion-item highlight line displayed twice

### ISSUE THREAD

**Issue by Mr-Mime** [ionic-team/ionic-framework#25930] opened 2022-09-13 13:31 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

After upgrading from 5.x to 6.x I noticed that the line of some input fields was shown twice when selected (highlighted).
To confirm that it is not an issue with some css or custom elements, I opened a example project in stackblitz.

I was able to confirm that under different zoom levels the line is shown twice or once.

### Expected Behavior

I expect to always only see one line.

### Steps to Reproduce

I took the first modal example code from the v6.x docs.
Here: https://ionicframework.com/docs/api/modal#inline-modals-recommended
And opened it in stackblitz via the button in the preview.

When stackblitz has loaded I press the open button and then select the input field of the modal.
When zooming in and out I see two lines at different zoom levels.

Here is what it looks like on 120% for me:
![Screenshot 2022-09-13 15:18:29](https://user-images.githubusercontent.com/37423773/189913894-da6ea581-3ca9-4b6c-b851-bc0c95b83f9c.png)

 

### Ionic Info

```

Ionic:

   Ionic CLI                     : 6.17.1 (/usr/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.2.6
   @angular-devkit/build-angular : 12.2.8
   @angular-devkit/schematics    : 12.2.8
   @angular/cli                  : 12.2.8
   @ionic/angular-toolkit        : 4.0.0

Capacitor:

   Capacitor CLI      : 4.2.0
   @capacitor/android : 4.2.0
   @capacitor/core    : 4.2.0
   @capacitor/ios     : 4.2.0

Utility:

   cordova-res (update available: 0.15.4) : 0.15.3
   native-run                             : 1.7.0

System:

   NodeJS : v16.15.1 (/usr/bin/node)
   npm    : 8.5.5
   OS     : Linux 5.10
```

**Comment by liamdebeasi** [comment] 2022-09-13 13:33
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/25431.

**Comment by liamdebeasi** [comment] 2022-09-13 13:34
I also updated the description of #25431 since I think it was a bit hard to find.

**Closed by liamdebeasi** 2022-09-13 13:33 UTC
Labels: triage

**Comment by Mr-Mime** [comment] 2022-09-13 13:44
Hmm don't know how I missed this one...
Thanks :+1:
