### ISSUE TITLE
datetime - how to get year and month value in presentation=datetime

### ISSUE THREAD

**Issue by praveeno** [ionic-team/ionic-framework#25650] opened 2022-07-18 04:08 UTC
rendering a ionic-date time
`<ion-datetime #popoverDatetime2
                      showDefaultButtons="true"
                      doneText="OK"
                      presentation="date"
                      [max]="today"
                      (ionChange)="formatDate(popoverDatetime2.value)">`
                      
 when we click top left, month-year option, it change in month-year mode,
 here if i select any month and year, and press ok, it close, but not getting correct month & year in ionChange
 
![image](https://user-images.githubusercontent.com/19618730/179443946-d4419862-2a5c-482e-adc0-1ef4a8537c05.png)

https://github.com/ionic-team/ionic-framework/blob/b7afcb0f0c36d84f3b4d65844df28e6293bc1ea5/core/src/components/datetime/datetime.tsx#L1188

**Comment by praveeno** [comment] 2022-07-18 04:10
currently I'm getting month & year from dom, and manually updating it in angular form

**Comment by sean-perkins** [comment] 2022-07-18 16:25
Please use our issue template when reporting an issue with Ionic. We will need a reproduction app to better understand your problem.

**Comment by praveeno** [comment] 2022-07-21 17:17
not raising a UI or functional bug, need a understanding, as not able to fingure out how to let use change year and month, as mentioned in screenshot, once i select month and year, and click okay, the popover close, but value is not updated in formGroup

**Comment by liamdebeasi** [comment] 2022-08-01 13:52
Hey there,

The [Ionic Forum](https://forum.ionicframework.com/) is a better place to get help with Ionic. We use this tracker exclusively for bug reports or feature requests.

However, your questions seems to be related to https://github.com/ionic-team/ionic-framework/issues/25585. We do not preserve the date when selecting the month/year. As a result, the correct date is never set when confirming the date selection.

We also made changes in [Ionic v6.1.4](https://github.com/ionic-team/ionic-framework/commit/aa5e1b962150b9ed9629812ec566873784526c83) to hide the confirm/cancel buttons when showing the month and year wheel. Developer feedback indicated that it was not clear what the buttons were meant to do (confirm the date selection? close the month/year view? something else).

I am going to close this, but I recommend following #25585 for updates on the issue. Thanks!

**Closed by liamdebeasi** 2022-08-01 13:52 UTC
Labels: ionitron: needs reproduction
