### ISSUE TITLE
bug: Keyboard button "next" does not focus on correct input/field.

### ISSUE THREAD

**Issue by SidiBecker** [ionic-team/ionic-framework#22463] opened 2020-11-09 21:29 UTC
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
When I click the "next" button on the keyboard, the focus goes to the next "ion-input" field, even though I previously had an "ion-select" field.

**Expected behavior:**
When you click the "next" button the focus should go to the next "ion-item" of the form.

**Steps to reproduce:**
Start a new project
On a page, put the code below

**Related code:**
```
<form>
    <ion-item tabindex="1">
      <ion-label color="secondary" position="floating" stacked>Item 1
      </ion-label>
      <ion-input text-uppercase maxlength="60" class="f-14" type="text" clearInput></ion-input>
    </ion-item>

    <ion-item tabindex="2">
      <ion-label color="secondary" position="floating" stacked>Item 2
      </ion-label>
      <ion-select class="f-14" [interfaceOptions]="{ header: 'TESTE' }" okText="CONFIRMAR" cancelText="CANCELAR"
        interface="alert">
        <ion-select-option class="f-14">
          valor</ion-select-option>
      </ion-select>
    </ion-item>

    <ion-item tabindex="3">
      <ion-label color="secondary" position="floating" stacked>Item 3
      </ion-label>
      <ion-select class="f-14" [interfaceOptions]="{ header: 'TESTE' }" okText="CONFIRMAR" cancelText="CANCELAR"
        interface="alert">
        <ion-select-option class="f-14">
          valor</ion-select-option>
      </ion-select>
    </ion-item>

    <ion-item tabindex="4">
      <ion-label color="secondary" position="floating" stacked>Item 4

      </ion-label>
      <ion-input #enderecoCep class="f-14" maxlength="9" type="tel" clearInput>
      </ion-input>
    </ion-item>

    <ion-item tabindex="5">
      <ion-label color="secondary" position="floating" stacked>Item 5
      </ion-label>
      <ion-select class="f-14" [interfaceOptions]="{ header: 'TESTE' }" okText="CONFIRMAR" cancelText="CANCELAR"
        interface="alert">
        <ion-select-option class="f-14">
          valor</ion-select-option>
      </ion-select>
    </ion-item>

    <ion-item tabindex="6">
      <ion-label color="secondary" position="floating" stacked>Item 6
      </ion-label>
      <ion-input text-uppercase maxlength="60" class="f-14" type="text" clearInput></ion-input>
    </ion-item>


    <ion-item tabindex="7">
      <ion-label color="secondary" position="floating" stacked>Item 7
      </ion-label>
      <ion-input text-uppercase maxlength="60" class="f-14" type="text" clearInput></ion-input>
    </ion-item>

  </form>
```

**Other information:**
The focus sequence is in the fields:
1 --> 4 --> 6 --> 7. These are ion-input fields.

Original (but clock and limited?) issue: https://github.com/ionic-team/ionic-framework/issues/19504

**Ionic info:**

```
   Ionic CLI                     : 6.9.2 (C:\Program Files\node-js\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.2.3
   @angular-devkit/build-angular : 0.803.28
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.3.28
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.2, (and 29 other plugins)

Utility:

   cordova-res : 0.8.1
   native-run  : 0.2.8

System:

   Android SDK Tools : 26.1.1 (D:\Android\sdk)
   NodeJS            : v10.16.0 (C:\Program Files\node-js\node.exe)
   npm               : 6.9.0
   OS                : Windows 10
```

**Comment by liamdebeasi** [comment] 2020-11-10 13:49
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/19504. We locked the issue so others on the thread did not continue to get emails every time someone commented saying that they had the bug.

**Closed by liamdebeasi** 2020-11-10 13:49 UTC
Labels: triage
