### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by khain2007** [ionic-team/ionic-framework#22824] opened 2021-01-26 20:51 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

In iOS, an ion-item requires more than one tap to activate the click event.

**Expected behavior:**

Only one tap should be required.

**Steps to reproduce:**

Copy and paste a code similar to the one that I attach, and you well required more than one tap on iOS to activate the click event.

**Related code:**

```
<ion-item [detailIcon]="null" [ngStyle]="{'margin-top':passengers ? 0 : '30px'}" button (click)="showPassengerPicker()">
        <ion-label color="primary" position="floating">
          <div style="position:absolute; top:2px;">
            <ion-icon name="people-outline"></ion-icon>
          </div>
          <span style="margin-left:20px;" i18n>Passengers</span>
        </ion-label>
        <ion-input style="user-select: none" readonly [value]="passengers"></ion-input>
      </ion-item>
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.12.3 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.5.2
   @angular-devkit/build-angular : 0.1100.7
   @angular-devkit/schematics    : 11.0.7
   @angular/cli                  : 11.0.7
   @ionic/angular-toolkit        : 3.0.0

Capacitor:

   Capacitor CLI   : 2.4.6
   @capacitor/core : 2.4.6

Utility:

   cordova-res                          : not installed
   native-run (update available: 1.3.0) : 0.3.0

System:

   NodeJS : v15.6.0 (/opt/homebrew/Cellar/node/15.6.0/bin/node)
   npm    : 7.4.0
   OS     : macOS Big Sur
```

**Comment by liamdebeasi** [comment] 2021-01-27 14:15
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/21871.

**Closed by liamdebeasi** 2021-01-27 14:15 UTC
Labels: triage
