### ISSUE TITLE
bug: IonInput has no placeholder text when type="time"

### ISSUE THREAD

**Issue by Shruti2906** [ionic-team/ionic-framework#29070] opened 2024-02-19 13:55 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

<IonInput type="time" placeholder="Time" value={schedule.time}/>

"Time" placeholder not being displayed. The input shows up with an empty(__:__) placeholder.

### Expected Behavior

That the placeholder would show up in the input, before a time is selected.

### Steps to Reproduce

Create an IonInput with the following (tried both undefined and null) and neither resulted in the placeholder showing up.

<IonInput type="time" placeholder="Time" value={schedule.time}/>
<IonInput type={schedule.time ? : undefined : "time"} placeholder="Time" value={schedule.time}/>

### Ionic Info

ionic info

Ionic:

   Ionic CLI       : 7.1.1 (C:\Users\codin\AppData\Roaming\nvm\v16.20.2\node_modules\@ionic\cli)
   Ionic Framework : @ionic/react 7.5.6

Capacitor:

   Capacitor CLI      : 5.6.0
   @capacitor/android : 5.5.1
   @capacitor/core    : 5.5.1
   @capacitor/ios     : 5.5.1

Utility:

   cordova-res : not installed globally
   native-run  : 2.0.1

System:

   NodeJS : v16.20.2 (C:\Program Files\nodejs\node.exe)
   npm    : 8.19.4
   OS     : Windows 10

**Comment by Shruti2906** [comment] 2024-02-23 16:39
Here is the github link for reproduced code:  https://github.com/Shruti2906/ionicPlaceHolderIssue

**Comment by amandaejohnston** [comment] 2024-02-27 19:18
Thank you, and apologies for the delay. This behavior matches that of a native `<input>`: https://codepen.io/Amanda-Johnston/pen/eYoOWod

In general, I would not recommend using the `placeholder` attribute as a substitute for a label, as this has accessibility problems. You can read more here: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/placeholder#accessibility_concerns

Instead, I would try one of these two alternatives:
1. Use the `label` prop of `IonInput` instead of `placeholder`.
2. Use an `IonDatetimeButton` instead of an `IonInput`: https://ionicframework.com/docs/api/datetime-button

I'm going to close this as not a bug in Ionic, but let me know if you have any questions.

**Closed by amandaejohnston** 2024-02-27 19:18 UTC
Labels: triage
