### ISSUE TITLE
bug: Modal backdrop click prevented by .modal-shadow element positioning

### ISSUE THREAD

**Issue by KirstenStake** [ionic-team/ionic-framework#24939] opened 2022-03-15 05:19 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

When settings a --height (or any of the height variables) to an ion-modal, that height gets applied to the class .modal-shadow as well but the positioning is not correct. This results in a section of the shadow preventing click events.

This seems to have only happened recently as was working fine for a long time.

It seems to have been mentioned here before https://github.com/ionic-team/ionic-framework/issues/21426 but was closed. Also, from the linked older bug ticket, how come it was advised that only full-page modals should be used? I thought the whole concept of the --height variables was for us to customise? (or is that comment no longer relevant)

<img width="1671" alt="Screen Shot 2022-03-15 at 4 18 13 pm" src="https://user-images.githubusercontent.com/70495867/158311821-e3e06c9e-9ac0-4725-bf53-90864a36023f.png">

### Expected Behavior

Setting a different height to the modal other than 100% should have no effect on the modal-shadow placement.

### Steps to Reproduce

- set --height variable to any % value lower than 100%
- inspect the .modal-shadow class, you can see that it has the same % applied but the positioning is higher than the modal

### Ionic Info

Ionic:

   Ionic CLI                     : 6.18.2 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.10
   @angular-devkit/build-angular : 13.2.5
   @angular-devkit/schematics    : 12.2.14
   @angular/cli                  : 13.2.5
   @ionic/angular-toolkit        : 5.0.0

Capacitor:

   Capacitor CLI      : 3.4.3
   @capacitor/android : 3.4.3
   @capacitor/core    : 3.4.3
   @capacitor/ios     : 3.4.3

Utility:

   cordova-res (update available: 0.15.4) : 0.15.3
   native-run                             : 1.5.0

System:

   NodeJS : v16.13.0 (/usr/local/bin/node)
   npm    : 8.1.0
   OS     : macOS Big Sur

**Comment by liamdebeasi** [comment] 2022-03-15 13:17
Thanks for the issue. Can you provide a GitHub repo I can use to reproduce the issue? I am not able to reproduce this behavior on my end.

**Comment by KirstenStake** [comment] 2022-03-15 22:57
Sure, I realised you also had to add this css to the modal to get it to show the bug:
This makes the modal align to the bottom of the screen.

```
  &::part(content) {
    margin-top: auto;
  }
```

@liamdebeasi  
Reproduction repo: 
https://github.com/KirstenStake/modal-ionic-bug/settings

**Comment by liamdebeasi** [comment] 2022-03-16 12:50
Thanks! Did you push your reproduction to the repo? The app appears to just be a blank starter application.

**Comment by KirstenStake** [comment] 2022-03-16 21:35
@liamdebeasi sorry about that, I pushed it properly now. hamimono's response fixes the issue though. still have pushed the repo properly in case you still want to see the "issue" but looks like the margin auto styling causes it to happen.

@hakimio thank you! that fixes it for me! appreciate it.

**Comment by liamdebeasi** [comment] 2022-03-17 16:27
Thanks! Since the solution provided in https://github.com/ionic-team/ionic-framework/issues/24939#issuecomment-1069181520 resolves the issue, am I good to close this?

**Closed** 2022-03-17 21:55 UTC
Labels: needs: reply
