### ISSUE TITLE
bug: swipe to go back does not work on Ionic React

### ISSUE THREAD

**Issue by julien-terral** [ionic-team/ionic-framework#20904] opened 2020-03-29 08:42 UTC
<h1>Bug Report</h1>
<strong>Ionic version : 5.0.1 (latest)</strong><br>
<strong>Variant used : React</strong><br>

<h2>Current behavior</h2>
On Ionic React, the transition of the swipe gesture to go back on the previous stacked screen is not working properly. When you route forward and then go back with the swipe gesture, I noticed that the swipe back gesture cause the animation to trigger twice.<br><br>

The back button works fine, the issue is just regarding the swipe to go back gesture.

I've only been able to reproduce this on a physical iOS device (iPhone 11, iOS 13) because it seems working well via the iOS simulator.<br>

<h3>Steps to reproduce</h3>
1. Open the app on your iOS device from <a href="http://beerodex-squid7331.firebaseapp.com" target="_blank">http://beerodex-squid7331.firebaseapp.com</a><br>
2. Click the "Goto page 2" button<br>
3. Use the swipe back gesture to go back to the previous page<br>

<h3>Video</h3>
This is a video of the occurrence :<br>
<a href="https://streamable.com/32sm7" target="_blank">https://streamable.com/32sm7</a>

<h3>Related code</h3>
This is a link to my GitHub project : <br>
<a href="https://github.com/Squid7331/react-ionic-swipegesture-issue
" target="_blank">https://github.com/Squid7331/react-ionic-swipegesture-issue</a>

<h3>Other info</h3>
Same issue as this topic on Ionic Framework forum :<br>
<a href="https://forum.ionicframework.com/t/swipe-back-gesture-on-ios-pwa-with-react-mixing-up/180024" target="_blank">https://forum.ionicframework.com/t/swipe-back-gesture-on-ios-pwa-with-react-mixing-up/180024</a>

<h3>Ionic info</h3>
<pre>
Ionic:

   Ionic CLI       : 6.3.0
   Ionic Framework : @ionic/react 5.0.7

Capacitor:

   Capacitor CLI   : 1.5.2
   @capacitor/core : 1.5.2

Utility:

   cordova-res : 0.11.0
   native-run  : 0.3.0

System:

   NodeJS : v12.16.0
   npm    : 6.13.4
</pre>

**Comment by lscardinali** [comment] 2020-03-29 13:39
This happened to me too as i posted on the forum in December
https://forum.ionicframework.com/t/swipe-back-gesture-on-ios-pwa-with-react-mixing-up/180024/2
And got no answer.

I've tried to disable the swipe back gesture by adding to App.tsx
`setupConfig({
    swipeBackEnabled: false,
  });`

And it does disable the Ionic's swipe back gesture, but the native one remains, which works, but when the swipe is completed and we're back on the first screen, the "pop" animation kicks in, resulting in a double animation again.
It can be seen here: https://streamable.com/ygjsy

This happens because _apparently_ we cannot disable the Safari's default swipe back gesture.
While there's a **history**, the swipe back will work.

I'll be looking into how the Angular counterpart works, as it works as it should and apparently still uses the **history**

**Comment by ccssmnn** [comment] 2020-05-18 13:05
I guess the problem is that the first animation we see is the one provided by iOS Safari when using this gesture. You can test this on any site. After Safari successfully returns to the previous site (Safari animation finishes) the animation triggered by `IonRouterOutlet` starts. Thus we see the animation twice, since they are pretty similar.

The quick fix is to disable animations in `IonRouterOutlet`. Since this would remove the animation on all devices you can set that boolean dependent on the platform where your app is running with the `isPlatform` method from `@ionic/react` documented [here](https://ionicframework.com/docs/react/platform).

**Comment by lucnat** [comment] 2020-06-05 11:11
Any update on this? @ccssmnn with your solution you have no animations at all if you press the "go back" button..which is suboptimal.

**Comment by avilao** [comment] 2020-06-18 23:51
I also have the same issue. Any new solutions?

**Comment by uncvrd** [comment] 2020-08-02 19:05
Also confirming this issue on a PWA as well. I've disabled `swipeBackEnabled` for non capacitor devices in hopes this would prevent a duplicate animation with no luck unfortunately.

**Comment by lucnat** [comment] 2020-08-29 16:04
As of now, disabling swipe back gesture as in https://ionicframework.com/docs/react/config works. Enabling it is still buggy, e.g. when used with a sidemenu. Also, it is not a smooth swipe back gesture, but snaps back once triggered.

**Comment by BerkeAras** [comment] 2021-03-02 14:38
At the moment, I am working on a fix for this issue (#22342). It is not very easy to fix, but I will give my best 👍

**Comment by Ripwords** [comment] 2021-09-15 18:38
just like to update that this is still happening on vue pwa too

**Comment by MaxInMoon** [comment] 2021-09-17 19:38
This is in my opinion a fundamental issue.

**Comment by Ripwords** [comment] 2021-09-28 06:50
is this currently happening only on safari PWA or is it occurring in the native iOS app as well?

**Comment by liamdebeasi** [comment] 2022-04-29 17:57
Thanks for the issue. There are a couple issues here:

1. Ionic React does not implement the swipe to go back gesture correctly. When you begin to swipe, the page transition kicks in and completes. It does not allow for a smooth swipe back experience. This issue is being tracked in https://github.com/ionic-team/ionic-framework/issues/22342.
2. When running an Ionic app in a mobile browser or as a PWA on iOS, users have to deal with both Ionic's swipe back gesture as well as iOS's built in swipe back gesture. This is being tracked in https://github.com/ionic-team/ionic-framework/issues/22299.

-----

To explain issue 2 a bit more:

When you set `swipeGesture={false}` on `IonRouterOutlet`, this only disables Ionic's swipe gesture. It does not disable the browser's swipe gesture. Additionally, when you route forward/back, Ionic runs a page transition.

So what is happening is when you swipe back, you first get the swipe back gesture from iOS. When the transition completes, Ionic runs its own page transition. Visually it appears as though there are duplicate transitions happening.

-----

Given that these issues have different requirements for resolving them, I am going to close this thread in favor of the two issues I linked to above. Please follow those threads for updates on this issue.

Thank you!

**Closed by liamdebeasi** 2022-04-29 17:57 UTC
Labels: package: react, type: bug
