### ISSUE TITLE
bug: ion-select with interface="popover" does not open popover

### ISSUE THREAD

**Issue by martinmitteregger** [ionic-team/ionic-framework#26643] opened 2023-01-19 14:30 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

After clicking onto an `ion-select` with `interface="popover"` the backdrop appears but no popover is shown.
The console shows the error or rather warning "_Found a 'popover' attribute with an invalid value._" 

![current_behavior](https://user-images.githubusercontent.com/15977182/213466996-cb65207f-2df1-4734-b877-377e63485c8b.png)

### Expected Behavior

After cclicking onto an `ion-select` with `interface="popover"` the backdrop AND the popover itself should be shown.

### Steps to Reproduce

Just run the stackblitz example from the [docs](https://ionicframework.com/docs/api/select#popover).
After opening the stackblitz example the docs show the same incorrect behavior!

![image](https://user-images.githubusercontent.com/15977182/213467819-b788a39b-250a-4844-b511-06d9bbe403ac.png)

### Ionic Info

I can't run `ionic info` in the stackblitz project but as I have the same error in my project here's my output

Ionic:
   Ionic CLI                     : 6.20.1
   Ionic Framework               : @ionic/angular 6.5.0
   @angular-devkit/build-angular : 15.1.1
   @angular-devkit/schematics    : 15.1.1
   @angular/cli                  : 15.1.1
   @ionic/angular-toolkit        : 7.0.0

Capacitor:
   Capacitor CLI      : 4.6.1
   @capacitor/android : 4.6.1
   @capacitor/core    : 4.6.1
   @capacitor/ios     : 4.6.1

Utility:
   cordova-res : 0.15.3
   native-run  : 1.7.1

System:
   NodeJS : v16.14.2
   npm    : 8.7.0
   OS     : Windows 10

### Additional Information

After removing `interface="popover"` it works as expected (but not as popover)

**Comment by liamdebeasi** [comment] 2023-01-19 14:55
Thanks for the report. What browser are you testing this on? I am testing this on Chrome 109 for macOS and the popover opens as expected.

**Comment by martinmitteregger** [comment] 2023-01-19 17:11
Edge 109.0.1518.55 & Chrome 109.0.5414.75 (both Windows 11)

**Comment by liamdebeasi** [comment] 2023-01-19 18:45
Thanks for the info. Does this reproduce in any other browser?

**Comment by software-OSG** [comment] 2023-01-23 14:02
Hello,

bug with Chrome Mac 109.0.5414.87

**Comment by liamdebeasi** [comment] 2023-01-23 14:03
@software-OSG Does this issue reproduce on any other browsers?

**Comment by liamdebeasi** [comment] 2023-01-23 14:28
Do you have any enabled browser plugins? (AdBlock, 1Password, etc)

**Comment by software-OSG** [comment] 2023-01-23 15:10
> Do you have any enabled browser plugins? (AdBlock, 1Password, etc). Also, are you using an Intel Mac or an Apple Silicon Mac (M1, M2 Pro, etc)

I have disabled all browser plugins in Chrome and I still have the bug.
I have a Intel Mac.

**Comment by liamdebeasi** [comment] 2023-01-23 16:04
Thanks! At this point, we believe this behavior to be caused by a new popover feature in Chrome: https://developer.chrome.com/docs/web-platform/popover-api/popover-property/ Ionic's popover component appears to be colliding with the browser's implementation.

However, the Ionic Team is not able to reproduce the issue. I am going to continue to investigate this and will reply here when I have more information.

**Comment by liamdebeasi** [comment] 2023-01-24 22:23
I believe this issue is related to Ionic passing a non-existent property during presentation: https://github.com/ionic-team/ionic-framework/blob/946807d67b972c41b52c23c8f00feca4c705b224/core/src/components/popover/popover.tsx#L453 This is likely legacy code that was never removed and is colliding with the `popover` property available in Chrome 109+

Could everyone try this dev build and let me know if it resolves the issue?

**Angular**
```
npm install @ionic/angular@6.5.1-dev.11674598433.1694c5ff
```

**React**
```
npm install @ionic/react@6.5.1-dev.11674598433.1694c5ff @ionic/react-router@6.5.1-dev.11674598433.1694c5ff
```

**Vue**
```
npm install @ionic/vue@6.5.1-dev.11674598433.1694c5ff @ionic/vue-router@6.5.1-dev.11674598433.1694c5ff
```

**Stencil/Vanilla JavaScript**
```
npm install @ionic/core@6.5.1-dev.11674598433.1694c5ff
```

**Comment by acoldfox** [comment] 2023-01-26 03:53
@liamdebeasi 
I still have the bug with @ionic/vue@6.5.1-dev.11674603407.1bf3d493
Intel Mac Chrome 109.0.5414.87

**Comment by liamdebeasi** [comment] 2023-01-26 13:27
> @liamdebeasi I still have the bug with @ionic/vue@6.5.1-dev.11674603407.1bf3d493 Intel Mac Chrome 109.0.5414.87

Are there any errors or warnings in the console?

**Comment by acoldfox** [comment] 2023-01-27 14:16
> > @liamdebeasi I still have the bug with @ionic/vue@6.5.1-dev.11674603407.1bf3d493 Intel Mac Chrome 109.0.5414.87
> 
> Are there any errors or warnings in the console?

@liamdebeasi Yes, the erros is:
index.esm.js?58b7:1845 Uncaught (in promise) TypeError: Invalid value used as weak map key
    at WeakMap.set (<anonymous>)
    at Object.attachViewToDom (index.esm.js?58b7:1845:1)
    at attachComponent (framework-delegate.js?e7e5:10:1)
    at Popover.hasController.present (popover.js?59f0:1246:1)
    at Select.disabled.open (ion-select.js?5f01:166:1)

**Comment by liamdebeasi** [comment] 2023-01-27 14:18
This is a different bug than what is described in https://github.com/ionic-team/ionic-framework/issues/26643#issue-1549277973. The original post notes a "Found a 'popover' attribute with an invalid value." warning not a WeakMap error.

Can you provide a GitHub repo I can use to reproduce the `WeakMap` error?

**Comment by acoldfox** [comment] 2023-01-27 14:51
@liamdebeasi This is the reproduce repo, I can reproduce the `WeakMap error`  on  chrome  with my intel mac and m2 mac
https://github.com/acoldfox/ionic-select-issue

**Comment by liamdebeasi** [comment] 2023-01-30 16:55
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/26672, and a fix will be available in an upcoming release of Ionic Framework.

The Vue issue noted in https://github.com/ionic-team/ionic-framework/issues/26643#issuecomment-1406565871 will be resolved in https://github.com/ionic-team/ionic-framework/pull/26694

**Closed** 2023-01-30 16:55 UTC
Labels: bug: external
