### ISSUE TITLE
bug: Angular, 2 Animation on a same element (not at the same time)

### ISSUE THREAD

**Issue by KrishenK0** [ionic-team/ionic-framework#25526] opened 2022-06-23 11:38 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

The thumbnail and little stuff (author, title, …) don't get back in their original position, when I trigger the footer drawer of my full-screen music player.

![image](https://user-images.githubusercontent.com/90158435/175288217-070ce035-13bb-4ceb-a42d-6ed666e1786d.png)

I make 2 animation that effect the image:
1. when I swipe-up the minified music player. (The thumbnail come small to big and centered)
2. when I swipe-up the footer. (The thumbnail come big to his original state)
vice-versa

There is a short video of my problem : https://www.youtube.com/watch?v=rBp7Cjm3KnY

### Expected Behavior

I expect my image just like the _YouTube music player_ to move 
* from small to big (centered) when I swipe-up the minified music player
* from big to small when I swipe-up the footer
* from small to big when I swipe-down (close) the footer
* from big to small when I minified the player

by using animation if it's possible.

### Steps to Reproduce

* Swipe-up the minified music player
* Swipe-up the footer
* Swipe-down (close) the footer
* Swipe-down (close) full-screen player

like the video https://www.youtube.com/watch?v=rBp7Cjm3KnY

### Code Reproduction URL

https://github.com/KrishenK0/playzik-app  or  https://dashboard.ionicframework.com/preview/95cc4a87/duixlv401e

### Ionic Info

```
[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package'

       Require stack:
       - C:\Users\fox25\AppData\Roaming\npm\node_modules\@ionic\cli\lib\project\index.js
       - C:\Users\fox25\AppData\Roaming\npm\node_modules\@ionic\cli\lib\index.js
       - C:\Users\fox25\AppData\Roaming\npm\node_modules\@ionic\cli\index.js
       - C:\Users\fox25\AppData\Roaming\npm\node_modules\@ionic\cli\bin\ionic
[WARN] Error loading @capacitor/android package.json: Error: Cannot find module '@capacitor/android/package'

       Require stack:
       - C:\Users\fox25\AppData\Roaming\npm\node_modules\@ionic\cli\lib\project\index.js
       - C:\Users\fox25\AppData\Roaming\npm\node_modules\@ionic\cli\lib\index.js
       - C:\Users\fox25\AppData\Roaming\npm\node_modules\@ionic\cli\index.js
       - C:\Users\fox25\AppData\Roaming\npm\node_modules\@ionic\cli\bin\ionic

Ionic:

   Ionic CLI                     : 6.20.1 (C:\Users\fox25\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.1.10
   @angular-devkit/build-angular : 14.0.2
   @angular-devkit/schematics    : 14.0.2
   @angular/cli                  : 14.0.2
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.6.0
   @capacitor/android : not installed
   @capacitor/core    : 3.6.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.6.0

System:

   NodeJS : v16.13.1 (C:\Program Files\nodejs\node.exe)
   npm    : 8.1.2
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment] 2022-06-23 13:32
Thanks for the issue. The animations appear to be working as intended here. You have two separate animations that animate the same element on the same property. When that happens, the most recently added animation takes priority. 

Here is an example outside of Ionic: https://codepen.io/liamdebeasi/pen/XWZLLKQ?editors=1010

Click the "Play Two" button. Notice that the square moves from `0px` to `100px` on the x-axis. Click the "Play One" button. Notice that the square does not move from `0px` to `50px` even though it should. This is because the "Play Two" animation was added more recently.

----

You have a few options for resolving this:

1. Have the second animation (the one that shows the sheet with the lorem ipsum) animate a cloned set of elements. This will allow you to have both animations without worrying about conflicts.
2. Destroy/re-create the second animation each time the gesture ends/starts. This may not be ideal performance-wise, but it would let you have one set of elements and not worry about animation conflicts.
3. Avoid the second animation altogether. Depending on what you are trying to do, you may find it easier to just avoid a conflicting animation in general.
4. You can experiment with composite operations on the raw Web Animation object: https://web.dev/web-animations/#smoother-animations-with-composite-modes. This may or may not give you the effect you want. Note that this is not supported everywhere yet: https://caniuse.com/?search=keyframe%20effect%20composite

**Closed** 2022-06-23 14:31 UTC
Labels: needs: reply
