### ISSUE TITLE
bug: Overflow not hidden in ion-textarea

### ISSUE THREAD

**Issue by Euxiniar** [ionic-team/ionic-framework#27083] opened 2023-04-01 19:27 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When defining an ion-textarea, with the css --border-radius property, the label inside protrudes from the corners. 

### Expected Behavior

The label should not protrudes from the corners of the ion-textarea.

### Steps to Reproduce

```html
<ion-textarea rows='1'
aria-label='My label'
style='--border-radius: 23pt;'>
</ion-textarea>
```

### Ionic Info

Ionic:

   Ionic CLI                     : 7.0.0 (C:\Users\Charles\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : not installed
   @angular-devkit/build-angular : 15.2.4
   @angular-devkit/schematics    : 12.2.18
   @angular/cli                  : 15.2.4
   @ionic/angular-toolkit        : 4.0.0

Capacitor:

   Capacitor CLI      : 4.7.1
   @capacitor/android : 4.6.1
   @capacitor/core    : 4.6.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v18.15.0 (C:\Program Files\nodejs\node.exe)
   npm    : 9.6.2
   OS     : Windows 10

### Additional Information

To correct this error, it is necessary to apply the css overflow:hidden property to the label:
```css
ion-textarea label {
  overflow: hidden;
}
```
This css property should probably be present by default, and not added in the global.scss

**Comment by liamdebeasi** [comment] 2023-04-03 14:09
Thanks for the report. Can you please clarify what the bug is? I am not able to reproduce the reported behavior on my end.

**Comment by Euxiniar** [comment] 2023-04-03 21:44
> Thanks for the report. Can you please clarify what the bug is? I am not able to reproduce the reported behavior on my end.

yeah sorry, I was not clear enough. Here is the whole css: 
```css
ion-content::part(background) {
  background: red;
}

ion-textarea {
  --border-radius: 23pt;
  --background: var(--ion-color-light);
  font-size: 16pt;
  --placeholder-color: var(--ion-color-primary);
}
```

and the html:
```html
<ion-content [fullscreen]="true">
  <ion-textarea rows='2'
                aria-label='My label'>
  </ion-textarea>
</ion-content>
```

The result is this
![localhost_8100_home(PlayStore) (1)](https://user-images.githubusercontent.com/25852639/229634325-3c61c847-a1bd-474b-b49e-9b7f9183ba3e.png)

**Comment by amandaejohnston** [comment] 2023-04-04 14:13
Can you try adding padding via the `--padding-start`, `--padding-end`, `--padding-top`, and `--padding-bottom` CSS properties on `ion-textarea` and see if that works for your use case? Even if overflow were hidden and the text didn't poke out from the corners, it would not display properly since it would be cut off.

If that doesn't work, could you post a minimal Github repo, Stackblitz app, etc. reproducing the behavior you're seeing? Copy-pasting your code, I get a different result from your screenshot.

**Comment by Euxiniar** [comment] 2023-04-04 20:41
> ```css
> ion-textarea label {
>   overflow: hidden;
> }
> ```

my solution 
_global:scss_ :
```css
ion-textarea label {
  overflow: hidden;
}
```

is not theoretical, I already tested it:
![image](https://user-images.githubusercontent.com/25852639/229912978-b6a82798-e2d6-4a2d-aa8d-280a42d5ffa3.png)

adding padding works of course, but it's just not the result I want to get by adding a border-radius:
![image](https://user-images.githubusercontent.com/25852639/229914256-387fbaa7-2500-4a0a-bc37-9872929b8b5a.png)

Here is the link to my repo to reproduce this bug:
[https://github.com/Euxiniar/ion-textarea](url)

**Comment by Snargol** [comment] 2023-04-05 07:20
Same problem here. A fix in a next version of ionic would be great.

**Comment by Euxiniar** [comment] 2023-04-05 14:28
> Just to be clear, does adding `overflow: hidden` in the CSS completely resolve the issue? Are there any other problems caused by overflow not being hidden by default, especially ones that can't be fixed with additional custom CSS?

Yes, it totally solves the issue. Or at least I haven't seen any other issues caused by setting --border-radius. It's just visually ugly.

**Comment by amandaejohnston** [comment] 2023-04-07 14:39
To make sure I'm following, is this the design you're trying to achieve? Or were you aiming for something else?
![cut off corners](https://user-images.githubusercontent.com/25852639/229912978-b6a82798-e2d6-4a2d-aa8d-280a42d5ffa3.png)

**Comment by Euxiniar** [comment] 2023-04-07 17:56
> To make sure I'm following, is this the design you're trying to achieve? Or were you aiming for something else?
> 
> ![cut off corners](https://user-images.githubusercontent.com/25852639/229912978-b6a82798-e2d6-4a2d-aa8d-280a42d5ffa3.png)

Yes it is

**Comment by amandaejohnston** [comment] 2023-04-07 17:59
Okay, thank you for the added detail. Since the issue is resolved with a bit of additional custom CSS, so I'm going to go ahead and close this out. Even if we did add `overflow: hidden` by default, the text is still cut off instead of hanging out of the corners, necessitating extra custom CSS anyway.

**Closed by amandaejohnston** 2023-04-07 17:59 UTC
Labels: triage

**Comment by Euxiniar** [comment] 2023-04-07 18:10
In what context would you want the text to hang out beyond the corners ?? Besides it has no coherence with the old text area, which worked like this
