### ISSUE TITLE
bug: Popover incorrectly positions in footer

### ISSUE THREAD

**Issue by matthew-valenti** [ionic-team/ionic-framework#26202] opened 2022-11-01 14:47 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

When an ion-popover containing an ion-list is added to an ion-toolbar in a ion-footer it shows as cut-off. The same behavior shows on both mobile and desktop browser views. The same behavior shows if the ion-toolbar is not within an ion-footer.

![image](https://user-images.githubusercontent.com/8585839/199264879-d8f075e8-c9f7-4fc9-928e-2f08cbd6ca9b.png)

### Expected Behavior

Popover to display all three ion-item elements on the screen in this example.

### Steps to Reproduce

1. Create a blank ionic project.

2. In src\app\home\home.page.html, paste the following code after the closing ion-content tag.

3. Do an ionic serve and click the "popover button".

```
<!-- Existing template code -->
</ion-content>

<!-- New template code -->
<ion-footer>
    <ion-toolbar>
        <ion-buttons slot="start">
            <ion-button id="button-popover">
                popover button
            </ion-button>
        </ion-buttons>
    </ion-toolbar>
</ion-footer>

<ion-popover trigger="button-popover" triggerAction="trigger">
    <ng-template>
        <ion-content>
            <ion-list>
                <ion-item detail>test</ion-item>
                <ion-item detail>test2</ion-item>
                <ion-item detail>test3</ion-item>
            </ion-list>
        </ion-content>
    </ng-template>
</ion-popover>
```

### Ionic Info

Ionic:
   Ionic CLI                     : 6.19.0 (C:\Users\matth\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.3.3
   @angular-devkit/build-angular : 14.2.7
   @angular-devkit/schematics    : 14.2.7
   @angular/cli                  : 14.2.7
   @ionic/angular-toolkit        : 6.1.0

Capacitor:
   Capacitor CLI      : 4.4.0
   @capacitor/android : not installed
   @capacitor/core    : 4.4.0
   @capacitor/ios     : not installed

Utility:
   cordova-res : not installed globally
   native-run  : 1.7.1

System:
   NodeJS : v16.13.2 (C:\Program Files\nodejs\node.exe)
   npm    : 8.1.2
   OS     : Windows 10

**Comment by MaxWeisen** [comment] 2022-11-04 18:13
I am experiencing the same thing with an `ion-popover` in a footer.

We also have an `ion-popover` in a header and that is working as expected.

My workaround for the `ion-popover` in the footer is to set the popover `--height` css property.

**Comment by sean-perkins** [comment] 2022-11-10 23:07
@matthew-valenti thank you for reporting this issue.

I am able to reproduce and have created an isolated reproduction: https://stackblitz.com/edit/angular-n4d4o2

We will track this as a bug.

**Comment by sean-perkins** [comment] 2022-11-10 23:09
On a second look, it looks like this is a duplicate of: https://github.com/ionic-team/ionic-framework/issues/24780

We will consolidate these issues with that parent task and track the fix accordingly.

Thanks!

**Closed by sean-perkins** 2022-11-10 23:09 UTC
Labels: package: core, type: bug
