### ISSUE TITLE
bug(datetime): month-year presentation doesn't check if day is in new month when changing value

### ISSUE THREAD

**Issue by Wuesteon** [ionic-team/ionic-framework#25030] opened 2022-03-31 13:10 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

when I select a date with `presentation='month-year'`, a date with the day 31 is always created

### Expected Behavior

Correct days should be displayed 

### Steps to Reproduce

```html

<ion-datetime formControlName="dateMin" presentation="month-year"></ion-datetime>
```

result:
![image](https://user-images.githubusercontent.com/23034719/161062389-3f5a9317-b6fe-469c-b50e-29abecacfb12.png)

### Ionic Info

Ionic:

   Ionic CLI : 6.17.1

Utility:

   cordova-res (update available: 0.15.4) : 0.15.2
   native-run (update available: 1.5.0)   : 1.4.1

System:

   NodeJS : v16.14.2
   npm    : 8.5.0
   OS     : macOS Monterey

### Additional Information

    "@ionic/angular": "6.0.8",

**Comment by DwieDima** [comment] 2022-04-05 07:44
I discovered the same issue.
The problem is, when `presentation` is set to `date-month`, it will always select the current day (lets say 05. of April 2022).
If you now switch months the current day will always be selected (05. of February ...).

This issue was created on 31. of March. If you now switch the month to February you'll get the date 31. of February 2022.

Here's a repoduction repo (you have to change your system date).

https://github.com/DwieDima/ion-datetime-bug

**Comment by amandaesmith3** [comment] 2022-04-13 14:15
Thanks, and apologies for the delayed response. I'm able to replicate this. If you initialize `date` to the 31st (`public date = "2022-03-31T15:00:00";`), you don't have to change your system date.

While using the `month-year` presentation means you don't care about the day, the issue is that Angular's `date` pipe (and probably other date formatting options) will interpret February 31st as March. 🤔 Example using `date | date:"LLLL"`:
![wrong month display](https://i.gyazo.com/2183098d22876ea61c317b17dd2199b6.png)
We should probably just force `month-year` to use the 1st for the day, or else add checks to ensure the date we're moving to is valid.

As a workaround, you can initialize the `datetime`'s value to the 1st of this month, or some other day that will be valid for all months.

**Comment by kyoz** [comment] 2022-07-07 08:20
For more information, this issue also happen with other presentation like `date` & `date-time`, when you switch between month-year selection wheels and date.

And seem ion-datetime only respect the init Form value, I'v tried to set the FormControl value before switching to month-year wheels but it's seem doesn't work, only click on days or set initial FormControl value work.

https://user-images.githubusercontent.com/29815830/177726566-cb566314-cc9c-49e0-9b02-aa6a7618be0e.mov

**Closed** 2022-09-26 13:33 UTC
Labels: package: core, type: bug
