### ISSUE TITLE
bug: ion-header is flickering

### ISSUE THREAD

**Issue by Chreggii** [ionic-team/ionic-framework#23082] opened 2021-03-22 19:05 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

`ion-header` is flickering when header contains an `ion-button` and header will be replaced with a new one

**Expected behavior:**

`ion-header` should not flicker

**Steps to reproduce:**

See here: https://stackblitz.com/edit/ionic-5-angular-10-start-template-qqqvxi?file=src%2Fapp%2Ftab1%2Ftab1.page.ts

**Related code:**

```
<ng-template #temp>
  <ion-header>
    <ion-toolbar>
      <ion-buttons>
        <ion-button>Back</ion-button>
      </ion-buttons>
      <ion-title>
        Loading
      </ion-title>
    </ion-toolbar>
  </ion-header>

</ng-template>

<ng-container *ngIf="pipe | async as value; else temp">
  <ion-header>
    <ion-toolbar>
      <ion-buttons>
        <ion-button>Back</ion-button>
      </ion-buttons>
      <ion-title>
        Value
      </ion-title>
    </ion-toolbar>
  </ion-header>

  <ion-content>
    value
  </ion-content>
</ng-container>
```

**Other information:**
When the `ion-button` will be replaced with a div, it works properly

**Comment by liamdebeasi** [comment] 2021-03-22 19:47
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/22541. (Same underlying issue)

**Closed by liamdebeasi** 2021-03-22 19:47 UTC
Labels: triage
