### ISSUE TITLE
bug: Username and password autofill on iOS does not update react state

### ISSUE THREAD

**Issue by milanharia** [ionic-team/ionic-framework#23413] opened 2021-06-04 13:22 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

When you have two ion-inputs to allow a user to login with username and password, on iOS at the top of the keyboard, it allows you to use keychain to select previously saved login details to autofill the inputs. When you tap on the username input and autofill both username and password, the onIonChange event triggers and the username state is updated as it should, however, despite the password text is filled into the password input, this does not trigger the onIonChange event and so the password state is never updated. This then means the user cannot login as the application thinks that they have not entered their password. You can see in the video I attached, since the state did not update, I was unable to press the login button (it is disabled if username or password are empty) and after editing the password I was able to press the login button, prompting the incorrect credentials text.
**Expected behavior:**

I would expect the username and password inputs to update with the autofilled credentials and then those credentials to perform as if a user inputted those details manually, thus triggering an event that allows the state to be updated. This means the user does not have to enter the password input and type inside it to make the state update.
**Steps to reproduce:**

An application which has a username and password input that allows users to autofill information using iOS keychain and using the useState hook from react to store the inputted information should reproduce this issue.
**Related code:**

```
const [username, setUsername] = useState("");
const [password, setPassword] = useState("");

<IonItem>
    <IonLabel>Username</IonLabel>
    <IonInput
          type='email'
          inputmode='email'
          value={username}
          onIonChange={(e) => setUsername(e.detail.value!)}
          clearInput
    ></IonInput>
</IonItem>
<IonItem>
          <IonLabel>Password</IonLabel>
    <IonInput
        value={password}
        type='password'
        onIonChange={(e) => setPassword(e.detail.value!)}
        clearInput
    ></IonInput>
</IonItem>
{showErrorMessage && (
    <IonText color='danger'>
         <p>The credentials you entered are invalid.</p>
    </IonText>
)}
<IonButton
    expand='full'
    onClick={loginHandler}
    disabled={!username || !password}
>
    Log in
</IonButton>
```

**Other information:**

https://user-images.githubusercontent.com/76167627/120807382-cb56b180-c53f-11eb-946e-88d4318ddd03.mov

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.13.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.6.6

Capacitor:

   Capacitor CLI   : 2.4.7
   @capacitor/core : 2.4.7

Utility:

   cordova-res : not installed
   native-run  : 1.3.0

System:

   NodeJS : v14.15.1 (/usr/local/bin/node)
   npm    : 6.14.8
   OS     : macOS Big Sur
```

**Comment by liamdebeasi** [comment] 2021-06-04 14:19
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/23335.

See https://github.com/ionic-team/ionic-framework/issues/23335#issuecomment-845270643 for explanation of an issue as well as a workaround. The workaround is written for Angular, but the content you can adapt for React is found in the `ngOnInit` method.

**Closed by liamdebeasi** 2021-06-04 14:19 UTC
Labels: triage
