### ISSUE TITLE
bug: ng command to generate pwa not working on ionic angular app

### ISSUE THREAD

**Issue by sfraguor** [ionic-team/ionic-framework#27144] opened 2023-04-07 21:10 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

I'm trying to transform my ionic/angular app to a pwa, but when i use ng add @angular/pwa is not working.
I created a new ionic app and the error is: **Bootstrap call not found** 
With my app the error is: 
**Schematic input does not validate against the Schema: {"projects":"app","project":"pwatest","target":"build"}
Errors:

  Data path "" must NOT have additional properties(projects).**

### Expected Behavior

I expect to create the needed pwa files

### Steps to Reproduce

1. ng add @angular/pwa

### Ionic Info

Ionic:

   Ionic CLI                     : 6.20.8 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : not installed
   @angular-devkit/build-angular : 15.2.5
   @angular-devkit/schematics    : 15.2.5
   @angular/cli                  : 15.2.5
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 4.7.3
   @capacitor/android : not installed
   @capacitor/core    : 4.7.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v18.15.0
   npm    : 9.5.0
   OS     : macOS Unknown

**Comment by liamdebeasi** [comment] 2023-04-07 22:09
Thanks for the report. I am going to close this as this is not a bug in Ionic. Ionic Angular starter apps now use standalone components, but It looks like the `@angular/pwa` package does not support standalone components yet. This is a known bug in the Angular CLI: https://github.com/angular/angular-cli/issues/23316

We also plan on offering NgModule and standalone options in the Ionic starters for developers who do not want to migrate to standalone components yet. I recommend following the link above for updates on the bug. Let me know if you have questions.

**Closed by liamdebeasi** 2023-04-07 22:09 UTC
Labels: triage

**Comment by sfraguor** [comment] 2023-04-07 22:22
Thanks @liamdebeasi i appreciate your information. I will wait to angular 16 then.
