### ISSUE TITLE
bug(modal): `canDismiss: false` should not enable swipe gesture

### ISSUE THREAD

**Issue by EinfachHans** [ionic-team/ionic-framework#28788] opened 2024-01-07 11:56 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

`canDismiss` is the new property for the modal dismiss behaviour, but i can't do everything with it what i could with `swipeToClose` before.

In my case, i have a card style modal. With `canDismiss: false`, users can still drag the modal a little bit down. I want to completely disable this for a modal.

### Expected Behavior

I need a way to disable the swipe to close gesture completly. I think `canDismiss: false` should do this. Also this should be reactive. I update the `canDismiss` from within my modal.

### Steps to Reproduce

Do you need one? Code [here](https://github.com/ionic-team/ionic-framework/blob/4ccc150edff4e3f33f453343aedb081d920b2f90/core/src/components/modal/modal.tsx#L550) is quite clear, as there is no check against canDismiss if the gesture should be added.

If you still need one, let me know. 

### Ionic Info

Ionic:

   Ionic CLI                     : 7.1.6 (/Users/hans/.nvm/versions/node/v20.9.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.6.2 (/Users/hans/IdeaProjects/sweepster/node_modules/@ionic/angular)
   @angular-devkit/build-angular : 17.0.7 (/Users/hans/IdeaProjects/sweepster/node_modules/@angular-devkit/build-angular)
   @angular-devkit/schematics    : 17.0.7 (/Users/hans/IdeaProjects/sweepster/node_modules/@angular-devkit/schematics)
   @angular/cli                  : 17.0.7 (/Users/hans/IdeaProjects/sweepster/node_modules/@angular/cli)
   @ionic/angular-toolkit        : 9.0.0 (/Users/hans/IdeaProjects/sweepster/node_modules/@ionic/angular-toolkit)

Capacitor:

   Capacitor CLI      : 5.6.0
   @capacitor/android : not installed
   @capacitor/core    : 5.6.0 (/Users/hans/IdeaProjects/sweepster/node_modules/@capacitor/core)
   @capacitor/ios     : not installed

Utility:

   cordova-res                          : not installed globally
   native-run (update available: 2.0.0) : 1.0.0

System:

   NodeJS : v20.9.0 (/Users/hanskrywalsky/.nvm/versions/node/v20.9.0/bin/node)
   npm    : 10.1.0
   OS     : macOS Unknown

**Comment by liamdebeasi** [comment] 2024-01-08 18:04
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework.

The swipe to close gesture is only enabled when using the card modal or the sheet modal. When `canDismiss: false` we still apply a bit of a rubber band effect to these modals to indicate that the modal is normally swipeable, but something in the application is preventing it from being dismissed (it's up to the developer to show the user what exactly this is).

This behavior aligns with the native card and sheet modals. For example, here is the Calendar app on iOS:

https://github.com/ionic-team/ionic-framework/assets/2721089/21bae4d9-2265-43cb-83c5-b3260bcfadde

----

The `swipeToClose` property was only intended to be used with the card modal and was intended to always be enabled when `presentingElement` was defined. Unfortunately, the way it was exposed created other behaviors that were not planned. For example, a swipe gesture could be added on a regular fullscreen modal.

**Closed by liamdebeasi** 2024-01-08 18:04 UTC
Labels: holiday triage

**Comment by EinfachHans** [comment] 2024-01-08 18:17
Hey @liamdebeasi - thanks for the answer.

I'm not fully happy with your answer. In your video we see the behavior with a `canDismiss` function right? There is a action sheet presented.

What is want to archive at the end of the day is a card style modal, but there should be no drag enabled. So there is no way to do this you don't see this as an useful option?

**Comment by EinfachHans** [comment] 2024-01-09 12:02
@liamdebeasi A little bit context:

I have a konva image editor inside of the modal. This is quite complex and the touch and drag events seem to conflict with the modal. Users drag the modal down when they just want to move a image inside of the editor.

A official way or workaround to disable the swipe to close completly would be needed here

**Comment by liamdebeasi** [comment] 2024-01-09 22:32
> I have a konva image editor inside of the modal. This is quite complex and the touch and drag events seem to conflict with the modal. Users drag the modal down when they just want to move a image inside of the editor.

Your application should ensure that touch events do not bubble up to the modal if the touch events are inside of the image editor. You can use `stopPropagation` for this purpose. We do something similar for the picker wheel: https://github.com/ionic-team/ionic-framework/blob/28752acebd2686964c3fa6bfa23f7cf58cdc25f7/core/src/components/picker-internal/picker-internal.tsx#L33-L43

When users swipe up/down on the picker wheel we call `stopPropagation` so that touch events do not bubble up and cause the user to accidentally dismiss the modal.
