### ISSUE TITLE
bug: iOS form Enter key not submitting form

### ISSUE THREAD

**Issue by graemeenglish** [ionic-team/ionic-framework#28153] opened 2023-09-11 15:16 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

On the iOS simulator a form is not submitted when clicking the Enter key on the simulator using Software keyboard or attached hardware keyboard.

Android and web work as expected.

Related to the fixes made in this issue https://github.com/ionic-team/ionic-framework/issues/19368

### Expected Behavior

Form should be submitted on iOS

### Steps to Reproduce

Run the attached repo
Look for console log 'fired' on pressing enter key when form field focused.

### Code Reproduction URL

https://github.com/graemeenglish/ionic-form-bug

### Ionic Info

Ionic:

   Ionic CLI                     : 6.18.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : not installed
   @angular-devkit/build-angular : 16.2.0
   @angular-devkit/schematics    : 16.2.0
   @angular/cli                  : 16.2.0
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.2.3
   @capacitor/android : 5.2.3
   @capacitor/core    : 5.2.3
   @capacitor/ios     : 5.2.3

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v16.17.0 (/usr/local/bin/node)
   npm    : 8.19.1
   OS     : macOS Monterey

### Additional Information

As suggested here
https://stackoverflow.com/a/11282107
Replacing the current 
`style="display:none" `
with
`style="visibility:hidden;position:absolute"`
makes it work on iOS

**Comment by liamdebeasi** [comment] 2023-09-11 21:15
Thanks for the report. Did you push your code changes? I only see a blank Tabs starter app.

**Comment by graemeenglish** [comment] 2023-09-11 21:30
Ouch sorry, should be there now

**Comment by liamdebeasi** [comment] 2023-09-15 14:06
Thanks for pushing the code. I'm not able to reproduce the reported behavior. Pressing the Enter/Return key when the form is valid causes the `onLogin` callback to be fired.

Pressing Enter/Return before the form is invalid does not submit the form, but that seems correct because your submit button is disabled.

https://github.com/ionic-team/ionic-framework/assets/2721089/4e99b6f0-8db9-4620-87cb-e0715d423d24

(Note: I changed the log to an `alert` to make it easy to see on the screen recording)

**Comment by graemeenglish** [comment] 2023-09-15 15:10
Thanks for taking a look.

Just rechecked and still see the problem

I'm using iPhone 14 Pro simulator with iOS 16.2. I've also changed mine to use alert.
I only see the alert on tapping the Sign In button

https://github.com/ionic-team/ionic-framework/assets/3304492/ac14dc75-dfb8-4502-9487-f60d39895cca

**Comment by liamdebeasi** [comment] 2023-09-15 18:28
I can reproduce the reported behavior on iOS 16.2, but I cannot reproduce it on iOS 16.4 and iOS 16.6:

https://github.com/ionic-team/ionic-framework/assets/2721089/20f96ecd-770f-4711-9781-6f88b94d3ad3
(16.6 was tested in https://github.com/ionic-team/ionic-framework/issues/28153#issuecomment-1721342077).

It looks like this was a WebKit bug that has since been fixed.

**Comment by graemeenglish** [comment] 2023-09-18 10:05
Ok, thanks for confirming.
I have a patch applied currently which resolves for me but I guess it will be at least a couple of ionic major releases before iOS 16 fall off the supported versions so might be worth changing in Ionic until such times as iOS 16 is no longer supported.

**Comment by liamdebeasi** [comment] 2023-09-18 12:44
We typically don't change the supported versions mid-release cycle since that's considered a breaking change. In this case this is a platform-level bug since I can also reproduce this outside of Ionic (using a regular `button` instead of an `ion-button` reproduces the same issue).

I am going to close this since the WebKit bug has been patched and a fix has been released, but let me know if you have any other questions.

**Closed by liamdebeasi** 2023-09-18 12:44 UTC
Labels: triage
