### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by saivishnutammineni** [ionic-team/ionic-framework#21911] opened 2020-08-12 05:10 UTC
# Bug Report
Overlays keyboard accessibility issues
**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
When any overlay component (popover, alert, full page loader etc) closes, the focus goes back to body element. A user with keyboard navigation has to navigate back to the previous place.

**Expected behavior:**
User should not have to navigate back from top of page again with keyboard. (ex: The focus should come back to the triggering element for modals / popovers / alerts)
Check the below link for expected behaviour
https://www.w3.org/TR/wai-aria-practices-1.1/#keyboard-interaction-7

**Steps to reproduce:**
Same as that for
https://github.com/ionic-team/ionic-framework/issues/21768#issue-658475047

**Ionic info:**
Ionic v  5.3.1

**Comment by liamdebeasi** [comment] 2020-08-12 14:24
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/21768#issue-658475047 (same underlying problem).

**Closed by liamdebeasi** 2020-08-12 14:24 UTC
Labels: triage
