### ISSUE TITLE
bug: vue, leaving and going back to a different tab causes new tab to not be shown

### ISSUE THREAD

**Issue by jakubkoje** [ionic-team/ionic-framework#23058] opened 2021-03-16 15:54 UTC
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**
When navigating from view outside tabs, router will render wrong tab content.

**Expected behavior:**
Ionic router should render the correct tab.

**Steps to reproduce:**

1. Clone this repo: https://github.com/HybridLab-Projects/ionic-vue-router-bug
2. Load both tabs content
3. Navigate from tab 1 to subpage and second subpage views
4. Click on button to redirect to tab 2 - URL will be tab 2 but rendered will be tab 1

Video of the issue
https://imgur.com/8qPlJPe 

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.13.1 (/home/jakub/.nvm/versions/node/v14.16.0/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 5.6.0

Capacitor:

   Capacitor CLI   : 2.4.7
   @capacitor/core : 2.4.7

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v14.16.0 (/home/jakub/.nvm/versions/node/v14.16.0/bin/node)
   npm    : 6.14.11
   OS     : Linux 4.19
```

**Comment by liamdebeasi** [comment] 2021-03-16 17:23
Thanks for the issue. There are a couple of issues here:

1. When a tabs outlet leaves, we do not hide the active tab.
2. When a tabs outlet is navigated back to but on a different tab, we do not show the new tab correctly.

Ionic React does not have this issue because it does both 1 and 2 above. I would prefer not to follow exactly what Ionic React does for 1 because when the outlet transitions away, the tab is hidden before the transition starts. Doing 1 will require some more thought. Doing 2 should be straightforward.

The functionality described in this issue used to work but stopped working as of 5.5.3 probably due to either https://github.com/ionic-team/ionic-framework/commit/2a3ce9a74e85111a2f1f470b9d8bfe2cda793ca5 or https://github.com/ionic-team/ionic-framework/commit/e3a05bfeb55d8eaa38aa08a37859aa4df6ffa2d4. That being said, the way it determined the entering and leaving view was incorrect, so it's a coincidence that this worked in the first place.

**Comment by liamdebeasi** [comment] 2021-04-15 18:38
Investigated further and Issue 1 is required to get lifecycle hooks firing on inner tab pages, so we may have to compromise on the tab being hidden before the transition starts. The benefits of having the lifecycle hooks outweigh the tab being hidden in my opinion.

**Comment by weilantian** [comment] 2021-04-22 16:03
Seems to have the same issue here. The project I have been working on uses @ionic/vue

This navigating bug would happen if I navigate my app using the sweep gesture.

https://user-images.githubusercontent.com/13176782/115746304-d0640500-a3c6-11eb-8cb9-cdcac98b7bd3.MP4

**Comment by liamdebeasi** [comment] 2021-04-22 16:32
@weilantian Could you reproduce this issue in an Ionic starter app and provide a link to the repo?

**Comment by weilantian** [comment] 2021-04-23 05:14
@liamdebeasi Here you go, I added some further explanation in the README.md.
Appreciate Ionic team's hard work.

https://github.com/weilantian/ionic-vue-navigtaing-issue-reproduce

**Comment by liamdebeasi** [comment] 2021-04-23 13:46
Thanks! I think the bug that is happening in your app is actually https://github.com/ionic-team/ionic-framework/issues/22895. We fixed a similar issue in Ionic Angular and I started work on a fix for Ionic Vue.

**Comment by capc0** [comment] 2021-04-29 06:53
@liamdebeasi can you maybe create a dev build of my PR https://github.com/ionic-team/ionic-framework/pull/23128 ? I am curious if that also fixes this issue.

**Comment by SorioliComputec** [comment] 2022-02-04 08:43
I'm still experiencing this issue with ionic version 6.18.1 and @ionic/vue: ^6.0.0. 
There's any fix or workaround for this issue? Thanks

**Comment by liamdebeasi** [comment] 2022-04-29 17:40
Thanks for the issue. I discussed this issue with the team, and we realized that this is a use case that Ionic does not support.

The primary issue here is that the app in https://github.com/ionic-team/ionic-framework/issues/23058#issue-832947377 is programmatically switching between tabs. In a mobile app, each tab is treated as its own stack, and items in one stack never interact with items in another stack. This means that there should never be a link in Tab 1 that brings users to Tab 2. Another way of thinking about this is that the only way an app should switch between tabs is if a user presses a tab button (or uses the hardware back button).

In the case of the sample app, the app is going from Tab 1 to a non-tabs page and then to Tab 2. Even though there is a non-tabs page in the middle, the same rules apply for mobile tabs.

I understand that this may be unexpected as Ionic tabs behave very differently than tabs you may have seen in other web based UI libraries. The reason for this is that Ionic tries to match the behavior of native mobile tabs as closely as possible.

------

To help developers better understand these differences and to figure out how to account for these differences in their apps, we have updated our documentation with better explanations and demos: https://ionicframework.com/docs/vue/navigation#how-tabs-in-ionic-work

We understand tabs are a complex component and the behavior of mobile tabs may be a bit unexpected, so we are looking to expand on these docs in the future.

I am going to close this issue. Thank you!

**Closed by liamdebeasi** 2022-04-29 17:40 UTC
Labels: package: vue, type: bug
