### ISSUE TITLE
bug: IonTextarea.setFocus() and autocapitalize="sentences" on iOS/Safari

### ISSUE THREAD

**Issue by archevis** [ionic-team/ionic-framework#23217] opened 2021-04-20 20:28 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
After clearing an ion-textarea set to autocapitalize="sentences" at the click of the button, and then calling setFocus() on the ion-textarea to keep focus there, the keyboard on iOS doesn't revert to uppercase until after two clicks on backspace.

**Expected behavior:**
As the contents of the ion-textarea is set to an empty string, the keyboard should revert immediately to uppercase since it is obviously at the beginning of a sentence.

**Steps to reproduce:**

1. Create a blank Ionic Angular app.
2. Replace contents of `src/app/home/home.page.ts` with the following:

```
import { Component, ViewChild } from '@angular/core';
import { IonTextarea } from '@ionic/angular';

@Component({
  selector: 'app-home',
  template: `
    <ion-content [fullscreen]="true">

      <ion-textarea [value]="input" autocapitalize="sentences" (ionInput)="onInput($event)">
      </ion-textarea>

      <ion-button (click)="onClear($event)">
        Clear
      </ion-button>

    </ion-content>
  `
})
export class HomePage {

  input = '';

  @ViewChild(IonTextarea)
  private ionTextArea: IonTextarea;

  onInput(event: any) {
    this.input = event.target.value;
  }

  async onClear(event: any) {
    this.input = '';
    await this.ionTextArea.setFocus();
  }
}
```
3. Start app with `ionic serve --external` and open the page with Safari on an iPhone.
4. Click the textarea, type some text, click Clear and notice how the keyboard stays lowercase.
5. Click backspace on keyboard twice and notice how the keyboard suddenly reverts to uppercase.

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.13.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.6.4
   @angular-devkit/build-angular : 0.1102.9
   @angular-devkit/schematics    : 11.2.9
   @angular/cli                  : 11.2.9
   @ionic/angular-toolkit        : 3.1.1

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.18.2 (/usr/bin/node)
   npm    : 7.9.0
   OS     : Linux 5.11
```

**Comment by liamdebeasi** [comment] 2021-04-20 21:30
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/22744.

To summarize, this behavior is a bug in WebKit, the engine that powers Safari and WKWebView. I am able to reproduce the same behavior using a regular `textarea` outside of Ionic Framework.

I opened a similar issue with the WebKit team back in January: https://bugs.webkit.org/show_bug.cgi?id=220430

**Closed by liamdebeasi** 2021-04-20 21:30 UTC
Labels: triage
