### ISSUE TITLE
bug: ion-icon triggers angular change detection

### ISSUE THREAD

**Issue by heinerlamprecht** [ionic-team/ionic-framework#19095] opened 2019-08-14 12:38 UTC
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**

I have a custom table with several rows.  If the table rows contain an ion-icon, the Angular change detection is triggered for each icon in that table.

**Expected behavior:**

The sheer existence of an ion-icon should not trigger the Angular change detection.

**Ionic info:**

```

Ionic:

   Ionic CLI                     : 5.2.4
   Ionic Framework               : @ionic/angular 4.7.4
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : not installed
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.15.0 (/usr/local/bin/node)
   npm    : 6.10.2
   OS     : macOS Mojave
   Xcode  : Xcode 10.3 Build version 10G8

```

**Comment by amandaesmith3** [comment] 2022-02-02 21:34
Thanks for the issue, I wanted to circle back around to this. I know it's been a while, but could you create a repo that reproduces the issue -- ideally on the latest version of Ionic 6, assuming it's still occurring there -- and link to it here?

**Comment by amandaesmith3** [comment] 2022-02-15 21:36
Since this thread is quite old, no reproduction was provided in the original post, and there hasn't been any recent activity, I'm just going to go ahead and close this out. If this is still occurring in the latest version of Ionic, please create a new issue, and ensure the template is fully filled out. Thank you!

**Closed by amandaesmith3** 2022-02-15 21:36 UTC
Labels: ionitron: needs reproduction
