### ISSUE TITLE
bug: "ion-no-padding" does not work, until "!important" (ion-list)

### ISSUE THREAD

**Issue by infacto** [ionic-team/ionic-framework#22266] opened 2020-10-07 07:38 UTC
# Bug Report

**Ionic version:**
**5.3.2**

**Current behavior:**

Adding the class name `ion-no-padding` has not effect. It's overwritten by `.list-md` (padding-top, padding-bottom).

**Expected behavior:**
`ion-no-padding` should work on `ion-list`. Remove the padding.

**Steps to reproduce:**
Use the [ion-list](https://ionicframework.com/docs/api/list) with [ion-no-padding](https://ionicframework.com/docs/layout/css-utilities). See that the padding is not removed.

**Related code:**

```html
<ion-content>
  <ion-list class="ion-no-padding">
    <ion-item-group>
      <ion-item-divider sticky><ion-label>Demo</ion-label></ion-item-divider>
      <ion-item>
        <ion-icon name="bug"slot="start"></ion-icon>
        <ion-label>Demo</ion-label>
      </ion-item>
    </ion-item-group>
  </ion-list>
</ion-content>
```

Chrome inspect:
![image](https://user-images.githubusercontent.com/60390085/95300356-52ec0380-087f-11eb-9bbe-e237d2142eca.png)

You can see that the `.md-list` is dominant. `.ion-no-padding` should have `!important`.

![image](https://user-images.githubusercontent.com/60390085/95301689-394bbb80-0881-11eb-8112-3ea7f2d25a51.png)

Maybe it has to do with the order of css load. I cannot reproduce in Stackblitz. But I have nothing special in my workspace. I going insane, what's wrong? Any idea? Should we use `!important`? ... I have no other custom styles on it. I have no idea. It's weird. Any guess may help. **↓ Demo project below. ↓**

![image](https://user-images.githubusercontent.com/60390085/95303762-e6bfce80-0883-11eb-9f84-e8c233f54e06.png)

**Ionic info:**
Ionic Angular (without Ionic CLI)

**Demo Project**

(I cannot reproduce it in Stackblitz) So please download this zip. It's a minimalist project (Angular Multi-App).
**[Download issue-demo.zip](https://github.com/ionic-team/ionic-framework/files/5339318/issue-demo.zip)**
Use `ng serve --project=demo-app` to run this app.

**Comment by liamdebeasi** [comment] 2020-10-07 13:18
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/17425 (same underlying issue)

**Closed by liamdebeasi** 2020-10-07 13:18 UTC
Labels: triage

**Comment by infacto** [comment] 2020-10-08 05:23
It's not about user styles. It's the build-in styles from the Ionic framework. The weird thing is that it's generally work.

The demo from my initial post does not work. But this works: [issue-demo-2.zip](https://github.com/ionic-team/ionic-framework/files/5345465/issue-demo-2.zip)

I have no idea what the problem is. ... Any guess about the reason?

**Comment by liamdebeasi** [comment] 2020-10-08 13:52
Hmm actually I took a closer look and tried to simplify your app. In both I have the following in `app.component.html`:

```html
<ion-app>
  <ion-content>
    <ion-list class="ion-no-padding">
      Hello
    </ion-list>
  </ion-content>
</ion-app>
```

But in `issue-demo` `ion-no-padding` does not work, but in `issue-demo-2` it does work. Going to look into this a bit more.

**Comment by liamdebeasi** [comment] 2020-10-08 14:04
In `issue-demo`, the `style` element containing the `.ion-no-padding` styles is added to the DOM after the `style` element containing `ion-list`/`.list-md`, but in `issue-demo-2` it's the other way around.

It looks like this is the reason for the discrepancy. Here is an example for better clarification:

I have two CodePens, each one with a square. In the `head` I apply two separate style elements. One makes the square blue and one makes the square green.

The square is blue here because the "blue" style is applied after the "green" style: https://codepen.io/liamdebeasi/pen/gOMbObo
The square is green here because the "green" style is applied after the "blue" style: https://codepen.io/liamdebeasi/pen/jOrEOEX

So the issue here is still a specificity issue similar to https://github.com/ionic-team/ionic-framework/issues/17425, but it doesn't seem related to anything Ionic Framework is doing. I need to look into why this is happening to get a better sense of the source.

**Comment by liamdebeasi** [comment] 2020-10-08 14:30
I updated each app to the latest version of Angular and Ionic Framework. My best guess right now is that maybe something with your monorepo setup is causing some styles to be loaded out of order.

Does this issue happen in a blank Ionic Framework starter application?

**Comment by infacto** [comment] 2020-10-09 06:11
Thanks you very much for investigation. ❤️ Yes, the second issue-demo is created from a blank Ionic project. The first one is from an Angular multi-app repository which contains a bunch of Ionic apps with single dependencies (inlc. Cordova). I don't use the Ionic CLI, because it cannot handle this mono-repo with shared Cordova setup. But anyway... 
Interesting... 🤔 I understand that the the style order is important to avoid things like `!important`. This is the topic of the referred issue. ... But I cannot understand what the problem is in my workspace. It's an official Angular multi-app workspace with Ionic. I build both projects with `ng build`. So the Ionic CLI does not matter. ... just think aloud ... *sigh* I continue debugging. I'll take a look at the files that were created by `ng build` and comparing the setup files, again. Let's hope I don't lose my mind. ^^

**Comment by infacto** [comment] 2020-10-09 08:57
Ok, I compared the rendered html in Chromium dev-tools. The style-tags order is different.
The following is a table with the order of all style-tags and a short code snippet inside. The style-tags itself have no id. So, only the code snippet can identify it.

**Style-Tags**
| Problem Demo | Working Demo |
| --- | --- |
| (data-styles) `ion-select-popover` ... | (data-styles) `ion-select-popover` ... |
| `:root { --ion-color-primary` ... | `html.plt-mobile ion-app` ... |
| `// App Global CSS` ... `html.ios` ... | `ion-header` ... |
| `html.plt-mobile ion-app` ... | `ion-list` ... |
| `ion-header` ... | `ion-item-group` ... |
| `.sc-ion-buttons-md-h` ... | `.sc-ion-buttons-md-h` ... |
| `ion-list` ... | `:root { --ion-color-primary` ... |
| `ion-item-group` ... | `// App Global CSS` ... `html.ios` ... |

How to ensure the correct order?

**Comment by liamdebeasi** [comment] 2020-10-09 13:35
Yeah I am a little confused on this one as well. For your mono-repo setup, did you need to modify `angular.json` at all? I know that file tells the Angular CLI where to load certain Ionic Framework styles from, so maybe something got changed there?

**Comment by infacto** [comment] 2020-10-09 14:55
I compared the angular.json files. I cannot see any related difference. They are equal. More or less. Just the e2e and unit test stuff is missing and the path of course. I also removed the includes from tsconfig and tested other files with the same version. I synced the files. Maybe I'm missing something? It's really disapointing ...

**Comment by infacto** [comment] 2020-10-14 06:53
Long story short: It's better with the upcoming Angular 11. Especially for the serve-mode. For the prod build you can set the `extractCss` flag in `angular.json`. It's not supported for serve. And for dev you have to pass it to the commend as argument like `ng build --extractCss=true`. This is maybe not the best solution. Until the order of styles is not 100% ensured yet. That's ridiculous. But anyway... I hope this "solution" (workaround) will work for long time. I'm not entirely satisfied with that. ...

**Comment by liamdebeasi** [comment] 2020-10-14 14:19
I am going to check with the team to see if anyone has run into something like this before with monorepos.

**Comment by mhartington** [comment] 2020-10-14 14:24
Can you put together a sample mono repo to inspect? Not a fan of downloading random zip files from github issues (no offense).

Not asking for a direct copy of your app, but if you can replicate it in a new project base, that can help eliminate other issues/settings.

**Comment by infacto** [comment] 2020-10-15 06:02
I would not completely rule out that the problem only occurs with monorepos. There are some other threads about the style order with Webpack on web. And I think this is since Angular Ivy (and its dependencies). But not sure... It's a nasty bug...

I've uploaded the problem demo zip (from this issue) to a [repository](https://github.com/infacto/multi-app-style-order-issue).
