### ISSUE TITLE
bug: Ionic 5 ion-range knob position when dir="rtl"

### ISSUE THREAD

**Issue by JayJayBinks** [ionic-team/ionic-framework#22589] opened 2020-11-27 08:39 UTC
**Ionic version:**
[x ] **5.x**

**I'm submitting a ...** 
[x ] bug report

**Current behavior:**
Given a ion-range
When setting the attribute dir="rtl"
Then the knob-handle sticks to the right and does not move when sliding

**Expected behavior:**
The knob-handle should move along when sliding

**Steps to reproduce:**
Given a ion-range
When setting the attribute dir="rtl"

**Related code:**
https://ionic-angular-v5-range-rtl.stackblitz.io

**Other information:**
The culprit seems to be:
`[dir=rtl] .range-knob-handle, :host-context([dir=rtl]) .range-knob-handle {
  left: unset;
  right: unset;
  right: 0;
}`

The value right never gets changed, so the knob sticks to the right.

**Ionic info:** 
@ionic/angular 5.0.5

**Comment by liamdebeasi** [comment] 2020-11-30 15:01
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/20201.

**Closed by liamdebeasi** 2020-11-30 15:01 UTC
Labels: triage
