### ISSUE TITLE
bug: @ionic/vue " ion-textarea" component do not show change value when set "autoGrow"

### ISSUE THREAD

**Issue by AlwaysLoveme** [ionic-team/ionic-framework#22612] opened 2020-12-02 08:00 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

I set the property "autoGrow" is true on "ion-textarea", when i changed the value (v-model), the textarea height is 0, and the current value can not show!
**Expected behavior:**

work well when set "autoGrow" is true;
**Steps to reproduce:**

**Related code:**
```
<template>
    <ion-textarea type="text" placeholder="请选择店铺地址" auto-grow :rows="2" v-model="state.address"></ion-textarea>
</template>
<script lang="ts">
import Emitter from 'tiny-emitter/instance';
import {defineComponent, onMounted, onUnmounted, nextTick} from 'vue';
export default defineComponent({
setup() {
       const state = reactive({
           address: "Hello world"
       });
        Emitter.on('mapSelect', (result: any) => {
          console.log(result.name);
          // this can not show in page, and the textarea height is 0
          state.address = result.name;
      })
      return { state }
}
})
</script>
```
![image](https://user-images.githubusercontent.com/29945352/100844902-69958c00-34b7-11eb-84b5-29dca23b7d98.png)

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.12.2 (/Users/zhuxian/.nvm/versions/node/v12.19.0/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 5.5.1

Capacitor:

   Capacitor CLI   : 2.4.2
   @capacitor/core : 2.4.2

Utility:

   cordova-res (update available: 0.15.2) : 0.15.1
   native-run                             : not installed

System:

   NodeJS : v12.19.0 (/Users/zhuxian/.nvm/versions/node/v12.19.0/bin/node)
   npm    : 6.14.9
   OS     : macOS Big Sur

```

**Comment by EinfachHans** [comment] 2020-12-02 13:51
Think it's a duplicate of #21242 - See my Comments there for why this happens and a workaround

**Comment by liamdebeasi** [comment] 2020-12-02 14:19
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/21242. (Thanks @EinfachHans!)

**Closed by liamdebeasi** 2020-12-02 14:19 UTC
Labels: triage
