### ISSUE TITLE
bug: Vue lifecycle hooks not triggered if data changes in ionic child components

### ISSUE THREAD

**Issue by khalo-sa** [ionic-team/ionic-framework#23802] opened 2021-08-23 19:22 UTC
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

If child components of an ionic component, e.g. "ion-card",  change data that lead to an update of the virtual dom, any kind of lifecycle hook should be triggered. But that doesn't happen (pleas echeck codesandbox).

### Expected Behavior

I expect a lifecycle hook to be triggered as soon as the data changes, which leads to a virtual dom update.

### Steps to Reproduce

https://codesandbox.io/s/ionic-vue3-lifecycle-hooks-70290?file=/src/components/HelloWorld.vue

Please check "HelloWorld.vue". If "ion-card" is replaced with a plain "div" element, the "onUpdated" hook fires upon button click. If ion-card is used, no hook is fired at all, even though the virtual dom has changed.

### Code Reproduction URL

https://codesandbox.io/s/ionic-vue3-lifecycle-hooks-70290?file=/src/components/HelloWorld.vue

### Ionic Info

The version is 5.6.14, all installed dependencies can be checked in the codesandbox.

**Comment by liamdebeasi** [comment] 2021-08-23 20:25
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. In the example you provided, the `ion-card` Vue component is being re-rendered, not your `HelloWorld` component. This is because your content is slotted inside of `ion-card`.

This is true of any Vue 3 component, not just Ionic Vue components. 

Here is Vue 3 SFC Playground example: https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiwgb25VcGRhdGVkLCBkZWZpbmVDb21wb25lbnQsIGggfSBmcm9tICd2dWUnO1xuICBcbmNvbnN0IGRlZmluZUNvbnRhaW5lciA9IChuYW1lKSA9PiB7XG4gIGNvbnN0IENvbnRhaW5lciA9IGRlZmluZUNvbXBvbmVudCh7XG4gICAgc2V0dXAoKSB7XG4gICAgICBvblVwZGF0ZWQoKCkgPT4ge1xuICAgICAgICBjb25zb2xlLmxvZygnV3JhcHBlciBjbXAgdXBkYXRlZCEnKVxuICAgICAgfSlcbiAgICB9LFxuICAgIHJlbmRlcigpIHtcbiAgICAgIHJldHVybiBoKCdkaXYnLCB7fSwgdGhpcy4kc2xvdHMuZGVmYXVsdCAmJiB0aGlzLiRzbG90cy5kZWZhdWx0KCkpO1xuICAgIH1cbiAgfSlcbiAgXG4gIENvbnRhaW5lci5kaXNwbGF5TmFtZSA9IG5hbWU7XG4gIFxuICByZXR1cm4gQ29udGFpbmVyO1xufVxuXG5jb25zdCBkYXRhID0gcmVmKFtdKTtcbmNvbnN0IGFkZE1zZyA9ICgpID0+IGRhdGEudmFsdWUucHVzaChcIm5ldyBNZXNzYWdlXCIpO1xuICBcbm9uVXBkYXRlZCgoKSA9PiB7XG4gIGNvbnNvbGUubG9nKCdBcHAgdXBkYXRlZCEnKTtcbn0pO1xuIFxuY29uc3QgV3JhcHBlckNtcCA9IGRlZmluZUNvbnRhaW5lcignd3JhcHBlci1jbXAnKTtcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDx3cmFwcGVyLWNtcD5cbiAgXHQ8YnV0dG9uIEBjbGljaz1cImFkZE1zZ1wiPmNsaWNrPC9idXR0b24+XG4gIFx0PGgxIHYtZm9yPVwiKG1zZywgaSkgaW4gZGF0YVwiIDprZXk9XCJpXCI+e3sgbXNnIH19PC9oMT5cbiAgPC93cmFwcGVyLWNtcD5cbjwvdGVtcGxhdGU+In0=

If you click the button you should see `Wrapper cmp updated!` in the console because the `wrapper-cmp` component is what is getting updated, not the `App` component. If you were to remove the `<wrapper-cmp>` from your template, you should see `App updated!` because the `App` component is updating.

**Closed by liamdebeasi** 2021-08-23 20:25 UTC
Labels: triage
