### ISSUE TITLE
bug: ion-datetime modal sometimes shows whitescreen

### ISSUE THREAD

**Issue by DominikRoth** [ionic-team/ionic-framework#24412] opened 2021-12-15 13:33 UTC
### Prerequisites

- [x] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [x] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [x] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

I have the new ion-datetime component (inside an ion-modal) in a form.

```
<form #form>
  <ion-modal class="datetime-modal" trigger="open-datetime">
          <ng-template>
            <ion-content>
              <ion-datetime
                [value]="variable"
                #dateTime
                (ionChange)="form.value.date = dateTime.value"
              ></ion-datetime>
            </ion-content>
          </ng-template>
   </ion-modal>
</form>
```

When I open the ion-datetime modal, sometimes it just opens with a white screen:
<img width="324" alt="Bildschirmfoto 2021-12-15 um 14 12 09" src="https://user-images.githubusercontent.com/86354362/146195280-33aea306-5475-46f6-be81-50599e84cff8.png">

### Expected Behavior

I expect it to display the dates
<img width="323" alt="Bildschirmfoto 2021-12-15 um 14 33 03" src="https://user-images.githubusercontent.com/86354362/146195820-462ffdd7-4ab5-4860-8682-6ee18fe6d928.png">

### Steps to Reproduce

I can't see a pattern when this always happen, but most of the time it happens when I reset my form and open the modal again.

### Ionic Info

Ionic:

   Ionic CLI                     : 6.16.3 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.0
   @angular-devkit/build-angular : 12.1.4
   @angular-devkit/schematics    : 12.1.4
   @angular/cli                  : 12.1.4
   @ionic/angular-toolkit        : 4.0.0

Capacitor:

   Capacitor CLI      : 3.1.2
   @capacitor/android : 3.2.4
   @capacitor/core    : 3.2.4
   @capacitor/ios     : 3.2.4

Utility:

   cordova-res                          : not installed globally
   native-run (update available: 1.5.0) : 1.4.0

System:

   NodeJS : v14.15.3 (/usr/local/bin/node)
   npm    : 6.14.9
   OS     : macOS Catalina

### Additional Information

I think this issue shows the same problem, but the author thinks it comes from darkmode: (https://github.com/ionic-team/ionic-framework/issues/24410)

**Comment by liamdebeasi** [comment] 2021-12-15 14:06
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/24112. This was fixed via https://github.com/ionic-team/ionic-framework/pull/24385 and will be available in an upcoming release of Ionic.

**Closed by liamdebeasi** 2021-12-15 14:06 UTC
Labels: triage
