### ISSUE TITLE
bug: Slower devices may trigger multiple click events causing duplicate modals, alerts, popovers, etc.

### ISSUE THREAD

**Issue by pixelone** [ionic-team/ionic-framework#23327] opened 2021-05-19 05:40 UTC
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**

Slower devices (Most Repeatable on older android devices and the android studio eliminator) can trigger multiple click events causing duplicate modals, alerts, etc.

**Expected behavior:**

I think there should be a throttle to prevent duplicate click events? Right now having to add a flag to prevent duplicate fire events every time on modal opened/closed is not ideal...  Slower devices sometimes hang which leads to duplicate button events being executed.

**Steps to reproduce:**

1. Start a New Ionic tabs project. 
2. Place a method to fire a modal in the side menu (app.component.ts) and the button trigger in (app.component.html)
3. Build android and use a tablet emulator (easier to test when the side menu is expanded)
3. Repeatably click the open modal button and you can get duplicate Modals stacked up. 

To make this easier to reproduce,  I pull in some items from a rest API in order to get some load on the modal. 

**Other information:**

I am not sure this is expected behavior, but it creates a problematic experience with any type of modal interaction. 

Modals may be fired twice, Alerts may also be fired twice, this usage was found by testing on an older android device and can be reproduced in the emulator.

Any solution or suggestion would be appreicated. 

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.15.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.6.7
   @angular-devkit/build-angular : 0.1102.13
   @angular-devkit/schematics    : 11.2.13
   @angular/cli                  : 11.2.13
   @ionic/angular-toolkit        : 3.1.1

Capacitor:

   Capacitor CLI   : 2.4.7
   @capacitor/core : 2.4.7

Utility:

   cordova-res : 0.15.3
   native-run  : not installed

System:

   NodeJS : v15.14.0 (/usr/local/Cellar/node/15.14.0/bin/node)
   npm    : 7.11.1
   OS     : macOS Big Sur
```

**Comment by liamdebeasi** [comment] 2021-05-19 12:31
Thanks for the issue. Emulators are not a reliable way of testing device performance. Can you reproduce this issue in an Ionic starter app and provide a link to the repo? Also, are you able to reproduce this on a physical Android device?

**Comment by pixelone** [comment] 2021-05-19 18:11
Yes I, discovered this on a physical android device.  I found you can duplicate this issue on older iPads as well.

To verify this wasn't bad code in my project I started a new tabs project, put a modal in the side menu with a rest API that pulls a 100 list items in.. click away and you can get duplicate modals showing. 

I have been unable to duplicate on newer devices such as an iPhone 11 / iPad 12, but some older devices seem to suffer a lag which allows multiple taps/clicks to be fired before the first click is fully complete..  This then results in duplicate modals, alerts, etc.

You can see the gif image below where duplicate modals are opened, in this case its two duplicate, but I have gotten 3-4 before. 

Whether this is a bug or not I am not sure, but appreciate any feedback as this created many problems on a project I was working on. The only way I have found to prevent it is  to use a directive to throttle clicks/taps or create a flag every time a modal is opened.

![dup-modal](https://user-images.githubusercontent.com/12859431/118859369-ffb74600-b88e-11eb-8f4d-00f0f60da1c1.gif)

**Comment by danielehrhardt** [comment] 2021-05-23 00:07
I can confirm this Issue. It does happen on Android and on iOS Devices. Even on old PCs. 
I can remember that this happens since Version 2 (Maybe also 1)

**Comment by faizanu94** [comment] 2021-05-24 08:19
Simply using [debounce](https://rxjs.dev/api/operators/debounce) in modal creation logic would be another solution, as usually debouncing is encouraged on user inputs which fetch data through HTTP in use cases like suggestions, filtering etc. for providing better performance and user experience:

```
debounce(func, timeout = 300) {
    let timer;
    return (...args) => {
        clearTimeout(timer);
        timer = setTimeout(() => { func.apply(this, args); }, timeout);
    };
}

async openModal() {
    const modal = await this.modalCtrl.create ...
}

openModalWrapper = this.debounce(() => this.openModal());
```

**Comment by liamdebeasi** [comment] 2021-05-24 13:04
Thanks for the additional information! The `modalController` was designed to create a new instance of a modal every time `modalController.create` is called. I do not think it would be a good idea to introduce some level of state to this otherwise stateless controller. That being said there are a few things we are doing in Ionic Framework v6 to make it easier to work around these issues:

1. In certain versions of Ionic (React and Vue at least for right now) we will be moving off Stencil's lazy loading which should reduce the likelihood of this behavior happening in the first place.
2. We will be adding the ability to use popovers and modals directly in your template. Since you would be dealing with a single modal or popover instance, this behavior would no longer happen.

We will have a beta period soon where developers can test this out.

In terms of what you can do now if you want to continue using the controller, I think it would be best for apps to wait on a previous `modalController.create` promise to resolve before calling it again. You could implement something like this:

```js
private openModal() {
  // If there is a modal in the process of opening, do not open a new modal
  if (this.modal) {
    return;
  }

  // Create the modal, but do not await it here until you assign it to this.modal
  const modalEl = this.modal = modalCtrl.create({ ... });
  
  // Wait for the modal to be created and presented
  await this.modal;
  await this.modal.present();

  // Clear the variable so the openModal function can be called again
  this.modal = undefined;

 // you can await the modalEl variable for onDidDismiss
}
```

I am going to close this issue as this is not a bug in Ionic Framework. Thanks!

**Closed by liamdebeasi** 2021-05-24 13:04 UTC
Labels: triage
