### ISSUE TITLE
bug: IonIcon doesn`t work with Rollup

### ISSUE THREAD

**Issue by Algoritm211** [ionic-team/ionic-framework#24014] opened 2021-10-05 07:59 UTC
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

We are developing a component library based on ionic and React using the Rollup collector and there was one problem using the IonIcon component. During the build, this error occurs:

```javascript
(!) Plugin typescript: @rollup/plugin-typescript TS4023: Exported variable 'PsychologistCardIcons' has or is using name 'IonIconProps' from external module "/Users/alexey/Desktop/uiComponents/node_modules/@ionic/react/dist/types/components/IonIcon" but cannot be named.
src/lib/therapist-card/TherapistCard.style.ts: (91:14)

export const PsychologistCardIcons = styled(IonIcon)`
```

Here is my styled-components that inherits from IonIcon: 
```typescript
import { IonIcon } from '@ionic/react';

export const PsychologistCardIcons = styled(IonIcon)`
  color: ${colorConstants.primaryColor};
  width: 20px;
  height: 20px;
  margin: 0;
    
  @media (max-width: 320px) {
    width: 19px;
  }
`;
```
And this is how I use it:
```typescript
<IconsContainer>
   <PsychologistCardIcons icon={timeOutline} />
    <p className='semiBold'>{`${psychologistDuration}`}</p>
</IconsContainer>
```

I also attach a config rollup.config.js

```javascript
import resolve from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';
import typescript from '@rollup/plugin-typescript';
import postcss from 'rollup-plugin-postcss';
import {terser} from 'rollup-plugin-terser';
import svg from 'rollup-plugin-svg-import';

export default {
    input: './src/index.ts',
    external: ['styled-components', 'react', 'react-dom'],
    globals: {'styled-components': 'styled'},
    options: [
        '',
    ],
    output: {
        dir: 'dist',
        format: 'esm',
        preserveModules: true,
        preserveModulesRoot: 'src',
        sourcemap: true,
    },
    plugins: [
        resolve(),
        commonjs(),
        typescript({
            tsconfig: './tsconfig.json',
            declaration: true,
            declarationDir: 'dist',
        }),
        postcss(),
        terser(),
        svg({
            stringify: false,
        }),
    ],
    context: 'window',
};

```

And tsconfig.json

```json
{
  "compilerOptions": {
    "rootDir": "src",
    "declaration": true,
    "declarationDir": "build",
    "module": "esnext",
    "target": "es5",
    "lib": ["es6", "dom", "es2016", "es2017"],
    "sourceMap": true,
    "jsx": "react",
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
    "declarationMap": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
  },
  "include": ["src/**/*"],
  "exclude": [
    "node_modules",
    "build",
    "storybook-static",
    "src/**/*.stories.tsx",
    "src/**/*.test.tsx"
  ]
}

```

### Expected Behavior

Inheriting from IonIcon works well and builds the code correctly

### Steps to Reproduce

Problem with building library with Ionic and inheritance and styled components

### Ionic Info

**Ionic:**

   - Ionic CLI       : 5.4.16 (/opt/homebrew/lib/node_modules/ionic)
   - Ionic Framework : @ionic/react 5.8.1

**Utility:**

   - cordova-res : not installed
   - native-run  : not installed

**System:**

   - NodeJS : v16.10.0 (/opt/homebrew/Cellar/node/16.10.0/bin/node)
   - npm    : 7.24.0
   - OS     : macOS Big Sur

**Comment by liamdebeasi** [comment] 2021-10-05 13:02
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/24015.

**Closed by liamdebeasi** 2021-10-05 13:02 UTC
Labels: triage
