### ISSUE TITLE
bug: Ion-datetime not functional after adding slot buttons

### ISSUE THREAD

**Issue by BramDecuypere** [ionic-team/ionic-framework#24607] opened 2022-01-20 12:14 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Either there is some documentation lacking, or there is a problem with the component itself.

When I use this as a component:

```
<ion-datetime (ionChange)="onDateChanged($event)">
   <ion-buttons slot="buttons">
      <ion-button color="primary" onClick="() => this.confirm()">Good to go!</ion-button>
      <ion-button color="danger" onClick="() => this.reset()">Reset</ion-button>
   </ion-buttons>
</ion-datetime>
```

### Expected Behavior

Just a functional component/documentation on order.

### Steps to Reproduce

1. Start with an ion-datetime
2. add the slots button -> calendar today is no longer working

### Ionic Info

v6

**Comment by Agular** [comment] 2022-01-24 09:10
I am having the same problem. When custom buttons are added, the datetime picker does not work. I can change the datem but it resets back to today when I choose the time.

**Comment by Agular** [comment] 2022-01-24 10:15
We have this on line 476 in datetime.tsx code. If buttons are slotted / default buttons are used, then confirm is not called on whenever user picks a new date or time. Confirm would update the value and emit it through the event listener.

However we need the component to confirm any date changes, but **not** emit any ionChange event.

Current workaround for updating the date at least would be to listen to the datetime click event and call confirm ourselves on the component. Sadly, we can't do that for the time picker since that event is stopped from propagating.

```const hasSlottedButtons = this.el.querySelector('[slot="buttons"]') !== null;
    if (hasSlottedButtons || this.showDefaultButtons) { return; }

    this.confirm();

**Comment by Agular** [comment] 2022-01-24 13:31
Simple reproduction. Added a gif.
When pushing the date, it's not confirmed and does not get a blue color.
Selecting the time for the picker does not update the time and also resets previously selected date 
```
<ion-datetime showDefaultButtons={true}>
  <ion-label slot="title">Title</ion-label>
</ion-datetime
```
![ionDateTimeButtonsDemo](https://user-images.githubusercontent.com/18621326/150791709-4382f899-6e80-45ae-bd1e-2ea94b9e872b.gif)

**Comment by amandaesmith3** [comment] 2022-01-27 15:14
Thanks for the issue, and glad to hear you were able to find the fix! I'm going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/24451.

**Closed by amandaesmith3** 2022-01-27 15:14 UTC
Labels: ionitron: needs reproduction
