### ISSUE TITLE
bug: Navigating between Tabs with Vue router-links doesn't behave as expected

### ISSUE THREAD

**Issue by gilbertsmink** [ionic-team/ionic-framework#22389] opened 2020-10-25 10:23 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

A router-link inside Tab2 that points to Tab1, opens in Tab2.

**Expected behavior:**

A router-link inside Tab2 that points to Tab1, opens in Tab1

**Steps to reproduce:**

1 Open tab 2
2 Click ‘Link to tab 1 main page’
3 Click tab 3
4 Click tab 2, now you will see tab 1 is opened in tab 2
5 Click tab2 again and tab2 will open

Step 4 is incorrect, I expect that tab 2 opens straight away.

Please see: https://streamable.com/vehebz

**Related code:**

https://github.com/gilbertsmink/ionic-vue-tabs-test

**Comment by liamdebeasi** [comment] 2020-10-26 19:21
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/22307. (same underlying problem)

**Closed by liamdebeasi** 2020-10-26 19:21 UTC
Labels: triage

**Comment by liamdebeasi** [comment] 2020-10-28 22:27
Hey there,

I have added a PR that resolves this issue. There is a dev build in https://github.com/ionic-team/ionic-framework/issues/22307#issuecomment-718244083 if you are interested in testing it out.

**Comment by gilbertsmink** [comment] 2020-10-29 15:59
I can confirm that the dev build resolves the issue for #22389! Super, thanks!
