### ISSUE TITLE
bug: input signal effects are not run when attaching a directive to an IonButton

### ISSUE THREAD

**Issue by Eraldo** [ionic-team/ionic-framework#29444] opened 2024-05-02 18:46 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v8.x

### Current Behavior

Running an effect on an input signal within a directive that is attached to an IonButton does not trigger/run the effect code.

### Expected Behavior

Running an effect on an input signal within a directive that is attached to an IonButton does trigger/run the effect code.

### Steps to Reproduce

1. Open the reproduction url.
2. Follow on screen instructions.

### Code Reproduction URL

https://stackblitz.com/edit/stackblitz-starters-gkckxf?file=src%2Fmain.ts

### Ionic Info

@ionic/angular: 8.1.0
Angular version: 17.3.4

### Additional Information

It works just fine if attached to other html tags.

Insight:
This is where the current behavior is probably sourced => https://github.com/ionic-team/ionic-framework/blob/ba5cebf2542c8fbd6c29af593a31a742e0caba1e/packages/angular/src/directives/proxies.ts#L357

Issue has been confirmed by "JB Nizet" and "Matthieu Riegler" and I was encouraged to create a bug report here.

**Comment by JeanMeche** [comment] 2024-05-02 18:52
Hi, this looks like a bug in Angular internals, I've re-open this issue over there.

**Comment by brandyscarney** [comment] 2024-05-03 16:23
Thank you for the issue! I am going to close this as it was confirmed above to be an Angular issue. Please follow along on that issue.

**Closed by brandyscarney** 2024-05-03 16:23 UTC
Labels: triage
