### ISSUE TITLE
bug: ionic/vue router raise error Cannot read property 'classList' of undefined

### ISSUE THREAD

**Issue by darkman97i** [ionic-team/ionic-framework#23620] opened 2021-07-13 18:58 UTC
# Bug Report

**Ionic version:**
* "@ionic/pwa-elements": "^3.0.2",
* "@ionic/vue": "^5.6.11",
* "@ionic/vue-router": "^5.6.11",

**Current behavior:**
Second time accessing a path is raising ionic/vue router

**Steps to reproduce:**
https://github.com/darkman97i/ionic-possible-bug-router#readme

![Selección_035](https://user-images.githubusercontent.com/958703/125508251-a7fa6e45-36bc-4e9b-956a-23d0b6208651.png)

**Related code:**
A sample application via GitHub: 
https://github.com/darkman97i/ionic-possible-bug-router

**Other information:**
Not sure if the issue was reported before here https://github.com/ionic-team/ionic-framework/issues/23377, by the description do not seems exactly the same

Thanks for your time

**Comment by liamdebeasi** [comment] 2021-07-13 20:50
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. Both your `Tab1` and `Tab3` pages are missing the `<ion-page>` component. All views in Ionic Vue require this wrapper component for transitions and lifecycle events to work properly: https://ionicframework.com/docs/vue/navigation#ionpage

**Closed by liamdebeasi** 2021-07-13 20:50 UTC
Labels: triage

**Comment by darkman97i** [comment] 2021-07-14 09:22
Thanks for your valuable support, 

I wrongly supposed with a single ion-page at the root of the hierarchy was enough. Because I have two calls with the router ( one to draw the master layout and another to draw wingle view ) it is required two ion-page one for each. 

My mistake, your documentation is clear "Each view that is navigated to using the router must include an IonPage component."

**Comment by liamdebeasi** [comment] 2021-07-14 12:40
I am also adding a check inside of Ionic Vue to warn developers whenever they forget `<ion-page>`: https://github.com/ionic-team/ionic-framework/pull/23625

It's an easy detail to miss, so hopefully this makes the developer experience a bit better.

**Comment by darkman97i** [comment] 2021-07-15 16:17
Thanks for the improvement.
