### ISSUE TITLE
Need event for breakpoints change on swipe up / down of Sheet Modal.

### ISSUE THREAD

**Issue by ashish-mahour** [ionic-team/ionic-framework#23989] opened 2021-09-28 12:25 UTC
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Need event for breakpoints change on swipe up / down of Sheet Modal.

### Describe the Use Case

Need to change contents based on available screen area.

**Comment by ashish-mahour** [comment] 2021-09-28 12:31
Looks like this is already requested in https://github.com/ionic-team/ionic-framework/issues/23955.

**Comment by liamdebeasi** [comment] 2021-09-28 13:06
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/23955.

**Closed by liamdebeasi** 2021-09-28 13:06 UTC
Labels: triage
