### ISSUE TITLE
bug: Content does not animate along with keyboard

### ISSUE THREAD

**Issue by igor-augustynski** [ionic-team/ionic-framework#21735] opened 2020-07-13 08:46 UTC
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
When focusing an input the keyboard opens with an animation, but the content just jumps up when the keyboard is done with the animation and does not follow along.

**Expected behavior:**
The content should move up and down following the keyboard animation.

**Steps to reproduce:**
Create a new ionic project, leave the default home page contents and add an input just under it. Build for iOS, run on a device and tap the input.

**Other information:**
![ionic-keyboard-issue](https://user-images.githubusercontent.com/6783824/87283797-fbdfc800-c4f5-11ea-910b-4da30a6a91ec.gif)

**Ionic info:**
```
Ionic:
   Ionic CLI                     : 6.10.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.2.3
   @angular-devkit/build-angular : 0.1000.2
   @angular-devkit/schematics    : 9.1.11
   @angular/cli                  : 10.0.2
   @ionic/angular-toolkit        : 2.2.0

Capacitor:
   Capacitor CLI   : 2.2.1
   @capacitor/core : 2.2.1

Utility:
   cordova-res : not installed
   native-run  : not installed

System:
   NodeJS : v14.4.0 (/usr/local/Cellar/node/14.4.0/bin/node)
   npm    : 6.14.5
   OS     : macOS Catalina
```

**Comment by liamdebeasi** [comment] 2020-07-13 13:07
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The default webview behavior is to resize the webview only when the keyboard has finished opening. You can change the resize behavior if you would like to implement some custom behavior: https://capacitorjs.com/docs/apis/keyboard#keyboard-configuration-ios-only-

**Closed by liamdebeasi** 2020-07-13 13:07 UTC
Labels: triage
