### ISSUE TITLE
bug: prefersWheel combined date-time pickers performance issues with a low minimum date

### ISSUE THREAD

**Issue by BurkusCat** [ionic-team/ionic-framework#26149] opened 2022-10-18 13:06 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

When you have a datepicker in wheel mode, if you have the `presentation` set to `date-time` and the `min` set to a long time in the past (e.g. 1900 is what we had set globally in our app), then you will experience performance issues. Setting the minimum to 2010 was still slow but not quite as bad.

I imagine what is happening is that the component is loading all possible dates back to your minimum year which would be very slow. Individual "date" and "time" pickers do not have any issues.

### Expected Behavior

An old minimum should not cause performance issues with this control. Suggestion: should the combined date/time picker have a year column in addition to month/day/hour/min? This would mean not having to generate all possible options.

### Steps to Reproduce

``` html
    <ion-datetime presentation="date-time"
        [preferWheel]="true"
        showDefaultButtons="true"
        min="1900"
        locale="en-GB"></ion-datetime>
```

### Ionic Info

Ionic:

   Ionic CLI                     : 6.19.0 (C:\Users\burku\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.3.0
   @angular-devkit/build-angular : 13.3.9
   @angular-devkit/schematics    : 13.2.6
   @angular/cli                  : 13.2.6
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.5.1
   @capacitor/android : 4.3.0
   @capacitor/core    : 4.3.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.1

System:

   NodeJS : v16.15.0 (C:\Program Files\nodejs\node.exe)
   npm    : 8.5.5
   OS     : Windows 10

### Additional Information

Workaround:
Set the minimum to a higher date (e.g. 2021). We are setting it to the previous year in our app which for our purposes will work fine.

**Comment by sean-perkins** [comment] 2022-10-18 20:32
@BurkusCat thank you for reporting this issue.

This has been fixed in [v6.3.1](https://github.com/ionic-team/ionic-framework/blob/main/CHANGELOG.md#631-2022-10-12).

Closing as a duplicate of #26059. Please comment if you continue to experience this issue on the latest version of Ionic and I will reopen and take another look.

Thanks!

**Closed by sean-perkins** 2022-10-18 20:32 UTC
Labels: triage
