### ISSUE TITLE
bug: v6, modal core delegate needs to account for modals placed at the root, hardware back button not working with modal

### ISSUE THREAD

**Issue by d00ML0rDz** [ionic-team/ionic-framework#23728] opened 2021-08-04 15:09 UTC
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

When setting up a fresh Ionic project and installing the v6 beta, the hardware back button on android doesn't navigate back when switching between the tabs if an IonModal has been added outside of IonReactRouter.

An example of why you might have the Modal outside of the ReactRouter is it may need to be opened on whatever page the user is on.

This was previously working fine in Ionic v5.

### Expected Behavior

The hardware back button should navigate back through the history.

### Steps to Reproduce

1. Pull the repo attached noticing the changes to the App.tsx underneath the IonReactRouter tag, where an IonModal has been added:
```
<IonModal isOpen={true}>
    Test
</IonModal>
```

2. Build and deploy the app to an android device. You should see that using the hardware back button does not go back when navigating between the 3 tabs and the modal does not display.

### Code Reproduction URL

https://github.com/d00ML0rDz/ionic-back-button-modal

### Ionic Info

Ionic:

   Ionic CLI       : 6.16.1 (C:\Users\jammi\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/react 6.0.0-beta.2

Capacitor:

   Capacitor CLI      : 3.1.2
   @capacitor/android : 3.1.2
   @capacitor/core    : 3.1.2
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.3
   native-run  : 1.4.0

System:

   NodeJS : v14.15.2 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.9
   OS     : Windows 10

**Comment by d00ML0rDz** [comment] 2021-08-09 14:53
It seems after some further investigation that this bug may not be limited to modals that exist outside the <IonTabs> component, but may apply to all of them. It seems even with IonPages that contain modals that upon opening those pages the hardware back button no longer responds to navigate back, even if the modal is closed and isn't opened in the page's lifetime.

**Comment by liamdebeasi** [comment] 2021-11-04 19:47
There are two issues here:

1. The hardware back button (HBB) listener for overlays currently accounts for all overlays, even if they are hidden. Overlays have a higher HBB priority than navigation does (https://ionicframework.com/docs/developing/hardware-back-button#internal-framework-handlers). Since the new declarative modals are in the DOM, the overlay utility is always picking up that non-presented modal when the HBB is pressed. In effect, this modal blocks navigation. The solution here is to only make the HBB listener account for open modals. This has technically been an issue for a long time, but the issue is more prevalent now with the declarative modals (to test, try doing `modalController.create`, but never present the modal).

2. The new utility that transports the overlays to the root of `ion-app` fails if the overlay is already in `ion-app`. The solution here is possibly to check if the parent element of the overlay is `ion-app`.

**Comment by liamdebeasi** [comment] 2021-11-08 15:19
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/24174, and a fix will be available in an upcoming release of Ionic Framework.

**Closed by liamdebeasi** 2021-11-08 15:19 UTC
Labels: package: core, type: bug
