### ISSUE TITLE
bug: ionic vue v-model ref being updated after ionChange fires

### ISSUE THREAD

**Issue by AlwaysLoveme** [ionic-team/ionic-framework#22610] opened 2020-12-02 02:26 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

use "v-model" on "ion-searchbar" return wrong value when trrigered "ionChange" event;
**Expected behavior:**

use "v-model" on "ion-searchbar" return correct value when trrigered "ionChange" event;
**Steps to reproduce:**

**Related code:**
```
<ion-searchbar placeholder="enter key" inputmode="search" animated debounce="500" v-model="keywords" @ionChange="change">

....
<script lang="ts">
import {useRouter} from 'vue-router';
import {defineComponent, ref} from 'vue';

export default defineComponent({
  name: "AMapLocation",
  setup() {
    const router = useRouter();
    const keywords = ref("");
    const change  = () => {
        // The value returned is the last updated value，Not the current value
        console.log(keywords.value);
     }
    return {
      keywords,
      change,
    };
  }
})
</script>
```

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.12.2 (/Users/zhuxian/.nvm/versions/node/v12.19.0/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 5.5.0

Capacitor:

   Capacitor CLI   : 2.4.2
   @capacitor/core : 2.4.2

Utility:

   cordova-res (update available: 0.15.2) : 0.15.1
   native-run                             : not installed

System:

   NodeJS : v12.19.0 (/Users/zhuxian/.nvm/versions/node/v12.19.0/bin/node)
   npm    : 6.14.9
   OS     : macOS Big Sur

```

**Comment by liamdebeasi** [comment] 2020-12-02 14:30
Thanks, I can reproduce this. The issue looks like the ref is being updated after the component's `ionChange` event fires. As a temporary workaround, you can wrap your call in a `requestAnimationFrame`:

```js
const change = () => {
  requestAnimationFrame(() => {
    console.log(keywords.value);
  });
}
```

**Comment by liamdebeasi** [comment] 2021-01-08 17:03
Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue?

```
npm install @ionic/vue5.6.0-dev.202101081655.6e93799 @ionic/vue-router@5.6.0-dev.202101081655.6e93799
```

**Comment by liamdebeasi** [comment] 2021-01-13 16:22
I confirmed the fix on my end and merged the changes in via https://github.com/ionic-team/ionic-framework/pull/22749, but please feel free to give the dev build a test!

**Closed by liamdebeasi** 2021-01-13 16:22 UTC
Labels: package: vue, type: bug
