### ISSUE TITLE
bug:  Cannot select a year higher than the current one in an ion-datetime

### ISSUE THREAD

**Issue by gsyjdcg** [ionic-team/ionic-framework#22191] opened 2020-09-28 08:33 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

Cannot select a year higher than the current one in an ion-datetime

**Expected behavior:**

To be able to select a year higher than the current one

**Steps to reproduce:**

You only need to add the following component:

<ion-datetime></ion-datetime>

**Comment by liamdebeasi** [comment] 2020-09-28 12:58
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. By default, the max year is shown as the current year. You can use the `max` property to show future years: https://ionicframework.com/docs/api/datetime#properties

**Closed by liamdebeasi** 2020-09-28 12:58 UTC
Labels: triage
