### ISSUE TITLE
feat: add start and progress events on sheet modals when cycling between breakpoints

### ISSUE THREAD

**Issue by greg-md** [ionic-team/ionic-framework#27751] opened 2023-07-05 23:47 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Currently there is only one event `ionBreakpointDidChange` when cycling between breakpoints of a sheet modal. But would be very useful to have 2 more events:

- `ionBreakpointWillChange` which should be triggered when the animation/swipe starts;
-  and `ionBreakpointChange` to keep track of the animation/swiping progress;

### Describe the Use Case

Both of these events would allow to smoothly change/animate other elements on the screen based on the current progress. For example showing/hiding headers/footers.

### Additional Information

A good working example is the Explore tab of the Airbnb app, when you swipe down the list modal to view the map -> the bottom tab bar and the map button is hiding based on modal progress.

**Comment by sean-perkins** [comment] 2023-07-06 02:26
Hello @greg-md thanks for this feature request! I'm going to attach a screen recording of the Explore tab that you are referring to with the Airbnb app.

https://github.com/ionic-team/ionic-framework/assets/13732623/9dd29c11-36a5-4381-904c-eec283ab606c

I will mention that I was able to break this effect in their app by scrolling from the primary content of the bottom sheet (when dragging up and down). 

I'm unsure about `ionBreakpointWillChange` emitting when swiping starts. I would expect based on similar event naming, that it should only emit when the swipe action would result in a different breakpoint being activated, but before the breakpoint is set. 

I'll discuss with the team about an event for when the sheet modal is dragged, to allow surrounding UI to respond to the current sheet modal position.

**Comment by sean-perkins** [comment] 2023-07-06 18:35
👋 after following up with the team we realized this is a duplicate of: https://github.com/ionic-team/ionic-framework/issues/23955. I'm going to close this feature request in favor of that one. I'll drop the reference for the Airbnb app onto that thread as well.

Thanks!

**Closed by sean-perkins** 2023-07-06 18:35 UTC
Labels: triage
