### ISSUE TITLE
bug: Nested router-outlet does not work properly

### ISSUE THREAD

**Issue by estankovic** [ionic-team/ionic-framework#22812] opened 2021-01-22 15:54 UTC
# Bug Report

**Ionic version:**
[?] **4.x**
[x] **5.x** (Angular)

**Current behavior:**
When creating nested `ion-router-outlet` or `router-outlet` only first navigation works.

**Expected behavior:**
When using nested `ion-router-outlet` or `router-outlet` all navigations should work, and correct components should be rendered.

**Steps to reproduce:**
In the [demo](https://stackblitz.com/github/estankovic/ionic-nested-routing-issue-2?file=src%2Fapp%2Ftab2%2Ftab2.page.html) project, 
1. Navigate to the Tab2
2. Then click on The SubTab2 button *(Propper component is presented)*
3. Now click on SubTab1 button *(Nothing happens, but in fact SubTab1 content should be presented)*

**Related code:**

[Live Demo](https://stackblitz.com/github/estankovic/ionic-nested-routing-issue-2?file=src%2Fapp%2Ftab2%2Ftab2.page.html)
[Repository to reproduce this issue](https://github.com/estankovic/ionic-nested-routing-issue-2)

**Other information:**
This is quite annoying as I am having in my project usage for nested routable components, but unfortunately now it is not possible to implement.

**Comment by liamdebeasi** [comment] 2021-01-22 16:06
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/18823 and/or https://github.com/ionic-team/ionic-framework/issues/18197 (there is some overlay in these issues).

**Closed by liamdebeasi** 2021-01-22 16:06 UTC
Labels: triage
