### ISSUE TITLE
bug: ion-item fill outline does not have transparent background for MD

### ISSUE THREAD

**Issue by MoAsmar** [ionic-team/ionic-framework#24966] opened 2022-03-19 21:59 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

I am requesting adding **"transparent"** background to ion-item component property **fill**

as per the description:

> The fill for the item. If 'solid' the item will have a background. If'outline' the item will be transparent with a border. Only available in md mode.
https://ionicframework.com/docs/api/item#fill

but this is not the case, `fill="outline"` always have white background and an outline around the item.

### Describe the Use Case

I am looking to make a list of items with all the ion-item functionality but with transparent background to keep the background image showing behind the item text

### Describe Preferred Solution

Preferred Solution:

` <ion-item fill="transparent"> `

### Describe Alternatives

To achieve that result I had to use the below CSS:

```
.item-md {
  background: transparent;
}
```

### Related Code

![image](https://user-images.githubusercontent.com/8542126/159139706-a0d07284-676c-4c0d-a0ca-eafe89f81b90.png)

### Additional Information

I don't know if this is a bug in fill="outline" value because as per the description it should make the item background transparent but it is not or maybe I misunderstood the purpose of the value "outline".

**Comment by sean-perkins** [comment] 2022-03-20 04:15
@MoAsmar thanks for this feature/issue.

After quickly comparing against the Material design implementation, this appears to be a bug with our implementation of `fill="outline"`. 

I've created a reproduction here: https://stackblitz.com/edit/nbjr2m?file=index.html

We are currently setting the background value to transparent for all states, other than the default background:

https://github.com/ionic-team/ionic-framework/blob/63842a25c32be689bdc8a12d7e1c09a03d350b51/core/src/components/item/item.md.scss#L434-L435

I'll update the issue to reflect this.

**Comment by sean-perkins** [comment] 2022-03-20 04:49
Looks like there's compounding problems here. In your example you aren't using an `ion-label`, but with a label and `position="floating"`, the MD implementation begins to degrade.

With just changing the background on `ion-item` to support transparent: 
<img width="801" alt="Screen Shot 2022-03-20 at 12 37 56 AM" src="https://user-images.githubusercontent.com/13732623/159148480-a1d471ca-d368-4d38-9efc-3533d71eaa06.png">

Updating `ion-label` to inherit the background color from the item's fill:
<img width="802" alt="Screen Shot 2022-03-20 at 12 37 27 AM" src="https://user-images.githubusercontent.com/13732623/159148482-7afc1ce8-af98-4472-9247-a84da790a76e.png">

I will need to discuss more with the team early next week. The PR to introduce this change: https://github.com/ionic-team/ionic-framework/pull/23354 did not align the implementation pattern against Material design. In Material's implementation they divide the container into a grid, so that they can hide the border that is currently displaying under the label. Ionic will need to do something similar or create a pseudo element matching the item's background that displays between the item and label. 

It may be advantageous to address this issue and other minor inconsistencies with the implementation at the same time. For instance, the outline/border animation is different between Ionic vs. Material.

**Comment by liamdebeasi** [comment] 2023-01-11 21:24
Thanks for the report. In Ionic 7 we are introducing a new syntax for working with `ion-input`. This issue is fixed when using that new syntax. We will have an Ionic 7 beta in the future where developers can test and provide feedback. There will also be a migration guide to show how to update to the new input syntax.

The work required to resolve this has been completed, so I am going to close this thread. Let me know if there are any questions.

**Closed by liamdebeasi** 2023-01-11 21:24 UTC
Labels: package: core, type: bug
