### ISSUE TITLE
bug: picker render problem

### ISSUE THREAD

**Issue by muyunwu** [ionic-team/ionic-framework#24162] opened 2021-11-04 08:15 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

picker columns not render options

### Expected Behavior

render options

### Steps to Reproduce

https://codesandbox.io/s/ion-picker-problem-h5851

**Comment by liamdebeasi** [comment] 2021-11-04 13:22
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/17664.

**Closed by liamdebeasi** 2021-11-04 13:22 UTC
Labels: triage

**Comment by outdoorfish** [comment] 2021-11-04 13:43
@liamdebeasi  thanks 

but this issue is options render empty rather overlap
is same issue?

Sorry for my poor English
<img width="1386" alt="截圖 2021-11-04 下午9 43 07" src="https://user-images.githubusercontent.com/92348687/140324099-d209ccec-79f1-4c1a-b745-daa11394f687.png">

**Comment by muyunwu** [comment] 2021-11-04 13:46
@liamdebeasi thanks

but this issue is options render empty rather overlap
is same issue?

<img width="1386" alt="截圖 2021-11-04 下午9 43 07" src="https://user-images.githubusercontent.com/36220587/140324594-bb1e62f0-960f-4e32-831e-34b561d942f8.png">
Sorry for my poor English

**Comment by liamdebeasi** [comment] 2021-11-04 13:47
Sorry, I should have clarified in my last comment. The two issues have the same underlying cause so that's why I grouped them together.
