### ISSUE TITLE
bug: accordion animation choppy

### ISSUE THREAD

**Issue by farisfaisalthena** [ionic-team/ionic-framework#25364] opened 2022-05-27 04:42 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

I have created an menu items and each categories are inside one accordion. upon opening the accordion some of them seems to have a choppy animation. You can see an example of the issue [here](https://www.youtube.com/watch?v=2PncrTZOQ-g). The choppy animation can be visible under "Campus Life" and "Academic & Enrollment". Besides this, the issue will be visible when navigating to the page the first time.

### Expected Behavior

N/A

### Steps to Reproduce

Not sure if this can be replicated but the repo i provided is the implementation which is being used on Prod.

- Open "Campus Life" and "Academic & Enrollment" accordion to see the issue.
- Refresh the page and open again

### Code Reproduction URL

https://github.com/farisfaisalthena/ionic-test

### Ionic Info

```typescript
Ionic:

   Ionic CLI                     : 6.19.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.1.7
   @angular-devkit/build-angular : 13.3.7
   @angular-devkit/schematics    : 13.3.7
   @angular/cli                  : 13.3.7
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.5.1
   @capacitor/android : not installed
   @capacitor/core    : 3.5.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.6.0

System:

   NodeJS : v16.14.2 (/usr/local/bin/node)
   npm    : 8.5.0
   OS     : macOS Monterey
```

**Comment by liamdebeasi** [comment] 2022-05-27 13:25
Thanks for the issue. This does not appear to be in Ionic bug. The problem here is with your usage of `ion-img`. The accordion needs to know the height of your content when the animation starts and expects that height to remain consistent throughout the animation. `ion-img` is designed to lazily load the image once `ion-img` is visible. This means that as the accordion content is shown, the images are loaded and cause a layout shift. This results in the choppy behavior you are reporting.

Here is a slowed down example:

https://user-images.githubusercontent.com/2721089/170704598-65c42993-c33e-43e4-b3af-a846d817e2bc.mov

(You might need to scrub through the video to see this.). Notice that as the accordion opens, the text inside of the card shifts due to the images loading.

-----

You have a couple options for avoiding this:

1. Use `<img>` without any lazy loading. This will avoid the layout shift as the images are loaded on page load. This may not be acceptable for your use case if you need lazy loading, but it is the simplest.
2. Set the `<ion-img>` to have a minimum width and height. I noticed that most of your icons are 32px x 32px. If you set `ion-img` to have a minimum width and height of 32px, you can avoid the layout shift and get the benefits of lazy loading. This may not be acceptable for your use case if your icons are different sizes.

So something like this:

```css
ion-img {
  min-width: 32px;
  min-height: 32px;
}
```

Can you try one of those and let me know if it resolves the issue?

**Comment by farisfaisalthena** [comment] 2022-05-27 13:31
Hi Liam,

Yup the issue is resolved with the suggested methods. Thank you for the quick response in clarifying this

**Comment by liamdebeasi** [comment] 2022-05-27 13:37
Glad to hear the issue is resolved! I am going to close this, but I am also going to update our accordion docs to make note of this: https://github.com/ionic-team/ionic-docs/pull/2353

Our documentation is not very clear about how to use lazy loaded content inside of accordion, so hopefully this helps other developers as well.

**Closed by liamdebeasi** 2022-05-27 13:37 UTC
Labels: triage
