### ISSUE TITLE
ion-back-button goes to root route when going from tabs A to tabs B

### ISSUE THREAD

**Issue by rygarok** [ionic-team/ionic-framework#22614] opened 2020-12-02 19:49 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

When I am in a page or sub-page of tabs A that redirects to a page or sub-page or tabs B for example, the back-button redirects to the "defaultHref" all the time.

Lets say I have 2 tabs

Clients (/clients)
Transactions (/transactions)

If I am inside a transaction **/transactions/5** for example, and I click on a button that says "See client info", which redirects to lets say **/clients/5** (a different tab), there is a back button here (to go back to the transaction lets say).

If I click on the back button from the client page, instead of redirecting me back to **/transactions/5**, its gonna redirect me to the defaultHref (which is the root page in my case "/")

**Expected behavior:**
In the example above, clicking the back button via the /clients/5 page, it should redirect me back to the /transactions/5 page since this is where I came from in the first place

**Steps to reproduce:**
**View loom example I did on my actual application**
https://www.loom.com/share/1900a674334a49a19e37f41f58f71075
1- I click on a link to another tab
2- I click the back button so I can go back to where i used to be
3- I get redirected to the root page "/" since this is the defaultHref

**Here is a quick project i created that reproduces the bug from scratch via the CLI**
https://bitbucket.org/agencemacmediacreation/ionic-tabs-back-bug-example

1- Navigate to http://localhost:8101/tabs/tab1/subpage1
2- Click on the "Go to different tab" button
3- From that page (http://localhost:8101/tabs/tab2/subpage2), click the "Back" button, which is a simple ion-back-button
4- You can see that you are not going back to the right page. The only reason it is coming back to the tab1 (not the subpage), is because the tab1 is the defaultHref for the ion-back-button "/"

**Related code:**

-->

**Sub-page 1**
```      
                    <ion-button [routerLink]="['/tabs2/sub-page2']">
                          Go to tabs #2
                    </ion-button>
```

**Sub-page 2**
```      
      <ion-buttons slot="start">
        <ion-back-button defaultHref="/" text="Back" ></ion-back-button>
      </ion-buttons>
```

**Ionic info:**
```
Ionic:

   Ionic CLI                     : 5.4.16 (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 5.4.3
   @angular-devkit/build-angular : 0.1002.0
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : not installed
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.16.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.12.0
   OS     : Windows 10


```

**Comment by rygarok** [comment] 2020-12-02 22:59
Hi there, I edited the initial post to include a bitbucket example of the issue!

**Comment by liamdebeasi** [comment] 2020-12-16 14:24
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. When switching between tabs, Ionic Angular sets the "root" page. This is different than navigating forward as there is no `ion-back-button` or swipe to go back gesture when setting the "root" page. As a result, the `ion-back-button` should not show up on subpage2. It is showing up in your app because you have set `defaultHref`.  Note that if you went  from `tabs/tab2` --> `tabs/tab2/subpage2`, then the `ion-back-button` would show up and navigate back to `tabs/tab2` since you navigated "forward" in that scenario.

Another way to think of this is if you started on `tabs/tab1` and clicked the "Tab 2" button to `tabs/tab2`, an `ion-back-button` on `Tab2` would not show up since Ionic Angular sets the root page when switching tabs there as well.

Thanks!

**Closed by liamdebeasi** 2020-12-16 14:24 UTC
Labels: ionitron: needs reproduction
