### ISSUE TITLE
bug: (iOS) Relaunching app and tapping ion-menu freezes app TypeError: undefined is not an object (evaluating 'this.menuInnerEl.offsetWidth')

### ISSUE THREAD

**Issue by danielehrhardt** [ionic-team/ionic-framework#25148] opened 2022-04-19 11:30 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

After the app is installed in the simulator/device the ion-menu is working fine, but after relaunching the app and tapping the ion-menu is not responding anymore and throws an error:  [error] - Unhandled Promise rejection: undefined is not an object (evaluating '_this4.menuInnerEl.offsetWidth') ; Zone: <root> ; Task: Promise.then ; Value: {} @capacitor://localhost/node_modules_ionic_core_dist_esm_ion-menu_3_entry_js.js:404:39

### Expected Behavior

App should not freeze.

### Steps to Reproduce

Put ion-menu in a lazy loaded Angular Module. Run the App on a iPad. Restart the App. 

### Ionic Info

Ionic:

   Ionic CLI                     : 6.19.0 (/Users/danielehrhardt/.nvm/versions/node/v16.13.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.1.1
   @angular-devkit/build-angular : 13.3.3
   @angular-devkit/schematics    : 13.3.3
   @angular/cli                  : 13.3.3
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.4.3
   @capacitor/android : 3.4.3
   @capacitor/core    : 3.4.3
   @capacitor/ios     : 3.4.3

Cordova:

   Cordova CLI       : not installed
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : 0.15.4
   native-run  : 1.5.0

System:

   NodeJS : v16.13.0 (/Users/danielehrhardt/.nvm/versions/node/v16.13.0/bin/node)
   npm    : 8.7.0
   OS     : macOS Monterey
   Xcode  : Xcode 13.3.1 Build version 13E500a

### Additional Information

Related:
https://github.com/ionic-team/ionic-framework/issues/24787
https://github.com/ionic-team/ionic-framework/blob/da896848776105ba1f7035c4412495786199bade/core/src/components/menu/menu.tsx#L412
https://github.com/ionic-team/ionic-framework/issues/17948

**Comment by liamdebeasi** [comment] 2022-04-19 13:38
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/24907.

**Closed by liamdebeasi** 2022-04-19 13:38 UTC
Labels: triage
