### ISSUE TITLE
bug: Ionic call Keyboard.getResizeMode() on Android throws uncaught error

### ISSUE THREAD

**Issue by farshidpg** [ionic-team/ionic-framework#27503] opened 2023-05-18 13:07 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

when app start in android the ```Keyboard.getResizeMode()``` call from one of the ionic global component that it catched and show  runtime error . I read docs of capacitor keyboard and we know that getResizeMode() method is for iOS only . why in android called on app init automatically ? 

This is my console error : 

```result Keyboard.getResizeMode (#71292250)```
```
{
    "message": "not implemented",
    "code": "UNIMPLEMENTED"
}
```

Also this is screen shots of android version

**it’s make my app unuseable**  with vue-cli in vite version the runtime error not show but console throw excetiopn still fire

<img width="982" alt="Screenshot 2023-05-18 at 4 16 12 PM" src="https://github.com/ionic-team/ionic-framework/assets/9290073/2f345e61-dfe5-4932-b861-7facb182a836">

And my android Emulator

<img width="503" alt="Screenshot 2023-05-18 at 4 16 40 PM" src="https://github.com/ionic-team/ionic-framework/assets/9290073/1c30d181-2831-497f-b176-7da4abe26799">

### Expected Behavior

I think if ionic use  the ```Keyboard.getResizeMode()``` in any components it should check platform first for ignore calling on android and call in iOS only

### Steps to Reproduce

1. Check the global ionic components that using Keyboard.getResizeMode()
2. make sure the platform checked first and call Keyboard.getResizeMode() only in iOS
3. Maybe Catche exception in ```capacitor/keyboard``` plugin  for ignore runtime error even Keyboard.getResizeMode() called in any platform by 3rd Party plugins or components thats not official .

### Code Reproduction URL

GitHub starter tab app created with  latest ionic cli  and ionic vue and capacitor 5 ( But the bug is still with cap 4  too  and I think its fire from ionic )

https://github.com/farshidpg/ionic-starter/tree/main

**Starter app ionic  info** 

```
Ionic:

   Ionic CLI       : 7.1.1
   Ionic Framework : @ionic/vue 7.0.7

Capacitor:

   Capacitor CLI      : 5.0.3
   @capacitor/android : 5.0.3
   @capacitor/core    : 5.0.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.2

System:

   NodeJS : v19.6.1
   npm    : 9.5.0
   OS     : macOS Unknown

```

the problem still get error on app init 

### Ionic Info

``` Ionic:

   Ionic CLI       : 7.1.1
   Ionic Framework : @ionic/vue 7.0.7

Capacitor:

   Capacitor CLI      : 4.8.0
   @capacitor/android : 4.8.0
   @capacitor/core    : 4.8.0
   @capacitor/ios     : 4.8.0

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.2

System:

   NodeJS : v19.6.1
   npm    : 9.5.0
   OS     : macOS



Android SDK : 33
```

### Additional Information

Capacitor keyboard plugin information ```getresizemode``` method

https://capacitorjs.com/docs/v4/apis/keyboard#getresizemode

I check my project and I know  I don't use  ```Keyboard.getResizeMode()``` method manually , I'm sure it's called globally

**Comment by farshidpg** [comment] 2023-05-18 13:53
> Thanks for the issue! This issue has been labeled as `needs reproduction`. This label is added to issues that need a code reproduction.
> 
> Please reproduce this issue in an Ionic starter application and provide a way for us to access it (GitHub repo, StackBlitz, etc). Without a reliable code reproduction, it is unlikely we will be able to resolve the issue, leading to it being closed.
> 
> If you have already provided a code snippet and are seeing this message, it is likely that the code snippet was not enough for our team to reproduce the issue.
> 
> For a guide on how to create a good reproduction, see our [Contributing Guide](https://ionicframework.com/docs/contributing/how-to-contribute#creating-a-good-code-reproduction).

The Code Reproduction URL added  to issue ( edited )

**Comment by sovaltd** [comment] 2023-05-18 19:03
any body can help with this i have same issue

**Comment by sean-perkins** [comment] 2023-05-18 20:36
Hello everyone 👋 

Could someone test with this dev-build and let me know if they run into any issues?

```
7.0.8-dev.11684441614.1e9b8b2d
```

**Comment by farshidpg** [comment] 2023-05-18 20:52
> Hello everyone 👋
> 
> Could someone test with this dev-build and let me know if they run into any issues?
> 
> ```
> 7.0.8-dev.11684441614.1e9b8b2d
> ```

> Hello everyone 👋
> 
> Could someone test with this dev-build and let me know if they run into any issues?
> 
> ```
> 7.0.8-dev.11684441614.1e9b8b2d
> ```

Thank you for update , but the problem not solve  nothing change  , I  test  again an starter  ionic app without tabs and   check the console there is not any problem , I think  this problem is for "footer, tab-bar: wait for resize before re-showing (https://github.com/ionic-team/ionic-framework/issues/27417) ([70d9854](https://github.com/ionic-team/ionic-framework/commit/70d9854d8df5259ed715e282a6ca40ca3bea6192)), closes https://github.com/ionic-team/ionic-framework/issues/25990" change  because when using the tab template console show me ``` Keyboard.getResizeMode() ``` called .

**Comment by sean-perkins** [comment] 2023-05-18 21:04
@farshidpg thanks for testing so quickly!

I believe the problem is related to that change as well, but with the shared keyboard logic we encapsulate.

For reference, this is what the dev-build changed: https://github.com/ionic-team/ionic-framework/commit/e9b8b2d789d9466697fd0ad4e3cc9ed7b65aacc1

I'll need to do a little more discovery to narrow where else the resize mode is being called (or if the platform check is not sufficient enough for this use case).

**Comment by farshidpg** [comment] 2023-05-18 21:12
> @farshidpg thanks for testing so quickly!
> 
> I believe the problem is related to that change as well, but with the shared keyboard logic we encapsulate.
> 
> For reference, this is what the dev-build changed: [e9b8b2d](https://github.com/ionic-team/ionic-framework/commit/e9b8b2d789d9466697fd0ad4e3cc9ed7b65aacc1)
> 
> I'll need to do a little more discovery to narrow where else the resize mode is being called (or if the platform check is not sufficient enough for this use case).
> 
> Edit: I actually see where my logic is flawed - an `engine` can be defined on `md`... let me rework that.

Thank you , I check dev-build changed .

I'm just thinking out loud for this solution , what happens if you do like this ? 
( add optional  for getResizeMode ) may be work , I don't know :)
```
getResizeMode(): Promise<KeyboardResizeOptions | undefined> {
    const engine = this.getEngine();
    if (!engine || !engine?.getResizeMode) {
    if (!engine || !isPlatform('ios') || !engine?.getResizeMode) {
      // getResizeMode is only available on iOS
      // see: https://ionicframework.com/docs/native/keyboard#getresizemode
      return Promise.resolve(undefined);
    }

    return engine.getResizeMode();
  },
    ```

**Comment by sean-perkins** [comment] 2023-05-18 21:23
If you are up for checking another dev-build: `7.0.8-dev.11684444351.1b1ab142`

I updated the checks so that the check for platform is first: https://github.com/ionic-team/ionic-framework/commit/b1ab142d3bb0120f42e1004cb66265ce213a40d7. This _should_ cause the behavior to noop for MD or if you are not using the Keyboard plugin from Capacitor. 

If that doesn't work - I can boot up an emulator and do additional testing tomorrow.

**Comment by farshidpg** [comment] 2023-05-18 21:44
> If you are up for checking another dev-build: `7.0.8-dev.11684444351.1b1ab142`
> 
> I updated the checks so that the check for platform is first: [b1ab142](https://github.com/ionic-team/ionic-framework/commit/b1ab142d3bb0120f42e1004cb66265ce213a40d7). This _should_ cause the behavior to noop for MD or if you are not using the Keyboard plugin from Capacitor.
> 
> If that doesn't work - I can boot up an emulator and do additional testing tomorrow.

Thank you , I test again and problem still exist on tabs template . 

I'am using the ```@capacitor/keyboard``` plugin version ```4.1.1``` but I test it with ```4.1.0``` and also ```5.0.2```

this is part of my package.json content

```
"@capacitor-community/file-opener": "^1.0.5",
"@capacitor/android": "4.8.0",
"@capacitor/app": "^4.1.1",
"@capacitor/camera": "^4.1.5",
"@capacitor/cli": "^4.8.0",
"@capacitor/clipboard": "^4.1.0",
"@capacitor/core": "^4.8.0",
"@capacitor/device": "^4.1.0",
"@capacitor/filesystem": "^4.1.4",
"@capacitor/haptics": "4.1.0",
"@capacitor/ios": "4.8.0",
"@capacitor/keyboard": "4.1.1",
"@capacitor/local-notifications": "^4.1.5",
"@capacitor/push-notifications": "^4.1.3-nightly-20230316T150919.0",
"@capacitor/splash-screen": "^4.2.0",
"@capgo/capacitor-mute": "^1.1.52",
"@capgo/native-audio": "^5.1.19",
"@ionic/core": "^7.0.8-dev.11684444351.1b1ab142",
"@ionic/pwa-elements": "^3.1.1",
"@ionic/storage": "^3.0.6",
"@ionic/vue": "^7.0.8-dev.11684444351.1b1ab142",
"@ionic/vue-router": "^7.0.8-dev.11684444351.1b1ab142",
"@vue/compiler-sfc": "^3.3.4",
"vue": "^3.3.4",
"vue-loader": "^17.1.1",
"vue-router": "^4.2.0",
```

**Comment by sean-perkins** [comment] 2023-05-19 01:24
@farshidpg can you remove the explicit `@ionic/core` dependency and run `npm ls @ionic/core`?

The expected output should be:
```
starter@0.0.1 /Users/sean/Documents/ionic/issues/ionic-starter
└─┬ @ionic/vue@7.0.8-dev.11684444351.1b1ab142
  └── @ionic/core@7.0.8-dev.11684444351.1b1ab142
```

Can you also confirm you are re-running `npm run build` and `npx cap copy android` after updating the dependency?

With the latest dev-build on the reproduction, I do not receive errors in the console on an emulator.

**Comment by farshidpg** [comment] 2023-05-19 01:36
> @farshidpg can you remove the explicit `@ionic/core` dependency and run `npm ls @ionic/core`?
> 
> The expected output should be:
> 
> ```
> starter@0.0.1 /Users/sean/Documents/ionic/issues/ionic-starter
> └─┬ @ionic/vue@7.0.8-dev.11684444351.1b1ab142
>   └── @ionic/core@7.0.8-dev.11684444351.1b1ab142
> ```
> 
> Can you also confirm you are re-running `npm run build` and `npx cap copy android` after updating the dependency?
> 
> With the latest dev-build on the reproduction, I do not receive errors in the console on an emulator.

Yes I run ``` npx cap copy  ``` and ``` npx cap sync ```  but the result of ``` npm ls @ionic/core ``` is wrong .

This is result :
```
cvpchat@0.0.1 /Users/farshidrezaiyan/Projects/ionic-starter
├── @ionic/core@7.0.8-nightly.20230518
└─┬ @ionic/vue@7.0.8-nightly.20230518
  └── @ionic/core@7.0.8-nightly.20230518 deduped
  ```

But why ? my package.json is update and I run :

```npm install```
```npm update```
```npx cap sync```
```cpx cap update```
whats worng with my project in local  that still using 7.0.8-nightly.20230518 ?

**Comment by farshidpg** [comment] 2023-05-19 02:07
> NPM package resolution can be difficult. The `nightly-` build is a different output than the provided dev build.
> 
> You can try removing the leading `^` in your package.json:


Yes, its work I remove the ```^``` and  now my project using the ```7.0.8-dev.11684444351.1b1ab142``` I check it .

Also the error solved 👍   the ```Keyboard.getResizeMode()``` don't call in android and no console error , no runtime error with vue-cli . 

Thank you bro, you save me 🥇

**Comment by sean-perkins** [comment] 2023-05-19 13:27
It is still subject to the team's review, you can track the pull request here: https://github.com/ionic-team/ionic-framework/pull/27514

Once merged, it will be available on the next week's patch release (we try to release weekly). 

Happy to help & thanks for the quick testing and verification 🎉

**Comment by farshidpg** [comment] 2023-05-24 20:00
> It is still subject to the team's review, you can track the pull request here: #27514
> 
> Once merged, it will be available on the next week's patch release (we try to release weekly).
> 
> Happy to help & thanks for the quick testing and verification 🎉

Hello , the 7.0.8 version released , is there this big fix in 7.0.8 ? ( is it merged ) 

Thank you

**Comment by chriswep** [comment] 2023-05-24 20:49
i tried `7.0.8` and the error is still there.

any reason why this wasn't included in the patch release? from what i see this throws an error on every android device.

**Comment by sean-perkins** [comment] 2023-05-24 20:57
> Once merged, it will be available on the next week's patch release (we try to release weekly). 

The PR was not merged, so it was not included in this week's patch release. The PR was still receiving feedback and was not ready for today's release. 

It has since been tested and approved with an alternative approach that isn't coupled to platform checks. 

It will be moved into a merge queue shortly and will be ready for the next week's release.

**Closed** 2023-05-24 21:33 UTC
Labels: package: core, type: bug
