### ISSUE TITLE
feat: ion-datetime add calendar day highlight customclass

### ISSUE THREAD

**Issue by GerardoPrototype** [ionic-team/ionic-framework#29426] opened 2024-04-30 20:05 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

I would like to add a bar below the numbers

### Describe the Use Case

<img width="432" alt="Captura de pantalla 2024-04-30 a la(s) 12 59 15 p m" src="https://github.com/ionic-team/ionic-framework/assets/133162777/7f5443e2-58ce-45bf-a878-10dd01c7541e">

### Describe Preferred Solution

I suppose for developer experience it can be added as an additional prop?
Otherwise editing the shadow css or a custom class?

Feedback for the solution would be helpful here as my opinion may be naive.

### Additional Information

#28022  I took some of the information from this case. since I think it is not a duplicate

**Comment by liamdebeasi** [comment] 2024-04-30 21:04
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/25340. The `highlightedDates` API lets you call out notable dates using text and background colors. We don't support the specific bar layout requested here, but this API can be used to achieve the overall goal of highlighting important dates.

**Closed by liamdebeasi** 2024-04-30 21:04 UTC
Labels: triage
