### ISSUE TITLE
bug: ion-list attribute "lines" not working when attribute "inset" is true

### ISSUE THREAD

**Issue by DwieDima** [ionic-team/ionic-framework#20819] opened 2020-03-19 12:50 UTC
# Bug Report

**Ionic version:**

[x] **5.0.5**

**Current behavior:**

When you create an `ion-list` with `ion-items` and set the attribute `inset="true"` on `ion-list`, the attribute `lines` wont have any effect on `ion-item`. Instead you'll always see full lines.

**Expected behavior:**

attribute `lines` on `ion-list` should work when attribute `inset="true"` is set. 

**Steps to reproduce:**

copy paste this snippet to any page:

```html
 <ion-list inset="true" lines="full">
    <ion-item detail="true">
      <ion-label>test</ion-label>
    </ion-item>
    <ion-item detail="true">
      <ion-label>test</ion-label>
    </ion-item>
    <ion-item detail="true">
      <ion-label>test</ion-label>
    </ion-item>
    <ion-item detail="true">
      <ion-label>test</ion-label>
    </ion-item>
    <ion-item detail="true">
      <ion-label>test</ion-label>
    </ion-item>
    <ion-item detail="true">
      <ion-label>test</ion-label>
    </ion-item>
    <ion-item detail="true">
      <ion-label>test</ion-label>
    </ion-item>
  </ion-list>
```
- change lines attribute to `lines="none"`, `lines="inset"` --> no effect.
- removing lines attribute will remain in `lines="full"`.
  - Isn't the default behaviour `lines="inset"` ?

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.2.2 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.1.0-dev.202003171608.9d9a02f
   @angular-devkit/build-angular : 0.900.5
   @angular-devkit/schematics    : 9.0.5
   @angular/cli                  : 9.0.5
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 1.5.0
   @capacitor/core : 1.5.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : none
   Cordova Plugins   : no whitelisted plugins (1 plugins total)

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   ios-deploy : 1.10.0
   ios-sim    : 8.0.2
   NodeJS     : v12.16.0 (/usr/local/bin/node)
   npm        : 6.13.4
   OS         : macOS Catalina
   Xcode      : Xcode 11.3.1 Build version 11C504
```

**Comment by liamdebeasi** [comment] 2020-03-19 13:29
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue? I am unable to reproduce the issue using the code snippet provided.

CodePen of ion-list: https://codepen.io/liamdebeasi/pen/LYVBVZb

**Comment by DwieDima** [comment] 2020-03-21 13:13
@liamdebeasi i see your codepen is working.
I've just created a fresh project with `"@ionic/angular": "^5.0.5"` and was able to reproduce the bug.
Heres the [repo](https://github.com/DwieDima/ion-list-bug).

--> when you serve the app, switch to iPad view using chrome browser:
- inspect
- toggle device toolbar
- select iPad

**Comment by liamdebeasi** [comment] 2020-04-01 14:01
Thanks for the follow up. I was able to reproduce the issue in my CodePen. It looks like this is related to https://github.com/ionic-team/ionic/issues/17425.

As a temporary workaround you can do the following to items in a list with `lines="none"` and `"inset="true"`.

```css
ion-list[inset=true][lines="none"] ion-item {
  --border-width: 0 !important;
}
```

**Comment by timdieperink** [comment] 2022-01-14 23:37
Were you able to fix this? I'm experiencing the same in Ionic 6 when trying to have inset lines within inset list items.. They remain full width.

**Comment by DwieDima** [comment] 2022-03-11 07:42
This also won't work if you use a plain `ion-item` with `lines="none"`

```html

    <ion-item class="ion-no-padding" lines="none">
      <ion-checkbox slot="start"></ion-checkbox>
      <ion-label class="ion-text-wrap>
        some label
      </ion-label>
    </ion-item>
```

workaround is:

```scss

ion-item {
  &[lines='none'] {
    --border-width: 0 !important;
  }
}
```

**Comment by ausminternet** [comment] 2022-11-14 10:26
workaround for `inset` with `lines="inset"`:

```css
ion-list[inset='true'][lines='inset'] ion-item {
  --border-width: 0 !important;
  --inner-border-width: 0 0 0.55px 0;
}
```

**Comment by liamdebeasi** [comment] 2023-01-11 22:12
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/26586, and a fix will be available in an upcoming release of Ionic Framework.

**Closed by liamdebeasi** 2023-01-11 22:12 UTC
Labels: package: core, type: bug
