### ISSUE TITLE
bug: Uncaught TypeError: Failed to construct 'URL': Invalid base URL

### ISSUE THREAD

**Issue by SiegeSailor** [ionic-team/ionic-framework#24480] opened 2021-12-23 05:21 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

The following message shows on the browser console whenever I render the component that contains `IonRefresherContent`.

```
Uncaught TypeError: Failed to construct 'URL': Invalid base URL
    at getAssetPath (index.js:2680)
    at getNamedUrl (icon.js:46)
    at getUrl (icon.js:27)
    at HTMLElement.loadIcon (icon.js:255)
    at icon.js:227
    at HTMLElement.waitUntilVisible (icon.js:250)
    at HTMLElement.connectedCallback (icon.js:225)
    at HTMLElement.connectedCallback (index.js:2280)
    at addVnodes (index.js:803)
    at patch (index.js:991)
    at renderVdom (index.js:1187)
    at callRender (index.js:1449)
    at updateComponent (index.js:1371)
    at index.js:1352
    at then (index.js:1582)
    at dispatchHooks (index.js:1352)
    at Array.dispatch (index.js:1320)
    at consume (index.js:2954)
    at flush (index.js:3009)
```

### Expected Behavior

Render `IonRefresherContent` without error messages.

### Steps to Reproduce

1. Use the following combo anywhere.

```
<IonRefresher slot="fixed">
  <IonRefresherContent />
</IonRefresher>
```

2. The error message is displayed on the browser console.

### Ionic Info

```
Ionic:

   Ionic CLI       : 6.18.1 (/Users/ken.zhang/.nvm/versions/node/v13.10.1/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 6.0.1

Capacitor:

   Capacitor CLI      : 3.0.0
   @capacitor/android : not installed
   @capacitor/core    : 3.0.0
   @capacitor/ios     : not installed

Utility:

   cordova-res (update available: 0.15.4) : 0.15.3
   native-run                             : 1.5.0

System:

   NodeJS : v13.10.1 (/Users/ken.zhang/.nvm/versions/node/v13.10.1/bin/node)
   npm    : 7.14.0
   OS     : macOS Big Sur
```

### Additional Information

```
dependencies in package.json

"@capacitor/app": "1.0.0",
"@capacitor/camera": "1.0.0",
"@capacitor/core": "3.0.0",
"@capacitor/filesystem": "1.0.0",
"@capacitor/haptics": "1.0.0",
"@capacitor/keyboard": "1.0.0",
"@capacitor/storage": "1.0.0",
"@ionic-native/camera": "5.36.0",
"@ionic-native/clipboard": "5.36.0",
"@ionic-native/core": "5.36.0",
"@ionic-native/firebase": "5.36.0",
"@ionic/pwa-elements": "3.1.1",
"@ionic/react": "6.0.1",
"@ionic/react-router": "6.0.1",
"@react-google-maps/api": "2.2.0",
"@reduxjs/toolkit": "1.5.1",
"@testing-library/jest-dom": "5.11.9",
"@testing-library/react": "11.2.5",
"@testing-library/user-event": "12.6.3",
"@types/deep-equal": "1.0.1",
"@types/jest": "26.0.20",
"@types/node": "12.19.15",
"@types/prettier": "2.2.3",
"@types/react": "16.14.3",
"@types/react-dom": "16.9.10",
"@types/react-geocode": "0.2.0",
"@types/react-redux": "7.1.16",
"@types/react-router": "5.1.11",
"@types/react-router-dom": "5.1.7",
"@types/styled-components": "5.1.9",
"@types/uuid": "8.3.3",
"connected-react-router": "6.9.1",
"cordova-clipboard": "1.3.0",
"cordova-plugin-camera": "5.0.2",
"cordova-plugin-firebase": "2.0.5",
"d3": "7.0.0",
"deep-equal": "1.1.1",
"env-cmd": "10.1.0",
"eslint": "7.26.0",
"fake-indexeddb": "3.1.7",
"firebase": "9.5.0",
"formik": "2.2.9",
"generate-avatar": "1.4.10",
"hash-wasm": "4.9.0",
"history": "4.0.0",
"husky": "6.0.0",
"ionicons": "5.4.0",
"lint-staged": "11.0.0",
"prettier": "2.3.0",
"promise-all-settled-polyfill": "0.1.2",
"query-string": "7.0.1",
"react": "17.0.2",
"react-dom": "17.0.2",
"react-error-boundary": "3.1.3",
"react-geocode": "0.2.3",
"react-image-lightbox": "5.1.4",
"react-redux": "7.2.4",
"react-router": "5.2.0",
"react-router-dom": "5.2.0",
"react-scripts": "4.0.3",
"redux": "4.1.0",
"styled-components": "5.3.0",
"typescript": "4.4.4",
"uuid": "8.3.2",
"web-vitals": "0.2.4",
"workbox-background-sync": "5.1.4",
"workbox-broadcast-update": "5.1.4",
"workbox-cacheable-response": "5.1.4",
"workbox-core": "5.1.4",
"workbox-expiration": "5.1.4",
"workbox-google-analytics": "5.1.4",
"workbox-navigation-preload": "5.1.4",
"workbox-precaching": "5.1.4",
"workbox-range-requests": "5.1.4",
"workbox-routing": "5.1.4",
"workbox-strategies": "5.1.4",
"workbox-streams": "5.1.4"
```

**Comment by ptmkenny** [comment] 2021-12-25 11:42
Getting the same issue in a similar configuration:

```
Ionic:

   Ionic CLI       : 6.18.1
   Ionic Framework : @ionic/react 6.0.1

Capacitor:

   Capacitor CLI      : 3.3.3
   @capacitor/android : 3.3.3
   @capacitor/core    : 3.3.3
   @capacitor/ios     : 3.3.3

Utility:

   cordova-res : 0.15.4
   native-run  : 1.5.0

System:

   NodeJS : v16.13.1 (/usr/bin/node)
   npm    : 8.1.2
   OS     : Linux 5.10

```

**Comment by adamklein** [comment] 2022-01-01 16:02
Same here.

**Comment by eidng8** [comment] 2022-01-02 17:13
Ionic:

   Ionic CLI       : 6.18.1 (C:\Users\JC\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/vue 6.0.1

Capacitor:

   Capacitor CLI      : 3.3.3
   @capacitor/android : 3.3.3
   @capacitor/core    : 3.3.3
   @capacitor/ios     : 3.3.3

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v16.13.1 (C:\Program Files\nodejs\node.exe)
   npm    : 8.3.0
   OS     : Windows 10

----------------------------------------------------------
Same here

**Comment by eidng8** [comment] 2022-01-03 07:55
`ion-icon` inside `ion-button` in `ion-header` also throws this error

**Comment by inspire22** [comment] 2022-01-03 23:04
I'm not using any ion-icons (could never get them to work) but I am using ion-refresher.

When I get this error it also prevents swiping ion-split-pane windows open to the right or left (they still open when the button is pressed manually).

**Comment by boboldehampsink** [comment] 2022-01-04 09:05
@inspire22 I use ion-refresher too. I read the refresher docs again, looking for something i might've missed since upgrading to ionic 6, and found that pulling-icon is now required on ion-refresher-content (https://ionicframework.com/docs/api/refresher#ios-usage)

When specifying that, the error disappears!

**Comment by inspire22** [comment] 2022-01-04 19:09
@boboldehampsink  thanks!  I had two of the errors, and now one is gone.  It's frustrating the chrome devtools don't show a traceback to what might be causing the second ionicons baseurl error.  My left & right split pane swiping is still broken too (and fixed when I remove ion-refresher)

**Comment by eidng8** [comment] 2022-01-05 01:12
I've done a little digging, it seems `plt.$resourcesUrl$` isn't populated before calling `getAssetPath()` in ion-icon. Neither the statement in `bootstrapLazy()` nor the `setAssetPath()` was run before hitting the rendering icons.

However, built-in components don't use these? (break points didn't fire)

**Comment by liamdebeasi** [comment] 2022-01-05 16:06
Thanks for the issue. Can you please reproduce this in a GitHub repo and provide a link to it?

**Comment by wsamoht** [comment] 2022-01-05 16:26
> @inspire22 I use ion-refresher too. I read the refresher docs again, looking for something i might've missed since upgrading to ionic 6, and found that pulling-icon is now required on ion-refresher-content (https://ionicframework.com/docs/api/refresher#ios-usage)
> 
> When specifying that, the error disappears!

Setting it for me also removed the error; however, the documentation says it is suppose to default to `lines` for iOS and `crescent` for Android so I would still say its a bug.

I'll create a repo with the issue reproduced.

**Comment by wsamoht** [comment] 2022-01-05 16:44
Here is a repo that reproduces the error. It only happens for iOS.

https://github.com/wsamoht/ionic-refresher-icon-type-error

**Comment by PxReaz** [comment] 2022-01-06 12:23
Hi, I have the same error when trying to add icon before label in IonMenu > IonItem ? Is this issue related ? Is there any temporary fix?
I'm using ionic react v6 and ionicons v5.5.4

**Comment by wsamoht** [comment] 2022-01-06 19:04
A temp fix in Vue I did was create a custom refresh component to set the `pulling-icon` if `ios`. If the `pulling-icon` is set for Android, it still works but acts differently when not present.

```javascript
// ContentRefresher.vue

<template>
    <IonRefresher slot="fixed" @ion-refresh="$emit('onRefresh', $event)">
        <IonRefresherContent v-if="isPlatform('ios')" pulling-icon="lines" />
        <IonRefresherContent v-else />
    </IonRefresher>
</template>

<script lang="ts">
import { defineComponent } from 'vue'
import { IonRefresher, IonRefresherContent, isPlatform, RefresherCustomEvent } from '@ionic/vue'

export default defineComponent({
    name: 'ContentRefresher',
    components: {
        IonRefresher,
        IonRefresherContent,
    },
    emits: {
        // eslint-disable-next-line @typescript-eslint/no-unused-vars
        onRefresh(payload: RefresherCustomEvent) {
            return true
        },
    },
    setup() {
        return {
            isPlatform,
        }
    },
})
</script>
```

```javascript
// Implemented

<template>
    <IonPage>
        <IonHeader class="text-center bg-primary-contrast">
            <IonToolbar mode="md">
                <IonTitle>Community</IonTitle>
            </IonToolbar>
        </IonHeader>
        <IonContent>
            <ContentRefresher @on-refresh="handleRefreshCommunities($event)" />
            <!-- Some stuff -->
        </IonContent>
    </IonPage>
</template>

<script lang="ts">
import { defineComponent } from 'vue'
import { RefresherCustomEvent } from '@ionic/vue'
import ContentRefresher from '@/components/shared/ContentRefresher.vue'

export default defineComponent({
    name: 'CommunityTab',
    components: {
        ContentRefresher,
    },
    methods: {
        async handleRefreshCommunities(event: RefresherCustomEvent): Promise<void> {
            // Do stuff

            event.detail.complete()
        },
    },
})
</script>
```

**Comment by inspire22** [comment] 2022-01-06 19:07
Not sure if anyone else is using ion-split-view and ion-menu's with swipeGesture, but these are also broken for me when using ion-refresher with the ionic 6 update.  I'm not sure if it's related to the icon bug or is something else.  I'll have more time in a week or two to make an example project, but wanted to mention it in case anyone else is struggling with it.

**Comment by liamdebeasi** [comment] 2022-01-06 19:13
This line looks to be the culprit: https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/refresher-content/refresher-content.tsx#L54

With lazy loaded components, the base URL you are seeing is set by Stencil automatically. When using non-lazy loaded components, the base URL is not set, leading to this error.

I will get this prioritized with the team and post here when I more to share. Thanks!

**Comment by liamdebeasi** [comment] 2022-01-06 21:06
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/24525, and a fix will be available in an upcoming release of Ionic Framework.

**Closed** 2022-01-06 21:06 UTC
Labels: package: core, type: bug
