### ISSUE TITLE
bug: Side Menu (IonMenu) does not close on samsung note8 (Android version 9)

### ISSUE THREAD

**Issue by konstantsolutions** [ionic-team/ionic-framework#19354] opened 2019-09-16 09:29 UTC
I am using IONIC4 for android application. I am creating android build for Android platform 7.1.4 & 8.0. 
The sideMenu navigation open when click but it not close itself when i click on any menu item.
I checked on other device the sidemenu is working but it is not work proper on note8 with android version 9.
Please provide solution ASAP.

Thanks.
Nirmal Sharma
nirmal.sharma@konstantinfosolutions.com

# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment] 2019-09-16 13:03
Thanks for the issue. Can you please fill out the template? It would be great if you could provide the result of running `ionic info` in your app's directory.

**Comment by tricki** [comment] 2019-09-19 16:38
This could be caused by [a bug I reported](https://github.com/ionic-team/ionic/issues/19376) which caused script errors that made the app unusable.

Try the newest build (see linked issue) and see if it works.

**Comment by ASHBAW** [comment] 2019-10-22 17:19
We are also seeing this issue on certain Android devices. We have not seen the issue on iOS devices.

Here is a code snippet:

```
<ion-menu side="start" menuId="first" [disabled]="onConnectionPage === true" [swipeGesture]="false">
    <ion-header>
      <ion-toolbar>
        <ion-title (click)="defaultSettings()" style="font-size:16px;">ChargerConnect</ion-title>
      </ion-toolbar>
    </ion-header>
    <ion-content>
      <ion-list lines="none">
        <ion-menu-toggle>
          <ion-button (click)="disconnect()" color="primary" expand="full">
            {{ 'Disconnect' | translate }}
          </ion-button>
    
          <ion-button (click)="openPage(pages[0])" style="--background:var(--dashboard)" expand="full">
            {{ dashboardString }}
          </ion-button>
  
          <ion-button (click)="openPage(pages[1])" style="--background:var(--diagnostic)" expand="full">
            {{ diagnosticsString }}
          </ion-button>

          <ion-button (click)="openPage(pages[2])" [disabled]="disableMenuOptions" style="--background:var(--history)" expand="full">
            {{ historyString }}
          </ion-button>
  
          <ion-button (click)="openPage(pages[3])" style="--background:var(--system-information)" expand="full">
            {{ systemInformationString }}
          </ion-button>

          <ion-button (click)="openPage(pages[4])" [disabled]="disableMenuOptions" style="--background:var(--system-profile)" expand="full">
            {{ systemProfileString }}
          </ion-button>

          <ion-button (click)="openPage(pages[5])" [disabled]="disableMenuOptions" style="--background:var(--battery-profile)"  expand="full">
            {{ batteryProfileString }}
          </ion-button>

          <ion-button (click)="openHelp()" expand="full">
            {{ 'Help' | translate }}
          </ion-button>
        </ion-menu-toggle>
      </ion-list>
    </ion-content>
  </ion-menu>
```

Below is my ionic info:

  ```
 Ionic CLI                     : 5.4.4 (/Users/temp/.nvm/versions/node/v11.12.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.9.0
   @angular-devkit/build-angular : 0.802.2
   @angular-devkit/schematics    : 8.3.3
   @angular/cli                  : 8.3.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0
   Cordova Platforms : android 8.1.0, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.1, (and 10 other plugins)

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.1
   NodeJS     : v11.12.0 (/Users/temp/.nvm/versions/node/v11.12.0/bin/node)
   npm        : 6.11.3
   OS         : macOS Mojave
   Xcode      : Xcode 11.1 Build version 11A1027
```

**Comment by liamdebeasi** [comment] 2019-10-22 17:44
Can you try this again on the latest version of Ionic? (v4.11.2)

**Comment by ASHBAW** [comment] 2019-10-22 17:47
Trying that now. I will let you know. Thanks

**Comment by proemke** [comment] 2019-10-22 21:33
Can you also try this:

```javascript
<ion-menu-toggle menu="first" autoHide="false">
```

**Comment by pjc2007** [comment] 2019-10-23 02:33
I had this problem. I updated to Ionic 4.11.2 but still did not work.

I then added the `menu="first"` as suggested above (I already had the autoHide="false"), and this seems to have fixed it for me.

**Comment by ASHBAW** [comment] 2019-10-28 13:48
I had a customer with a Pixel running Android 10 try a version of our app where I updated:

`<ion-menu-toggle menu="first" autoHide="false">`

and updated to:

`"@ionic/angular": "^4.11.2"`

The customer is still seeing the issue.

Any other potential fixes on this?

**Comment by liamdebeasi** [comment] 2019-10-28 13:53
Can you provide the code required to reproduce this issue? I am unable to reproduce the issue.

**Comment by ASHBAW** [comment] 2019-10-28 14:06
The issue has been reported to us by 4 different customers now. I unfortunately have not been able to duplicate the issue myself on the devices I have on hand to test it out. 

Below is my app.component.html:

```
<ion-app>

<ion-menu side="start" menuId="first" [disabled]="onConnectionPage === true" [swipeGesture]="false">
    <ion-header>
      <ion-toolbar>
        <ion-title (click)="defaultSettings()" style="font-size:16px;">ChargerConnect</ion-title>
      </ion-toolbar>
    </ion-header>
    <ion-content>
      <ion-list lines="none">
        **<ion-menu-toggle menu="first" autoHide="false">**
          <ion-button (click)="disconnect()" color="primary" expand="full">
            {{ 'Disconnect' | translate }}
          </ion-button>

          <!--
            <ion-item [routerLink]="pages[0].url" routerDirection="root" [class.active-item]="selectedPath === pages[0].url">
                {{ dashboardString }}
            </ion-item>
            -->
    
          <ion-button (click)="openPage(pages[0])" style="--background:var(--dashboard)" expand="full">
            {{ dashboardString }}
          </ion-button>
  
          <ion-button (click)="openPage(pages[1])" style="--background:var(--diagnostic)" expand="full">
            {{ diagnosticsString }}
          </ion-button>

          <ion-button (click)="openPage(pages[2])" [disabled]="disableMenuOptions" style="--background:var(--history)" expand="full">
            {{ historyString }}
          </ion-button>
  
          <ion-button (click)="openPage(pages[3])" style="--background:var(--system-information)" expand="full">
            {{ systemInformationString }}
          </ion-button>

          <ion-button (click)="openPage(pages[4])" [disabled]="disableMenuOptions" style="--background:var(--system-profile)" expand="full">
            {{ systemProfileString }}
          </ion-button>

          <ion-button (click)="openPage(pages[5])" [disabled]="disableMenuOptions" style="--background:var(--battery-profile)"  expand="full">
            {{ batteryProfileString }}
          </ion-button>

          <ion-button (click)="openHelp()" expand="full">
            {{ 'Help' | translate }}
          </ion-button>
        </ion-menu-toggle>
      </ion-list>
    </ion-content>
  </ion-menu>
  <ion-router-outlet main></ion-router-outlet>
</ion-app>
```
This is my ionic info:
```
Ionic:

   Ionic CLI                     : 5.4.4 (/Users/lester2/.nvm/versions/node/v12.6.0/lib/node_modules/ionic)
   **Ionic Framework               : @ionic/angular 4.11.2**
   @angular-devkit/build-angular : 0.802.2
   @angular-devkit/schematics    : 8.3.3
   @angular/cli                  : 8.3.3
   @ionic/angular-toolkit        : 2.1.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.1, (and 10 other plugins)

Utility:

   cordova-res : 0.6.0 (update available: 0.8.1)
   native-run  : 0.2.8 (update available: 0.2.9)

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.1
   NodeJS     : v12.6.0 (/Users/lester2/.nvm/versions/node/v12.6.0/bin/node)
   npm        : 6.11.3
   OS         : macOS Mojave
   Xcode      : Xcode 11.1 Build version 11A1027
```


Even though I am using <ion-menu-toggle> would it hurt or could it potential help by calling
 menu close with the MenuController on my openPage button click?

**Comment by liamdebeasi** [comment] 2019-10-28 14:12
Can you provide a complete code reproduction? I am still unable to reproduce the issue. When navigating to a page from a side menu, the menu closes as expected.

**Comment by ASHBAW** [comment] 2019-10-28 14:29
I actually can't reproduce the issue myself with devices we have on hand with our app. It is just a number of customers who have found the issue who I have been trying to work with. 

I have created a new side menu starter app that I will try to get one of the customers experiencing the issue to try out. I will also see what I can do about getting you access to our app.

**Comment by ASHBAW** [comment] 2019-10-31 19:15
I am trying to work with a customer seeing the issue. I created a new side menu starter app.

I notice in the package.json that a number of the modules are out of date:

```
  "dependencies": {
    "@angular/common": "~8.1.2",
    "@angular/compiler": "~8.1.2",
    "@angular/core": "~8.1.2",
    "@angular/forms": "~8.1.2",
    "@angular/platform-browser": "~8.1.2",
    "@angular/platform-browser-dynamic": "~8.1.2",
    "@angular/router": "~8.1.2",
    "@ionic-native/core": "^5.0.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic/angular": "^4.7.1",
    "core-js": "^2.5.4",
    "rxjs": "~6.5.1",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"
  },
```
Why are these starter ionic projects not using the latest modules?

For example @ionic/angular the latest version is 4.11.3, @ionic-native/core is 5.16.0.

Are we not suppose to be using the latest versions of for example @ionic/angular?

Could that be causing the issue I am seeing?

**Comment by liamdebeasi** [comment] 2019-10-31 19:18
`@ionic/angular@4.11.3` is the latest version. `@ionic-native/core` is separate (wrappers for native Cordova plugins).

**Comment by ASHBAW** [comment] 2019-10-31 19:25
Got it thank you.

**Comment by ASHBAW** [comment] 2019-11-04 13:36
Well, I redid how the side menu worked so that it was same as the ionic 4 side menu starter project and this fixed the issue. What I was doing before with the menu was :

```
  <ion-button (click)="openPage(pages[5])" [disabled]="disableMenuOptions" style="--background:var(--battery-profile)"  expand="full">
            {{ batteryProfileString }}
          </ion-button>
```
Where the click event method would perform some action **prior** to utilizing the router to route to the new page.

Now this is done via routerLink. 

```
         <ion-item [disabled]="disableMenuOptions" [routerDirection]="'root'" [routerLink]="[pages[5].url]">
              <ion-label>
                  {{ batteryProfileString }}
              </ion-label>
            </ion-item>
```

Not sure why my previous implementation does not work on some select devices (it worked in my Ionic 3 implementation for over a year now). but for now I am going with the routerLink approach.

**Comment by liamdebeasi** [comment] 2019-11-06 14:06
Ok glad it's working now. Are you able to post the code for `openPage`?

**Comment by ASHBAW** [comment] 2019-11-06 15:24
Yes here it is. Basically I was styling the buttons in the menu prior to routing to the selected page via the router.navigate(). 

```
openPage(page) {
    switch (page.title) {
      case this.dashboardString:
        document.body.style.setProperty('--dashboard', '#33cd5f');
        document.body.style.setProperty('--diagnostic', '#989aa2');
        document.body.style.setProperty('--history', '#989aa2');
        document.body.style.setProperty('--system-information', '#989aa2');
        document.body.style.setProperty('--system-profile', '#989aa2');
        document.body.style.setProperty('--battery-profile', '#989aa2');
        break;
      case this.diagnosticsString:
        document.body.style.setProperty('--dashboard', '#989aa2');
        document.body.style.setProperty('--diagnostic', '#33cd5f');
        document.body.style.setProperty('--history', '#989aa2');
        document.body.style.setProperty('--system-information', '#989aa2');
        document.body.style.setProperty('--system-profile', '#989aa2');
        document.body.style.setProperty('--battery-profile', '#989aa2');
        break;
      case this.historyString:
        document.body.style.setProperty('--dashboard', '#989aa2');
        document.body.style.setProperty('--diagnostic', '#989aa2');
        document.body.style.setProperty('--history', '#33cd5f');
        document.body.style.setProperty('--system-information', '#989aa2');
        document.body.style.setProperty('--system-profile', '#989aa2');
        document.body.style.setProperty('--battery-profile', '#989aa2');
        break;
      case this.systemInformationString:
        document.body.style.setProperty('--dashboard', '#989aa2');
        document.body.style.setProperty('--diagnostic', '#989aa2');
        document.body.style.setProperty('--history', '#989aa2');
        document.body.style.setProperty('--system-information', '#33cd5f');
        document.body.style.setProperty('--system-profile', '#989aa2');
        document.body.style.setProperty('--battery-profile', '#989aa2');
        break;
      case this.systemProfileString:
        document.body.style.setProperty('--dashboard', '#989aa2');
        document.body.style.setProperty('--diagnostic', '#989aa2');
        document.body.style.setProperty('--history', '#989aa2');
        document.body.style.setProperty('--system-information', '#989aa2');
        document.body.style.setProperty('--system-profile', '#33cd5f');
        document.body.style.setProperty('--battery-profile', '#989aa2');
        break;
      case this.batteryProfileString:
        document.body.style.setProperty('--dashboard', '#989aa2');
        document.body.style.setProperty('--diagnostic', '#989aa2');
        document.body.style.setProperty('--history', '#989aa2');
        document.body.style.setProperty('--system-information', '#989aa2');
        document.body.style.setProperty('--system-profile', '#989aa2');
        document.body.style.setProperty('--battery-profile', '#33cd5f');
        break;

      default:
        document.body.style.setProperty('--dashboard', '#989aa2');
        document.body.style.setProperty('--diagnostic', '#989aa2');
        document.body.style.setProperty('--history', '#989aa2');
        document.body.style.setProperty('--system-information', '#989aa2');
        document.body.style.setProperty('--system-profile', '#989aa2');
        document.body.style.setProperty('--battery-profile', '#989aa2');
    }

    this.zone.run(() => {
      this.router.navigate([page.url], {replaceUrl: true});
    });
  }
```
In my application I have a disconnect button that is part of the side menu (app is connected via bluetooth to another device). I use ngrx for storing state.

This is how I was disconnecting before - when selecting the disconnect in the side menu. I wanted the state information updated **prior** to transitioning to the proper page. This will not work on some of our customer's Android devices - get the issue where the side menu does not close.

```
  <ion-menu-toggle menu="first" autoHide="false">
          <ion-button (click)="disconnect()" color="primary" expand="full">
            {{ 'Disconnect' | translate }}
          </ion-button>
  ...

  disconnect() {
    this.store.dispatch(ConnectionDisconnectAction());

    this.zone.run(() => {
      this.router.navigate(['/connection'], {replaceUrl: true});
    });
}
```
Now I have to do the following:

```
  <ion-button (click)="disconnect()" [routerDirection]="'root'" [routerLink]="[pages[6].url]" color="primary" expand="full">
                {{ 'Disconnect' | translate }}
  </ion-button>

  disconnect() {
    this.store.dispatch(ConnectionDisconnectAction());
 }
```
This fixes the issue on those Android devices having the issue with the side menu not closing (i.e. using routerLink instead of router.navigate) but it causing a race condition on iOS devices where the route on disconnect occurs prior to the state being updated. So now I have to build my app separately for Android and iOS.

Not sure why using router.navigate would not work? Again I have used this code base since Ionic 3 was released and have not had any issues until now.

**Comment by mluis** [comment] 2019-11-12 11:39
Having the same issue on 2 different devices Android 7 and Android 9 ... How do one solve the issue?

**Comment by mluis** [comment] 2019-11-12 11:51
@liamdebeasi I think you might be able to reproduce the issue with the sample app side-menu on the emulator.

**Comment by ochikov** [comment] 2019-11-15 13:52
Reproduced on Nexus 5X (Android 10)
![Screen Shot 2019-11-15 at 15 52 05](https://user-images.githubusercontent.com/13587218/68948161-ef1ca000-07bf-11ea-915d-344ce8917326.png)

**Comment by konstantsolutions** [comment] 2019-11-15 14:05
Please check with latest ionic sidemenu sample. It is working there.

Today i got this error. When i checked with latest sidemenu sample, it is working :)

**Comment by ASHBAW** [comment] 2019-11-15 16:17
The side menu project using the following to route to a new page:

`[routerDirection]="'root'" [routerLink]="[url]"`

If you need to do something when a side menu button is pressed **prior** to routing to another page via a click event like the following:

```
<ion-button (click)="openPage(pages[0])"expand="full">
      {{ menu1String }}
</ion-button>

openPage(page) {
    // do somethings
    this.zone.run(() => {
      this.router.navigate([page.url], {replaceUrl: true});
    });
}
```
you will still see the issue on some devices

**Comment by jdnichollsc** [comment] 2019-12-18 03:12
I'm reproducing an issue that the main menu is not closing from browser when I import a Stencil Web Component using Ionic styles and core package from that component, using this configuration https://github.com/proyecto26/stencil-ionic-components/tree/master/src/global
I'm tring to close the menu from my login screen of Ionic 4 with this code:
```
ionViewWillEnter() {
  this.menuController.close();
  this.menuController.enable(false);
  this.menuController.swipeEnable(false);
}
```

Let me know what you think guys!

**Comment by liamdebeasi** [comment] 2020-06-29 20:53
Thanks for the issue. Is this still an issue with the latest version of Ionic Framework? If so, please provide a repo with the code required to reproduce this issue.

**Closed** 2020-07-13 20:59 UTC
Labels: needs: reply
