### ISSUE TITLE
bug: ion-datetime defaults to May 2021 instead of current month in calendar view if date is undefined

### ISSUE THREAD

**Issue by kygoh** [ionic-team/ionic-framework#28247] opened 2023-09-27 17:29 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

If `value` in the following html fragment is undefined or '', the calendar view defaults to May 2021:

```html
  <ion-popover trigger="open-modal" show-backdrop="false" side="right" id="popover-bottom">
    <ng-template>
      <ion-content>
        <ion-datetime
          #datetime
          size="cover"
          presentation="date"
          [max]="maxDate"
          showClearButton="true"
          showDefaultButtons="true"
          (ionChange)="onDatetimeChange($event)"
          [(ngModel)]="value"
        ></ion-datetime>
      </ion-content>
    </ng-template>
  </ion-popover>
```

### Expected Behavior

In v6.x, the calendar view defaults to current month.

### Steps to Reproduce

1. open the calendar view for the first time
2. ion-datetime component shows May 2021 in calendar view
3. console shows `[Ionic Warning]: Unable to parse date string: . Please provide a valid ISO 8601 datetime string.`

### Code Reproduction URL

https://github.com/kygoh/ionic7-blank-datetime-test

### Ionic Info

```
[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package.json'
       
       Require stack:
       - /usr/local/lib/node_modules/@ionic/cli/lib/project/index.js
       - /usr/local/lib/node_modules/@ionic/cli/lib/index.js
       - /usr/local/lib/node_modules/@ionic/cli/index.js
       - /usr/local/lib/node_modules/@ionic/cli/bin/ionic
[WARN] Error loading @capacitor/android package.json: Error: Cannot find module '@capacitor/android/package.json'
       
       Require stack:
       - /usr/local/lib/node_modules/@ionic/cli/lib/project/index.js
       - /usr/local/lib/node_modules/@ionic/cli/lib/index.js
       - /usr/local/lib/node_modules/@ionic/cli/index.js
       - /usr/local/lib/node_modules/@ionic/cli/bin/ionic

Ionic:

   Ionic CLI                     : 7.1.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.4.2
   @angular-devkit/build-angular : 16.2.3
   @angular-devkit/schematics    : 16.2.3
   @angular/cli                  : 16.2.3
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.4.1
   @capacitor/android : not installed
   @capacitor/core    : 5.4.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.3

System:

   NodeJS : v18.18.0 (/usr/local/bin/node)
   npm    : 9.8.1
   OS     : Linux 5.15
```

### Additional Information

stack trace from console:

```
[Ionic Warning]: Unable to parse date string: . Please provide a valid ISO 8601 datetime string.
printIonWarning  @  vendor.js:4740
parseDate  @  default-node_modules…sm_th-b84f04.js:264
Datetime.processValue  @  node_modules_ionic_c…e_3_entry_js.js:941
componentWillLoad  @  node_modules_ionic_c…_3_entry_js.js:1446
safeCall  @  vendor.js:4059
dispatchHooks  @  vendor.js:3858
dispatch  @  vendor.js:3815
consume  @  vendor.js:4688
flush  @  vendor.js:4702
```

Similar to:
* https://github.com/ionic-team/ionic-framework/issues/26170?

**Comment by liamdebeasi** [comment] 2023-09-27 20:49
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. As per the [Ionic 7 Breaking Changes Guide](https://github.com/ionic-team/ionic-framework/blob/main/BREAKING.md#datetime) passing an empty string to the `value` property will fail as it is not a valid ISO-8601 value.

Passing an empty string defaulted to the current date in Ionic 6 due to some technical debt we had internally where `null` was converted to the empty string in Ionic Angular. However, this was [resolved](https://github.com/ionic-team/ionic-framework/commit/ce2e37b1a172722630953dcb9560f334048c5b72) in Ionic 7. The current behavior aligns with the browser behavior where passing `new Date('')` results in `Invalid Date`.

**Closed by liamdebeasi** 2023-09-27 20:49 UTC
Labels: triage

**Comment by kygoh** [comment] 2023-09-27 21:24
If that's the case then Ionic 7 should remove the clear button from ion-datetime because `new Date(undefined)` results in `Invalid Date` as well. As of v7.4.2 I can click on Clear and Done button to get `undefined` from the component:

https://github.com/ionic-team/ionic-framework/blob/355d95d4d8454314d223ff4e2d5a39a007fd5da7/core/src/components/datetime/datetime.tsx#L502

https://github.com/ionic-team/ionic-framework/blob/355d95d4d8454314d223ff4e2d5a39a007fd5da7/core/src/components/datetime/datetime.tsx#L1422-L1425
