### ISSUE TITLE
bug: Label of checked checkboxes disappear after re-rendering

### ISSUE THREAD

**Issue by alexdabast** [ionic-team/ionic-framework#27152] opened 2023-04-10 14:37 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When you refresh (re-render) a checked checkbox with the new syntax for the label.
The label is no longer visible

### Expected Behavior

After a re-rendering of a checkbox the label should still be visible

### Steps to Reproduce

1. Press the show/hide button on the stackblitz
2. https://stackblitz.com/edit/angular-otdev1?file=src/app/example.component.html

### Code Reproduction URL

https://stackblitz.com/edit/angular-otdev1?file=src/app/example.component.html

### Ionic Info

Ionic:

   Ionic CLI : 7.0.1

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v16.19.1
   npm    : 8.19.3
   OS     : macOS Monterey

**Comment by liamdebeasi** [comment] 2023-04-10 15:25
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/27085. (Same underlying bug)

**Closed by liamdebeasi** 2023-04-10 15:25 UTC
Labels: triage
