### ISSUE TITLE
bug: ion-back-button component doesn't pop entries off the window.history stack

### ISSUE THREAD

**Issue by moose4lord** [ionic-team/ionic-framework#28973] opened 2024-02-04 14:55 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When implementing the ion-back-button component to navigate to the previous page, it doesn't pop the most recent entry off the browser's window.history stack. Instead it navigates back, but adds a new entry to the stack. This causes the ion-back-button and browser back button to get out of sync.

### Expected Behavior

Would expect ion-back-button to pop the history stack.

### Steps to Reproduce

In the sidebar example app, add code to include ion-back-button and monitor the window.history length.
In folder.page.ts, add ion-back-button and  a historyLength variable and ionViewWillEnter() function to folder.page.ts:
```
import { Component, inject, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { IonHeader, IonToolbar, IonButtons, IonMenuButton, IonTitle, IonContent, IonBackButton } from '@ionic/angular/standalone';  // include ionBackButton

@Component({
  selector: 'app-folder',
  templateUrl: './folder.page.html',
  styleUrls: ['./folder.page.scss'],
  standalone: true,
  imports: [IonHeader, IonToolbar, IonButtons, IonMenuButton, IonTitle, IonContent, IonBackButton],  // include ionBackButton
})
export class FolderPage implements OnInit {
  public folder!: string;
  private activatedRoute = inject(ActivatedRoute);
  public historyLength: number = window.history.length;  // create historyLength variable
  constructor() {}

  ngOnInit() {
    this.folder = this.activatedRoute.snapshot.paramMap.get('id') as string;
  }

  ionViewWillEnter() {
    this.historyLength = window.history.length;  // update historyLength variable
  }
}
```

Add code to folder.page.html to display historyLength:
```
 <ion-header [translucent]="true">
  <ion-toolbar>
    <ion-buttons slot="start">
      <ion-menu-button></ion-menu-button>
      <ion-back-button></ion-back-button>  <!-- include ion-back-button -->
    </ion-buttons>
    <ion-title>{{ folder }}</ion-title>
  </ion-toolbar>
</ion-header>

<ion-content [fullscreen]="true">
  <ion-header collapse="condense">
    <ion-toolbar>
      <ion-title size="large">{{ folder }}</ion-title>
    </ion-toolbar>
  </ion-header>

  <div id="container">
    <strong class="capitalize">{{ folder }}</strong>
    <p>Explore <a target="_blank" rel="noopener noreferrer" href="https://ionicframework.com/docs/components">UI Components</a></p>
    <p>window.history.length: {{ historyLength }}</p>  <!-- display window.history.length -->
  </div>
</ion-content>
```
Run "ionic serve" to start the app, then click on a few folders in the left sidebar (the window.history count should increment with each click). Now click the ion-back-button icon to navigate backwards (the window.history counter STILL increments as new pages are added to window.history). After returning to the original home page, click the browser back button and you'll walk back the window.history stack (you won't see the history counter decrement, because apparently the browser back button doesn't trigger the ionViewWillEnter life cycle event).

### Code Reproduction URL

[https://github.com/moose4lord/myApp.git](https://github.com/moose4lord/myApp.git)

### Ionic Info

Ionic:

   Ionic CLI                     : 7.2.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.7.0
   @angular-devkit/build-angular : 17.1.2
   @angular-devkit/schematics    : 17.1.2
   @angular/cli                  : 17.1.2
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.6.0
   @capacitor/android : not installed
   @capacitor/core    : 5.6.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 2.0.1

System:

   NodeJS : v20.11.0 (/usr/local/bin/node)
   npm    : 10.2.4
   OS     : macOS Unknown

**Comment by liamdebeasi** [comment] 2024-02-05 14:50
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/23448.

**Closed by liamdebeasi** 2024-02-05 14:50 UTC
Labels: triage
