### ISSUE TITLE
bug: NgxImageViewer on iOS - header and close button doesn't show on iOS - does work on Android

### ISSUE THREAD

**Issue by Luch76** [ionic-team/ionic-framework#21771] opened 2020-07-17 06:10 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

Use the component: https://www.npmjs.com/package/ngx-image-viewer
in an Ionic v5 angular & capacitor app 
The component involves showing a close button when viewing the pictures. On Android, this works fine. But on iOS, the close button and other fields (such as image description) do not show.

**Expected behavior:**

The close button would show on an image, similar to how it show on Android

**Steps to reproduce:**

Run the app, and click one of the images. On iOS, you'll see the close button does not show. On Android, it does show.

**Related code:**
Example app on Github: https://github.com/Luch76/IonicAngularImageFullScreenView.git

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.10.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.2.3
   @angular-devkit/build-angular : 0.901.11
   @angular-devkit/schematics    : 9.1.11
   @angular/cli                  : 9.1.11
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 2.3.0
   @capacitor/core : 2.3.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v13.12.0 (/usr/local/Cellar/node/13.12.0/bin/node)
   npm    : 6.14.6
   OS     : macOS Catalina

```

**Comment by liamdebeasi** [comment] 2020-07-17 13:29
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. We do not manage the ngx-image-viewer component, so if you are running into issues with that I recommend you file an issue with the plugin maintainer. The elements are showing up, they just appear underneath the `ion-header` element. It is possible you will need to show the close button in a different way (or remove the `ion-header`)

**Closed by liamdebeasi** 2020-07-17 13:29 UTC
Labels: triage
