### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by Lechevallier** [ionic-team/ionic-framework#25890] opened 2022-09-07 11:25 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

Popover randomly doesn't get well vertically centred using hook `useIonPopover`.
![popover](https://user-images.githubusercontent.com/10246002/188863803-30c2dd17-6a7e-4063-9a5d-a5fa35f8e326.gif)

### Expected Behavior

Popover should always be perfectly vertically centred by default

### Steps to Reproduce

I reproduced this behaviour in a [sandbox](https://codesandbox.io/embed/ionic-v6-sandbox-forked-sz60jp).
Then just keep on clicking "Click me" to see the popover sometimes well centred, sometimes no.

### Code Reproduction URL

https://codesandbox.io/embed/ionic-v6-sandbox-forked-sz60jp

### Ionic Info

Ionic:

   Ionic CLI       : 6.18.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 6.2.5

Capacitor:

   Capacitor CLI      : 4.1.0
   @capacitor/android : 4.1.0
   @capacitor/core    : 4.1.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.6.0

System:

   NodeJS : v14.15.0 (/usr/local/bin/node)
   npm    : 8.5.2
   OS     : macOS Catalina

### Additional Information

Note that I need to use this hook to present my popover because it's only way I found to pass data to it.
I can't use inline popover in my case.

Inspecting the popover element, it came out that it's the div with class `.popover-content` which gets the styling supposed to center it.
(In my app, my screen is 740x360, and the popover 250x296)
When it goes well, 32px is used, which is (360 - 296) / 2:
```css
top: calc(32px + var(--offset-y, 0px));
left: calc(245px + var(--offset-x, 0px));
transform-origin: left top;
```
When it goes wrong, 180px is used, which is (360 - 0) / 2:
```css
top: calc(180px + var(--offset-y, 0px));
left: calc(245px + var(--offset-x, 0px));
transform-origin: left top;
```
It's like it didn't got time to calculate the popover height 🤔 

This calcul is made by a function called `calculateWindowAdjustment`
https://github.com/ionic-team/ionic-framework/search?q=calculateWindowAdjustment

I didn't get further reading code.

**Comment by liamdebeasi** [comment] 2022-09-07 14:11
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/25337. That issue references using the `trigger` property, but the underlying issue appears to be the same.

**Closed by liamdebeasi** 2022-09-07 14:11 UTC
Labels: triage

**Comment by Lechevallier** [comment] 2022-09-09 09:20
@liamdebeasi Is there a fix planned for the next release? I can't publish my app with this bug...
Any workaround?
