### ISSUE TITLE
bug: Karma incorrectly reports [main] attribute deprecation

### ISSUE THREAD

**Issue by davidgeary** [ionic-team/ionic-framework#24563] opened 2022-01-12 14:06 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

When running the tests on an Ionic 6 application containing an `ion-menu` component, the following warning is sometimes issued, even though the related template does not use a `main` attribute:

``` sh
WARN: '[DEPRECATED][ion-menu] Using the [main] attribute is deprecated, please use the "contentId" property instead:
BEFORE:
  <ion-menu>...</ion-menu>
  <div main>...</div>

AFTER:
  <ion-menu contentId="main-content"></ion-menu>
  <div id="main-content">...</div>
'
```

Sometimes, the tests will also issue the error/warning:

``` sh
ERROR: 'Menu: must have a "content" element to listen for drag events on.'

WARN: 'split pane does not have a specified main node'
```

### Expected Behavior

No warning should be issued.

### Steps to Reproduce

Create a new Ionic starter project containing a menu and then just run the tests, e.g.

``` sh
ionic start foo sidemenu --type=angular --no-git
cd .\foo
ng test
```

### Ionic Info

Ionic:

   Ionic CLI                     : 6.18.1 (C:\Users\David\AppData\Roaming\nvm\v16.13.0\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.0.2
   @angular-devkit/build-angular : 13.1.2
   @angular-devkit/schematics    : 12.0.1
   @angular/cli                  : 13.1.2
   @ionic/angular-toolkit        : 5.0.3

Capacitor:

   Capacitor CLI      : 3.3.4
   @capacitor/android : 3.3.4
   @capacitor/core    : 3.3.4
   @capacitor/ios     : 3.3.4

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v16.13.0 (C:\Program Files\nodejs\node.exe)
   npm    : 8.1.0
   OS     : Windows 10

### Additional Information

This can be reproduced on the most simple example - the default starter project uses the following template but displays the warning:

``` html
<ion-app>
  <ion-split-pane contentId="main-content">
    <ion-menu contentId="main-content" type="overlay">
      <!-- Menu items omitted for brevity... -->
    </ion-menu>
    <ion-router-outlet id="main-content"></ion-router-outlet>
  </ion-split-pane>
</ion-app>
```

According to #20142, the deprecation warnings were removed as part of Ionic Framework v5.  However, this doesn't appear to be the case - see [this line in _menu.tsx_](https://github.com/ionic-team/ionic-framework/blob/223f36f6adacf8adce47cee4809a60c94a9e0efa/core/src/components/menu/menu.tsx#L176).

**Comment by liamdebeasi** [comment] 2022-01-12 15:58
Thanks! The "main attribute is deprecated" message will be removed via https://github.com/ionic-team/ionic-framework/pull/24565. 

The other errors appear to be caused by something separate, so I opened https://github.com/ionic-team/ionic-framework/issues/24566 to continue investigation for that.

**Comment by liamdebeasi** [comment] 2022-01-12 16:52
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/24565, and a fix will be available in an upcoming release of Ionic Framework.

Please follow #24566 for updates on that issue. Thanks!

**Closed** 2022-01-12 16:52 UTC
Labels: package: core, type: bug

**Comment by davidgeary** [comment] 2022-01-12 17:01
@liamdebeasi Thanks for the quick turnaround
