### ISSUE TITLE
bug: ion-popover doesnt have backdrop in tree-shaken build (react & vue)

### ISSUE THREAD

**Issue by JohnDeved** [ionic-team/ionic-framework#24449] opened 2021-12-20 11:08 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

in production, tree-shaken build, (`npm run build && npx serve -s build`) 
popover are not dismissable by clicking on the backdrop. (no backdrop seems to show up)
its also possible to scroll while the popup is open.
I noticed this behavior when upgrading from v5 to v6

https://user-images.githubusercontent.com/24187269/146756242-067557e2-17e2-4596-8375-f79e56709606.mov

hosted production build: https://8179360d.ionic-popover-bug.pages.dev/

### Expected Behavior

the backdrop should show up and it should be dismissable by clicking on it.
it also shouldn't be possible to scroll away while the popover is open.
interestingly enough everything seems to work fine in dev mode (`npm start`)

https://user-images.githubusercontent.com/24187269/146757472-e6def746-9153-4377-9e10-ba1b37485a84.mov

### Steps to Reproduce

The only step to reproduce is to use popover in any way with react ionic and build to production.
just clone reproduction repo and create and serve a production build to encounter the issues.

### Code Reproduction URL

https://github.com/JohnDeved/ionic-popover-bug

### Ionic Info

```
Ionic:

   Ionic CLI       : 5.4.16 (/Users/undefined/.npm/_npx/864a9e3c2cd0cf50/node_modules/ionic)
   Ionic Framework : @ionic/react 6.0.1

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v16.13.1 (/Users/undefined/.nvm/versions/node/v16.13.1/bin/node)
   npm    : 8.1.2
   OS     : macOS Big Sur
```

**Comment by sean-perkins** [comment] 2021-12-20 15:27
I believe this is a result of nested custom elements not being defined in overlays. This has been resolved here #24439 and will be available in the next release of Ionic.

You can use the dev build to verify this resolves your issue:
```bash
npm install @ionic/core@6.0.0-dev.1639604950.5995f29
```

**Comment by sean-perkins** [comment] 2021-12-20 19:05
Looks like this is a _similar_ issue, but not resolved with the mentioned PR. I'll track this as a bug in v6. 

The ion-backdrop custom element isn't being defined with the production build.

**Comment by sean-perkins** [comment] 2021-12-20 20:35
Hello @JohnDeved thanks for the issue! I have an open PR that addresses the issue.

The resolution affects both `ion-modal` and `ion-popover`; as inline overlay components were not defining their children custom elements in tree-shaken builds.

The Core team is mostly out on vacation/holidays for the remainder of the year and we won't be pushing a new release of Ionic until after the new year. 

I've created a dev build if you'd like to confirm in your own projects:

```bash
npm install @ionic/react@6.0.1-dev.1640031995.c1d4978
```

I appreciate the reproduction application and notes; they were super helpful debugging the issue!

**Comment by JohnDeved** [comment] 2021-12-20 21:24
@sean-perkins thank you so much for takeling, very quick and good work 👍

**Comment by halykon** [comment] 2021-12-21 13:23
Hey @sean-perkins, I tried using the development build you provided, but it seems like I'm running into another error:
![image](https://user-images.githubusercontent.com/37235804/146936236-67fd98f9-31bd-44aa-a9a6-f56ee5274197.png)

I've updated @JohnDeved's repo to use the dev build you provided. Also, https://6b1da293.ionic-popover-bug.pages.dev/ is a preview build (The actual error is only visible while running on the dev server though).

**Comment by meddario** [comment] 2021-12-30 21:59
Hi, the same also seems to happen with the vue.js version, `"@ionic/vue": "^6.0.0",` (actual version `6.0.1`). Popovers have no backdrop with the production build.

**Comment by meddario** [comment] 2022-01-01 18:27
Here  a reproducer for the vue.js version. The README.md contains the instructions to reproduce the problem.

Let me kwow if I need to open a separate issue
[ionic-vue-popover-backdrop.zip](https://github.com/ionic-team/ionic-framework/files/7798072/ionic-vue-popover-backdrop.zip)
.

**Closed** 2022-01-07 18:21 UTC
Labels: package: react, type: bug, v6
