### ISSUE TITLE
feat: being able to detachComponent manually (when optimizing modal loading)

### ISSUE THREAD

**Issue by sneko** [ionic-team/ionic-framework#18890] opened 2019-07-25 12:05 UTC
Hi everyone,

I'm currently using Ionic 4 with Vue.js and I followed examples where people `create()` and `present()` the modal when the user clicks.

But in my case it was taking sometimes 1 second to appear since the `create()` call was loading Vue component...

The workaround I made is, when arriving on a View component, I create all modals and popovers the user is able to click. And when the user clicks one of them, I just call `present()`. Like that it's pretty efficient and immediate.

My main concern when leaving my view, I would like to clean those prepared modals/popovers created in the DOM.

I tried to force the `dismiss()` but it doesn't remove the DOM. It seems linked to this condition:
https://github.com/ionic-team/ionic/blob/master/core/src/components/modal/modal.tsx#L168-L170

What do you think about removing this condition to always remove what's in the DOM?

Otherwise, could you please expose a method `destroy()` that use `detachComponent()`?

Thank you,

**Comment by liamdebeasi** [comment] 2019-07-25 13:03
Thanks for the feature request. Can you provide a code example of how you are creating modals? Modals should be removed from the DOM by default when dismissing.

**Comment by sneko** [comment] 2019-07-25 13:09
Hi @liamdebeasi,

```
  // Clean memory
  public beforeDestroy() {
    if (this.donateModal) {
      this.donateModal.dismiss()
    }
  }

  // Show the modal
  public showDonate() {
    if (this.donateModal) {
      this.donateModal.present();
    }
  }

  // Prepare the modal to be shown without delay
  protected async prepareDonateModal() {
    const modal = await this.$ionic.modalController.create({
      component: Donate,
      ...
    });

    // Since modal cannot be reused, we prepare a new one directly after the previous one being dismissed
    modal.onWillDismiss().then(this.prepareDonateModal);

    this.donateModal = modal;
  }
```
(when the current component is created I call `this.prepareDonateModal()` to prepare the modal).

About what you said, I guess, since I never `present()` the modal once, the modal is unable to be dismissed while detaching the component.

Or maybe I'm doing something wrong :/

**Comment by sneko** [comment] 2019-07-29 14:27
@liamdebeasi do you see a better solution I could use?

**Comment by liamdebeasi** [comment] 2019-08-01 13:29
Thanks for the follow up. Can you try `npm i @ionic/vue@next`? I am seeing the modal get removed from the DOM in that build.

**Comment by sneko** [comment] 2019-08-01 14:40
Hi @liamdebeasi , I'm using vue@next (v0.0.9) and my problem is still there.

You said `the modal get removed from the DOM`, could you confirm please you have created the modal, and then you called `dismiss()` without calling `present()` just before?

**Comment by liamdebeasi** [comment] 2019-08-01 14:43
Can you provide a repository with the code required to reproduce this issue? Thanks!

**Comment by liamdebeasi** [comment] 2019-08-01 14:46
Ahh yes I see what you're saying now. I was able to reproduce this issue. It looks like this is a bug in the core modal component, not in `@ionic/vue`. 

We will investigate a fix for this. Thanks!

**Comment by sneko** [comment] 2020-07-17 23:10
Hi @liamdebeasi ,

I checked this with Ionic v5.x but it's still happening. Note that not being able to destroy them (easily) results in kind of memory leak 😞 

Thank you,

**Comment by sneko** [comment] 2020-09-02 00:08
@liamdebeasi any plan/news please?

I may have missed something...

**Comment by sneko** [comment] 2020-09-28 00:02
Any chance someone look into it please?

cc @brandyscarney

**Comment by sneko** [comment] 2020-10-08 11:53
Sorry for tagging people, but it would be great to have at least a message... more than a year now 😢  Thank you.

cc @adamdbradley

**Comment by sneko** [comment] 2021-04-08 15:08
Should I give up on this issue? It sounds like a memory issue... @liamdebeasi @brandyscarney @adamdbradley

**Comment by sneko** [comment] 2021-07-26 08:20
@liamdebeasi still curious about this since you said:
```
Ahh yes I see what you're saying now. I was able to reproduce this issue. It looks like this is a bug in the core modal component, not in @ionic/vue.

We will investigate a fix for this. Thanks!
```

2 years now 🎂

**Comment by liamdebeasi** [comment] 2022-05-12 20:37
Hey there,

Apologies for the delay. This should be resolved with the introduction of declarative/inline modals in Ionic 6: https://ionicframework.com/docs/api/modal#inline-modals

With this approach, you can add the modal directly in your component template. This ensures that the modal component is already loaded when the user clicks a button to present the modal. It also means that modals that are never presented are automatically cleaned up when destroying the page. When your page component is destroyed, the child modals are destroyed too.

I am going to close this, but I recommend giving these new declarative/inline modals a try.

Thanks!

**Closed by liamdebeasi** 2022-05-12 20:37 UTC
Labels: package: core, type: bug
