### ISSUE TITLE
bug: Ion-datetime doesn't always initialize at the selected date

### ISSUE THREAD

**Issue by AlexyNau** [ionic-team/ionic-framework#28516] opened 2023-11-13 08:54 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When opening a `ion-datetime` in a `ion-popover`, the date doesn't always initialize at the selected date in v-model.

Once popover is opened, sometimes it shows _janvier 1923_
![image](https://github.com/ionic-team/ionic-framework/assets/36192838/55d539f5-1748-46aa-af4b-72f1efc3d339)

And other times it's fine, it shows _juin 2023_, the date in v-model.
![image](https://github.com/ionic-team/ionic-framework/assets/36192838/923b8189-3e88-4efc-809e-1db8b49318cc)

This behavior is only occured with `presentation` property set to `month-year` or `year`.

### Expected Behavior

When opening a `ion-datetime`, with `presentation` property set to `month-year` or `year`, in a `ion-popover`, the date should always initialize at the date in v-model.

### Steps to Reproduce

1. Create a `ion-datetime`, set `presentation` property to `month-year`
2. Set a date through v-model, for instance set `'2023-06-04T23:00:00.000+02:00'`
3. Add the `ion-datetime` in a `ion-popover` content with a trigger (see [ionicframework.com/docs/api/popover#triggers](https://ionicframework.com/docs/api/popover#triggers))
4. Open and close multiple times the popover
The wheel picker position is sometimes aligned to the current date, sometimes to 1 century before (top of the wheel).

### Code Reproduction URL

https://stackblitz.com/edit/vitejs-vite-rn9sej

### Ionic Info

See stackblitz `package.json`

**Comment by mapsandapps** [comment] 2023-11-13 18:42
Hi, thank you for the bug report. I'm able to reproduce this. I've created a (more) minimal reproduction on [stackblitz](https://stackblitz.com/edit/sh6qqk-j42g3w?file=src%2Fcomponents%2FExample.vue). I'm unable to reproduce the bug in Angular, React, or Javascript, although since it's sporadically occurring, it may be present in those as well but just more prominent in Vue.

**Comment by mapsandapps** [comment] 2023-11-13 19:55
Upon further reflection, it looks like this is a duplicate of #26234 (even though that one was reproducing only in Angular and this one is now reproducing (for me) only in Vue). As a workaround, you can use `keep-contents-mounted` on your Popover.

**Closed by mapsandapps** 2023-11-13 19:55 UTC
Labels: package: vue, type: bug
