### ISSUE TITLE
bug: Sheet modal overlay flashes when dismissed quickly using the handle on iOS

### ISSUE THREAD

**Issue by robholden** [ionic-team/ionic-framework#29288] opened 2024-04-05 17:31 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

A flash appears when dismissing a sheet modal by swiping the handle down quickly
![bug-record](https://github.com/ionic-team/ionic-framework/assets/6051248/3516b9e1-b54b-4281-acce-b530979991cd)

### Expected Behavior

No flashing after dismiss

### Steps to Reproduce

1. Press "Open Modal" on iOS simulator
2. Swipe down quickly with a short distance on the handle at the top of the modal sheet
3. Watch modal dismiss, then flash

### Code Reproduction URL

https://github.com/robholden/ionic-modal-flash

### Ionic Info

Ionic:

   Ionic CLI                     : 7.2.0 (/Users/rob/.nvm/versions/node/v20.9.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.8.3
   @angular-devkit/build-angular : 17.3.3
   @angular-devkit/schematics    : 17.3.3
   @angular/cli                  : 17.3.3
   @ionic/angular-toolkit        : 11.0.1

Capacitor:

   Capacitor CLI      : 5.7.4
   @capacitor/android : not installed
   @capacitor/core    : 5.7.4
   @capacitor/ios     : 5.7.4

Utility:

   cordova-res : not installed globally
   native-run  : 2.0.1

System:

   NodeJS : v20.9.0 (/Users/rob/.nvm/versions/node/v20.9.0/bin/node)
   npm    : 10.5.0
   OS     : macOS Unknown

### Additional Information

I can only replicate the problem when running natively via xcode on:
1. Iphone 15 - Simulator
2. Iphone 13 mini - Physical device

**Comment by EinfachHans** [comment] 2024-04-06 18:59
Probably duplicate of #28467

**Comment by liamdebeasi** [comment] 2024-04-08 13:55
Thanks for the report. As noted in https://github.com/ionic-team/ionic-framework/issues/29288#issuecomment-2041167710, this is a duplicate of #28467. The linked issue is a bug in WebKit, the engine that powers Safari on iOS. However, this issue has been resolved in a newer version of iOS, so I recommend updating your devices.

**Closed by liamdebeasi** 2024-04-08 13:55 UTC
Labels: triage
