### ISSUE TITLE
bug: Scrolling issue on iOS 12.4.8

### ISSUE THREAD

**Issue by SansDK** [ionic-team/ionic-framework#21999] opened 2020-08-28 08:24 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.3.2**

**Current behavior:**

In our Ionic PWA, scrolling is sometimes not possible on iOS.
If I am at the top of a certain page, and I try to drag down (to refresh the page), nothing happens.
I can only initiate the scrolling by scrolling to the bottom first, and to the top immediately after that.

Also, if you swipe down at the top of the page, it's like there is an invisible scroll bar present. When you let go after swiping down at the top, and then try to swipe up and down immediately after that, there is no scrolling action at all. You have to wait +- 1 second without touching the screen, and after that you can scroll (down) again.

**Expected behavior:**

I expect that scrolling should work just as it works on Android (or Chrome devtools iPhone mode). Pull to refresh should just work like expected and there should be no scroll blocking.

**Steps to reproduce:**

**Related code:**

I made a (bad, but working) project on Stackblitz where this can be reproduced.

https://stackblitz.com/edit/ionic-angular-v5-5hbj5z?file=src/app/test.component.html

I am testing on an iPhone 5s with iOS 12.4.8, using Safari.
To repro:

1. Open Stackblitz url.
2. Open Stackblitz application url on iPhone / iPhone Emulator (can't repro on PC).
3. Start dragging down just under the header / title bar.
4. Nothing happens..
5. (wait +- 1 sec) Drag up, scrolling works.
6. Drag down again, let go of the screen, and immediately try to drag up again, scrolling doesn't work

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.4.16 (/.npm/_npx/30377/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 5.3.2
   @angular-devkit/build-angular : 0.1000.8
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.18.3 (/usr/bin/node)
   npm    : 6.14.6
   OS     : Linux 4.18
```

**Comment by BerkeAras** [comment] 2020-08-29 10:52
@SansDK For me (iOS 14 Beta 6) it works fine.

**Comment by BerkeAras** [comment] 2020-08-29 10:52
Are you able to send a video how you see the error?

**Comment by liamdebeasi** [comment] 2020-08-31 13:54
Thanks for the issue. I was able to reproduce this issue on iOS 12; however, it appears to be a WebKit bug. I am going to close this as this is not a bug in Ionic Framework, but it does appear to have been fixed in newer versions of iOS.

**Closed by liamdebeasi** 2020-08-31 13:54 UTC
Labels: triage

**Comment by SansDK** [comment] 2020-09-01 08:33
Thanks for your answer.
Do you have any more information about this bug, or a Webkit Bugzilla link where this bug is discussed?

**Comment by SansDK** [comment] 2020-09-01 13:26
Could you try https://stackblitz.com/edit/ionic-v4-angular-tabs-oxch7n?file=package.json on iOS 12? There is also a list with the `<ion-refresher>` element (on tab 2), but the Angular and Ionic versions are different.

I don't have the iPhone 5s available for testing right now, but I believe that I tried this example and that it **did** work on iOS 12.4.8. If we could verify this info than we can figure out if it's really a Webkit bug or an Angular or Ionic bug (or maybe a combination of both).

Thanks in advance.

**Comment by SansDK** [comment] 2020-09-03 08:56
Confirmed also not working in iOS 13.6.1

**Comment by SansDK** [comment] 2020-09-11 13:23
Hey @liamdebeasi, could you perhaps re-open this issue?

I don't think that we call it a Webkit bug if we don't know the specifics of it, and it did seem to work in an older Ionic version.

**Comment by liamdebeasi** [comment] 2020-09-11 16:28
I will take a look and see if I can identify a workaround (might not be until early next week)

**Comment by liamdebeasi** [comment] 2020-09-17 17:57
So far I have only been able to reproduce this issue on iOS 12.4. I have tested this on iOS 13.3, iOS 13.6, iOS 13.7, and iOS 14 and have been unable to reproduce the issue there.

**Comment by SansDK** [comment] 2020-09-18 06:33
That's quite strange. Maybe that was a mistake from me.
Thanks for taking the time to test it on different iOS versions.

Have you also been able to test the other Stackblitz example that I sent you (on iOS 12)?

**Comment by liamdebeasi** [comment] 2020-09-18 14:07
Yes I can reproduce that other example on iOS 12. The difference is in how the gesture is created. In the first example, the pull to refresh gesture relies on scroll events. In this case, the browser does not appear to be emitting scroll events on the content in iOS 12 when used in that way. In the second example, the pull to refresh gesture relies on touch events.

On iOS 12 there appears to be an issue with scroll latching. I inspected the application further and it looks like scroll events are being dispatched on the `body` element or on `document`, not on the inner scroll div inside of `ion-content`.

As a workaround, you might want to consider falling back to the touch event pull to refresh gesture for devices running iOS 12.
