### ISSUE TITLE
feat: swipe to close when swiping the ion-content

### ISSUE THREAD

**Issue by muhamed87** [ionic-team/ionic-framework#25031] opened 2022-03-31 14:17 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

I see an issue regarding the swipe to close modal from ion-content and noticed that it is not an issue and user should swipe from the modal header.

But I guess if this feature added it will be better as this is a user experience in different apps he used usually so he will sure use the same behavior he expect as usual.

You can open facebook app for example and open any post comments, scroll down then scroll up you will see that once you reach the first comment when you scroll up once you swipe again from the comments it will close the modal.

Again I suggest this feature only because it is now a natural behavior the user already experiencing daily in different apps.

Thanks

### Describe the Use Case

You can open facebook app for example and open any post comments, scroll down then scroll up you will see that once you reach the first comment when you scroll up once you swipe again from the comments it will close the modal.

Again I suggest this feature only because it is now a natural behavior the user already experiencing daily in different apps.

### Describe Preferred Solution

Apply the normal behavior for swipe to close modal from the ion-content once it reaches the top of it while scrolling top

### Describe Alternatives

Facebook post comments modal

**Comment by liamdebeasi** [comment] 2022-03-31 15:24
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/22046.

**Closed by liamdebeasi** 2022-03-31 15:24 UTC
Labels: triage
