### ISSUE TITLE
bug: probable bug in #24315

### ISSUE THREAD

**Issue by vicb** [ionic-team/ionic-framework#24641] opened 2022-01-24 18:46 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

The fix in #24315 improves the router behavior by comparing the parameters on top of the ID which makes matchesIDs more robust.

I think that a few things could be improved in this CL:

https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/router/utils/matching.ts#L72-L80

The code assume that all segments of the chain ((`routeChain.path[j]`)) are parameter segment of the form (`/:param`). It doesn't account for fixed segments.

https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/router/utils/matching.ts#L72-L80

The code also assumes that all `routeIdParams` are populated from the parameter segments (i.e. `:params`). It misses the case where the parameters are populated from the `componentProps` of the `<ion-route>`.

If we agree on the those 2 points, I'd like to propose a PR.

@sean-perkins, what do you think ?

### Expected Behavior

Take into account fixed segments and componentProps.

### Steps to Reproduce

I modified the tests locally to make sure those 2 cases are not taken into account.

**Comment by sean-perkins** [comment] 2022-01-24 19:01
@vicb thanks for reporting this issue. 

Can we first establish a reproduction app that identifies the bug? A simple app with the router implementation that uses a mix of fixed path values and parameters. Alternatively if you want to provide the modified test spec that demonstrates the score is incorrectly determined when comparing the routes, that would suffice. 

I believe the `componentProps` on `ion-route` are indifferent of the browser's location history and is simply a way to assign parameters to the resolved view. The logic being reviewed is used to determine the correct view to resolve when evaluating a location history (typically for back navigation or direct navigation). Can you provide a use case to help me understand when `componentProps` should be taken into consideration when determining the view to resolve?

**Comment by vicb** [comment] 2022-01-24 19:25
> Can we first establish a reproduction app that identifies the bug?

I commented on #24315 to have access to the repro app you created for this PR (the one on the videos).
Having access to this app would simplify the task here and I think it should be checked-in and e2e tested.

> Alternatively if you want to provide the modified test spec

I do have a PR ready with updated specs but it builds on top of #24627. If we can get that PR merged, I'll submit the PR for this bug.

> I believe the componentProps on ion-route are indifferent of the browser's location history [...]

I think this is only partially true. 
`matchesIDs()` we be called as a result of `Router.navChanged()` being called.
`Router.navChanged()` is called when you change the stack in a `<ion-nav>` or select a tab in a `<ion-tabs>`. So the source is actually not a location history event in this case. What happens is we first update the DOM and `navChanged` will sync the route from the state of the DOM (what I call "backward" in my doc if you have seen it).

A simple use case would be:

```
<ion-route url="/cat" component="animal" .componentProps={{type: cat}}></ion-route>
<ion-route url="/dog" component="animal" .componentProps={{type: dog}}></ion-route>
```

Here we use the same component to display either a cat or a dog - the way we discriminate is by passing a component prop.

You can see in [routerIDstoChain](https://github.com/ionic-team/ionic-framework/blob/034d04920952b081d643e69bdbc66cf24e73a7f4/core/src/components/router/utils/matching.ts#L156) that we merge the router parameters with the segment parameters before calling setRouteId in [writeNavState](https://github.com/ionic-team/ionic-framework/blob/034d04920952b081d643e69bdbc66cf24e73a7f4/core/src/components/router/utils/dom.ts#L25).

So when reading back the Ids in [readNavState](https://github.com/ionic-team/ionic-framework/blob/034d04920952b081d643e69bdbc66cf24e73a7f4/core/src/components/router/utils/dom.ts#L57-L61) we will retrieve the merged parameters.

Does this make sense ?

**Comment by sean-perkins** [comment] 2022-01-24 19:41
The repo app for that specific issue is available here: https://github.com/cjorasch/issue-24223.

> I do have a PR ready with updated specs but it builds on top of #24627. If we can get that PR merged, I'll submit the PR for this bug.

I took a quick look over the PR, but will need to discuss with the team around terminology. The only immediate issue I see with that PR, is moving comment blocks from multi-line format to inline, breaks intellisense in VSCode. All public members with code documentation or multi-line comments should use: `/**` formatting instead of `//`.  All other changes seemed straightforward and just need internal verification before proceeding. 

>A simple use case would be:
>  ```
> <ion-route url="/cat" component="animal" componentProps={{type: cat}}></ion-route>
> <ion-route url="/dog" component="animal" componentProps={{type: dog}}></ion-route>
> ```

That makes sense to me, thanks for the added detail 👍  it's helpful when you want to have explicit routes with a shared component, but wouldn't want to have an open parameter like `url="/:type"`.

**Comment by vicb** [comment] 2022-01-24 19:50
> All public members with code documentation or multi-line comments should use: /** formatting instead of //

I think matchesIDs is an internal function, not a public member ?
_(And all those comments will go away with my PR fixing the issue)_

**Comment by liamdebeasi** [comment] 2022-02-15 14:31
I know we've been talking about this offline, but wanted to post my thoughts for visibility and further discussion.

While I agree that having `ion-tabs` and `ion-nav` notify `ion-router` is incorrect, I do not think that having the router account for component properties is the correct resolution.

The way I think of routing is that routing is the act of mapping a path to a component. This means that the router looks at the path (I.e. `/page/abc`) in order to determine the component (I.e. `<my-component>`).

Given that properties are set on the component, I do not think it makes sense to have the router also look at the component config too. In this case, navigating to `/page/a` and then `/page/a` again after some time should map to the same instance of a component because the global state (the URL) will be exactly the same. Developers should use route parameters if they want to get a new instance of the same component.

Does this address your concern?

**Comment by vicb** [comment] 2022-02-15 14:50
@liamdebeasi 

> While I agree that having ion-tabs and ion-nav notify ion-router is incorrect, I do not think that having the router account for component properties is the correct resolution.

I think the way ion-tabs and ion-nav works is kind of weird but we can still mostly make it work with the fix for the current issue.

There is still one weird case: let's imagine you are on route A and push the B components to a `ion-nav`. `ion-nav` will animate the view and B will be animated in. Once B is in it will notify the router. At that point the router can retrieve the route, let's say '/b'. Now imagine that route has a hook to prevent entering the route. We have to go back to A. It is valid an doable but still you have seen B entering the view before you get back to A. More on this on my 2 next PRs (after the pending one is merged).

> The way I think of routing is that routing is the act of mapping a path to a component. This means that the router looks at the path (I.e. /page/abc) in order to determine the component (I.e. <my-component>).

`ion-nav` and `ion-tabs` both work in the opposite way too (they also support the "regular way").

When you push a component to a nav or click a tab button, the path is deduced from the URL. This is what the current issue is about.

> Given that properties are set on the component, I do not think it makes sense to have the router also look at the component config too. In this case, navigating to /page/a and then /page/a again after some time should map to the same instance of a component because the global state (the URL) will be exactly the same. Developers should use route parameters if they want to get a new instance of the same component.

I think you are missing a common use case here. It is valid and common to have different routes with the same component which are then differentiate by route params.

A few examples:

```
<ion-route url="/cat" component="animal" componentProps={{type: cat}}></ion-route>
<ion-route url="/dog" component="animal" componentProps={{type: dog}}></ion-route>
```

```
<ion-route url="/users/active" component="user-list" componentProps={{type: active}}></ion-route>
<ion-route url="/users/inactive" component="user-list" componentProps={{type: inactive}}></ion-route>
<ion-route url="/users/admin" component="user-list" componentProps={{type: inactive}}></ion-route>
```

It is not possible to map the component to different urls if you do not consider the parameters.

> Does this address your concern?

No :) It didn't and I hope my explanation helped you understand why it is needed.
I am available to answer any of your questions.

**Comment by liamdebeasi** [comment] 2022-02-15 16:02
That makes sense. I think I would prefer that ion-tabs change the URL instead of having it notify the router post-transition. This seems like it would allow for hooks to fire before the transition happens without having to make any additional workarounds.


> I think you are missing a common use case here. It is valid and common to have different routes with the same component which are then differentiate by route params.
> 
> A few examples:
> 
> The component can display a picture of an animal and has a different title ("cat" or "dog")
> 
> ```
> <ion-route url="/cat" component="animal" componentProps={{type: cat}}></ion-route>
> <ion-route url="/dog" component="animal" componentProps={{type: dog}}></ion-route>
> ```
> 
> You have tabs displaying active/inactive/admin users - they all use the user-list component
> 
> ```
> <ion-route url="/users/active" component="user-list" componentProps={{type: active}}></ion-route>
> <ion-route url="/users/inactive" component="user-list" componentProps={{type: inactive}}></ion-route>
> <ion-route url="/users/admin" component="user-list" componentProps={{type: inactive}}></ion-route>
> ```
> 
> It is not possible to map the component to different urls if you do not consider the parameters.

I thought this is something we already support? The router will look at the parameters in the URL to determine which component to map to. My understanding of this issue's request is that you want the router to also look at the component properties (I.e. the stuff in `componentProps`) which I do not think is the correct behavior.

**Comment by vicb** [comment] 2022-02-15 16:57
Let's start with a little correction: this issue only applies to `<ion-nav>` where the id is the component. The problem described here is that multiple routes can use the same component hence have the same id. For tabs, the id is the name of the tab which by definition is unique.

> That makes sense. I think I would prefer that ion-tabs change the URL instead of having it notify the router post-transition. This seems like it would allow for hooks to fire before the transition happens without having to make any additional workarounds.

It is probably not possible to do that for tabs/nav. The reason being that the current system "remembers" the sub path (the part of the path that is inside the tabs/nav).

Let's say you have to tabs (tab1 and tab2 on path /tab1 and /tab2) and tab1 has nested outlets.

The first time you navigate to tab1, the route will be /tab1. Now if you navigate inside tab1 the route might become /tab1/nested/route. If you navigate to tab2, the route will become /tab2.

At that point if you activate the tab1 again the full view will be restored and the URL that will be generated from that is /tab1/nested/route. If you want to navigate by URL you would have to remember the sub-path (/nested/route) somehow. This would be challenging to implement (I'm not even sure we can fully support it without breaking changes).

> I thought this is something we already support? The router will look at the parameters in the URL to determine which component to map to. My understanding of this issue's request is that you want the router to also look at the component properties (I.e. the stuff in componentProps) which I do not think is the correct behavior. In this example, these routes all map to the same component, but they should be separate instances of the component as the paths are all different.

Yes if you look at my examples above the id (that is the component) is the same. The only way to map the DOM back to a unique route is then to consider both the id and the route parameters (i.e. `componentProps`).

> edit: Though in the above example, there are no parameters -- just fixed paths. Instead you could do something like this: /users/:state.

You could do `/users/:state` and this is supported but if you do that then you also have to create a hook to make sure that state is in a list of supported value. Overkill in those cases which is why I propose to also take route parameters into consideration.

What problem do you have with taking route parameters (/ `componentProps`) into consideration ?

**Comment by liamdebeasi** [comment] 2022-02-15 21:47
> Let's say you have to tabs (tab1 and tab2 on path /tab1 and /tab2) and tab1 has nested outlets.
> 
> The first time you navigate to tab1, the route will be /tab1. Now if you navigate inside tab1 the route might become /tab1/nested/route. If you navigate to tab2, the route will become /tab2.
> 
> At that point if you activate the tab1 again the full view will be restored and the URL that will be generated from that is /tab1/nested/route. If you want to navigate by URL you would have to remember the sub-path (/nested/route) somehow. This would be challenging to implement (I'm not even sure we can fully support it without breaking changes).

Just so I understand, when you say "nested outlet" are you nesting one or more instances of `ion-router-outlet` inside of a single tab? If so, then that is not the correct usage of nested outlets. Nested outlets should only be used when you want to render content in multiple outlets at once.

> Yes if you look at my examples above the id (that is the component) is the same. The only way to map the DOM back to a unique route is then to consider both the id and the route parameters (i.e. componentProps).

I think this is the part that I am confused on. Route parameters are not the same as `componentProps`. Route parameters are things like `:id` in the route definition. For example:

```html
<ion-route url="animals/:id" component="animal"></ion-route>
```

In the example above, the route parameter is `:id`. `componentProps` is an object that is passed to the rendered component and has nothing to do with routing.

Consider the following route config:
```html
<ion-route url="animals/cat" component="animal" componentProps={{ type: 'cat' }}></ion-route>
```

The above example has no parameters because the url is fixed to `animals/cat`. In other words, that URL cannot vary. The rendered component does receive component properties, but those properties have no tie to the route.

I agree that we should account for route parameters (I.e. `:id`) when path matching, but I do not think we should account for `componentProps`.

**Comment by vicb** [comment] 2022-02-15 22:01
> Just so I understand, when you say "nested outlet" are you nesting one or more instances of ion-router-outlet inside of a single tab? 

I mean any kind of outlet (tabs, nav, or router-outlet).

> If so, then that is not the correct usage of nested outlets. Nested outlets should only be used when you want to render content in multiple outlets at once.

If I understand what you mean then I don't agree here.

The nesting of (any kinds of) outlets should match the nesting of your routes. That is if you have nested routes you have to have nested (any kinds of) outlets.

It is perfectly valid to have a sub path rendered inside a tab (check the "tabs" e2e test in the router)

> I think this is the part that I am confused on. Route parameters are not the same as componentProps. Route parameters are things like :id in the route definition. For example:

I call componentProps route parameters and parameter from the path segment parameters, sorry for the confusion.

> In the example above, the route parameter is :id. componentProps is an object that is passed to the rendered component and has nothing to do with routing.

It has to do with routing because it is passed to the outlets (check setRouteId and getRouteId in the outlet interface).

> I agree that we should account for route parameters (I.e. :id) when path matching, but I do not think we should account for componentProps.

We should again for the reasons/examples I have mentioned before. You can check the test on my PR too.

**Comment by liamdebeasi** [comment] 2022-02-22 21:24
Thanks for the issue. After discussing with the team we have decided to close this out because the associated PR was rejected.

Please see https://github.com/ionic-team/ionic-framework/pull/24645 for more information. We are currently tracking router infrastructure changes internally, and we will communicate these changes with the community as we have them. Thanks!

**Closed by liamdebeasi** 2022-02-22 21:24 UTC
Labels: triage
