### ISSUE TITLE
feat: Tech Debt related to FW-5592

### ISSUE THREAD

**Issue by gongAll** [ionic-team/ionic-framework#29735] opened 2024-07-26 16:30 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/docs/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Right now, when I want to add some icon to the end of the ion-input element, doing so will make the floating behaviour to malfunction.

### Describe the Use Case

If I put an icon on the end slot of the ion-input, up until focusing the input, everything is fine. However, if I take focus away from the input the label will remain floating, instead of going back to its place.

### Describe Preferred Solution

Right now, floating behaviour is defined as such

``` typescript
const labelShouldFloat = labelPlacement === 'stacked' || (labelPlacement === 'floating' && (hasValue || hasFocus || hasStartEndSlots));
```
I would suggest just removing the "hasStartEndSlots" variable, since it doesn't seem to accomplish a whole lot. It doesn't make sense to keep the label floating when there is no value and there is no focus (unless there's some specific case I'm not seeing at the moment).

``` typescript
const labelShouldFloat = labelPlacement === 'stacked' || (labelPlacement === 'floating' && (hasValue || hasFocus));
```

**Comment by proxgames** [comment] 2024-08-01 20:14
Any update here?

**Comment by brandyscarney** [comment] 2024-08-07 21:46
Thank you for the issue. Marking this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/28665. Please upvote / subscribe to that issue for updates.

**Closed by brandyscarney** 2024-08-07 21:46 UTC
Labels: triage
