### ISSUE TITLE
bug: Flickering and unable to disable swipe back gesture on Safari IOS devices

### ISSUE THREAD

**Issue by DalinaLeila** [ionic-team/ionic-framework#25167] opened 2022-04-21 14:23 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

https://user-images.githubusercontent.com/39704983/164478444-3c277a79-5042-4d55-bfc8-7c0820745235.mov

### Expected Behavior

If **swipeBackEnabled is set to false**, the swipe gesture should be prevented and browser back navigation should not occur. 
When **swipeBackEnabled is set to true** only one of the browser back navigation or ionic built in back-transitions should occur, not both. 

There should be **no flashing** of a page transition when navigating to another page using the swipe gesture. 

### Steps to Reproduce

Generate a list starter ionic application:

Inside the main.ts file, set swipeBackEnabled to true/false. Navigate to a list item and back to the homepage on an ios device or ios simulator. 

**Drag finger from left edge of screen to right. In both cases, the swipe gesture triggers back navigation.**

### Ionic Info

Ionic:

   Ionic CLI       : 6.18.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 6.1.2

Capacitor:

   Capacitor CLI      : 3.4.3
   @capacitor/android : not installed
   @capacitor/core    : 3.4.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v14.16.0 (/usr/local/bin/node)
   npm    : 8.3.1
   OS     : macOS Monterey

**Comment by liamdebeasi** [comment] 2022-04-21 14:56
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/22299. The issue references PWAs but the underlying issue is the same.

**Closed by liamdebeasi** 2022-04-21 14:56 UTC
Labels: triage
