### ISSUE TITLE
onDoubleClick is not working (Ionic React)

### ISSUE THREAD

**Issue by jdnichollsc** [ionic-team/ionic-framework#21320] opened 2020-05-18 05:30 UTC
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
I'm testing `onDoubleClick` with **IonItem** and **IonCard** react components but it's not working:

**Expected behavior:**
Trigger the event as expected

**Steps to reproduce:**
- Add the event to these components from an Ionic React project

**Related code:**
```
<IonItem onDoubleClick={(e) => alert('not working')}>
</IonItem>
```
Sample application: https://stackblitz.com/edit/ionic-v4-react-double-click-issue

**Ionic info:**
```
Ionic:

   Ionic CLI       : 6.4.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.1.1

Capacitor:

   Capacitor CLI   : 2.0.2
   @capacitor/core : 2.0.2

Utility:

   cordova-res (update available: 0.14.0) : 0.8.0
   native-run (update available: 1.0.0)   : 0.2.8

System:

   NodeJS : v10.15.3 (/usr/local/bin/node)
   npm    : 6.14.4
   OS     : macOS Mojave
```

**Comment by jdnichollsc** [comment] 2020-05-18 14:13
@liamdebeasi this is the sample application https://stackblitz.com/edit/ionic-v4-react-double-click-issue
Thanks for your help!

**Comment by liamdebeasi** [comment] 2020-05-18 15:07
Thanks! I was able to reproduce this issue. I noticed your reproduction used an old version of Ionic React, so here is a reproduction of the issue using the latest version of Ionic: https://stackblitz.com/edit/ionic-v4-react-double-click-issue-jyvd9h

As a temporary workaround, adding the double click listener to the element via `addEventListener` seems to work.

**Comment by codespaceinc** [comment] 2021-04-16 20:40
Hey guys is there any update on this ? Encountered this issue as well. Can't seem to assign ref to IonTextArea with typescript either

**Comment by avalanche1** [comment] 2021-06-12 16:35
It's been a year guys. Can we get this fixed?

**Comment by MatrixRave** [comment] 2023-05-02 10:37
3 years later, the problem still seems to exist. Can anyone confirm this? And is there any outlook as to when the problem will be fixed? 
Thanks in advance!

**Comment by sean-perkins** [comment] 2023-05-31 20:53
@MatrixRave would you be available to test a dev-build to see if the problem is resolved?

```
npm install @ionic/react@7.0.11-dev.11685565959.10c33d71 ionic/react-router@7.0.11-dev.11685565959.10c33d71
```

**Closed** 2023-06-08 18:53 UTC
Labels: package: react, type: bug
