### ISSUE TITLE
bug: routing integration should not cache views

### ISSUE THREAD

**Issue by cocuriosa** [ionic-team/ionic-framework#22080] opened 2020-09-12 21:41 UTC
**Ionic version:**
[x] **5.31** @ionic/angular 5.3.1

**I'm submitting a ...** 
[x] bug report

**Current behavior:**
/x/a =routerLink-to-b=> /x/b =routerLink-to-a=> /x/a =back-button=> /x

I am on PageA (/x/a) and then navigate to PageB (/x/b) and now click on a routerLink="/x/a".
I end up on /x/a as expected but when I click the back button I don't get back to /x/b and instead find myself on /x.
As if it did take the a page that was already open and thus not have PageB in the history stack anymore.

When instead on PageB (/x/b) link to a PageC and from there go back, I end up on the PageB. 
So it really looks like when on PageB linking to PageA it goes BACK to the previous PageA and doens't go forward in the navigation.

However, when I use the web-browser back-button, it acts as I would expect it to. So it seems to really have to do something with the ionic-back-button/navigation.
My intuition would be that the reason is that the URL (component) I go to is already in the history and so it goes there instead of adding a new push to the history.

**Expected behavior:**
/x/a =routerLink-to-b=> /x/b =routerLink-to-a=> /x/a =back-button=> /x/b

**Steps to reproduce:**
1) Create a PageA with a defaultHref to PageX
2) Create a PageB with a defaultHref to PageX
3) have a component on PageB that uses a routerLink linking to PageA  and then click on the back-button on the PageA that you're getting to via the routerLink click

**Extra information:**
This seems related but not solved yet either:
https://stackoverflow.com/questions/40821005/i-have-an-issue-with-history-back-when-navigate-to-same-page

**Ionic info:** 
```
Ionic:

   Ionic CLI                     : 6.7.0 (C:\Users\corin\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.3.1
   @angular-devkit/build-angular : 0.1000.3
   @angular-devkit/schematics    : 10.0.3
   @angular/cli                  : 10.0.3
   @ionic/angular-toolkit        : 2.3.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.11.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.8
   OS     : Windows 10
```

**Comment by cocuriosa** [comment] 2020-09-14 13:27
> Please provide a reproduction with the minimum amount of code required to reproduce the issue. Without a reliable code reproduction, it is unlikely we will be able to resolve the issue, leading to it being closed.

Is there an online sandbox for the current Ionic Version that I can base it on?

**Comment by indraraj26** [comment] 2020-09-16 11:21
Sandbox: https://stackblitz.com/edit/github-tvcimp?file=src/app/app.component.ts

**Comment by cocuriosa** [comment] 2020-09-22 17:45
Thanks for the Sandbox-Link. 
Here is the reproduction: 
https://stackblitz.com/edit/back-button-navigation-issue?file=src/app/tabs/dashboard/dashboard.page.html
Looking forward to hearing back from you! :)

**Comment by indraraj26** [comment] 2020-10-08 08:05
Indeed It is bug and should preserve the router state.

**Comment by liamdebeasi** [comment] 2020-10-30 15:07
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/19531.

**Closed by liamdebeasi** 2020-10-30 15:07 UTC
Labels: ionitron: needs reproduction
