### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by FcoCrespo** [ionic-team/ionic-framework#25579] opened 2022-07-06 08:42 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

Hello,

in reference to the issue [#24998](https://github.com/ionic-team/ionic-framework/issues/24998) right now there is not any buttons when you change from date mode into month-year mode. 

For many users it is not intuituve to choose this data without default buttons.

I share the code and the aspect of  month-year mode.

```
<ion-modal trigger="open-modal" mode="md">
    <ng-template>
      <ion-content>
        <ion-datetime 
        #datetime 
        [value]="dateValue" size="cover"
        (ionChange)="dateChanged(datetime.value)"
        (ionCancel)="showPicker = false;"
        presentation="date"
        showDefaultButtons="true">
        </ion-datetime>
      </ion-content>
    </ng-template>
  </ion-modal>
</ion-content>
```

Thank you!

### Expected Behavior

Default Buttons should appear in month-year mode.

### Steps to Reproduce

![ionic date month-year without buttons](https://user-images.githubusercontent.com/55406000/177508840-9a69eede-b319-4f17-a28b-3c1a05bf7520.png)

### Ionic Info

Ionic:

   Ionic CLI                     : 6.20.1 (/usr/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.1.12
   @angular-devkit/build-angular : 14.0.4
   @angular-devkit/schematics    : 14.0.4
   @angular/cli                  : 14.0.4
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.6.0
   @capacitor/android : 3.6.0
   @capacitor/core    : 3.6.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.6.0

System:

   NodeJS : v16.15.1 (/usr/bin/node)
   npm    : 8.13.1
   OS     : Linux 5.4

**Comment by liamdebeasi** [comment] 2022-07-06 12:53
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/25531. This is an intentional design. I provided more reasoning here: https://github.com/ionic-team/ionic-framework/issues/25531#issuecomment-1165558435

You may also be interested in a new wheel picker feature we are working on: https://github.com/ionic-team/ionic-framework/issues/25531#issuecomment-1165568001

**Closed** 2022-07-06 12:53 UTC
Labels: triage
