### ISSUE TITLE
Your CSS styles are not loading in Chrome. Check your website because it's happening there too. You're welcome.

### ISSUE THREAD

**Issue by davidmedero** [ionic-team/ionic-framework#23410] opened 2021-06-03 19:55 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment] 2021-06-03 20:47
Hey there,

Which website is this? I checked ionicframework.com and ionic.io and both seem to be working fine in Chrome. You might want to try a hard refresh to avoid getting any cached files.

**Comment by davidmedero** [comment] 2021-06-03 20:56
My apologies. I just checked my 3rd pc and it's working there. I have no
idea why I am getting this error on my two other computers, both mac and
pc. I cleared my cache and hard refresh does nothing.

**Comment by liamdebeasi** [comment] 2021-06-03 21:00
Thanks! What version of Chrome are you using on the Macs where this is not working?

**Comment by davidmedero** [comment] 2021-06-03 21:01
Version 91.0.4472.77 (Official Build) (x86_64)

**Comment by liamdebeasi** [comment] 2021-06-03 21:05
Ok thanks. I double checked with our team, and they are not seeing any issues. There may be some caching going on in the CDN, so I would recommend trying again in an hour or two. I am going to close this issue for now, but feel free to let us know if you see any other issues on our website.

**Closed by liamdebeasi** 2021-06-03 21:05 UTC
Labels: triage

**Comment by davidmedero** [comment] 2021-06-03 21:06
Thank you Liam! I'll keep you posted

**Comment by davidmedero** [comment] 2021-06-03 21:14
Oh my god, I figured it out. I'm so embarrassed. It was because of an
extension called super dark mode. That would also explain why the default
theme for the Ionic framework was dark.

Sorry about that team

**Comment by liamdebeasi** [comment] 2021-06-03 21:17
No worries, glad the issue is resolved!
