### ISSUE TITLE
bug: chrome for windows and firefox close overlay when dismissing alert with escape key

### ISSUE THREAD

**Issue by easrng** [ionic-team/ionic-framework#25802] opened 2022-08-23 00:34 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

When dismissing a browser dialog (file picker, `alert`, etc) with the escape key, ionic overlays (popovers, dialogs, etc) also close.

### Expected Behavior

Dismissing a browser dialog with escape should only dismiss the browser dialog, not any ionic overlays.

### Steps to Reproduce

 - Show any ionic overlay
 - Open a browser `alert`
 - Hit escape
 - Observe that both the `alert` dialog and the ionic overlay are closed

### Code Reproduction URLs

 - [6.2.4-nightly.20220822](https://codepen.io/easrng/pen/gOeEBGq)
 - [6.2.3](https://codepen.io/easrng/pen/ExEMdLw)

### Ionic Info

I do not use the ionic CLI.

### Additional Information

I think changing from a keyup listener to a keypress listener may fix this.

**Comment by easrng** [comment] 2022-08-23 01:24
I can confirm that changing [this line](https://github.com/ionic-team/ionic-framework/blob/f9ab9b54ddb5a3004673e4aaa9cb62fd8e97ba07/core/src/utils/overlays.ts#L310) to use keypress fixes this.

**Comment by liamdebeasi** [comment] 2022-08-23 13:28
Thanks for the issue. I can reproduce this in Firefox only. Unfortunately, this appears to be a long standing bug in Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=112298.

The `keypress` event is deprecated, so I do not think we would be comfortable making the suggested change: https://developer.mozilla.org/en-US/docs/Web/API/Element/keypress_event

**Comment by liamdebeasi** [comment] 2022-08-23 19:09
I discussed this behavior more with the team.

It looks like when dismissing an `alert` dialog with the Escape key, Firefox will dispatch a `keyup` event. This causes overlays in Ionic to also dismiss. Other browsers do not emit `keyup` when dismissing an `alert` with the Escape key. This is a Firefox bug as I noted in https://github.com/ionic-team/ionic-framework/issues/25802#issuecomment-1224078575.

The reason why changing the listener to `keypress` works is that `keypress` is only dispatched when a key that produces a character value is pressed down. The Escape key does not produce a character value, so `keypress` is not fired. This is explained in https://developer.mozilla.org/en-US/docs/Web/API/Element/keypress_event. While the `alert` dialog will still dismiss, this change means that it will no longer possible to dismiss overlays with the Escape key.

----

When it comes to bugs in 3rd party software that impact Ionic apps, we typically keep the issue open if one of the following is true:

1. We can work around/fix the issue internally.
2. There is a good chance we can advocate to get this bug resolved in the 3rd party software.

At the moment we are not aware of a good workaround that can be implemented that does not negatively impact other parts of Ionic applications. Additionally, the Firefox bug has been open for 21 years at the time of writing. We think it is unlikely that this bug will be resolved anytime soon. As a result, we are going to close this as this is not a bug in Ionic.

I realize this may not be the resolution you were hoping for. If getting this issue fixed is important for your application, I recommend providing feedback on https://bugzilla.mozilla.org/show_bug.cgi?id=112298. Thank you for the report!

**Comment by liamdebeasi** [comment] 2022-08-23 19:35
Actually, I did not realize that this bug is limited to `keyup`. Moving to `keydown` seem to fix the issue here. Additionally, using `keydown` instead of `keyup` seems to more closely align with what the browser and native platforms do. I need to discuss with the team and see if this is something we are interested in doing, but I will re-open this for now.

**Comment by easrng** [comment] 2022-08-23 19:49
I can reproduce on chrome (windows)

**Comment by liamdebeasi** [comment] 2022-08-23 19:53
Ah interesting, I can reproduce the issue on Chrome for Windows, but it looks like Chrome for macOS is not affected. Regardless, switching to `keydown` fixes the issue there as well. I spoke with the team, and we are interested in making the `keydown` change. However, we do consider this a breaking change in behavior for how overlays currently work, so this fix will need to target Ionic 7, the next major release of Ionic.

**Comment by easrng** [comment] 2022-08-23 20:11
Would adding an option to switch to keydown be a breaking change? If not, could that be implemented? Right now I'm monkeypatching it with ```js
const real=Document.prototype.addEventListener;
Document.prototype.addEventListener=function(...args){
  if(args[0]=="keyup" && new Error().stack.split("\n").slice(0,5).join("\n").includes("ionic/p-79aef531.js")) args[0]="keydown"
  return real.call(this,...args)
}
```
but that's obviously not a great solution.

**Comment by liamdebeasi** [comment] 2022-08-23 20:26
Adding a feature to switch between `keydown` and `keyup` would avoid the breaking change. However, we typically try to avoid adding features that work around browser bugs as it adds a considerable amount of technical debt to the project.

I created an alternative workaround that may work for your use case: https://codepen.io/liamdebeasi/pen/YzaMGmr
If a `keyup` event is dispatched within a certain amount of time after the alert is dismissed, call `stopPropagation()` on the event which prevents it from bubbling. As a result, the overlay does not dismiss.

**Comment by liamdebeasi** [comment] 2022-08-23 21:16
I merged a fix for this issue via https://github.com/ionic-team/ionic-framework/pull/25811. This fix will be available when Ionic 7 ships.

In the meantime, you can either continue to use the workaround you have in https://github.com/ionic-team/ionic-framework/issues/25802#issuecomment-1224791276 or use the proposed alternative I provided in https://github.com/ionic-team/ionic-framework/issues/25802#issuecomment-1224824381.

I am going to close this since the fix has been merged into our codebase, but let me know if you have any additional questions. Thanks for the report!

**Closed by liamdebeasi** 2022-08-23 21:16 UTC
Labels: package: core, type: bug
