### ISSUE TITLE
feat: be able to get default picker options of ion-datetime

### ISSUE THREAD

**Issue by kodwi** [ionic-team/ionic-framework#22971] opened 2021-02-24 21:31 UTC
# Feature Request

**Ionic version:**

[x] **5.x**

**Describe the Feature Request**

I need to add `Clear` button to `ion-datetime` picker. I'm setting the custom picker options, but this overwrites the default buttons `Done` and `Cancel` with their default behavior.

**Describe Preferred Solution**

It would be nice, if you add some default property that contains default picker options to be able to use a trick like this:

`generateCustomPickerOptions(controlName: string) {
    return {
      ...this.clearablePicker.pickerOptions,
      buttons: [
        {
          text: 'CLear',
          handler: () => this.eventChangeForm.get(controlName).patchValue(null)
        },
        ...this.clearablePicker.pickerOptions.buttons
      ]
    };
  }`

sorry for code formatting, github couldn't make it human readable...

**Describe Alternatives**

**Related Code**

**Additional Context**

**Comment by liamdebeasi** [comment] 2021-02-24 21:41
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/17482.

**Closed by liamdebeasi** 2021-02-24 21:41 UTC
Labels: triage
