### ISSUE TITLE
bug: Debouce not working in ionic 7

### ISSUE THREAD

**Issue by tradingproject19** [ionic-team/ionic-framework#27143] opened 2023-04-07 20:35 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

We just migrated our app from ionic 6 to ionic 7 and found that debounce property on ion-searchbar is not working any more.

I have created a fiddle please have a look.

https://stackblitz.com/edit/ionic6-angular13-myrtnf?file=src/app/app.component.html

Please ignore ionic6 in the url name, I have changed packages.

### Expected Behavior

debounce should work as it was working in ionic 6

### Steps to Reproduce

https://stackblitz.com/edit/ionic6-angular13-myrtnf?file=src/app/app.component.html

### Code Reproduction URL

https://stackblitz.com/edit/ionic6-angular13-myrtnf?file=src/app/app.component.html

### Ionic Info

Ionic:

   Ionic CLI                     : 7.0.1 (C:\Users\hello\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.5.5
   @angular-devkit/build-angular : 15.1.6
   @angular-devkit/schematics    : 15.1.6
   @angular/cli                  : 15.1.6
   @ionic/angular-toolkit        : 6.1.0

Cordova:

   Cordova CLI       : 11.1.0
   Cordova Platforms : android 11.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 21 other plugins)

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.2

System:

   Android SDK Tools : 26.1.1 (C:\Users\hello\AppData\Local\Android\Sdk)
   NodeJS            : v18.15.0 (C:\Program Files\nodejs\node.exe)
   npm               : 9.5.0
   OS                : Windows 10

**Comment by liamdebeasi** [comment] 2023-04-07 21:51
Thanks for the issue. I am going to close this as this is not a bug in Ionic. In Ionic 7 we changed `debounce` to delay the emission of `ionInput` instead of `ionChange`: https://github.com/ionic-team/ionic-framework/blob/main/BREAKING.md#version-7x-searchbar

This is part of a broader change to have `ionChange` more closely align with the native `change` event. I recommend updating your code to listen for `ionInput` instead as that will allow you to detect each keystroke. Let me know if you have questions.

**Closed by liamdebeasi** 2023-04-07 21:51 UTC
Labels: triage
