### ISSUE TITLE
bug: Resource files not loaded with core

### ISSUE THREAD

**Issue by Mashiane** [ionic-team/ionic-framework#28655] opened 2023-12-06 20:52 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

I am using Ionic core with

https://cdn.jsdelivr.net/npm/@ionic/core/dist/ionic/ionic.esm.js
https://cdn.jsdelivr.net/npm/@ionic/core/dist/ionic/ionic.js
https://cdn.jsdelivr.net/npm/@ionic/core/css/ionic.bundle.css

I am getting a lot of errors about files that are not loaded.

Examples: https://cdn.jsdelivr.net/npm/@ionic/core/dist/ionic/p-b4bad293.system.entry.js
https://cdn.jsdelivr.net/npm/@ionic/core/dist/ionic/p-a0126dd5.system.entry.js

etc

### Expected Behavior

Files should be loaded.

### Steps to Reproduce

Follow the steps of using CDN here.

https://ionicframework.com/docs/intro/cdn

### Ionic Info

As I am not using the CLI, but CDN sorry.

### Additional Information

I hope everything is clear to reproduce the issue.

**Comment by liamdebeasi** [comment] 2023-12-06 21:17
Thanks for the report. This typically happens when the chunk hashes change on release day. For example, we released a new version of Ionic today that likely caused the hashes of each chunk to change. Unfortunately, if you are not pinning the version of Ionic and are loading a cached version of `ionic.js` or `ionic.esm.js` then your app will try to load chunks that no longer exist.

We do [purge the JSDelivr cache](https://github.com/ionic-team/ionic-framework/blob/ec9228f54feaeadb423543c3f83bc6cf2229e1cb/.github/workflows/release.yml#L95-L98) when releasing, but the files in question can be cached elsewhere (such as by the browser).

When loading from a CDN I recommend pinning your version so this does not happen. i.e. `https://cdn.jsdelivr.net/npm/@ionic/core@7.5.7/dist/ionic/ionic.esm.js`.

I'm going to close this since this is caching concern and not a bug in Ionic.

**Closed by liamdebeasi** 2023-12-06 21:17 UTC
Labels: triage
