### ISSUE TITLE
bug: scorm lms api error .

### ISSUE THREAD

**Issue by amantarento** [ionic-team/ionic-framework#27869] opened 2023-07-27 07:07 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v4.x

### Current Behavior

[An error has occured: Error-unable to acquire LMS API, content may not play porperly and results man not be recorded](https://stackoverflow.com/questions/76678561/an-error-has-occured-error-unable-to-acquire-lms-api-content-may-not-play-porp)

### Expected Behavior

how to integrate lms api in ionic 

### Steps to Reproduce

use iframe to load the lms content .

### Ionic Info

Ionic:

   Ionic CLI                     : 6.4.3 (/home/aman/.nvm/versions/node/v14.17.6/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.7.0
   @angular-devkit/build-angular : 0.901.15
   @angular-devkit/schematics    : 8.3.29
   @angular/cli                  : 9.1.15
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : 11.1.0
   Cordova Platforms : android 10.1.2
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 49 other plugins)

Utility:

   cordova-res                          : 0.15.4
   native-run (update available: 1.7.2) : 1.7.1

System:

   Android SDK Tools : 26.1.1 (/home/aman/Android/Sdk)
   NodeJS            : v14.17.6 (/home/aman/.nvm/versions/node/v14.17.6/bin/node)
   npm               : 6.14.15
   OS                : Linux 5.14

### Additional Information

Test

**Comment by sprakashg22** [comment] 2023-07-27 07:12
Yes, we are also facing similar error and looking for an solution on this. Attached screenshot of the error message for reference.
![MicrosoftTeams-image (2)](https://github.com/ionic-team/ionic-framework/assets/89121816/7dd2ddff-f0cb-46c2-9b51-3eeecfa2589a)

**Comment by amandaejohnston** [comment] 2023-07-27 14:21
Thank you for the report. Can you also confirm whether this occurs on Ionic 7.x? Both Ionic 4 and Ionic 5 are no longer supported.

**Comment by amandaejohnston** [comment] 2023-07-27 16:50
Could you create a minimal Github repo demonstrating the issue and post a link to that instead? Having a runnable example will help us determine the source of the issue and whether the fix works down the road. Please also ensure that it uses the latest version of Ionic if possible.

**Comment by amantarento** [comment] 2023-07-27 17:29
@amandaejohnston  i can't use latest version of ionic because in my app there are other dependency also so i have to rely on the version which i have posted earlier.

**Comment by amandaejohnston** [comment] 2023-07-27 17:39
You may need to create a new app from scratch using the `ionic start` command, then add the necessary libraries. Your reproduction should only contain the code necessary to show the problem. It will also help to ensure that the problem only occurs with Ionic installed, as the issue may be in LMS, not Ionic.

**Comment by amantarento** [comment] 2023-07-28 06:37
@amandaejohnston  here we are not able to communicate between iframe and parent window . i have used this https://github.com/DadUndead/ngx-scorm-wrapper wrapper also but it did't work .

**Comment by amandaejohnston** [comment] 2023-07-28 15:07
> hi @amandaejohnston this is my code <iframe #iframeElem title="HTML Content Viewer" i18n-title [src]="iframeUrl" (load)="onIframeLoadOrError('load',iframeElem,$event)" (error)="onIframeLoadOrError('error')" allow="fullscreen; accelerometer; autoplay; encrypted-media; gyroscope; microphone; camera;" class="html-iframe"></iframe> and here iframeUrl i am setting in ts file .here is sample of iframeUrl https://sunbirdcontent.s3-ap-south-1.amazonaws.com/content/html/do_11364358413983744011210-latest/index_lms.html

I noticed that if I open this example URL directly in my browser, I get the same error (screenshot below). Since the error occurs even without Ionic present, I am going to close this as not a bug in Ionic. I would recommend contacting technical support as mentioned in the error message.

![error in browser](https://i.gyazo.com/89fe6d9534087122f8b3c4b52054d9cd.png)

**Comment by amantarento** [comment] 2023-08-01 06:32
@amandaejohnston  you are not able to play this url (' https://sunbirdcontent.s3-ap-south-1.amazonaws.com/content/html/do_11364358413983744011210-latest/index_lms.html') in browser it need set of lms api method in window global variable like LMSInitialize,LMSFinish etc, i have declared this method in service but iframe window is not able to read the parent window and this is happening only in ionic app not in web view of angular .

**Comment by amandaejohnston** [comment] 2023-08-02 15:45
After talking with the team on this, we've agreed that this is more of a support question. I'd recommend asking on the [Ionic forums](https://forum.ionicframework.com/) or [Discord server](https://discord.com/invite/UPYYRhtyzp) for help. Closing this out with that in mind.

**Closed** 2023-08-02 15:45 UTC
Labels: ionitron: support
