### ISSUE TITLE
feat: Add ability to inject components as action sheet items

### ISSUE THREAD

**Issue by bryce13950** [ionic-team/ionic-framework#22027] opened 2020-09-03 21:45 UTC
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

At the moment the action sheet component only allows for a list of buttons with a strict API structure or a string to be passed through. It would be really great if we could pass through a component, so that we can put whatever we want into the action sheet as an option.

**Describe Preferred Solution**

Add React component as an option, and then simply put it into the component.

**Describe Alternatives**

The only thing I can see to do to achieve what I want is to listen to the `onWillPresent` callback, and then insert a bunch of dom elements into the menu node like so...

```
function buildOptions(me: User) {
	const actionSheetGroup = document.getElementById('user-selector-action-sheet')?.querySelector('.action-sheet-group') as HTMLElement;

	actionSheetGroup.innerHTML = '';

	const div = document.createElement('div');
	me.organization_managers?.forEach(organizationManager => {
		const item = document.createElement('div');
		item.innerText = organizationManager.organization.name;
		div.appendChild(item);
	});

	actionSheetGroup.appendChild(div);
}
```

Very very ugly, but it works.

**Related Code**

It would be great if I could setup an action sheet like so...

```
<IonActionSheet
	id={'user-selector-action-sheet'}
	isOpen={accountSwitchingDrawerOpen}
	onDidDismiss={() => setAccountSwitchingDrawerOpen(false)}
	buttons={[
		<IonItem>
			<IonIcon src={'/assets/customicon.svg'} slot={'start'}/>
			A Label
			<IonIcon src={'/assets/anothercustomicon.svg'} slot={'end'}/>
		</IonItem>,
		Another one here...,
		etc...
	]}/>
```

**Additional Context**

**Comment by bryce13950** [comment] 2020-09-03 22:15
After a bit of digging I was able to simplify my solution with ReactDOMServer.renderToString, but again still not ideal...

```
    actionSheetGroup.innerHTML = ReactDOMServer.renderToString(
        <IonList>
            <IonItem>
                {me.full_name}
            </IonItem>
        </IonList>
    );
```

**Comment by liamdebeasi** [comment] 2020-09-03 22:19
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/18067.

**Closed by liamdebeasi** 2020-09-03 22:19 UTC
Labels: triage

**Comment by bryce13950** [comment] 2020-09-03 22:22
Isn't that issue a bit different, since it is more general? This would have to be implemented into every single component with these sort of overlays correct? I could knock out action sheets pretty simply for you guys...

**Comment by liamdebeasi** [comment] 2020-09-04 13:44
The linked issue is pertains to overlay components (which action sheet is part of), but it falls under the same type of work. We have received requests for this in alert, action sheet, etc so we are tracking it in that thread. 

Honestly, we are not very likely to allow for custom components in these overlay components as it goes against the iOS and MD guidelines. However, we plan on adding more guidance on how to customize the modal for these advanced use cases. Additionally, we are adding a drawer-style feature for modals, so something like that could be used here as well when that is released.

**Comment by bryce13950** [comment] 2020-09-04 17:21
Is there an article, or issue that I could follow related to the drawer style?

**Comment by liamdebeasi** [comment] 2020-09-04 17:41
We have not released the drawer-style update yet, but we will be updating our docs with examples once we do.

**Comment by bryce13950** [comment] 2020-09-05 07:57
Is this the issue setup to track this feature? https://github.com/ionic-team/ionic-framework/issues/21039

**Comment by roman-rr** [comment] 2020-09-07 17:32
@bryce13950 Feel free to using this [Solution](https://github.com/roman-rr/cupertino-pane)
