### ISSUE TITLE
bug: Ionic@react IonInput below the half page focus delay

### ISSUE THREAD

**Issue by XueMeijing** [ionic-team/ionic-framework#25015] opened 2022-03-30 08:09 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

When the IonInput component loacated above the half page,  it focus normal. But when it  loacated below the half page, it focus delay. I find an issue similar https://github.com/ionic-team/ionic-framework/issues/20922 . Im not sure whether it is related about keyboard

https://user-images.githubusercontent.com/35559153/160783382-668e7611-f47f-440f-97e9-05c30ac9173c.mp4

### Expected Behavior

IonInput which below the half page focus immediately

### Steps to Reproduce

1.  Add a route page
2. Add IonPage IonContent
3. Add two IonInput

```
<IonPage>
      <IonContent>
        <IonInput placeholder='max'></IonInput>
        <div
          style={{
            margin: 20,
            height: 500
          }}
        >
        </div>
        <IonInput placeholder='max'></IonInput>
      </IonContent>
    </IonPage>
```

### Ionic Info

Ionic:

   Ionic CLI : 6.18.1

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v10.24.1
   npm    : 6.14.12
   OS     : macOS Big Sur

  ─────────────────────────────────────────────────

     Ionic CLI update available: 6.18.1 → 6.19.0
          Run npm i -g @ionic/cli to update

  ─────────────────────────────────────────────────

**Comment by XueMeijing** [comment] 2022-03-30 08:15
Alright,  scrollAssist: false solved this

**Comment by amandaesmith3** [comment] 2022-03-30 13:28
Thanks for the issue. I'm unable to replicate this with the code provided. Could you post a link to a Github repo I could use to replicate?

**Comment by XueMeijing** [comment] 2022-03-31 05:46
> replicate

**Comment by XueMeijing** [comment] 2022-03-31 05:50
> Thanks for the issue. I'm unable to replicate this with the code provided. Could you post a link to a Github repo I could use to replicate?

Maybe u have set scrollAssist: false in app.tsx? You can clone git@github.com:XueMeijing/ionic-test.git and change router to http://localhost:3000/issue25015 to recurrent this issue

**Comment by amandaesmith3** [comment] 2022-04-04 13:56
Thanks! I can reproduce on that repo, but not on the latest version of Ionic. Could you try updating and let me know if you see the same?
```
npm install @ionic/react@latest @ionic/react-router@latest
```

**Comment by XueMeijing** [comment] 2022-04-06 02:17
> Thanks! I can reproduce on that repo, but not on the latest version of Ionic. Could you try updating and let me know if you see the same?
> 
> ```
> npm install @ionic/react@latest @ionic/react-router@latest
> ```

Thanks for your reply. I updated @ionic/react@latest @ionic/react-router@latest and it still happen. setupIonicReact({scrollAssist: false}) makes IonInput works well currently. But this is config seems relation to keyboard. I'm not sure it still works well after capacitor it to app. If that happens, i will create a new issue to let you know

**Comment by amandaesmith3** [comment] 2022-04-06 13:51
What browser version are you using?

**Comment by XueMeijing** [comment] 2022-04-07 07:56
> What browser version are you using?

chrome 99.0.4844.51 (arm64)

**Comment by liamdebeasi** [comment] 2022-04-07 15:25
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/23664.

**Closed by liamdebeasi** 2022-04-07 15:25 UTC
Labels: triage
