### ISSUE TITLE
bug: Ion-header become black when open ion-modal

### ISSUE THREAD

**Issue by Saqib92** [ionic-team/ionic-framework#24906] opened 2022-03-09 07:34 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

`ion-header` becomes `black` when open `ion-modal`. in my case i am using card modal. 

### Expected Behavior

it should not become `black`. 
In my actual project i noticed that opening card modal my header becomes black and a style attribute added on body tag and on closing its not getting removed. 
but in my Example project I have produced same issue but the difference is in example project style tag getting removed from body after closing modal but for a second it stays `black`. 

### Steps to Reproduce

using ionic header on page and ion-modal (card style). open modal header become `black `and stay `black` after closing modal. 

### Code Reproduction URL

https://github.com/Saqib92/ionic-header-black-issue

### Ionic Info

```
Ionic:

   Ionic CLI                     : 6.18.2 (/Users/fahadaslam/.nvm/versions/node/v16.13.1/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.10
   @angular-devkit/build-angular : 13.2.5
   @angular-devkit/schematics    : 13.2.5
   @angular/cli                  : 13.2.5
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.4.3
   @capacitor/android : not installed
   @capacitor/core    : 3.4.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v16.13.1 (/Users/fahadaslam/.nvm/versions/node/v16.13.1/bin/node)
   npm    : 8.1.2
   OS     : macOS Monterey
```

### Additional Information

this is happening from `v6.0.0` to `v6.0.10` in all 6x versions this is happening.

**Comment by liamdebeasi** [comment] 2022-03-09 14:04
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. When opening the card modal, we set the `body` background color to black so it matches the native iOS behavior. You have the following CSS in your app:

```css
ion-toolbar {
    --background: transparent;
}
```

This sets the toolbar backgrounds to be transparent. As a result, the black you are seeing is the `body` background color. The toolbars themselves are not turning black.

**Closed by liamdebeasi** 2022-03-09 14:04 UTC
Labels: triage

**Comment by Saqib92** [comment] 2022-03-09 14:18
What should i do if i want to have transparent header or same color as ion-content?
