### ISSUE TITLE
bug: Ionic/Angular Singleton Service does not work when moving forward from Page to Page

### ISSUE THREAD

**Issue by jepiqueau** [ionic-team/ionic-framework#22604] opened 2020-12-01 10:57 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.5.1**

**Current behavior:**

After having defined a singleton service in the app.module.ts when moving forward from Page to Page, the service is reinitialized and then not act as a singleton service. When moving from a Page backward to the previous Page the service is acting as a singleton service.
It seems that the app.component is rerun each time you open a new page or move forward from one page to another page which is wrong and not when you move backward which is right.

**Expected behavior:**

The service should not reinitialize

**Steps to reproduce:**

A Ionic/Angular  well documented and demonstrating the bug is on Github `https://github.com/jepiqueau/test-singleton-service`

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```
```
Ionic:

   Ionic CLI                     : 6.12.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.5.1
   @angular-devkit/build-angular : 0.1100.2
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Capacitor:

   Capacitor CLI   : 2.4.3
   @capacitor/core : 2.4.3

Utility:

   cordova-res                          : not installed
   native-run (update available: 1.2.2) : 0.3.0

System:

   NodeJS : v12.18.3 (/usr/local/bin/node)
   npm    : 6.14.9
   OS     : macOS Big Sur


```

**Comment by liamdebeasi** [comment] 2020-12-01 14:26
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The problem here is that you are using `href` to navigate to your pages which is going to cause a full page reload. As a result, every time you navigate forward your service (and entire app) will be reinitialized. If you want to navigate forward as a single page app, you can either use the `Router` dependency injection or use the `routerLink` property on `ion-button`:

So instead of:

```html
<ion-button
  [href]="'./test-page-a'" 
  routerDirection="forward" 
  color='primary' 
  expand="block"
>Tests</ion-button>
```

You could do:

```html
<ion-button 
  routerLink='/test-page-a' 
  routerDirection="forward" 
  color='primary' 
  expand="block"
>Tests</ion-button> 
```

**Closed by liamdebeasi** 2020-12-01 14:26 UTC
Labels: triage

**Comment by jepiqueau** [comment] 2020-12-01 16:08
@liamdebeasi Thank you so much , i did not know. I learned something today so it is great
