### ISSUE TITLE
bug: click listener taking time to respond 

### ISSUE THREAD

**Issue by indraraj26** [ionic-team/ionic-framework#22177] opened 2020-09-25 16:06 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

When i click on go to search button it is taking time to route to search-box
Repo: https://github.com/indraraj26/ionic5-starter-tabs-sidemenu/tree/click-listener
reproduce: 
1. ionic serve
2. click on go to otp
3. click on go to home
4. click on go to search
5. then back
6. click on go to search

repeat 4, 5, 6 step 

**Expected behavior:**

When you click on search button it should route instantly

**Steps to reproduce:**

**Related code:**
![image](https://user-images.githubusercontent.com/23274631/94288952-abfd9280-ff75-11ea-97f8-ead530f8cfa8.png)

![image](https://user-images.githubusercontent.com/23274631/94289882-077c5000-ff77-11ea-981e-5414ed07663c.png)

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
ionic info

Ionic:

   Ionic CLI                     : 6.11.0 (C:\Users\indra26\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.3.2
   @angular-devkit/build-angular : 0.1000.8
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : android 9.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 6 other plugins)

Utility:

   cordova-res : 0.15.1
   native-run  : 1.0.0

System:

   Android SDK Tools : 26.1.1 (C:\Users\indra26\AppData\Local\Android\Sdk)
   NodeJS            : v10.16.3 (C:\Program Files\nodejs\node.exe)
   npm               : 6.9.0
   OS                : Windows 10

```

**Comment by liamdebeasi** [comment] 2020-09-25 17:21
Thanks for the issue. What device are you testing this on? I am getting a ~180ms initial load for the page, but subsequent visits to the page are fine.

**Comment by indraraj26** [comment] 2020-09-25 18:52
i have tested on chrome desktop browser as well as on device with android 7.1.2 chrome engine 85 something.
Everything is up to date.

**Comment by liamdebeasi** [comment] 2020-09-25 18:53
What kind of Android device?

**Comment by indraraj26** [comment] 2020-09-25 19:05
Redmi 4A (Mi brand)
![Screenshot_2020-09-26-00-34-15-471_com android settings](https://user-images.githubusercontent.com/23274631/94306183-1de2d580-ff90-11ea-8838-f2fdd4c2bf05.png)

**Comment by indraraj26** [comment] 2020-09-28 07:41
From browser mobile mode 

if you select pixel 2 device 
output: 
![image](https://user-images.githubusercontent.com/23274631/94399356-d6716a80-0184-11eb-98c3-8b5312584133.png)

if you select Galaxy S5 device 
output: 
![image](https://user-images.githubusercontent.com/23274631/94399658-6d3e2700-0185-11eb-8a1b-61b4120cea7b.png)

If you replace ion-row and ion-col with div only first navigation you might get ~180ms and subsequent visit to search-box is working fine.

====================================================

From my physical device android redmi 4a 7.12
![image](https://user-images.githubusercontent.com/23274631/94404028-f2c4d580-018b-11eb-847e-4c9f178a6122.png)

**Comment by indraraj26** [comment] 2020-09-30 12:00
Hey @liamdebeasi , 

what might be the issue ?

Thank you

**Comment by indraraj26** [comment] 2020-10-19 09:29
Hi, 

Ionic team any updates ? what could be the issue ?

Thank You

**Comment by liamdebeasi** [comment] 2020-10-19 20:05
Hi there,

We've been looking at this, and it looks like something in Angular is causing this issue. We are going to get in touch with an Angular team member to get a better idea of what is going on and will provide an update here when we have it.

**Comment by JosepAlacid** [comment] 2021-03-03 13:30
This issue is an "atomic" one. It's been thru Ionic v3 without any improvement.

**Comment by liamdebeasi** [comment] 2022-02-24 15:12
Thanks for the issue, and apologies for the delay. After updating to the latest versions of Ionic and Angular, I am no longer able to reproduce this behavior.

I am going to close this, but if you run into this again please feel free to open another issue with a code reproduction. Thanks!

**Closed by liamdebeasi** 2022-02-24 15:12 UTC
Labels: triage
