### ISSUE TITLE
bug: ion-popover mysteriously disappears

### ISSUE THREAD

**Issue by Staon** [ionic-team/ionic-framework#23139] opened 2021-04-03 18:06 UTC
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
The ion-popover disappears even though the `isOpen` property is true.

**Expected behavior:**
The ion-popover is still shown.

**Steps to reproduce:**

- Open the example application below.
- Enter the input component and start typing something. The popover should appear.
- Press the `Enter` key - the content of the input field should be reset. The popover "blinks" - it's turned off and turned on. Unfortunately, after a while the popover disappears again although the `isOpen` flag is true.

**Related code:**

Example application: https://github.com/Staon/ionic-bug2

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.13.1 (/home/staon/.nvm/versions/node/v15.10.0/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.6.3

Capacitor:

   Capacitor CLI   : 2.4.7
   @capacitor/core : 2.4.7

Utility:

   cordova-res : 0.15.3
   native-run  : 1.3.0

System:

   NodeJS : v15.10.0 (/home/staon/.nvm/versions/node/v15.10.0/bin/node)
   npm    : 7.5.3
   OS     : Linux 5.8
```

**Comment by liamdebeasi** [comment] 2021-04-05 13:38
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The problem here is that when you press "Enter", you run the following code:

```tsx
setState({
  showPopover: false,
  value: ''
})
```

While this does dismiss the popover, you are also updating the value of `ion-input`, causing `ionChange` to fire and another popover to open. To account for this, you should keep the state value the same.

**Closed by liamdebeasi** 2021-04-05 13:38 UTC
Labels: triage
