### ISSUE TITLE
bug: footer not working anymore inside a modal

### ISSUE THREAD

**Issue by natqe** [ionic-team/ionic-framework#24364] opened 2021-12-10 09:57 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

when placing ion-footer inside of ion-modal it should work properly with ion-content like ion-header does, but version 6 changes broke it, and now it not showing.

### Expected Behavior

when placing ion-footer inside of ion-modal it should work properly with ion-content

### Steps to Reproduce

create ion modal containing ion-header ion-content and ion-footer. ion-footer will be off of the screen

**Comment by liamdebeasi** [comment] 2021-12-10 13:55
Thanks for the issue. Can you please reproduce this in an Ionic starter app and provide a link to the repo? I cannot reproduce this in an Ionic 6 app.

**Comment by natqe** [comment] 2021-12-10 13:58
hi @liamdebeasi, i manage to fix it by wrapping 'IonModal' content with 'IonPage'. seems that in version 6 wrapping ionModal content with 'IonPage' is required. it will be perfect if it will be in the docs (currently without IonPage wrapper)

**Comment by liamdebeasi** [comment] 2021-12-13 14:22
Glad the issue is fixed, but can you still reproduce the issue in a starter app and provide a link to the repo? I am not seeing this happen on my end -- the content inside of a modal should automatically be wrapped with an `.ion-page` class.

**Comment by natqe** [comment] 2021-12-14 18:02
@liamdebeasi Yeah, is add it automatically when using `useIonModal` but not when using it as a jsx via `<IonModal>`

**Comment by alexlopezit** [comment] 2021-12-19 01:41
> @liamdebeasi Yeah, is add it automatically when using `useIonModal` but not when using it as a jsx via `<IonModal>`

I can confirm this issue after upgrading to Ionic 6, and thanks for the workaround of using IonPage

**Comment by jameson-w-taylor** [comment] 2022-01-04 20:04
The `<IonPage>` workaround did work for me, and here's a reproduction of the issue ([link](https://github.com/jameson-w-taylor/v6-ion-modal-bug)).

`<IonFooter>` appears to be rendering outside of the modal content area.

**Comment by liamdebeasi** [comment] 2022-01-06 21:17
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/24510, and a fix will be available in an upcoming release of Ionic Framework.

**Closed by liamdebeasi** 2022-01-06 21:17 UTC
Labels: triage
