### ISSUE TITLE
bug: The next page is displayed before the previous page is gone

### ISSUE THREAD

**Issue by lucasbaylon** [ionic-team/ionic-framework#28721] opened 2023-12-18 17:44 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When changing pages, the content of the next page is displayed, while the content of the page I was on still hasn't disappeared.

The problem seems to appear when I add common core between several pages, in this case, css, or when I modify the background of my pages ?!

### Expected Behavior

The navigation must be done with a clean transition and the elements of the first page must disappear at the same time as those of the second page appear.

### Steps to Reproduce

Just like me, add this :
ion-content {
    --background: none;
}
to the global.scss file

### Code Reproduction URL

https://github.com/lucasbaylon/ionic-bug

### Ionic Info

Ionic:

   Ionic CLI                     : 7.1.5
   Ionic Framework               : @ionic/angular 7.6.1
   @angular-devkit/build-angular : 17.0.7
   @angular-devkit/schematics    : 17.0.7
   @angular/cli                  : 17.0.7
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.6.0
   @capacitor/android : not installed
   @capacitor/core    : 5.6.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 2.0.0

System:

   NodeJS : v18.18.2 (C:\Program Files\nodejs\node.exe)
   npm    : 9.8.1
   OS     : Windows 10

### Additional Information

the problem disappears if I remove "background: none" from my "ion-content" tag in my global.scss file, but I have to leave this code to allow the correct display of my animation, located in the "app. component.html".

The problem also disappears if I remove the animation when changing a page ( IonicModule.forRoot({ animated: false}) in my app.module.ts ) but I want to keep this animation

Here is a preview of the animation bug :
![chrome_auLF7VTPHe](https://github.com/ionic-team/ionic-framework/assets/36708187/3cd0dbd3-88ec-4e2d-bab3-9bc268ff8312)

**Comment by liamdebeasi** [comment] 2023-12-18 17:51
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. This is by design. The new page appears on top of the old page and then animates up. Once the animation is done, the old page is hidden.

Your application removes the background color of the new page which means that you can see "underneath" the new page. As a result, you are seeing the old page. Typically the new page's content has a background color so the old page appears to fade out.

**Closed by liamdebeasi** 2023-12-18 17:51 UTC
Labels: triage

**Comment by lucasbaylon** [comment] 2023-12-18 18:00
@liamdebeasi Okay I understand, thanks for your feedback and sorry for opening an issue for that.

Good day
