### ISSUE TITLE
feat: Angular 12 support

### ISSUE THREAD

**Issue by mhartington** [ionic-team/ionic-framework#23298] opened 2021-05-12 23:34 UTC
_it's been out for 10 minutes now_

**Comment by liamdebeasi** [comment] 2021-05-12 23:35
_mike_

**Comment by UTSOURCE** [comment] 2021-05-13 07:52
use  ionic build --prod --release

`⠋ Generating index html...10 rules skipped due to selector errors:
  :host-context([dir=rtl]) .ion-float-start -> unmatched pseudo-class :host-context
  :host-context([dir=rtl]) .ion-float-end -> unmatched pseudo-class :host-context
  :host-context([dir=rtl]) .ion-float-sm-start -> unmatched pseudo-class :host-context
  :host-context([dir=rtl]) .ion-float-sm-end -> unmatched pseudo-class :host-context
  :host-context([dir=rtl]) .ion-float-md-start -> unmatched pseudo-class :host-context
  :host-context([dir=rtl]) .ion-float-md-end -> unmatched pseudo-class :host-context
  :host-context([dir=rtl]) .ion-float-lg-start -> unmatched pseudo-class :host-context
  :host-context([dir=rtl]) .ion-float-lg-end -> unmatched pseudo-class :host-context
  :host-context([dir=rtl]) .ion-float-xl-start -> unmatched pseudo-class :host-context
  :host-context([dir=rtl]) .ion-float-xl-end -> unmatched pseudo-class :host-context
✔ Index html generation complete.`

**Comment by mhartington** [comment] 2021-05-13 14:26
> ⠋ Generating index

@UTSOURCE this is not an issue. What you're seeing is just a notice. The css that is being printed out is included in the final output, just not inlined in the index.html. All good.

**Comment by Zeratoxx** [comment] 2021-05-17 13:28
Is it safe to use Angular 12?

**Comment by kirillgroshkov** [comment] 2021-05-17 15:58
> it's been out for 10 minutes now

Is this project DEAD?

just kidding:)

Just updated our medium-sized project to Angular 12, and, despite `peerDependencies` warnings (and having to specify package.json `resolutions: "@schematics/angular": "^12.0.0"`) - all worked well for us!

Yes, also needed to update our custom webpack config (from `ngx-build-plus`) to use Webpack5 syntax for IgnorePlugin.

So, high chance that just bumping allowed dependencies/peerDependencies in Ionic will do the job!

**Comment by UTSOURCE** [comment] 2021-05-18 01:05
@Zeratoxx  Very safe, seamless upgrade

**Comment by Sampath-Lokuge** [comment] 2021-05-19 09:01
Hello Mike, Will, we have official support for Angular 12 soon?

**Comment by UTSOURCE** [comment] 2021-05-19 09:03
@Sampath-Lokuge It's been supported

**Comment by Sampath-Lokuge** [comment] 2021-05-19 09:19
@UTSOURCE No. Still default template has ` "@angular/core": "~11.2.0",`. I need it to be `12.0.0`. That is why I have mentioned official support here.

**Comment by Sampath-Lokuge** [comment] 2021-05-19 16:00
Ok sure. Thanks a lot for the info!

**Comment by tgangso** [comment] 2021-05-20 11:26
Angular 12 seems to work fine, but my rebuild time between changes have become huge. HMR activated, and pretty sure I am using dev mode, but feels like prod build times. Any suggestions?

Example, changing one line in a .ts file:
`Initial Chunk Files                                 | Names   |     Size
main.js, 179.d8f9ae9a2d8bb958e50c.hot-update.js     | main    |  3.71 MB
runtime.js, 3666.d8f9ae9a2d8bb958e50c.hot-update.js | runtime | 13.61 kB

117 unchanged chunks

Build at: 2021-05-20T11:23:58.186Z - Hash: 9e878e9778e3216255f5 - Time: 53842ms

Warning: 10 rules skipped due to selector errors:
  :host-context([dir=rtl]) .ion-float-start -> unmatched pseudo-class :host-context
  :host-context([dir=rtl]) .ion-float-end -> unmatched pseudo-class :host-context
  :host-context([dir=rtl]) .ion-float-sm-start -> unmatched pseudo-class :host-context
  :host-context([dir=rtl]) .ion-float-sm-end -> unmatched pseudo-class :host-context
  :host-context([dir=rtl]) .ion-float-md-start -> unmatched pseudo-class :host-context
  :host-context([dir=rtl]) .ion-float-md-end -> unmatched pseudo-class :host-context
  :host-context([dir=rtl]) .ion-float-lg-start -> unmatched pseudo-class :host-context
  :host-context([dir=rtl]) .ion-float-lg-end -> unmatched pseudo-class :host-context
  :host-context([dir=rtl]) .ion-float-xl-start -> unmatched pseudo-class :host-context
  :host-context([dir=rtl]) .ion-float-xl-end -> unmatched pseudo-class :host-context



√ Compiled successfully.`

**Comment by godenji** [comment] 2021-05-23 08:02
I know the OP was joking in opening this issue so soon after the Angular 12 release, but what is the rationale for Ionic itself still supporting Angular 8.x? Presumably the footprint of Ionic + Angular would be reduced with latest Ivy improvements...

Supporting, for example, the last 3 major Angular versions would encourage users to upgrade both Angular and Ionic, rather than sticking with outdated versions of Angular that effectively penalize those that keep up-to-date with their dependencies.

**Comment by entrymon** [comment] 2021-05-24 08:01
Angular 12 builds Ionic project in prod mode, making dev builds slower and hard to debug any solutions? https://stackoverflow.com/questions/67594497/build-in-dev-mode-for-angular-12

**Comment by davidgeary** [comment] 2021-05-24 10:37
Ionic support for Angular 12 is not just a case of updating the `package.json` dependency versions.

As per [this issue](https://github.com/angular/angular-cli/issues/14471), Angular now defaults to the production config for builds, but the dev config for 'serve', so the `architect` targets in `angular.json` will need reviewing accordingly (as may the `scripts` commands in `package.json`).

**Comment by liamdebeasi** [comment] 2021-05-24 12:50
> I know the OP was joking in opening this issue so soon after the Angular 12 release, but what is the rationale for Ionic itself still supporting Angular 8.x? Presumably the footprint of Ionic + Angular would be reduced with latest Ivy improvements...
> 
> Supporting, for example, the last 3 major Angular versions would encourage users to upgrade both Angular and Ionic, rather than sticking with outdated versions of Angular that effectively penalize those that keep up-to-date with their dependencies.


Dropping support for Angular 8.x requires a breaking change to Ionic Framework, so we can only do those with major releases. For Ionic Framework v6 we do plan on updating the minimum required version.

**Comment by godenji** [comment] 2021-05-25 01:42
> For Ionic Framework v6 we do plan on updating the minimum required version.

Good to hear, thanks for the update.

**Comment by almothafar** [comment] 2021-05-26 13:32
I can confirm that it seems this is working fine, but there is a warning that might affect RTL versions #23367

**Comment by almothafar** [comment] 2021-05-27 09:23
OK, it is working fine in development, but in build running the command `ionic build --prod --engine=browser -- --configuration=production --verbose` is not working and failing.

```
LOG from webpack.ModuleConcatenationPlugin
<t> select relevant modules: 4.4328 ms
<t> sort relevant modules: 0.9297 ms
<t> find modules to concatenate: 273.6482 ms
<t> sort concat configurations: 0.0912 ms
<t> create concatenated modules: 81.109 ms
+ 3 hidden lines

LOG from webpack.FileSystemInfo
    1304 new snapshots created
    0% root snapshot uncached (0 / 0)
    0% children snapshot uncached (0 / 0)
    0 entries tested
    File info in cache: 687 timestamps 687 hashes 687 timestamp hash combinations
    File timestamp hash combination snapshot optimization: 48% (1439/3003) entries shared via 49 shared snapshots (277 times referenced)
    Directory info in cache: 1 timestamps 0 hashes 0 timestamp hash combinations
    Directory timestamp snapshot optimization: 0% (0/1) entries shared via 0 shared snapshots (0 times referenced)
    Managed items info in cache: 96 items
    Managed items snapshot optimization: 48% (1252/2588) entries shared via 13 shared snapshots (526 times referenced)
    Managed files snapshot optimization: 55% (2574/4705) entries shared via 15 shared snapshots (416 times referenced)
    Managed contexts snapshot optimization: 0% (0/2) entries shared via 0 shared snapshots (0 times referenced)

WARNING in [DedupeModuleResolvePlugin]: \mobile-app\node_modules\@ionic-super-tabs\angular\node_modules\tslib\tslib.es6.js -> \mobile-app\node_modules\@ionic\angular\node_modules\tslib\tslib.es6.js

WARNING in [DedupeModuleResolvePlugin]: \mobile-app\node_modules\@ionic\storage\node_modules\tslib\tslib.es6.js -> \mobile-app\node_modules\@ionic\angular\node_modules\tslib\tslib.es6.js

2021-05-27 12:11:21: webpack 5.36.2 compiled in 187579 ms (239dcfe4f24c41787bf2)
× Index html generation failed.
undefined:115:483316: property missing ':'
[ERROR] An error occurred while running subprocess ng.

        ng.cmd run app:build:prod --verbose exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.
  ionic:utils-process onBeforeExit handler: 'process.exit' received +0ms
  ionic:utils-process onBeforeExit handler: running 1 functions +1ms
  ionic:utils-process error while killing process tree for 3344: Error: Command failed: taskkill /pid 3344 /T /F
  ionic:utils-process ERROR: The process "3344" not found.
  ionic:utils-process
  ionic:utils-process     at ChildProcess.exithandler (node:child_process:326:12)
  ionic:utils-process     at ChildProcess.emit (node:events:365:28)
  ionic:utils-process     at maybeClose (node:internal/child_process:1067:16)
  ionic:utils-process     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5) {
  ionic:utils-process   killed: false,
  ionic:utils-process   code: 128,
  ionic:utils-process   signal: null,
  ionic:utils-process   cmd: 'taskkill /pid 3344 /T /F'
  ionic:utils-process } +124ms
  ionic:utils-process onBeforeExit handler: error from function: Error: Command failed: taskkill /pid 3344 /T /F
  ionic:utils-process ERROR: The process "3344" not found.
  ionic:utils-process
  ionic:utils-process     at ChildProcess.exithandler (node:child_process:326:12)
  ionic:utils-process     at ChildProcess.emit (node:events:365:28)
  ionic:utils-process     at maybeClose (node:internal/child_process:1067:16)
  ionic:utils-process     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5) {
  ionic:utils-process   killed: false,
  ionic:utils-process   code: 128,
  ionic:utils-process   signal: null,
  ionic:utils-process   cmd: 'taskkill /pid 3344 /T /F'
  ionic:utils-process } +3ms
  ionic:utils-process processExit: exiting (exit code: 1) +2ms
```

I reverted back to 11 and it is worked again.

What is the problem? how do I know that?

**Comment by meriturva** [comment] 2021-05-27 09:39
@almothafar issue is related to new feature called: inline critical CSS . try to disable it on angular.json file:

`"optimization": {"fonts": true, "scripts": true, "styles":{"minify":true,"inlineCritical":false}},`

seems It doesn't play well with embedded svg as background on css.

**Comment by almothafar** [comment] 2021-05-27 10:32
@meriturva that worked, thank you

**Comment by Frodriguez9** [comment] 2021-05-29 23:30
Hey guys, I am working on a project for the Udacity full-stack nanodegree. They used Angular for the front end, and for some reason, nothing is displayed on the client's site. I don't get any errors on my server-side either. The behavior is really strange and no mentor in the program has been able to help. I am an amateur so I don't know what else to try. 

Can anyone take a look at my repository and see if the problem can be replicated and what the solution is:

https://github.com/Frodriguez9/coffee-shop

Thank you so much in advance!

**Comment by bampakoa** [comment] 2021-06-01 19:50
Just tried the new Angular templates and the `package.json` file uses Angular 12 🥳

**Comment by almothafar** [comment] 2021-06-03 15:31
I noticed another issue, that all code now in a single main.js file instead of separated files for each component during development, I'm not sure what the issue is right now, but I believe it is something needed to be fixed in angular.json.

**Comment by mhartington** [comment] 2021-06-03 15:47
@almothafar Any sample project we could look at?

**Comment by Yohandah** [comment] 2021-06-07 12:21
Updating my project to Angular 12 caused an issue for me :

```
./node_modules/safe-buffer/index.js:2:13-30 - Error: Module not found: Error: Can't resolve 'buffer' in 'C:\Users\x\Documents\dev\x\x\x\frontend\node_modules\safe-buffer'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "buffer": require.resolve("buffer/") }'
        - install 'buffer'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "buffer": false }
```

Looks like because it upgraded to Webpack 5 and `Ionic 5` depends on `@angular-devkit/schematics` 11.2.13 that depends on `ora` 5.3 that depends on `bl` 4.0.3 that depends on `buffer` 5.7.1 ?

**Comment by roman-rr** [comment] 2021-06-09 18:53
@Yohandah 
```
npm i buffer
```

 **angular.json**
```json
"build": {
    "options": {
    ...
    "allowedCommonJsDependencies": ["buffer"]
  }
```

**tsconfig.json**
```json
"compilerOptions": {
    ...
    "paths": {
      "buffer": ["node_modules/buffer"]    
    }
}
```

**Comment by Yohandah** [comment] 2021-06-10 08:35
@roman-rr Yeah sure that's how I fixed it but I would've preferred not to add a "useless" dependency to my project

**Comment by Sampath-Lokuge** [comment] 2021-06-10 08:39
@Yohandah @roman-rr Yes, we MUST not do that. We need an official/proper solution here.

**Comment by almothafar** [comment] 2021-06-10 12:41
@mhartington never mind my issue, I found the problem, it was something seems missing and the default value probably got changed, so just for reference, I created a new ionic app (which is angular 12 and does not have that issue) and compared that angular,json with mine, the following configuration was missing from my version (or different) so I added/modified them:

```json
{
  "projects": {
    "app": {
    ...
      "architect": {
        "build": {
         "options": {
           ...
            "vendorChunk": true,
            "buildOptimizer": false,
            "sourceMap": true,
            "optimization": false,
            "namedChunks": true,
    ...
}
```

**Comment by mhartington** [comment] 2021-06-10 13:34
@Yohandah @roman-rr not sure how you all updated, but buffer shouldn't be an issue here.

Based off a few starters projects which I've updated, this only seems to be an issue when your package.json has `@angular-devkic/schematics` listed, which Ionic project should not have.


@Sampath-Lokuge 

> It is almost 1 month.

Yes, and most people have been able to update without issue. Please realize that there is only so many hours in a day. If you'd like an issue resolved faster, please submit a pull request.

**Comment by monurakkaya** [comment] 2021-06-13 11:53
Weirdest bug is coming from me. 

When I run `ionic serve` Webstorm seems drop support of ionic tags in html files. 

I remove node_modules and package.lock file then run npm install,  It seems like fix the problem but when I serve again, it happening again :/

**Comment by Yohandah** [comment] 2021-06-14 15:56
It was @angular-devkit/architect causing the issue for me, I can't remember why it was in my package.json, and everything seems to be working fine without it. I was the occasion to do a nice clean-up in my dependencies. Thanks

**Comment by martinmitteregger** [comment] 2021-06-16 14:36
@monurakkaya i have the same problem - very annoying :-(

**Comment by tn185070** [comment] 2021-06-21 21:08
min/max validation is not working on ion-inputs of type number. #20163 and #18240 reported this previously but at that time the issues were closed because it was a bug in Angular. Now Angular has fixed their bug in https://github.com/angular/angular/pull/39063 but the validation is still not working for ion-inputs. If I change `ion-input` to a `input` then the validation works.

**Comment by liamdebeasi** [comment] 2021-06-21 21:14
@tn185070 This does not seem to be related to Angular 12 support. Can you create a separate issue with a code reproduction?

**Comment by tn185070** [comment] 2021-06-21 21:15
@liamdebeasi sure. I thought it might be related because this was a fix added to angular 12.

**Comment by liamdebeasi** [comment] 2021-06-21 21:17
Ah that's fair. This thread is mainly focused on issues upgrading to Angular 12 (I.e. your app no longer works after the upgrade but worked before the upgrade)

Once you create the issue I will definitely take a look. Thank you!

**Comment by liamdebeasi** [comment] 2021-06-21 21:17
Hi everyone,

It has been about a month and most of the Angular 12-specific issues have been resolved in Ionic Framework. The lingering issues in this thread appear to unrelated to the Angular 12 upgrade and look to be issues with outdated or mismatched dependencies.

We are going to close and lock this issue. Moving forward any Angular 12 issues should be filed in their own issue at https://github.com/ionic-team/ionic-framework/issues/new/choose. Thank you!

**Closed by liamdebeasi** 2021-06-21 21:17 UTC
Labels: package: angular, type: feature request
