### ISSUE TITLE
feat: Add support to lock sheet modal height at set breakpoint

### ISSUE THREAD

**Issue by bot101** [ionic-team/ionic-framework#25641] opened 2022-07-15 08:11 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

The sheet modal currently allows setting a new breakpoint after it has been presented, but this cannot be locked in place and the sheet will grow in height if the user attempts to scroll a list or date (month view). This feature request is to suggest adding a method to `HTMLIonModalElement` that enables/disables changing modal breakpoint.

### Describe the Use Case

When attempting to scroll through a child element like `ion-datetime` in `month-year` presentation, 

### Describe Preferred Solution

Add a `HTMLIonModalElement.lockBreakpoint(boolean?)` that enables/disables breakpoint height changes  

### Related Code

```
async showTimelist() {
    if (this.rangeType === 'custom') {
      const modal = await this.modalCtrl.getTop();
      modal.setCurrentBreakpoint(1);
      modal.lockBreakpoint(true);
    }
 }

async onDateClick() {
    const modal = await this.modalCtrl.getTop();
    modal.lockBreakpoint();
  }

  async onDateBlur() {
    const modal = await this.modalCtrl.getTop();
    modal.lockBreakpoint(false);
  }

```

**Comment by bot101** [comment] 2022-07-17 18:23
@liamdebeasi Here is a demo repo: https://github.com/bot101/bottomsheet-demo. Attached also is a video that shows current behavior.

[screencast-localhost_8100-2022.07.17-18_53_35.webm](https://user-images.githubusercontent.com/8009733/179418714-d4737b8b-6397-41bf-b9a8-4b14d868c817.webm)

**Comment by EinfachHans** [comment] 2022-07-19 12:58
Duplicate of #24631 i guess? 😊

**Closed** 2022-07-19 13:48 UTC
Labels: triage
