### ISSUE TITLE
bug: ion-datetime - Infinite scroll to left

### ISSUE THREAD

**Issue by prathyushp1** [ionic-team/ionic-framework#24507] opened 2022-01-04 07:05 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

 <ion-datetime mode="ios" presentation="date" hour-cycle="h12" size="cover" [(ngModel)]="dateFromIonDatetime"
    style="margin-bottom: 10px;direction: rtl;" >
  </ion-datetime>

### Expected Behavior

 <ion-datetime mode="ios" presentation="date" hour-cycle="h12" size="cover" [(ngModel)]="dateFromIonDatetime"
    style="margin-bottom: 10px;direction: rtl;" >
  </ion-datetime>

### Steps to Reproduce

create new project and add this code

problem white using  style : direction "RTL"

 <ion-datetime mode="md" presentation="date" hour-cycle="h12" size="cover" [(ngModel)]="dateFromIonDatetime"
    style="margin-bottom: 10px;direction: rtl;" >
  </ion-datetime>

### Ionic Info

[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package'
       
       Require stack:
       - /usr/local/lib/node_modules/@ionic/cli/lib/project/index.js
       - /usr/local/lib/node_modules/@ionic/cli/lib/index.js
       - /usr/local/lib/node_modules/@ionic/cli/index.js
       - /usr/local/lib/node_modules/@ionic/cli/bin/ionic
[WARN] Error loading @capacitor/android package.json: Error: Cannot find module '@capacitor/android/package'
       
       Require stack:
       - /usr/local/lib/node_modules/@ionic/cli/lib/project/index.js
       - /usr/local/lib/node_modules/@ionic/cli/lib/index.js
       - /usr/local/lib/node_modules/@ionic/cli/index.js
       - /usr/local/lib/node_modules/@ionic/cli/bin/ionic

Ionic:

   Ionic CLI                     : 6.18.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.1
   @angular-devkit/build-angular : 13.0.4
   @angular-devkit/schematics    : 13.0.4
   @angular/cli                  : 13.0.4
   @ionic/angular-toolkit        : 5.0.3

Capacitor:

   Capacitor CLI      : 3.3.3
   @capacitor/android : not installed
   @capacitor/core    : 3.3.3
   @capacitor/ios     : not installed

Utility:

   cordova-res (update available: 0.15.4) : 0.15.3
   native-run                             : 1.5.0

System:

   NodeJS : v14.17.3 (/usr/local/bin/node)
   npm    : 7.19.1
   OS     : macOS Big Sur

**Comment by sean-perkins** [comment] 2022-01-04 15:28
Duplicate of #24472.

PR to address this is being tracked here: #24475. Thanks!

**Closed by sean-perkins** 2022-01-04 15:28 UTC
Labels: holiday triage
