### ISSUE TITLE
feat: ion-refresher ionEnd event

### ISSUE THREAD

**Issue by piotr-cz** [ionic-team/ionic-framework#29580] opened 2024-06-03 07:21 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/docs/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

On desktop while using _ion-refresh_ component, content is being selected
Example: [Docs > Ion-refresher > Basic Usage](https://ionicframework.com/docs/api/refresher#basic-usage)

This can be indirectly handled by adding an event like `ionEnd` to component that would be triggered when pull action ends.

### Describe the Use Case

As in description

### Describe Preferred Solution

The ion-refresher component can trigger additional event that would trigger when pulling action ends.

This already happens with `ionRefresh` event, however only when handle is pulled far enough to refresh and not when action is cancelled.

It would then be possible to set `user-select` property on content as in example below

### Describe Alternatives

none

### Related Code

```tsx
import { usState } from 'react'

export const Example = () => {
  const [isPulling, setIsPulling] = useState<boolean>(false)

  return (
    <IonPage>
      <IonRefresher
        ionStart={() => setIsPulling(true)}
        ionEnd={() => setIsPulling(false)}
      >
        <IonRefreshContent />
      </IonRefresher>

      <IonContent style={{ 'user-select': isPulling ? 'none' : 'initial' }}>
        Hello World
      </IonContent>
    </IonPage>
  )
}
```

### Additional Information

none

**Comment by brandyscarney** [comment] 2024-06-06 21:52
Thanks for the issue! This is a duplicate of https://github.com/ionic-team/ionic-framework/issues/24524. Please upvote and subscribe to that issue for updates, thank you!

**Closed by brandyscarney** 2024-06-06 21:52 UTC
Labels: triage

**Comment by piotr-cz** [comment] 2024-06-07 09:27
Thanks, somehow I could not find that issue
