### ISSUE TITLE
bug: Ion-modal not passing props data in ionic-vue

### ISSUE THREAD

**Issue by stripathix** [ionic-team/ionic-framework#22189] opened 2020-09-27 21:16 UTC
# Bug Report

**Ionic version:**
"@ionic/vue": "0.5.0",
 "@ionic/vue-router": "0.5.0",
"vue": "^3.0.0-0",

**Current behavior:**
I am migrating from Vue 2 to Vue 3 with an upgrade of Ionic-vue. On opening modal, not able to pass propsData even using basic template provided in ionic docs https://ionicframework.com/docs/api/modal.

**Expected behavior:**
Should pass props data to the modal component.

**Related code:**
View component method to open modal
```
    async openWorkshopFilterModal() {
      const modal = await modalController
        .create({
          component: WorkshopFilter,
          cssClass: 'my-custom-class',
          componentProps: {
            data: {
              content: 'New Content',
            },
            propsData: {
              title: 'New title',
            },
          },
        })
      return modal.present();
    },
```

Filter modal: WorkshopFilter.vue
```
<template>
  <div>
    <ion-header>
      <ion-toolbar>
        <ion-title>{{ title }}</ion-title>
      </ion-toolbar>
    </ion-header>
    <ion-content class="ion-padding">
      {{ content }}
    </ion-content>
  </div>
</template>

<script>
import { IonContent, IonHeader, IonTitle, IonToolbar } from '@ionic/vue';
import { defineComponent } from 'vue';

export default defineComponent({
  name: 'Modal',
  props: {
    title: { type: String, default: 'Super Modal' },
  },
  data() {
    return {
      content: 'Content',
    }
  },
  components: { IonContent, IonHeader, IonTitle, IonToolbar }
});
</script>
```

On the modal opening, title value is provided by the view using the below value is not used. It keeps using `Super Modal` as the title value.
```
 propsData: {
              title: 'New title',
            },
```

**Comment by liamdebeasi** [comment] 2020-09-28 16:22
Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue?

```shell
npm i @ionic/vue@0.6.0-dev.202009281616.96596ba @ionic/vue-router@0.6.0-dev.202009281616.96596ba
```

**Comment by stripathix** [comment] 2020-09-28 18:09
No, still not working.

**Comment by liamdebeasi** [comment] 2020-09-28 18:11
Can you please provide a GitHub repo I can use to reproduce this issue?

**Comment by stripathix** [comment] 2020-09-28 18:23
Yeah sure. Here it is. https://github.com/stripathix/ionic-modal-issue

On tab 1 we have a button to open the modal. The title used in modal is not what we pass as props.

**Comment by liamdebeasi** [comment] 2020-09-28 18:51
Sorry for the confusion, it looks like I gave you the wrong dev build. 

This is the correct dev build:
```
npm i @ionic/vue@0.6.0-dev.202009281843.d019b08 @ionic/vue-router@0.6.0-dev.202009281843.d019b08
```

The other issue is that there is a mismatch between the props defined on your component and the props being passed in. Your component expects a props object that looks like:

```typescript
{
  title: 'New Title'
}
```

but you are passing the following in:

```typescript
componentProps: {
  data: {
    content: 'New Content'
  },
  propsData: {
    title: 'New Title'
  }
}
```

Passing in the following should resolve the issue:

```typescript
componentProps: {
  title: 'New Title'
}
```

**Comment by stripathix** [comment] 2020-09-28 18:59
Thanks @liamdebeasi It works now with changes as you said.
But then looks like docs need changes for vue in here https://ionicframework.com/docs/api/modal.

In docs, it states that we need to pass propsData for props and data for data of the component.
<img width="582" alt="Screenshot 2020-09-29 at 12 28 24 AM" src="https://user-images.githubusercontent.com/8480351/94474053-b2487480-01ea-11eb-8ec5-77d00ce2ad7f.png">

**Comment by liamdebeasi** [comment] 2020-09-28 19:00
Good catch! The docs are incorrect there. I will fix that.

**Comment by liamdebeasi** [comment] 2020-09-28 19:06
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/22198, and a fix will be available in an upcoming release of Ionic Framework.

I made a PR for the docs changes here: https://github.com/ionic-team/ionic-framework/pull/22201

**Closed by liamdebeasi** 2020-09-28 19:06 UTC
Labels: package: vue, type: bug

**Comment by stripathix** [comment] 2020-10-03 09:06
Hey, @liamdebeasi from where can we know what is the next version released. I am not able to find anything related to new ionic/vue development in release notes and the npm version is also pretty old.

**Comment by liamdebeasi** [comment] 2020-10-05 13:27
I released it last week. Release notes are here: https://github.com/ionic-team/ionic-framework/blob/ionic-vue/packages/vue/CHANGELOG.md
