### ISSUE TITLE
ion-textarea with autoGrow and Form sometimes bugs

### ISSUE THREAD

**Issue by HansKrywaa** [ionic-team/ionic-framework#21707] opened 2020-07-08 16:22 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

Sometimes (not often) a Textbox using **autoGrow** in a Form sometimes appears to not calculate the height correctly:

<img width="432" alt="Bildschirmfoto 2020-07-08 um 18 12 34" src="https://user-images.githubusercontent.com/20899975/86943685-093c3180-c147-11ea-821d-bc712ff38e9e.png">

If this happens, this happens to all Textarea's on this Modal-Page.

**Expected behavior:**

To Calculate the Height always correctly 😃 

**Related code:**

```html
<ion-item>
    <ion-textarea required formControlName="descr" [autoGrow]="true"></ion-textarea>
</ion-item>
```

```ts
ngOnInit() {
   this.form.get('descr').setValue('Testi');
}
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.10.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.2.3
   @angular-devkit/build-angular : 0.1000.1
   @angular-devkit/schematics    : 9.1.9
   @angular/cli                  : 10.0.1
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 21 other plugins)

Utility:

   cordova-res : 0.15.1
   native-run  : 1.0.0

System:

   Android SDK Tools : 25.2.3 (/Users/hanskrywalsky/Library/Android/sdk)
   ios-deploy        : 1.10.0
   NodeJS            : v12.16.1 (/usr/local/bin/node)
   npm               : 6.14.5
   OS                : macOS Catalina
   Xcode             : Xcode 11.5 Build version 11E608c
```

**Comment by liamdebeasi** [comment] 2020-07-08 16:39
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/21242 (same underlying issue).

**Closed by liamdebeasi** 2020-07-08 16:39 UTC
Labels: triage
