### ISSUE TITLE
bug: Default sidemenu styling crowds status bar on iPhone

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/ionic-framework#22188] opened 2020-09-27 19:37 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
The default sidemenu styling crowds the status bar on iPhones. Appears to be find on iPads. I have not tried it on a notched Android device to see if there is an issue there or not.

**Expected behavior:**
Less crowding on iPhone devices.

**Steps to reproduce:**

1. generate a sidemenu app using the default starter
1. run on iPhone X / 11 or sim...

Screenshots attached, one showing iPhone 11 the other iPad.

![Simulator Screen Shot - iPhone 11 - 2020-09-27 at 14 12 50](https://user-images.githubusercontent.com/1526846/94374007-d1ea7a80-00ce-11eb-8e62-c191d5cb2b8b.png)
![Simulator Screen Shot - iPad Pro (9 7-inch) - 2020-09-27 at 14 30 25](https://user-images.githubusercontent.com/1526846/94374019-e2025a00-00ce-11eb-81d8-b626d59c1369.png)

**Comment by liamdebeasi** [comment] 2020-09-28 12:52
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/19482.

**Closed by liamdebeasi** 2020-09-28 12:52 UTC
Labels: triage
