### ISSUE TITLE
bug: Impossible to mimic Ionic v3 tabs navigation in v4

### ISSUE THREAD

**Issue by masimplo** [ionic-team/ionic-framework#18516] opened 2019-06-12 09:50 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

When needing to navigate to pages declared in routes of different tabs even if bug #18311 is fixed, leads to a different behaviour than Ionic v3 as pressing back will land the user to a different page than the one the navigation started from.

**Expected behavior:**

Open any page from any page and pressing back should lead to the first page.

**Steps to reproduce:**

- Have two tabs with routes:
/tabs/tab1/main/page1
/tabs/tab2/main/page2

- From page1 navigate to page2 using a button inside page1
- Press back in page2 (back will not appear due to #18311 currently, but the point stands)
- You land to /tabs/tab2/main instead of /tabs/tab1/main/page1

**Other information:**

I am trying to migrate a large Ionic v3 app to Ionic v4 but tabs navigation make it seem impossible.

I have an app with 5 tabs. When I am in tab 3 and click on a button I want to open a specific page, say Settings page, that is attached to a sub route of tab 5, change a setting and then come back. A pretty common scenario in mobile apps.
In Ionic v3 I would just push the Settings page onto the router and then pop it when the user pressed the back button and land back to tab 3 (and whichever sub route of it I might be on).
With the current router, settings is bound in a specific route e.g. /tabs/tab5/main/settings. Issue #18311 currently prevents navigating to /tabs/tab5/main/settings successfully, but even if fixed, when the user presses the back button in settings will land at /tabs/tab5/main instead of /tabs/tab3/main/some-sub-page.

I have thought of the following possible approaches, but all of the have their issues and wanted to know what the official recommended approach in solving such a common scenario is.

After #18311 is fixed go to the other route and when going back land on a different page. -- Pretty unacceptable as no mobile app is behaving this way

Have settings (and any other page) that might need to be opened by more than two tabs declared as modal and open it using the modal controller. -- This way we lose the possibility to lazy load the page and even worse have to convert all pages that that page might link to, to modals, thus making the router obsolete for most of our app

Declare the page (and all subpages and pages of other tabs it might open) to multiple router locations (i.e. /tabs/tab5/main/settings AND /tabs/tab3/main/settings) -- This leads to duplication and might easily lead to a circular dependancy standoff. Also navigations from the settings page to other parts of the app, become very tricky as they have to be declared relatively or detect the current route and route to the other page accordingly.

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0
   Ionic Framework               : @ionic/angular 4.4.2
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 8.0.0, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 31 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/michael/Library/Android/sdk)
   NodeJS            : v10.15.3 (/Users/michael/.nvm/versions/node/v10.15.3/bin/node)
   npm               : 6.9.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.2.1 Build version 10E1001```

**Comment by genebustam** [comment] 2019-07-03 15:52
> From page1 navigate to page2 using a button inside page1

How did you achieve that in the first place?

**Comment by toxaq** [comment] 2019-08-13 13:29
Yep, totally agree here. Ionic seems to have drunk the PWA koolaid and abandoned the mobile aspect of its roots. The missing tabsHideOnSubPages that "will not be recreated" is another part of this. Tabs is completely broken other than for trivial first level functionality. Actually wondering if I should be trying a different framework than upgrading as I've now spent more time fighting Ionic to reproduce my V3 functionality in V4 than I have in actually developing new features.

**Comment by masimplo** [comment] 2020-04-11 06:34
Any update on this? Tabs navigation need some love people, it has been almost a year and almost no such issues have been addressed.

**Comment by liamdebeasi** [comment] 2022-04-13 18:52
Thanks for the issue and apologies for the delay.

I read the thread, and there appear to be 3 separate issues. I will address each one individually:

----

1. When navigating from Tab 1 to a subpage in Tab 2, the `ion-back-button` will not appear. This is logged in #18311.

In this scenario, the application is trying to manipulate the Tab 2 stack from within Tab 1.

Each tab is designed to be an individual navigation stack. Items in one stack should never interact with items in another stack. As a result, the usage described in this issue is considered an anti pattern in both Ionic and native mobile application and is not supported.

The iOS App Store app is a great example of correct tabs usage. If you start on the "Today" tab, none of the buttons in that tab will ever redirect you to the "Games" tab or the "Apps" tab. The only way to access either of those tabs is to tap the associated button in the tab bar.

This is the use case that was provided: Users want to open a "Settings" view within a Tab. In this scenario, the "Settings" view is a separate tab. We recommend opening the "Settings" view as a modal instead. This is what the iOS App Store app does, and it allows you to access the "Settings" view from anywhere in your application.

I will update #18311 with this information as well.

------ 
2. Even after clicking the browser back button from the subpage in Tab 2, the app is directed to the main Tab 2 page.

The behavior described here is correct. As I mentioned in the previous section, each tab is its own stack. This means that when you are in the Tab 2 stack, Ionic will only pop pages off the Tab 2 stack. Ionic will never pop pages off the Tab 1 stack unless the user has navigated to the Tab 1 view. As a result, clicking the back button should bring you from the Tab 2 sub view back to the Tab 2 main view. As with the previous behavior, this aligns with how native mobile tabs work.

--------

3. It is not possible to hide the tab bar on subpages in tabs.

This is the intended behavior as tabs in Ionic were designed to match native mobile tabs. In native tabbed applications, the tab bar is always visible as long as the user is within the tabs context. The tab bar is hidden upon navigating to a non-tabs page.

For example, navigating to `/tabs/tab1/subpage` would keep the tab bar visible. However, navigating to `/settings`, a non-tab page, would cause the tab bar to be hidden.

Developers can also manually hide the tab bar by using a CSS `transform`. However, that is not recommended for the reasons above.

-----

The team has plans to release improved routing documentation. The goal here is to better explain how to get the most out of routing in Ionic and how to correctly use routing patterns such as tabs. This work is being tracked internally, and we hope to have more to share soon.

Since the behavior described here is working as intended, I am going to close this. Thank you!

**Closed by liamdebeasi** 2022-04-13 18:52 UTC
Labels: triage
