### ISSUE TITLE
bug: HammerModule doesn't work with my ionic5 angular 9 project 

### ISSUE THREAD

**Issue by ludonoel1** [ionic-team/ionic-framework#21714] opened 2020-07-09 18:11 UTC
Hello ,
**Ionic version:**
Ionic 5.2.1
angular 9.1.6

**Current behavior:**
My issue is simple : my project ionic/angular/hammerJS works fine in stackblitz but not in local with firefox and chrome..
Hwever it worked fine when I had a angule v6.x.x

**Expected behavior:**
HammerModule works fine with angular ionic version 9-5.

**Steps to reproduce:**
Create a simple project with a homepage.
homepage : 
<ion-content padding>
    <h2> Button Progress: {{ progress }}</h2>
    <h2> Presses State: {{ pressState }}</h2>
    <ion-button (press)="onPress($event)" (pressup)="onPressUp($event)">Press Me</ion-button>
</ion-content>

Hom
**Related code:**

StackBlitz 
Ionic Angular StackBlitz: https://stackblitz.com/edit/ionic-angular-v5-m8xt8c?file=package.json

Thank you

**Comment by liamdebeasi** [comment] 2020-07-09 19:29
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. In Ionic Framework v3, we found that HammerJS had a tendency to capture events and not let them propagate. This caused things as simple as scrolling to no longer work. As a result, we removed it in Ionic Framework v4.

Users are welcome to install it on their own, but we do not provide any kind of official support for HammerJS at this time.

With the release of Ionic Framework v5, we released our own gesture utility that you can use to create your own custom gestures: https://ionicframework.com/docs/utilities/gestures.

We have an open feature request to add some of the more common gestures into the framework by default.

**Closed by liamdebeasi** 2020-07-09 19:29 UTC
Labels: triage
