### ISSUE TITLE
bug: Wrong `this` scope inside component

### ISSUE THREAD

**Issue by 7evenmikser** [ionic-team/ionic-framework#22139] opened 2020-09-22 14:52 UTC
**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
Calling `this` does not cover whole component.

**Expected behavior:**
In Vue doing `console.log(this.user);` would print "x" in case of running do2, but here I'm getting undefined. 
`console.log(this);` returns scope INSIDE methods
```
Object { doTest: doTest(), do2: do2() }
```
 
**Related code:**
```
<template>
  <ion-app>
    <ion-router-outlet />
  </ion-app>
</template>

import { IonApp, IonRouterOutlet } from '@ionic/vue';
import { defineComponent } from 'vue';
import "@codetrix-studio/capacitor-google-auth";
import { App, Plugins } from '@capacitor/core';

export default defineComponent({
  name: 'App',
  components: {
    IonApp,
    IonRouterOutlet
  },
  data() {
    return{
      user: 'x',
      wtf: ''
    }
  },
  methods:{
    doTest(){
      const a = Plugins.GoogleAuth.signIn({value: 'string'});
      
    },
    do2() {
      console.log(this)
      console.log(this.user);
    }

  }
});
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.11.8 (c:\Users\mikser\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/vue 0.3.1

Capacitor:

   Capacitor CLI   : 2.4.1
   @capacitor/core : 2.4.1

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.18.4 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.6
   OS     : Windows 10
```

P.S. Let me know if I'm stupid and missed something simple.

**Comment by liamdebeasi** [comment] 2020-09-22 15:36
Thanks for the issue. Can you provide a GitHub repo that shows this issue happening? I am testing in an Ionic Vue starter application and cannot reproduce the issue.

**Comment by 7evenmikser** [comment] 2020-09-22 17:46
My bad, seems I had to explain more. I'm importing App into one of the views and calling this method from there using `App.methods.do2();`
Here it is git repository you asked
https://github.com/7evenmikser/ionicbug

**Comment by liamdebeasi** [comment] 2020-09-22 18:03
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. You are importing the definition of `App`, not the actual instance that is being used. While it is probably better to place the data you need in state management outside of the App component, you can access the instance of the component by placing a `ref` on `App`:

**main.ts**
```typescript
import { createApp, h } from 'vue';
...

const app = createApp({
  render: () => h(App, { ref: 'myAppRef' })
})

...
```

**Tab2.vue**
```typescript
...
methods: {
  do2() {
    this.$root.$refs.myAppRef.do2();
  }
}
...
```

**Closed by liamdebeasi** 2020-09-22 18:03 UTC
Labels: ionitron: needs reproduction

**Comment by 7evenmikser** [comment] 2020-09-22 18:04
Hm, got ya. Thanks a lot!
