### ISSUE TITLE
bug: ion-datetime jump to previous month after select time #2416

### ISSUE THREAD

**Issue by thomasyu929** [ionic-team/ionic-framework#25530] opened 2022-06-24 02:18 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

In ion-datetime if you select time when you are in current month. (For example today is Jun. 23th)
then close the time picker. the month will auto jump to May. but the selected date not change just UI glitch.

### Expected Behavior

this should not happened

### Steps to Reproduce

- Create `<ion-datetime>` component. 
- Select time in current month. (only happens on today's month)
- Close time picker
- You will see jump to last month.

### Code Reproduction URL

https://stackblitz.com/edit/angular-zv8q4b?file=src%2Fapp%2Fapp.component.html

### Ionic Info

just use the ionic api doc StackBlitz example link you will see this error

**Comment by Et3rnal** [comment] 2022-06-24 03:16
This issue can be seen on the home page demo as well https://ionicframework.com/docs

I have the issue with the date picker as well (not the time) when I placed the date picker inside a collapsable container (not ionic, bootstrap).
I had to disable the animation of the collapsable container, otherwise, it will jump one month every time I collapse/expand! this is worse when you have the max/min set as you are stuck as the arrows will be disabled! however, that was using **Firefox** browser only (chrome/edge) didn't have the issue! unlike the time picker issue which appears on all browsers.

I don't see a way to disable the time picker animation?

**Comment by liamdebeasi** [comment] 2022-06-24 12:55
Thanks for the issue. While I can reproduce this in StackBlitz, I cannot reproduce this in an Ionic starter app locally. We fixed this particular issue in Ionic 6.1.11: https://github.com/ionic-team/ionic-framework/commit/f9ab9b54ddb5a3004673e4aaa9cb62fd8e97ba07, so I wonder if StackBlitz is mistakenly installing an older version somehow.

Can you try this again with an Ionic starter app locally and let me know if you can reproduce the issue?

**Comment by Et3rnal** [comment] 2022-06-27 00:56
Hi @liamdebeasi 
I have reproduced the issue I mentioned using 6.1.11,
I think 6.1.11 does solve the issue of the time picker.

https://stackblitz.com/edit/angular-zv8q4b-5kacbg?file=src/app/app.component.html

You need firefox to see the issue, every time the collapse opens/closes, you will see the date picker jump!
Please let me know if you would like me to raise a new issue

set `[isAnimated]="true"` to false and issue is gone!
PS: collapse uses angular `BrowserAnimationsModule` to animate.

**Comment by liamdebeasi** [comment] 2022-06-28 17:55
Thanks! This looks like a Firefox-specific bug. The Bootstrap animation sets `overflow: hidden` on the `#collapse` element, which causes Firefox to incorrectly fire an IntersectionObserver callback again. A couple thoughts:

1. If you put the collapsing APIs on `ion-datetime` directly, does that fix the issue? (`#collapse="bs-collapse`, `[collapse]="isCollapsed"`, `[isAnimated]="true"`, etc)
2. Does the issue go away if you use `ion-accordion` instead?

**Comment by Et3rnal** [comment] 2022-06-29 00:08
Thanks @liamdebeasi moving `#collapse="bs-collapse" [collapse]="isCollapsed" [isAnimated]="true"` did indeed fix the issue!

**Comment by liamdebeasi** [comment] 2022-06-29 13:36
Glad to hear the issue is resolved. I am going to close this for now as the issue is a browser bug and there is a workaround. If you run into other troubles with this bug, let me know and we can re-open. Thanks again!

**Closed by liamdebeasi** 2022-06-29 13:36 UTC
Labels: triage
