### ISSUE TITLE
bug: status bar scroll to top does not fully cancel content scroll

### ISSUE THREAD

**Issue by EinfachHans** [ionic-team/ionic-framework#20423] opened 2020-02-10 08:46 UTC
# Bug Report

**Ionic version:**

[x] **4.11.10**
maybe also a topic for v5?

**Current behavior:**

When i have a large content on iOS and scroll down, then (while scrolling) tap on the status bar, a scroll to top is emitted. So far so good. But after that, the content is automatically scrolled a bit, like it scrolls the rest of the first scroll.

**Expected behavior:**

When i tap on the status bar and scroll to top, want to end the current scroll and don't continue scrolling.

**Video**

![Video-100220-09-35-26](https://user-images.githubusercontent.com/20899975/75616750-b37ec980-5b55-11ea-97c0-e9f0105bad2c.gif)

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.0.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 4.11.10
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.1.2

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 52 other plugins)

Utility:

   cordova-res (update available: 0.9.0) : 0.8.1
   native-run                            : 0.3.0

System:

   Android SDK Tools : 25.2.3 (/Users/hanskrywalsky/Library/Android/sdk)
   ios-deploy        : 1.10.0
   ios-sim           : 8.0.2
   NodeJS            : v10.16.3 (/usr/local/bin/node)
   npm               : 6.13.7
   OS                : macOS Catalina
   Xcode             : Xcode 11.3.1 Build version 11C504
```

**Comment by HansKrywaa** [comment] 2020-02-29 22:21
I did some Research about this Topic **interrupt Momentum Scroll* and found [this](https://stackoverflow.com/a/21579965/10908838):

> The trick is to set overflow: hidden, which stops the inertia/momentum scrolling.

**Comment by liamdebeasi** [comment] 2020-03-02 20:00
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?

**Comment by HansKrywaa** [comment] 2020-03-02 20:02
Yeah, i can do it, but only tomorrow. But you can just create a new App with a large List and run on an iOS Device.

**Comment by liamdebeasi** [comment] 2020-03-02 20:03
Thanks for the follow up. Are you using Cordova or Capacitor?

**Comment by HansKrywaa** [comment] 2020-03-02 20:03
Cordova, because not all of my Plugins are Capacitor-Ready

**Comment by liamdebeasi** [comment] 2020-03-02 20:24
Ok thanks I was able to reproduce this. There are some issues with the status bar tap in both Cordova and Capacitor so I will need to dig into this a bit more.

**Comment by HansKrywaa** [comment] 2020-03-02 20:26
I think it is not really because of the Status Bar Tap, as this just calls the Ion Contents scroll To Top right? So this must occur also with a for Example Fab Button that calls the Same Method. Have you seen my PR for this?

**Comment by HansKrywaa** [comment] 2020-07-09 10:32
@liamdebeasi Still exists in latest Version - Please check my PR

**Comment by EinfachHans** [comment] 2020-10-06 18:57
@liamdebeasi any Upadates on this? Did you check my pr for this?

**Comment by EinfachHans** [comment] 2021-04-15 12:26
@liamdebeasi any chance you can dig into this a bit more for V6?

**Comment by liamdebeasi** [comment] 2021-09-30 22:38
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/24001, and a fix will be available in an upcoming release of Ionic Framework.

**Closed** 2021-09-30 22:37 UTC
Labels: package: core, type: bug
