### ISSUE TITLE
bug: ion-content scrolls when opening side menu

### ISSUE THREAD

**Issue by WhatsThatItsPat** [ionic-team/ionic-framework#25263] opened 2022-05-09 22:42 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

As I'm dragging open the side menu (using the left side of the screen), I can still scroll the main content of the app vertically.

I found a really old issue about the same thing, but none of that should be relevant today.
https://github.com/ionic-team/ionic-framework/issues/9130

### Expected Behavior

I expect the content in the current page to stop moving vertically when I start interacting with the side menu.

### Steps to Reproduce

I used the cli to create a new side menu project and went through they typical Capacitor steps. I didn't change anything except to add some lorem ipsum so there's something to scroll.

Here's a video of it running on my iPhone:
https://photos.app.goo.gl/AM88ZANzfWyLsnRYA

### Ionic Info

Ionic:

   Ionic CLI                     : 6.19.0
   Ionic Framework               : @ionic/angular 6.1.4
   @angular-devkit/build-angular : 13.2.6
   @angular-devkit/schematics    : 13.2.6
   @angular/cli                  : 13.2.6
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.5.1
   @capacitor/android : not installed
   @capacitor/core    : 3.5.1
   @capacitor/ios     : 3.5.1

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v16.13.2
   npm    : 8.1.2
   OS     : macOS Big Sur

**Comment by liamdebeasi** [comment] 2022-05-10 13:00
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/21193.

**Closed by liamdebeasi** 2022-05-10 13:00 UTC
Labels: triage
