### ISSUE TITLE
Vue3: HTML native input v-model not updating value until the input is blurred

### ISSUE THREAD

**Issue by devhus** [ionic-team/ionic-framework#27534] opened 2023-05-23 00:20 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

In android:
When using v-model attr on a native HTML input ``<input .... />`` in a vue 3 project, The v-model attr doesn't work as expected.
The input does not update the v-model ref value until the input is blurred or the space key is pressed on the keyboard. 
All behaviors of v-model attr and @update, @input methods can be seen in the video below:
https://github.com/devhus/ionic-cap-test/blob/main/preview.webm

### Expected Behavior

In android:
v-model attr should update the ref value once any keyboard key is pressed, should behave the same as @input method behavior

### Steps to Reproduce

1. Create a fresh Ionic using Vue3 & Capacitor 7 (Or clone my repo https://github.com/devhus/ionic-cap-test)
2. ``npm run install``
3. ``npm run build``
4. ``ionic cap sync``
5. debug the app on Android Studio or your device
6. Test all the example inputs on the main screen, the first input that uses v-model attr doesn't behave as expected

### Code Reproduction URL

https://github.com/devhus/ionic-cap-test

### Ionic Info

Ionic:

   Ionic CLI       : 6.20.8 (C:\Users\devhu\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/vue 7.0.7

Capacitor:

   Capacitor CLI      : 5.0.3
   @capacitor/android : 5.0.3
   @capacitor/core    : 5.0.3
   @capacitor/ios     : 5.0.3

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.2

System:

   NodeJS : v18.14.0 (C:\Program Files\nodejs\node.exe)
   npm    : 9.3.1
   OS     : Windows 11

**Comment by liamdebeasi** [comment] 2023-05-23 13:38
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. Ionic manages the `v-model` updates for `ion-input`, but we do not manage the inputs for native `<input />` elements. According to the [Vue Form Input Bindings Docs](https://vuejs.org/guide/essentials/forms.html#form-input-bindings) the `v-model` state for native inputs is supposed to be updated on the `input` event. If this is not happening, you might want to consider filing an issue with the Vue team. Also, if this issue only happens when deployed to a webview via Capacitor, this might be a browser bug.

**Closed by liamdebeasi** 2023-05-23 13:38 UTC
Labels: triage

**Comment by devhus** [comment] 2023-05-23 14:28
@liamdebeasi Should i also fill an issue on Capacitorjs repo instead of here, since Capacitorjs is the web view provider ?
