### ISSUE TITLE
bug: in ios device with os 14 beta, content with tag 'ion-card-subtitle' jumps when scrolling

### ISSUE THREAD

**Issue by ronanjia** [ionic-team/ionic-framework#21880] opened 2020-08-05 03:16 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

**NOTE:** iPhone XS with IOS 14 beta.3/4 has this issue, but iPhone 7 plus works fine.

**content jump with card-subtitle**
![RPReplay_Final1596594885](https://user-images.githubusercontent.com/5581839/89366669-e2532a00-d709-11ea-969d-899bfe3ddacc.gif)

**scroll smooth without card-subtitle**
![RPReplay_Final1596594796](https://user-images.githubusercontent.com/5581839/89366721-00208f00-d70a-11ea-8b78-0374601b6ccc.gif)

**Expected behavior:**

content scrolls smooth

**Steps to reproduce:**

With `ion-card-subtitle` in `ion-content`, content jumps when scrolling

**Related code:**

```
<ion-content fullscreen class="ion-padding" [scrollY]="!showBackdrop">
  <ion-card>
    <ion-card-header>

      <!-- content jumps when scrolling with card subtitle  -->
      <ion-card-subtitle>sub</ion-card-subtitle>

      <ion-card-title>title</ion-card-title>
    </ion-card-header>
    <ion-card-content>
      123
    </ion-card-content>
  </ion-card>
</ion-content>
```

**Other information:**

Not sure if related to #21613 

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.11.0
   Ionic Framework               : @ionic/angular 5.3.0
   @angular-devkit/build-angular : 0.901.11
   @angular-devkit/schematics    : 9.1.11
   @angular/cli                  : 9.1.11
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 2.2.1
   @capacitor/core : 2.2.1

Utility:

   cordova-res : 0.15.1
   native-run  : 1.0.0

System:

   NodeJS : v10.16.0
   npm    : 6.11.1
   OS     : macOS Catalina
```

**Comment by ronanjia** [comment] 2020-08-05 16:53
Hi, i put a new starter ionic project on Github [here](https://github.com/ronanjia/TransBug-on-ios14b4), and the bug seems to exist on my iPhone Xs (ios 14 beta.4)

**Produce:**

1. start new app with capacitor
```
ionic start App blank
ionic build
ionic cap add ios
```
2. deploy to iPhone in Xcode
![RPReplay_Final1596646261](https://user-images.githubusercontent.com/5581839/89441057-25031980-d77f-11ea-8f31-b5cbc91bec27.gif)



With `ion-card-subtitle` commented out, it works fine!
```
<!-- <ion-card-subtitle>sub</ion-card-subtitle> -->
```
**CODE Location:** https://github.com/ronanjia/TransBug-on-ios14b4/blob/79b4bbbc96cd1f0b21f420c584ba85218b8fc716/src/app/home/home.page.html#L18

**Ionic Info**
```
Ionic:

   Ionic CLI                     : 6.11.0
   Ionic Framework               : @ionic/angular 5.3.1
   @angular-devkit/build-angular : 0.901.12
   @angular-devkit/schematics    : 9.1.12
   @angular/cli                  : 9.1.12
   @ionic/angular-toolkit        : 2.3.0

Capacitor:

   Capacitor CLI   : 2.4.0
   @capacitor/core : 2.4.0

Utility:

   cordova-res : 0.15.1
   native-run  : 1.0.0

System:

   NodeJS : v10.16.0
   npm    : 6.11.1
   OS     : macOS Catalina
```

**Comment by liamdebeasi** [comment] 2020-08-05 18:50
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/20932#issuecomment-608527041.

**Closed by liamdebeasi** 2020-08-05 18:50 UTC
Labels: ionitron: needs reproduction

**Comment by ronanjia** [comment] 2020-08-06 02:01
Hi Liam, thanks for your quick reply, i will keep track at the webkit issue, by far turn off `transform` works fine.

**Comment by ronanjia** [comment] 2020-08-10 11:01
Hi @liamdebeasi , i'm having another _SwipeBack_ problem which i'm not sure whether it is related.

**Current behavior:**
As you can see blow, when i navigate to office page, then swipe back to home page;
When i release my finger, the office page seems to jump to the middle of the viewport first, and then start to move away;


**Expected behavior:**
It should move directly form the position that the finger just released

![RPReplay_Final1597055249](https://user-images.githubusercontent.com/5581839/89775039-8fc6a300-db39-11ea-96c2-9ca1e9d4ff9d.gif)

**CODE Location:** https://github.com/ronanjia/TransBug-on-ios14b4/blob/68120483ba671ae306fe860f45056fd2fb0013ff/src/app/home/home.page.html#L23

Help please~

**Comment by liamdebeasi** [comment] 2020-08-10 13:16
That is an existing iOS 14 bug. The WebKit team has fixed it, but the patch has not been released yet.

**Comment by ronanjia** [comment] 2020-08-10 15:05
> That is an existing iOS 14 bug. The WebKit team has fixed it, but the patch has not been released yet.

Thanks a lot!
