### ISSUE TITLE
bug: ios, padding-left transition does not work on ion-item-sliding

### ISSUE THREAD

**Issue by popaprozac** [ionic-team/ionic-framework#24860] opened 2022-03-02 00:52 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

On Safari, an expandable `ion-item-option` does not smoothly transition when the "overswipe" threshold is met. The transition is ignored completely and the `ion-item-option` jumps to `padding-left: 100%`.

The padding transitions to 100% smoothly on Google Chrome and Firefox.

Setup:
```
<ion-item-sliding>
  <ion-item>
    <ion-label>Item label</ion-label>
  </ion-item>
  <ion-item-options side="end">
    <ion-item-option>Share</ion-item-option>
    <ion-item-option expandable color="danger">Delete</ion-item-option>
  </ion-item-options>
</ion-item-sliding>
```

### Expected Behavior

As Chrome and Firefox correctly display, the `padding-left` property on `ion-item-option[expandable]` should smoothly transition to `padding-left: 100%` when the `ion-item` is swiped.

### Steps to Reproduce

Overswipe on an `ion-item` in an `ion-item-sliding` in Safari.

### Code Reproduction URL

https://codepen.io/popaprozac/pen/wvPQENV

### Ionic Info

_Using Ionic components as web components_

Ionic:

   Ionic CLI : 6.18.1

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v17.1.0
   npm    : 8.2.0
   OS     : macOS Monterey

### Additional Information

Found that applying an explicit initial padding resolved the issue.

Adding `padding-left: 0%` to the expandable `ion-item-option` initially will allow the transition to work.

**Comment by liamdebeasi** [comment] 2022-03-02 14:17
Thanks for the issue. This the behavior is happening due to a bug in WebKit, the engine that powers Safari and WKWebView.

I can reproduce this on iOS 15.2. The good news is this appears to be fixed in iOS 15.4, so I will update this thread when that version is released.

**Closed** 2022-03-14 17:42 UTC
Labels: type: bug, bug: external
