### ISSUE TITLE
bug: ion-datetime when selecting time, when select 12:30AM return 12:30PM

### ISSUE THREAD

**Issue by winglovecola** [ionic-team/ionic-framework#22263] opened 2020-10-06 20:48 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
 when selecting time, when select 12:30AM return 12:30PM

**Expected behavior:**
 when selecting time, when select 12:30AM return 12:30AM

**Steps to reproduce:**
when selecting time, select 12:30AM and press done

**Related code:**

**Ionic info:**
Ionic:

   Ionic CLI                     : 5.4.16 (C:\Users\Wing He\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 5.3.4
   @angular-devkit/build-angular : 0.1001.4
   @angular-devkit/schematics    : 9.1.8
   @angular/cli                  : 10.1.4
   @ionic/angular-toolkit        : 2.3.3

Capacitor:

   Capacitor CLI   : 2.2.0
   @capacitor/core : 2.2.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.18.4 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.6
   OS     : Windows 10

**Comment by liamdebeasi** [comment] 2020-10-06 22:41
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/22171. This will be fixed in an upcoming release of Ionic Framework.

**Closed by liamdebeasi** 2020-10-06 22:41 UTC
Labels: triage
