### ISSUE TITLE
[Ionic v4] split-pane inside tabs broken

### ISSUE THREAD

**Issue by cleversolutions** [ionic-team/ionic-framework#14961] opened 2018-07-31 18:53 UTC
# Bug Report

**Ionic Info**
```
Ionic:

   ionic (Ionic CLI)          : 4.0.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.0
   @angular-devkit/core       : 0.7.0-rc.3
   @angular-devkit/schematics : 0.7.0-rc.3
   @angular/cli               : 6.0.8
   @ionic/ng-toolkit          : 1.0.0
   @ionic/schematics-angular  : 1.0.1

System:

   NodeJS : v8.10.0 (/usr/local/bin/node)
   npm    : 5.6.0
   OS     : macOS High Sierra
```

**Describe the Bug**
Using a split-pane inside a tabs container causes the menu in the split-pane to stop working after navigating to another tab then back to the tab with a tab-pane

**Steps to Reproduce**
1. Clone and run the example project below
2. Test the links in the menu in the split-pane on the Home tab to see that they work
3. Go to any of the other tabs
4. Return to the Home tab
5. Try any of the links in the split-pane again. They do not work.

**Related Code**
[GitHub](https://github.com/cleversolutions/ionic4DynamicTabs).

**Expected Behavior**
The navigation in the split pane should continue to function after activating another tab and returning to the tab which contains the split-pane.

**Additional Context**
Issue #14957 illustrates other issues with split-panes inside a tabs container.

**Comment by mhartington** [comment] 2018-09-17 15:20
Issue seems to be related to routerLink and how it resolves what component to route to, what outlet to use, and how to update the DOM.  I will note, a workaround is to replace the routerLink directives with hrefs and use absolute urls

```html
          <ion-item href="/tabs/(split-pane:split-pane/home)">one</ion-item>
          <ion-item href="/tabs/(split-pane:split-pane/about)">two</ion-item>
          <ion-item href="/tabs/(split-pane:split-pane/contact)">three</ion-item>
```

**Comment by paulstelzer** [comment] 2018-12-13 18:04
We've released beta.18 now with another refactor of tabs. Could you check if the issue is fixed? Please keep in mind the breaking changes: https://github.com/ionic-team/ionic/blob/master/CHANGELOG.md#400-beta18-2018-12-13

**Comment by MartineNavara** [comment] 2019-01-02 12:47
I just ran into the same problem with the release candidate (4.0.0-rc.0).

**Comment by MartineNavara** [comment] 2019-01-02 14:05
I created a simple example of the problem based on the tabs starter:
https://github.com/MartineNavara/TestSplitPaneWithTabs 

When you open the app and navigate to tab 2 and then back to tab 1, tab 1 will not show the side menu (tab 2 actually keeps its side menu).

**Comment by liamdebeasi** [comment] 2024-02-28 22:46
Hi everyone,

Since this issue was filed the team has made significant changes to how developers construct and interact with tabs. We've also made a number of improvements to both tabs and menu/split pane. The original configuration is no longer supported in Ionic, so I am going to close this.

If this is still a problem when using a supported tabs syntax, please feel free to open a new issue and include a reproduction. Thank you!

**Closed by liamdebeasi** 2024-02-28 22:46 UTC
Labels: package: angular
