### ISSUE TITLE
bug: Can't get Nested Tabs to work

### ISSUE THREAD

**Issue by nadavhalfon** [ionic-team/ionic-framework#28659] opened 2023-12-06 23:56 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

There is a tab view, and of the tabs has slotted at the top tab bar.
The Tabs Nested within The primary tabs are working good, but when switching to a tab from the primary tab something breaks and the top bars remain.

One thing I found out is that putting the inner Tabs inside IonContent fixes that problem but then sometimes the other tabs (from the primary view) breaks and shows nothing.

### Expected Behavior

Being able to use Tabs nested within tabs without any problem, there are many apps with this pattern.

### Steps to Reproduce

1. Create a parent IonTabs component
2. Create a few tabs
3. Choose one of the Tabs and make it also an IonTabs

Try now, then:
4. Wrap the child tabs component with IonContent

Try it now, you'll see it works better but now the primary tabs are broken by this error: 
```
StackManager.tsx:18 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'classList')
    at isViewVisible (StackManager.tsx:18:7)
    at StackManager.handlePageTransition (StackManager.tsx:156:12)
    at StackManager.componentDidUpdate (StackManager.tsx:71:12)
    at commitLayoutEffectOnFiber (react-dom.development.js:23333:30)
    at commitLayoutMountEffects_complete (react-dom.development.js:24688:9)
    at commitLayoutEffects_begin (react-dom.development.js:24674:7)
    at commitLayoutEffects_begin (react-dom.development.js:24656:11)
    at commitLayoutEffects (react-dom.development.js:24612:3)
    at commitRootImpl (react-dom.development.js:26823:5)
    at commitRoot (react-dom.development.js:26682:5)
```

### Ionic Info

@ionic/react: 7.5.6
@ionic/react-router: 7.5.6
@capacitor/code: 5.5.1

**Comment by liamdebeasi** [comment] 2023-12-07 14:37
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. Nested tabs is not something we support and is not something we recommend doing in mobile applications. Nested tabs is going to make it very difficult for users to navigate your application. In general, mobile applications have at most one level of tabs. The reason for this is each tab is an individual navigation stack which is different from how tabs behave on web applications (where nested tabs may be more user-friendly).

If you need to switch views within a single tab, I'd recommend using `ion-segment` instead: https://ionicframework.com/docs/api/segment

**Closed by liamdebeasi** 2023-12-07 14:37 UTC
Labels: triage
