### ISSUE TITLE
bug: Creating a modal component without resorting to customElements

### ISSUE THREAD

**Issue by raymondboswel** [ionic-team/ionic-framework#24379] opened 2021-12-13 12:21 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

 I'm currently using Ionic in a Svelte project. According to the docs, when using Ionic without one of the standard framework bindings, you ustom element. This is proving to be problematic, since my global styles / tailwind classes are not applied in the custom element.

### Expected Behavior

Having used @ionic/angular in quite a few projects it definitely didn't feel like the modal components were being converted to customElements behind the scenes, so I assume there's another mechanism that can be used in addition to creating custom elements?

### Steps to Reproduce

Create blank project with Svelte or just vanillaJS and use modalController in application

**Comment by liamdebeasi** [comment] 2021-12-13 16:26
Thanks for the issue. Can you try slotting your content in directly inside of `ion-modal`?

```html
<ion-modal is-open="true">
  <!-- put your content here -->
</ion-modal>
```

This should let you pass in content directly without having to use a custom element.

For Ionic Angular projects, we have a utility that interfaces with Angular so you can use Angular components. Since we do not have a Svelte integration, this utility does not exist for Svelte projects.

**Comment by liamdebeasi** [comment] 2021-12-13 16:45
Can you reproduce the layout issues in a sample app?

**Comment by raymondboswel** [comment] 2021-12-13 17:45
I'm sure I could. I'll create a reproduction in the AM :+1:

**Comment by liamdebeasi** [comment] 2021-12-13 17:47
Thank you!

**Comment by raymondboswel** [comment] 2021-12-14 06:02
I created a reproduction repo here: https://github.com/raymondboswel/ionic-modal-reproduction. There's a note and usage instructions in the README. Thanks :beers:

**Comment by liamdebeasi** [comment] 2021-12-16 20:47
The sizing issue seems to be related to the margins you have applied to `article`. Wrapping the article in a `<div class="ion-page">` seems to do the trick.

With the framework bindings we do this for you. Can you try that and let me know if it resolves the issue?

**Comment by raymondboswel** [comment] 2021-12-17 05:06
Hi @liamdebeasi, that works! We can close this one out. Thanks a million :+1:

**Comment by amandaesmith3** [comment] 2021-12-17 14:46
Glad to hear this is resolved! I'll close this. Thanks for using Ionic!

**Closed by amandaesmith3** 2021-12-17 14:46 UTC
Labels: triage
