### ISSUE TITLE
bug: Vue Ionic lifecycle hooks do not work for components loaded within a modal

### ISSUE THREAD

**Issue by JamieWritesCode** [ionic-team/ionic-framework#25378] opened 2022-05-30 22:27 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

Vue Ionic lifecycle hooks such as `ionViewDidEnter` work fine when loading a component through the router, however they do not work when opening the same component in a modal.

### Expected Behavior

I would expect that the desired behaviour is to have lifecycle hooks work inside modals as well. This is the way it works with Angular Ionic. Additionally, these hooks play an important role in knowing when the modal has completed its `present` animation - allowing us to delay loading of resources until after the animation is completed, improving the performance of the animation and user experience.

### Steps to Reproduce

See repo for minimal reproduction. Repo is a blank vue project, updated to demonstrate the issue. Note that the `HomePage` component logs it's message to console, but the `ModalPage` component does not.

### Code Reproduction URL

https://github.com/JamieWritesCode/vue-modal-lifecycle

### Ionic Info

Ionic:

   Ionic CLI       : 6.19.1 (C:\Users\jamie\AppData\Roaming\nvm\v16.15.0\node_modules\@ionic\cli)
   Ionic Framework : @ionic/vue 6.1.7

Capacitor:

   Capacitor CLI      : 3.5.1
   @capacitor/android : not installed
   @capacitor/core    : 3.5.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.6.0

System:

   NodeJS : v16.15.0 (C:\Program Files\nodejs\node.exe)
   npm    : 8.5.5
   OS     : Windows 10

**Comment by liamdebeasi** [comment] 2022-05-31 15:27
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. This behavior is by design. As per the docs, Ionic Lifecycle events only work with components that are activated via routing: https://ionicframework.com/docs/vue/lifecycle

Since modals are not activated via routing, they do not participate in Ionic Lifecycle events. For these components you have two options:

1. Use the built-in Vue component lifecycle methods (created, mounted, etc)
2. Listen for Ionic component lifecycle events (ionModalDidPresent, ionModalWillDismiss, etc).

**Closed by liamdebeasi** 2022-05-31 15:27 UTC
Labels: triage

**Comment by JamieWritesCode** [comment] 2022-06-01 00:18
Thanks @liamdebeasi , I can appreciate the logic behind the relation of lifecycle hooks to the router. I just found it a little confusing coming from Angular Ionic, where the default behaviour _**IS**_ to fire lifecycle events within modals. 🤷 That's on me for assuming, I guess.

For what it's worth, I do think this leaves a common use case without a great solution - that is, knowing when the modal has finished its entry animation from **_inside_** the modal component. As I mentioned at the top, this is very useful for delaying any operation that might impact the performance of the modal animation (like loading or mounting data etc). This use case is actually highlighted in the docs:

https://ionicframework.com/docs/vue/lifecycle#guidance-for-each-lifecycle-method

With my (admittedly limited) understanding of Vue, I don't see an obvious solution to this problem for modals without resorting to some kind of event bus or shared state to track the state of the modal animation - both of which feel a little obtuse. 

Perhaps an exploration of how we might make Ionic lifecycle hooks work for modals in Vue is warranted?
