### ISSUE TITLE
bug: new useIonModal hook for Ionic React renders component outside tree

### ISSUE THREAD

**Issue by babycourageous** [ionic-team/ionic-framework#23516] opened 2021-06-26 05:29 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x ] **5.x**
[ ] **6.x**

**Current behavior:**
Just in case this behavior is unintended, the new `useIonModal` hook renders the modal component passed to `present()` outside of the react tree as a sibling of the root node. Because of this, the component used has no access to any app-wide context that wraps the main "App" component that the calling component belongs to.

**Expected behavior:**
Render the component for the modal inside the root react tree.

**Steps to reproduce:**

Follow the Ionic docs for rendering/presenting a React modal using `useIonModal()` hook.

**Related code:**

Here's a screenshot where you see the component that the hook renders next to the component tree instead of inside it (either as a child or sibling of `<App />`)
<img width="363" alt="Screen Shot 2021-06-25 at 7 27 22 PM" src="https://user-images.githubusercontent.com/14936212/123493751-685eb480-d5eb-11eb-92f5-a4cb8be5dccc.png">

**Other information:**

In case this is the intended behavior for the `useIonModal` hook - this may be an opportunity to mention in the docs when deciding whether to use the original `<IonModal>` wrapping component or the hook. Perhaps that the hook is meant for modals that don't need access to app-wide data and for those and other complex use-cases continue to use the `<IonModal>` component. 
I would be happy to PR to the docs if needed!
Thanks

**Ionic info:**

```
Ionic:

   Ionic CLI       : 5.4.16 (/Users/rene/.npm/_npx/23301/lib/node_modules/ionic)
   Ionic Framework : @ionic/react 5.6.10

Capacitor:

   Capacitor CLI   : 2.4.6
   @capacitor/core : 2.4.7

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.16.3 (/Users/rene/.nvm/versions/node/v12.16.3/bin/node)
   npm    : 6.14.4
   OS     : macOS Mojave
```

**Comment by liamdebeasi** [comment] 2021-06-28 12:48
Thanks for the issue. Could you reproduce this issue in an Ionic starter app and provide a link to the repo?

**Comment by babycourageous** [comment] 2021-06-28 14:15
Hi Liam

Absolutely, here ya go!
https://github.com/babycourageous/ionic-react-modal-hook-issue

**Comment by liamdebeasi** [comment] 2021-07-16 13:21
Thanks, and sorry for the delay. I am able to reproduce this behavior. I am checking with the team to see if this the intended behavior.

**Comment by babycourageous** [comment] 2021-07-16 13:26
No prob at all @liamdebeasi ! Thanks for looking into it.

**Comment by babycourageous** [comment] 2021-08-09 16:19
Thanks for the update @liamdebeasi !

**Comment by DRiFTy17** [comment] 2021-09-22 15:29
@liamdebeasi has there been any progress/update on this? We're also running into this issue... Thanks!

**Comment by piotr-cz** [comment] 2021-11-03 10:42
@liamdebeasi I've fixed the issue with hard-wiring paths to react in tsconfig.json as described here: https://github.com/preactjs/preact/issues/2150#issuecomment-558127299

```jsonc
// tsconfig.json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "react": ["node_modules/preact/compat"],
      "react-dom": ["node_modules/preact/compat"]
    }
  }
}
```

**Comment by piotr-cz** [comment] 2021-11-03 10:52
@liamdebeasi 
Thanks, https://github.com/ionic-team/ionic-framework/pull/24132 solved the issue in VSCode, however I'm unable to build.
I'll post details in referenced PR

**Comment by liamdebeasi** [comment] 2021-11-03 13:25
Thanks for the issue. The original issue here was resolved via https://github.com/ionic-team/ionic-framework/commit/f3e492c897c8cda2b98050156f130654f4d7014a. The Preact issue has been resolved via https://github.com/ionic-team/ionic-framework/pull/24132, and a fix will be available in an upcoming release of Ionic 6.

- The build issue is is related to a Stencil change and has been fixed in Ionic 6 RC 2(see https://github.com/ionic-team/ionic-framework/issues/24153#issuecomment-958052376);
- The `tsconfig` changes were discussed in https://github.com/ionic-team/ionic-framework/pull/24132#issuecomment-959024082 and is an expected behavior of Preact. Developers should alias their exports: https://preactjs.com/guide/v10/getting-started/#typescript-preactcompat-configuration

**Closed by liamdebeasi** 2021-11-03 13:25 UTC
Labels: package: react, type: bug
