### ISSUE TITLE
bug: IonRefresher infinite loading state on iOS when remounting inline svgs

### ISSUE THREAD

**Issue by james2hey** [ionic-team/ionic-framework#25061] opened 2022-04-06 10:05 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

When using the `IonRefresher` and `IonRefresherContent` together on iOS, along with an `<svg>` that has a `<use>` element, this causes the refresher to infinitely stay in the "pulling" state even after the pulling gesture is completed if the svg is remounted.

https://user-images.githubusercontent.com/41892498/161946632-a3fdae46-f79f-4be1-9021-99c746a49ae3.mov

### Expected Behavior

The refresher moves to the next state after pulling gesture is finished.

### Steps to Reproduce

1. Build and run the app on an iOS simulator
2. Press and hold on the `<use>` element of the `svg`, then
3. Pull down and hold until the `svg` has been remounted
4. The refresher infinitely stays in the pulling state

### Code Reproduction URL

https://github.com/james2hey/ionic-refresh-svg-issue

### Ionic Info

Ionic:

   Ionic CLI       : 6.19.0 (/Users/jamestoohey/.nvm/versions/node/v12.20.0/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 6.0.14

Capacitor:

   Capacitor CLI      : 3.4.3
   @capacitor/android : not installed
   @capacitor/core    : 3.4.3
   @capacitor/ios     : 3.4.3

Utility:

   cordova-res : 0.15.4
   native-run  : 1.5.0

System:

   NodeJS : v12.20.0 (/Users/jamestoohey/.nvm/versions/node/v12.20.0/bin/node)
   npm    : 6.14.8
   OS     : macOS Monterey

**Comment by james2hey** [comment] 2022-04-13 08:18
Confirming that the Simulator is on iOS 15.4.
This also occurs on a a physical device. I'm using an iPhone on iOS 15.3.1 (see video attached).

https://user-images.githubusercontent.com/41892498/163132097-5b99104b-50d1-4e84-9d21-d1649746a2c9.mp4

**Comment by liamdebeasi** [comment] 2022-04-13 12:44
Do you have steps to reproduce the issue? I noticed in the video that you hold your gesture for a second or two before releasing. Is that required to reproduce the issue?

**Comment by james2hey** [comment] 2022-04-13 18:41
Yes the holding part is to remount the component (see step 3):

> ### Steps to Reproduce
> 1. Build and run the app on an iOS simulator
> 2. Press and hold on the `<use>` element of the `svg`, then
> 3. Pull down and hold until the `svg` has been remounted
> 4. The refresher infinitely stays in the pulling state

**Comment by james2hey** [comment] 2022-04-30 22:26
Thanks for looking into this. Yes the issue does go away when setting `pointer-events: none` on the SVG.

**Comment by liamdebeasi** [comment] 2022-05-02 13:48
Thanks for checking. I recommend moving forward with that solution. As I mentioned in https://github.com/ionic-team/ionic-framework/issues/25061#issuecomment-1102733017 this seems to be an intentional behavior since it is consistent across multiple browsers. As a result, Ionic likely cannot fix this behavior from our end since we are not receiving the `touchend` event.

I am going to close this out. Thanks for the report!

**Closed by liamdebeasi** 2022-05-02 13:48 UTC
Labels: triage
