### ISSUE TITLE
bug: predefined values ​​or default values ​​don't work in <InoRange> React

### ISSUE THREAD

**Issue by teomda** [ionic-team/ionic-framework#27988] opened 2023-08-11 01:47 UTC
### Describe the Bug

Hello,

I'm going to try to speak in English, I'm not good at writing it.

in React,

When i use ionNav for make a register wizard, in my component "step2" i use the next code:

const Step2: React.FC<RouteComponentProps & Step2Props> = ({ formData, setFormData, handleInputChange }) => {

    const {  workHours } = formData;

    const [vWorkHours, setvWorkhours] = useState(workHours)

    // (Testing) Set que values from props
    useEffect(() => {
        console.log('First set hours: ', workHours)
        setvWorkhours(workHours)
    }, [])
   // i Try to use workHours inside <IonRange, dont work

 <IonRange
      value={vWorkHours}
      name='startHours'
      aria-label="startHours"
      onIonChange={(e) => handleInputChange(e)}
      ticks={true}
      snaps={true}
      min={0}
      max={24}
      pin={true}
      dualKnobs={true}
      pinFormatter={(value: number) => (value > 11 ? `${value} PM` : `${value} AM`)}
  >
      <IonIcon slot="start" icon={sunnyOutline}></IonIcon>
      <IonIcon slot="end" icon={moonOutline}></IonIcon>
  </IonRange>

The result is that having or not predefined values, they are not set when displaying the component.

### Expected Behavior

That the <IonRange> component appears with the values ​​previously set through props

### Steps to Reproduce

Generate a State (useState) with a object with the values in the father component,

Send this object by props using IonNav to the next step component and set it in the value prop of<IonRange>

You can use the example for reproduction from: https://ionicframework.com/docs/api/range#dual-knobs in React version doing click in 'Open with StackBlitz'.
For iOS or MD is the same.

### Operating System

Windows

### Browser

Opera, Edge

### Version

Opera One(versión: 101.0.4843.33) and Edge Versión 115.0.1901.200 (Compilación oficial) (64 bits)

**Comment by teomda** [comment] 2023-08-14 19:57
Ok,
You can use the example for reproduction from: https://ionicframework.com/docs/api/range#dual-knobs in React version.
For iOS or MD is the same.

**Comment by sean-perkins** [comment] 2023-08-15 13:52
This issue is a duplicate of: https://github.com/ionic-team/ionic-framework/issues/25444.

**Closed by sean-perkins** 2023-08-15 13:52 UTC
Labels: ionitron: needs reproduction
