### ISSUE TITLE
bug: IonInput: IonOnChange event firing twice

### ISSUE THREAD

**Issue by nitink66** [ionic-team/ionic-framework#25287] opened 2022-05-14 17:42 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x
- [ ] Nightly

### Current Behavior

IonOnChange event for IonInput fires twice when backspacing 1 character.
Version: "@ionic/react": "5.6.11"

### Expected Behavior

When value is 1 character and backspace is pressed, input value should be empty.

### Steps to Reproduce

Steps to reproduce: If I enter any 10 characters, lets say "randomstring", into the input ,the value is now randomstring and then I press backspace to completely erase the value inside the input field, onChange event fires and input is empty, then onChange event fires a 2nd time with value of "r" (or what the previous character was) and input goes back to "r" (or the previous character) again. If i keep hitting backspace repeatedly the same thing happens until eventually the input clears.
Note: This is reproducible when you quickly erase off the values inside the input field.

Related Code:
```
<IonInput
        style={{ border: "1px solid black" }}
        onIonChange={handlePostcodeChange}
        value={postCodeInputValue}
        placeholder="Postcode"
        pattern="/^[a-z0-9]+$/i"
        maxlength={10}
        type="text"
      />

```

One of the similiar issue [Issue-21759](https://github.com/ionic-team/ionic-framework/issues/21759)

### Code Reproduction URL

https://codesandbox.io/s/naughty-bohr-mj0gmt?file=/src/App.tsx

### Ionic Info

'ionic' is not recognized as an internal or external command,
operable program or batch file.

**Comment by sean-perkins** [comment] 2022-05-16 02:29
@nitink66 thanks for reporting this issue.

In your application/example, are you assigning `postCodeInputValue` with `useState`? If so, this issue is a duplicate of #22868. I had an experimental PR to address this behavior here: #24858, but decided against merging, until after v7 discovery for Ionic + React 18/19 exploration (hoping for their custom elements support to ship in 19). 

Let me know if you are using `useState` and I can combine these issues. Thanks!

**Comment by sean-perkins** [comment] 2022-05-16 17:03
Done, thanks for the follow-up!

**Closed by sean-perkins** 2022-05-16 17:03 UTC
Labels: triage
