### ISSUE TITLE
bug: Centering ion-input dont work on Android

### ISSUE THREAD

**Issue by SvenBudak** [ionic-team/ionic-framework#28206] opened 2023-09-21 12:59 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

I have the same problem in many of my apps. As soon as I place `<ion-footer>` in a view and an `<ion-input>` in my `<ion-content>`, the centering to the input on focus just doesn't work properly. It's the same issue in all 4 apps I've developed. 

https://github.com/ionic-team/ionic-framework/assets/4930169/cb56cead-1793-4dd2-b819-bcceb58df3b5

### Expected Behavior

I Expect, that the Input is centering correctly and is not be ided by other elements...

### Steps to Reproduce

1. $ ionic start (Select Angular then Standalone)

2. open home.page.html and replace the default html with:
```html
<ion-content fullscreen>

  <div style="background-color: cornflowerblue; text-align: center;">
    <span style="line-height: 400px;">Let's imagine this is a picture...</span>
  </div>

  <h2 style="margin-top: 24px; text-align: center;">Wie sollen wir dich nennen?</h2>

  <form style="padding: 24px; display: flex; flex-direction: column; gap: 24px;">
    <ion-input label="User Name" labelPlacement="stacked" fill="outline"></ion-input>
  </form>

</ion-content>

<ion-footer class="ion-no-border">
  <ion-toolbar>
    <div style="padding: 24px;">
      <button style="width: 100%; height: 56px;">Submit</button>
    </div>
  </ion-toolbar>
</ion-footer>
```

3. Build a .aab or .apk and run it on your Android Device.

### Code Reproduction URL

[https://github.com/SvenBudak/ion-input-bug](https://github.com/SvenBudak/ion-input-bug)

### Ionic Info

```
Ionic:

   Ionic CLI                     : 7.1.1 (C:\Users\sven\AppData\Roaming\nvm\v18.17.0\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 7.4.1
   @angular-devkit/build-angular : 16.2.3
   @angular-devkit/schematics    : 16.2.3
   @angular/cli                  : 16.2.3
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.4.0
   @capacitor/android : 5.4.0
   @capacitor/core    : 5.4.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v18.17.0 (C:\Program Files\nodejs\node.exe)
   npm    : 9.6.7
   OS     : Windows 10
   ```

### Additional Information

I didnt tested this on iOS... MAYBE its there also broken...

**Comment by SvenBudak** [comment] 2023-09-21 13:18
@liamdebeasi Oh sorry, my reproduction code isnt enought? should i create also a new public repository where i did the steps already?

**Comment by liamdebeasi** [comment] 2023-09-21 14:15
Yes, please create a public repo. Webview resizing & centering content can be kind of tricky, so I want to make sure I am reproducing the same behavior you are reporting.

**Comment by SvenBudak** [comment] 2023-09-21 16:12
@liamdebeasi i added [this](https://github.com/SvenBudak/ion-input-bug) repository URL to my Post.
There is also a .apk, with this you can test directly without building the app.

**Comment by matzar** [comment] 2023-09-22 11:12
@SvenBudak I've replied on discord with a workaround to apply a margin to the `ion-footer` element based on the `keyboardHeight`. I'll re-post the workout here:

```ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { IonicModule } from '@ionic/angular';
import { Keyboard, KeyboardInfo } from '@capacitor/keyboard';

@Component({
  selector: 'app-home',
  templateUrl: 'home.page.html',
  styleUrls: ['home.page.scss'],
  standalone: true,
  imports: [IonicModule],
})
export class HomePage implements OnInit, OnDestroy{
  keyboardWillShowListener: any;
  keyboardWillHideListener: any;

  constructor() {}

  ngOnInit() {
    this.keyboardWillShowListener = Keyboard.addListener('keyboardWillShow', (info: KeyboardInfo) => {
      this.hideFooter(info.keyboardHeight);
    });

    this.keyboardWillHideListener = Keyboard.addListener('keyboardWillHide', () => {
      this.showFooter();
    });
  }

  ngOnDestroy() {
    this.keyboardWillShowListener.remove();
    this.keyboardWillHideListener.remove();
  }

  hideFooter(keyboardHeight: number) {
    const ionFooter = document.querySelector('ion-app');
      if (ionFooter) ionFooter.style.marginBottom = -keyboardHeight + 'px';
  }

  showFooter() {
    const ionFooter = document.querySelector('ion-app');
    if (ionFooter) ionFooter.style.marginBottom = '0px';
  }
}
```

If you're shipping only on Android then that's all you'll have to do. If you want the solution to work both on Android and iOS you'll have to make sure that you only move the footer on Android:
```ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { IonicModule } from '@ionic/angular';
import { Keyboard, KeyboardInfo } from '@capacitor/keyboard';
import { Platform } from '@ionic/angular';

@Component({
  selector: 'app-home',
  templateUrl: 'home.page.html',
  styleUrls: ['home.page.scss'],
  standalone: true,
  imports: [IonicModule],
})
export class HomePage implements OnInit, OnDestroy{
  keyboardWillShowListener: any;
  keyboardWillHideListener: any;

  constructor(private platform: Platform) {}

  ngOnInit() {
    if (this.platform.is('android')) {
      this.keyboardWillShowListener = Keyboard.addListener('keyboardWillShow', (info: KeyboardInfo) => {
        this.hideFooter(info.keyboardHeight);
      });

      this.keyboardWillHideListener = Keyboard.addListener('keyboardWillHide', () => {
        this.showFooter();
      });
    }
  }

  ngOnDestroy() {
    this.keyboardWillShowListener.remove();
    this.keyboardWillHideListener.remove();
  }

  hideFooter(keyboardHeight: number) {
    const ionFooter = document.querySelector('ion-app');
      if (ionFooter) ionFooter.style.marginBottom = -keyboardHeight + 'px';
  }

  showFooter() {
    const ionFooter = document.querySelector('ion-app');
    if (ionFooter) ionFooter.style.marginBottom = '0px';
  }
}
```

And if you'd like Angular specific solution (well, workaround), it'd be best to use `Renderer2` to manipulate the DOM:

1. Add `#footer` template reference variable in your template
```html
<ion-footer #footer class="ion-no-border">
  <ion-toolbar>
    <div style="padding: 24px;">
      <button style="width: 100%; height: 56px;">Submit</button>
    </div>
  </ion-toolbar>
</ion-footer>
```

2. Use `Renderer2` to manipulate the `#footer`:
```ts
import { Component, OnInit, OnDestroy, Renderer2, ViewChild, ElementRef } from '@angular/core';
import { IonicModule } from '@ionic/angular';
import { Keyboard, KeyboardInfo } from '@capacitor/keyboard';
import { Platform } from '@ionic/angular';

@Component({
  selector: 'app-home',
  templateUrl: 'home.page.html',
  styleUrls: ['home.page.scss'],
  standalone: true,
  imports: [IonicModule],
})
export class HomePage implements OnInit, OnDestroy{
  keyboardWillShowListener: any;
  keyboardWillHideListener: any;
  @ViewChild('footer', { read: ElementRef, static: false }) private footer!: ElementRef;

  constructor(private platform: Platform, private renderer: Renderer2) {}

  ngOnInit() {
    if (this.platform.is('android')) {
    this.keyboardWillShowListener = Keyboard.addListener('keyboardWillShow', (info: KeyboardInfo) => {
      this.hideFooter(info.keyboardHeight);
    });

    this.keyboardWillHideListener = Keyboard.addListener('keyboardWillHide', () => {
      this.showFooter();
    });
  }
  }

  ngOnDestroy() {
    this.keyboardWillShowListener.remove();
    this.keyboardWillHideListener.remove();
  }

  hideFooter(keyboardHeight: number) {
    if (this.footer) {
      this.renderer.setStyle(this.footer.nativeElement, 'marginBottom', `${-keyboardHeight}px`);
    }
  }

  showFooter() {
    if (this.footer) {
      this.renderer.setStyle(this.footer.nativeElement, 'marginBottom', '0px');
    }
  }
}
```

Hope this helps! :)

**Comment by matzar** [comment] 2023-09-22 11:33
@SvenBudak I've replied on discord with a workaround to apply a margin to the `ion-app` element based on the `keyboardHeight`. I'll re-post the workaround here:

```ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { IonicModule } from '@ionic/angular';
import { Keyboard, KeyboardInfo } from '@capacitor/keyboard';

@Component({
  selector: 'app-home',
  templateUrl: 'home.page.html',
  styleUrls: ['home.page.scss'],
  standalone: true,
  imports: [IonicModule],
})
export class HomePage implements OnInit, OnDestroy{
  keyboardWillShowListener: any;
  keyboardWillHideListener: any;

  constructor() {}


  ngOnInit() {
    // When the keyboard will show, we need to move the footer down
    this.keyboardWillShowListener = Keyboard.addListener('keyboardWillShow', (info: KeyboardInfo) => {
      this.setAppMarginBottomOnKeyboardShow(info.keyboardHeight);
    });

    // When the keyboard will hide, we need to move the footer back to its place
    this.keyboardWillHideListener = Keyboard.addListener('keyboardWillHide', () => {
      this.setAppMarginBottomOnKeyboardHide();
    });

  }

  ngOnDestroy() {
    this.keyboardWillShowListener.remove();
    this.keyboardWillHideListener.remove();
  }

  // Move the footer down by the height of the keyboard
  setAppMarginBottomOnKeyboardShow(keyboardHeight: number) {
    const ionFooter = document.querySelector('ion-app');
      if (ionFooter) ionFooter.style.marginBottom = -keyboardHeight + 'px';
  }

  // Move the footer back to its place
  setAppMarginBottomOnKeyboardHide() {
    const ionFooter = document.querySelector('ion-app');
    if (ionFooter) ionFooter.style.marginBottom = '0px';
  }
}
```

If you're shipping only on Android then that's all you'll have to do. If you want the solution to work both on Android and iOS you'll have to make sure that you only move the footer on Android:
```ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { IonicModule } from '@ionic/angular';
import { Keyboard, KeyboardInfo } from '@capacitor/keyboard';
import { Platform } from '@ionic/angular';

@Component({
  selector: 'app-home',
  templateUrl: 'home.page.html',
  styleUrls: ['home.page.scss'],
  standalone: true,
  imports: [IonicModule],
})
export class HomePage implements OnInit, OnDestroy{
  keyboardWillShowListener: any;
  keyboardWillHideListener: any;

  constructor(private platform: Platform) {}


  ngOnInit() {
    if (this.platform.is('android')) {
    // When the keyboard will show, we need to move the footer down
    this.keyboardWillShowListener = Keyboard.addListener('keyboardWillShow', (info: KeyboardInfo) => {
      this.setAppMarginBottomOnKeyboardShow(info.keyboardHeight);
    });

    // When the keyboard will hide, we need to move the footer back to its place
    this.keyboardWillHideListener = Keyboard.addListener('keyboardWillHide', () => {
      this.setAppMarginBottomOnKeyboardHide();
    });
    }
  }

  ngOnDestroy() {
    this.keyboardWillShowListener.remove();
    this.keyboardWillHideListener.remove();
  }

  // Move the footer down by the height of the keyboard
  setAppMarginBottomOnKeyboardShow(keyboardHeight: number) {
    const ionFooter = document.querySelector('ion-app');
      if (ionFooter) ionFooter.style.marginBottom = -keyboardHeight + 'px';
  }

  // Move the footer back to its place
  setAppMarginBottomOnKeyboardHide() {
    const ionFooter = document.querySelector('ion-app');
    if (ionFooter) ionFooter.style.marginBottom = '0px';
  }
}
```

and for iOS, use `KeyboardResize` in your `capacitor.config.ts`
```ts
import { CapacitorConfig } from '@capacitor/cli';
import { KeyboardResize } from '@capacitor/keyboard';

const config: CapacitorConfig = {
  appId: 'io.ionic.starter',
  appName: 'test',
  webDir: 'www',
  server: {
    androidScheme: 'https'
  },
  plugins: {
    Keyboard: {
      resize: KeyboardResize.Ionic, // <-- Add this. Change according to your requirements. 
    },
  },
};

export default config;
```

Hope this helps! :)

**Comment by matzar** [comment] 2023-09-22 11:41
And if you wanted to be Angular specific you could use `Renderer2` to manipulate the DOM. The code could be simplified a little bit as well.

Here, I'm using `Rendered2` to manipulate the `ion-app` element. I've kept the Android platform check:
```ts
import { Component, OnInit, Renderer2 } from '@angular/core';
import { IonicModule } from '@ionic/angular';
import { Keyboard, KeyboardInfo } from '@capacitor/keyboard';
import { Platform } from '@ionic/angular';

@Component({
  selector: 'app-home',
  templateUrl: 'home.page.html',
  styleUrls: ['home.page.scss'],
  standalone: true,
  imports: [IonicModule],
})
export class HomePage implements OnInit{

  constructor(private platform: Platform, private renderer: Renderer2) {}


  ngOnInit() {
   if (this.platform.is('android')) {
      const setAppMarginBottom = (value: string) => {
        const ionApp = document.querySelector('ion-app');
        if (ionApp) this.renderer.setStyle(ionApp, 'marginBottom', value);
      };

      Keyboard.addListener('keyboardWillShow', (info: KeyboardInfo) => {
        setAppMarginBottom(`${-info.keyboardHeight}px`);
      });

      Keyboard.addListener('keyboardWillHide', () => {
        setAppMarginBottom('0px');
      });
    }
  }
}
```

**Comment by liamdebeasi** [comment] 2023-09-22 17:15
The webview seems to be resizing/adjusting content correctly when I test your application on a Pixel 4a:

https://github.com/ionic-team/ionic-framework/assets/2721089/6df5af5f-e5c9-4649-a66f-2805ec65af86

**Comment by SvenBudak** [comment] 2023-09-22 17:42
No, I really haven't changed anything at all. I noticed this issue a year ago in an app I developed with Ionic 5 or 6. I truly did nothing but create a new project with ionic start, then added the Android platform using the "Ionic" plugin in vsCode. Then i wrote the HTML in home.page.html that i posted already. Thats exactly all i did.

Perhaps this doesn't happen on all Android versions? Have you tried my .apk file? If so, then you have the exact same code running on your Android as I do. If it still works for you, it means that the error doesn't occur on all Android smartphones.

A user on Discord came up with a workaround for the bug on Android: https://discord.com/channels/520266681499779082/1152587915105415288/1154779909416304731

However, it would be desirable to know this bug has been fixed directly in Ionic.

**Comment by liamdebeasi** [comment] 2023-09-22 18:11
> Perhaps this doesn't happen on all Android versions? Have you tried my .apk file? If so, then you have the exact same code running on your Android as I do. If it still works for you, it means that the error doesn't occur on all Android smartphones.

As a general security practice I don't run pre-compiled `.apk` packages on my test devices since I can't easily inspect the code first, so I won't be able to try the `.apk` -- sorry about that!

However, I did try this on multiple devices, and I got a consistent result on all of them:

| Pixel 4a, Android 13, Chromium WebView v119 | Moto G4, Android 7, Chromium WebView v119 | Samsung Galaxy S6, Android 7, Chromium WebView v107 |
| - | - | - |
| <video src="https://github.com/ionic-team/ionic-framework/assets/2721089/6df5af5f-e5c9-4649-a66f-2805ec65af86"></video> | <video src="https://github.com/ionic-team/ionic-framework/assets/2721089/9e65d9b1-129f-42c4-9669-93d588278a4b"></video> | <video src="https://github.com/ionic-team/ionic-framework/assets/2721089/6100fb76-adc7-4431-8f0d-bae82e4f128b"></video> |

> However, it would be desirable to know this bug has been fixed directly in Ionic.

Since I can't reproduce the issue I'm not able to say if this is an Ionic bug or not. However, I will note that Ionic does not automatically adjust your webview/scrollable content when the keyboard opens on Android, so it is unlikely that Ionic is contributing to this behavior. iOS has some special behaviors we account for since there are different webview resize configurations, but those same options don't exist on Android.

**Comment by SvenBudak** [comment] 2023-09-22 18:18
That's really odd... I've tested it on my (OnePlus 8 Pro) and on my wife's smartphone (OnePlus 8) and the issue occurs on both...

Also, someone in the discord mentioned the same problem: https://discord.com/channels/520266681499779082/1154463869280981064

Additionally, over the past few months, I've seen people in the discord asking if anyone knows a fix for this problem... I find it really strange that you're not experiencing this issue...

Is there anything else I can do to help with reproducing the issue?

I have Android 13 (the latest for my smartphone model)
WebView: 116.0.5845.172 (the latest for my smartphone model)

**Comment by liamdebeasi** [comment] 2023-09-22 18:49
One thing to try would be to see if the issue reproduces with a regular `<input />` element (i.e. remove `ion-input`).

If the issue does reproduce, you could then try reproducing the issue in a blank Capacitor webview (I have a repo here I use for such reproductions: https://github.com/liamdebeasi/blank-capacitor-repro). If the issue reproduces there then the issue is likely at the webview level, so you'd probably want to file feedback with the Chromium team.

**Comment by SvenBudak** [comment] 2023-09-22 18:52
> One thing to try would be to see if the issue reproduces with a regular `<input />` element (i.e. remove `ion-input`).

Okay i will try that now! :)

This Expenser app is available in the Google Play Store: https://play.google.com/store/apps/details?id=com.devMonkeys.expenser2&hl=de&gl=US

I'm not sure, but maybe you are allowed to download and test it? It is signed and has been checked by Google for malicious code.

**Comment by SvenBudak** [comment] 2023-09-22 19:02
Ok, I added a native <input> element in the app with the blue area at the top. That doesn't center automatically either. (I wasn't even aware that <input> elements center automatically. I thought up until now that it was an Ionic feature? (because Ionic also adds a keyboard offset, etc.)

However, I'm not sure how I can test something with your blank-capacitor-repro since I'm not very familiar with it.

Does this mean I should open a webview issue?

Do you have any tips for me on how to explain it to them in a way that they'll understand the problem?

**Comment by liamdebeasi** [comment] 2023-09-22 19:06
>  (because Ionic also adds a keyboard offset, etc.)

We do add that, but only for iOS. You can try forcibly enabling these features, though your mileage may vary:

```javascript
IonicModule.forRoot({ scrollAssist: true, scrollPadding: true });
```

> Does this mean I should open a webview issue?

> Do you have any tips for me on how to explain it to them in a way that they'll understand the problem?

I'd explain that the webview resizes inconsistnetly across platforms in a way that can cause content that was in view to be shifted offscreen. I'd mention the device, Android version, and webview version you tested this on. I'd also include a screen recording and a link to the production app that you can reproduce this with.

**Comment by SvenBudak** [comment] 2023-09-22 19:19
> We do add that, but only for iOS. You can try forcibly enabling these features, though your mileage may vary:
> 
> ```js
> IonicModule.forRoot({ scrollAssist: true, scrollPadding: true });
> ```

Now I finally understand the problem... I thought the keyboard offset was added on every platform... When you activate the mobile dev tool in Chrome and neither choose iOS nor Android, but simply select Responsive... it seems an iOS agent is still set in the background. That's why I've always been developing with the iOS agent for the past few years.

Be that as it may. If the keyboard LAYS OVER the webview and the webview doesn't resize, then the input can't center, because it has already scrolled to the end of the webpage.

If I add a lot of <br> under the input, the centering also works... so the solution would be to activate the keyboard offset on Android as well.

https://github.com/ionic-team/ionic-framework/assets/4930169/9fd4fa10-2957-49c7-98a9-8c6f746ddc19

But is it really a good solution to activate the keyboard offset on Android as well? After all, it works on your smartphones without this activation... I don't want it to break other things or create double spacing on your smartphones.

I've updated my repository. Maybe you can pull and test again with your device to see if it works with all the <br>?

**Comment by SvenBudak** [comment] 2023-09-22 19:25
My GOD!!! The problem is that I use Google Gboard on my phone... With Microsoft SwiftKey Keyboard, it works even without many <br>

@liamdebeasi Can you do me one last favor and install the Google Gboard app from the Play Store on one of your test devices? I'm really curious to see if you then experience the same issue...

IF that's the case, there should definitely be a note about it in the documentation :D

**Comment by liamdebeasi** [comment] 2023-09-22 19:46
> Can you do me one last favor and install the Google Gboard app from the Play Store on one of your test devices? I'm really curious to see if you then experience the same issue...

I believe my Pixel 4a was using Gboard.

> IF that's the case, there should definitely be a note about it in the documentation :D

> Addendum: After several tests in different apps, I've now found that with the other keyboard it doesn't ALWAYS work, but it works significantly better in some apps. It's very strange...

I'd still recommend filing feedback with the Chromium team. They may be able to improve the webview so the resizing is more consistent across different keyboards. It's strange that the behavior is inconsistent depending on the keyboard used.

**Comment by SvenBudak** [comment] 2023-09-22 20:54
Just to keep this Issue up to date: https://bugs.chromium.org/p/chromium/issues/detail?id=1486115

**Comment by liamdebeasi** [comment] 2023-09-25 14:08
> by the way: is it for me possible to enable this keyboard offset also for android?

Yes, you will need to explicitly enable the (private) `scrollPadding` and `scrollAssist` options in your Ionic Framework config: https://github.com/ionic-team/ionic-framework/blob/8a9db8c9496be6c872376caa27ed04272afdc6d4/core/src/utils/config.ts#L208-L213

(Note these are internal since they are supposed to be enabled automatically. However, in this case it's fine to enable this manually since you are trying to work around a webview bug. We don't have plans to remove these options.)

> Just to keep this Issue up to date: https://bugs.chromium.org/p/chromium/issues/detail?id=1486115

Thanks for filing the issue! Since this is a problem with the webview and not Ionic I am going to close this. However, let me know if you have any questions.

**Closed by liamdebeasi** 2023-09-25 14:08 UTC
Labels: triage

**Comment by SvenBudak** [comment] 2023-09-25 17:34
scrollPadding and scrollAssist dont helped sadly.
also funny is t hat i today notice that centering is working allways on <ion-textarea>. maybe it is a ionic issue?

**Comment by liamdebeasi** [comment] 2023-09-26 13:08
`scrollPadding` and `scrollAssist` were designed for iOS. As I noted in https://github.com/ionic-team/ionic-framework/issues/28206#issuecomment-1731915213, your mileage may vary. I had hoped that would help some, but that seems to not be the case.

> also funny is t hat i today notice that centering is working allways on . maybe it is a ionic issue?

Ionic Framework does not handle webview resizing. However, you could also try modifying the `windowSoftInputMode` preference to use either `adjustPan` or `adjustResize` in `AndroidManifest.xml`. This may give you a more consistent behavior. So your file would look something like this:

```xml
...
<activity
  ...
  android:windowSoftInputMode="adjustPan"
>
</activity>
```

**Comment by SvenBudak** [comment] 2023-09-26 14:09
i changed the ion-footer in my repository a bit. it contains now 2 buttons, so it has more height then before. maybe you can reproduce it now also? because it was working on your device because the pixel ratio or scaling or something like that?

**Comment by SvenBudak** [comment] 2023-09-26 15:01
Okay, I'm very sure now that I've truly understood what the problem is...

Webview seems to only execute the scroll when more than 50% of the input is covered upon opening the keyboard.

| No `<ion-footer>` without `<br>` over `<ion-input>` | No `<ion-footer>` with `<br>` over `<ion-input>` |
| ---      | ---       |
| https://sinkacom.upperyard.de/no_br.mp4 | https://sinkacom.upperyard.de/with_br.mp4 |

Now exactly the same, just with `<ion-footer>`

| With `<ion-footer>` without `<br>` over `<ion-input>` | With `<ion-footer>` with `<br>` over `<ion-input>` |
| ---      | ---       |
| https://sinkacom.upperyard.de/footer_no_br.mp4 | https://sinkacom.upperyard.de/footer_with_br.mp4 |

Sorry, I don't understand how to embed videos within tables inline... As soon as I put a video in the table, the preview breaks, and only the link remains there 😅

Okay, as we can see, `<ion-footer>` doesn't really have any impact on the resizing of the `WebView`. And THAT is precisely the problem. `WebView` doesn't care whether there's an ion-footer there or not. For `WebView`, the end of the view is simply right at the end of the view. Whether there's an element like `<ion-footer>` overlaying something doesn't matter at all. I don't know, however, if and how this can be resolved.

The reason my repo doesn't work for you is because your test devices have different screen heights.

Did I explain the problem well? Did you understand what the issue is?

**Comment by liamdebeasi** [comment] 2023-09-26 15:18
> Okay, as we can see, <ion-footer> doesn't really have any impact on the resizing of the WebView. And THAT is precisely the problem. WebView doesn't care whether there's an ion-footer there or not. For WebView, the end of the view is simply right at the end of the view. Whether there's an element like <ion-footer> overlaying something doesn't matter at all. I don't know, however, if and how this can be resolved.

That makes sense. The scroll assist utility likely didn't work because it ran into the same problem --- the input isn't actually covered by the keyboard if we only consider the keyboard and not the footer too. However, your application is configured in a way such that the footer hides the input when the keyboard is open, so the circumstances are a bit different.

I still don't think this is an Ionic bug. We make a best attempt to adjust the input in the scrollable content, but we're not able to handle every specific layout such as this where the footer overlays the content. It's up to the developer to ensure the content is visible even if the keyboard is open.

----

One thing I've seen in several native iOS/Android apps is updating the UI such that the input never has the chance to be hidden by the keyboard. The hero image would need to shrink, but it would allow the input to appear higher on the screen.

You could also have the form + submit button as a floating container that adjusts when the keyboard opens. I detailed a similar pattern here: https://ionic.io/blog/keyboard-improvements-for-ionic-apps. This works by setting a CSS transform on the container equal to the height of the keyboard. One benefit here is it will allow content to appear docked to the top of the input.

**Comment by SvenBudak** [comment] 2023-09-26 17:29
But I have simply used the exact layout that is shown first and foremost in the documentation: https://ionicframework.com/docs/api/footer#basic-usage

```html
<ion-content class="ion-padding">
  <h1>Content</h1>
</ion-content>
<ion-footer>
  <ion-toolbar>
    <ion-title>Footer</ion-title>
  </ion-toolbar>
</ion-footer>
```

If there's an input in this content, then the exact same problem would arise...

There's nothing special about my design; if you search for mobile app designs on Dribbble or anywhere else, you'll find that almost every design has these buttons at the bottom.

![image](https://github.com/ionic-team/ionic-framework/assets/4930169/9d7da222-4a97-4eea-a0be-ada4806128e9)

A solution should be sought directly within Ionic because it seems that everyone who develops with Ionic faces this problem. And if the only solution is that `<ion-footer>` is hidden as soon as the keyboard opens, that's not ideal, but it would at least resolve the issue. Additionally, this information should possibly be added to the documentation. Many of my colleagues and I have grappled with this for 1 to 2 years, constantly puzzling over it. I'm sure others are experiencing the same.

**Comment by SvenBudak** [comment] 2023-09-26 18:35
I have expanded the HTML code from the ion-footer docs by adding two elements to make it clear that it has nothing to do with a specific app design: https://ionicframework.com/docs/api/footer#basic-usage

```html
<ion-content [fullscreen]="true" class="ion-padding">
  <h1>Content</h1>
  <p>A text that has exactly the right length so that the input after opening the keyboard does not extend more than 50% over the webview. (Different on every screen)</p>
  <ion-input fill="outline"></ion-input>
</ion-content>

<ion-footer>
  <ion-toolbar>
    <ion-title>Footer</ion-title>
  </ion-toolbar>
</ion-footer>
```

https://github.com/ionic-team/ionic-framework/assets/4930169/50efdcaa-bd0f-4c30-b710-b540326a1e1d

**Comment by liamdebeasi** [comment] 2023-10-02 14:25
> A solution should be sought directly within Ionic because it seems that everyone who develops with Ionic faces this problem. And if the only solution is that <ion-footer> is hidden as soon as the keyboard opens, that's not ideal, but it would at least resolve the issue. 

As I noted in https://github.com/ionic-team/ionic-framework/issues/28206#issuecomment-1735762377, this is beyond the scope of what Ionic handles automatically for developers. We make a best effort to adjust inputs when the inputs are in the scrollable container. The reason we don't account for anything more complex than that is because we cannot safely assume what the desired behavior is. For example, a developer may want padding add to the content so the content can scroll. Another developer may want to transform the text input. Alternatively, other developers may want something entirely different.

Our position is the app developer is best suited to build a solution here because the solution needs to be crafted for their specific app layout. I gave several potential solutions. It sounds like you weren't a fan of any of them, but perhaps you could use them as a starting point for a solution that is more appropriate for your use case.

>Additionally, this information should possibly be added to the documentation. Many of my colleagues and I have grappled with this for 1 to 2 years, constantly puzzling over it. I'm sure others are experiencing the same.

If you have ideas for how we can improve our documentation, we'd be more than happy to accept a pull request for our docs site. I'd recommend updating this page since it covers keyboard behaviors: https://ionicframework.com/docs/developing/keyboard

----

As noted in https://github.com/ionic-team/ionic-framework/issues/28206#issuecomment-1733785898 this is not a bug with Ionic. I've explained the team's decision for closing this multiple times. There's an opportunity to improve the docs if you're interested in contributing. However, I'm going to lock this thread since I think the discussion here has served its purpose. Thanks!
