### ISSUE TITLE
bug: event ionKnobMoveStart and ionKnobMoveEnd not emitted on ion-range as per documentation

### ISSUE THREAD

**Issue by vgahlaut** [ionic-team/ionic-framework#25304] opened 2022-05-18 04:38 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

As per ion-range [documentation ](https://ionicframework.com/docs/api/range#events) events ionKnobMoveEnd and ionKnobMoveStart are not fired at all. 

### Expected Behavior

events ionKnobMoveStart  and ionKnobMoveEnd should be emitted when range knob is moved

### Steps to Reproduce

HTML Code
`<ion-range [min]="0" [max]="4" [step]="1" snaps="true" debounce="500" (ionKnobMoveStart)="knobStart($event)" (ionKnobMoveEnd)="knobEnd($event)"></ion-range>`

Typescript code

`  knobStart(event){
    console.log('knobStart:: invoked');
  }

  knobEnd(event){
    console.log('knobEnd:: invoked');
  }`

### Ionic Info

Ionic:

   Ionic CLI                     : 6.19.0 (C:\Users\vipin\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.0.15
   @angular-devkit/build-angular : 13.2.6
   @angular-devkit/schematics    : 13.2.6
   @angular/cli                  : 13.2.6
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.4.3
   @capacitor/android : not installed
   @capacitor/core    : 3.4.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.5.0

System:

   NodeJS : v16.14.2 (C:\Program Files\nodejs\node.exe)
   npm    : 8.6.0
   OS     : Windows 10

**Comment by liamdebeasi** [comment] 2022-05-18 12:45
Thanks for the issue. These events were added as part of Ionic 6.1 and are not available in Ionic 6.0.15: https://github.com/ionic-team/ionic-framework/blob/main/CHANGELOG.md#610-vanadium-2022-04-13

Please update to Ionic 6.1.0 or newer to use this feature. I am going to close this as this is not a bug in Ionic.

**Closed by liamdebeasi** 2022-05-18 12:45 UTC
Labels: triage
