### ISSUE TITLE
bug: Card modal consistently flicker 2 times when trying to close it

### ISSUE THREAD

**Issue by phuctm97** [ionic-team/ionic-framework#28577] opened 2023-11-27 07:21 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When swipe to close card modal and cancel, the modal consistently flicker/flash a few times before working smoothly. It seems like a reproducible behavior.

### Expected Behavior

It should not flicker/flash. It should always work smoothly like after a few attempts.

### Steps to Reproduce

1. Go to https://ionicframework.com/docs/api/modal#card-modal and try in the example.
2. Try pull down to close and cancel in the middle. The modal always consistently flicker/flash 2 times before working smoothly.

Or you can copy the example into a app and run on your device to reproduce it on device.

https://github.com/ionic-team/ionic-framework/assets/25026967/70ef0b34-2f29-47c1-8439-f73684aac68b

### Ionic Info

Ionic:

   Ionic CLI       : 7.1.5 (/Users/phuctm97/Projects/listenany/node_modules/.pnpm/@ionic+cli@7.1.5/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 7.5.6 (/Users/phuctm97/Projects/listenany/node_modules/.pnpm/@ionic+react@7.5.6_react-dom@18.2.0_react@18.2.0/node_modules/@ionic/react)

Capacitor:

   Capacitor CLI      : 5.5.1
   @capacitor/android : not installed
   @capacitor/core    : 5.5.1 (/Users/phuctm97/Projects/listenany/node_modules/.pnpm/@capacitor+core@5.5.1/node_modules/@capacitor/core)
   @capacitor/ios     : 5.5.1 (/Users/phuctm97/Projects/listenany/node_modules/.pnpm/@capacitor+ios@5.5.1_@capacitor+core@5.5.1/node_modules/@capacitor/ios)

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v18.18.0 (/Users/phuctm97/.nvm/versions/node/v18.18.0/bin/node)
   npm    : 10.2.0
   OS     : macOS Unknown

**Comment by liamdebeasi** [comment] 2023-11-27 14:43
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/28467.

**Closed by liamdebeasi** 2023-11-27 14:43 UTC
Labels: triage
