### ISSUE TITLE
bug: IonRouter is undefined when transitioning to page with Ion-Tabs, using vue-router and not @ionic/vue-router

### ISSUE THREAD

**Issue by karmstr7** [ionic-team/ionic-framework#23204] opened 2021-04-18 07:45 UTC
Relevant packages
```
"@ionic/core": "^5.5.1",
"@ionic/vue": "^5.5.2",
"vue-router": "^4.0.1",
"vue": "^3.0.4",
```

**Current behavior:**
Tested on the web and specific to the [Ion-Tabs](https://ionicframework.com/docs/api/tabs) components when using vue-router rather than @ionic/vue-router,  pages that include ion-tabs won't render because ionRouter is undefined. Also posted on [SO](https://stackoverflow.com/questions/67133990/ionic-tabs-not-rendering-due-to-router-incompatibilty-ionrouter-is-undefined-wh) with more detail. 

**Expected behavior:**
Should still navigate correctly to the given route, without defining the router file using @ionic/vue-router.

**Steps to reproduce:**
Use `createWebHistory` and `createRouter` from `vue-router` in the `router.ts` file to define your router file.
Then use the start code for ion-tabs from [here](https://ionicframework.com/docs/api/tabs).

**Comment by liamdebeasi** [comment] 2021-04-19 14:30
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The `@ionic/vue-router` package is required for tabs to work properly since each tab is its own navigation stack.

**Closed by liamdebeasi** 2021-04-19 14:30 UTC
Labels: triage
