### ISSUE TITLE
bug: ion-radio warnings in console when opening an ion-select with "Popover" interface

### ISSUE THREAD

**Issue by Lechevallier** [ionic-team/ionic-framework#27297] opened 2023-04-27 10:40 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Lots of **Ionic Warning** related to `ion-radio` appears in the navigator console when opening a Select with interface "Popover"

![image](https://user-images.githubusercontent.com/10246002/234837832-6188516d-bfd2-4316-9651-98fa11f1d4e7.png)

### Expected Behavior

No warning should appears in the navigator console when opening a Select with interface "Popover".
Warnings are on some code that developer don't have access to.

### Steps to Reproduce

- Go to Ionic official doc, **Select** page, **Interface Options** section: [link](https://ionicframework.com/docs/api/select#interface-options)
- Open the developer console of the navigator
- In the sandbox (available [here](https://stackblitz.com/run?file=src%2Fapp%2Fapp.component.ts) as well), click on the second select (the one called "Popover")
- Lots of **Ionic Warning** related to `ion-radio` appears in the console

### Code Reproduction URL

https://stackblitz.com/run?file=src%2Fapp%2Fapp.component.ts

### Ionic Info

Ionic 7

**Comment by amandaejohnston** [comment] 2023-04-27 14:11
Thank you for the issue. I'm going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/27071.

**Closed by amandaejohnston** 2023-04-27 14:11 UTC
Labels: triage
