### ISSUE TITLE
bug: delay before dates display on iOS

### ISSUE THREAD

**Issue by antoine92190** [ionic-team/ionic-framework#24822] opened 2022-02-21 08:57 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

There is a delay before the calendar dates are displayed on iOS device. No issue on browser or Android.

https://user-images.githubusercontent.com/16256207/154921468-a3abcd58-2602-4e26-ab5b-8514c50562a2.mov

### Expected Behavior

There should be no delay before displaying calendar dates

### Steps to Reproduce

Open the date picker as a modal, and see the delay before seeing the calendar dates

### Ionic Info

```
Ionic:

   Ionic CLI                     : 6.18.1 (/Users/antoinedupont/.npm-packages/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.8-dev.1644432569.937206e
   @angular-devkit/build-angular : 12.2.4 (/Users/antoinedupont/dev/agorapulse/platform/frontend/node_modules/@angular-devkit/build-angular)
   @angular-devkit/schematics    : 11.2.18
   @angular/cli                  : 12.2.4 (/Users/antoinedupont/dev/agorapulse/platform/frontend/node_modules/@angular/cli)
   @ionic/angular-toolkit        : 3.1.1

Capacitor:

   Capacitor CLI      : 3.2.4
   @capacitor/android : 3.2.4
   @capacitor/core    : 3.2.4
   @capacitor/ios     : 3.2.4

Cordova:

   Cordova CLI       : not installed
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v14.17.0 (/usr/local/bin/node)
   npm    : 6.14.13
   OS     : macOS Monterey
   Xcode  : Xcode 13.2.1 Build version 13C100
```

**Comment by sean-perkins** [comment] 2022-02-21 17:53
@antoine92190 thanks for reporting this issue. 

We currently delay the render of the calendar month days to offset intersection observers firing at incorrect times during initialization. 

The delay in a modal though is not ideal and we will track this as a bug to see if there's a different approach that can remove the need for the delay.

Thanks!

**Comment by liamdebeasi** [comment] 2022-02-22 20:59
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/24542. (Same underlying issue)

**Closed by liamdebeasi** 2022-02-22 20:59 UTC
Labels: package: core, type: bug
