### ISSUE TITLE
bug: File Input breaks on iOS 15 after unlocking device when installed to Home Screen

### ISSUE THREAD

**Issue by ghwilley** [ionic-team/ionic-framework#24783] opened 2022-02-14 21:02 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [X] v6.x

### Current Behavior

When an app with a file input is added to home on iOS 15, after locking and unlocking the screen while the app is up, the file input button stops working and the file upload options (Photo Library, Take Photo and Choose File) do not appear.

### Expected Behavior

The file upload options should appear.

### Steps to Reproduce

1. Generate a basic Ionic app with a file input that accepts images:
`<ion-app>
    <ion-content>
        <input type="file" accept="image/png, image/jpeg">
    </ion-content>
</ion-app>`

2. On an iOS 15 device, open the app in Safari, click the share button and select 'Add to Home Screen'.
3. Open the app from the Home Screen. The file upload button should work.
4. While the app is still up, lock your device.
5. Unlock your device and try to select a file.

### Code Reproduction URL

- https://github.com/ghwilley/basicIonicFileInput

### Ionic Info

Ionic:

   Ionic CLI                     : 5.4.16 (C:\Users\Username\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 6.0.7
   @angular-devkit/build-angular : 13.0.4
   @angular-devkit/schematics    : 13.0.4
   @angular/cli                  : 13.0.4
   @ionic/angular-toolkit        : 5.0.3

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v16.14.0 (C:\Program Files\nodejs\node.exe)
   npm    : 8.4.1
   OS     : Windows 10

### Additional Information

We were noticing the issue on Ionic 5 and Angular 11. Still getting it after updating with the Ionic Info posted.

This has been intermittent at times and might take clearing site data and trying again. In my minimal reproduction I've been able to get it on the first try on an iPhone XS and 6th gen iPad.

**Comment by liamdebeasi** [comment] 2022-02-14 22:11
Thanks for the issue. Are you able to identify the part of Ionic you think is causing this issue? From the code snippet you provided, it looks like you are using a native `<input>` element, which is not Ionic-related.

**Comment by ghwilley** [comment] 2022-02-15 13:45
I can't quite nail it down. I made a vanilla website with the ios meta tags:
`<meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />`
This vanilla site, installed to home, didn't replicate the behavior. I tried adding complexity to the vanilla site with showing and hiding divs/dynamic z-indexes on elements, no luck. The issue doesnt appear in iOS 14. Early on in debugging I thought it was related to an ion-modal and that maybe the dialogue was showing up off screen. I went through and hide every element, layer by layer, and didnt see anything.

I also looked into the click events and they're registering even when the dialog doesn't show up.

**Comment by liamdebeasi** [comment] 2022-02-16 01:13
Can you provide a GitHub repo that I can use to verify this behavior?

**Comment by ghwilley** [comment] 2022-02-16 14:07
Of course, here you go: https://github.com/ghwilley/basicIonicFileInput

**Comment by liamdebeasi** [comment] 2022-02-18 13:59
Thanks. What version of iOS are you testing this on? I cannot reproduce this behavior on my end.

**Comment by ghwilley** [comment] 2022-02-18 15:51
I could make a video of the issue being reproduced as well if that helps.

**Comment by sean-perkins** [comment] 2022-02-18 18:01
@ghwilley I was able to replicate the issue with your reproduction app & steps on iOS 15.3.1.

No exceptions/errors are thrown. 

After deleting the local bookmark and following the steps again, I'm not able to replicate consistently. One thing I am noticing, is that the popover options for selecting the source of the file can occasionally render at the bottom of the screen, instead of relative to the tap target. I wonder if when it's not functioning, if the options are rendering off screen.

|Correct|Incorrect|
|---|---|
|<img src="https://user-images.githubusercontent.com/13732623/154737073-fbc75ae9-0b39-4a6f-8834-cea40629999c.PNG" width="350px" />| <img src="https://user-images.githubusercontent.com/13732623/154737043-b3c76086-51eb-4ed0-8619-6a211c04e032.PNG" width="350px" />|

I am unable to narrow this down to anything Ionic specific though.

**Comment by liamdebeasi** [comment] 2022-02-18 20:22
Thanks for the additional information. I was able to reproduce a similar behavior pretty consistently by going to the home screen during the context menu's dismissing animation.

I was also able to reproduce this behavior outside of Ionic. The difference is very subtle, but notice in the "bad" screenshot that the context menu is slightly lower than where it should be.

| good | bad |
| ----- | ---- |
| ![IMG_0542](https://user-images.githubusercontent.com/2721089/154755587-d8c45300-9d46-471c-a9f9-ec67d4b9cc68.PNG) | ![IMG_0543](https://user-images.githubusercontent.com/2721089/154755599-fe292549-9717-4e7e-9651-e1522d9d3ade.PNG) |

 I think this problem is made worse in Ionic because the file select input is placed in a non-body container whereas the non-Ionic reproduction is placed in a body container. (I could be wrong about this though).

-------

The root issue here does not seem to be coming from Ionic, so I am going to close this out. I definitely encourage you to report this bug to the WebKit team at https://bugs.webkit.org/. Alternatively, you could join the WebKit Slack and see if anyone there has suggestions for workarounds. Thanks!

**Closed by liamdebeasi** 2022-02-18 20:22 UTC
Labels: triage

**Comment by ghwilley** [comment] 2022-02-18 20:53
Thanks for all the help! I was able to find this in webkit and it sounds like it the same issue: https://bugs.webkit.org/show_bug.cgi?id=235891
