### ISSUE TITLE
bug: Cant remove backButtonText

### ISSUE THREAD

**Issue by Hesesses** [ionic-team/ionic-framework#28962] opened 2024-02-02 10:37 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

I'm using the latest Ionic 7.7.0 with Angular standalone components

both `provideIonicAngular({ backButtonText: ''}),` 
and `<ion-back-button defaultHref="/tabs/home" text="" ></ion-back-button>`

Gives an console error `Cannot read properties of null (reading 'getBoundingClientRect')`

### Expected Behavior

Display backbutton without any texts and no errors and goes back to last page

### Steps to Reproduce

Edit main.ts:
```
bootstrapApplication(AppComponent, {
  providers: [
    { provide: RouteReuseStrategy, useClass: IonicRouteStrategy },
    provideIonicAngular({ backButtonText: ''}),
    provideRouter(routes),
  ],
});
```
create pages and navigation to go forward and back

### Ionic Info

```
Ionic CLI                     : 7.1.1 (/opt/homebrew/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.7.0
   @angular-devkit/build-angular : 17.1.2
   @angular-devkit/schematics    : 17.1.2
   @angular/cli                  : 17.1.2
   @ionic/angular-toolkit        : 9.0.0
   ```

**Comment by amandaejohnston** [comment] 2024-02-02 15:25
Actually, I'm going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/28751. Apologies for any confusion.

**Closed by amandaejohnston** 2024-02-02 15:25 UTC
Labels: ionitron: needs reproduction
