### ISSUE TITLE
bug: stencil async task queue interferes with ngx virtual scroller updates

### ISSUE THREAD

**Issue by julianpoy** [ionic-team/ionic-framework#24120] opened 2021-10-27 00:24 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

https://github.com/ionic-team/ionic-framework/issues/23437#issuecomment-950560276

Ever since [5.4.2](https://github.com/ionic-team/ionic-framework/releases/tag/v5.4.2) ngx-virtual-scroller has extreme jumping issues on IOS and is completely unusable past that version.

I created a demo repo to demonstrate the issue: https://github.com/julianpoy/demo-ionic-ngx-virtual-scroller-issues

On IOS, scroll through the list - notice the jumping.

The issue is most evident when scrolling quickly. Often when reaching the bottom of the list, the scroll position will jump directly back up to the top.

On version 5.4.2 and above you'll see this:

![ezgif-3-23a51daab51d](https://user-images.githubusercontent.com/7751154/138979440-b0331027-c2f2-4ade-9683-11c628debcc1.gif)

### Expected Behavior

Not to jump/glitch/generally be unusable.

See ionic-5.4.1 branch of the demo repo for an example.

Working as expected on 5.4.1:

![ezgif-3-1895361388dd](https://user-images.githubusercontent.com/7751154/138978997-d2cbd07f-c335-4d6c-b449-01856f4801dd.gif)

### Steps to Reproduce

https://github.com/julianpoy/demo-ionic-ngx-virtual-scroller-issues

See the reproduction steps there.

### Code Reproduction URL

https://github.com/julianpoy/demo-ionic-ngx-virtual-scroller-issues

### Ionic Info

Ionic:

   Ionic CLI                     : 6.18.0 (/home/julian/.local/share/nvm/v14.18.1/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.8.4
   @angular-devkit/build-angular : 12.1.4
   @angular-devkit/schematics    : 12.1.4
   @angular/cli                  : 12.1.4
   @ionic/angular-toolkit        : 4.0.0

Capacitor:

   Capacitor CLI      : 3.2.5
   @capacitor/android : not installed
   @capacitor/core    : 3.2.5
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.3
   native-run  : 1.5.0

System:

   NodeJS : v14.18.1 (/home/julian/.local/share/nvm/v14.18.1/bin/node)
   npm    : 6.14.15
   OS     : Linux 5.4

**Comment by julianpoy** [comment] 2021-10-31 16:04
@liamdebeasi yep, sorry. The original repo had a trackby function but I forgot to copy that over when creating the demo.

The issue remains the same regardless of the addition or removal of the trackby function.

I've added the trackby function to the demo repo.

**Comment by liamdebeasi** [comment] 2021-11-30 14:00
Sorry for the delay. I took a closer look at what is happening here. I have isolated the issue to this commit: https://github.com/ionic-team/ionic-framework/commit/c83826aa733594cf8041e34d5b4832907d7bc530

In Stencil 1, the default task queue was "async-congestion" but in Stencil 2 it is now using the "async" task queue. This seems to be clashing with some render lifecycles in Angular. I need to discuss more with the Stencil team about the appropriate path forward here.

**Comment by julianpoy** [comment] 2022-03-18 20:57
@liamdebeasi any updates here?

**Comment by julianpoy** [comment] 2022-04-27 04:52
@liamdebeasi just checking in here again, is there anything I can do to help with this?

**Comment by liamdebeasi** [comment] 2022-04-27 13:15
Hey there,

Sorry I missed your previous comment. So the big blocker right now is trying to identify how to account for the rendering lifecycle of the virtual scroller within the async task queue.

There was a similar issue a while back (https://github.com/ionic-team/ionic-framework/issues/22775) where the solution was to use trackBy, but that does not seem to work here. Perhaps the solution is a combination of trackBy and something else?

**Comment by liamdebeasi** [comment] 2022-08-18 19:43
Hey @julianpoy,

Apologies for the delay. I was able to take a closer look at this issue. 

After debugging this a bit more, I think that this is a bug in `ngx-virtual-scroller`, not Ionic or Stencil. There was indeed a change in Ionic 5.4.2 that made this issue appear, but I believe that the Ionic change triggered a bug in `ngx-virtual-scroller` that was not being triggered prior to 5.4.2.

------

The primary issue is here in the `ngx-virtual-scroller` source code: https://github.com/rintoj/ngx-virtual-scroller/blob/d1aed1eae324643d51f042acb8d902d3d51aa999/src/virtual-scroller.ts#L836

The virtual scroller uses `viewport.startIndexWithBuffer` and `viewport.endIndexWithBuffer` to determine the subset of the `this.items` array to render. These variables act as a sliding window so that new items appear as you scroll. For example, you may have a start of `0` and an end of `9`. As you scroll down, start will increase to `1` and end will increase to `10`.

The problem is that sometimes the library incorrectly calculates `viewport.startIndexWithBuffer`: https://github.com/rintoj/ngx-virtual-scroller/blob/d1aed1eae324643d51f042acb8d902d3d51aa999/src/virtual-scroller.ts#L1293. 

This means that if you have a start of `30` and an end of `39`, sometimes the start will reset to `4`, `0`, or some other number. This will happen multiple times in succession which results in the jumping behavior you reported in the original issue. When the index resets to `0` it gives the appearance of the scroll position jumping to the top.

The issue appears to trace back to this `startingArrayIndex_fractional` variable: https://github.com/rintoj/ngx-virtual-scroller/blob/d1aed1eae324643d51f042acb8d902d3d51aa999/src/virtual-scroller.ts#L1263. It appears that some of the `dimensions` values such as `itemsPerPage` are incorrect.

--------

This all means that on every scroll, the virtual scroller is attempting to create a large number of Ionic components (`ion-item` in this case). Depending on how quickly you scroll, I could get the app to try and create almost 200 `ion-item` instances over the course of a few scroll event callbacks. This results in forced layout shifts and rendering frames that can take 100s of milliseconds, creating even further jank.

I would normally recommend that you create an issue on the library repo, but it looks like `ngx-virtual-scroller` has not been updated in about 2 years: https://github.com/rintoj/ngx-virtual-scroller. It looks like another developer forked the repo and is maintaining a newer version of the library: https://github.com/iharbeck/ngx-virtual-scroller

It may be worth trying that newer library to see if the issue still reproduces. If it does, I recommend creating an issue on their repo.

I am going to close this since this is not a bug in Ionic, but please let me know if you have any additional questions. Thanks!

**Closed by liamdebeasi** 2022-08-18 19:43 UTC
Labels: type: bug, stencil
