### ISSUE TITLE
bug: NavAnimation with only transform (without opacitiy) won't work correctly

### ISSUE THREAD

**Issue by Bungeefan** [ionic-team/ionic-framework#21998] opened 2020-08-28 00:07 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

If I only use '.fromTo('transform', 'translateY(100%)', 'translateY(0)')' in my navAnimation, the page isn't displayed before the (invisible) animation is finished.

**Expected behavior:**

The page should be displayed at the beginning of the animation.

**Steps to reproduce:**

Add a custom navAnimation.
Don't use any effects like opacity (e.g. only transform).
Trigger the animation.

**Related code:**
It only works in Ionic v5 because of the new Animation API.

I used the following code to make the leaving page go up and the new one to come from the bottom.
Notice that I only had to use the opacity on the entering element for the workaround.
```
const enteringAnimation = animationCtrl.create()
    .addElement(opts.enteringEl)
    .duration(DURATION)
    .fromTo('opacity', 1, 1)
    .fromTo('transform', 'translateY(100%)', 'translateY(0)')

const leavingAnimation = animationCtrl.create()
    .addElement(opts.leavingEl)
    .duration(DURATION)
    .fromTo('transform', 'translateY(0)', 'translateY(-100%)');

return animationCtrl.create()
    .addAnimation([enteringAnimation, leavingAnimation]);
```

**Other information:**

I tried to find the cause of this issue and as far as I could find out. It's the 'ion-page-hidden' class on the component (e.g. app-home) which prevents the component being displayed properly.
I tried it multiple times with and without the opacity setting and I saw that when I am only using transform the 'ion-page-hidden' class stays all the time.
But when I am using opacity even if I only set from 1 to 1, the class gets replaced by 'ion-page-invisible' before the start and the animation looks fine.
Therefore, my guess to fix this would be to replace the class even when not using visibility effects like opacity.

**Ionic info:**

```
Ionic:
   Ionic CLI                     : 6.11.1 (/home/*****/.npm-global/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.3.1
   @angular-devkit/build-angular : 0.901.12
   @angular-devkit/schematics    : 9.1.12
   @angular/cli                  : 9.1.12
   @ionic/angular-toolkit        : 2.3.0

Capacitor:

   Capacitor CLI   : 2.4.0
   @capacitor/core : 2.4.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.19.0 (/usr/bin/node)
   npm    : 6.14.8
   OS     : Linux 5.4
```

**Comment by Bungeefan** [comment] 2020-08-28 20:59
@liamdebeasi I created a repository to show the issue.
https://github.com/Bungeefan/issue-21998

**Comment by liamdebeasi** [comment] 2020-09-03 17:22
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. You need to remove the `ion-page-invisible` class from the entering element before starting the animation. See: https://github.com/ionic-team/ionic-framework/blob/master/core/src/utils/transition/md.transition.ts#L20

**Closed by liamdebeasi** 2020-09-03 17:22 UTC
Labels: ionitron: needs reproduction
