### ISSUE TITLE
bug: `ion-tabs` does not support index route

### ISSUE THREAD

**Issue by AmitMY** [ionic-team/ionic-framework#27439] opened 2023-05-09 18:32 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

It is currently not possible to set the main tab to be at the route page
```html
<ion-tabs>
  <ion-tab-bar slot="bottom">
    <ion-tab-button tab="">
      <ion-icon aria-hidden="true" name="home"></ion-icon>
      <ion-label>Home</ion-label>
    </ion-tab-button>
  </ion-tab-bar>
</ion-tabs>
```

if used like this, "Home" is not highlighted when one is at the `/` page, and the tab does not navigate the user home

### Expected Behavior

The tab should be highlighted, and clicking it should navigate to the index

### Steps to Reproduce

Add multiple tabs, and an `ion-tab-button` with `tab=""`

### Code Reproduction URL

https://stackblitz.com/edit/angular-68pwvy?file=src/app/example.component.html

1. "Listen Now" is not highlighted
2. Click "Radio" then "Listen Now" again. Navigation does not work
### Ionic Info

Ionic:

Ionic CLI : 7.1.1

Utility:

cordova-res : 0.15.4
native-run : 1.7.2

System:

NodeJS : v18.15.0
npm : 9.5.0
OS : macOS Unknown

**Comment by AmitMY** [comment] 2023-05-09 19:50
Reproduction:
https://stackblitz.com/edit/angular-68pwvy?file=src/app/example.component.html

**Comment by liamdebeasi** [comment] 2023-05-11 13:11
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/16949.

**Closed by liamdebeasi** 2023-05-11 13:11 UTC
Labels: triage
