### ISSUE TITLE
feat: update to react-router v6

### ISSUE THREAD

**Issue by vaynevayne** [ionic-team/ionic-framework#28558] opened 2023-11-20 07:25 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

update to react-router v6

### Describe the Use Case

v6 supports data routing, considering an upgrade?

**Comment by liamdebeasi** [comment] 2023-11-20 14:21
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/24177.

**Closed by liamdebeasi** 2023-11-20 14:21 UTC
Labels: triage
