### ISSUE TITLE
bug: TypeError: e is not a function

### ISSUE THREAD

**Issue by paddelboot** [ionic-team/ionic-framework#23036] opened 2021-03-11 18:53 UTC
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**
Upon clicking the `ion-menu-button` component and selecting an item from the `ion-list` in the menu, I get below error. It seems to be related to TypeScript, which I have been trying to deactivate as [described in the official docs](https://ionicframework.com/docs/vue/quickstart#build-your-way-with-typescript-or-javascript).

````
ion-app_8.entry.js?c215:1 TypeError: e is not a function
    at eval (webpack-internal:///./node_modules/@ionic/core/dist/esm-es5/index-d8cfb4a8.js:14)
    at step (webpack-internal:///./node_modules/tslib/tslib.es6.js:124)
    at Object.eval [as next] (webpack-internal:///./node_modules/tslib/tslib.es6.js:105)
    at fulfilled (webpack-internal:///./node_modules/tslib/tslib.es6.js:95)
eval @ ion-app_8.entry.js?c215:1
````

**Expected behavior:**
Being able to navigate the `ion-menu` items.

**Steps to reproduce:**
Not sure, doesn't work in my starter app and not in my main project app.

**Related code:**

https://github.com/paddelboot/ionic-test

**Ionic info:**

**Additional Info**
This is supposed to be an Ionic Vue app without Typescript support.

```
Ionic:

   Ionic CLI       : 6.13.1 (/home/hans/.nvm/versions/node/v15.8.0/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 5.5.4

Capacitor:

   Capacitor CLI   : 2.4.6
   @capacitor/core : 2.4.6

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v15.8.0 (/home/hans/.nvm/versions/node/v15.8.0/bin/node)
   npm    : 7.5.1
   OS     : Linux 5.8

```

**Comment by liamdebeasi** [comment] 2021-03-11 20:34
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The problem here is that you are not providing a valid animation to `navAnimation` in your config. As per https://ionicframework.com/docs/vue/config#config-options, `navAnimation` accepts an `AnimationBuilder` instance which is just a function that calls `createAnimation()`.

If you want to disable animations, you should set `:animated="false"` on your `ion-router-outlet` instance.

**Closed by liamdebeasi** 2021-03-11 20:34 UTC
Labels: triage

**Comment by paddelboot** [comment] 2021-03-12 13:16
Thanks for pointing this out. I did not find the options for `navAnimation` and therefore guessed `none`.

I keep struggling though. Even with the page transition animation configured correctly, I cannot use the menu beyond the first click. The menu simply won't open again and I don't see any error messages in the console.

**Comment by liamdebeasi** [comment] 2021-03-12 14:14
I think the problem is with where you have placed `ion-menu`. Since you have `ion-menu` in your `Home` component, when you transition to `Projects` component, the `Home` component, including the menu, is hidden.

I recommend placing your `ion-menu` inside of `App.vue` like this:

```js
<template>
  <ion-app>
    <ion-menu menu-id="testmenu" content-id="mycontent">
      <ion-content>
        <ion-list>
          <ion-item type="button" router-link="/projects">
            <ion-label>Pokémon Projects</ion-label>
          </ion-item>
          <ion-item type="button" router-link="/home">
            <ion-label>Pokémon Home</ion-label>
          </ion-item>
        </ion-list>
      </ion-content>
    </ion-menu>
    <ion-router-outlet :animated="false" id="mycontent" />
  </ion-app>
</template>

<script>
import { IonApp, IonRouterOutlet, IonMenu, IonContent, IonList, IonItem, IonLabel } from '@ionic/vue';
import { defineComponent } from 'vue';

export default defineComponent({
  name: 'App',
  components: {
    IonApp,
    IonRouterOutlet,
    IonMenu, 
    IonContent, 
    IonList,
    IonItem, 
    IonLabel
  }

});
</script>
```

By doing this, you can also remove the `ion-menu` instances from `Home` and `Projects` (but you can keep the `ion-menu-button` in each).

Additionally, if you want the menu to close whenever you click on the item in your menu, you can wrap each `ion-item` in `ion-menu-toggle`: https://ionicframework.com/docs/api/menu-toggle

**Comment by paddelboot** [comment] 2021-03-12 17:02
Does this mean the whole `ion-menu` construct will not work within `ion-router-outlet`? How could I then build views where navigation can be placed dynamically, ie. view A has left sidebar navigation, view B has right sidebar navigation. It seems to me this wouldn't be possible with the code you are suggesting.

Our current approach was to build a base layout with slots which will be used in views, ie `Home.vue`:

        <template>
          <default-page>
            <div class="scss-test">
              <span class="nested">Home-Komponente mit SCSS-Styles</span>
            </div>
          </default-page>
        </template>

With `defaultPage.vue` being:

        <template>
          <ion-page>
            <ion-content :fullscreen="true" class="ion-padding" scroll-y="false">
              <ion-header>
                <ion-toolbar>
                  <ion-buttons slot="start">
                    <ion-menu-button
                      auto-hide="false"
                      menu="cc-sidebar"
                    ></ion-menu-button>
                  </ion-buttons>
                </ion-toolbar>
              </ion-header>
        
              <sidebar /> // has the ion-menu component
        
              <ion-content id="cc-content">
                <slot>Keine Inhalte</slot>
              </ion-content>
        
            </ion-content>
        
          </ion-page>
        </template>

And `App.vue` nothing more than:

        <template>
          <ion-app>
            <ion-router-outlet />
          </ion-app>
        </template>

But this seems to be impossible if Ionic framework requires me to have navigational items "outside" of `ion-router-outlet`. Or am I misunderstanding something?

**Comment by liamdebeasi** [comment] 2021-03-12 17:12
You can certainly do that, but you need to specify to your `ion-menu-button` which menu to open, otherwise it will just query for the first `ion-menu` available. I see you are doing that in your app, but the problem is that you are re-using IDs. In your `Projects` component, you should not be reusing the ID `testmenu` as that is the same ID for the menu in your `Home` component.

**Comment by paddelboot** [comment] 2021-03-15 11:10
Okay, I understand, thanks. From your point of view, are there performance considerations to be made when swapping the entire view (header, sidebar, main content, footer) on page transitions, instead of just the main content? Could this lead to a more "browsery" feeling when using the app?
