### ISSUE TITLE
bug: item being clicked after reorder

### ISSUE THREAD

**Issue by loopezz** [ionic-team/ionic-framework#28868] opened 2024-01-23 13:29 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

After dragging (on mouseup) an item within `ion-reorder-group` the item gets clicked. This only occurs on non-touch devices and having the mouse pointer outside the `ion-reorder` element. With touch simulation enabled this behavior does not occur.

Touch simulation enabled:
![Screen Recording 2024-01-23 at 14 06 06](https://github.com/ionic-team/ionic-framework/assets/11312418/bde6a5b1-e1ce-4a1c-9b47-3b6dc106af5d)

Touch simulation disabled (e.g. web browser on PC):
![Screen Recording 2024-01-23 at 14 06 49](https://github.com/ionic-team/ionic-framework/assets/11312418/3c27055d-10f5-4929-a04a-6e24e8b95bd6)

### Expected Behavior

The item must not be clicked.

### Steps to Reproduce

1. Checkout "Code Reproduction URL"
2. Reorder an item in a web browser
3. Move the mouse pointer to the left while dragging

### Code Reproduction URL

https://github.com/loopezz/ion-reorder.git

### Ionic Info

```
Ionic:

   Ionic CLI                     : 7.1.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.6.5
   @angular-devkit/build-angular : 17.1.0
   @angular-devkit/schematics    : 17.1.0
   @angular/cli                  : 17.1.0
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.6.0
   @capacitor/android : not installed
   @capacitor/core    : 5.6.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 2.0.0

System:

   NodeJS : v18.19.0 (/usr/local/bin/node)
   npm    : 10.2.3
   OS     : macOS Unknown
```

**Comment by liamdebeasi** [comment] 2024-01-23 14:51
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The browser handles when click events are dispatched, not Ionic. The reported behavior aligns with what happens outside of Ionic too (and it is also consistent across Chrome, Firefox, and Safari): https://codepen.io/liamdebeasi/pen/dyrzdQe

In this demo, click and drag from "Start here" over to "Drag over here and release". Once you release your mouse, the checkbox should be checked.

Mobile devices have different criteria for when click events are dispatched to account for accidental touches which may contribute to this behavior not happening on a physical mobile device.

-------

While this is the correct browser behavior, you may be able to work around this by disabling the checkbox on pointer down and then re-enabling it on pointer up:

```html
<ion-reorder-group (pointerdown)="disabled = true" (pointerup)="disabled = false" [disabled]="false" (ionItemReorder)="handleReorder($any($event))">
    <ion-item *ngFor="let item of items">
        <ion-checkbox [disabled]="disabled" label-placement="end" justify="start" [checked]="item.checked" [value]="item.id" (ionChange)="handleChecked($any($event))">
            <div class="ion-text-wrap">{{ item.name }}</div>
        </ion-checkbox>
        <ion-reorder slot="end"> </ion-reorder>
    </ion-item>
</ion-reorder-group>
```

**Closed by liamdebeasi** 2024-01-23 14:51 UTC
Labels: triage
