### ISSUE TITLE
bug: The ion-datetime component does not respect the min property of the user's timezone.

### ISSUE THREAD

**Issue by JulienLecoq** [ionic-team/ionic-framework#27670] opened 2023-06-19 09:39 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

The ion-datetime component does not respect the min property of the user's timezone.

<img width="366" alt="Capture d’écran 2023-06-19 à 11 32 14" src="https://github.com/ionic-team/ionic-framework/assets/54070985/7dae7fd2-9295-4886-ae16-742ab3fb8467">

On an Ionic application (with Angular), I have set the min property to: [min]="minDate.toISOString()" where minDate is new Date().

The current time here is 11:31 but the ion-datetime component shows by default and allows to select the min date time of 9:31 whereas this should not be possible.

### Expected Behavior

Respect the timezone of the user. For example, in my case, I should only be able to select time equals or above 11:31 and not 9:31.

### Steps to Reproduce

Create a ion-datetime, assign it the min property with new Date().toISOString() and a "date-time" presentation.

### Ionic Info

Ionic:

   Ionic CLI                     : 7.1.1 (/Users/julien_lecoq/.nvm/versions/node/v16.14.2/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.0.7
   @angular-devkit/build-angular : 16.0.2
   @angular-devkit/schematics    : 16.0.2
   @angular/cli                  : 16.0.2
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.0.1
   @capacitor/android : 5.0.5
   @capacitor/core    : 5.0.5
   @capacitor/ios     : 5.0.5

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v16.14.2 (/Users/julien_lecoq/.nvm/versions/node/v16.14.2/bin/node)
   npm    : 8.5.0
   OS     : macOS Unknown

**Comment by liamdebeasi** [comment] 2023-06-20 13:48
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework.

As per the [datetime documentation](https://ionicframework.com/docs/api/datetime#time-zones) datetime does not manipulate values according to the user's timezone. In other words, the value you give it is the value that is used. We have code on the linked documentation that shows how to account for timezones in an application.

**Closed by liamdebeasi** 2023-06-20 13:48 UTC
Labels: triage
