### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by bilalsaeed** [ionic-team/ionic-framework#26994] opened 2023-03-22 12:31 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v6.x

### Current Behavior

We just migrated our app from ionic v3 to ionic v6 after spending two months. Now we run android build on the device we get the following exception in device inspect.

**TypeError: Cannot read property 'hasOwnProperty' of undefined**

Is there any clue why this error might be occurring.?

Thank you.

### Expected Behavior

App should run on the device instead of showing a blank white page.

### Steps to Reproduce

1. ionic start
2. ionic cordova platform add android@latest
3. ionic cordova build android --prod

### Ionic Info

Ionic:

   Ionic CLI                     : 6.20.9 (C:\Users\bilal\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.5.5
   @angular-devkit/build-angular : 15.1.6
   @angular-devkit/schematics    : 15.1.6
   @angular/cli                  : 15.1.6
   @ionic/angular-toolkit        : 6.1.0

Cordova:

   Cordova CLI       : 11.1.0
   Cordova Platforms : android 11.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 21 other plugins)

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   Android SDK Tools : 26.1.1 (C:\Users\bilal\AppData\Local\Android\Sdk)
   NodeJS            : v18.15.0 (C:\Program Files\nodejs\node.exe)
   npm               : 9.5.0
   OS                : Windows 10

**Comment by sean-perkins** [comment] 2023-03-22 17:05
@bilalsaeed thank you for bringing this issue to our attention. However, in order for us to effectively investigate and resolve the problem, we will need more information from you.

Can you reproduce this issue in an Ionic starter and provide the Github repository here?

**Comment by bilalsaeed** [comment] 2023-03-22 17:13
Hi @sean-perkins thank you for reply.

Unfortunately, it's not occurring on starter template. I am trying to find the root cause of this issue but no success so far.

I added break points in main.js to debug the issue but I have not found anything. Attached is where it's breaking.

Is it possible if I can change my build settings so I can see the actual source code instead of this gibberish code?

![MicrosoftTeams-image (11)](https://user-images.githubusercontent.com/9278160/226984392-a97e0dfd-ad19-4e35-904b-a3595699b264.png)

**Comment by sean-perkins** [comment] 2023-03-23 03:28
@bilalsaeed what Android device are you testing with? Are you able to get the version of Chrome that it is running as well?

The output you are seeing is likely the result of a build output, which will bundle and inline the JS. You can try clicking the `main.js:1:94165` to see what relative code is around it. Chrome dev tools has a format option that may prettify the output as well: https://stackoverflow.com/a/6318092

If the issue does not reproduce in your web browser, there are a few different things that could be happening:
- The Android device could be using an older Javascript runtime that does not have the same features as your browser.
- The issue may only be present in code that is executed on device (e.g. from Cordova or a plugin), you could try disabling plugins to see if the problem persists.

**Comment by bilalsaeed** [comment] 2023-03-23 20:10
The problem resolved. 

I was running this `ionic cordova build android --prod`, I didn't know that --prod has been depracted. now build is working. 

Now there's another problem Splash screen is not hiding. I am using cordova cli 11. Should I downgrade to cordova cli 10?

**Comment by bilalsaeed** [comment] 2023-03-23 20:53
For now I have set auto hide to true but that's not the best solution.

**Comment by sean-perkins** [comment] 2023-03-23 21:37
@bilalsaeed since this isn't a problem with Ionic Framework, I'm going to close this issue. You can post your question in the Discord or the Ionic forums to receive support related assistance around Ionic or related technologies (i.e. Cordova). 

Thanks!

**Closed by sean-perkins** 2023-03-23 21:37 UTC
Labels: triage, ionitron: needs reproduction
