### ISSUE TITLE
bug: The screen becomes empty when scrolling too fast

### ISSUE THREAD

**Issue by jsgoupil** [ionic-team/ionic-framework#28967] opened 2024-02-02 19:57 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Scrolling anything in ionic will start displaying behavior that the screen starts to remove elements.
We literally tried everything by removing all the functionality of our app (menus, etc.) and we are unable to make this app stable. We wonder if there would be a way to turn off this thing where ionic is trying to remove objects from the screen since our app does not display infinite amounts of elements.

Our app plans to work only in PWA mode, we do not compile for iOS.
This reproduces all the time on Safari, Chrome, Safari Installed. Currently I have an iPad Air 2, 15.6.
But I get these bug reports on ionic 6 constantly, and now that we tried to update to ionic 7 it happens even more.

https://github.com/ionic-team/ionic-framework/assets/808649/6cd4370e-2507-4daa-9540-8b144dbbde7a

### Expected Behavior

Scrolling without elements disappearing.

### Steps to Reproduce

Visit: https://mobile-pre-prod.3cconnect.com/
Login: contact+tech1@jsgoupil.com
Password: password1

Click on the first "Continue" element on the screen then try to scroll.

### Ionic Info

```
[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package.json'

       Require stack:
       - C:\Users\jsgou\AppData\Roaming\npm\node_modules\@ionic\cli\lib\project\index.js
       - C:\Users\jsgou\AppData\Roaming\npm\node_modules\@ionic\cli\lib\index.js
       - C:\Users\jsgou\AppData\Roaming\npm\node_modules\@ionic\cli\index.js
       - C:\Users\jsgou\AppData\Roaming\npm\node_modules\@ionic\cli\bin\ionic
[WARN] Error loading @capacitor/android package.json: Error: Cannot find module '@capacitor/android/package.json'

       Require stack:
       - C:\Users\jsgou\AppData\Roaming\npm\node_modules\@ionic\cli\lib\project\index.js
       - C:\Users\jsgou\AppData\Roaming\npm\node_modules\@ionic\cli\lib\index.js
       - C:\Users\jsgou\AppData\Roaming\npm\node_modules\@ionic\cli\index.js
       - C:\Users\jsgou\AppData\Roaming\npm\node_modules\@ionic\cli\bin\ionic

Ionic:

   Ionic CLI       : 7.2.0 (C:\Users\jsgou\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/react 7.7.0

Capacitor:

   Capacitor CLI      : 5.6.0
   @capacitor/android : not installed
   @capacitor/core    : 5.6.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 2.0.1

System:

   NodeJS : v18.14.0 (C:\Program Files\nodejs\node.exe)
   npm    : 8.5.5
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment] 2024-02-02 20:24
Does this issue happen on newer versions of iOS or other devices? WebKit handles the rendering of the web content, not Ionic. Given the age of the device and the operating system, it's likely that this is related to device performance.

**Comment by jsgoupil** [comment] 2024-02-02 20:25
Yes, this started to manifest with the latest update of iOS. Definitely happening a lot of v17, but my iPad can also do it with the latest 15.6

**Comment by liamdebeasi** [comment] 2024-02-02 20:26
Can you provide a minimal reproduction of the issue that we can run on our test devices?

**Comment by jsgoupil** [comment] 2024-02-02 20:27
I will do my best today. yes.

**Comment by jsgoupil** [comment] 2024-02-04 17:05
I have reduced the code to a very minimal for you to repro, but the code is kind of private. Even though it's quite barebone now.
I have given you access to have a look. If you really need this to be public, I can consider opening it up.
https://github.com/3cconnect/3c-copy

```
npm install
yarn build
yarn serve
```
Then visit
`http://localhost:3501/appointments/3/info`

I can repro on iPad. Safari installed or not installed, and Chrome as well.

Simply scroll fast (flick) to the bottom of the page then everything disappears.

Let me know if you need anything else.

**Comment by jsgoupil** [comment] 2024-02-05 18:52
We tried to remove all `IonContent` and the app started to behave better. But obviously broke our UI.

https://github.com/ionic-team/ionic-framework/assets/808649/9159809c-b7c6-4087-98ab-29d953e2abf3

**Comment by amandaejohnston** [comment] 2024-02-05 18:58
Could you provide a more minimal repo that avoids using private code, then share it publicly? The best way would be to start with a blank Ionic app (see the [contributing guide](https://ionicframework.com/docs/contributing/how-to-contribute#creating-a-good-code-reproduction) for more info) and add to it until the issue reproduces. The current repro has a lot of extra functionality that makes it difficult to isolate the issue, and it would be ideal if the app could be shared publicly so the rest of the team can take a look.

**Comment by jsgoupil** [comment] 2024-02-07 17:25
We figured out the culprit. A font-face that was from Google long time ago was causing problem.
The `unicode-range` was not working properly.
By removing this code, it started to work:

```
// SourceSansPro - latin-ext
@font-face {
  font-family: 'Source Sans Pro';
  font-style: normal;
  font-weight: 400;
  src: url('/assets/fonts/SourceSansPro-Regular-ext.woff2') format('woff2');
  unicode-range: U+0100-02AF, U+0304, U+0308, U+0329, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F,
    U+A720-A7FF;
}

// Poppins - latin-ext
@font-face {
  font-family: 'Poppins';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: url('/assets/fonts/Poppins-Regular-ext.woff2') format('woff2');
  unicode-range: U+0100-02AF, U+0304, U+0308, U+0329, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F,
    U+A720-A7FF;
}
```

Since we figured out the issue, I will let you decide if you want to investigate further or close this bug. Thanks.

**Comment by amandaejohnston** [comment] 2024-02-07 17:30
Glad you were able to figure it out! Since it doesn't sound like this is a bug in Ionic, I'll go ahead and close it, but let us know if the problem pops up again in Ionic Framework code.

**Closed by amandaejohnston** 2024-02-07 17:30 UTC
Labels: triage
