### ISSUE TITLE
bug: ion-select 

### ISSUE THREAD

**Issue by chloekcz** [ionic-team/ionic-framework#19591] opened 2019-10-08 20:41 UTC
**Ionic version: **
[x] 4.x

**Current behavior**
When I select a value on my ion-select and I click on an other field, sometimes this value to modify without change of my part.
I've test on Ionic's documentation and I reproduct this error.

**Expected behavior**
My value must be the same.

**Comment by brandyscarney** [comment] 2019-10-08 21:54
Can you please provide a way to reproduce this? I can't reproduce it in the docs. A codepen sample would be helpful too: https://codepen.io/pen?template=aXENNW

Thank you!

**Comment by chloekcz** [comment] 2019-10-10 13:38
https://codepen.io/chloeweb/pen/pooJKaN

The issue is easily reproductible.
1) Select a value (for instance "NES" in the first ion-select.
2) Move the cursor and click again **quickly** after, while the cursor is still a "little hand".  

3) You will see the ion select value change.
 
If you look at the cursor, you will see, just after selecting a value, it stay as a "little hand" instead of becoming an arrow. So you can still change the value of the ion select after it had just closed.
 
I stay available to discuss this issue. It is especially visible on this example because the cursor for the other component (the ion-input) is not a little hand.
So you can see that the cursor doesn't change back to an arrow after you click on an option of the ion select.

**Comment by chloekcz** [comment] 2019-10-21 09:28
![ion-select](https://user-images.githubusercontent.com/43878714/67193650-ee2d6400-f3f5-11e9-8baa-0e75beb0c123.gif)

**Comment by liamdebeasi** [comment] 2022-04-14 13:28
Thanks for the issue. This has been resolved in the latest version of Ionic.

**Closed by liamdebeasi** 2022-04-14 13:28 UTC
Labels: package: core, type: bug
