### ISSUE TITLE
bug: navigation not working correctly in vue

### ISSUE THREAD

**Issue by khaledosman** [ionic-team/ionic-framework#23107] opened 2021-03-26 15:11 UTC
# Bug Report
navigation not working

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
path changes correctly, but the corresponding component doesn't get rendered/switch, an error is thrown when trying to navigate back

**Expected behavior:**
should navigate correctly

**Steps to reproduce:**
Sample application: https://codesandbox.io/s/ionic-5-vue-3-rn1xi
1. Click on "About" <-- location url is changed correctly, but component isn't updated
2. Click on "Home" <-- throws `Cannot read property 'classList' of undefined`

if I replace `ion-router-outlet` with `router-view` it works again

**Comment by bddexter** [comment] 2021-03-27 13:41
There seems to be something fundamentally buggy with `vue-router` support. See also my issue #23087

**Comment by liamdebeasi** [comment] 2021-03-29 13:15
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The problem here is you are not wrapping your pages in an `<ion-page>` element, which is required for all views. Please see https://ionicframework.com/docs/vue/navigation#ionpage for more information.

**Closed by liamdebeasi** 2021-03-29 13:15 UTC
Labels: triage
