### ISSUE TITLE
bug: (picker) pass single value to picker

### ISSUE THREAD

**Issue by indraraj26** [ionic-team/ionic-framework#19881] opened 2019-11-10 13:52 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

By default it is selecting without adding color primary. 
![image](https://user-images.githubusercontent.com/23274631/68545056-5963c800-03ef-11ea-9644-0b8a18065a89.png)

**Expected behavior:**

It should add primary color.

**Steps to reproduce:**

**1. Open picker again and again.**
**Related code:**

Html: 
https://github.com/indraraj26/ionic4-starter-tabs-sidemenu/blob/picker/src/app/home/home.page.html
TS:
https://github.com/indraraj26/ionic4-starter-tabs-sidemenu/blob/picker/src/app/home/home.page.ts

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
D:\ionicv4-github\ionic4-tabs-sidemenu>ionic info

Ionic:

   Ionic CLI                     : 5.4.4 (C:\Users\indra26\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.11.4
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : android 7.1.4
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 6 other plugins)

Utility:

   cordova-res : 0.8.0
   native-run  : 0.2.9

System:

   NodeJS : v10.16.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.9.0
   OS     : Windows 10


D:\ionicv4-github\ionic4-tabs-sidemenu>
```

**Comment by amandaesmith3** [comment] 2022-02-07 20:16
Thanks for the issue, I wanted to circle back to this. I'm unable to replicate the issue in the latest version of Ionic, both in Angular and core, so it looks like this has already been resolved. As a result, I'm going to close this out. If this is still something you're running into in Ionic 6, please create a new issue with an updated reproduction. Thanks!

**Closed by amandaesmith3** 2022-02-07 20:16 UTC
Labels: triage
