### ISSUE TITLE
bug: `ion-datetime` time value display won't update before confirmed when custom or default buttons are shown

### ISSUE THREAD

**Issue by darkxinyu** [ionic-team/ionic-framework#24528] opened 2022-01-07 03:48 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

configuring a `ion-datetime` with presentation 'date-time' and default buttons, when user make changes from time-picker, the time value displayed doesn't update to the new value, but after user press the confirm button then the new value can be retirived from ngModel, making the user a little bit confused, for that he can't see what time he picked until he confirmed.

### Expected Behavior

when using custom or default buttons, the time value display should update as soon as the user changes it so the user can see in real time what time he picked, and only making the real change until the user confirm it.

### Steps to Reproduce

1. configuring a `ion-datetime` with presentation 'date-time' and default buttons;
2. change the time from the time-picker;
3. display not updated.

the example of 'custom buttons' in the official `ion-datetime` documentation page also has this issue

### Code Reproduction URL

https://ionicframework.com/docs/api/datetime

### Ionic Info

Ionic:

   Ionic CLI                     : 6.18.1 (/Users/xxx/.config/yarn/global/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.1
   @angular-devkit/build-angular : 12.2.14
   @angular-devkit/schematics    : 12.2.14
   @angular/cli                  : 12.2.14
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : android 8.1.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 2.5.3, (and 11 other plugins)

Utility:

   cordova-res (update available: 0.15.4) : 0.14.1
   native-run (update available: 1.5.0)   : 0.3.0

System:

   Android SDK Tools : 26.1.1 (/Users/xxx/Library/Android/sdk)
   ios-sim           : 8.0.2
   NodeJS            : v17.3.0 (/usr/local/Cellar/node/17.3.0/bin/node)
   npm               : 8.3.0
   OS                : macOS Big Sur
   Xcode             : Xcode 13.2.1 Build version 13C100

**Comment by sean-perkins** [comment] 2022-01-07 04:18
Thanks for reporting this issue.

I believe this is a duplicate of #24451. The PR to address this has been merged here (#24454) and will be available in the next patch release.

**Closed by sean-perkins** 2022-01-07 04:18 UTC
Labels: holiday triage
