### ISSUE TITLE
bug: Cannot select a date in not-current month in ion-datetime on Android

### ISSUE THREAD

**Issue by Hugocaminada** [ionic-team/ionic-framework#24305] opened 2021-12-02 13:50 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

In v6, when i click on one of the arrows in the top-right of the date-time component -or select a different month via the top-left option- I cannot select a date without it jumping to the previous month. If you then click a date, it goes back to the previous month again.

Tested in dev & production on real device and emulator with newest release candidate of the v6 beta. 

https://user-images.githubusercontent.com/32323786/144433234-c7842142-0383-4478-84f3-d6383d4d3c41.mov

### Expected Behavior

Click on a date, that date gets selected

### Steps to Reproduce

1. Add a `<ion-datetime>` component to any screen.
2. Use capacitor to run the project on an Android phone or emulator.
3. Try to select a date in a different month than the current one

### Code Reproduction URL

https://github.com/Hugocaminada/datetime-test

### Ionic Info

       
       Require stack:
       - /usr/local/lib/node_modules/@ionic/cli/lib/project/index.js
       - /usr/local/lib/node_modules/@ionic/cli/lib/index.js
       - /usr/local/lib/node_modules/@ionic/cli/index.js
       - /usr/local/lib/node_modules/@ionic/cli/bin/ionic

Ionic:

   Ionic CLI                     : 6.18.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.0-rc.3
   @angular-devkit/build-angular : 12.1.4
   @angular-devkit/schematics    : 12.2.13
   @angular/cli                  : 12.1.4
   @ionic/angular-toolkit        : 4.0.0

Capacitor:

   Capacitor CLI      : 3.3.2
   @capacitor/android : 3.3.2
   @capacitor/core    : 3.3.2
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.3
   native-run  : 1.5.0

System:

   NodeJS : v14.17.3 (/usr/local/bin/node)
   npm    : 7.24.0
   OS     : macOS Monterey

**Comment by liamdebeasi** [comment] 2021-12-02 17:17
Thanks for the issue. What version of the webview are you running when deploying your app with Capacitor? You can find this by logging `window.navigator.userAgent` when inspecting your app in Chrome.

I am testing this on Chrome 95 and cannot reproduce this on my end.

**Comment by Hugocaminada** [comment] 2021-12-03 07:38
> Thanks for the issue. What version of the webview are you running when deploying your app with Capacitor? You can find this by logging `window.navigator.userAgent` when inspecting your app in Chrome.
> 
> I am testing this on Chrome 95 and cannot reproduce this on my end.

`window.navigator.userAgent` logs:

    Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 
    Safari/537.36

**Comment by Hugocaminada** [comment] 2021-12-03 08:14
> Thanks for the issue. What version of the webview are you running when deploying your app with Capacitor? You can find this by logging `window.navigator.userAgent` when inspecting your app in Chrome.
> 
> I am testing this on Chrome 95 and cannot reproduce this on my end.

    Mozilla/5.0 (Linux; Android 11; sdk_gphone_arm64 Build/RSR1.210722.003; wv) AppleWebKit/537.36 (KHTML, like Gecko) 
    Version/4.0 Chrome/91.0.4472.114 Mobile Safari/537.36

**Comment by Hugocaminada** [comment] 2021-12-07 13:17
It seems to be affected by witch device I'm emulating. I don't have the problem with the Pixel XL emulator, but it does happen on the Pixel 2 emulator. Same build, same Android version, same Chrome version.

**Comment by liamdebeasi** [comment] 2021-12-10 14:29
Apologies for the delay. I can reproduce this issue and will take a closer look. Thanks!

**Comment by liamdebeasi** [comment] 2021-12-10 15:14
I can reproduce this in Chrome 96 on my Pixel 4a. I cannot reproduce this in Firefox for macOS, Chrome for macOS, Safari for macOS and iOS -- this appears to be a bug specific to Chrome for Android.

I will look into reporting this to the Chromium team. I will post here when I have more updated. Thanks again!

**Comment by liamdebeasi** [comment] 2021-12-10 20:36
This issue has been fixed in Chrome 97. It is slated to release Jan 4, 2022. I will keep this issue open until Chrome 97 ships. Thanks again!

**Comment by liamdebeasi** [comment] 2022-01-04 18:51
Chrome 97 is releasing today which has a fix for this issue, so I am going to close this thread. Thanks for the report!

**Closed by liamdebeasi** 2022-01-04 18:51 UTC
Labels: type: bug, bug: external
