### ISSUE TITLE
bug: ios ion-segment button text is not readable in some instances.

### ISSUE THREAD

**Issue by FiniteSingularity** [ionic-team/ionic-framework#26350] opened 2022-11-22 22:10 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

If an `ion-segment` is contained in an `ion-toolbar` whose color is set to `light`, and the mode is `ios`, the segment-button text is unreadable in light mode. Additionally, if the `ion-toolbar` color is set to `dark`, the segment-button text is unreadable in dark mode.  Issue present in Chrome, Brave, and FireFox. (See attached screen shots)

![image](https://user-images.githubusercontent.com/72580859/203430912-a039b8cd-1301-44d1-8586-0a156f90864d.png)

![image](https://user-images.githubusercontent.com/72580859/203431183-ee16cc7a-0961-41f5-8dcd-357e73a382af.png)

### Expected Behavior

The `ion-segment-button` text should be readable regardless of the color of its container `ion-toolbar` in both light mode and dark mode.

### Steps to Reproduce

Make an `ion-toolbar`, set the color to `light`, add to it an `ion-segment` with buttons, and set its mode to `ios`.  Now open the page in a browser set to light mode.  The `ion-segment-button` text will be unreadable as its color will be nearly identical to the segment button background.  Or rather than that, just use the reproduced code linked below, and toggle your browser between light mode and dark mode.

### Code Reproduction URL

https://github.com/FiniteSingularity/ionic-segment-color-issue

### Ionic Info

Ionic:

   Ionic CLI                     : 6.12.3 (/mnt/c/Users/mdobo/AppData/Roaming/npm/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.3.8
   @angular-devkit/build-angular : 15.0.0
   @angular-devkit/schematics    : 15.0.0
   @angular/cli                  : 15.0.0
   @ionic/angular-toolkit        : 6.1.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v16.18.1 (/home/mark/.nvm/versions/node/v16.18.1/bin/node)
   npm    : 8.19.2
   OS     : Linux 5.10

### Additional Information

It appears that the text color is taken directly from the background color.  However, unlike the case where no color is set on the container, the button background is always white (causing the readability issue).  Can the light/dark color container segment work more like the non-color segment where it gets a dark button background for contrast in some cases?

**Comment by liamdebeasi** [comment] 2022-11-23 15:11
Thanks for the report. I can reproduce this. As you noted, the problem is that we force the segment indicator background to white when using the segment in a toolbar with color: https://github.com/ionic-team/ionic-framework/blob/181c44e4bbdee60cb00f46c296b2136dfd193f0e/core/src/components/segment-button/segment-button.ios.scss#L206

This causes issues on dark mode as the text color on the checked button is then set to the base color. For the `dark` palette, this base color is a very light gray. 
![image](https://user-images.githubusercontent.com/2721089/203580840-7bfe1ad5-3863-4a73-b923-ba61f0aeb0dc.png)

Similarly, this causes issues in light mode with the `light` palette as the base color is also a light gray:

![image](https://user-images.githubusercontent.com/2721089/203580804-22284778-dad0-40de-ae69-e3bd4d137a10.png)

-----

The solution here should be to have the background change to the theme's contrast color instead. This means that the indicator colors for certain color palettes may change, but affected color combos do not pass even [WCAG AA accessibility guidelines](https://wcag.com/designers/1-4-3-color-contrast/).

**Comment by FiniteSingularity** [comment] 2022-11-23 15:41
Thank you for the quick response and PR.  I look forward to using the fix when it's merged in.  🧡

**Comment by liamdebeasi** [comment] 2022-11-23 16:53
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/26353, and a fix will be available in an upcoming release of Ionic Framework.

**Closed by liamdebeasi** 2022-11-23 16:53 UTC
Labels: package: core, type: bug
