### ISSUE TITLE
bug: Click event on ion-item fires twice when ion-input is inside

### ISSUE THREAD

**Issue by aces-tm** [ionic-team/ionic-framework#29166] opened 2024-03-15 13:30 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

If there is a click event on ion-item and there is ion-input inside ion-item then if a user clicks on the padding area above ion-input then click event fires twice. In my case this opens a modal twice. 
```
<ion-item (click)="clickMe()">
    <ion-input label="My label" label-placement="floating" readonly [value]="deafaultValue" type="text"></ion-input>
</ion-item>
```

This is the same issue as this one https://github.com/ionic-team/ionic-framework/issues/26671 that is closed as Ionic team was not able to reproduce it.

### Expected Behavior

Click event to fire once

### Steps to Reproduce

If you click in the middle of `ion-input` integer will increase by 1. Click on the area above or below `ion-input`. Observe that integer will increase by 2

### Code Reproduction URL

https://stackblitz.com/edit/angular-v1tuxo?file=src%2Fapp%2Fexample.component.html

### Ionic Info

Ionic:

   Ionic CLI                     : 7.2.0 (/Users/andjelicnikola/.nvm/versions/node/v20.9.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.7.2
   @angular-devkit/build-angular : 17.2.0
   @angular-devkit/schematics    : 17.2.0
   @angular/cli                  : 17.2.0
   @ionic/angular-toolkit        : 11.0.1

Capacitor:

   Capacitor CLI      : 5.7.0
   @capacitor/android : 5.7.0
   @capacitor/core    : 5.7.0
   @capacitor/ios     : 5.7.0

Utility:

   cordova-res : not installed globally
   native-run  : 2.0.1

System:

   NodeJS : v20.9.0 (/Users/andjelicnikola/.nvm/versions/node/v20.9.0/bin/node)
   npm    : 10.2.3
   OS     : macOS Unknown

**Comment by liamdebeasi** [comment] 2024-03-15 13:44
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/28803#issuecomment-1884945641.

**Closed by liamdebeasi** 2024-03-15 13:44 UTC
Labels: triage
