### ISSUE TITLE
bug: datetime month and year picker not initialized properly on ios 14

### ISSUE THREAD

**Issue by wangzhengjiang** [ionic-team/ionic-framework#23910] opened 2021-09-09 15:12 UTC
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

when using ion-datetime v6 on iphone, choice months, program will always return previous month of the selected month. 

### Expected Behavior

it should return the month of selected.

### Steps to Reproduce

1. created a new app using V6
2. add ion-datetime in the pages
3. deploy to iphone. 
4. run in xcode, when choice month, program will return previous month instead of the month of selected. 

### Ionic Info

Ionic:

   Ionic CLI                     : 6.17.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.0-beta.5
   @angular-devkit/build-angular : 12.1.4
   @angular-devkit/schematics    : 12.1.4
   @angular/cli                  : 12.1.4
   @ionic/angular-toolkit        : 4.0.0

Capacitor:

   Capacitor CLI      : 3.2.0
   @capacitor/android : 3.2.2
   @capacitor/core    : 3.2.0
   @capacitor/ios     : 3.2.2

Utility:

   cordova-res                          : not installed globally
   native-run (update available: 1.4.1) : 1.4.0

System:

   NodeJS : v14.17.5 (/usr/local/bin/node)
   npm    : 7.22.0
   OS     : macOS Big Sur

**Comment by liamdebeasi** [comment] 2021-09-09 15:33
Thanks for the issue. Can you reproduce this in an Ionic starter app and provide a link to the repo?

**Comment by wangzhengjiang** [comment] 2021-09-09 16:14
I created a app, can reproduce the error on iphone. 

https://github.com/wangzhengjiang/testdatetime

**Comment by liamdebeasi** [comment] 2021-09-13 20:58
Thanks for the reply. I do not see any error logged in the console, and the dates appear to be returning correctly for me. Can you please clarify the steps to reproduce the issue?

**Comment by wangzhengjiang** [comment] 2021-09-15 14:56
https://user-images.githubusercontent.com/21355003/133457442-3a46ba9b-9685-45c0-91cf-7a14f5980fe0.mov

**Comment by liamdebeasi** [comment] 2021-09-22 19:21
I can reproduce this issue on iOS 14, but not on iOS 15. Seems to be resolved in iOS 15 but we should still try to find a workaround for iOS 14 given that iOS 15 is still fairly new.

**Comment by liamdebeasi** [comment] 2021-11-02 20:37
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/24142, and a fix will be available in an upcoming release of Ionic Framework.

**Closed by liamdebeasi** 2021-11-02 20:37 UTC
Labels: package: core, type: bug, v6
