### ISSUE TITLE
bug: form validation should not show red highlight until user has modified the field

### ISSUE THREAD

**Issue by Marius-Romanus** [ionic-team/ionic-framework#21643] opened 2020-06-29 13:02 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

In reactive Angular forms, the ion-items within an ion-input, the highlights are marked in red when they have not yet been touched.

**Expected behavior:**

They should be blue until they are not touched, even though the validation of required giving an error.

**Steps to reproduce:**

Create a reactive form group and add the required validation

**Related code:**

```
import { ReactiveFormsModule } from '@angular/forms';
imports: [
    ReactiveFormsModule,
    ...
],
```

```
formGroup: FormGroup;

constructor(public formBuilder: FormBuilder) {
    this.formGroup = this.formBuilder.group({
      text: [
        "",
        [Validators.required]
      ]
    });
}
```

```
<form [formGroup]="formGroup">
	<ion-item>
		<ion-label floating>Text</ion-label>
		<ion-input type="text" formControlName="text"></ion-input>
	</ion-item>
</form>
```

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.10.1
   Ionic Framework               : @ionic/angular 5.2.2
   @angular-devkit/build-angular : 0.1000.0
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 10.0.0
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 2.2.0
   @capacitor/core : 2.2.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v14.3.0
   npm    : 6.14.5
   OS     : Windows 10
```

**Comment by Marius-Romanus** [comment] 2020-06-30 21:34
Code reproduction in tab 1 of StackBlitz.

https://stackblitz.com/edit/ionic-v4-angular-tabs-qni8lg?file=src%2Fapp%2Ftab1%2Ftab1.page.ts

Regards

**Comment by liamdebeasi** [comment] 2020-07-13 18:25
Thanks for the follow up. Can you please provide some steps to reproduce the issue? The form appears to be functioning correctly when I check the StackBlitz.

**Comment by Marius-Romanus** [comment] 2020-07-14 13:29
The strict mode behavior is correct, but it is not correct for a user as far as UX is concerned, since the user has not yet written anything to have it automatically red-marked.
To be correct in my opinion, it should not be marked in red until it is touched or dirty.
Sorry if my English is not entirely correct. Regards

**Comment by liamdebeasi** [comment] 2020-07-14 13:36
Thanks! The input is not marked with the red underline until I touch the input. Here is what it looks like when I load the page:
![image](https://user-images.githubusercontent.com/2721089/87431816-2b093e80-c5b5-11ea-9d09-ae845ec33020.png)

I agree with the behavior you are expecting to see, but that is also the behavior I am experiencing in your code reproduction. Can you please double check your code?

**Comment by Marius-Romanus** [comment] 2020-07-14 13:46
Hello again :)
I'm going to try to explain another way.
When the user clicks on the entry, the bottom line is directly red.
This is because Angular interprets it as required, however the user has not yet started writing anything to input.
It would be more correct that although angular of a required error, it would not turn red, and blue until the input is touched.

**Comment by liamdebeasi** [comment] 2020-07-14 14:03
Thanks! That makes sense. I agree that this UX can be improved.

**Comment by madmacc** [comment] 2021-05-06 00:25
Is there any way we can turn of this red highlight until this has been improved?

**Comment by JZubero** [comment] 2021-10-06 05:59
@liamdebeasi Has this found it's way to the roadmap yet? Thanks

**Comment by myflowpl** [comment] 2022-04-11 08:35
Any news on this? 
It's really UX unfriendly

**Comment by ntorrey** [comment] 2022-11-27 20:27
Is there a workaround to use while we wait for this to be updated?

**Comment by MaxWieand** [comment] 2023-01-07 00:13
Is there at least any css trick that we can use until this UX behaviour is fixed?

**Comment by imsergiobernal** [comment] 2023-01-07 12:39
HAving the same problem in 13.2.7

**Comment by kurofeng** [comment] 2023-03-04 23:13
Try:
` <ion-note slot="error" *ngIf="this.group.controls['street_address'].touched"> ! Test </ion-note>`

**Comment by liamdebeasi** [comment] 2023-03-10 17:30
Hi everyone,

I recently merged a fix in https://github.com/ionic-team/ionic-framework/pull/26940 that resolves this issue when using the new form control syntax in Ionic 7. We have a migration guide available for using the new form control syntax (`ion-input` example: https://ionicframework.com/docs/v7/api/input#migrating-from-legacy-input-syntax).

Ionic 7 is currently in pre-release and will be stable soon. The work to resolve this issue has been completed, so I am going to close this issue. Let me know if there are any questions.

**Closed by liamdebeasi** 2023-03-10 17:30 UTC
Labels: package: core, type: bug
