### ISSUE TITLE
bug: non-native refresher breaks scrolling

### ISSUE THREAD

**Issue by mrahn24** [ionic-team/ionic-framework#27601] opened 2023-06-06 10:11 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When using a non-native refresher, moving the view (refresher) slightly down, back to the top of the view (deltaY <= 0) and down again in one move (one tap and hold) breaks the scrolling of the view. See attached video for a better understanding.

https://github.com/ionic-team/ionic-framework/assets/86344176/eae73145-8d3a-4b58-9621-9760874466ee

### Expected Behavior

View scrolling does not break when using the refresher.

### Steps to Reproduce

1. Checkout the sample application: [https://github.com/mrahn24/ionic-bug-examples -> Branch: bug/r](https://github.com/mrahn24/ionic-bug-examples/tree/bug/refresher-breaks-scrolling) and run it
2. Tap and hold to use the refresher
3. Move down (do not move over pullMax)
4. Move up to the top of the view (deltaY <= 0)
5. Move down (do not move over pullMax)
6. Release tap and hold
7. Try to scroll down -> Scroll should be broken

### Code Reproduction URL

https://github.com/mrahn24/ionic-bug-examples/tree/bug/refresher-breaks-scrolling

### Ionic Info

Ionic:

   Ionic CLI                     : 6.20.1 (/Users/mrahn/.config/yarn/global/node_modules/@ionic/cli)
   Ionic Framework               : not installed
   @angular-devkit/build-angular : 16.0.4
   @angular-devkit/schematics    : 15.2.8
   @angular/cli                  : 16.0.4
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.0.4
   @capacitor/android : not installed
   @capacitor/core    : 5.0.4
   @capacitor/ios     : not installed

Utility:

   cordova-res (update available: 0.15.4) : 0.15.1
   native-run                             : 1.7.2

System:

   NodeJS : v18.15.0 (/Users/mrahn/.n/bin/node)
   npm    : 9.5.0
   OS     : macOS

### Additional Information

Bug introduced with #26613

**Comment by liamdebeasi** [comment] 2023-06-06 14:33
Thanks for the report! I am able to reproduce this issue. I will take a look at your PR shortly.

**Comment by mrahn24** [comment] 2023-06-07 05:25
The dev build works like a charm. Thank you very much @liamdebeasi ! 🙏

**Comment by liamdebeasi** [comment] 2023-06-07 20:56
Thanks again for the report and the PR! This fix will be in the next release of Ionic v7. We also plan to backport this to Ionic v6 since it was introduced in that major release.

**Closed** 2023-06-07 20:56 UTC
Labels: package: core, type: bug

**Comment by liamdebeasi** [comment] 2023-06-08 17:37
This fix was released today as part of the v6.7.5 and v7.0.12 releases.
