### ISSUE TITLE
bug: hidden attribute is not respected

### ISSUE THREAD

**Issue by QuentinFarizon** [ionic-team/ionic-framework#28138] opened 2023-09-07 09:59 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v6.x, v7.x

### Current Behavior

I have a ion-select like this :

```
<ion-select hidden="true" data-cy="multielement-options" [ngModel]="selectedMultiHomePageElementEntry" interface="action-sheet"
            (ionChange)="onSelect($event)" [cancelText]="'HOME.CANCEL' | translate" #multiHomePageElementSelect>
  <ion-select-option data-cy="element-selector" class="ion-text-center" *ngFor="let element of homePageElementsList" value="{{element.homePageElementId}}">
    {{ element.homePageElementLabel}}
  </ion-select-option>
</ion-select>
```
After migrating to Angular 16, the hidden attribute does not seem to work anymore, the element is visible in the view.

### Expected Behavior

ion-select should be hidden 

### Steps to Reproduce

- 

### Ionic Info

```
$ ionic info

Ionic:

   Ionic CLI                     : 7.1.1 (/home/quentin/.nvm/versions/node/v16.15.1/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.3.3
   @angular-devkit/build-angular : 16.2.1
   @angular-devkit/schematics    : 16.2.1
   @angular/cli                  : 16.2.1
   @ionic/angular-toolkit        : 10.0.0

Cordova:

   Cordova CLI       : 11.0.0 (cordova-lib@11.1.0)
   Cordova Platforms : android 12.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 29 other plugins)

Utility:

   cordova-res                          : 0.15.4
   native-run (update available: 1.7.2) : 1.7.1

System:

   Android SDK Tools : 26.1.1 (/home/quentin/Android/Sdk)
   NodeJS            : v16.15.1 (/home/quentin/.nvm/versions/node/v16.15.1/bin/node)
   npm               : 8.13.1
   OS                : Linux 5.15

```

**Comment by amandaejohnston** [comment] 2023-09-07 14:23
Thank you for the issue, I'm able to reproduce this. It doesn't look to be Angular-specific. We place `display: block` on the `:host`, which is overwriting the browser's styling:

![dev tools screenshot](https://github.com/ionic-team/ionic-framework/assets/90629384/889582a1-ba62-4ab3-823b-3c90d966c721)

This is also happening with other components. We may need to adjust our stylesheets to account for the `hidden` attribute manually. In the meantime, one workaround is to apply the `ion-hide` class to the select instead, which will hide it successfully.

**Comment by amandaejohnston** [comment] 2023-09-07 14:26
Actually, hold that thought -- on further investigation, it looks like this was an intentional change as of Ionic 7, and is documented in the breaking changes here: https://github.com/ionic-team/ionic-framework/blob/main/BREAKING.md#css-utilities

As such, I'm going to close this out as not a bug in Ionic. Apologies for any confusion.

**Closed by amandaejohnston** 2023-09-07 14:26 UTC
Labels: package: core, type: bug

**Comment by QuentinFarizon** [comment] 2023-09-08 09:56
Hello @amandaejohnston I'm not sure to understand, both what you said and the breaking change documentation.

If it fallbacks to native hidden property, why isn't it hidden ?   
Also, the breaking change doesn't say by what it is replaced. How to hide elements ?

**Comment by amandaejohnston** [comment] 2023-09-08 14:55
The native property is being overwritten by Ionic's styling. If you would like to use the `hidden` attribute to hide elements, add this to your global CSS:
```css
[hidden] {
  display: none !important;
}
```

**Comment by QuentinFarizon** [comment] 2023-09-08 15:09
And Ionic doesn't provide a way to hide elements ?

**Comment by amandaejohnston** [comment] 2023-09-08 15:14
You can use the `ion-hide` class if you'd like: https://ionicframework.com/docs/layout/css-utilities#element-display
