### ISSUE TITLE
bug: router transition animation not applied when using browser back button

### ISSUE THREAD

**Issue by hoi4** [ionic-team/ionic-framework#28176] opened 2023-09-14 17:35 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When using the browser back button, the page transition animation is not played. 

Regarding the attached video: I just added an "about" page to the tabs starter project. The hard cut between the "about" page and the tab1 is me pressing the browser back button.

https://github.com/ionic-team/ionic-framework/assets/23243256/03162faf-e845-47e8-a907-0df9a761e364

### Expected Behavior

I would expect animations to work when using the browser back button

### Steps to Reproduce

1. Open tab1 and click the button to route to the "about" page
2. Click the browser back button

### Code Reproduction URL

https://github.com/hoi4/ionic-animation-test

### Ionic Info

```
Ionic:

   Ionic CLI                     : 5.4.16
   Ionic Framework               : 7.4.0
   @angular-devkit/build-angular : 16.2.2
   @angular-devkit/schematics    : 16.2.2
   @angular/cli                  : 16.2.2
   @ionic/angular-toolkit        : 9.0.0

System:

   NodeJS : v18.17.1 (/Users/philipp/.nvm/versions/node/v18.17.1/bin/node)
   npm    : 9.6.7
   OS     : macOS Unknown
```

**Comment by liamdebeasi** [comment] 2023-09-14 21:04
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/16569.

**Closed by liamdebeasi** 2023-09-14 21:04 UTC
Labels: triage

**Comment by hoi4** [comment] 2023-09-15 05:52
@liamdebeasi Do I understand correctly that this issue will never be tackled? We are trying to build a mobile-like experience for our web app where this would come in very handy. Is it a technical limitation?

**Comment by hoi4** [comment] 2023-09-15 08:51
For future reference: 

I found a workaround using Angular's `CanDeactivate` guard. 

```typescript
const canDeactivateFn: CanDeactivateFn<any> = (
  _component: any,
  _currentRoute: ActivatedRouteSnapshot,
  currentState: RouterStateSnapshot,
  nextState: RouterStateSnapshot,
): boolean => {
  const previousUrl = currentState.url;
  const nextUrl = nextState.url;

  inject(NavController).setDirection(previousUrl.includes(nextUrl) ? 'back' : 'forward');

  return true;
};
```

The key is to call `navController.setDirection`.

**Comment by liamdebeasi** [comment] 2023-09-15 13:12
> Do I understand correctly that this issue will never be tackled? We are trying to build a mobile-like experience for our web app where this would come in very handy. Is it a technical limitation?

It's a bug in our navigation implementation rather than an intentional design. We are working through a large backlog of tasks which means some items may take longer than others to fix, though we do plan to fix this.
