### ISSUE TITLE
bug: navigate in a pwa vue app is showing the Safari UI

### ISSUE THREAD

**Issue by TimothePearce** [ionic-team/ionic-framework#22592] opened 2020-11-27 17:27 UTC
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**
Using the tab navigation on an Ionic Vue app as a PWA added to my iOS device's homescreen, is currently showing the Safari UI (header and footer). This is not happening when using Angular or React.

**Steps to reproduce:**
1. Bootstrap a new Vue app with the "tabs" config
2. Execute `ionic serve` in the app directory
3. On an iOS device, go to the provided network URI
4. Add the app to the homescreen
5. Open the app
6. Navigate to tab 2

**Other information:**
![RPReplay_Final1606497296](https://user-images.githubusercontent.com/11693661/100473153-fd451200-30dd-11eb-9694-b7316f3b05f4.gif)

**Comment by liamdebeasi** [comment] 2020-11-30 14:54
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/19890.

**Closed by liamdebeasi** 2020-11-30 14:54 UTC
Labels: triage
