### ISSUE TITLE
bug: RouterLink only working the first time

### ISSUE THREAD

**Issue by JustinGuckes** [ionic-team/ionic-framework#21882] opened 2020-08-05 12:11 UTC
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**
When navigating to a route it works the first time, but not the second time (After going backer).
When simulating an iPad in Chrome it seems to work fine.

**Expected behavior:**
You would be able to navigate to the route as many times as you want.

**Steps to reproduce:**

1) Open route A using routerLink or router.navigateByUrl
2) then close the page using the back button or just go to another page.
3) Try to open Route A again,

Or use this Repo: https://github.com/JustinGuckes/ionic-routing-bug-mvp

**Related code:**
app-routing.module.ts
```

const routes: Routes = [
  {
    path: 'login',
    loadChildren: () => import('./modules/login/login.module').then(m => m.LoginModule),

  },
  {
    path: 'app',
    canActivate: [AuthGuard],
    loadChildren: () => import('./modules/layout/layout.module').then(m => m.LayoutModule),
  },
  {
    path: '**',
    redirectTo: 'app',
  },
];




@NgModule({
  imports: [
    RouterModule.forRoot(routes, {
      useHash: true,
      enableTracing: !environment.production
    })
  ],
  exports: [RouterModule]
})
```

layout-routing.module.ts
```
const routes: Routes = [
  {
    path: '',
    component: LayoutComponent,
    children: [
      {
        path: 'dashboard',
        loadChildren: () => import('../dashboard/dashboard.module').then(m => m.DashboardModule),
      },
      {
        path: 'recordbooks',
        loadChildren: () => import('../recordbooks/recordbooks.module').then(m => m.RecordbooksModule),
      },
      {
        path: '',
        redirectTo: 'dashboard',
        pathMatch: 'full'
      }
    ]
  },

];

@NgModule({
  imports: [
    RouterModule.forChild(routes)
  ],
  exports: [RouterModule]
})
```

dashboard-routing.module.ts
```
const routes: Routes = [
  {
    path: '',
    component: DashboardComponent,
  }
];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule]
})

```

recordbooks-routing.ts (The main issue, trying to open a recordbook using /app/recordbooks/ID HERE)
```

const routes: Routes = [
  {
    path: '',
    component: RecordbooksListComponent,
  },
  {
    path: ':id',
    component: RecordbooksSingleComponent,
  }
];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule]
})
```

**Other information:**
Having showTrace enabled in the Router shows that that the navigation doesnt even start.

As you can see in the following Ionic Info I'm using Angular 10, since it didnt work with Angular 9 either I hoped an update might solve the issue.
Same goes for @ionic/angular was using 5.0.0 and updated to 5.3.1, also didn't fix the issue.

**Ionic info:**
```
Ionic:

   Ionic CLI                     : 6.10.2 (C:\Users\justi\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.3.1
   @angular-devkit/build-angular : 0.1000.5
   @angular-devkit/schematics    : 9.1.12
   @angular/cli                  : 10.0.5
   @ionic/angular-toolkit        : 2.3.0

Capacitor:

   Capacitor CLI   : 2.3.0
   @capacitor/core : 2.3.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.18.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.6
   OS     : Windows 10
```

**Comment by JustinGuckes** [comment] 2020-08-06 07:16
Git Repository: https://github.com/JustinGuckes/ionic-routing-bug-mvp (Also Edited in Initial Post)

**Comment by liamdebeasi** [comment] 2020-08-06 13:49
Thanks for the reproduction. I'm confused, are you attempting to create a tabs-based application, or do you just want nested pages? Your application references tabs but attempts to use tabs without `ion-tabs`, which will not work.

**Comment by JustinGuckes** [comment] 2020-08-06 13:51
I just created a Blank Project using the tabs template since it provides 3 different routes and was the easiest to modify.

I just replaced ion tabs with ion-split-pane and add routerLinks to the ion-menu which should work as far I know ?

**Comment by mhartington** [comment] 2020-08-06 14:26
There's a few things that stand out.

- Nested router
 Typically, we don't recommend structuring things this way as it becomes difficult for angular router to know exactly what and where it should render something
- Non-absolute links
If you absolutely  _must_ have this, use absolute routes, so you are be explicit about what and where things should be updated.

for instance, modifying your links in tabs.html to work would be 

```
        <ion-item [routerLink]="['/','tabs','tab1']">Tab 1</ion-item>
        <ion-item [routerLink]="['/','tabs','tab2']">Tab 2</ion-item>
        <ion-item [routerLink]="['/','tabs','tab3']">Tab 3</ion-item>
```

or `/tabs/tab<n>` if you wanted to use strings instead.

**Comment by JustinGuckes** [comment] 2020-08-07 12:27
It seems to solve the issue in my provided example but somehow it doesnt in my Real-World-Project.

I've added my routes in my initial Post so maybe you can follow along;
In my example Project the issue was solved using absolute paths, however it doesnt work in my Real-World Project.
In my IRL Project using the absolute paths has the same effect (I'm trying /app/recordbooks/ID-HERE).

The main diff is that in my IRL Project I use tabs idk if this changes anything.

Also I'm not really sure if this is still a Bug or a mistake by my side? 
When I do normal Angular Applications I use routing the same way and it works there so I guess its ionic related?

**Comment by indraraj26** [comment] 2020-08-11 12:50
@JustinGuckes Is it possible for you to add real-world-project routing in your reproduce project, with that it will become easy to reproduce.
I have been using the same routing in my all angular project that you are using even in ionic.

**Comment by JustinGuckes** [comment] 2020-08-12 13:13
Okay after man many headaches i solved this issue.
honestly its such a dumb cause I have never experienced something like this and still can't understand how and why exactly that happened.

Anyways it was realted to a *ngFor directive, insteadof doing:

`*ngFor="let recordbook of recordbooks"`

I was calling a function like:

`*ngFor="let recordbook of getRecordbooks()"`

I dont know how that messed up the routing tho but it seems to work now.
Also I dont know if this should be considered as bug or not, I'm just gonna leave this open and let a mod decide :D ?

**Comment by liamdebeasi** [comment] 2020-08-17 15:06
Glad to hear the issue is resolved! It seems like this may have been an Angular bug given that changing the ngFor fixed it (Ionic Framework does not touch your ngFor directives). I am going to close this issue for now, thanks!

**Closed by liamdebeasi** 2020-08-17 15:06 UTC
Labels: triage

**Comment by SmallhillCZ** [comment] 2022-03-24 14:39
@liamdebeasi here (https://github.com/ionic-team/ionic-framework/issues/21882#issuecomment-669938114)  you claim one must use `<ion-tabs>` but in my issue you say "`ion-tab-bar` should already be usable outside of `ion-tabs`". which is true?

@mhartington says Ionic is not good for nested routing, but thats what <ion-tabs> does by default, create one more level of routing, despite abstracting away the router outlet

I have got the same issue as OP, having `[routerLink]` on `<ion-tab>` means it works only first time, then you may click whatever and nothing happens.

**Comment by liamdebeasi** [comment] 2022-03-24 14:48
I meant that `ion-tab-bar` should render correctly outside of `ion-tabs`. As per my comment on your issue (https://github.com/ionic-team/ionic-framework/issues/24637#issuecomment-1021294985) I asked for follow up information as I did not fully understand your request.

To have `ion-tab-bar` automatically work with our routing integrations, developers must use `ion-tabs`. However, developers can still use `ion-tab-bar` if they wish to use it for non-routing use cases. We do not support using `ion-tab-bar` outside of `ion-tabs` for routing use cases.


------

Mike did not say that Ionic is not good for nested routing. He said that he did not recommend the issue author use nested routing for their use case. Nested routing, while powerful, has very few instances where it is a good idea to use. An example of this is tabs.


------

Also please do not comment on closed issues. It makes it hard to keep track of the issues that still need triaging. Instead, please comment on the issues you have open or create a new one if your issues are closed/locked. Thanks!
