### ISSUE TITLE
bug: Ripple on list / checkboxes with label causes painting while scrolling (md mode)

### ISSUE THREAD

**Issue by qduborper** [ionic-team/ionic-framework#21736] opened 2020-07-13 11:18 UTC
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
There are cases where a ripple (md view) can happen on a list item while scrolling. When this happens the webview has to re-paint that item again which causes a frame rate drop in my tests. On IOS it creates undesired flicks on the bottom of the scroll.

**Expected behavior:**
Click/touch events need to be blocked on list items while scrolling so that this did not happen.

**Steps to reproduce:**
On material design view (mode md), put ion-checkbox component into a scroll list, with labels.

**Related code:**
Ionic documentation (https://ionicframework.com/docs/api/checkbox )

```
<IonList>
          <IonItemDivider>Default Checkbox</IonItemDivider>
          <IonItem>
            <IonLabel>Checked: {JSON.stringify(checked)}</IonLabel>
            <IonCheckbox checked={checked} onIonChange={e => setChecked(e.detail.checked)} />
          </IonItem>

          <IonItemDivider>Disabled Checkbox</IonItemDivider>
          <IonItem><IonCheckbox slot="end" disabled={true} /></IonItem>

          <IonItemDivider>Checkbox Colors</IonItemDivider>
          <IonItem>
            <IonCheckbox slot="end" color="primary" />
            <IonCheckbox slot="end" color="secondary" />
            <IonCheckbox slot="end" color="danger" />
            <IonCheckbox slot="end" color="light" />
            <IonCheckbox slot="end" color="dark" />
          </IonItem>
          <IonItemDivider>Checkboxes in a List</IonItemDivider>

          {checkboxList.map(({ val, isChecked }, i) => (
            <IonItem key={i}>
              <IonLabel>{val}</IonLabel>
              <IonCheckbox slot="end" value={val} checked={isChecked} />
            </IonItem>
          ))}
        </IonList>
```

**Other information:**
Related issue (https://github.com/ionic-team/ionic-framework/issues/7141)

**Comment by liamdebeasi** [comment] 2020-07-13 13:09
Thanks for the issue. Can you provide a repo that shows the framerate dropping? Additionally, what devices are you testing this on?

**Comment by qduborper** [comment] 2020-07-14 12:05
Hi,
I can't provide a repo but you can see below 2 examples on ios (iphone 11) with and without ripple effect (scrollling outside). Basically it's a list of checkbox and labels. You can see that the ripple effect cause re-paint when scrolling and create weird / jumps behaviour on top/bottom scroll. When we scroll we shouldn't have the ripple effect triggered ? In the meantime, is it possible to disable this ripple effect only on specific component like this checkbox ? 

Best regards

![with-ripple](https://user-images.githubusercontent.com/13855062/87423349-6f5b0580-c5da-11ea-90e0-c7879c7ad630.gif)
![without-ripple](https://user-images.githubusercontent.com/13855062/87423385-7f72e500-c5da-11ea-9cb8-647336e2182e.gif)

**Comment by liamdebeasi** [comment] 2020-07-14 13:41
Without a code reproduction, I am unable to fix the issue. Can you try to reproduce the issue in a blank Ionic starter application?

**Comment by qduborper** [comment] 2020-07-16 12:19
Yes please find below a blank starter project. Basically I just added mode to "md" and "rippleEffect" to true on App.tsx, then I added a list of checkboxes and label on Home.tsx. Please open it on ios with the browser or capacitor
[blank-starter-example.zip](https://github.com/ionic-team/ionic-framework/files/4931397/blank-starter-example.zip)

Here is a video screencast of this lags/jumps that occurs du to incorrect ripple effect triggered during scroll:
https://youtu.be/O66y51VXi8w

Best regards

**Comment by liamdebeasi** [comment] 2020-07-16 13:36
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The scroll jumping you are seeing is a bug in WebKit. I have reported this bug to the WebKit team, and they are able to reproduce the issue: https://bugs.webkit.org/show_bug.cgi?id=209968

**Closed by liamdebeasi** 2020-07-16 13:36 UTC
Labels: ionitron: needs reproduction

**Comment by qduborper** [comment] 2020-07-16 14:32
Ok thanks for your answer. As a workaround, is it possible to disable ripple effect on these checkbox element only, not all the components ? because I only saw the rippleEffect Boolean on the global setupConfig

**Comment by liamdebeasi** [comment] 2020-07-16 14:34
I believe we only offer a global ripple effect config currently.
