### ISSUE TITLE
bug: Ionic 7 `ion-input` & `ion-radio` with new label behavior is broken when used in modal with translations

### ISSUE THREAD

**Issue by Julien-Marcou** [ionic-team/ionic-framework#27147] opened 2023-04-08 16:33 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.0.1

### Current Behavior

`ion-radio` & `ion-input` with `[label]="'label' | translate"` are buggy when used inside modals, they only appear the first time you open the modal, and then they no longer appear.

### Expected Behavior

The label should always be displayed.

### Steps to Reproduce

I'll update this issue once I have a reproduction URL (as I discovered this bug on a private project)

### Ionic Info

```
Ionic:

   Ionic CLI                     : 7.0.1 (/home/jmarcou/.nvm/versions/node/v18.15.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.0.1
   @angular-devkit/build-angular : 15.2.5
   @angular-devkit/schematics    : 15.2.5
   @angular/cli                  : 15.2.5
   @ionic/angular-toolkit        : not installed

Capacitor:

   Capacitor CLI      : 4.7.3
   @capacitor/android : 4.7.3
   @capacitor/core    : 4.7.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v18.15.0 (/home/jmarcou/.nvm/versions/node/v18.15.0/bin/node)
   npm    : 9.6.1
   OS     : Linux 5.15
```

### Additional Information

It might be related to: https://github.com/ionic-team/ionic-framework/issues/27146

**Comment by liamdebeasi** [comment] 2023-04-10 13:10
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/27085.

**Closed by liamdebeasi** 2023-04-10 13:10 UTC
Labels: triage
