### ISSUE TITLE
bug: Broken scroll with angular CDK and ionic/angular 5.4.2 or higher

### ISSUE THREAD

**Issue by JumBay** [ionic-team/ionic-framework#22499] opened 2020-11-14 16:49 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

Starting from @ionic/angular 5.4.2 I've noticed that angular cdk virtual scroll is broken. 
As the bug is not easy to describe, here is a video that shows it: 

https://youtu.be/rmuJQ-036Ec

On the video you'll see an example app that runs the same code but on two different version of @ionic/angular 5.4.1 and 5.4.2 (the bug still exists on 5.4.4).

When you scroll down there is no issue, but when you start to scroll up, on v5.4.1 it's smooth but on v5.4.2 it's buggy

**Expected behavior:**

The scroll should not be buggy

**Steps to reproduce:**

clone this repository https://github.com/wako-app/virtual-scroll-and-ionic-5.4.2-issue and start it.
On this repository, if you switch to `v5.4.1` branch (or install `@ionic/angular 5.4.1`) you will see no bug.

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.12.1 (/Users/jb/.nvm/versions/node/v12.16.2/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.4.2
   @angular-devkit/build-angular : 0.1002.0
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.2.0
   @ionic/angular-toolkit        : 2.3.3

Utility:

   cordova-res : 0.15.2
   native-run  : 1.2.2

System:

   NodeJS : v12.16.2 (/Users/jb/.nvm/versions/node/v12.16.2/bin/node)
   npm    : 6.14.8
   OS     : macOS Big Sur
```

**Comment by BerkeAras** [comment] 2020-11-14 19:51
Ionic 5.4.2+ has scroll issues at the moment, see Issue #22498

**Comment by liamdebeasi** [comment] 2020-11-16 14:30
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/22473.

**Closed by liamdebeasi** 2020-11-16 14:30 UTC
Labels: triage

**Comment by JumBay** [comment] 2020-11-18 21:43
The issue is still present in 5.5.0

**Comment by mhartington** [comment] 2020-11-19 16:16
So looking at this, I'm actually more surprised it worked at to begin with 😬 

Basically the way virtual scroller works is that it takes the size of a child element, and uses it to layout each element appropriately.  Looking at the docs for CDK, they mention this


https://material.angular.io/cdk/scrolling/overview


With the way you have things setup, there ends up being multiple child elements, and the ion-grid needing to be a non-fixed size, the cdk-scroller breaks.

Why this works in previous releases for you is more confusing that why it breaks. Really this is just a limitation of the cdk-scroller.


If you want, you could try this one

https://github.com/rintoj/ngx-virtual-scroller

Which should support grid layout.

**Comment by BerkeAras** [comment] 2020-11-19 16:29
@mhartington Thanks for your help. Unfortunately this issue is not just present on Angular, it is present on ionic core too. Do you have a solution for that too?

**Comment by mhartington** [comment] 2020-11-19 16:39
@BerkeAras Please open a new issue with an example app for you situation.
