### ISSUE TITLE
bug: Fallback route breaks route params after redirect

### ISSUE THREAD

**Issue by sebastiencrevier** [ionic-team/ionic-framework#28984] opened 2024-02-06 16:32 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Let's say we enter a bad route, our fallback route will pick it up and redirect us to a valid route.

After the redirect, any route containing a route param won't be able to get resolved anymore, thus breaking the routing.

At this point, we need to force reload the page to fix the routing.

[screen-capture.webm](https://github.com/ionic-team/ionic-framework/assets/10478617/62bd4c0c-c20e-49b0-ab22-80c63fe93279)

### Expected Behavior

Fallback routes do not break routing.

### Steps to Reproduce

1. Enter an invalid route
2. Get redirected from the fallback route
3. Either this new route, or any following one containing a route param will not work properly

### Code Reproduction URL

https://github.com/sebastiencrevier/ionic-7-fallback-route-issue

### Ionic Info

Ionic:

   Ionic CLI       : 7.2.0 (C:\Users\sebas\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/react 7.6.6

Capacitor:

   Capacitor CLI      : 5.6.0
   @capacitor/android : not installed
   @capacitor/core    : 5.6.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 2.0.1

System:

   NodeJS : v20.10.0 (C:\Program Files\nodejs\node.exe)
   npm    : 10.2.3
   OS     : Windows 10

**Comment by amandaejohnston** [comment] 2024-02-07 15:23
Thank you for the issue. I'm going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/23743.

**Closed by amandaejohnston** 2024-02-07 15:23 UTC
Labels: triage
