### ISSUE TITLE
bug: can't go back to [min] date.

### ISSUE THREAD

**Issue by ciccilleju** [ionic-team/ionic-framework#24769] opened 2022-02-10 20:43 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

I’m using the lastest ion-datetime component and i’ve faced the following issue:

if i choose a min value as starting date, when i swipe months with the arrow and i go forward, i can’t go back to the first month.
For example, if I choose 1st of may 2022 as first available dater and 30th of september as max date if i go to june or july and i try to go back to may, i can’t and the min date available starts from 1st of june.
If i delete the starting date, everything works fine.

As you can see from the following video:

Uploading Registrazione schermo 2022-02-10 alle 21.35.09.mov…

### Expected Behavior

going from the first available month to the last one, back & forth

### Steps to Reproduce

in a ion-datetime component, choose a min value and a max value like this:

`      <ion-datetime [value]="dataSceltaInizio" size="cover" locale="it-IT"
        #dateTimePickervalue presentation="date" [min]="myService.minDate"
        [max]="myService.maxDate"
        (ionChange)="dataSceltaInizio = dateTimePicker.value;  ; dateTimePicker.confirm(); updateCalendarView();">

      </ion-datetime>`

### Ionic Info

Ionic:

   Ionic CLI                     : 6.18.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.7
   @angular-devkit/build-angular : 13.2.2
   @angular-devkit/schematics    : 13.2.2
   @angular/cli                  : 13.2.2
   @ionic/angular-toolkit        : 6.0.0

Capacitor:

   Capacitor CLI      : 3.4.0
   @capacitor/android : 3.4.0
   @capacitor/core    : 3.4.0
   @capacitor/ios     : 3.4.0

**Comment by liamdebeasi** [comment] 2022-02-10 21:51
Thanks for the issue. I am going to close this as a duplicate ofhttps://github.com/ionic-team/ionic-framework/issues/24757. This was fixed via https://github.com/ionic-team/ionic-framework/commit/7b3838cc670de7845bb5937d204e86cdba93b6e6.

**Closed by liamdebeasi** 2022-02-10 21:51 UTC
Labels: triage

**Comment by ciccilleju** [comment] 2022-02-10 22:13
Thank you so much for your reply
