### ISSUE TITLE
bug: Infninite scroll glitches when array's length divides on max / min value with decimal

### ISSUE THREAD

**Issue by NeroN7F** [ionic-team/ionic-framework#25219] opened 2022-04-29 16:50 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

I'm fetching data from the server into the array

    const performSearch = async () => {
      await axios
          .post('url', {'query': query})
          .then(response => {
            products.value = response.data
            productsLoaded.value = true
            queryStr.value = query

          })
    };

In this case, response is the products which are received in array, the value and length of array depend on search results. 

```
    let productLoadCount = ref(3)

    const pushData = () => {
      const max = productItems.value.length + productLoadCount.value;
      const min = max - productLoadCount.value;
      for (let i = min; i < max; i++) {
        productItems.value.push(products.value[i]);
      }
    };
```

When the infinite scroll is being triggered, everything works as expected, until it reaches the end of an array. Logics of function loadData() activates when all content has been shown, but because the max/min values are always rendering 3 items, without exception, an array that contains less than that would throw an error, eventually, it will break the code.

`TypeError: Cannot read properties of null (reading 'emitsOptions')`

Assuming that `    let productLoadCount = ref(3)` , which is max / min value and array length 11 would cause an error. It would render all 11 products as it should, but in the end, the logic that determines if all data is loaded would bug and break. 

Overall, if array length is less than value max/min in pushData or total length doesnt divides without decimal it throws an error 

It won't be that problematical, as infinite scroll fully functioning, but type error breaks some logic which prevents the user to click on the product and get url redirection.

Logic that would always calculate array length and load count could be worked around, but it would more complicated 

### Expected Behavior

Proper functioning off app logic to determine if all data is loaded by infinite scroll

### Steps to Reproduce

Set min & max value of infinite scroll to 6, when there are 20 items in the array

```
const max = items.value.length + 6;
const min = max - 6;
```

When all 20 items scrolled down, it would cause an error 

https://stackblitz.com/edit/vitejs-vite-djut6t?file=src%2FApp.vue

### Code Reproduction URL

https://stackblitz.com/edit/vitejs-vite-djut6t?file=src%2FApp.vue

### Ionic Info

Ionic:

   Ionic CLI : 6.19.0

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v16.13.0
   npm    : 8.1.0
   OS     : Windows 11

**Comment by liamdebeasi** [comment] 2022-04-29 17:30
Thanks for the issue. I cannot reproduce the `emitsOptions` error, but I can reproduce the following error when loading the 20th item:

```
App.vue:19 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'image')
```

After looking at your code, I do not see anything that would indicate this is an Ionic bug. The infinite scroll component only enables/disables when the app tells it to, so there may be a logic bug in your application that is resulting in this problem.

Are you able to provide any more details that can help me verify if this is a bug coming from inside of Ionic?

**Comment by NeroN7F** [comment] 2022-04-30 11:20
emitOptions error occurs when the bottom of infinite scroll is reached, scrolled to the top, and then to the bottom again. Loader will show up and emitOptions error will be visible in the console along with:

`Cannot read properties of undefined (reading 'get_thumbnail')`

where get_thumbnail is any data of the product

<img width="1282" alt="image" src="https://user-images.githubusercontent.com/49721208/166102525-1d13b5c6-019b-44ed-8b96-b21b29c729ba.png">

When fully scrolled to the bottom, then to the top and bottom, loader will show up again, even if an infinite scroll has been completed.

<img width="283" alt="image" src="https://user-images.githubusercontent.com/49721208/166102578-9f8609c9-14f8-4ceb-bb5f-fab904af79b1.png">

And then emmitOption error occurs

<img width="1276" alt="image" src="https://user-images.githubusercontent.com/49721208/166102638-e475f90b-8b66-40b2-9690-c2067c6e1f2b.png">

Normally, if an array's length can be divided by max, min value and the result will be an integer, everything would work fine. When the result will contain a decimal, this behavior occurs. When 9 of 11 items have been rendered it expects to get another 3 to activate logic that disables infinite scroll, while there are only 2, it causes the loader to show up again as it trying to get item that doesnt exists. The issue can be reproduced in any project

1. Add infinite scroll
2. Create an array with 10 items
3. in pushData change both min and max constants to any value that will divide by 10 with the remainder 
4. Scroll down to the bottom, until the end, then slightly to the top, so the last item wont be visible, and to the bottom again

**Comment by liamdebeasi** [comment] 2022-05-02 20:27
Thanks for the follow up. Ionic does not appear to be the cause of this issue. I observed `undefined` being pushed to `items.value`.

For example, if you change your loop to the following:

```js
for (let i = min; i < max - 1; i++) {
  items.value.push(posts.value[i]);
}
```

then the error I mentioned in https://github.com/ionic-team/ionic-framework/issues/25219#issuecomment-1113555275 does not happen.

I still am unable to reproduce the `emitsOption` error. However, looking at the screenshot you provided it is possible this is either another bug in your app or a bug in Vue. 

Are you able to identify which piece of Ionic's code you feel is causing this issue? Otherwise, I think it would be better to post on the [Ionic Forums](https://forum.ionicframework.com/) to get help debugging this problem.

**Comment by NeroN7F** [comment] 2022-05-03 17:44
To make sure that the error is not app's logic and eliminate doubts I've reproduced code as in [documentation](https://ionicframework.com/docs/api/infinite-scroll)

https://stackblitz.com/edit/vitejs-vite-djut6t?file=src%2FApp.vue

If array reaches the end:

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/49721208/166499841-a4b4f471-47ae-41bc-8403-6780a79bd180.png">

No emitOptions error, but `ev.target.disabled` doesnt executes to stop load data event, here's why loader still shows up if bottom is reached. 

Error `Cannot read properties of undefined (reading 'image')` is caused not by API or component, it appears only in circumstances which I [mentioned](https://github.com/ionic-team/ionic-framework/issues/25219#issuecomment-1113970751)

The issue is that `load data` event triggers again, even if there's no data, because condition below is never true. 
```
        if (items.value.length == posts.value.length) {
          ev.target.disabled = true;
        }
```
For loop pushes i amount of products into the items array, three for example.
```
      for (let i = min; i < max - 1; i++) {
        items.value.push(posts.value[i]);
      }
```
Total amount of products in posts array - 14, then when fourth Load data event will be completed, it will be triggered again to push 3 more items as max/ min constants indicate and will throw the error:  `Cannot read properties of undefined (reading 'image')` as 15th item does not exist. It prevents the logics of `productItems.value.length == catalog.value.length` to work as it 14 === 15 which always false and wont execute `ev.target.disabled = true;` which would constantly trigger loadData and
cause `Cannot read properties read properties of undefinied`. If the aim was always to render a fixed amount of items, then condition as in docs `items.value.length === 1000` would work, as the exact amount is known. If such a case was not considered during the development of Ionic, then it can not be considered as a bug, because it may be fixed by custom logic

**Comment by liamdebeasi** [comment] 2022-05-03 18:17
The logic we use to disable the refresher is specific to that example. It is not a universal example that will work for every use case. It is the responsibility of the app developer to write logic that disables the refresher at the correct time.

For example, you mentioned that the following `if` statement is never `true`, resulting in the refresher never being disabled:

```html
 if (items.value.length == posts.value.length) {
  ev.target.disabled = true;
}
```

In that case, you should revise the `if` statement such that it results in the refresher being disabled at the correct moment. Perhaps you need to do a less than or greater than comparison instead of a strict equality check?

This issue seems to be caused by an implementation detail, not a bug in Ionic. As a result, I am going to close this. I encourage you to post on the [Ionic Forums](https://forum.ionicframework.com/) if you need additional assistance in getting this implemented. Thanks!

**Closed by liamdebeasi** 2022-05-03 18:17 UTC
Labels: triage
