### ISSUE TITLE
bug: Ion Button Submit Doesnt Allow Return Key To Submit Form

### ISSUE THREAD

**Issue by Lindsor** [ionic-team/ionic-framework#22119] opened 2020-09-20 03:36 UTC
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
On desktop, if you create a reactive form and subscribe to the formGroup's (ngSubmit), the angular experience is that as long as there is a button[type=submit] the ngSubmit should trigger.
Currently using `<ion-button type=submit>` does not adhere to this experience.

**Expected behavior:**
The form should be submitted.

**NOTE: ** in the code below if you replace `<ion-button>` with `<button>` it works as expected.

**Steps to reproduce:**
```
<form [formGroup]="loginForm" (ngSubmit)="submitLogin()">
  <ion-grid>
    <ion-row class="ion-align-items-center">
      <ion-col size="12" size-sm="5">
        <ion-item>
          <ion-label position="stacked">Username</ion-label>
          <ion-input
            formControlName="username"
            inputmode="numeric"
            autocomplete="username"
            type="text"
          ></ion-input>
        </ion-item>
      </ion-col>

      <ion-col size="12" size-sm="4">
        <ion-item>
          <ion-label position="stacked">Password</ion-label>
          <ion-input
            formControlName="password"
            autocomplete="current-password"
            type="password"
          ></ion-input>
        </ion-item>
      </ion-col>

      <ion-col class="ion-text-right">
        <ion-button type="submit">Login</ion-button>
      </ion-col>
    </ion-row>
  </ion-grid>

</form>
```

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.11.8
   Ionic Framework               : @ionic/angular 5.3.3
   @angular-devkit/build-angular : 0.1001.2
   @angular-devkit/schematics    : 10.1.2
   @angular/cli                  : 10.1.2
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : 7.0.1
   Cordova Platforms : none
   Cordova Plugins   : no whitelisted plugins (3 plugins total)

Utility:

   cordova-res : 0.15.1
   native-run  : not installed

System:

   Android SDK Tools : 26.1.1 (/Users/mluz/Library/Android/sdk)
   ios-deploy        : 1.9.1
   ios-sim           : 6.0.0
   NodeJS            : v14.11.0 (/Users/mluz/.nvm/versions/node/v14.11.0/bin/node)
   npm               : 6.14.8
   OS                : macOS Catalina
   Xcode             : Xcode 11.3.1 Build version 11C504
```

**Comment by liamdebeasi** [comment] 2020-09-21 13:18
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/19368.

**Closed by liamdebeasi** 2020-09-21 13:18 UTC
Labels: triage
