### ISSUE TITLE
bug: IonLabel not visible in IonItem

### ISSUE THREAD

**Issue by YaMiSt** [ionic-team/ionic-framework#28040] opened 2023-08-22 13:46 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

If I have an IonItem and inside is an IonLabel and IonInput, the IonLabel will not be longer shown.

We don't want to use the label and labelPlacement of IonInput, because its very unflexible. 
(I allthough didn't understand why that was made, I liked the atomic design)

### Expected Behavior

The IonLabel should be visible inside a IonItem

### Steps to Reproduce

Demo:

`<IonItem>
  <IonLabel>Not visible</IonLabel>
  <IonInput aria-label="" />
  <IonButton slot="end">DO</IonButton>
<IonInput>`

### Ionic Info

Ionic:

   Ionic CLI       : 7.0.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 7.2.3

Capacitor:

   Capacitor CLI      : 1.3.0
   @capacitor/android : 3.9.0
   @capacitor/core    : 3.3.4
   @capacitor/ios     : 3.9.0

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v19.8.1 (/usr/local/Cellar/node/19.8.1/bin/node)
   npm    : 6.14.18
   OS     : macOS Unknown

  ───────────────────────────────────────────────

     Ionic CLI update available: 7.0.1 → 7.1.1
         Run npm i -g @ionic/cli to update

  ───────────────────────────────────────────────

**Comment by YaMiSt** [comment] 2023-08-22 16:23
Hi @liamdebeasi,

Yes, I know there is the new solution and you can work with slot.

But for layouts it is easier to have the elements on one level, for example when working with grids/widths, because we want to offer a uniform layout.

We will now build our own component, but I would still not simply hide the component in an IonItem. :)

**Comment by liamdebeasi** [comment] 2023-08-22 16:34
Thanks for the feedback! We made these form control changes to improve accessibility by ensuring that the visible text label is already associated with the form control. We also found that `ion-item` had a tendency to be misused, which resulted in other usability concerns. We are working on correcting some of those incorrect assumptions, and the form control update is part of this.

As I noted above, form controls in the main slot inside of `ion-item` are supposed to take up the full width since they are designed to be the only interactive element in there. The named slots exist so developers can put other interactive controls on the same row without conflicting with the interactive content in the default slot.

The original code snippet provided is not the correct usage because the `ion-label` is not actually associated with the `ion-input`. Interactive form controls should always have an associated label (whether that is visible text or an `aria-label`) to adhere to accessibility best practices. The new form control syntax ensures this, so I recommend trying to use the existing API instead of creating your own.

Ionic is working as intended here, so I am going to close this, but let me know if you have any questions.

**Closed by liamdebeasi** 2023-08-22 16:34 UTC
Labels: triage
