### ISSUE TITLE
bug: Axe tool highlight the issue with ion-date as "Certain ARIA roles must contain particular children".

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/ionic-framework#21667] opened 2020-07-03 11:05 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

Similar to an already reported issue with ion-select:

<img width="468" alt="Picture1" src="https://user-images.githubusercontent.com/1526846/86463431-198d8000-bcf3-11ea-94a3-c391237664a9.png">

**Comment by liamdebeasi** [comment] 2020-07-07 20:40
Confirmed. `ion-datetime` shouldn't event have `role="combobox"` since it is merely the trigger that opens `ion-picker` (which _should_ have `role="listbox"` I think).

**Comment by liamdebeasi** [comment] 2020-07-10 13:37
Fixed via https://github.com/ionic-team/ionic-framework/pull/21708

**Closed** 2020-07-10 13:37 UTC
Labels: package: core, type: bug
