### ISSUE TITLE
bug(ion-datetime) : max date 

### ISSUE THREAD

**Issue by indraraj26** [ionic-team/ionic-framework#26533] opened 2022-12-24 08:27 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

If you set min to today with that you will not be able to select future year but able to scroll in calendar and change year.
![Screenshot 2022-12-24 at 1 54 35 PM](https://user-images.githubusercontent.com/23274631/209427740-970d12ae-50d7-441a-8b47-75fe3a462f78.png)

### Expected Behavior

I should be able to to scroll year in above screenshot

### Steps to Reproduce

https://stackblitz.com/edit/angular-f31de2?file=src%2Fapp%2Fexample.component.html,src%2Fapp%2Fexample.component.ts

### Code Reproduction URL

https://stackblitz.com/edit/angular-f31de2?file=src%2Fapp%2Fexample.component.html,src%2Fapp%2Fexample.component.ts

### Ionic Info

Ionic: 6.4.1

**Comment by maylorsan** [comment] 2022-12-24 17:37
Yeap, I can confirm this behavior
Duplicate of: https://github.com/ionic-team/ionic-framework/issues/26532, as i see

**Comment by sean-perkins** [comment] 2022-12-27 16:44
This issue is a duplicate of: https://github.com/ionic-team/ionic-framework/issues/25293, by default we only render the current year in the year picker. 

If you want to work around this in the interim, you can assign a `max` value of a year value in the future.

e.g.:
```ts
<ion-datetime max="2030"></ion-datetime>
```

This is a repeat reported issue and also confusing to developers/users as it isn't clear that is the default behavior of the datetime. I'll discuss with the team once they are back after the New Year if we can start planning towards a resolution after v7 beta.

---

@maylorsan is your issue actually a duplicate of this? If so, we can close that as well. The description of your issue talks about jumping interactions with the picker, not the lack of selecting a future year.

**Closed by sean-perkins** 2022-12-27 16:44 UTC
Labels: holiday triage

**Comment by maylorsan** [comment] 2022-12-27 17:43
@sean-perkins Part of my problem is described in this issue.

I think that there is a bug in the scroller itself, because after you have moved to the next year, you are thrown back to the previous one, this is shown in the video in: https://github.com/ionic-team/ionic-framework/issues/25293
