### ISSUE TITLE
bug: Performance issues on rendering ion elements 

### ISSUE THREAD

**Issue by asa47** [ionic-team/ionic-framework#23187] opened 2021-04-14 11:24 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

We have noticed that when we renders a small number of ion elements, the app interaction becomes "slow". 
It seems that the application needs time to generate/render all the ion elements and the shadow dom elements. 

We were able to detect this issue by triggering different modals:
- Modal with 27 ion elements takes around 180ms to render
- Modal with 350 divs takes around 150ms to render
- Modal with 1 div and takes around 30ms to render

I would have thought that rendering 350 html elements would have been more expensive than rendering 27 ion elements, but it seems to be the other way round. Are we missing something? Or are we doing something wrong?
Please let us know, and I am happy to share additional code if needed.

**Expected behavior:**

It would be great if we could use the ion elements, without affecting the app performance. 

**Steps to reproduce:**

1. Download the repo on github (https://github.com/asa47/ion-perfomance).
2. Run the project
3. Refresh the page and click on one of the 3 buttons to trigger the different modals (Ionic modal, simple modal and empty modal)
    - "ionic modal" has 27 ion elements
    - "simple modal" has 350 divs
    - "empty modal" has 1 div
4) Check the console to see the timestamp

**Related code:**

The following is generated with the ionic starter blank template:
Repo (https://github.com/asa47/ion-perfomance)

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.12.3 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 5.6.4

Capacitor:

   Capacitor CLI   : 2.4.7
   @capacitor/core : 2.4.7

Utility:

   cordova-res (update available: 0.15.3) : 0.15.2
   native-run                             : not installed

System:

   NodeJS : v12.22.1 (/usr/local/bin/node)
   npm    : 6.14.12
   OS     : macOS Catalina
```

**Comment by liamdebeasi** [comment] 2021-04-14 14:58
Thanks for the issue! I can reproduce this, and there a few things contributing to the slow benchmark results:

1. Your benchmark includes a lazy load import for `modalController`:

```js
const { modalController } = await import('@ionic/vue');
```

While this does not significantly contribute to the load time, it is not related to any performance issues with rendering Ionic components and probably should not be included in the benchmark.

2. In the modal and popover components, we call a `deepReady` function which recursively finds all Ionic components and waits for them to be ready. In Ionic Vue v6 we will be introducing a "Custom Elements" build of Ionic which essentially gets rid of the need to wait for these components to be ready. I tested out a dev build of it and saw saving of over 100ms with the Ionic modal in your app.

3. The remaining time is likely just due to adding in Ionic components that use JavaScript. I would not expect the modal with Ionic components to be as fast as the empty modal. In particular, I have seen unnecessary usages of `ion-grid`, `ion-row`, and `ion-col` that contribute to these kinds of slowdowns in other apps. I think you could get a big cost savings if you just used CSS Grid rather than these grid components.

For context, these components were created before CSS Grid was widely supported. We will be rolling out new docs with Ionic Framework v6 that should aim to resolve some of these confusions about which to use (CSS Grid vs Flexbox vs `ion-grid` with Flexbox).

Your template would look something like this instead:

```html
<template>
  <ion-content>
    <template v-for="(value, index) of [1, 2, 3, 4, 5, 6]" :key="index">
      <div class="grid">
        <div class="ion-no-padding ion-text-center" size="3" v-for="(value2, index2) of [1, 2, 3, 4]" :key="index2">
          <ion-card class="modifier">
            <span>{{ value2 }}</span>
            <span>{{ value2 }}</span>
            <span>{{ value2 }}</span>
          </ion-card>
        </div>
      </div>
    </template>
  </ion-content>
</template>

<script lang="ts">
  import { IonCard, IonContent } from '@ionic/vue';
  import { defineComponent } from 'vue';
  export default defineComponent({
  name: 'IonicModal',
  components: {
    IonContent, IonCard
  }, setup() {
    return {
    };
  }
  });
</script>

<style scoped>
.grid {
  display: grid;

  grid-template-columns: repeat(4, 1fr);
}

ion-card {
  display: flex;
}

ion-card span {
  width: 100%;
  padding: 5px;
}
</style>
```

I am going to close this out as most of the actionable items from Ionic Team have already been completed. Thanks!

**Closed by liamdebeasi** 2021-04-14 14:58 UTC
Labels: triage

**Comment by jthoms1** [comment] 2021-12-15 18:00
I just upgraded this project to @ionic/vue v6. Here are the performance numbers I receive.
This is on an m1 macbook pro. These numbers are from running the production build rather than the dev build.

openIonicModal: 70.615234375 ms
openSimpleModal: 57.10791015625 ms
openEmptyModal: 15.800048828125 ms

With a CPU trottling to 6x slowdown in Chrome these are the performance numbers I receive.

openIonicModal: 68.98876953125 ms
openSimpleModal: 61.8330078125 ms
openEmptyModal: 14.125244140625 ms

You can see me reproduction here: https://github.com/jthoms1/ion-perfomance
