### ISSUE TITLE
bug: ion-password-toggle label-placement="floating" doesn't work

### ISSUE THREAD

**Issue by gasci** [ionic-team/ionic-framework#29695] opened 2024-07-07 19:42 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/docs/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v8.x

### Current Behavior

https://ionicframework.com/docs/api/input-password-toggle

The password toggle widget doesn't work with the `label-placement="floating"` attribute.

### Expected Behavior

It should float the label.
![Screenshot 2024-07-07 at 21 39 24](https://github.com/ionic-team/ionic-framework/assets/29505701/978bdaeb-7010-4c6c-90ce-6d1c0f08831c)

### Steps to Reproduce

```
<ion-item lines="none">
   <ion-input id="password-login" label-placement="floating" :label="$t('enter_your_password')">
        <ion-input-password-toggle slot="end"></ion-input-password-toggle>
   </ion-input>
</ion-item>
```

### Code Reproduction URL

https://ionicframework.com/docs/api/input-password-toggle

### Ionic Info

Ionic:

   Ionic CLI       : 7.2.0 (/opt/homebrew/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 8.2.5

Capacitor:

   Capacitor CLI      : 6.1.0
   @capacitor/android : 6.1.0
   @capacitor/core    : 6.1.0
   @capacitor/ios     : 6.1.0

Utility:

   cordova-res : not installed globally
   native-run  : 2.0.1

System:

   NodeJS : v18.19.0 (/Users/goktugasci/.nvm/versions/node/v18.19.0/bin/node)
   npm    : 10.8.1
   OS     : macOS Unknown

**Comment by brandyscarney** [comment] 2024-07-08 21:50
Thanks for the issue. I believe this is a duplicate of https://github.com/ionic-team/ionic-framework/issues/29449. Please let me know if I am misunderstanding the issue and I will reopen.

**Closed by brandyscarney** 2024-07-08 21:50 UTC
Labels: triage
