### ISSUE TITLE
bug: Using callback in ref attribute breaks IonInput

### ISSUE THREAD

**Issue by tonn** [ionic-team/ionic-framework#23111] opened 2021-03-28 09:12 UTC
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**
Other attributes of IonInput are ignored when I set callback to ref.

**Related code:**

https://codesandbox.io/s/ionic-react-forked-q8l4v?file=/src/pages/Home.tsx

```
const callback = useCallback((elem) => {
  console.dir(elem);
}, []);

...

<IonInput 
  className="asdasd" // <-- className is ignored
  onIonChange={(e) => setText(e.detail.value)} // <-- this callback is ignored too
  ref={callback} // <-- If remove this line ion-input will start work fine
/>
```

**Comment by liamdebeasi** [comment] 2021-03-29 15:04
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. When using `useCallback` you are not actually passing a ref to the `IonInput` instance. As a result, Ionic React does not know what to bind `className` and `onIonChange` to. Instead of using `useCallback`, you should use `useRef` as noted in the React docs: https://reactjs.org/docs/refs-and-the-dom.html

**Closed by liamdebeasi** 2021-03-29 15:04 UTC
Labels: triage

**Comment by tonn** [comment] 2021-03-29 15:11
>you should use useRef as noted in the React docs

I can't use useRef because I need ref in useEffect and this is not working. React docs suggest to use useCalback with ref-attribute in such situation
https://reactjs.org/docs/hooks-faq.html#how-can-i-measure-a-dom-node
https://stackoverflow.com/a/63033314/2316738

**Comment by liamdebeasi** [comment] 2021-03-29 15:26
Can you clarify what you are trying to do in your app?

**Comment by tonn** [comment] 2021-03-29 15:27
I need to set focus to input when component is rendered first time

**Comment by liamdebeasi** [comment] 2021-03-29 15:37
I recommend trying a lifecycle hook instead of using `useCallback`. The reason is that when `useCallback` is fired, the view itself may not have been shown via `IonRouterOutlet` yet. In this case, calling `ionInput.setFocus()` would not work.

There are 2 alternatives:

1. Use the `autofocus` property on `IonInput`. Some browsers have restrictions around autofocus, so this may or may not work depending on the browser you are using.
2. Use an Ionic lifecycle hook to focus the input once the page has been shown:

```jsx
import { useIonViewDidEnter } from '@ionic/react';

...

const myRef = useRef<HTMLIonInputElement>(null);
useIonViewDidEnter(() => {
  myRef.current && myRef.current.setFocus();
});

...

<IonInput ref={myRef} />
```

**Comment by tonn** [comment] 2021-04-06 12:21
Yep... autofocus work only first time.
And my component is not IonPage, it has no ionic page lifecycles. And it may be rendered and removed several time on one page. So I need to use callback in ref.
