### ISSUE TITLE
feat(scrollbar): force light / dark mode

### ISSUE THREAD

**Issue by DwieDima** [ionic-team/ionic-framework#26155] opened 2022-10-20 12:18 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Currently the scrollbar is light on darkmode and dark on lightmode.
If your device is on darkmode and the app content background is light, the scrollbar is hardly to find.
It should be possible to force the mode, so scrollbar is visible on light content.

In the screenshots below you see one in dark and the other in light mode:

## Darkmode
<img src="https://user-images.githubusercontent.com/26873275/196944814-655b5970-cafc-4abe-b8b9-c0fe21ba9fc9.jpeg" width="100">

## Lightmode
<img src="https://user-images.githubusercontent.com/26873275/196944843-0b187b72-bf4f-4d2a-b23a-65c9434c2c29.jpeg" width="100">

### Describe the Use Case

Developers should be able to force scrollbarColor to light or dark, so it fits to their content background-color.

### Describe Preferred Solution

extend `IonicConfig` with: 

`scrollbarColor: 'auto' | 'light' | 'dark'` default: `auto`

so it can be applied globally

### Describe Alternatives

you have to style it by your own, which is not consistent with different browsers or might break with future releases:
https://github.com/ionic-team/ionic-framework/issues/25217#issuecomment-1113324340

**Comment by liamdebeasi** [comment] 2022-10-27 15:45
Thanks for the report. Have you seen our documentation on [Adjusting System UI Components](https://ionicframework.com/docs/theming/dark-mode#adjusting-system-ui-components)? You could be able to force a particular color scheme.

**Comment by DwieDima** [comment] 2022-10-28 13:13
Thank you for the link!
This worked as expected 😄.

In my case i applied light to `ion-content` and `div` to show dark scroll-bar:

```css
ion-content,
div {
  color-scheme: light;
}
```

**Comment by DwieDima** [comment] 2022-11-08 14:10
sure:

https://stackblitz.com/edit/angular-5hfqes?file=src/global.css

you can reproduce it by directly opening the link on your device browser, no need to deploy:

https://angular-5hfqes.stackblitz.io/

- If you open this link on your iPhone safari with darkmode enabled, you'll still see the light scrollbar (wrong)
- If you open this link on your Mac safari with darkmode enabled, you'll see the dark scrollbar (correct)

**Comment by liamdebeasi** [comment] 2022-11-09 20:46
I can reproduce this behavior, but this is not an Ionic bug. It looks like there is a WebKit bug where nested container scrollbars always follow the OS-level dark theme preference: https://bugs.webkit.org/show_bug.cgi?id=206771

Is this is a bug you need resolved, I recommend posting on the WebKit bug thread and explain how this bug negatively impacts any apps you have in production.

**Comment by DwieDima** [comment] 2022-11-09 23:42
> I can reproduce this behavior, but this is not an Ionic bug. It looks like there is a WebKit bug where nested container scrollbars always follow the OS-level dark theme preference: https://bugs.webkit.org/show_bug.cgi?id=206771
> 
> Is this is a bug you need resolved, I recommend posting on the WebKit bug thread and explain how this bug negatively impacts any apps you have in production.

Thank you for providing the link. The issue is already described very well by the author, so i can only confirm this behavior.

Sadly this issue persists since 2020 :(

**Comment by liamdebeasi** [comment] 2022-11-10 18:13
If you do not want a dark mode for your app one thing you could try is creating an artificial gutter for the scrollbar. This gutter could have a white background in light mode and a dark background in dark mode which would ensure the correct contrast is used. You could also have it disappear after a timeout of not scrolling by using the `ionScrollEnd` event: https://ionicframework.com/docs/api/content#events

I am going to close this as this is not a bug in Ionic, but let me know if you have additional questions.

**Closed by liamdebeasi** 2022-11-10 18:13 UTC
Labels: triage
