### ISSUE TITLE
bug: React <IonInput type="date"  /> value is not rendered like other input value in Android

### ISSUE THREAD

**Issue by WorstTypist** [ionic-team/ionic-framework#28551] opened 2023-11-17 13:05 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

The `<IonInput type ="date" />` doesn't render the same as `<IonInput type ="text" />` 
The value displayed once entered is not aligned on the date input (also for datetime)
![image](https://github.com/ionic-team/ionic-framework/assets/88891878/1f747171-5616-4874-9e2c-2fc42fddd7d2)

Have to mention it's working as expected on a browser
![image](https://github.com/ionic-team/ionic-framework/assets/88891878/07e648ce-fd88-410c-ad45-da12068ec1df)

### Expected Behavior

Both inputs should render the value the same way.
inline (default) should be horizontally aligned
stacked or floating should have the same space between label and value as a text input

### Steps to Reproduce

Create an `<IonInput type="date" />`
Go to app, enter a value
See the value is not positionned as expected

### Code Reproduction URL

https://github.com/WorstTypist/ionic-test-app

### Ionic Info

Ionic:

   Ionic CLI       : 7.1.1 (C:\Users\I733564\AppData\Local\Volta\tools\image\packages\@ionic\cli\node_modules\@ionic\cli)
   Ionic Framework : @ionic/react 7.5.5

Capacitor:

   Capacitor CLI      : 5.5.1
   @capacitor/android : 5.5.1
   @capacitor/core    : 5.5.1
   @capacitor/ios     : not installed

Utility:

   cordova-res                          : not installed globally
   native-run (update available: 2.0.0) : 1.7.4

System:

   NodeJS : v20.6.1 (C:\Users\I733564\AppData\Local\Volta\tools\image\node\20.6.1\node.exe)
   npm    : 9.8.1
   OS     : Windows 10

**Comment by amandaejohnston** [comment] 2023-11-17 15:18
Thank you for the issue. I'm going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/28383.

**Closed by amandaejohnston** 2023-11-17 15:18 UTC
Labels: triage
