### ISSUE TITLE
bug: scrolling is broken after using ion-refresher together with ion-segment

### ISSUE THREAD

**Issue by sebastian-zarzycki-es** [ionic-team/ionic-framework#22590] opened 2020-11-27 13:46 UTC
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
When pulling down to enable refresher, sometimes (usually after content switch/repaint, so, for example, after switching segments) the content seems to be going several pixels down and is no longer scrollable (either in web version and in mobile native build). Seems that it is connected to segments somehow.

This does not happen with a refresher in a view without segments.

This error appears only in newest Ionic versions. It **does not** happen in @ionic/angular 5.4.1

![Nov-27-2020 14-42-13](https://user-images.githubusercontent.com/11352013/100455475-0bd00100-30bf-11eb-8626-4eea9cb707b4.gif)

**Expected behavior:**
Content should still be scrollable. No content movement.

**Steps to reproduce:**
Use refresher inside a view that is steered by ion-segment.

**Related code:**
Roughly:
```
<ion-content>

  <ion-segment [value]="currentTab" (ionChange)="onTabChange($event)">
    <ion-segment-button [value]="Tab.ACTIVE">
      <ion-label>ACTIVE</ion-label>
    </ion-segment-button>
    <ion-segment-button [value]="Tab.PAST">
      <ion-label>PAST</ion-label>
    </ion-segment-button>
  </ion-segment>

  <div class="ion-padding">
    <ng-container *ngIf="currentTab === Tab.ACTIVE">
      <ion-refresher slot="fixed" (ionRefresh)="doRefresh($event)">
        <ion-refresher-content></ion-refresher-content>
      </ion-refresher>
   </ng-container>
 </div>

</ion-content>
```

**Other information:**
**Ionic info:**
```
Ionic:

   Ionic CLI                     : 6.12.2 (/opt/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.5.1
   @angular-devkit/build-angular : 0.1001.6
   @angular-devkit/schematics    : 10.1.0
   @angular/cli                  : 10.1.6
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : 6.0.0, android 9.0.0, browser, ios 6.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 13 other plugins)

Utility:

   cordova-res : 0.15.2
   native-run  : 1.2.2

System:

   Android SDK Tools : 26.1.1 (/Users/rattkin/Library/Android/sdk)
   ios-deploy        : 1.11.3
   ios-sim           : 8.0.2
   NodeJS            : v14.15.1 (/opt/local/bin/node)
   npm               : 6.14.9
   OS                : macOS Big Sur
   Xcode             : Xcode 12.2 Build version 12B45b
```

**Comment by sebastian-zarzycki-es** [comment] 2020-11-30 19:20
I'm sure smart Ionic developers can reproduce it. Surely they prefer that from having a piece of buggy software on their hands.

**Comment by liamdebeasi** [comment] 2020-12-03 14:32
Hi there,

I asked for a code reproduction because I was unable to reproduce the issue using the code snippet provided. The easiest way to provide a code reproduction is to add the minimal amount of code to an Ionic starter application and post a link to the repo here.

**Comment by liamdebeasi** [comment] 2020-12-03 14:39
Actually, no need. Someone reported the same issue in https://github.com/ionic-team/ionic-framework/issues/22616 and was able to provide a code reproduction. I am going to close this issue in favor of that one.

**Closed by liamdebeasi** 2020-12-03 14:39 UTC
Labels: ionitron: needs reproduction

**Comment by sebastian-zarzycki-es** [comment] 2020-12-03 15:42
Great, I'm glad it could be reproduced. Good luck!
