### ISSUE TITLE
bug: invalid routing behavior when using browser back/forward buttons

### ISSUE THREAD

**Issue by legendar** [ionic-team/ionic-framework#28879] opened 2024-01-25 12:40 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When we have several nested views in one tab the forward browser button doesn't work correctly. 
We have three routes in one tab:
```
/tab1/
/tab1/nested
/tab1/nested/subnested
```
When we click the back browser button on "subnested" we navigate to the "nested" page as expected. Then when we click the forward browser button on the "nested" page we expect to navigate to the "subnested" page but instead see the root tab view. Note that the route path changed correctly

### Expected Behavior

We expect that the forward browser button will navigate to the forward view.

### Steps to Reproduce

In the provided repo:
1. open `/tab1` page
2. click "Go to nested page". you will navigate to `/tab1/nested`
3. click "Go to sub nested page". you will navigate to `/tab1/nested/subnested`
4. click browser back button.  you will navigate back to `/tab1/nested`
5. click browser forward button. the route will changed to `/tab1/nested/subnested` but the Tab1 root view is rendered

### Code Reproduction URL

https://github.com/legendar/ionic-issues

### Ionic Info

Ionic:

   Ionic CLI       : 7.2.0 (/***/ionic-issues/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 7.6.6

Capacitor:

   Capacitor CLI      : 5.6.0
   @capacitor/android : not installed
   @capacitor/core    : 5.6.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 2.0.0

System:

   NodeJS : v18.15.0 (/home/***/.nvm/versions/node/v18.15.0/bin/node)
   npm    : 9.5.0
   OS     : Linux 5.15

**Comment by liamdebeasi** [comment] 2024-01-25 14:08
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/23454.

**Closed by liamdebeasi** 2024-01-25 14:08 UTC
Labels: triage
