### ISSUE TITLE
Need to click ion-button two times to trigger the click event 

### ISSUE THREAD

**Issue by achakra21** [ionic-team/ionic-framework#23310] opened 2021-05-17 14:59 UTC
# Bug Report

**Ionic version:**
5.4.16

**Current behavior:**
I have to click two times to trigger the click event of an ion-button code chunk below

**Expected behavior:**
It should trigger the (click) saveMessage()  function

**Steps to reproduce:**
open the keyboard by focusing on ion-textarea and press save when keyboard. is up press the `save` button the saveMessge() method wont fireup

**Related code:**

```
<div class="msgContainer">
    <div class="defaultFont ion-padding-bottom"><b> Instructions:</b></div>
    <div class="inputContainer">
      <div class="login-input">


        <ion-textarea (ionBlur)="checkBlur(true)" (ionFocus)="checkFocous(false)" [(ngModel)]="item"></ion-textarea>


      </div>
      <ion-button tappable color="primary"  (click)='saveMessage(item)'>Save</ion-button>
    </div>
    <ion-list class="listClass" *ngIf="!isBlur">
      <ion-item>dummy test1</ion-item>
      <ion-item>dummy test2</ion-item>
      <ion-item>dummy test3</ion-item>

    </ion-list>
  </div>





```

**Comment by liamdebeasi** [comment] 2021-05-17 15:33
Thanks for the issue. Can you reproduce this in an Ionic starter app and provide a link to the repo?

**Comment by achakra21** [comment] 2021-05-18 14:28
When I removed `(ionBlur)="checkBlur(true)" (ionFocus)="checkFocous(false)"`

It worked I was using `ionBlur` and `ionFocus` for detecting keypad is on or not , now I am getting that using `Capacitor` `Keyboard` Plug-in

**Comment by liamdebeasi** [comment] 2021-05-19 12:43
Glad the issue is resolved! I am going to close this issue.

**Closed by liamdebeasi** 2021-05-19 12:43 UTC
Labels: ionitron: needs reproduction
