### ISSUE TITLE
bug: Ion Select, attribute : interface popover same choice displayed multiple times

### ISSUE THREAD

**Issue by raclettedesavoie** [ionic-team/ionic-framework#29544] opened 2024-05-23 06:14 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/docs/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

I have a bug with interface popover on the Ion-Select 
![image](https://github.com/ionic-team/ionic-framework/assets/78375181/6fe049c6-95cc-488c-a13a-36c78d044acb)
it displays twice the same select-option

The bug is only present with interface: popover
![image](https://github.com/ionic-team/ionic-framework/assets/78375181/a12938eb-b89f-4ed4-a673-753592da31bb)

### Expected Behavior

Not display the same select-option twice

### Steps to Reproduce

I tried with Ion-select documentation

### Code Reproduction URL

/

### Ionic Info

PS C:\Users\00190971\Documents\pairdriver-ui\mobile> ionic info  
[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package.json'

       Require stack:
       - C:\Users\00190971\AppData\Roaming\npm\node_modules\@ionic\cli\lib\project\index.js
       - C:\Users\00190971\AppData\Roaming\npm\node_modules\@ionic\cli\lib\index.js
       - C:\Users\00190971\AppData\Roaming\npm\node_modules\@ionic\cli\index.js
       - C:\Users\00190971\AppData\Roaming\npm\node_modules\@ionic\cli\bin\ionic

Ionic:

   Ionic CLI       : 7.2.0 (C:\Users\00190971\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/vue 8.1.2

Capacitor:

   Capacitor CLI      : 6.0.0
   @capacitor/android : 6.0.0
   @capacitor/core    : 6.0.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 2.0.1

System:

   NodeJS : v20.12.2 (C:\Program Files\nodejs\node.exe)
   npm    : 10.5.0
   OS     : Windows 10

**Comment by brandyscarney** [comment] 2024-05-28 21:05
I am not able to reproduce this using the Ionic Select documentation. A minimal reproduction is required for us to investigate this further. You can open the [select demo](https://ionicframework.com/docs/api/select#popover) in StackBlitz (the lightning bolt icon in the top right), fork it to add code that reproduces the problem, and then share the URL with us. Thank you!

**Comment by thetaPC** [comment] 2024-06-11 19:56
Closing this issue due to the lack of a minimal reproduction. Please feel free to open another issue with a repro if you are still having the bug.

**Closed by thetaPC** 2024-06-11 19:56 UTC
Labels: ionitron: needs reproduction
