### ISSUE TITLE
bug: Angular 17 and Ionic 7 - SSR issue

### ISSUE THREAD

**Issue by papastepano** [ionic-team/ionic-framework#29179] opened 2024-03-19 09:41 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Adding ionic to an Angular standalone app results in the following warning:
```
▲ [WARNING] The glob pattern import("./**/*.entry.js*") did not match any files [empty-glob]                                                          

    node_modules/@stencil/core/internal/client/index.js:4019:4:
      4019 │     `./${bundleId}.entry.js${BUILD.hotModuleReplacement && hmrVe...
           ╵     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
As a result components cannot be properly hydrated:
```
error-handler.service.ts:11 Error: NG0500: During hydration Angular expected <ion-toolbar> but found a comment node.

Angular expected this DOM:

<ion-header _ngcontent-ng-c3536642561="">
  <ion-toolbar>…</ion-toolbar>  <-- AT THIS LOCATION
  …
</ion-header>

Actual DOM is:

<ion-header _ngcontent-ng-c3536642561="">
  <!--  -->  <-- AT THIS LOCATION
  …
</ion-header>
```

### Expected Behavior

I am expecting Ionic to support SSR in Angular

### Steps to Reproduce

1. create a an angular app with ssr using cli
2. add ionic and any ion component from package standalone
3. serve the app

### Code Reproduction URL

https://github.com/

### Ionic Info

   Angular: 17.2.4
   Ionic CLI : 7.2.0
   NodeJS : v20.11.0
   npm    : 10.4.0

**Comment by liamdebeasi** [comment] 2024-03-19 13:06
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/28625#issuecomment-1843919548.

**Closed by liamdebeasi** 2024-03-19 13:06 UTC
Labels: triage

**Comment by papastepano** [comment] 2024-03-23 10:11
@liamdebeasi there is no clear resolution in the issue you are pointing to. Can you please provide some more information ?

**Comment by papastepano** [comment] 2024-03-24 18:45
https://github.com/ionic-team/stencil/issues/5427

**Comment by Lyfei** [comment] 2024-04-19 02:20
> [ionic-team/stencil#5427](https://github.com/ionic-team/stencil/issues/5427)

Looks like the problem hasn't been solved yet
