### ISSUE TITLE
feat/bug: Option to create modal in different parents other than the app root.

### ISSUE THREAD

**Issue by conde2** [ionic-team/ionic-framework#23250] opened 2021-05-01 01:09 UTC
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**
Option to create modal in different parents other than the app root.

**Describe Preferred Solution**
Pass the parent element where the modal will be appended when created, making possible to use different router outlets and components as parent.
 
```ts
    private routerOutlet: IonRouterOutlet,

      await this.modalController.create({
        component: ModalPage,
        swipeToClose: true,
        parentElement: this.routerOutlet.nativeEl
      });

```

I would like suggestion of workaround while this is not implmented.

**Describe Alternatives**
Make possible to pass an parentId to the modal options telling where the modal element should be appended

**Related Code**

https://github.com/ionic-team/ionic-framework/blob/master/core/src/utils/overlays.ts#L58

**Additional Context**

My use case is that I'm using a service inside a modal, but this service is injected by other component. This other compoenent has a button that is create the modal. When the modal is create, it throws errors because the Dependecy Injector cannot access the service, from the component where it was injected.

This issue is similar to this:
https://github.com/ionic-team/ionic-framework/issues/22689

https://forum.ionicframework.com/t/modal-inside-a-div-specifying-parent-element-for-a-modal/5799

**Comment by DwieDima** [comment] 2021-05-01 14:52
you can append modals to any parent of type HTMLElement (also router-outlets and components) by doing this:

```
// add an id to ion-router-outlet
<ion-router-outlet id="root-router"></ion-router-outlet>
```
```
// get an HTMLElement usign the id
document.getElementById('#root-router')
```

complete example:

```
openModal() {
      const parent = document.getElementById('#root-router');

      const modal = await this.modalController.create({
        component: ModalPage,
        swipeToClose: true,
        parentElement: parent
      });

    return modal.present();
}
```

**Comment by conde2** [comment] 2021-05-01 14:54
I tried that and it does not work, also in documentation it says that parentElement is only for ios mode, while I'm using md in some cases.

**Comment by liamdebeasi** [comment] 2021-05-03 15:15
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/22689 (the feature here mentions `ion-loading` but both loading and modal use the same overlay code)

**Closed by liamdebeasi** 2021-05-03 15:15 UTC
Labels: triage
