### ISSUE TITLE
bug: Angular standalone ionRadio [disabled]="undefined" leads to broken radios/group

### ISSUE THREAD

**Issue by KillerCodeMonkey** [ionic-team/ionic-framework#28571] opened 2023-11-22 14:40 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

IonRadio functionality breaks when `[disabled]="undefined"` is set when used as Angular standalone component.

### Expected Behavior

They are working like non-standalone components.

### Steps to Reproduce

1. Create empty ionic angular project
2. transform it to standalone
3. add IonRadioGroup + IonRadios to the App component template
4. pass `undefined` as disabled value -> in our real life app we have those `<ion-radio>`s defined in a `@for`, because they are dynamic configured
5. undefined is an allowed value, but breaks the complete radio button functionality in standalone angular components

### Code Reproduction URL

https://github.com/KillerCodeMonkey/ionic7-angular-standalone-radio-disabled-bug

### Ionic Info

```sh
Ionic:

   @angular-devkit/build-angular : 17.0.3
   @angular-devkit/schematics    : 17.0.3
   @angular/cli                  : 17.0.3
   @ionic/angular-toolkit        : 9.0.0
   @ionic/angular"               : 7.5.6

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v18.14.0 (/home/xxx/.volta/tools/image/node/18.14.0/bin/node)
   npm    : 9.3.1
   OS     : Linux 6.5
```

### Additional Information

My Idea: the proxyInput wrapper of the standalone components is overriding the "stencil" components defaults for the defined "InputProps".
https://github.com/ionic-team/ionic-framework/blob/main/packages/angular/standalone/src/directives/angular-component-lib/utils.ts#L5

Sadly i currently have no time to really investigate and fix it.
But i guess this problem is not limited to the radio-component or the disabled input.

**Comment by liamdebeasi** [comment] 2023-11-22 15:18
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. According to [the radio docs](https://ionicframework.com/docs/api/radio#disabled) setting `disabled` to `undefined` is not correct usage. This property only accepts boolean values.

The reason for the difference in behavior is that with the IonicModule approach setting `[disabled]="undefined"` was not actually overriding the property's default value of `false`. However, if you manually set the property to `undefined` in Dev Tools you'll see that the same behavior reproduces there. In the Angular standalone approach we use a different build of Stencil which does allow `[disabled]="undefined"` to override the default value of `false`.

> My Idea: the proxyInput wrapper of the standalone components is overriding the "stencil" components defaults for the defined "InputProps".

This does not appear related because the behavior reproduces in v7.5.0 which was before this change shipped.

Setting `disabled` to an accepted value (`true` or `false`) should resolve the issue.

**Closed by liamdebeasi** 2023-11-22 15:18 UTC
Labels: triage

**Comment by KillerCodeMonkey** [comment] 2023-11-22 15:52
alrighty :) thanks for the fast answer. we sure already fallback to `false`, but it was quite confusing because worked before the transition of our project to standalone components.
