### ISSUE TITLE
bug: ionic-vue, exceptions when navigating from dynamic to static route

### ISSUE THREAD

**Issue by khalo-sa** [ionic-team/ionic-framework#23369] opened 2021-05-26 14:48 UTC
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
Navigating from a route with url parameter "/step/:id" to a static route "/home" works, but throws exceptions. The exceptions seem to indicate that after navigating to the new route the component of the route one is coming from is tried to be rendered:
![image](https://user-images.githubusercontent.com/14795990/119681204-24d52700-be42-11eb-922f-2455b5fe6324.png)

**Expected behavior:**
No exceptions to be thrown.

**Steps to reproduce:** / **Related code:**
I created an example repo here: https://github.com/khalo-sa/ionic-vue-router-issue
When the app is runnning, On the root view click the button "start". Then click the "back" button and watch the console for the exceptions.

**Other information:**
I also noticed the missing transition animations when navigating between views of the same dynamically rendered component. This seems to be this issue: https://github.com/ionic-team/ionic-framework/issues/22662

**Ionic info:**
```
Ionic:

   Ionic CLI       : 6.16.1 (/opt/homebrew/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 5.6.6

Capacitor:

   Capacitor CLI      : 2.4.7
   @capacitor/android : not installed
   @capacitor/core    : 2.4.7
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v16.1.0 (/opt/homebrew/Cellar/node/16.1.0/bin/node)
   npm    : 7.11.2
   OS     : macOS Big Sur```

**Comment by liamdebeasi** [comment] 2021-05-26 15:44
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The problem here is that your template is trying to access a property inside of `step`, but `step` is undefined when you are leaving the page. 

You are watching `route.params.id`, so when you navigate away from `/step/step1`, `route.params.id` becomes undefined. In your callback, since `newId` is `undefined`, you are assigning `step.value` to be equal to `steps[undefined]` which itself is `undefined`.

**Closed by liamdebeasi** 2021-05-26 15:44 UTC
Labels: triage

**Comment by khalo-sa** [comment] 2021-05-26 17:46
Hey @liamdebeasi , thank you for your answer. However, I am not convinced.
I created a second almost identical project: https://github.com/khalo-sa/vue-router-demo
The only difference is that I am not using ionic, but only vue3 with vue-router v4... and the exceptions when navigating back to /home are gone!
And I feel this is what one should except: If I leave a route and corresponding view/component, why should I bother about what is watched on the *old* view?

**Comment by liamdebeasi** [comment] 2021-05-26 18:46
The difference is that in Ionic Vue we transition away the component before removing the old component from the DOM. Even though the URL has changed, the old component is still in the DOM while the animation completes. As a result, the template will re-render resulting in the error you are seeing.

In a regular Vue app with Vue Router, there is no transition as the component is immediately removed from the DOM. While your `watch` callback does fire again, the template does not need to re-render since it was already removed from the DOM. This avoids the error you are noting in this thread.

This is not really a bug as much as it is an implementation difference due to the fact that we have page transitions, so we need to keep the leaving component in the DOM for a bit longer.
