### ISSUE TITLE
Unable to style day-of-month buttons in ion-datetime compeonent

### ISSUE THREAD

**Issue by joshgarwood** [ionic-team/ionic-framework#25794] opened 2022-08-22 01:46 UTC
**I'm submitting a ...** 
[x ] bug report
[ ] feature request

**Current behavior:**
The "day of month" buttons on the ion-datetime component do not use the --ion-font-family variable.  The rest of the component correctly uses this variable, but the .calendar-day buttons do not.  I have also tried to apply custom styles to these elements with no luck; they seem to be buried in the shadow DOM with now "part" attribute.

**Expected behavior:**
The .calendar-day buttons should properly use the --ion-font-family variable.  Or, at least be capable of being styled.  

**Steps to reproduce:**
1. Create a new project or open an existing one.
2. In the variables.scss file, set the --ion-font-family variable to something non-generic
3. In a new or existing component, add an ion-datetime component
4. Notice that the Heading, Month name, and even the days of the week column headers (M,T,W,Th,F,S,S) use the --ion-font-family variable, but numbers for the month (with class .calendar-day) do not.

**Related code:**

Please see this StackBlitz example here: https://stackblitz.com/edit/ionic6-angular13-knwhsr?file=src/app/app.component.css

**Ionic info:** 

```
Ionic CLI : 6.20.1 (/usr/local/lib/node_modules/@ionic/cli)
Ionic Framework : @ionic/angular 6.2.1
@angular-devkit/build-angular : 14.1.1
@angular-devkit/schematics : 14.1.1
@angular/cli : 14.1.1
@ionic/angular-toolkit : 6.1.0
```

**Comment by liamdebeasi** [comment] 2022-08-22 15:13
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/25340.

**Closed by liamdebeasi** 2022-08-22 15:13 UTC
Labels: triage
