### ISSUE TITLE
bug: <ion-input> in readonly mode does not prevent keyboard's accessory bar to show and prevent use of (click)

### ISSUE THREAD

**Issue by bryplano** [ionic-team/ionic-framework#18155] opened 2019-04-26 19:57 UTC
# Bug Report

**Ionic version:**

[x] **4.2.X and 4.3.0**

**Current behavior:**

This issue appears to be identical to the v3 issue here: https://github.com/ionic-team/ionic-v3/issues/244

Summary for my v4 app:

I want to prevent the keyboard showing on an `ion-input` in order to show a native picker (in this case using `cordova-plugin-datepicker`). 

I use `readonly` and pass a callback function in the `(click)` attribute, but the accessoryView is shown on iOS with the first tap, and the second tap displays the picker behind the accessoryView.

**Expected behavior:**

The `datepicker` should show without the accessory bar popping up first / requiring extra taps.

**Steps to reproduce:**

Follow the steps on the README for the sample app below to reproduce.

- Exhibited on a physical iPhone XS Max running iOS 12.3b3

- Also exhibited on the iPhone 8, iOS 12.2 simulator

**Related code:**

[Sample App on Github](https://github.com/bryplano/DatePickerIonInputTest)

*[src/page/home/home.page.html](https://github.com/bryplano/DatePickerIonInputTest/blob/master/src/app/home/home.page.html)*
```
<ion-content>

  <ion-item lines="inset" (click)="chooseDate($event)"> 
    <ion-label position="floating">Label</ion-label> 
    <ion-input placeholder="mm/dd/yyyy" type="text" readonly></ion-input> 
    <ion-icon class="cal-icon" name="calendar" slot="end"></ion-icon> 
  </ion-item>

</ion-content>
```

*[src/app/home/home.page.ts](https://github.com/bryplano/DatePickerIonInputTest/blob/master/src/app/home/home.page.ts)*
```
    this.datePicker.show({
      date: this.currentDate,
      maxDate: this.currentDate,
      mode: 'date',
      androidTheme: this.datePicker.ANDROID_THEMES.THEME_HOLO_LIGHT,
      allowFutureDates: false
    });
```

**Other information:**

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.3.0
   @angular-devkit/build-angular : 0.13.8
   @angular-devkit/schematics    : 7.3.8
   @angular/cli                  : 7.3.8
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   cordova (Cordova CLI) : 9.0.3 (cordova-lib@9.0.2)
   Cordova Platforms     : ios 5.0.1
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 5 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/user/Library/Android/sdk)
   ios-deploy        : 2.0.0
   ios-sim           : 8.0.1
   NodeJS            : v10.15.3 (/usr/local/bin/node)
   npm               : 6.9.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.2.1 Build version 10E1001
```

**Comment by muntaqeem-bs23** [comment] 2019-08-30 06:09
Set the input's pointer event to none.

`<ion-input placeholder="mm/dd/yyyy" type="text" readonly style="pointer-events:none"></ion-input>`

did the trick for me.

**Comment by nickwinger** [comment] 2020-02-28 16:02
i have the same problem. You can still select an ion-input with a mouse click even if it has readonly or [readonly]="true"

**Comment by liamdebeasi** [comment] 2020-12-07 22:02
Thanks for the issue. This problem appears to be due to a bug in WebKit. The good news is that this issue was resolved in iOS 13 as I can only reproduce this on devices running iOS 12 and older.

I am going to close this issue as a fix for the underlying WebKit bug has shipped in newer versions of iOS.

**Closed by liamdebeasi** 2020-12-07 22:02 UTC
Labels: triage
