### ISSUE TITLE
bug: ion-item > inputs are all disabled if a child of ion-item is

### ISSUE THREAD

**Issue by me-to-you93** [ionic-team/ionic-framework#24291] opened 2021-12-01 09:55 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

Let's pretend a ion-item have some input childs like ion-checkbox or ion-input. If one of the child input is [disabled]="true", the whole ion-item is disabled too.

### Expected Behavior

Disabling one child should not propagate to other children

### Steps to Reproduce

Just have a ion-item with some disabled child inputs and some not.

Ionic:

   Ionic CLI                     : 5.4.16 (C:\Users\gmartin\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 5.9.1
   @angular-devkit/build-angular : 12.2.4
   @angular-devkit/schematics    : 12.2.4
   @angular/cli                  : 12.2.4
   @ionic/angular-toolkit        : 4.0.0

Cordova:

   Cordova CLI       : 10.0.0 (cordova-lib@10.1.0)
   Cordova Platforms : not available
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 18 other plugins)

Utility:

   cordova-res : 0.15.3
   native-run  : 1.5.0

System:

   Android SDK Tools : 26.1.1 (C:\Users\gmartin\AppData\Local\Android\Sdk)
   NodeJS            : v16.13.0 (C:\Program Files\nodejs\node.exe)
   npm               : 8.1.0
   OS                : Windows 10

### Additional Information

Therefore this was already fixed in this issue : https://github.com/ionic-team/ionic-framework/issues/18670
 and should be available since 4.6.1

**Comment by amandaesmith3** [comment] 2021-12-01 14:36
Thanks for the report, I'm able to reproduce. Looks like there's been a regression since https://github.com/ionic-team/ionic-framework/pull/18696; the extra inputs look interactable, but nothing happens when clicking them.

**Comment by me-to-you93** [comment] 2021-12-06 08:38
Hello, any feedback on this ?
My release is stuck with this :(
Thank you

**Comment by amandaesmith3** [comment] 2021-12-15 22:37
@me-to-you93 Could you try this dev build and let me know if it resolves the issue on your end? `npm install @ionic/angular@6.1.0-dev.202112152233.e254a3a`

It looks like the problem was actually a different bug entirely (see https://github.com/ionic-team/ionic-framework/pull/24423 for details), and while things look good on my end with the new fix, it would be very helpful if you could verify as well. If you're still running into problems, could you create a starter app reproducing the bug and post a link to the repo?

**Comment by amandaesmith3** [comment] 2021-12-16 18:10
@me-to-you93 In the interest of time, since much of our team will be out for the holidays soon, I've gone ahead and merged https://github.com/ionic-team/ionic-framework/pull/24423 and am closing this issue. The fix will be available in a future release of Ionic. In the meantime, a workaround would be to wrap the `ion-radio` in an `ion-radio-group`, even if it's the only radio in the group.

If this doesn't solve your problem, could you open a separate issue with a link to a repo that reproduces the bug? Thanks!

**Closed by amandaesmith3** 2021-12-16 18:10 UTC
Labels: needs: reply, package: core, type: bug

**Comment by me-to-you93** [comment] 2021-12-27 09:26
Hello,

I tried but the fix seems to be in Ionic 6 whereas I'm in Ionic 5 so I can't test it.
Also you talk about radio button but my case was with input controls.

The workaround doesn't work neither.

**Comment by me-to-you93** [comment] 2021-12-29 21:40
After temporary migrating to Ionic 6, I can finally confirm this fix solves my case.
Will it be available for Ionic 5 too ?

Thank you

**Comment by amandaesmith3** [comment] 2022-01-04 19:45
Could you try updating to the latest Ionic 5 version (5.9.3) and let me know if that fixes it? If not, could you reproduce the issue in an Ionic starter app and post a link to the repo here? I'm unable to reproduce the issue in Ionic 5 using only `ion-input`.

**Comment by me-to-you93** [comment] 2022-01-05 09:30
I'ma already in 5.9.3 and it doesn't fixes it. I was not able to reproduce with a starter app, don't know why.
I finally found a workaround, but i can confirm the bug is still present in 5.9.3, and fixed in 6.1.0.dev while also broken in 6.0.1

**Comment by amandaesmith3** [comment] 2022-01-05 14:29
We need a reproduction in order to confirm the bug is with Ionic and troubleshoot it. I'm going to leave this issue closed for now, but let me know if you're able to reproduce in a starter app.
