### ISSUE TITLE
bug: IonDateTime internal state breaks if navigating out of range

### ISSUE THREAD

**Issue by janrg** [ionic-team/ionic-framework#23939] opened 2021-09-15 17:36 UTC
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

In the new `IonDateTime` component, if I navigate to a month that is outside of the range given by min and max or to a month that is partially outside of the range while the last selected day would be out of range in this month, `onIonChange` is triggered with a broken internal state that cannot be recovered. The returned value changes to something like `2022-01-15T19:aN:00-aN:aN`. Selecting a valid date afterwards does not fix this and the time component remains in this broken state.

Tested in ionic react 6.0.0-beta.5

### Expected Behavior

onIonChange should not be triggered and the internal state of the component should not break

### Steps to Reproduce

`<IonDatetime min='2021-09' max='2021-10' onIonChange={(event) => {console.log(event.detail.value)}} />`

Use the arrows to navigate to August or November. Observe console output.

**Comment by janrg** [comment] 2021-09-15 19:31
Oh wow, that was incredibly quick. Thank you :-)

**Comment by liamdebeasi** [comment] 2021-09-15 19:42
Thanks for the issue. I put up a PR in #23940 and have included a dev build below if you are interested in testing it in your app:

```
npm install @ionic/react@6.0.0-dev.202109151938.3cfb72d @ionic/react-router@6.0.0-dev.202109151938.3cfb72d
```

**Comment by janrg** [comment] 2021-09-15 20:01
I have tested it and it looks like it works, thanks!
BTW: sorry this is a bit off-topic but is it intended that (at least in the browser) the time can only be changed by arrow up and down and not by typing into it?

**Comment by liamdebeasi** [comment] 2021-09-15 20:11
Glad the issue is resolved!

Currently you cannot type into the time container, but we are adding that soon!

**Comment by liamdebeasi** [comment] 2021-09-16 14:44
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/23940, and a fix will be available in an upcoming release of the Ionic v6 beta.

**Closed by liamdebeasi** 2021-09-16 14:44 UTC
Labels: package: core, type: bug
