### ISSUE TITLE
bug: ion-datetime bug

### ISSUE THREAD

**Issue by rraammiinn** [ionic-team/ionic-framework#29725] opened 2024-07-21 05:55 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/docs/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v8.x

### Current Behavior

I updated my ionic to the latest version ( 8.2.5 ) and ion-datetime with locale='fa-ir' still has that bug.

### Expected Behavior

...

### Steps to Reproduce

...

### Code Reproduction URL

https://github.com/ionic-team/ionic-framework

### Ionic Info

framework : vue
version : 8.2.5

**Comment by sean-perkins** [comment] 2024-07-22 18:23
@rraammiinn this will be your final warning. 

You opened: https://github.com/ionic-team/ionic-framework/issues/29682 and I closed the issue instructing you to provide an issue that was filled out and with a reproduction. 

You opened https://github.com/ionic-team/ionic-framework/issues/29694 without a reproduction. You need to provide **code** for the team to know what your configuration looks like to be able to reproduce and understand your problem and then prioritize a fix. 

I am going to close this issue. You may update #29694. Future tickets around this issue with a complete disregard for my feedback and the time of the maintainers of this project will result in either a suspension or ban from the community. 

Thank you.

**Closed by sean-perkins** 2024-07-22 18:23 UTC
Labels: triage
