### ISSUE TITLE
Cant Print all Pages using window.print in Latest Ionic

### ISSUE THREAD

**Issue by palone12** [ionic-team/ionic-framework#29294] opened 2024-04-08 05:30 UTC
@media print {
  ion-header,
  ion-tab-bar,
  ion-footer,
  .breadcrumb_trail,
  .nav-menu {
    display: none;
  }
  body,
  .app-root,
  .split-pane,
  .ion-page,
  ion-app,
  ion-nav {
    contain: none;
  }
  body,
  ion-nav {
    overflow: initial;
  }

  body {
    position: static;
    overflow: visible;
  }

  .publication__content {
    overflow-y: visible !important;
    position: relative;
  }
}

**Comment by liamdebeasi** [comment] 2024-04-08 13:46
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/19886.

**Closed by liamdebeasi** 2024-04-08 13:46 UTC
Labels: triage

**Comment by palone12** [comment] 2024-04-24 09:16
You Closed it but it isn't the solution for ionic - angular application . Take a close look before closing it .
<div class="publication__content" *ngIf="!isTableOfContents && isLoaded">
      <app-publication-page
        id="publicationContent"
        class="content"
        [title]="title"
        [titleClass]="titleClass"
        [content]="displayContent"
        (swipeleft)="swipe('left')"
        (swiperight)="swipe('right')"
        (tap)="tap($event)"
      ></app-publication-page>
    </div>
    
    my scroll content is present inside the div , and on window.print () it takes only height of the viewport , please look at this , it is a problem with ionic, make it less accessible to people who want the information in printed form.

**Comment by liamdebeasi** [comment] 2024-04-25 13:56
I was linking to the feature request for the behavior you are requesting, not a proposed solution. The requested behavior does not exist in Ionic Framework at the moment.
