### ISSUE TITLE
bug: disable content scrolling on ion-item-sliding slide event

### ISSUE THREAD

**Issue by MeMeMax** [ionic-team/ionic-framework#24640] opened 2022-01-24 17:10 UTC
Hi, I got the exact same issue like in this issue. A comment states that it was resolved but in version 6 it is still present.

Disable content scrolling if ion-item-sliding slide-event is in motion.

Ionic version:

[x] 6.0.0

Describe the Feature Request
Disable the content scrolling while sliding an ion-item-sliding, so it feels more natural. iOS Mail app can not scroll vertically while sliding.

Describe Preferred Solution
Scrolling is not possible while sliding. e.g. iOS Mail.

Additional Context

scrollmove

> Thanks for the issue. This has been resolved in Ionic Framework v5.6.14.
> 
> _Originally posted by @liamdebeasi in https://github.com/ionic-team/ionic-framework/issues/18219#issuecomment-902234775_

**Comment by sean-perkins** [comment] 2022-01-24 20:46
Hello @MeMeMax thanks for reporting this issue! Can you please help me by creating a reproduction of the issue? This will help both in debugging the issue and help when verifying the resolution.

**Comment by MeMeMax** [comment] 2022-01-25 05:37
@sean-perkins this is my markup
`<ion-list *ngIf="(merchantList | keyvalue)?.length && !loading" #slidingList>
    <div *ngFor="let merchant of merchantList | keyvalue;trackBy:identifyMerchants">
      <ion-item-divider>
        <ion-label>{{merchant.key}}</ion-label>
      </ion-item-divider>

      <ion-item-sliding *ngFor="let publicCoupon of merchant.value;trackBy:identifyPublicCoupon">
        <ion-item>
          <ion-reorder slot="start"></ion-reorder>
          <ion-label>
            <h2>{{publicCoupon.couponValue}}{{publicCoupon.couponType | couponType}} {{publicCoupon.couponClassOfGoods}}</h2>
            <h5 class="subheader">
              <div>Bis {{publicCoupon.validUntil | date:'dd.MM.YYYY'}}</div>
              <div>Nummer: *{{publicCoupon.barcodeNumber | slice:-5}}</div>
            </h5>
          </ion-label>
        </ion-item>
        <ion-item-options side="end">
          <ion-item-option (click)="add(publicCoupon)" color="primary">Zur Wallet</ion-item-option>
        </ion-item-options>
      </ion-item-sliding>
    </div>
  </ion-list>`

I guess you can only reproduce it on a real ios device. I am using an Iphone 12 Pro. I created a short video from my device for you.
![trim 7280F48C-929E-40D2-BCC7-94AD04DA65D5](https://user-images.githubusercontent.com/6450415/150917500-d5d902ee-0796-440e-8454-bded5554e5e2.gif)

Is that enough information?

**Comment by sean-perkins** [comment] 2022-01-25 22:15
@MeMeMax I'll still require a code reproduction to verify your issue.

With the code snippet (minus your app specific code), I'm unable to replicate the issue on device:
- https://github.com/sean-perkins/gh-24640-item-sliding
- `npm run start -- --host=0.0.0.0`
- Open on local network IP on device

<video src="https://user-images.githubusercontent.com/13732623/151068778-9ef5d3b0-897d-46c7-8816-f65efc6204c1.mp4"></video>

**Comment by MeMeMax** [comment] 2022-01-26 06:05
@sean-perkins thanks for taking the effort to try it out and sorry for the inconvenience. Here is a repository for you which should reproduce it:
https://github.com/MeMeMax/gh-24640-item-sliding

I see two differences to your implementation:
1. your list is larger than the visible content
2. You don´t have tabs in your app

I can´t say whether it only happens in a real ios deployment but my reproduction app should behave like the one in my video.

**Comment by sean-perkins** [comment] 2022-01-26 21:44
@MeMeMax thanks for the reproduction! I'm unfortunately still unable to replicate the issue, in both the mobile browser of the app, as well as running on device through Capacitor. 

We may be looking at a specific device or OS bug. Can you provide what device and OS version your device is running on? 

For reference, these are my specs:
- iPhone Xs Max (iOS 15.2.1)

**Comment by MeMeMax** [comment] 2022-01-27 06:25
Thanks for testing this. I have tested the following specs:

- iPhone 12 Pro (iOS 15.1.1)
- iPhone 12 Pro (iOS 15.3)

What I wonder about: In my reproduction there is always a scrollbar showing when I open it in dev mode on my browser. Even though the content is not larger than the Browser height. Is that as expected?

**Comment by MeMeMax** [comment] 2022-02-09 11:25
I just tested my App on a iPhone 8 with 15.2.1 and I have the same behavior.

Any clue why this happens?

**Comment by liamdebeasi** [comment] 2022-02-28 21:38
Hey there,

I tested this on the following devices and was unable to reproduce the issue:

- iPhone 13 running iOS 15.4 (beta)
- iPhone 7 running iOS 14.8
- iPhone 11 running iOS 15.2.1

I tested in both mobile Safari and in Capacitor.

Are you able to provide any additional information that could help us reproduce this issue? Otherwise we can close the issue for now and re-open if we are able to reproduce it.

**Comment by MeMeMax** [comment] 2022-03-01 05:09
Hi, I digged deeper into my structure and found that I have two nested ion-content elements with an router outlet. This caused this issue. So the structure was like this:

```
<ion-content>
      <router-outlet>
            <ion-content>
            </ion-content>
      <router-outlet>
</ion-content>
```

And I had to add '[scrollY]="false"' to the first ion-content:
```
<ion-content [scrollY]="false">
      <router-outlet>
            <ion-content>
            </ion-content>
      <router-outlet>
</ion-content>
```

Thanks for your patience. This can be closed then.

**Closed** 2022-03-01 13:21 UTC
Labels: triage
