### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by kevinclarkadstech** [ionic-team/ionic-framework#23252] opened 2021-05-01 04:42 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

When I use navContext.navigate(), before it renders the new page for some reason it re-renders the current page.  This page has a very large list of items so this is suboptimal.  Also it re-renders on Back button clicked, which is more understandable.  I expect it to be more like IonModal which can be displayed and closed without having any re-renders of the parent page.

**Expected behavior:**

It should navigate to the new page and render that page.  When clicking Back, it should preferably just have the last page in memory so it doesn't need to re-render.

**Steps to reproduce:**

Create a base Ionic React project.  Add a console.log to the first line inside your ion page functional component, which logs every render.  Additionally, create a list of items that also log to the console. Navigate from one page to another and when you click the link/button, you will see all the list components re-render and then it will navigate and render the next page.  When you click the Back button you will see the entire list render again.

I can set the array to [] right before calling the navContext.navigate, but the problem with this, is when navigating back, it will start the user at the top of the list again.  I would have to maintain the scroll position.  This would involve setting onIonScroll, but this causes its own issues, because that causes the content to "jump" when items are prepended to the list.

Having a modal that is inside one of the child list components will allow a show without re-rendering the entire page, but then has the issue of not being a hyperlink.

**Related code:**

```
insert short code snippets here
```

**Other information:**

Previous issue I found did not help me any: https://github.com/ionic-team/ionic-framework/issues/21635

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.13.0 (C:\Users\Kevin\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/react 5.5.2

Capacitor:

   Capacitor CLI   : 2.2.1
   @capacitor/core : 2.4.4

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.18.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.6
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment] 2021-05-03 15:14
Thanks for the issue. Can you reproduce this in an Ionic starter app and provide a link to the repo? I am unable to reproduce the issue using the info provided.

**Comment by kevinclarkadstech** [comment] 2021-05-12 21:05
Will get to this as soon as I can. Just FYI.

**Comment by liamdebeasi** [comment] 2021-05-28 13:55
Hey there! We typically close out issues without code reproductions after 2 weeks otherwise it makes it hard for us to stay on top of the different issues coming in. I am going to close this issue for now, but if you are able to make a reproduction feel free to reply with it here and I can re-open the issue (or you can open a new issue if you would prefer). Thanks!

**Closed by liamdebeasi** 2021-05-28 13:55 UTC
Labels: ionitron: needs reproduction
