### ISSUE TITLE
bug: item focus causes IonHeader and IonFooter to scroll up

### ISSUE THREAD

**Issue by csaar95** [ionic-team/ionic-framework#25504] opened 2022-06-20 09:56 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

If I am using multiple "tabs" on a single page, with a list of `IonItem`s and click an item on the second page, which isn't fully on the screen. Then `IonHeader` and `IonFooter` both move up, when the `IonItem` scrolls into focus.
![ion-action-sheet-test](https://user-images.githubusercontent.com/40690270/174574328-9e6e8e31-6262-4b92-8730-28f35ab8a242.gif)

This issue is a side effect of #25496, because I had to wrap my `IonCard`s into `IonItem`.

### Expected Behavior

Header and footer not moving up.

### Steps to Reproduce

1. Install code example
2. Switch to the second tab
3. Click on an item, which is only partially on the screen

### Code Reproduction URL

https://github.com/csaar95/ion-action-sheet-test

### Ionic Info

Ionic:

   Ionic CLI       : 6.18.1 (C:\Users\Christian\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/react 6.1.10

Capacitor:

   Capacitor CLI      : 3.6.0
   @capacitor/android : not installed
   @capacitor/core    : 3.6.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.6.0

System:

   NodeJS : v16.13.0 (C:\Program Files\nodejs\node.exe)
   npm    : 8.1.0
   OS     : Windows 10

### Additional Information

`IonCard` doesn't cause the error, because it's not moving into view.

**Comment by Julien-Marcou** [comment] 2022-06-21 07:52
You might be interested by #24499

**Comment by liamdebeasi** [comment] 2022-06-21 12:50
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/24499.

**Closed by liamdebeasi** 2022-06-21 12:50 UTC
Labels: triage
