### ISSUE TITLE
bug: Cannot read property 'emit' of undefined (ionStyle.emit)

### ISSUE THREAD

**Issue by ptchccnt2015** [ionic-team/ionic-framework#23546] opened 2021-07-01 08:38 UTC
![Screen Shot 2021-07-01 at 4 34 17 PM](https://user-images.githubusercontent.com/49133871/124093743-b7dd2e80-da8a-11eb-9317-e941048e803f.png)

Getting this error after upgrading to v6 Beta

Follow this correctly

https://github.com/ionic-team/ionic-framework/blob/next/BETA.md

**Comment by liamdebeasi** [comment] 2021-07-01 13:39
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/23539.

**Closed by liamdebeasi** 2021-07-01 13:39 UTC
Labels: triage
