### ISSUE TITLE
bug: Sheet Modal content should only begin scrolling once its at its maximum height

### ISSUE THREAD

**Issue by matthewgoodman13** [ionic-team/ionic-framework#24626] opened 2022-01-21 18:16 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Hi! I believe this issue is halfway between a bug and a feature for the new Sheet modals. It is also possible that I may be taking a wrong approach on this. 

**What I want:**
When you look at the Google Maps Bottom Sheet, you can notice that its content only scrolls once the modal is fully expanded. I would like this behavior.

Currently with Ionic's Sheet modals, if you add content that exceeds its height then add `overflow-y: scroll`, when you scroll on the modal, both the height and content scrolls simultaneously causing a buggy looking experience. For example, if the modal is at its 50% breakpoint and you begin expanding it to its maximum 100%, the gesture causes both the modal and content to scroll which seems quite unnatural when you see it. The content should stick to the top of the modal until its at its maximum, then begin scrolling afterwards.

### Expected Behavior

Content that exceeds the height of a Sheet modal should only begin scrolling once the sheet modal has been fully expanded.

### Steps to Reproduce

1) Create any Sheet Modal
2) Add enough content to it that it should exceed the viewports' height
3) Add overflow-y to modal
4) Scroll. (Buggy-looking scrolling will appear)

### Additional Information

I was thinking of possible solutions, and once events are emitted on breakpoints, this issue might be easier to tackle. There could be a scrolling class applied to the content that only is enabled if the modal is at its maximum position. (Any update with that feature? Can't wait to get my hands on it!)

Thanks!

**Comment by amandaesmith3** [comment] 2022-01-21 19:07
Thanks for the issue. I'm going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/24583; while the suggested fixes are a little different, it seems to be the same underlying behavior driving the report. I'm actively investigating that and should have a reply up there soon :eyes:

**Closed by amandaesmith3** 2022-01-21 19:07 UTC
Labels: triage
