### ISSUE TITLE
bug: fresh "blank" ionic app fails building for iOS on MBP M2Pro

### ISSUE THREAD

**Issue by caiusCitiriga** [ionic-team/ionic-framework#27630] opened 2023-06-11 16:38 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When trying to run a freshly created ionic application for iOS the build fails with the following error:

```
[capacitor] ✔ Copying web assets from www to ios/App/App/public in 281.81ms
[capacitor] ✔ Creating capacitor.config.json in ios/App/App in 392.04μs
[capacitor] [info] Inlining sourcemaps
[capacitor] ✔ copy ios in 312.03ms
[capacitor] ✔ Updating iOS plugins in 3.14ms
[capacitor] [info] Found 4 Capacitor plugins for ios:
[capacitor]        @capacitor/app@5.0.3
[capacitor]        @capacitor/haptics@5.0.4
[capacitor]        @capacitor/keyboard@5.0.4
[capacitor]        @capacitor/status-bar@5.0.4
[capacitor] [warn] Skipping pod install because CocoaPods is not installed
[capacitor] ✔ Updating iOS native dependencies with pod install in 773.83ms
[capacitor] ✔ update ios in 800.25ms
[capacitor] ✖ Running xcodebuild - failed!
[capacitor] [error] 2023-06-11 18:25:37.981 xcodebuild[20173:1348478] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled)
[capacitor]         Command line invocation:
[capacitor]         /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace App.xcworkspace -scheme App -configuration Debug -destination id=D0A3E0D0-8018-4DFC-AD81-52A557BB0E27 -derivedDataPath /Users/caiuscitiriga/Code/mxn/testApp/ios/DerivedData/D0A3E0D0-8018-4DFC-AD81-52A557BB0E27
[capacitor]
[capacitor]         User defaults from command line:
[capacitor]         IDEDerivedDataPathOverride = /Users/caiuscitiriga/Code/mxn/testApp/ios/DerivedData/D0A3E0D0-8018-4DFC-AD81-52A557BB0E27
[capacitor]         IDEPackageSupportUseBuiltinSCM = YES
[capacitor]
[capacitor]         --- xcodebuild: WARNING: Using the first of multiple matching destinations:
[capacitor]         { platform:iOS Simulator, id:D0A3E0D0-8018-4DFC-AD81-52A557BB0E27, OS:16.4, name:iPhone 14 }
[capacitor]         { platform:iOS Simulator, id:D0A3E0D0-8018-4DFC-AD81-52A557BB0E27, OS:16.4, name:iPhone 14 }
[capacitor]         Prepare packages
[capacitor]
[capacitor]         Computing target dependency graph and provisioning inputs
[capacitor]
[capacitor]         Create build description
[capacitor]         Build description signature: 029031e525b68e6191c7dc5e23a5830a
[capacitor]         Build description path: /Users/caiuscitiriga/Code/mxn/testApp/ios/DerivedData/D0A3E0D0-8018-4DFC-AD81-52A557BB0E27/Build/Intermediates.noindex/XCBuildData/029031e525b68e6191c7dc5e23a5830a.xcbuilddata
[capacitor]
[capacitor]         note: Building targets in dependency order
[capacitor]         /Users/caiuscitiriga/Code/mxn/testApp/ios/App/Pods/Target Support Files/Pods-App/Pods-App.debug.xcconfig:1:1: error: unable to open configuration settings file
[capacitor]         warning: Run script build phase '[CP] Embed Pods Frameworks' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'App' from project 'App')
[capacitor]         ** BUILD FAILED **
[capacitor]
[capacitor]
[ERROR] An error occurred while running subprocess capacitor.

        capacitor run ios --target D0A3E0D0-8018-4DFC-AD81-52A557BB0E27 exited with exit code
        1.

        Re-running this command with the --verbose flag may provide more information.
```

### Expected Behavior

I expect that the command: 

`ionic start testApp blank`

creates an app that can be run on an iOS simulator

### Steps to Reproduce

1. run `npm i -g @ionic/cli`
2. run `ionic start testApp blank`
3. run `cd testApp`
4. run `ionic capacitor add ios`
5. run `ionic capacitor copy ios`
6. run `ionic capacitor run ios` (selected iPhone 14 sim)
7: build throws error.

Also by trying to run: `ionic capacitor open ios` XCode opens a project with the Pods left sidebar item in red color, also any change made to the appId in the `capacitor.config.ts` does NOT reflect on XCode, even after re-running `ionic capacitor copy ios` and `ionic capacitor open ios`

![Screenshot 2023-06-11 at 18 35 00](https://github.com/ionic-team/ionic-framework/assets/12595721/b8bfb252-f938-439e-a3f8-f7bf81e78a31)

### Code Reproduction URL

https://github.com/caiusCitiriga/ionic7BlankAppBug

### Ionic Info

[WARN] Error loading @capacitor/android package.json: Error: Cannot find module '@capacitor/android/package.json'

       Require stack:
       - /Users/caiuscitiriga/.nvm/versions/node/v18.14.0/lib/node_modules/@ionic/cli/lib/project/index.js
       - /Users/caiuscitiriga/.nvm/versions/node/v18.14.0/lib/node_modules/@ionic/cli/lib/index.js
       - /Users/caiuscitiriga/.nvm/versions/node/v18.14.0/lib/node_modules/@ionic/cli/index.js
       - /Users/caiuscitiriga/.nvm/versions/node/v18.14.0/lib/node_modules/@ionic/cli/bin/ionic

Ionic:

   Ionic CLI                     : 7.1.1 (/Users/caiuscitiriga/.nvm/versions/node/v18.14.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.0.12
   @angular-devkit/build-angular : 16.0.5
   @angular-devkit/schematics    : 16.0.5
   @angular/cli                  : 16.0.5
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.0.5
   @capacitor/android : not installed
   @capacitor/core    : 5.0.5
   @capacitor/ios     : 5.0.5

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v18.14.0 (/Users/caiuscitiriga/.nvm/versions/node/v18.14.0/bin/node)
   npm    : 9.3.1
   OS     : macOS Unknown

### Additional Information

Hardware: MacBook Pro M2 Pro
OS: Ventura 13.4
XCode Version 14.3.1

**Comment by liamdebeasi** [comment] 2023-06-12 16:44
Thanks for the report. I am going to close this as this is not a bug in Ionic. The error logs note that this error is coming from the "capacitor" command which is handled by Capacitor, not Ionic Framework. I recommend looking at the [Capacitor iOS Troubleshooting](https://capacitorjs.com/docs/ios/troubleshooting) guide. Alternatively, you could post on the [Ionic Forum](https://forum.ionicframework.com/) for help with this. If after debugging you think you have found a Capacitor bug then you should file an issue on https://github.com/ionic-team/capacitor.

**Closed by liamdebeasi** 2023-06-12 16:44 UTC
Labels: triage

**Comment by caiusCitiriga** [comment] 2023-06-12 20:46
@liamdebeasi Thank you for your quick answer. Actually, I didn't think that this macbook was brand new and the Cocoapods were not installed 🙈

**Comment by caiusCitiriga** [comment] 2023-06-12 21:28
# Solved

I can confirm that installing CocoaPods solves the issue.
