### ISSUE TITLE
bug: tap click activates buttons without scrollEvents, but scrollEvents introduces perf issues

### ISSUE THREAD

**Issue by zrev2220** [ionic-team/ionic-framework#22030] opened 2020-09-04 21:17 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

When scrolling an `ion-list` with clickable `ion-item`s (`button="true"`), the item the user touches in order to scroll plays its "activated" style or animation (i.e. ripple effect on Android, darkened background on iOS). This happens _even if the user is not "clicking" on that item._

**Expected behavior:**

When scrolling the list, the touched item should not change in appearance (play the ripple effect or change the background). These styles should only activate when the user taps/clicks an item to __select__ it.

**Steps to reproduce:**

1. Create a basic Ionic app (`ionic start`)
2. Add an `ion-list` to one of the pages containing enough `ion-item`s to enable scrolling
3. Scroll the list with the app running in a mobile-ish environment (i.e. emulated touch enabled via devtools in a browser, or run on a physical device)

**Related code:**

StackBlitz: https://stackblitz.com/edit/ionic-list-ripple-bug

Snippet from Angular template:

```html
<ion-list>
  <ion-item *ngFor="let i of range(100)" button="true" detail="false">
    Item #{{i}}
  </ion-item>
</ion-list>
```

> The `range` function is defined as follows:
> 
> ```ts
> range(n) {
>   return Array.from(Array(n).keys());
> }
> ```

**Other information:**

This bug seems similar/identical to that identified in #15752. That issue references 7f38d377 as fixing the problem, but since I can reproduce it in a recent Ionic version, it seems to have reappeared(?).

**Ionic info:**

> _**Note:** I created the above StackBlitz example by forking https://stackblitz.com/edit/ionic-v4-angular-tabs. That codebase does not run as-is via `ionic serve` or `npm start`, and `ionic info` fails with an error:_
> 
> ```
> [WARN] You are not in an Ionic project directory. Project context may be missing.
> ```
> 
> _To at least provide_ some _useful `ionic info` output, I ran `ionic init` to make the directory an Ionic project. However, some Angular packages are still not installed (since StackBlitz magically makes things work), and the example may not be runnable locally without some additional installations and setup work._

```
[WARN] Error loading @ionic/angular-toolkit package.json: Error: Cannot find module '@ionic/angular-toolkit/package'

       Require stack:
       - <path to global node_modules>\@ionic\cli\lib\project\index.js
       - <path to global node_modules>\@ionic\cli\lib\index.js
       - <path to global node_modules>\@ionic\cli\index.js
       - <path to global node_modules>\@ionic\cli\bin\ionic
[WARN] Error loading @angular/cli package.json: Error: Cannot find module '@angular/cli/package'

       Require stack:
       - <path to global node_modules>\@ionic\cli\lib\project\index.js
       - <path to global node_modules>\@ionic\cli\lib\index.js
       - <path to global node_modules>\@ionic\cli\index.js
       - <path to global node_modules>\@ionic\cli\bin\ionic
[WARN] Error loading @angular-devkit/build-angular package.json: Error: Cannot find module
       '@angular-devkit/build-angular/package'

       Require stack:
       - <path to global node_modules>\@ionic\cli\lib\project\index.js
       - <path to global node_modules>\@ionic\cli\lib\index.js
       - <path to global node_modules>\@ionic\cli\index.js
       - <path to global node_modules>\@ionic\cli\bin\ionic

Ionic:

   Ionic CLI                     : 6.11.0
   Ionic Framework               : @ionic/angular 5.3.2
   @angular-devkit/build-angular : not installed
   @angular-devkit/schematics    : 10.1.0
   @angular/cli                  : not installed
   @ionic/angular-toolkit        : not installed

Utility:

   cordova-res : 0.15.1
   native-run  : 1.0.0

System:

   NodeJS : v14.4.0
   npm    : 6.14.5
   OS     : Windows 10
```

**Comment by danbn-100295** [comment] 2020-09-09 04:02
Same issuse on ios

**Comment by zrev2220** [comment] 2020-11-03 21:34
Any update on this? Issue still exists.

**Comment by DavidWiesner** [comment] 2020-11-27 06:50
I found a fix. Just add the empty attribute 'scroll-events' to the ion-content e.g.: ´<ion-content scroll-events>...</ion-content>´. In my opinion the ionic team should make this as default. It is not obvious that this functionality require an extra attribute.

**Comment by SvenBudak** [comment] 2021-01-25 20:22
Any news about this bug?

**Comment by virusv** [comment] 2021-01-27 12:50
I decided to just disable for now XD
```js
customElements.define("ion-ripple-effect", class extends HTMLElement {});
```

**Comment by digaus** [comment] 2021-02-12 16:23
Yes please fix this :/

**Comment by maciejgoscinski** [comment] 2021-07-23 13:09
Still there. For such a basic building block of a mobile-first UI framework, it should rather be considered quite important to fix.
In fact, there are numerous other scrolling issues on mobile, e.g. with toggle switches.

**Comment by nosTa1337** [comment] 2021-08-06 03:58
I can confirm the bug and a fix would be great. As @maciejgoscinski mentioned, this seems pretty important as the user UI experience is not so nice right now.

**Comment by avalanche1** [comment] 2021-08-06 18:08
This is also the issue for ripple effect, if a component has a `routerLink` prop.
```ts
<IonItem routerLink={`/edit-customer/${customerRec._id}`}>
```

**Comment by maciejgoscinski** [comment] 2021-08-08 20:06
Similar issue for `<ion-card>` when it has a routerLink on it. You can swipe content inside of it, which triggers the animation of the card tap (but not the click handler / routerLink itself).

**Comment by liamdebeasi** [comment] 2021-08-11 16:46
Thanks for the issue. If you enable set the `scrollEvents` property on `ion-content` to `true`, does it resolve the issue? We have some logic in our `tap-click` utility that is supposed to prevent this from happening, but the `ionScrollStart` and `ionScrollEnd` events are disabled by default for performance reasons until `scrollEvents` is turned on: https://github.com/ionic-team/ionic-framework/blob/main/core/src/utils/tap-click.ts#L143-L149

**Comment by DavidWiesner** [comment] 2021-08-11 17:25
@liamdebeasi yes this will resolves the problem but will introduce the performance problems you mentioned. See my comments above for more information https://github.com/ionic-team/ionic-framework/issues/22030#issuecomment-734675735 enabling scroll events is not an option to resolve this issue because of the performance impact. An passive listener may also resolve some performance issues for the scroll event part.

**Comment by liamdebeasi** [comment] 2021-08-11 17:31
Thanks for the update. We are looking into updating the tap click utility for modern browsers, so this context helps.

**Comment by avalanche1** [comment] 2021-08-12 17:06
@liamdebeasi Will this be resolved in v6 or v5 as well?

**Comment by seopei** [comment] 2022-03-11 15:11
@liamdebeasi any updates?

**Comment by muchbetterug** [comment] 2022-05-22 10:08
Any Updates?

**Comment by liamdebeasi** [comment] 2022-05-25 18:34
Hi everyone,

I have an experimental fix that I am working on to resolve this issue. Can you all give this a try and let me know if you run into any issues? Using the new [PointerEvents API](https://developer.mozilla.org/en-US/docs/Web/API/PointerEvent), we can listen for the `pointercancel` event to ensure that the activated/ripple effect state is not added while scrolling. This is good as it lets us avoid having to listen for the `scroll` event on `ion-content` which adds consistent main thread work while scrolling.

```
6.1.7-dev.11653503099.1a8d79df
```

This build works on all Ionic packages (`@ionic/angular`, `@ionic/react`, etc)

Note: This is an Ionic 6 build and is subject to all Ionic 6 breaking changes.

**Comment by liamdebeasi** [comment] 2022-06-03 16:29
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/25352, and a fix will be available in an upcoming release of Ionic Framework.

**Closed** 2022-06-03 16:29 UTC
Labels: package: core, type: bug
