### ISSUE TITLE
bug: ion-input autocapitalize "words" setting capitalizes second character

### ISSUE THREAD

**Issue by ehorodyski-ionic** [ionic-team/ionic-framework#21715] opened 2020-07-09 19:48 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

While working with a community member, it was observed that when setting `autocapitalize="words"` on an `<ion-input>` element, the second character of each word becomes capitalized on iOS. Android does not autocapitalize any words. 

**Expected behavior:**

The first letter of each word entered in the `<ion-input>` field should become capitalized.

**Steps to reproduce:**

1. Run the provided repro: `ionic cordova run android` and/or `ionic cordova run ios`.
2. Enter multiple words into the input field, ensuring that only lowercase and the space characters are used.

On iOS, it's observed that the second letter of each word is capitalized. 
On Android, it's observed that no characters are capitalized. 

**Related code:**

A repro can be found at the following link: https://github.com/ehorodyski-ionic/fw-ng-issue-autocapitalization

The relevant portion of code can be found below (containing the code contents of `src/app/explore-container/explore-container.component.html`):
```
<ion-list>
  <ion-item>
    <ion-label position="floating">Autocapitalize Words!</ion-label>
    <ion-input autocapitalize="words"></ion-input>
  </ion-item>
</ion-list>
```

**Other information:**

Screenshot:
![Screen Shot 2020-07-09 at 2 20 21 PM](https://user-images.githubusercontent.com/62819287/87083773-28949680-c1fb-11ea-8e90-ec0e2c0bec1b.png)

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.10.1 (/Users/eric/npm-global/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.2.3
   @angular-devkit/build-angular : 0.901.10
   @angular-devkit/schematics    : 9.1.10
   @angular/cli                  : 9.1.10
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.3 (cordova-lib@9.0.2)
   Cordova Platforms : android 8.1.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 4 other plugins)

Utility:

   cordova-res (update available: 0.15.1) : 0.11.0
   native-run                             : 1.0.0

System:

   Android SDK Tools : 26.1.1 (/Users/eric/Library/Android/sdk)
   ios-sim           : 8.0.2
   NodeJS            : v12.16.1 (/usr/local/bin/node)
   npm               : 6.14.4
   OS                : macOS Catalina
   Xcode             : Xcode 11.4.1 Build version 11E503a
```

**Comment by liamdebeasi** [comment] 2020-07-09 20:49
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. I was able to reproduce this outside of Ionic Framework -- it looks like a WebKit bug. I will look into reporting this to the WebKit team.

CodePen: https://codepen.io/liamdebeasi/pen/PoZevMd

**Closed by liamdebeasi** 2020-07-09 20:49 UTC
Labels: triage

**Comment by liamdebeasi** [comment] 2020-07-09 20:54
Looks like there is already a bug, and it has been fixed! https://bugs.webkit.org/show_bug.cgi?id=148504

**Comment by ehorodyski-ionic** [comment] 2020-07-09 23:10
Thanks @liamdebeasi -- it's good information to know that the `autocapitalize` property utilizes the mobile browser's implementation of the functionality.

I also want to leave the following information in here as well, [related to how `autocapitalize` works as an global attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autocapitalize) (**bold** emphasis mine):  

> The autocapitalize attribute **doesn’t affect behavior when typing on a physical keyboard**. Instead, it affects the behavior of other input mechanisms, such as virtual keyboards on mobile devices and voice input. The behavior of such mechanisms is that they often assist users by automatically capitalizing the first letter of sentences. The autocapitalize attribute enables authors to override that behavior per-element.
>
> **The autocapitalize attribute never causes autocapitalization to be enabled for an <input> element with a type attribute whose value is url, email, or password.**

This explains why the observation I had using Android - I was using my physical keyboard!
