### ISSUE TITLE
bug: click event fired twice when using stopImmediatePropagation()

### ISSUE THREAD

**Issue by digaus** [ionic-team/ionic-framework#26793] opened 2023-02-14 09:17 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] v7.x
- [ ] Nightly

### Current Behavior

Exactly like this issue: https://github.com/ionic-team/ionic-framework/issues/23041

Click event is fired twice when using `stopImmediatePropagation()` on the `ion-checkbox`

### Expected Behavior

Click event should only fire once

### Steps to Reproduce

```
<ion-item>
    <ion-checkbox slot="start" (click)="handleEvent($event)"></ion-checkbox>
    <ion-label>Test Checkbox</ion-label>
</ion-item>
```

```
    public handleEvent(event: PointerEvent): void {
        event.stopImmediatePropagation();
        console.log(event);
    }
```

### Ionic Info

```
Ionic:

   Ionic CLI                     : 6.20.8 (/Users/xx/.nvm/versions/node/v16.19.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.5.2
   @angular-devkit/build-angular : 14.1.0
   @angular-devkit/schematics    : 14.1.0
   @angular/cli                  : 14.1.0
   @ionic/angular-toolkit        : not installed

Capacitor:

   Capacitor CLI      : 4.6.1
   @capacitor/android : 4.6.1
   @capacitor/core    : 4.6.1
   @capacitor/ios     : 4.6.1

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.1

System:

   NodeJS : v16.19.0 (/Users/xx/.nvm/versions/node/v16.19.0/bin/node)
   npm    : 8.19.3
   OS     : macOS
```

### Additional Information

Can be fixed by also using `preventDefault()`, but I still think this is not the desired behaviour

**Comment by liamdebeasi** [comment] 2023-02-14 13:27
Thanks for the report. Can you reproduce this in an Ionic starer app and provide a link to the repo?

**Comment by digaus** [comment] 2023-02-14 13:52
> Thanks for the report. Can you reproduce this in an Ionic starer app and provide a link to the repo?

Here it is in stackblitz

https://stackblitz.com/edit/angular-fbrsv3?file=src/app/app.component.html

**Comment by liamdebeasi** [comment] 2023-02-14 15:46
Thanks! I can reproduce the behavior, but this does not appear to be a bug in Ionic. When clicking a `<label>`, the browser also dispatches a click event on the associated `<input>` element. This results in multiple click events.

Here is a reproduction of the same behavior with an `<input type="checkbox">` element: https://codepen.io/liamdebeasi/pen/RwYwLvp

Click the "Checkbox Label" text and you should see two click events in the console: One from `<label>` and one from `<input>`.

We had a similar issue with `ion-toggle` in https://github.com/ionic-team/ionic-framework/issues/23041. The solution there was to add `pointer-events: none` to the `<label>` element. However, we are unable to do that here because that prevents devs from clicking anywhere in the item to toggle the checkbox.

---

Can you help me understand what you are trying to do? If you are trying to detect when the checkbox state changes you should listen for `ionChange` instead.

**Comment by digaus** [comment] 2023-02-14 16:18
I am doing something like this: 
![image](https://user-images.githubusercontent.com/15358538/218794767-9d476ab1-e2e9-4c7d-b73e-b0e557fd7350.png)

Basically want to decide myself when to check the elements. With the header checkbox I can select all or deselect all depending on current state. `stopImmediatePropagation()` prevents the checkbox from being checked without me telling it to be

Since it seems not to be an Ionic issue I will just also use `preventDefault()` which makes it work again.

**Comment by liamdebeasi** [comment] 2023-02-15 14:05
Thanks for the reply. I am going to close this out, but let me know if you have any other questions.

**Closed by liamdebeasi** 2023-02-15 14:05 UTC
Labels: triage
