### ISSUE TITLE
bug: unexpected ionChange emit with wrong event data

### ISSUE THREAD

**Issue by loopezz** [ionic-team/ionic-framework#27986] opened 2023-08-14 13:17 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

`ionChange` on `ion-radio-group` is being trigger with wrong event data when used with `ion-accordion-group` as child element and after clicking on an `ion-accordion` element to toggle the accordion.

### Expected Behavior

It must **not** emit the `ionChange` of the `ion-radio-group` because the selected radio is unchanged.

### Steps to Reproduce

1. Go to https://stackblitz.com/edit/ionic7-highlight-issue-y3pfzf?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts,src%2Findex.html
2. Open console log;
3. Click on a radio button;
4. Confirm the `ionChange` is being trigger in the console log;
5. Toggle an accordion;
6. Check the console log once again.

### Ionic Info

-

**Comment by liamdebeasi** [comment] 2023-08-14 13:59
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The `ionChange` event bubbles. This means that when `ion-accordion-group` fires an `ionChange` event then it will bubble up, and the `ionChange` handler on `ion-radio-group` will fire too.

`ion-radio-group` is not emitting an `ionChange` event with an invalid value. Instead, your `(ionChange)` listener on `ion-radio-group` is responding to the `ionChange` event that is bubbling from `ion-accordion-group`. Your `logRadioGroupChanged` code should be updated to only run if the event target is the radio group:

```ts
logRadioGroupChanged(event: any) {
  if (event.target.tagName === 'ION-RADIO-GROUP') {
    console.log('Radio group changed:', event.detail.value);
  }
}
```

**Closed by liamdebeasi** 2023-08-14 13:59 UTC
Labels: triage

**Comment by liamdebeasi** [comment] 2023-08-14 14:03
You can also prevent this bubbling by calling `event.stopPropagation()` on your `ion-accordion-group` `ionChange` handler.
