### ISSUE TITLE
bug: Split Pane and :host() pseudo selector causes issue in Safari via LogRocket

### ISSUE THREAD

**Issue by bdsimmons** [ionic-team/ionic-framework#21908] opened 2020-08-11 15:46 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

We are using Ionic/react 5.3.1 and it works beautifully, but we have run into an issue on iPhones/Safari while using the service LogRocket and Ionic Split Panes.

This is what our app looks like when rendered properly and this is what the user actually sees.
<img width="373" alt="Screen Shot 2020-08-11 at 10 20 24 AM" src="https://user-images.githubusercontent.com/3876229/89918330-81bb6580-dbbf-11ea-804d-842a63f1b232.png">

And if you open the side navigation:
<img width="372" alt="Screen Shot 2020-08-11 at 10 20 31 AM" src="https://user-images.githubusercontent.com/3876229/89918315-7ec07500-dbbf-11ea-929c-22163671d866.png">

This is what we see in the screen recordings of LogRocket:
<img width="467" alt="Screen Shot 2020-08-11 at 10 19 56 AM" src="https://user-images.githubusercontent.com/3876229/89918348-86801980-dbbf-11ea-804b-1476b9081be2.png">

I worked with LogRocket to try to debug this issue, and this was the information I got from them:

> Hello, this is a known issue with WebKit (Safari) where certain style rules (specifically the :host() pseudo-selector that Ionic uses) are not handled appropriately, which causes the issue you're seeing. Here's the issue we filed with WebKit about this problem: https://bugs.webkit.org/show_bug.cgi?id=207567
We are still considering possible work-arounds to this issue, but given the nature of the bug do not intend to move quickly on a resolution. I've referred the engineering team to this report, you'll be notified again when we make any progress on this issue.

**Expected behavior:**

I should be able to view user sessions without the split pan showing and taking over the viewport if the user has not opened the side navigation.

**Steps to reproduce:**

Create an ionic project with a split pane side navigation menu and configure logrocket. Record a session and the recording will be corrupted.

**Related code:**
```
<IonApp>
  <IonReactRouter>
    <IonSplitPane contentId="main">
      <SideMenu />
      <IonRouterOutlet id="main">
        /*Routes*/
      </IonRouterOutlet>
    </IonSplitPane>
  </IonReactRouter>
</IonApp>
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.10.1 (/Users/ben/.nvm/versions/node/v13.11.0/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.3.1

Capacitor:

   Capacitor CLI   : 1.5.2
   @capacitor/core : 1.5.2

Utility:

   cordova-res (update available: 0.15.1) : 0.11.0
   native-run                             : 1.0.0

System:

   NodeJS : v13.11.0 (/Users/ben/.nvm/versions/node/v13.11.0/bin/node)
   npm    : 6.14.5
   OS     : macOS Catalina
```

**Comment by liamdebeasi** [comment] 2020-09-29 14:12
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. As you mentioned in your post, this is a bug in WebKit. I looked at the WebKit thread you linked to, and it looks like the issue was resolved a few weeks ago. Upcoming versions of iOS/Safari should get this fix, but older versions will not.

**Closed by liamdebeasi** 2020-09-29 14:12 UTC
Labels: ionitron: needs reproduction
