### ISSUE TITLE
bug: Opening Ion Modal in multiple Ion Tabs breaks z-index of tab page (Ionic React)

### ISSUE THREAD

**Issue by armespavong** [ionic-team/ionic-framework#28007] opened 2023-08-16 17:29 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Tab page stucks at current page when clicking tab button after modal inside each tab were opened. I noticed that z-index of div with class name "ion-page" stopped changing.

I also tried inline method and isOpen method, results are same.

### Expected Behavior

Clicking tab button should change the tab page.

### Steps to Reproduce

1. Create multiple tabs
2. Add modal into each tab
3. Open modal inside a tab
4. Close modal
5. Click on tab button to change page
6. Open modal in current page
7. Close modal
8. Click on tab button to change page (Page stucks at current)

### Code Reproduction URL

https://github.com/armespavong/ionic7-react-issue.git

### Ionic Info

Ionic:

   Ionic CLI       : 7.1.1 (/Users/patiparnne/.nvm/versions/node/v18.16.1/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 7.3.0

Capacitor:

   Capacitor CLI      : 5.2.3
   @capacitor/android : not installed
   @capacitor/core    : 5.2.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v18.16.1 (/Users/patiparnne/.nvm/versions/node/v18.16.1/bin/node)
   npm    : 9.8.1
   OS     : macOS Unknown

### Additional Information

Please see my [uploaded video](https://youtu.be/dGoLLRT2MMA)

**Comment by liamdebeasi** [comment] 2023-08-16 18:39
Thanks for the report. Did you push your code? The linked repo is empty.

**Comment by armespavong** [comment] 2023-08-17 10:58
> Thanks for the report. Can you push your code? The linked repo is empty.

Sorry, my mistake.
Please re-check the repository again [Code Reproduction URL](https://github.com/armespavong/ionic7-react-issue.git)

**Comment by liamdebeasi** [comment] 2023-08-17 13:04
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/23863. The linked issue notes nested child pages in tabs, but it looks like this bug applies to tabs in general.

**Closed by liamdebeasi** 2023-08-17 13:04 UTC
Labels: triage
