### ISSUE TITLE
bug: ion-backdrop visible=false not working

### ISSUE THREAD

**Issue by Sovai** [ionic-team/ionic-framework#29177] opened 2024-03-19 04:48 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

ionic vue when set visible=false it still show up.

### Expected Behavior

  <ion-backdrop :visible="false" />
this should hide the backdrop

### Steps to Reproduce

  <ion-backdrop :visible="false" />

### Code Reproduction URL

https://stackblitz.com/edit/m3udbc?file=src%2Fcomponents%2FExample.vue

### Ionic Info

I am using "@ionic/vue": "^7.7.3"

**Comment by liamdebeasi** [comment] 2024-03-19 13:09
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The `background` CSS in your example is overriding the code we set to clear the backdrop opacity.

The `visible` property was originally created for internal use, and it sets the background color of the backdrop to `transparent` but still receives click events. As a result, we do not hide it using `display: none`.

We set a `.backdrop-hide` class on the host element that sets `background-color: transparent`. However, since your CSS takes priority the transparent background is not taking effect.

You can fix this by changing your selector to `ion-backdrop:not(.backdrop-hide)`.

**Closed by liamdebeasi** 2024-03-19 13:09 UTC
Labels: triage
