### ISSUE TITLE
bug: Collapsible Large Titles Flicker 

### ISSUE THREAD

**Issue by seanaguinaga** [ionic-team/ionic-framework#27060] opened 2023-03-30 00:05 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

With version 7, the collapsed title flashes upon navigation

Does not happen with version 6

https://user-images.githubusercontent.com/15254340/228694868-c1a59b02-84a3-41eb-93ea-cae83d9294f7.mov

Please see video ^

### Expected Behavior

Would not flash, as in version 6

### Steps to Reproduce

upgrade to version 7

see flash on collapsed title

### Ionic Info

```
Ionic:

   Ionic CLI : 6.20.8

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v18.15.0
   npm    : 9.5.0
   OS     : macOS
```

**Comment by seanaguinaga** [comment] 2023-03-30 15:15
hey @liamdebeasi how do I give you access to a private monorepo?

**Comment by liamdebeasi** [comment] 2023-03-30 15:16
I recommend reproducing this in an Ionic starter application and providing a link to the repo. This way you can have a minimal reproduction without providing any secret/private code.

**Comment by seanaguinaga** [comment] 2023-03-30 15:24
https://github.com/seanaguinaga/large-title-repro

A little different - duration is longer - but I'm certain it's the same cause

Thank you for all that you Liam - Ionic is amazing (as you know)

**Comment by seanaguinaga** [comment] 2023-04-07 17:44
Also happens here on mlynch's repo on first render

https://github.com/mlynch/nextjs-tailwind-ionic-capacitor-starter

**Comment by thetaPC** [comment] 2023-05-19 23:46
@seanaguinaga please provide a video clip of the flickering that you are experiencing on your repo, [large-title-repro](https://github.com/seanaguinaga/large-title-repro). This would allow us to track the bug easier since I have not been able to replicate it on your repo.

**Comment by thetaPC** [comment] 2023-05-19 23:47
@milanharia please provide the reproduction that you mention. I wasn't able to replicate it using the React Tabs starter and this is a tricky bug.

**Comment by seanaguinaga** [comment] 2023-05-22 16:34
Title comes in showing - note the name of the person on the navigated to page

https://github.com/ionic-team/ionic-framework/assets/15254340/c23c0688-9fb8-4c4f-8fd1-2532beda6464

**Comment by thetaPC** [comment] 2023-05-22 18:41
Thank you! I was able to replicate the issue by building the [project](https://github.com/seanaguinaga/large-title-repro/tree/main) to IOS.

**Comment by liamdebeasi** [comment] 2023-10-03 20:50
Hi everyone,

Here is a dev build with a proposed fix if anyone is interested in testing: `7.4.3-dev.11696365694.156f41d3`

Install Example: 

```
npm install @ionic/react@7.4.3-dev.11696365694.156f41d3 @ionic/react-router@7.4.3-dev.11696365694.156f41d3
```

**Comment by liamdebeasi** [comment] 2023-10-05 18:45
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/28277, and a fix will be available in an upcoming release of Ionic Framework. Feel free to keep testing the dev build, and let me know if you run into any issues.

**Closed** 2023-10-05 18:45 UTC
Labels: package: core, type: bug

**Comment by moerphie** [comment] 2023-10-14 09:17
@liamdebeasi #28277 hasn't fixed it for me. 

```vue
<template>
    <ion-page ref="xxxpage">
        <ion-header :translucent="true">
            <ion-toolbar>
                <ion-title>XXX</ion-title>
            </ion-toolbar>
        </ion-header>

        <ion-content :fullscreen="true">
            <ion-header collapse="condense">
                <ion-toolbar>
                    <ion-title size="large">
                        XXX
                    </ion-title>
                </ion-toolbar>
            </ion-header>
        </ion-content>
    </ion-page>
</template>
```

```json
"@ionic/vue": "7.5.0",
"@ionic/vue-router": "7.5.0",
```


https://github.com/ionic-team/ionic-framework/assets/12500071/89cf9b4d-5566-4285-a9fc-aeda86ec2f2d

**Comment by liamdebeasi** [comment] 2023-10-16 14:40
Please file a new issue with a reproduction case.
