### ISSUE TITLE
bug: `<ion-menu>` inside a route from a `<ion-tabs>` does not work unless we hard refresh the route

### ISSUE THREAD

**Issue by mrleblanc101** [ionic-team/ionic-framework#28457] opened 2023-11-02 17:28 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

If the ion-menu is on the first tab, it will work.
But if it's not, the menu won't appear unless you do a hard reload on that page.
![2023-11-02 13 21 44](https://github.com/ionic-team/ionic-framework/assets/17392251/1520fbbb-a55b-4e37-a8f7-94a94a5a0fdf)

### Expected Behavior

The ion-menu should work inside a route from an ion-tab.

### Steps to Reproduce

1. Start an app from the tabs starter
2. Add an `<ion-menu>` in `TabsPage.vue` and a `<ion-menu-button>` in `Tab2Page.vue`
3. Navigate to that route, the menu button wont appear.
4. Hard refresh, the menu button will appear and work properly.

I also tried to put the `<ion-menu>` at the `Tab2Page.vue` as a second root element like in the documentation. but this cause to `vue-router` error: 
> Extraneous non-props attributes (registerIonPage) were passed to component but could not be automatically inherited because component renders fragment or text root nodes. 
```
<template>
  <ion-menu content-id="main-content">
    ...
  </ion-menu>
  <ion-page id="main-content">
    ...
  </ion-page>
</template>
```

### Code Reproduction URL

Here, the menu work but if you navigate to Tab 2, you can never go back to Tab 1, it will not render: https://github.com/mrleblanc101/test-ion-menu-in-tab

Here, I placed the menu in Tab 2, it will not appear since it's not the first page that render. If hard refresh the page on Tab 2, it will appear: https://github.com/mrleblanc101/test-ion-menu-at-root

### Ionic Info

Ionic:

   Ionic CLI       : 7.1.1 (/Users/sleblanc/.nvm/versions/node/v16.19.1/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 7.5.3-dev.11698760841.12aff234

Capacitor:

   Capacitor CLI      : 5.5.0
   @capacitor/android : not installed
   @capacitor/core    : 5.5.0
   @capacitor/ios     : 5.5.0

Utility:

   cordova-res                          : not installed globally
   native-run (update available: 2.0.0) : 1.7.3

System:

   NodeJS : v16.19.1 (/Users/sleblanc/.nvm/versions/node/v16.19.1/bin/node)
   npm    : 8.19.3
   OS     : macOS Ventura 14.1

**Comment by mrleblanc101** [comment] 2023-11-03 15:30
I added my 2 test case: 
https://github.com/mrleblanc101/test-ion-menu-in-tab
https://github.com/mrleblanc101/test-ion-menu-at-root

I edited the post with the necessary information

**Comment by mrleblanc101** [comment] 2023-11-03 15:44
I think the doc is just wrong, I was able to make it work in the end.
I had to put the `<ion-menu>` inside the `<ion-page>` instead of at the root.
And I added the `id="main-content"` on the `<ion-content>` instead of the `<ion-page>` component.

**Comment by mrleblanc101** [comment] 2023-11-03 15:56
Oh, I can make ion-menu work at the component root if i add `v-bind="$attrs"` on `<ion-page>` so that it receive the props passed from `<ion-router-outlet>` even if there are multiple root node in the component.

**Comment by liamdebeasi** [comment] 2023-11-07 14:29
Can you make your repos public? I can't access them currently.

**Comment by mrleblanc101** [comment] 2023-11-07 14:56
@liamdebeasi Oups, my bad ! I'll do this right away. But as you'll see I think it's more a documentation issue as I found a way to make it work.

**Comment by liamdebeasi** [comment] 2023-11-20 20:58
Hey there,

Sorry for the delay. I took a look into this, and the problem is that the menu needs to be contained inside of `ion-page`. Each view needs to have a single root node in order for routing to work. For `Tab1Page` there were two nodes (`ion-menu` and `ion-page`).

I'd also recommend placing the menu at the end of the view so it does not conflict with the collapsible large title. The collapsible large title looks for first instance of `ion-header` so it can find the main header (i.e. the small header that shows up when you scroll) Your template should look like this:

```html
<template> 
    <ion-page>
        <ion-header>
            <ion-toolbar>
                <ion-title>Tab 1</ion-title>
                <ion-buttons slot="end">
                    <ion-menu-button></ion-menu-button>
                </ion-buttons>
            </ion-toolbar>
        </ion-header>
        <ion-content id="main-content" :fullscreen="true">
            <ion-header collapse="condense">
                <ion-toolbar>
                    <ion-title size="large">Tab 1</ion-title>
                </ion-toolbar>
            </ion-header>

            <ExploreContainer name="Tab 1 page" />
        </ion-content>
        <ion-menu type="push" side="end" content-id="main-content">
            <ion-header>
                <ion-toolbar>
                    <ion-title>Menu</ion-title>
                </ion-toolbar>
            </ion-header>
            <ion-content class="ion-padding">
                <ion-list>
                    <ion-item>
                        <ion-label>Test</ion-label>
                    </ion-item>
                </ion-list>
            </ion-content>
        </ion-menu>
    </ion-page>
</template>
```

Can you give this a try and let me know if it fixes the issue?

**Comment by mrleblanc101** [comment] 2023-11-23 21:51
As I said previously, the exemple in the doc are wrong. They simply don't work. I was able to solve my problem, so I think the exemple in the docs should be improved/fixed.

**Comment by liamdebeasi** [comment] 2023-11-27 15:42
Ah I see. So the demo is working correctly here, but it's a bit confusing since `ion-page` is used as a wrapper element so users can swipe on the main content. However, these demos do not use the router so there will be some differences.

We can look into revising these demos to be more clear. However, I am going to close this thread for now because the main issue has been resolved.

**Closed by liamdebeasi** 2023-11-27 15:42 UTC
Labels: triage
