### ISSUE TITLE
[v5] bug: Firefox Browser Extension/Addon not displaying correctly

### ISSUE THREAD

**Issue by zwacky** [ionic-team/ionic-framework#20478] opened 2020-02-13 20:31 UTC
# Bug Report

**Ionic version:**
[ ] 4.x
[x] **5.x**

**Current behavior:**
using Ionic in a browser extension doesn't show the app correctly in firefox (does display correctly in chrome).

![image](https://user-images.githubusercontent.com/1093032/74471179-11e25180-4ea0-11ea-8f1b-7267892c5bc3.png)

**Expected behavior:**

![image](https://user-images.githubusercontent.com/1093032/74471313-4e15b200-4ea0-11ea-9ea9-92c3d94ee3b7.png)

**Related code:**
This happens because in `import "@ionic/react/css/structure.css";` the following css code makes the app in the firefox extension/addon popup fail:

```
...
body {
  ...
  position: fixed;
  ...
}
...
```

**Possible workaround in app**
I realise this issue is not high prio because of a small adoption rate of browser extensions using Ionic. But to the devs out there who may go through the same, these css lines in your App.scss helped me:

```
body {
  // 👇 because the body is not .hydrated yet, it will hide, but also the popup's width gets smaller
  display: block !important; 
  // 👇 this counter acts the `position: fixed` in structure.css
  position: relative !important;
}
```

**Steps to reproduce:**
- open firefox
- go to `about:debugging#/runtime/this-firefox`
- click `Load Temporary Add-on...`
- navigate to the extracted zips of ...-working.zip or ...-broken.zip
- click on the new extension bell icon on the top right

**Files**
- [build-broken.zip](https://drive.google.com/open?id=13N3TGkGDnF4Wgwl7UQQT3HqKbDmHLeBX)
- [build-working.zip](https://drive.google.com/open?id=14Ia9Nwj7TCPdnTtXojLq0OmXn5UR4cz7)

**Comment by amandaesmith3** [comment] 2022-02-03 18:49
Thanks for the issue! Since this has been posted, we've changed how hydration works in Ionic React, meaning it's likely this has been fixed in Ionic 6. As such, I'm going to go ahead and close this out. If you're still seeing this in the latest version of Ionic, please create a new issue, including a link to the source code for the reproduction app if possible so we can debug. Thanks!

**Closed by amandaesmith3** 2022-02-03 18:49 UTC
Labels: triage
