### ISSUE TITLE
bug: range events in 7.5.4

### ISSUE THREAD

**Issue by GTorreil** [ionic-team/ionic-framework#28556] opened 2023-11-19 14:58 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

(somewhat) minimal reproduction :
``` html
<div>{{ modelValue }}</div>

    <IonRange
      :value="modelValue"
      :min="0"
      :max="100"
      :step="5"
      ticks
      snaps
      @v-ion-input="emit('update:modelValue', $event.detail.value)"
    />
```

- `@ionic/vue@7.5.3` : value updates when dragging the "range" control. tthe displayed value also updates.
- `@ionic/vue@7.5.4` : the value never updates.

### Expected Behavior

I expect the value to update in both `@ionic/vue@7.5.3` and `@ionic/vue@7.5.4`.

### Steps to Reproduce

1. Run the minimal reproduction case above with @ionic/vue@7.5.3

### Code Reproduction URL

https://gist.github.com/GTorreil/d2ca59710f36846f524134797ad89319

### Ionic Info

Ionic:

   Ionic CLI       : 7.1.5 (/Users/guillaumetorreilles/.asdf/installs/nodejs/21.2.0/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 7.5.4

Capacitor:

   Capacitor CLI      : 5.5.1
   @capacitor/android : 5.5.1
   @capacitor/core    : 5.5.1
   @capacitor/ios     : 5.5.1

Utility:

   cordova-res                          : not installed globally
   native-run (update available: 2.0.0) : 1.7.4

System:

   NodeJS : v21.2.0 (/Users/guillaumetorreilles/.asdf/installs/nodejs/21.2.0/bin/node)
   npm    : 10.2.3
   OS     : macOS Unknown

**Comment by liamdebeasi** [comment] 2023-11-20 14:23
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The `v-ion-input` usage was a workaround for the bug noted in https://github.com/ionic-team/ionic-framework/issues/27292#issuecomment-1737473203. That bug has since been fixed, so `ion-input` can now be used as normal. This was also mentioned in the release notes: https://github.com/ionic-team/ionic-framework/releases/tag/v7.5.5

**Closed by liamdebeasi** 2023-11-20 14:23 UTC
Labels: triage

**Comment by GTorreil** [comment] 2023-11-20 15:57
Oh, sorry I missed that part when I read the release notes. Everything works, thanks a lot !
