### ISSUE TITLE
bug: NavController.navigateRoot() does not trigger a navigation animation.

### ISSUE THREAD

**Issue by KevinBassaDevelopment** [ionic-team/ionic-framework#20014] opened 2019-11-28 07:59 UTC
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**

- NavController.navigateRoot() does not trigger a navigation animation.
- When changing the default navigation animations to an animation that moves a page out of the view, using 'navigateRoot()' will keep the page invisible.

**Expected behavior:**
- The animation of NavController.navigateRoot() should be customizable.

**Steps to reproduce:**
1.  replace default navigation animations with custom ones that change opacity:0  or transform: translateX(-100%)
2.  use 'navigateForward([page2])' //1->2
3. use 'navigateRoot([page1])'         //2->1
4. now page 2 is removed from stack, but page 1 still has  transform: translateX(-100%) and is invisible

**Related code:**

app.module.ts
```
   IonicModule.forRoot({
      navAnimation : myTransitionAnimation
    }),
```

nav-animations.ts:
```
import { Animation, NavOptions } from '@ionic/core';

export function myTransitionAnimation(AnimationC: Animation, _: HTMLElement, opts: TransitionOptions): Promise<Animation> {

    const TRANSLATE_DIRECTION = 'translateX';

    const RIGHT = '100%';
    const CENTER = '0px';
    const LEFT = '-100%';

    const inactiveOpacity = 1;
    const activeOpacity = 1;

    const enteringEl = opts.enteringEl;
    const leavingEl = opts.leavingEl;

    const ionPageElement = getIonPageElement(enteringEl);
    const rootTransition = new AnimationC();

    rootTransition
        .addElement(ionPageElement)
        .beforeRemoveClass('ion-page-invisible');

    const backDirection = (opts.direction === 'back');

    if (backDirection) {
        // BACK, entering component
        rootTransition
            .duration(opts.duration || 350)
            .easing('cubic-bezier(0.3,0,0.66,1)')
            .fromTo(TRANSLATE_DIRECTION, LEFT, CENTER, true) // ### could be commented out for better performance
            .fromTo('opacity', inactiveOpacity, activeOpacity, true);  // ####  could be commented out for better performance

    } else {
        // FORWARD:  entering component, comming from right to center
        rootTransition
            .duration(opts.duration || 350)
            .easing('cubic-bezier(0.3,0,0.66,1)')
            .fromTo(TRANSLATE_DIRECTION, RIGHT, CENTER, true)
            .fromTo('opacity', inactiveOpacity, activeOpacity, true);
    }

    // Animate toolbar if it's there
    const enteringToolbarEle = ionPageElement.querySelector('ion-toolbar');
    if (enteringToolbarEle) {
        const enteringToolBar = new AnimationC();
        enteringToolBar.addElement(enteringToolbarEle);
        rootTransition.add(enteringToolBar);
    }

    if (leavingEl && backDirection) {
        // BACK, leaving component
        rootTransition
            .duration(opts.duration || 350)
            .easing('cubic-bezier(0.3,0,0.66,1)');

        const leavingPage = new AnimationC();
        leavingPage
            .addElement(getIonPageElement(leavingEl))
            .fromTo(TRANSLATE_DIRECTION, CENTER, RIGHT)
            .fromTo('opacity', activeOpacity, inactiveOpacity);

        rootTransition.add(leavingPage);
    } else if (leavingEl && !backDirection) {
        // FORWARD, leaving component
        // ####could be completly commented out for better performance ########
        rootTransition
            .duration(opts.duration || 350)
            .easing('cubic-bezier(0.3,0,0.66,1)');

        const leavingPage = new AnimationC();
        leavingPage
            .addElement(getIonPageElement(leavingEl))
            .fromTo(TRANSLATE_DIRECTION, CENTER, LEFT)
            .fromTo('opacity', activeOpacity, inactiveOpacity);

        rootTransition.add(leavingPage);
    }

    return Promise.resolve(rootTransition);
}

export interface TransitionOptions extends NavOptions {
    progressCallback?: ((ani: Animation | undefined) => void);
    window: Window;
    baseEl: any;
    enteringEl: HTMLElement;
    leavingEl: HTMLElement | undefined;
}

function getIonPageElement(element: HTMLElement) {
    if (element.classList.contains('ion-page')) {
        return element;
    }
    const ionPage = element.querySelector(':scope > .ion-page, :scope > ion-nav, :scope > ion-tabs');
    if (ionPage) {
        return ionPage;
    }
    return element;
}

```

**Other information:**
Using the browser 'back' button has the same behaviour.
A workaround for this is:

```
  public subscribeToBrowserBackBtnEvents(): void {
    window.onpopstate = ev => {
      console.log('browser back()');
      this._navCtrl.setDirection('back', true, 'back');
    };
  }
```

**Ionic info:**
```
Ionic:

   Ionic CLI                     : 5.4.5
   Ionic Framework               : @ionic/angular 4.11.3
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.3.17
   @angular/cli                  : 8.3.17
   @ionic/angular-toolkit        : 2.1.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.15.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment] 2022-06-02 13:27
Thanks for the issue and apologies for the delay. In the time since this issue was opened, there have been many enhancements and fixes made to Ionic Framework that may have resolved this issue.

It is difficult for us to verify whether or not this is still an issue as no GitHub repo was provided in the original post (Code snippets are typically not enough to reproduce more complex issues). I am going to close this issue for now. If this issue is still occurring, please reply with a minimal GitHub repo that we can use to verify this behavior. At that point, we will be more than happy to reopen this issue. Thank you!

-----

For more info on how to create a good code reproduction, please see https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-a-good-code-reproduction.

**Closed by liamdebeasi** 2022-06-02 13:27 UTC
Labels: triage
