### ISSUE TITLE
bug: Android forces Dark Mode on my Ionic apps

### ISSUE THREAD

**Issue by Sibi4** [ionic-team/ionic-framework#24771] opened 2022-02-11 11:51 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

Xiaomi phones all of a sudden force Dark Mode on my Ionic Apps. Background color of the app has changed from white to black, the text from black to white. Also some buttons with CSS classes='primary' have now changed color. Dark mode in my phone is not active. 
This happened for the first time on February 10th, 2022. Till this day, my Ionic apps on Xiaomi phones were running perfectly fine. 
Do you have any idea how can I solve this issue?

**Edit:** now I have this problem on all Android phones (Samsung, Xiaomi, etc).

### Expected Behavior

My app must have Light mode. Dark mode must not be forced.

### Steps to Reproduce

I have noticed the same behaviour only in Xiaomi phones. 

### Ionic Info

Ionic:

   Ionic CLI       : 6.13.1
   Ionic Framework : @ionic/react 5.6.0

Capacitor:

   Capacitor CLI   : 3.0.0
   @capacitor/core : 3.0.0

Utility:

   cordova-res : not installed
   native-run  : 1.3.0

System:

   NodeJS : v14.17.0 (C:\Program Files (x86)\nodejs\node.exe)
   npm    : 6.14.13
   OS     : Windows 10

### Additional Information

Android version: 11

**Comment by Sibi4** [comment] 2022-02-11 12:21
> @Sibi4 Hi, can you provide pictures of the case and what android versions have you tested this on ?

Android version 11. Regarding the pictures, they are a bit large. Sorry, I don't really know how to fix them. The white background is the right one, I took the screenshot from a Samsung. The black background happens in Xiaomi phone.

**Comment by liamdebeasi** [comment] 2022-02-11 14:21
Thanks for the issue. What version of the Chrome webview is running on that Xiaomi phone? To find this, you can log `window.navigator.userAgent` when inspecting your app with Chrome Dev Tools.

Also, can you please provide a GitHub repo I can use to reproduce the issue?

**Comment by Umfi** [comment] 2022-02-12 13:24
I also had this problem with an Ionic 6 app using my Xiaomi device running Android 11. I didn't even made any style related changes.  Also the removing of the @media (prefers-color-scheme: dark) {} section in src/theme/variables.css didn't helped.

After some testing around I used following quickfix to fix the problem.

In public/index.html replace 
`<meta name="color-scheme" content="light dark" />` 
with 
`<meta name="color-scheme" content="light" />`

**Comment by Piedade** [comment] 2022-02-13 13:17
This bug also happens on Huawei phones
Changing `<meta name="color-scheme" content="light" />` dind't work for me.

'Mozilla/5.0 (Linux; Android 11; M2007J20CG Build/RKQ1.200826.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/98.0.4758.87 Mobile Safari/537.36'

**Comment by YoeriNijs** [comment] 2022-02-13 19:53
It is not only Xiaomi. I can confirm that this is the case on Nokia and Fairphone devices. It happens since this week.

I've tried to disable dark mode, but that did not help.

**Comment by YoeriNijs** [comment] 2022-02-14 06:23
Forum topic: https://forum.ionicframework.com/t/installed-app-suddenly-becomes-dark/220376

**Comment by YoeriNijs** [comment] 2022-02-14 06:29
Suspect: https://chromestatus.com/feature/5157621012103168

**Comment by Sibi4** [comment] 2022-02-14 08:39
> Suspect: https://chromestatus.com/feature/5157621012103168
> 
> So it should be ‘only light’?
> 
> `<meta name="color-scheme" content="only light" />`
> 
> **Edit: nope, doesn't work.**

I manged to find a workaround only for the moment. I removed 'dark' from this line of code: `<meta name="color-scheme" content="light dark" />` . Also, inside `media (prefers-color-scheme: dark) {}` section in src/theme/variables.css I used the same colors as I use for light mode. So, Android can force dark mode, but the css will be the same as light mode anyway. This is a solution only for the moment. Hopefully this bug will be fixed soon.

**Comment by Sibi4** [comment] 2022-02-14 08:54
> After some testing around I used following quickfix to fix the problem.
> 
> Remove the @media (prefers-color-scheme: dark) {} section in src/theme/variables.css. Instead add the body.dark css rules and append dark class manually to the body on app start, if dark mode is enabled.

@Umfi, I didn't understand this line. Could you please explain it to me? Where should I put body.dark css rules? Inside which file?

**Comment by Umfi** [comment] 2022-02-14 09:09
@Sibi4 
Have a look at my source file.

https://github.com/Umfi/my-fitness-app/blob/master/src/theme/variables.css

I moved the content from within @media (prefers-color-scheme: dark) {} outside of it. And added the class "dark" to the body,

So instead of
`@media (prefers-color-scheme: dark) {
  body {
.
.
.
}
}`

it's now 

`
  body.dark {
.
.
.
}`

And on app start i manually append the class dark to the body if dark mode should be active.

I hope this is clear.

**Comment by martinpllu** [comment] 2022-02-14 09:59
We see this issue in our app on Pixel 4a / Android 12 (ionic-native 5.36.0, capacitor 3.3.3)

"Mozilla/5.0 (Linux; Android 12; sdk_gphone64_arm64 Build/SE1A.211012.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/91.0.4472.114 Mobile Safari/537.36"

One of our users also reports the same problem on Pixel 3.

The problem only seems to affect our ionic UI packaged inside a native capacitor app. The PWA version of the app looks OK in Chrome on the device, which possibly points to WebView.

**Comment by Sibi4** [comment] 2022-02-14 10:12
> @Sibi4 Have a look at my source file.
> 
> https://github.com/Umfi/my-fitness-app/blob/master/src/theme/variables.css
> 
> I moved the content from within @media (prefers-color-scheme: dark) {} outside of it. And added the class "dark" to the body,
> 
> So instead of `@media (prefers-color-scheme: dark) { body { . . . } }`
> 
> it's now
> 
> ` body.dark { . . . }`
> 
> And on app start i manually append the class dark to the body if dark mode should be active.
> 
> I hope this is clear.

@Umfi , thanks :)

**Comment by wgrientidev** [comment] 2022-02-14 11:20
@Umfi 's solution works well.

It would be nice though to know which Google update caused this mess.

**Comment by liamdebeasi** [comment] 2022-02-14 22:51
Hi everyone,

Can someone please provide a GitHub repo I can use to reproduce the issue? I cannot reproduce this on my end.

**Comment by 10Wired** [comment] 2022-02-15 13:11
@liamdebeasi [liamdebeasi](https://github.com/liamdebeasi) My Phone is a Pixel 5 with Android 12 and Webview Version 97.0.xxx
Last Webview Update at 2022-01-19. Since Friday 11th of February my App is in dark Mode

**Comment by Sibi4** [comment] 2022-02-15 13:22
@liamdebeasi, my phone has Android 11 and Webview version: 98.0.XXX

**Comment by liamdebeasi** [comment] 2022-02-15 13:52
Unfortunately I am unable to reproduce this behavior, so there is not much I can do to help. Can someone please provide some steps to reproduce the issue or try and debug the issue further?

**Comment by fadifannoun** [comment] 2022-02-16 09:47
> @Sibi4 Have a look at my source file.
> 
> https://github.com/Umfi/my-fitness-app/blob/master/src/theme/variables.css
> 
> I moved the content from within @media (prefers-color-scheme: dark) {} outside of it. And added the class "dark" to the body,
> 
> So instead of `@media (prefers-color-scheme: dark) { body { . . . } }`
> 
> it's now
> 
> ` body.dark { . . . }`
> 
> And on app start i manually append the class dark to the body if dark mode should be active.
> 
> I hope this is clear.

I tried to append dark class manually to the page body following this document https://ionicframework.com/docs/theming/dark-mode#automatically-enable-dark-mode but the issue remains as ```window.matchMedia('(prefers-color-scheme: dark)').matches``` always return true, so in any case the body will have the dark class.

This behavior happened to our on store application, also happened with the app version built with the following Ionic environment

```
Ionic:

   Ionic CLI                     : 6.12.2 
   Ionic Framework               : @ionic/angular 6.0.5
   @angular-devkit/build-angular : 13.2.2
   @angular-devkit/schematics    : 13.0.4
   @angular/cli                  : 13.2.2
   @ionic/angular-toolkit        : 6.0.0

Cordova:

   Cordova CLI       : 11.0.0
   Cordova Platforms : android 10.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 17 other plugins)

Utility:

   cordova-res : 0.15.2
   native-run  : 1.3.0

System:

   Android SDK Tools : 26.1.1 
   NodeJS            : v14.15.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.14.8
   OS                : Windows 10
```
I would like also to mention that dark mode is also forced in a pure Cordova Android app. Could this be in any way related to ```setForceDarkAllowed``` in Android Webview?

**Comment by Sibi4** [comment] 2022-02-16 10:21
@fadifannoun, I don't find 'setForceDarkAllowed' anywhere in my android folder because of API level I think, but have you tried to set it to 'false'? Is dark mode still forced?

**Comment by fadifannoun** [comment] 2022-02-16 11:20
@Sibi4 actually I am not able to locate it anywhere also, just following some resources, suggestions, and solution to issues seems related, sharing below resources I went through and evaluating which one could be the answer or some workaround, I haven't yet tried any of them yet:

WebView Manager Plugin (Please read through this article, it seems to highlight the main cause)
https://git.scat.su/external/cordova-plugin-android-webview-manager

Theme based solution
https://www.androidbugfix.com/2021/12/how-do-i-force-darken-webview-parent-so.html

Detec Dark Mode differently, not using ```prefers-color-scheme```, instead try this plugin to natively access the mode settings
https://ionicframework.com/docs/native/theme-detection

I will update this if I get any good result

**Comment by jcesarmobile** [comment] 2022-02-16 16:08
there is a newer update from February 14th, 98.0.4759.101, that seems to solve the issue for me

**Comment by Umfi** [comment] 2022-02-17 13:54
Problem still exists on my phone with Android 
11 using Webview 98.0.4758.101 but with the Android Webview Beta (99.0.4844.35) the problem is gone.

**Comment by Sibi4** [comment] 2022-02-17 14:02
@Umfi , on my phone too. Android 11 using Webview 98.0.4758.101

**Comment by enriqueloz88** [comment] 2022-02-19 13:04
Another one here with the same problem (on a xiaomi phone) in ionic 6. For those who want to try to reproduce it, the steps that I have followed are:

- Create a new app from scratch following the usual steps (ionic start newApp)
- Deploy the app to the phone with android studio
- Once installed on the phone everything seems to be fine, dark mode only comes into play when the phone's dark mode is activated
- When you leave the application, if you stop or close the app, when you re-enter the dark mode will be activated, whether or not it is activated on your phone.
- If you delete all the cache of the app, it returns to the initial situation, everything works as expected.

If the app is debugged we see how it always enters this condition, whether the dark mode of your phone is activated or not, which is strange

```sh
if (window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) {
      console.log("Dark mode active") // Always here
}else{
      console.log("Light mode")
}
```

**Comment by 108174** [comment] 2022-02-20 15:32
Hi, I have the same issue and I notice that, if you host the app on a server and access it in the browser then the style is indeed light. However, the Android version is dark regardless of the system settings. ( I have a Samsung s10 )

**Comment by rluttikhuizen** [comment] 2022-02-20 19:29
We experience the same issue (for both Ionic React 5 and 6 on the latest Android Webview). Using code from https://github.com/ionic-team/capacitor/discussions/1978 in the various hooks of the MainActivity seems to be a workaround, but it would be nice if this is not needed for the media query ‘prefers-color-scheme’ to work out of the box on Android Webview.

**Comment by gusgonnet** [comment] 2022-02-21 14:07
> Unfortunately I am unable to reproduce this behavior, so there is not much I can do to help. Can someone please provide some steps to reproduce the issue or try and debug the issue further?

Hi Liam,
I have invited you to a private repo I have that has this issue.
On the local browser with ionic serve, the app looks white but on the phone (pixel 5, Android 12) it comes up with a dark theme I have not enabled (at least on purpose).

Let me know if you see similar on your end.
Thank you!

Local browser:
![image](https://user-images.githubusercontent.com/12150030/154970484-c7d975b3-f588-4e4a-bc03-dc1ccc7b523b.png)


Android 12 Pixel 5 phone:
![image](https://user-images.githubusercontent.com/12150030/154970561-ae8c650d-4733-4e2e-930d-2da7ba1b85ab.png)

**Comment by codexsysin** [comment] 2022-02-21 18:07
We just figured out. If you need help on this issue, kindly write to support@codexsys.com

**Comment by gusgonnet** [comment] 2022-02-21 18:59
> We just figured out. If you need help on this issue, kindly write to [support@codexsys.com](mailto:support@codexsys.com)

Would you be able to post the solution here for everyone's benefit? Thanks

**Comment by liamdebeasi** [comment] 2022-02-22 21:10
Hi everyone,

I am able to intermittently reproduce this behavior on my end. After investigating, this appears to be an behavior with the Android WebView, not Ionic.

Up until recently, the Android WebView did not have support for dark mode. Ionic ships with dark mode media queries, so when Android WebView started working with dark mode, your apps automatically switched to dark mode.

I do not know if this was an intentional change, but I do know this is not related to a bug in Ionic. I am going to close this, but feel free to file feedback on https://bugs.chromium.org/p/chromium/issues/list if you are running into bugs with this automatic dark mode switching. Thanks!

**Closed by liamdebeasi** 2022-02-22 21:10 UTC
Labels: triage

**Comment by scallacs** [comment] 2022-02-24 07:59
Indeed it's not a bug related to Ionic.
If you use cordova, installing this plugin fixed dark mode detection for me : https://github.com/timbru31/cordova-plugin-android-dark-mode-support.

**Comment by gusgonnet** [comment] 2022-02-24 16:19
_Indeed it's not a bug related to Ionic._
@scallacs salut Stephane,
I fail to see the rationale here. How does installing a plugin external to Ionic prove that this is not a bug in Ionic?
Shouldn't Ionic have behaved in a way so you did NOT need to install a plugin to fix this?
Anyhow the bug is closed, so not much to discuss.
Merci

**Comment by liamdebeasi** [comment] 2022-02-24 16:27
Ionic apps created via the CLI activate dark mode when the following CSS condition is met:

```css
@media (prefers-color-scheme: dark) {
```

Source: https://github.com/ionic-team/starters/blob/main/vue/base/src/theme/variables.css#L79

Ionic does not manage the on/off state of dark mode. The only thing the media query does is apply different styles when the state of dark mode is "on".

The problem is that the webview is always reporting that `prefers-color-scheme: dark` is `true`. As a result, the dark mode theme applies. As I mentioned before, I recommend submitting feedback on https://bugs.chromium.org/p/chromium/issues/list.

**Comment by liamdebeasi** [comment] 2022-02-24 16:32
The other thing I will note is if this is actively causing problems with your apps, you can temporarily remove dark mode support by disabling the `@media (prefers-color-scheme: dark) {` in your project.

**Comment by gusgonnet** [comment] 2022-02-24 17:07
> The problem is that the webview is always reporting that `prefers-color-scheme: dark` is `true`. As a result, the dark mode theme applies.

Thank you @liamdebeasi for taking the time to explain a bit more!
That was very helpful to me. Kudos.

**Comment by enriqueloz88** [comment] 2022-02-24 17:20
> _Indeed it's not a bug related to Ionic._ @scallacs salut Stephane, I fail to see the rationale here. How does installing a plugin external to Ionic prove that this is not a bug in Ionic? Shouldn't Ionic have behaved in a way so you did NOT need to install a plugin to fix this? Anyhow the bug is closed, so not much to discuss. Merci

Totally agree with this. If there is a plugin or something that fixes the error it should come by default in ionic, we shouldn't have to install anything to make things work. Especially since the dark mode is something that comes by default when you create an app in ionic through the cli, it is something that should be already working from the beginning. 

And if it is a temporary error of something external like the Android webView, it should not be us who report that error, but the Ionic team itself, because it is something that affects the framework a lot, it does not seem to me that this is a minor bug

**Comment by liamdebeasi** [comment] 2022-02-24 17:28
The issue appears to be fixed with WebView 99 (Android System WebView Beta on Google Play).

According to https://chromestatus.com/features/schedule, Chrome 99 will be released on March 1st.

**Comment by rabhiaziz** [comment] 2022-02-25 03:37
I have been pulling my hairs because the Dark mode, 
My application takes the dark mode automatically, I don't know why.

```
ionic version:  6.18.1
angular: 13.0.0,
mobile: Samsung s9
Android: 10
one UI version: 2.5
```

So i solve this by deleting all dark scss:
In variables.scss
`@media (prefers-color-scheme: dark){...}`
in index.html
` <meta name="color-scheme" content="light dark" />`

We hope that issue solved soon...

**Comment by Sibi4** [comment] 2022-02-28 13:01
@liamdebeasi, which feature in Chrome Release 99 solves our issue?

**Comment by liamdebeasi** [comment] 2022-02-28 13:47
The features listed on that page did not fix the issue. There is likely a bug fix commit somewhere in the codebase that fixed the issue.

I am able to reproduce the issue with WebView 98, and I cannot reproduce the issue with WebView 99 which is why I suggested the issue is fixed in that version. My inclusion of https://chromestatus.com/features/schedule was only to note that Chrome 99 is scheduled to release March 1st. WebView 99 should also be released around that time.

**Comment by distante** [comment] 2022-03-09 11:06
@liamdebeasi did you already tried it with the released version?

I have it updated and the problem stills happens and in my device is a little bit more extreme.

The app starts on Dark Mode, and it forces the dark mode on the phone. I can not change dark mode unless I run `adb shell settings put global low_power_sticky 0` and reboot the phone.

This is happening with a Poco F3 with MIUI 12.5.7 (Android 11).

My app has all the latest Capacitor updates until today and the `userAgent` reports `Chrome/99.0.4844.58`

**Comment by liamdebeasi** [comment] 2022-03-09 13:58
If you are still running into issues, I recommend reporting this issue to the Chromium team: https://bugs.chromium.org/p/chromium/issues/list

**Comment by distante** [comment] 2022-03-09 14:35
Will do!

**Comment by tetsuwanadam** [comment] 2022-03-17 23:50
Just updated WebView (non-beta) to 99.0.4844.73 and I'm still seeing this issue. How's it looking for everyone else?

**Comment by enriqueloz88** [comment] 2022-03-18 09:19
Yes, the problem is still happening for me also in the latest version of the webView. Does anyone have the link to the issue? I can not finde it here
https://bugs.chromium.org/p/chromium/issues/list

Let's hope it gets resolved soon because it's really annoying

**Comment by rluttikhuizen** [comment] 2022-03-19 09:29
Yes we are also still experiencing the problem after the Webview upgrade to 99.x. In the meantime we are changing our MainActivity.java based on the following posts to fix the issue:

https://github.com/ionic-team/capacitor/discussions/1978
https://forum.ionicframework.com/t/dark-mode-not-working-capacitor/185400

**Comment by jcesarmobile** [comment] 2022-04-07 13:59
Based on the last comment on the issue liam reported, looks like the WebView will now match the theme of the app.

Capacitor apps use a dark theme by default, so all Capacitor apps will have dark mode enabled by default.

If you want to force light mode you can set a light theme by changing this line in `res/values/styles.xml`

`<style name="AppTheme.NoActionBar" parent="Theme.AppCompat.NoActionBar">`
to
`<style name="AppTheme.NoActionBar" parent="Theme.AppCompat.Light.NoActionBar">`
or if you want it to automatically change based on the user setting you can use
`<style name="AppTheme.NoActionBar" parent="Theme.AppCompat.DayNight.NoActionBar">`

note that the theme change also affects other system dialogs such as web alert/prompt/confirm and the native equivalents from @capacitor/dialog plugin.

**Comment by findela** [comment] 2022-04-23 20:33
@jcesarmobile your solution - just works like a charm!

**Comment by mariomka** [comment] 2022-05-13 08:13
> <style name="AppTheme.NoActionBar" parent="Theme.AppCompat.DayNight.NoActionBar">

I think this should be the default value for a new Ionic project...
