### ISSUE TITLE
bug: angular lazy loaded components do not wait for hydration during tests

### ISSUE THREAD

**Issue by studioromeo** [ionic-team/ionic-framework#27204] opened 2023-04-13 22:57 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Hard to explain but essentially its not possible to trigger click handlers of ionic components from within tests. Note by click handlers I'm referring to this https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/segment/segment.tsx#L452-L477

This affects tests on `ion-segment` in particular as the segment isn't changed when a click event is dispatched to it. This ends up failing the tests that expect that segment to be changed.

Note worthy things:
- Adding a slight delay in the test before triggering a click event seems to help fix the issue except
- This only works if the browser running the test is in focus. If its in the background the test will fail
- Doesn't appear to be isolated to just `ion-segment`, is also present on `ion-button` so this could be all components.

### Expected Behavior

When dispatching a click event on an ion element the click handler from within the component is triggered in the same way that it would be if a real user clicked.

The test in the code repo url should pass

### Steps to Reproduce

1. Checkout code repo url and install
2. Run `npm test`
3. Note changes in test output when commenting out setTimeout

### Code Reproduction URL

https://github.com/studioromeo/ionic-click-handler

### Ionic Info

Ionic:

   Ionic CLI                     : 7.0.1
   Ionic Framework               : @ionic/angular 7.0.2
   @angular-devkit/build-angular : 15.2.6
   @angular-devkit/schematics    : 15.2.6
   @angular/cli                  : 15.2.6
   @ionic/angular-toolkit        : 9.0.0

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v18.15.0
   npm    : 9.5.0
   OS     : macOS Unknown

**Comment by liamdebeasi** [comment] 2023-04-17 18:18
Thanks for the report. I can reproduce this, but I need to take a closer look and see why this is happening. It looks like Ionic components are getting initialized after the test runs.

**Comment by liamdebeasi** [comment] 2023-07-17 17:30
This looks to be related to https://github.com/ionic-team/ionic-framework/issues/25646, so I am going to merge the two threads. As Sean noted in https://github.com/ionic-team/ionic-framework/issues/25646#issuecomment-1185747390, we are moving towards a non-lazy loaded solution for Ionic Angular which should help mitigate this issue. I will update the linked thread when I have more to share regarding that change.

**Closed by liamdebeasi** 2023-07-17 17:30 UTC
Labels: package: angular, type: bug
