### ISSUE TITLE
bug: Modern Syntax

### ISSUE THREAD

**Issue by godenji** [ionic-team/ionic-framework#27413] opened 2023-05-08 01:23 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

According to the [v7 blog post](https://ionic.io/blog/ionic-7-is-here) we should now adapt markup to  "modern syntax" for form elements.

For those of us that were fine with the supposed code bloat of having to type `ion-item` and `ion-label` blocks (which is IMO more readable/structured than the new syntax), the migration of existing code to the new syntax is somewhat annoying, but doable. However, eliminating these markup blocks is leading to some unexpected behavior.

For example, from the checkbox docs the following should place the label at the start of the line and the checkbox element at the end:
`<ion-checkbox justify="space-between">Space Between Label and Control</ion-checkbox>`  

but it doesn't; this despite the docs stating that:
> note
> ion-item is only used in the demos to emphasize how justify works. It is not needed in order for justify to function correctly.

Instead, both label and checkbox are left-aligned to the page.

When wrapping the checkbox element in `<ion-item>` then the expected behavior occurs.

Similarly, without wrapping form elements in `<ion-item>` then left/right padding is lost (i.e. elements are mashed up against screen edges). Are we supposed to mimic `ion-item` padding with custom form css?

AFAICT one very much does need  `<ion-item>` to get "legacy" spacing behavior..

Obviously for large code bases (fortunately not yet the case in my app)), without an automated rewrite tool this is quite the chore migrating from legacy to modern syntax. One could kick the can down the road until v8, but in the interim the large number of deprecation warnings in the console makes it difficult to debug one's code.

Sorry if this comes off as a  bit rant-ish (latest versions of Ionic and Angular are awesome overall, just wanted to put this out there to hopefully smooth out the migration path. 

### Expected Behavior

That the modern syntax aligns with expected behavior.

### Steps to Reproduce

Install Ionic + Angular

Add component with the following markup:
`<ion-checkbox justify="space-between">Space Between Label and Control</ion-checkbox>` 

View result in Chrome browser.

### Ionic Info

Ionic:

   Ionic CLI                     : 6.17.1 (/path/to/@ionic/cli)
   Ionic Framework               : not installed
   @angular-devkit/build-angular : 16.0.0
   @angular-devkit/schematics    : 16.0.0
   @angular/cli                  : 16.0.0
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.0.1
   @capacitor/android : not installed
   @capacitor/core    : 5.0.1
   @capacitor/ios     : not installed

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v18.12.1 (/usr/bin/node)
   npm    : 8.19.2
   OS     : Linux 6.1

**Comment by liamdebeasi** [comment] 2023-05-08 12:49
Thanks for the report. `ion-checkbox` has a width of `100%` when used inside of an `ion-item`. This is why `justify="space-between"` appears to work when that component is used inside of `ion-item`. When checkboxes are used outside of `ion-item`, we make minimal assumptions about how these checkboxes are laid out (since they can vary between apps). As a result, checkboxes only take up as much space as they need when used outside of `ion-item`. 

Here is an example of `justify="space-between"` when used outside of `ion-item`: https://codepen.io/liamdebeasi/pen/jOeZdWj

As for the padding, this is a similar reasoning. When the checkbox is used inside of an `ion-item` we can safely make assumptions about layout because checkboxes are supposed to be used in a certain way inside of `ion-item`. We cannot make those same assumptions when checkboxes are used outside of `ion-item`. When the checkboxes are used outside of `ion-item` it is up to the developer to provide the correct layout/spacing/alignment.

As for the migration itself, the changes here are really about labels on the form controls. You can continue to use form controls inside of `ion-item`, and this will continue to be a supported use case. In other words, if you are happy using checkboxes in a item/list, you can safely continue to do so. The main difference is the label should be passed to the form control (like you are doing in your example) instead of using a sibling `ion-label`.

**Comment by liamdebeasi** [comment] 2023-05-09 14:00
We'd be happy to review a PR if you have ideas for how we could improve the wording. Might be worth updating this section: https://ionicframework.com/docs/api/checkbox#migrating-from-legacy-checkbox-syntax (though we'll want to do this for input, textarea, select, radio, and range too)

I am going to close this since this is not a bug in Ionic, but let me know if you have questions.

**Closed by liamdebeasi** 2023-05-09 14:00 UTC
Labels: triage
