### ISSUE TITLE
bug: ion-select does not trigger ionChange event and fail to bind value under vue

### ISSUE THREAD

**Issue by villageFlower** [ionic-team/ionic-framework#23241] opened 2021-04-26 18:19 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

ion-select does not trigger ionChange event and fail to bind value

**Expected behavior:**

@ionChange should trigger onchange function & the value should bind with a variable

**Steps to reproduce:**

**Related code:**

```
I have tried
            <ion-select interface="popover" :value="selected" v-model="selected" @ionChange="selected = $event.target.value">
              <ion-select-option value="">Please Select</ion-select-option>
              <ion-select-option value="facilities">facilities</ion-select-option>
            </ion-select>
and
            <ion-select interface="popover" :value="selected" v-model="selected" @ionChange="onChange()">
              <ion-select-option value="">Please Select</ion-select-option>
              <ion-select-option value="facilities">facilities</ion-select-option>
            </ion-select>
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
Ionic:

   Ionic CLI       : 6.13.1 (C:\Users\simon\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/vue 5.6.5

Capacitor:

   Capacitor CLI   : 2.4.7
   @capacitor/core : 2.4.7

Utility:

   cordova-res                          : 0.15.3
   native-run (update available: 1.2.2) : 1.0.0

System:

   NodeJS : v14.6.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.6
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment] 2021-04-26 18:28
Thanks for the issue. Can you reproduce this issue in an Ionic starter app and provide a link to the repo?

**Comment by villageFlower** [comment] 2021-04-26 18:49
Hi, thanks for replying. here is the repo link:
https://github.com/villageFlower/issueApp.git

**Comment by villageFlower** [comment] 2021-04-26 18:49
> Thanks for the issue. Can you reproduce this issue in an Ionic starter app and provide a link to the repo?
Hi, thanks for replying. here is the repo link:
https://github.com/villageFlower/issueApp.git

**Comment by liamdebeasi** [comment] 2021-04-26 19:03
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The problem here is that you are not importing the `IonSelect` and `IonSelectOption` components prior to using them. While the components do still render, what you are getting is the underlying Web Component instance, not an actual Vue component. As a result, Vue features such as `v-model` will not work properly.

In your console log you should see this warning that is an indication that you need to import the component:

```
[Vue warn]: Failed to resolve component: ion-select 
  at <Home ref=Ref< undefined > key="/home" isInOutlet=true  ... > 
  at <IonRouterOutlet> 
  at <IonApp> 
  at <App>
```

See https://ionicframework.com/docs/vue/troubleshooting#failed-to-resolve-component for more information. We also provide info in that guide on how to do global component registration so you do not need to keep importing components.

**Closed by liamdebeasi** 2021-04-26 19:03 UTC
Labels: ionitron: needs reproduction
