### ISSUE TITLE
Page navigations are too slow in  ionic v4 ios14 beta 

### ISSUE THREAD

**Issue by prameela-reddy** [ionic-team/ionic-framework#21849] opened 2020-07-30 04:53 UTC
i have observed page transistions are too slow in ionic v4 on ios14beta.

ionic info:

Ionic:

   Ionic CLI                     : 5.2.8 (/Users/phani/.nvm/versions/node/v12.9.1/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.9.0
   @angular-devkit/build-angular : 0.803.2
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.3.5
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.1, (and 21 other plugins)

Utility:

   cordova-res : 0.8.1 (update available: 0.10.0)
   native-run  : not installed

System:

   NodeJS : v12.9.1 (/Users/phani/.nvm/versions/node/v12.9.1/bin/node)
   npm    : 6.10.2
   OS     : macOS Catalina

**Comment by HansKrywaa** [comment] 2020-07-30 08:34
See #21613

**Comment by liamdebeasi** [comment] 2020-07-30 13:26
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/21613.

**Closed by liamdebeasi** 2020-07-30 13:26 UTC
Labels: triage
