### ISSUE TITLE
bug: ion-split-pane menu has a black right border when app is in light mode and device is in dark mode

### ISSUE THREAD

**Issue by RZMiRaN** [ionic-team/ionic-framework#23877] opened 2021-09-05 17:15 UTC
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

![image](https://user-images.githubusercontent.com/11421315/132135355-90678261-616b-482e-8715-713c34d6392e.png)

### Expected Behavior

![image](https://user-images.githubusercontent.com/11421315/132135376-4f37e48f-9875-4c18-a0a8-67bdafd742d9.png)

### Steps to Reproduce

Create a blank project, create a basic ion-split pane like below

```
<ion-split-pane contentId="main" when="lg">
  <ion-menu contentId="main" menuId="main" side="start" type="overlay">
    <ion-header>
      <ion-toolbar color="primary">
        <ion-title>Navigation</ion-title>
      </ion-toolbar>
    </ion-header>
    <ion-content>
      <ion-list>
        <ion-menu-toggle autoHide="false">
          <ion-item routerLink="/home/departments" routerDirection="root" routerLinkActive="active-link">
            <ion-label>Departments</ion-label>
          </ion-item>
          <ion-item routerLink="/home/classes" routerDirection="root" routerLinkActive="active-link">
            <ion-label>Classes</ion-label>
          </ion-item>
          <ion-item routerLink="/home/logs" routerDirection="root" routerLinkActive="active-link">
            <ion-label>Logs</ion-label>
          </ion-item>
        </ion-menu-toggle>
      </ion-list>
    </ion-content>
  </ion-menu>
  <ion-router-outlet id="main"></ion-router-outlet>
</ion-split-pane>
```

### Ionic Info

Ionic:

   Ionic CLI                     : 6.17.0 (C:\Users\Miran\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.7.0
   @angular-devkit/build-angular : 12.1.4
   @angular-devkit/schematics    : 12.1.4
   @angular/cli                  : 12.1.4
   @ionic/angular-toolkit        : 4.0.0

Capacitor:

   Capacitor CLI      : 3.2.2
   @capacitor/android : not installed
   @capacitor/core    : 3.2.2
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.4.0

System:

   NodeJS : v14.17.6 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.15
   OS     : Windows 10

### Additional Information

That line turns black after like half a second from the page load

Edit: I just noticed the following:
- When my computer is in dark mode and I change the prefers-color-scheme to light, the app is indeed light and the problem exists.
- When my computer is in light mode and I change the prefers-color-scheme to light, the app turns dark.
- When my computer is in light mode and I change the prefers-color-scheme to dark, the app turns light and the problem disappears.

**Comment by liamdebeasi** [comment] 2021-09-07 14:55
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The black border you are seeing is the `body` background color since the split pane border has opacity. We add a `color-scheme` meta tag to your `index.html` file that causes parts of your app such as the body and scrollbar to automatically adjust for dark mode. To fix this, you will need to remove the `color-scheme` meta tag from `src/index.html`.

**Closed by liamdebeasi** 2021-09-07 14:55 UTC
Labels: triage
