### ISSUE TITLE
bug: @ionic/vue  infiniteScroll can not work well after run refresher component

### ISSUE THREAD

**Issue by AlwaysLoveme** [ionic-team/ionic-framework#22458] opened 2020-11-09 09:17 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

use ionic width vue latest version: there is both refreher component with infiniteScroll component, when page first came in, infinteScorll worked well , but run refresher component after infiniteScroll, infiniteScroll can not triggered any more
**Expected behavior:**

infiniteScroll component can work well after run refresher component
**Steps to reproduce:**

**Related code:**
```
import axios from '@/utils/axios';

/**
 * 通用分页加载数据类
 * **/
class CommonList {
    // 本次请求的地址
    url: string = '';
    // 当前页
    page: number = 1;
    // 基于分页的参数集合
    params: object = {};
    // 请求方式，默认post
    method: string = 'post';
    // 是否有数据
    nodata: boolean = false;
    // 请求结果集合
    httpResult: never[] = [];

    /**
     * @param url: http request url
     * @param params: http request data
     * @param loadmore: default is not, refresh
     * @param method: http request methods, default is "POST"
     * **/
    async getListData(url: string, params: object = {}, loadmore: boolean = false, method: string = 'post') {
        this.url = url;
        this.params = params;
        this.method = method;
        const refresher = this.getInfiniteAndRefreshElement('ion-refresher');
        const infiniteScroll = this.getInfiniteAndRefreshElement('ion-infinite-scroll');
        if (!loadmore) {
            this.page = 1;
        }
        const param = {
            ...params,
            limit: 20,
            page: this.page,
        };
        const {data, status} = await axios[method](url, param);
        await this.finishInfiniteAndRefresh(refresher);
        await this.finishInfiniteAndRefresh(infiniteScroll, false);
        if (status) {
            const list: never[] = data instanceof Array ? data : data.list;
            loadmore ? this.httpResult.push(...list) : this.httpResult = list;
            if (list.length === 0) {
                await this.finishInfiniteAndRefresh(infiniteScroll, true);
                this.nodata = this.page === 1;
                return data;
            }
            this.page++;
        }
        return data;
    }

    getInfiniteAndRefreshElement(tagName: string) {
        const elements: HTMLElement | any = document.querySelectorAll(tagName);
        return elements;
    }

    async finishInfiniteAndRefresh(elements: any, disabled: boolean = false) {
        elements.forEach((element: HTMLElement | any) => {
            element.complete();
            element.disabled = disabled;
        });
    }
}

export default CommonList
```
```
<ion-content>
    <template v-if="refresh">
      <ion-refresher mode="md" slot="fixed" pull-min="100" pull-max="600" @ionRefresh="$emit('refresh')">
        <ion-refresher-content></ion-refresher-content>
      </ion-refresher>
    </template>

    <slot></slot>

    <template v-if="infinite">
      <ion-infinite-scroll mode="md" threshold="100px" @ionInfinite="$emit('infinite')">
        <ion-infinite-scroll-content></ion-infinite-scroll-content>
      </ion-infinite-scroll>
    </template>
  </ion-content>
```

A sample application via GitHub: https://github.com/AlwaysLoveme/ionic-vue3

**Other information:**
**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.12.1 (/Users/zhuxian/.nvm/versions/node/v12.19.0/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 5.4.2

Capacitor:

   Capacitor CLI   : 2.4.2
   @capacitor/core : 2.4.2

Utility:

   cordova-res (update available: 0.15.2) : 0.15.1
   native-run                             : not installed

System:

   NodeJS : v12.19.0 (/Users/zhuxian/.nvm/versions/node/v12.19.0/bin/node)
   npm    : 6.14.8
   OS     : macOS Catalina

```

**Comment by liamdebeasi** [comment] 2020-11-09 15:49
Thanks for the issue. Can you please provide some steps to reproduce the issue in your app? I am not quite sure how to navigate your application.

**Comment by AlwaysLoveme** [comment] 2020-11-10 02:15
> Thanks for the issue. Can you please provide some steps to reproduce the issue in your app? I am not quite sure how to navigate your application.
OK，here is the simple code: https://github.com/AlwaysLoveme/ionic-vue-infiniteScroll-demo
1. run app in brower 
2. scroll home page into bottom to trigger infiniteScroll component, set the Attributes disabled is true
3. scroll home page into top to trigger refresher component, and reset infiniteScroll disabled is false
4. scroll home page into bottom, then  page did not  trigger infiniteScroll component any more, At this moment，the Attributes disabled is false,

and here is another problem, i set the global mode style  is "ios", and i set the refresher component mode is "md", the refresher style  is still "ios" style:

in main.ts
```
const app = createApp(App)
  .use(IonicVue, {
    mode: 'ios'
  })
  .use(router);
```
```
<ion-refresher slot="fixed" mode="md" pull-min="200">
        <ion-refresher-content></ion-refresher-content>
      </ion-refresher>
```

**Comment by liamdebeasi** [comment] 2020-11-10 17:01
Thanks for the clarification.

The problem here is that between disabling/enabling the infinite scroll and the height you assigned to `#container`, you are not giving enough of a threshold for the infinite scroll component to properly fire.  When you disable the infinite scroll component, this hides the component which alters the height of the content. The `100px` threshold in your app would be fine if you did not alter the height of the content. In this situation, it is better to use a relative threshold such as `15%`. Using that resolved the issue on my end.

In terms of the mode issue, this looks like a bug. I am not sure if this is a bug in Stencil or in Ionic Framework, but I will look into it and open another issue.

**Closed by liamdebeasi** 2020-11-10 17:01 UTC
Labels: triage
