### ISSUE TITLE
bug: IonButton onClick not working when inside IonInput div slot label

### ISSUE THREAD

**Issue by si458** [ionic-team/ionic-framework#28714] opened 2023-12-16 23:32 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

if you put an IonButton with an onClick inside the new `<div slot='label>` on an IonInput inside an IonItem,
the onClick event is not being called?
but also the button isnt being rendered as a IonButton? (like showing the mouse over or CLICK effect like a normal IonButton)

### Expected Behavior

for the onclick event to be called when i click the ionbutton?

### Steps to Reproduce

```
<IonItem>
<IonInput
  className="ion-text-right"
  placeholder="Scan/Enter A Barcode"
  required
  onIonInput={(e) => handleInputChange('itemBarcode', e.detail.value!)}
  ref={itemBarcode}
>
<div slot='label'>
Barcode <IonText color={'danger'}>*</IonText>
<IonButton className='ion-margin-start' onClick={generateBarcode}><Icon path={mdiBarcode} size={1} /></IonButton>
</div>
</IonInput>
</IonItem>
```
```
 const generateBarcode = () => {
    console.log('generateBarcode');
    const newBarcode = chance.string({ length: 13, numeric: true });
    setInputValues((prevValues) => ({
      ...prevValues,
      itemBarcode: newBarcode,
    }));
    if (itemBarcode.current) itemBarcode.current.value = newBarcode;
  }
```

### Ionic Info

PS C:\Users\ASUS\Documents\Developer\MySumUpTill> ionic info
[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package.json'

       Require stack:
       - C:\Users\ASUS\AppData\Roaming\nvm\v20.10.0\node_modules\@ionic\cli\lib\project\index.js
       - C:\Users\ASUS\AppData\Roaming\nvm\v20.10.0\node_modules\@ionic\cli\lib\index.js
       - C:\Users\ASUS\AppData\Roaming\nvm\v20.10.0\node_modules\@ionic\cli\index.js
       - C:\Users\ASUS\AppData\Roaming\nvm\v20.10.0\node_modules\@ionic\cli\bin\ionic
[WARN] Error loading @capacitor/android package.json: Error: Cannot find module '@capacitor/android/package.json'

       Require stack:
       - C:\Users\ASUS\AppData\Roaming\nvm\v20.10.0\node_modules\@ionic\cli\lib\project\index.js
       - C:\Users\ASUS\AppData\Roaming\nvm\v20.10.0\node_modules\@ionic\cli\lib\index.js
       - C:\Users\ASUS\AppData\Roaming\nvm\v20.10.0\node_modules\@ionic\cli\index.js
       - C:\Users\ASUS\AppData\Roaming\nvm\v20.10.0\node_modules\@ionic\cli\bin\ionic

Ionic:

   Ionic CLI       : 7.1.5 (C:\Users\ASUS\AppData\Roaming\nvm\v20.10.0\node_modules\@ionic\cli)
   Ionic Framework : @ionic/react 7.6.1

Capacitor:

   Capacitor CLI      : 5.6.0
   @capacitor/android : not installed
   @capacitor/core    : 5.6.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 2.0.0

System:

   NodeJS : v20.10.0 (C:\Program Files\nodejs\node.exe)
   npm    : 10.2.4
   OS     : Windows 10

**Comment by liamdebeasi** [comment] 2023-12-18 13:51
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. We add `pointer-events: none` for accessibility reasons. When a screen reader is enabled, double tapping the label content should always click the label and therefore focus the input. We found that on some older version of iOS/Android that this would not happen unless `pointer-events` we removed from the child elements.

For your use case, you likely want `slot="start"` or `slot="end"` instead. This will render the button next to the input but won't interfere with the label. Here's an example: https://codepen.io/liamdebeasi/pen/qBgeYBo

**Closed by liamdebeasi** 2023-12-18 13:51 UTC
Labels: triage

**Comment by si458** [comment] 2023-12-18 13:55
Hi,
this doesnt help my issue, as i WANT the button to be located NEXT to the label, but NOT infront of it or at the end?
are you also saying that ANY button thats put inside the label will physically not work?
can i not override the pointer-events some how?

**Comment by liamdebeasi** [comment] 2023-12-18 14:01
You can certainly override the `pointer-events` property by modifying the `.label-text-wrapper` element. However, placing the button inside of the label slot will likely negatively impact the user experience for people who utilize screen readers, so I don't recommend doing this.

If you always want the button on the starting side of the label text then you can use the `start` slot in `ion-item` instead. I updated the demo at https://codepen.io/liamdebeasi/pen/qBgeYBo to show this.

**Comment by si458** [comment] 2023-12-18 14:05
thank you @liamdebeasi im having one of those weeks!
im not worried about the 'screen readers/accessability features' as this is a custom app for myself built in electron!
