### ISSUE TITLE
bug: scroll assist not positioning correctly

### ISSUE THREAD

**Issue by 7freaks-otte** [ionic-team/ionic-framework#21688] opened 2020-07-07 07:34 UTC
# Bug Report

**Ionic version:**
[x] **5.x** (especially 5.2.3)

**Current behavior:**
While scroll-assist was recently improved to position inputs more precise it also introduces a problem when the keyboard height is corrected shortly after the first "keyboardWillShow" event.

- In my case I tap into a normal input field => ion-content scrolls to the correct position respecting keyboard height.

- Then I tap on a password field => ion-content scrolls to the correct position first, but 30ms later iOS detects that it could offer me to choose a saved password and adds a password bar above the keyboard that now covers the input field.

**Expected behavior:**
I would expext the scroll-assist to wait for around 100ms if a second "keyboardWillShow" event will correct the keyboard height because of a input suggestion bar.

<img width="573" alt="Screenshot 2020-07-06 at 11 13 38" src="https://user-images.githubusercontent.com/11407404/86731855-334f0000-c030-11ea-9957-caeccf8c0a7c.png">

Alternatively the input field could be positioned 50px to the top which would cover most cases and make the next field that needs to be filled out visible as well.

**Steps to reproduce:**
![Hnet-image](https://user-images.githubusercontent.com/11407404/86737507-a22e5800-c034-11ea-9dd6-28797c0cabb3.gif)
(Note: the black area below "Password" actually covering the complete password input including the caret is the password keyboard with suggestion bar which is excluded from screen recording by iOS)
<img width="411" alt="Screen Shot 2019-06-21 at 1 39 10 PM" src="https://user-images.githubusercontent.com/11407404/86737854-e1f53f80-c034-11ea-89e4-1be1fc5dde46.png">

**Comment by 7freaks-otte** [comment] 2020-07-07 13:54
There's no need for code. Any form with a normal `ion-input` and one with `type="password"` will do as long as you test it on an iOS device in a Capacitor container.

```
<p>enough</p><p>space</p><p>to</p><p>move</p><p>inputs</p><p>below</p><p>keyboard</p>

<ion-list>
    <ion-item>
        <ion-label position="stacked">Email</ion-label>
        <ion-input type="email"></ion-input>
    </ion-item>
    <ion-item>
        <ion-label position="stacked">Password</ion-label>
        <ion-input type="password"></ion-input>
    </ion-item>
</ion-list>
```

- Tapping in the email input will scroll to the right position.
- Tapping in the password input will not scroll enough as the first `keyboardWillShow` will give a keyboard height of 291px, then iOS decides to show you a bar to select saved passwords and triggers a second `keyboardWillShow` event with a keyboard height of 336px.

These extra 45px added milliseconds later as the password suggestion bar is added, are enough to cover the input field after it was scrolled respecting the first 291px.

Please just have a look at the screenshots provided above (unfortunately iOS does not record the password keyboard probably because of privacy concerns and you can only see the black area)

**Comment by 7freaks-otte** [comment] 2020-07-07 14:03
@liamdebeasi Remember when you added the "keyboardWillShow" and "resize" listeners with a 300ms fallback to scroll-assist.ts detaching the listeners after whatever happens first?

iOS adding the password suggestion bar results in a second "keyboardWillShow" event with a different keyboard height but scroll-assist's `jsSetFocus` will never know and `scrollContent` is not called again to update the scroll position.

**Comment by liamdebeasi** [comment] 2020-07-07 14:05
We need a repo we can clone to reproduce the issue. Code snippets are typically not enough to reproduce the issue.

**Comment by 7freaks-otte** [comment] 2020-07-08 07:41
What about the conference app? 😉

```
ionic start conference conference --type=angular --capacitor
cd conference
```

Update ionic and add capacitor (as the --capacitor flag does not seem to work with the conference app)
```
npm install @ionic/angular@5.2.3 @capacitor/cli @capacitor/core
```

Make sure that there is enough space above the login form and build the app
```
echo ".login-logo { min-height: 400px \!important; }" >> src/global.scss
ionic build
```

Init capacitor, sync and open Xcode
```
npx cap init
npx cap add ios
npx cap open ios
```

Open the conference app on an iOS device
- Navigate to Account/Login in the left menu
- Tap the "Username" input field => scrolling works
- Close the keyboard by tapping anywhere else
- Tap the "Password" input field => scrolling does not work

You will be experiencing 1 of 2 possible effects:
- Either the content will not scroll at all because of the capacitor keyboard resize method and not enough space below the password field so the content just cannot scroll before the webview is resized
- Or, which is my initial problem, the content will scroll the password field just above the keyboard, but will then cover the password input with the "select saved password proposal bar" which is added to the keyboard milliseconds after its first "keyboardWillShow" event. But the second "keyboardWillShow" event with the corrected keyboard height is ignored by scroll-assist

**Comment by liamdebeasi** [comment] 2020-07-08 13:48
Thanks. It looks like the webview is only resized after the "Passwords" bar appears, so Ionic Framework should wait for that as well. I will make a fix.

**Comment by liamdebeasi** [comment] 2020-07-10 13:41
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/21703, and a fix will be available in an upcoming release of Ionic Framework.

**Closed by liamdebeasi** 2020-07-10 13:41 UTC
Labels: package: core, type: bug
