### ISSUE TITLE
bug: IonToggle & IonRange issue in IonMenu

### ISSUE THREAD

**Issue by kutoman** [ionic-team/ionic-framework#22989] opened 2021-03-01 12:31 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

`IonToggle` and `IonRange` are not interactable in an `IonMenu`. I've tested this via ionic serve with various browsers.

**Expected behavior:**

that those controls are interactable

**Steps to reproduce:**

putting those components in an `IonMenu`

**Related code:**

```ts
import React, { MutableRefObject, useEffect, useRef } from 'react';
import { IonContent, IonHeader, IonIcon, IonItem, IonLabel, IonList, IonMenu, IonNote, IonPage, IonRange, IonTitle, IonToggle, IonToolbar } from '@ionic/react';
import { glassesOutline, settingsOutline } from 'ionicons/icons';
import './Home.css';

const MyMenu = React.forwardRef<HTMLIonMenuElement, {}>((props, ref) => {

  return (
    <IonMenu ref={ref} contentId="menu-content" side="end" type="overlay" >
      <IonHeader>
        <IonToolbar color="primary">
          <IonIcon icon={settingsOutline} slot="secondary" />
          <IonTitle class="ion-text-capitalize">Menu</IonTitle>
        </IonToolbar>
      </IonHeader>
      <IonContent id="menu-content">
        <IonList>
          <IonItem>
            <IonLabel class="ion-text-capitalize">foo</IonLabel>
            <IonToggle color="success" slot="end" checked={true}  />
          </IonItem>
          <IonItem>
            <IonRange min={0} max={100} value={50}>
              <IonIcon icon={ glassesOutline } size="small" slot="start" />
              <IonIcon icon={ glassesOutline } size="medium" slot="end" />
            </IonRange>
          </IonItem>
        </IonList>
      </IonContent>
  </IonMenu>
)})


const Home: React.FC = () => {

  const menuRef: MutableRefObject<HTMLIonMenuElement|null> = useRef(null)

  useEffect(() => {setTimeout(() => menuRef.current!!.setOpen(true), 1000)})

  return (
    <IonPage>
      <MyMenu ref={menuRef}/>
      <IonHeader>
        <IonToolbar>
          <IonTitle>Buggy</IonTitle>
        </IonToolbar>
      </IonHeader>
      <IonContent fullscreen onClick={async () => {
        const m = menuRef.current!!
        if(! await m.isOpen()) m.setOpen(true)
      }}>
        <IonNote class="ion-text-center">tap to open menu</IonNote>
      </IonContent>
    </IonPage>
  );
};

export default Home;

```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.12.3 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.5.4

Capacitor:

   Capacitor CLI   : 2.4.6
   @capacitor/core : 2.4.6

Utility:

   cordova-res (update available: 0.15.3) : 0.14.0
   native-run (update available: 1.3.0)   : 0.3.0

System:

   NodeJS : v12.16.1 (/usr/local/bin/node)
   npm    : 6.14.8
   OS     : macOS Catalina
```

**Comment by liamdebeasi** [comment] 2021-03-01 13:48
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The problem is that the side menu needs to be used as a sibling of `IonRouterOutlet`, not as a child of it. When opening a menu, we set `pointer-events: none` on the content inside of `IonRouterOutlet` so you cannot interact with it, but since your menu is inside of `IonRouterOutlet`, the `pointer-events: none` is applying to the content inside of your menu.

**Closed by liamdebeasi** 2021-03-01 13:48 UTC
Labels: triage

**Comment by kutoman** [comment] 2021-03-01 15:31
@liamdebeasi but why are buttons (`IonButton`) working in the same scenario?

**Comment by kutoman** [comment] 2021-03-02 12:15
sorry but even when I place the `IonMenu` outside of `IonRouterOutlet` it still doesn't work for me (either as a sibling to `IonRouterOutlet` or `IonTabs` or even `IonReactRouter`). In addition to this, when I consider the fact that however `IonButton`s work it seems to me that this is indeed a bug.

**Comment by BerkeAras** [comment] 2021-03-02 12:19
@kutoman Could you provide a demonstration of a UseCase? Maybe there would be a workaround or it could fixed with a PR.

**Comment by kutoman** [comment] 2021-03-02 12:28
@BerkeAras sure. I've put the menu as sibling to `IonRouterOutlet` as @liamdebeasi stated. Here the button is clickable but `IonToggle` and `IonRange` are not however :

**App.tsx**
```ts
import { Redirect, Route } from 'react-router-dom';
import { IonApp, IonRouterOutlet } from '@ionic/react';
import { IonReactRouter } from '@ionic/react-router';
import Home, { MyMenu } from './pages/Home';

/* Core CSS required for Ionic components to work properly */
import '@ionic/react/css/core.css';

/* Basic CSS for apps built with Ionic */
import '@ionic/react/css/normalize.css';
import '@ionic/react/css/structure.css';
import '@ionic/react/css/typography.css';

/* Optional CSS utils that can be commented out */
import '@ionic/react/css/padding.css';
import '@ionic/react/css/float-elements.css';
import '@ionic/react/css/text-alignment.css';
import '@ionic/react/css/text-transformation.css';
import '@ionic/react/css/flex-utils.css';
import '@ionic/react/css/display.css';

/* Theme variables */
import './theme/variables.css';

const App: React.FC = () => (
  <IonApp>
    <IonReactRouter>
      <MyMenu/>
      <IonRouterOutlet>
        <Route exact path="/home">
          <Home />
        </Route>
        <Route exact path="/">
          <Redirect to="/home" />
        </Route>
      </IonRouterOutlet>
    </IonReactRouter>
  </IonApp>
);

export default App;

```

**Home.tsx**
```tsx
import React, {  } from 'react';
import { IonButton, IonContent, IonHeader, IonIcon, IonItem, IonLabel, IonList, IonMenu, IonMenuButton, IonNote, IonPage, IonRange, IonTitle, IonToggle, IonToolbar } from '@ionic/react';
import { glassesOutline, settingsOutline } from 'ionicons/icons';
import './Home.css';

export const MyMenu = React.forwardRef<HTMLIonMenuElement, {}>((props, ref) => {

  return (
    <IonMenu ref={ref} contentId="menu-content" side="end" type="overlay" >
      <IonHeader>
        <IonToolbar color="primary">
          <IonIcon icon={settingsOutline} slot="secondary" />
          <IonTitle class="ion-text-capitalize">Menu</IonTitle>
        </IonToolbar>
      </IonHeader>
      <IonContent id="menu-content">
        <IonList>
          <IonItem>
            <IonLabel class="ion-text-capitalize">foo</IonLabel>
            <IonToggle color="success" slot="end" checked={true}  />
          </IonItem>
          <IonItem>
            <IonRange min={0} max={100} value={50}>
              <IonIcon icon={ glassesOutline } size="small" slot="start" />
              <IonIcon icon={ glassesOutline } size="medium" slot="end" />
            </IonRange>
          </IonItem>
        </IonList>
        <IonItem>
          <IonButton>but I'm working</IonButton>
        </IonItem>
      </IonContent>
  </IonMenu>
)})


const Home: React.FC = () => {

  return (
    <IonPage>
      <IonHeader>
        <IonToolbar>
          <IonTitle>Buggy</IonTitle>
          <IonMenuButton slot="end"/>
        </IonToolbar>
      </IonHeader>
      <IonContent fullscreen>
        <IonNote class="ion-text-center">tap to open menu</IonNote>
      </IonContent>
    </IonPage>
  );
};

export default Home;

```

**Comment by liamdebeasi** [comment] 2021-03-02 14:22
The problem here is that you are selecting the wrong `IonContent` for your `contentId`. The `contentId` refers to your main page's content, not the content inside of your menu. This is how we determine which content is inactive.

Try setting `id="menu-content"` on `IonRouterOutlet` instead.

**Comment by kutoman** [comment] 2021-03-03 10:03
@liamdebeasi yes that's it! thanks! Then it's even working inside of `IonRouterOutlet` (thus I don't need to put the menu as a sibling to `IonRouterOutlet`).
Actually I made the false decision regarding `contentId` by reading the ionic docs. Imho the description there is a bit vague, I would suggest to make it more clear.

currently this is stated there:
**contentId**: The content's id the menu should use.
_but which content is meant exactly? the one which the menu contains or the one from the IonPage?_

**Comment by liamdebeasi** [comment] 2021-03-03 14:08
Yeah that's a really vague description 😅 . I will update the docs so it's more clear.
