### ISSUE TITLE
bug: ionic serve crash if run on a machine with ipv6 link-local address

### ISSUE THREAD

**Issue by touilleMan** [ionic-team/ionic-framework#24916] opened 2022-03-10 11:27 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

ionic serve is crashing if the machine it is running on has a ipv6 address starting with `fe80:` (which are link-local address, https://www.cisco.com/c/en/us/support/docs/ip/ip-version-6-ipv6/113328-ipv6-lla.html).

This weird link-local address is present if running on a virtual machine (tested with vmware with both NAT and Bridged network adapter).

### Expected Behavior

ionic serve should not crash ;)

### Steps to Reproduce

On a ubuntu 20.04 virtual machine running on vmware.

With a fresh ionic project created with `ionic start client_ionic_2 blank --type=vue --capacitor`:

```
$ ionic serve --verbose
  ionic:lib Terminal info: { ci: false, shell: '/usr/bin/fish', tty: true, windows: false } +0ms
  ionic:lib CLI global options: { _: [ 'serve' ], help: null, h: null, verbose: true, quiet: null, interactive: true, color: true, confirm: null, json: null, project: null, '--': [] } +3ms
  ionic:lib:project Project type from config: @ionic/vue (vue) +0ms
  ionic:lib:project Project details: { context: 'app', type: 'vue', errors: [], configPath: '/home/miguel/projects/parsec-webfront-poc2/fullstack/client_ionic_2/ionic.config.json' } +1ms
  ionic Context: { binPath: '/home/miguel/.local/lib/node_modules/@ionic/cli/bin/ionic', libPath: '/home/miguel/.local/lib/node_modules/@ionic/cli', execPath: '/home/miguel/projects/parsec-webfront-poc2/fullstack/client_ionic_2', version: '6.18.2' } +0ms
  ionic:lib:serve serve options: {
  ionic:lib:serve   '--': [],
  ionic:lib:serve   host: 'localhost',
  ionic:lib:serve   browser: undefined,
  ionic:lib:serve   browserOption: undefined,
  ionic:lib:serve   engine: 'browser',
  ionic:lib:serve   externalAddressRequired: false,
  ionic:lib:serve   lab: false,
  ionic:lib:serve   labHost: 'localhost',
  ionic:lib:serve   labPort: 8200,
  ionic:lib:serve   livereload: true,
  ionic:lib:serve   open: true,
  ionic:lib:serve   platform: undefined,
  ionic:lib:serve   port: 8100,
  ionic:lib:serve   proxy: true,
  ionic:lib:serve   project: undefined,
  ionic:lib:serve   publicHost: undefined,
  ionic:lib:serve   verbose: true
  ionic:lib:serve } +0ms
  ionic:lib:telemetry Sending telemetry for command: 'ionic serve' [ '--verbose', '--interactive', '--color' ] +0ms
  ionic:lib:hooks Looking for ionic:serve:before npm script. +0ms
  ionic:utils-network checking for open port on 0.0.0.0:8100 +0ms
  ionic:utils-network checking for open port on 127.0.0.1:8100 +7ms
  ionic:utils-network checking for open port on ::1:8100 +1ms
  ionic:utils-network checking for open port on 192.168.1.23:8100 +3ms
  ionic:utils-network checking for open port on 2a01:cb15:81f1:2600:13b1:eee0:1cf7:93b1:8100 +0ms
  ionic:utils-network checking for open port on 2a01:cb15:81f1:2600:5b61:a459:51a4:9315:8100 +1ms
  ionic:utils-network checking for open port on fe80::7fe5:a1ec:5c44:db49:8100 +0ms
  ionic:utils-network error while checking fe80::7fe5:a1ec:5c44:db49:8100: Error: listen EINVAL: invalid argument fe80::7fe5:a1ec:5c44:db49:8100     at Server.setupListenHandle [as _listen2] (node:net:1313:21)     at listenInCluster (node:net:1378:12)     at doListen (node:net:1516:7)     at processTicksAndRejections (node:internal/process/task_queues:84:21) { code: 'EINVAL', errno: -22, syscall: 'listen', address: 'fe80::7fe5:a1ec:5c44:db49', port: 8100 } +1ms
  ionic:lib:serve Looking for ionic:serve npm script. +32ms
> vue-cli-service serve
  ionic:lib:serve received unexpected close for vue-cli-service (code: 1) +515ms

[ERROR] vue-cli-service has unexpectedly closed (exit code 1).
        
        The Ionic CLI will exit. Please check any output above for error details.
  ionic:utils-process onBeforeExit handler: 'process.exit' received +0ms
  ionic:utils-process onBeforeExit handler: running 1 functions +0ms
  ionic:utils-process processExit: exiting (exit code: 1) +21ms
```

### Ionic Info

Ionic:

   Ionic CLI       : 6.18.2 (/home/miguel/.local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 6.0.11

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v16.14.0 (/snap/node/5953/bin/node)
   npm    : not installed
   OS     : Linux 5.13

**Comment by liamdebeasi** [comment] 2022-03-10 13:53
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The error is coming from `vue-cli-service`, not the Ionic CLI:

```
ionic:lib:serve received unexpected close for vue-cli-service (code: 1) +515ms

[ERROR] vue-cli-service has unexpectedly closed (exit code 1).
```

I recommend posting on the [Ionic Forum](https://forum.ionicframework.com/) for assistance with this issue. If you feel this is a bug in the Vue CLI, please file an issue on [the Vue CLI GitHub repo](https://github.com/vuejs/vue-cli).

**Closed by liamdebeasi** 2022-03-10 13:53 UTC
Labels: triage

**Comment by touilleMan** [comment] 2022-03-10 16:03
Thanks for the quick answer @liamdebeasi !

You are right, I was mistaken by the `ionic:utils-network error [...]` log line, but this is not the cause of the crash (ionic cannot work with fe80: address and handle the issue correctly by ignoring this ip address and carrying on 😃 )

**Comment by liamdebeasi** [comment] 2022-03-10 16:39
If you feel this is a bug in the Ionic CLI, I recommend filing an issue on the [Ionic CLI GitHub Repo](https://github.com/ionic-team/ionic-cli).
