### ISSUE TITLE
bug: small ion-fab-button with a ion-fab-list has a wrong click event area

### ISSUE THREAD

**Issue by Yohandah** [ionic-team/ionic-framework#21772] opened 2020-07-17 08:58 UTC
# Bug Report

**Ionic version:**

[x] **5.x**

**Current behavior:**

If a `ion-fab` has a `ion-fab-button size="small"` with a `ion-fab-list`, the area of the `ion-fab` will trigger the ion-fab-list even if the `ion-fab-button` isn't pressed. Which makes the click event trigger without actually pressing the `ion-fab-button`. I encountered this issue while binding a `(click)` event to the `ion-fab-button`

**Expected behavior:**

The `ion-fab-list` should be triggered only when the `ion-fab-button` is pressed, and not the `ion-fab` area itself.
Or the small `ion-fab-button` area should take the whole ion-fab area (so it's triggered when pressing the `ion-fab` area).

**Related code:**
- Press the red area of the first fab (normal size) : the `ion-fab-button` is triggered (ripple effect, click event, pointer is changing, ...), the `ion-fab-list` as well
- Press the red area of the second fab (small size) : the `ion-fab-list` is triggered but not the `ion-fab-button` (no ripple effect, no click event, pointer doesn't change, ...)

https://stackblitz.com/edit/ionic-v5-bug-fab-size

**Comment by liamdebeasi** [comment] 2020-07-17 13:33
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. We add margin to the inner `ion-fab-button` when it is small to keep it aligned with the list. You can remove the `margin` if you would like, but you will need to re-align the inner buttons as well.

**Comment by Yohandah** [comment] 2020-07-17 13:49
@liamdebeasi Okay thanks .. I still don't get why clicking into the margin of this opens the ion-fab-list but do not trigger the cursor, ripple effect, and click event of the ion-fab-button then .. I thought it was wrongly binded to the ion-fab area ?

**Comment by liamdebeasi** [comment] 2020-07-17 13:59
Oh I didn't even notice that. The ripple effect only fires when you click the `ion-fab-button`. It looks like `ion-fab` listens for a click event on the host, which is why clicking the button margin area opens the list, but does not trigger the ripple effect.

The ripple effect not firing is probably a bug.

**Comment by Yohandah** [comment] 2020-07-17 14:05
@liamdebeasi Yeah that's my issue! Because I need to catch when the `ion-fab-list` opens or close and this little area doesn't allow me to track this since the `ion-fab-button` doesn't catch the (click) event.

> The ripple effect not firing is probably a bug.

There's also the cursor that's not into "click" (pointer) mode

If I have time I'll try to look into it and work on a bugfix but I'm not sure I'm up to the task haha ^^"

**Comment by liamdebeasi** [comment] 2020-07-17 14:11
What you described makes sense. Thanks for following up, otherwise I would have missed that 😄 .

**Comment by Akash280899** [comment] 2022-05-04 07:55
When clicking on ion-fab , the ripple effect not working. is the issue been solved?

**Comment by liamdebeasi** [comment] 2022-06-06 17:47
Can everyone try the following dev build and let me know if it resolves the issue?

```
6.1.9-dev.11654537362.165e92c3
```

Example: `npm install @ionic/angular@6.1.9-dev.11654537362.165e92c3`

**Comment by liamdebeasi** [comment] 2022-06-08 17:28
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/25413, and a fix will be available in an upcoming release of Ionic Framework. Please feel free to continue testing the dev build. This fix will also be available in the next nightly build of Ionic.

**Closed** 2022-06-08 17:28 UTC
Labels: help wanted, package: core, type: bug
