### ISSUE TITLE
bug: ion-segment not properly initialized when in ion-modal

### ISSUE THREAD

**Issue by rusekr** [ionic-team/ionic-framework#28858] opened 2024-01-19 16:41 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Resume: ion-segment initial value not properly displayed in ion-modal. 

Here is simple testcase ionic-angular app https://github.com/rusekr/finstorm/tree/master with one modal and three tabs.

Runs with `npm run start`. On second tab this is fab with modal. On modal two segments and two radios for one property `transactionType`. Radios initialized correctly, segments not.

### Expected Behavior

ion-segment selects by model segment on modal opened.

### Steps to Reproduce

1. Runs code above with `npm run start`
2. Go to second tab.
3. Click fab with plus sign to open modal.
4. See correct behaviour of ion-radio buttons and incorrect behavior (all segments deselected) of ion-segment.

### Code Reproduction URL

https://github.com/rusekr/finstorm/tree/master

### Ionic Info

Ionic:

   Ionic CLI                     : 7.1.5 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.6.5
   @angular-devkit/build-angular : 17.1.0
   @angular-devkit/schematics    : 17.1.0
   @angular/cli                  : 17.1.0
   @ionic/angular-toolkit        : 11.0.0

Capacitor:

   Capacitor CLI      : 5.6.0
   @capacitor/android : 5.6.0
   @capacitor/core    : 5.6.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 2.0.0

System:

   NodeJS : v20.10.0 (/usr/bin/node20)
   npm    : 10.2.3
   OS     : Linux 6.6

### Additional Information

Tried [value] property instead or alongside ngModel with no luck.

**Comment by liamdebeasi** [comment] 2024-01-19 17:57
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/28816. I merged a fix for this a couple days ago, so the fix will be in an upcoming version of Ionic.

**Closed by liamdebeasi** 2024-01-19 17:57 UTC
Labels: triage

**Comment by rusekr** [comment] 2024-01-19 20:29
Thanks for the info! Added fix as monkey patch for now before new release via patch-package and it works great!
