### ISSUE TITLE
Back button defaultBack animating forward in tabs

### ISSUE THREAD

**Issue by TiagoDamascena** [ionic-team/ionic-framework#18567] opened 2019-06-18 12:40 UTC
# Bug Report

**Ionic version:**
[x] **4.5.0**

**Current behavior:**
The back button is animating forward when it doen't have a history (defaultBack) and is called from an ion-tab sub page.

**Expected behavior:**
The animation goes back like in other pages out of ion-tabs.

**Steps to reproduce:**
Create a tabs app and add a ion-back-button on a tab subpage with a defaultBack to the tab parent page. Open the app directly on the tab subpage (to keep history empty) and click on the back button.

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.0.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.5.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 8 other plugins)

Utility:

   cordova-res : 0.3.0
   native-run  : 0.2.5
```

**Comment by liamdebeasi** [comment] 2023-10-13 17:40
Thanks for the report. This appears to be the same issue as https://github.com/ionic-team/ionic-framework/issues/17053. While this was a bug in older versions of Ionic 4, it appears to have been resolved in newer versions of Ionic. I was unable to reproduce this behavior in Ionic 7.5.0. If you are still running into a problem with navigation, please open a new issue and include a reproduction case.

**Closed by liamdebeasi** 2023-10-13 17:40 UTC
Labels: package: angular, type: bug
