### ISSUE TITLE
bug: ion-page render problem

### ISSUE THREAD

**Issue by outdoorfish** [ionic-team/ionic-framework#24377] opened 2021-12-13 03:18 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

1. if route change faster than router transition, ion-page will not render
2. some situations, ion-page render incorrect

### Expected Behavior

ion-page render correct

### Steps to Reproduce

1. change route faster than router transition

https://user-images.githubusercontent.com/92348687/145746694-cf9cacd0-392e-4c92-aa66-0915055fe4ac.mov

2. push route, go back, change nested route(replace)

https://user-images.githubusercontent.com/92348687/145746712-a2734e54-8ddd-46fc-8811-ece3655538af.mov

### Code Reproduction URL

https://github.com/outdoorfish/ionic-ion-page-issue/tree/master/ionic-ion-page-issue

**Comment by liamdebeasi** [comment] 2021-12-13 16:23
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/24226.

**Closed by liamdebeasi** 2021-12-13 16:23 UTC
Labels: triage
