### ISSUE TITLE
bug: Stencil components have incorrect event types

### ISSUE THREAD

**Issue by mikaelkaron** [ionic-team/ionic-framework#24952] opened 2022-03-17 00:12 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

signature of [`onIonInfinite`](https://ionicframework.com/docs/api/infinite-scroll#events) is not compatible with [`InfiniteScrollCustomEvent`​](https://ionicframework.com/docs/api/infinite-scroll#infinitescrollcustomevent).

### Expected Behavior

I'm expecting this to work:

```jsx
<ion-infinite-scroll onIonInfinite={ev => setTimeout(() => ev.target.complete(), 2000)}>
  <ion-infinite-scroll-content loadingSpinner="dots"></ion-infinite-scroll-content>
</ion-infinite-scroll>
```

### Steps to Reproduce

try compiling expected code, will fail as `typeof ev` is `CustomEvent<void>`which is not assignable to `InfiniteScrollCustomEvent`

### Ionic Info

```console
Ionic:

   Ionic CLI : 5.4.16

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v16.13.1
   npm    : 8.1.2
   OS     : Linux 5.10
```

### Additional Information

I saw a [discussion on the forums](https://forum.ionicframework.com/t/how-can-i-use-infinite-scroll-with-typescript/213900/3) that indicated this should work in v6 so I hope I'm not doing it wrong.

**Comment by sean-perkins** [comment] 2022-03-17 03:22
Closing as a duplicate of #24245.

We are still investigating a solution to this in the generated wrappers. In the interim, you can manually set the types to avoid the errors or type cast as any:


```ts
onIonInfinite={(ev: any) => setTimeout(() => ev.target.complete(), 2000)}
```

**Comment by sean-perkins** [comment] 2022-03-17 16:35
Apologies, I believe I have closed this issue premature. The syntax you are using is JSX, which would not coincide with the existing Angular issue. 

I'll re-open and look into it.

**Comment by mikaelkaron** [comment] 2022-03-17 21:22
The solution in ionic-team/stencil#3286 looks really nice! Looking forward to using this once implemented in stencil/here.

PS: I see you've added a title to this issue (I forgot that - thanks) but FYI I use "pure" stencil in my project - so it's probably "any framework that uses TS" that is affected.

**Comment by sean-perkins** [comment] 2022-03-21 18:36
@mikaelkaron update on the issue, I ended up closing that PR in favor of an internal change to the Stencil compiler to correct this issue at scale. 

https://github.com/ionic-team/stencil/pull/3296

In that change, all Stencil custom events will inherit the custom HTML element type for the event target. It also generates a new interface for each web component, that you can export to your implementers, to have better typings. 

For Ionic, what this will look like in theory is:
```ts
import { ComponentEvents } from '@ionic/core';

onIonInfinite(ev: ComponentEvents.IonInfiniteScrollEventDetail<void>) {}
```

This would replace all our custom maintained interfaces like: `IonInfiniteScrollEventDetail`. It also accepts a generic, which you can use to provide the specific event detail you are listening for. An example of this for something like `ion-datetime`, would be:

```ts
import { ComponentEvents, DatetimeChangeEventDetail } from '@ionic/core';

onIonChange(event: ComponentEvents.IonDatetimeEventDetail<DatetimeChangeEventDetail>) {}
```

These types are only necessary when your bindings are disconnected from the reference. For JSX, the underlying type would be inherited:
```tsx
<IonInfinite onIonInfinite={ev => {
  // ev type is ComponentEvents.IonInfiniteScrollEventDetail<void>
  // ev.target type is HTMLIonInfiniteScrollElement
  // ev.detail type is void
}} />
```

Since these types extend `CustomEvent`, anywhere you don't need the `target` type to be the HTML element type, you can still use `CustomEvent<T>`.

**Closed** 2023-08-16 15:03 UTC
Labels: type: bug, stencil
