### ISSUE TITLE
bug: ion-range is cutted of left and right if its placed in ion-item

### ISSUE THREAD

**Issue by SvenBudak** [ionic-team/ionic-framework#28108] opened 2023-09-01 15:34 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

https://ionicframework.com/docs/api/item#item-inputs See the last item and slide the range to the end. You will see that its cutted off:
![image](https://github.com/ionic-team/ionic-framework/assets/4930169/b5c0d783-28b8-45eb-aa0e-c90bd7b6edf8)

here how it looks in a app with backgroub color:
![image](https://github.com/ionic-team/ionic-framework/assets/4930169/d8c178c5-9f7a-4431-861c-90c80ff4efe4)

### Expected Behavior

should not cutted off

### Steps to Reproduce

open the doc and scroll down to ion-range

### Code Reproduction URL

https://ionicframework.com/docs/api/item#item-inputs

### Ionic Info

latest

**Comment by mapsandapps** [comment] 2023-09-01 15:39
Hi, it sounds like this is a duplicate of #27199. I'm going to close this in favor of that one. You can follow that issue for updates.

**Closed by mapsandapps** 2023-09-01 15:39 UTC
Labels: triage
