### ISSUE TITLE
bug: Navigating between instances of the same route with different parameters does not show udpated content

### ISSUE THREAD

**Issue by beneverard** [ionic-team/ionic-framework#22931] opened 2021-02-16 14:37 UTC
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
Navigating between instances of the same route with different parameters does not create a new version of the component, and thus does not show the correct data for the route.

**Expected behavior:**
When navigating between the same route with different parameter, a new component should be spawned with its own state, allowing navigation back to the previous and separate instance.

**Steps to reproduce:**
1. Go to [bug test example](https://compassionate-noether-a4b908.netlify.app/)
2. Go to the 1st message
3. Click blue "Go To Message 5" button
4. URL updates, but the component key/content does not change

(Note, I didn't setup Netlify redirects, so visit the root URL and navigate from within the app)

**Related code:**
This is the `ion-button` code, the only change made from the Vue sample:

    <ion-button router-link="/message/5" routerDirection="forward" :detail="false" class="list-item">Go To Message 5</ion-button>

**Other information:**
This [bug report](https://github.com/ionic-team/ionic-framework/issues/20543) says how components stay mounted in order to allow the state to be kept the same when navigating back through the history, but in this case the component is staying mounted and retains the original message data (index 0), instead of the new message data (index 5).

https://github.com/ionic-team/ionic-framework/issues/20543

This makes sense but causes a problem in this situation.

**Ionic info:**

```
$ ionic info

Ionic:

   Ionic CLI       : 6.12.4 (/Users/beneverard/.config/yarn/global/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 5.5.4

Capacitor:

   Capacitor CLI   : 2.4.6
   @capacitor/core : 2.4.6

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v15.7.0 (/usr/local/bin/node)
   npm    : 7.4.3
   OS     : macOS Catalina
```

**Comment by liamdebeasi** [comment] 2021-02-16 15:05
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/22662.

**Closed by liamdebeasi** 2021-02-16 15:05 UTC

**Comment by beneverard** [comment] 2021-02-16 15:09
Hi @liamdebeasi, thanks, I did see this after I just posted. I just want to check, in your bug report you say "The new page content simply appears.", whereas what I'm reporting here is that the new content doesn't display at all.

Just want to make sure you're aware, they very well may be covering the same issue.

**Comment by liamdebeasi** [comment] 2021-02-16 15:13
Thanks for clarifying! Yeah I think the two issues are related.

**Comment by beneverard** [comment] 2021-02-16 15:14
Thanks again Liam :-)
