### ISSUE TITLE
bug: the time picker does not scroll to the right time values after opening the time picker component

### ISSUE THREAD

**Issue by escoumf** [ionic-team/ionic-framework#24876] opened 2022-03-04 13:31 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

When opening the time picker the time picker does not scroll to the given hour and minute.

### Expected Behavior

As an user I expect the given hour and minute on the time picker.

### Steps to Reproduce

1. Clone [the datetime migration example](https://github.com/ionic-team/datetime-migration-samples/)
2. Change directory to `./datetime-migration-samples/angular`
3. Checkout `next` branch
4. Call `npm install`
5. Update `@ionic/angular` from `6.0.0-rc.3` to `6.0.10` with `npm update @ionic/angular@6.0.10`
6. Call `ionic serve`
7. Go to the browser with the page of `datetime-migration-samples` project
8. Click on the `Birthday` item. A modal date-time picker dialog will open
9. Click on the time field. A time picker will open with wrong hour and minute values, which is a bug.

### Ionic Info

[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package'
       
       Require stack:
       - /usr/local/lib/node_modules/@ionic/cli/lib/project/index.js
       - /usr/local/lib/node_modules/@ionic/cli/lib/index.js
       - /usr/local/lib/node_modules/@ionic/cli/index.js
       - /usr/local/lib/node_modules/@ionic/cli/bin/ionic
[WARN] Error loading @capacitor/android package.json: Error: Cannot find module '@capacitor/android/package'
       
       Require stack:
       - /usr/local/lib/node_modules/@ionic/cli/lib/project/index.js
       - /usr/local/lib/node_modules/@ionic/cli/lib/index.js
       - /usr/local/lib/node_modules/@ionic/cli/index.js
       - /usr/local/lib/node_modules/@ionic/cli/bin/ionic

Ionic:

   Ionic CLI                     : 6.18.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.10
   @angular-devkit/build-angular : 12.1.4
   @angular-devkit/schematics    : 12.1.4
   @angular/cli                  : 12.1.4
   @ionic/angular-toolkit        : 4.0.0

Capacitor:

   Capacitor CLI      : 3.3.2
   @capacitor/android : not installed
   @capacitor/core    : 3.3.2
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v14.15.5 (/usr/local/bin/node)
   npm    : 7.24.2
   OS     : Linux 5.4

**Comment by escoumf** [comment] 2022-03-04 13:59
The field `isColumnVisible` in class `PickerColumnInternal` implemented in `picker-column-internal.tsx` has to be set to `true` in `visibleCallback` before calling `scrollActiveItemIntoView`. This will fix this issue.

**Comment by liamdebeasi** [comment] 2022-03-04 14:18
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/24878.

**Closed by liamdebeasi** 2022-03-04 14:18 UTC
Labels: triage
